Information Modeller: main.cpp File Reference
main.cpp File Reference
Functions
string elementType_str (ElementType elementType)
void printElement (DeviceElement *element)
void printSubelements (vector< shared_ptr< DeviceElement >> elements)
void printDevice (Device *device)
unique_ptr< Device > buildDeviceFromAFunction ()
int main ()
Function Documentation
buildDeviceFromAFunction()
unique_ptr<Device> buildDeviceFromAFunction ()
Definition at line 68 of file main.cpp.
References Model_Factory::DeviceBuilder::addDeviceElement(), Model_Factory::DeviceBuilder::addDeviceElementGroup(), Model_Factory::DeviceBuilder::getDevice(), and Information_Model::Readonly.
Referenced by main().
elementType_str()
string elementType_str (ElementType elementType)
Definition at line 9 of file main.cpp.
References Information_Model::Function, Information_Model::Group, Information_Model::Observable, Information_Model::Readonly, Information_Model::Undefined, and Information_Model::Writable.
Referenced by printElement().
main()
int main ()
Definition at line 83 of file main.cpp.
References Model_Factory::DeviceBuilder::addDeviceElement(), Model_Factory::DeviceBuilder::addDeviceElementGroup(), buildDeviceFromAFunction(), Information_Model::Function, Model_Factory::DeviceBuilder::getDevice(), Information_Model::Group, Information_Model::Observable, printDevice(), Information_Model::Readonly, GroupElementDoesNotExistException::what(), and Information_Model::Writable.
printDevice()
void printDevice (Device * device)
Definition at line 56 of file main.cpp.
References Information_Model::Device::getDeviceElementGroup(), Information_Model::NamedElement::getElementDescription(), Information_Model::NamedElement::getElementName(), Information_Model::NamedElement::getElementRefId(), Information_Model::DeviceElementGroup::getSubelements(), and printSubelements().
Referenced by main().
printElement()
void printElement (DeviceElement * element)
Definition at line 24 of file main.cpp.
References elementType_str(), Information_Model::NamedElement::getElementDescription(), Information_Model::NamedElement::getElementName(), Information_Model::NamedElement::getElementRefId(), and Information_Model::DeviceElement::getElementType().
Referenced by printSubelements().
printSubelements()
void printSubelements (vector< shared_ptr< DeviceElement >> elements)
Definition at line 33 of file main.cpp.
References Information_Model::DeviceElementGroup::getSubelements(), Information_Model::Group, and printElement().
Referenced by printDevice().