Project Template: Opc.Ua.DataTypeSchemaHeader Class Reference
Opc.Ua.DataTypeSchemaHeader Class Reference
Public Member Functions
DataTypeSchemaHeader ()
The default constructor.
virtual void Encode (IEncoder encoder)
virtual void Decode (IDecoder decoder)
virtual bool IsEqual (IEncodeable encodeable)
virtual object Clone ()
new object MemberwiseClone ()
Properties
StringCollection Namespaces [get, set]
StructureDescriptionCollection StructureDataTypes [get, set]
EnumDescriptionCollection EnumDataTypes [get, set]
SimpleTypeDescriptionCollection SimpleDataTypes [get, set]
virtual ExpandedNodeId TypeId [get]
virtual ExpandedNodeId BinaryEncodingId [get]
virtual ExpandedNodeId XmlEncodingId [get]
Detailed Description
<exclude>
Definition at line 3785 of file Opc.Ua.DataTypes.cs.
Constructor & Destructor Documentation
DataTypeSchemaHeader()
Opc.Ua.DataTypeSchemaHeader.DataTypeSchemaHeader () inline
The default constructor.
Definition at line 3791 of file Opc.Ua.DataTypes.cs.
Member Function Documentation
Clone()
virtual object Opc.Ua.DataTypeSchemaHeader.Clone () inline virtual
Reimplemented in Opc.Ua.DataSetMetaDataType, and Opc.Ua.UABinaryFileDataType.
Definition at line 3977 of file Opc.Ua.DataTypes.cs.
Decode()
virtual void Opc.Ua.DataTypeSchemaHeader.Decode (IDecoder decoder) inline virtual
Reimplemented in Opc.Ua.DataSetMetaDataType, and Opc.Ua.UABinaryFileDataType.
Definition at line 3940 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
Encode()
virtual void Opc.Ua.DataTypeSchemaHeader.Encode (IEncoder encoder) inline virtual
Reimplemented in Opc.Ua.DataSetMetaDataType, and Opc.Ua.UABinaryFileDataType.
Definition at line 3927 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
IsEqual()
virtual bool Opc.Ua.DataTypeSchemaHeader.IsEqual (IEncodeable encodeable) inline virtual
Reimplemented in Opc.Ua.DataSetMetaDataType, and Opc.Ua.UABinaryFileDataType.
Definition at line 3953 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Object.
MemberwiseClone()
new object Opc.Ua.DataTypeSchemaHeader.MemberwiseClone () inline
Definition at line 3984 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.StructureDescriptionCollection.Clone(), Opc.Ua.EnumDescriptionCollection.Clone(), Opc.Ua.SimpleTypeDescriptionCollection.Clone(), Opc.Ua.DataTypeSchemaHeader.MemberwiseClone(), and Opc.Ua.Namespaces.OpcUaXsd.
Referenced by Opc.Ua.DataTypeSchemaHeader.MemberwiseClone().
Property Documentation
BinaryEncodingId
virtual ExpandedNodeId Opc.Ua.DataTypeSchemaHeader.BinaryEncodingId get
Definition at line 3916 of file Opc.Ua.DataTypes.cs.
EnumDataTypes
EnumDescriptionCollection Opc.Ua.DataTypeSchemaHeader.EnumDataTypes get set
Definition at line 3867 of file Opc.Ua.DataTypes.cs.
Namespaces
StringCollection Opc.Ua.DataTypeSchemaHeader.Namespaces get set
Definition at line 3823 of file Opc.Ua.DataTypes.cs.
SimpleDataTypes
SimpleTypeDescriptionCollection Opc.Ua.DataTypeSchemaHeader.SimpleDataTypes get set
Definition at line 3889 of file Opc.Ua.DataTypes.cs.
StructureDataTypes
StructureDescriptionCollection Opc.Ua.DataTypeSchemaHeader.StructureDataTypes get set
Definition at line 3845 of file Opc.Ua.DataTypes.cs.
TypeId
virtual ExpandedNodeId Opc.Ua.DataTypeSchemaHeader.TypeId get
Definition at line 3910 of file Opc.Ua.DataTypes.cs.
XmlEncodingId
virtual ExpandedNodeId Opc.Ua.DataTypeSchemaHeader.XmlEncodingId get
Definition at line 3922 of file Opc.Ua.DataTypes.cs.
The documentation for this class was generated from the following file:
Opc.Ua.DataTypes.cs