Project Template: opcua_clientapi.h File Reference
opcua_clientapi.h File Reference
Functions
OPCUA_BEGIN_EXTERN_C OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_FindServers (OpcUa_Channel hChannel, const OpcUa_RequestHeader *pRequestHeader, const OpcUa_String *pEndpointUrl, OpcUa_Int32 nNoOfLocaleIds, const OpcUa_String *pLocaleIds, OpcUa_Int32 nNoOfServerUris, const OpcUa_String *pServerUris, OpcUa_ResponseHeader *pResponseHeader, OpcUa_Int32 *pNoOfServers, OpcUa_ApplicationDescription **pServers)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginFindServers (OpcUa_Channel hChannel, const OpcUa_RequestHeader *pRequestHeader, const OpcUa_String *pEndpointUrl, OpcUa_Int32 nNoOfLocaleIds, const OpcUa_String *pLocaleIds, OpcUa_Int32 nNoOfServerUris, const OpcUa_String *pServerUris, OpcUa_Channel_PfnRequestComplete *pCallback, OpcUa_Void *pCallbackData)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_FindServersOnNetwork (OpcUa_Channel hChannel, const OpcUa_RequestHeader *pRequestHeader, OpcUa_UInt32 nStartingRecordId, OpcUa_UInt32 nMaxRecordsToReturn, OpcUa_Int32 nNoOfServerCapabilityFilter, const OpcUa_String *pServerCapabilityFilter, OpcUa_ResponseHeader *pResponseHeader, OpcUa_DateTime *pLastCounterResetTime, OpcUa_Int32 *pNoOfServers, OpcUa_ServerOnNetwork **pServers)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginFindServersOnNetwork (OpcUa_Channel hChannel, const OpcUa_RequestHeader *pRequestHeader, OpcUa_UInt32 nStartingRecordId, OpcUa_UInt32 nMaxRecordsToReturn, OpcUa_Int32 nNoOfServerCapabilityFilter, const OpcUa_String *pServerCapabilityFilter, OpcUa_Channel_PfnRequestComplete *pCallback, OpcUa_Void *pCallbackData)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_GetEndpoints (OpcUa_Channel hChannel, const OpcUa_RequestHeader *pRequestHeader, const OpcUa_String *pEndpointUrl, OpcUa_Int32 nNoOfLocaleIds, const OpcUa_String *pLocaleIds, OpcUa_Int32 nNoOfProfileUris, const OpcUa_String *pProfileUris, OpcUa_ResponseHeader *pResponseHeader, OpcUa_Int32 *pNoOfEndpoints, OpcUa_EndpointDescription **pEndpoints)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginGetEndpoints (OpcUa_Channel hChannel, const OpcUa_RequestHeader *pRequestHeader, const OpcUa_String *pEndpointUrl, OpcUa_Int32 nNoOfLocaleIds, const OpcUa_String *pLocaleIds, OpcUa_Int32 nNoOfProfileUris, const OpcUa_String *pProfileUris, OpcUa_Channel_PfnRequestComplete *pCallback, OpcUa_Void *pCallbackData)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_RegisterServer (OpcUa_Channel hChannel, const OpcUa_RequestHeader *pRequestHeader, const OpcUa_RegisteredServer *pServer, OpcUa_ResponseHeader *pResponseHeader)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginRegisterServer (OpcUa_Channel hChannel, const OpcUa_RequestHeader *pRequestHeader, const OpcUa_RegisteredServer *pServer, OpcUa_Channel_PfnRequestComplete *pCallback, OpcUa_Void *pCallbackData)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_RegisterServer2 (OpcUa_Channel hChannel, const OpcUa_RequestHeader *pRequestHeader, const OpcUa_RegisteredServer *pServer, OpcUa_Int32 nNoOfDiscoveryConfiguration, const OpcUa_ExtensionObject *pDiscoveryConfiguration, OpcUa_ResponseHeader *pResponseHeader, OpcUa_Int32 *pNoOfConfigurationResults, OpcUa_StatusCode **pConfigurationResults, OpcUa_Int32 *pNoOfDiagnosticInfos, OpcUa_DiagnosticInfo **pDiagnosticInfos)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginRegisterServer2 (OpcUa_Channel hChannel, const OpcUa_RequestHeader *pRequestHeader, const OpcUa_RegisteredServer *pServer, OpcUa_Int32 nNoOfDiscoveryConfiguration, const OpcUa_ExtensionObject *pDiscoveryConfiguration, OpcUa_Channel_PfnRequestComplete *pCallback, OpcUa_Void *pCallbackData)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_CreateSession (OpcUa_Channel hChannel, const OpcUa_RequestHeader *pRequestHeader, const OpcUa_ApplicationDescription *pClientDescription, const OpcUa_String *pServerUri, const OpcUa_String *pEndpointUrl, const OpcUa_String *pSessionName, const OpcUa_ByteString *pClientNonce, const OpcUa_ByteString *pClientCertificate, OpcUa_Double nRequestedSessionTimeout, OpcUa_UInt32 nMaxResponseMessageSize, OpcUa_ResponseHeader *pResponseHeader, OpcUa_NodeId *pSessionId, OpcUa_NodeId *pAuthenticationToken, OpcUa_Double *pRevisedSessionTimeout, OpcUa_ByteString *pServerNonce, OpcUa_ByteString *pServerCertificate, OpcUa_Int32 *pNoOfServerEndpoints, OpcUa_EndpointDescription **pServerEndpoints, OpcUa_Int32 *pNoOfServerSoftwareCertificates, OpcUa_SignedSoftwareCertificate **pServerSoftwareCertificates, OpcUa_SignatureData *pServerSignature, OpcUa_UInt32 *pMaxRequestMessageSize)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginCreateSession (OpcUa_Channel hChannel, const OpcUa_RequestHeader *pRequestHeader, const OpcUa_ApplicationDescription *pClientDescription, const OpcUa_String *pServerUri, const OpcUa_String *pEndpointUrl, const OpcUa_String *pSessionName, const OpcUa_ByteString *pClientNonce, const OpcUa_ByteString *pClientCertificate, OpcUa_Double nRequestedSessionTimeout, OpcUa_UInt32 nMaxResponseMessageSize, OpcUa_Channel_PfnRequestComplete *pCallback, OpcUa_Void *pCallbackData)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_ActivateSession (OpcUa_Channel hChannel, const OpcUa_RequestHeader *pRequestHeader, const OpcUa_SignatureData *pClientSignature, OpcUa_Int32 nNoOfClientSoftwareCertificates, const OpcUa_SignedSoftwareCertificate *pClientSoftwareCertificates, OpcUa_Int32 nNoOfLocaleIds, const OpcUa_String *pLocaleIds, const OpcUa_ExtensionObject *pUserIdentityToken, const OpcUa_SignatureData *pUserTokenSignature, OpcUa_ResponseHeader *pResponseHeader, OpcUa_ByteString *pServerNonce, OpcUa_Int32 *pNoOfResults, OpcUa_StatusCode **pResults, OpcUa_Int32 *pNoOfDiagnosticInfos, OpcUa_DiagnosticInfo **pDiagnosticInfos)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginActivateSession (OpcUa_Channel hChannel, const OpcUa_RequestHeader *pRequestHeader, const OpcUa_SignatureData *pClientSignature, OpcUa_Int32 nNoOfClientSoftwareCertificates, const OpcUa_SignedSoftwareCertificate *pClientSoftwareCertificates, OpcUa_Int32 nNoOfLocaleIds, const OpcUa_String *pLocaleIds, const OpcUa_ExtensionObject *pUserIdentityToken, const OpcUa_SignatureData *pUserTokenSignature, OpcUa_Channel_PfnRequestComplete *pCallback, OpcUa_Void *pCallbackData)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_CloseSession (OpcUa_Channel hChannel, const OpcUa_RequestHeader *pRequestHeader, OpcUa_Boolean bDeleteSubscriptions, OpcUa_ResponseHeader *pResponseHeader)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginCloseSession (OpcUa_Channel hChannel, const OpcUa_RequestHeader *pRequestHeader, OpcUa_Boolean bDeleteSubscriptions, OpcUa_Channel_PfnRequestComplete *pCallback, OpcUa_Void *pCallbackData)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_Cancel (OpcUa_Channel hChannel, const OpcUa_RequestHeader *pRequestHeader, OpcUa_UInt32 nRequestHandle, OpcUa_ResponseHeader *pResponseHeader, OpcUa_UInt32 *pCancelCount)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginCancel (OpcUa_Channel hChannel, const OpcUa_RequestHeader *pRequestHeader, OpcUa_UInt32 nRequestHandle, OpcUa_Channel_PfnRequestComplete *pCallback, OpcUa_Void *pCallbackData)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_AddNodes (OpcUa_Channel hChannel, const OpcUa_RequestHeader *pRequestHeader, OpcUa_Int32 nNoOfNodesToAdd, const OpcUa_AddNodesItem *pNodesToAdd, OpcUa_ResponseHeader *pResponseHeader, OpcUa_Int32 *pNoOfResults, OpcUa_AddNodesResult **pResults, OpcUa_Int32 *pNoOfDiagnosticInfos, OpcUa_DiagnosticInfo **pDiagnosticInfos)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginAddNodes (OpcUa_Channel hChannel, const OpcUa_RequestHeader *pRequestHeader, OpcUa_Int32 nNoOfNodesToAdd, const OpcUa_AddNodesItem *pNodesToAdd, OpcUa_Channel_PfnRequestComplete *pCallback, OpcUa_Void *pCallbackData)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_AddReferences (OpcUa_Channel hChannel, const OpcUa_RequestHeader *pRequestHeader, OpcUa_Int32 nNoOfReferencesToAdd, const OpcUa_AddReferencesItem *pReferencesToAdd, OpcUa_ResponseHeader *pResponseHeader, OpcUa_Int32 *pNoOfResults, OpcUa_StatusCode **pResults, OpcUa_Int32 *pNoOfDiagnosticInfos, OpcUa_DiagnosticInfo **pDiagnosticInfos)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginAddReferences (OpcUa_Channel hChannel, const OpcUa_RequestHeader *pRequestHeader, OpcUa_Int32 nNoOfReferencesToAdd, const OpcUa_AddReferencesItem *pReferencesToAdd, OpcUa_Channel_PfnRequestComplete *pCallback, OpcUa_Void *pCallbackData)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_DeleteNodes (OpcUa_Channel hChannel, const OpcUa_RequestHeader *pRequestHeader, OpcUa_Int32 nNoOfNodesToDelete, const OpcUa_DeleteNodesItem *pNodesToDelete, OpcUa_ResponseHeader *pResponseHeader, OpcUa_Int32 *pNoOfResults, OpcUa_StatusCode **pResults, OpcUa_Int32 *pNoOfDiagnosticInfos, OpcUa_DiagnosticInfo **pDiagnosticInfos)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginDeleteNodes (OpcUa_Channel hChannel, const OpcUa_RequestHeader *pRequestHeader, OpcUa_Int32 nNoOfNodesToDelete, const OpcUa_DeleteNodesItem *pNodesToDelete, OpcUa_Channel_PfnRequestComplete *pCallback, OpcUa_Void *pCallbackData)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_DeleteReferences (OpcUa_Channel hChannel, const OpcUa_RequestHeader *pRequestHeader, OpcUa_Int32 nNoOfReferencesToDelete, const OpcUa_DeleteReferencesItem *pReferencesToDelete, OpcUa_ResponseHeader *pResponseHeader, OpcUa_Int32 *pNoOfResults, OpcUa_StatusCode **pResults, OpcUa_Int32 *pNoOfDiagnosticInfos, OpcUa_DiagnosticInfo **pDiagnosticInfos)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginDeleteReferences (OpcUa_Channel hChannel, const OpcUa_RequestHeader *pRequestHeader, OpcUa_Int32 nNoOfReferencesToDelete, const OpcUa_DeleteReferencesItem *pReferencesToDelete, OpcUa_Channel_PfnRequestComplete *pCallback, OpcUa_Void *pCallbackData)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_Browse (OpcUa_Channel hChannel, const OpcUa_RequestHeader *pRequestHeader, const OpcUa_ViewDescription *pView, OpcUa_UInt32 nRequestedMaxReferencesPerNode, OpcUa_Int32 nNoOfNodesToBrowse, const OpcUa_BrowseDescription *pNodesToBrowse, OpcUa_ResponseHeader *pResponseHeader, OpcUa_Int32 *pNoOfResults, OpcUa_BrowseResult **pResults, OpcUa_Int32 *pNoOfDiagnosticInfos, OpcUa_DiagnosticInfo **pDiagnosticInfos)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginBrowse (OpcUa_Channel hChannel, const OpcUa_RequestHeader *pRequestHeader, const OpcUa_ViewDescription *pView, OpcUa_UInt32 nRequestedMaxReferencesPerNode, OpcUa_Int32 nNoOfNodesToBrowse, const OpcUa_BrowseDescription *pNodesToBrowse, OpcUa_Channel_PfnRequestComplete *pCallback, OpcUa_Void *pCallbackData)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BrowseNext (OpcUa_Channel hChannel, const OpcUa_RequestHeader *pRequestHeader, OpcUa_Boolean bReleaseContinuationPoints, OpcUa_Int32 nNoOfContinuationPoints, const OpcUa_ByteString *pContinuationPoints, OpcUa_ResponseHeader *pResponseHeader, OpcUa_Int32 *pNoOfResults, OpcUa_BrowseResult **pResults, OpcUa_Int32 *pNoOfDiagnosticInfos, OpcUa_DiagnosticInfo **pDiagnosticInfos)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginBrowseNext (OpcUa_Channel hChannel, const OpcUa_RequestHeader *pRequestHeader, OpcUa_Boolean bReleaseContinuationPoints, OpcUa_Int32 nNoOfContinuationPoints, const OpcUa_ByteString *pContinuationPoints, OpcUa_Channel_PfnRequestComplete *pCallback, OpcUa_Void *pCallbackData)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_TranslateBrowsePathsToNodeIds (OpcUa_Channel hChannel, const OpcUa_RequestHeader *pRequestHeader, OpcUa_Int32 nNoOfBrowsePaths, const OpcUa_BrowsePath *pBrowsePaths, OpcUa_ResponseHeader *pResponseHeader, OpcUa_Int32 *pNoOfResults, OpcUa_BrowsePathResult **pResults, OpcUa_Int32 *pNoOfDiagnosticInfos, OpcUa_DiagnosticInfo **pDiagnosticInfos)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginTranslateBrowsePathsToNodeIds (OpcUa_Channel hChannel, const OpcUa_RequestHeader *pRequestHeader, OpcUa_Int32 nNoOfBrowsePaths, const OpcUa_BrowsePath *pBrowsePaths, OpcUa_Channel_PfnRequestComplete *pCallback, OpcUa_Void *pCallbackData)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_RegisterNodes (OpcUa_Channel hChannel, const OpcUa_RequestHeader *pRequestHeader, OpcUa_Int32 nNoOfNodesToRegister, const OpcUa_NodeId *pNodesToRegister, OpcUa_ResponseHeader *pResponseHeader, OpcUa_Int32 *pNoOfRegisteredNodeIds, OpcUa_NodeId **pRegisteredNodeIds)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginRegisterNodes (OpcUa_Channel hChannel, const OpcUa_RequestHeader *pRequestHeader, OpcUa_Int32 nNoOfNodesToRegister, const OpcUa_NodeId *pNodesToRegister, OpcUa_Channel_PfnRequestComplete *pCallback, OpcUa_Void *pCallbackData)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_UnregisterNodes (OpcUa_Channel hChannel, const OpcUa_RequestHeader *pRequestHeader, OpcUa_Int32 nNoOfNodesToUnregister, const OpcUa_NodeId *pNodesToUnregister, OpcUa_ResponseHeader *pResponseHeader)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginUnregisterNodes (OpcUa_Channel hChannel, const OpcUa_RequestHeader *pRequestHeader, OpcUa_Int32 nNoOfNodesToUnregister, const OpcUa_NodeId *pNodesToUnregister, OpcUa_Channel_PfnRequestComplete *pCallback, OpcUa_Void *pCallbackData)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_QueryFirst (OpcUa_Channel hChannel, const OpcUa_RequestHeader *pRequestHeader, const OpcUa_ViewDescription *pView, OpcUa_Int32 nNoOfNodeTypes, const OpcUa_NodeTypeDescription *pNodeTypes, const OpcUa_ContentFilter *pFilter, OpcUa_UInt32 nMaxDataSetsToReturn, OpcUa_UInt32 nMaxReferencesToReturn, OpcUa_ResponseHeader *pResponseHeader, OpcUa_Int32 *pNoOfQueryDataSets, OpcUa_QueryDataSet **pQueryDataSets, OpcUa_ByteString *pContinuationPoint, OpcUa_Int32 *pNoOfParsingResults, OpcUa_ParsingResult **pParsingResults, OpcUa_Int32 *pNoOfDiagnosticInfos, OpcUa_DiagnosticInfo **pDiagnosticInfos, OpcUa_ContentFilterResult *pFilterResult)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginQueryFirst (OpcUa_Channel hChannel, const OpcUa_RequestHeader *pRequestHeader, const OpcUa_ViewDescription *pView, OpcUa_Int32 nNoOfNodeTypes, const OpcUa_NodeTypeDescription *pNodeTypes, const OpcUa_ContentFilter *pFilter, OpcUa_UInt32 nMaxDataSetsToReturn, OpcUa_UInt32 nMaxReferencesToReturn, OpcUa_Channel_PfnRequestComplete *pCallback, OpcUa_Void *pCallbackData)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_QueryNext (OpcUa_Channel hChannel, const OpcUa_RequestHeader *pRequestHeader, OpcUa_Boolean bReleaseContinuationPoint, const OpcUa_ByteString *pContinuationPoint, OpcUa_ResponseHeader *pResponseHeader, OpcUa_Int32 *pNoOfQueryDataSets, OpcUa_QueryDataSet **pQueryDataSets, OpcUa_ByteString *pRevisedContinuationPoint)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginQueryNext (OpcUa_Channel hChannel, const OpcUa_RequestHeader *pRequestHeader, OpcUa_Boolean bReleaseContinuationPoint, const OpcUa_ByteString *pContinuationPoint, OpcUa_Channel_PfnRequestComplete *pCallback, OpcUa_Void *pCallbackData)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_Read (OpcUa_Channel hChannel, const OpcUa_RequestHeader *pRequestHeader, OpcUa_Double nMaxAge, OpcUa_TimestampsToReturn eTimestampsToReturn, OpcUa_Int32 nNoOfNodesToRead, const OpcUa_ReadValueId *pNodesToRead, OpcUa_ResponseHeader *pResponseHeader, OpcUa_Int32 *pNoOfResults, OpcUa_DataValue **pResults, OpcUa_Int32 *pNoOfDiagnosticInfos, OpcUa_DiagnosticInfo **pDiagnosticInfos)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginRead (OpcUa_Channel hChannel, const OpcUa_RequestHeader *pRequestHeader, OpcUa_Double nMaxAge, OpcUa_TimestampsToReturn eTimestampsToReturn, OpcUa_Int32 nNoOfNodesToRead, const OpcUa_ReadValueId *pNodesToRead, OpcUa_Channel_PfnRequestComplete *pCallback, OpcUa_Void *pCallbackData)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_HistoryRead (OpcUa_Channel hChannel, const OpcUa_RequestHeader *pRequestHeader, const OpcUa_ExtensionObject *pHistoryReadDetails, OpcUa_TimestampsToReturn eTimestampsToReturn, OpcUa_Boolean bReleaseContinuationPoints, OpcUa_Int32 nNoOfNodesToRead, const OpcUa_HistoryReadValueId *pNodesToRead, OpcUa_ResponseHeader *pResponseHeader, OpcUa_Int32 *pNoOfResults, OpcUa_HistoryReadResult **pResults, OpcUa_Int32 *pNoOfDiagnosticInfos, OpcUa_DiagnosticInfo **pDiagnosticInfos)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginHistoryRead (OpcUa_Channel hChannel, const OpcUa_RequestHeader *pRequestHeader, const OpcUa_ExtensionObject *pHistoryReadDetails, OpcUa_TimestampsToReturn eTimestampsToReturn, OpcUa_Boolean bReleaseContinuationPoints, OpcUa_Int32 nNoOfNodesToRead, const OpcUa_HistoryReadValueId *pNodesToRead, OpcUa_Channel_PfnRequestComplete *pCallback, OpcUa_Void *pCallbackData)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_Write (OpcUa_Channel hChannel, const OpcUa_RequestHeader *pRequestHeader, OpcUa_Int32 nNoOfNodesToWrite, const OpcUa_WriteValue *pNodesToWrite, OpcUa_ResponseHeader *pResponseHeader, OpcUa_Int32 *pNoOfResults, OpcUa_StatusCode **pResults, OpcUa_Int32 *pNoOfDiagnosticInfos, OpcUa_DiagnosticInfo **pDiagnosticInfos)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginWrite (OpcUa_Channel hChannel, const OpcUa_RequestHeader *pRequestHeader, OpcUa_Int32 nNoOfNodesToWrite, const OpcUa_WriteValue *pNodesToWrite, OpcUa_Channel_PfnRequestComplete *pCallback, OpcUa_Void *pCallbackData)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_HistoryUpdate (OpcUa_Channel hChannel, const OpcUa_RequestHeader *pRequestHeader, OpcUa_Int32 nNoOfHistoryUpdateDetails, const OpcUa_ExtensionObject *pHistoryUpdateDetails, OpcUa_ResponseHeader *pResponseHeader, OpcUa_Int32 *pNoOfResults, OpcUa_HistoryUpdateResult **pResults, OpcUa_Int32 *pNoOfDiagnosticInfos, OpcUa_DiagnosticInfo **pDiagnosticInfos)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginHistoryUpdate (OpcUa_Channel hChannel, const OpcUa_RequestHeader *pRequestHeader, OpcUa_Int32 nNoOfHistoryUpdateDetails, const OpcUa_ExtensionObject *pHistoryUpdateDetails, OpcUa_Channel_PfnRequestComplete *pCallback, OpcUa_Void *pCallbackData)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_Call (OpcUa_Channel hChannel, const OpcUa_RequestHeader *pRequestHeader, OpcUa_Int32 nNoOfMethodsToCall, const OpcUa_CallMethodRequest *pMethodsToCall, OpcUa_ResponseHeader *pResponseHeader, OpcUa_Int32 *pNoOfResults, OpcUa_CallMethodResult **pResults, OpcUa_Int32 *pNoOfDiagnosticInfos, OpcUa_DiagnosticInfo **pDiagnosticInfos)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginCall (OpcUa_Channel hChannel, const OpcUa_RequestHeader *pRequestHeader, OpcUa_Int32 nNoOfMethodsToCall, const OpcUa_CallMethodRequest *pMethodsToCall, OpcUa_Channel_PfnRequestComplete *pCallback, OpcUa_Void *pCallbackData)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_CreateMonitoredItems (OpcUa_Channel hChannel, const OpcUa_RequestHeader *pRequestHeader, OpcUa_UInt32 nSubscriptionId, OpcUa_TimestampsToReturn eTimestampsToReturn, OpcUa_Int32 nNoOfItemsToCreate, const OpcUa_MonitoredItemCreateRequest *pItemsToCreate, OpcUa_ResponseHeader *pResponseHeader, OpcUa_Int32 *pNoOfResults, OpcUa_MonitoredItemCreateResult **pResults, OpcUa_Int32 *pNoOfDiagnosticInfos, OpcUa_DiagnosticInfo **pDiagnosticInfos)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginCreateMonitoredItems (OpcUa_Channel hChannel, const OpcUa_RequestHeader *pRequestHeader, OpcUa_UInt32 nSubscriptionId, OpcUa_TimestampsToReturn eTimestampsToReturn, OpcUa_Int32 nNoOfItemsToCreate, const OpcUa_MonitoredItemCreateRequest *pItemsToCreate, OpcUa_Channel_PfnRequestComplete *pCallback, OpcUa_Void *pCallbackData)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_ModifyMonitoredItems (OpcUa_Channel hChannel, const OpcUa_RequestHeader *pRequestHeader, OpcUa_UInt32 nSubscriptionId, OpcUa_TimestampsToReturn eTimestampsToReturn, OpcUa_Int32 nNoOfItemsToModify, const OpcUa_MonitoredItemModifyRequest *pItemsToModify, OpcUa_ResponseHeader *pResponseHeader, OpcUa_Int32 *pNoOfResults, OpcUa_MonitoredItemModifyResult **pResults, OpcUa_Int32 *pNoOfDiagnosticInfos, OpcUa_DiagnosticInfo **pDiagnosticInfos)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginModifyMonitoredItems (OpcUa_Channel hChannel, const OpcUa_RequestHeader *pRequestHeader, OpcUa_UInt32 nSubscriptionId, OpcUa_TimestampsToReturn eTimestampsToReturn, OpcUa_Int32 nNoOfItemsToModify, const OpcUa_MonitoredItemModifyRequest *pItemsToModify, OpcUa_Channel_PfnRequestComplete *pCallback, OpcUa_Void *pCallbackData)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_SetMonitoringMode (OpcUa_Channel hChannel, const OpcUa_RequestHeader *pRequestHeader, OpcUa_UInt32 nSubscriptionId, OpcUa_MonitoringMode eMonitoringMode, OpcUa_Int32 nNoOfMonitoredItemIds, const OpcUa_UInt32 *pMonitoredItemIds, OpcUa_ResponseHeader *pResponseHeader, OpcUa_Int32 *pNoOfResults, OpcUa_StatusCode **pResults, OpcUa_Int32 *pNoOfDiagnosticInfos, OpcUa_DiagnosticInfo **pDiagnosticInfos)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginSetMonitoringMode (OpcUa_Channel hChannel, const OpcUa_RequestHeader *pRequestHeader, OpcUa_UInt32 nSubscriptionId, OpcUa_MonitoringMode eMonitoringMode, OpcUa_Int32 nNoOfMonitoredItemIds, const OpcUa_UInt32 *pMonitoredItemIds, OpcUa_Channel_PfnRequestComplete *pCallback, OpcUa_Void *pCallbackData)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_SetTriggering (OpcUa_Channel hChannel, const OpcUa_RequestHeader *pRequestHeader, OpcUa_UInt32 nSubscriptionId, OpcUa_UInt32 nTriggeringItemId, OpcUa_Int32 nNoOfLinksToAdd, const OpcUa_UInt32 *pLinksToAdd, OpcUa_Int32 nNoOfLinksToRemove, const OpcUa_UInt32 *pLinksToRemove, OpcUa_ResponseHeader *pResponseHeader, OpcUa_Int32 *pNoOfAddResults, OpcUa_StatusCode **pAddResults, OpcUa_Int32 *pNoOfAddDiagnosticInfos, OpcUa_DiagnosticInfo **pAddDiagnosticInfos, OpcUa_Int32 *pNoOfRemoveResults, OpcUa_StatusCode **pRemoveResults, OpcUa_Int32 *pNoOfRemoveDiagnosticInfos, OpcUa_DiagnosticInfo **pRemoveDiagnosticInfos)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginSetTriggering (OpcUa_Channel hChannel, const OpcUa_RequestHeader *pRequestHeader, OpcUa_UInt32 nSubscriptionId, OpcUa_UInt32 nTriggeringItemId, OpcUa_Int32 nNoOfLinksToAdd, const OpcUa_UInt32 *pLinksToAdd, OpcUa_Int32 nNoOfLinksToRemove, const OpcUa_UInt32 *pLinksToRemove, OpcUa_Channel_PfnRequestComplete *pCallback, OpcUa_Void *pCallbackData)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_DeleteMonitoredItems (OpcUa_Channel hChannel, const OpcUa_RequestHeader *pRequestHeader, OpcUa_UInt32 nSubscriptionId, OpcUa_Int32 nNoOfMonitoredItemIds, const OpcUa_UInt32 *pMonitoredItemIds, OpcUa_ResponseHeader *pResponseHeader, OpcUa_Int32 *pNoOfResults, OpcUa_StatusCode **pResults, OpcUa_Int32 *pNoOfDiagnosticInfos, OpcUa_DiagnosticInfo **pDiagnosticInfos)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginDeleteMonitoredItems (OpcUa_Channel hChannel, const OpcUa_RequestHeader *pRequestHeader, OpcUa_UInt32 nSubscriptionId, OpcUa_Int32 nNoOfMonitoredItemIds, const OpcUa_UInt32 *pMonitoredItemIds, OpcUa_Channel_PfnRequestComplete *pCallback, OpcUa_Void *pCallbackData)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_CreateSubscription (OpcUa_Channel hChannel, const OpcUa_RequestHeader *pRequestHeader, OpcUa_Double nRequestedPublishingInterval, OpcUa_UInt32 nRequestedLifetimeCount, OpcUa_UInt32 nRequestedMaxKeepAliveCount, OpcUa_UInt32 nMaxNotificationsPerPublish, OpcUa_Boolean bPublishingEnabled, OpcUa_Byte nPriority, OpcUa_ResponseHeader *pResponseHeader, OpcUa_UInt32 *pSubscriptionId, OpcUa_Double *pRevisedPublishingInterval, OpcUa_UInt32 *pRevisedLifetimeCount, OpcUa_UInt32 *pRevisedMaxKeepAliveCount)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginCreateSubscription (OpcUa_Channel hChannel, const OpcUa_RequestHeader *pRequestHeader, OpcUa_Double nRequestedPublishingInterval, OpcUa_UInt32 nRequestedLifetimeCount, OpcUa_UInt32 nRequestedMaxKeepAliveCount, OpcUa_UInt32 nMaxNotificationsPerPublish, OpcUa_Boolean bPublishingEnabled, OpcUa_Byte nPriority, OpcUa_Channel_PfnRequestComplete *pCallback, OpcUa_Void *pCallbackData)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_ModifySubscription (OpcUa_Channel hChannel, const OpcUa_RequestHeader *pRequestHeader, OpcUa_UInt32 nSubscriptionId, OpcUa_Double nRequestedPublishingInterval, OpcUa_UInt32 nRequestedLifetimeCount, OpcUa_UInt32 nRequestedMaxKeepAliveCount, OpcUa_UInt32 nMaxNotificationsPerPublish, OpcUa_Byte nPriority, OpcUa_ResponseHeader *pResponseHeader, OpcUa_Double *pRevisedPublishingInterval, OpcUa_UInt32 *pRevisedLifetimeCount, OpcUa_UInt32 *pRevisedMaxKeepAliveCount)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginModifySubscription (OpcUa_Channel hChannel, const OpcUa_RequestHeader *pRequestHeader, OpcUa_UInt32 nSubscriptionId, OpcUa_Double nRequestedPublishingInterval, OpcUa_UInt32 nRequestedLifetimeCount, OpcUa_UInt32 nRequestedMaxKeepAliveCount, OpcUa_UInt32 nMaxNotificationsPerPublish, OpcUa_Byte nPriority, OpcUa_Channel_PfnRequestComplete *pCallback, OpcUa_Void *pCallbackData)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_SetPublishingMode (OpcUa_Channel hChannel, const OpcUa_RequestHeader *pRequestHeader, OpcUa_Boolean bPublishingEnabled, OpcUa_Int32 nNoOfSubscriptionIds, const OpcUa_UInt32 *pSubscriptionIds, OpcUa_ResponseHeader *pResponseHeader, OpcUa_Int32 *pNoOfResults, OpcUa_StatusCode **pResults, OpcUa_Int32 *pNoOfDiagnosticInfos, OpcUa_DiagnosticInfo **pDiagnosticInfos)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginSetPublishingMode (OpcUa_Channel hChannel, const OpcUa_RequestHeader *pRequestHeader, OpcUa_Boolean bPublishingEnabled, OpcUa_Int32 nNoOfSubscriptionIds, const OpcUa_UInt32 *pSubscriptionIds, OpcUa_Channel_PfnRequestComplete *pCallback, OpcUa_Void *pCallbackData)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_Publish (OpcUa_Channel hChannel, const OpcUa_RequestHeader *pRequestHeader, OpcUa_Int32 nNoOfSubscriptionAcknowledgements, const OpcUa_SubscriptionAcknowledgement *pSubscriptionAcknowledgements, OpcUa_ResponseHeader *pResponseHeader, OpcUa_UInt32 *pSubscriptionId, OpcUa_Int32 *pNoOfAvailableSequenceNumbers, OpcUa_UInt32 **pAvailableSequenceNumbers, OpcUa_Boolean *pMoreNotifications, OpcUa_NotificationMessage *pNotificationMessage, OpcUa_Int32 *pNoOfResults, OpcUa_StatusCode **pResults, OpcUa_Int32 *pNoOfDiagnosticInfos, OpcUa_DiagnosticInfo **pDiagnosticInfos)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginPublish (OpcUa_Channel hChannel, const OpcUa_RequestHeader *pRequestHeader, OpcUa_Int32 nNoOfSubscriptionAcknowledgements, const OpcUa_SubscriptionAcknowledgement *pSubscriptionAcknowledgements, OpcUa_Channel_PfnRequestComplete *pCallback, OpcUa_Void *pCallbackData)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_Republish (OpcUa_Channel hChannel, const OpcUa_RequestHeader *pRequestHeader, OpcUa_UInt32 nSubscriptionId, OpcUa_UInt32 nRetransmitSequenceNumber, OpcUa_ResponseHeader *pResponseHeader, OpcUa_NotificationMessage *pNotificationMessage)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginRepublish (OpcUa_Channel hChannel, const OpcUa_RequestHeader *pRequestHeader, OpcUa_UInt32 nSubscriptionId, OpcUa_UInt32 nRetransmitSequenceNumber, OpcUa_Channel_PfnRequestComplete *pCallback, OpcUa_Void *pCallbackData)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_TransferSubscriptions (OpcUa_Channel hChannel, const OpcUa_RequestHeader *pRequestHeader, OpcUa_Int32 nNoOfSubscriptionIds, const OpcUa_UInt32 *pSubscriptionIds, OpcUa_Boolean bSendInitialValues, OpcUa_ResponseHeader *pResponseHeader, OpcUa_Int32 *pNoOfResults, OpcUa_TransferResult **pResults, OpcUa_Int32 *pNoOfDiagnosticInfos, OpcUa_DiagnosticInfo **pDiagnosticInfos)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginTransferSubscriptions (OpcUa_Channel hChannel, const OpcUa_RequestHeader *pRequestHeader, OpcUa_Int32 nNoOfSubscriptionIds, const OpcUa_UInt32 *pSubscriptionIds, OpcUa_Boolean bSendInitialValues, OpcUa_Channel_PfnRequestComplete *pCallback, OpcUa_Void *pCallbackData)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_DeleteSubscriptions (OpcUa_Channel hChannel, const OpcUa_RequestHeader *pRequestHeader, OpcUa_Int32 nNoOfSubscriptionIds, const OpcUa_UInt32 *pSubscriptionIds, OpcUa_ResponseHeader *pResponseHeader, OpcUa_Int32 *pNoOfResults, OpcUa_StatusCode **pResults, OpcUa_Int32 *pNoOfDiagnosticInfos, OpcUa_DiagnosticInfo **pDiagnosticInfos)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginDeleteSubscriptions (OpcUa_Channel hChannel, const OpcUa_RequestHeader *pRequestHeader, OpcUa_Int32 nNoOfSubscriptionIds, const OpcUa_UInt32 *pSubscriptionIds, OpcUa_Channel_PfnRequestComplete *pCallback, OpcUa_Void *pCallbackData)
Function Documentation
OpcUa_ClientApi_ActivateSession()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_ActivateSession (OpcUa_Channel hChannel, const OpcUa_RequestHeader * pRequestHeader, const OpcUa_SignatureData * pClientSignature, OpcUa_Int32 nNoOfClientSoftwareCertificates, const OpcUa_SignedSoftwareCertificate * pClientSoftwareCertificates, OpcUa_Int32 nNoOfLocaleIds, const OpcUa_String * pLocaleIds, const OpcUa_ExtensionObject * pUserIdentityToken, const OpcUa_SignatureData * pUserTokenSignature, OpcUa_ResponseHeader * pResponseHeader, OpcUa_ByteString * pServerNonce, OpcUa_Int32 * pNoOfResults, OpcUa_StatusCode ** pResults, OpcUa_Int32 * pNoOfDiagnosticInfos, OpcUa_DiagnosticInfo ** pDiagnosticInfos)
Definition at line 908 of file opcua_clientapi.c.
References _OpcUa_ActivateSessionRequest::ClientSignature, _OpcUa_ActivateSessionRequest::ClientSoftwareCertificates, _OpcUa_ActivateSessionRequest::LocaleIds, _OpcUa_ActivateSessionRequest::NoOfClientSoftwareCertificates, _OpcUa_ActivateSessionRequest::NoOfLocaleIds, OpcUa_ActivateSessionRequest_EncodeableType, OpcUa_ActivateSessionRequest_Initialize(), _OpcUa_ActivateSessionRequest::RequestHeader, _OpcUa_ActivateSessionRequest::UserIdentityToken, and _OpcUa_ActivateSessionRequest::UserTokenSignature.
OpcUa_ClientApi_AddNodes()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_AddNodes (OpcUa_Channel hChannel, const OpcUa_RequestHeader * pRequestHeader, OpcUa_Int32 nNoOfNodesToAdd, const OpcUa_AddNodesItem * pNodesToAdd, OpcUa_ResponseHeader * pResponseHeader, OpcUa_Int32 * pNoOfResults, OpcUa_AddNodesResult ** pResults, OpcUa_Int32 * pNoOfDiagnosticInfos, OpcUa_DiagnosticInfo ** pDiagnosticInfos)
Definition at line 1300 of file opcua_clientapi.c.
References _OpcUa_AddNodesRequest::NodesToAdd, _OpcUa_AddNodesRequest::NoOfNodesToAdd, OpcUa_AddNodesRequest_EncodeableType, OpcUa_AddNodesRequest_Initialize(), and _OpcUa_AddNodesRequest::RequestHeader.
OpcUa_ClientApi_AddReferences()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_AddReferences (OpcUa_Channel hChannel, const OpcUa_RequestHeader * pRequestHeader, OpcUa_Int32 nNoOfReferencesToAdd, const OpcUa_AddReferencesItem * pReferencesToAdd, OpcUa_ResponseHeader * pResponseHeader, OpcUa_Int32 * pNoOfResults, OpcUa_StatusCode ** pResults, OpcUa_Int32 * pNoOfDiagnosticInfos, OpcUa_DiagnosticInfo ** pDiagnosticInfos)
Definition at line 1430 of file opcua_clientapi.c.
References _OpcUa_AddReferencesRequest::NoOfReferencesToAdd, OpcUa_AddReferencesRequest_EncodeableType, OpcUa_AddReferencesRequest_Initialize(), _OpcUa_AddReferencesRequest::ReferencesToAdd, and _OpcUa_AddReferencesRequest::RequestHeader.
OpcUa_ClientApi_BeginActivateSession()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginActivateSession (OpcUa_Channel hChannel, const OpcUa_RequestHeader * pRequestHeader, const OpcUa_SignatureData * pClientSignature, OpcUa_Int32 nNoOfClientSoftwareCertificates, const OpcUa_SignedSoftwareCertificate * pClientSoftwareCertificates, OpcUa_Int32 nNoOfLocaleIds, const OpcUa_String * pLocaleIds, const OpcUa_ExtensionObject * pUserIdentityToken, const OpcUa_SignatureData * pUserTokenSignature, OpcUa_Channel_PfnRequestComplete * pCallback, OpcUa_Void * pCallbackData)
Definition at line 1008 of file opcua_clientapi.c.
References _OpcUa_ActivateSessionRequest::ClientSignature, _OpcUa_ActivateSessionRequest::ClientSoftwareCertificates, _OpcUa_ActivateSessionRequest::LocaleIds, _OpcUa_ActivateSessionRequest::NoOfClientSoftwareCertificates, _OpcUa_ActivateSessionRequest::NoOfLocaleIds, OpcUa_ActivateSessionRequest_EncodeableType, OpcUa_ActivateSessionRequest_Initialize(), _OpcUa_ActivateSessionRequest::RequestHeader, _OpcUa_ActivateSessionRequest::UserIdentityToken, and _OpcUa_ActivateSessionRequest::UserTokenSignature.
OpcUa_ClientApi_BeginAddNodes()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginAddNodes (OpcUa_Channel hChannel, const OpcUa_RequestHeader * pRequestHeader, OpcUa_Int32 nNoOfNodesToAdd, const OpcUa_AddNodesItem * pNodesToAdd, OpcUa_Channel_PfnRequestComplete * pCallback, OpcUa_Void * pCallbackData)
Definition at line 1383 of file opcua_clientapi.c.
References _OpcUa_AddNodesRequest::NodesToAdd, _OpcUa_AddNodesRequest::NoOfNodesToAdd, OpcUa_AddNodesRequest_EncodeableType, OpcUa_AddNodesRequest_Initialize(), and _OpcUa_AddNodesRequest::RequestHeader.
OpcUa_ClientApi_BeginAddReferences()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginAddReferences (OpcUa_Channel hChannel, const OpcUa_RequestHeader * pRequestHeader, OpcUa_Int32 nNoOfReferencesToAdd, const OpcUa_AddReferencesItem * pReferencesToAdd, OpcUa_Channel_PfnRequestComplete * pCallback, OpcUa_Void * pCallbackData)
Definition at line 1513 of file opcua_clientapi.c.
References _OpcUa_AddReferencesRequest::NoOfReferencesToAdd, OpcUa_AddReferencesRequest_EncodeableType, OpcUa_AddReferencesRequest_Initialize(), _OpcUa_AddReferencesRequest::ReferencesToAdd, and _OpcUa_AddReferencesRequest::RequestHeader.
OpcUa_ClientApi_BeginBrowse()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginBrowse (OpcUa_Channel hChannel, const OpcUa_RequestHeader * pRequestHeader, const OpcUa_ViewDescription * pView, OpcUa_UInt32 nRequestedMaxReferencesPerNode, OpcUa_Int32 nNoOfNodesToBrowse, const OpcUa_BrowseDescription * pNodesToBrowse, OpcUa_Channel_PfnRequestComplete * pCallback, OpcUa_Void * pCallbackData)
Definition at line 1909 of file opcua_clientapi.c.
References _OpcUa_BrowseRequest::NodesToBrowse, _OpcUa_BrowseRequest::NoOfNodesToBrowse, OpcUa_BrowseRequest_EncodeableType, OpcUa_BrowseRequest_Initialize(), _OpcUa_BrowseRequest::RequestedMaxReferencesPerNode, _OpcUa_BrowseRequest::RequestHeader, and _OpcUa_BrowseRequest::View.
OpcUa_ClientApi_BeginBrowseNext()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginBrowseNext (OpcUa_Channel hChannel, const OpcUa_RequestHeader * pRequestHeader, OpcUa_Boolean bReleaseContinuationPoints, OpcUa_Int32 nNoOfContinuationPoints, const OpcUa_ByteString * pContinuationPoints, OpcUa_Channel_PfnRequestComplete * pCallback, OpcUa_Void * pCallbackData)
Definition at line 2048 of file opcua_clientapi.c.
References _OpcUa_BrowseNextRequest::ContinuationPoints, _OpcUa_BrowseNextRequest::NoOfContinuationPoints, OpcUa_BrowseNextRequest_EncodeableType, OpcUa_BrowseNextRequest_Initialize(), _OpcUa_BrowseNextRequest::ReleaseContinuationPoints, and _OpcUa_BrowseNextRequest::RequestHeader.
OpcUa_ClientApi_BeginCall()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginCall (OpcUa_Channel hChannel, const OpcUa_RequestHeader * pRequestHeader, OpcUa_Int32 nNoOfMethodsToCall, const OpcUa_CallMethodRequest * pMethodsToCall, OpcUa_Channel_PfnRequestComplete * pCallback, OpcUa_Void * pCallbackData)
Definition at line 3398 of file opcua_clientapi.c.
References _OpcUa_CallRequest::MethodsToCall, _OpcUa_CallRequest::NoOfMethodsToCall, OpcUa_CallRequest_EncodeableType, OpcUa_CallRequest_Initialize(), and _OpcUa_CallRequest::RequestHeader.
OpcUa_ClientApi_BeginCancel()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginCancel (OpcUa_Channel hChannel, const OpcUa_RequestHeader * pRequestHeader, OpcUa_UInt32 nRequestHandle, OpcUa_Channel_PfnRequestComplete * pCallback, OpcUa_Void * pCallbackData)
Definition at line 1255 of file opcua_clientapi.c.
References OpcUa_CancelRequest_EncodeableType, OpcUa_CancelRequest_Initialize(), _OpcUa_CancelRequest::RequestHandle, and _OpcUa_CancelRequest::RequestHeader.
OpcUa_ClientApi_BeginCloseSession()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginCloseSession (OpcUa_Channel hChannel, const OpcUa_RequestHeader * pRequestHeader, OpcUa_Boolean bDeleteSubscriptions, OpcUa_Channel_PfnRequestComplete * pCallback, OpcUa_Void * pCallbackData)
Definition at line 1138 of file opcua_clientapi.c.
References _OpcUa_CloseSessionRequest::DeleteSubscriptions, OpcUa_CloseSessionRequest_EncodeableType, OpcUa_CloseSessionRequest_Initialize(), and _OpcUa_CloseSessionRequest::RequestHeader.
OpcUa_ClientApi_BeginCreateMonitoredItems()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginCreateMonitoredItems (OpcUa_Channel hChannel, const OpcUa_RequestHeader * pRequestHeader, OpcUa_UInt32 nSubscriptionId, OpcUa_TimestampsToReturn eTimestampsToReturn, OpcUa_Int32 nNoOfItemsToCreate, const OpcUa_MonitoredItemCreateRequest * pItemsToCreate, OpcUa_Channel_PfnRequestComplete * pCallback, OpcUa_Void * pCallbackData)
Definition at line 3534 of file opcua_clientapi.c.
References _OpcUa_CreateMonitoredItemsRequest::ItemsToCreate, _OpcUa_CreateMonitoredItemsRequest::NoOfItemsToCreate, OpcUa_CreateMonitoredItemsRequest_EncodeableType, OpcUa_CreateMonitoredItemsRequest_Initialize(), _OpcUa_CreateMonitoredItemsRequest::RequestHeader, _OpcUa_CreateMonitoredItemsRequest::SubscriptionId, and _OpcUa_CreateMonitoredItemsRequest::TimestampsToReturn.
OpcUa_ClientApi_BeginCreateSession()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginCreateSession (OpcUa_Channel hChannel, const OpcUa_RequestHeader * pRequestHeader, const OpcUa_ApplicationDescription * pClientDescription, const OpcUa_String * pServerUri, const OpcUa_String * pEndpointUrl, const OpcUa_String * pSessionName, const OpcUa_ByteString * pClientNonce, const OpcUa_ByteString * pClientCertificate, OpcUa_Double nRequestedSessionTimeout, OpcUa_UInt32 nMaxResponseMessageSize, OpcUa_Channel_PfnRequestComplete * pCallback, OpcUa_Void * pCallbackData)
Definition at line 842 of file opcua_clientapi.c.
References _OpcUa_CreateSessionRequest::ClientCertificate, _OpcUa_CreateSessionRequest::ClientDescription, _OpcUa_CreateSessionRequest::ClientNonce, _OpcUa_CreateSessionRequest::EndpointUrl, _OpcUa_CreateSessionRequest::MaxResponseMessageSize, OpcUa_CreateSessionRequest_EncodeableType, OpcUa_CreateSessionRequest_Initialize(), _OpcUa_CreateSessionRequest::RequestedSessionTimeout, _OpcUa_CreateSessionRequest::RequestHeader, _OpcUa_CreateSessionRequest::ServerUri, and _OpcUa_CreateSessionRequest::SessionName.
OpcUa_ClientApi_BeginCreateSubscription()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginCreateSubscription (OpcUa_Channel hChannel, const OpcUa_RequestHeader * pRequestHeader, OpcUa_Double nRequestedPublishingInterval, OpcUa_UInt32 nRequestedLifetimeCount, OpcUa_UInt32 nRequestedMaxKeepAliveCount, OpcUa_UInt32 nMaxNotificationsPerPublish, OpcUa_Boolean bPublishingEnabled, OpcUa_Byte nPriority, OpcUa_Channel_PfnRequestComplete * pCallback, OpcUa_Void * pCallbackData)
Definition at line 4267 of file opcua_clientapi.c.
References _OpcUa_CreateSubscriptionRequest::MaxNotificationsPerPublish, OpcUa_CreateSubscriptionRequest_EncodeableType, OpcUa_CreateSubscriptionRequest_Initialize(), _OpcUa_CreateSubscriptionRequest::Priority, _OpcUa_CreateSubscriptionRequest::PublishingEnabled, _OpcUa_CreateSubscriptionRequest::RequestedLifetimeCount, _OpcUa_CreateSubscriptionRequest::RequestedMaxKeepAliveCount, _OpcUa_CreateSubscriptionRequest::RequestedPublishingInterval, and _OpcUa_CreateSubscriptionRequest::RequestHeader.
OpcUa_ClientApi_BeginDeleteMonitoredItems()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginDeleteMonitoredItems (OpcUa_Channel hChannel, const OpcUa_RequestHeader * pRequestHeader, OpcUa_UInt32 nSubscriptionId, OpcUa_Int32 nNoOfMonitoredItemIds, const OpcUa_UInt32 * pMonitoredItemIds, OpcUa_Channel_PfnRequestComplete * pCallback, OpcUa_Void * pCallbackData)
Definition at line 4121 of file opcua_clientapi.c.
References _OpcUa_DeleteMonitoredItemsRequest::MonitoredItemIds, _OpcUa_DeleteMonitoredItemsRequest::NoOfMonitoredItemIds, OpcUa_DeleteMonitoredItemsRequest_EncodeableType, OpcUa_DeleteMonitoredItemsRequest_Initialize(), _OpcUa_DeleteMonitoredItemsRequest::RequestHeader, and _OpcUa_DeleteMonitoredItemsRequest::SubscriptionId.
OpcUa_ClientApi_BeginDeleteNodes()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginDeleteNodes (OpcUa_Channel hChannel, const OpcUa_RequestHeader * pRequestHeader, OpcUa_Int32 nNoOfNodesToDelete, const OpcUa_DeleteNodesItem * pNodesToDelete, OpcUa_Channel_PfnRequestComplete * pCallback, OpcUa_Void * pCallbackData)
Definition at line 1643 of file opcua_clientapi.c.
References _OpcUa_DeleteNodesRequest::NodesToDelete, _OpcUa_DeleteNodesRequest::NoOfNodesToDelete, OpcUa_DeleteNodesRequest_EncodeableType, OpcUa_DeleteNodesRequest_Initialize(), and _OpcUa_DeleteNodesRequest::RequestHeader.
OpcUa_ClientApi_BeginDeleteReferences()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginDeleteReferences (OpcUa_Channel hChannel, const OpcUa_RequestHeader * pRequestHeader, OpcUa_Int32 nNoOfReferencesToDelete, const OpcUa_DeleteReferencesItem * pReferencesToDelete, OpcUa_Channel_PfnRequestComplete * pCallback, OpcUa_Void * pCallbackData)
Definition at line 1773 of file opcua_clientapi.c.
References _OpcUa_DeleteReferencesRequest::NoOfReferencesToDelete, OpcUa_DeleteReferencesRequest_EncodeableType, OpcUa_DeleteReferencesRequest_Initialize(), _OpcUa_DeleteReferencesRequest::ReferencesToDelete, and _OpcUa_DeleteReferencesRequest::RequestHeader.
OpcUa_ClientApi_BeginDeleteSubscriptions()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginDeleteSubscriptions (OpcUa_Channel hChannel, const OpcUa_RequestHeader * pRequestHeader, OpcUa_Int32 nNoOfSubscriptionIds, const OpcUa_UInt32 * pSubscriptionIds, OpcUa_Channel_PfnRequestComplete * pCallback, OpcUa_Void * pCallbackData)
Definition at line 5103 of file opcua_clientapi.c.
References _OpcUa_DeleteSubscriptionsRequest::NoOfSubscriptionIds, OpcUa_DeleteSubscriptionsRequest_EncodeableType, OpcUa_DeleteSubscriptionsRequest_Initialize(), _OpcUa_DeleteSubscriptionsRequest::RequestHeader, and _OpcUa_DeleteSubscriptionsRequest::SubscriptionIds.
OpcUa_ClientApi_BeginFindServers()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginFindServers (OpcUa_Channel hChannel, const OpcUa_RequestHeader * pRequestHeader, const OpcUa_String * pEndpointUrl, OpcUa_Int32 nNoOfLocaleIds, const OpcUa_String * pLocaleIds, OpcUa_Int32 nNoOfServerUris, const OpcUa_String * pServerUris, OpcUa_Channel_PfnRequestComplete * pCallback, OpcUa_Void * pCallbackData)
Definition at line 135 of file opcua_clientapi.c.
References _OpcUa_FindServersRequest::EndpointUrl, _OpcUa_FindServersRequest::LocaleIds, _OpcUa_FindServersRequest::NoOfLocaleIds, _OpcUa_FindServersRequest::NoOfServerUris, OpcUa_FindServersRequest_EncodeableType, OpcUa_FindServersRequest_Initialize(), _OpcUa_FindServersRequest::RequestHeader, and _OpcUa_FindServersRequest::ServerUris.
OpcUa_ClientApi_BeginFindServersOnNetwork()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginFindServersOnNetwork (OpcUa_Channel hChannel, const OpcUa_RequestHeader * pRequestHeader, OpcUa_UInt32 nStartingRecordId, OpcUa_UInt32 nMaxRecordsToReturn, OpcUa_Int32 nNoOfServerCapabilityFilter, const OpcUa_String * pServerCapabilityFilter, OpcUa_Channel_PfnRequestComplete * pCallback, OpcUa_Void * pCallbackData)
Definition at line 276 of file opcua_clientapi.c.
References _OpcUa_FindServersOnNetworkRequest::MaxRecordsToReturn, _OpcUa_FindServersOnNetworkRequest::NoOfServerCapabilityFilter, OpcUa_FindServersOnNetworkRequest_EncodeableType, OpcUa_FindServersOnNetworkRequest_Initialize(), _OpcUa_FindServersOnNetworkRequest::RequestHeader, _OpcUa_FindServersOnNetworkRequest::ServerCapabilityFilter, and _OpcUa_FindServersOnNetworkRequest::StartingRecordId.
OpcUa_ClientApi_BeginGetEndpoints()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginGetEndpoints (OpcUa_Channel hChannel, const OpcUa_RequestHeader * pRequestHeader, const OpcUa_String * pEndpointUrl, OpcUa_Int32 nNoOfLocaleIds, const OpcUa_String * pLocaleIds, OpcUa_Int32 nNoOfProfileUris, const OpcUa_String * pProfileUris, OpcUa_Channel_PfnRequestComplete * pCallback, OpcUa_Void * pCallbackData)
Definition at line 414 of file opcua_clientapi.c.
References _OpcUa_GetEndpointsRequest::EndpointUrl, _OpcUa_GetEndpointsRequest::LocaleIds, _OpcUa_GetEndpointsRequest::NoOfLocaleIds, _OpcUa_GetEndpointsRequest::NoOfProfileUris, OpcUa_GetEndpointsRequest_EncodeableType, OpcUa_GetEndpointsRequest_Initialize(), _OpcUa_GetEndpointsRequest::ProfileUris, and _OpcUa_GetEndpointsRequest::RequestHeader.
OpcUa_ClientApi_BeginHistoryRead()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginHistoryRead (OpcUa_Channel hChannel, const OpcUa_RequestHeader * pRequestHeader, const OpcUa_ExtensionObject * pHistoryReadDetails, OpcUa_TimestampsToReturn eTimestampsToReturn, OpcUa_Boolean bReleaseContinuationPoints, OpcUa_Int32 nNoOfNodesToRead, const OpcUa_HistoryReadValueId * pNodesToRead, OpcUa_Channel_PfnRequestComplete * pCallback, OpcUa_Void * pCallbackData)
Definition at line 2999 of file opcua_clientapi.c.
References _OpcUa_HistoryReadRequest::HistoryReadDetails, _OpcUa_HistoryReadRequest::NodesToRead, _OpcUa_HistoryReadRequest::NoOfNodesToRead, OpcUa_HistoryReadRequest_EncodeableType, OpcUa_HistoryReadRequest_Initialize(), _OpcUa_HistoryReadRequest::ReleaseContinuationPoints, _OpcUa_HistoryReadRequest::RequestHeader, and _OpcUa_HistoryReadRequest::TimestampsToReturn.
OpcUa_ClientApi_BeginHistoryUpdate()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginHistoryUpdate (OpcUa_Channel hChannel, const OpcUa_RequestHeader * pRequestHeader, OpcUa_Int32 nNoOfHistoryUpdateDetails, const OpcUa_ExtensionObject * pHistoryUpdateDetails, OpcUa_Channel_PfnRequestComplete * pCallback, OpcUa_Void * pCallbackData)
Definition at line 3268 of file opcua_clientapi.c.
References _OpcUa_HistoryUpdateRequest::HistoryUpdateDetails, _OpcUa_HistoryUpdateRequest::NoOfHistoryUpdateDetails, OpcUa_HistoryUpdateRequest_EncodeableType, OpcUa_HistoryUpdateRequest_Initialize(), and _OpcUa_HistoryUpdateRequest::RequestHeader.
OpcUa_ClientApi_BeginModifyMonitoredItems()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginModifyMonitoredItems (OpcUa_Channel hChannel, const OpcUa_RequestHeader * pRequestHeader, OpcUa_UInt32 nSubscriptionId, OpcUa_TimestampsToReturn eTimestampsToReturn, OpcUa_Int32 nNoOfItemsToModify, const OpcUa_MonitoredItemModifyRequest * pItemsToModify, OpcUa_Channel_PfnRequestComplete * pCallback, OpcUa_Void * pCallbackData)
Definition at line 3676 of file opcua_clientapi.c.
References _OpcUa_ModifyMonitoredItemsRequest::ItemsToModify, _OpcUa_ModifyMonitoredItemsRequest::NoOfItemsToModify, OpcUa_ModifyMonitoredItemsRequest_EncodeableType, OpcUa_ModifyMonitoredItemsRequest_Initialize(), _OpcUa_ModifyMonitoredItemsRequest::RequestHeader, _OpcUa_ModifyMonitoredItemsRequest::SubscriptionId, and _OpcUa_ModifyMonitoredItemsRequest::TimestampsToReturn.
OpcUa_ClientApi_BeginModifySubscription()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginModifySubscription (OpcUa_Channel hChannel, const OpcUa_RequestHeader * pRequestHeader, OpcUa_UInt32 nSubscriptionId, OpcUa_Double nRequestedPublishingInterval, OpcUa_UInt32 nRequestedLifetimeCount, OpcUa_UInt32 nRequestedMaxKeepAliveCount, OpcUa_UInt32 nMaxNotificationsPerPublish, OpcUa_Byte nPriority, OpcUa_Channel_PfnRequestComplete * pCallback, OpcUa_Void * pCallbackData)
Definition at line 4420 of file opcua_clientapi.c.
References _OpcUa_ModifySubscriptionRequest::MaxNotificationsPerPublish, OpcUa_ModifySubscriptionRequest_EncodeableType, OpcUa_ModifySubscriptionRequest_Initialize(), _OpcUa_ModifySubscriptionRequest::Priority, _OpcUa_ModifySubscriptionRequest::RequestedLifetimeCount, _OpcUa_ModifySubscriptionRequest::RequestedMaxKeepAliveCount, _OpcUa_ModifySubscriptionRequest::RequestedPublishingInterval, _OpcUa_ModifySubscriptionRequest::RequestHeader, and _OpcUa_ModifySubscriptionRequest::SubscriptionId.
OpcUa_ClientApi_BeginPublish()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginPublish (OpcUa_Channel hChannel, const OpcUa_RequestHeader * pRequestHeader, OpcUa_Int32 nNoOfSubscriptionAcknowledgements, const OpcUa_SubscriptionAcknowledgement * pSubscriptionAcknowledgements, OpcUa_Channel_PfnRequestComplete * pCallback, OpcUa_Void * pCallbackData)
Definition at line 4714 of file opcua_clientapi.c.
References _OpcUa_PublishRequest::NoOfSubscriptionAcknowledgements, OpcUa_PublishRequest_EncodeableType, OpcUa_PublishRequest_Initialize(), _OpcUa_PublishRequest::RequestHeader, and _OpcUa_PublishRequest::SubscriptionAcknowledgements.
OpcUa_ClientApi_BeginQueryFirst()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginQueryFirst (OpcUa_Channel hChannel, const OpcUa_RequestHeader * pRequestHeader, const OpcUa_ViewDescription * pView, OpcUa_Int32 nNoOfNodeTypes, const OpcUa_NodeTypeDescription * pNodeTypes, const OpcUa_ContentFilter * pFilter, OpcUa_UInt32 nMaxDataSetsToReturn, OpcUa_UInt32 nMaxReferencesToReturn, OpcUa_Channel_PfnRequestComplete * pCallback, OpcUa_Void * pCallbackData)
Definition at line 2577 of file opcua_clientapi.c.
References _OpcUa_QueryFirstRequest::Filter, _OpcUa_QueryFirstRequest::MaxDataSetsToReturn, _OpcUa_QueryFirstRequest::MaxReferencesToReturn, _OpcUa_QueryFirstRequest::NodeTypes, _OpcUa_QueryFirstRequest::NoOfNodeTypes, OpcUa_QueryFirstRequest_EncodeableType, OpcUa_QueryFirstRequest_Initialize(), _OpcUa_QueryFirstRequest::RequestHeader, and _OpcUa_QueryFirstRequest::View.
OpcUa_ClientApi_BeginQueryNext()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginQueryNext (OpcUa_Channel hChannel, const OpcUa_RequestHeader * pRequestHeader, OpcUa_Boolean bReleaseContinuationPoint, const OpcUa_ByteString * pContinuationPoint, OpcUa_Channel_PfnRequestComplete * pCallback, OpcUa_Void * pCallbackData)
Definition at line 2717 of file opcua_clientapi.c.
References _OpcUa_QueryNextRequest::ContinuationPoint, OpcUa_QueryNextRequest_EncodeableType, OpcUa_QueryNextRequest_Initialize(), _OpcUa_QueryNextRequest::ReleaseContinuationPoint, and _OpcUa_QueryNextRequest::RequestHeader.
OpcUa_ClientApi_BeginRead()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginRead (OpcUa_Channel hChannel, const OpcUa_RequestHeader * pRequestHeader, OpcUa_Double nMaxAge, OpcUa_TimestampsToReturn eTimestampsToReturn, OpcUa_Int32 nNoOfNodesToRead, const OpcUa_ReadValueId * pNodesToRead, OpcUa_Channel_PfnRequestComplete * pCallback, OpcUa_Void * pCallbackData)
Definition at line 2854 of file opcua_clientapi.c.
References _OpcUa_ReadRequest::MaxAge, _OpcUa_ReadRequest::NodesToRead, _OpcUa_ReadRequest::NoOfNodesToRead, OpcUa_ReadRequest_EncodeableType, OpcUa_ReadRequest_Initialize(), _OpcUa_ReadRequest::RequestHeader, and _OpcUa_ReadRequest::TimestampsToReturn.
OpcUa_ClientApi_BeginRegisterNodes()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginRegisterNodes (OpcUa_Channel hChannel, const OpcUa_RequestHeader * pRequestHeader, OpcUa_Int32 nNoOfNodesToRegister, const OpcUa_NodeId * pNodesToRegister, OpcUa_Channel_PfnRequestComplete * pCallback, OpcUa_Void * pCallbackData)
Definition at line 2305 of file opcua_clientapi.c.
References _OpcUa_RegisterNodesRequest::NodesToRegister, _OpcUa_RegisterNodesRequest::NoOfNodesToRegister, OpcUa_RegisterNodesRequest_EncodeableType, OpcUa_RegisterNodesRequest_Initialize(), and _OpcUa_RegisterNodesRequest::RequestHeader.
OpcUa_ClientApi_BeginRegisterServer()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginRegisterServer (OpcUa_Channel hChannel, const OpcUa_RequestHeader * pRequestHeader, const OpcUa_RegisteredServer * pServer, OpcUa_Channel_PfnRequestComplete * pCallback, OpcUa_Void * pCallbackData)
Definition at line 538 of file opcua_clientapi.c.
References OpcUa_RegisterServerRequest_EncodeableType, OpcUa_RegisterServerRequest_Initialize(), _OpcUa_RegisterServerRequest::RequestHeader, and _OpcUa_RegisterServerRequest::Server.
OpcUa_ClientApi_BeginRegisterServer2()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginRegisterServer2 (OpcUa_Channel hChannel, const OpcUa_RequestHeader * pRequestHeader, const OpcUa_RegisteredServer * pServer, OpcUa_Int32 nNoOfDiscoveryConfiguration, const OpcUa_ExtensionObject * pDiscoveryConfiguration, OpcUa_Channel_PfnRequestComplete * pCallback, OpcUa_Void * pCallbackData)
Definition at line 669 of file opcua_clientapi.c.
References _OpcUa_RegisterServer2Request::DiscoveryConfiguration, _OpcUa_RegisterServer2Request::NoOfDiscoveryConfiguration, OpcUa_RegisterServer2Request_EncodeableType, OpcUa_RegisterServer2Request_Initialize(), _OpcUa_RegisterServer2Request::RequestHeader, and _OpcUa_RegisterServer2Request::Server.
OpcUa_ClientApi_BeginRepublish()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginRepublish (OpcUa_Channel hChannel, const OpcUa_RequestHeader * pRequestHeader, OpcUa_UInt32 nSubscriptionId, OpcUa_UInt32 nRetransmitSequenceNumber, OpcUa_Channel_PfnRequestComplete * pCallback, OpcUa_Void * pCallbackData)
Definition at line 4836 of file opcua_clientapi.c.
References OpcUa_RepublishRequest_EncodeableType, OpcUa_RepublishRequest_Initialize(), _OpcUa_RepublishRequest::RequestHeader, _OpcUa_RepublishRequest::RetransmitSequenceNumber, and _OpcUa_RepublishRequest::SubscriptionId.
OpcUa_ClientApi_BeginSetMonitoringMode()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginSetMonitoringMode (OpcUa_Channel hChannel, const OpcUa_RequestHeader * pRequestHeader, OpcUa_UInt32 nSubscriptionId, OpcUa_MonitoringMode eMonitoringMode, OpcUa_Int32 nNoOfMonitoredItemIds, const OpcUa_UInt32 * pMonitoredItemIds, OpcUa_Channel_PfnRequestComplete * pCallback, OpcUa_Void * pCallbackData)
Definition at line 3818 of file opcua_clientapi.c.
References _OpcUa_SetMonitoringModeRequest::MonitoredItemIds, _OpcUa_SetMonitoringModeRequest::MonitoringMode, _OpcUa_SetMonitoringModeRequest::NoOfMonitoredItemIds, OpcUa_SetMonitoringModeRequest_EncodeableType, OpcUa_SetMonitoringModeRequest_Initialize(), _OpcUa_SetMonitoringModeRequest::RequestHeader, and _OpcUa_SetMonitoringModeRequest::SubscriptionId.
OpcUa_ClientApi_BeginSetPublishingMode()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginSetPublishingMode (OpcUa_Channel hChannel, const OpcUa_RequestHeader * pRequestHeader, OpcUa_Boolean bPublishingEnabled, OpcUa_Int32 nNoOfSubscriptionIds, const OpcUa_UInt32 * pSubscriptionIds, OpcUa_Channel_PfnRequestComplete * pCallback, OpcUa_Void * pCallbackData)
Definition at line 4566 of file opcua_clientapi.c.
References _OpcUa_SetPublishingModeRequest::NoOfSubscriptionIds, OpcUa_SetPublishingModeRequest_EncodeableType, OpcUa_SetPublishingModeRequest_Initialize(), _OpcUa_SetPublishingModeRequest::PublishingEnabled, _OpcUa_SetPublishingModeRequest::RequestHeader, and _OpcUa_SetPublishingModeRequest::SubscriptionIds.
OpcUa_ClientApi_BeginSetTriggering()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginSetTriggering (OpcUa_Channel hChannel, const OpcUa_RequestHeader * pRequestHeader, OpcUa_UInt32 nSubscriptionId, OpcUa_UInt32 nTriggeringItemId, OpcUa_Int32 nNoOfLinksToAdd, const OpcUa_UInt32 * pLinksToAdd, OpcUa_Int32 nNoOfLinksToRemove, const OpcUa_UInt32 * pLinksToRemove, OpcUa_Channel_PfnRequestComplete * pCallback, OpcUa_Void * pCallbackData)
Definition at line 3977 of file opcua_clientapi.c.
References _OpcUa_SetTriggeringRequest::LinksToAdd, _OpcUa_SetTriggeringRequest::LinksToRemove, _OpcUa_SetTriggeringRequest::NoOfLinksToAdd, _OpcUa_SetTriggeringRequest::NoOfLinksToRemove, OpcUa_SetTriggeringRequest_EncodeableType, OpcUa_SetTriggeringRequest_Initialize(), _OpcUa_SetTriggeringRequest::RequestHeader, _OpcUa_SetTriggeringRequest::SubscriptionId, and _OpcUa_SetTriggeringRequest::TriggeringItemId.
OpcUa_ClientApi_BeginTransferSubscriptions()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginTransferSubscriptions (OpcUa_Channel hChannel, const OpcUa_RequestHeader * pRequestHeader, OpcUa_Int32 nNoOfSubscriptionIds, const OpcUa_UInt32 * pSubscriptionIds, OpcUa_Boolean bSendInitialValues, OpcUa_Channel_PfnRequestComplete * pCallback, OpcUa_Void * pCallbackData)
Definition at line 4970 of file opcua_clientapi.c.
References _OpcUa_TransferSubscriptionsRequest::NoOfSubscriptionIds, OpcUa_TransferSubscriptionsRequest_EncodeableType, OpcUa_TransferSubscriptionsRequest_Initialize(), _OpcUa_TransferSubscriptionsRequest::RequestHeader, _OpcUa_TransferSubscriptionsRequest::SendInitialValues, and _OpcUa_TransferSubscriptionsRequest::SubscriptionIds.
OpcUa_ClientApi_BeginTranslateBrowsePathsToNodeIds()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginTranslateBrowsePathsToNodeIds (OpcUa_Channel hChannel, const OpcUa_RequestHeader * pRequestHeader, OpcUa_Int32 nNoOfBrowsePaths, const OpcUa_BrowsePath * pBrowsePaths, OpcUa_Channel_PfnRequestComplete * pCallback, OpcUa_Void * pCallbackData)
Definition at line 2181 of file opcua_clientapi.c.
References _OpcUa_TranslateBrowsePathsToNodeIdsRequest::BrowsePaths, _OpcUa_TranslateBrowsePathsToNodeIdsRequest::NoOfBrowsePaths, OpcUa_TranslateBrowsePathsToNodeIdsRequest_EncodeableType, OpcUa_TranslateBrowsePathsToNodeIdsRequest_Initialize(), and _OpcUa_TranslateBrowsePathsToNodeIdsRequest::RequestHeader.
OpcUa_ClientApi_BeginUnregisterNodes()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginUnregisterNodes (OpcUa_Channel hChannel, const OpcUa_RequestHeader * pRequestHeader, OpcUa_Int32 nNoOfNodesToUnregister, const OpcUa_NodeId * pNodesToUnregister, OpcUa_Channel_PfnRequestComplete * pCallback, OpcUa_Void * pCallbackData)
Definition at line 2423 of file opcua_clientapi.c.
References _OpcUa_UnregisterNodesRequest::NodesToUnregister, _OpcUa_UnregisterNodesRequest::NoOfNodesToUnregister, OpcUa_UnregisterNodesRequest_EncodeableType, OpcUa_UnregisterNodesRequest_Initialize(), and _OpcUa_UnregisterNodesRequest::RequestHeader.
OpcUa_ClientApi_BeginWrite()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginWrite (OpcUa_Channel hChannel, const OpcUa_RequestHeader * pRequestHeader, OpcUa_Int32 nNoOfNodesToWrite, const OpcUa_WriteValue * pNodesToWrite, OpcUa_Channel_PfnRequestComplete * pCallback, OpcUa_Void * pCallbackData)
Definition at line 3138 of file opcua_clientapi.c.
References _OpcUa_WriteRequest::NodesToWrite, _OpcUa_WriteRequest::NoOfNodesToWrite, OpcUa_WriteRequest_EncodeableType, OpcUa_WriteRequest_Initialize(), and _OpcUa_WriteRequest::RequestHeader.
OpcUa_ClientApi_Browse()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_Browse (OpcUa_Channel hChannel, const OpcUa_RequestHeader * pRequestHeader, const OpcUa_ViewDescription * pView, OpcUa_UInt32 nRequestedMaxReferencesPerNode, OpcUa_Int32 nNoOfNodesToBrowse, const OpcUa_BrowseDescription * pNodesToBrowse, OpcUa_ResponseHeader * pResponseHeader, OpcUa_Int32 * pNoOfResults, OpcUa_BrowseResult ** pResults, OpcUa_Int32 * pNoOfDiagnosticInfos, OpcUa_DiagnosticInfo ** pDiagnosticInfos)
Definition at line 1820 of file opcua_clientapi.c.
References _OpcUa_BrowseRequest::NodesToBrowse, _OpcUa_BrowseRequest::NoOfNodesToBrowse, OpcUa_BrowseRequest_EncodeableType, OpcUa_BrowseRequest_Initialize(), _OpcUa_BrowseRequest::RequestedMaxReferencesPerNode, _OpcUa_BrowseRequest::RequestHeader, and _OpcUa_BrowseRequest::View.
OpcUa_ClientApi_BrowseNext()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BrowseNext (OpcUa_Channel hChannel, const OpcUa_RequestHeader * pRequestHeader, OpcUa_Boolean bReleaseContinuationPoints, OpcUa_Int32 nNoOfContinuationPoints, const OpcUa_ByteString * pContinuationPoints, OpcUa_ResponseHeader * pResponseHeader, OpcUa_Int32 * pNoOfResults, OpcUa_BrowseResult ** pResults, OpcUa_Int32 * pNoOfDiagnosticInfos, OpcUa_DiagnosticInfo ** pDiagnosticInfos)
Definition at line 1962 of file opcua_clientapi.c.
References _OpcUa_BrowseNextRequest::ContinuationPoints, _OpcUa_BrowseNextRequest::NoOfContinuationPoints, OpcUa_BrowseNextRequest_EncodeableType, OpcUa_BrowseNextRequest_Initialize(), _OpcUa_BrowseNextRequest::ReleaseContinuationPoints, and _OpcUa_BrowseNextRequest::RequestHeader.
OpcUa_ClientApi_Call()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_Call (OpcUa_Channel hChannel, const OpcUa_RequestHeader * pRequestHeader, OpcUa_Int32 nNoOfMethodsToCall, const OpcUa_CallMethodRequest * pMethodsToCall, OpcUa_ResponseHeader * pResponseHeader, OpcUa_Int32 * pNoOfResults, OpcUa_CallMethodResult ** pResults, OpcUa_Int32 * pNoOfDiagnosticInfos, OpcUa_DiagnosticInfo ** pDiagnosticInfos)
Definition at line 3315 of file opcua_clientapi.c.
References _OpcUa_CallRequest::MethodsToCall, _OpcUa_CallRequest::NoOfMethodsToCall, OpcUa_CallRequest_EncodeableType, OpcUa_CallRequest_Initialize(), and _OpcUa_CallRequest::RequestHeader.
OpcUa_ClientApi_Cancel()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_Cancel (OpcUa_Channel hChannel, const OpcUa_RequestHeader * pRequestHeader, OpcUa_UInt32 nRequestHandle, OpcUa_ResponseHeader * pResponseHeader, OpcUa_UInt32 * pCancelCount)
Definition at line 1183 of file opcua_clientapi.c.
References OpcUa_CancelRequest_EncodeableType, OpcUa_CancelRequest_Initialize(), _OpcUa_CancelRequest::RequestHandle, and _OpcUa_CancelRequest::RequestHeader.
OpcUa_ClientApi_CloseSession()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_CloseSession (OpcUa_Channel hChannel, const OpcUa_RequestHeader * pRequestHeader, OpcUa_Boolean bDeleteSubscriptions, OpcUa_ResponseHeader * pResponseHeader)
Definition at line 1069 of file opcua_clientapi.c.
References _OpcUa_CloseSessionRequest::DeleteSubscriptions, OpcUa_CloseSessionRequest_EncodeableType, OpcUa_CloseSessionRequest_Initialize(), and _OpcUa_CloseSessionRequest::RequestHeader.
OpcUa_ClientApi_CreateMonitoredItems()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_CreateMonitoredItems (OpcUa_Channel hChannel, const OpcUa_RequestHeader * pRequestHeader, OpcUa_UInt32 nSubscriptionId, OpcUa_TimestampsToReturn eTimestampsToReturn, OpcUa_Int32 nNoOfItemsToCreate, const OpcUa_MonitoredItemCreateRequest * pItemsToCreate, OpcUa_ResponseHeader * pResponseHeader, OpcUa_Int32 * pNoOfResults, OpcUa_MonitoredItemCreateResult ** pResults, OpcUa_Int32 * pNoOfDiagnosticInfos, OpcUa_DiagnosticInfo ** pDiagnosticInfos)
Definition at line 3445 of file opcua_clientapi.c.
References _OpcUa_CreateMonitoredItemsRequest::ItemsToCreate, _OpcUa_CreateMonitoredItemsRequest::NoOfItemsToCreate, OpcUa_CreateMonitoredItemsRequest_EncodeableType, OpcUa_CreateMonitoredItemsRequest_Initialize(), _OpcUa_CreateMonitoredItemsRequest::RequestHeader, _OpcUa_CreateMonitoredItemsRequest::SubscriptionId, and _OpcUa_CreateMonitoredItemsRequest::TimestampsToReturn.
OpcUa_ClientApi_CreateSession()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_CreateSession (OpcUa_Channel hChannel, const OpcUa_RequestHeader * pRequestHeader, const OpcUa_ApplicationDescription * pClientDescription, const OpcUa_String * pServerUri, const OpcUa_String * pEndpointUrl, const OpcUa_String * pSessionName, const OpcUa_ByteString * pClientNonce, const OpcUa_ByteString * pClientCertificate, OpcUa_Double nRequestedSessionTimeout, OpcUa_UInt32 nMaxResponseMessageSize, OpcUa_ResponseHeader * pResponseHeader, OpcUa_NodeId * pSessionId, OpcUa_NodeId * pAuthenticationToken, OpcUa_Double * pRevisedSessionTimeout, OpcUa_ByteString * pServerNonce, OpcUa_ByteString * pServerCertificate, OpcUa_Int32 * pNoOfServerEndpoints, OpcUa_EndpointDescription ** pServerEndpoints, OpcUa_Int32 * pNoOfServerSoftwareCertificates, OpcUa_SignedSoftwareCertificate ** pServerSoftwareCertificates, OpcUa_SignatureData * pServerSignature, OpcUa_UInt32 * pMaxRequestMessageSize)
Definition at line 719 of file opcua_clientapi.c.
References _OpcUa_CreateSessionRequest::ClientCertificate, _OpcUa_CreateSessionRequest::ClientDescription, _OpcUa_CreateSessionRequest::ClientNonce, _OpcUa_CreateSessionRequest::EndpointUrl, _OpcUa_CreateSessionRequest::MaxResponseMessageSize, OpcUa_CreateSessionRequest_EncodeableType, OpcUa_CreateSessionRequest_Initialize(), _OpcUa_CreateSessionRequest::RequestedSessionTimeout, _OpcUa_CreateSessionRequest::RequestHeader, _OpcUa_CreateSessionRequest::ServerUri, and _OpcUa_CreateSessionRequest::SessionName.
OpcUa_ClientApi_CreateSubscription()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_CreateSubscription (OpcUa_Channel hChannel, const OpcUa_RequestHeader * pRequestHeader, OpcUa_Double nRequestedPublishingInterval, OpcUa_UInt32 nRequestedLifetimeCount, OpcUa_UInt32 nRequestedMaxKeepAliveCount, OpcUa_UInt32 nMaxNotificationsPerPublish, OpcUa_Boolean bPublishingEnabled, OpcUa_Byte nPriority, OpcUa_ResponseHeader * pResponseHeader, OpcUa_UInt32 * pSubscriptionId, OpcUa_Double * pRevisedPublishingInterval, OpcUa_UInt32 * pRevisedLifetimeCount, OpcUa_UInt32 * pRevisedMaxKeepAliveCount)
Definition at line 4171 of file opcua_clientapi.c.
References _OpcUa_CreateSubscriptionRequest::MaxNotificationsPerPublish, OpcUa_CreateSubscriptionRequest_EncodeableType, OpcUa_CreateSubscriptionRequest_Initialize(), _OpcUa_CreateSubscriptionRequest::Priority, _OpcUa_CreateSubscriptionRequest::PublishingEnabled, _OpcUa_CreateSubscriptionRequest::RequestedLifetimeCount, _OpcUa_CreateSubscriptionRequest::RequestedMaxKeepAliveCount, _OpcUa_CreateSubscriptionRequest::RequestedPublishingInterval, and _OpcUa_CreateSubscriptionRequest::RequestHeader.
OpcUa_ClientApi_DeleteMonitoredItems()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_DeleteMonitoredItems (OpcUa_Channel hChannel, const OpcUa_RequestHeader * pRequestHeader, OpcUa_UInt32 nSubscriptionId, OpcUa_Int32 nNoOfMonitoredItemIds, const OpcUa_UInt32 * pMonitoredItemIds, OpcUa_ResponseHeader * pResponseHeader, OpcUa_Int32 * pNoOfResults, OpcUa_StatusCode ** pResults, OpcUa_Int32 * pNoOfDiagnosticInfos, OpcUa_DiagnosticInfo ** pDiagnosticInfos)
Definition at line 4035 of file opcua_clientapi.c.
References _OpcUa_DeleteMonitoredItemsRequest::MonitoredItemIds, _OpcUa_DeleteMonitoredItemsRequest::NoOfMonitoredItemIds, OpcUa_DeleteMonitoredItemsRequest_EncodeableType, OpcUa_DeleteMonitoredItemsRequest_Initialize(), _OpcUa_DeleteMonitoredItemsRequest::RequestHeader, and _OpcUa_DeleteMonitoredItemsRequest::SubscriptionId.
OpcUa_ClientApi_DeleteNodes()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_DeleteNodes (OpcUa_Channel hChannel, const OpcUa_RequestHeader * pRequestHeader, OpcUa_Int32 nNoOfNodesToDelete, const OpcUa_DeleteNodesItem * pNodesToDelete, OpcUa_ResponseHeader * pResponseHeader, OpcUa_Int32 * pNoOfResults, OpcUa_StatusCode ** pResults, OpcUa_Int32 * pNoOfDiagnosticInfos, OpcUa_DiagnosticInfo ** pDiagnosticInfos)
Definition at line 1560 of file opcua_clientapi.c.
References _OpcUa_DeleteNodesRequest::NodesToDelete, _OpcUa_DeleteNodesRequest::NoOfNodesToDelete, OpcUa_DeleteNodesRequest_EncodeableType, OpcUa_DeleteNodesRequest_Initialize(), and _OpcUa_DeleteNodesRequest::RequestHeader.
OpcUa_ClientApi_DeleteReferences()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_DeleteReferences (OpcUa_Channel hChannel, const OpcUa_RequestHeader * pRequestHeader, OpcUa_Int32 nNoOfReferencesToDelete, const OpcUa_DeleteReferencesItem * pReferencesToDelete, OpcUa_ResponseHeader * pResponseHeader, OpcUa_Int32 * pNoOfResults, OpcUa_StatusCode ** pResults, OpcUa_Int32 * pNoOfDiagnosticInfos, OpcUa_DiagnosticInfo ** pDiagnosticInfos)
Definition at line 1690 of file opcua_clientapi.c.
References _OpcUa_DeleteReferencesRequest::NoOfReferencesToDelete, OpcUa_DeleteReferencesRequest_EncodeableType, OpcUa_DeleteReferencesRequest_Initialize(), _OpcUa_DeleteReferencesRequest::ReferencesToDelete, and _OpcUa_DeleteReferencesRequest::RequestHeader.
OpcUa_ClientApi_DeleteSubscriptions()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_DeleteSubscriptions (OpcUa_Channel hChannel, const OpcUa_RequestHeader * pRequestHeader, OpcUa_Int32 nNoOfSubscriptionIds, const OpcUa_UInt32 * pSubscriptionIds, OpcUa_ResponseHeader * pResponseHeader, OpcUa_Int32 * pNoOfResults, OpcUa_StatusCode ** pResults, OpcUa_Int32 * pNoOfDiagnosticInfos, OpcUa_DiagnosticInfo ** pDiagnosticInfos)
Definition at line 5020 of file opcua_clientapi.c.
References _OpcUa_DeleteSubscriptionsRequest::NoOfSubscriptionIds, OpcUa_DeleteSubscriptionsRequest_EncodeableType, OpcUa_DeleteSubscriptionsRequest_Initialize(), _OpcUa_DeleteSubscriptionsRequest::RequestHeader, and _OpcUa_DeleteSubscriptionsRequest::SubscriptionIds.
OpcUa_ClientApi_FindServers()
OPCUA_BEGIN_EXTERN_C OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_FindServers (OpcUa_Channel hChannel, const OpcUa_RequestHeader * pRequestHeader, const OpcUa_String * pEndpointUrl, OpcUa_Int32 nNoOfLocaleIds, const OpcUa_String * pLocaleIds, OpcUa_Int32 nNoOfServerUris, const OpcUa_String * pServerUris, OpcUa_ResponseHeader * pResponseHeader, OpcUa_Int32 * pNoOfServers, OpcUa_ApplicationDescription ** pServers)
Definition at line 50 of file opcua_clientapi.c.
References _OpcUa_FindServersRequest::EndpointUrl, _OpcUa_FindServersRequest::LocaleIds, _OpcUa_FindServersRequest::NoOfLocaleIds, _OpcUa_FindServersRequest::NoOfServerUris, OpcUa_FindServersRequest_EncodeableType, OpcUa_FindServersRequest_Initialize(), _OpcUa_FindServersRequest::RequestHeader, and _OpcUa_FindServersRequest::ServerUris.
OpcUa_ClientApi_FindServersOnNetwork()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_FindServersOnNetwork (OpcUa_Channel hChannel, const OpcUa_RequestHeader * pRequestHeader, OpcUa_UInt32 nStartingRecordId, OpcUa_UInt32 nMaxRecordsToReturn, OpcUa_Int32 nNoOfServerCapabilityFilter, const OpcUa_String * pServerCapabilityFilter, OpcUa_ResponseHeader * pResponseHeader, OpcUa_DateTime * pLastCounterResetTime, OpcUa_Int32 * pNoOfServers, OpcUa_ServerOnNetwork ** pServers)
Definition at line 190 of file opcua_clientapi.c.
References _OpcUa_FindServersOnNetworkRequest::MaxRecordsToReturn, _OpcUa_FindServersOnNetworkRequest::NoOfServerCapabilityFilter, OpcUa_FindServersOnNetworkRequest_EncodeableType, OpcUa_FindServersOnNetworkRequest_Initialize(), _OpcUa_FindServersOnNetworkRequest::RequestHeader, _OpcUa_FindServersOnNetworkRequest::ServerCapabilityFilter, and _OpcUa_FindServersOnNetworkRequest::StartingRecordId.
OpcUa_ClientApi_GetEndpoints()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_GetEndpoints (OpcUa_Channel hChannel, const OpcUa_RequestHeader * pRequestHeader, const OpcUa_String * pEndpointUrl, OpcUa_Int32 nNoOfLocaleIds, const OpcUa_String * pLocaleIds, OpcUa_Int32 nNoOfProfileUris, const OpcUa_String * pProfileUris, OpcUa_ResponseHeader * pResponseHeader, OpcUa_Int32 * pNoOfEndpoints, OpcUa_EndpointDescription ** pEndpoints)
Definition at line 329 of file opcua_clientapi.c.
References _OpcUa_GetEndpointsRequest::EndpointUrl, _OpcUa_GetEndpointsRequest::LocaleIds, _OpcUa_GetEndpointsRequest::NoOfLocaleIds, _OpcUa_GetEndpointsRequest::NoOfProfileUris, OpcUa_GetEndpointsRequest_EncodeableType, OpcUa_GetEndpointsRequest_Initialize(), _OpcUa_GetEndpointsRequest::ProfileUris, and _OpcUa_GetEndpointsRequest::RequestHeader.
OpcUa_ClientApi_HistoryRead()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_HistoryRead (OpcUa_Channel hChannel, const OpcUa_RequestHeader * pRequestHeader, const OpcUa_ExtensionObject * pHistoryReadDetails, OpcUa_TimestampsToReturn eTimestampsToReturn, OpcUa_Boolean bReleaseContinuationPoints, OpcUa_Int32 nNoOfNodesToRead, const OpcUa_HistoryReadValueId * pNodesToRead, OpcUa_ResponseHeader * pResponseHeader, OpcUa_Int32 * pNoOfResults, OpcUa_HistoryReadResult ** pResults, OpcUa_Int32 * pNoOfDiagnosticInfos, OpcUa_DiagnosticInfo ** pDiagnosticInfos)
Definition at line 2907 of file opcua_clientapi.c.
References _OpcUa_HistoryReadRequest::HistoryReadDetails, _OpcUa_HistoryReadRequest::NodesToRead, _OpcUa_HistoryReadRequest::NoOfNodesToRead, OpcUa_HistoryReadRequest_EncodeableType, OpcUa_HistoryReadRequest_Initialize(), _OpcUa_HistoryReadRequest::ReleaseContinuationPoints, _OpcUa_HistoryReadRequest::RequestHeader, and _OpcUa_HistoryReadRequest::TimestampsToReturn.
OpcUa_ClientApi_HistoryUpdate()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_HistoryUpdate (OpcUa_Channel hChannel, const OpcUa_RequestHeader * pRequestHeader, OpcUa_Int32 nNoOfHistoryUpdateDetails, const OpcUa_ExtensionObject * pHistoryUpdateDetails, OpcUa_ResponseHeader * pResponseHeader, OpcUa_Int32 * pNoOfResults, OpcUa_HistoryUpdateResult ** pResults, OpcUa_Int32 * pNoOfDiagnosticInfos, OpcUa_DiagnosticInfo ** pDiagnosticInfos)
Definition at line 3185 of file opcua_clientapi.c.
References _OpcUa_HistoryUpdateRequest::HistoryUpdateDetails, _OpcUa_HistoryUpdateResult::NoOfDiagnosticInfos, _OpcUa_HistoryUpdateRequest::NoOfHistoryUpdateDetails, OpcUa_HistoryUpdateRequest_EncodeableType, OpcUa_HistoryUpdateRequest_Initialize(), and _OpcUa_HistoryUpdateRequest::RequestHeader.
OpcUa_ClientApi_ModifyMonitoredItems()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_ModifyMonitoredItems (OpcUa_Channel hChannel, const OpcUa_RequestHeader * pRequestHeader, OpcUa_UInt32 nSubscriptionId, OpcUa_TimestampsToReturn eTimestampsToReturn, OpcUa_Int32 nNoOfItemsToModify, const OpcUa_MonitoredItemModifyRequest * pItemsToModify, OpcUa_ResponseHeader * pResponseHeader, OpcUa_Int32 * pNoOfResults, OpcUa_MonitoredItemModifyResult ** pResults, OpcUa_Int32 * pNoOfDiagnosticInfos, OpcUa_DiagnosticInfo ** pDiagnosticInfos)
Definition at line 3587 of file opcua_clientapi.c.
References _OpcUa_ModifyMonitoredItemsRequest::ItemsToModify, _OpcUa_ModifyMonitoredItemsRequest::NoOfItemsToModify, OpcUa_ModifyMonitoredItemsRequest_EncodeableType, OpcUa_ModifyMonitoredItemsRequest_Initialize(), _OpcUa_ModifyMonitoredItemsRequest::RequestHeader, _OpcUa_ModifyMonitoredItemsRequest::SubscriptionId, and _OpcUa_ModifyMonitoredItemsRequest::TimestampsToReturn.
OpcUa_ClientApi_ModifySubscription()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_ModifySubscription (OpcUa_Channel hChannel, const OpcUa_RequestHeader * pRequestHeader, OpcUa_UInt32 nSubscriptionId, OpcUa_Double nRequestedPublishingInterval, OpcUa_UInt32 nRequestedLifetimeCount, OpcUa_UInt32 nRequestedMaxKeepAliveCount, OpcUa_UInt32 nMaxNotificationsPerPublish, OpcUa_Byte nPriority, OpcUa_ResponseHeader * pResponseHeader, OpcUa_Double * pRevisedPublishingInterval, OpcUa_UInt32 * pRevisedLifetimeCount, OpcUa_UInt32 * pRevisedMaxKeepAliveCount)
Definition at line 4327 of file opcua_clientapi.c.
References _OpcUa_ModifySubscriptionRequest::MaxNotificationsPerPublish, OpcUa_ModifySubscriptionRequest_EncodeableType, OpcUa_ModifySubscriptionRequest_Initialize(), _OpcUa_ModifySubscriptionRequest::Priority, _OpcUa_ModifySubscriptionRequest::RequestedLifetimeCount, _OpcUa_ModifySubscriptionRequest::RequestedMaxKeepAliveCount, _OpcUa_ModifySubscriptionRequest::RequestedPublishingInterval, _OpcUa_ModifySubscriptionRequest::RequestHeader, and _OpcUa_ModifySubscriptionRequest::SubscriptionId.
OpcUa_ClientApi_Publish()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_Publish (OpcUa_Channel hChannel, const OpcUa_RequestHeader * pRequestHeader, OpcUa_Int32 nNoOfSubscriptionAcknowledgements, const OpcUa_SubscriptionAcknowledgement * pSubscriptionAcknowledgements, OpcUa_ResponseHeader * pResponseHeader, OpcUa_UInt32 * pSubscriptionId, OpcUa_Int32 * pNoOfAvailableSequenceNumbers, OpcUa_UInt32 ** pAvailableSequenceNumbers, OpcUa_Boolean * pMoreNotifications, OpcUa_NotificationMessage * pNotificationMessage, OpcUa_Int32 * pNoOfResults, OpcUa_StatusCode ** pResults, OpcUa_Int32 * pNoOfDiagnosticInfos, OpcUa_DiagnosticInfo ** pDiagnosticInfos)
Definition at line 4616 of file opcua_clientapi.c.
References _OpcUa_PublishRequest::NoOfSubscriptionAcknowledgements, OpcUa_PublishRequest_EncodeableType, OpcUa_PublishRequest_Initialize(), _OpcUa_PublishRequest::RequestHeader, and _OpcUa_PublishRequest::SubscriptionAcknowledgements.
OpcUa_ClientApi_QueryFirst()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_QueryFirst (OpcUa_Channel hChannel, const OpcUa_RequestHeader * pRequestHeader, const OpcUa_ViewDescription * pView, OpcUa_Int32 nNoOfNodeTypes, const OpcUa_NodeTypeDescription * pNodeTypes, const OpcUa_ContentFilter * pFilter, OpcUa_UInt32 nMaxDataSetsToReturn, OpcUa_UInt32 nMaxReferencesToReturn, OpcUa_ResponseHeader * pResponseHeader, OpcUa_Int32 * pNoOfQueryDataSets, OpcUa_QueryDataSet ** pQueryDataSets, OpcUa_ByteString * pContinuationPoint, OpcUa_Int32 * pNoOfParsingResults, OpcUa_ParsingResult ** pParsingResults, OpcUa_Int32 * pNoOfDiagnosticInfos, OpcUa_DiagnosticInfo ** pDiagnosticInfos, OpcUa_ContentFilterResult * pFilterResult)
Definition at line 2470 of file opcua_clientapi.c.
References _OpcUa_QueryFirstRequest::Filter, _OpcUa_QueryFirstRequest::MaxDataSetsToReturn, _OpcUa_QueryFirstRequest::MaxReferencesToReturn, _OpcUa_QueryFirstRequest::NodeTypes, _OpcUa_QueryFirstRequest::NoOfNodeTypes, OpcUa_QueryFirstRequest_EncodeableType, OpcUa_QueryFirstRequest_Initialize(), _OpcUa_QueryFirstRequest::RequestHeader, and _OpcUa_QueryFirstRequest::View.
OpcUa_ClientApi_QueryNext()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_QueryNext (OpcUa_Channel hChannel, const OpcUa_RequestHeader * pRequestHeader, OpcUa_Boolean bReleaseContinuationPoint, const OpcUa_ByteString * pContinuationPoint, OpcUa_ResponseHeader * pResponseHeader, OpcUa_Int32 * pNoOfQueryDataSets, OpcUa_QueryDataSet ** pQueryDataSets, OpcUa_ByteString * pRevisedContinuationPoint)
Definition at line 2636 of file opcua_clientapi.c.
References _OpcUa_QueryNextRequest::ContinuationPoint, OpcUa_QueryNextRequest_EncodeableType, OpcUa_QueryNextRequest_Initialize(), _OpcUa_QueryNextRequest::ReleaseContinuationPoint, and _OpcUa_QueryNextRequest::RequestHeader.
OpcUa_ClientApi_Read()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_Read (OpcUa_Channel hChannel, const OpcUa_RequestHeader * pRequestHeader, OpcUa_Double nMaxAge, OpcUa_TimestampsToReturn eTimestampsToReturn, OpcUa_Int32 nNoOfNodesToRead, const OpcUa_ReadValueId * pNodesToRead, OpcUa_ResponseHeader * pResponseHeader, OpcUa_Int32 * pNoOfResults, OpcUa_DataValue ** pResults, OpcUa_Int32 * pNoOfDiagnosticInfos, OpcUa_DiagnosticInfo ** pDiagnosticInfos)
Definition at line 2765 of file opcua_clientapi.c.
References _OpcUa_ReadRequest::MaxAge, _OpcUa_ReadRequest::NodesToRead, _OpcUa_ReadRequest::NoOfNodesToRead, OpcUa_ReadRequest_EncodeableType, OpcUa_ReadRequest_Initialize(), _OpcUa_ReadRequest::RequestHeader, and _OpcUa_ReadRequest::TimestampsToReturn.
OpcUa_ClientApi_RegisterNodes()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_RegisterNodes (OpcUa_Channel hChannel, const OpcUa_RequestHeader * pRequestHeader, OpcUa_Int32 nNoOfNodesToRegister, const OpcUa_NodeId * pNodesToRegister, OpcUa_ResponseHeader * pResponseHeader, OpcUa_Int32 * pNoOfRegisteredNodeIds, OpcUa_NodeId ** pRegisteredNodeIds)
Definition at line 2228 of file opcua_clientapi.c.
References _OpcUa_RegisterNodesRequest::NodesToRegister, _OpcUa_RegisterNodesRequest::NoOfNodesToRegister, OpcUa_RegisterNodesRequest_EncodeableType, OpcUa_RegisterNodesRequest_Initialize(), and _OpcUa_RegisterNodesRequest::RequestHeader.
OpcUa_ClientApi_RegisterServer()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_RegisterServer (OpcUa_Channel hChannel, const OpcUa_RequestHeader * pRequestHeader, const OpcUa_RegisteredServer * pServer, OpcUa_ResponseHeader * pResponseHeader)
Definition at line 469 of file opcua_clientapi.c.
References OpcUa_RegisterServerRequest_EncodeableType, OpcUa_RegisterServerRequest_Initialize(), _OpcUa_RegisterServerRequest::RequestHeader, and _OpcUa_RegisterServerRequest::Server.
OpcUa_ClientApi_RegisterServer2()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_RegisterServer2 (OpcUa_Channel hChannel, const OpcUa_RequestHeader * pRequestHeader, const OpcUa_RegisteredServer * pServer, OpcUa_Int32 nNoOfDiscoveryConfiguration, const OpcUa_ExtensionObject * pDiscoveryConfiguration, OpcUa_ResponseHeader * pResponseHeader, OpcUa_Int32 * pNoOfConfigurationResults, OpcUa_StatusCode ** pConfigurationResults, OpcUa_Int32 * pNoOfDiagnosticInfos, OpcUa_DiagnosticInfo ** pDiagnosticInfos)
Definition at line 583 of file opcua_clientapi.c.
References _OpcUa_RegisterServer2Request::DiscoveryConfiguration, _OpcUa_RegisterServer2Request::NoOfDiscoveryConfiguration, OpcUa_RegisterServer2Request_EncodeableType, OpcUa_RegisterServer2Request_Initialize(), _OpcUa_RegisterServer2Request::RequestHeader, and _OpcUa_RegisterServer2Request::Server.
OpcUa_ClientApi_Republish()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_Republish (OpcUa_Channel hChannel, const OpcUa_RequestHeader * pRequestHeader, OpcUa_UInt32 nSubscriptionId, OpcUa_UInt32 nRetransmitSequenceNumber, OpcUa_ResponseHeader * pResponseHeader, OpcUa_NotificationMessage * pNotificationMessage)
Definition at line 4761 of file opcua_clientapi.c.
References OpcUa_RepublishRequest_EncodeableType, OpcUa_RepublishRequest_Initialize(), _OpcUa_RepublishRequest::RequestHeader, _OpcUa_RepublishRequest::RetransmitSequenceNumber, and _OpcUa_RepublishRequest::SubscriptionId.
OpcUa_ClientApi_SetMonitoringMode()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_SetMonitoringMode (OpcUa_Channel hChannel, const OpcUa_RequestHeader * pRequestHeader, OpcUa_UInt32 nSubscriptionId, OpcUa_MonitoringMode eMonitoringMode, OpcUa_Int32 nNoOfMonitoredItemIds, const OpcUa_UInt32 * pMonitoredItemIds, OpcUa_ResponseHeader * pResponseHeader, OpcUa_Int32 * pNoOfResults, OpcUa_StatusCode ** pResults, OpcUa_Int32 * pNoOfDiagnosticInfos, OpcUa_DiagnosticInfo ** pDiagnosticInfos)
Definition at line 3729 of file opcua_clientapi.c.
References _OpcUa_SetMonitoringModeRequest::MonitoredItemIds, _OpcUa_SetMonitoringModeRequest::MonitoringMode, _OpcUa_SetMonitoringModeRequest::NoOfMonitoredItemIds, OpcUa_SetMonitoringModeRequest_EncodeableType, OpcUa_SetMonitoringModeRequest_Initialize(), _OpcUa_SetMonitoringModeRequest::RequestHeader, and _OpcUa_SetMonitoringModeRequest::SubscriptionId.
OpcUa_ClientApi_SetPublishingMode()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_SetPublishingMode (OpcUa_Channel hChannel, const OpcUa_RequestHeader * pRequestHeader, OpcUa_Boolean bPublishingEnabled, OpcUa_Int32 nNoOfSubscriptionIds, const OpcUa_UInt32 * pSubscriptionIds, OpcUa_ResponseHeader * pResponseHeader, OpcUa_Int32 * pNoOfResults, OpcUa_StatusCode ** pResults, OpcUa_Int32 * pNoOfDiagnosticInfos, OpcUa_DiagnosticInfo ** pDiagnosticInfos)
Definition at line 4480 of file opcua_clientapi.c.
References _OpcUa_SetPublishingModeRequest::NoOfSubscriptionIds, OpcUa_SetPublishingModeRequest_EncodeableType, OpcUa_SetPublishingModeRequest_Initialize(), _OpcUa_SetPublishingModeRequest::PublishingEnabled, _OpcUa_SetPublishingModeRequest::RequestHeader, and _OpcUa_SetPublishingModeRequest::SubscriptionIds.
OpcUa_ClientApi_SetTriggering()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_SetTriggering (OpcUa_Channel hChannel, const OpcUa_RequestHeader * pRequestHeader, OpcUa_UInt32 nSubscriptionId, OpcUa_UInt32 nTriggeringItemId, OpcUa_Int32 nNoOfLinksToAdd, const OpcUa_UInt32 * pLinksToAdd, OpcUa_Int32 nNoOfLinksToRemove, const OpcUa_UInt32 * pLinksToRemove, OpcUa_ResponseHeader * pResponseHeader, OpcUa_Int32 * pNoOfAddResults, OpcUa_StatusCode ** pAddResults, OpcUa_Int32 * pNoOfAddDiagnosticInfos, OpcUa_DiagnosticInfo ** pAddDiagnosticInfos, OpcUa_Int32 * pNoOfRemoveResults, OpcUa_StatusCode ** pRemoveResults, OpcUa_Int32 * pNoOfRemoveDiagnosticInfos, OpcUa_DiagnosticInfo ** pRemoveDiagnosticInfos)
Definition at line 3871 of file opcua_clientapi.c.
References _OpcUa_SetTriggeringRequest::LinksToAdd, _OpcUa_SetTriggeringRequest::LinksToRemove, _OpcUa_SetTriggeringRequest::NoOfLinksToAdd, _OpcUa_SetTriggeringRequest::NoOfLinksToRemove, OpcUa_SetTriggeringRequest_EncodeableType, OpcUa_SetTriggeringRequest_Initialize(), _OpcUa_SetTriggeringRequest::RequestHeader, _OpcUa_SetTriggeringRequest::SubscriptionId, and _OpcUa_SetTriggeringRequest::TriggeringItemId.
OpcUa_ClientApi_TransferSubscriptions()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_TransferSubscriptions (OpcUa_Channel hChannel, const OpcUa_RequestHeader * pRequestHeader, OpcUa_Int32 nNoOfSubscriptionIds, const OpcUa_UInt32 * pSubscriptionIds, OpcUa_Boolean bSendInitialValues, OpcUa_ResponseHeader * pResponseHeader, OpcUa_Int32 * pNoOfResults, OpcUa_TransferResult ** pResults, OpcUa_Int32 * pNoOfDiagnosticInfos, OpcUa_DiagnosticInfo ** pDiagnosticInfos)
Definition at line 4884 of file opcua_clientapi.c.
References _OpcUa_TransferSubscriptionsRequest::NoOfSubscriptionIds, OpcUa_TransferSubscriptionsRequest_EncodeableType, OpcUa_TransferSubscriptionsRequest_Initialize(), _OpcUa_TransferSubscriptionsRequest::RequestHeader, _OpcUa_TransferSubscriptionsRequest::SendInitialValues, and _OpcUa_TransferSubscriptionsRequest::SubscriptionIds.
OpcUa_ClientApi_TranslateBrowsePathsToNodeIds()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_TranslateBrowsePathsToNodeIds (OpcUa_Channel hChannel, const OpcUa_RequestHeader * pRequestHeader, OpcUa_Int32 nNoOfBrowsePaths, const OpcUa_BrowsePath * pBrowsePaths, OpcUa_ResponseHeader * pResponseHeader, OpcUa_Int32 * pNoOfResults, OpcUa_BrowsePathResult ** pResults, OpcUa_Int32 * pNoOfDiagnosticInfos, OpcUa_DiagnosticInfo ** pDiagnosticInfos)
Definition at line 2098 of file opcua_clientapi.c.
References _OpcUa_TranslateBrowsePathsToNodeIdsRequest::BrowsePaths, _OpcUa_TranslateBrowsePathsToNodeIdsRequest::NoOfBrowsePaths, OpcUa_TranslateBrowsePathsToNodeIdsRequest_EncodeableType, OpcUa_TranslateBrowsePathsToNodeIdsRequest_Initialize(), and _OpcUa_TranslateBrowsePathsToNodeIdsRequest::RequestHeader.
OpcUa_ClientApi_UnregisterNodes()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_UnregisterNodes (OpcUa_Channel hChannel, const OpcUa_RequestHeader * pRequestHeader, OpcUa_Int32 nNoOfNodesToUnregister, const OpcUa_NodeId * pNodesToUnregister, OpcUa_ResponseHeader * pResponseHeader)
Definition at line 2352 of file opcua_clientapi.c.
References _OpcUa_UnregisterNodesRequest::NodesToUnregister, _OpcUa_UnregisterNodesRequest::NoOfNodesToUnregister, OpcUa_UnregisterNodesRequest_EncodeableType, OpcUa_UnregisterNodesRequest_Initialize(), and _OpcUa_UnregisterNodesRequest::RequestHeader.
OpcUa_ClientApi_Write()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_Write (OpcUa_Channel hChannel, const OpcUa_RequestHeader * pRequestHeader, OpcUa_Int32 nNoOfNodesToWrite, const OpcUa_WriteValue * pNodesToWrite, OpcUa_ResponseHeader * pResponseHeader, OpcUa_Int32 * pNoOfResults, OpcUa_StatusCode ** pResults, OpcUa_Int32 * pNoOfDiagnosticInfos, OpcUa_DiagnosticInfo ** pDiagnosticInfos)
Definition at line 3055 of file opcua_clientapi.c.
References _OpcUa_WriteRequest::NodesToWrite, _OpcUa_WriteRequest::NoOfNodesToWrite, OpcUa_WriteRequest_EncodeableType, OpcUa_WriteRequest_Initialize(), and _OpcUa_WriteRequest::RequestHeader.