Project Template: Opc.Ua.ProgramDiagnostic2DataType Class Reference
Opc.Ua.ProgramDiagnostic2DataType Class Reference
Public Member Functions
ProgramDiagnostic2DataType ()
The default constructor.
virtual void Encode (IEncoder encoder)
virtual void Decode (IDecoder decoder)
virtual bool IsEqual (IEncodeable encodeable)
virtual object Clone ()
new object MemberwiseClone ()
Properties
NodeId CreateSessionId [get, set]
string CreateClientName [get, set]
DateTime InvocationCreationTime [get, set]
DateTime LastTransitionTime [get, set]
string LastMethodCall [get, set]
NodeId LastMethodSessionId [get, set]
ArgumentCollection LastMethodInputArguments [get, set]
ArgumentCollection LastMethodOutputArguments [get, set]
VariantCollection LastMethodInputValues [get, set]
VariantCollection LastMethodOutputValues [get, set]
DateTime LastMethodCallTime [get, set]
StatusResult LastMethodReturnStatus [get, set]
virtual ExpandedNodeId TypeId [get]
virtual ExpandedNodeId BinaryEncodingId [get]
virtual ExpandedNodeId XmlEncodingId [get]
Detailed Description
<exclude>
Definition at line 67406 of file Opc.Ua.DataTypes.cs.
Constructor & Destructor Documentation
ProgramDiagnostic2DataType()
Opc.Ua.ProgramDiagnostic2DataType.ProgramDiagnostic2DataType () inline
The default constructor.
Definition at line 67412 of file Opc.Ua.DataTypes.cs.
Member Function Documentation
Clone()
virtual object Opc.Ua.ProgramDiagnostic2DataType.Clone () inline virtual
Definition at line 67708 of file Opc.Ua.DataTypes.cs.
Decode()
virtual void Opc.Ua.ProgramDiagnostic2DataType.Decode (IDecoder decoder) inline virtual
Definition at line 67655 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
Encode()
virtual void Opc.Ua.ProgramDiagnostic2DataType.Encode (IEncoder encoder) inline virtual
Definition at line 67634 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
IsEqual()
virtual bool Opc.Ua.ProgramDiagnostic2DataType.IsEqual (IEncodeable encodeable) inline virtual
Definition at line 67676 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Object.
MemberwiseClone()
new object Opc.Ua.ProgramDiagnostic2DataType.MemberwiseClone () inline
Definition at line 67715 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.ArgumentCollection.Clone(), Opc.Ua.StatusResult.Clone(), Opc.Ua.ProgramDiagnostic2DataType.MemberwiseClone(), Opc.Ua.NodeId, and Opc.Ua.Namespaces.OpcUaXsd.
Referenced by Opc.Ua.ProgramDiagnostic2DataType.MemberwiseClone().
Property Documentation
BinaryEncodingId
virtual ExpandedNodeId Opc.Ua.ProgramDiagnostic2DataType.BinaryEncodingId get
Definition at line 67623 of file Opc.Ua.DataTypes.cs.
CreateClientName
string Opc.Ua.ProgramDiagnostic2DataType.CreateClientName get set
Definition at line 67458 of file Opc.Ua.DataTypes.cs.
CreateSessionId
NodeId Opc.Ua.ProgramDiagnostic2DataType.CreateSessionId get set
Definition at line 67450 of file Opc.Ua.DataTypes.cs.
InvocationCreationTime
DateTime Opc.Ua.ProgramDiagnostic2DataType.InvocationCreationTime get set
Definition at line 67466 of file Opc.Ua.DataTypes.cs.
LastMethodCall
string Opc.Ua.ProgramDiagnostic2DataType.LastMethodCall get set
Definition at line 67482 of file Opc.Ua.DataTypes.cs.
LastMethodCallTime
DateTime Opc.Ua.ProgramDiagnostic2DataType.LastMethodCallTime get set
Definition at line 67586 of file Opc.Ua.DataTypes.cs.
LastMethodInputArguments
ArgumentCollection Opc.Ua.ProgramDiagnostic2DataType.LastMethodInputArguments get set
Definition at line 67500 of file Opc.Ua.DataTypes.cs.
LastMethodInputValues
VariantCollection Opc.Ua.ProgramDiagnostic2DataType.LastMethodInputValues get set
Definition at line 67544 of file Opc.Ua.DataTypes.cs.
LastMethodOutputArguments
ArgumentCollection Opc.Ua.ProgramDiagnostic2DataType.LastMethodOutputArguments get set
Definition at line 67522 of file Opc.Ua.DataTypes.cs.
LastMethodOutputValues
VariantCollection Opc.Ua.ProgramDiagnostic2DataType.LastMethodOutputValues get set
Definition at line 67566 of file Opc.Ua.DataTypes.cs.
LastMethodReturnStatus
StatusResult Opc.Ua.ProgramDiagnostic2DataType.LastMethodReturnStatus get set
Definition at line 67596 of file Opc.Ua.DataTypes.cs.
LastMethodSessionId
NodeId Opc.Ua.ProgramDiagnostic2DataType.LastMethodSessionId get set
Definition at line 67490 of file Opc.Ua.DataTypes.cs.
LastTransitionTime
DateTime Opc.Ua.ProgramDiagnostic2DataType.LastTransitionTime get set
Definition at line 67474 of file Opc.Ua.DataTypes.cs.
TypeId
virtual ExpandedNodeId Opc.Ua.ProgramDiagnostic2DataType.TypeId get
Definition at line 67617 of file Opc.Ua.DataTypes.cs.
XmlEncodingId
virtual ExpandedNodeId Opc.Ua.ProgramDiagnostic2DataType.XmlEncodingId get
Definition at line 67629 of file Opc.Ua.DataTypes.cs.
The documentation for this class was generated from the following file:
Opc.Ua.DataTypes.cs