Project Template: Opc.Ua.PubSubGroupDataType Class Reference
Opc.Ua.PubSubGroupDataType Class Reference
Public Member Functions
PubSubGroupDataType ()
The default constructor.
virtual void Encode (IEncoder encoder)
virtual void Decode (IDecoder decoder)
virtual bool IsEqual (IEncodeable encodeable)
virtual object Clone ()
new object MemberwiseClone ()
Properties
string Name [get, set]
bool Enabled [get, set]
MessageSecurityMode SecurityMode [get, set]
string SecurityGroupId [get, set]
EndpointDescriptionCollection SecurityKeyServices [get, set]
uint MaxNetworkMessageSize [get, set]
KeyValuePairCollection GroupProperties [get, set]
virtual ExpandedNodeId TypeId [get]
virtual ExpandedNodeId BinaryEncodingId [get]
virtual ExpandedNodeId XmlEncodingId [get]
Detailed Description
<exclude>
Definition at line 8599 of file Opc.Ua.DataTypes.cs.
Constructor & Destructor Documentation
PubSubGroupDataType()
Opc.Ua.PubSubGroupDataType.PubSubGroupDataType () inline
The default constructor.
Definition at line 8605 of file Opc.Ua.DataTypes.cs.
Member Function Documentation
Clone()
virtual object Opc.Ua.PubSubGroupDataType.Clone () inline virtual
Reimplemented in Opc.Ua.ReaderGroupDataType, and Opc.Ua.WriterGroupDataType.
Definition at line 8799 of file Opc.Ua.DataTypes.cs.
Decode()
virtual void Opc.Ua.PubSubGroupDataType.Decode (IDecoder decoder) inline virtual
Reimplemented in Opc.Ua.ReaderGroupDataType, and Opc.Ua.WriterGroupDataType.
Definition at line 8756 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
Encode()
virtual void Opc.Ua.PubSubGroupDataType.Encode (IEncoder encoder) inline virtual
Reimplemented in Opc.Ua.ReaderGroupDataType, and Opc.Ua.WriterGroupDataType.
Definition at line 8740 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
IsEqual()
virtual bool Opc.Ua.PubSubGroupDataType.IsEqual (IEncodeable encodeable) inline virtual
Reimplemented in Opc.Ua.ReaderGroupDataType, and Opc.Ua.WriterGroupDataType.
Definition at line 8772 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Object.
MemberwiseClone()
new object Opc.Ua.PubSubGroupDataType.MemberwiseClone () inline
Definition at line 8806 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.KeyValuePairCollection.Clone(), Opc.Ua.EndpointDescriptionCollection.Clone(), Opc.Ua.PubSubGroupDataType.MemberwiseClone(), and Opc.Ua.Namespaces.OpcUaXsd.
Referenced by Opc.Ua.PubSubGroupDataType.MemberwiseClone().
Property Documentation
BinaryEncodingId
virtual ExpandedNodeId Opc.Ua.PubSubGroupDataType.BinaryEncodingId get
Definition at line 8729 of file Opc.Ua.DataTypes.cs.
Enabled
bool Opc.Ua.PubSubGroupDataType.Enabled get set
Definition at line 8646 of file Opc.Ua.DataTypes.cs.
GroupProperties
KeyValuePairCollection Opc.Ua.PubSubGroupDataType.GroupProperties get set
Definition at line 8702 of file Opc.Ua.DataTypes.cs.
MaxNetworkMessageSize
uint Opc.Ua.PubSubGroupDataType.MaxNetworkMessageSize get set
Definition at line 8692 of file Opc.Ua.DataTypes.cs.
Name
string Opc.Ua.PubSubGroupDataType.Name get set
Definition at line 8638 of file Opc.Ua.DataTypes.cs.
SecurityGroupId
string Opc.Ua.PubSubGroupDataType.SecurityGroupId get set
Definition at line 8662 of file Opc.Ua.DataTypes.cs.
SecurityKeyServices
EndpointDescriptionCollection Opc.Ua.PubSubGroupDataType.SecurityKeyServices get set
Definition at line 8672 of file Opc.Ua.DataTypes.cs.
SecurityMode
MessageSecurityMode Opc.Ua.PubSubGroupDataType.SecurityMode get set
Definition at line 8654 of file Opc.Ua.DataTypes.cs.
TypeId
virtual ExpandedNodeId Opc.Ua.PubSubGroupDataType.TypeId get
Definition at line 8723 of file Opc.Ua.DataTypes.cs.
XmlEncodingId
virtual ExpandedNodeId Opc.Ua.PubSubGroupDataType.XmlEncodingId get
Definition at line 8735 of file Opc.Ua.DataTypes.cs.
The documentation for this class was generated from the following file:
Opc.Ua.DataTypes.cs