Project Template: Sercos.SercosProfileState Class Reference
Sercos.SercosProfileState Class Reference
Stores an instance of the SercosProfileType ObjectType.
Public Member Functions
SercosProfileState (NodeState parent)
Initializes the type with its default attribute values.
Public Member Functions inherited from Sercos.FunctionalGroupState
FunctionalGroupState (NodeState parent)
Initializes the type with its default attribute values.
Protected Member Functions
override NodeId GetDefaultTypeDefinitionId (NamespaceTable namespaceUris)
Returns the id of the default type definition node for the instance.
override void Initialize (ISystemContext context)
Initializes the instance.
override void Initialize (ISystemContext context, NodeState source)
Initializes the instance with a node.
override void InitializeOptionalChildren (ISystemContext context)
Initializes the any option children defined for the instance.
Protected Member Functions inherited from Sercos.FunctionalGroupState
override NodeId GetDefaultTypeDefinitionId (NamespaceTable namespaceUris)
Returns the id of the default type definition node for the instance.
override void Initialize (ISystemContext context)
Initializes the instance.
override void Initialize (ISystemContext context, NodeState source)
Initializes the instance with a node.
override void InitializeOptionalChildren (ISystemContext context)
Initializes the any option children defined for the instance.
Detailed Description
Stores an instance of the SercosProfileType ObjectType.
<exclude>
Definition at line 120 of file Sercos.Classes.cs.
Constructor & Destructor Documentation
SercosProfileState()
Sercos.SercosProfileState.SercosProfileState (NodeState parent) inline
Initializes the type with its default attribute values.
Definition at line 126 of file Sercos.Classes.cs.
Member Function Documentation
GetDefaultTypeDefinitionId()
override NodeId Sercos.SercosProfileState.GetDefaultTypeDefinitionId (NamespaceTable namespaceUris) inline protected
Returns the id of the default type definition node for the instance.
Definition at line 133 of file Sercos.Classes.cs.
References Sercos.FunctionalGroupState.Initialize(), Sercos.FunctionalGroupState.InitializeOptionalChildren(), Opc.Ua.NodeId, Sercos.Namespaces.Sercos, and Sercos.ObjectTypes.SercosProfileType.
Initialize() [1/2]
override void Sercos.SercosProfileState.Initialize (ISystemContext context) inline protected
Initializes the instance.
Definition at line 142 of file Sercos.Classes.cs.
Initialize() [2/2]
override void Sercos.SercosProfileState.Initialize (ISystemContext context, NodeState source) inline protected
Initializes the instance with a node.
Definition at line 151 of file Sercos.Classes.cs.
References Sercos.FunctionalGroupState.InitializeOptionalChildren().
InitializeOptionalChildren()
override void Sercos.SercosProfileState.InitializeOptionalChildren (ISystemContext context) inline protected
Initializes the any option children defined for the instance.
Definition at line 160 of file Sercos.Classes.cs.
The documentation for this class was generated from the following file:
Sercos.Classes.cs