Project Template: Opc.Ua.PublishedDataSetDataType Class Reference
Opc.Ua.PublishedDataSetDataType Class Reference
Public Member Functions
PublishedDataSetDataType ()
The default constructor.
virtual void Encode (IEncoder encoder)
virtual void Decode (IDecoder decoder)
virtual bool IsEqual (IEncodeable encodeable)
virtual object Clone ()
new object MemberwiseClone ()
Properties
string Name [get, set]
StringCollection DataSetFolder [get, set]
DataSetMetaDataType DataSetMetaData [get, set]
KeyValuePairCollection ExtensionFields [get, set]
ExtensionObject DataSetSource [get, set]
virtual ExpandedNodeId TypeId [get]
virtual ExpandedNodeId BinaryEncodingId [get]
virtual ExpandedNodeId XmlEncodingId [get]
Detailed Description
<exclude>
Definition at line 6360 of file Opc.Ua.DataTypes.cs.
Constructor & Destructor Documentation
PublishedDataSetDataType()
Opc.Ua.PublishedDataSetDataType.PublishedDataSetDataType () inline
The default constructor.
Definition at line 6366 of file Opc.Ua.DataTypes.cs.
Member Function Documentation
Clone()
virtual object Opc.Ua.PublishedDataSetDataType.Clone () inline virtual
Definition at line 6550 of file Opc.Ua.DataTypes.cs.
Decode()
virtual void Opc.Ua.PublishedDataSetDataType.Decode (IDecoder decoder) inline virtual
Definition at line 6511 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
Encode()
virtual void Opc.Ua.PublishedDataSetDataType.Encode (IEncoder encoder) inline virtual
Definition at line 6497 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
IsEqual()
virtual bool Opc.Ua.PublishedDataSetDataType.IsEqual (IEncodeable encodeable) inline virtual
Definition at line 6525 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Object.
MemberwiseClone()
new object Opc.Ua.PublishedDataSetDataType.MemberwiseClone () inline
Definition at line 6557 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.KeyValuePairCollection.Clone(), Opc.Ua.DataSetMetaDataType.Clone(), Opc.Ua.PublishedDataSetDataType.MemberwiseClone(), and Opc.Ua.Namespaces.OpcUaXsd.
Referenced by Opc.Ua.PublishedDataSetDataType.MemberwiseClone().
Property Documentation
BinaryEncodingId
virtual ExpandedNodeId Opc.Ua.PublishedDataSetDataType.BinaryEncodingId get
Definition at line 6486 of file Opc.Ua.DataTypes.cs.
DataSetFolder
StringCollection Opc.Ua.PublishedDataSetDataType.DataSetFolder get set
Definition at line 6407 of file Opc.Ua.DataTypes.cs.
DataSetMetaData
DataSetMetaDataType Opc.Ua.PublishedDataSetDataType.DataSetMetaData get set
Definition at line 6429 of file Opc.Ua.DataTypes.cs.
DataSetSource
ExtensionObject Opc.Ua.PublishedDataSetDataType.DataSetSource get set
Definition at line 6471 of file Opc.Ua.DataTypes.cs.
ExtensionFields
KeyValuePairCollection Opc.Ua.PublishedDataSetDataType.ExtensionFields get set
Definition at line 6451 of file Opc.Ua.DataTypes.cs.
Name
string Opc.Ua.PublishedDataSetDataType.Name get set
Definition at line 6397 of file Opc.Ua.DataTypes.cs.
TypeId
virtual ExpandedNodeId Opc.Ua.PublishedDataSetDataType.TypeId get
Definition at line 6480 of file Opc.Ua.DataTypes.cs.
XmlEncodingId
virtual ExpandedNodeId Opc.Ua.PublishedDataSetDataType.XmlEncodingId get
Definition at line 6492 of file Opc.Ua.DataTypes.cs.
The documentation for this class was generated from the following file:
Opc.Ua.DataTypes.cs