Project Template: Opc.Ua.DataSetWriterDataType Class Reference
Opc.Ua.DataSetWriterDataType Class Reference
Public Member Functions
DataSetWriterDataType ()
The default constructor.
virtual void Encode (IEncoder encoder)
virtual void Decode (IDecoder decoder)
virtual bool IsEqual (IEncodeable encodeable)
virtual object Clone ()
new object MemberwiseClone ()
Properties
string Name [get, set]
bool Enabled [get, set]
ushort DataSetWriterId [get, set]
uint DataSetFieldContentMask [get, set]
uint KeyFrameCount [get, set]
string DataSetName [get, set]
KeyValuePairCollection DataSetWriterProperties [get, set]
ExtensionObject TransportSettings [get, set]
ExtensionObject MessageSettings [get, set]
virtual ExpandedNodeId TypeId [get]
virtual ExpandedNodeId BinaryEncodingId [get]
virtual ExpandedNodeId XmlEncodingId [get]
Detailed Description
<exclude>
Definition at line 7848 of file Opc.Ua.DataTypes.cs.
Constructor & Destructor Documentation
DataSetWriterDataType()
Opc.Ua.DataSetWriterDataType.DataSetWriterDataType () inline
The default constructor.
Definition at line 7854 of file Opc.Ua.DataTypes.cs.
Member Function Documentation
Clone()
virtual object Opc.Ua.DataSetWriterDataType.Clone () inline virtual
Definition at line 8058 of file Opc.Ua.DataTypes.cs.
Decode()
virtual void Opc.Ua.DataSetWriterDataType.Decode (IDecoder decoder) inline virtual
Definition at line 8011 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.DataSetWriterId, and Opc.Ua.Namespaces.OpcUaXsd.
Encode()
virtual void Opc.Ua.DataSetWriterDataType.Encode (IEncoder encoder) inline virtual
Definition at line 7993 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.DataSetWriterId, and Opc.Ua.Namespaces.OpcUaXsd.
IsEqual()
virtual bool Opc.Ua.DataSetWriterDataType.IsEqual (IEncodeable encodeable) inline virtual
Definition at line 8029 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Object.
MemberwiseClone()
new object Opc.Ua.DataSetWriterDataType.MemberwiseClone () inline
Definition at line 8065 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.KeyValuePairCollection.Clone(), Opc.Ua.DataSetWriterDataType.MemberwiseClone(), and Opc.Ua.Namespaces.OpcUaXsd.
Referenced by Opc.Ua.DataSetWriterDataType.MemberwiseClone().
Property Documentation
BinaryEncodingId
virtual ExpandedNodeId Opc.Ua.DataSetWriterDataType.BinaryEncodingId get
Definition at line 7982 of file Opc.Ua.DataTypes.cs.
DataSetFieldContentMask
uint Opc.Ua.DataSetWriterDataType.DataSetFieldContentMask get set
Definition at line 7913 of file Opc.Ua.DataTypes.cs.
DataSetName
string Opc.Ua.DataSetWriterDataType.DataSetName get set
Definition at line 7929 of file Opc.Ua.DataTypes.cs.
DataSetWriterId
ushort Opc.Ua.DataSetWriterDataType.DataSetWriterId get set
Definition at line 7905 of file Opc.Ua.DataTypes.cs.
DataSetWriterProperties
KeyValuePairCollection Opc.Ua.DataSetWriterDataType.DataSetWriterProperties get set
Definition at line 7939 of file Opc.Ua.DataTypes.cs.
Enabled
bool Opc.Ua.DataSetWriterDataType.Enabled get set
Definition at line 7897 of file Opc.Ua.DataTypes.cs.
KeyFrameCount
uint Opc.Ua.DataSetWriterDataType.KeyFrameCount get set
Definition at line 7921 of file Opc.Ua.DataTypes.cs.
MessageSettings
ExtensionObject Opc.Ua.DataSetWriterDataType.MessageSettings get set
Definition at line 7967 of file Opc.Ua.DataTypes.cs.
Name
string Opc.Ua.DataSetWriterDataType.Name get set
Definition at line 7889 of file Opc.Ua.DataTypes.cs.
TransportSettings
ExtensionObject Opc.Ua.DataSetWriterDataType.TransportSettings get set
Definition at line 7959 of file Opc.Ua.DataTypes.cs.
TypeId
virtual ExpandedNodeId Opc.Ua.DataSetWriterDataType.TypeId get
Definition at line 7976 of file Opc.Ua.DataTypes.cs.
XmlEncodingId
virtual ExpandedNodeId Opc.Ua.DataSetWriterDataType.XmlEncodingId get
Definition at line 7988 of file Opc.Ua.DataTypes.cs.
The documentation for this class was generated from the following file:
Opc.Ua.DataTypes.cs