Project Template: Opc.Ua.StructureDescription Class Reference
Opc.Ua.StructureDescription Class Reference
Public Member Functions
StructureDescription ()
The default constructor.
override void Encode (IEncoder encoder)
override void Decode (IDecoder decoder)
override bool IsEqual (IEncodeable encodeable)
override object Clone ()
new object MemberwiseClone ()
Public Member Functions inherited from Opc.Ua.DataTypeDescription
DataTypeDescription ()
The default constructor.
new object MemberwiseClone ()
Properties
StructureDefinition StructureDefinition [get, set]
override ExpandedNodeId TypeId [get]
override ExpandedNodeId BinaryEncodingId [get]
override ExpandedNodeId XmlEncodingId [get]
Properties inherited from Opc.Ua.DataTypeDescription
NodeId DataTypeId [get, set]
QualifiedName Name [get, set]
virtual ExpandedNodeId TypeId [get]
virtual ExpandedNodeId BinaryEncodingId [get]
virtual ExpandedNodeId XmlEncodingId [get]
Detailed Description
<exclude>
Definition at line 4331 of file Opc.Ua.DataTypes.cs.
Constructor & Destructor Documentation
StructureDescription()
Opc.Ua.StructureDescription.StructureDescription () inline
The default constructor.
Definition at line 4337 of file Opc.Ua.DataTypes.cs.
Member Function Documentation
Clone()
override object Opc.Ua.StructureDescription.Clone () inline virtual
Reimplemented from Opc.Ua.DataTypeDescription.
Definition at line 4450 of file Opc.Ua.DataTypes.cs.
Decode()
override void Opc.Ua.StructureDescription.Decode (IDecoder decoder) inline virtual
Reimplemented from Opc.Ua.DataTypeDescription.
Definition at line 4416 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
Encode()
override void Opc.Ua.StructureDescription.Encode (IEncoder encoder) inline virtual
Reimplemented from Opc.Ua.DataTypeDescription.
Definition at line 4404 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
IsEqual()
override bool Opc.Ua.StructureDescription.IsEqual (IEncodeable encodeable) inline virtual
Reimplemented from Opc.Ua.DataTypeDescription.
Definition at line 4428 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Object.
MemberwiseClone()
new object Opc.Ua.StructureDescription.MemberwiseClone () inline
Definition at line 4457 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.StructureDefinition.Clone(), Opc.Ua.StructureDescription.MemberwiseClone(), and Opc.Ua.Namespaces.OpcUaXsd.
Referenced by Opc.Ua.StructureDescription.MemberwiseClone().
Property Documentation
BinaryEncodingId
override ExpandedNodeId Opc.Ua.StructureDescription.BinaryEncodingId get
Definition at line 4393 of file Opc.Ua.DataTypes.cs.
StructureDefinition
StructureDefinition Opc.Ua.StructureDescription.StructureDefinition get set
Definition at line 4366 of file Opc.Ua.DataTypes.cs.
TypeId
override ExpandedNodeId Opc.Ua.StructureDescription.TypeId get
Definition at line 4387 of file Opc.Ua.DataTypes.cs.
XmlEncodingId
override ExpandedNodeId Opc.Ua.StructureDescription.XmlEncodingId get
Definition at line 4399 of file Opc.Ua.DataTypes.cs.
The documentation for this class was generated from the following file:
Opc.Ua.DataTypes.cs