Project Template: Opc.Ua.SignatureData Class Reference
Opc.Ua.SignatureData Class Reference
Public Member Functions
SignatureData ()
The default constructor.
virtual void Encode (IEncoder encoder)
virtual void Decode (IDecoder decoder)
virtual bool IsEqual (IEncodeable encodeable)
virtual object Clone ()
new object MemberwiseClone ()
Properties
string Algorithm [get, set]
byte [] Signature [get, set]
virtual ExpandedNodeId TypeId [get]
virtual ExpandedNodeId BinaryEncodingId [get]
virtual ExpandedNodeId XmlEncodingId [get]
Detailed Description
<exclude>
Definition at line 29046 of file Opc.Ua.DataTypes.cs.
Constructor & Destructor Documentation
SignatureData()
Opc.Ua.SignatureData.SignatureData () inline
The default constructor.
Definition at line 29052 of file Opc.Ua.DataTypes.cs.
Member Function Documentation
Clone()
virtual object Opc.Ua.SignatureData.Clone () inline virtual
Definition at line 29158 of file Opc.Ua.DataTypes.cs.
Referenced by Opc.Ua.CreateSessionResponse.MemberwiseClone(), and Opc.Ua.ActivateSessionRequest.MemberwiseClone().
Decode()
virtual void Opc.Ua.SignatureData.Decode (IDecoder decoder) inline virtual
Definition at line 29125 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
Encode()
virtual void Opc.Ua.SignatureData.Encode (IEncoder encoder) inline virtual
Definition at line 29114 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
IsEqual()
virtual bool Opc.Ua.SignatureData.IsEqual (IEncodeable encodeable) inline virtual
Definition at line 29136 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Object.
MemberwiseClone()
new object Opc.Ua.SignatureData.MemberwiseClone () inline
Definition at line 29165 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.SignatureData.MemberwiseClone(), and Opc.Ua.Namespaces.OpcUaXsd.
Referenced by Opc.Ua.SignatureData.MemberwiseClone().
Property Documentation
Algorithm
string Opc.Ua.SignatureData.Algorithm get set
Definition at line 29080 of file Opc.Ua.DataTypes.cs.
BinaryEncodingId
virtual ExpandedNodeId Opc.Ua.SignatureData.BinaryEncodingId get
Definition at line 29103 of file Opc.Ua.DataTypes.cs.
Signature
byte [] Opc.Ua.SignatureData.Signature get set
Definition at line 29088 of file Opc.Ua.DataTypes.cs.
TypeId
virtual ExpandedNodeId Opc.Ua.SignatureData.TypeId get
Definition at line 29097 of file Opc.Ua.DataTypes.cs.
XmlEncodingId
virtual ExpandedNodeId Opc.Ua.SignatureData.XmlEncodingId get
Definition at line 29109 of file Opc.Ua.DataTypes.cs.
The documentation for this class was generated from the following file:
Opc.Ua.DataTypes.cs