Project Template: Opc.Ua.DeleteReferencesRequest Class Reference
Opc.Ua.DeleteReferencesRequest Class Reference
Public Member Functions
DeleteReferencesRequest ()
The default constructor.
virtual void Encode (IEncoder encoder)
virtual void Decode (IDecoder decoder)
virtual bool IsEqual (IEncodeable encodeable)
virtual object Clone ()
new object MemberwiseClone ()
Properties
RequestHeader RequestHeader [get, set]
DeleteReferencesItemCollection ReferencesToDelete [get, set]
virtual ExpandedNodeId TypeId [get]
virtual ExpandedNodeId BinaryEncodingId [get]
virtual ExpandedNodeId XmlEncodingId [get]
Detailed Description
<exclude>
Definition at line 1538 of file Opc.Ua.Messages.cs.
Constructor & Destructor Documentation
DeleteReferencesRequest()
Opc.Ua.DeleteReferencesRequest.DeleteReferencesRequest () inline
The default constructor.
Definition at line 36114 of file Opc.Ua.DataTypes.cs.
Member Function Documentation
Clone()
virtual object Opc.Ua.DeleteReferencesRequest.Clone () inline virtual
Definition at line 36248 of file Opc.Ua.DataTypes.cs.
Decode()
virtual void Opc.Ua.DeleteReferencesRequest.Decode (IDecoder decoder) inline virtual
Definition at line 36215 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
Encode()
virtual void Opc.Ua.DeleteReferencesRequest.Encode (IEncoder encoder) inline virtual
Definition at line 36204 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
IsEqual()
virtual bool Opc.Ua.DeleteReferencesRequest.IsEqual (IEncodeable encodeable) inline virtual
Definition at line 36226 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Object.
MemberwiseClone()
new object Opc.Ua.DeleteReferencesRequest.MemberwiseClone () inline
Definition at line 36255 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.RequestHeader.Clone(), Opc.Ua.DeleteReferencesItemCollection.Clone(), Opc.Ua.DeleteReferencesRequest.MemberwiseClone(), and Opc.Ua.Namespaces.OpcUaXsd.
Referenced by Opc.Ua.DeleteReferencesRequest.MemberwiseClone().
Property Documentation
BinaryEncodingId
virtual ExpandedNodeId Opc.Ua.DeleteReferencesRequest.BinaryEncodingId get
Definition at line 36193 of file Opc.Ua.DataTypes.cs.
ReferencesToDelete
DeleteReferencesItemCollection Opc.Ua.DeleteReferencesRequest.ReferencesToDelete get set
Definition at line 36166 of file Opc.Ua.DataTypes.cs.
Referenced by Opc.Ua.SessionClient.BeginDeleteReferences(), Opc.Ua.SessionClient.EndDeleteNodes(), and Opc.Ua.SessionEndpoint.EndDeleteNodes().
RequestHeader
RequestHeader Opc.Ua.DeleteReferencesRequest.RequestHeader get set
Definition at line 36144 of file Opc.Ua.DataTypes.cs.
Referenced by Opc.Ua.SessionClient.BeginDeleteReferences(), Opc.Ua.SessionClient.EndDeleteNodes(), and Opc.Ua.SessionEndpoint.EndDeleteNodes().
TypeId
virtual ExpandedNodeId Opc.Ua.DeleteReferencesRequest.TypeId get
Definition at line 36187 of file Opc.Ua.DataTypes.cs.
XmlEncodingId
virtual ExpandedNodeId Opc.Ua.DeleteReferencesRequest.XmlEncodingId get
Definition at line 36199 of file Opc.Ua.DataTypes.cs.
The documentation for this class was generated from the following files:
Opc.Ua.Messages.cs
Opc.Ua.DataTypes.cs