Project Template: Opc.Ua.RegisterServerResponse Class Reference
Opc.Ua.RegisterServerResponse Class Reference
Public Member Functions
RegisterServerResponse ()
The default constructor.
virtual void Encode (IEncoder encoder)
virtual void Decode (IDecoder decoder)
virtual bool IsEqual (IEncodeable encodeable)
virtual object Clone ()
new object MemberwiseClone ()
Properties
ResponseHeader ResponseHeader [get, set]
virtual ExpandedNodeId TypeId [get]
virtual ExpandedNodeId BinaryEncodingId [get]
virtual ExpandedNodeId XmlEncodingId [get]
Detailed Description
<exclude>
Definition at line 365 of file Opc.Ua.Messages.cs.
Constructor & Destructor Documentation
RegisterServerResponse()
Opc.Ua.RegisterServerResponse.RegisterServerResponse () inline
The default constructor.
Definition at line 27082 of file Opc.Ua.DataTypes.cs.
Member Function Documentation
Clone()
virtual object Opc.Ua.RegisterServerResponse.Clone () inline virtual
Definition at line 27190 of file Opc.Ua.DataTypes.cs.
Decode()
virtual void Opc.Ua.RegisterServerResponse.Decode (IDecoder decoder) inline virtual
Definition at line 27159 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
Encode()
virtual void Opc.Ua.RegisterServerResponse.Encode (IEncoder encoder) inline virtual
Definition at line 27149 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
IsEqual()
virtual bool Opc.Ua.RegisterServerResponse.IsEqual (IEncodeable encodeable) inline virtual
Definition at line 27169 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Object.
MemberwiseClone()
new object Opc.Ua.RegisterServerResponse.MemberwiseClone () inline
Definition at line 27197 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.ResponseHeader.Clone(), Opc.Ua.RegisterServerResponse.MemberwiseClone(), and Opc.Ua.Namespaces.OpcUaXsd.
Referenced by Opc.Ua.RegisterServerResponse.MemberwiseClone().
Property Documentation
BinaryEncodingId
virtual ExpandedNodeId Opc.Ua.RegisterServerResponse.BinaryEncodingId get
Definition at line 27138 of file Opc.Ua.DataTypes.cs.
ResponseHeader
ResponseHeader Opc.Ua.RegisterServerResponse.ResponseHeader get set
Definition at line 27111 of file Opc.Ua.DataTypes.cs.
Referenced by Opc.Ua.RegisterServerMessage.CreateResponse(), Opc.Ua.DiscoveryEndpoint.EndGetEndpoints(), Opc.Ua.RegistrationClient.EndRegisterServer(), and Opc.Ua.RegisterServerResponseMessage.RegisterServerResponseMessage().
TypeId
virtual ExpandedNodeId Opc.Ua.RegisterServerResponse.TypeId get
Definition at line 27132 of file Opc.Ua.DataTypes.cs.
XmlEncodingId
virtual ExpandedNodeId Opc.Ua.RegisterServerResponse.XmlEncodingId get
Definition at line 27144 of file Opc.Ua.DataTypes.cs.
The documentation for this class was generated from the following files:
Opc.Ua.Messages.cs
Opc.Ua.DataTypes.cs