HaSSL: HaSLL::Logger Class Reference
HaSLL::Logger Class Reference
Logging wrapper.
#include <Logger.hpp>
Public Member Functions
Logger (std::vector< std::shared_ptr< spdlog::sinks::sink >> sinks, const std::string &logger_name)
Construct a new Logger object.
void configure (SeverityLevel level=SeverityLevel::DEBUG)
Configures the logging level for this instance.
template<typename... Args>
void log (SeverityLevel level, spdlog::string_view_t message, const Args &... args)
Logs a message to SeverityLevel.
std::string getName ()
Returns the name of this logger.
Private Attributes
std::shared_ptr< spdlog::logger > logger_
std::string name_
Detailed Description
Logging wrapper.
Constructor & Destructor Documentation
Logger()
HaSLL::Logger::Logger (std::vector< std::shared_ptr< spdlog::sinks::sink >> sinks, const std::string & logger_name)
Construct a new Logger object.
Attention
This ctor should only be called by LoggerRepository
Parameters
sinks
logger_name
Member Function Documentation
configure()
void HaSLL::Logger::configure (SeverityLevel level = SeverityLevel::DEBUG)
Configures the logging level for this instance.
Parameters
level
getName()
std::string HaSLL::Logger::getName ()
Returns the name of this logger.
Returns
std::string
Referenced by log().
log()
template<typename... Args> void HaSLL::Logger::log (SeverityLevel level, spdlog::string_view_t message, const Args &... args) inline
Logs a message to SeverityLevel.
Example use:
  logger->log(SeverityLevel::TRACE, "Welcome to a frontend for spdlog!");
  @param level
  @param message
 /
 void log(SeverityLevel level, spdlog::string_view_t message);
Template Parameters
Args
Parameters
level
message
args
References getName(), HaSLL::getSPDLogLevel(), and logger_.
Field Documentation
logger_
std::shared_ptr<spdlog::logger> HaSLL::Logger::logger_ private
Referenced by log().
name_
std::string HaSLL::Logger::name_ private
The documentation for this class was generated from the following file:
Logger.hpp