Project Template: Opc.Ua.CloseSecureChannelResponse Class Reference
Opc.Ua.CloseSecureChannelResponse Class Reference
Public Member Functions
CloseSecureChannelResponse ()
The default constructor.
virtual void Encode (IEncoder encoder)
virtual void Decode (IDecoder decoder)
virtual bool IsEqual (IEncodeable encodeable)
virtual object Clone ()
new object MemberwiseClone ()
Properties
ResponseHeader ResponseHeader [get, set]
virtual ExpandedNodeId TypeId [get]
virtual ExpandedNodeId BinaryEncodingId [get]
virtual ExpandedNodeId XmlEncodingId [get]
Detailed Description
<exclude>
Definition at line 686 of file Opc.Ua.Messages.cs.
Constructor & Destructor Documentation
CloseSecureChannelResponse()
Opc.Ua.CloseSecureChannelResponse.CloseSecureChannelResponse () inline
The default constructor.
Definition at line 28675 of file Opc.Ua.DataTypes.cs.
Member Function Documentation
Clone()
virtual object Opc.Ua.CloseSecureChannelResponse.Clone () inline virtual
Definition at line 28783 of file Opc.Ua.DataTypes.cs.
Decode()
virtual void Opc.Ua.CloseSecureChannelResponse.Decode (IDecoder decoder) inline virtual
Definition at line 28752 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
Encode()
virtual void Opc.Ua.CloseSecureChannelResponse.Encode (IEncoder encoder) inline virtual
Definition at line 28742 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
IsEqual()
virtual bool Opc.Ua.CloseSecureChannelResponse.IsEqual (IEncodeable encodeable) inline virtual
Definition at line 28762 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Object.
MemberwiseClone()
new object Opc.Ua.CloseSecureChannelResponse.MemberwiseClone () inline
Definition at line 28790 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.ResponseHeader.Clone(), Opc.Ua.CloseSecureChannelResponse.MemberwiseClone(), and Opc.Ua.Namespaces.OpcUaXsd.
Referenced by Opc.Ua.CloseSecureChannelResponse.MemberwiseClone().
Property Documentation
BinaryEncodingId
virtual ExpandedNodeId Opc.Ua.CloseSecureChannelResponse.BinaryEncodingId get
Definition at line 28731 of file Opc.Ua.DataTypes.cs.
ResponseHeader
ResponseHeader Opc.Ua.CloseSecureChannelResponse.ResponseHeader get set
Definition at line 28704 of file Opc.Ua.DataTypes.cs.
Referenced by Opc.Ua.CloseSecureChannelResponseMessage.CloseSecureChannelResponseMessage(), and Opc.Ua.CloseSecureChannelMessage.CreateResponse().
TypeId
virtual ExpandedNodeId Opc.Ua.CloseSecureChannelResponse.TypeId get
Definition at line 28725 of file Opc.Ua.DataTypes.cs.
XmlEncodingId
virtual ExpandedNodeId Opc.Ua.CloseSecureChannelResponse.XmlEncodingId get
Definition at line 28737 of file Opc.Ua.DataTypes.cs.
The documentation for this class was generated from the following files:
Opc.Ua.Messages.cs
Opc.Ua.DataTypes.cs