Project Template: Opc.Ua.Fdi5.RegisterNodesResult Class Reference
Opc.Ua.Fdi5.RegisterNodesResult Class Reference
Public Member Functions
RegisterNodesResult ()
The default constructor.
virtual void Encode (IEncoder encoder)
virtual void Decode (IDecoder decoder)
virtual bool IsEqual (IEncodeable encodeable)
virtual object Clone ()
new object MemberwiseClone ()
Properties
int Status [get, set]
RegisteredNodeCollection RegisteredNodes [get, set]
virtual ExpandedNodeId TypeId [get]
virtual ExpandedNodeId BinaryEncodingId [get]
virtual ExpandedNodeId XmlEncodingId [get]
Detailed Description
<exclude>
Definition at line 782 of file Opc.Ua.Fdi5.DataTypes.cs.
Constructor & Destructor Documentation
RegisterNodesResult()
Opc.Ua.Fdi5.RegisterNodesResult.RegisterNodesResult () inline
The default constructor.
Definition at line 788 of file Opc.Ua.Fdi5.DataTypes.cs.
Member Function Documentation
Clone()
virtual object Opc.Ua.Fdi5.RegisterNodesResult.Clone () inline virtual
Definition at line 908 of file Opc.Ua.Fdi5.DataTypes.cs.
Decode()
virtual void Opc.Ua.Fdi5.RegisterNodesResult.Decode (IDecoder decoder) inline virtual
Definition at line 875 of file Opc.Ua.Fdi5.DataTypes.cs.
References Opc.Ua.Fdi5.Namespaces.OpcUaFdi5Xsd, and Opc.Ua.Status.
Encode()
virtual void Opc.Ua.Fdi5.RegisterNodesResult.Encode (IEncoder encoder) inline virtual
Definition at line 864 of file Opc.Ua.Fdi5.DataTypes.cs.
References Opc.Ua.Fdi5.Namespaces.OpcUaFdi5Xsd, and Opc.Ua.Status.
IsEqual()
virtual bool Opc.Ua.Fdi5.RegisterNodesResult.IsEqual (IEncodeable encodeable) inline virtual
Definition at line 886 of file Opc.Ua.Fdi5.DataTypes.cs.
References Opc.Ua.Object.
MemberwiseClone()
new object Opc.Ua.Fdi5.RegisterNodesResult.MemberwiseClone () inline
Definition at line 915 of file Opc.Ua.Fdi5.DataTypes.cs.
References Opc.Ua.Fdi5.RegisteredNodeCollection.Clone(), Opc.Ua.Fdi5.RegisterNodesResult.MemberwiseClone(), and Opc.Ua.Fdi5.Namespaces.OpcUaFdi5Xsd.
Referenced by Opc.Ua.Fdi5.RegisterNodesResult.MemberwiseClone().
Property Documentation
BinaryEncodingId
virtual ExpandedNodeId Opc.Ua.Fdi5.RegisterNodesResult.BinaryEncodingId get
Definition at line 853 of file Opc.Ua.Fdi5.DataTypes.cs.
RegisteredNodes
RegisteredNodeCollection Opc.Ua.Fdi5.RegisterNodesResult.RegisteredNodes get set
Definition at line 826 of file Opc.Ua.Fdi5.DataTypes.cs.
Status
int Opc.Ua.Fdi5.RegisterNodesResult.Status get set
Definition at line 816 of file Opc.Ua.Fdi5.DataTypes.cs.
TypeId
virtual ExpandedNodeId Opc.Ua.Fdi5.RegisterNodesResult.TypeId get
Definition at line 847 of file Opc.Ua.Fdi5.DataTypes.cs.
XmlEncodingId
virtual ExpandedNodeId Opc.Ua.Fdi5.RegisterNodesResult.XmlEncodingId get
Definition at line 859 of file Opc.Ua.Fdi5.DataTypes.cs.
The documentation for this class was generated from the following file:
Opc.Ua.Fdi5.DataTypes.cs