Project Template: Opc.Ua.HistoryUpdateRequest Class Reference
Opc.Ua.HistoryUpdateRequest Class Reference
Public Member Functions
HistoryUpdateRequest ()
The default constructor.
virtual void Encode (IEncoder encoder)
virtual void Decode (IDecoder decoder)
virtual bool IsEqual (IEncodeable encodeable)
virtual object Clone ()
new object MemberwiseClone ()
Properties
RequestHeader RequestHeader [get, set]
ExtensionObjectCollection HistoryUpdateDetails [get, set]
virtual ExpandedNodeId TypeId [get]
virtual ExpandedNodeId BinaryEncodingId [get]
virtual ExpandedNodeId XmlEncodingId [get]
Detailed Description
<exclude>
Definition at line 2715 of file Opc.Ua.Messages.cs.
Constructor & Destructor Documentation
HistoryUpdateRequest()
Opc.Ua.HistoryUpdateRequest.HistoryUpdateRequest () inline
The default constructor.
Definition at line 50393 of file Opc.Ua.DataTypes.cs.
Member Function Documentation
Clone()
virtual object Opc.Ua.HistoryUpdateRequest.Clone () inline virtual
Definition at line 50527 of file Opc.Ua.DataTypes.cs.
Decode()
virtual void Opc.Ua.HistoryUpdateRequest.Decode (IDecoder decoder) inline virtual
Definition at line 50494 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
Encode()
virtual void Opc.Ua.HistoryUpdateRequest.Encode (IEncoder encoder) inline virtual
Definition at line 50483 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
IsEqual()
virtual bool Opc.Ua.HistoryUpdateRequest.IsEqual (IEncodeable encodeable) inline virtual
Definition at line 50505 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Object.
MemberwiseClone()
new object Opc.Ua.HistoryUpdateRequest.MemberwiseClone () inline
Definition at line 50534 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.RequestHeader.Clone(), Opc.Ua.HistoryUpdateRequest.MemberwiseClone(), and Opc.Ua.Namespaces.OpcUaXsd.
Referenced by Opc.Ua.HistoryUpdateRequest.MemberwiseClone().
Property Documentation
BinaryEncodingId
virtual ExpandedNodeId Opc.Ua.HistoryUpdateRequest.BinaryEncodingId get
Definition at line 50472 of file Opc.Ua.DataTypes.cs.
HistoryUpdateDetails
ExtensionObjectCollection Opc.Ua.HistoryUpdateRequest.HistoryUpdateDetails get set
Definition at line 50445 of file Opc.Ua.DataTypes.cs.
Referenced by Opc.Ua.SessionClient.BeginHistoryUpdate(), Opc.Ua.SessionEndpoint.EndWrite(), and Opc.Ua.SessionClient.EndWrite().
RequestHeader
RequestHeader Opc.Ua.HistoryUpdateRequest.RequestHeader get set
Definition at line 50423 of file Opc.Ua.DataTypes.cs.
Referenced by Opc.Ua.SessionClient.BeginHistoryUpdate(), Opc.Ua.SessionEndpoint.EndWrite(), and Opc.Ua.SessionClient.EndWrite().
TypeId
virtual ExpandedNodeId Opc.Ua.HistoryUpdateRequest.TypeId get
Definition at line 50466 of file Opc.Ua.DataTypes.cs.
XmlEncodingId
virtual ExpandedNodeId Opc.Ua.HistoryUpdateRequest.XmlEncodingId get
Definition at line 50478 of file Opc.Ua.DataTypes.cs.
The documentation for this class was generated from the following files:
Opc.Ua.Messages.cs
Opc.Ua.DataTypes.cs