Project Template: client_highlevel.h File Reference
client_highlevel.h File Reference
Typedefs
typedef UA_Boolean(* UA_HistoricalIteratorCallback) (UA_Client *client, const UA_NodeId *nodeId, UA_Boolean moreDataAvailable, const UA_ExtensionObject *data, void *callbackContext)
typedef UA_StatusCode(* UA_NodeIteratorCallback) (UA_NodeId childId, UA_Boolean isInverse, UA_NodeId referenceTypeId, void *handle)
Functions
_UA_BEGIN_DECLS UA_StatusCode UA_EXPORT __UA_Client_readAttribute (UA_Client *client, const UA_NodeId *nodeId, UA_AttributeId attributeId, void *out, const UA_DataType *outDataType)
static UA_INLINE UA_StatusCode UA_Client_readNodeIdAttribute (UA_Client *client, const UA_NodeId nodeId, UA_NodeId *outNodeId)
static UA_INLINE UA_StatusCode UA_Client_readNodeClassAttribute (UA_Client *client, const UA_NodeId nodeId, UA_NodeClass *outNodeClass)
static UA_INLINE UA_StatusCode UA_Client_readBrowseNameAttribute (UA_Client *client, const UA_NodeId nodeId, UA_QualifiedName *outBrowseName)
static UA_INLINE UA_StatusCode UA_Client_readDisplayNameAttribute (UA_Client *client, const UA_NodeId nodeId, UA_LocalizedText *outDisplayName)
static UA_INLINE UA_StatusCode UA_Client_readDescriptionAttribute (UA_Client *client, const UA_NodeId nodeId, UA_LocalizedText *outDescription)
static UA_INLINE UA_StatusCode UA_Client_readWriteMaskAttribute (UA_Client *client, const UA_NodeId nodeId, UA_UInt32 *outWriteMask)
static UA_INLINE UA_StatusCode UA_Client_readUserWriteMaskAttribute (UA_Client *client, const UA_NodeId nodeId, UA_UInt32 *outUserWriteMask)
static UA_INLINE UA_StatusCode UA_Client_readIsAbstractAttribute (UA_Client *client, const UA_NodeId nodeId, UA_Boolean *outIsAbstract)
static UA_INLINE UA_StatusCode UA_Client_readSymmetricAttribute (UA_Client *client, const UA_NodeId nodeId, UA_Boolean *outSymmetric)
static UA_INLINE UA_StatusCode UA_Client_readInverseNameAttribute (UA_Client *client, const UA_NodeId nodeId, UA_LocalizedText *outInverseName)
static UA_INLINE UA_StatusCode UA_Client_readContainsNoLoopsAttribute (UA_Client *client, const UA_NodeId nodeId, UA_Boolean *outContainsNoLoops)
static UA_INLINE UA_StatusCode UA_Client_readEventNotifierAttribute (UA_Client *client, const UA_NodeId nodeId, UA_Byte *outEventNotifier)
static UA_INLINE UA_StatusCode UA_Client_readValueAttribute (UA_Client *client, const UA_NodeId nodeId, UA_Variant *outValue)
static UA_INLINE UA_StatusCode UA_Client_readDataTypeAttribute (UA_Client *client, const UA_NodeId nodeId, UA_NodeId *outDataType)
static UA_INLINE UA_StatusCode UA_Client_readValueRankAttribute (UA_Client *client, const UA_NodeId nodeId, UA_Int32 *outValueRank)
UA_StatusCode UA_EXPORT UA_Client_readArrayDimensionsAttribute (UA_Client *client, const UA_NodeId nodeId, size_t *outArrayDimensionsSize, UA_UInt32 **outArrayDimensions)
static UA_INLINE UA_StatusCode UA_Client_readAccessLevelAttribute (UA_Client *client, const UA_NodeId nodeId, UA_Byte *outAccessLevel)
static UA_INLINE UA_StatusCode UA_Client_readUserAccessLevelAttribute (UA_Client *client, const UA_NodeId nodeId, UA_Byte *outUserAccessLevel)
static UA_INLINE UA_StatusCode UA_Client_readMinimumSamplingIntervalAttribute (UA_Client *client, const UA_NodeId nodeId, UA_Double *outMinSamplingInterval)
static UA_INLINE UA_StatusCode UA_Client_readHistorizingAttribute (UA_Client *client, const UA_NodeId nodeId, UA_Boolean *outHistorizing)
static UA_INLINE UA_StatusCode UA_Client_readExecutableAttribute (UA_Client *client, const UA_NodeId nodeId, UA_Boolean *outExecutable)
static UA_INLINE UA_StatusCode UA_Client_readUserExecutableAttribute (UA_Client *client, const UA_NodeId nodeId, UA_Boolean *outUserExecutable)
UA_StatusCode UA_EXPORT UA_Client_HistoryRead_events (UA_Client *client, const UA_NodeId *nodeId, const UA_HistoricalIteratorCallback callback, UA_DateTime startTime, UA_DateTime endTime, UA_String indexRange, const UA_EventFilter filter, UA_UInt32 numValuesPerNode, UA_TimestampsToReturn timestampsToReturn, void *callbackContext)
UA_StatusCode UA_EXPORT UA_Client_HistoryRead_raw (UA_Client *client, const UA_NodeId *nodeId, const UA_HistoricalIteratorCallback callback, UA_DateTime startTime, UA_DateTime endTime, UA_String indexRange, UA_Boolean returnBounds, UA_UInt32 numValuesPerNode, UA_TimestampsToReturn timestampsToReturn, void *callbackContext)
UA_StatusCode UA_EXPORT UA_Client_HistoryRead_modified (UA_Client *client, const UA_NodeId *nodeId, const UA_HistoricalIteratorCallback callback, UA_DateTime startTime, UA_DateTime endTime, UA_String indexRange, UA_Boolean returnBounds, UA_UInt32 numValuesPerNode, UA_TimestampsToReturn timestampsToReturn, void *callbackContext)
UA_StatusCode UA_EXPORT UA_Client_HistoryUpdate_insert (UA_Client *client, const UA_NodeId *nodeId, UA_DataValue *value)
UA_StatusCode UA_EXPORT UA_Client_HistoryUpdate_replace (UA_Client *client, const UA_NodeId *nodeId, UA_DataValue *value)
UA_StatusCode UA_EXPORT UA_Client_HistoryUpdate_update (UA_Client *client, const UA_NodeId *nodeId, UA_DataValue *value)
UA_StatusCode UA_EXPORT UA_Client_HistoryUpdate_deleteRaw (UA_Client *client, const UA_NodeId *nodeId, UA_DateTime startTimestamp, UA_DateTime endTimestamp)
UA_StatusCode UA_EXPORT __UA_Client_writeAttribute (UA_Client *client, const UA_NodeId *nodeId, UA_AttributeId attributeId, const void *in, const UA_DataType *inDataType)
static UA_INLINE UA_StatusCode UA_Client_writeNodeIdAttribute (UA_Client *client, const UA_NodeId nodeId, const UA_NodeId *newNodeId)
static UA_INLINE UA_StatusCode UA_Client_writeNodeClassAttribute (UA_Client *client, const UA_NodeId nodeId, const UA_NodeClass *newNodeClass)
static UA_INLINE UA_StatusCode UA_Client_writeBrowseNameAttribute (UA_Client *client, const UA_NodeId nodeId, const UA_QualifiedName *newBrowseName)
static UA_INLINE UA_StatusCode UA_Client_writeDisplayNameAttribute (UA_Client *client, const UA_NodeId nodeId, const UA_LocalizedText *newDisplayName)
static UA_INLINE UA_StatusCode UA_Client_writeDescriptionAttribute (UA_Client *client, const UA_NodeId nodeId, const UA_LocalizedText *newDescription)
static UA_INLINE UA_StatusCode UA_Client_writeWriteMaskAttribute (UA_Client *client, const UA_NodeId nodeId, const UA_UInt32 *newWriteMask)
static UA_INLINE UA_StatusCode UA_Client_writeUserWriteMaskAttribute (UA_Client *client, const UA_NodeId nodeId, const UA_UInt32 *newUserWriteMask)
static UA_INLINE UA_StatusCode UA_Client_writeIsAbstractAttribute (UA_Client *client, const UA_NodeId nodeId, const UA_Boolean *newIsAbstract)
static UA_INLINE UA_StatusCode UA_Client_writeSymmetricAttribute (UA_Client *client, const UA_NodeId nodeId, const UA_Boolean *newSymmetric)
static UA_INLINE UA_StatusCode UA_Client_writeInverseNameAttribute (UA_Client *client, const UA_NodeId nodeId, const UA_LocalizedText *newInverseName)
static UA_INLINE UA_StatusCode UA_Client_writeContainsNoLoopsAttribute (UA_Client *client, const UA_NodeId nodeId, const UA_Boolean *newContainsNoLoops)
static UA_INLINE UA_StatusCode UA_Client_writeEventNotifierAttribute (UA_Client *client, const UA_NodeId nodeId, const UA_Byte *newEventNotifier)
static UA_INLINE UA_StatusCode UA_Client_writeValueAttribute (UA_Client *client, const UA_NodeId nodeId, const UA_Variant *newValue)
static UA_INLINE UA_StatusCode UA_Client_writeDataTypeAttribute (UA_Client *client, const UA_NodeId nodeId, const UA_NodeId *newDataType)
static UA_INLINE UA_StatusCode UA_Client_writeValueRankAttribute (UA_Client *client, const UA_NodeId nodeId, const UA_Int32 *newValueRank)
UA_StatusCode UA_EXPORT UA_Client_writeArrayDimensionsAttribute (UA_Client *client, const UA_NodeId nodeId, size_t newArrayDimensionsSize, const UA_UInt32 *newArrayDimensions)
static UA_INLINE UA_StatusCode UA_Client_writeAccessLevelAttribute (UA_Client *client, const UA_NodeId nodeId, const UA_Byte *newAccessLevel)
static UA_INLINE UA_StatusCode UA_Client_writeUserAccessLevelAttribute (UA_Client *client, const UA_NodeId nodeId, const UA_Byte *newUserAccessLevel)
static UA_INLINE UA_StatusCode UA_Client_writeMinimumSamplingIntervalAttribute (UA_Client *client, const UA_NodeId nodeId, const UA_Double *newMinInterval)
static UA_INLINE UA_StatusCode UA_Client_writeHistorizingAttribute (UA_Client *client, const UA_NodeId nodeId, const UA_Boolean *newHistorizing)
static UA_INLINE UA_StatusCode UA_Client_writeExecutableAttribute (UA_Client *client, const UA_NodeId nodeId, const UA_Boolean *newExecutable)
static UA_INLINE UA_StatusCode UA_Client_writeUserExecutableAttribute (UA_Client *client, const UA_NodeId nodeId, const UA_Boolean *newUserExecutable)
UA_StatusCode UA_EXPORT UA_Client_call (UA_Client *client, const UA_NodeId objectId, const UA_NodeId methodId, size_t inputSize, const UA_Variant *input, size_t *outputSize, UA_Variant **output)
UA_StatusCode UA_EXPORT UA_Client_addReference (UA_Client *client, const UA_NodeId sourceNodeId, const UA_NodeId referenceTypeId, UA_Boolean isForward, const UA_String targetServerUri, const UA_ExpandedNodeId targetNodeId, UA_NodeClass targetNodeClass)
UA_StatusCode UA_EXPORT UA_Client_deleteReference (UA_Client *client, const UA_NodeId sourceNodeId, const UA_NodeId referenceTypeId, UA_Boolean isForward, const UA_ExpandedNodeId targetNodeId, UA_Boolean deleteBidirectional)
UA_StatusCode UA_EXPORT UA_Client_deleteNode (UA_Client *client, const UA_NodeId nodeId, UA_Boolean deleteTargetReferences)
UA_StatusCode UA_EXPORT __UA_Client_addNode (UA_Client *client, const UA_NodeClass nodeClass, const UA_NodeId requestedNewNodeId, const UA_NodeId parentNodeId, const UA_NodeId referenceTypeId, const UA_QualifiedName browseName, const UA_NodeId typeDefinition, const UA_NodeAttributes *attr, const UA_DataType *attributeType, UA_NodeId *outNewNodeId)
static UA_INLINE UA_StatusCode UA_Client_addVariableNode (UA_Client *client, const UA_NodeId requestedNewNodeId, const UA_NodeId parentNodeId, const UA_NodeId referenceTypeId, const UA_QualifiedName browseName, const UA_NodeId typeDefinition, const UA_VariableAttributes attr, UA_NodeId *outNewNodeId)
static UA_INLINE UA_StatusCode UA_Client_addVariableTypeNode (UA_Client *client, const UA_NodeId requestedNewNodeId, const UA_NodeId parentNodeId, const UA_NodeId referenceTypeId, const UA_QualifiedName browseName, const UA_VariableTypeAttributes attr, UA_NodeId *outNewNodeId)
static UA_INLINE UA_StatusCode UA_Client_addObjectNode (UA_Client *client, const UA_NodeId requestedNewNodeId, const UA_NodeId parentNodeId, const UA_NodeId referenceTypeId, const UA_QualifiedName browseName, const UA_NodeId typeDefinition, const UA_ObjectAttributes attr, UA_NodeId *outNewNodeId)
static UA_INLINE UA_StatusCode UA_Client_addObjectTypeNode (UA_Client *client, const UA_NodeId requestedNewNodeId, const UA_NodeId parentNodeId, const UA_NodeId referenceTypeId, const UA_QualifiedName browseName, const UA_ObjectTypeAttributes attr, UA_NodeId *outNewNodeId)
static UA_INLINE UA_StatusCode UA_Client_addViewNode (UA_Client *client, const UA_NodeId requestedNewNodeId, const UA_NodeId parentNodeId, const UA_NodeId referenceTypeId, const UA_QualifiedName browseName, const UA_ViewAttributes attr, UA_NodeId *outNewNodeId)
static UA_INLINE UA_StatusCode UA_Client_addReferenceTypeNode (UA_Client *client, const UA_NodeId requestedNewNodeId, const UA_NodeId parentNodeId, const UA_NodeId referenceTypeId, const UA_QualifiedName browseName, const UA_ReferenceTypeAttributes attr, UA_NodeId *outNewNodeId)
static UA_INLINE UA_StatusCode UA_Client_addDataTypeNode (UA_Client *client, const UA_NodeId requestedNewNodeId, const UA_NodeId parentNodeId, const UA_NodeId referenceTypeId, const UA_QualifiedName browseName, const UA_DataTypeAttributes attr, UA_NodeId *outNewNodeId)
static UA_INLINE UA_StatusCode UA_Client_addMethodNode (UA_Client *client, const UA_NodeId requestedNewNodeId, const UA_NodeId parentNodeId, const UA_NodeId referenceTypeId, const UA_QualifiedName browseName, const UA_MethodAttributes attr, UA_NodeId *outNewNodeId)
UA_StatusCode UA_EXPORT UA_Client_NamespaceGetIndex (UA_Client *client, UA_String *namespaceUri, UA_UInt16 *namespaceIndex)
UA_StatusCode UA_EXPORT UA_Client_forEachChildNodeCall (UA_Client *client, UA_NodeId parentNodeId, UA_NodeIteratorCallback callback, void *handle)
Variables
UA_EXPORT const UA_VariableAttributes UA_VariableAttributes_default
UA_EXPORT const UA_VariableTypeAttributes UA_VariableTypeAttributes_default
UA_EXPORT const UA_MethodAttributes UA_MethodAttributes_default
UA_EXPORT const UA_ObjectAttributes UA_ObjectAttributes_default
UA_EXPORT const UA_ObjectTypeAttributes UA_ObjectTypeAttributes_default
UA_EXPORT const UA_ReferenceTypeAttributes UA_ReferenceTypeAttributes_default
UA_EXPORT const UA_DataTypeAttributes UA_DataTypeAttributes_default
UA_EXPORT const UA_ViewAttributes UA_ViewAttributes_default
Typedef Documentation
UA_HistoricalIteratorCallback
typedef UA_Boolean(* UA_HistoricalIteratorCallback) (UA_Client *client, const UA_NodeId *nodeId, UA_Boolean moreDataAvailable, const UA_ExtensionObject *data, void *callbackContext)
Historical Access ^^^^^^^^^^^^^^^^^ The following functions can be used to read a single node historically. Use the regular service to read several nodes at once.
Definition at line 223 of file client_highlevel.h.
UA_NodeIteratorCallback
typedef UA_StatusCode(* UA_NodeIteratorCallback) (UA_NodeId childId, UA_Boolean isInverse, UA_NodeId referenceTypeId, void *handle)
Definition at line 650 of file client_highlevel.h.
Function Documentation
__UA_Client_addNode()
UA_StatusCode UA_EXPORT __UA_Client_addNode (UA_Client * client, const UA_NodeClass nodeClass, const UA_NodeId requestedNewNodeId, const UA_NodeId parentNodeId, const UA_NodeId referenceTypeId, const UA_QualifiedName browseName, const UA_NodeId typeDefinition, const UA_NodeAttributes * attr, const UA_DataType * attributeType, UA_NodeId * outNewNodeId)
Referenced by UA_Client_addDataTypeNode(), UA_Client_addMethodNode(), UA_Client_addObjectNode(), UA_Client_addObjectTypeNode(), UA_Client_addReferenceTypeNode(), UA_Client_addVariableNode(), UA_Client_addVariableTypeNode(), UA_Client_addViewNode(), and UA_Client_writeUserExecutableAttribute().
__UA_Client_readAttribute()
_UA_BEGIN_DECLS UA_StatusCode UA_EXPORT __UA_Client_readAttribute (UA_Client * client, const UA_NodeId * nodeId, UA_AttributeId attributeId, void * out, const UA_DataType * outDataType)
.. _client-highlevel:
Highlevel Client Functionality
The following definitions are convenience functions making use of the standard OPC UA services in the background. This is a less flexible way of handling the stack, because at many places sensible defaults are presumed; at the same time using these functions is the easiest way of implementing an OPC UA application, as you will not have to consider all the details that go into the OPC UA services. If more flexibility is needed, you can always achieve the same functionality using the raw :ref:OPC UA services <client-services>.
Read Attributes ^^^^^^^^^^^^^^^ The following functions can be used to retrieve a single node attribute. Use the regular service to read several attributes at once.
Referenced by UA_Client_readAccessLevelAttribute(), UA_Client_readBrowseNameAttribute(), UA_Client_readContainsNoLoopsAttribute(), UA_Client_readDataTypeAttribute(), UA_Client_readDescriptionAttribute(), UA_Client_readDisplayNameAttribute(), UA_Client_readEventNotifierAttribute(), UA_Client_readExecutableAttribute(), UA_Client_readHistorizingAttribute(), UA_Client_readInverseNameAttribute(), UA_Client_readIsAbstractAttribute(), UA_Client_readMinimumSamplingIntervalAttribute(), UA_Client_readNodeClassAttribute(), UA_Client_readNodeIdAttribute(), UA_Client_readSymmetricAttribute(), UA_Client_readUserAccessLevelAttribute(), UA_Client_readUserExecutableAttribute(), UA_Client_readUserWriteMaskAttribute(), UA_Client_readValueAttribute(), UA_Client_readValueRankAttribute(), and UA_Client_readWriteMaskAttribute().
__UA_Client_writeAttribute()
UA_StatusCode UA_EXPORT __UA_Client_writeAttribute (UA_Client * client, const UA_NodeId * nodeId, UA_AttributeId attributeId, const void * in, const UA_DataType * inDataType)
Write Attributes ^^^^^^^^^^^^^^^^
The following functions can be use to write a single node attribute at a time. Use the regular write service to write several attributes at once.
Referenced by UA_Client_writeAccessLevelAttribute(), UA_Client_writeBrowseNameAttribute(), UA_Client_writeContainsNoLoopsAttribute(), UA_Client_writeDataTypeAttribute(), UA_Client_writeDescriptionAttribute(), UA_Client_writeDisplayNameAttribute(), UA_Client_writeEventNotifierAttribute(), UA_Client_writeExecutableAttribute(), UA_Client_writeHistorizingAttribute(), UA_Client_writeInverseNameAttribute(), UA_Client_writeIsAbstractAttribute(), UA_Client_writeMinimumSamplingIntervalAttribute(), UA_Client_writeNodeClassAttribute(), UA_Client_writeNodeIdAttribute(), UA_Client_writeSymmetricAttribute(), UA_Client_writeUserAccessLevelAttribute(), UA_Client_writeUserExecutableAttribute(), UA_Client_writeUserWriteMaskAttribute(), UA_Client_writeValueAttribute(), UA_Client_writeValueRankAttribute(), and UA_Client_writeWriteMaskAttribute().
UA_Client_addDataTypeNode()
static UA_INLINE UA_StatusCode UA_Client_addDataTypeNode (UA_Client * client, const UA_NodeId requestedNewNodeId, const UA_NodeId parentNodeId, const UA_NodeId referenceTypeId, const UA_QualifiedName browseName, const UA_DataTypeAttributes attr, UA_NodeId * outNewNodeId) static
Definition at line 605 of file client_highlevel.h.
References __UA_Client_addNode(), UA_NODECLASS_DATATYPE, UA_NODEID_NULL, and UA_TYPES.
UA_Client_addMethodNode()
static UA_INLINE UA_StatusCode UA_Client_addMethodNode (UA_Client * client, const UA_NodeId requestedNewNodeId, const UA_NodeId parentNodeId, const UA_NodeId referenceTypeId, const UA_QualifiedName browseName, const UA_MethodAttributes attr, UA_NodeId * outNewNodeId) static
Definition at line 619 of file client_highlevel.h.
References __UA_Client_addNode(), UA_Client_NamespaceGetIndex(), UA_NODECLASS_METHOD, UA_NODEID_NULL, and UA_TYPES.
UA_Client_addObjectNode()
static UA_INLINE UA_StatusCode UA_Client_addObjectNode (UA_Client * client, const UA_NodeId requestedNewNodeId, const UA_NodeId parentNodeId, const UA_NodeId referenceTypeId, const UA_QualifiedName browseName, const UA_NodeId typeDefinition, const UA_ObjectAttributes attr, UA_NodeId * outNewNodeId) static
Definition at line 549 of file client_highlevel.h.
References __UA_Client_addNode(), UA_NODECLASS_OBJECT, and UA_TYPES.
UA_Client_addObjectTypeNode()
static UA_INLINE UA_StatusCode UA_Client_addObjectTypeNode (UA_Client * client, const UA_NodeId requestedNewNodeId, const UA_NodeId parentNodeId, const UA_NodeId referenceTypeId, const UA_QualifiedName browseName, const UA_ObjectTypeAttributes attr, UA_NodeId * outNewNodeId) static
Definition at line 562 of file client_highlevel.h.
References __UA_Client_addNode(), UA_NODECLASS_OBJECTTYPE, UA_NODEID_NULL, and UA_TYPES.
UA_Client_addReference()
UA_StatusCode UA_EXPORT UA_Client_addReference (UA_Client * client, const UA_NodeId sourceNodeId, const UA_NodeId referenceTypeId, UA_Boolean isForward, const UA_String targetServerUri, const UA_ExpandedNodeId targetNodeId, UA_NodeClass targetNodeClass)
Node Management ^^^^^^^^^^^^^^^ See the section on :ref:server-side node management <addnodes>.
Referenced by UA_Client_writeUserExecutableAttribute().
UA_Client_addReferenceTypeNode()
static UA_INLINE UA_StatusCode UA_Client_addReferenceTypeNode (UA_Client * client, const UA_NodeId requestedNewNodeId, const UA_NodeId parentNodeId, const UA_NodeId referenceTypeId, const UA_QualifiedName browseName, const UA_ReferenceTypeAttributes attr, UA_NodeId * outNewNodeId) static
Definition at line 589 of file client_highlevel.h.
References __UA_Client_addNode(), UA_NODECLASS_REFERENCETYPE, UA_NODEID_NULL, and UA_TYPES.
UA_Client_addVariableNode()
static UA_INLINE UA_StatusCode UA_Client_addVariableNode (UA_Client * client, const UA_NodeId requestedNewNodeId, const UA_NodeId parentNodeId, const UA_NodeId referenceTypeId, const UA_QualifiedName browseName, const UA_NodeId typeDefinition, const UA_VariableAttributes attr, UA_NodeId * outNewNodeId) static
Definition at line 518 of file client_highlevel.h.
References __UA_Client_addNode(), UA_NODECLASS_VARIABLE, and UA_TYPES.
UA_Client_addVariableTypeNode()
static UA_INLINE UA_StatusCode UA_Client_addVariableTypeNode (UA_Client * client, const UA_NodeId requestedNewNodeId, const UA_NodeId parentNodeId, const UA_NodeId referenceTypeId, const UA_QualifiedName browseName, const UA_VariableTypeAttributes attr, UA_NodeId * outNewNodeId) static
Definition at line 533 of file client_highlevel.h.
References __UA_Client_addNode(), UA_NODECLASS_VARIABLETYPE, UA_NODEID_NULL, and UA_TYPES.
UA_Client_addViewNode()
static UA_INLINE UA_StatusCode UA_Client_addViewNode (UA_Client * client, const UA_NodeId requestedNewNodeId, const UA_NodeId parentNodeId, const UA_NodeId referenceTypeId, const UA_QualifiedName browseName, const UA_ViewAttributes attr, UA_NodeId * outNewNodeId) static
Definition at line 576 of file client_highlevel.h.
References __UA_Client_addNode(), UA_NODECLASS_VIEW, UA_NODEID_NULL, and UA_TYPES.
UA_Client_call()
UA_StatusCode UA_EXPORT UA_Client_call (UA_Client * client, const UA_NodeId objectId, const UA_NodeId methodId, size_t inputSize, const UA_Variant * input, size_t * outputSize, UA_Variant ** output)
Method Calling ^^^^^^^^^^^^^^
Referenced by UA_Client_writeUserExecutableAttribute().
UA_Client_deleteNode()
UA_StatusCode UA_EXPORT UA_Client_deleteNode (UA_Client * client, const UA_NodeId nodeId, UA_Boolean deleteTargetReferences)
Referenced by UA_Client_writeUserExecutableAttribute().
UA_Client_deleteReference()
UA_StatusCode UA_EXPORT UA_Client_deleteReference (UA_Client * client, const UA_NodeId sourceNodeId, const UA_NodeId referenceTypeId, UA_Boolean isForward, const UA_ExpandedNodeId targetNodeId, UA_Boolean deleteBidirectional)
Referenced by UA_Client_writeUserExecutableAttribute().
UA_Client_forEachChildNodeCall()
UA_StatusCode UA_EXPORT UA_Client_forEachChildNodeCall (UA_Client * client, UA_NodeId parentNodeId, UA_NodeIteratorCallback callback, void * handle)
UA_Client_HistoryRead_events()
UA_StatusCode UA_EXPORT UA_Client_HistoryRead_events (UA_Client * client, const UA_NodeId * nodeId, const UA_HistoricalIteratorCallback callback, UA_DateTime startTime, UA_DateTime endTime, UA_String indexRange, const UA_EventFilter filter, UA_UInt32 numValuesPerNode, UA_TimestampsToReturn timestampsToReturn, void * callbackContext)
UA_Client_HistoryRead_modified()
UA_StatusCode UA_EXPORT UA_Client_HistoryRead_modified (UA_Client * client, const UA_NodeId * nodeId, const UA_HistoricalIteratorCallback callback, UA_DateTime startTime, UA_DateTime endTime, UA_String indexRange, UA_Boolean returnBounds, UA_UInt32 numValuesPerNode, UA_TimestampsToReturn timestampsToReturn, void * callbackContext)
UA_Client_HistoryRead_raw()
UA_StatusCode UA_EXPORT UA_Client_HistoryRead_raw (UA_Client * client, const UA_NodeId * nodeId, const UA_HistoricalIteratorCallback callback, UA_DateTime startTime, UA_DateTime endTime, UA_String indexRange, UA_Boolean returnBounds, UA_UInt32 numValuesPerNode, UA_TimestampsToReturn timestampsToReturn, void * callbackContext)
UA_Client_HistoryUpdate_deleteRaw()
UA_StatusCode UA_EXPORT UA_Client_HistoryUpdate_deleteRaw (UA_Client * client, const UA_NodeId * nodeId, UA_DateTime startTimestamp, UA_DateTime endTimestamp)
UA_Client_HistoryUpdate_insert()
UA_StatusCode UA_EXPORT UA_Client_HistoryUpdate_insert (UA_Client * client, const UA_NodeId * nodeId, UA_DataValue * value)
UA_Client_HistoryUpdate_replace()
UA_StatusCode UA_EXPORT UA_Client_HistoryUpdate_replace (UA_Client * client, const UA_NodeId * nodeId, UA_DataValue * value)
UA_Client_HistoryUpdate_update()
UA_StatusCode UA_EXPORT UA_Client_HistoryUpdate_update (UA_Client * client, const UA_NodeId * nodeId, UA_DataValue * value)
UA_Client_NamespaceGetIndex()
UA_StatusCode UA_EXPORT UA_Client_NamespaceGetIndex (UA_Client * client, UA_String * namespaceUri, UA_UInt16 * namespaceIndex)
Misc Highlevel Functionality ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Referenced by UA_Client_addMethodNode().
UA_Client_readAccessLevelAttribute()
static UA_INLINE UA_StatusCode UA_Client_readAccessLevelAttribute (UA_Client * client, const UA_NodeId nodeId, UA_Byte * outAccessLevel) static
Definition at line 167 of file client_highlevel.h.
References __UA_Client_readAttribute(), UA_ATTRIBUTEID_ACCESSLEVEL, and UA_TYPES.
UA_Client_readArrayDimensionsAttribute()
UA_StatusCode UA_EXPORT UA_Client_readArrayDimensionsAttribute (UA_Client * client, const UA_NodeId nodeId, size_t * outArrayDimensionsSize, UA_UInt32 ** outArrayDimensions)
Referenced by UA_Client_readValueRankAttribute().
UA_Client_readBrowseNameAttribute()
static UA_INLINE UA_StatusCode UA_Client_readBrowseNameAttribute (UA_Client * client, const UA_NodeId nodeId, UA_QualifiedName * outBrowseName) static
Definition at line 63 of file client_highlevel.h.
References __UA_Client_readAttribute(), UA_ATTRIBUTEID_BROWSENAME, and UA_TYPES.
UA_Client_readContainsNoLoopsAttribute()
static UA_INLINE UA_StatusCode UA_Client_readContainsNoLoopsAttribute (UA_Client * client, const UA_NodeId nodeId, UA_Boolean * outContainsNoLoops) static
Definition at line 125 of file client_highlevel.h.
References __UA_Client_readAttribute(), UA_ATTRIBUTEID_CONTAINSNOLOOPS, and UA_TYPES.
UA_Client_readDataTypeAttribute()
static UA_INLINE UA_StatusCode UA_Client_readDataTypeAttribute (UA_Client * client, const UA_NodeId nodeId, UA_NodeId * outDataType) static
Definition at line 148 of file client_highlevel.h.
References __UA_Client_readAttribute(), UA_ATTRIBUTEID_DATATYPE, and UA_TYPES.
UA_Client_readDescriptionAttribute()
static UA_INLINE UA_StatusCode UA_Client_readDescriptionAttribute (UA_Client * client, const UA_NodeId nodeId, UA_LocalizedText * outDescription) static
Definition at line 79 of file client_highlevel.h.
References __UA_Client_readAttribute(), UA_ATTRIBUTEID_DESCRIPTION, and UA_TYPES.
UA_Client_readDisplayNameAttribute()
static UA_INLINE UA_StatusCode UA_Client_readDisplayNameAttribute (UA_Client * client, const UA_NodeId nodeId, UA_LocalizedText * outDisplayName) static
Definition at line 71 of file client_highlevel.h.
References __UA_Client_readAttribute(), UA_ATTRIBUTEID_DISPLAYNAME, and UA_TYPES.
UA_Client_readEventNotifierAttribute()
static UA_INLINE UA_StatusCode UA_Client_readEventNotifierAttribute (UA_Client * client, const UA_NodeId nodeId, UA_Byte * outEventNotifier) static
Definition at line 134 of file client_highlevel.h.
References __UA_Client_readAttribute(), UA_ATTRIBUTEID_EVENTNOTIFIER, and UA_TYPES.
UA_Client_readExecutableAttribute()
static UA_INLINE UA_StatusCode UA_Client_readExecutableAttribute (UA_Client * client, const UA_NodeId nodeId, UA_Boolean * outExecutable) static
Definition at line 200 of file client_highlevel.h.
References __UA_Client_readAttribute(), UA_ATTRIBUTEID_EXECUTABLE, and UA_TYPES.
UA_Client_readHistorizingAttribute()
static UA_INLINE UA_StatusCode UA_Client_readHistorizingAttribute (UA_Client * client, const UA_NodeId nodeId, UA_Boolean * outHistorizing) static
Definition at line 193 of file client_highlevel.h.
References __UA_Client_readAttribute(), UA_ATTRIBUTEID_HISTORIZING, and UA_TYPES.
UA_Client_readInverseNameAttribute()
static UA_INLINE UA_StatusCode UA_Client_readInverseNameAttribute (UA_Client * client, const UA_NodeId nodeId, UA_LocalizedText * outInverseName) static
Definition at line 117 of file client_highlevel.h.
References __UA_Client_readAttribute(), UA_ATTRIBUTEID_INVERSENAME, and UA_TYPES.
UA_Client_readIsAbstractAttribute()
static UA_INLINE UA_StatusCode UA_Client_readIsAbstractAttribute (UA_Client * client, const UA_NodeId nodeId, UA_Boolean * outIsAbstract) static
Definition at line 103 of file client_highlevel.h.
References __UA_Client_readAttribute(), UA_ATTRIBUTEID_ISABSTRACT, and UA_TYPES.
UA_Client_readMinimumSamplingIntervalAttribute()
static UA_INLINE UA_StatusCode UA_Client_readMinimumSamplingIntervalAttribute (UA_Client * client, const UA_NodeId nodeId, UA_Double * outMinSamplingInterval) static
Definition at line 183 of file client_highlevel.h.
References __UA_Client_readAttribute(), UA_ATTRIBUTEID_MINIMUMSAMPLINGINTERVAL, and UA_TYPES.
UA_Client_readNodeClassAttribute()
static UA_INLINE UA_StatusCode UA_Client_readNodeClassAttribute (UA_Client * client, const UA_NodeId nodeId, UA_NodeClass * outNodeClass) static
Definition at line 56 of file client_highlevel.h.
References __UA_Client_readAttribute(), UA_ATTRIBUTEID_NODECLASS, and UA_TYPES.
UA_Client_readNodeIdAttribute()
static UA_INLINE UA_StatusCode UA_Client_readNodeIdAttribute (UA_Client * client, const UA_NodeId nodeId, UA_NodeId * outNodeId) static
Definition at line 49 of file client_highlevel.h.
References __UA_Client_readAttribute(), UA_ATTRIBUTEID_NODEID, and UA_TYPES.
UA_Client_readSymmetricAttribute()
static UA_INLINE UA_StatusCode UA_Client_readSymmetricAttribute (UA_Client * client, const UA_NodeId nodeId, UA_Boolean * outSymmetric) static
Definition at line 110 of file client_highlevel.h.
References __UA_Client_readAttribute(), UA_ATTRIBUTEID_SYMMETRIC, and UA_TYPES.
UA_Client_readUserAccessLevelAttribute()
static UA_INLINE UA_StatusCode UA_Client_readUserAccessLevelAttribute (UA_Client * client, const UA_NodeId nodeId, UA_Byte * outUserAccessLevel) static
Definition at line 174 of file client_highlevel.h.
References __UA_Client_readAttribute(), UA_ATTRIBUTEID_USERACCESSLEVEL, and UA_TYPES.
UA_Client_readUserExecutableAttribute()
static UA_INLINE UA_StatusCode UA_Client_readUserExecutableAttribute (UA_Client * client, const UA_NodeId nodeId, UA_Boolean * outUserExecutable) static
Definition at line 207 of file client_highlevel.h.
References __UA_Client_readAttribute(), UA_ATTRIBUTEID_USEREXECUTABLE, and UA_TYPES.
UA_Client_readUserWriteMaskAttribute()
static UA_INLINE UA_StatusCode UA_Client_readUserWriteMaskAttribute (UA_Client * client, const UA_NodeId nodeId, UA_UInt32 * outUserWriteMask) static
Definition at line 94 of file client_highlevel.h.
References __UA_Client_readAttribute(), UA_ATTRIBUTEID_USERWRITEMASK, and UA_TYPES.
UA_Client_readValueAttribute()
static UA_INLINE UA_StatusCode UA_Client_readValueAttribute (UA_Client * client, const UA_NodeId nodeId, UA_Variant * outValue) static
Definition at line 141 of file client_highlevel.h.
References __UA_Client_readAttribute(), UA_ATTRIBUTEID_VALUE, and UA_TYPES.
UA_Client_readValueRankAttribute()
static UA_INLINE UA_StatusCode UA_Client_readValueRankAttribute (UA_Client * client, const UA_NodeId nodeId, UA_Int32 * outValueRank) static
Definition at line 155 of file client_highlevel.h.
References __UA_Client_readAttribute(), UA_ATTRIBUTEID_VALUERANK, UA_Client_readArrayDimensionsAttribute(), and UA_TYPES.
UA_Client_readWriteMaskAttribute()
static UA_INLINE UA_StatusCode UA_Client_readWriteMaskAttribute (UA_Client * client, const UA_NodeId nodeId, UA_UInt32 * outWriteMask) static
Definition at line 87 of file client_highlevel.h.
References __UA_Client_readAttribute(), UA_ATTRIBUTEID_WRITEMASK, and UA_TYPES.
UA_Client_writeAccessLevelAttribute()
static UA_INLINE UA_StatusCode UA_Client_writeAccessLevelAttribute (UA_Client * client, const UA_NodeId nodeId, const UA_Byte * newAccessLevel) static
Definition at line 410 of file client_highlevel.h.
References __UA_Client_writeAttribute(), UA_ATTRIBUTEID_ACCESSLEVEL, and UA_TYPES.
UA_Client_writeArrayDimensionsAttribute()
UA_StatusCode UA_EXPORT UA_Client_writeArrayDimensionsAttribute (UA_Client * client, const UA_NodeId nodeId, size_t newArrayDimensionsSize, const UA_UInt32 * newArrayDimensions)
Referenced by UA_Client_writeValueRankAttribute().
UA_Client_writeBrowseNameAttribute()
static UA_INLINE UA_StatusCode UA_Client_writeBrowseNameAttribute (UA_Client * client, const UA_NodeId nodeId, const UA_QualifiedName * newBrowseName) static
Definition at line 304 of file client_highlevel.h.
References __UA_Client_writeAttribute(), UA_ATTRIBUTEID_BROWSENAME, and UA_TYPES.
UA_Client_writeContainsNoLoopsAttribute()
static UA_INLINE UA_StatusCode UA_Client_writeContainsNoLoopsAttribute (UA_Client * client, const UA_NodeId nodeId, const UA_Boolean * newContainsNoLoops) static
Definition at line 366 of file client_highlevel.h.
References __UA_Client_writeAttribute(), UA_ATTRIBUTEID_CONTAINSNOLOOPS, and UA_TYPES.
UA_Client_writeDataTypeAttribute()
static UA_INLINE UA_StatusCode UA_Client_writeDataTypeAttribute (UA_Client * client, const UA_NodeId nodeId, const UA_NodeId * newDataType) static
Definition at line 391 of file client_highlevel.h.
References __UA_Client_writeAttribute(), UA_ATTRIBUTEID_DATATYPE, and UA_TYPES.
UA_Client_writeDescriptionAttribute()
static UA_INLINE UA_StatusCode UA_Client_writeDescriptionAttribute (UA_Client * client, const UA_NodeId nodeId, const UA_LocalizedText * newDescription) static
Definition at line 320 of file client_highlevel.h.
References __UA_Client_writeAttribute(), UA_ATTRIBUTEID_DESCRIPTION, and UA_TYPES.
UA_Client_writeDisplayNameAttribute()
static UA_INLINE UA_StatusCode UA_Client_writeDisplayNameAttribute (UA_Client * client, const UA_NodeId nodeId, const UA_LocalizedText * newDisplayName) static
Definition at line 312 of file client_highlevel.h.
References __UA_Client_writeAttribute(), UA_ATTRIBUTEID_DISPLAYNAME, and UA_TYPES.
UA_Client_writeEventNotifierAttribute()
static UA_INLINE UA_StatusCode UA_Client_writeEventNotifierAttribute (UA_Client * client, const UA_NodeId nodeId, const UA_Byte * newEventNotifier) static
Definition at line 375 of file client_highlevel.h.
References __UA_Client_writeAttribute(), UA_ATTRIBUTEID_EVENTNOTIFIER, and UA_TYPES.
UA_Client_writeExecutableAttribute()
static UA_INLINE UA_StatusCode UA_Client_writeExecutableAttribute (UA_Client * client, const UA_NodeId nodeId, const UA_Boolean * newExecutable) static
Definition at line 442 of file client_highlevel.h.
References __UA_Client_writeAttribute(), UA_ATTRIBUTEID_EXECUTABLE, and UA_TYPES.
UA_Client_writeHistorizingAttribute()
static UA_INLINE UA_StatusCode UA_Client_writeHistorizingAttribute (UA_Client * client, const UA_NodeId nodeId, const UA_Boolean * newHistorizing) static
Definition at line 435 of file client_highlevel.h.
References __UA_Client_writeAttribute(), UA_ATTRIBUTEID_HISTORIZING, and UA_TYPES.
UA_Client_writeInverseNameAttribute()
static UA_INLINE UA_StatusCode UA_Client_writeInverseNameAttribute (UA_Client * client, const UA_NodeId nodeId, const UA_LocalizedText * newInverseName) static
Definition at line 358 of file client_highlevel.h.
References __UA_Client_writeAttribute(), UA_ATTRIBUTEID_INVERSENAME, and UA_TYPES.
UA_Client_writeIsAbstractAttribute()
static UA_INLINE UA_StatusCode UA_Client_writeIsAbstractAttribute (UA_Client * client, const UA_NodeId nodeId, const UA_Boolean * newIsAbstract) static
Definition at line 344 of file client_highlevel.h.
References __UA_Client_writeAttribute(), UA_ATTRIBUTEID_ISABSTRACT, and UA_TYPES.
UA_Client_writeMinimumSamplingIntervalAttribute()
static UA_INLINE UA_StatusCode UA_Client_writeMinimumSamplingIntervalAttribute (UA_Client * client, const UA_NodeId nodeId, const UA_Double * newMinInterval) static
Definition at line 426 of file client_highlevel.h.
References __UA_Client_writeAttribute(), UA_ATTRIBUTEID_MINIMUMSAMPLINGINTERVAL, and UA_TYPES.
UA_Client_writeNodeClassAttribute()
static UA_INLINE UA_StatusCode UA_Client_writeNodeClassAttribute (UA_Client * client, const UA_NodeId nodeId, const UA_NodeClass * newNodeClass) static
Definition at line 297 of file client_highlevel.h.
References __UA_Client_writeAttribute(), UA_ATTRIBUTEID_NODECLASS, and UA_TYPES.
UA_Client_writeNodeIdAttribute()
static UA_INLINE UA_StatusCode UA_Client_writeNodeIdAttribute (UA_Client * client, const UA_NodeId nodeId, const UA_NodeId * newNodeId) static
Definition at line 290 of file client_highlevel.h.
References __UA_Client_writeAttribute(), UA_ATTRIBUTEID_NODEID, and UA_TYPES.
UA_Client_writeSymmetricAttribute()
static UA_INLINE UA_StatusCode UA_Client_writeSymmetricAttribute (UA_Client * client, const UA_NodeId nodeId, const UA_Boolean * newSymmetric) static
Definition at line 351 of file client_highlevel.h.
References __UA_Client_writeAttribute(), UA_ATTRIBUTEID_SYMMETRIC, and UA_TYPES.
UA_Client_writeUserAccessLevelAttribute()
static UA_INLINE UA_StatusCode UA_Client_writeUserAccessLevelAttribute (UA_Client * client, const UA_NodeId nodeId, const UA_Byte * newUserAccessLevel) static
Definition at line 417 of file client_highlevel.h.
References __UA_Client_writeAttribute(), UA_ATTRIBUTEID_USERACCESSLEVEL, and UA_TYPES.
UA_Client_writeUserExecutableAttribute()
static UA_INLINE UA_StatusCode UA_Client_writeUserExecutableAttribute (UA_Client * client, const UA_NodeId nodeId, const UA_Boolean * newUserExecutable) static
Definition at line 449 of file client_highlevel.h.
References __UA_Client_addNode(), __UA_Client_writeAttribute(), UA_ATTRIBUTEID_USEREXECUTABLE, UA_Client_addReference(), UA_Client_call(), UA_Client_deleteNode(), UA_Client_deleteReference(), UA_DataTypeAttributes_default, UA_MethodAttributes_default, UA_ObjectAttributes_default, UA_ObjectTypeAttributes_default, UA_ReferenceTypeAttributes_default, UA_TYPES, UA_VariableAttributes_default, UA_VariableTypeAttributes_default, and UA_ViewAttributes_default.
UA_Client_writeUserWriteMaskAttribute()
static UA_INLINE UA_StatusCode UA_Client_writeUserWriteMaskAttribute (UA_Client * client, const UA_NodeId nodeId, const UA_UInt32 * newUserWriteMask) static
Definition at line 335 of file client_highlevel.h.
References __UA_Client_writeAttribute(), UA_ATTRIBUTEID_USERWRITEMASK, and UA_TYPES.
UA_Client_writeValueAttribute()
static UA_INLINE UA_StatusCode UA_Client_writeValueAttribute (UA_Client * client, const UA_NodeId nodeId, const UA_Variant * newValue) static
Definition at line 384 of file client_highlevel.h.
References __UA_Client_writeAttribute(), UA_ATTRIBUTEID_VALUE, and UA_TYPES.
UA_Client_writeValueRankAttribute()
static UA_INLINE UA_StatusCode UA_Client_writeValueRankAttribute (UA_Client * client, const UA_NodeId nodeId, const UA_Int32 * newValueRank) static
Definition at line 398 of file client_highlevel.h.
References __UA_Client_writeAttribute(), UA_ATTRIBUTEID_VALUERANK, UA_Client_writeArrayDimensionsAttribute(), and UA_TYPES.
UA_Client_writeWriteMaskAttribute()
static UA_INLINE UA_StatusCode UA_Client_writeWriteMaskAttribute (UA_Client * client, const UA_NodeId nodeId, const UA_UInt32 * newWriteMask) static
Definition at line 328 of file client_highlevel.h.
References __UA_Client_writeAttribute(), UA_ATTRIBUTEID_WRITEMASK, and UA_TYPES.
Variable Documentation
UA_DataTypeAttributes_default
UA_EXPORT const UA_DataTypeAttributes UA_DataTypeAttributes_default
Referenced by function_namespace0_generated_10_begin(), function_namespace0_generated_11_begin(), function_namespace0_generated_12_begin(), function_namespace0_generated_13_begin(), function_namespace0_generated_14_begin(), function_namespace0_generated_15_begin(), function_namespace0_generated_16_begin(), function_namespace0_generated_17_begin(), function_namespace0_generated_18_begin(), function_namespace0_generated_19_begin(), function_namespace0_generated_20_begin(), function_namespace0_generated_21_begin(), function_namespace0_generated_22_begin(), function_namespace0_generated_23_begin(), function_namespace0_generated_24_begin(), function_namespace0_generated_25_begin(), function_namespace0_generated_26_begin(), function_namespace0_generated_27_begin(), function_namespace0_generated_28_begin(), function_namespace0_generated_29_begin(), function_namespace0_generated_2_begin(), function_namespace0_generated_30_begin(), function_namespace0_generated_31_begin(), function_namespace0_generated_32_begin(), function_namespace0_generated_33_begin(), function_namespace0_generated_35_begin(), function_namespace0_generated_37_begin(), function_namespace0_generated_3_begin(), function_namespace0_generated_43_begin(), function_namespace0_generated_44_begin(), function_namespace0_generated_45_begin(), function_namespace0_generated_46_begin(), function_namespace0_generated_47_begin(), function_namespace0_generated_48_begin(), function_namespace0_generated_49_begin(), function_namespace0_generated_4_begin(), function_namespace0_generated_50_begin(), function_namespace0_generated_5_begin(), function_namespace0_generated_6_begin(), function_namespace0_generated_7_begin(), function_namespace0_generated_8_begin(), function_namespace0_generated_9_begin(), and UA_Client_writeUserExecutableAttribute().
UA_MethodAttributes_default
UA_EXPORT const UA_MethodAttributes UA_MethodAttributes_default
Referenced by function_namespace0_generated_96_begin(), and UA_Client_writeUserExecutableAttribute().
UA_ObjectAttributes_default
UA_EXPORT const UA_ObjectAttributes UA_ObjectAttributes_default
Referenced by addDeviceNode(), addGroupNode(), function_namespace0_generated_112_begin(), function_namespace0_generated_127_begin(), function_namespace0_generated_131_begin(), function_namespace0_generated_133_begin(), function_namespace0_generated_134_begin(), function_namespace0_generated_146_begin(), function_namespace0_generated_147_begin(), function_namespace0_generated_149_begin(), function_namespace0_generated_150_begin(), function_namespace0_generated_151_begin(), function_namespace0_generated_52_begin(), function_namespace0_generated_53_begin(), function_namespace0_generated_63_begin(), function_namespace0_generated_67_begin(), function_namespace0_generated_69_begin(), function_namespace0_generated_70_begin(), function_namespace0_generated_72_begin(), function_namespace0_generated_75_begin(), function_namespace0_generated_94_begin(), and UA_Client_writeUserExecutableAttribute().
UA_ObjectTypeAttributes_default
UA_EXPORT const UA_ObjectTypeAttributes UA_ObjectTypeAttributes_default
Referenced by function_namespace0_generated_135_begin(), function_namespace0_generated_136_begin(), function_namespace0_generated_145_begin(), function_namespace0_generated_51_begin(), function_namespace0_generated_55_begin(), function_namespace0_generated_62_begin(), function_namespace0_generated_68_begin(), function_namespace0_generated_71_begin(), function_namespace0_generated_77_begin(), function_namespace0_generated_93_begin(), and UA_Client_writeUserExecutableAttribute().
UA_ReferenceTypeAttributes_default
UA_EXPORT const UA_ReferenceTypeAttributes UA_ReferenceTypeAttributes_default
Referenced by function_namespace0_generated_0_begin(), function_namespace0_generated_1_begin(), function_namespace0_generated_38_begin(), function_namespace0_generated_39_begin(), function_namespace0_generated_40_begin(), function_namespace0_generated_41_begin(), function_namespace0_generated_42_begin(), and UA_Client_writeUserExecutableAttribute().
UA_VariableAttributes_default
UA_EXPORT const UA_VariableAttributes UA_VariableAttributes_default
Referenced by addMetricNode(), function_namespace0_generated_100_begin(), function_namespace0_generated_101_begin(), function_namespace0_generated_102_begin(), function_namespace0_generated_103_begin(), function_namespace0_generated_104_begin(), function_namespace0_generated_105_begin(), function_namespace0_generated_106_begin(), function_namespace0_generated_107_begin(), function_namespace0_generated_108_begin(), function_namespace0_generated_109_begin(), function_namespace0_generated_110_begin(), function_namespace0_generated_111_begin(), function_namespace0_generated_113_begin(), function_namespace0_generated_114_begin(), function_namespace0_generated_115_begin(), function_namespace0_generated_116_begin(), function_namespace0_generated_117_begin(), function_namespace0_generated_118_begin(), function_namespace0_generated_119_begin(), function_namespace0_generated_120_begin(), function_namespace0_generated_121_begin(), function_namespace0_generated_122_begin(), function_namespace0_generated_123_begin(), function_namespace0_generated_124_begin(), function_namespace0_generated_125_begin(), function_namespace0_generated_126_begin(), function_namespace0_generated_128_begin(), function_namespace0_generated_129_begin(), function_namespace0_generated_130_begin(), function_namespace0_generated_132_begin(), function_namespace0_generated_137_begin(), function_namespace0_generated_138_begin(), function_namespace0_generated_139_begin(), function_namespace0_generated_140_begin(), function_namespace0_generated_141_begin(), function_namespace0_generated_142_begin(), function_namespace0_generated_143_begin(), function_namespace0_generated_144_begin(), function_namespace0_generated_148_begin(), function_namespace0_generated_152_begin(), function_namespace0_generated_153_begin(), function_namespace0_generated_154_begin(), function_namespace0_generated_155_begin(), function_namespace0_generated_156_begin(), function_namespace0_generated_157_begin(), function_namespace0_generated_158_begin(), function_namespace0_generated_159_begin(), function_namespace0_generated_160_begin(), function_namespace0_generated_161_begin(), function_namespace0_generated_162_begin(), function_namespace0_generated_163_begin(), function_namespace0_generated_164_begin(), function_namespace0_generated_165_begin(), function_namespace0_generated_34_begin(), function_namespace0_generated_36_begin(), function_namespace0_generated_57_begin(), function_namespace0_generated_58_begin(), function_namespace0_generated_60_begin(), function_namespace0_generated_61_begin(), function_namespace0_generated_64_begin(), function_namespace0_generated_65_begin(), function_namespace0_generated_66_begin(), function_namespace0_generated_73_begin(), function_namespace0_generated_74_begin(), function_namespace0_generated_76_begin(), function_namespace0_generated_78_begin(), function_namespace0_generated_81_begin(), function_namespace0_generated_82_begin(), function_namespace0_generated_83_begin(), function_namespace0_generated_84_begin(), function_namespace0_generated_85_begin(), function_namespace0_generated_86_begin(), function_namespace0_generated_87_begin(), function_namespace0_generated_88_begin(), function_namespace0_generated_89_begin(), function_namespace0_generated_90_begin(), function_namespace0_generated_91_begin(), function_namespace0_generated_92_begin(), function_namespace0_generated_95_begin(), function_namespace0_generated_97_begin(), function_namespace0_generated_98_begin(), function_namespace0_generated_99_begin(), and UA_Client_writeUserExecutableAttribute().
UA_VariableTypeAttributes_default
UA_EXPORT const UA_VariableTypeAttributes UA_VariableTypeAttributes_default
Referenced by function_namespace0_generated_54_begin(), function_namespace0_generated_56_begin(), function_namespace0_generated_59_begin(), function_namespace0_generated_79_begin(), function_namespace0_generated_80_begin(), and UA_Client_writeUserExecutableAttribute().
UA_ViewAttributes_default
UA_EXPORT const UA_ViewAttributes UA_ViewAttributes_default
Referenced by UA_Client_writeUserExecutableAttribute().