Project Template: Opc.Ua.FieldMetaData Class Reference
Opc.Ua.FieldMetaData Class Reference
Public Member Functions
FieldMetaData ()
The default constructor.
virtual void Encode (IEncoder encoder)
virtual void Decode (IDecoder decoder)
virtual bool IsEqual (IEncodeable encodeable)
virtual object Clone ()
new object MemberwiseClone ()
Properties
string Name [get, set]
LocalizedText Description [get, set]
ushort FieldFlags [get, set]
byte BuiltInType [get, set]
NodeId DataType [get, set]
int ValueRank [get, set]
UInt32Collection ArrayDimensions [get, set]
uint MaxStringLength [get, set]
Uuid DataSetFieldId [get, set]
KeyValuePairCollection Properties [get, set]
virtual ExpandedNodeId TypeId [get]
virtual ExpandedNodeId BinaryEncodingId [get]
virtual ExpandedNodeId XmlEncodingId [get]
Detailed Description
<exclude>
Definition at line 5737 of file Opc.Ua.DataTypes.cs.
Constructor & Destructor Documentation
FieldMetaData()
Opc.Ua.FieldMetaData.FieldMetaData () inline
The default constructor.
Definition at line 5743 of file Opc.Ua.DataTypes.cs.
Member Function Documentation
Clone()
virtual object Opc.Ua.FieldMetaData.Clone () inline virtual
Definition at line 5973 of file Opc.Ua.DataTypes.cs.
Decode()
virtual void Opc.Ua.FieldMetaData.Decode (IDecoder decoder) inline virtual
Definition at line 5924 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.ArrayDimensions, Opc.Ua.Description, Opc.Ua.Namespaces.OpcUaXsd, and Opc.Ua.ValueRank.
Encode()
virtual void Opc.Ua.FieldMetaData.Encode (IEncoder encoder) inline virtual
Definition at line 5905 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.ArrayDimensions, Opc.Ua.Description, Opc.Ua.Namespaces.OpcUaXsd, and Opc.Ua.ValueRank.
IsEqual()
virtual bool Opc.Ua.FieldMetaData.IsEqual (IEncodeable encodeable) inline virtual
Definition at line 5943 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Object.
MemberwiseClone()
new object Opc.Ua.FieldMetaData.MemberwiseClone () inline
Definition at line 5980 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.KeyValuePairCollection.Clone(), Opc.Ua.FieldMetaData.MemberwiseClone(), Opc.Ua.NodeId, and Opc.Ua.Namespaces.OpcUaXsd.
Referenced by Opc.Ua.FieldMetaData.MemberwiseClone().
Property Documentation
ArrayDimensions
UInt32Collection Opc.Ua.FieldMetaData.ArrayDimensions get set
Definition at line 5829 of file Opc.Ua.DataTypes.cs.
BinaryEncodingId
virtual ExpandedNodeId Opc.Ua.FieldMetaData.BinaryEncodingId get
Definition at line 5894 of file Opc.Ua.DataTypes.cs.
BuiltInType
byte Opc.Ua.FieldMetaData.BuiltInType get set
Definition at line 5803 of file Opc.Ua.DataTypes.cs.
DataSetFieldId
Uuid Opc.Ua.FieldMetaData.DataSetFieldId get set
Definition at line 5857 of file Opc.Ua.DataTypes.cs.
DataType
NodeId Opc.Ua.FieldMetaData.DataType get set
Definition at line 5811 of file Opc.Ua.DataTypes.cs.
Description
LocalizedText Opc.Ua.FieldMetaData.Description get set
Definition at line 5787 of file Opc.Ua.DataTypes.cs.
FieldFlags
ushort Opc.Ua.FieldMetaData.FieldFlags get set
Definition at line 5795 of file Opc.Ua.DataTypes.cs.
MaxStringLength
uint Opc.Ua.FieldMetaData.MaxStringLength get set
Definition at line 5849 of file Opc.Ua.DataTypes.cs.
Name
string Opc.Ua.FieldMetaData.Name get set
Definition at line 5779 of file Opc.Ua.DataTypes.cs.
Properties
KeyValuePairCollection Opc.Ua.FieldMetaData.Properties get set
Definition at line 5867 of file Opc.Ua.DataTypes.cs.
TypeId
virtual ExpandedNodeId Opc.Ua.FieldMetaData.TypeId get
Definition at line 5888 of file Opc.Ua.DataTypes.cs.
ValueRank
int Opc.Ua.FieldMetaData.ValueRank get set
Definition at line 5819 of file Opc.Ua.DataTypes.cs.
XmlEncodingId
virtual ExpandedNodeId Opc.Ua.FieldMetaData.XmlEncodingId get
Definition at line 5900 of file Opc.Ua.DataTypes.cs.
The documentation for this class was generated from the following file:
Opc.Ua.DataTypes.cs