Project Template: Opc.Ua.Fdi5 Namespace Reference
Opc.Ua.Fdi5 Namespace Reference
Data Structures
class AbortActionMethodState
Stores an instance of the AbortActionMethodType Method.
class ActionServiceState
Stores an instance of the ActionServiceType ObjectType.
class ActionState
Stores an instance of the ActionType ObjectType.
class ApplyMethodState
Stores an instance of the ApplyMethodType Method.
class ApplyResult
class ApplyResultCollection
A collection of ApplyResult objects.
class BrowseNames
Declares all of the BrowseNames used in the Model Design.
class DataTypeIds
A class that declares constants for all DataTypes in the Model Design.
class DataTypes
A class that declares constants for all DataTypes in the Model Design.
class DirectDeviceAccessState
Stores an instance of the DirectDeviceAccessType ObjectType.
class DiscardMethodState
Stores an instance of the DiscardMethodType Method.
class EditContextState
Stores an instance of the EditContextType ObjectType.
class EndDirectAccessMethodState
Stores an instance of the EndDirectAccessMethodType Method.
class GetEditContextMethodState
Stores an instance of the GetEditContextMethodType Method.
class InitDirectAccessMethodState
Stores an instance of the InitDirectAccessMethodType Method.
class InvokeActionMethodState
Stores an instance of the InvokeActionMethodType Method.
class LogAuditTrailMessageMethodState
Stores an instance of the LogAuditTrailMessage Method.
class MethodIds
A class that declares constants for all Methods in the Model Design.
class Methods
A class that declares constants for all Methods in the Model Design.
class Namespaces
Defines constants for all namespaces referenced by the model design.
class ObjectIds
A class that declares constants for all Objects in the Model Design.
class Objects
A class that declares constants for all Objects in the Model Design.
class ObjectTypeIds
A class that declares constants for all ObjectTypes in the Model Design.
class ObjectTypes
A class that declares constants for all ObjectTypes in the Model Design.
class RegisteredNode
class RegisteredNodeCollection
A collection of RegisteredNode objects.
class RegisterNodesMethodState
Stores an instance of the RegisterNodesMethodType Method.
class RegisterNodesResult
class RegisterNodesResultCollection
A collection of RegisterNodesResult objects.
class RegistrationParameters
class RegistrationParametersCollection
A collection of RegistrationParameters objects.
class ResetMethodState
Stores an instance of the ResetMethodType Method.
class RespondActionMethodState
Stores an instance of the RespondActionMethodType Method.
class StyleTypeCollection
A collection of StyleType objects.
class TransferIncident
class TransferIncidentCollection
A collection of TransferIncident objects.
class TransferMethodState
Stores an instance of the TransferMethodType Method.
class UIDescriptionState
Stores an instance of the UIDescriptionType VariableType.
class UIPlugInState
Stores an instance of the UIPlugInType VariableType.
class VariableIds
A class that declares constants for all Variables in the Model Design.
class Variables
A class that declares constants for all Variables in the Model Design.
class VariableTypeIds
A class that declares constants for all VariableTypes in the Model Design.
class VariableTypes
A class that declares constants for all VariableTypes in the Model Design.
class WindowModeTypeCollection
A collection of WindowModeType objects.
Enumerations
enum WindowModeType { WindowModeType.ModalWindow = 1, WindowModeType.NonModalWindow = 2, WindowModeType.UIP = 3 }
enum StyleType { StyleType.Window = 1, StyleType.Dialog = 2 }
Functions
delegate ServiceResult InvokeActionMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, string actionName, string methodArguments, ref NodeId actionNodeId, ref int invokeActionError)
Used to receive notifications when the method is called.
delegate ServiceResult RespondActionMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, NodeId actionNodeId, string response, ref int respondActionError)
Used to receive notifications when the method is called.
delegate ServiceResult AbortActionMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, NodeId actionNodeId, ref int abortActionError)
Used to receive notifications when the method is called.
delegate ServiceResult GetEditContextMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, string parentId, WindowModeType targetWindowMode, ref string editContextId, ref int getEditContextStatus)
Used to receive notifications when the method is called.
delegate ServiceResult RegisterNodesMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, string editContextId, RegistrationParameters[] nodesToRegister, ref RegisterNodesResult registerNodesStatus)
Used to receive notifications when the method is called.
delegate ServiceResult ApplyMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, string editContextId, ref ApplyResult applyStatus)
Used to receive notifications when the method is called.
delegate ServiceResult ResetMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, string editContextId, ref int resetStatus)
Used to receive notifications when the method is called.
delegate ServiceResult DiscardMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, string editContextId, ref int discardStatus)
Used to receive notifications when the method is called.
delegate ServiceResult InitDirectAccessMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, string context, ref int initDirectAccessError)
Used to receive notifications when the method is called.
delegate ServiceResult TransferMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, string sendData, string receiveData, ref int transferError)
Used to receive notifications when the method is called.
delegate ServiceResult EndDirectAccessMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, bool invalidateCache, ref int endDirectAccessError)
Used to receive notifications when the method is called.
delegate ServiceResult LogAuditTrailMessageMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, string message)
Used to receive notifications when the method is called.
Enumeration Type Documentation
StyleType
enum Opc.Ua.Fdi5.StyleType strong
<exclude>
Enumerator
Window
Dialog
Definition at line 158 of file Opc.Ua.Fdi5.DataTypes.cs.
WindowModeType
enum Opc.Ua.Fdi5.WindowModeType strong
<exclude>
Enumerator
ModalWindow
NonModalWindow
UIP
Definition at line 48 of file Opc.Ua.Fdi5.DataTypes.cs.
Function Documentation
AbortActionMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.Fdi5.AbortActionMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, NodeId actionNodeId, ref int abortActionError)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.Fdi5.AbortActionMethodState.InitializeOptionalChildren().
ApplyMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.Fdi5.ApplyMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, string editContextId, ref ApplyResult applyStatus)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.Fdi5.ApplyMethodState.InitializeOptionalChildren().
DiscardMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.Fdi5.DiscardMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, string editContextId, ref int discardStatus)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.Fdi5.DiscardMethodState.InitializeOptionalChildren().
EndDirectAccessMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.Fdi5.EndDirectAccessMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, bool invalidateCache, ref int endDirectAccessError)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.Fdi5.EndDirectAccessMethodState.InitializeOptionalChildren().
GetEditContextMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.Fdi5.GetEditContextMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, string parentId, WindowModeType targetWindowMode, ref string editContextId, ref int getEditContextStatus)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.Fdi5.GetEditContextMethodState.InitializeOptionalChildren().
InitDirectAccessMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.Fdi5.InitDirectAccessMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, string context, ref int initDirectAccessError)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.Fdi5.InitDirectAccessMethodState.InitializeOptionalChildren().
InvokeActionMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.Fdi5.InvokeActionMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, string actionName, string methodArguments, ref NodeId actionNodeId, ref int invokeActionError)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.Fdi5.InvokeActionMethodState.InitializeOptionalChildren().
LogAuditTrailMessageMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.Fdi5.LogAuditTrailMessageMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, string message)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.Fdi5.LogAuditTrailMessageMethodState.InitializeOptionalChildren().
RegisterNodesMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.Fdi5.RegisterNodesMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, string editContextId, RegistrationParameters [] nodesToRegister, ref RegisterNodesResult registerNodesStatus)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.Fdi5.RegisterNodesMethodState.InitializeOptionalChildren().
ResetMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.Fdi5.ResetMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, string editContextId, ref int resetStatus)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.Fdi5.ResetMethodState.InitializeOptionalChildren().
RespondActionMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.Fdi5.RespondActionMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, NodeId actionNodeId, string response, ref int respondActionError)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.Fdi5.RespondActionMethodState.InitializeOptionalChildren().
TransferMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.Fdi5.TransferMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, string sendData, string receiveData, ref int transferError)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.Fdi5.TransferMethodState.InitializeOptionalChildren().