HaSSL: Information_Model::DeviceElementGroup Class Reference
Information_Model::DeviceElementGroup Class Reference abstract
This Class Models a List of Elements within the Device.
#include <DeviceElementGroup.hpp>
Public Member Functions
virtual std::vector< std::shared_ptr< DeviceElement > > getSubelements ()=0
virtual std::shared_ptr< DeviceElement > getSubelement (const std::string REF_ID)=0
virtual unsigned int getNumericElementId ()=0
virtual ~DeviceElementGroup ()=default
Public Member Functions inherited from Information_Model::DeviceElement
DeviceElement (const std::string REF_ID, const std::string NAME, const std::string DESC, ElementType type)
ElementType getElementType ()
virtual ~DeviceElement ()=default
Public Member Functions inherited from Information_Model::NamedElement
const std::string getElementName ()
const std::string getElementDescription ()
const std::string getElementRefId ()
virtual ~NamedElement ()=default
Protected Member Functions
DeviceElementGroup (const std::string REF_ID, const std::string NAME, const std::string DESC)
Protected Member Functions inherited from Information_Model::NamedElement
NamedElement (const std::string REF_ID, const std::string NAME, const std::string DESC)
Additional Inherited Members
Protected Attributes inherited from Information_Model::DeviceElement
ElementType elementType = ElementType::Undefined
Detailed Description
This Class Models a List of Elements within the Device.
It may contain more DeviceElementGroup instances, which act as sublists. The implementation of this class exists in Model_Factory::DeviceElementGroupImpl
Attention
This class should be instantiated by Model_Factory::DeviceBuilder only!
Author
Dovydas Girdvainis
Date
18.07.2019
Constructor & Destructor Documentation
DeviceElementGroup()
Information_Model::DeviceElementGroup::DeviceElementGroup (const std::string REF_ID, const std::string NAME, const std::string DESC) inline protected
References getNumericElementId(), getSubelement(), getSubelements(), and ~DeviceElementGroup().
~DeviceElementGroup()
virtual Information_Model::DeviceElementGroup::~DeviceElementGroup () virtual default
Referenced by DeviceElementGroup().
Member Function Documentation
getNumericElementId()
virtual unsigned int Information_Model::DeviceElementGroup::getNumericElementId () pure virtual
Referenced by DeviceElementGroup(), and MockDeviceElementGroup::MockDeviceElementGroup().
getSubelement()
virtual std::shared_ptr<DeviceElement> Information_Model::DeviceElementGroup::getSubelement (const std::string REF_ID) pure virtual
Referenced by DeviceElementGroup(), and MockDeviceElementGroup::MockDeviceElementGroup().
getSubelements()
virtual std::vector<std::shared_ptr<DeviceElement> > Information_Model::DeviceElementGroup::getSubelements () pure virtual
Referenced by DeviceElementGroup(), and MockDeviceElementGroup::MockDeviceElementGroup().
The documentation for this class was generated from the following file:
DeviceElementGroup.hpp