Project Template: Opc.Ua.RegisterNodesRequest Class Reference
Opc.Ua.RegisterNodesRequest Class Reference
Public Member Functions
RegisterNodesRequest ()
The default constructor.
virtual void Encode (IEncoder encoder)
virtual void Decode (IDecoder decoder)
virtual bool IsEqual (IEncodeable encodeable)
virtual object Clone ()
new object MemberwiseClone ()
Properties
RequestHeader RequestHeader [get, set]
NodeIdCollection NodesToRegister [get, set]
virtual ExpandedNodeId TypeId [get]
virtual ExpandedNodeId BinaryEncodingId [get]
virtual ExpandedNodeId XmlEncodingId [get]
Detailed Description
<exclude>
Definition at line 1966 of file Opc.Ua.Messages.cs.
Constructor & Destructor Documentation
RegisterNodesRequest()
Opc.Ua.RegisterNodesRequest.RegisterNodesRequest () inline
The default constructor.
Definition at line 40010 of file Opc.Ua.DataTypes.cs.
Member Function Documentation
Clone()
virtual object Opc.Ua.RegisterNodesRequest.Clone () inline virtual
Definition at line 40144 of file Opc.Ua.DataTypes.cs.
Decode()
virtual void Opc.Ua.RegisterNodesRequest.Decode (IDecoder decoder) inline virtual
Definition at line 40111 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
Encode()
virtual void Opc.Ua.RegisterNodesRequest.Encode (IEncoder encoder) inline virtual
Definition at line 40100 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
IsEqual()
virtual bool Opc.Ua.RegisterNodesRequest.IsEqual (IEncodeable encodeable) inline virtual
Definition at line 40122 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Object.
MemberwiseClone()
new object Opc.Ua.RegisterNodesRequest.MemberwiseClone () inline
Definition at line 40151 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.RequestHeader.Clone(), Opc.Ua.RegisterNodesRequest.MemberwiseClone(), and Opc.Ua.Namespaces.OpcUaXsd.
Referenced by Opc.Ua.RegisterNodesRequest.MemberwiseClone().
Property Documentation
BinaryEncodingId
virtual ExpandedNodeId Opc.Ua.RegisterNodesRequest.BinaryEncodingId get
Definition at line 40089 of file Opc.Ua.DataTypes.cs.
NodesToRegister
NodeIdCollection Opc.Ua.RegisterNodesRequest.NodesToRegister get set
Definition at line 40062 of file Opc.Ua.DataTypes.cs.
Referenced by Opc.Ua.SessionClient.BeginRegisterNodes(), Opc.Ua.SessionClient.EndTranslateBrowsePathsToNodeIds(), and Opc.Ua.SessionEndpoint.EndTranslateBrowsePathsToNodeIds().
RequestHeader
RequestHeader Opc.Ua.RegisterNodesRequest.RequestHeader get set
Definition at line 40040 of file Opc.Ua.DataTypes.cs.
Referenced by Opc.Ua.SessionClient.BeginRegisterNodes(), Opc.Ua.SessionClient.EndTranslateBrowsePathsToNodeIds(), and Opc.Ua.SessionEndpoint.EndTranslateBrowsePathsToNodeIds().
TypeId
virtual ExpandedNodeId Opc.Ua.RegisterNodesRequest.TypeId get
Definition at line 40083 of file Opc.Ua.DataTypes.cs.
XmlEncodingId
virtual ExpandedNodeId Opc.Ua.RegisterNodesRequest.XmlEncodingId get
Definition at line 40095 of file Opc.Ua.DataTypes.cs.
The documentation for this class was generated from the following files:
Opc.Ua.Messages.cs
Opc.Ua.DataTypes.cs