Project Template: Opc.Ua.Di Namespace Reference
Opc.Ua.Di Namespace Reference
Data Structures
class BlockState
Stores an instance of the BlockType ObjectType.
class BreakLockMethodState
Stores an instance of the BreakLockMethodType Method.
class BrowseNames
Declares all of the BrowseNames used in the Model Design.
class CheckFunctionAlarmState
Stores an instance of the CheckFunctionAlarmType ObjectType.
class ComponentState
Stores an instance of the ComponentType ObjectType.
class ConfigurableObjectState
Stores an instance of the ConfigurableObjectType ObjectType.
class ConnectionPointState
Stores an instance of the ConnectionPointType ObjectType.
class DataTypeIds
A class that declares constants for all DataTypes in the Model Design.
class DataTypes
A class that declares constants for all DataTypes in the Model Design.
class DeviceHealthDiagnosticAlarmState
Stores an instance of the DeviceHealthDiagnosticAlarmType ObjectType.
class DeviceHealthEnumerationCollection
A collection of DeviceHealthEnumeration objects.
class DeviceState
Stores an instance of the DeviceType ObjectType.
class ExitLockMethodState
Stores an instance of the ExitLockMethodType Method.
class FailureAlarmState
Stores an instance of the FailureAlarmType ObjectType.
class FetchResultDataType
class FetchResultDataTypeCollection
A collection of FetchResultDataType objects.
class FetchTransferResultDataMethodState
Stores an instance of the FetchTransferResultDataMethodType Method.
class FunctionalGroupState
Stores an instance of the FunctionalGroupType ObjectType.
class IDeviceHealthState
Stores an instance of the IDeviceHealthType ObjectType.
class InitLockMethodState
Stores an instance of the InitLockMethodType Method.
class ISupportInfoState
Stores an instance of the ISupportInfoType ObjectType.
class ITagNameplateState
Stores an instance of the ITagNameplateType ObjectType.
class IVendorNameplateState
Stores an instance of the IVendorNameplateType ObjectType.
class LockingServicesState
Stores an instance of the LockingServicesType ObjectType.
class MaintenanceRequiredAlarmState
Stores an instance of the MaintenanceRequiredAlarmType ObjectType.
class MethodIds
A class that declares constants for all Methods in the Model Design.
class Methods
A class that declares constants for all Methods in the Model Design.
class Namespaces
Defines constants for all namespaces referenced by the model design.
class NetworkState
Stores an instance of the NetworkType ObjectType.
class ObjectIds
A class that declares constants for all Objects in the Model Design.
class Objects
A class that declares constants for all Objects in the Model Design.
class ObjectTypeIds
A class that declares constants for all ObjectTypes in the Model Design.
class ObjectTypes
A class that declares constants for all ObjectTypes in the Model Design.
class OffSpecAlarmState
Stores an instance of the OffSpecAlarmType ObjectType.
class ParameterResultDataType
class ParameterResultDataTypeCollection
A collection of ParameterResultDataType objects.
class ProtocolState
Stores an instance of the ProtocolType ObjectType.
class ReferenceTypeIds
A class that declares constants for all ReferenceTypes in the Model Design.
class ReferenceTypes
A class that declares constants for all ReferenceTypes in the Model Design.
class RenewLockMethodState
Stores an instance of the RenewLockMethodType Method.
class SoftwareState
Stores an instance of the SoftwareType ObjectType.
class TopologyElementState
Stores an instance of the TopologyElementType ObjectType.
class TransferFromDeviceMethodState
Stores an instance of the TransferFromDeviceMethodType Method.
class TransferResultDataDataType
class TransferResultDataDataTypeCollection
A collection of TransferResultDataDataType objects.
class TransferResultErrorDataType
class TransferResultErrorDataTypeCollection
A collection of TransferResultErrorDataType objects.
class TransferServicesState
Stores an instance of the TransferServicesType ObjectType.
class TransferToDeviceMethodState
Stores an instance of the TransferToDeviceMethodType Method.
class UIElementState
Stores an instance of the UIElementType VariableType.
class VariableIds
A class that declares constants for all Variables in the Model Design.
class Variables
A class that declares constants for all Variables in the Model Design.
class VariableTypeIds
A class that declares constants for all VariableTypes in the Model Design.
class VariableTypes
A class that declares constants for all VariableTypes in the Model Design.
Enumerations
enum DeviceHealthEnumeration {
DeviceHealthEnumeration.NORMAL = 0, DeviceHealthEnumeration.FAILURE = 1, DeviceHealthEnumeration.CHECK_FUNCTION = 2, DeviceHealthEnumeration.OFF_SPEC = 3,
DeviceHealthEnumeration.MAINTENANCE_REQUIRED = 4
}
Functions
delegate ServiceResult TransferToDeviceMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, ref int transferID, ref int initTransferStatus)
Used to receive notifications when the method is called.
delegate ServiceResult TransferFromDeviceMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, ref int transferID, ref int initTransferStatus)
Used to receive notifications when the method is called.
delegate ServiceResult FetchTransferResultDataMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, int transferID, int sequenceNumber, int maxParameterResultsToReturn, bool omitGoodResults, ref ExtensionObject fetchResultData)
Used to receive notifications when the method is called.
delegate ServiceResult InitLockMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, string context, ref int initLockStatus)
Used to receive notifications when the method is called.
delegate ServiceResult RenewLockMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, ref int renewLockStatus)
Used to receive notifications when the method is called.
delegate ServiceResult ExitLockMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, ref int exitLockStatus)
Used to receive notifications when the method is called.
delegate ServiceResult BreakLockMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, ref int breakLockStatus)
Used to receive notifications when the method is called.
Enumeration Type Documentation
DeviceHealthEnumeration
enum Opc.Ua.Di.DeviceHealthEnumeration strong
<exclude>
Enumerator
NORMAL
FAILURE
CHECK_FUNCTION
OFF_SPEC
MAINTENANCE_REQUIRED
Definition at line 47 of file Opc.Ua.Di.DataTypes.cs.
Function Documentation
BreakLockMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.Di.BreakLockMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, ref int breakLockStatus)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.Di.BreakLockMethodState.InitializeOptionalChildren().
ExitLockMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.Di.ExitLockMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, ref int exitLockStatus)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.Di.ExitLockMethodState.InitializeOptionalChildren().
FetchTransferResultDataMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.Di.FetchTransferResultDataMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, int transferID, int sequenceNumber, int maxParameterResultsToReturn, bool omitGoodResults, ref ExtensionObject fetchResultData)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.Di.FetchTransferResultDataMethodState.InitializeOptionalChildren().
InitLockMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.Di.InitLockMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, string context, ref int initLockStatus)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.Di.InitLockMethodState.InitializeOptionalChildren().
RenewLockMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.Di.RenewLockMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, ref int renewLockStatus)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.Di.RenewLockMethodState.InitializeOptionalChildren().
TransferFromDeviceMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.Di.TransferFromDeviceMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, ref int transferID, ref int initTransferStatus)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.Di.TransferFromDeviceMethodState.InitializeOptionalChildren().
TransferToDeviceMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.Di.TransferToDeviceMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, ref int transferID, ref int initTransferStatus)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.Di.TransferToDeviceMethodState.InitializeOptionalChildren().