set(OVERRIDE_COMPILER_PATHS off CACHE BOOL "Set to true, if you desire to provide your own copiler paths with CMAKE_C_COMPILER and CMAKE_CXX_COMPILER variables")

if(NOT OVERRIDE_COMPILER_PATHS)
    if(WIN32) 
        if("${CMAKE_CXX_COMPILER_ID}" STREQUAL "GNU")
            message(WARNING "Using default GCC compiler path at: C:/mingw64/bin")
			set(CMAKE_C_COMPILER C:/mingw64/bin/gcc.exe CACHE PATH "" FORCE)
			set(CMAKE_CXX_COMPILER C:/mingw64/bin/g++.exe CACHE PATH "" FORCE)
        elseif("${CMAKE_CXX_COMPILER_ID}" STREQUAL "Clang")
            message(SEND_ERROR "Clang compiler options might need to be configured! Please check cmake/compiler-toolchain.cmake!") 
        elseif ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "MSVC")
            message(SEND_ERROR "MSVC compiler support is expermental! Use it at your own risk!")
            message(SEND_ERROR "MSVC compiler options might need to be configured! Please check cmake/compiler-toolchain.cmake!")
        endif()
    else(UNIX) 
        message(WARNING "Using default GCC compiler path at: usr/bin/gcc") 
        set(CMAKE_C_COMPILER /usr/bin/gcc CACHE PATH "" FORCE)
        set(CMAKE_CXX_COMPILER /usr/bin/g++ CACHE PATH "" FORCE)
    endif()
endif()
