get_filename_component(SELF_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
include(${CMAKE_CURRENT_LIST_DIR}/lib/Model_Translator.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/modules/Data_Consumer_Notifier-0.0.0-Linux/data_consumer_notifier-config.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/modules/Information_Modeler-0.0.0-Linux/information_modeler-config.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/modules/OPCUA_Node_Model-0.0.0-Linux/opcua_node_model-config.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/modules/open62541_server_runner-0.0.0-Linux/open62541_server_runner-config.cmake)