Project Template: opcua_clientapi.c File Reference
opcua_clientapi.c File Reference
Functions
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_FindServers (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader *a_pRequestHeader, const OpcUa_String *a_pEndpointUrl, OpcUa_Int32 a_nNoOfLocaleIds, const OpcUa_String *a_pLocaleIds, OpcUa_Int32 a_nNoOfServerUris, const OpcUa_String *a_pServerUris, OpcUa_ResponseHeader *a_pResponseHeader, OpcUa_Int32 *a_pNoOfServers, OpcUa_ApplicationDescription **a_pServers)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginFindServers (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader *a_pRequestHeader, const OpcUa_String *a_pEndpointUrl, OpcUa_Int32 a_nNoOfLocaleIds, const OpcUa_String *a_pLocaleIds, OpcUa_Int32 a_nNoOfServerUris, const OpcUa_String *a_pServerUris, OpcUa_Channel_PfnRequestComplete *a_pCallback, OpcUa_Void *a_pCallbackData)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_FindServersOnNetwork (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader *a_pRequestHeader, OpcUa_UInt32 a_nStartingRecordId, OpcUa_UInt32 a_nMaxRecordsToReturn, OpcUa_Int32 a_nNoOfServerCapabilityFilter, const OpcUa_String *a_pServerCapabilityFilter, OpcUa_ResponseHeader *a_pResponseHeader, OpcUa_DateTime *a_pLastCounterResetTime, OpcUa_Int32 *a_pNoOfServers, OpcUa_ServerOnNetwork **a_pServers)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginFindServersOnNetwork (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader *a_pRequestHeader, OpcUa_UInt32 a_nStartingRecordId, OpcUa_UInt32 a_nMaxRecordsToReturn, OpcUa_Int32 a_nNoOfServerCapabilityFilter, const OpcUa_String *a_pServerCapabilityFilter, OpcUa_Channel_PfnRequestComplete *a_pCallback, OpcUa_Void *a_pCallbackData)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_GetEndpoints (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader *a_pRequestHeader, const OpcUa_String *a_pEndpointUrl, OpcUa_Int32 a_nNoOfLocaleIds, const OpcUa_String *a_pLocaleIds, OpcUa_Int32 a_nNoOfProfileUris, const OpcUa_String *a_pProfileUris, OpcUa_ResponseHeader *a_pResponseHeader, OpcUa_Int32 *a_pNoOfEndpoints, OpcUa_EndpointDescription **a_pEndpoints)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginGetEndpoints (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader *a_pRequestHeader, const OpcUa_String *a_pEndpointUrl, OpcUa_Int32 a_nNoOfLocaleIds, const OpcUa_String *a_pLocaleIds, OpcUa_Int32 a_nNoOfProfileUris, const OpcUa_String *a_pProfileUris, OpcUa_Channel_PfnRequestComplete *a_pCallback, OpcUa_Void *a_pCallbackData)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_RegisterServer (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader *a_pRequestHeader, const OpcUa_RegisteredServer *a_pServer, OpcUa_ResponseHeader *a_pResponseHeader)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginRegisterServer (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader *a_pRequestHeader, const OpcUa_RegisteredServer *a_pServer, OpcUa_Channel_PfnRequestComplete *a_pCallback, OpcUa_Void *a_pCallbackData)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_RegisterServer2 (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader *a_pRequestHeader, const OpcUa_RegisteredServer *a_pServer, OpcUa_Int32 a_nNoOfDiscoveryConfiguration, const OpcUa_ExtensionObject *a_pDiscoveryConfiguration, OpcUa_ResponseHeader *a_pResponseHeader, OpcUa_Int32 *a_pNoOfConfigurationResults, OpcUa_StatusCode **a_pConfigurationResults, OpcUa_Int32 *a_pNoOfDiagnosticInfos, OpcUa_DiagnosticInfo **a_pDiagnosticInfos)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginRegisterServer2 (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader *a_pRequestHeader, const OpcUa_RegisteredServer *a_pServer, OpcUa_Int32 a_nNoOfDiscoveryConfiguration, const OpcUa_ExtensionObject *a_pDiscoveryConfiguration, OpcUa_Channel_PfnRequestComplete *a_pCallback, OpcUa_Void *a_pCallbackData)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_CreateSession (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader *a_pRequestHeader, const OpcUa_ApplicationDescription *a_pClientDescription, const OpcUa_String *a_pServerUri, const OpcUa_String *a_pEndpointUrl, const OpcUa_String *a_pSessionName, const OpcUa_ByteString *a_pClientNonce, const OpcUa_ByteString *a_pClientCertificate, OpcUa_Double a_nRequestedSessionTimeout, OpcUa_UInt32 a_nMaxResponseMessageSize, OpcUa_ResponseHeader *a_pResponseHeader, OpcUa_NodeId *a_pSessionId, OpcUa_NodeId *a_pAuthenticationToken, OpcUa_Double *a_pRevisedSessionTimeout, OpcUa_ByteString *a_pServerNonce, OpcUa_ByteString *a_pServerCertificate, OpcUa_Int32 *a_pNoOfServerEndpoints, OpcUa_EndpointDescription **a_pServerEndpoints, OpcUa_Int32 *a_pNoOfServerSoftwareCertificates, OpcUa_SignedSoftwareCertificate **a_pServerSoftwareCertificates, OpcUa_SignatureData *a_pServerSignature, OpcUa_UInt32 *a_pMaxRequestMessageSize)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginCreateSession (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader *a_pRequestHeader, const OpcUa_ApplicationDescription *a_pClientDescription, const OpcUa_String *a_pServerUri, const OpcUa_String *a_pEndpointUrl, const OpcUa_String *a_pSessionName, const OpcUa_ByteString *a_pClientNonce, const OpcUa_ByteString *a_pClientCertificate, OpcUa_Double a_nRequestedSessionTimeout, OpcUa_UInt32 a_nMaxResponseMessageSize, OpcUa_Channel_PfnRequestComplete *a_pCallback, OpcUa_Void *a_pCallbackData)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_ActivateSession (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader *a_pRequestHeader, const OpcUa_SignatureData *a_pClientSignature, OpcUa_Int32 a_nNoOfClientSoftwareCertificates, const OpcUa_SignedSoftwareCertificate *a_pClientSoftwareCertificates, OpcUa_Int32 a_nNoOfLocaleIds, const OpcUa_String *a_pLocaleIds, const OpcUa_ExtensionObject *a_pUserIdentityToken, const OpcUa_SignatureData *a_pUserTokenSignature, OpcUa_ResponseHeader *a_pResponseHeader, OpcUa_ByteString *a_pServerNonce, OpcUa_Int32 *a_pNoOfResults, OpcUa_StatusCode **a_pResults, OpcUa_Int32 *a_pNoOfDiagnosticInfos, OpcUa_DiagnosticInfo **a_pDiagnosticInfos)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginActivateSession (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader *a_pRequestHeader, const OpcUa_SignatureData *a_pClientSignature, OpcUa_Int32 a_nNoOfClientSoftwareCertificates, const OpcUa_SignedSoftwareCertificate *a_pClientSoftwareCertificates, OpcUa_Int32 a_nNoOfLocaleIds, const OpcUa_String *a_pLocaleIds, const OpcUa_ExtensionObject *a_pUserIdentityToken, const OpcUa_SignatureData *a_pUserTokenSignature, OpcUa_Channel_PfnRequestComplete *a_pCallback, OpcUa_Void *a_pCallbackData)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_CloseSession (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader *a_pRequestHeader, OpcUa_Boolean a_bDeleteSubscriptions, OpcUa_ResponseHeader *a_pResponseHeader)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginCloseSession (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader *a_pRequestHeader, OpcUa_Boolean a_bDeleteSubscriptions, OpcUa_Channel_PfnRequestComplete *a_pCallback, OpcUa_Void *a_pCallbackData)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_Cancel (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader *a_pRequestHeader, OpcUa_UInt32 a_nRequestHandle, OpcUa_ResponseHeader *a_pResponseHeader, OpcUa_UInt32 *a_pCancelCount)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginCancel (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader *a_pRequestHeader, OpcUa_UInt32 a_nRequestHandle, OpcUa_Channel_PfnRequestComplete *a_pCallback, OpcUa_Void *a_pCallbackData)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_AddNodes (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader *a_pRequestHeader, OpcUa_Int32 a_nNoOfNodesToAdd, const OpcUa_AddNodesItem *a_pNodesToAdd, OpcUa_ResponseHeader *a_pResponseHeader, OpcUa_Int32 *a_pNoOfResults, OpcUa_AddNodesResult **a_pResults, OpcUa_Int32 *a_pNoOfDiagnosticInfos, OpcUa_DiagnosticInfo **a_pDiagnosticInfos)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginAddNodes (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader *a_pRequestHeader, OpcUa_Int32 a_nNoOfNodesToAdd, const OpcUa_AddNodesItem *a_pNodesToAdd, OpcUa_Channel_PfnRequestComplete *a_pCallback, OpcUa_Void *a_pCallbackData)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_AddReferences (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader *a_pRequestHeader, OpcUa_Int32 a_nNoOfReferencesToAdd, const OpcUa_AddReferencesItem *a_pReferencesToAdd, OpcUa_ResponseHeader *a_pResponseHeader, OpcUa_Int32 *a_pNoOfResults, OpcUa_StatusCode **a_pResults, OpcUa_Int32 *a_pNoOfDiagnosticInfos, OpcUa_DiagnosticInfo **a_pDiagnosticInfos)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginAddReferences (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader *a_pRequestHeader, OpcUa_Int32 a_nNoOfReferencesToAdd, const OpcUa_AddReferencesItem *a_pReferencesToAdd, OpcUa_Channel_PfnRequestComplete *a_pCallback, OpcUa_Void *a_pCallbackData)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_DeleteNodes (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader *a_pRequestHeader, OpcUa_Int32 a_nNoOfNodesToDelete, const OpcUa_DeleteNodesItem *a_pNodesToDelete, OpcUa_ResponseHeader *a_pResponseHeader, OpcUa_Int32 *a_pNoOfResults, OpcUa_StatusCode **a_pResults, OpcUa_Int32 *a_pNoOfDiagnosticInfos, OpcUa_DiagnosticInfo **a_pDiagnosticInfos)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginDeleteNodes (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader *a_pRequestHeader, OpcUa_Int32 a_nNoOfNodesToDelete, const OpcUa_DeleteNodesItem *a_pNodesToDelete, OpcUa_Channel_PfnRequestComplete *a_pCallback, OpcUa_Void *a_pCallbackData)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_DeleteReferences (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader *a_pRequestHeader, OpcUa_Int32 a_nNoOfReferencesToDelete, const OpcUa_DeleteReferencesItem *a_pReferencesToDelete, OpcUa_ResponseHeader *a_pResponseHeader, OpcUa_Int32 *a_pNoOfResults, OpcUa_StatusCode **a_pResults, OpcUa_Int32 *a_pNoOfDiagnosticInfos, OpcUa_DiagnosticInfo **a_pDiagnosticInfos)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginDeleteReferences (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader *a_pRequestHeader, OpcUa_Int32 a_nNoOfReferencesToDelete, const OpcUa_DeleteReferencesItem *a_pReferencesToDelete, OpcUa_Channel_PfnRequestComplete *a_pCallback, OpcUa_Void *a_pCallbackData)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_Browse (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader *a_pRequestHeader, const OpcUa_ViewDescription *a_pView, OpcUa_UInt32 a_nRequestedMaxReferencesPerNode, OpcUa_Int32 a_nNoOfNodesToBrowse, const OpcUa_BrowseDescription *a_pNodesToBrowse, OpcUa_ResponseHeader *a_pResponseHeader, OpcUa_Int32 *a_pNoOfResults, OpcUa_BrowseResult **a_pResults, OpcUa_Int32 *a_pNoOfDiagnosticInfos, OpcUa_DiagnosticInfo **a_pDiagnosticInfos)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginBrowse (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader *a_pRequestHeader, const OpcUa_ViewDescription *a_pView, OpcUa_UInt32 a_nRequestedMaxReferencesPerNode, OpcUa_Int32 a_nNoOfNodesToBrowse, const OpcUa_BrowseDescription *a_pNodesToBrowse, OpcUa_Channel_PfnRequestComplete *a_pCallback, OpcUa_Void *a_pCallbackData)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BrowseNext (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader *a_pRequestHeader, OpcUa_Boolean a_bReleaseContinuationPoints, OpcUa_Int32 a_nNoOfContinuationPoints, const OpcUa_ByteString *a_pContinuationPoints, OpcUa_ResponseHeader *a_pResponseHeader, OpcUa_Int32 *a_pNoOfResults, OpcUa_BrowseResult **a_pResults, OpcUa_Int32 *a_pNoOfDiagnosticInfos, OpcUa_DiagnosticInfo **a_pDiagnosticInfos)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginBrowseNext (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader *a_pRequestHeader, OpcUa_Boolean a_bReleaseContinuationPoints, OpcUa_Int32 a_nNoOfContinuationPoints, const OpcUa_ByteString *a_pContinuationPoints, OpcUa_Channel_PfnRequestComplete *a_pCallback, OpcUa_Void *a_pCallbackData)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_TranslateBrowsePathsToNodeIds (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader *a_pRequestHeader, OpcUa_Int32 a_nNoOfBrowsePaths, const OpcUa_BrowsePath *a_pBrowsePaths, OpcUa_ResponseHeader *a_pResponseHeader, OpcUa_Int32 *a_pNoOfResults, OpcUa_BrowsePathResult **a_pResults, OpcUa_Int32 *a_pNoOfDiagnosticInfos, OpcUa_DiagnosticInfo **a_pDiagnosticInfos)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginTranslateBrowsePathsToNodeIds (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader *a_pRequestHeader, OpcUa_Int32 a_nNoOfBrowsePaths, const OpcUa_BrowsePath *a_pBrowsePaths, OpcUa_Channel_PfnRequestComplete *a_pCallback, OpcUa_Void *a_pCallbackData)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_RegisterNodes (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader *a_pRequestHeader, OpcUa_Int32 a_nNoOfNodesToRegister, const OpcUa_NodeId *a_pNodesToRegister, OpcUa_ResponseHeader *a_pResponseHeader, OpcUa_Int32 *a_pNoOfRegisteredNodeIds, OpcUa_NodeId **a_pRegisteredNodeIds)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginRegisterNodes (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader *a_pRequestHeader, OpcUa_Int32 a_nNoOfNodesToRegister, const OpcUa_NodeId *a_pNodesToRegister, OpcUa_Channel_PfnRequestComplete *a_pCallback, OpcUa_Void *a_pCallbackData)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_UnregisterNodes (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader *a_pRequestHeader, OpcUa_Int32 a_nNoOfNodesToUnregister, const OpcUa_NodeId *a_pNodesToUnregister, OpcUa_ResponseHeader *a_pResponseHeader)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginUnregisterNodes (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader *a_pRequestHeader, OpcUa_Int32 a_nNoOfNodesToUnregister, const OpcUa_NodeId *a_pNodesToUnregister, OpcUa_Channel_PfnRequestComplete *a_pCallback, OpcUa_Void *a_pCallbackData)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_QueryFirst (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader *a_pRequestHeader, const OpcUa_ViewDescription *a_pView, OpcUa_Int32 a_nNoOfNodeTypes, const OpcUa_NodeTypeDescription *a_pNodeTypes, const OpcUa_ContentFilter *a_pFilter, OpcUa_UInt32 a_nMaxDataSetsToReturn, OpcUa_UInt32 a_nMaxReferencesToReturn, OpcUa_ResponseHeader *a_pResponseHeader, OpcUa_Int32 *a_pNoOfQueryDataSets, OpcUa_QueryDataSet **a_pQueryDataSets, OpcUa_ByteString *a_pContinuationPoint, OpcUa_Int32 *a_pNoOfParsingResults, OpcUa_ParsingResult **a_pParsingResults, OpcUa_Int32 *a_pNoOfDiagnosticInfos, OpcUa_DiagnosticInfo **a_pDiagnosticInfos, OpcUa_ContentFilterResult *a_pFilterResult)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginQueryFirst (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader *a_pRequestHeader, const OpcUa_ViewDescription *a_pView, OpcUa_Int32 a_nNoOfNodeTypes, const OpcUa_NodeTypeDescription *a_pNodeTypes, const OpcUa_ContentFilter *a_pFilter, OpcUa_UInt32 a_nMaxDataSetsToReturn, OpcUa_UInt32 a_nMaxReferencesToReturn, OpcUa_Channel_PfnRequestComplete *a_pCallback, OpcUa_Void *a_pCallbackData)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_QueryNext (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader *a_pRequestHeader, OpcUa_Boolean a_bReleaseContinuationPoint, const OpcUa_ByteString *a_pContinuationPoint, OpcUa_ResponseHeader *a_pResponseHeader, OpcUa_Int32 *a_pNoOfQueryDataSets, OpcUa_QueryDataSet **a_pQueryDataSets, OpcUa_ByteString *a_pRevisedContinuationPoint)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginQueryNext (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader *a_pRequestHeader, OpcUa_Boolean a_bReleaseContinuationPoint, const OpcUa_ByteString *a_pContinuationPoint, OpcUa_Channel_PfnRequestComplete *a_pCallback, OpcUa_Void *a_pCallbackData)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_Read (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader *a_pRequestHeader, OpcUa_Double a_nMaxAge, OpcUa_TimestampsToReturn a_eTimestampsToReturn, OpcUa_Int32 a_nNoOfNodesToRead, const OpcUa_ReadValueId *a_pNodesToRead, OpcUa_ResponseHeader *a_pResponseHeader, OpcUa_Int32 *a_pNoOfResults, OpcUa_DataValue **a_pResults, OpcUa_Int32 *a_pNoOfDiagnosticInfos, OpcUa_DiagnosticInfo **a_pDiagnosticInfos)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginRead (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader *a_pRequestHeader, OpcUa_Double a_nMaxAge, OpcUa_TimestampsToReturn a_eTimestampsToReturn, OpcUa_Int32 a_nNoOfNodesToRead, const OpcUa_ReadValueId *a_pNodesToRead, OpcUa_Channel_PfnRequestComplete *a_pCallback, OpcUa_Void *a_pCallbackData)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_HistoryRead (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader *a_pRequestHeader, const OpcUa_ExtensionObject *a_pHistoryReadDetails, OpcUa_TimestampsToReturn a_eTimestampsToReturn, OpcUa_Boolean a_bReleaseContinuationPoints, OpcUa_Int32 a_nNoOfNodesToRead, const OpcUa_HistoryReadValueId *a_pNodesToRead, OpcUa_ResponseHeader *a_pResponseHeader, OpcUa_Int32 *a_pNoOfResults, OpcUa_HistoryReadResult **a_pResults, OpcUa_Int32 *a_pNoOfDiagnosticInfos, OpcUa_DiagnosticInfo **a_pDiagnosticInfos)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginHistoryRead (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader *a_pRequestHeader, const OpcUa_ExtensionObject *a_pHistoryReadDetails, OpcUa_TimestampsToReturn a_eTimestampsToReturn, OpcUa_Boolean a_bReleaseContinuationPoints, OpcUa_Int32 a_nNoOfNodesToRead, const OpcUa_HistoryReadValueId *a_pNodesToRead, OpcUa_Channel_PfnRequestComplete *a_pCallback, OpcUa_Void *a_pCallbackData)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_Write (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader *a_pRequestHeader, OpcUa_Int32 a_nNoOfNodesToWrite, const OpcUa_WriteValue *a_pNodesToWrite, OpcUa_ResponseHeader *a_pResponseHeader, OpcUa_Int32 *a_pNoOfResults, OpcUa_StatusCode **a_pResults, OpcUa_Int32 *a_pNoOfDiagnosticInfos, OpcUa_DiagnosticInfo **a_pDiagnosticInfos)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginWrite (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader *a_pRequestHeader, OpcUa_Int32 a_nNoOfNodesToWrite, const OpcUa_WriteValue *a_pNodesToWrite, OpcUa_Channel_PfnRequestComplete *a_pCallback, OpcUa_Void *a_pCallbackData)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_HistoryUpdate (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader *a_pRequestHeader, OpcUa_Int32 a_nNoOfHistoryUpdateDetails, const OpcUa_ExtensionObject *a_pHistoryUpdateDetails, OpcUa_ResponseHeader *a_pResponseHeader, OpcUa_Int32 *a_pNoOfResults, OpcUa_HistoryUpdateResult **a_pResults, OpcUa_Int32 *a_pNoOfDiagnosticInfos, OpcUa_DiagnosticInfo **a_pDiagnosticInfos)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginHistoryUpdate (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader *a_pRequestHeader, OpcUa_Int32 a_nNoOfHistoryUpdateDetails, const OpcUa_ExtensionObject *a_pHistoryUpdateDetails, OpcUa_Channel_PfnRequestComplete *a_pCallback, OpcUa_Void *a_pCallbackData)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_Call (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader *a_pRequestHeader, OpcUa_Int32 a_nNoOfMethodsToCall, const OpcUa_CallMethodRequest *a_pMethodsToCall, OpcUa_ResponseHeader *a_pResponseHeader, OpcUa_Int32 *a_pNoOfResults, OpcUa_CallMethodResult **a_pResults, OpcUa_Int32 *a_pNoOfDiagnosticInfos, OpcUa_DiagnosticInfo **a_pDiagnosticInfos)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginCall (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader *a_pRequestHeader, OpcUa_Int32 a_nNoOfMethodsToCall, const OpcUa_CallMethodRequest *a_pMethodsToCall, OpcUa_Channel_PfnRequestComplete *a_pCallback, OpcUa_Void *a_pCallbackData)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_CreateMonitoredItems (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader *a_pRequestHeader, OpcUa_UInt32 a_nSubscriptionId, OpcUa_TimestampsToReturn a_eTimestampsToReturn, OpcUa_Int32 a_nNoOfItemsToCreate, const OpcUa_MonitoredItemCreateRequest *a_pItemsToCreate, OpcUa_ResponseHeader *a_pResponseHeader, OpcUa_Int32 *a_pNoOfResults, OpcUa_MonitoredItemCreateResult **a_pResults, OpcUa_Int32 *a_pNoOfDiagnosticInfos, OpcUa_DiagnosticInfo **a_pDiagnosticInfos)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginCreateMonitoredItems (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader *a_pRequestHeader, OpcUa_UInt32 a_nSubscriptionId, OpcUa_TimestampsToReturn a_eTimestampsToReturn, OpcUa_Int32 a_nNoOfItemsToCreate, const OpcUa_MonitoredItemCreateRequest *a_pItemsToCreate, OpcUa_Channel_PfnRequestComplete *a_pCallback, OpcUa_Void *a_pCallbackData)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_ModifyMonitoredItems (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader *a_pRequestHeader, OpcUa_UInt32 a_nSubscriptionId, OpcUa_TimestampsToReturn a_eTimestampsToReturn, OpcUa_Int32 a_nNoOfItemsToModify, const OpcUa_MonitoredItemModifyRequest *a_pItemsToModify, OpcUa_ResponseHeader *a_pResponseHeader, OpcUa_Int32 *a_pNoOfResults, OpcUa_MonitoredItemModifyResult **a_pResults, OpcUa_Int32 *a_pNoOfDiagnosticInfos, OpcUa_DiagnosticInfo **a_pDiagnosticInfos)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginModifyMonitoredItems (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader *a_pRequestHeader, OpcUa_UInt32 a_nSubscriptionId, OpcUa_TimestampsToReturn a_eTimestampsToReturn, OpcUa_Int32 a_nNoOfItemsToModify, const OpcUa_MonitoredItemModifyRequest *a_pItemsToModify, OpcUa_Channel_PfnRequestComplete *a_pCallback, OpcUa_Void *a_pCallbackData)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_SetMonitoringMode (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader *a_pRequestHeader, OpcUa_UInt32 a_nSubscriptionId, OpcUa_MonitoringMode a_eMonitoringMode, OpcUa_Int32 a_nNoOfMonitoredItemIds, const OpcUa_UInt32 *a_pMonitoredItemIds, OpcUa_ResponseHeader *a_pResponseHeader, OpcUa_Int32 *a_pNoOfResults, OpcUa_StatusCode **a_pResults, OpcUa_Int32 *a_pNoOfDiagnosticInfos, OpcUa_DiagnosticInfo **a_pDiagnosticInfos)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginSetMonitoringMode (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader *a_pRequestHeader, OpcUa_UInt32 a_nSubscriptionId, OpcUa_MonitoringMode a_eMonitoringMode, OpcUa_Int32 a_nNoOfMonitoredItemIds, const OpcUa_UInt32 *a_pMonitoredItemIds, OpcUa_Channel_PfnRequestComplete *a_pCallback, OpcUa_Void *a_pCallbackData)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_SetTriggering (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader *a_pRequestHeader, OpcUa_UInt32 a_nSubscriptionId, OpcUa_UInt32 a_nTriggeringItemId, OpcUa_Int32 a_nNoOfLinksToAdd, const OpcUa_UInt32 *a_pLinksToAdd, OpcUa_Int32 a_nNoOfLinksToRemove, const OpcUa_UInt32 *a_pLinksToRemove, OpcUa_ResponseHeader *a_pResponseHeader, OpcUa_Int32 *a_pNoOfAddResults, OpcUa_StatusCode **a_pAddResults, OpcUa_Int32 *a_pNoOfAddDiagnosticInfos, OpcUa_DiagnosticInfo **a_pAddDiagnosticInfos, OpcUa_Int32 *a_pNoOfRemoveResults, OpcUa_StatusCode **a_pRemoveResults, OpcUa_Int32 *a_pNoOfRemoveDiagnosticInfos, OpcUa_DiagnosticInfo **a_pRemoveDiagnosticInfos)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginSetTriggering (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader *a_pRequestHeader, OpcUa_UInt32 a_nSubscriptionId, OpcUa_UInt32 a_nTriggeringItemId, OpcUa_Int32 a_nNoOfLinksToAdd, const OpcUa_UInt32 *a_pLinksToAdd, OpcUa_Int32 a_nNoOfLinksToRemove, const OpcUa_UInt32 *a_pLinksToRemove, OpcUa_Channel_PfnRequestComplete *a_pCallback, OpcUa_Void *a_pCallbackData)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_DeleteMonitoredItems (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader *a_pRequestHeader, OpcUa_UInt32 a_nSubscriptionId, OpcUa_Int32 a_nNoOfMonitoredItemIds, const OpcUa_UInt32 *a_pMonitoredItemIds, OpcUa_ResponseHeader *a_pResponseHeader, OpcUa_Int32 *a_pNoOfResults, OpcUa_StatusCode **a_pResults, OpcUa_Int32 *a_pNoOfDiagnosticInfos, OpcUa_DiagnosticInfo **a_pDiagnosticInfos)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginDeleteMonitoredItems (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader *a_pRequestHeader, OpcUa_UInt32 a_nSubscriptionId, OpcUa_Int32 a_nNoOfMonitoredItemIds, const OpcUa_UInt32 *a_pMonitoredItemIds, OpcUa_Channel_PfnRequestComplete *a_pCallback, OpcUa_Void *a_pCallbackData)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_CreateSubscription (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader *a_pRequestHeader, OpcUa_Double a_nRequestedPublishingInterval, OpcUa_UInt32 a_nRequestedLifetimeCount, OpcUa_UInt32 a_nRequestedMaxKeepAliveCount, OpcUa_UInt32 a_nMaxNotificationsPerPublish, OpcUa_Boolean a_bPublishingEnabled, OpcUa_Byte a_nPriority, OpcUa_ResponseHeader *a_pResponseHeader, OpcUa_UInt32 *a_pSubscriptionId, OpcUa_Double *a_pRevisedPublishingInterval, OpcUa_UInt32 *a_pRevisedLifetimeCount, OpcUa_UInt32 *a_pRevisedMaxKeepAliveCount)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginCreateSubscription (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader *a_pRequestHeader, OpcUa_Double a_nRequestedPublishingInterval, OpcUa_UInt32 a_nRequestedLifetimeCount, OpcUa_UInt32 a_nRequestedMaxKeepAliveCount, OpcUa_UInt32 a_nMaxNotificationsPerPublish, OpcUa_Boolean a_bPublishingEnabled, OpcUa_Byte a_nPriority, OpcUa_Channel_PfnRequestComplete *a_pCallback, OpcUa_Void *a_pCallbackData)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_ModifySubscription (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader *a_pRequestHeader, OpcUa_UInt32 a_nSubscriptionId, OpcUa_Double a_nRequestedPublishingInterval, OpcUa_UInt32 a_nRequestedLifetimeCount, OpcUa_UInt32 a_nRequestedMaxKeepAliveCount, OpcUa_UInt32 a_nMaxNotificationsPerPublish, OpcUa_Byte a_nPriority, OpcUa_ResponseHeader *a_pResponseHeader, OpcUa_Double *a_pRevisedPublishingInterval, OpcUa_UInt32 *a_pRevisedLifetimeCount, OpcUa_UInt32 *a_pRevisedMaxKeepAliveCount)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginModifySubscription (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader *a_pRequestHeader, OpcUa_UInt32 a_nSubscriptionId, OpcUa_Double a_nRequestedPublishingInterval, OpcUa_UInt32 a_nRequestedLifetimeCount, OpcUa_UInt32 a_nRequestedMaxKeepAliveCount, OpcUa_UInt32 a_nMaxNotificationsPerPublish, OpcUa_Byte a_nPriority, OpcUa_Channel_PfnRequestComplete *a_pCallback, OpcUa_Void *a_pCallbackData)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_SetPublishingMode (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader *a_pRequestHeader, OpcUa_Boolean a_bPublishingEnabled, OpcUa_Int32 a_nNoOfSubscriptionIds, const OpcUa_UInt32 *a_pSubscriptionIds, OpcUa_ResponseHeader *a_pResponseHeader, OpcUa_Int32 *a_pNoOfResults, OpcUa_StatusCode **a_pResults, OpcUa_Int32 *a_pNoOfDiagnosticInfos, OpcUa_DiagnosticInfo **a_pDiagnosticInfos)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginSetPublishingMode (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader *a_pRequestHeader, OpcUa_Boolean a_bPublishingEnabled, OpcUa_Int32 a_nNoOfSubscriptionIds, const OpcUa_UInt32 *a_pSubscriptionIds, OpcUa_Channel_PfnRequestComplete *a_pCallback, OpcUa_Void *a_pCallbackData)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_Publish (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader *a_pRequestHeader, OpcUa_Int32 a_nNoOfSubscriptionAcknowledgements, const OpcUa_SubscriptionAcknowledgement *a_pSubscriptionAcknowledgements, OpcUa_ResponseHeader *a_pResponseHeader, OpcUa_UInt32 *a_pSubscriptionId, OpcUa_Int32 *a_pNoOfAvailableSequenceNumbers, OpcUa_UInt32 **a_pAvailableSequenceNumbers, OpcUa_Boolean *a_pMoreNotifications, OpcUa_NotificationMessage *a_pNotificationMessage, OpcUa_Int32 *a_pNoOfResults, OpcUa_StatusCode **a_pResults, OpcUa_Int32 *a_pNoOfDiagnosticInfos, OpcUa_DiagnosticInfo **a_pDiagnosticInfos)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginPublish (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader *a_pRequestHeader, OpcUa_Int32 a_nNoOfSubscriptionAcknowledgements, const OpcUa_SubscriptionAcknowledgement *a_pSubscriptionAcknowledgements, OpcUa_Channel_PfnRequestComplete *a_pCallback, OpcUa_Void *a_pCallbackData)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_Republish (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader *a_pRequestHeader, OpcUa_UInt32 a_nSubscriptionId, OpcUa_UInt32 a_nRetransmitSequenceNumber, OpcUa_ResponseHeader *a_pResponseHeader, OpcUa_NotificationMessage *a_pNotificationMessage)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginRepublish (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader *a_pRequestHeader, OpcUa_UInt32 a_nSubscriptionId, OpcUa_UInt32 a_nRetransmitSequenceNumber, OpcUa_Channel_PfnRequestComplete *a_pCallback, OpcUa_Void *a_pCallbackData)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_TransferSubscriptions (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader *a_pRequestHeader, OpcUa_Int32 a_nNoOfSubscriptionIds, const OpcUa_UInt32 *a_pSubscriptionIds, OpcUa_Boolean a_bSendInitialValues, OpcUa_ResponseHeader *a_pResponseHeader, OpcUa_Int32 *a_pNoOfResults, OpcUa_TransferResult **a_pResults, OpcUa_Int32 *a_pNoOfDiagnosticInfos, OpcUa_DiagnosticInfo **a_pDiagnosticInfos)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginTransferSubscriptions (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader *a_pRequestHeader, OpcUa_Int32 a_nNoOfSubscriptionIds, const OpcUa_UInt32 *a_pSubscriptionIds, OpcUa_Boolean a_bSendInitialValues, OpcUa_Channel_PfnRequestComplete *a_pCallback, OpcUa_Void *a_pCallbackData)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_DeleteSubscriptions (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader *a_pRequestHeader, OpcUa_Int32 a_nNoOfSubscriptionIds, const OpcUa_UInt32 *a_pSubscriptionIds, OpcUa_ResponseHeader *a_pResponseHeader, OpcUa_Int32 *a_pNoOfResults, OpcUa_StatusCode **a_pResults, OpcUa_Int32 *a_pNoOfDiagnosticInfos, OpcUa_DiagnosticInfo **a_pDiagnosticInfos)
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginDeleteSubscriptions (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader *a_pRequestHeader, OpcUa_Int32 a_nNoOfSubscriptionIds, const OpcUa_UInt32 *a_pSubscriptionIds, OpcUa_Channel_PfnRequestComplete *a_pCallback, OpcUa_Void *a_pCallbackData)
Function Documentation
OpcUa_ClientApi_ActivateSession()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_ActivateSession (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader * a_pRequestHeader, const OpcUa_SignatureData * a_pClientSignature, OpcUa_Int32 a_nNoOfClientSoftwareCertificates, const OpcUa_SignedSoftwareCertificate * a_pClientSoftwareCertificates, OpcUa_Int32 a_nNoOfLocaleIds, const OpcUa_String * a_pLocaleIds, const OpcUa_ExtensionObject * a_pUserIdentityToken, const OpcUa_SignatureData * a_pUserTokenSignature, OpcUa_ResponseHeader * a_pResponseHeader, OpcUa_ByteString * a_pServerNonce, OpcUa_Int32 * a_pNoOfResults, OpcUa_StatusCode ** a_pResults, OpcUa_Int32 * a_pNoOfDiagnosticInfos, OpcUa_DiagnosticInfo ** a_pDiagnosticInfos)
Definition at line 908 of file opcua_clientapi.c.
References _OpcUa_ActivateSessionRequest::ClientSignature, _OpcUa_ActivateSessionRequest::ClientSoftwareCertificates, _OpcUa_ActivateSessionRequest::LocaleIds, _OpcUa_ActivateSessionRequest::NoOfClientSoftwareCertificates, _OpcUa_ActivateSessionRequest::NoOfLocaleIds, OpcUa_ActivateSessionRequest_EncodeableType, OpcUa_ActivateSessionRequest_Initialize(), _OpcUa_ActivateSessionRequest::RequestHeader, _OpcUa_ActivateSessionRequest::UserIdentityToken, and _OpcUa_ActivateSessionRequest::UserTokenSignature.
OpcUa_ClientApi_AddNodes()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_AddNodes (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader * a_pRequestHeader, OpcUa_Int32 a_nNoOfNodesToAdd, const OpcUa_AddNodesItem * a_pNodesToAdd, OpcUa_ResponseHeader * a_pResponseHeader, OpcUa_Int32 * a_pNoOfResults, OpcUa_AddNodesResult ** a_pResults, OpcUa_Int32 * a_pNoOfDiagnosticInfos, OpcUa_DiagnosticInfo ** a_pDiagnosticInfos)
Definition at line 1300 of file opcua_clientapi.c.
References _OpcUa_AddNodesRequest::NodesToAdd, _OpcUa_AddNodesRequest::NoOfNodesToAdd, OpcUa_AddNodesRequest_EncodeableType, OpcUa_AddNodesRequest_Initialize(), and _OpcUa_AddNodesRequest::RequestHeader.
OpcUa_ClientApi_AddReferences()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_AddReferences (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader * a_pRequestHeader, OpcUa_Int32 a_nNoOfReferencesToAdd, const OpcUa_AddReferencesItem * a_pReferencesToAdd, OpcUa_ResponseHeader * a_pResponseHeader, OpcUa_Int32 * a_pNoOfResults, OpcUa_StatusCode ** a_pResults, OpcUa_Int32 * a_pNoOfDiagnosticInfos, OpcUa_DiagnosticInfo ** a_pDiagnosticInfos)
Definition at line 1430 of file opcua_clientapi.c.
References _OpcUa_AddReferencesRequest::NoOfReferencesToAdd, OpcUa_AddReferencesRequest_EncodeableType, OpcUa_AddReferencesRequest_Initialize(), _OpcUa_AddReferencesRequest::ReferencesToAdd, and _OpcUa_AddReferencesRequest::RequestHeader.
OpcUa_ClientApi_BeginActivateSession()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginActivateSession (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader * a_pRequestHeader, const OpcUa_SignatureData * a_pClientSignature, OpcUa_Int32 a_nNoOfClientSoftwareCertificates, const OpcUa_SignedSoftwareCertificate * a_pClientSoftwareCertificates, OpcUa_Int32 a_nNoOfLocaleIds, const OpcUa_String * a_pLocaleIds, const OpcUa_ExtensionObject * a_pUserIdentityToken, const OpcUa_SignatureData * a_pUserTokenSignature, OpcUa_Channel_PfnRequestComplete * a_pCallback, OpcUa_Void * a_pCallbackData)
Definition at line 1008 of file opcua_clientapi.c.
References _OpcUa_ActivateSessionRequest::ClientSignature, _OpcUa_ActivateSessionRequest::ClientSoftwareCertificates, _OpcUa_ActivateSessionRequest::LocaleIds, _OpcUa_ActivateSessionRequest::NoOfClientSoftwareCertificates, _OpcUa_ActivateSessionRequest::NoOfLocaleIds, OpcUa_ActivateSessionRequest_EncodeableType, OpcUa_ActivateSessionRequest_Initialize(), _OpcUa_ActivateSessionRequest::RequestHeader, _OpcUa_ActivateSessionRequest::UserIdentityToken, and _OpcUa_ActivateSessionRequest::UserTokenSignature.
OpcUa_ClientApi_BeginAddNodes()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginAddNodes (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader * a_pRequestHeader, OpcUa_Int32 a_nNoOfNodesToAdd, const OpcUa_AddNodesItem * a_pNodesToAdd, OpcUa_Channel_PfnRequestComplete * a_pCallback, OpcUa_Void * a_pCallbackData)
Definition at line 1383 of file opcua_clientapi.c.
References _OpcUa_AddNodesRequest::NodesToAdd, _OpcUa_AddNodesRequest::NoOfNodesToAdd, OpcUa_AddNodesRequest_EncodeableType, OpcUa_AddNodesRequest_Initialize(), and _OpcUa_AddNodesRequest::RequestHeader.
OpcUa_ClientApi_BeginAddReferences()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginAddReferences (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader * a_pRequestHeader, OpcUa_Int32 a_nNoOfReferencesToAdd, const OpcUa_AddReferencesItem * a_pReferencesToAdd, OpcUa_Channel_PfnRequestComplete * a_pCallback, OpcUa_Void * a_pCallbackData)
Definition at line 1513 of file opcua_clientapi.c.
References _OpcUa_AddReferencesRequest::NoOfReferencesToAdd, OpcUa_AddReferencesRequest_EncodeableType, OpcUa_AddReferencesRequest_Initialize(), _OpcUa_AddReferencesRequest::ReferencesToAdd, and _OpcUa_AddReferencesRequest::RequestHeader.
OpcUa_ClientApi_BeginBrowse()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginBrowse (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader * a_pRequestHeader, const OpcUa_ViewDescription * a_pView, OpcUa_UInt32 a_nRequestedMaxReferencesPerNode, OpcUa_Int32 a_nNoOfNodesToBrowse, const OpcUa_BrowseDescription * a_pNodesToBrowse, OpcUa_Channel_PfnRequestComplete * a_pCallback, OpcUa_Void * a_pCallbackData)
Definition at line 1909 of file opcua_clientapi.c.
References _OpcUa_BrowseRequest::NodesToBrowse, _OpcUa_BrowseRequest::NoOfNodesToBrowse, OpcUa_BrowseRequest_EncodeableType, OpcUa_BrowseRequest_Initialize(), _OpcUa_BrowseRequest::RequestedMaxReferencesPerNode, _OpcUa_BrowseRequest::RequestHeader, and _OpcUa_BrowseRequest::View.
OpcUa_ClientApi_BeginBrowseNext()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginBrowseNext (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader * a_pRequestHeader, OpcUa_Boolean a_bReleaseContinuationPoints, OpcUa_Int32 a_nNoOfContinuationPoints, const OpcUa_ByteString * a_pContinuationPoints, OpcUa_Channel_PfnRequestComplete * a_pCallback, OpcUa_Void * a_pCallbackData)
Definition at line 2048 of file opcua_clientapi.c.
References _OpcUa_BrowseNextRequest::ContinuationPoints, _OpcUa_BrowseNextRequest::NoOfContinuationPoints, OpcUa_BrowseNextRequest_EncodeableType, OpcUa_BrowseNextRequest_Initialize(), _OpcUa_BrowseNextRequest::ReleaseContinuationPoints, and _OpcUa_BrowseNextRequest::RequestHeader.
OpcUa_ClientApi_BeginCall()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginCall (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader * a_pRequestHeader, OpcUa_Int32 a_nNoOfMethodsToCall, const OpcUa_CallMethodRequest * a_pMethodsToCall, OpcUa_Channel_PfnRequestComplete * a_pCallback, OpcUa_Void * a_pCallbackData)
Definition at line 3398 of file opcua_clientapi.c.
References _OpcUa_CallRequest::MethodsToCall, _OpcUa_CallRequest::NoOfMethodsToCall, OpcUa_CallRequest_EncodeableType, OpcUa_CallRequest_Initialize(), and _OpcUa_CallRequest::RequestHeader.
OpcUa_ClientApi_BeginCancel()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginCancel (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader * a_pRequestHeader, OpcUa_UInt32 a_nRequestHandle, OpcUa_Channel_PfnRequestComplete * a_pCallback, OpcUa_Void * a_pCallbackData)
Definition at line 1255 of file opcua_clientapi.c.
References OpcUa_CancelRequest_EncodeableType, OpcUa_CancelRequest_Initialize(), _OpcUa_CancelRequest::RequestHandle, and _OpcUa_CancelRequest::RequestHeader.
OpcUa_ClientApi_BeginCloseSession()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginCloseSession (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader * a_pRequestHeader, OpcUa_Boolean a_bDeleteSubscriptions, OpcUa_Channel_PfnRequestComplete * a_pCallback, OpcUa_Void * a_pCallbackData)
Definition at line 1138 of file opcua_clientapi.c.
References _OpcUa_CloseSessionRequest::DeleteSubscriptions, OpcUa_CloseSessionRequest_EncodeableType, OpcUa_CloseSessionRequest_Initialize(), and _OpcUa_CloseSessionRequest::RequestHeader.
OpcUa_ClientApi_BeginCreateMonitoredItems()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginCreateMonitoredItems (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader * a_pRequestHeader, OpcUa_UInt32 a_nSubscriptionId, OpcUa_TimestampsToReturn a_eTimestampsToReturn, OpcUa_Int32 a_nNoOfItemsToCreate, const OpcUa_MonitoredItemCreateRequest * a_pItemsToCreate, OpcUa_Channel_PfnRequestComplete * a_pCallback, OpcUa_Void * a_pCallbackData)
Definition at line 3534 of file opcua_clientapi.c.
References _OpcUa_CreateMonitoredItemsRequest::ItemsToCreate, _OpcUa_CreateMonitoredItemsRequest::NoOfItemsToCreate, OpcUa_CreateMonitoredItemsRequest_EncodeableType, OpcUa_CreateMonitoredItemsRequest_Initialize(), _OpcUa_CreateMonitoredItemsRequest::RequestHeader, _OpcUa_CreateMonitoredItemsRequest::SubscriptionId, and _OpcUa_CreateMonitoredItemsRequest::TimestampsToReturn.
OpcUa_ClientApi_BeginCreateSession()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginCreateSession (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader * a_pRequestHeader, const OpcUa_ApplicationDescription * a_pClientDescription, const OpcUa_String * a_pServerUri, const OpcUa_String * a_pEndpointUrl, const OpcUa_String * a_pSessionName, const OpcUa_ByteString * a_pClientNonce, const OpcUa_ByteString * a_pClientCertificate, OpcUa_Double a_nRequestedSessionTimeout, OpcUa_UInt32 a_nMaxResponseMessageSize, OpcUa_Channel_PfnRequestComplete * a_pCallback, OpcUa_Void * a_pCallbackData)
Definition at line 842 of file opcua_clientapi.c.
References _OpcUa_CreateSessionRequest::ClientCertificate, _OpcUa_CreateSessionRequest::ClientDescription, _OpcUa_CreateSessionRequest::ClientNonce, _OpcUa_CreateSessionRequest::EndpointUrl, _OpcUa_CreateSessionRequest::MaxResponseMessageSize, OpcUa_CreateSessionRequest_EncodeableType, OpcUa_CreateSessionRequest_Initialize(), _OpcUa_CreateSessionRequest::RequestedSessionTimeout, _OpcUa_CreateSessionRequest::RequestHeader, _OpcUa_CreateSessionRequest::ServerUri, and _OpcUa_CreateSessionRequest::SessionName.
OpcUa_ClientApi_BeginCreateSubscription()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginCreateSubscription (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader * a_pRequestHeader, OpcUa_Double a_nRequestedPublishingInterval, OpcUa_UInt32 a_nRequestedLifetimeCount, OpcUa_UInt32 a_nRequestedMaxKeepAliveCount, OpcUa_UInt32 a_nMaxNotificationsPerPublish, OpcUa_Boolean a_bPublishingEnabled, OpcUa_Byte a_nPriority, OpcUa_Channel_PfnRequestComplete * a_pCallback, OpcUa_Void * a_pCallbackData)
Definition at line 4267 of file opcua_clientapi.c.
References _OpcUa_CreateSubscriptionRequest::MaxNotificationsPerPublish, OpcUa_CreateSubscriptionRequest_EncodeableType, OpcUa_CreateSubscriptionRequest_Initialize(), _OpcUa_CreateSubscriptionRequest::Priority, _OpcUa_CreateSubscriptionRequest::PublishingEnabled, _OpcUa_CreateSubscriptionRequest::RequestedLifetimeCount, _OpcUa_CreateSubscriptionRequest::RequestedMaxKeepAliveCount, _OpcUa_CreateSubscriptionRequest::RequestedPublishingInterval, and _OpcUa_CreateSubscriptionRequest::RequestHeader.
OpcUa_ClientApi_BeginDeleteMonitoredItems()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginDeleteMonitoredItems (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader * a_pRequestHeader, OpcUa_UInt32 a_nSubscriptionId, OpcUa_Int32 a_nNoOfMonitoredItemIds, const OpcUa_UInt32 * a_pMonitoredItemIds, OpcUa_Channel_PfnRequestComplete * a_pCallback, OpcUa_Void * a_pCallbackData)
Definition at line 4121 of file opcua_clientapi.c.
References _OpcUa_DeleteMonitoredItemsRequest::MonitoredItemIds, _OpcUa_DeleteMonitoredItemsRequest::NoOfMonitoredItemIds, OpcUa_DeleteMonitoredItemsRequest_EncodeableType, OpcUa_DeleteMonitoredItemsRequest_Initialize(), _OpcUa_DeleteMonitoredItemsRequest::RequestHeader, and _OpcUa_DeleteMonitoredItemsRequest::SubscriptionId.
OpcUa_ClientApi_BeginDeleteNodes()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginDeleteNodes (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader * a_pRequestHeader, OpcUa_Int32 a_nNoOfNodesToDelete, const OpcUa_DeleteNodesItem * a_pNodesToDelete, OpcUa_Channel_PfnRequestComplete * a_pCallback, OpcUa_Void * a_pCallbackData)
Definition at line 1643 of file opcua_clientapi.c.
References _OpcUa_DeleteNodesRequest::NodesToDelete, _OpcUa_DeleteNodesRequest::NoOfNodesToDelete, OpcUa_DeleteNodesRequest_EncodeableType, OpcUa_DeleteNodesRequest_Initialize(), and _OpcUa_DeleteNodesRequest::RequestHeader.
OpcUa_ClientApi_BeginDeleteReferences()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginDeleteReferences (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader * a_pRequestHeader, OpcUa_Int32 a_nNoOfReferencesToDelete, const OpcUa_DeleteReferencesItem * a_pReferencesToDelete, OpcUa_Channel_PfnRequestComplete * a_pCallback, OpcUa_Void * a_pCallbackData)
Definition at line 1773 of file opcua_clientapi.c.
References _OpcUa_DeleteReferencesRequest::NoOfReferencesToDelete, OpcUa_DeleteReferencesRequest_EncodeableType, OpcUa_DeleteReferencesRequest_Initialize(), _OpcUa_DeleteReferencesRequest::ReferencesToDelete, and _OpcUa_DeleteReferencesRequest::RequestHeader.
OpcUa_ClientApi_BeginDeleteSubscriptions()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginDeleteSubscriptions (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader * a_pRequestHeader, OpcUa_Int32 a_nNoOfSubscriptionIds, const OpcUa_UInt32 * a_pSubscriptionIds, OpcUa_Channel_PfnRequestComplete * a_pCallback, OpcUa_Void * a_pCallbackData)
Definition at line 5103 of file opcua_clientapi.c.
References _OpcUa_DeleteSubscriptionsRequest::NoOfSubscriptionIds, OpcUa_DeleteSubscriptionsRequest_EncodeableType, OpcUa_DeleteSubscriptionsRequest_Initialize(), _OpcUa_DeleteSubscriptionsRequest::RequestHeader, and _OpcUa_DeleteSubscriptionsRequest::SubscriptionIds.
OpcUa_ClientApi_BeginFindServers()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginFindServers (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader * a_pRequestHeader, const OpcUa_String * a_pEndpointUrl, OpcUa_Int32 a_nNoOfLocaleIds, const OpcUa_String * a_pLocaleIds, OpcUa_Int32 a_nNoOfServerUris, const OpcUa_String * a_pServerUris, OpcUa_Channel_PfnRequestComplete * a_pCallback, OpcUa_Void * a_pCallbackData)
Definition at line 135 of file opcua_clientapi.c.
References _OpcUa_FindServersRequest::EndpointUrl, _OpcUa_FindServersRequest::LocaleIds, _OpcUa_FindServersRequest::NoOfLocaleIds, _OpcUa_FindServersRequest::NoOfServerUris, OpcUa_FindServersRequest_EncodeableType, OpcUa_FindServersRequest_Initialize(), _OpcUa_FindServersRequest::RequestHeader, and _OpcUa_FindServersRequest::ServerUris.
OpcUa_ClientApi_BeginFindServersOnNetwork()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginFindServersOnNetwork (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader * a_pRequestHeader, OpcUa_UInt32 a_nStartingRecordId, OpcUa_UInt32 a_nMaxRecordsToReturn, OpcUa_Int32 a_nNoOfServerCapabilityFilter, const OpcUa_String * a_pServerCapabilityFilter, OpcUa_Channel_PfnRequestComplete * a_pCallback, OpcUa_Void * a_pCallbackData)
Definition at line 276 of file opcua_clientapi.c.
References _OpcUa_FindServersOnNetworkRequest::MaxRecordsToReturn, _OpcUa_FindServersOnNetworkRequest::NoOfServerCapabilityFilter, OpcUa_FindServersOnNetworkRequest_EncodeableType, OpcUa_FindServersOnNetworkRequest_Initialize(), _OpcUa_FindServersOnNetworkRequest::RequestHeader, _OpcUa_FindServersOnNetworkRequest::ServerCapabilityFilter, and _OpcUa_FindServersOnNetworkRequest::StartingRecordId.
OpcUa_ClientApi_BeginGetEndpoints()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginGetEndpoints (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader * a_pRequestHeader, const OpcUa_String * a_pEndpointUrl, OpcUa_Int32 a_nNoOfLocaleIds, const OpcUa_String * a_pLocaleIds, OpcUa_Int32 a_nNoOfProfileUris, const OpcUa_String * a_pProfileUris, OpcUa_Channel_PfnRequestComplete * a_pCallback, OpcUa_Void * a_pCallbackData)
Definition at line 414 of file opcua_clientapi.c.
References _OpcUa_GetEndpointsRequest::EndpointUrl, _OpcUa_GetEndpointsRequest::LocaleIds, _OpcUa_GetEndpointsRequest::NoOfLocaleIds, _OpcUa_GetEndpointsRequest::NoOfProfileUris, OpcUa_GetEndpointsRequest_EncodeableType, OpcUa_GetEndpointsRequest_Initialize(), _OpcUa_GetEndpointsRequest::ProfileUris, and _OpcUa_GetEndpointsRequest::RequestHeader.
OpcUa_ClientApi_BeginHistoryRead()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginHistoryRead (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader * a_pRequestHeader, const OpcUa_ExtensionObject * a_pHistoryReadDetails, OpcUa_TimestampsToReturn a_eTimestampsToReturn, OpcUa_Boolean a_bReleaseContinuationPoints, OpcUa_Int32 a_nNoOfNodesToRead, const OpcUa_HistoryReadValueId * a_pNodesToRead, OpcUa_Channel_PfnRequestComplete * a_pCallback, OpcUa_Void * a_pCallbackData)
Definition at line 2999 of file opcua_clientapi.c.
References _OpcUa_HistoryReadRequest::HistoryReadDetails, _OpcUa_HistoryReadRequest::NodesToRead, _OpcUa_HistoryReadRequest::NoOfNodesToRead, OpcUa_HistoryReadRequest_EncodeableType, OpcUa_HistoryReadRequest_Initialize(), _OpcUa_HistoryReadRequest::ReleaseContinuationPoints, _OpcUa_HistoryReadRequest::RequestHeader, and _OpcUa_HistoryReadRequest::TimestampsToReturn.
OpcUa_ClientApi_BeginHistoryUpdate()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginHistoryUpdate (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader * a_pRequestHeader, OpcUa_Int32 a_nNoOfHistoryUpdateDetails, const OpcUa_ExtensionObject * a_pHistoryUpdateDetails, OpcUa_Channel_PfnRequestComplete * a_pCallback, OpcUa_Void * a_pCallbackData)
Definition at line 3268 of file opcua_clientapi.c.
References _OpcUa_HistoryUpdateRequest::HistoryUpdateDetails, _OpcUa_HistoryUpdateRequest::NoOfHistoryUpdateDetails, OpcUa_HistoryUpdateRequest_EncodeableType, OpcUa_HistoryUpdateRequest_Initialize(), and _OpcUa_HistoryUpdateRequest::RequestHeader.
OpcUa_ClientApi_BeginModifyMonitoredItems()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginModifyMonitoredItems (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader * a_pRequestHeader, OpcUa_UInt32 a_nSubscriptionId, OpcUa_TimestampsToReturn a_eTimestampsToReturn, OpcUa_Int32 a_nNoOfItemsToModify, const OpcUa_MonitoredItemModifyRequest * a_pItemsToModify, OpcUa_Channel_PfnRequestComplete * a_pCallback, OpcUa_Void * a_pCallbackData)
Definition at line 3676 of file opcua_clientapi.c.
References _OpcUa_ModifyMonitoredItemsRequest::ItemsToModify, _OpcUa_ModifyMonitoredItemsRequest::NoOfItemsToModify, OpcUa_ModifyMonitoredItemsRequest_EncodeableType, OpcUa_ModifyMonitoredItemsRequest_Initialize(), _OpcUa_ModifyMonitoredItemsRequest::RequestHeader, _OpcUa_ModifyMonitoredItemsRequest::SubscriptionId, and _OpcUa_ModifyMonitoredItemsRequest::TimestampsToReturn.
OpcUa_ClientApi_BeginModifySubscription()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginModifySubscription (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader * a_pRequestHeader, OpcUa_UInt32 a_nSubscriptionId, OpcUa_Double a_nRequestedPublishingInterval, OpcUa_UInt32 a_nRequestedLifetimeCount, OpcUa_UInt32 a_nRequestedMaxKeepAliveCount, OpcUa_UInt32 a_nMaxNotificationsPerPublish, OpcUa_Byte a_nPriority, OpcUa_Channel_PfnRequestComplete * a_pCallback, OpcUa_Void * a_pCallbackData)
Definition at line 4420 of file opcua_clientapi.c.
References _OpcUa_ModifySubscriptionRequest::MaxNotificationsPerPublish, OpcUa_ModifySubscriptionRequest_EncodeableType, OpcUa_ModifySubscriptionRequest_Initialize(), _OpcUa_ModifySubscriptionRequest::Priority, _OpcUa_ModifySubscriptionRequest::RequestedLifetimeCount, _OpcUa_ModifySubscriptionRequest::RequestedMaxKeepAliveCount, _OpcUa_ModifySubscriptionRequest::RequestedPublishingInterval, _OpcUa_ModifySubscriptionRequest::RequestHeader, and _OpcUa_ModifySubscriptionRequest::SubscriptionId.
OpcUa_ClientApi_BeginPublish()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginPublish (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader * a_pRequestHeader, OpcUa_Int32 a_nNoOfSubscriptionAcknowledgements, const OpcUa_SubscriptionAcknowledgement * a_pSubscriptionAcknowledgements, OpcUa_Channel_PfnRequestComplete * a_pCallback, OpcUa_Void * a_pCallbackData)
Definition at line 4714 of file opcua_clientapi.c.
References _OpcUa_PublishRequest::NoOfSubscriptionAcknowledgements, OpcUa_PublishRequest_EncodeableType, OpcUa_PublishRequest_Initialize(), _OpcUa_PublishRequest::RequestHeader, and _OpcUa_PublishRequest::SubscriptionAcknowledgements.
OpcUa_ClientApi_BeginQueryFirst()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginQueryFirst (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader * a_pRequestHeader, const OpcUa_ViewDescription * a_pView, OpcUa_Int32 a_nNoOfNodeTypes, const OpcUa_NodeTypeDescription * a_pNodeTypes, const OpcUa_ContentFilter * a_pFilter, OpcUa_UInt32 a_nMaxDataSetsToReturn, OpcUa_UInt32 a_nMaxReferencesToReturn, OpcUa_Channel_PfnRequestComplete * a_pCallback, OpcUa_Void * a_pCallbackData)
Definition at line 2577 of file opcua_clientapi.c.
References _OpcUa_QueryFirstRequest::Filter, _OpcUa_QueryFirstRequest::MaxDataSetsToReturn, _OpcUa_QueryFirstRequest::MaxReferencesToReturn, _OpcUa_QueryFirstRequest::NodeTypes, _OpcUa_QueryFirstRequest::NoOfNodeTypes, OpcUa_QueryFirstRequest_EncodeableType, OpcUa_QueryFirstRequest_Initialize(), _OpcUa_QueryFirstRequest::RequestHeader, and _OpcUa_QueryFirstRequest::View.
OpcUa_ClientApi_BeginQueryNext()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginQueryNext (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader * a_pRequestHeader, OpcUa_Boolean a_bReleaseContinuationPoint, const OpcUa_ByteString * a_pContinuationPoint, OpcUa_Channel_PfnRequestComplete * a_pCallback, OpcUa_Void * a_pCallbackData)
Definition at line 2717 of file opcua_clientapi.c.
References _OpcUa_QueryNextRequest::ContinuationPoint, OpcUa_QueryNextRequest_EncodeableType, OpcUa_QueryNextRequest_Initialize(), _OpcUa_QueryNextRequest::ReleaseContinuationPoint, and _OpcUa_QueryNextRequest::RequestHeader.
OpcUa_ClientApi_BeginRead()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginRead (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader * a_pRequestHeader, OpcUa_Double a_nMaxAge, OpcUa_TimestampsToReturn a_eTimestampsToReturn, OpcUa_Int32 a_nNoOfNodesToRead, const OpcUa_ReadValueId * a_pNodesToRead, OpcUa_Channel_PfnRequestComplete * a_pCallback, OpcUa_Void * a_pCallbackData)
Definition at line 2854 of file opcua_clientapi.c.
References _OpcUa_ReadRequest::MaxAge, _OpcUa_ReadRequest::NodesToRead, _OpcUa_ReadRequest::NoOfNodesToRead, OpcUa_ReadRequest_EncodeableType, OpcUa_ReadRequest_Initialize(), _OpcUa_ReadRequest::RequestHeader, and _OpcUa_ReadRequest::TimestampsToReturn.
OpcUa_ClientApi_BeginRegisterNodes()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginRegisterNodes (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader * a_pRequestHeader, OpcUa_Int32 a_nNoOfNodesToRegister, const OpcUa_NodeId * a_pNodesToRegister, OpcUa_Channel_PfnRequestComplete * a_pCallback, OpcUa_Void * a_pCallbackData)
Definition at line 2305 of file opcua_clientapi.c.
References _OpcUa_RegisterNodesRequest::NodesToRegister, _OpcUa_RegisterNodesRequest::NoOfNodesToRegister, OpcUa_RegisterNodesRequest_EncodeableType, OpcUa_RegisterNodesRequest_Initialize(), and _OpcUa_RegisterNodesRequest::RequestHeader.
OpcUa_ClientApi_BeginRegisterServer()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginRegisterServer (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader * a_pRequestHeader, const OpcUa_RegisteredServer * a_pServer, OpcUa_Channel_PfnRequestComplete * a_pCallback, OpcUa_Void * a_pCallbackData)
Definition at line 538 of file opcua_clientapi.c.
References OpcUa_RegisterServerRequest_EncodeableType, OpcUa_RegisterServerRequest_Initialize(), _OpcUa_RegisterServerRequest::RequestHeader, and _OpcUa_RegisterServerRequest::Server.
OpcUa_ClientApi_BeginRegisterServer2()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginRegisterServer2 (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader * a_pRequestHeader, const OpcUa_RegisteredServer * a_pServer, OpcUa_Int32 a_nNoOfDiscoveryConfiguration, const OpcUa_ExtensionObject * a_pDiscoveryConfiguration, OpcUa_Channel_PfnRequestComplete * a_pCallback, OpcUa_Void * a_pCallbackData)
Definition at line 669 of file opcua_clientapi.c.
References _OpcUa_RegisterServer2Request::DiscoveryConfiguration, _OpcUa_RegisterServer2Request::NoOfDiscoveryConfiguration, OpcUa_RegisterServer2Request_EncodeableType, OpcUa_RegisterServer2Request_Initialize(), _OpcUa_RegisterServer2Request::RequestHeader, and _OpcUa_RegisterServer2Request::Server.
OpcUa_ClientApi_BeginRepublish()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginRepublish (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader * a_pRequestHeader, OpcUa_UInt32 a_nSubscriptionId, OpcUa_UInt32 a_nRetransmitSequenceNumber, OpcUa_Channel_PfnRequestComplete * a_pCallback, OpcUa_Void * a_pCallbackData)
Definition at line 4836 of file opcua_clientapi.c.
References OpcUa_RepublishRequest_EncodeableType, OpcUa_RepublishRequest_Initialize(), _OpcUa_RepublishRequest::RequestHeader, _OpcUa_RepublishRequest::RetransmitSequenceNumber, and _OpcUa_RepublishRequest::SubscriptionId.
OpcUa_ClientApi_BeginSetMonitoringMode()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginSetMonitoringMode (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader * a_pRequestHeader, OpcUa_UInt32 a_nSubscriptionId, OpcUa_MonitoringMode a_eMonitoringMode, OpcUa_Int32 a_nNoOfMonitoredItemIds, const OpcUa_UInt32 * a_pMonitoredItemIds, OpcUa_Channel_PfnRequestComplete * a_pCallback, OpcUa_Void * a_pCallbackData)
Definition at line 3818 of file opcua_clientapi.c.
References _OpcUa_SetMonitoringModeRequest::MonitoredItemIds, _OpcUa_SetMonitoringModeRequest::MonitoringMode, _OpcUa_SetMonitoringModeRequest::NoOfMonitoredItemIds, OpcUa_SetMonitoringModeRequest_EncodeableType, OpcUa_SetMonitoringModeRequest_Initialize(), _OpcUa_SetMonitoringModeRequest::RequestHeader, and _OpcUa_SetMonitoringModeRequest::SubscriptionId.
OpcUa_ClientApi_BeginSetPublishingMode()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginSetPublishingMode (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader * a_pRequestHeader, OpcUa_Boolean a_bPublishingEnabled, OpcUa_Int32 a_nNoOfSubscriptionIds, const OpcUa_UInt32 * a_pSubscriptionIds, OpcUa_Channel_PfnRequestComplete * a_pCallback, OpcUa_Void * a_pCallbackData)
Definition at line 4566 of file opcua_clientapi.c.
References _OpcUa_SetPublishingModeRequest::NoOfSubscriptionIds, OpcUa_SetPublishingModeRequest_EncodeableType, OpcUa_SetPublishingModeRequest_Initialize(), _OpcUa_SetPublishingModeRequest::PublishingEnabled, _OpcUa_SetPublishingModeRequest::RequestHeader, and _OpcUa_SetPublishingModeRequest::SubscriptionIds.
OpcUa_ClientApi_BeginSetTriggering()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginSetTriggering (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader * a_pRequestHeader, OpcUa_UInt32 a_nSubscriptionId, OpcUa_UInt32 a_nTriggeringItemId, OpcUa_Int32 a_nNoOfLinksToAdd, const OpcUa_UInt32 * a_pLinksToAdd, OpcUa_Int32 a_nNoOfLinksToRemove, const OpcUa_UInt32 * a_pLinksToRemove, OpcUa_Channel_PfnRequestComplete * a_pCallback, OpcUa_Void * a_pCallbackData)
Definition at line 3977 of file opcua_clientapi.c.
References _OpcUa_SetTriggeringRequest::LinksToAdd, _OpcUa_SetTriggeringRequest::LinksToRemove, _OpcUa_SetTriggeringRequest::NoOfLinksToAdd, _OpcUa_SetTriggeringRequest::NoOfLinksToRemove, OpcUa_SetTriggeringRequest_EncodeableType, OpcUa_SetTriggeringRequest_Initialize(), _OpcUa_SetTriggeringRequest::RequestHeader, _OpcUa_SetTriggeringRequest::SubscriptionId, and _OpcUa_SetTriggeringRequest::TriggeringItemId.
OpcUa_ClientApi_BeginTransferSubscriptions()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginTransferSubscriptions (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader * a_pRequestHeader, OpcUa_Int32 a_nNoOfSubscriptionIds, const OpcUa_UInt32 * a_pSubscriptionIds, OpcUa_Boolean a_bSendInitialValues, OpcUa_Channel_PfnRequestComplete * a_pCallback, OpcUa_Void * a_pCallbackData)
Definition at line 4970 of file opcua_clientapi.c.
References _OpcUa_TransferSubscriptionsRequest::NoOfSubscriptionIds, OpcUa_TransferSubscriptionsRequest_EncodeableType, OpcUa_TransferSubscriptionsRequest_Initialize(), _OpcUa_TransferSubscriptionsRequest::RequestHeader, _OpcUa_TransferSubscriptionsRequest::SendInitialValues, and _OpcUa_TransferSubscriptionsRequest::SubscriptionIds.
OpcUa_ClientApi_BeginTranslateBrowsePathsToNodeIds()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginTranslateBrowsePathsToNodeIds (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader * a_pRequestHeader, OpcUa_Int32 a_nNoOfBrowsePaths, const OpcUa_BrowsePath * a_pBrowsePaths, OpcUa_Channel_PfnRequestComplete * a_pCallback, OpcUa_Void * a_pCallbackData)
Definition at line 2181 of file opcua_clientapi.c.
References _OpcUa_TranslateBrowsePathsToNodeIdsRequest::BrowsePaths, _OpcUa_TranslateBrowsePathsToNodeIdsRequest::NoOfBrowsePaths, OpcUa_TranslateBrowsePathsToNodeIdsRequest_EncodeableType, OpcUa_TranslateBrowsePathsToNodeIdsRequest_Initialize(), and _OpcUa_TranslateBrowsePathsToNodeIdsRequest::RequestHeader.
OpcUa_ClientApi_BeginUnregisterNodes()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginUnregisterNodes (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader * a_pRequestHeader, OpcUa_Int32 a_nNoOfNodesToUnregister, const OpcUa_NodeId * a_pNodesToUnregister, OpcUa_Channel_PfnRequestComplete * a_pCallback, OpcUa_Void * a_pCallbackData)
Definition at line 2423 of file opcua_clientapi.c.
References _OpcUa_UnregisterNodesRequest::NodesToUnregister, _OpcUa_UnregisterNodesRequest::NoOfNodesToUnregister, OpcUa_UnregisterNodesRequest_EncodeableType, OpcUa_UnregisterNodesRequest_Initialize(), and _OpcUa_UnregisterNodesRequest::RequestHeader.
OpcUa_ClientApi_BeginWrite()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BeginWrite (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader * a_pRequestHeader, OpcUa_Int32 a_nNoOfNodesToWrite, const OpcUa_WriteValue * a_pNodesToWrite, OpcUa_Channel_PfnRequestComplete * a_pCallback, OpcUa_Void * a_pCallbackData)
Definition at line 3138 of file opcua_clientapi.c.
References _OpcUa_WriteRequest::NodesToWrite, _OpcUa_WriteRequest::NoOfNodesToWrite, OpcUa_WriteRequest_EncodeableType, OpcUa_WriteRequest_Initialize(), and _OpcUa_WriteRequest::RequestHeader.
OpcUa_ClientApi_Browse()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_Browse (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader * a_pRequestHeader, const OpcUa_ViewDescription * a_pView, OpcUa_UInt32 a_nRequestedMaxReferencesPerNode, OpcUa_Int32 a_nNoOfNodesToBrowse, const OpcUa_BrowseDescription * a_pNodesToBrowse, OpcUa_ResponseHeader * a_pResponseHeader, OpcUa_Int32 * a_pNoOfResults, OpcUa_BrowseResult ** a_pResults, OpcUa_Int32 * a_pNoOfDiagnosticInfos, OpcUa_DiagnosticInfo ** a_pDiagnosticInfos)
Definition at line 1820 of file opcua_clientapi.c.
References _OpcUa_BrowseRequest::NodesToBrowse, _OpcUa_BrowseRequest::NoOfNodesToBrowse, OpcUa_BrowseRequest_EncodeableType, OpcUa_BrowseRequest_Initialize(), _OpcUa_BrowseRequest::RequestedMaxReferencesPerNode, _OpcUa_BrowseRequest::RequestHeader, and _OpcUa_BrowseRequest::View.
OpcUa_ClientApi_BrowseNext()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_BrowseNext (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader * a_pRequestHeader, OpcUa_Boolean a_bReleaseContinuationPoints, OpcUa_Int32 a_nNoOfContinuationPoints, const OpcUa_ByteString * a_pContinuationPoints, OpcUa_ResponseHeader * a_pResponseHeader, OpcUa_Int32 * a_pNoOfResults, OpcUa_BrowseResult ** a_pResults, OpcUa_Int32 * a_pNoOfDiagnosticInfos, OpcUa_DiagnosticInfo ** a_pDiagnosticInfos)
Definition at line 1962 of file opcua_clientapi.c.
References _OpcUa_BrowseNextRequest::ContinuationPoints, _OpcUa_BrowseNextRequest::NoOfContinuationPoints, OpcUa_BrowseNextRequest_EncodeableType, OpcUa_BrowseNextRequest_Initialize(), _OpcUa_BrowseNextRequest::ReleaseContinuationPoints, and _OpcUa_BrowseNextRequest::RequestHeader.
OpcUa_ClientApi_Call()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_Call (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader * a_pRequestHeader, OpcUa_Int32 a_nNoOfMethodsToCall, const OpcUa_CallMethodRequest * a_pMethodsToCall, OpcUa_ResponseHeader * a_pResponseHeader, OpcUa_Int32 * a_pNoOfResults, OpcUa_CallMethodResult ** a_pResults, OpcUa_Int32 * a_pNoOfDiagnosticInfos, OpcUa_DiagnosticInfo ** a_pDiagnosticInfos)
Definition at line 3315 of file opcua_clientapi.c.
References _OpcUa_CallRequest::MethodsToCall, _OpcUa_CallRequest::NoOfMethodsToCall, OpcUa_CallRequest_EncodeableType, OpcUa_CallRequest_Initialize(), and _OpcUa_CallRequest::RequestHeader.
OpcUa_ClientApi_Cancel()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_Cancel (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader * a_pRequestHeader, OpcUa_UInt32 a_nRequestHandle, OpcUa_ResponseHeader * a_pResponseHeader, OpcUa_UInt32 * a_pCancelCount)
Definition at line 1183 of file opcua_clientapi.c.
References OpcUa_CancelRequest_EncodeableType, OpcUa_CancelRequest_Initialize(), _OpcUa_CancelRequest::RequestHandle, and _OpcUa_CancelRequest::RequestHeader.
OpcUa_ClientApi_CloseSession()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_CloseSession (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader * a_pRequestHeader, OpcUa_Boolean a_bDeleteSubscriptions, OpcUa_ResponseHeader * a_pResponseHeader)
Definition at line 1069 of file opcua_clientapi.c.
References _OpcUa_CloseSessionRequest::DeleteSubscriptions, OpcUa_CloseSessionRequest_EncodeableType, OpcUa_CloseSessionRequest_Initialize(), and _OpcUa_CloseSessionRequest::RequestHeader.
OpcUa_ClientApi_CreateMonitoredItems()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_CreateMonitoredItems (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader * a_pRequestHeader, OpcUa_UInt32 a_nSubscriptionId, OpcUa_TimestampsToReturn a_eTimestampsToReturn, OpcUa_Int32 a_nNoOfItemsToCreate, const OpcUa_MonitoredItemCreateRequest * a_pItemsToCreate, OpcUa_ResponseHeader * a_pResponseHeader, OpcUa_Int32 * a_pNoOfResults, OpcUa_MonitoredItemCreateResult ** a_pResults, OpcUa_Int32 * a_pNoOfDiagnosticInfos, OpcUa_DiagnosticInfo ** a_pDiagnosticInfos)
Definition at line 3445 of file opcua_clientapi.c.
References _OpcUa_CreateMonitoredItemsRequest::ItemsToCreate, _OpcUa_CreateMonitoredItemsRequest::NoOfItemsToCreate, OpcUa_CreateMonitoredItemsRequest_EncodeableType, OpcUa_CreateMonitoredItemsRequest_Initialize(), _OpcUa_CreateMonitoredItemsRequest::RequestHeader, _OpcUa_CreateMonitoredItemsRequest::SubscriptionId, and _OpcUa_CreateMonitoredItemsRequest::TimestampsToReturn.
OpcUa_ClientApi_CreateSession()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_CreateSession (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader * a_pRequestHeader, const OpcUa_ApplicationDescription * a_pClientDescription, const OpcUa_String * a_pServerUri, const OpcUa_String * a_pEndpointUrl, const OpcUa_String * a_pSessionName, const OpcUa_ByteString * a_pClientNonce, const OpcUa_ByteString * a_pClientCertificate, OpcUa_Double a_nRequestedSessionTimeout, OpcUa_UInt32 a_nMaxResponseMessageSize, OpcUa_ResponseHeader * a_pResponseHeader, OpcUa_NodeId * a_pSessionId, OpcUa_NodeId * a_pAuthenticationToken, OpcUa_Double * a_pRevisedSessionTimeout, OpcUa_ByteString * a_pServerNonce, OpcUa_ByteString * a_pServerCertificate, OpcUa_Int32 * a_pNoOfServerEndpoints, OpcUa_EndpointDescription ** a_pServerEndpoints, OpcUa_Int32 * a_pNoOfServerSoftwareCertificates, OpcUa_SignedSoftwareCertificate ** a_pServerSoftwareCertificates, OpcUa_SignatureData * a_pServerSignature, OpcUa_UInt32 * a_pMaxRequestMessageSize)
Definition at line 719 of file opcua_clientapi.c.
References _OpcUa_CreateSessionRequest::ClientCertificate, _OpcUa_CreateSessionRequest::ClientDescription, _OpcUa_CreateSessionRequest::ClientNonce, _OpcUa_CreateSessionRequest::EndpointUrl, _OpcUa_CreateSessionRequest::MaxResponseMessageSize, OpcUa_CreateSessionRequest_EncodeableType, OpcUa_CreateSessionRequest_Initialize(), _OpcUa_CreateSessionRequest::RequestedSessionTimeout, _OpcUa_CreateSessionRequest::RequestHeader, _OpcUa_CreateSessionRequest::ServerUri, and _OpcUa_CreateSessionRequest::SessionName.
OpcUa_ClientApi_CreateSubscription()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_CreateSubscription (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader * a_pRequestHeader, OpcUa_Double a_nRequestedPublishingInterval, OpcUa_UInt32 a_nRequestedLifetimeCount, OpcUa_UInt32 a_nRequestedMaxKeepAliveCount, OpcUa_UInt32 a_nMaxNotificationsPerPublish, OpcUa_Boolean a_bPublishingEnabled, OpcUa_Byte a_nPriority, OpcUa_ResponseHeader * a_pResponseHeader, OpcUa_UInt32 * a_pSubscriptionId, OpcUa_Double * a_pRevisedPublishingInterval, OpcUa_UInt32 * a_pRevisedLifetimeCount, OpcUa_UInt32 * a_pRevisedMaxKeepAliveCount)
Definition at line 4171 of file opcua_clientapi.c.
References _OpcUa_CreateSubscriptionRequest::MaxNotificationsPerPublish, OpcUa_CreateSubscriptionRequest_EncodeableType, OpcUa_CreateSubscriptionRequest_Initialize(), _OpcUa_CreateSubscriptionRequest::Priority, _OpcUa_CreateSubscriptionRequest::PublishingEnabled, _OpcUa_CreateSubscriptionRequest::RequestedLifetimeCount, _OpcUa_CreateSubscriptionRequest::RequestedMaxKeepAliveCount, _OpcUa_CreateSubscriptionRequest::RequestedPublishingInterval, and _OpcUa_CreateSubscriptionRequest::RequestHeader.
OpcUa_ClientApi_DeleteMonitoredItems()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_DeleteMonitoredItems (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader * a_pRequestHeader, OpcUa_UInt32 a_nSubscriptionId, OpcUa_Int32 a_nNoOfMonitoredItemIds, const OpcUa_UInt32 * a_pMonitoredItemIds, OpcUa_ResponseHeader * a_pResponseHeader, OpcUa_Int32 * a_pNoOfResults, OpcUa_StatusCode ** a_pResults, OpcUa_Int32 * a_pNoOfDiagnosticInfos, OpcUa_DiagnosticInfo ** a_pDiagnosticInfos)
Definition at line 4035 of file opcua_clientapi.c.
References _OpcUa_DeleteMonitoredItemsRequest::MonitoredItemIds, _OpcUa_DeleteMonitoredItemsRequest::NoOfMonitoredItemIds, OpcUa_DeleteMonitoredItemsRequest_EncodeableType, OpcUa_DeleteMonitoredItemsRequest_Initialize(), _OpcUa_DeleteMonitoredItemsRequest::RequestHeader, and _OpcUa_DeleteMonitoredItemsRequest::SubscriptionId.
OpcUa_ClientApi_DeleteNodes()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_DeleteNodes (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader * a_pRequestHeader, OpcUa_Int32 a_nNoOfNodesToDelete, const OpcUa_DeleteNodesItem * a_pNodesToDelete, OpcUa_ResponseHeader * a_pResponseHeader, OpcUa_Int32 * a_pNoOfResults, OpcUa_StatusCode ** a_pResults, OpcUa_Int32 * a_pNoOfDiagnosticInfos, OpcUa_DiagnosticInfo ** a_pDiagnosticInfos)
Definition at line 1560 of file opcua_clientapi.c.
References _OpcUa_DeleteNodesRequest::NodesToDelete, _OpcUa_DeleteNodesRequest::NoOfNodesToDelete, OpcUa_DeleteNodesRequest_EncodeableType, OpcUa_DeleteNodesRequest_Initialize(), and _OpcUa_DeleteNodesRequest::RequestHeader.
OpcUa_ClientApi_DeleteReferences()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_DeleteReferences (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader * a_pRequestHeader, OpcUa_Int32 a_nNoOfReferencesToDelete, const OpcUa_DeleteReferencesItem * a_pReferencesToDelete, OpcUa_ResponseHeader * a_pResponseHeader, OpcUa_Int32 * a_pNoOfResults, OpcUa_StatusCode ** a_pResults, OpcUa_Int32 * a_pNoOfDiagnosticInfos, OpcUa_DiagnosticInfo ** a_pDiagnosticInfos)
Definition at line 1690 of file opcua_clientapi.c.
References _OpcUa_DeleteReferencesRequest::NoOfReferencesToDelete, OpcUa_DeleteReferencesRequest_EncodeableType, OpcUa_DeleteReferencesRequest_Initialize(), _OpcUa_DeleteReferencesRequest::ReferencesToDelete, and _OpcUa_DeleteReferencesRequest::RequestHeader.
OpcUa_ClientApi_DeleteSubscriptions()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_DeleteSubscriptions (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader * a_pRequestHeader, OpcUa_Int32 a_nNoOfSubscriptionIds, const OpcUa_UInt32 * a_pSubscriptionIds, OpcUa_ResponseHeader * a_pResponseHeader, OpcUa_Int32 * a_pNoOfResults, OpcUa_StatusCode ** a_pResults, OpcUa_Int32 * a_pNoOfDiagnosticInfos, OpcUa_DiagnosticInfo ** a_pDiagnosticInfos)
Definition at line 5020 of file opcua_clientapi.c.
References _OpcUa_DeleteSubscriptionsRequest::NoOfSubscriptionIds, OpcUa_DeleteSubscriptionsRequest_EncodeableType, OpcUa_DeleteSubscriptionsRequest_Initialize(), _OpcUa_DeleteSubscriptionsRequest::RequestHeader, and _OpcUa_DeleteSubscriptionsRequest::SubscriptionIds.
OpcUa_ClientApi_FindServers()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_FindServers (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader * a_pRequestHeader, const OpcUa_String * a_pEndpointUrl, OpcUa_Int32 a_nNoOfLocaleIds, const OpcUa_String * a_pLocaleIds, OpcUa_Int32 a_nNoOfServerUris, const OpcUa_String * a_pServerUris, OpcUa_ResponseHeader * a_pResponseHeader, OpcUa_Int32 * a_pNoOfServers, OpcUa_ApplicationDescription ** a_pServers)
Definition at line 50 of file opcua_clientapi.c.
References _OpcUa_FindServersRequest::EndpointUrl, _OpcUa_FindServersRequest::LocaleIds, _OpcUa_FindServersRequest::NoOfLocaleIds, _OpcUa_FindServersRequest::NoOfServerUris, OpcUa_FindServersRequest_EncodeableType, OpcUa_FindServersRequest_Initialize(), _OpcUa_FindServersRequest::RequestHeader, and _OpcUa_FindServersRequest::ServerUris.
OpcUa_ClientApi_FindServersOnNetwork()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_FindServersOnNetwork (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader * a_pRequestHeader, OpcUa_UInt32 a_nStartingRecordId, OpcUa_UInt32 a_nMaxRecordsToReturn, OpcUa_Int32 a_nNoOfServerCapabilityFilter, const OpcUa_String * a_pServerCapabilityFilter, OpcUa_ResponseHeader * a_pResponseHeader, OpcUa_DateTime * a_pLastCounterResetTime, OpcUa_Int32 * a_pNoOfServers, OpcUa_ServerOnNetwork ** a_pServers)
Definition at line 190 of file opcua_clientapi.c.
References _OpcUa_FindServersOnNetworkRequest::MaxRecordsToReturn, _OpcUa_FindServersOnNetworkRequest::NoOfServerCapabilityFilter, OpcUa_FindServersOnNetworkRequest_EncodeableType, OpcUa_FindServersOnNetworkRequest_Initialize(), _OpcUa_FindServersOnNetworkRequest::RequestHeader, _OpcUa_FindServersOnNetworkRequest::ServerCapabilityFilter, and _OpcUa_FindServersOnNetworkRequest::StartingRecordId.
OpcUa_ClientApi_GetEndpoints()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_GetEndpoints (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader * a_pRequestHeader, const OpcUa_String * a_pEndpointUrl, OpcUa_Int32 a_nNoOfLocaleIds, const OpcUa_String * a_pLocaleIds, OpcUa_Int32 a_nNoOfProfileUris, const OpcUa_String * a_pProfileUris, OpcUa_ResponseHeader * a_pResponseHeader, OpcUa_Int32 * a_pNoOfEndpoints, OpcUa_EndpointDescription ** a_pEndpoints)
Definition at line 329 of file opcua_clientapi.c.
References _OpcUa_GetEndpointsRequest::EndpointUrl, _OpcUa_GetEndpointsRequest::LocaleIds, _OpcUa_GetEndpointsRequest::NoOfLocaleIds, _OpcUa_GetEndpointsRequest::NoOfProfileUris, OpcUa_GetEndpointsRequest_EncodeableType, OpcUa_GetEndpointsRequest_Initialize(), _OpcUa_GetEndpointsRequest::ProfileUris, and _OpcUa_GetEndpointsRequest::RequestHeader.
OpcUa_ClientApi_HistoryRead()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_HistoryRead (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader * a_pRequestHeader, const OpcUa_ExtensionObject * a_pHistoryReadDetails, OpcUa_TimestampsToReturn a_eTimestampsToReturn, OpcUa_Boolean a_bReleaseContinuationPoints, OpcUa_Int32 a_nNoOfNodesToRead, const OpcUa_HistoryReadValueId * a_pNodesToRead, OpcUa_ResponseHeader * a_pResponseHeader, OpcUa_Int32 * a_pNoOfResults, OpcUa_HistoryReadResult ** a_pResults, OpcUa_Int32 * a_pNoOfDiagnosticInfos, OpcUa_DiagnosticInfo ** a_pDiagnosticInfos)
Definition at line 2907 of file opcua_clientapi.c.
References _OpcUa_HistoryReadRequest::HistoryReadDetails, _OpcUa_HistoryReadRequest::NodesToRead, _OpcUa_HistoryReadRequest::NoOfNodesToRead, OpcUa_HistoryReadRequest_EncodeableType, OpcUa_HistoryReadRequest_Initialize(), _OpcUa_HistoryReadRequest::ReleaseContinuationPoints, _OpcUa_HistoryReadRequest::RequestHeader, and _OpcUa_HistoryReadRequest::TimestampsToReturn.
OpcUa_ClientApi_HistoryUpdate()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_HistoryUpdate (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader * a_pRequestHeader, OpcUa_Int32 a_nNoOfHistoryUpdateDetails, const OpcUa_ExtensionObject * a_pHistoryUpdateDetails, OpcUa_ResponseHeader * a_pResponseHeader, OpcUa_Int32 * a_pNoOfResults, OpcUa_HistoryUpdateResult ** a_pResults, OpcUa_Int32 * a_pNoOfDiagnosticInfos, OpcUa_DiagnosticInfo ** a_pDiagnosticInfos)
Definition at line 3185 of file opcua_clientapi.c.
References _OpcUa_HistoryUpdateRequest::HistoryUpdateDetails, _OpcUa_HistoryUpdateResult::NoOfDiagnosticInfos, _OpcUa_HistoryUpdateRequest::NoOfHistoryUpdateDetails, OpcUa_HistoryUpdateRequest_EncodeableType, OpcUa_HistoryUpdateRequest_Initialize(), and _OpcUa_HistoryUpdateRequest::RequestHeader.
OpcUa_ClientApi_ModifyMonitoredItems()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_ModifyMonitoredItems (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader * a_pRequestHeader, OpcUa_UInt32 a_nSubscriptionId, OpcUa_TimestampsToReturn a_eTimestampsToReturn, OpcUa_Int32 a_nNoOfItemsToModify, const OpcUa_MonitoredItemModifyRequest * a_pItemsToModify, OpcUa_ResponseHeader * a_pResponseHeader, OpcUa_Int32 * a_pNoOfResults, OpcUa_MonitoredItemModifyResult ** a_pResults, OpcUa_Int32 * a_pNoOfDiagnosticInfos, OpcUa_DiagnosticInfo ** a_pDiagnosticInfos)
Definition at line 3587 of file opcua_clientapi.c.
References _OpcUa_ModifyMonitoredItemsRequest::ItemsToModify, _OpcUa_ModifyMonitoredItemsRequest::NoOfItemsToModify, OpcUa_ModifyMonitoredItemsRequest_EncodeableType, OpcUa_ModifyMonitoredItemsRequest_Initialize(), _OpcUa_ModifyMonitoredItemsRequest::RequestHeader, _OpcUa_ModifyMonitoredItemsRequest::SubscriptionId, and _OpcUa_ModifyMonitoredItemsRequest::TimestampsToReturn.
OpcUa_ClientApi_ModifySubscription()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_ModifySubscription (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader * a_pRequestHeader, OpcUa_UInt32 a_nSubscriptionId, OpcUa_Double a_nRequestedPublishingInterval, OpcUa_UInt32 a_nRequestedLifetimeCount, OpcUa_UInt32 a_nRequestedMaxKeepAliveCount, OpcUa_UInt32 a_nMaxNotificationsPerPublish, OpcUa_Byte a_nPriority, OpcUa_ResponseHeader * a_pResponseHeader, OpcUa_Double * a_pRevisedPublishingInterval, OpcUa_UInt32 * a_pRevisedLifetimeCount, OpcUa_UInt32 * a_pRevisedMaxKeepAliveCount)
Definition at line 4327 of file opcua_clientapi.c.
References _OpcUa_ModifySubscriptionRequest::MaxNotificationsPerPublish, OpcUa_ModifySubscriptionRequest_EncodeableType, OpcUa_ModifySubscriptionRequest_Initialize(), _OpcUa_ModifySubscriptionRequest::Priority, _OpcUa_ModifySubscriptionRequest::RequestedLifetimeCount, _OpcUa_ModifySubscriptionRequest::RequestedMaxKeepAliveCount, _OpcUa_ModifySubscriptionRequest::RequestedPublishingInterval, _OpcUa_ModifySubscriptionRequest::RequestHeader, and _OpcUa_ModifySubscriptionRequest::SubscriptionId.
OpcUa_ClientApi_Publish()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_Publish (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader * a_pRequestHeader, OpcUa_Int32 a_nNoOfSubscriptionAcknowledgements, const OpcUa_SubscriptionAcknowledgement * a_pSubscriptionAcknowledgements, OpcUa_ResponseHeader * a_pResponseHeader, OpcUa_UInt32 * a_pSubscriptionId, OpcUa_Int32 * a_pNoOfAvailableSequenceNumbers, OpcUa_UInt32 ** a_pAvailableSequenceNumbers, OpcUa_Boolean * a_pMoreNotifications, OpcUa_NotificationMessage * a_pNotificationMessage, OpcUa_Int32 * a_pNoOfResults, OpcUa_StatusCode ** a_pResults, OpcUa_Int32 * a_pNoOfDiagnosticInfos, OpcUa_DiagnosticInfo ** a_pDiagnosticInfos)
Definition at line 4616 of file opcua_clientapi.c.
References _OpcUa_PublishRequest::NoOfSubscriptionAcknowledgements, OpcUa_PublishRequest_EncodeableType, OpcUa_PublishRequest_Initialize(), _OpcUa_PublishRequest::RequestHeader, and _OpcUa_PublishRequest::SubscriptionAcknowledgements.
OpcUa_ClientApi_QueryFirst()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_QueryFirst (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader * a_pRequestHeader, const OpcUa_ViewDescription * a_pView, OpcUa_Int32 a_nNoOfNodeTypes, const OpcUa_NodeTypeDescription * a_pNodeTypes, const OpcUa_ContentFilter * a_pFilter, OpcUa_UInt32 a_nMaxDataSetsToReturn, OpcUa_UInt32 a_nMaxReferencesToReturn, OpcUa_ResponseHeader * a_pResponseHeader, OpcUa_Int32 * a_pNoOfQueryDataSets, OpcUa_QueryDataSet ** a_pQueryDataSets, OpcUa_ByteString * a_pContinuationPoint, OpcUa_Int32 * a_pNoOfParsingResults, OpcUa_ParsingResult ** a_pParsingResults, OpcUa_Int32 * a_pNoOfDiagnosticInfos, OpcUa_DiagnosticInfo ** a_pDiagnosticInfos, OpcUa_ContentFilterResult * a_pFilterResult)
Definition at line 2470 of file opcua_clientapi.c.
References _OpcUa_QueryFirstRequest::Filter, _OpcUa_QueryFirstRequest::MaxDataSetsToReturn, _OpcUa_QueryFirstRequest::MaxReferencesToReturn, _OpcUa_QueryFirstRequest::NodeTypes, _OpcUa_QueryFirstRequest::NoOfNodeTypes, OpcUa_QueryFirstRequest_EncodeableType, OpcUa_QueryFirstRequest_Initialize(), _OpcUa_QueryFirstRequest::RequestHeader, and _OpcUa_QueryFirstRequest::View.
OpcUa_ClientApi_QueryNext()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_QueryNext (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader * a_pRequestHeader, OpcUa_Boolean a_bReleaseContinuationPoint, const OpcUa_ByteString * a_pContinuationPoint, OpcUa_ResponseHeader * a_pResponseHeader, OpcUa_Int32 * a_pNoOfQueryDataSets, OpcUa_QueryDataSet ** a_pQueryDataSets, OpcUa_ByteString * a_pRevisedContinuationPoint)
Definition at line 2636 of file opcua_clientapi.c.
References _OpcUa_QueryNextRequest::ContinuationPoint, OpcUa_QueryNextRequest_EncodeableType, OpcUa_QueryNextRequest_Initialize(), _OpcUa_QueryNextRequest::ReleaseContinuationPoint, and _OpcUa_QueryNextRequest::RequestHeader.
OpcUa_ClientApi_Read()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_Read (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader * a_pRequestHeader, OpcUa_Double a_nMaxAge, OpcUa_TimestampsToReturn a_eTimestampsToReturn, OpcUa_Int32 a_nNoOfNodesToRead, const OpcUa_ReadValueId * a_pNodesToRead, OpcUa_ResponseHeader * a_pResponseHeader, OpcUa_Int32 * a_pNoOfResults, OpcUa_DataValue ** a_pResults, OpcUa_Int32 * a_pNoOfDiagnosticInfos, OpcUa_DiagnosticInfo ** a_pDiagnosticInfos)
Definition at line 2765 of file opcua_clientapi.c.
References _OpcUa_ReadRequest::MaxAge, _OpcUa_ReadRequest::NodesToRead, _OpcUa_ReadRequest::NoOfNodesToRead, OpcUa_ReadRequest_EncodeableType, OpcUa_ReadRequest_Initialize(), _OpcUa_ReadRequest::RequestHeader, and _OpcUa_ReadRequest::TimestampsToReturn.
OpcUa_ClientApi_RegisterNodes()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_RegisterNodes (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader * a_pRequestHeader, OpcUa_Int32 a_nNoOfNodesToRegister, const OpcUa_NodeId * a_pNodesToRegister, OpcUa_ResponseHeader * a_pResponseHeader, OpcUa_Int32 * a_pNoOfRegisteredNodeIds, OpcUa_NodeId ** a_pRegisteredNodeIds)
Definition at line 2228 of file opcua_clientapi.c.
References _OpcUa_RegisterNodesRequest::NodesToRegister, _OpcUa_RegisterNodesRequest::NoOfNodesToRegister, OpcUa_RegisterNodesRequest_EncodeableType, OpcUa_RegisterNodesRequest_Initialize(), and _OpcUa_RegisterNodesRequest::RequestHeader.
OpcUa_ClientApi_RegisterServer()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_RegisterServer (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader * a_pRequestHeader, const OpcUa_RegisteredServer * a_pServer, OpcUa_ResponseHeader * a_pResponseHeader)
Definition at line 469 of file opcua_clientapi.c.
References OpcUa_RegisterServerRequest_EncodeableType, OpcUa_RegisterServerRequest_Initialize(), _OpcUa_RegisterServerRequest::RequestHeader, and _OpcUa_RegisterServerRequest::Server.
OpcUa_ClientApi_RegisterServer2()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_RegisterServer2 (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader * a_pRequestHeader, const OpcUa_RegisteredServer * a_pServer, OpcUa_Int32 a_nNoOfDiscoveryConfiguration, const OpcUa_ExtensionObject * a_pDiscoveryConfiguration, OpcUa_ResponseHeader * a_pResponseHeader, OpcUa_Int32 * a_pNoOfConfigurationResults, OpcUa_StatusCode ** a_pConfigurationResults, OpcUa_Int32 * a_pNoOfDiagnosticInfos, OpcUa_DiagnosticInfo ** a_pDiagnosticInfos)
Definition at line 583 of file opcua_clientapi.c.
References _OpcUa_RegisterServer2Request::DiscoveryConfiguration, _OpcUa_RegisterServer2Request::NoOfDiscoveryConfiguration, OpcUa_RegisterServer2Request_EncodeableType, OpcUa_RegisterServer2Request_Initialize(), _OpcUa_RegisterServer2Request::RequestHeader, and _OpcUa_RegisterServer2Request::Server.
OpcUa_ClientApi_Republish()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_Republish (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader * a_pRequestHeader, OpcUa_UInt32 a_nSubscriptionId, OpcUa_UInt32 a_nRetransmitSequenceNumber, OpcUa_ResponseHeader * a_pResponseHeader, OpcUa_NotificationMessage * a_pNotificationMessage)
Definition at line 4761 of file opcua_clientapi.c.
References OpcUa_RepublishRequest_EncodeableType, OpcUa_RepublishRequest_Initialize(), _OpcUa_RepublishRequest::RequestHeader, _OpcUa_RepublishRequest::RetransmitSequenceNumber, and _OpcUa_RepublishRequest::SubscriptionId.
OpcUa_ClientApi_SetMonitoringMode()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_SetMonitoringMode (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader * a_pRequestHeader, OpcUa_UInt32 a_nSubscriptionId, OpcUa_MonitoringMode a_eMonitoringMode, OpcUa_Int32 a_nNoOfMonitoredItemIds, const OpcUa_UInt32 * a_pMonitoredItemIds, OpcUa_ResponseHeader * a_pResponseHeader, OpcUa_Int32 * a_pNoOfResults, OpcUa_StatusCode ** a_pResults, OpcUa_Int32 * a_pNoOfDiagnosticInfos, OpcUa_DiagnosticInfo ** a_pDiagnosticInfos)
Definition at line 3729 of file opcua_clientapi.c.
References _OpcUa_SetMonitoringModeRequest::MonitoredItemIds, _OpcUa_SetMonitoringModeRequest::MonitoringMode, _OpcUa_SetMonitoringModeRequest::NoOfMonitoredItemIds, OpcUa_SetMonitoringModeRequest_EncodeableType, OpcUa_SetMonitoringModeRequest_Initialize(), _OpcUa_SetMonitoringModeRequest::RequestHeader, and _OpcUa_SetMonitoringModeRequest::SubscriptionId.
OpcUa_ClientApi_SetPublishingMode()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_SetPublishingMode (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader * a_pRequestHeader, OpcUa_Boolean a_bPublishingEnabled, OpcUa_Int32 a_nNoOfSubscriptionIds, const OpcUa_UInt32 * a_pSubscriptionIds, OpcUa_ResponseHeader * a_pResponseHeader, OpcUa_Int32 * a_pNoOfResults, OpcUa_StatusCode ** a_pResults, OpcUa_Int32 * a_pNoOfDiagnosticInfos, OpcUa_DiagnosticInfo ** a_pDiagnosticInfos)
Definition at line 4480 of file opcua_clientapi.c.
References _OpcUa_SetPublishingModeRequest::NoOfSubscriptionIds, OpcUa_SetPublishingModeRequest_EncodeableType, OpcUa_SetPublishingModeRequest_Initialize(), _OpcUa_SetPublishingModeRequest::PublishingEnabled, _OpcUa_SetPublishingModeRequest::RequestHeader, and _OpcUa_SetPublishingModeRequest::SubscriptionIds.
OpcUa_ClientApi_SetTriggering()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_SetTriggering (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader * a_pRequestHeader, OpcUa_UInt32 a_nSubscriptionId, OpcUa_UInt32 a_nTriggeringItemId, OpcUa_Int32 a_nNoOfLinksToAdd, const OpcUa_UInt32 * a_pLinksToAdd, OpcUa_Int32 a_nNoOfLinksToRemove, const OpcUa_UInt32 * a_pLinksToRemove, OpcUa_ResponseHeader * a_pResponseHeader, OpcUa_Int32 * a_pNoOfAddResults, OpcUa_StatusCode ** a_pAddResults, OpcUa_Int32 * a_pNoOfAddDiagnosticInfos, OpcUa_DiagnosticInfo ** a_pAddDiagnosticInfos, OpcUa_Int32 * a_pNoOfRemoveResults, OpcUa_StatusCode ** a_pRemoveResults, OpcUa_Int32 * a_pNoOfRemoveDiagnosticInfos, OpcUa_DiagnosticInfo ** a_pRemoveDiagnosticInfos)
Definition at line 3871 of file opcua_clientapi.c.
References _OpcUa_SetTriggeringRequest::LinksToAdd, _OpcUa_SetTriggeringRequest::LinksToRemove, _OpcUa_SetTriggeringRequest::NoOfLinksToAdd, _OpcUa_SetTriggeringRequest::NoOfLinksToRemove, OpcUa_SetTriggeringRequest_EncodeableType, OpcUa_SetTriggeringRequest_Initialize(), _OpcUa_SetTriggeringRequest::RequestHeader, _OpcUa_SetTriggeringRequest::SubscriptionId, and _OpcUa_SetTriggeringRequest::TriggeringItemId.
OpcUa_ClientApi_TransferSubscriptions()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_TransferSubscriptions (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader * a_pRequestHeader, OpcUa_Int32 a_nNoOfSubscriptionIds, const OpcUa_UInt32 * a_pSubscriptionIds, OpcUa_Boolean a_bSendInitialValues, OpcUa_ResponseHeader * a_pResponseHeader, OpcUa_Int32 * a_pNoOfResults, OpcUa_TransferResult ** a_pResults, OpcUa_Int32 * a_pNoOfDiagnosticInfos, OpcUa_DiagnosticInfo ** a_pDiagnosticInfos)
Definition at line 4884 of file opcua_clientapi.c.
References _OpcUa_TransferSubscriptionsRequest::NoOfSubscriptionIds, OpcUa_TransferSubscriptionsRequest_EncodeableType, OpcUa_TransferSubscriptionsRequest_Initialize(), _OpcUa_TransferSubscriptionsRequest::RequestHeader, _OpcUa_TransferSubscriptionsRequest::SendInitialValues, and _OpcUa_TransferSubscriptionsRequest::SubscriptionIds.
OpcUa_ClientApi_TranslateBrowsePathsToNodeIds()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_TranslateBrowsePathsToNodeIds (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader * a_pRequestHeader, OpcUa_Int32 a_nNoOfBrowsePaths, const OpcUa_BrowsePath * a_pBrowsePaths, OpcUa_ResponseHeader * a_pResponseHeader, OpcUa_Int32 * a_pNoOfResults, OpcUa_BrowsePathResult ** a_pResults, OpcUa_Int32 * a_pNoOfDiagnosticInfos, OpcUa_DiagnosticInfo ** a_pDiagnosticInfos)
Definition at line 2098 of file opcua_clientapi.c.
References _OpcUa_TranslateBrowsePathsToNodeIdsRequest::BrowsePaths, _OpcUa_TranslateBrowsePathsToNodeIdsRequest::NoOfBrowsePaths, OpcUa_TranslateBrowsePathsToNodeIdsRequest_EncodeableType, OpcUa_TranslateBrowsePathsToNodeIdsRequest_Initialize(), and _OpcUa_TranslateBrowsePathsToNodeIdsRequest::RequestHeader.
OpcUa_ClientApi_UnregisterNodes()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_UnregisterNodes (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader * a_pRequestHeader, OpcUa_Int32 a_nNoOfNodesToUnregister, const OpcUa_NodeId * a_pNodesToUnregister, OpcUa_ResponseHeader * a_pResponseHeader)
Definition at line 2352 of file opcua_clientapi.c.
References _OpcUa_UnregisterNodesRequest::NodesToUnregister, _OpcUa_UnregisterNodesRequest::NoOfNodesToUnregister, OpcUa_UnregisterNodesRequest_EncodeableType, OpcUa_UnregisterNodesRequest_Initialize(), and _OpcUa_UnregisterNodesRequest::RequestHeader.
OpcUa_ClientApi_Write()
OPCUA_EXPORT OpcUa_StatusCode OpcUa_ClientApi_Write (OpcUa_Channel a_hChannel, const OpcUa_RequestHeader * a_pRequestHeader, OpcUa_Int32 a_nNoOfNodesToWrite, const OpcUa_WriteValue * a_pNodesToWrite, OpcUa_ResponseHeader * a_pResponseHeader, OpcUa_Int32 * a_pNoOfResults, OpcUa_StatusCode ** a_pResults, OpcUa_Int32 * a_pNoOfDiagnosticInfos, OpcUa_DiagnosticInfo ** a_pDiagnosticInfos)
Definition at line 3055 of file opcua_clientapi.c.
References _OpcUa_WriteRequest::NodesToWrite, _OpcUa_WriteRequest::NoOfNodesToWrite, OpcUa_WriteRequest_EncodeableType, OpcUa_WriteRequest_Initialize(), and _OpcUa_WriteRequest::RequestHeader.