Project Template: types_generated_encoding_binary.h File Reference
types_generated_encoding_binary.h File Reference
Functions
static UA_INLINE size_t UA_Boolean_calcSizeBinary (const UA_Boolean *src)
static UA_INLINE UA_StatusCode UA_Boolean_encodeBinary (const UA_Boolean *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_Boolean_decodeBinary (const UA_ByteString *src, size_t *offset, UA_Boolean *dst)
static UA_INLINE size_t UA_SByte_calcSizeBinary (const UA_SByte *src)
static UA_INLINE UA_StatusCode UA_SByte_encodeBinary (const UA_SByte *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_SByte_decodeBinary (const UA_ByteString *src, size_t *offset, UA_SByte *dst)
static UA_INLINE size_t UA_Byte_calcSizeBinary (const UA_Byte *src)
static UA_INLINE UA_StatusCode UA_Byte_encodeBinary (const UA_Byte *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_Byte_decodeBinary (const UA_ByteString *src, size_t *offset, UA_Byte *dst)
static UA_INLINE size_t UA_Int16_calcSizeBinary (const UA_Int16 *src)
static UA_INLINE UA_StatusCode UA_Int16_encodeBinary (const UA_Int16 *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_Int16_decodeBinary (const UA_ByteString *src, size_t *offset, UA_Int16 *dst)
static UA_INLINE size_t UA_UInt16_calcSizeBinary (const UA_UInt16 *src)
static UA_INLINE UA_StatusCode UA_UInt16_encodeBinary (const UA_UInt16 *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_UInt16_decodeBinary (const UA_ByteString *src, size_t *offset, UA_UInt16 *dst)
static UA_INLINE size_t UA_Int32_calcSizeBinary (const UA_Int32 *src)
static UA_INLINE UA_StatusCode UA_Int32_encodeBinary (const UA_Int32 *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_Int32_decodeBinary (const UA_ByteString *src, size_t *offset, UA_Int32 *dst)
static UA_INLINE size_t UA_UInt32_calcSizeBinary (const UA_UInt32 *src)
static UA_INLINE UA_StatusCode UA_UInt32_encodeBinary (const UA_UInt32 *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_UInt32_decodeBinary (const UA_ByteString *src, size_t *offset, UA_UInt32 *dst)
static UA_INLINE size_t UA_Int64_calcSizeBinary (const UA_Int64 *src)
static UA_INLINE UA_StatusCode UA_Int64_encodeBinary (const UA_Int64 *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_Int64_decodeBinary (const UA_ByteString *src, size_t *offset, UA_Int64 *dst)
static UA_INLINE size_t UA_UInt64_calcSizeBinary (const UA_UInt64 *src)
static UA_INLINE UA_StatusCode UA_UInt64_encodeBinary (const UA_UInt64 *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_UInt64_decodeBinary (const UA_ByteString *src, size_t *offset, UA_UInt64 *dst)
static UA_INLINE size_t UA_Float_calcSizeBinary (const UA_Float *src)
static UA_INLINE UA_StatusCode UA_Float_encodeBinary (const UA_Float *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_Float_decodeBinary (const UA_ByteString *src, size_t *offset, UA_Float *dst)
static UA_INLINE size_t UA_Double_calcSizeBinary (const UA_Double *src)
static UA_INLINE UA_StatusCode UA_Double_encodeBinary (const UA_Double *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_Double_decodeBinary (const UA_ByteString *src, size_t *offset, UA_Double *dst)
static UA_INLINE size_t UA_String_calcSizeBinary (const UA_String *src)
static UA_INLINE UA_StatusCode UA_String_encodeBinary (const UA_String *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_String_decodeBinary (const UA_ByteString *src, size_t *offset, UA_String *dst)
static UA_INLINE size_t UA_DateTime_calcSizeBinary (const UA_DateTime *src)
static UA_INLINE UA_StatusCode UA_DateTime_encodeBinary (const UA_DateTime *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_DateTime_decodeBinary (const UA_ByteString *src, size_t *offset, UA_DateTime *dst)
static UA_INLINE size_t UA_Guid_calcSizeBinary (const UA_Guid *src)
static UA_INLINE UA_StatusCode UA_Guid_encodeBinary (const UA_Guid *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_Guid_decodeBinary (const UA_ByteString *src, size_t *offset, UA_Guid *dst)
static UA_INLINE size_t UA_ByteString_calcSizeBinary (const UA_ByteString *src)
static UA_INLINE UA_StatusCode UA_ByteString_encodeBinary (const UA_ByteString *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_ByteString_decodeBinary (const UA_ByteString *src, size_t *offset, UA_ByteString *dst)
static UA_INLINE size_t UA_XmlElement_calcSizeBinary (const UA_XmlElement *src)
static UA_INLINE UA_StatusCode UA_XmlElement_encodeBinary (const UA_XmlElement *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_XmlElement_decodeBinary (const UA_ByteString *src, size_t *offset, UA_XmlElement *dst)
static UA_INLINE size_t UA_NodeId_calcSizeBinary (const UA_NodeId *src)
static UA_INLINE UA_StatusCode UA_NodeId_encodeBinary (const UA_NodeId *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_NodeId_decodeBinary (const UA_ByteString *src, size_t *offset, UA_NodeId *dst)
static UA_INLINE size_t UA_ExpandedNodeId_calcSizeBinary (const UA_ExpandedNodeId *src)
static UA_INLINE UA_StatusCode UA_ExpandedNodeId_encodeBinary (const UA_ExpandedNodeId *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_ExpandedNodeId_decodeBinary (const UA_ByteString *src, size_t *offset, UA_ExpandedNodeId *dst)
static UA_INLINE size_t UA_StatusCode_calcSizeBinary (const UA_StatusCode *src)
static UA_INLINE UA_StatusCode UA_StatusCode_encodeBinary (const UA_StatusCode *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_StatusCode_decodeBinary (const UA_ByteString *src, size_t *offset, UA_StatusCode *dst)
static UA_INLINE size_t UA_QualifiedName_calcSizeBinary (const UA_QualifiedName *src)
static UA_INLINE UA_StatusCode UA_QualifiedName_encodeBinary (const UA_QualifiedName *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_QualifiedName_decodeBinary (const UA_ByteString *src, size_t *offset, UA_QualifiedName *dst)
static UA_INLINE size_t UA_LocalizedText_calcSizeBinary (const UA_LocalizedText *src)
static UA_INLINE UA_StatusCode UA_LocalizedText_encodeBinary (const UA_LocalizedText *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_LocalizedText_decodeBinary (const UA_ByteString *src, size_t *offset, UA_LocalizedText *dst)
static UA_INLINE size_t UA_ExtensionObject_calcSizeBinary (const UA_ExtensionObject *src)
static UA_INLINE UA_StatusCode UA_ExtensionObject_encodeBinary (const UA_ExtensionObject *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_ExtensionObject_decodeBinary (const UA_ByteString *src, size_t *offset, UA_ExtensionObject *dst)
static UA_INLINE size_t UA_DataValue_calcSizeBinary (const UA_DataValue *src)
static UA_INLINE UA_StatusCode UA_DataValue_encodeBinary (const UA_DataValue *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_DataValue_decodeBinary (const UA_ByteString *src, size_t *offset, UA_DataValue *dst)
static UA_INLINE size_t UA_Variant_calcSizeBinary (const UA_Variant *src)
static UA_INLINE UA_StatusCode UA_Variant_encodeBinary (const UA_Variant *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_Variant_decodeBinary (const UA_ByteString *src, size_t *offset, UA_Variant *dst)
static UA_INLINE size_t UA_DiagnosticInfo_calcSizeBinary (const UA_DiagnosticInfo *src)
static UA_INLINE UA_StatusCode UA_DiagnosticInfo_encodeBinary (const UA_DiagnosticInfo *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_DiagnosticInfo_decodeBinary (const UA_ByteString *src, size_t *offset, UA_DiagnosticInfo *dst)
static UA_INLINE size_t UA_ViewAttributes_calcSizeBinary (const UA_ViewAttributes *src)
static UA_INLINE UA_StatusCode UA_ViewAttributes_encodeBinary (const UA_ViewAttributes *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_ViewAttributes_decodeBinary (const UA_ByteString *src, size_t *offset, UA_ViewAttributes *dst)
static UA_INLINE size_t UA_ElementOperand_calcSizeBinary (const UA_ElementOperand *src)
static UA_INLINE UA_StatusCode UA_ElementOperand_encodeBinary (const UA_ElementOperand *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_ElementOperand_decodeBinary (const UA_ByteString *src, size_t *offset, UA_ElementOperand *dst)
static UA_INLINE size_t UA_VariableAttributes_calcSizeBinary (const UA_VariableAttributes *src)
static UA_INLINE UA_StatusCode UA_VariableAttributes_encodeBinary (const UA_VariableAttributes *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_VariableAttributes_decodeBinary (const UA_ByteString *src, size_t *offset, UA_VariableAttributes *dst)
static UA_INLINE size_t UA_EnumValueType_calcSizeBinary (const UA_EnumValueType *src)
static UA_INLINE UA_StatusCode UA_EnumValueType_encodeBinary (const UA_EnumValueType *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_EnumValueType_decodeBinary (const UA_ByteString *src, size_t *offset, UA_EnumValueType *dst)
static UA_INLINE size_t UA_EventFieldList_calcSizeBinary (const UA_EventFieldList *src)
static UA_INLINE UA_StatusCode UA_EventFieldList_encodeBinary (const UA_EventFieldList *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_EventFieldList_decodeBinary (const UA_ByteString *src, size_t *offset, UA_EventFieldList *dst)
static UA_INLINE size_t UA_MonitoredItemCreateResult_calcSizeBinary (const UA_MonitoredItemCreateResult *src)
static UA_INLINE UA_StatusCode UA_MonitoredItemCreateResult_encodeBinary (const UA_MonitoredItemCreateResult *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_MonitoredItemCreateResult_decodeBinary (const UA_ByteString *src, size_t *offset, UA_MonitoredItemCreateResult *dst)
static UA_INLINE size_t UA_ServerDiagnosticsSummaryDataType_calcSizeBinary (const UA_ServerDiagnosticsSummaryDataType *src)
static UA_INLINE UA_StatusCode UA_ServerDiagnosticsSummaryDataType_encodeBinary (const UA_ServerDiagnosticsSummaryDataType *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_ServerDiagnosticsSummaryDataType_decodeBinary (const UA_ByteString *src, size_t *offset, UA_ServerDiagnosticsSummaryDataType *dst)
static UA_INLINE size_t UA_ContentFilterElementResult_calcSizeBinary (const UA_ContentFilterElementResult *src)
static UA_INLINE UA_StatusCode UA_ContentFilterElementResult_encodeBinary (const UA_ContentFilterElementResult *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_ContentFilterElementResult_decodeBinary (const UA_ByteString *src, size_t *offset, UA_ContentFilterElementResult *dst)
static UA_INLINE size_t UA_LiteralOperand_calcSizeBinary (const UA_LiteralOperand *src)
static UA_INLINE UA_StatusCode UA_LiteralOperand_encodeBinary (const UA_LiteralOperand *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_LiteralOperand_decodeBinary (const UA_ByteString *src, size_t *offset, UA_LiteralOperand *dst)
static UA_INLINE size_t UA_MessageSecurityMode_calcSizeBinary (const UA_MessageSecurityMode *src)
static UA_INLINE UA_StatusCode UA_MessageSecurityMode_encodeBinary (const UA_MessageSecurityMode *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_MessageSecurityMode_decodeBinary (const UA_ByteString *src, size_t *offset, UA_MessageSecurityMode *dst)
static UA_INLINE size_t UA_UtcTime_calcSizeBinary (const UA_UtcTime *src)
static UA_INLINE UA_StatusCode UA_UtcTime_encodeBinary (const UA_UtcTime *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_UtcTime_decodeBinary (const UA_ByteString *src, size_t *offset, UA_UtcTime *dst)
static UA_INLINE size_t UA_UserIdentityToken_calcSizeBinary (const UA_UserIdentityToken *src)
static UA_INLINE UA_StatusCode UA_UserIdentityToken_encodeBinary (const UA_UserIdentityToken *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_UserIdentityToken_decodeBinary (const UA_ByteString *src, size_t *offset, UA_UserIdentityToken *dst)
static UA_INLINE size_t UA_X509IdentityToken_calcSizeBinary (const UA_X509IdentityToken *src)
static UA_INLINE UA_StatusCode UA_X509IdentityToken_encodeBinary (const UA_X509IdentityToken *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_X509IdentityToken_decodeBinary (const UA_ByteString *src, size_t *offset, UA_X509IdentityToken *dst)
static UA_INLINE size_t UA_MonitoredItemNotification_calcSizeBinary (const UA_MonitoredItemNotification *src)
static UA_INLINE UA_StatusCode UA_MonitoredItemNotification_encodeBinary (const UA_MonitoredItemNotification *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_MonitoredItemNotification_decodeBinary (const UA_ByteString *src, size_t *offset, UA_MonitoredItemNotification *dst)
static UA_INLINE size_t UA_ResponseHeader_calcSizeBinary (const UA_ResponseHeader *src)
static UA_INLINE UA_StatusCode UA_ResponseHeader_encodeBinary (const UA_ResponseHeader *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_ResponseHeader_decodeBinary (const UA_ByteString *src, size_t *offset, UA_ResponseHeader *dst)
static UA_INLINE size_t UA_SignatureData_calcSizeBinary (const UA_SignatureData *src)
static UA_INLINE UA_StatusCode UA_SignatureData_encodeBinary (const UA_SignatureData *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_SignatureData_decodeBinary (const UA_ByteString *src, size_t *offset, UA_SignatureData *dst)
static UA_INLINE size_t UA_ModifySubscriptionResponse_calcSizeBinary (const UA_ModifySubscriptionResponse *src)
static UA_INLINE UA_StatusCode UA_ModifySubscriptionResponse_encodeBinary (const UA_ModifySubscriptionResponse *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_ModifySubscriptionResponse_decodeBinary (const UA_ByteString *src, size_t *offset, UA_ModifySubscriptionResponse *dst)
static UA_INLINE size_t UA_NodeAttributes_calcSizeBinary (const UA_NodeAttributes *src)
static UA_INLINE UA_StatusCode UA_NodeAttributes_encodeBinary (const UA_NodeAttributes *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_NodeAttributes_decodeBinary (const UA_ByteString *src, size_t *offset, UA_NodeAttributes *dst)
static UA_INLINE size_t UA_ActivateSessionResponse_calcSizeBinary (const UA_ActivateSessionResponse *src)
static UA_INLINE UA_StatusCode UA_ActivateSessionResponse_encodeBinary (const UA_ActivateSessionResponse *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_ActivateSessionResponse_decodeBinary (const UA_ByteString *src, size_t *offset, UA_ActivateSessionResponse *dst)
static UA_INLINE size_t UA_VariableTypeAttributes_calcSizeBinary (const UA_VariableTypeAttributes *src)
static UA_INLINE UA_StatusCode UA_VariableTypeAttributes_encodeBinary (const UA_VariableTypeAttributes *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_VariableTypeAttributes_decodeBinary (const UA_ByteString *src, size_t *offset, UA_VariableTypeAttributes *dst)
static UA_INLINE size_t UA_CallMethodResult_calcSizeBinary (const UA_CallMethodResult *src)
static UA_INLINE UA_StatusCode UA_CallMethodResult_encodeBinary (const UA_CallMethodResult *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_CallMethodResult_decodeBinary (const UA_ByteString *src, size_t *offset, UA_CallMethodResult *dst)
static UA_INLINE size_t UA_MonitoringMode_calcSizeBinary (const UA_MonitoringMode *src)
static UA_INLINE UA_StatusCode UA_MonitoringMode_encodeBinary (const UA_MonitoringMode *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_MonitoringMode_decodeBinary (const UA_ByteString *src, size_t *offset, UA_MonitoringMode *dst)
static UA_INLINE size_t UA_SetMonitoringModeResponse_calcSizeBinary (const UA_SetMonitoringModeResponse *src)
static UA_INLINE UA_StatusCode UA_SetMonitoringModeResponse_encodeBinary (const UA_SetMonitoringModeResponse *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_SetMonitoringModeResponse_decodeBinary (const UA_ByteString *src, size_t *offset, UA_SetMonitoringModeResponse *dst)
static UA_INLINE size_t UA_BrowseResultMask_calcSizeBinary (const UA_BrowseResultMask *src)
static UA_INLINE UA_StatusCode UA_BrowseResultMask_encodeBinary (const UA_BrowseResultMask *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_BrowseResultMask_decodeBinary (const UA_ByteString *src, size_t *offset, UA_BrowseResultMask *dst)
static UA_INLINE size_t UA_RequestHeader_calcSizeBinary (const UA_RequestHeader *src)
static UA_INLINE UA_StatusCode UA_RequestHeader_encodeBinary (const UA_RequestHeader *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_RequestHeader_decodeBinary (const UA_ByteString *src, size_t *offset, UA_RequestHeader *dst)
static UA_INLINE size_t UA_MonitoredItemModifyResult_calcSizeBinary (const UA_MonitoredItemModifyResult *src)
static UA_INLINE UA_StatusCode UA_MonitoredItemModifyResult_encodeBinary (const UA_MonitoredItemModifyResult *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_MonitoredItemModifyResult_decodeBinary (const UA_ByteString *src, size_t *offset, UA_MonitoredItemModifyResult *dst)
static UA_INLINE size_t UA_CloseSecureChannelRequest_calcSizeBinary (const UA_CloseSecureChannelRequest *src)
static UA_INLINE UA_StatusCode UA_CloseSecureChannelRequest_encodeBinary (const UA_CloseSecureChannelRequest *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_CloseSecureChannelRequest_decodeBinary (const UA_ByteString *src, size_t *offset, UA_CloseSecureChannelRequest *dst)
static UA_INLINE size_t UA_NotificationMessage_calcSizeBinary (const UA_NotificationMessage *src)
static UA_INLINE UA_StatusCode UA_NotificationMessage_encodeBinary (const UA_NotificationMessage *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_NotificationMessage_decodeBinary (const UA_ByteString *src, size_t *offset, UA_NotificationMessage *dst)
static UA_INLINE size_t UA_CreateSubscriptionResponse_calcSizeBinary (const UA_CreateSubscriptionResponse *src)
static UA_INLINE UA_StatusCode UA_CreateSubscriptionResponse_encodeBinary (const UA_CreateSubscriptionResponse *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_CreateSubscriptionResponse_decodeBinary (const UA_ByteString *src, size_t *offset, UA_CreateSubscriptionResponse *dst)
static UA_INLINE size_t UA_MdnsDiscoveryConfiguration_calcSizeBinary (const UA_MdnsDiscoveryConfiguration *src)
static UA_INLINE UA_StatusCode UA_MdnsDiscoveryConfiguration_encodeBinary (const UA_MdnsDiscoveryConfiguration *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_MdnsDiscoveryConfiguration_decodeBinary (const UA_ByteString *src, size_t *offset, UA_MdnsDiscoveryConfiguration *dst)
static UA_INLINE size_t UA_BrowseDirection_calcSizeBinary (const UA_BrowseDirection *src)
static UA_INLINE UA_StatusCode UA_BrowseDirection_encodeBinary (const UA_BrowseDirection *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_BrowseDirection_decodeBinary (const UA_ByteString *src, size_t *offset, UA_BrowseDirection *dst)
static UA_INLINE size_t UA_CallMethodRequest_calcSizeBinary (const UA_CallMethodRequest *src)
static UA_INLINE UA_StatusCode UA_CallMethodRequest_encodeBinary (const UA_CallMethodRequest *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_CallMethodRequest_decodeBinary (const UA_ByteString *src, size_t *offset, UA_CallMethodRequest *dst)
static UA_INLINE size_t UA_ReadResponse_calcSizeBinary (const UA_ReadResponse *src)
static UA_INLINE UA_StatusCode UA_ReadResponse_encodeBinary (const UA_ReadResponse *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_ReadResponse_decodeBinary (const UA_ByteString *src, size_t *offset, UA_ReadResponse *dst)
static UA_INLINE size_t UA_TimestampsToReturn_calcSizeBinary (const UA_TimestampsToReturn *src)
static UA_INLINE UA_StatusCode UA_TimestampsToReturn_encodeBinary (const UA_TimestampsToReturn *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_TimestampsToReturn_decodeBinary (const UA_ByteString *src, size_t *offset, UA_TimestampsToReturn *dst)
static UA_INLINE size_t UA_NodeClass_calcSizeBinary (const UA_NodeClass *src)
static UA_INLINE UA_StatusCode UA_NodeClass_encodeBinary (const UA_NodeClass *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_NodeClass_decodeBinary (const UA_ByteString *src, size_t *offset, UA_NodeClass *dst)
static UA_INLINE size_t UA_ObjectTypeAttributes_calcSizeBinary (const UA_ObjectTypeAttributes *src)
static UA_INLINE UA_StatusCode UA_ObjectTypeAttributes_encodeBinary (const UA_ObjectTypeAttributes *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_ObjectTypeAttributes_decodeBinary (const UA_ByteString *src, size_t *offset, UA_ObjectTypeAttributes *dst)
static UA_INLINE size_t UA_SecurityTokenRequestType_calcSizeBinary (const UA_SecurityTokenRequestType *src)
static UA_INLINE UA_StatusCode UA_SecurityTokenRequestType_encodeBinary (const UA_SecurityTokenRequestType *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_SecurityTokenRequestType_decodeBinary (const UA_ByteString *src, size_t *offset, UA_SecurityTokenRequestType *dst)
static UA_INLINE size_t UA_CloseSessionResponse_calcSizeBinary (const UA_CloseSessionResponse *src)
static UA_INLINE UA_StatusCode UA_CloseSessionResponse_encodeBinary (const UA_CloseSessionResponse *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_CloseSessionResponse_decodeBinary (const UA_ByteString *src, size_t *offset, UA_CloseSessionResponse *dst)
static UA_INLINE size_t UA_SetPublishingModeRequest_calcSizeBinary (const UA_SetPublishingModeRequest *src)
static UA_INLINE UA_StatusCode UA_SetPublishingModeRequest_encodeBinary (const UA_SetPublishingModeRequest *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_SetPublishingModeRequest_decodeBinary (const UA_ByteString *src, size_t *offset, UA_SetPublishingModeRequest *dst)
static UA_INLINE size_t UA_IssuedIdentityToken_calcSizeBinary (const UA_IssuedIdentityToken *src)
static UA_INLINE UA_StatusCode UA_IssuedIdentityToken_encodeBinary (const UA_IssuedIdentityToken *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_IssuedIdentityToken_decodeBinary (const UA_ByteString *src, size_t *offset, UA_IssuedIdentityToken *dst)
static UA_INLINE size_t UA_ServerOnNetwork_calcSizeBinary (const UA_ServerOnNetwork *src)
static UA_INLINE UA_StatusCode UA_ServerOnNetwork_encodeBinary (const UA_ServerOnNetwork *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_ServerOnNetwork_decodeBinary (const UA_ByteString *src, size_t *offset, UA_ServerOnNetwork *dst)
static UA_INLINE size_t UA_DeleteMonitoredItemsResponse_calcSizeBinary (const UA_DeleteMonitoredItemsResponse *src)
static UA_INLINE UA_StatusCode UA_DeleteMonitoredItemsResponse_encodeBinary (const UA_DeleteMonitoredItemsResponse *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_DeleteMonitoredItemsResponse_decodeBinary (const UA_ByteString *src, size_t *offset, UA_DeleteMonitoredItemsResponse *dst)
static UA_INLINE size_t UA_ApplicationType_calcSizeBinary (const UA_ApplicationType *src)
static UA_INLINE UA_StatusCode UA_ApplicationType_encodeBinary (const UA_ApplicationType *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_ApplicationType_decodeBinary (const UA_ByteString *src, size_t *offset, UA_ApplicationType *dst)
static UA_INLINE size_t UA_DiscoveryConfiguration_calcSizeBinary (const UA_DiscoveryConfiguration *src)
static UA_INLINE UA_StatusCode UA_DiscoveryConfiguration_encodeBinary (const UA_DiscoveryConfiguration *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_DiscoveryConfiguration_decodeBinary (const UA_ByteString *src, size_t *offset, UA_DiscoveryConfiguration *dst)
static UA_INLINE size_t UA_BrowseNextRequest_calcSizeBinary (const UA_BrowseNextRequest *src)
static UA_INLINE UA_StatusCode UA_BrowseNextRequest_encodeBinary (const UA_BrowseNextRequest *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_BrowseNextRequest_decodeBinary (const UA_ByteString *src, size_t *offset, UA_BrowseNextRequest *dst)
static UA_INLINE size_t UA_ModifySubscriptionRequest_calcSizeBinary (const UA_ModifySubscriptionRequest *src)
static UA_INLINE UA_StatusCode UA_ModifySubscriptionRequest_encodeBinary (const UA_ModifySubscriptionRequest *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_ModifySubscriptionRequest_decodeBinary (const UA_ByteString *src, size_t *offset, UA_ModifySubscriptionRequest *dst)
static UA_INLINE size_t UA_BrowseDescription_calcSizeBinary (const UA_BrowseDescription *src)
static UA_INLINE UA_StatusCode UA_BrowseDescription_encodeBinary (const UA_BrowseDescription *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_BrowseDescription_decodeBinary (const UA_ByteString *src, size_t *offset, UA_BrowseDescription *dst)
static UA_INLINE size_t UA_SignedSoftwareCertificate_calcSizeBinary (const UA_SignedSoftwareCertificate *src)
static UA_INLINE UA_StatusCode UA_SignedSoftwareCertificate_encodeBinary (const UA_SignedSoftwareCertificate *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_SignedSoftwareCertificate_decodeBinary (const UA_ByteString *src, size_t *offset, UA_SignedSoftwareCertificate *dst)
static UA_INLINE size_t UA_BrowsePathTarget_calcSizeBinary (const UA_BrowsePathTarget *src)
static UA_INLINE UA_StatusCode UA_BrowsePathTarget_encodeBinary (const UA_BrowsePathTarget *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_BrowsePathTarget_decodeBinary (const UA_ByteString *src, size_t *offset, UA_BrowsePathTarget *dst)
static UA_INLINE size_t UA_WriteResponse_calcSizeBinary (const UA_WriteResponse *src)
static UA_INLINE UA_StatusCode UA_WriteResponse_encodeBinary (const UA_WriteResponse *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_WriteResponse_decodeBinary (const UA_ByteString *src, size_t *offset, UA_WriteResponse *dst)
static UA_INLINE size_t UA_AddNodesResult_calcSizeBinary (const UA_AddNodesResult *src)
static UA_INLINE UA_StatusCode UA_AddNodesResult_encodeBinary (const UA_AddNodesResult *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_AddNodesResult_decodeBinary (const UA_ByteString *src, size_t *offset, UA_AddNodesResult *dst)
static UA_INLINE size_t UA_RegisterServerResponse_calcSizeBinary (const UA_RegisterServerResponse *src)
static UA_INLINE UA_StatusCode UA_RegisterServerResponse_encodeBinary (const UA_RegisterServerResponse *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_RegisterServerResponse_decodeBinary (const UA_ByteString *src, size_t *offset, UA_RegisterServerResponse *dst)
static UA_INLINE size_t UA_AddReferencesItem_calcSizeBinary (const UA_AddReferencesItem *src)
static UA_INLINE UA_StatusCode UA_AddReferencesItem_encodeBinary (const UA_AddReferencesItem *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_AddReferencesItem_decodeBinary (const UA_ByteString *src, size_t *offset, UA_AddReferencesItem *dst)
static UA_INLINE size_t UA_RegisterServer2Response_calcSizeBinary (const UA_RegisterServer2Response *src)
static UA_INLINE UA_StatusCode UA_RegisterServer2Response_encodeBinary (const UA_RegisterServer2Response *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_RegisterServer2Response_decodeBinary (const UA_ByteString *src, size_t *offset, UA_RegisterServer2Response *dst)
static UA_INLINE size_t UA_DeleteReferencesResponse_calcSizeBinary (const UA_DeleteReferencesResponse *src)
static UA_INLINE UA_StatusCode UA_DeleteReferencesResponse_encodeBinary (const UA_DeleteReferencesResponse *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_DeleteReferencesResponse_decodeBinary (const UA_ByteString *src, size_t *offset, UA_DeleteReferencesResponse *dst)
static UA_INLINE size_t UA_RelativePathElement_calcSizeBinary (const UA_RelativePathElement *src)
static UA_INLINE UA_StatusCode UA_RelativePathElement_encodeBinary (const UA_RelativePathElement *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_RelativePathElement_decodeBinary (const UA_ByteString *src, size_t *offset, UA_RelativePathElement *dst)
static UA_INLINE size_t UA_SubscriptionAcknowledgement_calcSizeBinary (const UA_SubscriptionAcknowledgement *src)
static UA_INLINE UA_StatusCode UA_SubscriptionAcknowledgement_encodeBinary (const UA_SubscriptionAcknowledgement *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_SubscriptionAcknowledgement_decodeBinary (const UA_ByteString *src, size_t *offset, UA_SubscriptionAcknowledgement *dst)
static UA_INLINE size_t UA_CreateMonitoredItemsResponse_calcSizeBinary (const UA_CreateMonitoredItemsResponse *src)
static UA_INLINE UA_StatusCode UA_CreateMonitoredItemsResponse_encodeBinary (const UA_CreateMonitoredItemsResponse *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_CreateMonitoredItemsResponse_decodeBinary (const UA_ByteString *src, size_t *offset, UA_CreateMonitoredItemsResponse *dst)
static UA_INLINE size_t UA_DeleteReferencesItem_calcSizeBinary (const UA_DeleteReferencesItem *src)
static UA_INLINE UA_StatusCode UA_DeleteReferencesItem_encodeBinary (const UA_DeleteReferencesItem *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_DeleteReferencesItem_decodeBinary (const UA_ByteString *src, size_t *offset, UA_DeleteReferencesItem *dst)
static UA_INLINE size_t UA_WriteValue_calcSizeBinary (const UA_WriteValue *src)
static UA_INLINE UA_StatusCode UA_WriteValue_encodeBinary (const UA_WriteValue *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_WriteValue_decodeBinary (const UA_ByteString *src, size_t *offset, UA_WriteValue *dst)
static UA_INLINE size_t UA_DataTypeAttributes_calcSizeBinary (const UA_DataTypeAttributes *src)
static UA_INLINE UA_StatusCode UA_DataTypeAttributes_encodeBinary (const UA_DataTypeAttributes *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_DataTypeAttributes_decodeBinary (const UA_ByteString *src, size_t *offset, UA_DataTypeAttributes *dst)
static UA_INLINE size_t UA_AddReferencesResponse_calcSizeBinary (const UA_AddReferencesResponse *src)
static UA_INLINE UA_StatusCode UA_AddReferencesResponse_encodeBinary (const UA_AddReferencesResponse *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_AddReferencesResponse_decodeBinary (const UA_ByteString *src, size_t *offset, UA_AddReferencesResponse *dst)
static UA_INLINE size_t UA_DeadbandType_calcSizeBinary (const UA_DeadbandType *src)
static UA_INLINE UA_StatusCode UA_DeadbandType_encodeBinary (const UA_DeadbandType *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_DeadbandType_decodeBinary (const UA_ByteString *src, size_t *offset, UA_DeadbandType *dst)
static UA_INLINE size_t UA_DataChangeTrigger_calcSizeBinary (const UA_DataChangeTrigger *src)
static UA_INLINE UA_StatusCode UA_DataChangeTrigger_encodeBinary (const UA_DataChangeTrigger *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_DataChangeTrigger_decodeBinary (const UA_ByteString *src, size_t *offset, UA_DataChangeTrigger *dst)
static UA_INLINE size_t UA_BuildInfo_calcSizeBinary (const UA_BuildInfo *src)
static UA_INLINE UA_StatusCode UA_BuildInfo_encodeBinary (const UA_BuildInfo *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_BuildInfo_decodeBinary (const UA_ByteString *src, size_t *offset, UA_BuildInfo *dst)
static UA_INLINE size_t UA_FilterOperand_calcSizeBinary (const UA_FilterOperand *src)
static UA_INLINE UA_StatusCode UA_FilterOperand_encodeBinary (const UA_FilterOperand *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_FilterOperand_decodeBinary (const UA_ByteString *src, size_t *offset, UA_FilterOperand *dst)
static UA_INLINE size_t UA_MonitoringParameters_calcSizeBinary (const UA_MonitoringParameters *src)
static UA_INLINE UA_StatusCode UA_MonitoringParameters_encodeBinary (const UA_MonitoringParameters *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_MonitoringParameters_decodeBinary (const UA_ByteString *src, size_t *offset, UA_MonitoringParameters *dst)
static UA_INLINE size_t UA_DeleteNodesItem_calcSizeBinary (const UA_DeleteNodesItem *src)
static UA_INLINE UA_StatusCode UA_DeleteNodesItem_encodeBinary (const UA_DeleteNodesItem *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_DeleteNodesItem_decodeBinary (const UA_ByteString *src, size_t *offset, UA_DeleteNodesItem *dst)
static UA_INLINE size_t UA_ReadValueId_calcSizeBinary (const UA_ReadValueId *src)
static UA_INLINE UA_StatusCode UA_ReadValueId_encodeBinary (const UA_ReadValueId *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_ReadValueId_decodeBinary (const UA_ByteString *src, size_t *offset, UA_ReadValueId *dst)
static UA_INLINE size_t UA_CallRequest_calcSizeBinary (const UA_CallRequest *src)
static UA_INLINE UA_StatusCode UA_CallRequest_encodeBinary (const UA_CallRequest *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_CallRequest_decodeBinary (const UA_ByteString *src, size_t *offset, UA_CallRequest *dst)
static UA_INLINE size_t UA_RelativePath_calcSizeBinary (const UA_RelativePath *src)
static UA_INLINE UA_StatusCode UA_RelativePath_encodeBinary (const UA_RelativePath *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_RelativePath_decodeBinary (const UA_ByteString *src, size_t *offset, UA_RelativePath *dst)
static UA_INLINE size_t UA_DeleteNodesRequest_calcSizeBinary (const UA_DeleteNodesRequest *src)
static UA_INLINE UA_StatusCode UA_DeleteNodesRequest_encodeBinary (const UA_DeleteNodesRequest *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_DeleteNodesRequest_decodeBinary (const UA_ByteString *src, size_t *offset, UA_DeleteNodesRequest *dst)
static UA_INLINE size_t UA_MonitoredItemModifyRequest_calcSizeBinary (const UA_MonitoredItemModifyRequest *src)
static UA_INLINE UA_StatusCode UA_MonitoredItemModifyRequest_encodeBinary (const UA_MonitoredItemModifyRequest *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_MonitoredItemModifyRequest_decodeBinary (const UA_ByteString *src, size_t *offset, UA_MonitoredItemModifyRequest *dst)
static UA_INLINE size_t UA_UserTokenType_calcSizeBinary (const UA_UserTokenType *src)
static UA_INLINE UA_StatusCode UA_UserTokenType_encodeBinary (const UA_UserTokenType *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_UserTokenType_decodeBinary (const UA_ByteString *src, size_t *offset, UA_UserTokenType *dst)
static UA_INLINE size_t UA_AggregateConfiguration_calcSizeBinary (const UA_AggregateConfiguration *src)
static UA_INLINE UA_StatusCode UA_AggregateConfiguration_encodeBinary (const UA_AggregateConfiguration *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_AggregateConfiguration_decodeBinary (const UA_ByteString *src, size_t *offset, UA_AggregateConfiguration *dst)
static UA_INLINE size_t UA_LocaleId_calcSizeBinary (const UA_LocaleId *src)
static UA_INLINE UA_StatusCode UA_LocaleId_encodeBinary (const UA_LocaleId *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_LocaleId_decodeBinary (const UA_ByteString *src, size_t *offset, UA_LocaleId *dst)
static UA_INLINE size_t UA_UnregisterNodesResponse_calcSizeBinary (const UA_UnregisterNodesResponse *src)
static UA_INLINE UA_StatusCode UA_UnregisterNodesResponse_encodeBinary (const UA_UnregisterNodesResponse *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_UnregisterNodesResponse_decodeBinary (const UA_ByteString *src, size_t *offset, UA_UnregisterNodesResponse *dst)
static UA_INLINE size_t UA_ContentFilterResult_calcSizeBinary (const UA_ContentFilterResult *src)
static UA_INLINE UA_StatusCode UA_ContentFilterResult_encodeBinary (const UA_ContentFilterResult *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_ContentFilterResult_decodeBinary (const UA_ByteString *src, size_t *offset, UA_ContentFilterResult *dst)
static UA_INLINE size_t UA_UserTokenPolicy_calcSizeBinary (const UA_UserTokenPolicy *src)
static UA_INLINE UA_StatusCode UA_UserTokenPolicy_encodeBinary (const UA_UserTokenPolicy *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_UserTokenPolicy_decodeBinary (const UA_ByteString *src, size_t *offset, UA_UserTokenPolicy *dst)
static UA_INLINE size_t UA_DeleteMonitoredItemsRequest_calcSizeBinary (const UA_DeleteMonitoredItemsRequest *src)
static UA_INLINE UA_StatusCode UA_DeleteMonitoredItemsRequest_encodeBinary (const UA_DeleteMonitoredItemsRequest *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_DeleteMonitoredItemsRequest_decodeBinary (const UA_ByteString *src, size_t *offset, UA_DeleteMonitoredItemsRequest *dst)
static UA_INLINE size_t UA_SetMonitoringModeRequest_calcSizeBinary (const UA_SetMonitoringModeRequest *src)
static UA_INLINE UA_StatusCode UA_SetMonitoringModeRequest_encodeBinary (const UA_SetMonitoringModeRequest *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_SetMonitoringModeRequest_decodeBinary (const UA_ByteString *src, size_t *offset, UA_SetMonitoringModeRequest *dst)
static UA_INLINE size_t UA_Duration_calcSizeBinary (const UA_Duration *src)
static UA_INLINE UA_StatusCode UA_Duration_encodeBinary (const UA_Duration *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_Duration_decodeBinary (const UA_ByteString *src, size_t *offset, UA_Duration *dst)
static UA_INLINE size_t UA_ReferenceTypeAttributes_calcSizeBinary (const UA_ReferenceTypeAttributes *src)
static UA_INLINE UA_StatusCode UA_ReferenceTypeAttributes_encodeBinary (const UA_ReferenceTypeAttributes *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_ReferenceTypeAttributes_decodeBinary (const UA_ByteString *src, size_t *offset, UA_ReferenceTypeAttributes *dst)
static UA_INLINE size_t UA_GetEndpointsRequest_calcSizeBinary (const UA_GetEndpointsRequest *src)
static UA_INLINE UA_StatusCode UA_GetEndpointsRequest_encodeBinary (const UA_GetEndpointsRequest *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_GetEndpointsRequest_decodeBinary (const UA_ByteString *src, size_t *offset, UA_GetEndpointsRequest *dst)
static UA_INLINE size_t UA_CloseSecureChannelResponse_calcSizeBinary (const UA_CloseSecureChannelResponse *src)
static UA_INLINE UA_StatusCode UA_CloseSecureChannelResponse_encodeBinary (const UA_CloseSecureChannelResponse *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_CloseSecureChannelResponse_decodeBinary (const UA_ByteString *src, size_t *offset, UA_CloseSecureChannelResponse *dst)
static UA_INLINE size_t UA_ViewDescription_calcSizeBinary (const UA_ViewDescription *src)
static UA_INLINE UA_StatusCode UA_ViewDescription_encodeBinary (const UA_ViewDescription *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_ViewDescription_decodeBinary (const UA_ByteString *src, size_t *offset, UA_ViewDescription *dst)
static UA_INLINE size_t UA_SetPublishingModeResponse_calcSizeBinary (const UA_SetPublishingModeResponse *src)
static UA_INLINE UA_StatusCode UA_SetPublishingModeResponse_encodeBinary (const UA_SetPublishingModeResponse *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_SetPublishingModeResponse_decodeBinary (const UA_ByteString *src, size_t *offset, UA_SetPublishingModeResponse *dst)
static UA_INLINE size_t UA_StatusChangeNotification_calcSizeBinary (const UA_StatusChangeNotification *src)
static UA_INLINE UA_StatusCode UA_StatusChangeNotification_encodeBinary (const UA_StatusChangeNotification *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_StatusChangeNotification_decodeBinary (const UA_ByteString *src, size_t *offset, UA_StatusChangeNotification *dst)
static UA_INLINE size_t UA_NodeAttributesMask_calcSizeBinary (const UA_NodeAttributesMask *src)
static UA_INLINE UA_StatusCode UA_NodeAttributesMask_encodeBinary (const UA_NodeAttributesMask *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_NodeAttributesMask_decodeBinary (const UA_ByteString *src, size_t *offset, UA_NodeAttributesMask *dst)
static UA_INLINE size_t UA_EventFilterResult_calcSizeBinary (const UA_EventFilterResult *src)
static UA_INLINE UA_StatusCode UA_EventFilterResult_encodeBinary (const UA_EventFilterResult *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_EventFilterResult_decodeBinary (const UA_ByteString *src, size_t *offset, UA_EventFilterResult *dst)
static UA_INLINE size_t UA_MonitoredItemCreateRequest_calcSizeBinary (const UA_MonitoredItemCreateRequest *src)
static UA_INLINE UA_StatusCode UA_MonitoredItemCreateRequest_encodeBinary (const UA_MonitoredItemCreateRequest *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_MonitoredItemCreateRequest_decodeBinary (const UA_ByteString *src, size_t *offset, UA_MonitoredItemCreateRequest *dst)
static UA_INLINE size_t UA_Range_calcSizeBinary (const UA_Range *src)
static UA_INLINE UA_StatusCode UA_Range_encodeBinary (const UA_Range *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_Range_decodeBinary (const UA_ByteString *src, size_t *offset, UA_Range *dst)
static UA_INLINE size_t UA_DataChangeNotification_calcSizeBinary (const UA_DataChangeNotification *src)
static UA_INLINE UA_StatusCode UA_DataChangeNotification_encodeBinary (const UA_DataChangeNotification *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_DataChangeNotification_decodeBinary (const UA_ByteString *src, size_t *offset, UA_DataChangeNotification *dst)
static UA_INLINE size_t UA_Argument_calcSizeBinary (const UA_Argument *src)
static UA_INLINE UA_StatusCode UA_Argument_encodeBinary (const UA_Argument *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_Argument_decodeBinary (const UA_ByteString *src, size_t *offset, UA_Argument *dst)
static UA_INLINE size_t UA_ChannelSecurityToken_calcSizeBinary (const UA_ChannelSecurityToken *src)
static UA_INLINE UA_StatusCode UA_ChannelSecurityToken_encodeBinary (const UA_ChannelSecurityToken *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_ChannelSecurityToken_decodeBinary (const UA_ByteString *src, size_t *offset, UA_ChannelSecurityToken *dst)
static UA_INLINE size_t UA_ServerState_calcSizeBinary (const UA_ServerState *src)
static UA_INLINE UA_StatusCode UA_ServerState_encodeBinary (const UA_ServerState *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_ServerState_decodeBinary (const UA_ByteString *src, size_t *offset, UA_ServerState *dst)
static UA_INLINE size_t UA_EventNotificationList_calcSizeBinary (const UA_EventNotificationList *src)
static UA_INLINE UA_StatusCode UA_EventNotificationList_encodeBinary (const UA_EventNotificationList *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_EventNotificationList_decodeBinary (const UA_ByteString *src, size_t *offset, UA_EventNotificationList *dst)
static UA_INLINE size_t UA_AnonymousIdentityToken_calcSizeBinary (const UA_AnonymousIdentityToken *src)
static UA_INLINE UA_StatusCode UA_AnonymousIdentityToken_encodeBinary (const UA_AnonymousIdentityToken *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_AnonymousIdentityToken_decodeBinary (const UA_ByteString *src, size_t *offset, UA_AnonymousIdentityToken *dst)
static UA_INLINE size_t UA_FilterOperator_calcSizeBinary (const UA_FilterOperator *src)
static UA_INLINE UA_StatusCode UA_FilterOperator_encodeBinary (const UA_FilterOperator *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_FilterOperator_decodeBinary (const UA_ByteString *src, size_t *offset, UA_FilterOperator *dst)
static UA_INLINE size_t UA_AggregateFilter_calcSizeBinary (const UA_AggregateFilter *src)
static UA_INLINE UA_StatusCode UA_AggregateFilter_encodeBinary (const UA_AggregateFilter *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_AggregateFilter_decodeBinary (const UA_ByteString *src, size_t *offset, UA_AggregateFilter *dst)
static UA_INLINE size_t UA_RepublishResponse_calcSizeBinary (const UA_RepublishResponse *src)
static UA_INLINE UA_StatusCode UA_RepublishResponse_encodeBinary (const UA_RepublishResponse *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_RepublishResponse_decodeBinary (const UA_ByteString *src, size_t *offset, UA_RepublishResponse *dst)
static UA_INLINE size_t UA_DeleteSubscriptionsResponse_calcSizeBinary (const UA_DeleteSubscriptionsResponse *src)
static UA_INLINE UA_StatusCode UA_DeleteSubscriptionsResponse_encodeBinary (const UA_DeleteSubscriptionsResponse *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_DeleteSubscriptionsResponse_decodeBinary (const UA_ByteString *src, size_t *offset, UA_DeleteSubscriptionsResponse *dst)
static UA_INLINE size_t UA_RegisterNodesRequest_calcSizeBinary (const UA_RegisterNodesRequest *src)
static UA_INLINE UA_StatusCode UA_RegisterNodesRequest_encodeBinary (const UA_RegisterNodesRequest *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_RegisterNodesRequest_decodeBinary (const UA_ByteString *src, size_t *offset, UA_RegisterNodesRequest *dst)
static UA_INLINE size_t UA_MethodAttributes_calcSizeBinary (const UA_MethodAttributes *src)
static UA_INLINE UA_StatusCode UA_MethodAttributes_encodeBinary (const UA_MethodAttributes *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_MethodAttributes_decodeBinary (const UA_ByteString *src, size_t *offset, UA_MethodAttributes *dst)
static UA_INLINE size_t UA_UserNameIdentityToken_calcSizeBinary (const UA_UserNameIdentityToken *src)
static UA_INLINE UA_StatusCode UA_UserNameIdentityToken_encodeBinary (const UA_UserNameIdentityToken *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_UserNameIdentityToken_decodeBinary (const UA_ByteString *src, size_t *offset, UA_UserNameIdentityToken *dst)
static UA_INLINE size_t UA_UnregisterNodesRequest_calcSizeBinary (const UA_UnregisterNodesRequest *src)
static UA_INLINE UA_StatusCode UA_UnregisterNodesRequest_encodeBinary (const UA_UnregisterNodesRequest *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_UnregisterNodesRequest_decodeBinary (const UA_ByteString *src, size_t *offset, UA_UnregisterNodesRequest *dst)
static UA_INLINE size_t UA_OpenSecureChannelResponse_calcSizeBinary (const UA_OpenSecureChannelResponse *src)
static UA_INLINE UA_StatusCode UA_OpenSecureChannelResponse_encodeBinary (const UA_OpenSecureChannelResponse *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_OpenSecureChannelResponse_decodeBinary (const UA_ByteString *src, size_t *offset, UA_OpenSecureChannelResponse *dst)
static UA_INLINE size_t UA_SetTriggeringResponse_calcSizeBinary (const UA_SetTriggeringResponse *src)
static UA_INLINE UA_StatusCode UA_SetTriggeringResponse_encodeBinary (const UA_SetTriggeringResponse *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_SetTriggeringResponse_decodeBinary (const UA_ByteString *src, size_t *offset, UA_SetTriggeringResponse *dst)
static UA_INLINE size_t UA_SimpleAttributeOperand_calcSizeBinary (const UA_SimpleAttributeOperand *src)
static UA_INLINE UA_StatusCode UA_SimpleAttributeOperand_encodeBinary (const UA_SimpleAttributeOperand *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_SimpleAttributeOperand_decodeBinary (const UA_ByteString *src, size_t *offset, UA_SimpleAttributeOperand *dst)
static UA_INLINE size_t UA_RepublishRequest_calcSizeBinary (const UA_RepublishRequest *src)
static UA_INLINE UA_StatusCode UA_RepublishRequest_encodeBinary (const UA_RepublishRequest *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_RepublishRequest_decodeBinary (const UA_ByteString *src, size_t *offset, UA_RepublishRequest *dst)
static UA_INLINE size_t UA_RegisterNodesResponse_calcSizeBinary (const UA_RegisterNodesResponse *src)
static UA_INLINE UA_StatusCode UA_RegisterNodesResponse_encodeBinary (const UA_RegisterNodesResponse *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_RegisterNodesResponse_decodeBinary (const UA_ByteString *src, size_t *offset, UA_RegisterNodesResponse *dst)
static UA_INLINE size_t UA_ModifyMonitoredItemsResponse_calcSizeBinary (const UA_ModifyMonitoredItemsResponse *src)
static UA_INLINE UA_StatusCode UA_ModifyMonitoredItemsResponse_encodeBinary (const UA_ModifyMonitoredItemsResponse *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_ModifyMonitoredItemsResponse_decodeBinary (const UA_ByteString *src, size_t *offset, UA_ModifyMonitoredItemsResponse *dst)
static UA_INLINE size_t UA_DeleteSubscriptionsRequest_calcSizeBinary (const UA_DeleteSubscriptionsRequest *src)
static UA_INLINE UA_StatusCode UA_DeleteSubscriptionsRequest_encodeBinary (const UA_DeleteSubscriptionsRequest *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_DeleteSubscriptionsRequest_decodeBinary (const UA_ByteString *src, size_t *offset, UA_DeleteSubscriptionsRequest *dst)
static UA_INLINE size_t UA_RedundancySupport_calcSizeBinary (const UA_RedundancySupport *src)
static UA_INLINE UA_StatusCode UA_RedundancySupport_encodeBinary (const UA_RedundancySupport *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_RedundancySupport_decodeBinary (const UA_ByteString *src, size_t *offset, UA_RedundancySupport *dst)
static UA_INLINE size_t UA_BrowsePath_calcSizeBinary (const UA_BrowsePath *src)
static UA_INLINE UA_StatusCode UA_BrowsePath_encodeBinary (const UA_BrowsePath *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_BrowsePath_decodeBinary (const UA_ByteString *src, size_t *offset, UA_BrowsePath *dst)
static UA_INLINE size_t UA_ObjectAttributes_calcSizeBinary (const UA_ObjectAttributes *src)
static UA_INLINE UA_StatusCode UA_ObjectAttributes_encodeBinary (const UA_ObjectAttributes *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_ObjectAttributes_decodeBinary (const UA_ByteString *src, size_t *offset, UA_ObjectAttributes *dst)
static UA_INLINE size_t UA_PublishRequest_calcSizeBinary (const UA_PublishRequest *src)
static UA_INLINE UA_StatusCode UA_PublishRequest_encodeBinary (const UA_PublishRequest *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_PublishRequest_decodeBinary (const UA_ByteString *src, size_t *offset, UA_PublishRequest *dst)
static UA_INLINE size_t UA_FindServersRequest_calcSizeBinary (const UA_FindServersRequest *src)
static UA_INLINE UA_StatusCode UA_FindServersRequest_encodeBinary (const UA_FindServersRequest *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_FindServersRequest_decodeBinary (const UA_ByteString *src, size_t *offset, UA_FindServersRequest *dst)
static UA_INLINE size_t UA_FindServersOnNetworkResponse_calcSizeBinary (const UA_FindServersOnNetworkResponse *src)
static UA_INLINE UA_StatusCode UA_FindServersOnNetworkResponse_encodeBinary (const UA_FindServersOnNetworkResponse *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_FindServersOnNetworkResponse_decodeBinary (const UA_ByteString *src, size_t *offset, UA_FindServersOnNetworkResponse *dst)
static UA_INLINE size_t UA_ReferenceDescription_calcSizeBinary (const UA_ReferenceDescription *src)
static UA_INLINE UA_StatusCode UA_ReferenceDescription_encodeBinary (const UA_ReferenceDescription *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_ReferenceDescription_decodeBinary (const UA_ByteString *src, size_t *offset, UA_ReferenceDescription *dst)
static UA_INLINE size_t UA_CreateSubscriptionRequest_calcSizeBinary (const UA_CreateSubscriptionRequest *src)
static UA_INLINE UA_StatusCode UA_CreateSubscriptionRequest_encodeBinary (const UA_CreateSubscriptionRequest *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_CreateSubscriptionRequest_decodeBinary (const UA_ByteString *src, size_t *offset, UA_CreateSubscriptionRequest *dst)
static UA_INLINE size_t UA_FindServersOnNetworkRequest_calcSizeBinary (const UA_FindServersOnNetworkRequest *src)
static UA_INLINE UA_StatusCode UA_FindServersOnNetworkRequest_encodeBinary (const UA_FindServersOnNetworkRequest *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_FindServersOnNetworkRequest_decodeBinary (const UA_ByteString *src, size_t *offset, UA_FindServersOnNetworkRequest *dst)
static UA_INLINE size_t UA_CallResponse_calcSizeBinary (const UA_CallResponse *src)
static UA_INLINE UA_StatusCode UA_CallResponse_encodeBinary (const UA_CallResponse *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_CallResponse_decodeBinary (const UA_ByteString *src, size_t *offset, UA_CallResponse *dst)
static UA_INLINE size_t UA_DeleteNodesResponse_calcSizeBinary (const UA_DeleteNodesResponse *src)
static UA_INLINE UA_StatusCode UA_DeleteNodesResponse_encodeBinary (const UA_DeleteNodesResponse *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_DeleteNodesResponse_decodeBinary (const UA_ByteString *src, size_t *offset, UA_DeleteNodesResponse *dst)
static UA_INLINE size_t UA_ModifyMonitoredItemsRequest_calcSizeBinary (const UA_ModifyMonitoredItemsRequest *src)
static UA_INLINE UA_StatusCode UA_ModifyMonitoredItemsRequest_encodeBinary (const UA_ModifyMonitoredItemsRequest *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_ModifyMonitoredItemsRequest_decodeBinary (const UA_ByteString *src, size_t *offset, UA_ModifyMonitoredItemsRequest *dst)
static UA_INLINE size_t UA_ServiceFault_calcSizeBinary (const UA_ServiceFault *src)
static UA_INLINE UA_StatusCode UA_ServiceFault_encodeBinary (const UA_ServiceFault *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_ServiceFault_decodeBinary (const UA_ByteString *src, size_t *offset, UA_ServiceFault *dst)
static UA_INLINE size_t UA_PublishResponse_calcSizeBinary (const UA_PublishResponse *src)
static UA_INLINE UA_StatusCode UA_PublishResponse_encodeBinary (const UA_PublishResponse *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_PublishResponse_decodeBinary (const UA_ByteString *src, size_t *offset, UA_PublishResponse *dst)
static UA_INLINE size_t UA_CreateMonitoredItemsRequest_calcSizeBinary (const UA_CreateMonitoredItemsRequest *src)
static UA_INLINE UA_StatusCode UA_CreateMonitoredItemsRequest_encodeBinary (const UA_CreateMonitoredItemsRequest *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_CreateMonitoredItemsRequest_decodeBinary (const UA_ByteString *src, size_t *offset, UA_CreateMonitoredItemsRequest *dst)
static UA_INLINE size_t UA_OpenSecureChannelRequest_calcSizeBinary (const UA_OpenSecureChannelRequest *src)
static UA_INLINE UA_StatusCode UA_OpenSecureChannelRequest_encodeBinary (const UA_OpenSecureChannelRequest *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_OpenSecureChannelRequest_decodeBinary (const UA_ByteString *src, size_t *offset, UA_OpenSecureChannelRequest *dst)
static UA_INLINE size_t UA_CloseSessionRequest_calcSizeBinary (const UA_CloseSessionRequest *src)
static UA_INLINE UA_StatusCode UA_CloseSessionRequest_encodeBinary (const UA_CloseSessionRequest *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_CloseSessionRequest_decodeBinary (const UA_ByteString *src, size_t *offset, UA_CloseSessionRequest *dst)
static UA_INLINE size_t UA_SetTriggeringRequest_calcSizeBinary (const UA_SetTriggeringRequest *src)
static UA_INLINE UA_StatusCode UA_SetTriggeringRequest_encodeBinary (const UA_SetTriggeringRequest *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_SetTriggeringRequest_decodeBinary (const UA_ByteString *src, size_t *offset, UA_SetTriggeringRequest *dst)
static UA_INLINE size_t UA_BrowseResult_calcSizeBinary (const UA_BrowseResult *src)
static UA_INLINE UA_StatusCode UA_BrowseResult_encodeBinary (const UA_BrowseResult *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_BrowseResult_decodeBinary (const UA_ByteString *src, size_t *offset, UA_BrowseResult *dst)
static UA_INLINE size_t UA_AddReferencesRequest_calcSizeBinary (const UA_AddReferencesRequest *src)
static UA_INLINE UA_StatusCode UA_AddReferencesRequest_encodeBinary (const UA_AddReferencesRequest *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_AddReferencesRequest_decodeBinary (const UA_ByteString *src, size_t *offset, UA_AddReferencesRequest *dst)
static UA_INLINE size_t UA_AddNodesItem_calcSizeBinary (const UA_AddNodesItem *src)
static UA_INLINE UA_StatusCode UA_AddNodesItem_encodeBinary (const UA_AddNodesItem *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_AddNodesItem_decodeBinary (const UA_ByteString *src, size_t *offset, UA_AddNodesItem *dst)
static UA_INLINE size_t UA_ServerStatusDataType_calcSizeBinary (const UA_ServerStatusDataType *src)
static UA_INLINE UA_StatusCode UA_ServerStatusDataType_encodeBinary (const UA_ServerStatusDataType *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_ServerStatusDataType_decodeBinary (const UA_ByteString *src, size_t *offset, UA_ServerStatusDataType *dst)
static UA_INLINE size_t UA_BrowseNextResponse_calcSizeBinary (const UA_BrowseNextResponse *src)
static UA_INLINE UA_StatusCode UA_BrowseNextResponse_encodeBinary (const UA_BrowseNextResponse *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_BrowseNextResponse_decodeBinary (const UA_ByteString *src, size_t *offset, UA_BrowseNextResponse *dst)
static UA_INLINE size_t UA_RegisteredServer_calcSizeBinary (const UA_RegisteredServer *src)
static UA_INLINE UA_StatusCode UA_RegisteredServer_encodeBinary (const UA_RegisteredServer *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_RegisteredServer_decodeBinary (const UA_ByteString *src, size_t *offset, UA_RegisteredServer *dst)
static UA_INLINE size_t UA_ApplicationDescription_calcSizeBinary (const UA_ApplicationDescription *src)
static UA_INLINE UA_StatusCode UA_ApplicationDescription_encodeBinary (const UA_ApplicationDescription *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_ApplicationDescription_decodeBinary (const UA_ByteString *src, size_t *offset, UA_ApplicationDescription *dst)
static UA_INLINE size_t UA_ReadRequest_calcSizeBinary (const UA_ReadRequest *src)
static UA_INLINE UA_StatusCode UA_ReadRequest_encodeBinary (const UA_ReadRequest *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_ReadRequest_decodeBinary (const UA_ByteString *src, size_t *offset, UA_ReadRequest *dst)
static UA_INLINE size_t UA_ActivateSessionRequest_calcSizeBinary (const UA_ActivateSessionRequest *src)
static UA_INLINE UA_StatusCode UA_ActivateSessionRequest_encodeBinary (const UA_ActivateSessionRequest *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_ActivateSessionRequest_decodeBinary (const UA_ByteString *src, size_t *offset, UA_ActivateSessionRequest *dst)
static UA_INLINE size_t UA_BrowsePathResult_calcSizeBinary (const UA_BrowsePathResult *src)
static UA_INLINE UA_StatusCode UA_BrowsePathResult_encodeBinary (const UA_BrowsePathResult *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_BrowsePathResult_decodeBinary (const UA_ByteString *src, size_t *offset, UA_BrowsePathResult *dst)
static UA_INLINE size_t UA_AddNodesRequest_calcSizeBinary (const UA_AddNodesRequest *src)
static UA_INLINE UA_StatusCode UA_AddNodesRequest_encodeBinary (const UA_AddNodesRequest *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_AddNodesRequest_decodeBinary (const UA_ByteString *src, size_t *offset, UA_AddNodesRequest *dst)
static UA_INLINE size_t UA_BrowseRequest_calcSizeBinary (const UA_BrowseRequest *src)
static UA_INLINE UA_StatusCode UA_BrowseRequest_encodeBinary (const UA_BrowseRequest *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_BrowseRequest_decodeBinary (const UA_ByteString *src, size_t *offset, UA_BrowseRequest *dst)
static UA_INLINE size_t UA_WriteRequest_calcSizeBinary (const UA_WriteRequest *src)
static UA_INLINE UA_StatusCode UA_WriteRequest_encodeBinary (const UA_WriteRequest *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_WriteRequest_decodeBinary (const UA_ByteString *src, size_t *offset, UA_WriteRequest *dst)
static UA_INLINE size_t UA_AddNodesResponse_calcSizeBinary (const UA_AddNodesResponse *src)
static UA_INLINE UA_StatusCode UA_AddNodesResponse_encodeBinary (const UA_AddNodesResponse *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_AddNodesResponse_decodeBinary (const UA_ByteString *src, size_t *offset, UA_AddNodesResponse *dst)
static UA_INLINE size_t UA_RegisterServer2Request_calcSizeBinary (const UA_RegisterServer2Request *src)
static UA_INLINE UA_StatusCode UA_RegisterServer2Request_encodeBinary (const UA_RegisterServer2Request *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_RegisterServer2Request_decodeBinary (const UA_ByteString *src, size_t *offset, UA_RegisterServer2Request *dst)
static UA_INLINE size_t UA_AttributeOperand_calcSizeBinary (const UA_AttributeOperand *src)
static UA_INLINE UA_StatusCode UA_AttributeOperand_encodeBinary (const UA_AttributeOperand *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_AttributeOperand_decodeBinary (const UA_ByteString *src, size_t *offset, UA_AttributeOperand *dst)
static UA_INLINE size_t UA_DataChangeFilter_calcSizeBinary (const UA_DataChangeFilter *src)
static UA_INLINE UA_StatusCode UA_DataChangeFilter_encodeBinary (const UA_DataChangeFilter *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_DataChangeFilter_decodeBinary (const UA_ByteString *src, size_t *offset, UA_DataChangeFilter *dst)
static UA_INLINE size_t UA_EndpointDescription_calcSizeBinary (const UA_EndpointDescription *src)
static UA_INLINE UA_StatusCode UA_EndpointDescription_encodeBinary (const UA_EndpointDescription *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_EndpointDescription_decodeBinary (const UA_ByteString *src, size_t *offset, UA_EndpointDescription *dst)
static UA_INLINE size_t UA_DeleteReferencesRequest_calcSizeBinary (const UA_DeleteReferencesRequest *src)
static UA_INLINE UA_StatusCode UA_DeleteReferencesRequest_encodeBinary (const UA_DeleteReferencesRequest *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_DeleteReferencesRequest_decodeBinary (const UA_ByteString *src, size_t *offset, UA_DeleteReferencesRequest *dst)
static UA_INLINE size_t UA_TranslateBrowsePathsToNodeIdsRequest_calcSizeBinary (const UA_TranslateBrowsePathsToNodeIdsRequest *src)
static UA_INLINE UA_StatusCode UA_TranslateBrowsePathsToNodeIdsRequest_encodeBinary (const UA_TranslateBrowsePathsToNodeIdsRequest *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_TranslateBrowsePathsToNodeIdsRequest_decodeBinary (const UA_ByteString *src, size_t *offset, UA_TranslateBrowsePathsToNodeIdsRequest *dst)
static UA_INLINE size_t UA_FindServersResponse_calcSizeBinary (const UA_FindServersResponse *src)
static UA_INLINE UA_StatusCode UA_FindServersResponse_encodeBinary (const UA_FindServersResponse *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_FindServersResponse_decodeBinary (const UA_ByteString *src, size_t *offset, UA_FindServersResponse *dst)
static UA_INLINE size_t UA_CreateSessionRequest_calcSizeBinary (const UA_CreateSessionRequest *src)
static UA_INLINE UA_StatusCode UA_CreateSessionRequest_encodeBinary (const UA_CreateSessionRequest *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_CreateSessionRequest_decodeBinary (const UA_ByteString *src, size_t *offset, UA_CreateSessionRequest *dst)
static UA_INLINE size_t UA_ContentFilterElement_calcSizeBinary (const UA_ContentFilterElement *src)
static UA_INLINE UA_StatusCode UA_ContentFilterElement_encodeBinary (const UA_ContentFilterElement *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_ContentFilterElement_decodeBinary (const UA_ByteString *src, size_t *offset, UA_ContentFilterElement *dst)
static UA_INLINE size_t UA_RegisterServerRequest_calcSizeBinary (const UA_RegisterServerRequest *src)
static UA_INLINE UA_StatusCode UA_RegisterServerRequest_encodeBinary (const UA_RegisterServerRequest *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_RegisterServerRequest_decodeBinary (const UA_ByteString *src, size_t *offset, UA_RegisterServerRequest *dst)
static UA_INLINE size_t UA_TranslateBrowsePathsToNodeIdsResponse_calcSizeBinary (const UA_TranslateBrowsePathsToNodeIdsResponse *src)
static UA_INLINE UA_StatusCode UA_TranslateBrowsePathsToNodeIdsResponse_encodeBinary (const UA_TranslateBrowsePathsToNodeIdsResponse *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_TranslateBrowsePathsToNodeIdsResponse_decodeBinary (const UA_ByteString *src, size_t *offset, UA_TranslateBrowsePathsToNodeIdsResponse *dst)
static UA_INLINE size_t UA_BrowseResponse_calcSizeBinary (const UA_BrowseResponse *src)
static UA_INLINE UA_StatusCode UA_BrowseResponse_encodeBinary (const UA_BrowseResponse *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_BrowseResponse_decodeBinary (const UA_ByteString *src, size_t *offset, UA_BrowseResponse *dst)
static UA_INLINE size_t UA_CreateSessionResponse_calcSizeBinary (const UA_CreateSessionResponse *src)
static UA_INLINE UA_StatusCode UA_CreateSessionResponse_encodeBinary (const UA_CreateSessionResponse *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_CreateSessionResponse_decodeBinary (const UA_ByteString *src, size_t *offset, UA_CreateSessionResponse *dst)
static UA_INLINE size_t UA_ContentFilter_calcSizeBinary (const UA_ContentFilter *src)
static UA_INLINE UA_StatusCode UA_ContentFilter_encodeBinary (const UA_ContentFilter *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_ContentFilter_decodeBinary (const UA_ByteString *src, size_t *offset, UA_ContentFilter *dst)
static UA_INLINE size_t UA_GetEndpointsResponse_calcSizeBinary (const UA_GetEndpointsResponse *src)
static UA_INLINE UA_StatusCode UA_GetEndpointsResponse_encodeBinary (const UA_GetEndpointsResponse *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_GetEndpointsResponse_decodeBinary (const UA_ByteString *src, size_t *offset, UA_GetEndpointsResponse *dst)
static UA_INLINE size_t UA_EventFilter_calcSizeBinary (const UA_EventFilter *src)
static UA_INLINE UA_StatusCode UA_EventFilter_encodeBinary (const UA_EventFilter *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_EventFilter_decodeBinary (const UA_ByteString *src, size_t *offset, UA_EventFilter *dst)
Function Documentation
UA_ActivateSessionRequest_calcSizeBinary()
static UA_INLINE size_t UA_ActivateSessionRequest_calcSizeBinary (const UA_ActivateSessionRequest * src) static
Definition at line 2311 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_ActivateSessionRequest_decodeBinary()
static UA_INLINE UA_StatusCode UA_ActivateSessionRequest_decodeBinary (const UA_ByteString * src, size_t * offset, UA_ActivateSessionRequest * dst) static
Definition at line 2319 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_ActivateSessionRequest_encodeBinary()
static UA_INLINE UA_StatusCode UA_ActivateSessionRequest_encodeBinary (const UA_ActivateSessionRequest * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 2315 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_ActivateSessionResponse_calcSizeBinary()
static UA_INLINE size_t UA_ActivateSessionResponse_calcSizeBinary (const UA_ActivateSessionResponse * src) static
Definition at line 617 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_ActivateSessionResponse_decodeBinary()
static UA_INLINE UA_StatusCode UA_ActivateSessionResponse_decodeBinary (const UA_ByteString * src, size_t * offset, UA_ActivateSessionResponse * dst) static
Definition at line 625 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_ActivateSessionResponse_encodeBinary()
static UA_INLINE UA_StatusCode UA_ActivateSessionResponse_encodeBinary (const UA_ActivateSessionResponse * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 621 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_AddNodesItem_calcSizeBinary()
static UA_INLINE size_t UA_AddNodesItem_calcSizeBinary (const UA_AddNodesItem * src) static
Definition at line 2227 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_AddNodesItem_decodeBinary()
static UA_INLINE UA_StatusCode UA_AddNodesItem_decodeBinary (const UA_ByteString * src, size_t * offset, UA_AddNodesItem * dst) static
Definition at line 2235 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_AddNodesItem_encodeBinary()
static UA_INLINE UA_StatusCode UA_AddNodesItem_encodeBinary (const UA_AddNodesItem * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 2231 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_AddNodesRequest_calcSizeBinary()
static UA_INLINE size_t UA_AddNodesRequest_calcSizeBinary (const UA_AddNodesRequest * src) static
Definition at line 2339 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_AddNodesRequest_decodeBinary()
static UA_INLINE UA_StatusCode UA_AddNodesRequest_decodeBinary (const UA_ByteString * src, size_t * offset, UA_AddNodesRequest * dst) static
Definition at line 2347 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_AddNodesRequest_encodeBinary()
static UA_INLINE UA_StatusCode UA_AddNodesRequest_encodeBinary (const UA_AddNodesRequest * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 2343 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_AddNodesResponse_calcSizeBinary()
static UA_INLINE size_t UA_AddNodesResponse_calcSizeBinary (const UA_AddNodesResponse * src) static
Definition at line 2381 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_AddNodesResponse_decodeBinary()
static UA_INLINE UA_StatusCode UA_AddNodesResponse_decodeBinary (const UA_ByteString * src, size_t * offset, UA_AddNodesResponse * dst) static
Definition at line 2389 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_AddNodesResponse_encodeBinary()
static UA_INLINE UA_StatusCode UA_AddNodesResponse_encodeBinary (const UA_AddNodesResponse * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 2385 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_AddNodesResult_calcSizeBinary()
static UA_INLINE size_t UA_AddNodesResult_calcSizeBinary (const UA_AddNodesResult * src) static
Definition at line 1065 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_AddNodesResult_decodeBinary()
static UA_INLINE UA_StatusCode UA_AddNodesResult_decodeBinary (const UA_ByteString * src, size_t * offset, UA_AddNodesResult * dst) static
Definition at line 1073 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_AddNodesResult_encodeBinary()
static UA_INLINE UA_StatusCode UA_AddNodesResult_encodeBinary (const UA_AddNodesResult * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 1069 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_AddReferencesItem_calcSizeBinary()
static UA_INLINE size_t UA_AddReferencesItem_calcSizeBinary (const UA_AddReferencesItem * src) static
Definition at line 1093 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_AddReferencesItem_decodeBinary()
static UA_INLINE UA_StatusCode UA_AddReferencesItem_decodeBinary (const UA_ByteString * src, size_t * offset, UA_AddReferencesItem * dst) static
Definition at line 1101 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_AddReferencesItem_encodeBinary()
static UA_INLINE UA_StatusCode UA_AddReferencesItem_encodeBinary (const UA_AddReferencesItem * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 1097 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_AddReferencesRequest_calcSizeBinary()
static UA_INLINE size_t UA_AddReferencesRequest_calcSizeBinary (const UA_AddReferencesRequest * src) static
Definition at line 2213 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_AddReferencesRequest_decodeBinary()
static UA_INLINE UA_StatusCode UA_AddReferencesRequest_decodeBinary (const UA_ByteString * src, size_t * offset, UA_AddReferencesRequest * dst) static
Definition at line 2221 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_AddReferencesRequest_encodeBinary()
static UA_INLINE UA_StatusCode UA_AddReferencesRequest_encodeBinary (const UA_AddReferencesRequest * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 2217 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_AddReferencesResponse_calcSizeBinary()
static UA_INLINE size_t UA_AddReferencesResponse_calcSizeBinary (const UA_AddReferencesResponse * src) static
Definition at line 1219 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_AddReferencesResponse_decodeBinary()
static UA_INLINE UA_StatusCode UA_AddReferencesResponse_decodeBinary (const UA_ByteString * src, size_t * offset, UA_AddReferencesResponse * dst) static
Definition at line 1227 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_AddReferencesResponse_encodeBinary()
static UA_INLINE UA_StatusCode UA_AddReferencesResponse_encodeBinary (const UA_AddReferencesResponse * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 1223 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_AggregateConfiguration_calcSizeBinary()
static UA_INLINE size_t UA_AggregateConfiguration_calcSizeBinary (const UA_AggregateConfiguration * src) static
Definition at line 1401 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_AggregateConfiguration_decodeBinary()
static UA_INLINE UA_StatusCode UA_AggregateConfiguration_decodeBinary (const UA_ByteString * src, size_t * offset, UA_AggregateConfiguration * dst) static
Definition at line 1409 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_AggregateConfiguration_encodeBinary()
static UA_INLINE UA_StatusCode UA_AggregateConfiguration_encodeBinary (const UA_AggregateConfiguration * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 1405 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_AggregateFilter_calcSizeBinary()
static UA_INLINE size_t UA_AggregateFilter_calcSizeBinary (const UA_AggregateFilter * src) static
Definition at line 1751 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_AggregateFilter_decodeBinary()
static UA_INLINE UA_StatusCode UA_AggregateFilter_decodeBinary (const UA_ByteString * src, size_t * offset, UA_AggregateFilter * dst) static
Definition at line 1759 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_AggregateFilter_encodeBinary()
static UA_INLINE UA_StatusCode UA_AggregateFilter_encodeBinary (const UA_AggregateFilter * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 1755 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_AnonymousIdentityToken_calcSizeBinary()
static UA_INLINE size_t UA_AnonymousIdentityToken_calcSizeBinary (const UA_AnonymousIdentityToken * src) static
Definition at line 1723 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_AnonymousIdentityToken_decodeBinary()
static UA_INLINE UA_StatusCode UA_AnonymousIdentityToken_decodeBinary (const UA_ByteString * src, size_t * offset, UA_AnonymousIdentityToken * dst) static
Definition at line 1731 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_AnonymousIdentityToken_encodeBinary()
static UA_INLINE UA_StatusCode UA_AnonymousIdentityToken_encodeBinary (const UA_AnonymousIdentityToken * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 1727 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_ApplicationDescription_calcSizeBinary()
static UA_INLINE size_t UA_ApplicationDescription_calcSizeBinary (const UA_ApplicationDescription * src) static
Definition at line 2283 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_ApplicationDescription_decodeBinary()
static UA_INLINE UA_StatusCode UA_ApplicationDescription_decodeBinary (const UA_ByteString * src, size_t * offset, UA_ApplicationDescription * dst) static
Definition at line 2291 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_ApplicationDescription_encodeBinary()
static UA_INLINE UA_StatusCode UA_ApplicationDescription_encodeBinary (const UA_ApplicationDescription * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 2287 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_ApplicationType_calcSizeBinary()
static UA_INLINE size_t UA_ApplicationType_calcSizeBinary (const UA_ApplicationType * src) static
Definition at line 953 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_ApplicationType_decodeBinary()
static UA_INLINE UA_StatusCode UA_ApplicationType_decodeBinary (const UA_ByteString * src, size_t * offset, UA_ApplicationType * dst) static
Definition at line 961 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_ApplicationType_encodeBinary()
static UA_INLINE UA_StatusCode UA_ApplicationType_encodeBinary (const UA_ApplicationType * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 957 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_Argument_calcSizeBinary()
static UA_INLINE size_t UA_Argument_calcSizeBinary (const UA_Argument * src) static
Definition at line 1667 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_Argument_decodeBinary()
static UA_INLINE UA_StatusCode UA_Argument_decodeBinary (const UA_ByteString * src, size_t * offset, UA_Argument * dst) static
Definition at line 1675 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_Argument_encodeBinary()
static UA_INLINE UA_StatusCode UA_Argument_encodeBinary (const UA_Argument * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 1671 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_AttributeOperand_calcSizeBinary()
static UA_INLINE size_t UA_AttributeOperand_calcSizeBinary (const UA_AttributeOperand * src) static
Definition at line 2409 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_AttributeOperand_decodeBinary()
static UA_INLINE UA_StatusCode UA_AttributeOperand_decodeBinary (const UA_ByteString * src, size_t * offset, UA_AttributeOperand * dst) static
Definition at line 2417 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_AttributeOperand_encodeBinary()
static UA_INLINE UA_StatusCode UA_AttributeOperand_encodeBinary (const UA_AttributeOperand * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 2413 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_Boolean_calcSizeBinary()
static UA_INLINE size_t UA_Boolean_calcSizeBinary (const UA_Boolean * src) static
Definition at line 15 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_Boolean_decodeBinary()
static UA_INLINE UA_StatusCode UA_Boolean_decodeBinary (const UA_ByteString * src, size_t * offset, UA_Boolean * dst) static
Definition at line 23 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_Boolean_encodeBinary()
static UA_INLINE UA_StatusCode UA_Boolean_encodeBinary (const UA_Boolean * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 19 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_BrowseDescription_calcSizeBinary()
static UA_INLINE size_t UA_BrowseDescription_calcSizeBinary (const UA_BrowseDescription * src) static
Definition at line 1009 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_BrowseDescription_decodeBinary()
static UA_INLINE UA_StatusCode UA_BrowseDescription_decodeBinary (const UA_ByteString * src, size_t * offset, UA_BrowseDescription * dst) static
Definition at line 1017 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_BrowseDescription_encodeBinary()
static UA_INLINE UA_StatusCode UA_BrowseDescription_encodeBinary (const UA_BrowseDescription * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 1013 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_BrowseDirection_calcSizeBinary()
static UA_INLINE size_t UA_BrowseDirection_calcSizeBinary (const UA_BrowseDirection * src) static
Definition at line 785 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_BrowseDirection_decodeBinary()
static UA_INLINE UA_StatusCode UA_BrowseDirection_decodeBinary (const UA_ByteString * src, size_t * offset, UA_BrowseDirection * dst) static
Definition at line 793 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_BrowseDirection_encodeBinary()
static UA_INLINE UA_StatusCode UA_BrowseDirection_encodeBinary (const UA_BrowseDirection * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 789 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_BrowseNextRequest_calcSizeBinary()
static UA_INLINE size_t UA_BrowseNextRequest_calcSizeBinary (const UA_BrowseNextRequest * src) static
Definition at line 981 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_BrowseNextRequest_decodeBinary()
static UA_INLINE UA_StatusCode UA_BrowseNextRequest_decodeBinary (const UA_ByteString * src, size_t * offset, UA_BrowseNextRequest * dst) static
Definition at line 989 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_BrowseNextRequest_encodeBinary()
static UA_INLINE UA_StatusCode UA_BrowseNextRequest_encodeBinary (const UA_BrowseNextRequest * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 985 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_BrowseNextResponse_calcSizeBinary()
static UA_INLINE size_t UA_BrowseNextResponse_calcSizeBinary (const UA_BrowseNextResponse * src) static
Definition at line 2255 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_BrowseNextResponse_decodeBinary()
static UA_INLINE UA_StatusCode UA_BrowseNextResponse_decodeBinary (const UA_ByteString * src, size_t * offset, UA_BrowseNextResponse * dst) static
Definition at line 2263 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_BrowseNextResponse_encodeBinary()
static UA_INLINE UA_StatusCode UA_BrowseNextResponse_encodeBinary (const UA_BrowseNextResponse * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 2259 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_BrowsePath_calcSizeBinary()
static UA_INLINE size_t UA_BrowsePath_calcSizeBinary (const UA_BrowsePath * src) static
Definition at line 1961 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_BrowsePath_decodeBinary()
static UA_INLINE UA_StatusCode UA_BrowsePath_decodeBinary (const UA_ByteString * src, size_t * offset, UA_BrowsePath * dst) static
Definition at line 1969 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_BrowsePath_encodeBinary()
static UA_INLINE UA_StatusCode UA_BrowsePath_encodeBinary (const UA_BrowsePath * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 1965 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_BrowsePathResult_calcSizeBinary()
static UA_INLINE size_t UA_BrowsePathResult_calcSizeBinary (const UA_BrowsePathResult * src) static
Definition at line 2325 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_BrowsePathResult_decodeBinary()
static UA_INLINE UA_StatusCode UA_BrowsePathResult_decodeBinary (const UA_ByteString * src, size_t * offset, UA_BrowsePathResult * dst) static
Definition at line 2333 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_BrowsePathResult_encodeBinary()
static UA_INLINE UA_StatusCode UA_BrowsePathResult_encodeBinary (const UA_BrowsePathResult * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 2329 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_BrowsePathTarget_calcSizeBinary()
static UA_INLINE size_t UA_BrowsePathTarget_calcSizeBinary (const UA_BrowsePathTarget * src) static
Definition at line 1037 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_BrowsePathTarget_decodeBinary()
static UA_INLINE UA_StatusCode UA_BrowsePathTarget_decodeBinary (const UA_ByteString * src, size_t * offset, UA_BrowsePathTarget * dst) static
Definition at line 1045 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_BrowsePathTarget_encodeBinary()
static UA_INLINE UA_StatusCode UA_BrowsePathTarget_encodeBinary (const UA_BrowsePathTarget * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 1041 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_BrowseRequest_calcSizeBinary()
static UA_INLINE size_t UA_BrowseRequest_calcSizeBinary (const UA_BrowseRequest * src) static
Definition at line 2353 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_BrowseRequest_decodeBinary()
static UA_INLINE UA_StatusCode UA_BrowseRequest_decodeBinary (const UA_ByteString * src, size_t * offset, UA_BrowseRequest * dst) static
Definition at line 2361 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_BrowseRequest_encodeBinary()
static UA_INLINE UA_StatusCode UA_BrowseRequest_encodeBinary (const UA_BrowseRequest * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 2357 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_BrowseResponse_calcSizeBinary()
static UA_INLINE size_t UA_BrowseResponse_calcSizeBinary (const UA_BrowseResponse * src) static
Definition at line 2549 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_BrowseResponse_decodeBinary()
static UA_INLINE UA_StatusCode UA_BrowseResponse_decodeBinary (const UA_ByteString * src, size_t * offset, UA_BrowseResponse * dst) static
Definition at line 2557 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_BrowseResponse_encodeBinary()
static UA_INLINE UA_StatusCode UA_BrowseResponse_encodeBinary (const UA_BrowseResponse * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 2553 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_BrowseResult_calcSizeBinary()
static UA_INLINE size_t UA_BrowseResult_calcSizeBinary (const UA_BrowseResult * src) static
Definition at line 2199 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_BrowseResult_decodeBinary()
static UA_INLINE UA_StatusCode UA_BrowseResult_decodeBinary (const UA_ByteString * src, size_t * offset, UA_BrowseResult * dst) static
Definition at line 2207 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_BrowseResult_encodeBinary()
static UA_INLINE UA_StatusCode UA_BrowseResult_encodeBinary (const UA_BrowseResult * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 2203 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_BrowseResultMask_calcSizeBinary()
static UA_INLINE size_t UA_BrowseResultMask_calcSizeBinary (const UA_BrowseResultMask * src) static
Definition at line 687 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_BrowseResultMask_decodeBinary()
static UA_INLINE UA_StatusCode UA_BrowseResultMask_decodeBinary (const UA_ByteString * src, size_t * offset, UA_BrowseResultMask * dst) static
Definition at line 695 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_BrowseResultMask_encodeBinary()
static UA_INLINE UA_StatusCode UA_BrowseResultMask_encodeBinary (const UA_BrowseResultMask * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 691 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_BuildInfo_calcSizeBinary()
static UA_INLINE size_t UA_BuildInfo_calcSizeBinary (const UA_BuildInfo * src) static
Definition at line 1261 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_BuildInfo_decodeBinary()
static UA_INLINE UA_StatusCode UA_BuildInfo_decodeBinary (const UA_ByteString * src, size_t * offset, UA_BuildInfo * dst) static
Definition at line 1269 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_BuildInfo_encodeBinary()
static UA_INLINE UA_StatusCode UA_BuildInfo_encodeBinary (const UA_BuildInfo * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 1265 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_Byte_calcSizeBinary()
static UA_INLINE size_t UA_Byte_calcSizeBinary (const UA_Byte * src) static
Definition at line 43 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_Byte_decodeBinary()
static UA_INLINE UA_StatusCode UA_Byte_decodeBinary (const UA_ByteString * src, size_t * offset, UA_Byte * dst) static
Definition at line 51 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_Byte_encodeBinary()
static UA_INLINE UA_StatusCode UA_Byte_encodeBinary (const UA_Byte * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 47 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_ByteString_calcSizeBinary()
static UA_INLINE size_t UA_ByteString_calcSizeBinary (const UA_ByteString * src) static
Definition at line 211 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_ByteString_decodeBinary()
static UA_INLINE UA_StatusCode UA_ByteString_decodeBinary (const UA_ByteString * src, size_t * offset, UA_ByteString * dst) static
Definition at line 219 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_ByteString_encodeBinary()
static UA_INLINE UA_StatusCode UA_ByteString_encodeBinary (const UA_ByteString * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 215 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_CallMethodRequest_calcSizeBinary()
static UA_INLINE size_t UA_CallMethodRequest_calcSizeBinary (const UA_CallMethodRequest * src) static
Definition at line 799 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_CallMethodRequest_decodeBinary()
static UA_INLINE UA_StatusCode UA_CallMethodRequest_decodeBinary (const UA_ByteString * src, size_t * offset, UA_CallMethodRequest * dst) static
Definition at line 807 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_CallMethodRequest_encodeBinary()
static UA_INLINE UA_StatusCode UA_CallMethodRequest_encodeBinary (const UA_CallMethodRequest * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 803 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_CallMethodResult_calcSizeBinary()
static UA_INLINE size_t UA_CallMethodResult_calcSizeBinary (const UA_CallMethodResult * src) static
Definition at line 645 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_CallMethodResult_decodeBinary()
static UA_INLINE UA_StatusCode UA_CallMethodResult_decodeBinary (const UA_ByteString * src, size_t * offset, UA_CallMethodResult * dst) static
Definition at line 653 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_CallMethodResult_encodeBinary()
static UA_INLINE UA_StatusCode UA_CallMethodResult_encodeBinary (const UA_CallMethodResult * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 649 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_CallRequest_calcSizeBinary()
static UA_INLINE size_t UA_CallRequest_calcSizeBinary (const UA_CallRequest * src) static
Definition at line 1331 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_CallRequest_decodeBinary()
static UA_INLINE UA_StatusCode UA_CallRequest_decodeBinary (const UA_ByteString * src, size_t * offset, UA_CallRequest * dst) static
Definition at line 1339 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_CallRequest_encodeBinary()
static UA_INLINE UA_StatusCode UA_CallRequest_encodeBinary (const UA_CallRequest * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 1335 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_CallResponse_calcSizeBinary()
static UA_INLINE size_t UA_CallResponse_calcSizeBinary (const UA_CallResponse * src) static
Definition at line 2073 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_CallResponse_decodeBinary()
static UA_INLINE UA_StatusCode UA_CallResponse_decodeBinary (const UA_ByteString * src, size_t * offset, UA_CallResponse * dst) static
Definition at line 2081 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_CallResponse_encodeBinary()
static UA_INLINE UA_StatusCode UA_CallResponse_encodeBinary (const UA_CallResponse * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 2077 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_ChannelSecurityToken_calcSizeBinary()
static UA_INLINE size_t UA_ChannelSecurityToken_calcSizeBinary (const UA_ChannelSecurityToken * src) static
Definition at line 1681 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_ChannelSecurityToken_decodeBinary()
static UA_INLINE UA_StatusCode UA_ChannelSecurityToken_decodeBinary (const UA_ByteString * src, size_t * offset, UA_ChannelSecurityToken * dst) static
Definition at line 1689 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_ChannelSecurityToken_encodeBinary()
static UA_INLINE UA_StatusCode UA_ChannelSecurityToken_encodeBinary (const UA_ChannelSecurityToken * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 1685 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_CloseSecureChannelRequest_calcSizeBinary()
static UA_INLINE size_t UA_CloseSecureChannelRequest_calcSizeBinary (const UA_CloseSecureChannelRequest * src) static
Definition at line 729 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_CloseSecureChannelRequest_decodeBinary()
static UA_INLINE UA_StatusCode UA_CloseSecureChannelRequest_decodeBinary (const UA_ByteString * src, size_t * offset, UA_CloseSecureChannelRequest * dst) static
Definition at line 737 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_CloseSecureChannelRequest_encodeBinary()
static UA_INLINE UA_StatusCode UA_CloseSecureChannelRequest_encodeBinary (const UA_CloseSecureChannelRequest * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 733 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_CloseSecureChannelResponse_calcSizeBinary()
static UA_INLINE size_t UA_CloseSecureChannelResponse_calcSizeBinary (const UA_CloseSecureChannelResponse * src) static
Definition at line 1541 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_CloseSecureChannelResponse_decodeBinary()
static UA_INLINE UA_StatusCode UA_CloseSecureChannelResponse_decodeBinary (const UA_ByteString * src, size_t * offset, UA_CloseSecureChannelResponse * dst) static
Definition at line 1549 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_CloseSecureChannelResponse_encodeBinary()
static UA_INLINE UA_StatusCode UA_CloseSecureChannelResponse_encodeBinary (const UA_CloseSecureChannelResponse * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 1545 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_CloseSessionRequest_calcSizeBinary()
static UA_INLINE size_t UA_CloseSessionRequest_calcSizeBinary (const UA_CloseSessionRequest * src) static
Definition at line 2171 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_CloseSessionRequest_decodeBinary()
static UA_INLINE UA_StatusCode UA_CloseSessionRequest_decodeBinary (const UA_ByteString * src, size_t * offset, UA_CloseSessionRequest * dst) static
Definition at line 2179 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_CloseSessionRequest_encodeBinary()
static UA_INLINE UA_StatusCode UA_CloseSessionRequest_encodeBinary (const UA_CloseSessionRequest * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 2175 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_CloseSessionResponse_calcSizeBinary()
static UA_INLINE size_t UA_CloseSessionResponse_calcSizeBinary (const UA_CloseSessionResponse * src) static
Definition at line 883 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_CloseSessionResponse_decodeBinary()
static UA_INLINE UA_StatusCode UA_CloseSessionResponse_decodeBinary (const UA_ByteString * src, size_t * offset, UA_CloseSessionResponse * dst) static
Definition at line 891 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_CloseSessionResponse_encodeBinary()
static UA_INLINE UA_StatusCode UA_CloseSessionResponse_encodeBinary (const UA_CloseSessionResponse * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 887 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_ContentFilter_calcSizeBinary()
static UA_INLINE size_t UA_ContentFilter_calcSizeBinary (const UA_ContentFilter * src) static
Definition at line 2577 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_ContentFilter_decodeBinary()
static UA_INLINE UA_StatusCode UA_ContentFilter_decodeBinary (const UA_ByteString * src, size_t * offset, UA_ContentFilter * dst) static
Definition at line 2585 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_ContentFilter_encodeBinary()
static UA_INLINE UA_StatusCode UA_ContentFilter_encodeBinary (const UA_ContentFilter * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 2581 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_ContentFilterElement_calcSizeBinary()
static UA_INLINE size_t UA_ContentFilterElement_calcSizeBinary (const UA_ContentFilterElement * src) static
Definition at line 2507 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_ContentFilterElement_decodeBinary()
static UA_INLINE UA_StatusCode UA_ContentFilterElement_decodeBinary (const UA_ByteString * src, size_t * offset, UA_ContentFilterElement * dst) static
Definition at line 2515 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_ContentFilterElement_encodeBinary()
static UA_INLINE UA_StatusCode UA_ContentFilterElement_encodeBinary (const UA_ContentFilterElement * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 2511 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_ContentFilterElementResult_calcSizeBinary()
static UA_INLINE size_t UA_ContentFilterElementResult_calcSizeBinary (const UA_ContentFilterElementResult * src) static
Definition at line 463 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_ContentFilterElementResult_decodeBinary()
static UA_INLINE UA_StatusCode UA_ContentFilterElementResult_decodeBinary (const UA_ByteString * src, size_t * offset, UA_ContentFilterElementResult * dst) static
Definition at line 471 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_ContentFilterElementResult_encodeBinary()
static UA_INLINE UA_StatusCode UA_ContentFilterElementResult_encodeBinary (const UA_ContentFilterElementResult * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 467 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_ContentFilterResult_calcSizeBinary()
static UA_INLINE size_t UA_ContentFilterResult_calcSizeBinary (const UA_ContentFilterResult * src) static
Definition at line 1443 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_ContentFilterResult_decodeBinary()
static UA_INLINE UA_StatusCode UA_ContentFilterResult_decodeBinary (const UA_ByteString * src, size_t * offset, UA_ContentFilterResult * dst) static
Definition at line 1451 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_ContentFilterResult_encodeBinary()
static UA_INLINE UA_StatusCode UA_ContentFilterResult_encodeBinary (const UA_ContentFilterResult * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 1447 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_CreateMonitoredItemsRequest_calcSizeBinary()
static UA_INLINE size_t UA_CreateMonitoredItemsRequest_calcSizeBinary (const UA_CreateMonitoredItemsRequest * src) static
Definition at line 2143 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_CreateMonitoredItemsRequest_decodeBinary()
static UA_INLINE UA_StatusCode UA_CreateMonitoredItemsRequest_decodeBinary (const UA_ByteString * src, size_t * offset, UA_CreateMonitoredItemsRequest * dst) static
Definition at line 2151 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_CreateMonitoredItemsRequest_encodeBinary()
static UA_INLINE UA_StatusCode UA_CreateMonitoredItemsRequest_encodeBinary (const UA_CreateMonitoredItemsRequest * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 2147 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_CreateMonitoredItemsResponse_calcSizeBinary()
static UA_INLINE size_t UA_CreateMonitoredItemsResponse_calcSizeBinary (const UA_CreateMonitoredItemsResponse * src) static
Definition at line 1163 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_CreateMonitoredItemsResponse_decodeBinary()
static UA_INLINE UA_StatusCode UA_CreateMonitoredItemsResponse_decodeBinary (const UA_ByteString * src, size_t * offset, UA_CreateMonitoredItemsResponse * dst) static
Definition at line 1171 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_CreateMonitoredItemsResponse_encodeBinary()
static UA_INLINE UA_StatusCode UA_CreateMonitoredItemsResponse_encodeBinary (const UA_CreateMonitoredItemsResponse * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 1167 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_CreateSessionRequest_calcSizeBinary()
static UA_INLINE size_t UA_CreateSessionRequest_calcSizeBinary (const UA_CreateSessionRequest * src) static
Definition at line 2493 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_CreateSessionRequest_decodeBinary()
static UA_INLINE UA_StatusCode UA_CreateSessionRequest_decodeBinary (const UA_ByteString * src, size_t * offset, UA_CreateSessionRequest * dst) static
Definition at line 2501 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_CreateSessionRequest_encodeBinary()
static UA_INLINE UA_StatusCode UA_CreateSessionRequest_encodeBinary (const UA_CreateSessionRequest * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 2497 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_CreateSessionResponse_calcSizeBinary()
static UA_INLINE size_t UA_CreateSessionResponse_calcSizeBinary (const UA_CreateSessionResponse * src) static
Definition at line 2563 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_CreateSessionResponse_decodeBinary()
static UA_INLINE UA_StatusCode UA_CreateSessionResponse_decodeBinary (const UA_ByteString * src, size_t * offset, UA_CreateSessionResponse * dst) static
Definition at line 2571 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_CreateSessionResponse_encodeBinary()
static UA_INLINE UA_StatusCode UA_CreateSessionResponse_encodeBinary (const UA_CreateSessionResponse * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 2567 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_CreateSubscriptionRequest_calcSizeBinary()
static UA_INLINE size_t UA_CreateSubscriptionRequest_calcSizeBinary (const UA_CreateSubscriptionRequest * src) static
Definition at line 2045 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_CreateSubscriptionRequest_decodeBinary()
static UA_INLINE UA_StatusCode UA_CreateSubscriptionRequest_decodeBinary (const UA_ByteString * src, size_t * offset, UA_CreateSubscriptionRequest * dst) static
Definition at line 2053 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_CreateSubscriptionRequest_encodeBinary()
static UA_INLINE UA_StatusCode UA_CreateSubscriptionRequest_encodeBinary (const UA_CreateSubscriptionRequest * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 2049 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_CreateSubscriptionResponse_calcSizeBinary()
static UA_INLINE size_t UA_CreateSubscriptionResponse_calcSizeBinary (const UA_CreateSubscriptionResponse * src) static
Definition at line 757 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_CreateSubscriptionResponse_decodeBinary()
static UA_INLINE UA_StatusCode UA_CreateSubscriptionResponse_decodeBinary (const UA_ByteString * src, size_t * offset, UA_CreateSubscriptionResponse * dst) static
Definition at line 765 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_CreateSubscriptionResponse_encodeBinary()
static UA_INLINE UA_StatusCode UA_CreateSubscriptionResponse_encodeBinary (const UA_CreateSubscriptionResponse * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 761 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_DataChangeFilter_calcSizeBinary()
static UA_INLINE size_t UA_DataChangeFilter_calcSizeBinary (const UA_DataChangeFilter * src) static
Definition at line 2423 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_DataChangeFilter_decodeBinary()
static UA_INLINE UA_StatusCode UA_DataChangeFilter_decodeBinary (const UA_ByteString * src, size_t * offset, UA_DataChangeFilter * dst) static
Definition at line 2431 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_DataChangeFilter_encodeBinary()
static UA_INLINE UA_StatusCode UA_DataChangeFilter_encodeBinary (const UA_DataChangeFilter * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 2427 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_DataChangeNotification_calcSizeBinary()
static UA_INLINE size_t UA_DataChangeNotification_calcSizeBinary (const UA_DataChangeNotification * src) static
Definition at line 1653 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_DataChangeNotification_decodeBinary()
static UA_INLINE UA_StatusCode UA_DataChangeNotification_decodeBinary (const UA_ByteString * src, size_t * offset, UA_DataChangeNotification * dst) static
Definition at line 1661 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_DataChangeNotification_encodeBinary()
static UA_INLINE UA_StatusCode UA_DataChangeNotification_encodeBinary (const UA_DataChangeNotification * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 1657 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_DataChangeTrigger_calcSizeBinary()
static UA_INLINE size_t UA_DataChangeTrigger_calcSizeBinary (const UA_DataChangeTrigger * src) static
Definition at line 1247 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_DataChangeTrigger_decodeBinary()
static UA_INLINE UA_StatusCode UA_DataChangeTrigger_decodeBinary (const UA_ByteString * src, size_t * offset, UA_DataChangeTrigger * dst) static
Definition at line 1255 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_DataChangeTrigger_encodeBinary()
static UA_INLINE UA_StatusCode UA_DataChangeTrigger_encodeBinary (const UA_DataChangeTrigger * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 1251 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_DataTypeAttributes_calcSizeBinary()
static UA_INLINE size_t UA_DataTypeAttributes_calcSizeBinary (const UA_DataTypeAttributes * src) static
Definition at line 1205 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_DataTypeAttributes_decodeBinary()
static UA_INLINE UA_StatusCode UA_DataTypeAttributes_decodeBinary (const UA_ByteString * src, size_t * offset, UA_DataTypeAttributes * dst) static
Definition at line 1213 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_DataTypeAttributes_encodeBinary()
static UA_INLINE UA_StatusCode UA_DataTypeAttributes_encodeBinary (const UA_DataTypeAttributes * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 1209 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_DataValue_calcSizeBinary()
static UA_INLINE size_t UA_DataValue_calcSizeBinary (const UA_DataValue * src) static
Definition at line 323 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_DataValue_decodeBinary()
static UA_INLINE UA_StatusCode UA_DataValue_decodeBinary (const UA_ByteString * src, size_t * offset, UA_DataValue * dst) static
Definition at line 331 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_DataValue_encodeBinary()
static UA_INLINE UA_StatusCode UA_DataValue_encodeBinary (const UA_DataValue * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 327 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_DateTime_calcSizeBinary()
static UA_INLINE size_t UA_DateTime_calcSizeBinary (const UA_DateTime * src) static
Definition at line 183 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_DateTime_decodeBinary()
static UA_INLINE UA_StatusCode UA_DateTime_decodeBinary (const UA_ByteString * src, size_t * offset, UA_DateTime * dst) static
Definition at line 191 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_DateTime_encodeBinary()
static UA_INLINE UA_StatusCode UA_DateTime_encodeBinary (const UA_DateTime * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 187 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_DeadbandType_calcSizeBinary()
static UA_INLINE size_t UA_DeadbandType_calcSizeBinary (const UA_DeadbandType * src) static
Definition at line 1233 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_DeadbandType_decodeBinary()
static UA_INLINE UA_StatusCode UA_DeadbandType_decodeBinary (const UA_ByteString * src, size_t * offset, UA_DeadbandType * dst) static
Definition at line 1241 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_DeadbandType_encodeBinary()
static UA_INLINE UA_StatusCode UA_DeadbandType_encodeBinary (const UA_DeadbandType * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 1237 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_DeleteMonitoredItemsRequest_calcSizeBinary()
static UA_INLINE size_t UA_DeleteMonitoredItemsRequest_calcSizeBinary (const UA_DeleteMonitoredItemsRequest * src) static
Definition at line 1471 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_DeleteMonitoredItemsRequest_decodeBinary()
static UA_INLINE UA_StatusCode UA_DeleteMonitoredItemsRequest_decodeBinary (const UA_ByteString * src, size_t * offset, UA_DeleteMonitoredItemsRequest * dst) static
Definition at line 1479 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_DeleteMonitoredItemsRequest_encodeBinary()
static UA_INLINE UA_StatusCode UA_DeleteMonitoredItemsRequest_encodeBinary (const UA_DeleteMonitoredItemsRequest * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 1475 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_DeleteMonitoredItemsResponse_calcSizeBinary()
static UA_INLINE size_t UA_DeleteMonitoredItemsResponse_calcSizeBinary (const UA_DeleteMonitoredItemsResponse * src) static
Definition at line 939 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_DeleteMonitoredItemsResponse_decodeBinary()
static UA_INLINE UA_StatusCode UA_DeleteMonitoredItemsResponse_decodeBinary (const UA_ByteString * src, size_t * offset, UA_DeleteMonitoredItemsResponse * dst) static
Definition at line 947 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_DeleteMonitoredItemsResponse_encodeBinary()
static UA_INLINE UA_StatusCode UA_DeleteMonitoredItemsResponse_encodeBinary (const UA_DeleteMonitoredItemsResponse * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 943 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_DeleteNodesItem_calcSizeBinary()
static UA_INLINE size_t UA_DeleteNodesItem_calcSizeBinary (const UA_DeleteNodesItem * src) static
Definition at line 1303 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_DeleteNodesItem_decodeBinary()
static UA_INLINE UA_StatusCode UA_DeleteNodesItem_decodeBinary (const UA_ByteString * src, size_t * offset, UA_DeleteNodesItem * dst) static
Definition at line 1311 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_DeleteNodesItem_encodeBinary()
static UA_INLINE UA_StatusCode UA_DeleteNodesItem_encodeBinary (const UA_DeleteNodesItem * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 1307 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_DeleteNodesRequest_calcSizeBinary()
static UA_INLINE size_t UA_DeleteNodesRequest_calcSizeBinary (const UA_DeleteNodesRequest * src) static
Definition at line 1359 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_DeleteNodesRequest_decodeBinary()
static UA_INLINE UA_StatusCode UA_DeleteNodesRequest_decodeBinary (const UA_ByteString * src, size_t * offset, UA_DeleteNodesRequest * dst) static
Definition at line 1367 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_DeleteNodesRequest_encodeBinary()
static UA_INLINE UA_StatusCode UA_DeleteNodesRequest_encodeBinary (const UA_DeleteNodesRequest * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 1363 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_DeleteNodesResponse_calcSizeBinary()
static UA_INLINE size_t UA_DeleteNodesResponse_calcSizeBinary (const UA_DeleteNodesResponse * src) static
Definition at line 2087 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_DeleteNodesResponse_decodeBinary()
static UA_INLINE UA_StatusCode UA_DeleteNodesResponse_decodeBinary (const UA_ByteString * src, size_t * offset, UA_DeleteNodesResponse * dst) static
Definition at line 2095 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_DeleteNodesResponse_encodeBinary()
static UA_INLINE UA_StatusCode UA_DeleteNodesResponse_encodeBinary (const UA_DeleteNodesResponse * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 2091 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_DeleteReferencesItem_calcSizeBinary()
static UA_INLINE size_t UA_DeleteReferencesItem_calcSizeBinary (const UA_DeleteReferencesItem * src) static
Definition at line 1177 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_DeleteReferencesItem_decodeBinary()
static UA_INLINE UA_StatusCode UA_DeleteReferencesItem_decodeBinary (const UA_ByteString * src, size_t * offset, UA_DeleteReferencesItem * dst) static
Definition at line 1185 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_DeleteReferencesItem_encodeBinary()
static UA_INLINE UA_StatusCode UA_DeleteReferencesItem_encodeBinary (const UA_DeleteReferencesItem * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 1181 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_DeleteReferencesRequest_calcSizeBinary()
static UA_INLINE size_t UA_DeleteReferencesRequest_calcSizeBinary (const UA_DeleteReferencesRequest * src) static
Definition at line 2451 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_DeleteReferencesRequest_decodeBinary()
static UA_INLINE UA_StatusCode UA_DeleteReferencesRequest_decodeBinary (const UA_ByteString * src, size_t * offset, UA_DeleteReferencesRequest * dst) static
Definition at line 2459 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_DeleteReferencesRequest_encodeBinary()
static UA_INLINE UA_StatusCode UA_DeleteReferencesRequest_encodeBinary (const UA_DeleteReferencesRequest * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 2455 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_DeleteReferencesResponse_calcSizeBinary()
static UA_INLINE size_t UA_DeleteReferencesResponse_calcSizeBinary (const UA_DeleteReferencesResponse * src) static
Definition at line 1121 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_DeleteReferencesResponse_decodeBinary()
static UA_INLINE UA_StatusCode UA_DeleteReferencesResponse_decodeBinary (const UA_ByteString * src, size_t * offset, UA_DeleteReferencesResponse * dst) static
Definition at line 1129 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_DeleteReferencesResponse_encodeBinary()
static UA_INLINE UA_StatusCode UA_DeleteReferencesResponse_encodeBinary (const UA_DeleteReferencesResponse * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 1125 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_DeleteSubscriptionsRequest_calcSizeBinary()
static UA_INLINE size_t UA_DeleteSubscriptionsRequest_calcSizeBinary (const UA_DeleteSubscriptionsRequest * src) static
Definition at line 1933 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_DeleteSubscriptionsRequest_decodeBinary()
static UA_INLINE UA_StatusCode UA_DeleteSubscriptionsRequest_decodeBinary (const UA_ByteString * src, size_t * offset, UA_DeleteSubscriptionsRequest * dst) static
Definition at line 1941 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_DeleteSubscriptionsRequest_encodeBinary()
static UA_INLINE UA_StatusCode UA_DeleteSubscriptionsRequest_encodeBinary (const UA_DeleteSubscriptionsRequest * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 1937 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_DeleteSubscriptionsResponse_calcSizeBinary()
static UA_INLINE size_t UA_DeleteSubscriptionsResponse_calcSizeBinary (const UA_DeleteSubscriptionsResponse * src) static
Definition at line 1779 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_DeleteSubscriptionsResponse_decodeBinary()
static UA_INLINE UA_StatusCode UA_DeleteSubscriptionsResponse_decodeBinary (const UA_ByteString * src, size_t * offset, UA_DeleteSubscriptionsResponse * dst) static
Definition at line 1787 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_DeleteSubscriptionsResponse_encodeBinary()
static UA_INLINE UA_StatusCode UA_DeleteSubscriptionsResponse_encodeBinary (const UA_DeleteSubscriptionsResponse * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 1783 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_DiagnosticInfo_calcSizeBinary()
static UA_INLINE size_t UA_DiagnosticInfo_calcSizeBinary (const UA_DiagnosticInfo * src) static
Definition at line 351 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_DiagnosticInfo_decodeBinary()
static UA_INLINE UA_StatusCode UA_DiagnosticInfo_decodeBinary (const UA_ByteString * src, size_t * offset, UA_DiagnosticInfo * dst) static
Definition at line 359 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_DiagnosticInfo_encodeBinary()
static UA_INLINE UA_StatusCode UA_DiagnosticInfo_encodeBinary (const UA_DiagnosticInfo * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 355 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_DiscoveryConfiguration_calcSizeBinary()
static UA_INLINE size_t UA_DiscoveryConfiguration_calcSizeBinary (const UA_DiscoveryConfiguration * src) static
Definition at line 967 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_DiscoveryConfiguration_decodeBinary()
static UA_INLINE UA_StatusCode UA_DiscoveryConfiguration_decodeBinary (const UA_ByteString * src, size_t * offset, UA_DiscoveryConfiguration * dst) static
Definition at line 975 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_DiscoveryConfiguration_encodeBinary()
static UA_INLINE UA_StatusCode UA_DiscoveryConfiguration_encodeBinary (const UA_DiscoveryConfiguration * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 971 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_Double_calcSizeBinary()
static UA_INLINE size_t UA_Double_calcSizeBinary (const UA_Double * src) static
Definition at line 155 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_Double_decodeBinary()
static UA_INLINE UA_StatusCode UA_Double_decodeBinary (const UA_ByteString * src, size_t * offset, UA_Double * dst) static
Definition at line 163 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_Double_encodeBinary()
static UA_INLINE UA_StatusCode UA_Double_encodeBinary (const UA_Double * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 159 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_Duration_calcSizeBinary()
static UA_INLINE size_t UA_Duration_calcSizeBinary (const UA_Duration * src) static
Definition at line 1499 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_Duration_decodeBinary()
static UA_INLINE UA_StatusCode UA_Duration_decodeBinary (const UA_ByteString * src, size_t * offset, UA_Duration * dst) static
Definition at line 1507 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_Duration_encodeBinary()
static UA_INLINE UA_StatusCode UA_Duration_encodeBinary (const UA_Duration * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 1503 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_ElementOperand_calcSizeBinary()
static UA_INLINE size_t UA_ElementOperand_calcSizeBinary (const UA_ElementOperand * src) static
Definition at line 379 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_ElementOperand_decodeBinary()
static UA_INLINE UA_StatusCode UA_ElementOperand_decodeBinary (const UA_ByteString * src, size_t * offset, UA_ElementOperand * dst) static
Definition at line 387 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_ElementOperand_encodeBinary()
static UA_INLINE UA_StatusCode UA_ElementOperand_encodeBinary (const UA_ElementOperand * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 383 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_EndpointDescription_calcSizeBinary()
static UA_INLINE size_t UA_EndpointDescription_calcSizeBinary (const UA_EndpointDescription * src) static
Definition at line 2437 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_EndpointDescription_decodeBinary()
static UA_INLINE UA_StatusCode UA_EndpointDescription_decodeBinary (const UA_ByteString * src, size_t * offset, UA_EndpointDescription * dst) static
Definition at line 2445 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_EndpointDescription_encodeBinary()
static UA_INLINE UA_StatusCode UA_EndpointDescription_encodeBinary (const UA_EndpointDescription * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 2441 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_EnumValueType_calcSizeBinary()
static UA_INLINE size_t UA_EnumValueType_calcSizeBinary (const UA_EnumValueType * src) static
Definition at line 407 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_EnumValueType_decodeBinary()
static UA_INLINE UA_StatusCode UA_EnumValueType_decodeBinary (const UA_ByteString * src, size_t * offset, UA_EnumValueType * dst) static
Definition at line 415 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_EnumValueType_encodeBinary()
static UA_INLINE UA_StatusCode UA_EnumValueType_encodeBinary (const UA_EnumValueType * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 411 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_EventFieldList_calcSizeBinary()
static UA_INLINE size_t UA_EventFieldList_calcSizeBinary (const UA_EventFieldList * src) static
Definition at line 421 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_EventFieldList_decodeBinary()
static UA_INLINE UA_StatusCode UA_EventFieldList_decodeBinary (const UA_ByteString * src, size_t * offset, UA_EventFieldList * dst) static
Definition at line 429 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_EventFieldList_encodeBinary()
static UA_INLINE UA_StatusCode UA_EventFieldList_encodeBinary (const UA_EventFieldList * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 425 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_EventFilter_calcSizeBinary()
static UA_INLINE size_t UA_EventFilter_calcSizeBinary (const UA_EventFilter * src) static
Definition at line 2605 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_EventFilter_decodeBinary()
static UA_INLINE UA_StatusCode UA_EventFilter_decodeBinary (const UA_ByteString * src, size_t * offset, UA_EventFilter * dst) static
Definition at line 2613 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_EventFilter_encodeBinary()
static UA_INLINE UA_StatusCode UA_EventFilter_encodeBinary (const UA_EventFilter * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 2609 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_EventFilterResult_calcSizeBinary()
static UA_INLINE size_t UA_EventFilterResult_calcSizeBinary (const UA_EventFilterResult * src) static
Definition at line 1611 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_EventFilterResult_decodeBinary()
static UA_INLINE UA_StatusCode UA_EventFilterResult_decodeBinary (const UA_ByteString * src, size_t * offset, UA_EventFilterResult * dst) static
Definition at line 1619 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_EventFilterResult_encodeBinary()
static UA_INLINE UA_StatusCode UA_EventFilterResult_encodeBinary (const UA_EventFilterResult * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 1615 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_EventNotificationList_calcSizeBinary()
static UA_INLINE size_t UA_EventNotificationList_calcSizeBinary (const UA_EventNotificationList * src) static
Definition at line 1709 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_EventNotificationList_decodeBinary()
static UA_INLINE UA_StatusCode UA_EventNotificationList_decodeBinary (const UA_ByteString * src, size_t * offset, UA_EventNotificationList * dst) static
Definition at line 1717 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_EventNotificationList_encodeBinary()
static UA_INLINE UA_StatusCode UA_EventNotificationList_encodeBinary (const UA_EventNotificationList * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 1713 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_ExpandedNodeId_calcSizeBinary()
static UA_INLINE size_t UA_ExpandedNodeId_calcSizeBinary (const UA_ExpandedNodeId * src) static
Definition at line 253 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_ExpandedNodeId_decodeBinary()
static UA_INLINE UA_StatusCode UA_ExpandedNodeId_decodeBinary (const UA_ByteString * src, size_t * offset, UA_ExpandedNodeId * dst) static
Definition at line 261 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_ExpandedNodeId_encodeBinary()
static UA_INLINE UA_StatusCode UA_ExpandedNodeId_encodeBinary (const UA_ExpandedNodeId * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 257 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_ExtensionObject_calcSizeBinary()
static UA_INLINE size_t UA_ExtensionObject_calcSizeBinary (const UA_ExtensionObject * src) static
Definition at line 309 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_ExtensionObject_decodeBinary()
static UA_INLINE UA_StatusCode UA_ExtensionObject_decodeBinary (const UA_ByteString * src, size_t * offset, UA_ExtensionObject * dst) static
Definition at line 317 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_ExtensionObject_encodeBinary()
static UA_INLINE UA_StatusCode UA_ExtensionObject_encodeBinary (const UA_ExtensionObject * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 313 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_FilterOperand_calcSizeBinary()
static UA_INLINE size_t UA_FilterOperand_calcSizeBinary (const UA_FilterOperand * src) static
Definition at line 1275 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_FilterOperand_decodeBinary()
static UA_INLINE UA_StatusCode UA_FilterOperand_decodeBinary (const UA_ByteString * src, size_t * offset, UA_FilterOperand * dst) static
Definition at line 1283 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_FilterOperand_encodeBinary()
static UA_INLINE UA_StatusCode UA_FilterOperand_encodeBinary (const UA_FilterOperand * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 1279 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_FilterOperator_calcSizeBinary()
static UA_INLINE size_t UA_FilterOperator_calcSizeBinary (const UA_FilterOperator * src) static
Definition at line 1737 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_FilterOperator_decodeBinary()
static UA_INLINE UA_StatusCode UA_FilterOperator_decodeBinary (const UA_ByteString * src, size_t * offset, UA_FilterOperator * dst) static
Definition at line 1745 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_FilterOperator_encodeBinary()
static UA_INLINE UA_StatusCode UA_FilterOperator_encodeBinary (const UA_FilterOperator * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 1741 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_FindServersOnNetworkRequest_calcSizeBinary()
static UA_INLINE size_t UA_FindServersOnNetworkRequest_calcSizeBinary (const UA_FindServersOnNetworkRequest * src) static
Definition at line 2059 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_FindServersOnNetworkRequest_decodeBinary()
static UA_INLINE UA_StatusCode UA_FindServersOnNetworkRequest_decodeBinary (const UA_ByteString * src, size_t * offset, UA_FindServersOnNetworkRequest * dst) static
Definition at line 2067 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_FindServersOnNetworkRequest_encodeBinary()
static UA_INLINE UA_StatusCode UA_FindServersOnNetworkRequest_encodeBinary (const UA_FindServersOnNetworkRequest * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 2063 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_FindServersOnNetworkResponse_calcSizeBinary()
static UA_INLINE size_t UA_FindServersOnNetworkResponse_calcSizeBinary (const UA_FindServersOnNetworkResponse * src) static
Definition at line 2017 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_FindServersOnNetworkResponse_decodeBinary()
static UA_INLINE UA_StatusCode UA_FindServersOnNetworkResponse_decodeBinary (const UA_ByteString * src, size_t * offset, UA_FindServersOnNetworkResponse * dst) static
Definition at line 2025 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_FindServersOnNetworkResponse_encodeBinary()
static UA_INLINE UA_StatusCode UA_FindServersOnNetworkResponse_encodeBinary (const UA_FindServersOnNetworkResponse * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 2021 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_FindServersRequest_calcSizeBinary()
static UA_INLINE size_t UA_FindServersRequest_calcSizeBinary (const UA_FindServersRequest * src) static
Definition at line 2003 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_FindServersRequest_decodeBinary()
static UA_INLINE UA_StatusCode UA_FindServersRequest_decodeBinary (const UA_ByteString * src, size_t * offset, UA_FindServersRequest * dst) static
Definition at line 2011 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_FindServersRequest_encodeBinary()
static UA_INLINE UA_StatusCode UA_FindServersRequest_encodeBinary (const UA_FindServersRequest * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 2007 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_FindServersResponse_calcSizeBinary()
static UA_INLINE size_t UA_FindServersResponse_calcSizeBinary (const UA_FindServersResponse * src) static
Definition at line 2479 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_FindServersResponse_decodeBinary()
static UA_INLINE UA_StatusCode UA_FindServersResponse_decodeBinary (const UA_ByteString * src, size_t * offset, UA_FindServersResponse * dst) static
Definition at line 2487 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_FindServersResponse_encodeBinary()
static UA_INLINE UA_StatusCode UA_FindServersResponse_encodeBinary (const UA_FindServersResponse * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 2483 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_Float_calcSizeBinary()
static UA_INLINE size_t UA_Float_calcSizeBinary (const UA_Float * src) static
Definition at line 141 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_Float_decodeBinary()
static UA_INLINE UA_StatusCode UA_Float_decodeBinary (const UA_ByteString * src, size_t * offset, UA_Float * dst) static
Definition at line 149 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_Float_encodeBinary()
static UA_INLINE UA_StatusCode UA_Float_encodeBinary (const UA_Float * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 145 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_GetEndpointsRequest_calcSizeBinary()
static UA_INLINE size_t UA_GetEndpointsRequest_calcSizeBinary (const UA_GetEndpointsRequest * src) static
Definition at line 1527 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_GetEndpointsRequest_decodeBinary()
static UA_INLINE UA_StatusCode UA_GetEndpointsRequest_decodeBinary (const UA_ByteString * src, size_t * offset, UA_GetEndpointsRequest * dst) static
Definition at line 1535 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_GetEndpointsRequest_encodeBinary()
static UA_INLINE UA_StatusCode UA_GetEndpointsRequest_encodeBinary (const UA_GetEndpointsRequest * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 1531 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_GetEndpointsResponse_calcSizeBinary()
static UA_INLINE size_t UA_GetEndpointsResponse_calcSizeBinary (const UA_GetEndpointsResponse * src) static
Definition at line 2591 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_GetEndpointsResponse_decodeBinary()
static UA_INLINE UA_StatusCode UA_GetEndpointsResponse_decodeBinary (const UA_ByteString * src, size_t * offset, UA_GetEndpointsResponse * dst) static
Definition at line 2599 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_GetEndpointsResponse_encodeBinary()
static UA_INLINE UA_StatusCode UA_GetEndpointsResponse_encodeBinary (const UA_GetEndpointsResponse * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 2595 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_Guid_calcSizeBinary()
static UA_INLINE size_t UA_Guid_calcSizeBinary (const UA_Guid * src) static
Definition at line 197 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_Guid_decodeBinary()
static UA_INLINE UA_StatusCode UA_Guid_decodeBinary (const UA_ByteString * src, size_t * offset, UA_Guid * dst) static
Definition at line 205 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_Guid_encodeBinary()
static UA_INLINE UA_StatusCode UA_Guid_encodeBinary (const UA_Guid * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 201 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_Int16_calcSizeBinary()
static UA_INLINE size_t UA_Int16_calcSizeBinary (const UA_Int16 * src) static
Definition at line 57 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_Int16_decodeBinary()
static UA_INLINE UA_StatusCode UA_Int16_decodeBinary (const UA_ByteString * src, size_t * offset, UA_Int16 * dst) static
Definition at line 65 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_Int16_encodeBinary()
static UA_INLINE UA_StatusCode UA_Int16_encodeBinary (const UA_Int16 * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 61 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_Int32_calcSizeBinary()
static UA_INLINE size_t UA_Int32_calcSizeBinary (const UA_Int32 * src) static
Definition at line 85 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_Int32_decodeBinary()
static UA_INLINE UA_StatusCode UA_Int32_decodeBinary (const UA_ByteString * src, size_t * offset, UA_Int32 * dst) static
Definition at line 93 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_Int32_encodeBinary()
static UA_INLINE UA_StatusCode UA_Int32_encodeBinary (const UA_Int32 * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 89 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_Int64_calcSizeBinary()
static UA_INLINE size_t UA_Int64_calcSizeBinary (const UA_Int64 * src) static
Definition at line 113 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_Int64_decodeBinary()
static UA_INLINE UA_StatusCode UA_Int64_decodeBinary (const UA_ByteString * src, size_t * offset, UA_Int64 * dst) static
Definition at line 121 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_Int64_encodeBinary()
static UA_INLINE UA_StatusCode UA_Int64_encodeBinary (const UA_Int64 * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 117 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_IssuedIdentityToken_calcSizeBinary()
static UA_INLINE size_t UA_IssuedIdentityToken_calcSizeBinary (const UA_IssuedIdentityToken * src) static
Definition at line 911 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_IssuedIdentityToken_decodeBinary()
static UA_INLINE UA_StatusCode UA_IssuedIdentityToken_decodeBinary (const UA_ByteString * src, size_t * offset, UA_IssuedIdentityToken * dst) static
Definition at line 919 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_IssuedIdentityToken_encodeBinary()
static UA_INLINE UA_StatusCode UA_IssuedIdentityToken_encodeBinary (const UA_IssuedIdentityToken * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 915 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_LiteralOperand_calcSizeBinary()
static UA_INLINE size_t UA_LiteralOperand_calcSizeBinary (const UA_LiteralOperand * src) static
Definition at line 477 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_LiteralOperand_decodeBinary()
static UA_INLINE UA_StatusCode UA_LiteralOperand_decodeBinary (const UA_ByteString * src, size_t * offset, UA_LiteralOperand * dst) static
Definition at line 485 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_LiteralOperand_encodeBinary()
static UA_INLINE UA_StatusCode UA_LiteralOperand_encodeBinary (const UA_LiteralOperand * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 481 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_LocaleId_calcSizeBinary()
static UA_INLINE size_t UA_LocaleId_calcSizeBinary (const UA_LocaleId * src) static
Definition at line 1415 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_LocaleId_decodeBinary()
static UA_INLINE UA_StatusCode UA_LocaleId_decodeBinary (const UA_ByteString * src, size_t * offset, UA_LocaleId * dst) static
Definition at line 1423 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_LocaleId_encodeBinary()
static UA_INLINE UA_StatusCode UA_LocaleId_encodeBinary (const UA_LocaleId * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 1419 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_LocalizedText_calcSizeBinary()
static UA_INLINE size_t UA_LocalizedText_calcSizeBinary (const UA_LocalizedText * src) static
Definition at line 295 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_LocalizedText_decodeBinary()
static UA_INLINE UA_StatusCode UA_LocalizedText_decodeBinary (const UA_ByteString * src, size_t * offset, UA_LocalizedText * dst) static
Definition at line 303 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_LocalizedText_encodeBinary()
static UA_INLINE UA_StatusCode UA_LocalizedText_encodeBinary (const UA_LocalizedText * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 299 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_MdnsDiscoveryConfiguration_calcSizeBinary()
static UA_INLINE size_t UA_MdnsDiscoveryConfiguration_calcSizeBinary (const UA_MdnsDiscoveryConfiguration * src) static
Definition at line 771 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_MdnsDiscoveryConfiguration_decodeBinary()
static UA_INLINE UA_StatusCode UA_MdnsDiscoveryConfiguration_decodeBinary (const UA_ByteString * src, size_t * offset, UA_MdnsDiscoveryConfiguration * dst) static
Definition at line 779 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_MdnsDiscoveryConfiguration_encodeBinary()
static UA_INLINE UA_StatusCode UA_MdnsDiscoveryConfiguration_encodeBinary (const UA_MdnsDiscoveryConfiguration * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 775 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_MessageSecurityMode_calcSizeBinary()
static UA_INLINE size_t UA_MessageSecurityMode_calcSizeBinary (const UA_MessageSecurityMode * src) static
Definition at line 491 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_MessageSecurityMode_decodeBinary()
static UA_INLINE UA_StatusCode UA_MessageSecurityMode_decodeBinary (const UA_ByteString * src, size_t * offset, UA_MessageSecurityMode * dst) static
Definition at line 499 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_MessageSecurityMode_encodeBinary()
static UA_INLINE UA_StatusCode UA_MessageSecurityMode_encodeBinary (const UA_MessageSecurityMode * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 495 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_MethodAttributes_calcSizeBinary()
static UA_INLINE size_t UA_MethodAttributes_calcSizeBinary (const UA_MethodAttributes * src) static
Definition at line 1807 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_MethodAttributes_decodeBinary()
static UA_INLINE UA_StatusCode UA_MethodAttributes_decodeBinary (const UA_ByteString * src, size_t * offset, UA_MethodAttributes * dst) static
Definition at line 1815 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_MethodAttributes_encodeBinary()
static UA_INLINE UA_StatusCode UA_MethodAttributes_encodeBinary (const UA_MethodAttributes * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 1811 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_ModifyMonitoredItemsRequest_calcSizeBinary()
static UA_INLINE size_t UA_ModifyMonitoredItemsRequest_calcSizeBinary (const UA_ModifyMonitoredItemsRequest * src) static
Definition at line 2101 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_ModifyMonitoredItemsRequest_decodeBinary()
static UA_INLINE UA_StatusCode UA_ModifyMonitoredItemsRequest_decodeBinary (const UA_ByteString * src, size_t * offset, UA_ModifyMonitoredItemsRequest * dst) static
Definition at line 2109 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_ModifyMonitoredItemsRequest_encodeBinary()
static UA_INLINE UA_StatusCode UA_ModifyMonitoredItemsRequest_encodeBinary (const UA_ModifyMonitoredItemsRequest * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 2105 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_ModifyMonitoredItemsResponse_calcSizeBinary()
static UA_INLINE size_t UA_ModifyMonitoredItemsResponse_calcSizeBinary (const UA_ModifyMonitoredItemsResponse * src) static
Definition at line 1919 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_ModifyMonitoredItemsResponse_decodeBinary()
static UA_INLINE UA_StatusCode UA_ModifyMonitoredItemsResponse_decodeBinary (const UA_ByteString * src, size_t * offset, UA_ModifyMonitoredItemsResponse * dst) static
Definition at line 1927 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_ModifyMonitoredItemsResponse_encodeBinary()
static UA_INLINE UA_StatusCode UA_ModifyMonitoredItemsResponse_encodeBinary (const UA_ModifyMonitoredItemsResponse * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 1923 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_ModifySubscriptionRequest_calcSizeBinary()
static UA_INLINE size_t UA_ModifySubscriptionRequest_calcSizeBinary (const UA_ModifySubscriptionRequest * src) static
Definition at line 995 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_ModifySubscriptionRequest_decodeBinary()
static UA_INLINE UA_StatusCode UA_ModifySubscriptionRequest_decodeBinary (const UA_ByteString * src, size_t * offset, UA_ModifySubscriptionRequest * dst) static
Definition at line 1003 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_ModifySubscriptionRequest_encodeBinary()
static UA_INLINE UA_StatusCode UA_ModifySubscriptionRequest_encodeBinary (const UA_ModifySubscriptionRequest * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 999 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_ModifySubscriptionResponse_calcSizeBinary()
static UA_INLINE size_t UA_ModifySubscriptionResponse_calcSizeBinary (const UA_ModifySubscriptionResponse * src) static
Definition at line 589 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_ModifySubscriptionResponse_decodeBinary()
static UA_INLINE UA_StatusCode UA_ModifySubscriptionResponse_decodeBinary (const UA_ByteString * src, size_t * offset, UA_ModifySubscriptionResponse * dst) static
Definition at line 597 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_ModifySubscriptionResponse_encodeBinary()
static UA_INLINE UA_StatusCode UA_ModifySubscriptionResponse_encodeBinary (const UA_ModifySubscriptionResponse * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 593 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_MonitoredItemCreateRequest_calcSizeBinary()
static UA_INLINE size_t UA_MonitoredItemCreateRequest_calcSizeBinary (const UA_MonitoredItemCreateRequest * src) static
Definition at line 1625 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_MonitoredItemCreateRequest_decodeBinary()
static UA_INLINE UA_StatusCode UA_MonitoredItemCreateRequest_decodeBinary (const UA_ByteString * src, size_t * offset, UA_MonitoredItemCreateRequest * dst) static
Definition at line 1633 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_MonitoredItemCreateRequest_encodeBinary()
static UA_INLINE UA_StatusCode UA_MonitoredItemCreateRequest_encodeBinary (const UA_MonitoredItemCreateRequest * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 1629 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_MonitoredItemCreateResult_calcSizeBinary()
static UA_INLINE size_t UA_MonitoredItemCreateResult_calcSizeBinary (const UA_MonitoredItemCreateResult * src) static
Definition at line 435 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_MonitoredItemCreateResult_decodeBinary()
static UA_INLINE UA_StatusCode UA_MonitoredItemCreateResult_decodeBinary (const UA_ByteString * src, size_t * offset, UA_MonitoredItemCreateResult * dst) static
Definition at line 443 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_MonitoredItemCreateResult_encodeBinary()
static UA_INLINE UA_StatusCode UA_MonitoredItemCreateResult_encodeBinary (const UA_MonitoredItemCreateResult * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 439 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_MonitoredItemModifyRequest_calcSizeBinary()
static UA_INLINE size_t UA_MonitoredItemModifyRequest_calcSizeBinary (const UA_MonitoredItemModifyRequest * src) static
Definition at line 1373 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_MonitoredItemModifyRequest_decodeBinary()
static UA_INLINE UA_StatusCode UA_MonitoredItemModifyRequest_decodeBinary (const UA_ByteString * src, size_t * offset, UA_MonitoredItemModifyRequest * dst) static
Definition at line 1381 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_MonitoredItemModifyRequest_encodeBinary()
static UA_INLINE UA_StatusCode UA_MonitoredItemModifyRequest_encodeBinary (const UA_MonitoredItemModifyRequest * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 1377 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_MonitoredItemModifyResult_calcSizeBinary()
static UA_INLINE size_t UA_MonitoredItemModifyResult_calcSizeBinary (const UA_MonitoredItemModifyResult * src) static
Definition at line 715 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_MonitoredItemModifyResult_decodeBinary()
static UA_INLINE UA_StatusCode UA_MonitoredItemModifyResult_decodeBinary (const UA_ByteString * src, size_t * offset, UA_MonitoredItemModifyResult * dst) static
Definition at line 723 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_MonitoredItemModifyResult_encodeBinary()
static UA_INLINE UA_StatusCode UA_MonitoredItemModifyResult_encodeBinary (const UA_MonitoredItemModifyResult * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 719 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_MonitoredItemNotification_calcSizeBinary()
static UA_INLINE size_t UA_MonitoredItemNotification_calcSizeBinary (const UA_MonitoredItemNotification * src) static
Definition at line 547 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_MonitoredItemNotification_decodeBinary()
static UA_INLINE UA_StatusCode UA_MonitoredItemNotification_decodeBinary (const UA_ByteString * src, size_t * offset, UA_MonitoredItemNotification * dst) static
Definition at line 555 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_MonitoredItemNotification_encodeBinary()
static UA_INLINE UA_StatusCode UA_MonitoredItemNotification_encodeBinary (const UA_MonitoredItemNotification * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 551 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_MonitoringMode_calcSizeBinary()
static UA_INLINE size_t UA_MonitoringMode_calcSizeBinary (const UA_MonitoringMode * src) static
Definition at line 659 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_MonitoringMode_decodeBinary()
static UA_INLINE UA_StatusCode UA_MonitoringMode_decodeBinary (const UA_ByteString * src, size_t * offset, UA_MonitoringMode * dst) static
Definition at line 667 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_MonitoringMode_encodeBinary()
static UA_INLINE UA_StatusCode UA_MonitoringMode_encodeBinary (const UA_MonitoringMode * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 663 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_MonitoringParameters_calcSizeBinary()
static UA_INLINE size_t UA_MonitoringParameters_calcSizeBinary (const UA_MonitoringParameters * src) static
Definition at line 1289 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_MonitoringParameters_decodeBinary()
static UA_INLINE UA_StatusCode UA_MonitoringParameters_decodeBinary (const UA_ByteString * src, size_t * offset, UA_MonitoringParameters * dst) static
Definition at line 1297 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_MonitoringParameters_encodeBinary()
static UA_INLINE UA_StatusCode UA_MonitoringParameters_encodeBinary (const UA_MonitoringParameters * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 1293 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_NodeAttributes_calcSizeBinary()
static UA_INLINE size_t UA_NodeAttributes_calcSizeBinary (const UA_NodeAttributes * src) static
Definition at line 603 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_NodeAttributes_decodeBinary()
static UA_INLINE UA_StatusCode UA_NodeAttributes_decodeBinary (const UA_ByteString * src, size_t * offset, UA_NodeAttributes * dst) static
Definition at line 611 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_NodeAttributes_encodeBinary()
static UA_INLINE UA_StatusCode UA_NodeAttributes_encodeBinary (const UA_NodeAttributes * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 607 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_NodeAttributesMask_calcSizeBinary()
static UA_INLINE size_t UA_NodeAttributesMask_calcSizeBinary (const UA_NodeAttributesMask * src) static
Definition at line 1597 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_NodeAttributesMask_decodeBinary()
static UA_INLINE UA_StatusCode UA_NodeAttributesMask_decodeBinary (const UA_ByteString * src, size_t * offset, UA_NodeAttributesMask * dst) static
Definition at line 1605 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_NodeAttributesMask_encodeBinary()
static UA_INLINE UA_StatusCode UA_NodeAttributesMask_encodeBinary (const UA_NodeAttributesMask * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 1601 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_NodeClass_calcSizeBinary()
static UA_INLINE size_t UA_NodeClass_calcSizeBinary (const UA_NodeClass * src) static
Definition at line 841 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_NodeClass_decodeBinary()
static UA_INLINE UA_StatusCode UA_NodeClass_decodeBinary (const UA_ByteString * src, size_t * offset, UA_NodeClass * dst) static
Definition at line 849 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_NodeClass_encodeBinary()
static UA_INLINE UA_StatusCode UA_NodeClass_encodeBinary (const UA_NodeClass * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 845 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_NodeId_calcSizeBinary()
static UA_INLINE size_t UA_NodeId_calcSizeBinary (const UA_NodeId * src) static
Definition at line 239 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_NodeId_decodeBinary()
static UA_INLINE UA_StatusCode UA_NodeId_decodeBinary (const UA_ByteString * src, size_t * offset, UA_NodeId * dst) static
Definition at line 247 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_NodeId_encodeBinary()
static UA_INLINE UA_StatusCode UA_NodeId_encodeBinary (const UA_NodeId * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 243 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_NotificationMessage_calcSizeBinary()
static UA_INLINE size_t UA_NotificationMessage_calcSizeBinary (const UA_NotificationMessage * src) static
Definition at line 743 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_NotificationMessage_decodeBinary()
static UA_INLINE UA_StatusCode UA_NotificationMessage_decodeBinary (const UA_ByteString * src, size_t * offset, UA_NotificationMessage * dst) static
Definition at line 751 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_NotificationMessage_encodeBinary()
static UA_INLINE UA_StatusCode UA_NotificationMessage_encodeBinary (const UA_NotificationMessage * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 747 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_ObjectAttributes_calcSizeBinary()
static UA_INLINE size_t UA_ObjectAttributes_calcSizeBinary (const UA_ObjectAttributes * src) static
Definition at line 1975 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_ObjectAttributes_decodeBinary()
static UA_INLINE UA_StatusCode UA_ObjectAttributes_decodeBinary (const UA_ByteString * src, size_t * offset, UA_ObjectAttributes * dst) static
Definition at line 1983 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_ObjectAttributes_encodeBinary()
static UA_INLINE UA_StatusCode UA_ObjectAttributes_encodeBinary (const UA_ObjectAttributes * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 1979 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_ObjectTypeAttributes_calcSizeBinary()
static UA_INLINE size_t UA_ObjectTypeAttributes_calcSizeBinary (const UA_ObjectTypeAttributes * src) static
Definition at line 855 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_ObjectTypeAttributes_decodeBinary()
static UA_INLINE UA_StatusCode UA_ObjectTypeAttributes_decodeBinary (const UA_ByteString * src, size_t * offset, UA_ObjectTypeAttributes * dst) static
Definition at line 863 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_ObjectTypeAttributes_encodeBinary()
static UA_INLINE UA_StatusCode UA_ObjectTypeAttributes_encodeBinary (const UA_ObjectTypeAttributes * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 859 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_OpenSecureChannelRequest_calcSizeBinary()
static UA_INLINE size_t UA_OpenSecureChannelRequest_calcSizeBinary (const UA_OpenSecureChannelRequest * src) static
Definition at line 2157 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_OpenSecureChannelRequest_decodeBinary()
static UA_INLINE UA_StatusCode UA_OpenSecureChannelRequest_decodeBinary (const UA_ByteString * src, size_t * offset, UA_OpenSecureChannelRequest * dst) static
Definition at line 2165 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_OpenSecureChannelRequest_encodeBinary()
static UA_INLINE UA_StatusCode UA_OpenSecureChannelRequest_encodeBinary (const UA_OpenSecureChannelRequest * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 2161 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_OpenSecureChannelResponse_calcSizeBinary()
static UA_INLINE size_t UA_OpenSecureChannelResponse_calcSizeBinary (const UA_OpenSecureChannelResponse * src) static
Definition at line 1849 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_OpenSecureChannelResponse_decodeBinary()
static UA_INLINE UA_StatusCode UA_OpenSecureChannelResponse_decodeBinary (const UA_ByteString * src, size_t * offset, UA_OpenSecureChannelResponse * dst) static
Definition at line 1857 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_OpenSecureChannelResponse_encodeBinary()
static UA_INLINE UA_StatusCode UA_OpenSecureChannelResponse_encodeBinary (const UA_OpenSecureChannelResponse * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 1853 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_PublishRequest_calcSizeBinary()
static UA_INLINE size_t UA_PublishRequest_calcSizeBinary (const UA_PublishRequest * src) static
Definition at line 1989 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_PublishRequest_decodeBinary()
static UA_INLINE UA_StatusCode UA_PublishRequest_decodeBinary (const UA_ByteString * src, size_t * offset, UA_PublishRequest * dst) static
Definition at line 1997 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_PublishRequest_encodeBinary()
static UA_INLINE UA_StatusCode UA_PublishRequest_encodeBinary (const UA_PublishRequest * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 1993 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_PublishResponse_calcSizeBinary()
static UA_INLINE size_t UA_PublishResponse_calcSizeBinary (const UA_PublishResponse * src) static
Definition at line 2129 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_PublishResponse_decodeBinary()
static UA_INLINE UA_StatusCode UA_PublishResponse_decodeBinary (const UA_ByteString * src, size_t * offset, UA_PublishResponse * dst) static
Definition at line 2137 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_PublishResponse_encodeBinary()
static UA_INLINE UA_StatusCode UA_PublishResponse_encodeBinary (const UA_PublishResponse * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 2133 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_QualifiedName_calcSizeBinary()
static UA_INLINE size_t UA_QualifiedName_calcSizeBinary (const UA_QualifiedName * src) static
Definition at line 281 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_QualifiedName_decodeBinary()
static UA_INLINE UA_StatusCode UA_QualifiedName_decodeBinary (const UA_ByteString * src, size_t * offset, UA_QualifiedName * dst) static
Definition at line 289 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_QualifiedName_encodeBinary()
static UA_INLINE UA_StatusCode UA_QualifiedName_encodeBinary (const UA_QualifiedName * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 285 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_Range_calcSizeBinary()
static UA_INLINE size_t UA_Range_calcSizeBinary (const UA_Range * src) static
Definition at line 1639 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_Range_decodeBinary()
static UA_INLINE UA_StatusCode UA_Range_decodeBinary (const UA_ByteString * src, size_t * offset, UA_Range * dst) static
Definition at line 1647 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_Range_encodeBinary()
static UA_INLINE UA_StatusCode UA_Range_encodeBinary (const UA_Range * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 1643 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_ReadRequest_calcSizeBinary()
static UA_INLINE size_t UA_ReadRequest_calcSizeBinary (const UA_ReadRequest * src) static
Definition at line 2297 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_ReadRequest_decodeBinary()
static UA_INLINE UA_StatusCode UA_ReadRequest_decodeBinary (const UA_ByteString * src, size_t * offset, UA_ReadRequest * dst) static
Definition at line 2305 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_ReadRequest_encodeBinary()
static UA_INLINE UA_StatusCode UA_ReadRequest_encodeBinary (const UA_ReadRequest * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 2301 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_ReadResponse_calcSizeBinary()
static UA_INLINE size_t UA_ReadResponse_calcSizeBinary (const UA_ReadResponse * src) static
Definition at line 813 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_ReadResponse_decodeBinary()
static UA_INLINE UA_StatusCode UA_ReadResponse_decodeBinary (const UA_ByteString * src, size_t * offset, UA_ReadResponse * dst) static
Definition at line 821 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_ReadResponse_encodeBinary()
static UA_INLINE UA_StatusCode UA_ReadResponse_encodeBinary (const UA_ReadResponse * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 817 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_ReadValueId_calcSizeBinary()
static UA_INLINE size_t UA_ReadValueId_calcSizeBinary (const UA_ReadValueId * src) static
Definition at line 1317 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_ReadValueId_decodeBinary()
static UA_INLINE UA_StatusCode UA_ReadValueId_decodeBinary (const UA_ByteString * src, size_t * offset, UA_ReadValueId * dst) static
Definition at line 1325 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_ReadValueId_encodeBinary()
static UA_INLINE UA_StatusCode UA_ReadValueId_encodeBinary (const UA_ReadValueId * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 1321 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_RedundancySupport_calcSizeBinary()
static UA_INLINE size_t UA_RedundancySupport_calcSizeBinary (const UA_RedundancySupport * src) static
Definition at line 1947 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_RedundancySupport_decodeBinary()
static UA_INLINE UA_StatusCode UA_RedundancySupport_decodeBinary (const UA_ByteString * src, size_t * offset, UA_RedundancySupport * dst) static
Definition at line 1955 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_RedundancySupport_encodeBinary()
static UA_INLINE UA_StatusCode UA_RedundancySupport_encodeBinary (const UA_RedundancySupport * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 1951 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_ReferenceDescription_calcSizeBinary()
static UA_INLINE size_t UA_ReferenceDescription_calcSizeBinary (const UA_ReferenceDescription * src) static
Definition at line 2031 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_ReferenceDescription_decodeBinary()
static UA_INLINE UA_StatusCode UA_ReferenceDescription_decodeBinary (const UA_ByteString * src, size_t * offset, UA_ReferenceDescription * dst) static
Definition at line 2039 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_ReferenceDescription_encodeBinary()
static UA_INLINE UA_StatusCode UA_ReferenceDescription_encodeBinary (const UA_ReferenceDescription * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 2035 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_ReferenceTypeAttributes_calcSizeBinary()
static UA_INLINE size_t UA_ReferenceTypeAttributes_calcSizeBinary (const UA_ReferenceTypeAttributes * src) static
Definition at line 1513 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_ReferenceTypeAttributes_decodeBinary()
static UA_INLINE UA_StatusCode UA_ReferenceTypeAttributes_decodeBinary (const UA_ByteString * src, size_t * offset, UA_ReferenceTypeAttributes * dst) static
Definition at line 1521 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_ReferenceTypeAttributes_encodeBinary()
static UA_INLINE UA_StatusCode UA_ReferenceTypeAttributes_encodeBinary (const UA_ReferenceTypeAttributes * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 1517 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_RegisteredServer_calcSizeBinary()
static UA_INLINE size_t UA_RegisteredServer_calcSizeBinary (const UA_RegisteredServer * src) static
Definition at line 2269 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_RegisteredServer_decodeBinary()
static UA_INLINE UA_StatusCode UA_RegisteredServer_decodeBinary (const UA_ByteString * src, size_t * offset, UA_RegisteredServer * dst) static
Definition at line 2277 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_RegisteredServer_encodeBinary()
static UA_INLINE UA_StatusCode UA_RegisteredServer_encodeBinary (const UA_RegisteredServer * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 2273 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_RegisterNodesRequest_calcSizeBinary()
static UA_INLINE size_t UA_RegisterNodesRequest_calcSizeBinary (const UA_RegisterNodesRequest * src) static
Definition at line 1793 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_RegisterNodesRequest_decodeBinary()
static UA_INLINE UA_StatusCode UA_RegisterNodesRequest_decodeBinary (const UA_ByteString * src, size_t * offset, UA_RegisterNodesRequest * dst) static
Definition at line 1801 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_RegisterNodesRequest_encodeBinary()
static UA_INLINE UA_StatusCode UA_RegisterNodesRequest_encodeBinary (const UA_RegisterNodesRequest * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 1797 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_RegisterNodesResponse_calcSizeBinary()
static UA_INLINE size_t UA_RegisterNodesResponse_calcSizeBinary (const UA_RegisterNodesResponse * src) static
Definition at line 1905 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_RegisterNodesResponse_decodeBinary()
static UA_INLINE UA_StatusCode UA_RegisterNodesResponse_decodeBinary (const UA_ByteString * src, size_t * offset, UA_RegisterNodesResponse * dst) static
Definition at line 1913 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_RegisterNodesResponse_encodeBinary()
static UA_INLINE UA_StatusCode UA_RegisterNodesResponse_encodeBinary (const UA_RegisterNodesResponse * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 1909 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_RegisterServer2Request_calcSizeBinary()
static UA_INLINE size_t UA_RegisterServer2Request_calcSizeBinary (const UA_RegisterServer2Request * src) static
Definition at line 2395 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_RegisterServer2Request_decodeBinary()
static UA_INLINE UA_StatusCode UA_RegisterServer2Request_decodeBinary (const UA_ByteString * src, size_t * offset, UA_RegisterServer2Request * dst) static
Definition at line 2403 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_RegisterServer2Request_encodeBinary()
static UA_INLINE UA_StatusCode UA_RegisterServer2Request_encodeBinary (const UA_RegisterServer2Request * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 2399 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_RegisterServer2Response_calcSizeBinary()
static UA_INLINE size_t UA_RegisterServer2Response_calcSizeBinary (const UA_RegisterServer2Response * src) static
Definition at line 1107 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_RegisterServer2Response_decodeBinary()
static UA_INLINE UA_StatusCode UA_RegisterServer2Response_decodeBinary (const UA_ByteString * src, size_t * offset, UA_RegisterServer2Response * dst) static
Definition at line 1115 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_RegisterServer2Response_encodeBinary()
static UA_INLINE UA_StatusCode UA_RegisterServer2Response_encodeBinary (const UA_RegisterServer2Response * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 1111 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_RegisterServerRequest_calcSizeBinary()
static UA_INLINE size_t UA_RegisterServerRequest_calcSizeBinary (const UA_RegisterServerRequest * src) static
Definition at line 2521 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_RegisterServerRequest_decodeBinary()
static UA_INLINE UA_StatusCode UA_RegisterServerRequest_decodeBinary (const UA_ByteString * src, size_t * offset, UA_RegisterServerRequest * dst) static
Definition at line 2529 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_RegisterServerRequest_encodeBinary()
static UA_INLINE UA_StatusCode UA_RegisterServerRequest_encodeBinary (const UA_RegisterServerRequest * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 2525 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_RegisterServerResponse_calcSizeBinary()
static UA_INLINE size_t UA_RegisterServerResponse_calcSizeBinary (const UA_RegisterServerResponse * src) static
Definition at line 1079 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_RegisterServerResponse_decodeBinary()
static UA_INLINE UA_StatusCode UA_RegisterServerResponse_decodeBinary (const UA_ByteString * src, size_t * offset, UA_RegisterServerResponse * dst) static
Definition at line 1087 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_RegisterServerResponse_encodeBinary()
static UA_INLINE UA_StatusCode UA_RegisterServerResponse_encodeBinary (const UA_RegisterServerResponse * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 1083 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_RelativePath_calcSizeBinary()
static UA_INLINE size_t UA_RelativePath_calcSizeBinary (const UA_RelativePath * src) static
Definition at line 1345 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_RelativePath_decodeBinary()
static UA_INLINE UA_StatusCode UA_RelativePath_decodeBinary (const UA_ByteString * src, size_t * offset, UA_RelativePath * dst) static
Definition at line 1353 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_RelativePath_encodeBinary()
static UA_INLINE UA_StatusCode UA_RelativePath_encodeBinary (const UA_RelativePath * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 1349 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_RelativePathElement_calcSizeBinary()
static UA_INLINE size_t UA_RelativePathElement_calcSizeBinary (const UA_RelativePathElement * src) static
Definition at line 1135 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_RelativePathElement_decodeBinary()
static UA_INLINE UA_StatusCode UA_RelativePathElement_decodeBinary (const UA_ByteString * src, size_t * offset, UA_RelativePathElement * dst) static
Definition at line 1143 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_RelativePathElement_encodeBinary()
static UA_INLINE UA_StatusCode UA_RelativePathElement_encodeBinary (const UA_RelativePathElement * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 1139 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_RepublishRequest_calcSizeBinary()
static UA_INLINE size_t UA_RepublishRequest_calcSizeBinary (const UA_RepublishRequest * src) static
Definition at line 1891 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_RepublishRequest_decodeBinary()
static UA_INLINE UA_StatusCode UA_RepublishRequest_decodeBinary (const UA_ByteString * src, size_t * offset, UA_RepublishRequest * dst) static
Definition at line 1899 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_RepublishRequest_encodeBinary()
static UA_INLINE UA_StatusCode UA_RepublishRequest_encodeBinary (const UA_RepublishRequest * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 1895 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_RepublishResponse_calcSizeBinary()
static UA_INLINE size_t UA_RepublishResponse_calcSizeBinary (const UA_RepublishResponse * src) static
Definition at line 1765 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_RepublishResponse_decodeBinary()
static UA_INLINE UA_StatusCode UA_RepublishResponse_decodeBinary (const UA_ByteString * src, size_t * offset, UA_RepublishResponse * dst) static
Definition at line 1773 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_RepublishResponse_encodeBinary()
static UA_INLINE UA_StatusCode UA_RepublishResponse_encodeBinary (const UA_RepublishResponse * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 1769 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_RequestHeader_calcSizeBinary()
static UA_INLINE size_t UA_RequestHeader_calcSizeBinary (const UA_RequestHeader * src) static
Definition at line 701 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_RequestHeader_decodeBinary()
static UA_INLINE UA_StatusCode UA_RequestHeader_decodeBinary (const UA_ByteString * src, size_t * offset, UA_RequestHeader * dst) static
Definition at line 709 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_RequestHeader_encodeBinary()
static UA_INLINE UA_StatusCode UA_RequestHeader_encodeBinary (const UA_RequestHeader * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 705 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_ResponseHeader_calcSizeBinary()
static UA_INLINE size_t UA_ResponseHeader_calcSizeBinary (const UA_ResponseHeader * src) static
Definition at line 561 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_ResponseHeader_decodeBinary()
static UA_INLINE UA_StatusCode UA_ResponseHeader_decodeBinary (const UA_ByteString * src, size_t * offset, UA_ResponseHeader * dst) static
Definition at line 569 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_ResponseHeader_encodeBinary()
static UA_INLINE UA_StatusCode UA_ResponseHeader_encodeBinary (const UA_ResponseHeader * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 565 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_SByte_calcSizeBinary()
static UA_INLINE size_t UA_SByte_calcSizeBinary (const UA_SByte * src) static
Definition at line 29 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_SByte_decodeBinary()
static UA_INLINE UA_StatusCode UA_SByte_decodeBinary (const UA_ByteString * src, size_t * offset, UA_SByte * dst) static
Definition at line 37 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_SByte_encodeBinary()
static UA_INLINE UA_StatusCode UA_SByte_encodeBinary (const UA_SByte * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 33 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_SecurityTokenRequestType_calcSizeBinary()
static UA_INLINE size_t UA_SecurityTokenRequestType_calcSizeBinary (const UA_SecurityTokenRequestType * src) static
Definition at line 869 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_SecurityTokenRequestType_decodeBinary()
static UA_INLINE UA_StatusCode UA_SecurityTokenRequestType_decodeBinary (const UA_ByteString * src, size_t * offset, UA_SecurityTokenRequestType * dst) static
Definition at line 877 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_SecurityTokenRequestType_encodeBinary()
static UA_INLINE UA_StatusCode UA_SecurityTokenRequestType_encodeBinary (const UA_SecurityTokenRequestType * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 873 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_ServerDiagnosticsSummaryDataType_calcSizeBinary()
static UA_INLINE size_t UA_ServerDiagnosticsSummaryDataType_calcSizeBinary (const UA_ServerDiagnosticsSummaryDataType * src) static
Definition at line 449 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_ServerDiagnosticsSummaryDataType_decodeBinary()
static UA_INLINE UA_StatusCode UA_ServerDiagnosticsSummaryDataType_decodeBinary (const UA_ByteString * src, size_t * offset, UA_ServerDiagnosticsSummaryDataType * dst) static
Definition at line 457 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_ServerDiagnosticsSummaryDataType_encodeBinary()
static UA_INLINE UA_StatusCode UA_ServerDiagnosticsSummaryDataType_encodeBinary (const UA_ServerDiagnosticsSummaryDataType * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 453 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_ServerOnNetwork_calcSizeBinary()
static UA_INLINE size_t UA_ServerOnNetwork_calcSizeBinary (const UA_ServerOnNetwork * src) static
Definition at line 925 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_ServerOnNetwork_decodeBinary()
static UA_INLINE UA_StatusCode UA_ServerOnNetwork_decodeBinary (const UA_ByteString * src, size_t * offset, UA_ServerOnNetwork * dst) static
Definition at line 933 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_ServerOnNetwork_encodeBinary()
static UA_INLINE UA_StatusCode UA_ServerOnNetwork_encodeBinary (const UA_ServerOnNetwork * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 929 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_ServerState_calcSizeBinary()
static UA_INLINE size_t UA_ServerState_calcSizeBinary (const UA_ServerState * src) static
Definition at line 1695 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_ServerState_decodeBinary()
static UA_INLINE UA_StatusCode UA_ServerState_decodeBinary (const UA_ByteString * src, size_t * offset, UA_ServerState * dst) static
Definition at line 1703 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_ServerState_encodeBinary()
static UA_INLINE UA_StatusCode UA_ServerState_encodeBinary (const UA_ServerState * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 1699 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_ServerStatusDataType_calcSizeBinary()
static UA_INLINE size_t UA_ServerStatusDataType_calcSizeBinary (const UA_ServerStatusDataType * src) static
Definition at line 2241 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_ServerStatusDataType_decodeBinary()
static UA_INLINE UA_StatusCode UA_ServerStatusDataType_decodeBinary (const UA_ByteString * src, size_t * offset, UA_ServerStatusDataType * dst) static
Definition at line 2249 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_ServerStatusDataType_encodeBinary()
static UA_INLINE UA_StatusCode UA_ServerStatusDataType_encodeBinary (const UA_ServerStatusDataType * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 2245 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_ServiceFault_calcSizeBinary()
static UA_INLINE size_t UA_ServiceFault_calcSizeBinary (const UA_ServiceFault * src) static
Definition at line 2115 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_ServiceFault_decodeBinary()
static UA_INLINE UA_StatusCode UA_ServiceFault_decodeBinary (const UA_ByteString * src, size_t * offset, UA_ServiceFault * dst) static
Definition at line 2123 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_ServiceFault_encodeBinary()
static UA_INLINE UA_StatusCode UA_ServiceFault_encodeBinary (const UA_ServiceFault * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 2119 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_SetMonitoringModeRequest_calcSizeBinary()
static UA_INLINE size_t UA_SetMonitoringModeRequest_calcSizeBinary (const UA_SetMonitoringModeRequest * src) static
Definition at line 1485 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_SetMonitoringModeRequest_decodeBinary()
static UA_INLINE UA_StatusCode UA_SetMonitoringModeRequest_decodeBinary (const UA_ByteString * src, size_t * offset, UA_SetMonitoringModeRequest * dst) static
Definition at line 1493 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_SetMonitoringModeRequest_encodeBinary()
static UA_INLINE UA_StatusCode UA_SetMonitoringModeRequest_encodeBinary (const UA_SetMonitoringModeRequest * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 1489 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_SetMonitoringModeResponse_calcSizeBinary()
static UA_INLINE size_t UA_SetMonitoringModeResponse_calcSizeBinary (const UA_SetMonitoringModeResponse * src) static
Definition at line 673 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_SetMonitoringModeResponse_decodeBinary()
static UA_INLINE UA_StatusCode UA_SetMonitoringModeResponse_decodeBinary (const UA_ByteString * src, size_t * offset, UA_SetMonitoringModeResponse * dst) static
Definition at line 681 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_SetMonitoringModeResponse_encodeBinary()
static UA_INLINE UA_StatusCode UA_SetMonitoringModeResponse_encodeBinary (const UA_SetMonitoringModeResponse * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 677 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_SetPublishingModeRequest_calcSizeBinary()
static UA_INLINE size_t UA_SetPublishingModeRequest_calcSizeBinary (const UA_SetPublishingModeRequest * src) static
Definition at line 897 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_SetPublishingModeRequest_decodeBinary()
static UA_INLINE UA_StatusCode UA_SetPublishingModeRequest_decodeBinary (const UA_ByteString * src, size_t * offset, UA_SetPublishingModeRequest * dst) static
Definition at line 905 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_SetPublishingModeRequest_encodeBinary()
static UA_INLINE UA_StatusCode UA_SetPublishingModeRequest_encodeBinary (const UA_SetPublishingModeRequest * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 901 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_SetPublishingModeResponse_calcSizeBinary()
static UA_INLINE size_t UA_SetPublishingModeResponse_calcSizeBinary (const UA_SetPublishingModeResponse * src) static
Definition at line 1569 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_SetPublishingModeResponse_decodeBinary()
static UA_INLINE UA_StatusCode UA_SetPublishingModeResponse_decodeBinary (const UA_ByteString * src, size_t * offset, UA_SetPublishingModeResponse * dst) static
Definition at line 1577 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_SetPublishingModeResponse_encodeBinary()
static UA_INLINE UA_StatusCode UA_SetPublishingModeResponse_encodeBinary (const UA_SetPublishingModeResponse * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 1573 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_SetTriggeringRequest_calcSizeBinary()
static UA_INLINE size_t UA_SetTriggeringRequest_calcSizeBinary (const UA_SetTriggeringRequest * src) static
Definition at line 2185 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_SetTriggeringRequest_decodeBinary()
static UA_INLINE UA_StatusCode UA_SetTriggeringRequest_decodeBinary (const UA_ByteString * src, size_t * offset, UA_SetTriggeringRequest * dst) static
Definition at line 2193 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_SetTriggeringRequest_encodeBinary()
static UA_INLINE UA_StatusCode UA_SetTriggeringRequest_encodeBinary (const UA_SetTriggeringRequest * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 2189 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_SetTriggeringResponse_calcSizeBinary()
static UA_INLINE size_t UA_SetTriggeringResponse_calcSizeBinary (const UA_SetTriggeringResponse * src) static
Definition at line 1863 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_SetTriggeringResponse_decodeBinary()
static UA_INLINE UA_StatusCode UA_SetTriggeringResponse_decodeBinary (const UA_ByteString * src, size_t * offset, UA_SetTriggeringResponse * dst) static
Definition at line 1871 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_SetTriggeringResponse_encodeBinary()
static UA_INLINE UA_StatusCode UA_SetTriggeringResponse_encodeBinary (const UA_SetTriggeringResponse * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 1867 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_SignatureData_calcSizeBinary()
static UA_INLINE size_t UA_SignatureData_calcSizeBinary (const UA_SignatureData * src) static
Definition at line 575 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_SignatureData_decodeBinary()
static UA_INLINE UA_StatusCode UA_SignatureData_decodeBinary (const UA_ByteString * src, size_t * offset, UA_SignatureData * dst) static
Definition at line 583 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_SignatureData_encodeBinary()
static UA_INLINE UA_StatusCode UA_SignatureData_encodeBinary (const UA_SignatureData * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 579 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_SignedSoftwareCertificate_calcSizeBinary()
static UA_INLINE size_t UA_SignedSoftwareCertificate_calcSizeBinary (const UA_SignedSoftwareCertificate * src) static
Definition at line 1023 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_SignedSoftwareCertificate_decodeBinary()
static UA_INLINE UA_StatusCode UA_SignedSoftwareCertificate_decodeBinary (const UA_ByteString * src, size_t * offset, UA_SignedSoftwareCertificate * dst) static
Definition at line 1031 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_SignedSoftwareCertificate_encodeBinary()
static UA_INLINE UA_StatusCode UA_SignedSoftwareCertificate_encodeBinary (const UA_SignedSoftwareCertificate * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 1027 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_SimpleAttributeOperand_calcSizeBinary()
static UA_INLINE size_t UA_SimpleAttributeOperand_calcSizeBinary (const UA_SimpleAttributeOperand * src) static
Definition at line 1877 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_SimpleAttributeOperand_decodeBinary()
static UA_INLINE UA_StatusCode UA_SimpleAttributeOperand_decodeBinary (const UA_ByteString * src, size_t * offset, UA_SimpleAttributeOperand * dst) static
Definition at line 1885 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_SimpleAttributeOperand_encodeBinary()
static UA_INLINE UA_StatusCode UA_SimpleAttributeOperand_encodeBinary (const UA_SimpleAttributeOperand * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 1881 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_StatusChangeNotification_calcSizeBinary()
static UA_INLINE size_t UA_StatusChangeNotification_calcSizeBinary (const UA_StatusChangeNotification * src) static
Definition at line 1583 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_StatusChangeNotification_decodeBinary()
static UA_INLINE UA_StatusCode UA_StatusChangeNotification_decodeBinary (const UA_ByteString * src, size_t * offset, UA_StatusChangeNotification * dst) static
Definition at line 1591 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_StatusChangeNotification_encodeBinary()
static UA_INLINE UA_StatusCode UA_StatusChangeNotification_encodeBinary (const UA_StatusChangeNotification * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 1587 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_StatusCode_calcSizeBinary()
static UA_INLINE size_t UA_StatusCode_calcSizeBinary (const UA_StatusCode * src) static
Definition at line 267 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_StatusCode_decodeBinary()
static UA_INLINE UA_StatusCode UA_StatusCode_decodeBinary (const UA_ByteString * src, size_t * offset, UA_StatusCode * dst) static
Definition at line 275 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_StatusCode_encodeBinary()
static UA_INLINE UA_StatusCode UA_StatusCode_encodeBinary (const UA_StatusCode * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 271 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_String_calcSizeBinary()
static UA_INLINE size_t UA_String_calcSizeBinary (const UA_String * src) static
Definition at line 169 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_String_decodeBinary()
static UA_INLINE UA_StatusCode UA_String_decodeBinary (const UA_ByteString * src, size_t * offset, UA_String * dst) static
Definition at line 177 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_String_encodeBinary()
static UA_INLINE UA_StatusCode UA_String_encodeBinary (const UA_String * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 173 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_SubscriptionAcknowledgement_calcSizeBinary()
static UA_INLINE size_t UA_SubscriptionAcknowledgement_calcSizeBinary (const UA_SubscriptionAcknowledgement * src) static
Definition at line 1149 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_SubscriptionAcknowledgement_decodeBinary()
static UA_INLINE UA_StatusCode UA_SubscriptionAcknowledgement_decodeBinary (const UA_ByteString * src, size_t * offset, UA_SubscriptionAcknowledgement * dst) static
Definition at line 1157 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_SubscriptionAcknowledgement_encodeBinary()
static UA_INLINE UA_StatusCode UA_SubscriptionAcknowledgement_encodeBinary (const UA_SubscriptionAcknowledgement * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 1153 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_TimestampsToReturn_calcSizeBinary()
static UA_INLINE size_t UA_TimestampsToReturn_calcSizeBinary (const UA_TimestampsToReturn * src) static
Definition at line 827 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_TimestampsToReturn_decodeBinary()
static UA_INLINE UA_StatusCode UA_TimestampsToReturn_decodeBinary (const UA_ByteString * src, size_t * offset, UA_TimestampsToReturn * dst) static
Definition at line 835 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_TimestampsToReturn_encodeBinary()
static UA_INLINE UA_StatusCode UA_TimestampsToReturn_encodeBinary (const UA_TimestampsToReturn * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 831 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_TranslateBrowsePathsToNodeIdsRequest_calcSizeBinary()
static UA_INLINE size_t UA_TranslateBrowsePathsToNodeIdsRequest_calcSizeBinary (const UA_TranslateBrowsePathsToNodeIdsRequest * src) static
Definition at line 2465 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_TranslateBrowsePathsToNodeIdsRequest_decodeBinary()
static UA_INLINE UA_StatusCode UA_TranslateBrowsePathsToNodeIdsRequest_decodeBinary (const UA_ByteString * src, size_t * offset, UA_TranslateBrowsePathsToNodeIdsRequest * dst) static
Definition at line 2473 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_TranslateBrowsePathsToNodeIdsRequest_encodeBinary()
static UA_INLINE UA_StatusCode UA_TranslateBrowsePathsToNodeIdsRequest_encodeBinary (const UA_TranslateBrowsePathsToNodeIdsRequest * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 2469 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_TranslateBrowsePathsToNodeIdsResponse_calcSizeBinary()
static UA_INLINE size_t UA_TranslateBrowsePathsToNodeIdsResponse_calcSizeBinary (const UA_TranslateBrowsePathsToNodeIdsResponse * src) static
Definition at line 2535 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_TranslateBrowsePathsToNodeIdsResponse_decodeBinary()
static UA_INLINE UA_StatusCode UA_TranslateBrowsePathsToNodeIdsResponse_decodeBinary (const UA_ByteString * src, size_t * offset, UA_TranslateBrowsePathsToNodeIdsResponse * dst) static
Definition at line 2543 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_TranslateBrowsePathsToNodeIdsResponse_encodeBinary()
static UA_INLINE UA_StatusCode UA_TranslateBrowsePathsToNodeIdsResponse_encodeBinary (const UA_TranslateBrowsePathsToNodeIdsResponse * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 2539 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_UInt16_calcSizeBinary()
static UA_INLINE size_t UA_UInt16_calcSizeBinary (const UA_UInt16 * src) static
Definition at line 71 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_UInt16_decodeBinary()
static UA_INLINE UA_StatusCode UA_UInt16_decodeBinary (const UA_ByteString * src, size_t * offset, UA_UInt16 * dst) static
Definition at line 79 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_UInt16_encodeBinary()
static UA_INLINE UA_StatusCode UA_UInt16_encodeBinary (const UA_UInt16 * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 75 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_UInt32_calcSizeBinary()
static UA_INLINE size_t UA_UInt32_calcSizeBinary (const UA_UInt32 * src) static
Definition at line 99 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_UInt32_decodeBinary()
static UA_INLINE UA_StatusCode UA_UInt32_decodeBinary (const UA_ByteString * src, size_t * offset, UA_UInt32 * dst) static
Definition at line 107 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_UInt32_encodeBinary()
static UA_INLINE UA_StatusCode UA_UInt32_encodeBinary (const UA_UInt32 * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 103 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_UInt64_calcSizeBinary()
static UA_INLINE size_t UA_UInt64_calcSizeBinary (const UA_UInt64 * src) static
Definition at line 127 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_UInt64_decodeBinary()
static UA_INLINE UA_StatusCode UA_UInt64_decodeBinary (const UA_ByteString * src, size_t * offset, UA_UInt64 * dst) static
Definition at line 135 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_UInt64_encodeBinary()
static UA_INLINE UA_StatusCode UA_UInt64_encodeBinary (const UA_UInt64 * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 131 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_UnregisterNodesRequest_calcSizeBinary()
static UA_INLINE size_t UA_UnregisterNodesRequest_calcSizeBinary (const UA_UnregisterNodesRequest * src) static
Definition at line 1835 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_UnregisterNodesRequest_decodeBinary()
static UA_INLINE UA_StatusCode UA_UnregisterNodesRequest_decodeBinary (const UA_ByteString * src, size_t * offset, UA_UnregisterNodesRequest * dst) static
Definition at line 1843 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_UnregisterNodesRequest_encodeBinary()
static UA_INLINE UA_StatusCode UA_UnregisterNodesRequest_encodeBinary (const UA_UnregisterNodesRequest * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 1839 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_UnregisterNodesResponse_calcSizeBinary()
static UA_INLINE size_t UA_UnregisterNodesResponse_calcSizeBinary (const UA_UnregisterNodesResponse * src) static
Definition at line 1429 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_UnregisterNodesResponse_decodeBinary()
static UA_INLINE UA_StatusCode UA_UnregisterNodesResponse_decodeBinary (const UA_ByteString * src, size_t * offset, UA_UnregisterNodesResponse * dst) static
Definition at line 1437 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_UnregisterNodesResponse_encodeBinary()
static UA_INLINE UA_StatusCode UA_UnregisterNodesResponse_encodeBinary (const UA_UnregisterNodesResponse * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 1433 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_UserIdentityToken_calcSizeBinary()
static UA_INLINE size_t UA_UserIdentityToken_calcSizeBinary (const UA_UserIdentityToken * src) static
Definition at line 519 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_UserIdentityToken_decodeBinary()
static UA_INLINE UA_StatusCode UA_UserIdentityToken_decodeBinary (const UA_ByteString * src, size_t * offset, UA_UserIdentityToken * dst) static
Definition at line 527 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_UserIdentityToken_encodeBinary()
static UA_INLINE UA_StatusCode UA_UserIdentityToken_encodeBinary (const UA_UserIdentityToken * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 523 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_UserNameIdentityToken_calcSizeBinary()
static UA_INLINE size_t UA_UserNameIdentityToken_calcSizeBinary (const UA_UserNameIdentityToken * src) static
Definition at line 1821 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_UserNameIdentityToken_decodeBinary()
static UA_INLINE UA_StatusCode UA_UserNameIdentityToken_decodeBinary (const UA_ByteString * src, size_t * offset, UA_UserNameIdentityToken * dst) static
Definition at line 1829 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_UserNameIdentityToken_encodeBinary()
static UA_INLINE UA_StatusCode UA_UserNameIdentityToken_encodeBinary (const UA_UserNameIdentityToken * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 1825 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_UserTokenPolicy_calcSizeBinary()
static UA_INLINE size_t UA_UserTokenPolicy_calcSizeBinary (const UA_UserTokenPolicy * src) static
Definition at line 1457 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_UserTokenPolicy_decodeBinary()
static UA_INLINE UA_StatusCode UA_UserTokenPolicy_decodeBinary (const UA_ByteString * src, size_t * offset, UA_UserTokenPolicy * dst) static
Definition at line 1465 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_UserTokenPolicy_encodeBinary()
static UA_INLINE UA_StatusCode UA_UserTokenPolicy_encodeBinary (const UA_UserTokenPolicy * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 1461 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_UserTokenType_calcSizeBinary()
static UA_INLINE size_t UA_UserTokenType_calcSizeBinary (const UA_UserTokenType * src) static
Definition at line 1387 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_UserTokenType_decodeBinary()
static UA_INLINE UA_StatusCode UA_UserTokenType_decodeBinary (const UA_ByteString * src, size_t * offset, UA_UserTokenType * dst) static
Definition at line 1395 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_UserTokenType_encodeBinary()
static UA_INLINE UA_StatusCode UA_UserTokenType_encodeBinary (const UA_UserTokenType * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 1391 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_UtcTime_calcSizeBinary()
static UA_INLINE size_t UA_UtcTime_calcSizeBinary (const UA_UtcTime * src) static
Definition at line 505 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_UtcTime_decodeBinary()
static UA_INLINE UA_StatusCode UA_UtcTime_decodeBinary (const UA_ByteString * src, size_t * offset, UA_UtcTime * dst) static
Definition at line 513 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_UtcTime_encodeBinary()
static UA_INLINE UA_StatusCode UA_UtcTime_encodeBinary (const UA_UtcTime * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 509 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_VariableAttributes_calcSizeBinary()
static UA_INLINE size_t UA_VariableAttributes_calcSizeBinary (const UA_VariableAttributes * src) static
Definition at line 393 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_VariableAttributes_decodeBinary()
static UA_INLINE UA_StatusCode UA_VariableAttributes_decodeBinary (const UA_ByteString * src, size_t * offset, UA_VariableAttributes * dst) static
Definition at line 401 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_VariableAttributes_encodeBinary()
static UA_INLINE UA_StatusCode UA_VariableAttributes_encodeBinary (const UA_VariableAttributes * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 397 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_VariableTypeAttributes_calcSizeBinary()
static UA_INLINE size_t UA_VariableTypeAttributes_calcSizeBinary (const UA_VariableTypeAttributes * src) static
Definition at line 631 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_VariableTypeAttributes_decodeBinary()
static UA_INLINE UA_StatusCode UA_VariableTypeAttributes_decodeBinary (const UA_ByteString * src, size_t * offset, UA_VariableTypeAttributes * dst) static
Definition at line 639 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_VariableTypeAttributes_encodeBinary()
static UA_INLINE UA_StatusCode UA_VariableTypeAttributes_encodeBinary (const UA_VariableTypeAttributes * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 635 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_Variant_calcSizeBinary()
static UA_INLINE size_t UA_Variant_calcSizeBinary (const UA_Variant * src) static
Definition at line 337 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_Variant_decodeBinary()
static UA_INLINE UA_StatusCode UA_Variant_decodeBinary (const UA_ByteString * src, size_t * offset, UA_Variant * dst) static
Definition at line 345 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_Variant_encodeBinary()
static UA_INLINE UA_StatusCode UA_Variant_encodeBinary (const UA_Variant * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 341 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_ViewAttributes_calcSizeBinary()
static UA_INLINE size_t UA_ViewAttributes_calcSizeBinary (const UA_ViewAttributes * src) static
Definition at line 365 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_ViewAttributes_decodeBinary()
static UA_INLINE UA_StatusCode UA_ViewAttributes_decodeBinary (const UA_ByteString * src, size_t * offset, UA_ViewAttributes * dst) static
Definition at line 373 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_ViewAttributes_encodeBinary()
static UA_INLINE UA_StatusCode UA_ViewAttributes_encodeBinary (const UA_ViewAttributes * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 369 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_ViewDescription_calcSizeBinary()
static UA_INLINE size_t UA_ViewDescription_calcSizeBinary (const UA_ViewDescription * src) static
Definition at line 1555 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_ViewDescription_decodeBinary()
static UA_INLINE UA_StatusCode UA_ViewDescription_decodeBinary (const UA_ByteString * src, size_t * offset, UA_ViewDescription * dst) static
Definition at line 1563 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_ViewDescription_encodeBinary()
static UA_INLINE UA_StatusCode UA_ViewDescription_encodeBinary (const UA_ViewDescription * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 1559 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_WriteRequest_calcSizeBinary()
static UA_INLINE size_t UA_WriteRequest_calcSizeBinary (const UA_WriteRequest * src) static
Definition at line 2367 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_WriteRequest_decodeBinary()
static UA_INLINE UA_StatusCode UA_WriteRequest_decodeBinary (const UA_ByteString * src, size_t * offset, UA_WriteRequest * dst) static
Definition at line 2375 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_WriteRequest_encodeBinary()
static UA_INLINE UA_StatusCode UA_WriteRequest_encodeBinary (const UA_WriteRequest * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 2371 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_WriteResponse_calcSizeBinary()
static UA_INLINE size_t UA_WriteResponse_calcSizeBinary (const UA_WriteResponse * src) static
Definition at line 1051 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_WriteResponse_decodeBinary()
static UA_INLINE UA_StatusCode UA_WriteResponse_decodeBinary (const UA_ByteString * src, size_t * offset, UA_WriteResponse * dst) static
Definition at line 1059 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_WriteResponse_encodeBinary()
static UA_INLINE UA_StatusCode UA_WriteResponse_encodeBinary (const UA_WriteResponse * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 1055 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_WriteValue_calcSizeBinary()
static UA_INLINE size_t UA_WriteValue_calcSizeBinary (const UA_WriteValue * src) static
Definition at line 1191 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_WriteValue_decodeBinary()
static UA_INLINE UA_StatusCode UA_WriteValue_decodeBinary (const UA_ByteString * src, size_t * offset, UA_WriteValue * dst) static
Definition at line 1199 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_WriteValue_encodeBinary()
static UA_INLINE UA_StatusCode UA_WriteValue_encodeBinary (const UA_WriteValue * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 1195 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_X509IdentityToken_calcSizeBinary()
static UA_INLINE size_t UA_X509IdentityToken_calcSizeBinary (const UA_X509IdentityToken * src) static
Definition at line 533 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_X509IdentityToken_decodeBinary()
static UA_INLINE UA_StatusCode UA_X509IdentityToken_decodeBinary (const UA_ByteString * src, size_t * offset, UA_X509IdentityToken * dst) static
Definition at line 541 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_X509IdentityToken_encodeBinary()
static UA_INLINE UA_StatusCode UA_X509IdentityToken_encodeBinary (const UA_X509IdentityToken * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 537 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.
UA_XmlElement_calcSizeBinary()
static UA_INLINE size_t UA_XmlElement_calcSizeBinary (const UA_XmlElement * src) static
Definition at line 225 of file types_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TYPES.
UA_XmlElement_decodeBinary()
static UA_INLINE UA_StatusCode UA_XmlElement_decodeBinary (const UA_ByteString * src, size_t * offset, UA_XmlElement * dst) static
Definition at line 233 of file types_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TYPES.
UA_XmlElement_encodeBinary()
static UA_INLINE UA_StatusCode UA_XmlElement_encodeBinary (const UA_XmlElement * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 229 of file types_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TYPES.