Project Template: Opc.Ua.RegisteredServer Class Reference
Opc.Ua.RegisteredServer Class Reference
Public Member Functions
RegisteredServer ()
The default constructor.
virtual void Encode (IEncoder encoder)
virtual void Decode (IDecoder decoder)
virtual bool IsEqual (IEncodeable encodeable)
virtual object Clone ()
new object MemberwiseClone ()
Properties
string ServerUri [get, set]
string ProductUri [get, set]
LocalizedTextCollection ServerNames [get, set]
ApplicationType ServerType [get, set]
string GatewayServerUri [get, set]
StringCollection DiscoveryUrls [get, set]
string SemaphoreFilePath [get, set]
bool IsOnline [get, set]
virtual ExpandedNodeId TypeId [get]
virtual ExpandedNodeId BinaryEncodingId [get]
virtual ExpandedNodeId XmlEncodingId [get]
Detailed Description
<exclude>
Definition at line 26559 of file Opc.Ua.DataTypes.cs.
Constructor & Destructor Documentation
RegisteredServer()
Opc.Ua.RegisteredServer.RegisteredServer () inline
The default constructor.
Definition at line 26565 of file Opc.Ua.DataTypes.cs.
Member Function Documentation
Clone()
virtual object Opc.Ua.RegisteredServer.Clone () inline virtual
Definition at line 26771 of file Opc.Ua.DataTypes.cs.
Referenced by Opc.Ua.RegisterServerRequest.MemberwiseClone(), and Opc.Ua.RegisterServer2Request.MemberwiseClone().
Decode()
virtual void Opc.Ua.RegisteredServer.Decode (IDecoder decoder) inline virtual
Definition at line 26726 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
Encode()
virtual void Opc.Ua.RegisteredServer.Encode (IEncoder encoder) inline virtual
Definition at line 26709 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
IsEqual()
virtual bool Opc.Ua.RegisteredServer.IsEqual (IEncodeable encodeable) inline virtual
Definition at line 26743 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Object.
MemberwiseClone()
new object Opc.Ua.RegisteredServer.MemberwiseClone () inline
Definition at line 26778 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.RegisteredServer.MemberwiseClone(), and Opc.Ua.Namespaces.OpcUaXsd.
Referenced by Opc.Ua.RegisteredServer.MemberwiseClone().
Property Documentation
BinaryEncodingId
virtual ExpandedNodeId Opc.Ua.RegisteredServer.BinaryEncodingId get
Definition at line 26698 of file Opc.Ua.DataTypes.cs.
DiscoveryUrls
StringCollection Opc.Ua.RegisteredServer.DiscoveryUrls get set
Definition at line 26655 of file Opc.Ua.DataTypes.cs.
GatewayServerUri
string Opc.Ua.RegisteredServer.GatewayServerUri get set
Definition at line 26645 of file Opc.Ua.DataTypes.cs.
IsOnline
bool Opc.Ua.RegisteredServer.IsOnline get set
Definition at line 26683 of file Opc.Ua.DataTypes.cs.
ProductUri
string Opc.Ua.RegisteredServer.ProductUri get set
Definition at line 26607 of file Opc.Ua.DataTypes.cs.
SemaphoreFilePath
string Opc.Ua.RegisteredServer.SemaphoreFilePath get set
Definition at line 26675 of file Opc.Ua.DataTypes.cs.
ServerNames
LocalizedTextCollection Opc.Ua.RegisteredServer.ServerNames get set
Definition at line 26617 of file Opc.Ua.DataTypes.cs.
ServerType
ApplicationType Opc.Ua.RegisteredServer.ServerType get set
Definition at line 26637 of file Opc.Ua.DataTypes.cs.
ServerUri
string Opc.Ua.RegisteredServer.ServerUri get set
Definition at line 26599 of file Opc.Ua.DataTypes.cs.
TypeId
virtual ExpandedNodeId Opc.Ua.RegisteredServer.TypeId get
Definition at line 26692 of file Opc.Ua.DataTypes.cs.
XmlEncodingId
virtual ExpandedNodeId Opc.Ua.RegisteredServer.XmlEncodingId get
Definition at line 26704 of file Opc.Ua.DataTypes.cs.
The documentation for this class was generated from the following file:
Opc.Ua.DataTypes.cs