Project Template: Opc.Ua.StructureDefinition Class Reference
Opc.Ua.StructureDefinition Class Reference
Public Member Functions
StructureDefinition ()
The default constructor.
override void Encode (IEncoder encoder)
override void Decode (IDecoder decoder)
override bool IsEqual (IEncodeable encodeable)
override object Clone ()
new object MemberwiseClone ()
Public Member Functions inherited from Opc.Ua.DataTypeDefinition
DataTypeDefinition ()
The default constructor.
new object MemberwiseClone ()
Properties
NodeId DefaultEncodingId [get, set]
NodeId BaseDataType [get, set]
StructureType StructureType [get, set]
StructureFieldCollection Fields [get, set]
override ExpandedNodeId TypeId [get]
override ExpandedNodeId BinaryEncodingId [get]
override ExpandedNodeId XmlEncodingId [get]
Properties inherited from Opc.Ua.DataTypeDefinition
virtual ExpandedNodeId TypeId [get]
virtual ExpandedNodeId BinaryEncodingId [get]
virtual ExpandedNodeId XmlEncodingId [get]
Detailed Description
<exclude>
Definition at line 18902 of file Opc.Ua.DataTypes.cs.
Constructor & Destructor Documentation
StructureDefinition()
Opc.Ua.StructureDefinition.StructureDefinition () inline
The default constructor.
Definition at line 18908 of file Opc.Ua.DataTypes.cs.
Member Function Documentation
Clone()
override object Opc.Ua.StructureDefinition.Clone () inline virtual
Reimplemented from Opc.Ua.DataTypeDefinition.
Definition at line 19057 of file Opc.Ua.DataTypes.cs.
Referenced by Opc.Ua.StructureDescription.MemberwiseClone().
Decode()
override void Opc.Ua.StructureDefinition.Decode (IDecoder decoder) inline virtual
Reimplemented from Opc.Ua.DataTypeDefinition.
Definition at line 19017 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
Encode()
override void Opc.Ua.StructureDefinition.Encode (IEncoder encoder) inline virtual
Reimplemented from Opc.Ua.DataTypeDefinition.
Definition at line 19002 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
IsEqual()
override bool Opc.Ua.StructureDefinition.IsEqual (IEncodeable encodeable) inline virtual
Reimplemented from Opc.Ua.DataTypeDefinition.
Definition at line 19032 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Object.
MemberwiseClone()
new object Opc.Ua.StructureDefinition.MemberwiseClone () inline
Definition at line 19064 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.StructureFieldCollection.Clone(), Opc.Ua.StructureDefinition.MemberwiseClone(), Opc.Ua.NodeId, and Opc.Ua.Namespaces.OpcUaXsd.
Referenced by Opc.Ua.StructureDefinition.MemberwiseClone().
Property Documentation
BaseDataType
NodeId Opc.Ua.StructureDefinition.BaseDataType get set
Definition at line 18946 of file Opc.Ua.DataTypes.cs.
BinaryEncodingId
override ExpandedNodeId Opc.Ua.StructureDefinition.BinaryEncodingId get
Definition at line 18991 of file Opc.Ua.DataTypes.cs.
DefaultEncodingId
NodeId Opc.Ua.StructureDefinition.DefaultEncodingId get set
Definition at line 18938 of file Opc.Ua.DataTypes.cs.
Fields
StructureFieldCollection Opc.Ua.StructureDefinition.Fields get set
Definition at line 18964 of file Opc.Ua.DataTypes.cs.
StructureType
StructureType Opc.Ua.StructureDefinition.StructureType get set
Definition at line 18954 of file Opc.Ua.DataTypes.cs.
TypeId
override ExpandedNodeId Opc.Ua.StructureDefinition.TypeId get
Definition at line 18985 of file Opc.Ua.DataTypes.cs.
XmlEncodingId
override ExpandedNodeId Opc.Ua.StructureDefinition.XmlEncodingId get
Definition at line 18997 of file Opc.Ua.DataTypes.cs.
The documentation for this class was generated from the following file:
Opc.Ua.DataTypes.cs