Information Modeller: Model_Factory::DeviceBuilder Class Reference
Model_Factory::DeviceBuilder Class Reference
This class constructs an instance of Model_Factory::DevicImpl as a Infromation_Model::Device.
#include <DeviceBuilder.hpp>
Public Member Functions
DeviceBuilder (const std::string NAME, const std::string REF_ID, const std::string DESC)
std::string addDeviceElementGroup (const std::string NAME, const std::string DESC)
This calls DeviceImpl::addDeviceElementGroup() method, whcih sets a single instance of Information_Model::DeviceElementGroup within. This method should be only called once per device construction!
std::string addDeviceElement (const std::string NAME, const std::string DESC, Information_Model::ElementType type)
This method calls DeviceElementGroupImpl::addDeviceElement() method to create an instance of Information_Model:DeviceElement class.
std::string addDeviceElement (const std::string GROUP_REFID, const std::string NAME, const std::string DESC, Information_Model::ElementType type)
std::unique_ptr< Information_Model::Device > getDevice ()
This method returns a pointer with full ownership rights.
Detailed Description
This class constructs an instance of Model_Factory::DevicImpl as a Infromation_Model::Device.
Author
Dovydas Girdvainis
Date
18.07.2019
Definition at line 22 of file DeviceBuilder.hpp.
Constructor & Destructor Documentation
DeviceBuilder()
DeviceBuilder::DeviceBuilder (const std::string NAME, const std::string REF_ID, const std::string DESC)
Definition at line 10 of file DeviceBuilder.cpp.
Member Function Documentation
addDeviceElement() [1/2]
string DeviceBuilder::addDeviceElement (const std::string NAME, const std::string DESC, Information_Model::ElementType type)
This method calls DeviceElementGroupImpl::addDeviceElement() method to create an instance of Information_Model:DeviceElement class.
Parameters
NAME
DESC
type
Returns
std::string Reference ID of Information_Model:DeviceElement instance
Definition at line 23 of file DeviceBuilder.cpp.
References Model_Factory::DeviceElementGroupImpl::addDeviceElement().
Referenced by buildDeviceFromAFunction(), and main().
addDeviceElement() [2/2]
string DeviceBuilder::addDeviceElement (const std::string GROUP_REFID, const std::string NAME, const std::string DESC, Information_Model::ElementType type)
Definition at line 36 of file DeviceBuilder.cpp.
References Information_Model::NamedElement::getElementRefId(), Model_Factory::DeviceElementGroupImpl::getSubelement(), Model_Factory::DeviceElementGroupImpl::getSubelements(), and Information_Model::Group.
addDeviceElementGroup()
string DeviceBuilder::addDeviceElementGroup (const std::string NAME, const std::string DESC)
This calls DeviceImpl::addDeviceElementGroup() method, whcih sets a single instance of Information_Model::DeviceElementGroup within. This method should be only called once per device construction!
If called more than once, it will override the previous instance of DeviceImpl: DeviceImpl::device_element_group If you want to add DeviceElementGroup instances, you need to call DeviceBuilder::addDeviceElement()
Parameters
NAME
DESC
Returns
std::string Reference ID of DeviceImpl: DeviceImpl::device_element_group
Definition at line 17 of file DeviceBuilder.cpp.
References Model_Factory::DeviceImpl::addDeviceElementGroup().
Referenced by buildDeviceFromAFunction(), and main().
getDevice()
unique_ptr< Information_Model::Device > DeviceBuilder::getDevice ()
This method returns a pointer with full ownership rights.
Attention
If this pointer is not saved by the caller, it will be cleaned up by the Garbadge collector.
Returns
std::unique_ptr<Information_Model::Device>
Definition at line 149 of file DeviceBuilder.cpp.
Referenced by buildDeviceFromAFunction(), and main().
The documentation for this class was generated from the following files:
DeviceBuilder.hpp
DeviceBuilder.cpp