Project Template: namespace0_generated.h File Reference
namespace0_generated.h File Reference
Typedefs
typedef UA_StatusCode(* UA_exchangeEncodeBuffer) (void *handle, UA_Byte **bufPos, const UA_Byte **bufEnd)
Functions
UA_StatusCode UA_encodeBinary (const void *src, const UA_DataType *type, UA_Byte **bufPos, const UA_Byte **bufEnd, UA_exchangeEncodeBuffer exchangeCallback, void *exchangeHandle) UA_FUNC_ATTR_WARN_UNUSED_RESULT
UA_StatusCode UA_decodeBinary (const UA_ByteString *src, size_t *offset, void *dst, const UA_DataType *type, size_t customTypesSize, const UA_DataType *customTypes) UA_FUNC_ATTR_WARN_UNUSED_RESULT
size_t UA_calcSizeBinary (void *p, const UA_DataType *type)
const UA_DataType * UA_findDataTypeByBinary (const UA_NodeId *typeId)
_UA_BEGIN_DECLS UA_StatusCode namespace0_generated (UA_Server *server)
Typedef Documentation
UA_exchangeEncodeBuffer
typedef UA_StatusCode(* UA_exchangeEncodeBuffer) (void *handle, UA_Byte **bufPos, const UA_Byte **bufEnd)
Definition at line 15 of file namespace0_generated.h.
Function Documentation
namespace0_generated()
_UA_BEGIN_DECLS UA_StatusCode namespace0_generated (UA_Server * server)
Definition at line 4352 of file namespace0_generated.c.
References function_namespace0_generated_0_begin(), function_namespace0_generated_0_finish(), function_namespace0_generated_100_begin(), function_namespace0_generated_100_finish(), function_namespace0_generated_101_begin(), function_namespace0_generated_101_finish(), function_namespace0_generated_102_begin(), function_namespace0_generated_102_finish(), function_namespace0_generated_103_begin(), function_namespace0_generated_103_finish(), function_namespace0_generated_104_begin(), function_namespace0_generated_104_finish(), function_namespace0_generated_105_begin(), function_namespace0_generated_105_finish(), function_namespace0_generated_106_begin(), function_namespace0_generated_106_finish(), function_namespace0_generated_107_begin(), function_namespace0_generated_107_finish(), function_namespace0_generated_108_begin(), function_namespace0_generated_108_finish(), function_namespace0_generated_109_begin(), function_namespace0_generated_109_finish(), function_namespace0_generated_10_begin(), function_namespace0_generated_10_finish(), function_namespace0_generated_110_begin(), function_namespace0_generated_110_finish(), function_namespace0_generated_111_begin(), function_namespace0_generated_111_finish(), function_namespace0_generated_112_begin(), function_namespace0_generated_112_finish(), function_namespace0_generated_113_begin(), function_namespace0_generated_113_finish(), function_namespace0_generated_114_begin(), function_namespace0_generated_114_finish(), function_namespace0_generated_115_begin(), function_namespace0_generated_115_finish(), function_namespace0_generated_116_begin(), function_namespace0_generated_116_finish(), function_namespace0_generated_117_begin(), function_namespace0_generated_117_finish(), function_namespace0_generated_118_begin(), function_namespace0_generated_118_finish(), function_namespace0_generated_119_begin(), function_namespace0_generated_119_finish(), function_namespace0_generated_11_begin(), function_namespace0_generated_11_finish(), function_namespace0_generated_120_begin(), function_namespace0_generated_120_finish(), function_namespace0_generated_121_begin(), function_namespace0_generated_121_finish(), function_namespace0_generated_122_begin(), function_namespace0_generated_122_finish(), function_namespace0_generated_123_begin(), function_namespace0_generated_123_finish(), function_namespace0_generated_124_begin(), function_namespace0_generated_124_finish(), function_namespace0_generated_125_begin(), function_namespace0_generated_125_finish(), function_namespace0_generated_126_begin(), function_namespace0_generated_126_finish(), function_namespace0_generated_127_begin(), function_namespace0_generated_127_finish(), function_namespace0_generated_128_begin(), function_namespace0_generated_128_finish(), function_namespace0_generated_129_begin(), function_namespace0_generated_129_finish(), function_namespace0_generated_12_begin(), function_namespace0_generated_12_finish(), function_namespace0_generated_130_begin(), function_namespace0_generated_130_finish(), function_namespace0_generated_131_begin(), function_namespace0_generated_131_finish(), function_namespace0_generated_132_begin(), function_namespace0_generated_132_finish(), function_namespace0_generated_133_begin(), function_namespace0_generated_133_finish(), function_namespace0_generated_134_begin(), function_namespace0_generated_134_finish(), function_namespace0_generated_135_begin(), function_namespace0_generated_135_finish(), function_namespace0_generated_136_begin(), function_namespace0_generated_136_finish(), function_namespace0_generated_137_begin(), function_namespace0_generated_137_finish(), function_namespace0_generated_138_begin(), function_namespace0_generated_138_finish(), function_namespace0_generated_139_begin(), function_namespace0_generated_139_finish(), function_namespace0_generated_13_begin(), function_namespace0_generated_13_finish(), function_namespace0_generated_140_begin(), function_namespace0_generated_140_finish(), function_namespace0_generated_141_begin(), function_namespace0_generated_141_finish(), function_namespace0_generated_142_begin(), function_namespace0_generated_142_finish(), function_namespace0_generated_143_begin(), function_namespace0_generated_143_finish(), function_namespace0_generated_144_begin(), function_namespace0_generated_144_finish(), function_namespace0_generated_145_begin(), function_namespace0_generated_145_finish(), function_namespace0_generated_146_begin(), function_namespace0_generated_146_finish(), function_namespace0_generated_147_begin(), function_namespace0_generated_147_finish(), function_namespace0_generated_148_begin(), function_namespace0_generated_148_finish(), function_namespace0_generated_149_begin(), function_namespace0_generated_149_finish(), function_namespace0_generated_14_begin(), function_namespace0_generated_14_finish(), function_namespace0_generated_150_begin(), function_namespace0_generated_150_finish(), function_namespace0_generated_151_begin(), function_namespace0_generated_151_finish(), function_namespace0_generated_152_begin(), function_namespace0_generated_152_finish(), function_namespace0_generated_153_begin(), function_namespace0_generated_153_finish(), function_namespace0_generated_154_begin(), function_namespace0_generated_154_finish(), function_namespace0_generated_155_begin(), function_namespace0_generated_155_finish(), function_namespace0_generated_156_begin(), function_namespace0_generated_156_finish(), function_namespace0_generated_157_begin(), function_namespace0_generated_157_finish(), function_namespace0_generated_158_begin(), function_namespace0_generated_158_finish(), function_namespace0_generated_159_begin(), function_namespace0_generated_159_finish(), function_namespace0_generated_15_begin(), function_namespace0_generated_15_finish(), function_namespace0_generated_160_begin(), function_namespace0_generated_160_finish(), function_namespace0_generated_161_begin(), function_namespace0_generated_161_finish(), function_namespace0_generated_162_begin(), function_namespace0_generated_162_finish(), function_namespace0_generated_163_begin(), function_namespace0_generated_163_finish(), function_namespace0_generated_164_begin(), function_namespace0_generated_164_finish(), function_namespace0_generated_165_begin(), function_namespace0_generated_165_finish(), function_namespace0_generated_16_begin(), function_namespace0_generated_16_finish(), function_namespace0_generated_17_begin(), function_namespace0_generated_17_finish(), function_namespace0_generated_18_begin(), function_namespace0_generated_18_finish(), function_namespace0_generated_19_begin(), function_namespace0_generated_19_finish(), function_namespace0_generated_1_begin(), function_namespace0_generated_1_finish(), function_namespace0_generated_20_begin(), function_namespace0_generated_20_finish(), function_namespace0_generated_21_begin(), function_namespace0_generated_21_finish(), function_namespace0_generated_22_begin(), function_namespace0_generated_22_finish(), function_namespace0_generated_23_begin(), function_namespace0_generated_23_finish(), function_namespace0_generated_24_begin(), function_namespace0_generated_24_finish(), function_namespace0_generated_25_begin(), function_namespace0_generated_25_finish(), function_namespace0_generated_26_begin(), function_namespace0_generated_26_finish(), function_namespace0_generated_27_begin(), function_namespace0_generated_27_finish(), function_namespace0_generated_28_begin(), function_namespace0_generated_28_finish(), function_namespace0_generated_29_begin(), function_namespace0_generated_29_finish(), function_namespace0_generated_2_begin(), function_namespace0_generated_2_finish(), function_namespace0_generated_30_begin(), function_namespace0_generated_30_finish(), function_namespace0_generated_31_begin(), function_namespace0_generated_31_finish(), function_namespace0_generated_32_begin(), function_namespace0_generated_32_finish(), function_namespace0_generated_33_begin(), function_namespace0_generated_33_finish(), function_namespace0_generated_34_begin(), function_namespace0_generated_34_finish(), function_namespace0_generated_35_begin(), function_namespace0_generated_35_finish(), function_namespace0_generated_36_begin(), function_namespace0_generated_36_finish(), function_namespace0_generated_37_begin(), function_namespace0_generated_37_finish(), function_namespace0_generated_38_begin(), function_namespace0_generated_38_finish(), function_namespace0_generated_39_begin(), function_namespace0_generated_39_finish(), function_namespace0_generated_3_begin(), function_namespace0_generated_3_finish(), function_namespace0_generated_40_begin(), function_namespace0_generated_40_finish(), function_namespace0_generated_41_begin(), function_namespace0_generated_41_finish(), function_namespace0_generated_42_begin(), function_namespace0_generated_42_finish(), function_namespace0_generated_43_begin(), function_namespace0_generated_43_finish(), function_namespace0_generated_44_begin(), function_namespace0_generated_44_finish(), function_namespace0_generated_45_begin(), function_namespace0_generated_45_finish(), function_namespace0_generated_46_begin(), function_namespace0_generated_46_finish(), function_namespace0_generated_47_begin(), function_namespace0_generated_47_finish(), function_namespace0_generated_48_begin(), function_namespace0_generated_48_finish(), function_namespace0_generated_49_begin(), function_namespace0_generated_49_finish(), function_namespace0_generated_4_begin(), function_namespace0_generated_4_finish(), function_namespace0_generated_50_begin(), function_namespace0_generated_50_finish(), function_namespace0_generated_51_begin(), function_namespace0_generated_51_finish(), function_namespace0_generated_52_begin(), function_namespace0_generated_52_finish(), function_namespace0_generated_53_begin(), function_namespace0_generated_53_finish(), function_namespace0_generated_54_begin(), function_namespace0_generated_54_finish(), function_namespace0_generated_55_begin(), function_namespace0_generated_55_finish(), function_namespace0_generated_56_begin(), function_namespace0_generated_56_finish(), function_namespace0_generated_57_begin(), function_namespace0_generated_57_finish(), function_namespace0_generated_58_begin(), function_namespace0_generated_58_finish(), function_namespace0_generated_59_begin(), function_namespace0_generated_59_finish(), function_namespace0_generated_5_begin(), function_namespace0_generated_5_finish(), function_namespace0_generated_60_begin(), function_namespace0_generated_60_finish(), function_namespace0_generated_61_begin(), function_namespace0_generated_61_finish(), function_namespace0_generated_62_begin(), function_namespace0_generated_62_finish(), function_namespace0_generated_63_begin(), function_namespace0_generated_63_finish(), function_namespace0_generated_64_begin(), function_namespace0_generated_64_finish(), function_namespace0_generated_65_begin(), function_namespace0_generated_65_finish(), function_namespace0_generated_66_begin(), function_namespace0_generated_66_finish(), function_namespace0_generated_67_begin(), function_namespace0_generated_67_finish(), function_namespace0_generated_68_begin(), function_namespace0_generated_68_finish(), function_namespace0_generated_69_begin(), function_namespace0_generated_69_finish(), function_namespace0_generated_6_begin(), function_namespace0_generated_6_finish(), function_namespace0_generated_70_begin(), function_namespace0_generated_70_finish(), function_namespace0_generated_71_begin(), function_namespace0_generated_71_finish(), function_namespace0_generated_72_begin(), function_namespace0_generated_72_finish(), function_namespace0_generated_73_begin(), function_namespace0_generated_73_finish(), function_namespace0_generated_74_begin(), function_namespace0_generated_74_finish(), function_namespace0_generated_75_begin(), function_namespace0_generated_75_finish(), function_namespace0_generated_76_begin(), function_namespace0_generated_76_finish(), function_namespace0_generated_77_begin(), function_namespace0_generated_77_finish(), function_namespace0_generated_78_begin(), function_namespace0_generated_78_finish(), function_namespace0_generated_79_begin(), function_namespace0_generated_79_finish(), function_namespace0_generated_7_begin(), function_namespace0_generated_7_finish(), function_namespace0_generated_80_begin(), function_namespace0_generated_80_finish(), function_namespace0_generated_81_begin(), function_namespace0_generated_81_finish(), function_namespace0_generated_82_begin(), function_namespace0_generated_82_finish(), function_namespace0_generated_83_begin(), function_namespace0_generated_83_finish(), function_namespace0_generated_84_begin(), function_namespace0_generated_84_finish(), function_namespace0_generated_85_begin(), function_namespace0_generated_85_finish(), function_namespace0_generated_86_begin(), function_namespace0_generated_86_finish(), function_namespace0_generated_87_begin(), function_namespace0_generated_87_finish(), function_namespace0_generated_88_begin(), function_namespace0_generated_88_finish(), function_namespace0_generated_89_begin(), function_namespace0_generated_89_finish(), function_namespace0_generated_8_begin(), function_namespace0_generated_8_finish(), function_namespace0_generated_90_begin(), function_namespace0_generated_90_finish(), function_namespace0_generated_91_begin(), function_namespace0_generated_91_finish(), function_namespace0_generated_92_begin(), function_namespace0_generated_92_finish(), function_namespace0_generated_93_begin(), function_namespace0_generated_93_finish(), function_namespace0_generated_94_begin(), function_namespace0_generated_94_finish(), function_namespace0_generated_95_begin(), function_namespace0_generated_95_finish(), function_namespace0_generated_96_begin(), function_namespace0_generated_96_finish(), function_namespace0_generated_97_begin(), function_namespace0_generated_97_finish(), function_namespace0_generated_98_begin(), function_namespace0_generated_98_finish(), function_namespace0_generated_99_begin(), function_namespace0_generated_99_finish(), function_namespace0_generated_9_begin(), function_namespace0_generated_9_finish(), nodeset_compiler.nodeset_compiler::ns, and UA_Server_addNamespace().
UA_calcSizeBinary()
size_t UA_calcSizeBinary (void * p, const UA_DataType * type)
Referenced by UA_ActivateSessionRequest_calcSizeBinary(), UA_ActivateSessionResponse_calcSizeBinary(), UA_AddNodesItem_calcSizeBinary(), UA_AddNodesRequest_calcSizeBinary(), UA_AddNodesResponse_calcSizeBinary(), UA_AddNodesResult_calcSizeBinary(), UA_AddReferencesItem_calcSizeBinary(), UA_AddReferencesRequest_calcSizeBinary(), UA_AddReferencesResponse_calcSizeBinary(), UA_AggregateConfiguration_calcSizeBinary(), UA_AggregateFilter_calcSizeBinary(), UA_AnonymousIdentityToken_calcSizeBinary(), UA_ApplicationDescription_calcSizeBinary(), UA_ApplicationType_calcSizeBinary(), UA_Argument_calcSizeBinary(), UA_AsymmetricAlgorithmSecurityHeader_calcSizeBinary(), UA_AttributeOperand_calcSizeBinary(), UA_Boolean_calcSizeBinary(), UA_BrowseDescription_calcSizeBinary(), UA_BrowseDirection_calcSizeBinary(), UA_BrowseNextRequest_calcSizeBinary(), UA_BrowseNextResponse_calcSizeBinary(), UA_BrowsePath_calcSizeBinary(), UA_BrowsePathResult_calcSizeBinary(), UA_BrowsePathTarget_calcSizeBinary(), UA_BrowseRequest_calcSizeBinary(), UA_BrowseResponse_calcSizeBinary(), UA_BrowseResult_calcSizeBinary(), UA_BrowseResultMask_calcSizeBinary(), UA_BuildInfo_calcSizeBinary(), UA_Byte_calcSizeBinary(), UA_ByteString_calcSizeBinary(), UA_CallMethodRequest_calcSizeBinary(), UA_CallMethodResult_calcSizeBinary(), UA_CallRequest_calcSizeBinary(), UA_CallResponse_calcSizeBinary(), UA_ChannelSecurityToken_calcSizeBinary(), UA_ChunkType_calcSizeBinary(), UA_CloseSecureChannelRequest_calcSizeBinary(), UA_CloseSecureChannelResponse_calcSizeBinary(), UA_CloseSessionRequest_calcSizeBinary(), UA_CloseSessionResponse_calcSizeBinary(), UA_ContentFilter_calcSizeBinary(), UA_ContentFilterElement_calcSizeBinary(), UA_ContentFilterElementResult_calcSizeBinary(), UA_ContentFilterResult_calcSizeBinary(), UA_CreateMonitoredItemsRequest_calcSizeBinary(), UA_CreateMonitoredItemsResponse_calcSizeBinary(), UA_CreateSessionRequest_calcSizeBinary(), UA_CreateSessionResponse_calcSizeBinary(), UA_CreateSubscriptionRequest_calcSizeBinary(), UA_CreateSubscriptionResponse_calcSizeBinary(), UA_DataChangeFilter_calcSizeBinary(), UA_DataChangeNotification_calcSizeBinary(), UA_DataChangeTrigger_calcSizeBinary(), UA_DataTypeAttributes_calcSizeBinary(), UA_DataValue_calcSizeBinary(), UA_DateTime_calcSizeBinary(), UA_DeadbandType_calcSizeBinary(), UA_DeleteMonitoredItemsRequest_calcSizeBinary(), UA_DeleteMonitoredItemsResponse_calcSizeBinary(), UA_DeleteNodesItem_calcSizeBinary(), UA_DeleteNodesRequest_calcSizeBinary(), UA_DeleteNodesResponse_calcSizeBinary(), UA_DeleteReferencesItem_calcSizeBinary(), UA_DeleteReferencesRequest_calcSizeBinary(), UA_DeleteReferencesResponse_calcSizeBinary(), UA_DeleteSubscriptionsRequest_calcSizeBinary(), UA_DeleteSubscriptionsResponse_calcSizeBinary(), UA_DiagnosticInfo_calcSizeBinary(), UA_DiscoveryConfiguration_calcSizeBinary(), UA_Double_calcSizeBinary(), UA_Duration_calcSizeBinary(), UA_ElementOperand_calcSizeBinary(), UA_EndpointDescription_calcSizeBinary(), UA_EnumValueType_calcSizeBinary(), UA_EventFieldList_calcSizeBinary(), UA_EventFilter_calcSizeBinary(), UA_EventFilterResult_calcSizeBinary(), UA_EventNotificationList_calcSizeBinary(), UA_ExpandedNodeId_calcSizeBinary(), UA_ExtensionObject_calcSizeBinary(), UA_FilterOperand_calcSizeBinary(), UA_FilterOperator_calcSizeBinary(), UA_FindServersOnNetworkRequest_calcSizeBinary(), UA_FindServersOnNetworkResponse_calcSizeBinary(), UA_FindServersRequest_calcSizeBinary(), UA_FindServersResponse_calcSizeBinary(), UA_Float_calcSizeBinary(), UA_GetEndpointsRequest_calcSizeBinary(), UA_GetEndpointsResponse_calcSizeBinary(), UA_Guid_calcSizeBinary(), UA_Int16_calcSizeBinary(), UA_Int32_calcSizeBinary(), UA_Int64_calcSizeBinary(), UA_IssuedIdentityToken_calcSizeBinary(), UA_LiteralOperand_calcSizeBinary(), UA_LocaleId_calcSizeBinary(), UA_LocalizedText_calcSizeBinary(), UA_MdnsDiscoveryConfiguration_calcSizeBinary(), UA_MessageSecurityMode_calcSizeBinary(), UA_MessageType_calcSizeBinary(), UA_MethodAttributes_calcSizeBinary(), UA_ModifyMonitoredItemsRequest_calcSizeBinary(), UA_ModifyMonitoredItemsResponse_calcSizeBinary(), UA_ModifySubscriptionRequest_calcSizeBinary(), UA_ModifySubscriptionResponse_calcSizeBinary(), UA_MonitoredItemCreateRequest_calcSizeBinary(), UA_MonitoredItemCreateResult_calcSizeBinary(), UA_MonitoredItemModifyRequest_calcSizeBinary(), UA_MonitoredItemModifyResult_calcSizeBinary(), UA_MonitoredItemNotification_calcSizeBinary(), UA_MonitoringMode_calcSizeBinary(), UA_MonitoringParameters_calcSizeBinary(), UA_NodeAttributes_calcSizeBinary(), UA_NodeAttributesMask_calcSizeBinary(), UA_NodeClass_calcSizeBinary(), UA_NodeId_calcSizeBinary(), UA_NotificationMessage_calcSizeBinary(), UA_ObjectAttributes_calcSizeBinary(), UA_ObjectTypeAttributes_calcSizeBinary(), UA_OpenSecureChannelRequest_calcSizeBinary(), UA_OpenSecureChannelResponse_calcSizeBinary(), UA_PublishRequest_calcSizeBinary(), UA_PublishResponse_calcSizeBinary(), UA_QualifiedName_calcSizeBinary(), UA_Range_calcSizeBinary(), UA_ReadRequest_calcSizeBinary(), UA_ReadResponse_calcSizeBinary(), UA_ReadValueId_calcSizeBinary(), UA_RedundancySupport_calcSizeBinary(), UA_ReferenceDescription_calcSizeBinary(), UA_ReferenceTypeAttributes_calcSizeBinary(), UA_RegisteredServer_calcSizeBinary(), UA_RegisterNodesRequest_calcSizeBinary(), UA_RegisterNodesResponse_calcSizeBinary(), UA_RegisterServer2Request_calcSizeBinary(), UA_RegisterServer2Response_calcSizeBinary(), UA_RegisterServerRequest_calcSizeBinary(), UA_RegisterServerResponse_calcSizeBinary(), UA_RelativePath_calcSizeBinary(), UA_RelativePathElement_calcSizeBinary(), UA_RepublishRequest_calcSizeBinary(), UA_RepublishResponse_calcSizeBinary(), UA_RequestHeader_calcSizeBinary(), UA_ResponseHeader_calcSizeBinary(), UA_SByte_calcSizeBinary(), UA_SecureConversationMessageAbortBody_calcSizeBinary(), UA_SecureConversationMessageFooter_calcSizeBinary(), UA_SecureConversationMessageHeader_calcSizeBinary(), UA_SecurityTokenRequestType_calcSizeBinary(), UA_SequenceHeader_calcSizeBinary(), UA_ServerDiagnosticsSummaryDataType_calcSizeBinary(), UA_ServerOnNetwork_calcSizeBinary(), UA_ServerState_calcSizeBinary(), UA_ServerStatusDataType_calcSizeBinary(), UA_ServiceFault_calcSizeBinary(), UA_SetMonitoringModeRequest_calcSizeBinary(), UA_SetMonitoringModeResponse_calcSizeBinary(), UA_SetPublishingModeRequest_calcSizeBinary(), UA_SetPublishingModeResponse_calcSizeBinary(), UA_SetTriggeringRequest_calcSizeBinary(), UA_SetTriggeringResponse_calcSizeBinary(), UA_SignatureData_calcSizeBinary(), UA_SignedSoftwareCertificate_calcSizeBinary(), UA_SimpleAttributeOperand_calcSizeBinary(), UA_StatusChangeNotification_calcSizeBinary(), UA_StatusCode_calcSizeBinary(), UA_String_calcSizeBinary(), UA_SubscriptionAcknowledgement_calcSizeBinary(), UA_SymmetricAlgorithmSecurityHeader_calcSizeBinary(), UA_TcpAcknowledgeMessage_calcSizeBinary(), UA_TcpErrorMessage_calcSizeBinary(), UA_TcpHelloMessage_calcSizeBinary(), UA_TcpMessageHeader_calcSizeBinary(), UA_TimestampsToReturn_calcSizeBinary(), UA_TranslateBrowsePathsToNodeIdsRequest_calcSizeBinary(), UA_TranslateBrowsePathsToNodeIdsResponse_calcSizeBinary(), UA_UInt16_calcSizeBinary(), UA_UInt32_calcSizeBinary(), UA_UInt64_calcSizeBinary(), UA_UnregisterNodesRequest_calcSizeBinary(), UA_UnregisterNodesResponse_calcSizeBinary(), UA_UserIdentityToken_calcSizeBinary(), UA_UserNameIdentityToken_calcSizeBinary(), UA_UserTokenPolicy_calcSizeBinary(), UA_UserTokenType_calcSizeBinary(), UA_UtcTime_calcSizeBinary(), UA_VariableAttributes_calcSizeBinary(), UA_VariableTypeAttributes_calcSizeBinary(), UA_Variant_calcSizeBinary(), UA_ViewAttributes_calcSizeBinary(), UA_ViewDescription_calcSizeBinary(), UA_WriteRequest_calcSizeBinary(), UA_WriteResponse_calcSizeBinary(), UA_WriteValue_calcSizeBinary(), UA_X509IdentityToken_calcSizeBinary(), and UA_XmlElement_calcSizeBinary().
UA_decodeBinary()
UA_StatusCode UA_decodeBinary (const UA_ByteString * src, size_t * offset, void * dst, const UA_DataType * type, size_t customTypesSize, const UA_DataType * customTypes)
Referenced by UA_ActivateSessionRequest_decodeBinary(), UA_ActivateSessionResponse_decodeBinary(), UA_AddNodesItem_decodeBinary(), UA_AddNodesRequest_decodeBinary(), UA_AddNodesResponse_decodeBinary(), UA_AddNodesResult_decodeBinary(), UA_AddReferencesItem_decodeBinary(), UA_AddReferencesRequest_decodeBinary(), UA_AddReferencesResponse_decodeBinary(), UA_AggregateConfiguration_decodeBinary(), UA_AggregateFilter_decodeBinary(), UA_AnonymousIdentityToken_decodeBinary(), UA_ApplicationDescription_decodeBinary(), UA_ApplicationType_decodeBinary(), UA_Argument_decodeBinary(), UA_AsymmetricAlgorithmSecurityHeader_decodeBinary(), UA_AttributeOperand_decodeBinary(), UA_Boolean_decodeBinary(), UA_BrowseDescription_decodeBinary(), UA_BrowseDirection_decodeBinary(), UA_BrowseNextRequest_decodeBinary(), UA_BrowseNextResponse_decodeBinary(), UA_BrowsePath_decodeBinary(), UA_BrowsePathResult_decodeBinary(), UA_BrowsePathTarget_decodeBinary(), UA_BrowseRequest_decodeBinary(), UA_BrowseResponse_decodeBinary(), UA_BrowseResult_decodeBinary(), UA_BrowseResultMask_decodeBinary(), UA_BuildInfo_decodeBinary(), UA_Byte_decodeBinary(), UA_ByteString_decodeBinary(), UA_CallMethodRequest_decodeBinary(), UA_CallMethodResult_decodeBinary(), UA_CallRequest_decodeBinary(), UA_CallResponse_decodeBinary(), UA_ChannelSecurityToken_decodeBinary(), UA_ChunkType_decodeBinary(), UA_CloseSecureChannelRequest_decodeBinary(), UA_CloseSecureChannelResponse_decodeBinary(), UA_CloseSessionRequest_decodeBinary(), UA_CloseSessionResponse_decodeBinary(), UA_ContentFilter_decodeBinary(), UA_ContentFilterElement_decodeBinary(), UA_ContentFilterElementResult_decodeBinary(), UA_ContentFilterResult_decodeBinary(), UA_CreateMonitoredItemsRequest_decodeBinary(), UA_CreateMonitoredItemsResponse_decodeBinary(), UA_CreateSessionRequest_decodeBinary(), UA_CreateSessionResponse_decodeBinary(), UA_CreateSubscriptionRequest_decodeBinary(), UA_CreateSubscriptionResponse_decodeBinary(), UA_DataChangeFilter_decodeBinary(), UA_DataChangeNotification_decodeBinary(), UA_DataChangeTrigger_decodeBinary(), UA_DataTypeAttributes_decodeBinary(), UA_DataValue_decodeBinary(), UA_DateTime_decodeBinary(), UA_DeadbandType_decodeBinary(), UA_DeleteMonitoredItemsRequest_decodeBinary(), UA_DeleteMonitoredItemsResponse_decodeBinary(), UA_DeleteNodesItem_decodeBinary(), UA_DeleteNodesRequest_decodeBinary(), UA_DeleteNodesResponse_decodeBinary(), UA_DeleteReferencesItem_decodeBinary(), UA_DeleteReferencesRequest_decodeBinary(), UA_DeleteReferencesResponse_decodeBinary(), UA_DeleteSubscriptionsRequest_decodeBinary(), UA_DeleteSubscriptionsResponse_decodeBinary(), UA_DiagnosticInfo_decodeBinary(), UA_DiscoveryConfiguration_decodeBinary(), UA_Double_decodeBinary(), UA_Duration_decodeBinary(), UA_ElementOperand_decodeBinary(), UA_EndpointDescription_decodeBinary(), UA_EnumValueType_decodeBinary(), UA_EventFieldList_decodeBinary(), UA_EventFilter_decodeBinary(), UA_EventFilterResult_decodeBinary(), UA_EventNotificationList_decodeBinary(), UA_ExpandedNodeId_decodeBinary(), UA_ExtensionObject_decodeBinary(), UA_FilterOperand_decodeBinary(), UA_FilterOperator_decodeBinary(), UA_FindServersOnNetworkRequest_decodeBinary(), UA_FindServersOnNetworkResponse_decodeBinary(), UA_FindServersRequest_decodeBinary(), UA_FindServersResponse_decodeBinary(), UA_Float_decodeBinary(), UA_GetEndpointsRequest_decodeBinary(), UA_GetEndpointsResponse_decodeBinary(), UA_Guid_decodeBinary(), UA_Int16_decodeBinary(), UA_Int32_decodeBinary(), UA_Int64_decodeBinary(), UA_IssuedIdentityToken_decodeBinary(), UA_LiteralOperand_decodeBinary(), UA_LocaleId_decodeBinary(), UA_LocalizedText_decodeBinary(), UA_MdnsDiscoveryConfiguration_decodeBinary(), UA_MessageSecurityMode_decodeBinary(), UA_MessageType_decodeBinary(), UA_MethodAttributes_decodeBinary(), UA_ModifyMonitoredItemsRequest_decodeBinary(), UA_ModifyMonitoredItemsResponse_decodeBinary(), UA_ModifySubscriptionRequest_decodeBinary(), UA_ModifySubscriptionResponse_decodeBinary(), UA_MonitoredItemCreateRequest_decodeBinary(), UA_MonitoredItemCreateResult_decodeBinary(), UA_MonitoredItemModifyRequest_decodeBinary(), UA_MonitoredItemModifyResult_decodeBinary(), UA_MonitoredItemNotification_decodeBinary(), UA_MonitoringMode_decodeBinary(), UA_MonitoringParameters_decodeBinary(), UA_NodeAttributes_decodeBinary(), UA_NodeAttributesMask_decodeBinary(), UA_NodeClass_decodeBinary(), UA_NodeId_decodeBinary(), UA_NotificationMessage_decodeBinary(), UA_ObjectAttributes_decodeBinary(), UA_ObjectTypeAttributes_decodeBinary(), UA_OpenSecureChannelRequest_decodeBinary(), UA_OpenSecureChannelResponse_decodeBinary(), UA_PublishRequest_decodeBinary(), UA_PublishResponse_decodeBinary(), UA_QualifiedName_decodeBinary(), UA_Range_decodeBinary(), UA_ReadRequest_decodeBinary(), UA_ReadResponse_decodeBinary(), UA_ReadValueId_decodeBinary(), UA_RedundancySupport_decodeBinary(), UA_ReferenceDescription_decodeBinary(), UA_ReferenceTypeAttributes_decodeBinary(), UA_RegisteredServer_decodeBinary(), UA_RegisterNodesRequest_decodeBinary(), UA_RegisterNodesResponse_decodeBinary(), UA_RegisterServer2Request_decodeBinary(), UA_RegisterServer2Response_decodeBinary(), UA_RegisterServerRequest_decodeBinary(), UA_RegisterServerResponse_decodeBinary(), UA_RelativePath_decodeBinary(), UA_RelativePathElement_decodeBinary(), UA_RepublishRequest_decodeBinary(), UA_RepublishResponse_decodeBinary(), UA_RequestHeader_decodeBinary(), UA_ResponseHeader_decodeBinary(), UA_SByte_decodeBinary(), UA_SecureConversationMessageAbortBody_decodeBinary(), UA_SecureConversationMessageFooter_decodeBinary(), UA_SecureConversationMessageHeader_decodeBinary(), UA_SecurityTokenRequestType_decodeBinary(), UA_SequenceHeader_decodeBinary(), UA_ServerDiagnosticsSummaryDataType_decodeBinary(), UA_ServerOnNetwork_decodeBinary(), UA_ServerState_decodeBinary(), UA_ServerStatusDataType_decodeBinary(), UA_ServiceFault_decodeBinary(), UA_SetMonitoringModeRequest_decodeBinary(), UA_SetMonitoringModeResponse_decodeBinary(), UA_SetPublishingModeRequest_decodeBinary(), UA_SetPublishingModeResponse_decodeBinary(), UA_SetTriggeringRequest_decodeBinary(), UA_SetTriggeringResponse_decodeBinary(), UA_SignatureData_decodeBinary(), UA_SignedSoftwareCertificate_decodeBinary(), UA_SimpleAttributeOperand_decodeBinary(), UA_StatusChangeNotification_decodeBinary(), UA_StatusCode_decodeBinary(), UA_String_decodeBinary(), UA_SubscriptionAcknowledgement_decodeBinary(), UA_SymmetricAlgorithmSecurityHeader_decodeBinary(), UA_TcpAcknowledgeMessage_decodeBinary(), UA_TcpErrorMessage_decodeBinary(), UA_TcpHelloMessage_decodeBinary(), UA_TcpMessageHeader_decodeBinary(), UA_TimestampsToReturn_decodeBinary(), UA_TranslateBrowsePathsToNodeIdsRequest_decodeBinary(), UA_TranslateBrowsePathsToNodeIdsResponse_decodeBinary(), UA_UInt16_decodeBinary(), UA_UInt32_decodeBinary(), UA_UInt64_decodeBinary(), UA_UnregisterNodesRequest_decodeBinary(), UA_UnregisterNodesResponse_decodeBinary(), UA_UserIdentityToken_decodeBinary(), UA_UserNameIdentityToken_decodeBinary(), UA_UserTokenPolicy_decodeBinary(), UA_UserTokenType_decodeBinary(), UA_UtcTime_decodeBinary(), UA_VariableAttributes_decodeBinary(), UA_VariableTypeAttributes_decodeBinary(), UA_Variant_decodeBinary(), UA_ViewAttributes_decodeBinary(), UA_ViewDescription_decodeBinary(), UA_WriteRequest_decodeBinary(), UA_WriteResponse_decodeBinary(), UA_WriteValue_decodeBinary(), UA_X509IdentityToken_decodeBinary(), and UA_XmlElement_decodeBinary().
UA_encodeBinary()
UA_StatusCode UA_encodeBinary (const void * src, const UA_DataType * type, UA_Byte ** bufPos, const UA_Byte ** bufEnd, UA_exchangeEncodeBuffer exchangeCallback, void * exchangeHandle)
Referenced by UA_ActivateSessionRequest_encodeBinary(), UA_ActivateSessionResponse_encodeBinary(), UA_AddNodesItem_encodeBinary(), UA_AddNodesRequest_encodeBinary(), UA_AddNodesResponse_encodeBinary(), UA_AddNodesResult_encodeBinary(), UA_AddReferencesItem_encodeBinary(), UA_AddReferencesRequest_encodeBinary(), UA_AddReferencesResponse_encodeBinary(), UA_AggregateConfiguration_encodeBinary(), UA_AggregateFilter_encodeBinary(), UA_AnonymousIdentityToken_encodeBinary(), UA_ApplicationDescription_encodeBinary(), UA_ApplicationType_encodeBinary(), UA_Argument_encodeBinary(), UA_AsymmetricAlgorithmSecurityHeader_encodeBinary(), UA_AttributeOperand_encodeBinary(), UA_Boolean_encodeBinary(), UA_BrowseDescription_encodeBinary(), UA_BrowseDirection_encodeBinary(), UA_BrowseNextRequest_encodeBinary(), UA_BrowseNextResponse_encodeBinary(), UA_BrowsePath_encodeBinary(), UA_BrowsePathResult_encodeBinary(), UA_BrowsePathTarget_encodeBinary(), UA_BrowseRequest_encodeBinary(), UA_BrowseResponse_encodeBinary(), UA_BrowseResult_encodeBinary(), UA_BrowseResultMask_encodeBinary(), UA_BuildInfo_encodeBinary(), UA_Byte_encodeBinary(), UA_ByteString_encodeBinary(), UA_CallMethodRequest_encodeBinary(), UA_CallMethodResult_encodeBinary(), UA_CallRequest_encodeBinary(), UA_CallResponse_encodeBinary(), UA_ChannelSecurityToken_encodeBinary(), UA_ChunkType_encodeBinary(), UA_CloseSecureChannelRequest_encodeBinary(), UA_CloseSecureChannelResponse_encodeBinary(), UA_CloseSessionRequest_encodeBinary(), UA_CloseSessionResponse_encodeBinary(), UA_ContentFilter_encodeBinary(), UA_ContentFilterElement_encodeBinary(), UA_ContentFilterElementResult_encodeBinary(), UA_ContentFilterResult_encodeBinary(), UA_CreateMonitoredItemsRequest_encodeBinary(), UA_CreateMonitoredItemsResponse_encodeBinary(), UA_CreateSessionRequest_encodeBinary(), UA_CreateSessionResponse_encodeBinary(), UA_CreateSubscriptionRequest_encodeBinary(), UA_CreateSubscriptionResponse_encodeBinary(), UA_DataChangeFilter_encodeBinary(), UA_DataChangeNotification_encodeBinary(), UA_DataChangeTrigger_encodeBinary(), UA_DataTypeAttributes_encodeBinary(), UA_DataValue_encodeBinary(), UA_DateTime_encodeBinary(), UA_DeadbandType_encodeBinary(), UA_DeleteMonitoredItemsRequest_encodeBinary(), UA_DeleteMonitoredItemsResponse_encodeBinary(), UA_DeleteNodesItem_encodeBinary(), UA_DeleteNodesRequest_encodeBinary(), UA_DeleteNodesResponse_encodeBinary(), UA_DeleteReferencesItem_encodeBinary(), UA_DeleteReferencesRequest_encodeBinary(), UA_DeleteReferencesResponse_encodeBinary(), UA_DeleteSubscriptionsRequest_encodeBinary(), UA_DeleteSubscriptionsResponse_encodeBinary(), UA_DiagnosticInfo_encodeBinary(), UA_DiscoveryConfiguration_encodeBinary(), UA_Double_encodeBinary(), UA_Duration_encodeBinary(), UA_ElementOperand_encodeBinary(), UA_EndpointDescription_encodeBinary(), UA_EnumValueType_encodeBinary(), UA_EventFieldList_encodeBinary(), UA_EventFilter_encodeBinary(), UA_EventFilterResult_encodeBinary(), UA_EventNotificationList_encodeBinary(), UA_ExpandedNodeId_encodeBinary(), UA_ExtensionObject_encodeBinary(), UA_FilterOperand_encodeBinary(), UA_FilterOperator_encodeBinary(), UA_FindServersOnNetworkRequest_encodeBinary(), UA_FindServersOnNetworkResponse_encodeBinary(), UA_FindServersRequest_encodeBinary(), UA_FindServersResponse_encodeBinary(), UA_Float_encodeBinary(), UA_GetEndpointsRequest_encodeBinary(), UA_GetEndpointsResponse_encodeBinary(), UA_Guid_encodeBinary(), UA_Int16_encodeBinary(), UA_Int32_encodeBinary(), UA_Int64_encodeBinary(), UA_IssuedIdentityToken_encodeBinary(), UA_LiteralOperand_encodeBinary(), UA_LocaleId_encodeBinary(), UA_LocalizedText_encodeBinary(), UA_MdnsDiscoveryConfiguration_encodeBinary(), UA_MessageSecurityMode_encodeBinary(), UA_MessageType_encodeBinary(), UA_MethodAttributes_encodeBinary(), UA_ModifyMonitoredItemsRequest_encodeBinary(), UA_ModifyMonitoredItemsResponse_encodeBinary(), UA_ModifySubscriptionRequest_encodeBinary(), UA_ModifySubscriptionResponse_encodeBinary(), UA_MonitoredItemCreateRequest_encodeBinary(), UA_MonitoredItemCreateResult_encodeBinary(), UA_MonitoredItemModifyRequest_encodeBinary(), UA_MonitoredItemModifyResult_encodeBinary(), UA_MonitoredItemNotification_encodeBinary(), UA_MonitoringMode_encodeBinary(), UA_MonitoringParameters_encodeBinary(), UA_NodeAttributes_encodeBinary(), UA_NodeAttributesMask_encodeBinary(), UA_NodeClass_encodeBinary(), UA_NodeId_encodeBinary(), UA_NotificationMessage_encodeBinary(), UA_ObjectAttributes_encodeBinary(), UA_ObjectTypeAttributes_encodeBinary(), UA_OpenSecureChannelRequest_encodeBinary(), UA_OpenSecureChannelResponse_encodeBinary(), UA_PublishRequest_encodeBinary(), UA_PublishResponse_encodeBinary(), UA_QualifiedName_encodeBinary(), UA_Range_encodeBinary(), UA_ReadRequest_encodeBinary(), UA_ReadResponse_encodeBinary(), UA_ReadValueId_encodeBinary(), UA_RedundancySupport_encodeBinary(), UA_ReferenceDescription_encodeBinary(), UA_ReferenceTypeAttributes_encodeBinary(), UA_RegisteredServer_encodeBinary(), UA_RegisterNodesRequest_encodeBinary(), UA_RegisterNodesResponse_encodeBinary(), UA_RegisterServer2Request_encodeBinary(), UA_RegisterServer2Response_encodeBinary(), UA_RegisterServerRequest_encodeBinary(), UA_RegisterServerResponse_encodeBinary(), UA_RelativePath_encodeBinary(), UA_RelativePathElement_encodeBinary(), UA_RepublishRequest_encodeBinary(), UA_RepublishResponse_encodeBinary(), UA_RequestHeader_encodeBinary(), UA_ResponseHeader_encodeBinary(), UA_SByte_encodeBinary(), UA_SecureConversationMessageAbortBody_encodeBinary(), UA_SecureConversationMessageFooter_encodeBinary(), UA_SecureConversationMessageHeader_encodeBinary(), UA_SecurityTokenRequestType_encodeBinary(), UA_SequenceHeader_encodeBinary(), UA_ServerDiagnosticsSummaryDataType_encodeBinary(), UA_ServerOnNetwork_encodeBinary(), UA_ServerState_encodeBinary(), UA_ServerStatusDataType_encodeBinary(), UA_ServiceFault_encodeBinary(), UA_SetMonitoringModeRequest_encodeBinary(), UA_SetMonitoringModeResponse_encodeBinary(), UA_SetPublishingModeRequest_encodeBinary(), UA_SetPublishingModeResponse_encodeBinary(), UA_SetTriggeringRequest_encodeBinary(), UA_SetTriggeringResponse_encodeBinary(), UA_SignatureData_encodeBinary(), UA_SignedSoftwareCertificate_encodeBinary(), UA_SimpleAttributeOperand_encodeBinary(), UA_StatusChangeNotification_encodeBinary(), UA_StatusCode_encodeBinary(), UA_String_encodeBinary(), UA_SubscriptionAcknowledgement_encodeBinary(), UA_SymmetricAlgorithmSecurityHeader_encodeBinary(), UA_TcpAcknowledgeMessage_encodeBinary(), UA_TcpErrorMessage_encodeBinary(), UA_TcpHelloMessage_encodeBinary(), UA_TcpMessageHeader_encodeBinary(), UA_TimestampsToReturn_encodeBinary(), UA_TranslateBrowsePathsToNodeIdsRequest_encodeBinary(), UA_TranslateBrowsePathsToNodeIdsResponse_encodeBinary(), UA_UInt16_encodeBinary(), UA_UInt32_encodeBinary(), UA_UInt64_encodeBinary(), UA_UnregisterNodesRequest_encodeBinary(), UA_UnregisterNodesResponse_encodeBinary(), UA_UserIdentityToken_encodeBinary(), UA_UserNameIdentityToken_encodeBinary(), UA_UserTokenPolicy_encodeBinary(), UA_UserTokenType_encodeBinary(), UA_UtcTime_encodeBinary(), UA_VariableAttributes_encodeBinary(), UA_VariableTypeAttributes_encodeBinary(), UA_Variant_encodeBinary(), UA_ViewAttributes_encodeBinary(), UA_ViewDescription_encodeBinary(), UA_WriteRequest_encodeBinary(), UA_WriteResponse_encodeBinary(), UA_WriteValue_encodeBinary(), UA_X509IdentityToken_encodeBinary(), and UA_XmlElement_encodeBinary().
UA_findDataTypeByBinary()
const UA_DataType* UA_findDataTypeByBinary (const UA_NodeId * typeId)