Project Template: Opc.Ua.ContentFilterResult Class Reference
Opc.Ua.ContentFilterResult Class Reference
Public Member Functions
ContentFilterResult ()
The default constructor.
virtual void Encode (IEncoder encoder)
virtual void Decode (IDecoder decoder)
virtual bool IsEqual (IEncodeable encodeable)
virtual object Clone ()
new object MemberwiseClone ()
Properties
ContentFilterElementResultCollection ElementResults [get, set]
DiagnosticInfoCollection ElementDiagnosticInfos [get, set]
virtual ExpandedNodeId TypeId [get]
virtual ExpandedNodeId BinaryEncodingId [get]
virtual ExpandedNodeId XmlEncodingId [get]
Detailed Description
<exclude>
Definition at line 43763 of file Opc.Ua.DataTypes.cs.
Constructor & Destructor Documentation
ContentFilterResult()
Opc.Ua.ContentFilterResult.ContentFilterResult () inline
The default constructor.
Definition at line 43769 of file Opc.Ua.DataTypes.cs.
Member Function Documentation
Clone()
virtual object Opc.Ua.ContentFilterResult.Clone () inline virtual
Definition at line 43903 of file Opc.Ua.DataTypes.cs.
Referenced by Opc.Ua.QueryFirstResponse.MemberwiseClone(), and Opc.Ua.EventFilterResult.MemberwiseClone().
Decode()
virtual void Opc.Ua.ContentFilterResult.Decode (IDecoder decoder) inline virtual
Definition at line 43870 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
Encode()
virtual void Opc.Ua.ContentFilterResult.Encode (IEncoder encoder) inline virtual
Definition at line 43859 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
IsEqual()
virtual bool Opc.Ua.ContentFilterResult.IsEqual (IEncodeable encodeable) inline virtual
Definition at line 43881 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Object.
MemberwiseClone()
new object Opc.Ua.ContentFilterResult.MemberwiseClone () inline
Definition at line 43910 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.ContentFilterElementResultCollection.Clone(), Opc.Ua.ContentFilterResult.MemberwiseClone(), and Opc.Ua.Namespaces.OpcUaXsd.
Referenced by Opc.Ua.ContentFilterResult.MemberwiseClone().
Property Documentation
BinaryEncodingId
virtual ExpandedNodeId Opc.Ua.ContentFilterResult.BinaryEncodingId get
Definition at line 43848 of file Opc.Ua.DataTypes.cs.
ElementDiagnosticInfos
DiagnosticInfoCollection Opc.Ua.ContentFilterResult.ElementDiagnosticInfos get set
Definition at line 43821 of file Opc.Ua.DataTypes.cs.
ElementResults
ContentFilterElementResultCollection Opc.Ua.ContentFilterResult.ElementResults get set
Definition at line 43799 of file Opc.Ua.DataTypes.cs.
TypeId
virtual ExpandedNodeId Opc.Ua.ContentFilterResult.TypeId get
Definition at line 43842 of file Opc.Ua.DataTypes.cs.
XmlEncodingId
virtual ExpandedNodeId Opc.Ua.ContentFilterResult.XmlEncodingId get
Definition at line 43854 of file Opc.Ua.DataTypes.cs.
The documentation for this class was generated from the following file:
Opc.Ua.DataTypes.cs