Project Template: Opc.Ua.ChannelSecurityToken Class Reference
Opc.Ua.ChannelSecurityToken Class Reference
Public Member Functions
ChannelSecurityToken ()
The default constructor.
virtual void Encode (IEncoder encoder)
virtual void Decode (IDecoder decoder)
virtual bool IsEqual (IEncodeable encodeable)
virtual object Clone ()
new object MemberwiseClone ()
Properties
uint ChannelId [get, set]
uint TokenId [get, set]
DateTime CreatedAt [get, set]
uint RevisedLifetime [get, set]
virtual ExpandedNodeId TypeId [get]
virtual ExpandedNodeId BinaryEncodingId [get]
virtual ExpandedNodeId XmlEncodingId [get]
Detailed Description
<exclude>
Definition at line 27931 of file Opc.Ua.DataTypes.cs.
Constructor & Destructor Documentation
ChannelSecurityToken()
Opc.Ua.ChannelSecurityToken.ChannelSecurityToken () inline
The default constructor.
Definition at line 27937 of file Opc.Ua.DataTypes.cs.
Member Function Documentation
Clone()
virtual object Opc.Ua.ChannelSecurityToken.Clone () inline virtual
Definition at line 28067 of file Opc.Ua.DataTypes.cs.
Referenced by Opc.Ua.OpenSecureChannelResponse.MemberwiseClone().
Decode()
virtual void Opc.Ua.ChannelSecurityToken.Decode (IDecoder decoder) inline virtual
Definition at line 28030 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
Encode()
virtual void Opc.Ua.ChannelSecurityToken.Encode (IEncoder encoder) inline virtual
Definition at line 28017 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
IsEqual()
virtual bool Opc.Ua.ChannelSecurityToken.IsEqual (IEncodeable encodeable) inline virtual
Definition at line 28043 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Object.
MemberwiseClone()
new object Opc.Ua.ChannelSecurityToken.MemberwiseClone () inline
Definition at line 28074 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.ChannelSecurityToken.MemberwiseClone(), and Opc.Ua.Namespaces.OpcUaXsd.
Referenced by Opc.Ua.ChannelSecurityToken.MemberwiseClone().
Property Documentation
BinaryEncodingId
virtual ExpandedNodeId Opc.Ua.ChannelSecurityToken.BinaryEncodingId get
Definition at line 28006 of file Opc.Ua.DataTypes.cs.
ChannelId
uint Opc.Ua.ChannelSecurityToken.ChannelId get set
Definition at line 27967 of file Opc.Ua.DataTypes.cs.
CreatedAt
DateTime Opc.Ua.ChannelSecurityToken.CreatedAt get set
Definition at line 27983 of file Opc.Ua.DataTypes.cs.
RevisedLifetime
uint Opc.Ua.ChannelSecurityToken.RevisedLifetime get set
Definition at line 27991 of file Opc.Ua.DataTypes.cs.
TokenId
uint Opc.Ua.ChannelSecurityToken.TokenId get set
Definition at line 27975 of file Opc.Ua.DataTypes.cs.
TypeId
virtual ExpandedNodeId Opc.Ua.ChannelSecurityToken.TypeId get
Definition at line 28000 of file Opc.Ua.DataTypes.cs.
XmlEncodingId
virtual ExpandedNodeId Opc.Ua.ChannelSecurityToken.XmlEncodingId get
Definition at line 28012 of file Opc.Ua.DataTypes.cs.
The documentation for this class was generated from the following file:
Opc.Ua.DataTypes.cs