Project Template: Opc.Ua.BrowsePathResult Class Reference
Opc.Ua.BrowsePathResult Class Reference
Public Member Functions
BrowsePathResult ()
The default constructor.
virtual void Encode (IEncoder encoder)
virtual void Decode (IDecoder decoder)
virtual bool IsEqual (IEncodeable encodeable)
virtual object Clone ()
new object MemberwiseClone ()
Properties
StatusCode StatusCode [get, set]
BrowsePathTargetCollection Targets [get, set]
virtual ExpandedNodeId TypeId [get]
virtual ExpandedNodeId BinaryEncodingId [get]
virtual ExpandedNodeId XmlEncodingId [get]
Detailed Description
<exclude>
Definition at line 39383 of file Opc.Ua.DataTypes.cs.
Constructor & Destructor Documentation
BrowsePathResult()
Opc.Ua.BrowsePathResult.BrowsePathResult () inline
The default constructor.
Definition at line 39389 of file Opc.Ua.DataTypes.cs.
Member Function Documentation
Clone()
virtual object Opc.Ua.BrowsePathResult.Clone () inline virtual
Definition at line 39509 of file Opc.Ua.DataTypes.cs.
Decode()
virtual void Opc.Ua.BrowsePathResult.Decode (IDecoder decoder) inline virtual
Definition at line 39476 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd, and Opc.Ua.StatusCode.
Encode()
virtual void Opc.Ua.BrowsePathResult.Encode (IEncoder encoder) inline virtual
Definition at line 39465 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd, and Opc.Ua.StatusCode.
IsEqual()
virtual bool Opc.Ua.BrowsePathResult.IsEqual (IEncodeable encodeable) inline virtual
Definition at line 39487 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Object.
MemberwiseClone()
new object Opc.Ua.BrowsePathResult.MemberwiseClone () inline
Definition at line 39516 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.BrowsePathTargetCollection.Clone(), Opc.Ua.BrowsePathResult.MemberwiseClone(), Opc.Ua.Namespaces.OpcUaXsd, and Opc.Ua.StatusCode.
Referenced by Opc.Ua.BrowsePathResult.MemberwiseClone().
Property Documentation
BinaryEncodingId
virtual ExpandedNodeId Opc.Ua.BrowsePathResult.BinaryEncodingId get
Definition at line 39454 of file Opc.Ua.DataTypes.cs.
StatusCode
StatusCode Opc.Ua.BrowsePathResult.StatusCode get set
Definition at line 39417 of file Opc.Ua.DataTypes.cs.
Targets
BrowsePathTargetCollection Opc.Ua.BrowsePathResult.Targets get set
Definition at line 39427 of file Opc.Ua.DataTypes.cs.
TypeId
virtual ExpandedNodeId Opc.Ua.BrowsePathResult.TypeId get
Definition at line 39448 of file Opc.Ua.DataTypes.cs.
XmlEncodingId
virtual ExpandedNodeId Opc.Ua.BrowsePathResult.XmlEncodingId get
Definition at line 39460 of file Opc.Ua.DataTypes.cs.
The documentation for this class was generated from the following file:
Opc.Ua.DataTypes.cs