Project Template: Opc.Ua.Adi Namespace Reference
Opc.Ua.Adi Namespace Reference
Data Structures
class AccessorySlotState
Stores an instance of the AccessorySlotType ObjectType.
class AccessorySlotStateMachineState
Stores an instance of the AccessorySlotStateMachineType ObjectType.
class AccessoryState
Stores an instance of the AccessoryType ObjectType.
class AcousticSpectrometerDeviceState
Stores an instance of the AcousticSpectrometerDeviceType ObjectType.
class AcousticSpectrometerDeviceStreamState
Stores an instance of the AcousticSpectrometerDeviceStreamType ObjectType.
class AcquisitionResultStatusEnumerationCollection
A collection of AcquisitionResultStatusEnumeration objects.
class AlarmStateEnumerationCollection
A collection of AlarmStateEnumeration objects.
class AnalyserChannel_OperatingModeExecuteSubStateMachineState
Stores an instance of the AnalyserChannel_OperatingModeExecuteSubStateMachineType ObjectType.
class AnalyserChannel_OperatingModeSubStateMachineState
Stores an instance of the AnalyserChannel_OperatingModeSubStateMachineType ObjectType.
class AnalyserChannelLocalStateState
Stores an instance of the AnalyserChannelLocalStateType ObjectType.
class AnalyserChannelMaintenanceStateState
Stores an instance of the AnalyserChannelMaintenanceStateType ObjectType.
class AnalyserChannelOperatingExecuteStateState
Stores an instance of the AnalyserChannelOperatingExecuteStateType ObjectType.
class AnalyserChannelOperatingStateState
Stores an instance of the AnalyserChannelOperatingStateType ObjectType.
class AnalyserChannelState
Stores an instance of the AnalyserChannelType ObjectType.
class AnalyserChannelStateMachineState
Stores an instance of the AnalyserChannelStateMachineType ObjectType.
class AnalyserChannelTypeStartSingleAcquisitionMethodState
Stores an instance of the AnalyserChannelTypeStartSingleAcquisitionMethodType Method.
class AnalyserDeviceState
Stores an instance of the AnalyserDeviceType ObjectType.
class AnalyserDeviceStateMachineState
Stores an instance of the AnalyserDeviceStateMachineType ObjectType.
class AnalyserDeviceTypeCompareConfigDataDigestMethodState
Stores an instance of the AnalyserDeviceTypeCompareConfigDataDigestMethodType Method.
class AnalyserDeviceTypeGetConfigDataDigestMethodState
Stores an instance of the AnalyserDeviceTypeGetConfigDataDigestMethodType Method.
class AnalyserDeviceTypeGetConfigurationMethodState
Stores an instance of the AnalyserDeviceTypeGetConfigurationMethodType Method.
class AnalyserDeviceTypeSetConfigurationMethodState
Stores an instance of the AnalyserDeviceTypeSetConfigurationMethodType Method.
class BrowseNames
Declares all of the BrowseNames used in the Model Design.
class ChemometricModelState
Stores an instance of the ChemometricModelType VariableType.
class ChromatographDeviceState
Stores an instance of the ChromatographDeviceType ObjectType.
class ChromatographDeviceStreamState
Stores an instance of the ChromatographDeviceStreamType ObjectType.
class DataTypeIds
A class that declares constants for all DataTypes in the Model Design.
class DataTypes
A class that declares constants for all DataTypes in the Model Design.
class DetectorState
Stores an instance of the DetectorType ObjectType.
class EngineeringValueState
Stores an instance of the EngineeringValueType VariableType.
class ExecutionCycleEnumerationCollection
A collection of ExecutionCycleEnumeration objects.
class GcOvenState
Stores an instance of the GcOvenType ObjectType.
class MassSpectrometerDeviceState
Stores an instance of the MassSpectrometerDeviceType ObjectType.
class MassSpectrometerDeviceStreamState
Stores an instance of the MassSpectrometerDeviceStreamType ObjectType.
class MethodIds
A class that declares constants for all Methods in the Model Design.
class Methods
A class that declares constants for all Methods in the Model Design.
class MNRDeviceStreamState
Stores an instance of the MNRDeviceStreamType ObjectType.
class MVAModelState
Stores an instance of the MVAModelType VariableType.
class MVAOutputParameterState
Stores an instance of the MVAOutputParameterType VariableType.
class MVAPredictMethodState
Stores an instance of the MVAPredictMethodType Method.
class Namespaces
Defines constants for all namespaces referenced by the model design.
class NMRDeviceState
Stores an instance of the NMRDeviceType ObjectType.
class ObjectIds
A class that declares constants for all Objects in the Model Design.
class Objects
A class that declares constants for all Objects in the Model Design.
class ObjectTypeIds
A class that declares constants for all ObjectTypes in the Model Design.
class ObjectTypes
A class that declares constants for all ObjectTypes in the Model Design.
class ParticleSizeMonitorDeviceState
Stores an instance of the ParticleSizeMonitorDeviceType ObjectType.
class ParticleSizeMonitorDeviceStreamState
Stores an instance of the ParticleSizeMonitorDeviceStreamType ObjectType.
class ProcessVariableState
Stores an instance of the ProcessVariableType VariableType.
class ReferenceTypeIds
A class that declares constants for all ReferenceTypes in the Model Design.
class ReferenceTypes
A class that declares constants for all ReferenceTypes in the Model Design.
class SmartSamplingSystemState
Stores an instance of the SmartSamplingSystemType ObjectType.
class SourceState
Stores an instance of the SourceType ObjectType.
class SpectrometerDeviceState
Stores an instance of the SpectrometerDeviceType ObjectType.
class SpectrometerDeviceStreamState
Stores an instance of the SpectrometerDeviceStreamType ObjectType.
class StreamState
Stores an instance of the StreamType ObjectType.
class VariableIds
A class that declares constants for all Variables in the Model Design.
class Variables
A class that declares constants for all Variables in the Model Design.
class VariableTypeIds
A class that declares constants for all VariableTypes in the Model Design.
class VariableTypes
A class that declares constants for all VariableTypes in the Model Design.
Enumerations
enum ExecutionCycleEnumeration {
ExecutionCycleEnumeration.IDLE = 0, ExecutionCycleEnumeration.DIAGNOSTIC = 1, ExecutionCycleEnumeration.CLEANING = 2, ExecutionCycleEnumeration.CALIBRATION = 4,
ExecutionCycleEnumeration.VALIDATION = 8, ExecutionCycleEnumeration.SAMPLING = 16, ExecutionCycleEnumeration.DIAGNOSTIC_WITH_GRAB_SAMPLE = 32769, ExecutionCycleEnumeration.CLEANING_WITH_GRAB_SAMPLE = 32770,
ExecutionCycleEnumeration.CALIBRATION_WITH_GRAB_SAMPLE = 32772, ExecutionCycleEnumeration.VALIDATION_WITH_GRAB_SAMPLE = 32776, ExecutionCycleEnumeration.SAMPLING_WITH_GRAB_SAMPLE = 32784
}
enum AcquisitionResultStatusEnumeration {
AcquisitionResultStatusEnumeration.NOT_USED = 0, AcquisitionResultStatusEnumeration.GOOD = 1, AcquisitionResultStatusEnumeration.BAD = 2, AcquisitionResultStatusEnumeration.UNKNOWN = 3,
AcquisitionResultStatusEnumeration.PARTIAL = 4
}
enum AlarmStateEnumeration {
AlarmStateEnumeration.NORMAL_0 = 0, AlarmStateEnumeration.WARNING_LOW_1 = 1, AlarmStateEnumeration.WARNING_HIGH_2 = 2, AlarmStateEnumeration.WARNING_4 = 4,
AlarmStateEnumeration.ALARM_LOW_8 = 8, AlarmStateEnumeration.ALARM_HIGH_16 = 16, AlarmStateEnumeration.ALARM_32 = 32
}
Functions
delegate ServiceResult AnalyserDeviceTypeGetConfigurationMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, ref byte[] configData)
Used to receive notifications when the method is called.
delegate ServiceResult AnalyserDeviceTypeSetConfigurationMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, byte[] configData, ref string configDataDigest)
Used to receive notifications when the method is called.
delegate ServiceResult AnalyserDeviceTypeGetConfigDataDigestMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, ref string configDataDigest)
Used to receive notifications when the method is called.
delegate ServiceResult AnalyserDeviceTypeCompareConfigDataDigestMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, string configDataDigest, ref bool isEqual)
Used to receive notifications when the method is called.
delegate ServiceResult AnalyserChannelTypeStartSingleAcquisitionMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, ExecutionCycleEnumeration executionCycle, uint executionCycleSubcode, string selectedStream)
Used to receive notifications when the method is called.
delegate ServiceResult MVAPredictMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, NodeId targetModel, int mainDataIndex, Variant[] inputs, ref Variant[] outputs)
Used to receive notifications when the method is called.
Enumeration Type Documentation
AcquisitionResultStatusEnumeration
enum Opc.Ua.Adi.AcquisitionResultStatusEnumeration strong
<exclude>
Enumerator
NOT_USED
GOOD
BAD
UNKNOWN
PARTIAL
Definition at line 190 of file Opc.Ua.Adi.DataTypes.cs.
AlarmStateEnumeration
enum Opc.Ua.Adi.AlarmStateEnumeration strong
<exclude>
Enumerator
NORMAL_0
WARNING_LOW_1
WARNING_HIGH_2
WARNING_4
ALARM_LOW_8
ALARM_HIGH_16
ALARM_32
Definition at line 308 of file Opc.Ua.Adi.DataTypes.cs.
ExecutionCycleEnumeration
enum Opc.Ua.Adi.ExecutionCycleEnumeration strong
<exclude>
Enumerator
IDLE
DIAGNOSTIC
CLEANING
CALIBRATION
VALIDATION
SAMPLING
DIAGNOSTIC_WITH_GRAB_SAMPLE
CLEANING_WITH_GRAB_SAMPLE
CALIBRATION_WITH_GRAB_SAMPLE
VALIDATION_WITH_GRAB_SAMPLE
SAMPLING_WITH_GRAB_SAMPLE
Definition at line 48 of file Opc.Ua.Adi.DataTypes.cs.
Function Documentation
AnalyserChannelTypeStartSingleAcquisitionMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.Adi.AnalyserChannelTypeStartSingleAcquisitionMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, ExecutionCycleEnumeration executionCycle, uint executionCycleSubcode, string selectedStream)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.Adi.AnalyserChannelTypeStartSingleAcquisitionMethodState.InitializeOptionalChildren().
AnalyserDeviceTypeCompareConfigDataDigestMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.Adi.AnalyserDeviceTypeCompareConfigDataDigestMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, string configDataDigest, ref bool isEqual)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.Adi.AnalyserDeviceTypeCompareConfigDataDigestMethodState.InitializeOptionalChildren().
AnalyserDeviceTypeGetConfigDataDigestMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.Adi.AnalyserDeviceTypeGetConfigDataDigestMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, ref string configDataDigest)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.Adi.AnalyserDeviceTypeGetConfigDataDigestMethodState.InitializeOptionalChildren().
AnalyserDeviceTypeGetConfigurationMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.Adi.AnalyserDeviceTypeGetConfigurationMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, ref byte [] configData)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.Adi.AnalyserDeviceTypeGetConfigurationMethodState.InitializeOptionalChildren().
AnalyserDeviceTypeSetConfigurationMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.Adi.AnalyserDeviceTypeSetConfigurationMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, byte [] configData, ref string configDataDigest)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.Adi.AnalyserDeviceTypeSetConfigurationMethodState.InitializeOptionalChildren().
MVAPredictMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.Adi.MVAPredictMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, NodeId targetModel, int mainDataIndex, Variant [] inputs, ref Variant [] outputs)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.Adi.MVAPredictMethodState.InitializeOptionalChildren().