Project Template: Opc.Ua.UABinaryFileDataType Class Reference
Opc.Ua.UABinaryFileDataType Class Reference
Public Member Functions
UABinaryFileDataType ()
The default constructor.
override void Encode (IEncoder encoder)
override void Decode (IDecoder decoder)
override bool IsEqual (IEncodeable encodeable)
override object Clone ()
new object MemberwiseClone ()
Public Member Functions inherited from Opc.Ua.DataTypeSchemaHeader
DataTypeSchemaHeader ()
The default constructor.
new object MemberwiseClone ()
Properties
string SchemaLocation [get, set]
KeyValuePairCollection FileHeader [get, set]
Variant Body [get, set]
override ExpandedNodeId TypeId [get]
override ExpandedNodeId BinaryEncodingId [get]
override ExpandedNodeId XmlEncodingId [get]
Properties inherited from Opc.Ua.DataTypeSchemaHeader
StringCollection Namespaces [get, set]
StructureDescriptionCollection StructureDataTypes [get, set]
EnumDescriptionCollection EnumDataTypes [get, set]
SimpleTypeDescriptionCollection SimpleDataTypes [get, set]
virtual ExpandedNodeId TypeId [get]
virtual ExpandedNodeId BinaryEncodingId [get]
virtual ExpandedNodeId XmlEncodingId [get]
Detailed Description
<exclude>
Definition at line 5053 of file Opc.Ua.DataTypes.cs.
Constructor & Destructor Documentation
UABinaryFileDataType()
Opc.Ua.UABinaryFileDataType.UABinaryFileDataType () inline
The default constructor.
Definition at line 5059 of file Opc.Ua.DataTypes.cs.
Member Function Documentation
Clone()
override object Opc.Ua.UABinaryFileDataType.Clone () inline virtual
Reimplemented from Opc.Ua.DataTypeSchemaHeader.
Definition at line 5196 of file Opc.Ua.DataTypes.cs.
Decode()
override void Opc.Ua.UABinaryFileDataType.Decode (IDecoder decoder) inline virtual
Reimplemented from Opc.Ua.DataTypeSchemaHeader.
Definition at line 5158 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
Encode()
override void Opc.Ua.UABinaryFileDataType.Encode (IEncoder encoder) inline virtual
Reimplemented from Opc.Ua.DataTypeSchemaHeader.
Definition at line 5144 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
IsEqual()
override bool Opc.Ua.UABinaryFileDataType.IsEqual (IEncodeable encodeable) inline virtual
Reimplemented from Opc.Ua.DataTypeSchemaHeader.
Definition at line 5172 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Object.
MemberwiseClone()
new object Opc.Ua.UABinaryFileDataType.MemberwiseClone () inline
Definition at line 5203 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.KeyValuePairCollection.Clone(), Opc.Ua.UABinaryFileDataType.MemberwiseClone(), and Opc.Ua.Namespaces.OpcUaXsd.
Referenced by Opc.Ua.UABinaryFileDataType.MemberwiseClone().
Property Documentation
BinaryEncodingId
override ExpandedNodeId Opc.Ua.UABinaryFileDataType.BinaryEncodingId get
Definition at line 5133 of file Opc.Ua.DataTypes.cs.
Body
Variant Opc.Ua.UABinaryFileDataType.Body get set
Definition at line 5118 of file Opc.Ua.DataTypes.cs.
FileHeader
KeyValuePairCollection Opc.Ua.UABinaryFileDataType.FileHeader get set
Definition at line 5098 of file Opc.Ua.DataTypes.cs.
SchemaLocation
string Opc.Ua.UABinaryFileDataType.SchemaLocation get set
Definition at line 5088 of file Opc.Ua.DataTypes.cs.
TypeId
override ExpandedNodeId Opc.Ua.UABinaryFileDataType.TypeId get
Definition at line 5127 of file Opc.Ua.DataTypes.cs.
XmlEncodingId
override ExpandedNodeId Opc.Ua.UABinaryFileDataType.XmlEncodingId get
Definition at line 5139 of file Opc.Ua.DataTypes.cs.
The documentation for this class was generated from the following file:
Opc.Ua.DataTypes.cs