Project Template: Opc.Ua.EnumDefinition Class Reference
Opc.Ua.EnumDefinition Class Reference
Public Member Functions
EnumDefinition ()
The default constructor.
override void Encode (IEncoder encoder)
override void Decode (IDecoder decoder)
override bool IsEqual (IEncodeable encodeable)
override object Clone ()
new object MemberwiseClone ()
Public Member Functions inherited from Opc.Ua.DataTypeDefinition
DataTypeDefinition ()
The default constructor.
new object MemberwiseClone ()
Properties
EnumFieldCollection Fields [get, set]
override ExpandedNodeId TypeId [get]
override ExpandedNodeId BinaryEncodingId [get]
override ExpandedNodeId XmlEncodingId [get]
Properties inherited from Opc.Ua.DataTypeDefinition
virtual ExpandedNodeId TypeId [get]
virtual ExpandedNodeId BinaryEncodingId [get]
virtual ExpandedNodeId XmlEncodingId [get]
Detailed Description
<exclude>
Definition at line 19180 of file Opc.Ua.DataTypes.cs.
Constructor & Destructor Documentation
EnumDefinition()
Opc.Ua.EnumDefinition.EnumDefinition () inline
The default constructor.
Definition at line 19186 of file Opc.Ua.DataTypes.cs.
Member Function Documentation
Clone()
override object Opc.Ua.EnumDefinition.Clone () inline virtual
Reimplemented from Opc.Ua.DataTypeDefinition.
Definition at line 19299 of file Opc.Ua.DataTypes.cs.
Referenced by Opc.Ua.EnumDescription.MemberwiseClone().
Decode()
override void Opc.Ua.EnumDefinition.Decode (IDecoder decoder) inline virtual
Reimplemented from Opc.Ua.DataTypeDefinition.
Definition at line 19265 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
Encode()
override void Opc.Ua.EnumDefinition.Encode (IEncoder encoder) inline virtual
Reimplemented from Opc.Ua.DataTypeDefinition.
Definition at line 19253 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
IsEqual()
override bool Opc.Ua.EnumDefinition.IsEqual (IEncodeable encodeable) inline virtual
Reimplemented from Opc.Ua.DataTypeDefinition.
Definition at line 19277 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Object.
MemberwiseClone()
new object Opc.Ua.EnumDefinition.MemberwiseClone () inline
Definition at line 19306 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.EnumFieldCollection.Clone(), Opc.Ua.EnumDefinition.MemberwiseClone(), and Opc.Ua.Namespaces.OpcUaXsd.
Referenced by Opc.Ua.EnumDefinition.MemberwiseClone().
Property Documentation
BinaryEncodingId
override ExpandedNodeId Opc.Ua.EnumDefinition.BinaryEncodingId get
Definition at line 19242 of file Opc.Ua.DataTypes.cs.
Fields
EnumFieldCollection Opc.Ua.EnumDefinition.Fields get set
Definition at line 19215 of file Opc.Ua.DataTypes.cs.
TypeId
override ExpandedNodeId Opc.Ua.EnumDefinition.TypeId get
Definition at line 19236 of file Opc.Ua.DataTypes.cs.
XmlEncodingId
override ExpandedNodeId Opc.Ua.EnumDefinition.XmlEncodingId get
Definition at line 19248 of file Opc.Ua.DataTypes.cs.
The documentation for this class was generated from the following file:
Opc.Ua.DataTypes.cs