Project Template: server_config_default.h File Reference
server_config_default.h File Reference
Functions
UA_EXPORT UA_StatusCode UA_ServerConfig_setMinimalCustomBuffer (UA_ServerConfig *config, UA_UInt16 portNumber, const UA_ByteString *certificate, UA_UInt32 sendBufferSize, UA_UInt32 recvBufferSize)
static UA_INLINE UA_StatusCode UA_ServerConfig_setMinimal (UA_ServerConfig *config, UA_UInt16 portNumber, const UA_ByteString *certificate)
UA_EXPORT UA_StatusCode UA_ServerConfig_setDefaultWithSecurityPolicies (UA_ServerConfig *conf, UA_UInt16 portNumber, const UA_ByteString *certificate, const UA_ByteString *privateKey, const UA_ByteString *trustList, size_t trustListSize, const UA_ByteString *issuerList, size_t issuerListSize, const UA_ByteString *revocationList, size_t revocationListSize)
static UA_INLINE UA_StatusCode UA_ServerConfig_setDefault (UA_ServerConfig *config)
UA_EXPORT UA_StatusCode UA_ServerConfig_setBasics (UA_ServerConfig *conf)
UA_EXPORT UA_StatusCode UA_ServerConfig_addNetworkLayerTCP (UA_ServerConfig *conf, UA_UInt16 portNumber, UA_UInt32 sendBufferSize, UA_UInt32 recvBufferSize)
UA_EXPORT UA_StatusCode UA_ServerConfig_addNetworkLayerWS (UA_ServerConfig *conf, UA_UInt16 portNumber, UA_UInt32 sendBufferSize, UA_UInt32 recvBufferSize)
UA_EXPORT UA_StatusCode UA_ServerConfig_addSecurityPolicyNone (UA_ServerConfig *config, const UA_ByteString *certificate)
UA_EXPORT UA_StatusCode UA_ServerConfig_addSecurityPolicyBasic128Rsa15 (UA_ServerConfig *config, const UA_ByteString *certificate, const UA_ByteString *privateKey)
UA_EXPORT UA_StatusCode UA_ServerConfig_addSecurityPolicyBasic256 (UA_ServerConfig *config, const UA_ByteString *certificate, const UA_ByteString *privateKey)
UA_EXPORT UA_StatusCode UA_ServerConfig_addSecurityPolicyBasic256Sha256 (UA_ServerConfig *config, const UA_ByteString *certificate, const UA_ByteString *privateKey)
UA_EXPORT UA_StatusCode UA_ServerConfig_addAllSecurityPolicies (UA_ServerConfig *config, const UA_ByteString *certificate, const UA_ByteString *privateKey)
UA_EXPORT UA_StatusCode UA_ServerConfig_addEndpoint (UA_ServerConfig *config, const UA_String securityPolicyUri, UA_MessageSecurityMode securityMode)
UA_EXPORT UA_StatusCode UA_ServerConfig_addAllEndpoints (UA_ServerConfig *config)
Variables
_UA_BEGIN_DECLS const UA_EXPORT UA_ConnectionConfig UA_ConnectionConfig_default
Function Documentation
UA_ServerConfig_addAllEndpoints()
UA_EXPORT UA_StatusCode UA_ServerConfig_addAllEndpoints (UA_ServerConfig * config)
Referenced by UA_ServerConfig_setDefault().
UA_ServerConfig_addAllSecurityPolicies()
UA_EXPORT UA_StatusCode UA_ServerConfig_addAllSecurityPolicies (UA_ServerConfig * config, const UA_ByteString * certificate, const UA_ByteString * privateKey)
Referenced by UA_ServerConfig_setDefault().
UA_ServerConfig_addEndpoint()
UA_EXPORT UA_StatusCode UA_ServerConfig_addEndpoint (UA_ServerConfig * config, const UA_String securityPolicyUri, UA_MessageSecurityMode securityMode)
Referenced by UA_ServerConfig_setDefault().
UA_ServerConfig_addNetworkLayerTCP()
UA_EXPORT UA_StatusCode UA_ServerConfig_addNetworkLayerTCP (UA_ServerConfig * conf, UA_UInt16 portNumber, UA_UInt32 sendBufferSize, UA_UInt32 recvBufferSize)
Referenced by UA_ServerConfig_setDefault().
UA_ServerConfig_addNetworkLayerWS()
UA_EXPORT UA_StatusCode UA_ServerConfig_addNetworkLayerWS (UA_ServerConfig * conf, UA_UInt16 portNumber, UA_UInt32 sendBufferSize, UA_UInt32 recvBufferSize)
Referenced by UA_ServerConfig_setDefault().
UA_ServerConfig_addSecurityPolicyBasic128Rsa15()
UA_EXPORT UA_StatusCode UA_ServerConfig_addSecurityPolicyBasic128Rsa15 (UA_ServerConfig * config, const UA_ByteString * certificate, const UA_ByteString * privateKey)
Referenced by UA_ServerConfig_setDefault().
UA_ServerConfig_addSecurityPolicyBasic256()
UA_EXPORT UA_StatusCode UA_ServerConfig_addSecurityPolicyBasic256 (UA_ServerConfig * config, const UA_ByteString * certificate, const UA_ByteString * privateKey)
Referenced by UA_ServerConfig_setDefault().
UA_ServerConfig_addSecurityPolicyBasic256Sha256()
UA_EXPORT UA_StatusCode UA_ServerConfig_addSecurityPolicyBasic256Sha256 (UA_ServerConfig * config, const UA_ByteString * certificate, const UA_ByteString * privateKey)
Referenced by UA_ServerConfig_setDefault().
UA_ServerConfig_addSecurityPolicyNone()
UA_EXPORT UA_StatusCode UA_ServerConfig_addSecurityPolicyNone (UA_ServerConfig * config, const UA_ByteString * certificate)
Referenced by UA_ServerConfig_setDefault().
UA_ServerConfig_setBasics()
UA_EXPORT UA_StatusCode UA_ServerConfig_setBasics (UA_ServerConfig * conf)
Referenced by UA_ServerConfig_setDefault().
UA_ServerConfig_setDefault()
static UA_INLINE UA_StatusCode UA_ServerConfig_setDefault (UA_ServerConfig * config) static
Definition at line 80 of file server_config_default.h.
References UA_ServerConfig_addAllEndpoints(), UA_ServerConfig_addAllSecurityPolicies(), UA_ServerConfig_addEndpoint(), UA_ServerConfig_addNetworkLayerTCP(), UA_ServerConfig_addNetworkLayerWS(), UA_ServerConfig_addSecurityPolicyBasic128Rsa15(), UA_ServerConfig_addSecurityPolicyBasic256(), UA_ServerConfig_addSecurityPolicyBasic256Sha256(), UA_ServerConfig_addSecurityPolicyNone(), UA_ServerConfig_setBasics(), and UA_ServerConfig_setMinimal().
Referenced by startServer().
UA_ServerConfig_setDefaultWithSecurityPolicies()
UA_EXPORT UA_StatusCode UA_ServerConfig_setDefaultWithSecurityPolicies (UA_ServerConfig * conf, UA_UInt16 portNumber, const UA_ByteString * certificate, const UA_ByteString * privateKey, const UA_ByteString * trustList, size_t trustListSize, const UA_ByteString * issuerList, size_t issuerListSize, const UA_ByteString * revocationList, size_t revocationListSize)
Referenced by UA_ServerConfig_setMinimal().
UA_ServerConfig_setMinimal()
static UA_INLINE UA_StatusCode UA_ServerConfig_setMinimal (UA_ServerConfig * config, UA_UInt16 portNumber, const UA_ByteString * certificate) static
Definition at line 55 of file server_config_default.h.
References UA_ServerConfig_setDefaultWithSecurityPolicies(), and UA_ServerConfig_setMinimalCustomBuffer().
Referenced by UA_ServerConfig_setDefault().
UA_ServerConfig_setMinimalCustomBuffer()
UA_EXPORT UA_StatusCode UA_ServerConfig_setMinimalCustomBuffer (UA_ServerConfig * config, UA_UInt16 portNumber, const UA_ByteString * certificate, UA_UInt32 sendBufferSize, UA_UInt32 recvBufferSize)
Referenced by UA_ServerConfig_setMinimal().
Variable Documentation
UA_ConnectionConfig_default
_UA_BEGIN_DECLS const UA_EXPORT UA_ConnectionConfig UA_ConnectionConfig_default