Project Template: Opc.Ua.Di.TransferResultDataDataType Class Reference
Opc.Ua.Di.TransferResultDataDataType Class Reference
Public Member Functions
TransferResultDataDataType ()
The default constructor.
override void Encode (IEncoder encoder)
override void Decode (IDecoder decoder)
override bool IsEqual (IEncodeable encodeable)
override object Clone ()
new object MemberwiseClone ()
Public Member Functions inherited from Opc.Ua.Di.FetchResultDataType
FetchResultDataType ()
The default constructor.
new object MemberwiseClone ()
Properties
int SequenceNumber [get, set]
bool EndOfResults [get, set]
ParameterResultDataTypeCollection ParameterDefs [get, set]
override ExpandedNodeId TypeId [get]
override ExpandedNodeId BinaryEncodingId [get]
override ExpandedNodeId XmlEncodingId [get]
Properties inherited from Opc.Ua.Di.FetchResultDataType
virtual ExpandedNodeId TypeId [get]
virtual ExpandedNodeId BinaryEncodingId [get]
virtual ExpandedNodeId XmlEncodingId [get]
Detailed Description
<exclude>
Definition at line 605 of file Opc.Ua.Di.DataTypes.cs.
Constructor & Destructor Documentation
TransferResultDataDataType()
Opc.Ua.Di.TransferResultDataDataType.TransferResultDataDataType () inline
The default constructor.
Definition at line 611 of file Opc.Ua.Di.DataTypes.cs.
Member Function Documentation
Clone()
override object Opc.Ua.Di.TransferResultDataDataType.Clone () inline virtual
Reimplemented from Opc.Ua.Di.FetchResultDataType.
Definition at line 748 of file Opc.Ua.Di.DataTypes.cs.
Decode()
override void Opc.Ua.Di.TransferResultDataDataType.Decode (IDecoder decoder) inline virtual
Reimplemented from Opc.Ua.Di.FetchResultDataType.
Definition at line 710 of file Opc.Ua.Di.DataTypes.cs.
References Opc.Ua.Di.Namespaces.OpcUaDiXsd, and Opc.Ua.SequenceNumber.
Encode()
override void Opc.Ua.Di.TransferResultDataDataType.Encode (IEncoder encoder) inline virtual
Reimplemented from Opc.Ua.Di.FetchResultDataType.
Definition at line 696 of file Opc.Ua.Di.DataTypes.cs.
References Opc.Ua.Di.Namespaces.OpcUaDiXsd, and Opc.Ua.SequenceNumber.
IsEqual()
override bool Opc.Ua.Di.TransferResultDataDataType.IsEqual (IEncodeable encodeable) inline virtual
Reimplemented from Opc.Ua.Di.FetchResultDataType.
Definition at line 724 of file Opc.Ua.Di.DataTypes.cs.
References Opc.Ua.Object.
MemberwiseClone()
new object Opc.Ua.Di.TransferResultDataDataType.MemberwiseClone () inline
Definition at line 755 of file Opc.Ua.Di.DataTypes.cs.
References Opc.Ua.Di.ParameterResultDataTypeCollection.Clone(), Opc.Ua.Di.TransferResultDataDataType.MemberwiseClone(), and Opc.Ua.Di.Namespaces.OpcUaDiXsd.
Referenced by Opc.Ua.Di.TransferResultDataDataType.MemberwiseClone().
Property Documentation
BinaryEncodingId
override ExpandedNodeId Opc.Ua.Di.TransferResultDataDataType.BinaryEncodingId get
Definition at line 685 of file Opc.Ua.Di.DataTypes.cs.
EndOfResults
bool Opc.Ua.Di.TransferResultDataDataType.EndOfResults get set
Definition at line 648 of file Opc.Ua.Di.DataTypes.cs.
ParameterDefs
ParameterResultDataTypeCollection Opc.Ua.Di.TransferResultDataDataType.ParameterDefs get set
Definition at line 658 of file Opc.Ua.Di.DataTypes.cs.
SequenceNumber
int Opc.Ua.Di.TransferResultDataDataType.SequenceNumber get set
Definition at line 640 of file Opc.Ua.Di.DataTypes.cs.
TypeId
override ExpandedNodeId Opc.Ua.Di.TransferResultDataDataType.TypeId get
Definition at line 679 of file Opc.Ua.Di.DataTypes.cs.
XmlEncodingId
override ExpandedNodeId Opc.Ua.Di.TransferResultDataDataType.XmlEncodingId get
Definition at line 691 of file Opc.Ua.Di.DataTypes.cs.
The documentation for this class was generated from the following file:
Opc.Ua.Di.DataTypes.cs