Project Template: Opc.Ua.AggregateConfiguration Class Reference
Opc.Ua.AggregateConfiguration Class Reference
Public Member Functions
AggregateConfiguration ()
The default constructor.
virtual void Encode (IEncoder encoder)
virtual void Decode (IDecoder decoder)
virtual bool IsEqual (IEncodeable encodeable)
virtual object Clone ()
new object MemberwiseClone ()
Properties
bool UseServerCapabilitiesDefaults [get, set]
bool TreatUncertainAsBad [get, set]
byte PercentDataBad [get, set]
byte PercentDataGood [get, set]
bool UseSlopedExtrapolation [get, set]
virtual ExpandedNodeId TypeId [get]
virtual ExpandedNodeId BinaryEncodingId [get]
virtual ExpandedNodeId XmlEncodingId [get]
Detailed Description
<exclude>
Definition at line 52237 of file Opc.Ua.DataTypes.cs.
Constructor & Destructor Documentation
AggregateConfiguration()
Opc.Ua.AggregateConfiguration.AggregateConfiguration () inline
The default constructor.
Definition at line 52243 of file Opc.Ua.DataTypes.cs.
Member Function Documentation
Clone()
virtual object Opc.Ua.AggregateConfiguration.Clone () inline virtual
Definition at line 52385 of file Opc.Ua.DataTypes.cs.
Referenced by Opc.Ua.ReadProcessedDetails.MemberwiseClone(), Opc.Ua.AggregateFilter.MemberwiseClone(), and Opc.Ua.AggregateFilterResult.MemberwiseClone().
Decode()
virtual void Opc.Ua.AggregateConfiguration.Decode (IDecoder decoder) inline virtual
Definition at line 52346 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
Encode()
virtual void Opc.Ua.AggregateConfiguration.Encode (IEncoder encoder) inline virtual
Definition at line 52332 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
IsEqual()
virtual bool Opc.Ua.AggregateConfiguration.IsEqual (IEncodeable encodeable) inline virtual
Definition at line 52360 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Object.
MemberwiseClone()
new object Opc.Ua.AggregateConfiguration.MemberwiseClone () inline
Definition at line 52392 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.AggregateConfiguration.MemberwiseClone(), and Opc.Ua.Namespaces.OpcUaXsd.
Referenced by Opc.Ua.AggregateConfiguration.MemberwiseClone().
Property Documentation
BinaryEncodingId
virtual ExpandedNodeId Opc.Ua.AggregateConfiguration.BinaryEncodingId get
Definition at line 52321 of file Opc.Ua.DataTypes.cs.
PercentDataBad
byte Opc.Ua.AggregateConfiguration.PercentDataBad get set
Definition at line 52290 of file Opc.Ua.DataTypes.cs.
PercentDataGood
byte Opc.Ua.AggregateConfiguration.PercentDataGood get set
Definition at line 52298 of file Opc.Ua.DataTypes.cs.
TreatUncertainAsBad
bool Opc.Ua.AggregateConfiguration.TreatUncertainAsBad get set
Definition at line 52282 of file Opc.Ua.DataTypes.cs.
TypeId
virtual ExpandedNodeId Opc.Ua.AggregateConfiguration.TypeId get
Definition at line 52315 of file Opc.Ua.DataTypes.cs.
UseServerCapabilitiesDefaults
bool Opc.Ua.AggregateConfiguration.UseServerCapabilitiesDefaults get set
Definition at line 52274 of file Opc.Ua.DataTypes.cs.
UseSlopedExtrapolation
bool Opc.Ua.AggregateConfiguration.UseSlopedExtrapolation get set
Definition at line 52306 of file Opc.Ua.DataTypes.cs.
XmlEncodingId
virtual ExpandedNodeId Opc.Ua.AggregateConfiguration.XmlEncodingId get
Definition at line 52327 of file Opc.Ua.DataTypes.cs.
The documentation for this class was generated from the following file:
Opc.Ua.DataTypes.cs