Project Template: transport_generated_encoding_binary.h File Reference
transport_generated_encoding_binary.h File Reference
Functions
static UA_INLINE size_t UA_SecureConversationMessageAbortBody_calcSizeBinary (const UA_SecureConversationMessageAbortBody *src)
static UA_INLINE UA_StatusCode UA_SecureConversationMessageAbortBody_encodeBinary (const UA_SecureConversationMessageAbortBody *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_SecureConversationMessageAbortBody_decodeBinary (const UA_ByteString *src, size_t *offset, UA_SecureConversationMessageAbortBody *dst)
static UA_INLINE size_t UA_SecureConversationMessageFooter_calcSizeBinary (const UA_SecureConversationMessageFooter *src)
static UA_INLINE UA_StatusCode UA_SecureConversationMessageFooter_encodeBinary (const UA_SecureConversationMessageFooter *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_SecureConversationMessageFooter_decodeBinary (const UA_ByteString *src, size_t *offset, UA_SecureConversationMessageFooter *dst)
static UA_INLINE size_t UA_TcpHelloMessage_calcSizeBinary (const UA_TcpHelloMessage *src)
static UA_INLINE UA_StatusCode UA_TcpHelloMessage_encodeBinary (const UA_TcpHelloMessage *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_TcpHelloMessage_decodeBinary (const UA_ByteString *src, size_t *offset, UA_TcpHelloMessage *dst)
static UA_INLINE size_t UA_TcpErrorMessage_calcSizeBinary (const UA_TcpErrorMessage *src)
static UA_INLINE UA_StatusCode UA_TcpErrorMessage_encodeBinary (const UA_TcpErrorMessage *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_TcpErrorMessage_decodeBinary (const UA_ByteString *src, size_t *offset, UA_TcpErrorMessage *dst)
static UA_INLINE size_t UA_MessageType_calcSizeBinary (const UA_MessageType *src)
static UA_INLINE UA_StatusCode UA_MessageType_encodeBinary (const UA_MessageType *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_MessageType_decodeBinary (const UA_ByteString *src, size_t *offset, UA_MessageType *dst)
static UA_INLINE size_t UA_AsymmetricAlgorithmSecurityHeader_calcSizeBinary (const UA_AsymmetricAlgorithmSecurityHeader *src)
static UA_INLINE UA_StatusCode UA_AsymmetricAlgorithmSecurityHeader_encodeBinary (const UA_AsymmetricAlgorithmSecurityHeader *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_AsymmetricAlgorithmSecurityHeader_decodeBinary (const UA_ByteString *src, size_t *offset, UA_AsymmetricAlgorithmSecurityHeader *dst)
static UA_INLINE size_t UA_TcpAcknowledgeMessage_calcSizeBinary (const UA_TcpAcknowledgeMessage *src)
static UA_INLINE UA_StatusCode UA_TcpAcknowledgeMessage_encodeBinary (const UA_TcpAcknowledgeMessage *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_TcpAcknowledgeMessage_decodeBinary (const UA_ByteString *src, size_t *offset, UA_TcpAcknowledgeMessage *dst)
static UA_INLINE size_t UA_SequenceHeader_calcSizeBinary (const UA_SequenceHeader *src)
static UA_INLINE UA_StatusCode UA_SequenceHeader_encodeBinary (const UA_SequenceHeader *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_SequenceHeader_decodeBinary (const UA_ByteString *src, size_t *offset, UA_SequenceHeader *dst)
static UA_INLINE size_t UA_TcpMessageHeader_calcSizeBinary (const UA_TcpMessageHeader *src)
static UA_INLINE UA_StatusCode UA_TcpMessageHeader_encodeBinary (const UA_TcpMessageHeader *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_TcpMessageHeader_decodeBinary (const UA_ByteString *src, size_t *offset, UA_TcpMessageHeader *dst)
static UA_INLINE size_t UA_ChunkType_calcSizeBinary (const UA_ChunkType *src)
static UA_INLINE UA_StatusCode UA_ChunkType_encodeBinary (const UA_ChunkType *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_ChunkType_decodeBinary (const UA_ByteString *src, size_t *offset, UA_ChunkType *dst)
static UA_INLINE size_t UA_SymmetricAlgorithmSecurityHeader_calcSizeBinary (const UA_SymmetricAlgorithmSecurityHeader *src)
static UA_INLINE UA_StatusCode UA_SymmetricAlgorithmSecurityHeader_encodeBinary (const UA_SymmetricAlgorithmSecurityHeader *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_SymmetricAlgorithmSecurityHeader_decodeBinary (const UA_ByteString *src, size_t *offset, UA_SymmetricAlgorithmSecurityHeader *dst)
static UA_INLINE size_t UA_SecureConversationMessageHeader_calcSizeBinary (const UA_SecureConversationMessageHeader *src)
static UA_INLINE UA_StatusCode UA_SecureConversationMessageHeader_encodeBinary (const UA_SecureConversationMessageHeader *src, UA_Byte **bufPos, const UA_Byte *bufEnd)
static UA_INLINE UA_StatusCode UA_SecureConversationMessageHeader_decodeBinary (const UA_ByteString *src, size_t *offset, UA_SecureConversationMessageHeader *dst)
Function Documentation
UA_AsymmetricAlgorithmSecurityHeader_calcSizeBinary()
static UA_INLINE size_t UA_AsymmetricAlgorithmSecurityHeader_calcSizeBinary (const UA_AsymmetricAlgorithmSecurityHeader * src) static
Definition at line 85 of file transport_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TRANSPORT.
UA_AsymmetricAlgorithmSecurityHeader_decodeBinary()
static UA_INLINE UA_StatusCode UA_AsymmetricAlgorithmSecurityHeader_decodeBinary (const UA_ByteString * src, size_t * offset, UA_AsymmetricAlgorithmSecurityHeader * dst) static
Definition at line 93 of file transport_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TRANSPORT.
UA_AsymmetricAlgorithmSecurityHeader_encodeBinary()
static UA_INLINE UA_StatusCode UA_AsymmetricAlgorithmSecurityHeader_encodeBinary (const UA_AsymmetricAlgorithmSecurityHeader * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 89 of file transport_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TRANSPORT.
UA_ChunkType_calcSizeBinary()
static UA_INLINE size_t UA_ChunkType_calcSizeBinary (const UA_ChunkType * src) static
Definition at line 141 of file transport_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TRANSPORT.
UA_ChunkType_decodeBinary()
static UA_INLINE UA_StatusCode UA_ChunkType_decodeBinary (const UA_ByteString * src, size_t * offset, UA_ChunkType * dst) static
Definition at line 149 of file transport_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TRANSPORT.
UA_ChunkType_encodeBinary()
static UA_INLINE UA_StatusCode UA_ChunkType_encodeBinary (const UA_ChunkType * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 145 of file transport_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TRANSPORT.
UA_MessageType_calcSizeBinary()
static UA_INLINE size_t UA_MessageType_calcSizeBinary (const UA_MessageType * src) static
Definition at line 71 of file transport_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TRANSPORT.
UA_MessageType_decodeBinary()
static UA_INLINE UA_StatusCode UA_MessageType_decodeBinary (const UA_ByteString * src, size_t * offset, UA_MessageType * dst) static
Definition at line 79 of file transport_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TRANSPORT.
UA_MessageType_encodeBinary()
static UA_INLINE UA_StatusCode UA_MessageType_encodeBinary (const UA_MessageType * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 75 of file transport_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TRANSPORT.
UA_SecureConversationMessageAbortBody_calcSizeBinary()
static UA_INLINE size_t UA_SecureConversationMessageAbortBody_calcSizeBinary (const UA_SecureConversationMessageAbortBody * src) static
Definition at line 15 of file transport_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TRANSPORT.
UA_SecureConversationMessageAbortBody_decodeBinary()
static UA_INLINE UA_StatusCode UA_SecureConversationMessageAbortBody_decodeBinary (const UA_ByteString * src, size_t * offset, UA_SecureConversationMessageAbortBody * dst) static
Definition at line 23 of file transport_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TRANSPORT.
UA_SecureConversationMessageAbortBody_encodeBinary()
static UA_INLINE UA_StatusCode UA_SecureConversationMessageAbortBody_encodeBinary (const UA_SecureConversationMessageAbortBody * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 19 of file transport_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TRANSPORT.
UA_SecureConversationMessageFooter_calcSizeBinary()
static UA_INLINE size_t UA_SecureConversationMessageFooter_calcSizeBinary (const UA_SecureConversationMessageFooter * src) static
Definition at line 29 of file transport_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TRANSPORT.
UA_SecureConversationMessageFooter_decodeBinary()
static UA_INLINE UA_StatusCode UA_SecureConversationMessageFooter_decodeBinary (const UA_ByteString * src, size_t * offset, UA_SecureConversationMessageFooter * dst) static
Definition at line 37 of file transport_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TRANSPORT.
UA_SecureConversationMessageFooter_encodeBinary()
static UA_INLINE UA_StatusCode UA_SecureConversationMessageFooter_encodeBinary (const UA_SecureConversationMessageFooter * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 33 of file transport_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TRANSPORT.
UA_SecureConversationMessageHeader_calcSizeBinary()
static UA_INLINE size_t UA_SecureConversationMessageHeader_calcSizeBinary (const UA_SecureConversationMessageHeader * src) static
Definition at line 169 of file transport_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TRANSPORT.
UA_SecureConversationMessageHeader_decodeBinary()
static UA_INLINE UA_StatusCode UA_SecureConversationMessageHeader_decodeBinary (const UA_ByteString * src, size_t * offset, UA_SecureConversationMessageHeader * dst) static
Definition at line 177 of file transport_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TRANSPORT.
UA_SecureConversationMessageHeader_encodeBinary()
static UA_INLINE UA_StatusCode UA_SecureConversationMessageHeader_encodeBinary (const UA_SecureConversationMessageHeader * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 173 of file transport_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TRANSPORT.
UA_SequenceHeader_calcSizeBinary()
static UA_INLINE size_t UA_SequenceHeader_calcSizeBinary (const UA_SequenceHeader * src) static
Definition at line 113 of file transport_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TRANSPORT.
UA_SequenceHeader_decodeBinary()
static UA_INLINE UA_StatusCode UA_SequenceHeader_decodeBinary (const UA_ByteString * src, size_t * offset, UA_SequenceHeader * dst) static
Definition at line 121 of file transport_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TRANSPORT.
UA_SequenceHeader_encodeBinary()
static UA_INLINE UA_StatusCode UA_SequenceHeader_encodeBinary (const UA_SequenceHeader * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 117 of file transport_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TRANSPORT.
UA_SymmetricAlgorithmSecurityHeader_calcSizeBinary()
static UA_INLINE size_t UA_SymmetricAlgorithmSecurityHeader_calcSizeBinary (const UA_SymmetricAlgorithmSecurityHeader * src) static
Definition at line 155 of file transport_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TRANSPORT.
UA_SymmetricAlgorithmSecurityHeader_decodeBinary()
static UA_INLINE UA_StatusCode UA_SymmetricAlgorithmSecurityHeader_decodeBinary (const UA_ByteString * src, size_t * offset, UA_SymmetricAlgorithmSecurityHeader * dst) static
Definition at line 163 of file transport_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TRANSPORT.
UA_SymmetricAlgorithmSecurityHeader_encodeBinary()
static UA_INLINE UA_StatusCode UA_SymmetricAlgorithmSecurityHeader_encodeBinary (const UA_SymmetricAlgorithmSecurityHeader * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 159 of file transport_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TRANSPORT.
UA_TcpAcknowledgeMessage_calcSizeBinary()
static UA_INLINE size_t UA_TcpAcknowledgeMessage_calcSizeBinary (const UA_TcpAcknowledgeMessage * src) static
Definition at line 99 of file transport_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TRANSPORT.
UA_TcpAcknowledgeMessage_decodeBinary()
static UA_INLINE UA_StatusCode UA_TcpAcknowledgeMessage_decodeBinary (const UA_ByteString * src, size_t * offset, UA_TcpAcknowledgeMessage * dst) static
Definition at line 107 of file transport_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TRANSPORT.
UA_TcpAcknowledgeMessage_encodeBinary()
static UA_INLINE UA_StatusCode UA_TcpAcknowledgeMessage_encodeBinary (const UA_TcpAcknowledgeMessage * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 103 of file transport_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TRANSPORT.
UA_TcpErrorMessage_calcSizeBinary()
static UA_INLINE size_t UA_TcpErrorMessage_calcSizeBinary (const UA_TcpErrorMessage * src) static
Definition at line 57 of file transport_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TRANSPORT.
UA_TcpErrorMessage_decodeBinary()
static UA_INLINE UA_StatusCode UA_TcpErrorMessage_decodeBinary (const UA_ByteString * src, size_t * offset, UA_TcpErrorMessage * dst) static
Definition at line 65 of file transport_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TRANSPORT.
UA_TcpErrorMessage_encodeBinary()
static UA_INLINE UA_StatusCode UA_TcpErrorMessage_encodeBinary (const UA_TcpErrorMessage * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 61 of file transport_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TRANSPORT.
UA_TcpHelloMessage_calcSizeBinary()
static UA_INLINE size_t UA_TcpHelloMessage_calcSizeBinary (const UA_TcpHelloMessage * src) static
Definition at line 43 of file transport_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TRANSPORT.
UA_TcpHelloMessage_decodeBinary()
static UA_INLINE UA_StatusCode UA_TcpHelloMessage_decodeBinary (const UA_ByteString * src, size_t * offset, UA_TcpHelloMessage * dst) static
Definition at line 51 of file transport_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TRANSPORT.
UA_TcpHelloMessage_encodeBinary()
static UA_INLINE UA_StatusCode UA_TcpHelloMessage_encodeBinary (const UA_TcpHelloMessage * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 47 of file transport_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TRANSPORT.
UA_TcpMessageHeader_calcSizeBinary()
static UA_INLINE size_t UA_TcpMessageHeader_calcSizeBinary (const UA_TcpMessageHeader * src) static
Definition at line 127 of file transport_generated_encoding_binary.h.
References UA_calcSizeBinary(), and UA_TRANSPORT.
UA_TcpMessageHeader_decodeBinary()
static UA_INLINE UA_StatusCode UA_TcpMessageHeader_decodeBinary (const UA_ByteString * src, size_t * offset, UA_TcpMessageHeader * dst) static
Definition at line 135 of file transport_generated_encoding_binary.h.
References UA_decodeBinary(), and UA_TRANSPORT.
UA_TcpMessageHeader_encodeBinary()
static UA_INLINE UA_StatusCode UA_TcpMessageHeader_encodeBinary (const UA_TcpMessageHeader * src, UA_Byte ** bufPos, const UA_Byte * bufEnd) static
Definition at line 131 of file transport_generated_encoding_binary.h.
References UA_encodeBinary(), and UA_TRANSPORT.