Project Template: client_highlevel_async.h File Reference
client_highlevel_async.h File Reference
Typedefs
typedef void(* UA_ClientAsyncWriteCallback) (UA_Client *client, void *userdata, UA_UInt32 requestId, UA_WriteResponse *wr)
typedef void(* UA_ClientAsyncBrowseCallback) (UA_Client *client, void *userdata, UA_UInt32 requestId, UA_BrowseResponse *wr)
typedef void(* UA_ClientAsyncReadDataTypeAttributeCallback) (UA_Client *client, void *userdata, UA_UInt32 requestId, UA_NodeId *var)
typedef void(* UA_ClientAsyncReadValueAttributeCallback) (UA_Client *client, void *userdata, UA_UInt32 requestId, UA_Variant *var)
typedef void(* UA_ClientAsyncReadNodeIdAttributeCallback) (UA_Client *client, void *userdata, UA_UInt32 requestId, UA_NodeId *out)
typedef void(* UA_ClientAsyncReadNodeClassAttributeCallback) (UA_Client *client, void *userdata, UA_UInt32 requestId, UA_NodeClass *out)
typedef void(* UA_ClientAsyncReadBrowseNameAttributeCallback) (UA_Client *client, void *userdata, UA_UInt32 requestId, UA_QualifiedName *out)
typedef void(* UA_ClientAsyncReadDisplayNameAttributeCallback) (UA_Client *client, void *userdata, UA_UInt32 requestId, UA_LocalizedText *out)
typedef void(* UA_ClientAsyncReadDescriptionAttributeCallback) (UA_Client *client, void *userdata, UA_UInt32 requestId, UA_LocalizedText *out)
typedef void(* UA_ClientAsyncReadWriteMaskAttributeCallback) (UA_Client *client, void *userdata, UA_UInt32 requestId, UA_UInt32 *out)
typedef void(* UA_ClientAsyncReadUserWriteMaskAttributeCallback) (UA_Client *client, void *userdata, UA_UInt32 requestId, UA_UInt32 *out)
typedef void(* UA_ClientAsyncReadIsAbstractAttributeCallback) (UA_Client *client, void *userdata, UA_UInt32 requestId, UA_Boolean *out)
typedef void(* UA_ClientAsyncReadSymmetricAttributeCallback) (UA_Client *client, void *userdata, UA_UInt32 requestId, UA_Boolean *out)
typedef void(* UA_ClientAsyncReadInverseNameAttributeCallback) (UA_Client *client, void *userdata, UA_UInt32 requestId, UA_LocalizedText *out)
typedef void(* UA_ClientAsyncReadContainsNoLoopsAttributeCallback) (UA_Client *client, void *userdata, UA_UInt32 requestId, UA_Boolean *out)
typedef void(* UA_ClientAsyncReadEventNotifierAttributeCallback) (UA_Client *client, void *userdata, UA_UInt32 requestId, UA_Byte *out)
typedef void(* UA_ClientAsyncReadValueRankAttributeCallback) (UA_Client *client, void *userdata, UA_UInt32 requestId, UA_Int32 *out)
typedef void(* UA_ClientAsyncReadAccessLevelAttributeCallback) (UA_Client *client, void *userdata, UA_UInt32 requestId, UA_Byte *out)
typedef void(* UA_ClientAsyncReadUserAccessLevelAttributeCallback) (UA_Client *client, void *userdata, UA_UInt32 requestId, UA_Byte *out)
typedef void(* UA_ClientAsyncReadMinimumSamplingIntervalAttributeCallback) (UA_Client *client, void *userdata, UA_UInt32 requestId, UA_Double *out)
typedef void(* UA_ClientAsyncReadHistorizingAttributeCallback) (UA_Client *client, void *userdata, UA_UInt32 requestId, UA_Boolean *out)
typedef void(* UA_ClientAsyncReadExecutableAttributeCallback) (UA_Client *client, void *userdata, UA_UInt32 requestId, UA_Boolean *out)
typedef void(* UA_ClientAsyncReadUserExecutableAttributeCallback) (UA_Client *client, void *userdata, UA_UInt32 requestId, UA_Boolean *out)
typedef void(* UA_ClientAsyncCallCallback) (UA_Client *client, void *userdata, UA_UInt32 requestId, UA_CallResponse *cr)
typedef void(* UA_ClientAsyncAddNodesCallback) (UA_Client *client, void *userdata, UA_UInt32 requestId, UA_AddNodesResponse *ar)
typedef void(* UA_ClientAsyncTranslateCallback) (UA_Client *client, void *userdata, UA_UInt32 requestId, UA_TranslateBrowsePathsToNodeIdsResponse *tr)
Functions
static UA_INLINE UA_StatusCode UA_Client_sendAsyncReadRequest (UA_Client *client, UA_ReadRequest *request, UA_ClientAsyncReadCallback readCallback, void *userdata, UA_UInt32 *reqId)
static UA_INLINE UA_StatusCode UA_Client_sendAsyncWriteRequest (UA_Client *client, UA_WriteRequest *request, UA_ClientAsyncWriteCallback writeCallback, void *userdata, UA_UInt32 *reqId)
static UA_INLINE UA_StatusCode UA_Client_sendAsyncBrowseRequest (UA_Client *client, UA_BrowseRequest *request, UA_ClientAsyncBrowseCallback browseCallback, void *userdata, UA_UInt32 *reqId)
UA_StatusCode UA_EXPORT __UA_Client_readAttribute_async (UA_Client *client, const UA_NodeId *nodeId, UA_AttributeId attributeId, const UA_DataType *outDataType, UA_ClientAsyncServiceCallback callback, void *userdata, UA_UInt32 *reqId)
static UA_INLINE UA_StatusCode UA_Client_readDataTypeAttribute_async (UA_Client *client, const UA_NodeId nodeId, UA_ClientAsyncReadDataTypeAttributeCallback callback, void *userdata, UA_UInt32 *reqId)
static UA_INLINE UA_StatusCode UA_Client_readValueAttribute_async (UA_Client *client, const UA_NodeId nodeId, UA_ClientAsyncReadValueAttributeCallback callback, void *userdata, UA_UInt32 *reqId)
static UA_INLINE UA_StatusCode UA_Client_readNodeIdAttribute_async (UA_Client *client, const UA_NodeId nodeId, UA_ClientAsyncReadNodeIdAttributeCallback callback, void *userdata, UA_UInt32 *reqId)
static UA_INLINE UA_StatusCode UA_Client_readNodeClassAttribute_async (UA_Client *client, const UA_NodeId nodeId, UA_ClientAsyncReadNodeClassAttributeCallback callback, void *userdata, UA_UInt32 *reqId)
static UA_INLINE UA_StatusCode UA_Client_readBrowseNameAttribute_async (UA_Client *client, const UA_NodeId nodeId, UA_ClientAsyncReadBrowseNameAttributeCallback callback, void *userdata, UA_UInt32 *reqId)
static UA_INLINE UA_StatusCode UA_Client_readDisplayNameAttribute_async (UA_Client *client, const UA_NodeId nodeId, UA_ClientAsyncReadDisplayNameAttributeCallback callback, void *userdata, UA_UInt32 *reqId)
static UA_INLINE UA_StatusCode UA_Client_readDescriptionAttribute_async (UA_Client *client, const UA_NodeId nodeId, UA_ClientAsyncReadDescriptionAttributeCallback callback, void *userdata, UA_UInt32 *reqId)
static UA_INLINE UA_StatusCode UA_Client_readWriteMaskAttribute_async (UA_Client *client, const UA_NodeId nodeId, UA_ClientAsyncReadWriteMaskAttributeCallback callback, void *userdata, UA_UInt32 *reqId)
static UA_INLINE UA_StatusCode UA_Client_readUserWriteMaskAttribute_async (UA_Client *client, const UA_NodeId nodeId, UA_ClientAsyncReadUserWriteMaskAttributeCallback callback, void *userdata, UA_UInt32 *reqId)
static UA_INLINE UA_StatusCode UA_Client_readIsAbstractAttribute_async (UA_Client *client, const UA_NodeId nodeId, UA_ClientAsyncReadIsAbstractAttributeCallback callback, void *userdata, UA_UInt32 *reqId)
static UA_INLINE UA_StatusCode UA_Client_readSymmetricAttribute_async (UA_Client *client, const UA_NodeId nodeId, UA_ClientAsyncReadSymmetricAttributeCallback callback, void *userdata, UA_UInt32 *reqId)
static UA_INLINE UA_StatusCode UA_Client_readInverseNameAttribute_async (UA_Client *client, const UA_NodeId nodeId, UA_ClientAsyncReadInverseNameAttributeCallback callback, void *userdata, UA_UInt32 *reqId)
static UA_INLINE UA_StatusCode UA_Client_readContainsNoLoopsAttribute_async (UA_Client *client, const UA_NodeId nodeId, UA_ClientAsyncReadContainsNoLoopsAttributeCallback callback, void *userdata, UA_UInt32 *reqId)
static UA_INLINE UA_StatusCode UA_Client_readEventNotifierAttribute_async (UA_Client *client, const UA_NodeId nodeId, UA_ClientAsyncReadEventNotifierAttributeCallback callback, void *userdata, UA_UInt32 *reqId)
static UA_INLINE UA_StatusCode UA_Client_readValueRankAttribute_async (UA_Client *client, const UA_NodeId nodeId, UA_ClientAsyncReadValueRankAttributeCallback callback, void *userdata, UA_UInt32 *reqId)
static UA_INLINE UA_StatusCode UA_Client_readAccessLevelAttribute_async (UA_Client *client, const UA_NodeId nodeId, UA_ClientAsyncReadAccessLevelAttributeCallback callback, void *userdata, UA_UInt32 *reqId)
static UA_INLINE UA_StatusCode UA_Client_readUserAccessLevelAttribute_async (UA_Client *client, const UA_NodeId nodeId, UA_ClientAsyncReadUserAccessLevelAttributeCallback callback, void *userdata, UA_UInt32 *reqId)
static UA_INLINE UA_StatusCode UA_Client_readMinimumSamplingIntervalAttribute_async (UA_Client *client, const UA_NodeId nodeId, UA_ClientAsyncReadMinimumSamplingIntervalAttributeCallback callback, void *userdata, UA_UInt32 *reqId)
static UA_INLINE UA_StatusCode UA_Client_readHistorizingAttribute_async (UA_Client *client, const UA_NodeId nodeId, UA_ClientAsyncReadHistorizingAttributeCallback callback, void *userdata, UA_UInt32 *reqId)
static UA_INLINE UA_StatusCode UA_Client_readExecutableAttribute_async (UA_Client *client, const UA_NodeId nodeId, UA_ClientAsyncReadExecutableAttributeCallback callback, void *userdata, UA_UInt32 *reqId)
static UA_INLINE UA_StatusCode UA_Client_readUserExecutableAttribute_async (UA_Client *client, const UA_NodeId nodeId, UA_ClientAsyncReadUserExecutableAttributeCallback callback, void *userdata, UA_UInt32 *reqId)
UA_StatusCode UA_EXPORT __UA_Client_writeAttribute_async (UA_Client *client, const UA_NodeId *nodeId, UA_AttributeId attributeId, const void *in, const UA_DataType *inDataType, UA_ClientAsyncServiceCallback callback, void *userdata, UA_UInt32 *reqId)
static UA_INLINE UA_StatusCode UA_Client_writeValueAttribute_async (UA_Client *client, const UA_NodeId nodeId, const UA_Variant *newValue, UA_ClientAsyncWriteCallback callback, void *userdata, UA_UInt32 *reqId)
static UA_INLINE UA_StatusCode UA_Client_writeNodeIdAttribute_async (UA_Client *client, const UA_NodeId nodeId, const UA_NodeId *outNodeId, UA_ClientAsyncServiceCallback callback, void *userdata, UA_UInt32 *reqId)
static UA_INLINE UA_StatusCode UA_Client_writeNodeClassAttribute_async (UA_Client *client, const UA_NodeId nodeId, const UA_NodeClass *outNodeClass, UA_ClientAsyncServiceCallback callback, void *userdata, UA_UInt32 *reqId)
static UA_INLINE UA_StatusCode UA_Client_writeBrowseNameAttribute_async (UA_Client *client, const UA_NodeId nodeId, const UA_QualifiedName *outBrowseName, UA_ClientAsyncServiceCallback callback, void *userdata, UA_UInt32 *reqId)
static UA_INLINE UA_StatusCode UA_Client_writeDisplayNameAttribute_async (UA_Client *client, const UA_NodeId nodeId, const UA_LocalizedText *outDisplayName, UA_ClientAsyncServiceCallback callback, void *userdata, UA_UInt32 *reqId)
static UA_INLINE UA_StatusCode UA_Client_writeDescriptionAttribute_async (UA_Client *client, const UA_NodeId nodeId, const UA_LocalizedText *outDescription, UA_ClientAsyncServiceCallback callback, void *userdata, UA_UInt32 *reqId)
static UA_INLINE UA_StatusCode UA_Client_writeWriteMaskAttribute_async (UA_Client *client, const UA_NodeId nodeId, const UA_UInt32 *outWriteMask, UA_ClientAsyncServiceCallback callback, void *userdata, UA_UInt32 *reqId)
static UA_INLINE UA_StatusCode UA_Client_writeUserWriteMaskAttribute_async (UA_Client *client, const UA_NodeId nodeId, const UA_UInt32 *outUserWriteMask, UA_ClientAsyncServiceCallback callback, void *userdata, UA_UInt32 *reqId)
static UA_INLINE UA_StatusCode UA_Client_writeIsAbstractAttribute_async (UA_Client *client, const UA_NodeId nodeId, const UA_Boolean *outIsAbstract, UA_ClientAsyncServiceCallback callback, void *userdata, UA_UInt32 *reqId)
static UA_INLINE UA_StatusCode UA_Client_writeSymmetricAttribute_async (UA_Client *client, const UA_NodeId nodeId, const UA_Boolean *outSymmetric, UA_ClientAsyncServiceCallback callback, void *userdata, UA_UInt32 *reqId)
static UA_INLINE UA_StatusCode UA_Client_writeInverseNameAttribute_async (UA_Client *client, const UA_NodeId nodeId, const UA_LocalizedText *outInverseName, UA_ClientAsyncServiceCallback callback, void *userdata, UA_UInt32 *reqId)
static UA_INLINE UA_StatusCode UA_Client_writeContainsNoLoopsAttribute_async (UA_Client *client, const UA_NodeId nodeId, const UA_Boolean *outContainsNoLoops, UA_ClientAsyncServiceCallback callback, void *userdata, UA_UInt32 *reqId)
static UA_INLINE UA_StatusCode UA_Client_writeEventNotifierAttribute_async (UA_Client *client, const UA_NodeId nodeId, const UA_Byte *outEventNotifier, UA_ClientAsyncServiceCallback callback, void *userdata, UA_UInt32 *reqId)
static UA_INLINE UA_StatusCode UA_Client_writeDataTypeAttribute_async (UA_Client *client, const UA_NodeId nodeId, const UA_NodeId *outDataType, UA_ClientAsyncServiceCallback callback, void *userdata, UA_UInt32 *reqId)
static UA_INLINE UA_StatusCode UA_Client_writeValueRankAttribute_async (UA_Client *client, const UA_NodeId nodeId, const UA_Int32 *outValueRank, UA_ClientAsyncServiceCallback callback, void *userdata, UA_UInt32 *reqId)
static UA_INLINE UA_StatusCode UA_Client_writeAccessLevelAttribute_async (UA_Client *client, const UA_NodeId nodeId, const UA_Byte *outAccessLevel, UA_ClientAsyncServiceCallback callback, void *userdata, UA_UInt32 *reqId)
static UA_INLINE UA_StatusCode UA_Client_writeUserAccessLevelAttribute_async (UA_Client *client, const UA_NodeId nodeId, const UA_Byte *outUserAccessLevel, UA_ClientAsyncServiceCallback callback, void *userdata, UA_UInt32 *reqId)
static UA_INLINE UA_StatusCode UA_Client_writeMinimumSamplingIntervalAttribute_async (UA_Client *client, const UA_NodeId nodeId, const UA_Double *outMinimumSamplingInterval, UA_ClientAsyncServiceCallback callback, void *userdata, UA_UInt32 *reqId)
static UA_INLINE UA_StatusCode UA_Client_writeHistorizingAttribute_async (UA_Client *client, const UA_NodeId nodeId, const UA_Boolean *outHistorizing, UA_ClientAsyncServiceCallback callback, void *userdata, UA_UInt32 *reqId)
static UA_INLINE UA_StatusCode UA_Client_writeExecutableAttribute_async (UA_Client *client, const UA_NodeId nodeId, const UA_Boolean *outExecutable, UA_ClientAsyncServiceCallback callback, void *userdata, UA_UInt32 *reqId)
static UA_INLINE UA_StatusCode UA_Client_writeUserExecutableAttribute_async (UA_Client *client, const UA_NodeId nodeId, const UA_Boolean *outUserExecutable, UA_ClientAsyncServiceCallback callback, void *userdata, UA_UInt32 *reqId)
UA_StatusCode UA_EXPORT __UA_Client_call_async (UA_Client *client, const UA_NodeId objectId, const UA_NodeId methodId, size_t inputSize, const UA_Variant *input, UA_ClientAsyncServiceCallback callback, void *userdata, UA_UInt32 *reqId)
static UA_INLINE UA_StatusCode UA_Client_call_async (UA_Client *client, const UA_NodeId objectId, const UA_NodeId methodId, size_t inputSize, const UA_Variant *input, UA_ClientAsyncCallCallback callback, void *userdata, UA_UInt32 *reqId)
UA_StatusCode UA_EXPORT __UA_Client_addNode_async (UA_Client *client, const UA_NodeClass nodeClass, const UA_NodeId requestedNewNodeId, const UA_NodeId parentNodeId, const UA_NodeId referenceTypeId, const UA_QualifiedName browseName, const UA_NodeId typeDefinition, const UA_NodeAttributes *attr, const UA_DataType *attributeType, UA_NodeId *outNewNodeId, UA_ClientAsyncServiceCallback callback, void *userdata, UA_UInt32 *reqId)
static UA_INLINE UA_StatusCode UA_Client_addVariableNode_async (UA_Client *client, const UA_NodeId requestedNewNodeId, const UA_NodeId parentNodeId, const UA_NodeId referenceTypeId, const UA_QualifiedName browseName, const UA_NodeId typeDefinition, const UA_VariableAttributes attr, UA_NodeId *outNewNodeId, UA_ClientAsyncAddNodesCallback callback, void *userdata, UA_UInt32 *reqId)
static UA_INLINE UA_StatusCode UA_Client_addVariableTypeNode_async (UA_Client *client, const UA_NodeId requestedNewNodeId, const UA_NodeId parentNodeId, const UA_NodeId referenceTypeId, const UA_QualifiedName browseName, const UA_VariableTypeAttributes attr, UA_NodeId *outNewNodeId, UA_ClientAsyncAddNodesCallback callback, void *userdata, UA_UInt32 *reqId)
static UA_INLINE UA_StatusCode UA_Client_addObjectNode_async (UA_Client *client, const UA_NodeId requestedNewNodeId, const UA_NodeId parentNodeId, const UA_NodeId referenceTypeId, const UA_QualifiedName browseName, const UA_NodeId typeDefinition, const UA_ObjectAttributes attr, UA_NodeId *outNewNodeId, UA_ClientAsyncAddNodesCallback callback, void *userdata, UA_UInt32 *reqId)
static UA_INLINE UA_StatusCode UA_Client_addObjectTypeNode_async (UA_Client *client, const UA_NodeId requestedNewNodeId, const UA_NodeId parentNodeId, const UA_NodeId referenceTypeId, const UA_QualifiedName browseName, const UA_ObjectTypeAttributes attr, UA_NodeId *outNewNodeId, UA_ClientAsyncAddNodesCallback callback, void *userdata, UA_UInt32 *reqId)
static UA_INLINE UA_StatusCode UA_Client_addViewNode_async (UA_Client *client, const UA_NodeId requestedNewNodeId, const UA_NodeId parentNodeId, const UA_NodeId referenceTypeId, const UA_QualifiedName browseName, const UA_ViewAttributes attr, UA_NodeId *outNewNodeId, UA_ClientAsyncAddNodesCallback callback, void *userdata, UA_UInt32 *reqId)
static UA_INLINE UA_StatusCode UA_Client_addReferenceTypeNode_async (UA_Client *client, const UA_NodeId requestedNewNodeId, const UA_NodeId parentNodeId, const UA_NodeId referenceTypeId, const UA_QualifiedName browseName, const UA_ReferenceTypeAttributes attr, UA_NodeId *outNewNodeId, UA_ClientAsyncAddNodesCallback callback, void *userdata, UA_UInt32 *reqId)
static UA_INLINE UA_StatusCode UA_Client_addDataTypeNode_async (UA_Client *client, const UA_NodeId requestedNewNodeId, const UA_NodeId parentNodeId, const UA_NodeId referenceTypeId, const UA_QualifiedName browseName, const UA_DataTypeAttributes attr, UA_NodeId *outNewNodeId, UA_ClientAsyncAddNodesCallback callback, void *userdata, UA_UInt32 *reqId)
static UA_INLINE UA_StatusCode UA_Client_addMethodNode_async (UA_Client *client, const UA_NodeId requestedNewNodeId, const UA_NodeId parentNodeId, const UA_NodeId referenceTypeId, const UA_QualifiedName browseName, const UA_MethodAttributes attr, UA_NodeId *outNewNodeId, UA_ClientAsyncAddNodesCallback callback, void *userdata, UA_UInt32 *reqId)
UA_StatusCode UA_EXPORT __UA_Client_translateBrowsePathsToNodeIds_async (UA_Client *client, char *paths[], UA_UInt32 ids[], size_t pathSize, UA_ClientAsyncServiceCallback callback, void *userdata, UA_UInt32 *reqId)
static UA_INLINE UA_StatusCode UA_Cient_translateBrowsePathsToNodeIds_async (UA_Client *client, char **paths, UA_UInt32 *ids, size_t pathSize, UA_ClientAsyncTranslateCallback callback, void *userdata, UA_UInt32 *reqId)
Variables
_UA_BEGIN_DECLS typedef void(* UA_ClientAsyncReadCallback)(UA_Client *client, void *userdata, UA_UInt32 requestId, UA_ReadResponse *rr)
Typedef Documentation
UA_ClientAsyncAddNodesCallback
typedef void(* UA_ClientAsyncAddNodesCallback) (UA_Client *client, void *userdata, UA_UInt32 requestId, UA_AddNodesResponse *ar)
Node Management ^^^^^^^^^^^^^^^
Definition at line 567 of file client_highlevel_async.h.
UA_ClientAsyncBrowseCallback
typedef void(* UA_ClientAsyncBrowseCallback) (UA_Client *client, void *userdata, UA_UInt32 requestId, UA_BrowseResponse *wr)
Definition at line 42 of file client_highlevel_async.h.
UA_ClientAsyncCallCallback
typedef void(* UA_ClientAsyncCallCallback) (UA_Client *client, void *userdata, UA_UInt32 requestId, UA_CallResponse *cr)
Definition at line 550 of file client_highlevel_async.h.
UA_ClientAsyncReadAccessLevelAttributeCallback
typedef void(* UA_ClientAsyncReadAccessLevelAttributeCallback) (UA_Client *client, void *userdata, UA_UInt32 requestId, UA_Byte *out)
Definition at line 259 of file client_highlevel_async.h.
UA_ClientAsyncReadBrowseNameAttributeCallback
typedef void(* UA_ClientAsyncReadBrowseNameAttributeCallback) (UA_Client *client, void *userdata, UA_UInt32 requestId, UA_QualifiedName *out)
Definition at line 116 of file client_highlevel_async.h.
UA_ClientAsyncReadContainsNoLoopsAttributeCallback
typedef void(* UA_ClientAsyncReadContainsNoLoopsAttributeCallback) (UA_Client *client, void *userdata, UA_UInt32 requestId, UA_Boolean *out)
Definition at line 220 of file client_highlevel_async.h.
UA_ClientAsyncReadDataTypeAttributeCallback
typedef void(* UA_ClientAsyncReadDataTypeAttributeCallback) (UA_Client *client, void *userdata, UA_UInt32 requestId, UA_NodeId *var)
Definition at line 64 of file client_highlevel_async.h.
UA_ClientAsyncReadDescriptionAttributeCallback
typedef void(* UA_ClientAsyncReadDescriptionAttributeCallback) (UA_Client *client, void *userdata, UA_UInt32 requestId, UA_LocalizedText *out)
Definition at line 142 of file client_highlevel_async.h.
UA_ClientAsyncReadDisplayNameAttributeCallback
typedef void(* UA_ClientAsyncReadDisplayNameAttributeCallback) (UA_Client *client, void *userdata, UA_UInt32 requestId, UA_LocalizedText *out)
Definition at line 129 of file client_highlevel_async.h.
UA_ClientAsyncReadEventNotifierAttributeCallback
typedef void(* UA_ClientAsyncReadEventNotifierAttributeCallback) (UA_Client *client, void *userdata, UA_UInt32 requestId, UA_Byte *out)
Definition at line 233 of file client_highlevel_async.h.
UA_ClientAsyncReadExecutableAttributeCallback
typedef void(* UA_ClientAsyncReadExecutableAttributeCallback) (UA_Client *client, void *userdata, UA_UInt32 requestId, UA_Boolean *out)
Definition at line 310 of file client_highlevel_async.h.
UA_ClientAsyncReadHistorizingAttributeCallback
typedef void(* UA_ClientAsyncReadHistorizingAttributeCallback) (UA_Client *client, void *userdata, UA_UInt32 requestId, UA_Boolean *out)
Definition at line 297 of file client_highlevel_async.h.
UA_ClientAsyncReadInverseNameAttributeCallback
typedef void(* UA_ClientAsyncReadInverseNameAttributeCallback) (UA_Client *client, void *userdata, UA_UInt32 requestId, UA_LocalizedText *out)
Definition at line 207 of file client_highlevel_async.h.
UA_ClientAsyncReadIsAbstractAttributeCallback
typedef void(* UA_ClientAsyncReadIsAbstractAttributeCallback) (UA_Client *client, void *userdata, UA_UInt32 requestId, UA_Boolean *out)
Definition at line 181 of file client_highlevel_async.h.
UA_ClientAsyncReadMinimumSamplingIntervalAttributeCallback
typedef void(* UA_ClientAsyncReadMinimumSamplingIntervalAttributeCallback) (UA_Client *client, void *userdata, UA_UInt32 requestId, UA_Double *out)
Definition at line 285 of file client_highlevel_async.h.
UA_ClientAsyncReadNodeClassAttributeCallback
typedef void(* UA_ClientAsyncReadNodeClassAttributeCallback) (UA_Client *client, void *userdata, UA_UInt32 requestId, UA_NodeClass *out)
Definition at line 103 of file client_highlevel_async.h.
UA_ClientAsyncReadNodeIdAttributeCallback
typedef void(* UA_ClientAsyncReadNodeIdAttributeCallback) (UA_Client *client, void *userdata, UA_UInt32 requestId, UA_NodeId *out)
Definition at line 91 of file client_highlevel_async.h.
UA_ClientAsyncReadSymmetricAttributeCallback
typedef void(* UA_ClientAsyncReadSymmetricAttributeCallback) (UA_Client *client, void *userdata, UA_UInt32 requestId, UA_Boolean *out)
Definition at line 194 of file client_highlevel_async.h.
UA_ClientAsyncReadUserAccessLevelAttributeCallback
typedef void(* UA_ClientAsyncReadUserAccessLevelAttributeCallback) (UA_Client *client, void *userdata, UA_UInt32 requestId, UA_Byte *out)
Definition at line 272 of file client_highlevel_async.h.
UA_ClientAsyncReadUserExecutableAttributeCallback
typedef void(* UA_ClientAsyncReadUserExecutableAttributeCallback) (UA_Client *client, void *userdata, UA_UInt32 requestId, UA_Boolean *out)
Definition at line 323 of file client_highlevel_async.h.
UA_ClientAsyncReadUserWriteMaskAttributeCallback
typedef void(* UA_ClientAsyncReadUserWriteMaskAttributeCallback) (UA_Client *client, void *userdata, UA_UInt32 requestId, UA_UInt32 *out)
Definition at line 168 of file client_highlevel_async.h.
UA_ClientAsyncReadValueAttributeCallback
typedef void(* UA_ClientAsyncReadValueAttributeCallback) (UA_Client *client, void *userdata, UA_UInt32 requestId, UA_Variant *var)
Definition at line 78 of file client_highlevel_async.h.
UA_ClientAsyncReadValueRankAttributeCallback
typedef void(* UA_ClientAsyncReadValueRankAttributeCallback) (UA_Client *client, void *userdata, UA_UInt32 requestId, UA_Int32 *out)
Definition at line 246 of file client_highlevel_async.h.
UA_ClientAsyncReadWriteMaskAttributeCallback
typedef void(* UA_ClientAsyncReadWriteMaskAttributeCallback) (UA_Client *client, void *userdata, UA_UInt32 requestId, UA_UInt32 *out)
Definition at line 155 of file client_highlevel_async.h.
UA_ClientAsyncTranslateCallback
typedef void(* UA_ClientAsyncTranslateCallback) (UA_Client *client, void *userdata, UA_UInt32 requestId, UA_TranslateBrowsePathsToNodeIdsResponse *tr)
Definition at line 706 of file client_highlevel_async.h.
UA_ClientAsyncWriteCallback
typedef void(* UA_ClientAsyncWriteCallback) (UA_Client *client, void *userdata, UA_UInt32 requestId, UA_WriteResponse *wr)
Definition at line 31 of file client_highlevel_async.h.
Function Documentation
__UA_Client_addNode_async()
UA_StatusCode UA_EXPORT __UA_Client_addNode_async (UA_Client * client, const UA_NodeClass nodeClass, const UA_NodeId requestedNewNodeId, const UA_NodeId parentNodeId, const UA_NodeId referenceTypeId, const UA_QualifiedName browseName, const UA_NodeId typeDefinition, const UA_NodeAttributes * attr, const UA_DataType * attributeType, UA_NodeId * outNewNodeId, UA_ClientAsyncServiceCallback callback, void * userdata, UA_UInt32 * reqId)
Referenced by UA_Client_addDataTypeNode_async(), UA_Client_addMethodNode_async(), UA_Client_addObjectNode_async(), UA_Client_addObjectTypeNode_async(), UA_Client_addReferenceTypeNode_async(), UA_Client_addVariableNode_async(), UA_Client_addVariableTypeNode_async(), and UA_Client_addViewNode_async().
__UA_Client_call_async()
UA_StatusCode UA_EXPORT __UA_Client_call_async (UA_Client * client, const UA_NodeId objectId, const UA_NodeId methodId, size_t inputSize, const UA_Variant * input, UA_ClientAsyncServiceCallback callback, void * userdata, UA_UInt32 * reqId)
Method Calling ^^^^^^^^^^^^^^
Referenced by UA_Client_call_async(), and UA_Client_writeUserExecutableAttribute_async().
__UA_Client_readAttribute_async()
UA_StatusCode UA_EXPORT __UA_Client_readAttribute_async (UA_Client * client, const UA_NodeId * nodeId, UA_AttributeId attributeId, const UA_DataType * outDataType, UA_ClientAsyncServiceCallback callback, void * userdata, UA_UInt32 * reqId)
Read Attribute ^^^^^^^^^^^^^^
Referenced by UA_Client_readAccessLevelAttribute_async(), UA_Client_readBrowseNameAttribute_async(), UA_Client_readContainsNoLoopsAttribute_async(), UA_Client_readDataTypeAttribute_async(), UA_Client_readDescriptionAttribute_async(), UA_Client_readDisplayNameAttribute_async(), UA_Client_readEventNotifierAttribute_async(), UA_Client_readExecutableAttribute_async(), UA_Client_readHistorizingAttribute_async(), UA_Client_readInverseNameAttribute_async(), UA_Client_readIsAbstractAttribute_async(), UA_Client_readMinimumSamplingIntervalAttribute_async(), UA_Client_readNodeClassAttribute_async(), UA_Client_readNodeIdAttribute_async(), UA_Client_readSymmetricAttribute_async(), UA_Client_readUserAccessLevelAttribute_async(), UA_Client_readUserExecutableAttribute_async(), UA_Client_readUserWriteMaskAttribute_async(), UA_Client_readValueAttribute_async(), UA_Client_readValueRankAttribute_async(), UA_Client_readWriteMaskAttribute_async(), and UA_Client_sendAsyncBrowseRequest().
__UA_Client_translateBrowsePathsToNodeIds_async()
UA_StatusCode UA_EXPORT __UA_Client_translateBrowsePathsToNodeIds_async (UA_Client * client, char * paths[], UA_UInt32 ids[], size_t pathSize, UA_ClientAsyncServiceCallback callback, void * userdata, UA_UInt32 * reqId)
Misc Functionalities ^^^^^^^^^^^^^^^^^^^^
Referenced by UA_Cient_translateBrowsePathsToNodeIds_async(), and UA_Client_addMethodNode_async().
__UA_Client_writeAttribute_async()
UA_StatusCode UA_EXPORT __UA_Client_writeAttribute_async (UA_Client * client, const UA_NodeId * nodeId, UA_AttributeId attributeId, const void * in, const UA_DataType * inDataType, UA_ClientAsyncServiceCallback callback, void * userdata, UA_UInt32 * reqId)
Write Attribute ^^^^^^^^^^^^^^
Referenced by UA_Client_readUserExecutableAttribute_async(), UA_Client_writeAccessLevelAttribute_async(), UA_Client_writeBrowseNameAttribute_async(), UA_Client_writeContainsNoLoopsAttribute_async(), UA_Client_writeDataTypeAttribute_async(), UA_Client_writeDescriptionAttribute_async(), UA_Client_writeDisplayNameAttribute_async(), UA_Client_writeEventNotifierAttribute_async(), UA_Client_writeExecutableAttribute_async(), UA_Client_writeHistorizingAttribute_async(), UA_Client_writeInverseNameAttribute_async(), UA_Client_writeIsAbstractAttribute_async(), UA_Client_writeMinimumSamplingIntervalAttribute_async(), UA_Client_writeNodeClassAttribute_async(), UA_Client_writeNodeIdAttribute_async(), UA_Client_writeSymmetricAttribute_async(), UA_Client_writeUserAccessLevelAttribute_async(), UA_Client_writeUserExecutableAttribute_async(), UA_Client_writeUserWriteMaskAttribute_async(), UA_Client_writeValueAttribute_async(), UA_Client_writeValueRankAttribute_async(), and UA_Client_writeWriteMaskAttribute_async().
UA_Cient_translateBrowsePathsToNodeIds_async()
static UA_INLINE UA_StatusCode UA_Cient_translateBrowsePathsToNodeIds_async (UA_Client * client, char ** paths, UA_UInt32 * ids, size_t pathSize, UA_ClientAsyncTranslateCallback callback, void * userdata, UA_UInt32 * reqId) static
Definition at line 711 of file client_highlevel_async.h.
References __UA_Client_translateBrowsePathsToNodeIds_async().
UA_Client_addDataTypeNode_async()
static UA_INLINE UA_StatusCode UA_Client_addDataTypeNode_async (UA_Client * client, const UA_NodeId requestedNewNodeId, const UA_NodeId parentNodeId, const UA_NodeId referenceTypeId, const UA_QualifiedName browseName, const UA_DataTypeAttributes attr, UA_NodeId * outNewNodeId, UA_ClientAsyncAddNodesCallback callback, void * userdata, UA_UInt32 * reqId) static
Definition at line 667 of file client_highlevel_async.h.
References __UA_Client_addNode_async(), UA_NODECLASS_DATATYPE, UA_NODEID_NULL, and UA_TYPES.
UA_Client_addMethodNode_async()
static UA_INLINE UA_StatusCode UA_Client_addMethodNode_async (UA_Client * client, const UA_NodeId requestedNewNodeId, const UA_NodeId parentNodeId, const UA_NodeId referenceTypeId, const UA_QualifiedName browseName, const UA_MethodAttributes attr, UA_NodeId * outNewNodeId, UA_ClientAsyncAddNodesCallback callback, void * userdata, UA_UInt32 * reqId) static
Definition at line 682 of file client_highlevel_async.h.
References __UA_Client_addNode_async(), __UA_Client_translateBrowsePathsToNodeIds_async(), UA_NODECLASS_METHOD, UA_NODEID_NULL, and UA_TYPES.
UA_Client_addObjectNode_async()
static UA_INLINE UA_StatusCode UA_Client_addObjectNode_async (UA_Client * client, const UA_NodeId requestedNewNodeId, const UA_NodeId parentNodeId, const UA_NodeId referenceTypeId, const UA_QualifiedName browseName, const UA_NodeId typeDefinition, const UA_ObjectAttributes attr, UA_NodeId * outNewNodeId, UA_ClientAsyncAddNodesCallback callback, void * userdata, UA_UInt32 * reqId) static
Definition at line 611 of file client_highlevel_async.h.
References __UA_Client_addNode_async(), UA_NODECLASS_OBJECT, and UA_TYPES.
UA_Client_addObjectTypeNode_async()
static UA_INLINE UA_StatusCode UA_Client_addObjectTypeNode_async (UA_Client * client, const UA_NodeId requestedNewNodeId, const UA_NodeId parentNodeId, const UA_NodeId referenceTypeId, const UA_QualifiedName browseName, const UA_ObjectTypeAttributes attr, UA_NodeId * outNewNodeId, UA_ClientAsyncAddNodesCallback callback, void * userdata, UA_UInt32 * reqId) static
Definition at line 627 of file client_highlevel_async.h.
References __UA_Client_addNode_async(), UA_NODECLASS_OBJECTTYPE, UA_NODEID_NULL, and UA_TYPES.
UA_Client_addReferenceTypeNode_async()
static UA_INLINE UA_StatusCode UA_Client_addReferenceTypeNode_async (UA_Client * client, const UA_NodeId requestedNewNodeId, const UA_NodeId parentNodeId, const UA_NodeId referenceTypeId, const UA_QualifiedName browseName, const UA_ReferenceTypeAttributes attr, UA_NodeId * outNewNodeId, UA_ClientAsyncAddNodesCallback callback, void * userdata, UA_UInt32 * reqId) static
Definition at line 654 of file client_highlevel_async.h.
References __UA_Client_addNode_async(), UA_NODECLASS_REFERENCETYPE, UA_NODEID_NULL, and UA_TYPES.
UA_Client_addVariableNode_async()
static UA_INLINE UA_StatusCode UA_Client_addVariableNode_async (UA_Client * client, const UA_NodeId requestedNewNodeId, const UA_NodeId parentNodeId, const UA_NodeId referenceTypeId, const UA_QualifiedName browseName, const UA_NodeId typeDefinition, const UA_VariableAttributes attr, UA_NodeId * outNewNodeId, UA_ClientAsyncAddNodesCallback callback, void * userdata, UA_UInt32 * reqId) static
Definition at line 582 of file client_highlevel_async.h.
References __UA_Client_addNode_async(), UA_NODECLASS_VARIABLE, and UA_TYPES.
UA_Client_addVariableTypeNode_async()
static UA_INLINE UA_StatusCode UA_Client_addVariableTypeNode_async (UA_Client * client, const UA_NodeId requestedNewNodeId, const UA_NodeId parentNodeId, const UA_NodeId referenceTypeId, const UA_QualifiedName browseName, const UA_VariableTypeAttributes attr, UA_NodeId * outNewNodeId, UA_ClientAsyncAddNodesCallback callback, void * userdata, UA_UInt32 * reqId) static
Definition at line 598 of file client_highlevel_async.h.
References __UA_Client_addNode_async(), UA_NODECLASS_VARIABLETYPE, UA_NODEID_NULL, and UA_TYPES.
UA_Client_addViewNode_async()
static UA_INLINE UA_StatusCode UA_Client_addViewNode_async (UA_Client * client, const UA_NodeId requestedNewNodeId, const UA_NodeId parentNodeId, const UA_NodeId referenceTypeId, const UA_QualifiedName browseName, const UA_ViewAttributes attr, UA_NodeId * outNewNodeId, UA_ClientAsyncAddNodesCallback callback, void * userdata, UA_UInt32 * reqId) static
Definition at line 640 of file client_highlevel_async.h.
References __UA_Client_addNode_async(), UA_NODECLASS_VIEW, UA_NODEID_NULL, and UA_TYPES.
UA_Client_call_async()
static UA_INLINE UA_StatusCode UA_Client_call_async (UA_Client * client, const UA_NodeId objectId, const UA_NodeId methodId, size_t inputSize, const UA_Variant * input, UA_ClientAsyncCallCallback callback, void * userdata, UA_UInt32 * reqId) static
Definition at line 554 of file client_highlevel_async.h.
References __UA_Client_call_async().
UA_Client_readAccessLevelAttribute_async()
static UA_INLINE UA_StatusCode UA_Client_readAccessLevelAttribute_async (UA_Client * client, const UA_NodeId nodeId, UA_ClientAsyncReadAccessLevelAttributeCallback callback, void * userdata, UA_UInt32 * reqId) static
Definition at line 264 of file client_highlevel_async.h.
References __UA_Client_readAttribute_async(), UA_ATTRIBUTEID_ACCESSLEVEL, and UA_TYPES.
UA_Client_readBrowseNameAttribute_async()
static UA_INLINE UA_StatusCode UA_Client_readBrowseNameAttribute_async (UA_Client * client, const UA_NodeId nodeId, UA_ClientAsyncReadBrowseNameAttributeCallback callback, void * userdata, UA_UInt32 * reqId) static
Definition at line 121 of file client_highlevel_async.h.
References __UA_Client_readAttribute_async(), UA_ATTRIBUTEID_BROWSENAME, and UA_TYPES.
UA_Client_readContainsNoLoopsAttribute_async()
static UA_INLINE UA_StatusCode UA_Client_readContainsNoLoopsAttribute_async (UA_Client * client, const UA_NodeId nodeId, UA_ClientAsyncReadContainsNoLoopsAttributeCallback callback, void * userdata, UA_UInt32 * reqId) static
Definition at line 225 of file client_highlevel_async.h.
References __UA_Client_readAttribute_async(), UA_ATTRIBUTEID_CONTAINSNOLOOPS, and UA_TYPES.
UA_Client_readDataTypeAttribute_async()
static UA_INLINE UA_StatusCode UA_Client_readDataTypeAttribute_async (UA_Client * client, const UA_NodeId nodeId, UA_ClientAsyncReadDataTypeAttributeCallback callback, void * userdata, UA_UInt32 * reqId) static
Definition at line 69 of file client_highlevel_async.h.
References __UA_Client_readAttribute_async(), UA_ATTRIBUTEID_DATATYPE, and UA_TYPES.
UA_Client_readDescriptionAttribute_async()
static UA_INLINE UA_StatusCode UA_Client_readDescriptionAttribute_async (UA_Client * client, const UA_NodeId nodeId, UA_ClientAsyncReadDescriptionAttributeCallback callback, void * userdata, UA_UInt32 * reqId) static
Definition at line 147 of file client_highlevel_async.h.
References __UA_Client_readAttribute_async(), UA_ATTRIBUTEID_DESCRIPTION, and UA_TYPES.
UA_Client_readDisplayNameAttribute_async()
static UA_INLINE UA_StatusCode UA_Client_readDisplayNameAttribute_async (UA_Client * client, const UA_NodeId nodeId, UA_ClientAsyncReadDisplayNameAttributeCallback callback, void * userdata, UA_UInt32 * reqId) static
Definition at line 134 of file client_highlevel_async.h.
References __UA_Client_readAttribute_async(), UA_ATTRIBUTEID_DISPLAYNAME, and UA_TYPES.
UA_Client_readEventNotifierAttribute_async()
static UA_INLINE UA_StatusCode UA_Client_readEventNotifierAttribute_async (UA_Client * client, const UA_NodeId nodeId, UA_ClientAsyncReadEventNotifierAttributeCallback callback, void * userdata, UA_UInt32 * reqId) static
Definition at line 238 of file client_highlevel_async.h.
References __UA_Client_readAttribute_async(), UA_ATTRIBUTEID_EVENTNOTIFIER, and UA_TYPES.
UA_Client_readExecutableAttribute_async()
static UA_INLINE UA_StatusCode UA_Client_readExecutableAttribute_async (UA_Client * client, const UA_NodeId nodeId, UA_ClientAsyncReadExecutableAttributeCallback callback, void * userdata, UA_UInt32 * reqId) static
Definition at line 315 of file client_highlevel_async.h.
References __UA_Client_readAttribute_async(), UA_ATTRIBUTEID_EXECUTABLE, and UA_TYPES.
UA_Client_readHistorizingAttribute_async()
static UA_INLINE UA_StatusCode UA_Client_readHistorizingAttribute_async (UA_Client * client, const UA_NodeId nodeId, UA_ClientAsyncReadHistorizingAttributeCallback callback, void * userdata, UA_UInt32 * reqId) static
Definition at line 302 of file client_highlevel_async.h.
References __UA_Client_readAttribute_async(), UA_ATTRIBUTEID_HISTORIZING, and UA_TYPES.
UA_Client_readInverseNameAttribute_async()
static UA_INLINE UA_StatusCode UA_Client_readInverseNameAttribute_async (UA_Client * client, const UA_NodeId nodeId, UA_ClientAsyncReadInverseNameAttributeCallback callback, void * userdata, UA_UInt32 * reqId) static
Definition at line 212 of file client_highlevel_async.h.
References __UA_Client_readAttribute_async(), UA_ATTRIBUTEID_INVERSENAME, and UA_TYPES.
UA_Client_readIsAbstractAttribute_async()
static UA_INLINE UA_StatusCode UA_Client_readIsAbstractAttribute_async (UA_Client * client, const UA_NodeId nodeId, UA_ClientAsyncReadIsAbstractAttributeCallback callback, void * userdata, UA_UInt32 * reqId) static
Definition at line 186 of file client_highlevel_async.h.
References __UA_Client_readAttribute_async(), UA_ATTRIBUTEID_ISABSTRACT, and UA_TYPES.
UA_Client_readMinimumSamplingIntervalAttribute_async()
static UA_INLINE UA_StatusCode UA_Client_readMinimumSamplingIntervalAttribute_async (UA_Client * client, const UA_NodeId nodeId, UA_ClientAsyncReadMinimumSamplingIntervalAttributeCallback callback, void * userdata, UA_UInt32 * reqId) static
Definition at line 288 of file client_highlevel_async.h.
References __UA_Client_readAttribute_async(), UA_ATTRIBUTEID_MINIMUMSAMPLINGINTERVAL, and UA_TYPES.
UA_Client_readNodeClassAttribute_async()
static UA_INLINE UA_StatusCode UA_Client_readNodeClassAttribute_async (UA_Client * client, const UA_NodeId nodeId, UA_ClientAsyncReadNodeClassAttributeCallback callback, void * userdata, UA_UInt32 * reqId) static
Definition at line 108 of file client_highlevel_async.h.
References __UA_Client_readAttribute_async(), UA_ATTRIBUTEID_NODECLASS, and UA_TYPES.
UA_Client_readNodeIdAttribute_async()
static UA_INLINE UA_StatusCode UA_Client_readNodeIdAttribute_async (UA_Client * client, const UA_NodeId nodeId, UA_ClientAsyncReadNodeIdAttributeCallback callback, void * userdata, UA_UInt32 * reqId) static
Definition at line 96 of file client_highlevel_async.h.
References __UA_Client_readAttribute_async(), UA_ATTRIBUTEID_NODEID, and UA_TYPES.
UA_Client_readSymmetricAttribute_async()
static UA_INLINE UA_StatusCode UA_Client_readSymmetricAttribute_async (UA_Client * client, const UA_NodeId nodeId, UA_ClientAsyncReadSymmetricAttributeCallback callback, void * userdata, UA_UInt32 * reqId) static
Definition at line 199 of file client_highlevel_async.h.
References __UA_Client_readAttribute_async(), UA_ATTRIBUTEID_SYMMETRIC, and UA_TYPES.
UA_Client_readUserAccessLevelAttribute_async()
static UA_INLINE UA_StatusCode UA_Client_readUserAccessLevelAttribute_async (UA_Client * client, const UA_NodeId nodeId, UA_ClientAsyncReadUserAccessLevelAttributeCallback callback, void * userdata, UA_UInt32 * reqId) static
Definition at line 277 of file client_highlevel_async.h.
References __UA_Client_readAttribute_async(), UA_ATTRIBUTEID_USERACCESSLEVEL, and UA_TYPES.
UA_Client_readUserExecutableAttribute_async()
static UA_INLINE UA_StatusCode UA_Client_readUserExecutableAttribute_async (UA_Client * client, const UA_NodeId nodeId, UA_ClientAsyncReadUserExecutableAttributeCallback callback, void * userdata, UA_UInt32 * reqId) static
Definition at line 328 of file client_highlevel_async.h.
References __UA_Client_readAttribute_async(), __UA_Client_writeAttribute_async(), UA_ATTRIBUTEID_USEREXECUTABLE, and UA_TYPES.
UA_Client_readUserWriteMaskAttribute_async()
static UA_INLINE UA_StatusCode UA_Client_readUserWriteMaskAttribute_async (UA_Client * client, const UA_NodeId nodeId, UA_ClientAsyncReadUserWriteMaskAttributeCallback callback, void * userdata, UA_UInt32 * reqId) static
Definition at line 173 of file client_highlevel_async.h.
References __UA_Client_readAttribute_async(), UA_ATTRIBUTEID_USERWRITEMASK, and UA_TYPES.
UA_Client_readValueAttribute_async()
static UA_INLINE UA_StatusCode UA_Client_readValueAttribute_async (UA_Client * client, const UA_NodeId nodeId, UA_ClientAsyncReadValueAttributeCallback callback, void * userdata, UA_UInt32 * reqId) static
Definition at line 83 of file client_highlevel_async.h.
References __UA_Client_readAttribute_async(), UA_ATTRIBUTEID_VALUE, and UA_TYPES.
UA_Client_readValueRankAttribute_async()
static UA_INLINE UA_StatusCode UA_Client_readValueRankAttribute_async (UA_Client * client, const UA_NodeId nodeId, UA_ClientAsyncReadValueRankAttributeCallback callback, void * userdata, UA_UInt32 * reqId) static
Definition at line 251 of file client_highlevel_async.h.
References __UA_Client_readAttribute_async(), UA_ATTRIBUTEID_VALUERANK, and UA_TYPES.
UA_Client_readWriteMaskAttribute_async()
static UA_INLINE UA_StatusCode UA_Client_readWriteMaskAttribute_async (UA_Client * client, const UA_NodeId nodeId, UA_ClientAsyncReadWriteMaskAttributeCallback callback, void * userdata, UA_UInt32 * reqId) static
Definition at line 160 of file client_highlevel_async.h.
References __UA_Client_readAttribute_async(), UA_ATTRIBUTEID_WRITEMASK, and UA_TYPES.
UA_Client_sendAsyncBrowseRequest()
static UA_INLINE UA_StatusCode UA_Client_sendAsyncBrowseRequest (UA_Client * client, UA_BrowseRequest * request, UA_ClientAsyncBrowseCallback browseCallback, void * userdata, UA_UInt32 * reqId) static
Definition at line 45 of file client_highlevel_async.h.
References __UA_Client_readAttribute_async(), UA_Client_sendAsyncRequest(), and UA_TYPES.
UA_Client_sendAsyncReadRequest()
static UA_INLINE UA_StatusCode UA_Client_sendAsyncReadRequest (UA_Client * client, UA_ReadRequest * request, UA_ClientAsyncReadCallback readCallback, void * userdata, UA_UInt32 * reqId) static
Definition at line 23 of file client_highlevel_async.h.
References UA_Client_sendAsyncRequest(), and UA_TYPES.
UA_Client_sendAsyncWriteRequest()
static UA_INLINE UA_StatusCode UA_Client_sendAsyncWriteRequest (UA_Client * client, UA_WriteRequest * request, UA_ClientAsyncWriteCallback writeCallback, void * userdata, UA_UInt32 * reqId) static
Definition at line 34 of file client_highlevel_async.h.
References UA_Client_sendAsyncRequest(), and UA_TYPES.
UA_Client_writeAccessLevelAttribute_async()
static UA_INLINE UA_StatusCode UA_Client_writeAccessLevelAttribute_async (UA_Client * client, const UA_NodeId nodeId, const UA_Byte * outAccessLevel, UA_ClientAsyncServiceCallback callback, void * userdata, UA_UInt32 * reqId) static
Definition at line 485 of file client_highlevel_async.h.
References __UA_Client_writeAttribute_async(), UA_ATTRIBUTEID_ACCESSLEVEL, and UA_TYPES.
UA_Client_writeBrowseNameAttribute_async()
static UA_INLINE UA_StatusCode UA_Client_writeBrowseNameAttribute_async (UA_Client * client, const UA_NodeId nodeId, const UA_QualifiedName * outBrowseName, UA_ClientAsyncServiceCallback callback, void * userdata, UA_UInt32 * reqId) static
Definition at line 377 of file client_highlevel_async.h.
References __UA_Client_writeAttribute_async(), UA_ATTRIBUTEID_BROWSENAME, and UA_TYPES.
UA_Client_writeContainsNoLoopsAttribute_async()
static UA_INLINE UA_StatusCode UA_Client_writeContainsNoLoopsAttribute_async (UA_Client * client, const UA_NodeId nodeId, const UA_Boolean * outContainsNoLoops, UA_ClientAsyncServiceCallback callback, void * userdata, UA_UInt32 * reqId) static
Definition at line 449 of file client_highlevel_async.h.
References __UA_Client_writeAttribute_async(), UA_ATTRIBUTEID_CONTAINSNOLOOPS, and UA_TYPES.
UA_Client_writeDataTypeAttribute_async()
static UA_INLINE UA_StatusCode UA_Client_writeDataTypeAttribute_async (UA_Client * client, const UA_NodeId nodeId, const UA_NodeId * outDataType, UA_ClientAsyncServiceCallback callback, void * userdata, UA_UInt32 * reqId) static
Definition at line 467 of file client_highlevel_async.h.
References __UA_Client_writeAttribute_async(), UA_ATTRIBUTEID_DATATYPE, and UA_TYPES.
UA_Client_writeDescriptionAttribute_async()
static UA_INLINE UA_StatusCode UA_Client_writeDescriptionAttribute_async (UA_Client * client, const UA_NodeId nodeId, const UA_LocalizedText * outDescription, UA_ClientAsyncServiceCallback callback, void * userdata, UA_UInt32 * reqId) static
Definition at line 395 of file client_highlevel_async.h.
References __UA_Client_writeAttribute_async(), UA_ATTRIBUTEID_DESCRIPTION, and UA_TYPES.
UA_Client_writeDisplayNameAttribute_async()
static UA_INLINE UA_StatusCode UA_Client_writeDisplayNameAttribute_async (UA_Client * client, const UA_NodeId nodeId, const UA_LocalizedText * outDisplayName, UA_ClientAsyncServiceCallback callback, void * userdata, UA_UInt32 * reqId) static
Definition at line 386 of file client_highlevel_async.h.
References __UA_Client_writeAttribute_async(), UA_ATTRIBUTEID_DISPLAYNAME, and UA_TYPES.
UA_Client_writeEventNotifierAttribute_async()
static UA_INLINE UA_StatusCode UA_Client_writeEventNotifierAttribute_async (UA_Client * client, const UA_NodeId nodeId, const UA_Byte * outEventNotifier, UA_ClientAsyncServiceCallback callback, void * userdata, UA_UInt32 * reqId) static
Definition at line 458 of file client_highlevel_async.h.
References __UA_Client_writeAttribute_async(), UA_ATTRIBUTEID_EVENTNOTIFIER, and UA_TYPES.
UA_Client_writeExecutableAttribute_async()
static UA_INLINE UA_StatusCode UA_Client_writeExecutableAttribute_async (UA_Client * client, const UA_NodeId nodeId, const UA_Boolean * outExecutable, UA_ClientAsyncServiceCallback callback, void * userdata, UA_UInt32 * reqId) static
Definition at line 522 of file client_highlevel_async.h.
References __UA_Client_writeAttribute_async(), UA_ATTRIBUTEID_EXECUTABLE, and UA_TYPES.
UA_Client_writeHistorizingAttribute_async()
static UA_INLINE UA_StatusCode UA_Client_writeHistorizingAttribute_async (UA_Client * client, const UA_NodeId nodeId, const UA_Boolean * outHistorizing, UA_ClientAsyncServiceCallback callback, void * userdata, UA_UInt32 * reqId) static
Definition at line 513 of file client_highlevel_async.h.
References __UA_Client_writeAttribute_async(), UA_ATTRIBUTEID_HISTORIZING, and UA_TYPES.
UA_Client_writeInverseNameAttribute_async()
static UA_INLINE UA_StatusCode UA_Client_writeInverseNameAttribute_async (UA_Client * client, const UA_NodeId nodeId, const UA_LocalizedText * outInverseName, UA_ClientAsyncServiceCallback callback, void * userdata, UA_UInt32 * reqId) static
Definition at line 440 of file client_highlevel_async.h.
References __UA_Client_writeAttribute_async(), UA_ATTRIBUTEID_INVERSENAME, and UA_TYPES.
UA_Client_writeIsAbstractAttribute_async()
static UA_INLINE UA_StatusCode UA_Client_writeIsAbstractAttribute_async (UA_Client * client, const UA_NodeId nodeId, const UA_Boolean * outIsAbstract, UA_ClientAsyncServiceCallback callback, void * userdata, UA_UInt32 * reqId) static
Definition at line 422 of file client_highlevel_async.h.
References __UA_Client_writeAttribute_async(), UA_ATTRIBUTEID_ISABSTRACT, and UA_TYPES.
UA_Client_writeMinimumSamplingIntervalAttribute_async()
static UA_INLINE UA_StatusCode UA_Client_writeMinimumSamplingIntervalAttribute_async (UA_Client * client, const UA_NodeId nodeId, const UA_Double * outMinimumSamplingInterval, UA_ClientAsyncServiceCallback callback, void * userdata, UA_UInt32 * reqId) static
Definition at line 503 of file client_highlevel_async.h.
References __UA_Client_writeAttribute_async(), UA_ATTRIBUTEID_MINIMUMSAMPLINGINTERVAL, and UA_TYPES.
UA_Client_writeNodeClassAttribute_async()
static UA_INLINE UA_StatusCode UA_Client_writeNodeClassAttribute_async (UA_Client * client, const UA_NodeId nodeId, const UA_NodeClass * outNodeClass, UA_ClientAsyncServiceCallback callback, void * userdata, UA_UInt32 * reqId) static
Definition at line 368 of file client_highlevel_async.h.
References __UA_Client_writeAttribute_async(), UA_ATTRIBUTEID_NODECLASS, and UA_TYPES.
UA_Client_writeNodeIdAttribute_async()
static UA_INLINE UA_StatusCode UA_Client_writeNodeIdAttribute_async (UA_Client * client, const UA_NodeId nodeId, const UA_NodeId * outNodeId, UA_ClientAsyncServiceCallback callback, void * userdata, UA_UInt32 * reqId) static
Definition at line 359 of file client_highlevel_async.h.
References __UA_Client_writeAttribute_async(), UA_ATTRIBUTEID_NODEID, and UA_TYPES.
UA_Client_writeSymmetricAttribute_async()
static UA_INLINE UA_StatusCode UA_Client_writeSymmetricAttribute_async (UA_Client * client, const UA_NodeId nodeId, const UA_Boolean * outSymmetric, UA_ClientAsyncServiceCallback callback, void * userdata, UA_UInt32 * reqId) static
Definition at line 431 of file client_highlevel_async.h.
References __UA_Client_writeAttribute_async(), UA_ATTRIBUTEID_SYMMETRIC, and UA_TYPES.
UA_Client_writeUserAccessLevelAttribute_async()
static UA_INLINE UA_StatusCode UA_Client_writeUserAccessLevelAttribute_async (UA_Client * client, const UA_NodeId nodeId, const UA_Byte * outUserAccessLevel, UA_ClientAsyncServiceCallback callback, void * userdata, UA_UInt32 * reqId) static
Definition at line 494 of file client_highlevel_async.h.
References __UA_Client_writeAttribute_async(), UA_ATTRIBUTEID_USERACCESSLEVEL, and UA_TYPES.
UA_Client_writeUserExecutableAttribute_async()
static UA_INLINE UA_StatusCode UA_Client_writeUserExecutableAttribute_async (UA_Client * client, const UA_NodeId nodeId, const UA_Boolean * outUserExecutable, UA_ClientAsyncServiceCallback callback, void * userdata, UA_UInt32 * reqId) static
Definition at line 531 of file client_highlevel_async.h.
References __UA_Client_call_async(), __UA_Client_writeAttribute_async(), UA_ATTRIBUTEID_USEREXECUTABLE, and UA_TYPES.
UA_Client_writeUserWriteMaskAttribute_async()
static UA_INLINE UA_StatusCode UA_Client_writeUserWriteMaskAttribute_async (UA_Client * client, const UA_NodeId nodeId, const UA_UInt32 * outUserWriteMask, UA_ClientAsyncServiceCallback callback, void * userdata, UA_UInt32 * reqId) static
Definition at line 413 of file client_highlevel_async.h.
References __UA_Client_writeAttribute_async(), UA_ATTRIBUTEID_USERWRITEMASK, and UA_TYPES.
UA_Client_writeValueAttribute_async()
static UA_INLINE UA_StatusCode UA_Client_writeValueAttribute_async (UA_Client * client, const UA_NodeId nodeId, const UA_Variant * newValue, UA_ClientAsyncWriteCallback callback, void * userdata, UA_UInt32 * reqId) static
Definition at line 348 of file client_highlevel_async.h.
References __UA_Client_writeAttribute_async(), UA_ATTRIBUTEID_VALUE, and UA_TYPES.
UA_Client_writeValueRankAttribute_async()
static UA_INLINE UA_StatusCode UA_Client_writeValueRankAttribute_async (UA_Client * client, const UA_NodeId nodeId, const UA_Int32 * outValueRank, UA_ClientAsyncServiceCallback callback, void * userdata, UA_UInt32 * reqId) static
Definition at line 476 of file client_highlevel_async.h.
References __UA_Client_writeAttribute_async(), UA_ATTRIBUTEID_VALUERANK, and UA_TYPES.
UA_Client_writeWriteMaskAttribute_async()
static UA_INLINE UA_StatusCode UA_Client_writeWriteMaskAttribute_async (UA_Client * client, const UA_NodeId nodeId, const UA_UInt32 * outWriteMask, UA_ClientAsyncServiceCallback callback, void * userdata, UA_UInt32 * reqId) static
Definition at line 404 of file client_highlevel_async.h.
References __UA_Client_writeAttribute_async(), UA_ATTRIBUTEID_WRITEMASK, and UA_TYPES.
Variable Documentation
UA_ClientAsyncReadCallback
_UA_BEGIN_DECLS typedef void(* UA_ClientAsyncReadCallback) (UA_Client *client, void *userdata, UA_UInt32 requestId, UA_ReadResponse *rr)
Raw Services ^^^^^^^^^^^^
Definition at line 20 of file client_highlevel_async.h.