Project Template: Opc.Ua.AxisInformation Class Reference
Opc.Ua.AxisInformation Class Reference
Public Member Functions
AxisInformation ()
The default constructor.
virtual void Encode (IEncoder encoder)
virtual void Decode (IDecoder decoder)
virtual bool IsEqual (IEncodeable encodeable)
virtual object Clone ()
new object MemberwiseClone ()
Properties
EUInformation EngineeringUnits [get, set]
Range EURange [get, set]
LocalizedText Title [get, set]
AxisScaleEnumeration AxisScaleType [get, set]
DoubleCollection AxisSteps [get, set]
virtual ExpandedNodeId TypeId [get]
virtual ExpandedNodeId BinaryEncodingId [get]
virtual ExpandedNodeId XmlEncodingId [get]
Detailed Description
<exclude>
Definition at line 66730 of file Opc.Ua.DataTypes.cs.
Constructor & Destructor Documentation
AxisInformation()
Opc.Ua.AxisInformation.AxisInformation () inline
The default constructor.
Definition at line 66736 of file Opc.Ua.DataTypes.cs.
Member Function Documentation
Clone()
virtual object Opc.Ua.AxisInformation.Clone () inline virtual
Definition at line 66920 of file Opc.Ua.DataTypes.cs.
Decode()
virtual void Opc.Ua.AxisInformation.Decode (IDecoder decoder) inline virtual
Definition at line 66881 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
Encode()
virtual void Opc.Ua.AxisInformation.Encode (IEncoder encoder) inline virtual
Definition at line 66867 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
IsEqual()
virtual bool Opc.Ua.AxisInformation.IsEqual (IEncodeable encodeable) inline virtual
Definition at line 66895 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Object.
MemberwiseClone()
new object Opc.Ua.AxisInformation.MemberwiseClone () inline
Definition at line 66927 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Range.Clone(), Opc.Ua.EUInformation.Clone(), Opc.Ua.AxisInformation.MemberwiseClone(), and Opc.Ua.Namespaces.OpcUaXsd.
Referenced by Opc.Ua.AxisInformation.MemberwiseClone().
Property Documentation
AxisScaleType
AxisScaleEnumeration Opc.Ua.AxisInformation.AxisScaleType get set
Definition at line 66819 of file Opc.Ua.DataTypes.cs.
AxisSteps
DoubleCollection Opc.Ua.AxisInformation.AxisSteps get set
Definition at line 66829 of file Opc.Ua.DataTypes.cs.
BinaryEncodingId
virtual ExpandedNodeId Opc.Ua.AxisInformation.BinaryEncodingId get
Definition at line 66856 of file Opc.Ua.DataTypes.cs.
EngineeringUnits
EUInformation Opc.Ua.AxisInformation.EngineeringUnits get set
Definition at line 66769 of file Opc.Ua.DataTypes.cs.
EURange
Range Opc.Ua.AxisInformation.EURange get set
Definition at line 66791 of file Opc.Ua.DataTypes.cs.
Title
LocalizedText Opc.Ua.AxisInformation.Title get set
Definition at line 66811 of file Opc.Ua.DataTypes.cs.
TypeId
virtual ExpandedNodeId Opc.Ua.AxisInformation.TypeId get
Definition at line 66850 of file Opc.Ua.DataTypes.cs.
XmlEncodingId
virtual ExpandedNodeId Opc.Ua.AxisInformation.XmlEncodingId get
Definition at line 66862 of file Opc.Ua.DataTypes.cs.
The documentation for this class was generated from the following file:
Opc.Ua.DataTypes.cs