Project Template: nodeset_compiler.nodeset_compiler Namespace Reference
nodeset_compiler.nodeset_compiler Namespace Reference
Functions
def getTypesArray (nsIdx)
Variables
parser = argparse.ArgumentParser(formatter_class=argparse.RawDescriptionHelpFormatter)
metavar
type
dest
action
default
help
const
nargs
choices
args = parser.parse_args()
logger = logging.getLogger(__name__)
int verbosity = 0
level
ns = NodeSet()
int nsCount = 0
loadedFiles = list()
xmlfile
True
typesArray
line = line.replace(" ", "")
id = line.replace("\n", "")
filename
Function Documentation
getTypesArray()
def nodeset_compiler.nodeset_compiler.getTypesArray (nsIdx)
Definition at line 117 of file nodeset_compiler.py.
Variable Documentation
action
nodeset_compiler.nodeset_compiler.action
Definition at line 35 of file nodeset_compiler.py.
args
nodeset_compiler.nodeset_compiler.args = parser.parse_args()
Definition at line 91 of file nodeset_compiler.py.
choices
nodeset_compiler.nodeset_compiler.choices
Definition at line 88 of file nodeset_compiler.py.
const
nodeset_compiler.nodeset_compiler.const
Definition at line 86 of file nodeset_compiler.py.
default
nodeset_compiler.nodeset_compiler.default
Definition at line 36 of file nodeset_compiler.py.
dest
nodeset_compiler.nodeset_compiler.dest
Definition at line 34 of file nodeset_compiler.py.
filename
nodeset_compiler.nodeset_compiler.filename
Definition at line 199 of file nodeset_compiler.py.
help
nodeset_compiler.nodeset_compiler.help
Definition at line 37 of file nodeset_compiler.py.
id
nodeset_compiler.nodeset_compiler.id = line.replace("\n", "")
Definition at line 151 of file nodeset_compiler.py.
Referenced by UA_EXPANDEDNODEID_BYTESTRING(), UA_EXPANDEDNODEID_BYTESTRING_ALLOC(), UA_EXPANDEDNODEID_NUMERIC(), UA_EXPANDEDNODEID_STRING(), UA_EXPANDEDNODEID_STRING_ALLOC(), UA_EXPANDEDNODEID_STRING_GUID(), UA_NODEID_BYTESTRING(), UA_NODEID_BYTESTRING_ALLOC(), UA_NODEID_GUID(), UA_NODEID_NUMERIC(), UA_NODEID_STRING(), and UA_NODEID_STRING_ALLOC().
level
nodeset_compiler.nodeset_compiler.level
Definition at line 100 of file nodeset_compiler.py.
line
nodeset_compiler.nodeset_compiler.line = line.replace(" ", "")
Definition at line 150 of file nodeset_compiler.py.
loadedFiles
nodeset_compiler.nodeset_compiler.loadedFiles = list()
Definition at line 114 of file nodeset_compiler.py.
logger
nodeset_compiler.nodeset_compiler.logger = logging.getLogger(__name__)
Definition at line 94 of file nodeset_compiler.py.
metavar
nodeset_compiler.nodeset_compiler.metavar
Definition at line 32 of file nodeset_compiler.py.
nargs
nodeset_compiler.nodeset_compiler.nargs
Definition at line 87 of file nodeset_compiler.py.
ns
nodeset_compiler.nodeset_compiler.ns = NodeSet()
Definition at line 112 of file nodeset_compiler.py.
Referenced by namespace0_generated().
nsCount
int nodeset_compiler.nodeset_compiler.nsCount = 0
Definition at line 113 of file nodeset_compiler.py.
parser
nodeset_compiler.nodeset_compiler.parser = argparse.ArgumentParser(formatter_class=argparse.RawDescriptionHelpFormatter)
Definition at line 30 of file nodeset_compiler.py.
True
nodeset_compiler.nodeset_compiler.True
Definition at line 129 of file nodeset_compiler.py.
type
nodeset_compiler.nodeset_compiler.type
Definition at line 33 of file nodeset_compiler.py.
typesArray
nodeset_compiler.nodeset_compiler.typesArray
Definition at line 129 of file nodeset_compiler.py.
verbosity
nodeset_compiler.nodeset_compiler.verbosity = 0
Definition at line 96 of file nodeset_compiler.py.
xmlfile
nodeset_compiler.nodeset_compiler.xmlfile
Definition at line 129 of file nodeset_compiler.py.