Project Template: Opc.Ua.ProgramDiagnosticDataType Class Reference
Opc.Ua.ProgramDiagnosticDataType Class Reference
Public Member Functions
ProgramDiagnosticDataType ()
The default constructor.
virtual void Encode (IEncoder encoder)
virtual void Decode (IDecoder decoder)
virtual bool IsEqual (IEncodeable encodeable)
virtual object Clone ()
new object MemberwiseClone ()
Properties
NodeId CreateSessionId [get, set]
string CreateClientName [get, set]
DateTime InvocationCreationTime [get, set]
DateTime LastTransitionTime [get, set]
string LastMethodCall [get, set]
NodeId LastMethodSessionId [get, set]
ArgumentCollection LastMethodInputArguments [get, set]
ArgumentCollection LastMethodOutputArguments [get, set]
DateTime LastMethodCallTime [get, set]
StatusResult LastMethodReturnStatus [get, set]
virtual ExpandedNodeId TypeId [get]
virtual ExpandedNodeId BinaryEncodingId [get]
virtual ExpandedNodeId XmlEncodingId [get]
Detailed Description
<exclude>
Definition at line 67106 of file Opc.Ua.DataTypes.cs.
Constructor & Destructor Documentation
ProgramDiagnosticDataType()
Opc.Ua.ProgramDiagnosticDataType.ProgramDiagnosticDataType () inline
The default constructor.
Definition at line 67112 of file Opc.Ua.DataTypes.cs.
Member Function Documentation
Clone()
virtual object Opc.Ua.ProgramDiagnosticDataType.Clone () inline virtual
Definition at line 67356 of file Opc.Ua.DataTypes.cs.
Decode()
virtual void Opc.Ua.ProgramDiagnosticDataType.Decode (IDecoder decoder) inline virtual
Definition at line 67307 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
Encode()
virtual void Opc.Ua.ProgramDiagnosticDataType.Encode (IEncoder encoder) inline virtual
Definition at line 67288 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
IsEqual()
virtual bool Opc.Ua.ProgramDiagnosticDataType.IsEqual (IEncodeable encodeable) inline virtual
Definition at line 67326 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Object.
MemberwiseClone()
new object Opc.Ua.ProgramDiagnosticDataType.MemberwiseClone () inline
Definition at line 67363 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.ArgumentCollection.Clone(), Opc.Ua.StatusResult.Clone(), Opc.Ua.ProgramDiagnosticDataType.MemberwiseClone(), Opc.Ua.NodeId, and Opc.Ua.Namespaces.OpcUaXsd.
Referenced by Opc.Ua.ProgramDiagnosticDataType.MemberwiseClone().
Property Documentation
BinaryEncodingId
virtual ExpandedNodeId Opc.Ua.ProgramDiagnosticDataType.BinaryEncodingId get
Definition at line 67277 of file Opc.Ua.DataTypes.cs.
CreateClientName
string Opc.Ua.ProgramDiagnosticDataType.CreateClientName get set
Definition at line 67156 of file Opc.Ua.DataTypes.cs.
CreateSessionId
NodeId Opc.Ua.ProgramDiagnosticDataType.CreateSessionId get set
Definition at line 67148 of file Opc.Ua.DataTypes.cs.
InvocationCreationTime
DateTime Opc.Ua.ProgramDiagnosticDataType.InvocationCreationTime get set
Definition at line 67164 of file Opc.Ua.DataTypes.cs.
LastMethodCall
string Opc.Ua.ProgramDiagnosticDataType.LastMethodCall get set
Definition at line 67180 of file Opc.Ua.DataTypes.cs.
LastMethodCallTime
DateTime Opc.Ua.ProgramDiagnosticDataType.LastMethodCallTime get set
Definition at line 67240 of file Opc.Ua.DataTypes.cs.
LastMethodInputArguments
ArgumentCollection Opc.Ua.ProgramDiagnosticDataType.LastMethodInputArguments get set
Definition at line 67198 of file Opc.Ua.DataTypes.cs.
LastMethodOutputArguments
ArgumentCollection Opc.Ua.ProgramDiagnosticDataType.LastMethodOutputArguments get set
Definition at line 67220 of file Opc.Ua.DataTypes.cs.
LastMethodReturnStatus
StatusResult Opc.Ua.ProgramDiagnosticDataType.LastMethodReturnStatus get set
Definition at line 67250 of file Opc.Ua.DataTypes.cs.
LastMethodSessionId
NodeId Opc.Ua.ProgramDiagnosticDataType.LastMethodSessionId get set
Definition at line 67188 of file Opc.Ua.DataTypes.cs.
LastTransitionTime
DateTime Opc.Ua.ProgramDiagnosticDataType.LastTransitionTime get set
Definition at line 67172 of file Opc.Ua.DataTypes.cs.
TypeId
virtual ExpandedNodeId Opc.Ua.ProgramDiagnosticDataType.TypeId get
Definition at line 67271 of file Opc.Ua.DataTypes.cs.
XmlEncodingId
virtual ExpandedNodeId Opc.Ua.ProgramDiagnosticDataType.XmlEncodingId get
Definition at line 67283 of file Opc.Ua.DataTypes.cs.
The documentation for this class was generated from the following file:
Opc.Ua.DataTypes.cs