Project Template: Opc.Ua.RepublishResponse Class Reference
Opc.Ua.RepublishResponse Class Reference
Public Member Functions
RepublishResponse ()
The default constructor.
virtual void Encode (IEncoder encoder)
virtual void Decode (IDecoder decoder)
virtual bool IsEqual (IEncodeable encodeable)
virtual object Clone ()
new object MemberwiseClone ()
Properties
ResponseHeader ResponseHeader [get, set]
NotificationMessage NotificationMessage [get, set]
virtual ExpandedNodeId TypeId [get]
virtual ExpandedNodeId BinaryEncodingId [get]
virtual ExpandedNodeId XmlEncodingId [get]
Detailed Description
<exclude>
Definition at line 3896 of file Opc.Ua.Messages.cs.
Constructor & Destructor Documentation
RepublishResponse()
Opc.Ua.RepublishResponse.RepublishResponse () inline
The default constructor.
Definition at line 60043 of file Opc.Ua.DataTypes.cs.
Member Function Documentation
Clone()
virtual object Opc.Ua.RepublishResponse.Clone () inline virtual
Definition at line 60177 of file Opc.Ua.DataTypes.cs.
Decode()
virtual void Opc.Ua.RepublishResponse.Decode (IDecoder decoder) inline virtual
Definition at line 60144 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
Encode()
virtual void Opc.Ua.RepublishResponse.Encode (IEncoder encoder) inline virtual
Definition at line 60133 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
IsEqual()
virtual bool Opc.Ua.RepublishResponse.IsEqual (IEncodeable encodeable) inline virtual
Definition at line 60155 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Object.
MemberwiseClone()
new object Opc.Ua.RepublishResponse.MemberwiseClone () inline
Definition at line 60184 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.ResponseHeader.Clone(), Opc.Ua.NotificationMessage.Clone(), Opc.Ua.RepublishResponse.MemberwiseClone(), and Opc.Ua.Namespaces.OpcUaXsd.
Referenced by Opc.Ua.RepublishResponse.MemberwiseClone().
Property Documentation
BinaryEncodingId
virtual ExpandedNodeId Opc.Ua.RepublishResponse.BinaryEncodingId get
Definition at line 60122 of file Opc.Ua.DataTypes.cs.
NotificationMessage
NotificationMessage Opc.Ua.RepublishResponse.NotificationMessage get set
Definition at line 60095 of file Opc.Ua.DataTypes.cs.
Referenced by Opc.Ua.SessionEndpoint.EndPublish(), Opc.Ua.SessionClient.EndPublish(), and Opc.Ua.SessionClient.EndRepublish().
ResponseHeader
ResponseHeader Opc.Ua.RepublishResponse.ResponseHeader get set
Definition at line 60073 of file Opc.Ua.DataTypes.cs.
Referenced by Opc.Ua.RepublishMessage.CreateResponse(), Opc.Ua.SessionEndpoint.EndPublish(), Opc.Ua.SessionClient.EndPublish(), Opc.Ua.SessionClient.EndRepublish(), and Opc.Ua.RepublishResponseMessage.RepublishResponseMessage().
TypeId
virtual ExpandedNodeId Opc.Ua.RepublishResponse.TypeId get
Definition at line 60116 of file Opc.Ua.DataTypes.cs.
XmlEncodingId
virtual ExpandedNodeId Opc.Ua.RepublishResponse.XmlEncodingId get
Definition at line 60128 of file Opc.Ua.DataTypes.cs.
The documentation for this class was generated from the following files:
Opc.Ua.Messages.cs
Opc.Ua.DataTypes.cs