Project Template: Opc.Ua.ApplicationDescription Class Reference
Opc.Ua.ApplicationDescription Class Reference
Public Member Functions
ApplicationDescription ()
The default constructor.
virtual void Encode (IEncoder encoder)
virtual void Decode (IDecoder decoder)
virtual bool IsEqual (IEncodeable encodeable)
virtual object Clone ()
new object MemberwiseClone ()
Properties
string ApplicationUri [get, set]
string ProductUri [get, set]
LocalizedText ApplicationName [get, set]
ApplicationType ApplicationType [get, set]
string GatewayServerUri [get, set]
string DiscoveryProfileUri [get, set]
StringCollection DiscoveryUrls [get, set]
virtual ExpandedNodeId TypeId [get]
virtual ExpandedNodeId BinaryEncodingId [get]
virtual ExpandedNodeId XmlEncodingId [get]
Detailed Description
<exclude>
Definition at line 23117 of file Opc.Ua.DataTypes.cs.
Constructor & Destructor Documentation
ApplicationDescription()
Opc.Ua.ApplicationDescription.ApplicationDescription () inline
The default constructor.
Definition at line 23123 of file Opc.Ua.DataTypes.cs.
Member Function Documentation
Clone()
virtual object Opc.Ua.ApplicationDescription.Clone () inline virtual
Definition at line 23303 of file Opc.Ua.DataTypes.cs.
Referenced by Opc.Ua.EndpointDescription.MemberwiseClone(), Opc.Ua.CreateSessionRequest.MemberwiseClone(), and Opc.Ua.SessionDiagnosticsDataType.MemberwiseClone().
Decode()
virtual void Opc.Ua.ApplicationDescription.Decode (IDecoder decoder) inline virtual
Definition at line 23260 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
Encode()
virtual void Opc.Ua.ApplicationDescription.Encode (IEncoder encoder) inline virtual
Definition at line 23244 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
IsEqual()
virtual bool Opc.Ua.ApplicationDescription.IsEqual (IEncodeable encodeable) inline virtual
Definition at line 23276 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Object.
MemberwiseClone()
new object Opc.Ua.ApplicationDescription.MemberwiseClone () inline
Definition at line 23310 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.ApplicationDescription.MemberwiseClone(), and Opc.Ua.Namespaces.OpcUaXsd.
Referenced by Opc.Ua.ApplicationDescription.MemberwiseClone().
Property Documentation
ApplicationName
LocalizedText Opc.Ua.ApplicationDescription.ApplicationName get set
Definition at line 23172 of file Opc.Ua.DataTypes.cs.
ApplicationType
ApplicationType Opc.Ua.ApplicationDescription.ApplicationType get set
Definition at line 23180 of file Opc.Ua.DataTypes.cs.
ApplicationUri
string Opc.Ua.ApplicationDescription.ApplicationUri get set
Definition at line 23156 of file Opc.Ua.DataTypes.cs.
BinaryEncodingId
virtual ExpandedNodeId Opc.Ua.ApplicationDescription.BinaryEncodingId get
Definition at line 23233 of file Opc.Ua.DataTypes.cs.
DiscoveryProfileUri
string Opc.Ua.ApplicationDescription.DiscoveryProfileUri get set
Definition at line 23196 of file Opc.Ua.DataTypes.cs.
DiscoveryUrls
StringCollection Opc.Ua.ApplicationDescription.DiscoveryUrls get set
Definition at line 23206 of file Opc.Ua.DataTypes.cs.
GatewayServerUri
string Opc.Ua.ApplicationDescription.GatewayServerUri get set
Definition at line 23188 of file Opc.Ua.DataTypes.cs.
ProductUri
string Opc.Ua.ApplicationDescription.ProductUri get set
Definition at line 23164 of file Opc.Ua.DataTypes.cs.
TypeId
virtual ExpandedNodeId Opc.Ua.ApplicationDescription.TypeId get
Definition at line 23227 of file Opc.Ua.DataTypes.cs.
XmlEncodingId
virtual ExpandedNodeId Opc.Ua.ApplicationDescription.XmlEncodingId get
Definition at line 23239 of file Opc.Ua.DataTypes.cs.
The documentation for this class was generated from the following file:
Opc.Ua.DataTypes.cs