Information Modeller: Information_Model::NamedElement Class Reference
Information_Model::NamedElement Class Reference
This is the base class for all of the other modelling classes.
#include <NamedElement.hpp>
Public Member Functions
const std::string getElementName ()
const std::string getElementDescription ()
const std::string getElementRefId ()
virtual ~NamedElement ()=default
Protected Member Functions
NamedElement (const std::string REF_ID, const std::string NAME, const std::string DESC)
Detailed Description
This is the base class for all of the other modelling classes.
Attention
This class should be instantiated by its children only!
Author
Dovydas Girdvainis
Date
18.07.2019
Definition at line 18 of file NamedElement.hpp.
Constructor & Destructor Documentation
NamedElement()
NamedElement::NamedElement (const std::string REF_ID, const std::string NAME, const std::string DESC) protected
Definition at line 6 of file NamedElementImpl.cpp.
~NamedElement()
virtual Information_Model::NamedElement::~NamedElement () virtual default
Member Function Documentation
getElementDescription()
const string NamedElement::getElementDescription ()
Definition at line 12 of file NamedElementImpl.cpp.
Referenced by printDevice(), and printElement().
getElementName()
const string NamedElement::getElementName ()
Definition at line 14 of file NamedElementImpl.cpp.
Referenced by printDevice(), and printElement().
getElementRefId()
const string NamedElement::getElementRefId ()
Definition at line 16 of file NamedElementImpl.cpp.
Referenced by Model_Factory::DeviceBuilder::addDeviceElement(), Model_Factory::DeviceElementGroupImpl::generate_Reference_ID(), printDevice(), and printElement().
The documentation for this class was generated from the following files:
NamedElement.hpp
NamedElementImpl.cpp