Project Template: Opc.Ua.ReaderGroupDataType Class Reference
Opc.Ua.ReaderGroupDataType Class Reference
Public Member Functions
ReaderGroupDataType ()
The default constructor.
override void Encode (IEncoder encoder)
override void Decode (IDecoder decoder)
override bool IsEqual (IEncodeable encodeable)
override object Clone ()
new object MemberwiseClone ()
Public Member Functions inherited from Opc.Ua.PubSubGroupDataType
PubSubGroupDataType ()
The default constructor.
new object MemberwiseClone ()
Properties
ExtensionObject TransportSettings [get, set]
ExtensionObject MessageSettings [get, set]
DataSetReaderDataTypeCollection DataSetReaders [get, set]
override ExpandedNodeId TypeId [get]
override ExpandedNodeId BinaryEncodingId [get]
override ExpandedNodeId XmlEncodingId [get]
Properties inherited from Opc.Ua.PubSubGroupDataType
string Name [get, set]
bool Enabled [get, set]
MessageSecurityMode SecurityMode [get, set]
string SecurityGroupId [get, set]
EndpointDescriptionCollection SecurityKeyServices [get, set]
uint MaxNetworkMessageSize [get, set]
KeyValuePairCollection GroupProperties [get, set]
virtual ExpandedNodeId TypeId [get]
virtual ExpandedNodeId BinaryEncodingId [get]
virtual ExpandedNodeId XmlEncodingId [get]
Detailed Description
<exclude>
Definition at line 10712 of file Opc.Ua.DataTypes.cs.
Constructor & Destructor Documentation
ReaderGroupDataType()
Opc.Ua.ReaderGroupDataType.ReaderGroupDataType () inline
The default constructor.
Definition at line 10718 of file Opc.Ua.DataTypes.cs.
Member Function Documentation
Clone()
override object Opc.Ua.ReaderGroupDataType.Clone () inline virtual
Reimplemented from Opc.Ua.PubSubGroupDataType.
Definition at line 10855 of file Opc.Ua.DataTypes.cs.
Decode()
override void Opc.Ua.ReaderGroupDataType.Decode (IDecoder decoder) inline virtual
Reimplemented from Opc.Ua.PubSubGroupDataType.
Definition at line 10817 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
Encode()
override void Opc.Ua.ReaderGroupDataType.Encode (IEncoder encoder) inline virtual
Reimplemented from Opc.Ua.PubSubGroupDataType.
Definition at line 10803 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
IsEqual()
override bool Opc.Ua.ReaderGroupDataType.IsEqual (IEncodeable encodeable) inline virtual
Reimplemented from Opc.Ua.PubSubGroupDataType.
Definition at line 10831 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Object.
MemberwiseClone()
new object Opc.Ua.ReaderGroupDataType.MemberwiseClone () inline
Definition at line 10862 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.DataSetReaderDataTypeCollection.Clone(), Opc.Ua.ReaderGroupDataType.MemberwiseClone(), and Opc.Ua.Namespaces.OpcUaXsd.
Referenced by Opc.Ua.ReaderGroupDataType.MemberwiseClone().
Property Documentation
BinaryEncodingId
override ExpandedNodeId Opc.Ua.ReaderGroupDataType.BinaryEncodingId get
Definition at line 10792 of file Opc.Ua.DataTypes.cs.
DataSetReaders
DataSetReaderDataTypeCollection Opc.Ua.ReaderGroupDataType.DataSetReaders get set
Definition at line 10765 of file Opc.Ua.DataTypes.cs.
MessageSettings
ExtensionObject Opc.Ua.ReaderGroupDataType.MessageSettings get set
Definition at line 10755 of file Opc.Ua.DataTypes.cs.
TransportSettings
ExtensionObject Opc.Ua.ReaderGroupDataType.TransportSettings get set
Definition at line 10747 of file Opc.Ua.DataTypes.cs.
TypeId
override ExpandedNodeId Opc.Ua.ReaderGroupDataType.TypeId get
Definition at line 10786 of file Opc.Ua.DataTypes.cs.
XmlEncodingId
override ExpandedNodeId Opc.Ua.ReaderGroupDataType.XmlEncodingId get
Definition at line 10798 of file Opc.Ua.DataTypes.cs.
The documentation for this class was generated from the following file:
Opc.Ua.DataTypes.cs