Project Template: Opc.Ua.NetworkGroupDataType Class Reference
Opc.Ua.NetworkGroupDataType Class Reference
Public Member Functions
NetworkGroupDataType ()
The default constructor.
virtual void Encode (IEncoder encoder)
virtual void Decode (IDecoder decoder)
virtual bool IsEqual (IEncodeable encodeable)
virtual object Clone ()
new object MemberwiseClone ()
Properties
string ServerUri [get, set]
EndpointUrlListDataTypeCollection NetworkPaths [get, set]
virtual ExpandedNodeId TypeId [get]
virtual ExpandedNodeId BinaryEncodingId [get]
virtual ExpandedNodeId XmlEncodingId [get]
Detailed Description
<exclude>
Definition at line 61982 of file Opc.Ua.DataTypes.cs.
Constructor & Destructor Documentation
NetworkGroupDataType()
Opc.Ua.NetworkGroupDataType.NetworkGroupDataType () inline
The default constructor.
Definition at line 61988 of file Opc.Ua.DataTypes.cs.
Member Function Documentation
Clone()
virtual object Opc.Ua.NetworkGroupDataType.Clone () inline virtual
Definition at line 62108 of file Opc.Ua.DataTypes.cs.
Decode()
virtual void Opc.Ua.NetworkGroupDataType.Decode (IDecoder decoder) inline virtual
Definition at line 62075 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
Encode()
virtual void Opc.Ua.NetworkGroupDataType.Encode (IEncoder encoder) inline virtual
Definition at line 62064 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
IsEqual()
virtual bool Opc.Ua.NetworkGroupDataType.IsEqual (IEncodeable encodeable) inline virtual
Definition at line 62086 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Object.
MemberwiseClone()
new object Opc.Ua.NetworkGroupDataType.MemberwiseClone () inline
Definition at line 62115 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.EndpointUrlListDataTypeCollection.Clone(), Opc.Ua.NetworkGroupDataType.MemberwiseClone(), and Opc.Ua.Namespaces.OpcUaXsd.
Referenced by Opc.Ua.NetworkGroupDataType.MemberwiseClone().
Property Documentation
BinaryEncodingId
virtual ExpandedNodeId Opc.Ua.NetworkGroupDataType.BinaryEncodingId get
Definition at line 62053 of file Opc.Ua.DataTypes.cs.
NetworkPaths
EndpointUrlListDataTypeCollection Opc.Ua.NetworkGroupDataType.NetworkPaths get set
Definition at line 62026 of file Opc.Ua.DataTypes.cs.
ServerUri
string Opc.Ua.NetworkGroupDataType.ServerUri get set
Definition at line 62016 of file Opc.Ua.DataTypes.cs.
TypeId
virtual ExpandedNodeId Opc.Ua.NetworkGroupDataType.TypeId get
Definition at line 62047 of file Opc.Ua.DataTypes.cs.
XmlEncodingId
virtual ExpandedNodeId Opc.Ua.NetworkGroupDataType.XmlEncodingId get
Definition at line 62059 of file Opc.Ua.DataTypes.cs.
The documentation for this class was generated from the following file:
Opc.Ua.DataTypes.cs