Project Template: Opc.Ua.BuildInfo Class Reference
Opc.Ua.BuildInfo Class Reference
Public Member Functions
BuildInfo ()
The default constructor.
virtual void Encode (IEncoder encoder)
virtual void Decode (IDecoder decoder)
virtual bool IsEqual (IEncodeable encodeable)
virtual object Clone ()
new object MemberwiseClone ()
Properties
string ProductUri [get, set]
string ManufacturerName [get, set]
string ProductName [get, set]
string SoftwareVersion [get, set]
string BuildNumber [get, set]
DateTime BuildDate [get, set]
virtual ExpandedNodeId TypeId [get]
virtual ExpandedNodeId BinaryEncodingId [get]
virtual ExpandedNodeId XmlEncodingId [get]
Detailed Description
<exclude>
Definition at line 61222 of file Opc.Ua.DataTypes.cs.
Constructor & Destructor Documentation
BuildInfo()
Opc.Ua.BuildInfo.BuildInfo () inline
The default constructor.
Definition at line 61228 of file Opc.Ua.DataTypes.cs.
Member Function Documentation
Clone()
virtual object Opc.Ua.BuildInfo.Clone () inline virtual
Definition at line 61382 of file Opc.Ua.DataTypes.cs.
Referenced by Opc.Ua.ServerStatusDataType.MemberwiseClone().
Decode()
virtual void Opc.Ua.BuildInfo.Decode (IDecoder decoder) inline virtual
Definition at line 61341 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
Encode()
virtual void Opc.Ua.BuildInfo.Encode (IEncoder encoder) inline virtual
Definition at line 61326 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
IsEqual()
virtual bool Opc.Ua.BuildInfo.IsEqual (IEncodeable encodeable) inline virtual
Definition at line 61356 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Object.
MemberwiseClone()
new object Opc.Ua.BuildInfo.MemberwiseClone () inline
Definition at line 61389 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.BuildInfo.MemberwiseClone(), and Opc.Ua.Namespaces.OpcUaXsd.
Referenced by Opc.Ua.BuildInfo.MemberwiseClone().
Property Documentation
BinaryEncodingId
virtual ExpandedNodeId Opc.Ua.BuildInfo.BinaryEncodingId get
Definition at line 61315 of file Opc.Ua.DataTypes.cs.
BuildDate
DateTime Opc.Ua.BuildInfo.BuildDate get set
Definition at line 61300 of file Opc.Ua.DataTypes.cs.
BuildNumber
string Opc.Ua.BuildInfo.BuildNumber get set
Definition at line 61292 of file Opc.Ua.DataTypes.cs.
ManufacturerName
string Opc.Ua.BuildInfo.ManufacturerName get set
Definition at line 61268 of file Opc.Ua.DataTypes.cs.
ProductName
string Opc.Ua.BuildInfo.ProductName get set
Definition at line 61276 of file Opc.Ua.DataTypes.cs.
ProductUri
string Opc.Ua.BuildInfo.ProductUri get set
Definition at line 61260 of file Opc.Ua.DataTypes.cs.
SoftwareVersion
string Opc.Ua.BuildInfo.SoftwareVersion get set
Definition at line 61284 of file Opc.Ua.DataTypes.cs.
TypeId
virtual ExpandedNodeId Opc.Ua.BuildInfo.TypeId get
Definition at line 61309 of file Opc.Ua.DataTypes.cs.
XmlEncodingId
virtual ExpandedNodeId Opc.Ua.BuildInfo.XmlEncodingId get
Definition at line 61321 of file Opc.Ua.DataTypes.cs.
The documentation for this class was generated from the following file:
Opc.Ua.DataTypes.cs