HaSSL: MockDevice Class Reference
MockDevice Class Reference
#include <Device_MOCK.hpp>
Public Member Functions
MockDevice (const std::string REF_ID, const std::string NAME, const std::string DESC)
MOCK_METHOD (std::shared_ptr< Information_Model::DeviceElementGroup >, getDeviceElementGroup,(),(override))
Public Member Functions inherited from Information_Model::Device
virtual std::shared_ptr< Information_Model::DeviceElementGroup > getDeviceElementGroup ()=0
Public Member Functions inherited from Information_Model::NamedElement
const std::string getElementName ()
const std::string getElementDescription ()
const std::string getElementRefId ()
virtual ~NamedElement ()=default
Additional Inherited Members
Protected Member Functions inherited from Information_Model::Device
Device (const std::string REF_ID, const std::string NAME, const std::string DESC)
Protected Member Functions inherited from Information_Model::NamedElement
NamedElement (const std::string REF_ID, const std::string NAME, const std::string DESC)
Constructor & Destructor Documentation
MockDevice()
MockDevice::MockDevice (const std::string REF_ID, const std::string NAME, const std::string DESC) inline
References Information_Model::Device::getDeviceElementGroup(), and MOCK_METHOD().
Member Function Documentation
MOCK_METHOD()
MockDevice::MOCK_METHOD (std::shared_ptr< Information_Model::DeviceElementGroup > , getDeviceElementGroup , () , (override))
Referenced by MockDevice().
The documentation for this class was generated from the following file:
Device_MOCK.hpp