Information Modeller: Information_Model::DeviceElementGroupImpl Class Reference
Information_Model::DeviceElementGroupImpl Class Reference
This class is an implementation of Information_Model::DeviceElementGroup It contains all of the virtual method implementations and the building mechanism for Information_Model::DeviceElementGroup instances.
#include <DeviceElementGroupImpl.hpp>
Public Member Functions
DeviceElementGroupImpl (const std::string refId, const std::string name, const std::string desc)
std::string addDeviceElement (const std::string name, const std::string desc, Information_Model::ElementType type)
This method creates an instance of Information_Model:DeviceElement class and adds it to DeviceElementGroupImpl: DeviceElementGroupImpl::subelements vector.
std::vector< std::shared_ptr< Information_Model::DeviceElement > > getSubelements ()
Information_Model::DeviceElement * getSubelement (const std::string refId)
void incrementElementId ()
std::string generate_Reference_ID (Information_Model::ElementType elementType)
unsigned int getNumericElementId ()
virtual ~DeviceElementGroupImpl ()=default
Public Member Functions inherited from Information_Model::DeviceElementGroup
virtual ~DeviceElementGroup ()=default
Public Member Functions inherited from Information_Model::DeviceElement
ElementType getElementType ()
virtual ~DeviceElement ()=default
Public Member Functions inherited from Information_Model::NamedElement
const std::string getElementName ()
const std::string getElementDescription ()
const std::string getElementRefId ()
virtual ~NamedElement ()=default
Additional Inherited Members
Protected Member Functions inherited from Information_Model::DeviceElementGroup
DeviceElementGroup (const std::string REF_ID, const std::string NAME, const std::string DESC)
Protected Member Functions inherited from Information_Model::DeviceElement
DeviceElement (const std::string REF_ID, const std::string NAME, const std::string DESC, ElementType type)
Protected Member Functions inherited from Information_Model::NamedElement
NamedElement (const std::string REF_ID, const std::string NAME, const std::string DESC)
Protected Attributes inherited from Information_Model::DeviceElement
ElementType elementType = ElementType::Undefined
Detailed Description
This class is an implementation of Information_Model::DeviceElementGroup It contains all of the virtual method implementations and the building mechanism for Information_Model::DeviceElementGroup instances.
Author
Dovydas Girdvainis
Date
18.07.2019
Definition at line 18 of file DeviceElementGroupImpl.hpp.
Constructor & Destructor Documentation
DeviceElementGroupImpl()
DeviceElementGroupImpl::DeviceElementGroupImpl (const std::string refId, const std::string name, const std::string desc)
Definition at line 11 of file DeviceElementGroupImpl.cpp.
~DeviceElementGroupImpl()
virtual Information_Model::DeviceElementGroupImpl::~DeviceElementGroupImpl () virtual default
Member Function Documentation
addDeviceElement()
string DeviceElementGroupImpl::addDeviceElement (const std::string name, const std::string desc, Information_Model::ElementType type)
This method creates an instance of Information_Model:DeviceElement class and adds it to DeviceElementGroupImpl: DeviceElementGroupImpl::subelements vector.
Parameters
NAME
DESC
type
Returns
std::string Reference ID of DeviceElement within DeviceElementGroupImpl: DeviceElementGroupImpl::subelements vector
Definition at line 21 of file DeviceElementGroupImpl.cpp.
References Information_Model::Function, generate_Reference_ID(), Information_Model::Group, Information_Model::Observable, Information_Model::Readonly, and Information_Model::Writable.
Referenced by Model_Factory::DeviceBuilder::addDeviceElement().
generate_Reference_ID()
string DeviceElementGroupImpl::generate_Reference_ID (Information_Model::ElementType elementType)
Definition at line 104 of file DeviceElementGroupImpl.cpp.
References Information_Model::Function, Information_Model::NamedElement::getElementRefId(), getNumericElementId(), Information_Model::Group, incrementElementId(), Information_Model::Observable, Information_Model::Readonly, Information_Model::Undefined, and Information_Model::Writable.
Referenced by addDeviceElement().
getNumericElementId()
unsigned int DeviceElementGroupImpl::getNumericElementId () virtual
Implements Information_Model::DeviceElementGroup.
Definition at line 98 of file DeviceElementGroupImpl.cpp.
Referenced by generate_Reference_ID().
getSubelement()
Information_Model::DeviceElement * DeviceElementGroupImpl::getSubelement (const std::string refId) virtual
Implements Information_Model::DeviceElementGroup.
Definition at line 68 of file DeviceElementGroupImpl.cpp.
Referenced by Model_Factory::DeviceBuilder::addDeviceElement().
getSubelements()
vector< std::shared_ptr< Information_Model::DeviceElement > > DeviceElementGroupImpl::getSubelements () virtual
Implements Information_Model::DeviceElementGroup.
Definition at line 82 of file DeviceElementGroupImpl.cpp.
Referenced by Model_Factory::DeviceBuilder::addDeviceElement().
incrementElementId()
void DeviceElementGroupImpl::incrementElementId ()
Definition at line 93 of file DeviceElementGroupImpl.cpp.
Referenced by generate_Reference_ID().
The documentation for this class was generated from the following files:
DeviceElementGroupImpl.hpp
DeviceElementGroupImpl.cpp