Project Template: Opc.Ua.AddReferencesRequest Class Reference
Opc.Ua.AddReferencesRequest Class Reference
Public Member Functions
AddReferencesRequest ()
The default constructor.
virtual void Encode (IEncoder encoder)
virtual void Decode (IDecoder decoder)
virtual bool IsEqual (IEncodeable encodeable)
virtual object Clone ()
new object MemberwiseClone ()
Properties
RequestHeader RequestHeader [get, set]
AddReferencesItemCollection ReferencesToAdd [get, set]
virtual ExpandedNodeId TypeId [get]
virtual ExpandedNodeId BinaryEncodingId [get]
virtual ExpandedNodeId XmlEncodingId [get]
Detailed Description
<exclude>
Definition at line 1324 of file Opc.Ua.Messages.cs.
Constructor & Destructor Documentation
AddReferencesRequest()
Opc.Ua.AddReferencesRequest.AddReferencesRequest () inline
The default constructor.
Definition at line 34858 of file Opc.Ua.DataTypes.cs.
Member Function Documentation
Clone()
virtual object Opc.Ua.AddReferencesRequest.Clone () inline virtual
Definition at line 34992 of file Opc.Ua.DataTypes.cs.
Decode()
virtual void Opc.Ua.AddReferencesRequest.Decode (IDecoder decoder) inline virtual
Definition at line 34959 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
Encode()
virtual void Opc.Ua.AddReferencesRequest.Encode (IEncoder encoder) inline virtual
Definition at line 34948 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
IsEqual()
virtual bool Opc.Ua.AddReferencesRequest.IsEqual (IEncodeable encodeable) inline virtual
Definition at line 34970 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Object.
MemberwiseClone()
new object Opc.Ua.AddReferencesRequest.MemberwiseClone () inline
Definition at line 34999 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.RequestHeader.Clone(), Opc.Ua.AddReferencesItemCollection.Clone(), Opc.Ua.AddReferencesRequest.MemberwiseClone(), and Opc.Ua.Namespaces.OpcUaXsd.
Referenced by Opc.Ua.AddReferencesRequest.MemberwiseClone().
Property Documentation
BinaryEncodingId
virtual ExpandedNodeId Opc.Ua.AddReferencesRequest.BinaryEncodingId get
Definition at line 34937 of file Opc.Ua.DataTypes.cs.
ReferencesToAdd
AddReferencesItemCollection Opc.Ua.AddReferencesRequest.ReferencesToAdd get set
Definition at line 34910 of file Opc.Ua.DataTypes.cs.
Referenced by Opc.Ua.SessionClient.BeginAddReferences(), Opc.Ua.SessionClient.EndAddNodes(), and Opc.Ua.SessionEndpoint.EndAddNodes().
RequestHeader
RequestHeader Opc.Ua.AddReferencesRequest.RequestHeader get set
Definition at line 34888 of file Opc.Ua.DataTypes.cs.
Referenced by Opc.Ua.SessionClient.BeginAddReferences(), Opc.Ua.SessionClient.EndAddNodes(), and Opc.Ua.SessionEndpoint.EndAddNodes().
TypeId
virtual ExpandedNodeId Opc.Ua.AddReferencesRequest.TypeId get
Definition at line 34931 of file Opc.Ua.DataTypes.cs.
XmlEncodingId
virtual ExpandedNodeId Opc.Ua.AddReferencesRequest.XmlEncodingId get
Definition at line 34943 of file Opc.Ua.DataTypes.cs.
The documentation for this class was generated from the following files:
Opc.Ua.Messages.cs
Opc.Ua.DataTypes.cs