Project Template: nodeset_compiler.nodes Namespace Reference
nodeset_compiler.nodes Namespace Reference
Data Structures
class DataTypeNode
class MethodNode
class Node
class ObjectNode
class ObjectTypeNode
class Reference
class ReferenceTypeNode
class VariableNode
class VariableTypeNode
class ViewNode
Functions
def unicode (s)
def RefOrAlias (s)
Variables
logger = logging.getLogger(__name__)
Function Documentation
RefOrAlias()
def nodeset_compiler.nodes.RefOrAlias (s)
Definition at line 63 of file nodes.py.
Referenced by nodeset_compiler.nodes.VariableNode.parseXML(), and nodeset_compiler.nodes.Node.parseXMLReferences().
unicode()
def nodeset_compiler.nodes.unicode (s)
Definition at line 31 of file nodes.py.
Referenced by nodeset_compiler.nodes.ReferenceTypeNode.parseXML(), and nodeset_compiler.nodes.VariableNode.parseXML().
Variable Documentation
logger
nodeset_compiler.nodes.logger = logging.getLogger(__name__)
Definition at line 27 of file nodes.py.