Project Template: Opc.Ua.QueryDataDescription Class Reference
Opc.Ua.QueryDataDescription Class Reference
Public Member Functions
QueryDataDescription ()
The default constructor.
virtual void Encode (IEncoder encoder)
virtual void Decode (IDecoder decoder)
virtual bool IsEqual (IEncodeable encodeable)
virtual object Clone ()
new object MemberwiseClone ()
Properties
RelativePath RelativePath [get, set]
uint AttributeId [get, set]
string IndexRange [get, set]
virtual ExpandedNodeId TypeId [get]
virtual ExpandedNodeId BinaryEncodingId [get]
virtual ExpandedNodeId XmlEncodingId [get]
Detailed Description
<exclude>
Definition at line 41001 of file Opc.Ua.DataTypes.cs.
Constructor & Destructor Documentation
QueryDataDescription()
Opc.Ua.QueryDataDescription.QueryDataDescription () inline
The default constructor.
Definition at line 41007 of file Opc.Ua.DataTypes.cs.
Member Function Documentation
Clone()
virtual object Opc.Ua.QueryDataDescription.Clone () inline virtual
Definition at line 41139 of file Opc.Ua.DataTypes.cs.
Decode()
virtual void Opc.Ua.QueryDataDescription.Decode (IDecoder decoder) inline virtual
Definition at line 41104 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
Encode()
virtual void Opc.Ua.QueryDataDescription.Encode (IEncoder encoder) inline virtual
Definition at line 41092 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
IsEqual()
virtual bool Opc.Ua.QueryDataDescription.IsEqual (IEncodeable encodeable) inline virtual
Definition at line 41116 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Object.
MemberwiseClone()
new object Opc.Ua.QueryDataDescription.MemberwiseClone () inline
Definition at line 41146 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.RelativePath.Clone(), Opc.Ua.QueryDataDescription.MemberwiseClone(), and Opc.Ua.Namespaces.OpcUaXsd.
Referenced by Opc.Ua.QueryDataDescription.MemberwiseClone().
Property Documentation
AttributeId
uint Opc.Ua.QueryDataDescription.AttributeId get set
Definition at line 41058 of file Opc.Ua.DataTypes.cs.
BinaryEncodingId
virtual ExpandedNodeId Opc.Ua.QueryDataDescription.BinaryEncodingId get
Definition at line 41081 of file Opc.Ua.DataTypes.cs.
IndexRange
string Opc.Ua.QueryDataDescription.IndexRange get set
Definition at line 41066 of file Opc.Ua.DataTypes.cs.
RelativePath
RelativePath Opc.Ua.QueryDataDescription.RelativePath get set
Definition at line 41038 of file Opc.Ua.DataTypes.cs.
TypeId
virtual ExpandedNodeId Opc.Ua.QueryDataDescription.TypeId get
Definition at line 41075 of file Opc.Ua.DataTypes.cs.
XmlEncodingId
virtual ExpandedNodeId Opc.Ua.QueryDataDescription.XmlEncodingId get
Definition at line 41087 of file Opc.Ua.DataTypes.cs.
The documentation for this class was generated from the following file:
Opc.Ua.DataTypes.cs