Project Template: Opc.Ua.EndpointDescription Class Reference
Opc.Ua.EndpointDescription Class Reference
Public Member Functions
EndpointDescription ()
The default constructor.
virtual void Encode (IEncoder encoder)
virtual void Decode (IDecoder decoder)
virtual bool IsEqual (IEncodeable encodeable)
virtual object Clone ()
new object MemberwiseClone ()
Properties
string EndpointUrl [get, set]
ApplicationDescription Server [get, set]
byte [] ServerCertificate [get, set]
MessageSecurityMode SecurityMode [get, set]
string SecurityPolicyUri [get, set]
UserTokenPolicyCollection UserIdentityTokens [get, set]
string TransportProfileUri [get, set]
byte SecurityLevel [get, set]
virtual ExpandedNodeId TypeId [get]
virtual ExpandedNodeId BinaryEncodingId [get]
virtual ExpandedNodeId XmlEncodingId [get]
Detailed Description
<exclude>
Definition at line 25826 of file Opc.Ua.DataTypes.cs.
Constructor & Destructor Documentation
EndpointDescription()
Opc.Ua.EndpointDescription.EndpointDescription () inline
The default constructor.
Definition at line 25832 of file Opc.Ua.DataTypes.cs.
Member Function Documentation
Clone()
virtual object Opc.Ua.EndpointDescription.Clone () inline virtual
Definition at line 26038 of file Opc.Ua.DataTypes.cs.
Decode()
virtual void Opc.Ua.EndpointDescription.Decode (IDecoder decoder) inline virtual
Definition at line 25993 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd, and Opc.Ua.Server.
Encode()
virtual void Opc.Ua.EndpointDescription.Encode (IEncoder encoder) inline virtual
Definition at line 25976 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd, and Opc.Ua.Server.
IsEqual()
virtual bool Opc.Ua.EndpointDescription.IsEqual (IEncodeable encodeable) inline virtual
Definition at line 26010 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Object.
MemberwiseClone()
new object Opc.Ua.EndpointDescription.MemberwiseClone () inline
Definition at line 26045 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.ApplicationDescription.Clone(), Opc.Ua.UserTokenPolicyCollection.Clone(), Opc.Ua.EndpointDescription.MemberwiseClone(), and Opc.Ua.Namespaces.OpcUaXsd.
Referenced by Opc.Ua.EndpointDescription.MemberwiseClone().
Property Documentation
BinaryEncodingId
virtual ExpandedNodeId Opc.Ua.EndpointDescription.BinaryEncodingId get
Definition at line 25965 of file Opc.Ua.DataTypes.cs.
EndpointUrl
string Opc.Ua.EndpointDescription.EndpointUrl get set
Definition at line 25866 of file Opc.Ua.DataTypes.cs.
SecurityLevel
byte Opc.Ua.EndpointDescription.SecurityLevel get set
Definition at line 25950 of file Opc.Ua.DataTypes.cs.
SecurityMode
MessageSecurityMode Opc.Ua.EndpointDescription.SecurityMode get set
Definition at line 25904 of file Opc.Ua.DataTypes.cs.
SecurityPolicyUri
string Opc.Ua.EndpointDescription.SecurityPolicyUri get set
Definition at line 25912 of file Opc.Ua.DataTypes.cs.
Server
ApplicationDescription Opc.Ua.EndpointDescription.Server get set
Definition at line 25876 of file Opc.Ua.DataTypes.cs.
ServerCertificate
byte [] Opc.Ua.EndpointDescription.ServerCertificate get set
Definition at line 25896 of file Opc.Ua.DataTypes.cs.
TransportProfileUri
string Opc.Ua.EndpointDescription.TransportProfileUri get set
Definition at line 25942 of file Opc.Ua.DataTypes.cs.
TypeId
virtual ExpandedNodeId Opc.Ua.EndpointDescription.TypeId get
Definition at line 25959 of file Opc.Ua.DataTypes.cs.
UserIdentityTokens
UserTokenPolicyCollection Opc.Ua.EndpointDescription.UserIdentityTokens get set
Definition at line 25922 of file Opc.Ua.DataTypes.cs.
XmlEncodingId
virtual ExpandedNodeId Opc.Ua.EndpointDescription.XmlEncodingId get
Definition at line 25971 of file Opc.Ua.DataTypes.cs.
The documentation for this class was generated from the following file:
Opc.Ua.DataTypes.cs