Project Template: Opc.Ua.TargetVariablesDataType Class Reference
Opc.Ua.TargetVariablesDataType Class Reference
Public Member Functions
TargetVariablesDataType ()
The default constructor.
override void Encode (IEncoder encoder)
override void Decode (IDecoder decoder)
override bool IsEqual (IEncodeable encodeable)
override object Clone ()
new object MemberwiseClone ()
Public Member Functions inherited from Opc.Ua.SubscribedDataSetDataType
SubscribedDataSetDataType ()
The default constructor.
new object MemberwiseClone ()
Properties
FieldTargetDataTypeCollection TargetVariables [get, set]
override ExpandedNodeId TypeId [get]
override ExpandedNodeId BinaryEncodingId [get]
override ExpandedNodeId XmlEncodingId [get]
Properties inherited from Opc.Ua.SubscribedDataSetDataType
virtual ExpandedNodeId TypeId [get]
virtual ExpandedNodeId BinaryEncodingId [get]
virtual ExpandedNodeId XmlEncodingId [get]
Detailed Description
<exclude>
Definition at line 12479 of file Opc.Ua.DataTypes.cs.
Constructor & Destructor Documentation
TargetVariablesDataType()
Opc.Ua.TargetVariablesDataType.TargetVariablesDataType () inline
The default constructor.
Definition at line 12485 of file Opc.Ua.DataTypes.cs.
Member Function Documentation
Clone()
override object Opc.Ua.TargetVariablesDataType.Clone () inline virtual
Reimplemented from Opc.Ua.SubscribedDataSetDataType.
Definition at line 12598 of file Opc.Ua.DataTypes.cs.
Decode()
override void Opc.Ua.TargetVariablesDataType.Decode (IDecoder decoder) inline virtual
Reimplemented from Opc.Ua.SubscribedDataSetDataType.
Definition at line 12564 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
Encode()
override void Opc.Ua.TargetVariablesDataType.Encode (IEncoder encoder) inline virtual
Reimplemented from Opc.Ua.SubscribedDataSetDataType.
Definition at line 12552 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
IsEqual()
override bool Opc.Ua.TargetVariablesDataType.IsEqual (IEncodeable encodeable) inline virtual
Reimplemented from Opc.Ua.SubscribedDataSetDataType.
Definition at line 12576 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Object.
MemberwiseClone()
new object Opc.Ua.TargetVariablesDataType.MemberwiseClone () inline
Definition at line 12605 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.FieldTargetDataTypeCollection.Clone(), Opc.Ua.TargetVariablesDataType.MemberwiseClone(), and Opc.Ua.Namespaces.OpcUaXsd.
Referenced by Opc.Ua.TargetVariablesDataType.MemberwiseClone().
Property Documentation
BinaryEncodingId
override ExpandedNodeId Opc.Ua.TargetVariablesDataType.BinaryEncodingId get
Definition at line 12541 of file Opc.Ua.DataTypes.cs.
TargetVariables
FieldTargetDataTypeCollection Opc.Ua.TargetVariablesDataType.TargetVariables get set
Definition at line 12514 of file Opc.Ua.DataTypes.cs.
TypeId
override ExpandedNodeId Opc.Ua.TargetVariablesDataType.TypeId get
Definition at line 12535 of file Opc.Ua.DataTypes.cs.
XmlEncodingId
override ExpandedNodeId Opc.Ua.TargetVariablesDataType.XmlEncodingId get
Definition at line 12547 of file Opc.Ua.DataTypes.cs.
The documentation for this class was generated from the following file:
Opc.Ua.DataTypes.cs