Information Modeller: Information_Model::DeviceElement Class Reference
Information_Model::DeviceElement Class Reference
This class is the base for all of the elements within the Information_Model::Device.
#include <DeviceElement.hpp>
Public Member Functions
ElementType getElementType ()
virtual ~DeviceElement ()=default
Public Member Functions inherited from Information_Model::NamedElement
const std::string getElementName ()
const std::string getElementDescription ()
const std::string getElementRefId ()
virtual ~NamedElement ()=default
Protected Member Functions
DeviceElement (const std::string REF_ID, const std::string NAME, const std::string DESC, ElementType type)
Protected Member Functions inherited from Information_Model::NamedElement
NamedElement (const std::string REF_ID, const std::string NAME, const std::string DESC)
Protected Attributes
ElementType elementType = ElementType::Undefined
Detailed Description
This class is the base for all of the elements within the Information_Model::Device.
Attention
This class should be instantiated by its children only!
Author
Dovydas Girdvainis
Date
18.07.2019
Definition at line 26 of file DeviceElement.hpp.
Constructor & Destructor Documentation
DeviceElement()
Information_Model::DeviceElement::DeviceElement (const std::string REF_ID, const std::string NAME, const std::string DESC, ElementType type) inline protected
Definition at line 32 of file DeviceElement.hpp.
References getElementType(), and ~DeviceElement().
~DeviceElement()
virtual Information_Model::DeviceElement::~DeviceElement () virtual default
Referenced by DeviceElement().
Member Function Documentation
getElementType()
ElementType DeviceElement::getElementType ()
Definition at line 7 of file DeviceElementImpl.cpp.
Referenced by DeviceElement(), and printElement().
Field Documentation
elementType
ElementType Information_Model::DeviceElement::elementType = ElementType::Undefined protected
Definition at line 29 of file DeviceElement.hpp.
The documentation for this class was generated from the following files:
DeviceElement.hpp
DeviceElementImpl.cpp