HaSSL: MockDeviceElementGroup Class Reference
MockDeviceElementGroup Class Reference
#include <DeviceElementGroup_MOCK.hpp>
Public Member Functions
MockDeviceElementGroup (const std::string REF_ID, const std::string NAME, const std::string DESC)
MOCK_METHOD (std::vector< std::shared_ptr< DeviceElement >>, getSubelements,(),(override))
MOCK_METHOD (std::shared_ptr< Information_Model::DeviceElement >, getSubelement,(const std::string REF_ID),(override))
MOCK_METHOD (unsigned int, getNumericElementId,(),(override))
Public Member Functions inherited from Information_Model::DeviceElementGroup
virtual std::vector< std::shared_ptr< DeviceElement > > getSubelements ()=0
virtual std::shared_ptr< DeviceElement > getSubelement (const std::string REF_ID)=0
virtual unsigned int getNumericElementId ()=0
virtual ~DeviceElementGroup ()=default
Public Member Functions inherited from Information_Model::DeviceElement
DeviceElement (const std::string REF_ID, const std::string NAME, const std::string DESC, ElementType type)
ElementType getElementType ()
virtual ~DeviceElement ()=default
Public Member Functions inherited from Information_Model::NamedElement
const std::string getElementName ()
const std::string getElementDescription ()
const std::string getElementRefId ()
virtual ~NamedElement ()=default
Additional Inherited Members
Protected Member Functions inherited from Information_Model::DeviceElementGroup
DeviceElementGroup (const std::string REF_ID, const std::string NAME, const std::string DESC)
Protected Member Functions inherited from Information_Model::NamedElement
NamedElement (const std::string REF_ID, const std::string NAME, const std::string DESC)
Protected Attributes inherited from Information_Model::DeviceElement
ElementType elementType = ElementType::Undefined
Constructor & Destructor Documentation
MockDeviceElementGroup()
MockDeviceElementGroup::MockDeviceElementGroup (const std::string REF_ID, const std::string NAME, const std::string DESC) inline
References Information_Model::DeviceElementGroup::getNumericElementId(), Information_Model::DeviceElementGroup::getSubelement(), Information_Model::DeviceElementGroup::getSubelements(), and MOCK_METHOD().
Member Function Documentation
MOCK_METHOD() [1/3]
MockDeviceElementGroup::MOCK_METHOD (std::vector< std::shared_ptr< DeviceElement >> , getSubelements , () , (override))
Referenced by MockDeviceElementGroup().
MOCK_METHOD() [2/3]
MockDeviceElementGroup::MOCK_METHOD (std::shared_ptr< Information_Model::DeviceElement > , getSubelement , (const std::string REF_ID) , (override))
MOCK_METHOD() [3/3]
MockDeviceElementGroup::MOCK_METHOD (unsigned int, getNumericElementId , () , (override))
The documentation for this class was generated from the following file:
DeviceElementGroup_MOCK.hpp