Project Template: Opc.Ua.FindServersRequest Class Reference
Opc.Ua.FindServersRequest Class Reference
Public Member Functions
FindServersRequest ()
The default constructor.
virtual void Encode (IEncoder encoder)
virtual void Decode (IDecoder decoder)
virtual bool IsEqual (IEncodeable encodeable)
virtual object Clone ()
new object MemberwiseClone ()
Properties
RequestHeader RequestHeader [get, set]
string EndpointUrl [get, set]
StringCollection LocaleIds [get, set]
StringCollection ServerUris [get, set]
virtual ExpandedNodeId TypeId [get]
virtual ExpandedNodeId BinaryEncodingId [get]
virtual ExpandedNodeId XmlEncodingId [get]
Detailed Description
<exclude>
Definition at line 40 of file Opc.Ua.Messages.cs.
Constructor & Destructor Documentation
FindServersRequest()
Opc.Ua.FindServersRequest.FindServersRequest () inline
The default constructor.
Definition at line 24448 of file Opc.Ua.DataTypes.cs.
Member Function Documentation
Clone()
virtual object Opc.Ua.FindServersRequest.Clone () inline virtual
Definition at line 24620 of file Opc.Ua.DataTypes.cs.
Decode()
virtual void Opc.Ua.FindServersRequest.Decode (IDecoder decoder) inline virtual
Definition at line 24583 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
Encode()
virtual void Opc.Ua.FindServersRequest.Encode (IEncoder encoder) inline virtual
Definition at line 24570 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
IsEqual()
virtual bool Opc.Ua.FindServersRequest.IsEqual (IEncodeable encodeable) inline virtual
Definition at line 24596 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Object.
MemberwiseClone()
new object Opc.Ua.FindServersRequest.MemberwiseClone () inline
Definition at line 24627 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.RequestHeader.Clone(), Opc.Ua.FindServersRequest.MemberwiseClone(), and Opc.Ua.Namespaces.OpcUaXsd.
Referenced by Opc.Ua.FindServersRequest.MemberwiseClone().
Property Documentation
BinaryEncodingId
virtual ExpandedNodeId Opc.Ua.FindServersRequest.BinaryEncodingId get
Definition at line 24559 of file Opc.Ua.DataTypes.cs.
EndpointUrl
string Opc.Ua.FindServersRequest.EndpointUrl get set
Definition at line 24500 of file Opc.Ua.DataTypes.cs.
Referenced by Opc.Ua.DiscoveryClient.BeginFindServers().
LocaleIds
StringCollection Opc.Ua.FindServersRequest.LocaleIds get set
Definition at line 24510 of file Opc.Ua.DataTypes.cs.
Referenced by Opc.Ua.DiscoveryClient.BeginFindServers().
RequestHeader
RequestHeader Opc.Ua.FindServersRequest.RequestHeader get set
Definition at line 24480 of file Opc.Ua.DataTypes.cs.
Referenced by Opc.Ua.DiscoveryClient.BeginFindServers().
ServerUris
StringCollection Opc.Ua.FindServersRequest.ServerUris get set
Definition at line 24532 of file Opc.Ua.DataTypes.cs.
Referenced by Opc.Ua.DiscoveryClient.BeginFindServers().
TypeId
virtual ExpandedNodeId Opc.Ua.FindServersRequest.TypeId get
Definition at line 24553 of file Opc.Ua.DataTypes.cs.
XmlEncodingId
virtual ExpandedNodeId Opc.Ua.FindServersRequest.XmlEncodingId get
Definition at line 24565 of file Opc.Ua.DataTypes.cs.
The documentation for this class was generated from the following files:
Opc.Ua.Messages.cs
Opc.Ua.DataTypes.cs