Project Template: Opc.Ua.SubscribedDataSetMirrorDataType Class Reference
Opc.Ua.SubscribedDataSetMirrorDataType Class Reference
Public Member Functions
SubscribedDataSetMirrorDataType ()
The default constructor.
override void Encode (IEncoder encoder)
override void Decode (IDecoder decoder)
override bool IsEqual (IEncodeable encodeable)
override object Clone ()
new object MemberwiseClone ()
Public Member Functions inherited from Opc.Ua.SubscribedDataSetDataType
SubscribedDataSetDataType ()
The default constructor.
new object MemberwiseClone ()
Properties
string ParentNodeName [get, set]
RolePermissionTypeCollection RolePermissions [get, set]
override ExpandedNodeId TypeId [get]
override ExpandedNodeId BinaryEncodingId [get]
override ExpandedNodeId XmlEncodingId [get]
Properties inherited from Opc.Ua.SubscribedDataSetDataType
virtual ExpandedNodeId TypeId [get]
virtual ExpandedNodeId BinaryEncodingId [get]
virtual ExpandedNodeId XmlEncodingId [get]
Detailed Description
<exclude>
Definition at line 13126 of file Opc.Ua.DataTypes.cs.
Constructor & Destructor Documentation
SubscribedDataSetMirrorDataType()
Opc.Ua.SubscribedDataSetMirrorDataType.SubscribedDataSetMirrorDataType () inline
The default constructor.
Definition at line 13132 of file Opc.Ua.DataTypes.cs.
Member Function Documentation
Clone()
override object Opc.Ua.SubscribedDataSetMirrorDataType.Clone () inline virtual
Reimplemented from Opc.Ua.SubscribedDataSetDataType.
Definition at line 13257 of file Opc.Ua.DataTypes.cs.
Decode()
override void Opc.Ua.SubscribedDataSetMirrorDataType.Decode (IDecoder decoder) inline virtual
Reimplemented from Opc.Ua.SubscribedDataSetDataType.
Definition at line 13221 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd, and Opc.Ua.RolePermissions.
Encode()
override void Opc.Ua.SubscribedDataSetMirrorDataType.Encode (IEncoder encoder) inline virtual
Reimplemented from Opc.Ua.SubscribedDataSetDataType.
Definition at line 13208 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd, and Opc.Ua.RolePermissions.
IsEqual()
override bool Opc.Ua.SubscribedDataSetMirrorDataType.IsEqual (IEncodeable encodeable) inline virtual
Reimplemented from Opc.Ua.SubscribedDataSetDataType.
Definition at line 13234 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Object.
MemberwiseClone()
new object Opc.Ua.SubscribedDataSetMirrorDataType.MemberwiseClone () inline
Definition at line 13264 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.RolePermissionTypeCollection.Clone(), Opc.Ua.SubscribedDataSetMirrorDataType.MemberwiseClone(), and Opc.Ua.Namespaces.OpcUaXsd.
Referenced by Opc.Ua.SubscribedDataSetMirrorDataType.MemberwiseClone().
Property Documentation
BinaryEncodingId
override ExpandedNodeId Opc.Ua.SubscribedDataSetMirrorDataType.BinaryEncodingId get
Definition at line 13197 of file Opc.Ua.DataTypes.cs.
ParentNodeName
string Opc.Ua.SubscribedDataSetMirrorDataType.ParentNodeName get set
Definition at line 13160 of file Opc.Ua.DataTypes.cs.
RolePermissions
RolePermissionTypeCollection Opc.Ua.SubscribedDataSetMirrorDataType.RolePermissions get set
Definition at line 13170 of file Opc.Ua.DataTypes.cs.
TypeId
override ExpandedNodeId Opc.Ua.SubscribedDataSetMirrorDataType.TypeId get
Definition at line 13191 of file Opc.Ua.DataTypes.cs.
XmlEncodingId
override ExpandedNodeId Opc.Ua.SubscribedDataSetMirrorDataType.XmlEncodingId get
Definition at line 13203 of file Opc.Ua.DataTypes.cs.
The documentation for this class was generated from the following file:
Opc.Ua.DataTypes.cs