Project Template: Opc.Ua.WriterGroupDataType Class Reference
Opc.Ua.WriterGroupDataType Class Reference
Public Member Functions
WriterGroupDataType ()
The default constructor.
override void Encode (IEncoder encoder)
override void Decode (IDecoder decoder)
override bool IsEqual (IEncodeable encodeable)
override object Clone ()
new object MemberwiseClone ()
Public Member Functions inherited from Opc.Ua.PubSubGroupDataType
PubSubGroupDataType ()
The default constructor.
new object MemberwiseClone ()
Properties
ushort WriterGroupId [get, set]
double PublishingInterval [get, set]
double KeepAliveTime [get, set]
byte Priority [get, set]
StringCollection LocaleIds [get, set]
string HeaderLayoutUri [get, set]
ExtensionObject TransportSettings [get, set]
ExtensionObject MessageSettings [get, set]
DataSetWriterDataTypeCollection DataSetWriters [get, set]
override ExpandedNodeId TypeId [get]
override ExpandedNodeId BinaryEncodingId [get]
override ExpandedNodeId XmlEncodingId [get]
Properties inherited from Opc.Ua.PubSubGroupDataType
string Name [get, set]
bool Enabled [get, set]
MessageSecurityMode SecurityMode [get, set]
string SecurityGroupId [get, set]
EndpointDescriptionCollection SecurityKeyServices [get, set]
uint MaxNetworkMessageSize [get, set]
KeyValuePairCollection GroupProperties [get, set]
virtual ExpandedNodeId TypeId [get]
virtual ExpandedNodeId BinaryEncodingId [get]
virtual ExpandedNodeId XmlEncodingId [get]
Detailed Description
<exclude>
Definition at line 8928 of file Opc.Ua.DataTypes.cs.
Constructor & Destructor Documentation
WriterGroupDataType()
Opc.Ua.WriterGroupDataType.WriterGroupDataType () inline
The default constructor.
Definition at line 8934 of file Opc.Ua.DataTypes.cs.
Member Function Documentation
Clone()
override object Opc.Ua.WriterGroupDataType.Clone () inline virtual
Reimplemented from Opc.Ua.PubSubGroupDataType.
Definition at line 9157 of file Opc.Ua.DataTypes.cs.
Decode()
override void Opc.Ua.WriterGroupDataType.Decode (IDecoder decoder) inline virtual
Reimplemented from Opc.Ua.PubSubGroupDataType.
Definition at line 9107 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd, and Opc.Ua.WriterGroupId.
Encode()
override void Opc.Ua.WriterGroupDataType.Encode (IEncoder encoder) inline virtual
Reimplemented from Opc.Ua.PubSubGroupDataType.
Definition at line 9087 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd, and Opc.Ua.WriterGroupId.
IsEqual()
override bool Opc.Ua.WriterGroupDataType.IsEqual (IEncodeable encodeable) inline virtual
Reimplemented from Opc.Ua.PubSubGroupDataType.
Definition at line 9127 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Object.
MemberwiseClone()
new object Opc.Ua.WriterGroupDataType.MemberwiseClone () inline
Definition at line 9164 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.DataSetWriterDataTypeCollection.Clone(), Opc.Ua.WriterGroupDataType.MemberwiseClone(), and Opc.Ua.Namespaces.OpcUaXsd.
Referenced by Opc.Ua.WriterGroupDataType.MemberwiseClone().
Property Documentation
BinaryEncodingId
override ExpandedNodeId Opc.Ua.WriterGroupDataType.BinaryEncodingId get
Definition at line 9076 of file Opc.Ua.DataTypes.cs.
DataSetWriters
DataSetWriterDataTypeCollection Opc.Ua.WriterGroupDataType.DataSetWriters get set
Definition at line 9049 of file Opc.Ua.DataTypes.cs.
HeaderLayoutUri
string Opc.Ua.WriterGroupDataType.HeaderLayoutUri get set
Definition at line 9023 of file Opc.Ua.DataTypes.cs.
KeepAliveTime
double Opc.Ua.WriterGroupDataType.KeepAliveTime get set
Definition at line 8985 of file Opc.Ua.DataTypes.cs.
LocaleIds
StringCollection Opc.Ua.WriterGroupDataType.LocaleIds get set
Definition at line 9003 of file Opc.Ua.DataTypes.cs.
MessageSettings
ExtensionObject Opc.Ua.WriterGroupDataType.MessageSettings get set
Definition at line 9039 of file Opc.Ua.DataTypes.cs.
Priority
byte Opc.Ua.WriterGroupDataType.Priority get set
Definition at line 8993 of file Opc.Ua.DataTypes.cs.
PublishingInterval
double Opc.Ua.WriterGroupDataType.PublishingInterval get set
Definition at line 8977 of file Opc.Ua.DataTypes.cs.
TransportSettings
ExtensionObject Opc.Ua.WriterGroupDataType.TransportSettings get set
Definition at line 9031 of file Opc.Ua.DataTypes.cs.
TypeId
override ExpandedNodeId Opc.Ua.WriterGroupDataType.TypeId get
Definition at line 9070 of file Opc.Ua.DataTypes.cs.
WriterGroupId
ushort Opc.Ua.WriterGroupDataType.WriterGroupId get set
Definition at line 8969 of file Opc.Ua.DataTypes.cs.
XmlEncodingId
override ExpandedNodeId Opc.Ua.WriterGroupDataType.XmlEncodingId get
Definition at line 9082 of file Opc.Ua.DataTypes.cs.
The documentation for this class was generated from the following file:
Opc.Ua.DataTypes.cs