Project Template: Opc.Ua.DeleteSubscriptionsRequest Class Reference
Opc.Ua.DeleteSubscriptionsRequest Class Reference
Public Member Functions
DeleteSubscriptionsRequest ()
The default constructor.
virtual void Encode (IEncoder encoder)
virtual void Decode (IDecoder decoder)
virtual bool IsEqual (IEncodeable encodeable)
virtual object Clone ()
new object MemberwiseClone ()
Properties
RequestHeader RequestHeader [get, set]
UInt32Collection SubscriptionIds [get, set]
virtual ExpandedNodeId TypeId [get]
virtual ExpandedNodeId BinaryEncodingId [get]
virtual ExpandedNodeId XmlEncodingId [get]
Detailed Description
<exclude>
Definition at line 4106 of file Opc.Ua.Messages.cs.
Constructor & Destructor Documentation
DeleteSubscriptionsRequest()
Opc.Ua.DeleteSubscriptionsRequest.DeleteSubscriptionsRequest () inline
The default constructor.
Definition at line 60852 of file Opc.Ua.DataTypes.cs.
Member Function Documentation
Clone()
virtual object Opc.Ua.DeleteSubscriptionsRequest.Clone () inline virtual
Definition at line 60986 of file Opc.Ua.DataTypes.cs.
Decode()
virtual void Opc.Ua.DeleteSubscriptionsRequest.Decode (IDecoder decoder) inline virtual
Definition at line 60953 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
Encode()
virtual void Opc.Ua.DeleteSubscriptionsRequest.Encode (IEncoder encoder) inline virtual
Definition at line 60942 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
IsEqual()
virtual bool Opc.Ua.DeleteSubscriptionsRequest.IsEqual (IEncodeable encodeable) inline virtual
Definition at line 60964 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Object.
MemberwiseClone()
new object Opc.Ua.DeleteSubscriptionsRequest.MemberwiseClone () inline
Definition at line 60993 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.RequestHeader.Clone(), Opc.Ua.DeleteSubscriptionsRequest.MemberwiseClone(), and Opc.Ua.Namespaces.OpcUaXsd.
Referenced by Opc.Ua.DeleteSubscriptionsRequest.MemberwiseClone().
Property Documentation
BinaryEncodingId
virtual ExpandedNodeId Opc.Ua.DeleteSubscriptionsRequest.BinaryEncodingId get
Definition at line 60931 of file Opc.Ua.DataTypes.cs.
RequestHeader
RequestHeader Opc.Ua.DeleteSubscriptionsRequest.RequestHeader get set
Definition at line 60882 of file Opc.Ua.DataTypes.cs.
Referenced by Opc.Ua.SessionClient.BeginDeleteSubscriptions(), Opc.Ua.SessionEndpoint.EndTransferSubscriptions(), and Opc.Ua.SessionClient.EndTransferSubscriptions().
SubscriptionIds
UInt32Collection Opc.Ua.DeleteSubscriptionsRequest.SubscriptionIds get set
Definition at line 60904 of file Opc.Ua.DataTypes.cs.
Referenced by Opc.Ua.SessionClient.BeginDeleteSubscriptions(), Opc.Ua.SessionEndpoint.EndTransferSubscriptions(), and Opc.Ua.SessionClient.EndTransferSubscriptions().
TypeId
virtual ExpandedNodeId Opc.Ua.DeleteSubscriptionsRequest.TypeId get
Definition at line 60925 of file Opc.Ua.DataTypes.cs.
XmlEncodingId
virtual ExpandedNodeId Opc.Ua.DeleteSubscriptionsRequest.XmlEncodingId get
Definition at line 60937 of file Opc.Ua.DataTypes.cs.
The documentation for this class was generated from the following files:
Opc.Ua.Messages.cs
Opc.Ua.DataTypes.cs