Project Template: Opc.Ua.UnregisterNodesRequest Class Reference
Opc.Ua.UnregisterNodesRequest Class Reference
Public Member Functions
UnregisterNodesRequest ()
The default constructor.
virtual void Encode (IEncoder encoder)
virtual void Decode (IDecoder decoder)
virtual bool IsEqual (IEncodeable encodeable)
virtual object Clone ()
new object MemberwiseClone ()
Properties
RequestHeader RequestHeader [get, set]
NodeIdCollection NodesToUnregister [get, set]
virtual ExpandedNodeId TypeId [get]
virtual ExpandedNodeId BinaryEncodingId [get]
virtual ExpandedNodeId XmlEncodingId [get]
Detailed Description
<exclude>
Definition at line 2073 of file Opc.Ua.Messages.cs.
Constructor & Destructor Documentation
UnregisterNodesRequest()
Opc.Ua.UnregisterNodesRequest.UnregisterNodesRequest () inline
The default constructor.
Definition at line 40358 of file Opc.Ua.DataTypes.cs.
Member Function Documentation
Clone()
virtual object Opc.Ua.UnregisterNodesRequest.Clone () inline virtual
Definition at line 40492 of file Opc.Ua.DataTypes.cs.
Decode()
virtual void Opc.Ua.UnregisterNodesRequest.Decode (IDecoder decoder) inline virtual
Definition at line 40459 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
Encode()
virtual void Opc.Ua.UnregisterNodesRequest.Encode (IEncoder encoder) inline virtual
Definition at line 40448 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
IsEqual()
virtual bool Opc.Ua.UnregisterNodesRequest.IsEqual (IEncodeable encodeable) inline virtual
Definition at line 40470 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Object.
MemberwiseClone()
new object Opc.Ua.UnregisterNodesRequest.MemberwiseClone () inline
Definition at line 40499 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.RequestHeader.Clone(), Opc.Ua.UnregisterNodesRequest.MemberwiseClone(), and Opc.Ua.Namespaces.OpcUaXsd.
Referenced by Opc.Ua.UnregisterNodesRequest.MemberwiseClone().
Property Documentation
BinaryEncodingId
virtual ExpandedNodeId Opc.Ua.UnregisterNodesRequest.BinaryEncodingId get
Definition at line 40437 of file Opc.Ua.DataTypes.cs.
NodesToUnregister
NodeIdCollection Opc.Ua.UnregisterNodesRequest.NodesToUnregister get set
Definition at line 40410 of file Opc.Ua.DataTypes.cs.
Referenced by Opc.Ua.SessionClient.BeginUnregisterNodes(), Opc.Ua.SessionClient.EndRegisterNodes(), and Opc.Ua.SessionEndpoint.EndRegisterNodes().
RequestHeader
RequestHeader Opc.Ua.UnregisterNodesRequest.RequestHeader get set
Definition at line 40388 of file Opc.Ua.DataTypes.cs.
Referenced by Opc.Ua.SessionClient.BeginUnregisterNodes(), Opc.Ua.SessionClient.EndRegisterNodes(), and Opc.Ua.SessionEndpoint.EndRegisterNodes().
TypeId
virtual ExpandedNodeId Opc.Ua.UnregisterNodesRequest.TypeId get
Definition at line 40431 of file Opc.Ua.DataTypes.cs.
XmlEncodingId
virtual ExpandedNodeId Opc.Ua.UnregisterNodesRequest.XmlEncodingId get
Definition at line 40443 of file Opc.Ua.DataTypes.cs.
The documentation for this class was generated from the following files:
Opc.Ua.Messages.cs
Opc.Ua.DataTypes.cs