Project Template: Opc.Ua.ReadProcessedDetails Class Reference
Opc.Ua.ReadProcessedDetails Class Reference
Public Member Functions
ReadProcessedDetails ()
The default constructor.
override void Encode (IEncoder encoder)
override void Decode (IDecoder decoder)
override bool IsEqual (IEncodeable encodeable)
override object Clone ()
new object MemberwiseClone ()
Public Member Functions inherited from Opc.Ua.HistoryReadDetails
HistoryReadDetails ()
The default constructor.
new object MemberwiseClone ()
Properties
DateTime StartTime [get, set]
DateTime EndTime [get, set]
double ProcessingInterval [get, set]
NodeIdCollection AggregateType [get, set]
AggregateConfiguration AggregateConfiguration [get, set]
override ExpandedNodeId TypeId [get]
override ExpandedNodeId BinaryEncodingId [get]
override ExpandedNodeId XmlEncodingId [get]
Properties inherited from Opc.Ua.HistoryReadDetails
virtual ExpandedNodeId TypeId [get]
virtual ExpandedNodeId BinaryEncodingId [get]
virtual ExpandedNodeId XmlEncodingId [get]
Detailed Description
<exclude>
Definition at line 46807 of file Opc.Ua.DataTypes.cs.
Constructor & Destructor Documentation
ReadProcessedDetails()
Opc.Ua.ReadProcessedDetails.ReadProcessedDetails () inline
The default constructor.
Definition at line 46813 of file Opc.Ua.DataTypes.cs.
Member Function Documentation
Clone()
override object Opc.Ua.ReadProcessedDetails.Clone () inline virtual
Reimplemented from Opc.Ua.HistoryReadDetails.
Definition at line 46988 of file Opc.Ua.DataTypes.cs.
Decode()
override void Opc.Ua.ReadProcessedDetails.Decode (IDecoder decoder) inline virtual
Reimplemented from Opc.Ua.HistoryReadDetails.
Definition at line 46946 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
Encode()
override void Opc.Ua.ReadProcessedDetails.Encode (IEncoder encoder) inline virtual
Reimplemented from Opc.Ua.HistoryReadDetails.
Definition at line 46930 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
IsEqual()
override bool Opc.Ua.ReadProcessedDetails.IsEqual (IEncodeable encodeable) inline virtual
Reimplemented from Opc.Ua.HistoryReadDetails.
Definition at line 46962 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Object.
MemberwiseClone()
new object Opc.Ua.ReadProcessedDetails.MemberwiseClone () inline
Definition at line 46995 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.AggregateConfiguration.Clone(), Opc.Ua.ReadProcessedDetails.MemberwiseClone(), and Opc.Ua.Namespaces.OpcUaXsd.
Referenced by Opc.Ua.ReadProcessedDetails.MemberwiseClone().
Property Documentation
AggregateConfiguration
AggregateConfiguration Opc.Ua.ReadProcessedDetails.AggregateConfiguration get set
Definition at line 46892 of file Opc.Ua.DataTypes.cs.
AggregateType
NodeIdCollection Opc.Ua.ReadProcessedDetails.AggregateType get set
Definition at line 46870 of file Opc.Ua.DataTypes.cs.
BinaryEncodingId
override ExpandedNodeId Opc.Ua.ReadProcessedDetails.BinaryEncodingId get
Definition at line 46919 of file Opc.Ua.DataTypes.cs.
EndTime
DateTime Opc.Ua.ReadProcessedDetails.EndTime get set
Definition at line 46852 of file Opc.Ua.DataTypes.cs.
ProcessingInterval
double Opc.Ua.ReadProcessedDetails.ProcessingInterval get set
Definition at line 46860 of file Opc.Ua.DataTypes.cs.
StartTime
DateTime Opc.Ua.ReadProcessedDetails.StartTime get set
Definition at line 46844 of file Opc.Ua.DataTypes.cs.
TypeId
override ExpandedNodeId Opc.Ua.ReadProcessedDetails.TypeId get
Definition at line 46913 of file Opc.Ua.DataTypes.cs.
XmlEncodingId
override ExpandedNodeId Opc.Ua.ReadProcessedDetails.XmlEncodingId get
Definition at line 46925 of file Opc.Ua.DataTypes.cs.
The documentation for this class was generated from the following file:
Opc.Ua.DataTypes.cs