Project Template: Sercos.FunctionalGroupState Class Reference
Sercos.FunctionalGroupState Class Reference
Stores an instance of the FunctionalGroupType ObjectType.
Public Member Functions
FunctionalGroupState (NodeState parent)
Initializes the type with its default attribute values.
Protected Member Functions
override NodeId GetDefaultTypeDefinitionId (NamespaceTable namespaceUris)
Returns the id of the default type definition node for the instance.
override void Initialize (ISystemContext context)
Initializes the instance.
override void Initialize (ISystemContext context, NodeState source)
Initializes the instance with a node.
override void InitializeOptionalChildren (ISystemContext context)
Initializes the any option children defined for the instance.
Detailed Description
Stores an instance of the FunctionalGroupType ObjectType.
<exclude>
Definition at line 47 of file Sercos.Classes.cs.
Constructor & Destructor Documentation
FunctionalGroupState()
Sercos.FunctionalGroupState.FunctionalGroupState (NodeState parent) inline
Initializes the type with its default attribute values.
Definition at line 53 of file Sercos.Classes.cs.
Referenced by Sercos.SercosDeviceState.FindChild().
Member Function Documentation
GetDefaultTypeDefinitionId()
override NodeId Sercos.FunctionalGroupState.GetDefaultTypeDefinitionId (NamespaceTable namespaceUris) inline protected
Returns the id of the default type definition node for the instance.
Definition at line 60 of file Sercos.Classes.cs.
References Sercos.ObjectTypes.FunctionalGroupType, Sercos.FunctionalGroupState.Initialize(), Sercos.FunctionalGroupState.InitializeOptionalChildren(), Opc.Ua.NodeId, and Sercos.Namespaces.Sercos.
Initialize() [1/2]
override void Sercos.FunctionalGroupState.Initialize (ISystemContext context) inline protected
Initializes the instance.
Definition at line 69 of file Sercos.Classes.cs.
Referenced by Sercos.FunctionalGroupState.GetDefaultTypeDefinitionId(), Sercos.SercosProfileState.GetDefaultTypeDefinitionId(), Sercos.SercosClassState.GetDefaultTypeDefinitionId(), Sercos.SercosFunctionGroupState.GetDefaultTypeDefinitionId(), Sercos.SercosDeviceState.GetDefaultTypeDefinitionId(), Sercos.ProfileSetState.GetDefaultTypeDefinitionId(), Sercos.ClassSetState.GetDefaultTypeDefinitionId(), Sercos.FunctionGroupSetState.GetDefaultTypeDefinitionId(), and Sercos.SercosParameterState< T >.GetDefaultValueRank().
Initialize() [2/2]
override void Sercos.FunctionalGroupState.Initialize (ISystemContext context, NodeState source) inline protected
Initializes the instance with a node.
Definition at line 78 of file Sercos.Classes.cs.
References Sercos.FunctionalGroupState.InitializeOptionalChildren().
InitializeOptionalChildren()
override void Sercos.FunctionalGroupState.InitializeOptionalChildren (ISystemContext context) inline protected
Initializes the any option children defined for the instance.
Definition at line 87 of file Sercos.Classes.cs.
Referenced by Sercos.FunctionalGroupState.GetDefaultTypeDefinitionId(), Sercos.SercosProfileState.GetDefaultTypeDefinitionId(), Sercos.SercosClassState.GetDefaultTypeDefinitionId(), Sercos.SercosFunctionGroupState.GetDefaultTypeDefinitionId(), Sercos.SercosDeviceState.GetDefaultTypeDefinitionId(), Sercos.ProfileSetState.GetDefaultTypeDefinitionId(), Sercos.ClassSetState.GetDefaultTypeDefinitionId(), Sercos.FunctionGroupSetState.GetDefaultTypeDefinitionId(), Sercos.SercosParameterState< T >.GetDefaultValueRank(), Sercos.FunctionalGroupState.Initialize(), Sercos.SercosProfileState.Initialize(), Sercos.SercosClassState.Initialize(), Sercos.SercosFunctionGroupState.Initialize(), Sercos.SercosDeviceState.Initialize(), Sercos.ProfileSetState.Initialize(), Sercos.ClassSetState.Initialize(), Sercos.FunctionGroupSetState.Initialize(), and Sercos.SercosParameterState< T >.Initialize().
The documentation for this class was generated from the following file:
Sercos.Classes.cs