Project Template: Opc.Ua.DataChangeNotification Class Reference
Opc.Ua.DataChangeNotification Class Reference
Public Member Functions
DataChangeNotification ()
The default constructor.
override void Encode (IEncoder encoder)
override void Decode (IDecoder decoder)
override bool IsEqual (IEncodeable encodeable)
override object Clone ()
new object MemberwiseClone ()
Public Member Functions inherited from Opc.Ua.NotificationData
NotificationData ()
The default constructor.
new object MemberwiseClone ()
Properties
MonitoredItemNotificationCollection MonitoredItems [get, set]
DiagnosticInfoCollection DiagnosticInfos [get, set]
override ExpandedNodeId TypeId [get]
override ExpandedNodeId BinaryEncodingId [get]
override ExpandedNodeId XmlEncodingId [get]
Properties inherited from Opc.Ua.NotificationData
virtual ExpandedNodeId TypeId [get]
virtual ExpandedNodeId BinaryEncodingId [get]
virtual ExpandedNodeId XmlEncodingId [get]
Detailed Description
<exclude>
Definition at line 57984 of file Opc.Ua.DataTypes.cs.
Constructor & Destructor Documentation
DataChangeNotification()
Opc.Ua.DataChangeNotification.DataChangeNotification () inline
The default constructor.
Definition at line 57990 of file Opc.Ua.DataTypes.cs.
Member Function Documentation
Clone()
override object Opc.Ua.DataChangeNotification.Clone () inline virtual
Reimplemented from Opc.Ua.NotificationData.
Definition at line 58129 of file Opc.Ua.DataTypes.cs.
Decode()
override void Opc.Ua.DataChangeNotification.Decode (IDecoder decoder) inline virtual
Reimplemented from Opc.Ua.NotificationData.
Definition at line 58093 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
Encode()
override void Opc.Ua.DataChangeNotification.Encode (IEncoder encoder) inline virtual
Reimplemented from Opc.Ua.NotificationData.
Definition at line 58080 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
IsEqual()
override bool Opc.Ua.DataChangeNotification.IsEqual (IEncodeable encodeable) inline virtual
Reimplemented from Opc.Ua.NotificationData.
Definition at line 58106 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Object.
MemberwiseClone()
new object Opc.Ua.DataChangeNotification.MemberwiseClone () inline
Definition at line 58136 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.MonitoredItemNotificationCollection.Clone(), Opc.Ua.DataChangeNotification.MemberwiseClone(), and Opc.Ua.Namespaces.OpcUaXsd.
Referenced by Opc.Ua.DataChangeNotification.MemberwiseClone().
Property Documentation
BinaryEncodingId
override ExpandedNodeId Opc.Ua.DataChangeNotification.BinaryEncodingId get
Definition at line 58069 of file Opc.Ua.DataTypes.cs.
DiagnosticInfos
DiagnosticInfoCollection Opc.Ua.DataChangeNotification.DiagnosticInfos get set
Definition at line 58042 of file Opc.Ua.DataTypes.cs.
MonitoredItems
MonitoredItemNotificationCollection Opc.Ua.DataChangeNotification.MonitoredItems get set
Definition at line 58020 of file Opc.Ua.DataTypes.cs.
TypeId
override ExpandedNodeId Opc.Ua.DataChangeNotification.TypeId get
Definition at line 58063 of file Opc.Ua.DataTypes.cs.
XmlEncodingId
override ExpandedNodeId Opc.Ua.DataChangeNotification.XmlEncodingId get
Definition at line 58075 of file Opc.Ua.DataTypes.cs.
The documentation for this class was generated from the following file:
Opc.Ua.DataTypes.cs