Project Template: generate_datatypes Namespace Reference
generate_datatypes Namespace Reference
Data Structures
class BuiltinType
class EnumerationType
class OpaqueType
class StructMember
Type Classes #.
class StructType
class Type
class TypeDescription
Parse TypeDescriptions #.
Functions
def getTypeName (xmlTypeName)
def makeCLiteral (value)
def makeCIdentifier (value)
def get_base_type_for_opaque (name)
def getNodeidTypeAndId (nodeId)
def parseTypeDefinitions (outname, xmlDescription, namespace, addToTypes=None)
def parseTypeDescriptions (f, namespaceid)
def merge_dicts (dict_args)
def printh (string)
def printf (string)
def printe (string)
def printc (string)
def iter_types (v)
Variables
types = OrderedDict()
types_imported = OrderedDict()
dictionary typedescriptions = {}
dictionary user_opaque_type_mapping = {}
list excluded_types
list builtin_types
bool isInternalTypes = False
dictionary builtin_overlayable
list whitelistFuncAttrWarnUnusedResult = []
dictionary type_aliases = { "CharArray" : "String" }
parser = argparse.ArgumentParser()
Parse the Command Line Input#.
metavar
type
dest
action
default
help
args = parser.parse_args()
outname = args.outfile.split("/")[-1]
string inname = ', '.join(list(map(lambda x:x.name.split("/")[-1], args.type_bsd)))
outname_import = outname_import.lower()
Create Types #.
file_import
namespace
addToTypes
list selected_types = []
fh = open(args.outfile + "_generated.h", 'w')
Write out the Definitions #.
ff = open(args.outfile + "_generated_handling.h", 'w')
fe = open(args.outfile + "_generated_encoding_binary.h", 'w')
fc = open(args.outfile + "_generated.c",'w')
def filtered_types = iter_types(types)
Print Header #.
Function Documentation
get_base_type_for_opaque()
def generate_datatypes.get_base_type_for_opaque (name)
Definition at line 80 of file generate_datatypes.py.
Referenced by parseTypeDefinitions().
getNodeidTypeAndId()
def generate_datatypes.getNodeidTypeAndId (nodeId)
Definition at line 96 of file generate_datatypes.py.
Referenced by generate_datatypes.Type.datatype_c().
getTypeName()
def generate_datatypes.getTypeName (xmlTypeName)
Definition at line 68 of file generate_datatypes.py.
Referenced by parseTypeDefinitions().
iter_types()
def generate_datatypes.iter_types (v)
Definition at line 568 of file generate_datatypes.py.
References printh(), and type.
makeCIdentifier()
def generate_datatypes.makeCIdentifier (value)
Definition at line 77 of file generate_datatypes.py.
Referenced by generate_datatypes.Type.datatype_c(), generate_datatypes.Type.datatype_ptr(), generate_datatypes.Type.encoding_h(), generate_datatypes.Type.functions_c(), nodeset_compiler.backend_open62541_nodes.generateExtensionObjectSubtypeCode(), nodeset_compiler.backend_open62541_nodes.generateNodeCode_begin(), nodeset_compiler.backend_open62541_nodes.getTypeBrowseName(), nodeset_compiler.backend_open62541_nodes.getTypesArrayForValue(), generate_datatypes.Type.members_c(), generate_datatypes.EnumerationType.typedef_h(), and generate_datatypes.StructType.typedef_h().
makeCLiteral()
def generate_datatypes.makeCLiteral (value)
Definition at line 73 of file generate_datatypes.py.
merge_dicts()
def generate_datatypes.merge_dicts (dict_args)
Given any number of dicts, shallow copy and merge into a new dict,
precedence goes to key value pairs in latter dicts.
Definition at line 438 of file generate_datatypes.py.
parseTypeDefinitions()
def generate_datatypes.parseTypeDefinitions (outname, xmlDescription, namespace, addToTypes = None)
Definition at line 321 of file generate_datatypes.py.
References get_base_type_for_opaque(), and getTypeName().
parseTypeDescriptions()
def generate_datatypes.parseTypeDescriptions (f, namespaceid)
Definition at line 396 of file generate_datatypes.py.
printc()
def generate_datatypes.printc (string)
Definition at line 565 of file generate_datatypes.py.
printe()
def generate_datatypes.printe (string)
Definition at line 563 of file generate_datatypes.py.
printf()
def generate_datatypes.printf (string)
Definition at line 561 of file generate_datatypes.py.
Referenced by main().
printh()
def generate_datatypes.printh (string)
Definition at line 559 of file generate_datatypes.py.
Referenced by iter_types().
Variable Documentation
action
generate_datatypes.action
Definition at line 457 of file generate_datatypes.py.
addToTypes
generate_datatypes.addToTypes
Definition at line 534 of file generate_datatypes.py.
args
generate_datatypes.args = parser.parse_args()
Definition at line 512 of file generate_datatypes.py.
builtin_overlayable
dictionary generate_datatypes.builtin_overlayable
Initial value:
 =  {"Boolean": "true",
                        "SByte": "true", "Byte": "true",
                        "Int16": "UA_BINARY_OVERLAYABLE_INTEGER",
                        "UInt16": "UA_BINARY_OVERLAYABLE_INTEGER",
                        "Int32": "UA_BINARY_OVERLAYABLE_INTEGER",
                        "UInt32": "UA_BINARY_OVERLAYABLE_INTEGER",
                        "Int64": "UA_BINARY_OVERLAYABLE_INTEGER",
                        "UInt64": "UA_BINARY_OVERLAYABLE_INTEGER",
                        "Float": "UA_BINARY_OVERLAYABLE_FLOAT",
                        "Double": "UA_BINARY_OVERLAYABLE_FLOAT",
                        "DateTime": "UA_BINARY_OVERLAYABLE_INTEGER",
                        "StatusCode": "UA_BINARY_OVERLAYABLE_INTEGER",
                        "Guid": "(UA_BINARY_OVERLAYABLE_INTEGER && " +
                        "offsetof(UA_Guid, data2) == sizeof(UA_UInt32) && " +
                        "offsetof(UA_Guid, data3) == (sizeof(UA_UInt16) + sizeof(UA_UInt32)) && " +
                        "offsetof(UA_Guid, data4) == (2*sizeof(UA_UInt32)))"}
Definition at line 47 of file generate_datatypes.py.
builtin_types
list generate_datatypes.builtin_types
Initial value:
 =  ["Boolean", "SByte", "Byte", "Int16", "UInt16", "Int32", "UInt32",
                  "Int64", "UInt64", "Float", "Double", "String", "DateTime", "Guid",
                  "ByteString", "XmlElement", "NodeId", "ExpandedNodeId", "StatusCode",
                  "QualifiedName", "LocalizedText", "ExtensionObject", "DataValue",
                  "Variant", "DiagnosticInfo"]
Definition at line 34 of file generate_datatypes.py.
default
generate_datatypes.default
Definition at line 458 of file generate_datatypes.py.
dest
generate_datatypes.dest
Definition at line 456 of file generate_datatypes.py.
excluded_types
list generate_datatypes.excluded_types
Initial value:
 =  ["NodeIdType", "InstanceNode", "TypeNode", "Node", "ObjectNode",
                   "ObjectTypeNode", "VariableNode", "VariableTypeNode", "ReferenceTypeNode",
                   "MethodNode", "ViewNode", "DataTypeNode",
                   "NumericRange", "NumericRangeDimensions",
                   "UA_ServerDiagnosticsSummaryDataType", "UA_SamplingIntervalDiagnosticsDataType",
                   "UA_SessionSecurityDiagnosticsDataType", "UA_SubscriptionDiagnosticsDataType",
                   "UA_SessionDiagnosticsDataType"]
Definition at line 26 of file generate_datatypes.py.
fc
generate_datatypes.fc = open(args.outfile + "_generated.c",'w')
Definition at line 558 of file generate_datatypes.py.
fe
generate_datatypes.fe = open(args.outfile + "_generated_encoding_binary.h", 'w')
Definition at line 557 of file generate_datatypes.py.
ff
generate_datatypes.ff = open(args.outfile + "_generated_handling.h", 'w')
Definition at line 556 of file generate_datatypes.py.
fh
generate_datatypes.fh = open(args.outfile + "_generated.h", 'w')
Write out the Definitions #.
Definition at line 555 of file generate_datatypes.py.
file_import
generate_datatypes.file_import
Definition at line 530 of file generate_datatypes.py.
filtered_types
def generate_datatypes.filtered_types = iter_types(types)
Print Header #.
Definition at line 603 of file generate_datatypes.py.
help
generate_datatypes.help
Definition at line 459 of file generate_datatypes.py.
inname
string generate_datatypes.inname = ', '.join(list(map(lambda x:x.name.split("/")[-1], args.type_bsd)))
Definition at line 515 of file generate_datatypes.py.
isInternalTypes
generate_datatypes.isInternalTypes = False
Definition at line 41 of file generate_datatypes.py.
metavar
generate_datatypes.metavar
Definition at line 454 of file generate_datatypes.py.
namespace
generate_datatypes.namespace
Definition at line 534 of file generate_datatypes.py.
outname
generate_datatypes.outname = args.outfile.split("/")[-1]
Definition at line 514 of file generate_datatypes.py.
outname_import
generate_datatypes.outname_import = outname_import.lower()
Create Types #.
Definition at line 530 of file generate_datatypes.py.
parser
generate_datatypes.parser = argparse.ArgumentParser()
Parse the Command Line Input#.
Definition at line 452 of file generate_datatypes.py.
selected_types
generate_datatypes.selected_types = []
Definition at line 544 of file generate_datatypes.py.
type
generate_datatypes.type
Definition at line 455 of file generate_datatypes.py.
Referenced by nodeset_compiler.backend_open62541_datatypes.generateNodeValueCode(), iter_types(), and UA_Variant_hasArrayType().
type_aliases
dictionary generate_datatypes.type_aliases = { "CharArray" : "String" }
Definition at line 67 of file generate_datatypes.py.
typedescriptions
def generate_datatypes.typedescriptions = {}
Definition at line 23 of file generate_datatypes.py.
types
generate_datatypes.types = OrderedDict()
Definition at line 21 of file generate_datatypes.py.
types_imported
generate_datatypes.types_imported = OrderedDict()
Definition at line 22 of file generate_datatypes.py.
user_opaque_type_mapping
dictionary generate_datatypes.user_opaque_type_mapping = {}
Definition at line 24 of file generate_datatypes.py.
whitelistFuncAttrWarnUnusedResult
list generate_datatypes.whitelistFuncAttrWarnUnusedResult = []
Definition at line 64 of file generate_datatypes.py.