Project Template: Opc.Ua.DataSetReaderDataType Class Reference
Opc.Ua.DataSetReaderDataType Class Reference
Public Member Functions
DataSetReaderDataType ()
The default constructor.
virtual void Encode (IEncoder encoder)
virtual void Decode (IDecoder decoder)
virtual bool IsEqual (IEncodeable encodeable)
virtual object Clone ()
new object MemberwiseClone ()
Properties
string Name [get, set]
bool Enabled [get, set]
Variant PublisherId [get, set]
ushort WriterGroupId [get, set]
ushort DataSetWriterId [get, set]
DataSetMetaDataType DataSetMetaData [get, set]
uint DataSetFieldContentMask [get, set]
double MessageReceiveTimeout [get, set]
uint KeyFrameCount [get, set]
string HeaderLayoutUri [get, set]
MessageSecurityMode SecurityMode [get, set]
string SecurityGroupId [get, set]
EndpointDescriptionCollection SecurityKeyServices [get, set]
KeyValuePairCollection DataSetReaderProperties [get, set]
ExtensionObject TransportSettings [get, set]
ExtensionObject MessageSettings [get, set]
ExtensionObject SubscribedDataSet [get, set]
virtual ExpandedNodeId TypeId [get]
virtual ExpandedNodeId BinaryEncodingId [get]
virtual ExpandedNodeId XmlEncodingId [get]
Detailed Description
<exclude>
Definition at line 11384 of file Opc.Ua.DataTypes.cs.
Constructor & Destructor Documentation
DataSetReaderDataType()
Opc.Ua.DataSetReaderDataType.DataSetReaderDataType () inline
The default constructor.
Definition at line 11390 of file Opc.Ua.DataTypes.cs.
Member Function Documentation
Clone()
virtual object Opc.Ua.DataSetReaderDataType.Clone () inline virtual
Definition at line 11718 of file Opc.Ua.DataTypes.cs.
Decode()
virtual void Opc.Ua.DataSetReaderDataType.Decode (IDecoder decoder) inline virtual
Definition at line 11655 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.DataSetWriterId, Opc.Ua.Namespaces.OpcUaXsd, Opc.Ua.PublisherId, and Opc.Ua.WriterGroupId.
Encode()
virtual void Opc.Ua.DataSetReaderDataType.Encode (IEncoder encoder) inline virtual
Definition at line 11629 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.DataSetWriterId, Opc.Ua.Namespaces.OpcUaXsd, Opc.Ua.PublisherId, and Opc.Ua.WriterGroupId.
IsEqual()
virtual bool Opc.Ua.DataSetReaderDataType.IsEqual (IEncodeable encodeable) inline virtual
Definition at line 11681 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Object.
MemberwiseClone()
new object Opc.Ua.DataSetReaderDataType.MemberwiseClone () inline
Definition at line 11725 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.KeyValuePairCollection.Clone(), Opc.Ua.DataSetMetaDataType.Clone(), Opc.Ua.EndpointDescriptionCollection.Clone(), Opc.Ua.DataSetReaderDataType.MemberwiseClone(), and Opc.Ua.Namespaces.OpcUaXsd.
Referenced by Opc.Ua.DataSetReaderDataType.MemberwiseClone().
Property Documentation
BinaryEncodingId
virtual ExpandedNodeId Opc.Ua.DataSetReaderDataType.BinaryEncodingId get
Definition at line 11618 of file Opc.Ua.DataTypes.cs.
DataSetFieldContentMask
uint Opc.Ua.DataSetReaderDataType.DataSetFieldContentMask get set
Definition at line 11495 of file Opc.Ua.DataTypes.cs.
DataSetMetaData
DataSetMetaDataType Opc.Ua.DataSetReaderDataType.DataSetMetaData get set
Definition at line 11475 of file Opc.Ua.DataTypes.cs.
DataSetReaderProperties
KeyValuePairCollection Opc.Ua.DataSetReaderDataType.DataSetReaderProperties get set
Definition at line 11567 of file Opc.Ua.DataTypes.cs.
DataSetWriterId
ushort Opc.Ua.DataSetReaderDataType.DataSetWriterId get set
Definition at line 11465 of file Opc.Ua.DataTypes.cs.
Enabled
bool Opc.Ua.DataSetReaderDataType.Enabled get set
Definition at line 11441 of file Opc.Ua.DataTypes.cs.
HeaderLayoutUri
string Opc.Ua.DataSetReaderDataType.HeaderLayoutUri get set
Definition at line 11519 of file Opc.Ua.DataTypes.cs.
KeyFrameCount
uint Opc.Ua.DataSetReaderDataType.KeyFrameCount get set
Definition at line 11511 of file Opc.Ua.DataTypes.cs.
MessageReceiveTimeout
double Opc.Ua.DataSetReaderDataType.MessageReceiveTimeout get set
Definition at line 11503 of file Opc.Ua.DataTypes.cs.
MessageSettings
ExtensionObject Opc.Ua.DataSetReaderDataType.MessageSettings get set
Definition at line 11595 of file Opc.Ua.DataTypes.cs.
Name
string Opc.Ua.DataSetReaderDataType.Name get set
Definition at line 11433 of file Opc.Ua.DataTypes.cs.
PublisherId
Variant Opc.Ua.DataSetReaderDataType.PublisherId get set
Definition at line 11449 of file Opc.Ua.DataTypes.cs.
SecurityGroupId
string Opc.Ua.DataSetReaderDataType.SecurityGroupId get set
Definition at line 11535 of file Opc.Ua.DataTypes.cs.
SecurityKeyServices
EndpointDescriptionCollection Opc.Ua.DataSetReaderDataType.SecurityKeyServices get set
Definition at line 11545 of file Opc.Ua.DataTypes.cs.
SecurityMode
MessageSecurityMode Opc.Ua.DataSetReaderDataType.SecurityMode get set
Definition at line 11527 of file Opc.Ua.DataTypes.cs.
SubscribedDataSet
ExtensionObject Opc.Ua.DataSetReaderDataType.SubscribedDataSet get set
Definition at line 11603 of file Opc.Ua.DataTypes.cs.
TransportSettings
ExtensionObject Opc.Ua.DataSetReaderDataType.TransportSettings get set
Definition at line 11587 of file Opc.Ua.DataTypes.cs.
TypeId
virtual ExpandedNodeId Opc.Ua.DataSetReaderDataType.TypeId get
Definition at line 11612 of file Opc.Ua.DataTypes.cs.
WriterGroupId
ushort Opc.Ua.DataSetReaderDataType.WriterGroupId get set
Definition at line 11457 of file Opc.Ua.DataTypes.cs.
XmlEncodingId
virtual ExpandedNodeId Opc.Ua.DataSetReaderDataType.XmlEncodingId get
Definition at line 11624 of file Opc.Ua.DataTypes.cs.
The documentation for this class was generated from the following file:
Opc.Ua.DataTypes.cs