Project Template: Opc.Ua.OpenSecureChannelRequest Class Reference
Opc.Ua.OpenSecureChannelRequest Class Reference
Public Member Functions
OpenSecureChannelRequest ()
The default constructor.
virtual void Encode (IEncoder encoder)
virtual void Decode (IDecoder decoder)
virtual bool IsEqual (IEncodeable encodeable)
virtual object Clone ()
new object MemberwiseClone ()
Properties
RequestHeader RequestHeader [get, set]
uint ClientProtocolVersion [get, set]
SecurityTokenRequestType RequestType [get, set]
MessageSecurityMode SecurityMode [get, set]
byte [] ClientNonce [get, set]
uint RequestedLifetime [get, set]
virtual ExpandedNodeId TypeId [get]
virtual ExpandedNodeId BinaryEncodingId [get]
virtual ExpandedNodeId XmlEncodingId [get]
Detailed Description
<exclude>
Definition at line 575 of file Opc.Ua.Messages.cs.
Constructor & Destructor Documentation
OpenSecureChannelRequest()
Opc.Ua.OpenSecureChannelRequest.OpenSecureChannelRequest () inline
The default constructor.
Definition at line 28111 of file Opc.Ua.DataTypes.cs.
Member Function Documentation
Clone()
virtual object Opc.Ua.OpenSecureChannelRequest.Clone () inline virtual
Definition at line 28279 of file Opc.Ua.DataTypes.cs.
Decode()
virtual void Opc.Ua.OpenSecureChannelRequest.Decode (IDecoder decoder) inline virtual
Definition at line 28238 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
Encode()
virtual void Opc.Ua.OpenSecureChannelRequest.Encode (IEncoder encoder) inline virtual
Definition at line 28223 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
IsEqual()
virtual bool Opc.Ua.OpenSecureChannelRequest.IsEqual (IEncodeable encodeable) inline virtual
Definition at line 28253 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Object.
MemberwiseClone()
new object Opc.Ua.OpenSecureChannelRequest.MemberwiseClone () inline
Definition at line 28286 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.RequestHeader.Clone(), Opc.Ua.OpenSecureChannelRequest.MemberwiseClone(), and Opc.Ua.Namespaces.OpcUaXsd.
Referenced by Opc.Ua.OpenSecureChannelRequest.MemberwiseClone().
Property Documentation
BinaryEncodingId
virtual ExpandedNodeId Opc.Ua.OpenSecureChannelRequest.BinaryEncodingId get
Definition at line 28212 of file Opc.Ua.DataTypes.cs.
ClientNonce
byte [] Opc.Ua.OpenSecureChannelRequest.ClientNonce get set
Definition at line 28189 of file Opc.Ua.DataTypes.cs.
ClientProtocolVersion
uint Opc.Ua.OpenSecureChannelRequest.ClientProtocolVersion get set
Definition at line 28165 of file Opc.Ua.DataTypes.cs.
RequestedLifetime
uint Opc.Ua.OpenSecureChannelRequest.RequestedLifetime get set
Definition at line 28197 of file Opc.Ua.DataTypes.cs.
RequestHeader
RequestHeader Opc.Ua.OpenSecureChannelRequest.RequestHeader get set
Definition at line 28145 of file Opc.Ua.DataTypes.cs.
RequestType
SecurityTokenRequestType Opc.Ua.OpenSecureChannelRequest.RequestType get set
Definition at line 28173 of file Opc.Ua.DataTypes.cs.
SecurityMode
MessageSecurityMode Opc.Ua.OpenSecureChannelRequest.SecurityMode get set
Definition at line 28181 of file Opc.Ua.DataTypes.cs.
TypeId
virtual ExpandedNodeId Opc.Ua.OpenSecureChannelRequest.TypeId get
Definition at line 28206 of file Opc.Ua.DataTypes.cs.
XmlEncodingId
virtual ExpandedNodeId Opc.Ua.OpenSecureChannelRequest.XmlEncodingId get
Definition at line 28218 of file Opc.Ua.DataTypes.cs.
The documentation for this class was generated from the following files:
Opc.Ua.Messages.cs
Opc.Ua.DataTypes.cs