Project Template: client_subscriptions.h File Reference
client_subscriptions.h File Reference
Typedefs
typedef void(* UA_Client_StatusChangeNotificationCallback) (UA_Client *client, UA_UInt32 subId, void *subContext, UA_StatusChangeNotification *notification)
typedef void(* UA_Client_DeleteMonitoredItemCallback) (UA_Client *client, UA_UInt32 subId, void *subContext, UA_UInt32 monId, void *monContext)
typedef void(* UA_Client_DataChangeNotificationCallback) (UA_Client *client, UA_UInt32 subId, void *subContext, UA_UInt32 monId, void *monContext, UA_DataValue *value)
typedef void(* UA_Client_EventNotificationCallback) (UA_Client *client, UA_UInt32 subId, void *subContext, UA_UInt32 monId, void *monContext, size_t nEventFields, UA_Variant *eventFields)
Functions
static UA_INLINE UA_CreateSubscriptionRequest UA_CreateSubscriptionRequest_default (void)
UA_CreateSubscriptionResponse UA_EXPORT UA_Client_Subscriptions_create (UA_Client *client, const UA_CreateSubscriptionRequest request, void *subscriptionContext, UA_Client_StatusChangeNotificationCallback statusChangeCallback, UA_Client_DeleteSubscriptionCallback deleteCallback)
UA_ModifySubscriptionResponse UA_EXPORT UA_Client_Subscriptions_modify (UA_Client *client, const UA_ModifySubscriptionRequest request)
UA_DeleteSubscriptionsResponse UA_EXPORT UA_Client_Subscriptions_delete (UA_Client *client, const UA_DeleteSubscriptionsRequest request)
UA_StatusCode UA_EXPORT UA_Client_Subscriptions_deleteSingle (UA_Client *client, UA_UInt32 subscriptionId)
static UA_INLINE UA_SetPublishingModeResponse UA_Client_Subscriptions_setPublishingMode (UA_Client *client, const UA_SetPublishingModeRequest request)
static UA_INLINE UA_MonitoredItemCreateRequest UA_MonitoredItemCreateRequest_default (UA_NodeId nodeId)
UA_CreateMonitoredItemsResponse UA_EXPORT UA_Client_MonitoredItems_createDataChanges (UA_Client *client, const UA_CreateMonitoredItemsRequest request, void **contexts, UA_Client_DataChangeNotificationCallback *callbacks, UA_Client_DeleteMonitoredItemCallback *deleteCallbacks)
UA_MonitoredItemCreateResult UA_EXPORT UA_Client_MonitoredItems_createDataChange (UA_Client *client, UA_UInt32 subscriptionId, UA_TimestampsToReturn timestampsToReturn, const UA_MonitoredItemCreateRequest item, void *context, UA_Client_DataChangeNotificationCallback callback, UA_Client_DeleteMonitoredItemCallback deleteCallback)
UA_CreateMonitoredItemsResponse UA_EXPORT UA_Client_MonitoredItems_createEvents (UA_Client *client, const UA_CreateMonitoredItemsRequest request, void **contexts, UA_Client_EventNotificationCallback *callback, UA_Client_DeleteMonitoredItemCallback *deleteCallback)
UA_MonitoredItemCreateResult UA_EXPORT UA_Client_MonitoredItems_createEvent (UA_Client *client, UA_UInt32 subscriptionId, UA_TimestampsToReturn timestampsToReturn, const UA_MonitoredItemCreateRequest item, void *context, UA_Client_EventNotificationCallback callback, UA_Client_DeleteMonitoredItemCallback deleteCallback)
UA_DeleteMonitoredItemsResponse UA_EXPORT UA_Client_MonitoredItems_delete (UA_Client *client, const UA_DeleteMonitoredItemsRequest)
UA_StatusCode UA_EXPORT UA_Client_MonitoredItems_deleteSingle (UA_Client *client, UA_UInt32 subscriptionId, UA_UInt32 monitoredItemId)
UA_ModifyMonitoredItemsResponse UA_EXPORT UA_Client_MonitoredItems_modify (UA_Client *client, const UA_ModifyMonitoredItemsRequest request)
static UA_INLINE UA_SetMonitoringModeResponse UA_Client_MonitoredItems_setMonitoringMode (UA_Client *client, const UA_SetMonitoringModeRequest request)
static UA_INLINE UA_SetTriggeringResponse UA_Client_MonitoredItems_setTriggering (UA_Client *client, const UA_SetTriggeringRequest request)
Variables
_UA_BEGIN_DECLS typedef void(* UA_Client_DeleteSubscriptionCallback)(UA_Client *client, UA_UInt32 subId, void *subContext)
Typedef Documentation
UA_Client_DataChangeNotificationCallback
typedef void(* UA_Client_DataChangeNotificationCallback) (UA_Client *client, UA_UInt32 subId, void *subContext, UA_UInt32 monId, void *monContext, UA_DataValue *value)
Definition at line 130 of file client_subscriptions.h.
UA_Client_DeleteMonitoredItemCallback
typedef void(* UA_Client_DeleteMonitoredItemCallback) (UA_Client *client, UA_UInt32 subId, void *subContext, UA_UInt32 monId, void *monContext)
The clientHandle parameter can't be set by the user, any value will be replaced by the client before sending the request to the server.
Definition at line 125 of file client_subscriptions.h.
UA_Client_EventNotificationCallback
typedef void(* UA_Client_EventNotificationCallback) (UA_Client *client, UA_UInt32 subId, void *subContext, UA_UInt32 monId, void *monContext, size_t nEventFields, UA_Variant *eventFields)
Definition at line 136 of file client_subscriptions.h.
UA_Client_StatusChangeNotificationCallback
typedef void(* UA_Client_StatusChangeNotificationCallback) (UA_Client *client, UA_UInt32 subId, void *subContext, UA_StatusChangeNotification *notification)
Definition at line 40 of file client_subscriptions.h.
Function Documentation
UA_Client_MonitoredItems_createDataChange()
UA_MonitoredItemCreateResult UA_EXPORT UA_Client_MonitoredItems_createDataChange (UA_Client * client, UA_UInt32 subscriptionId, UA_TimestampsToReturn timestampsToReturn, const UA_MonitoredItemCreateRequest item, void * context, UA_Client_DataChangeNotificationCallback callback, UA_Client_DeleteMonitoredItemCallback deleteCallback)
UA_Client_MonitoredItems_createDataChanges()
UA_CreateMonitoredItemsResponse UA_EXPORT UA_Client_MonitoredItems_createDataChanges (UA_Client * client, const UA_CreateMonitoredItemsRequest request, void ** contexts, UA_Client_DataChangeNotificationCallback * callbacks, UA_Client_DeleteMonitoredItemCallback * deleteCallbacks)
UA_Client_MonitoredItems_createEvent()
UA_MonitoredItemCreateResult UA_EXPORT UA_Client_MonitoredItems_createEvent (UA_Client * client, UA_UInt32 subscriptionId, UA_TimestampsToReturn timestampsToReturn, const UA_MonitoredItemCreateRequest item, void * context, UA_Client_EventNotificationCallback callback, UA_Client_DeleteMonitoredItemCallback deleteCallback)
UA_Client_MonitoredItems_createEvents()
UA_CreateMonitoredItemsResponse UA_EXPORT UA_Client_MonitoredItems_createEvents (UA_Client * client, const UA_CreateMonitoredItemsRequest request, void ** contexts, UA_Client_EventNotificationCallback * callback, UA_Client_DeleteMonitoredItemCallback * deleteCallback)
UA_Client_MonitoredItems_delete()
UA_DeleteMonitoredItemsResponse UA_EXPORT UA_Client_MonitoredItems_delete (UA_Client * client, const UA_DeleteMonitoredItemsRequest)
UA_Client_MonitoredItems_deleteSingle()
UA_StatusCode UA_EXPORT UA_Client_MonitoredItems_deleteSingle (UA_Client * client, UA_UInt32 subscriptionId, UA_UInt32 monitoredItemId)
UA_Client_MonitoredItems_modify()
UA_ModifyMonitoredItemsResponse UA_EXPORT UA_Client_MonitoredItems_modify (UA_Client * client, const UA_ModifyMonitoredItemsRequest request)
UA_Client_MonitoredItems_setMonitoringMode()
static UA_INLINE UA_SetMonitoringModeResponse UA_Client_MonitoredItems_setMonitoringMode (UA_Client * client, const UA_SetMonitoringModeRequest request) static
The following service calls go directly to the server. The MonitoredItem settings are not stored in the client.
Definition at line 182 of file client_subscriptions.h.
References __UA_Client_Service(), and UA_TYPES.
UA_Client_MonitoredItems_setTriggering()
static UA_INLINE UA_SetTriggeringResponse UA_Client_MonitoredItems_setTriggering (UA_Client * client, const UA_SetTriggeringRequest request) static
Definition at line 192 of file client_subscriptions.h.
References __UA_Client_Service(), and UA_TYPES.
UA_Client_Subscriptions_create()
UA_CreateSubscriptionResponse UA_EXPORT UA_Client_Subscriptions_create (UA_Client * client, const UA_CreateSubscriptionRequest request, void * subscriptionContext, UA_Client_StatusChangeNotificationCallback statusChangeCallback, UA_Client_DeleteSubscriptionCallback deleteCallback)
Referenced by UA_CreateSubscriptionRequest_default().
UA_Client_Subscriptions_delete()
UA_DeleteSubscriptionsResponse UA_EXPORT UA_Client_Subscriptions_delete (UA_Client * client, const UA_DeleteSubscriptionsRequest request)
Referenced by UA_CreateSubscriptionRequest_default().
UA_Client_Subscriptions_deleteSingle()
UA_StatusCode UA_EXPORT UA_Client_Subscriptions_deleteSingle (UA_Client * client, UA_UInt32 subscriptionId)
Referenced by UA_CreateSubscriptionRequest_default().
UA_Client_Subscriptions_modify()
UA_ModifySubscriptionResponse UA_EXPORT UA_Client_Subscriptions_modify (UA_Client * client, const UA_ModifySubscriptionRequest request)
Referenced by UA_CreateSubscriptionRequest_default().
UA_Client_Subscriptions_setPublishingMode()
static UA_INLINE UA_SetPublishingModeResponse UA_Client_Subscriptions_setPublishingMode (UA_Client * client, const UA_SetPublishingModeRequest request) static
Definition at line 84 of file client_subscriptions.h.
References __UA_Client_Service(), and UA_TYPES.
UA_CreateSubscriptionRequest_default()
static UA_INLINE UA_CreateSubscriptionRequest UA_CreateSubscriptionRequest_default (void) static
Definition at line 52 of file client_subscriptions.h.
References UA_CreateSubscriptionRequest::maxNotificationsPerPublish, UA_CreateSubscriptionRequest::priority, UA_CreateSubscriptionRequest::publishingEnabled, UA_CreateSubscriptionRequest::requestedLifetimeCount, UA_CreateSubscriptionRequest::requestedMaxKeepAliveCount, UA_CreateSubscriptionRequest::requestedPublishingInterval, UA_Client_DeleteSubscriptionCallback, UA_Client_Subscriptions_create(), UA_Client_Subscriptions_delete(), UA_Client_Subscriptions_deleteSingle(), UA_Client_Subscriptions_modify(), and UA_CreateSubscriptionRequest_init().
UA_MonitoredItemCreateRequest_default()
static UA_INLINE UA_MonitoredItemCreateRequest UA_MonitoredItemCreateRequest_default (UA_NodeId nodeId) static
MonitoredItems
MonitoredItems for Events indicate the EventNotifier attribute. This indicates to the server not to monitor changes of the attribute, but to forward Event notifications from that node.
During the creation of a MonitoredItem, the server may return changed adjusted parameters. Check the returned UA_CreateMonitoredItemsResponse to get the current parameters.
Definition at line 107 of file client_subscriptions.h.
References UA_ReadValueId::attributeId, UA_MonitoringParameters::discardOldest, UA_MonitoredItemCreateRequest::itemToMonitor, UA_MonitoredItemCreateRequest::monitoringMode, UA_ReadValueId::nodeId, UA_MonitoringParameters::queueSize, UA_MonitoredItemCreateRequest::requestedParameters, UA_MonitoringParameters::samplingInterval, UA_ATTRIBUTEID_VALUE, UA_MonitoredItemCreateRequest_init(), and UA_MONITORINGMODE_REPORTING.
Variable Documentation
UA_Client_DeleteSubscriptionCallback
_UA_BEGIN_DECLS typedef void(* UA_Client_DeleteSubscriptionCallback) (UA_Client *client, UA_UInt32 subId, void *subContext)
.. _client-subscriptions:
Subscriptions
Subscriptions in OPC UA are asynchronous. That is, the client sends several PublishRequests to the server. The server returns PublishResponses with notifications. But only when a notification has been generated. The client does not wait for the responses and continues normal operations.
Note the difference between Subscriptions and MonitoredItems. Subscriptions are used to report back notifications. MonitoredItems are used to generate notifications. Every MonitoredItem is attached to exactly one Subscription. And a Subscription can contain many MonitoredItems.
The client automatically processes PublishResponses (with a callback) in the background and keeps enough PublishRequests in transit. The PublishResponses may be recieved during a synchronous service call or in UA_Client_runAsync.
Definition at line 37 of file client_subscriptions.h.
Referenced by UA_CreateSubscriptionRequest_default().