Project Template: nodeset_compiler.nodeset Namespace Reference
nodeset_compiler.nodeset Namespace Reference
Data Structures
class NodeSet
Functions
def unicode (s)
def getSubTypesOf (nodeset, node, skipNodes=[])
def extractNamespaces (xmlfile)
def buildAliasList (xmlelement)
Variables
logger = logging.getLogger(__name__)
string_types = str
hassubtype = NodeId("ns=0;i=45")
Helper Functions #.
Function Documentation
buildAliasList()
def nodeset_compiler.nodeset.buildAliasList (xmlelement)
Parses the <Alias> XML Element present in must XML NodeSet definitions.
   Contents the Alias element are stored in a dictionary for further
   dereferencing during pointer linkage (see linkOpenPointer()).
Definition at line 95 of file nodeset.py.
References nodeset_compiler.nodeset.unicode().
Referenced by nodeset_compiler.nodeset.NodeSet.addNodeSet().
extractNamespaces()
def nodeset_compiler.nodeset.extractNamespaces (xmlfile)
Definition at line 63 of file nodeset.py.
Referenced by nodeset_compiler.nodeset.NodeSet.addNodeSet().
getSubTypesOf()
def nodeset_compiler.nodeset.getSubTypesOf (nodeset, node, skipNodes = [])
Definition at line 47 of file nodeset.py.
Referenced by nodeset_compiler.nodeset.NodeSet.getRelevantOrderingReferences(), and nodeset_compiler.nodeset.NodeSet.setNodeParent().
unicode()
def nodeset_compiler.nodeset.unicode (s)
Definition at line 35 of file nodeset.py.
Referenced by nodeset_compiler.nodeset.buildAliasList().
Variable Documentation
hassubtype
nodeset_compiler.nodeset.hassubtype = NodeId("ns=0;i=45")
Helper Functions #.
Definition at line 45 of file nodeset.py.
logger
nodeset_compiler.nodeset.logger = logging.getLogger(__name__)
Definition at line 31 of file nodeset.py.
string_types
nodeset_compiler.nodeset.string_types = str
Definition at line 37 of file nodeset.py.