Project Template: Opc.Ua.PublishedDataItemsDataType Class Reference
Opc.Ua.PublishedDataItemsDataType Class Reference
Public Member Functions
PublishedDataItemsDataType ()
The default constructor.
override void Encode (IEncoder encoder)
override void Decode (IDecoder decoder)
override bool IsEqual (IEncodeable encodeable)
override object Clone ()
new object MemberwiseClone ()
Public Member Functions inherited from Opc.Ua.PublishedDataSetSourceDataType
PublishedDataSetSourceDataType ()
The default constructor.
new object MemberwiseClone ()
Properties
PublishedVariableDataTypeCollection PublishedData [get, set]
override ExpandedNodeId TypeId [get]
override ExpandedNodeId BinaryEncodingId [get]
override ExpandedNodeId XmlEncodingId [get]
Properties inherited from Opc.Ua.PublishedDataSetSourceDataType
virtual ExpandedNodeId TypeId [get]
virtual ExpandedNodeId BinaryEncodingId [get]
virtual ExpandedNodeId XmlEncodingId [get]
Detailed Description
<exclude>
Definition at line 7208 of file Opc.Ua.DataTypes.cs.
Constructor & Destructor Documentation
PublishedDataItemsDataType()
Opc.Ua.PublishedDataItemsDataType.PublishedDataItemsDataType () inline
The default constructor.
Definition at line 7214 of file Opc.Ua.DataTypes.cs.
Member Function Documentation
Clone()
override object Opc.Ua.PublishedDataItemsDataType.Clone () inline virtual
Reimplemented from Opc.Ua.PublishedDataSetSourceDataType.
Definition at line 7327 of file Opc.Ua.DataTypes.cs.
Decode()
override void Opc.Ua.PublishedDataItemsDataType.Decode (IDecoder decoder) inline virtual
Reimplemented from Opc.Ua.PublishedDataSetSourceDataType.
Definition at line 7293 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
Encode()
override void Opc.Ua.PublishedDataItemsDataType.Encode (IEncoder encoder) inline virtual
Reimplemented from Opc.Ua.PublishedDataSetSourceDataType.
Definition at line 7281 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
IsEqual()
override bool Opc.Ua.PublishedDataItemsDataType.IsEqual (IEncodeable encodeable) inline virtual
Reimplemented from Opc.Ua.PublishedDataSetSourceDataType.
Definition at line 7305 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Object.
MemberwiseClone()
new object Opc.Ua.PublishedDataItemsDataType.MemberwiseClone () inline
Definition at line 7334 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.PublishedVariableDataTypeCollection.Clone(), Opc.Ua.PublishedDataItemsDataType.MemberwiseClone(), and Opc.Ua.Namespaces.OpcUaXsd.
Referenced by Opc.Ua.PublishedDataItemsDataType.MemberwiseClone().
Property Documentation
BinaryEncodingId
override ExpandedNodeId Opc.Ua.PublishedDataItemsDataType.BinaryEncodingId get
Definition at line 7270 of file Opc.Ua.DataTypes.cs.
PublishedData
PublishedVariableDataTypeCollection Opc.Ua.PublishedDataItemsDataType.PublishedData get set
Definition at line 7243 of file Opc.Ua.DataTypes.cs.
TypeId
override ExpandedNodeId Opc.Ua.PublishedDataItemsDataType.TypeId get
Definition at line 7264 of file Opc.Ua.DataTypes.cs.
XmlEncodingId
override ExpandedNodeId Opc.Ua.PublishedDataItemsDataType.XmlEncodingId get
Definition at line 7276 of file Opc.Ua.DataTypes.cs.
The documentation for this class was generated from the following file:
Opc.Ua.DataTypes.cs