Project Template: Opc.Ua.WriteRequest Class Reference
Opc.Ua.WriteRequest Class Reference
Public Member Functions
WriteRequest ()
The default constructor.
virtual void Encode (IEncoder encoder)
virtual void Decode (IDecoder decoder)
virtual bool IsEqual (IEncodeable encodeable)
virtual object Clone ()
new object MemberwiseClone ()
Properties
RequestHeader RequestHeader [get, set]
WriteValueCollection NodesToWrite [get, set]
virtual ExpandedNodeId TypeId [get]
virtual ExpandedNodeId BinaryEncodingId [get]
virtual ExpandedNodeId XmlEncodingId [get]
Detailed Description
<exclude>
Definition at line 2608 of file Opc.Ua.Messages.cs.
Constructor & Destructor Documentation
WriteRequest()
Opc.Ua.WriteRequest.WriteRequest () inline
The default constructor.
Definition at line 48564 of file Opc.Ua.DataTypes.cs.
Member Function Documentation
Clone()
virtual object Opc.Ua.WriteRequest.Clone () inline virtual
Definition at line 48698 of file Opc.Ua.DataTypes.cs.
Decode()
virtual void Opc.Ua.WriteRequest.Decode (IDecoder decoder) inline virtual
Definition at line 48665 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
Encode()
virtual void Opc.Ua.WriteRequest.Encode (IEncoder encoder) inline virtual
Definition at line 48654 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
IsEqual()
virtual bool Opc.Ua.WriteRequest.IsEqual (IEncodeable encodeable) inline virtual
Definition at line 48676 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Object.
MemberwiseClone()
new object Opc.Ua.WriteRequest.MemberwiseClone () inline
Definition at line 48705 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.RequestHeader.Clone(), Opc.Ua.WriteValueCollection.Clone(), Opc.Ua.WriteRequest.MemberwiseClone(), and Opc.Ua.Namespaces.OpcUaXsd.
Referenced by Opc.Ua.WriteRequest.MemberwiseClone().
Property Documentation
BinaryEncodingId
virtual ExpandedNodeId Opc.Ua.WriteRequest.BinaryEncodingId get
Definition at line 48643 of file Opc.Ua.DataTypes.cs.
NodesToWrite
WriteValueCollection Opc.Ua.WriteRequest.NodesToWrite get set
Definition at line 48616 of file Opc.Ua.DataTypes.cs.
Referenced by Opc.Ua.SessionClient.BeginWrite(), Opc.Ua.SessionEndpoint.EndHistoryRead(), and Opc.Ua.SessionClient.EndHistoryRead().
RequestHeader
RequestHeader Opc.Ua.WriteRequest.RequestHeader get set
Definition at line 48594 of file Opc.Ua.DataTypes.cs.
Referenced by Opc.Ua.SessionClient.BeginWrite(), Opc.Ua.SessionEndpoint.EndHistoryRead(), and Opc.Ua.SessionClient.EndHistoryRead().
TypeId
virtual ExpandedNodeId Opc.Ua.WriteRequest.TypeId get
Definition at line 48637 of file Opc.Ua.DataTypes.cs.
XmlEncodingId
virtual ExpandedNodeId Opc.Ua.WriteRequest.XmlEncodingId get
Definition at line 48649 of file Opc.Ua.DataTypes.cs.
The documentation for this class was generated from the following files:
Opc.Ua.Messages.cs
Opc.Ua.DataTypes.cs