Project Template: Opc.Ua.Fdi5.RegistrationParameters Class Reference
Opc.Ua.Fdi5.RegistrationParameters Class Reference
Public Member Functions
RegistrationParameters ()
The default constructor.
virtual void Encode (IEncoder encoder)
virtual void Decode (IDecoder decoder)
virtual bool IsEqual (IEncodeable encodeable)
virtual object Clone ()
new object MemberwiseClone ()
Properties
RelativePath Path [get, set]
uint SelectionFlags [get, set]
virtual ExpandedNodeId TypeId [get]
virtual ExpandedNodeId BinaryEncodingId [get]
virtual ExpandedNodeId XmlEncodingId [get]
Detailed Description
<exclude>
Definition at line 264 of file Opc.Ua.Fdi5.DataTypes.cs.
Constructor & Destructor Documentation
RegistrationParameters()
Opc.Ua.Fdi5.RegistrationParameters.RegistrationParameters () inline
The default constructor.
Definition at line 270 of file Opc.Ua.Fdi5.DataTypes.cs.
Member Function Documentation
Clone()
virtual object Opc.Ua.Fdi5.RegistrationParameters.Clone () inline virtual
Definition at line 390 of file Opc.Ua.Fdi5.DataTypes.cs.
Decode()
virtual void Opc.Ua.Fdi5.RegistrationParameters.Decode (IDecoder decoder) inline virtual
Definition at line 357 of file Opc.Ua.Fdi5.DataTypes.cs.
References Opc.Ua.Fdi5.Namespaces.OpcUaFdi5Xsd.
Encode()
virtual void Opc.Ua.Fdi5.RegistrationParameters.Encode (IEncoder encoder) inline virtual
Definition at line 346 of file Opc.Ua.Fdi5.DataTypes.cs.
References Opc.Ua.Fdi5.Namespaces.OpcUaFdi5Xsd.
IsEqual()
virtual bool Opc.Ua.Fdi5.RegistrationParameters.IsEqual (IEncodeable encodeable) inline virtual
Definition at line 368 of file Opc.Ua.Fdi5.DataTypes.cs.
References Opc.Ua.Object.
MemberwiseClone()
new object Opc.Ua.Fdi5.RegistrationParameters.MemberwiseClone () inline
Definition at line 397 of file Opc.Ua.Fdi5.DataTypes.cs.
References Opc.Ua.RelativePath.Clone(), Opc.Ua.Fdi5.RegistrationParameters.MemberwiseClone(), and Opc.Ua.Fdi5.Namespaces.OpcUaFdi5Xsd.
Referenced by Opc.Ua.Fdi5.RegistrationParameters.MemberwiseClone().
Property Documentation
BinaryEncodingId
virtual ExpandedNodeId Opc.Ua.Fdi5.RegistrationParameters.BinaryEncodingId get
Definition at line 335 of file Opc.Ua.Fdi5.DataTypes.cs.
Path
RelativePath Opc.Ua.Fdi5.RegistrationParameters.Path get set
Definition at line 300 of file Opc.Ua.Fdi5.DataTypes.cs.
SelectionFlags
uint Opc.Ua.Fdi5.RegistrationParameters.SelectionFlags get set
Definition at line 320 of file Opc.Ua.Fdi5.DataTypes.cs.
TypeId
virtual ExpandedNodeId Opc.Ua.Fdi5.RegistrationParameters.TypeId get
Definition at line 329 of file Opc.Ua.Fdi5.DataTypes.cs.
XmlEncodingId
virtual ExpandedNodeId Opc.Ua.Fdi5.RegistrationParameters.XmlEncodingId get
Definition at line 341 of file Opc.Ua.Fdi5.DataTypes.cs.
The documentation for this class was generated from the following file:
Opc.Ua.Fdi5.DataTypes.cs