Project Template: Opc.Ua.ConfigurationVersionDataType Class Reference
Opc.Ua.ConfigurationVersionDataType Class Reference
Public Member Functions
ConfigurationVersionDataType ()
The default constructor.
virtual void Encode (IEncoder encoder)
virtual void Decode (IDecoder decoder)
virtual bool IsEqual (IEncodeable encodeable)
virtual object Clone ()
new object MemberwiseClone ()
Properties
uint MajorVersion [get, set]
uint MinorVersion [get, set]
virtual ExpandedNodeId TypeId [get]
virtual ExpandedNodeId BinaryEncodingId [get]
virtual ExpandedNodeId XmlEncodingId [get]
Detailed Description
<exclude>
Definition at line 6129 of file Opc.Ua.DataTypes.cs.
Constructor & Destructor Documentation
ConfigurationVersionDataType()
Opc.Ua.ConfigurationVersionDataType.ConfigurationVersionDataType () inline
The default constructor.
Definition at line 6135 of file Opc.Ua.DataTypes.cs.
Member Function Documentation
Clone()
virtual object Opc.Ua.ConfigurationVersionDataType.Clone () inline virtual
Definition at line 6241 of file Opc.Ua.DataTypes.cs.
Referenced by Opc.Ua.DataSetMetaDataType.MemberwiseClone().
Decode()
virtual void Opc.Ua.ConfigurationVersionDataType.Decode (IDecoder decoder) inline virtual
Definition at line 6208 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.MajorVersion, Opc.Ua.MinorVersion, and Opc.Ua.Namespaces.OpcUaXsd.
Encode()
virtual void Opc.Ua.ConfigurationVersionDataType.Encode (IEncoder encoder) inline virtual
Definition at line 6197 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.MajorVersion, Opc.Ua.MinorVersion, and Opc.Ua.Namespaces.OpcUaXsd.
IsEqual()
virtual bool Opc.Ua.ConfigurationVersionDataType.IsEqual (IEncodeable encodeable) inline virtual
Definition at line 6219 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Object.
MemberwiseClone()
new object Opc.Ua.ConfigurationVersionDataType.MemberwiseClone () inline
Definition at line 6248 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.ConfigurationVersionDataType.MemberwiseClone(), and Opc.Ua.Namespaces.OpcUaXsd.
Referenced by Opc.Ua.ConfigurationVersionDataType.MemberwiseClone().
Property Documentation
BinaryEncodingId
virtual ExpandedNodeId Opc.Ua.ConfigurationVersionDataType.BinaryEncodingId get
Definition at line 6186 of file Opc.Ua.DataTypes.cs.
MajorVersion
uint Opc.Ua.ConfigurationVersionDataType.MajorVersion get set
Definition at line 6163 of file Opc.Ua.DataTypes.cs.
MinorVersion
uint Opc.Ua.ConfigurationVersionDataType.MinorVersion get set
Definition at line 6171 of file Opc.Ua.DataTypes.cs.
TypeId
virtual ExpandedNodeId Opc.Ua.ConfigurationVersionDataType.TypeId get
Definition at line 6180 of file Opc.Ua.DataTypes.cs.
XmlEncodingId
virtual ExpandedNodeId Opc.Ua.ConfigurationVersionDataType.XmlEncodingId get
Definition at line 6192 of file Opc.Ua.DataTypes.cs.
The documentation for this class was generated from the following file:
Opc.Ua.DataTypes.cs