Project Template: transport_generated_handling.h File Reference
transport_generated_handling.h File Reference
Functions
static _UA_BEGIN_DECLS UA_INLINE void UA_SecureConversationMessageAbortBody_init (UA_SecureConversationMessageAbortBody *p)
static UA_INLINE UA_SecureConversationMessageAbortBody * UA_SecureConversationMessageAbortBody_new (void)
static UA_INLINE UA_StatusCode UA_SecureConversationMessageAbortBody_copy (const UA_SecureConversationMessageAbortBody *src, UA_SecureConversationMessageAbortBody *dst)
static UA_INLINE void UA_SecureConversationMessageAbortBody_deleteMembers (UA_SecureConversationMessageAbortBody *p)
static UA_INLINE void UA_SecureConversationMessageAbortBody_clear (UA_SecureConversationMessageAbortBody *p)
static UA_INLINE void UA_SecureConversationMessageAbortBody_delete (UA_SecureConversationMessageAbortBody *p)
static UA_INLINE void UA_SecureConversationMessageFooter_init (UA_SecureConversationMessageFooter *p)
static UA_INLINE UA_SecureConversationMessageFooter * UA_SecureConversationMessageFooter_new (void)
static UA_INLINE UA_StatusCode UA_SecureConversationMessageFooter_copy (const UA_SecureConversationMessageFooter *src, UA_SecureConversationMessageFooter *dst)
static UA_INLINE void UA_SecureConversationMessageFooter_deleteMembers (UA_SecureConversationMessageFooter *p)
static UA_INLINE void UA_SecureConversationMessageFooter_clear (UA_SecureConversationMessageFooter *p)
static UA_INLINE void UA_SecureConversationMessageFooter_delete (UA_SecureConversationMessageFooter *p)
static UA_INLINE void UA_TcpHelloMessage_init (UA_TcpHelloMessage *p)
static UA_INLINE UA_TcpHelloMessage * UA_TcpHelloMessage_new (void)
static UA_INLINE UA_StatusCode UA_TcpHelloMessage_copy (const UA_TcpHelloMessage *src, UA_TcpHelloMessage *dst)
static UA_INLINE void UA_TcpHelloMessage_deleteMembers (UA_TcpHelloMessage *p)
static UA_INLINE void UA_TcpHelloMessage_clear (UA_TcpHelloMessage *p)
static UA_INLINE void UA_TcpHelloMessage_delete (UA_TcpHelloMessage *p)
static UA_INLINE void UA_TcpErrorMessage_init (UA_TcpErrorMessage *p)
static UA_INLINE UA_TcpErrorMessage * UA_TcpErrorMessage_new (void)
static UA_INLINE UA_StatusCode UA_TcpErrorMessage_copy (const UA_TcpErrorMessage *src, UA_TcpErrorMessage *dst)
static UA_INLINE void UA_TcpErrorMessage_deleteMembers (UA_TcpErrorMessage *p)
static UA_INLINE void UA_TcpErrorMessage_clear (UA_TcpErrorMessage *p)
static UA_INLINE void UA_TcpErrorMessage_delete (UA_TcpErrorMessage *p)
static UA_INLINE void UA_MessageType_init (UA_MessageType *p)
static UA_INLINE UA_MessageType * UA_MessageType_new (void)
static UA_INLINE UA_StatusCode UA_MessageType_copy (const UA_MessageType *src, UA_MessageType *dst)
static UA_INLINE void UA_MessageType_deleteMembers (UA_MessageType *p)
static UA_INLINE void UA_MessageType_clear (UA_MessageType *p)
static UA_INLINE void UA_MessageType_delete (UA_MessageType *p)
static UA_INLINE void UA_AsymmetricAlgorithmSecurityHeader_init (UA_AsymmetricAlgorithmSecurityHeader *p)
static UA_INLINE UA_AsymmetricAlgorithmSecurityHeader * UA_AsymmetricAlgorithmSecurityHeader_new (void)
static UA_INLINE UA_StatusCode UA_AsymmetricAlgorithmSecurityHeader_copy (const UA_AsymmetricAlgorithmSecurityHeader *src, UA_AsymmetricAlgorithmSecurityHeader *dst)
static UA_INLINE void UA_AsymmetricAlgorithmSecurityHeader_deleteMembers (UA_AsymmetricAlgorithmSecurityHeader *p)
static UA_INLINE void UA_AsymmetricAlgorithmSecurityHeader_clear (UA_AsymmetricAlgorithmSecurityHeader *p)
static UA_INLINE void UA_AsymmetricAlgorithmSecurityHeader_delete (UA_AsymmetricAlgorithmSecurityHeader *p)
static UA_INLINE void UA_TcpAcknowledgeMessage_init (UA_TcpAcknowledgeMessage *p)
static UA_INLINE UA_TcpAcknowledgeMessage * UA_TcpAcknowledgeMessage_new (void)
static UA_INLINE UA_StatusCode UA_TcpAcknowledgeMessage_copy (const UA_TcpAcknowledgeMessage *src, UA_TcpAcknowledgeMessage *dst)
static UA_INLINE void UA_TcpAcknowledgeMessage_deleteMembers (UA_TcpAcknowledgeMessage *p)
static UA_INLINE void UA_TcpAcknowledgeMessage_clear (UA_TcpAcknowledgeMessage *p)
static UA_INLINE void UA_TcpAcknowledgeMessage_delete (UA_TcpAcknowledgeMessage *p)
static UA_INLINE void UA_SequenceHeader_init (UA_SequenceHeader *p)
static UA_INLINE UA_SequenceHeader * UA_SequenceHeader_new (void)
static UA_INLINE UA_StatusCode UA_SequenceHeader_copy (const UA_SequenceHeader *src, UA_SequenceHeader *dst)
static UA_INLINE void UA_SequenceHeader_deleteMembers (UA_SequenceHeader *p)
static UA_INLINE void UA_SequenceHeader_clear (UA_SequenceHeader *p)
static UA_INLINE void UA_SequenceHeader_delete (UA_SequenceHeader *p)
static UA_INLINE void UA_TcpMessageHeader_init (UA_TcpMessageHeader *p)
static UA_INLINE UA_TcpMessageHeader * UA_TcpMessageHeader_new (void)
static UA_INLINE UA_StatusCode UA_TcpMessageHeader_copy (const UA_TcpMessageHeader *src, UA_TcpMessageHeader *dst)
static UA_INLINE void UA_TcpMessageHeader_deleteMembers (UA_TcpMessageHeader *p)
static UA_INLINE void UA_TcpMessageHeader_clear (UA_TcpMessageHeader *p)
static UA_INLINE void UA_TcpMessageHeader_delete (UA_TcpMessageHeader *p)
static UA_INLINE void UA_ChunkType_init (UA_ChunkType *p)
static UA_INLINE UA_ChunkType * UA_ChunkType_new (void)
static UA_INLINE UA_StatusCode UA_ChunkType_copy (const UA_ChunkType *src, UA_ChunkType *dst)
static UA_INLINE void UA_ChunkType_deleteMembers (UA_ChunkType *p)
static UA_INLINE void UA_ChunkType_clear (UA_ChunkType *p)
static UA_INLINE void UA_ChunkType_delete (UA_ChunkType *p)
static UA_INLINE void UA_SymmetricAlgorithmSecurityHeader_init (UA_SymmetricAlgorithmSecurityHeader *p)
static UA_INLINE UA_SymmetricAlgorithmSecurityHeader * UA_SymmetricAlgorithmSecurityHeader_new (void)
static UA_INLINE UA_StatusCode UA_SymmetricAlgorithmSecurityHeader_copy (const UA_SymmetricAlgorithmSecurityHeader *src, UA_SymmetricAlgorithmSecurityHeader *dst)
static UA_INLINE void UA_SymmetricAlgorithmSecurityHeader_deleteMembers (UA_SymmetricAlgorithmSecurityHeader *p)
static UA_INLINE void UA_SymmetricAlgorithmSecurityHeader_clear (UA_SymmetricAlgorithmSecurityHeader *p)
static UA_INLINE void UA_SymmetricAlgorithmSecurityHeader_delete (UA_SymmetricAlgorithmSecurityHeader *p)
static UA_INLINE void UA_SecureConversationMessageHeader_init (UA_SecureConversationMessageHeader *p)
static UA_INLINE UA_SecureConversationMessageHeader * UA_SecureConversationMessageHeader_new (void)
static UA_INLINE UA_StatusCode UA_SecureConversationMessageHeader_copy (const UA_SecureConversationMessageHeader *src, UA_SecureConversationMessageHeader *dst)
static UA_INLINE void UA_SecureConversationMessageHeader_deleteMembers (UA_SecureConversationMessageHeader *p)
static UA_INLINE void UA_SecureConversationMessageHeader_clear (UA_SecureConversationMessageHeader *p)
static UA_INLINE void UA_SecureConversationMessageHeader_delete (UA_SecureConversationMessageHeader *p)
Function Documentation
UA_AsymmetricAlgorithmSecurityHeader_clear()
static UA_INLINE void UA_AsymmetricAlgorithmSecurityHeader_clear (UA_AsymmetricAlgorithmSecurityHeader * p) static
Definition at line 196 of file transport_generated_handling.h.
References UA_clear(), and UA_TRANSPORT.
UA_AsymmetricAlgorithmSecurityHeader_copy()
static UA_INLINE UA_StatusCode UA_AsymmetricAlgorithmSecurityHeader_copy (const UA_AsymmetricAlgorithmSecurityHeader * src, UA_AsymmetricAlgorithmSecurityHeader * dst) static
Definition at line 186 of file transport_generated_handling.h.
References UA_copy(), and UA_TRANSPORT.
UA_AsymmetricAlgorithmSecurityHeader_delete()
static UA_INLINE void UA_AsymmetricAlgorithmSecurityHeader_delete (UA_AsymmetricAlgorithmSecurityHeader * p) static
Definition at line 201 of file transport_generated_handling.h.
References UA_delete(), and UA_TRANSPORT.
UA_AsymmetricAlgorithmSecurityHeader_deleteMembers()
static UA_INLINE void UA_AsymmetricAlgorithmSecurityHeader_deleteMembers (UA_AsymmetricAlgorithmSecurityHeader * p) static
Definition at line 191 of file transport_generated_handling.h.
References UA_clear(), and UA_TRANSPORT.
UA_AsymmetricAlgorithmSecurityHeader_init()
static UA_INLINE void UA_AsymmetricAlgorithmSecurityHeader_init (UA_AsymmetricAlgorithmSecurityHeader * p) static
Definition at line 176 of file transport_generated_handling.h.
UA_AsymmetricAlgorithmSecurityHeader_new()
static UA_INLINE UA_AsymmetricAlgorithmSecurityHeader* UA_AsymmetricAlgorithmSecurityHeader_new (void) static
Definition at line 181 of file transport_generated_handling.h.
References UA_new(), and UA_TRANSPORT.
UA_ChunkType_clear()
static UA_INLINE void UA_ChunkType_clear (UA_ChunkType * p) static
Definition at line 324 of file transport_generated_handling.h.
UA_ChunkType_copy()
static UA_INLINE UA_StatusCode UA_ChunkType_copy (const UA_ChunkType * src, UA_ChunkType * dst) static
Definition at line 313 of file transport_generated_handling.h.
UA_ChunkType_delete()
static UA_INLINE void UA_ChunkType_delete (UA_ChunkType * p) static
Definition at line 329 of file transport_generated_handling.h.
References UA_delete(), and UA_TRANSPORT.
UA_ChunkType_deleteMembers()
static UA_INLINE void UA_ChunkType_deleteMembers (UA_ChunkType * p) static
Definition at line 319 of file transport_generated_handling.h.
UA_ChunkType_init()
static UA_INLINE void UA_ChunkType_init (UA_ChunkType * p) static
Definition at line 303 of file transport_generated_handling.h.
UA_ChunkType_new()
static UA_INLINE UA_ChunkType* UA_ChunkType_new (void) static
Definition at line 308 of file transport_generated_handling.h.
References UA_new(), and UA_TRANSPORT.
UA_MessageType_clear()
static UA_INLINE void UA_MessageType_clear (UA_MessageType * p) static
Definition at line 165 of file transport_generated_handling.h.
UA_MessageType_copy()
static UA_INLINE UA_StatusCode UA_MessageType_copy (const UA_MessageType * src, UA_MessageType * dst) static
Definition at line 154 of file transport_generated_handling.h.
UA_MessageType_delete()
static UA_INLINE void UA_MessageType_delete (UA_MessageType * p) static
Definition at line 170 of file transport_generated_handling.h.
References UA_delete(), and UA_TRANSPORT.
UA_MessageType_deleteMembers()
static UA_INLINE void UA_MessageType_deleteMembers (UA_MessageType * p) static
Definition at line 160 of file transport_generated_handling.h.
UA_MessageType_init()
static UA_INLINE void UA_MessageType_init (UA_MessageType * p) static
Definition at line 144 of file transport_generated_handling.h.
UA_MessageType_new()
static UA_INLINE UA_MessageType* UA_MessageType_new (void) static
Definition at line 149 of file transport_generated_handling.h.
References UA_new(), and UA_TRANSPORT.
UA_SecureConversationMessageAbortBody_clear()
static UA_INLINE void UA_SecureConversationMessageAbortBody_clear (UA_SecureConversationMessageAbortBody * p) static
Definition at line 40 of file transport_generated_handling.h.
References UA_clear(), and UA_TRANSPORT.
UA_SecureConversationMessageAbortBody_copy()
static UA_INLINE UA_StatusCode UA_SecureConversationMessageAbortBody_copy (const UA_SecureConversationMessageAbortBody * src, UA_SecureConversationMessageAbortBody * dst) static
Definition at line 30 of file transport_generated_handling.h.
References UA_copy(), and UA_TRANSPORT.
UA_SecureConversationMessageAbortBody_delete()
static UA_INLINE void UA_SecureConversationMessageAbortBody_delete (UA_SecureConversationMessageAbortBody * p) static
Definition at line 45 of file transport_generated_handling.h.
References UA_delete(), and UA_TRANSPORT.
UA_SecureConversationMessageAbortBody_deleteMembers()
static UA_INLINE void UA_SecureConversationMessageAbortBody_deleteMembers (UA_SecureConversationMessageAbortBody * p) static
Definition at line 35 of file transport_generated_handling.h.
References UA_clear(), and UA_TRANSPORT.
UA_SecureConversationMessageAbortBody_init()
static _UA_BEGIN_DECLS UA_INLINE void UA_SecureConversationMessageAbortBody_init (UA_SecureConversationMessageAbortBody * p) static
Definition at line 20 of file transport_generated_handling.h.
UA_SecureConversationMessageAbortBody_new()
static UA_INLINE UA_SecureConversationMessageAbortBody* UA_SecureConversationMessageAbortBody_new (void) static
Definition at line 25 of file transport_generated_handling.h.
References UA_new(), and UA_TRANSPORT.
UA_SecureConversationMessageFooter_clear()
static UA_INLINE void UA_SecureConversationMessageFooter_clear (UA_SecureConversationMessageFooter * p) static
Definition at line 71 of file transport_generated_handling.h.
References UA_clear(), and UA_TRANSPORT.
UA_SecureConversationMessageFooter_copy()
static UA_INLINE UA_StatusCode UA_SecureConversationMessageFooter_copy (const UA_SecureConversationMessageFooter * src, UA_SecureConversationMessageFooter * dst) static
Definition at line 61 of file transport_generated_handling.h.
References UA_copy(), and UA_TRANSPORT.
UA_SecureConversationMessageFooter_delete()
static UA_INLINE void UA_SecureConversationMessageFooter_delete (UA_SecureConversationMessageFooter * p) static
Definition at line 76 of file transport_generated_handling.h.
References UA_delete(), and UA_TRANSPORT.
UA_SecureConversationMessageFooter_deleteMembers()
static UA_INLINE void UA_SecureConversationMessageFooter_deleteMembers (UA_SecureConversationMessageFooter * p) static
Definition at line 66 of file transport_generated_handling.h.
References UA_clear(), and UA_TRANSPORT.
UA_SecureConversationMessageFooter_init()
static UA_INLINE void UA_SecureConversationMessageFooter_init (UA_SecureConversationMessageFooter * p) static
Definition at line 51 of file transport_generated_handling.h.
UA_SecureConversationMessageFooter_new()
static UA_INLINE UA_SecureConversationMessageFooter* UA_SecureConversationMessageFooter_new (void) static
Definition at line 56 of file transport_generated_handling.h.
References UA_new(), and UA_TRANSPORT.
UA_SecureConversationMessageHeader_clear()
static UA_INLINE void UA_SecureConversationMessageHeader_clear (UA_SecureConversationMessageHeader * p) static
Definition at line 388 of file transport_generated_handling.h.
UA_SecureConversationMessageHeader_copy()
static UA_INLINE UA_StatusCode UA_SecureConversationMessageHeader_copy (const UA_SecureConversationMessageHeader * src, UA_SecureConversationMessageHeader * dst) static
Definition at line 377 of file transport_generated_handling.h.
UA_SecureConversationMessageHeader_delete()
static UA_INLINE void UA_SecureConversationMessageHeader_delete (UA_SecureConversationMessageHeader * p) static
Definition at line 393 of file transport_generated_handling.h.
References UA_delete(), and UA_TRANSPORT.
UA_SecureConversationMessageHeader_deleteMembers()
static UA_INLINE void UA_SecureConversationMessageHeader_deleteMembers (UA_SecureConversationMessageHeader * p) static
Definition at line 383 of file transport_generated_handling.h.
UA_SecureConversationMessageHeader_init()
static UA_INLINE void UA_SecureConversationMessageHeader_init (UA_SecureConversationMessageHeader * p) static
Definition at line 367 of file transport_generated_handling.h.
UA_SecureConversationMessageHeader_new()
static UA_INLINE UA_SecureConversationMessageHeader* UA_SecureConversationMessageHeader_new (void) static
Definition at line 372 of file transport_generated_handling.h.
References UA_new(), and UA_TRANSPORT.
UA_SequenceHeader_clear()
static UA_INLINE void UA_SequenceHeader_clear (UA_SequenceHeader * p) static
Definition at line 260 of file transport_generated_handling.h.
UA_SequenceHeader_copy()
static UA_INLINE UA_StatusCode UA_SequenceHeader_copy (const UA_SequenceHeader * src, UA_SequenceHeader * dst) static
Definition at line 249 of file transport_generated_handling.h.
UA_SequenceHeader_delete()
static UA_INLINE void UA_SequenceHeader_delete (UA_SequenceHeader * p) static
Definition at line 265 of file transport_generated_handling.h.
References UA_delete(), and UA_TRANSPORT.
UA_SequenceHeader_deleteMembers()
static UA_INLINE void UA_SequenceHeader_deleteMembers (UA_SequenceHeader * p) static
Definition at line 255 of file transport_generated_handling.h.
UA_SequenceHeader_init()
static UA_INLINE void UA_SequenceHeader_init (UA_SequenceHeader * p) static
Definition at line 239 of file transport_generated_handling.h.
UA_SequenceHeader_new()
static UA_INLINE UA_SequenceHeader* UA_SequenceHeader_new (void) static
Definition at line 244 of file transport_generated_handling.h.
References UA_new(), and UA_TRANSPORT.
UA_SymmetricAlgorithmSecurityHeader_clear()
static UA_INLINE void UA_SymmetricAlgorithmSecurityHeader_clear (UA_SymmetricAlgorithmSecurityHeader * p) static
Definition at line 356 of file transport_generated_handling.h.
UA_SymmetricAlgorithmSecurityHeader_copy()
static UA_INLINE UA_StatusCode UA_SymmetricAlgorithmSecurityHeader_copy (const UA_SymmetricAlgorithmSecurityHeader * src, UA_SymmetricAlgorithmSecurityHeader * dst) static
Definition at line 345 of file transport_generated_handling.h.
UA_SymmetricAlgorithmSecurityHeader_delete()
static UA_INLINE void UA_SymmetricAlgorithmSecurityHeader_delete (UA_SymmetricAlgorithmSecurityHeader * p) static
Definition at line 361 of file transport_generated_handling.h.
References UA_delete(), and UA_TRANSPORT.
UA_SymmetricAlgorithmSecurityHeader_deleteMembers()
static UA_INLINE void UA_SymmetricAlgorithmSecurityHeader_deleteMembers (UA_SymmetricAlgorithmSecurityHeader * p) static
Definition at line 351 of file transport_generated_handling.h.
UA_SymmetricAlgorithmSecurityHeader_init()
static UA_INLINE void UA_SymmetricAlgorithmSecurityHeader_init (UA_SymmetricAlgorithmSecurityHeader * p) static
Definition at line 335 of file transport_generated_handling.h.
UA_SymmetricAlgorithmSecurityHeader_new()
static UA_INLINE UA_SymmetricAlgorithmSecurityHeader* UA_SymmetricAlgorithmSecurityHeader_new (void) static
Definition at line 340 of file transport_generated_handling.h.
References UA_new(), and UA_TRANSPORT.
UA_TcpAcknowledgeMessage_clear()
static UA_INLINE void UA_TcpAcknowledgeMessage_clear (UA_TcpAcknowledgeMessage * p) static
Definition at line 228 of file transport_generated_handling.h.
UA_TcpAcknowledgeMessage_copy()
static UA_INLINE UA_StatusCode UA_TcpAcknowledgeMessage_copy (const UA_TcpAcknowledgeMessage * src, UA_TcpAcknowledgeMessage * dst) static
Definition at line 217 of file transport_generated_handling.h.
UA_TcpAcknowledgeMessage_delete()
static UA_INLINE void UA_TcpAcknowledgeMessage_delete (UA_TcpAcknowledgeMessage * p) static
Definition at line 233 of file transport_generated_handling.h.
References UA_delete(), and UA_TRANSPORT.
UA_TcpAcknowledgeMessage_deleteMembers()
static UA_INLINE void UA_TcpAcknowledgeMessage_deleteMembers (UA_TcpAcknowledgeMessage * p) static
Definition at line 223 of file transport_generated_handling.h.
UA_TcpAcknowledgeMessage_init()
static UA_INLINE void UA_TcpAcknowledgeMessage_init (UA_TcpAcknowledgeMessage * p) static
Definition at line 207 of file transport_generated_handling.h.
UA_TcpAcknowledgeMessage_new()
static UA_INLINE UA_TcpAcknowledgeMessage* UA_TcpAcknowledgeMessage_new (void) static
Definition at line 212 of file transport_generated_handling.h.
References UA_new(), and UA_TRANSPORT.
UA_TcpErrorMessage_clear()
static UA_INLINE void UA_TcpErrorMessage_clear (UA_TcpErrorMessage * p) static
Definition at line 133 of file transport_generated_handling.h.
References UA_clear(), and UA_TRANSPORT.
UA_TcpErrorMessage_copy()
static UA_INLINE UA_StatusCode UA_TcpErrorMessage_copy (const UA_TcpErrorMessage * src, UA_TcpErrorMessage * dst) static
Definition at line 123 of file transport_generated_handling.h.
References UA_copy(), and UA_TRANSPORT.
UA_TcpErrorMessage_delete()
static UA_INLINE void UA_TcpErrorMessage_delete (UA_TcpErrorMessage * p) static
Definition at line 138 of file transport_generated_handling.h.
References UA_delete(), and UA_TRANSPORT.
UA_TcpErrorMessage_deleteMembers()
static UA_INLINE void UA_TcpErrorMessage_deleteMembers (UA_TcpErrorMessage * p) static
Definition at line 128 of file transport_generated_handling.h.
References UA_clear(), and UA_TRANSPORT.
UA_TcpErrorMessage_init()
static UA_INLINE void UA_TcpErrorMessage_init (UA_TcpErrorMessage * p) static
Definition at line 113 of file transport_generated_handling.h.
UA_TcpErrorMessage_new()
static UA_INLINE UA_TcpErrorMessage* UA_TcpErrorMessage_new (void) static
Definition at line 118 of file transport_generated_handling.h.
References UA_new(), and UA_TRANSPORT.
UA_TcpHelloMessage_clear()
static UA_INLINE void UA_TcpHelloMessage_clear (UA_TcpHelloMessage * p) static
Definition at line 102 of file transport_generated_handling.h.
References UA_clear(), and UA_TRANSPORT.
UA_TcpHelloMessage_copy()
static UA_INLINE UA_StatusCode UA_TcpHelloMessage_copy (const UA_TcpHelloMessage * src, UA_TcpHelloMessage * dst) static
Definition at line 92 of file transport_generated_handling.h.
References UA_copy(), and UA_TRANSPORT.
UA_TcpHelloMessage_delete()
static UA_INLINE void UA_TcpHelloMessage_delete (UA_TcpHelloMessage * p) static
Definition at line 107 of file transport_generated_handling.h.
References UA_delete(), and UA_TRANSPORT.
UA_TcpHelloMessage_deleteMembers()
static UA_INLINE void UA_TcpHelloMessage_deleteMembers (UA_TcpHelloMessage * p) static
Definition at line 97 of file transport_generated_handling.h.
References UA_clear(), and UA_TRANSPORT.
UA_TcpHelloMessage_init()
static UA_INLINE void UA_TcpHelloMessage_init (UA_TcpHelloMessage * p) static
Definition at line 82 of file transport_generated_handling.h.
UA_TcpHelloMessage_new()
static UA_INLINE UA_TcpHelloMessage* UA_TcpHelloMessage_new (void) static
Definition at line 87 of file transport_generated_handling.h.
References UA_new(), and UA_TRANSPORT.
UA_TcpMessageHeader_clear()
static UA_INLINE void UA_TcpMessageHeader_clear (UA_TcpMessageHeader * p) static
Definition at line 292 of file transport_generated_handling.h.
UA_TcpMessageHeader_copy()
static UA_INLINE UA_StatusCode UA_TcpMessageHeader_copy (const UA_TcpMessageHeader * src, UA_TcpMessageHeader * dst) static
Definition at line 281 of file transport_generated_handling.h.
UA_TcpMessageHeader_delete()
static UA_INLINE void UA_TcpMessageHeader_delete (UA_TcpMessageHeader * p) static
Definition at line 297 of file transport_generated_handling.h.
References UA_delete(), and UA_TRANSPORT.
UA_TcpMessageHeader_deleteMembers()
static UA_INLINE void UA_TcpMessageHeader_deleteMembers (UA_TcpMessageHeader * p) static
Definition at line 287 of file transport_generated_handling.h.
UA_TcpMessageHeader_init()
static UA_INLINE void UA_TcpMessageHeader_init (UA_TcpMessageHeader * p) static
Definition at line 271 of file transport_generated_handling.h.
UA_TcpMessageHeader_new()
static UA_INLINE UA_TcpMessageHeader* UA_TcpMessageHeader_new (void) static
Definition at line 276 of file transport_generated_handling.h.
References UA_new(), and UA_TRANSPORT.