Project Template: Opc.Ua.SessionDiagnosticsDataType Class Reference
Opc.Ua.SessionDiagnosticsDataType Class Reference
Public Member Functions
SessionDiagnosticsDataType ()
The default constructor.
virtual void Encode (IEncoder encoder)
virtual void Decode (IDecoder decoder)
virtual bool IsEqual (IEncodeable encodeable)
virtual object Clone ()
new object MemberwiseClone ()
Properties
NodeId SessionId [get, set]
string SessionName [get, set]
ApplicationDescription ClientDescription [get, set]
string ServerUri [get, set]
string EndpointUrl [get, set]
StringCollection LocaleIds [get, set]
double ActualSessionTimeout [get, set]
uint MaxResponseMessageSize [get, set]
DateTime ClientConnectionTime [get, set]
DateTime ClientLastContactTime [get, set]
uint CurrentSubscriptionsCount [get, set]
uint CurrentMonitoredItemsCount [get, set]
uint CurrentPublishRequestsInQueue [get, set]
ServiceCounterDataType TotalRequestCount [get, set]
uint UnauthorizedRequestCount [get, set]
ServiceCounterDataType ReadCount [get, set]
ServiceCounterDataType HistoryReadCount [get, set]
ServiceCounterDataType WriteCount [get, set]
ServiceCounterDataType HistoryUpdateCount [get, set]
ServiceCounterDataType CallCount [get, set]
ServiceCounterDataType CreateMonitoredItemsCount [get, set]
ServiceCounterDataType ModifyMonitoredItemsCount [get, set]
ServiceCounterDataType SetMonitoringModeCount [get, set]
ServiceCounterDataType SetTriggeringCount [get, set]
ServiceCounterDataType DeleteMonitoredItemsCount [get, set]
ServiceCounterDataType CreateSubscriptionCount [get, set]
ServiceCounterDataType ModifySubscriptionCount [get, set]
ServiceCounterDataType SetPublishingModeCount [get, set]
ServiceCounterDataType PublishCount [get, set]
ServiceCounterDataType RepublishCount [get, set]
ServiceCounterDataType TransferSubscriptionsCount [get, set]
ServiceCounterDataType DeleteSubscriptionsCount [get, set]
ServiceCounterDataType AddNodesCount [get, set]
ServiceCounterDataType AddReferencesCount [get, set]
ServiceCounterDataType DeleteNodesCount [get, set]
ServiceCounterDataType DeleteReferencesCount [get, set]
ServiceCounterDataType BrowseCount [get, set]
ServiceCounterDataType BrowseNextCount [get, set]
ServiceCounterDataType TranslateBrowsePathsToNodeIdsCount [get, set]
ServiceCounterDataType QueryFirstCount [get, set]
ServiceCounterDataType QueryNextCount [get, set]
ServiceCounterDataType RegisterNodesCount [get, set]
ServiceCounterDataType UnregisterNodesCount [get, set]
virtual ExpandedNodeId TypeId [get]
virtual ExpandedNodeId BinaryEncodingId [get]
virtual ExpandedNodeId XmlEncodingId [get]
Detailed Description
<exclude>
Definition at line 62988 of file Opc.Ua.DataTypes.cs.
Constructor & Destructor Documentation
SessionDiagnosticsDataType()
Opc.Ua.SessionDiagnosticsDataType.SessionDiagnosticsDataType () inline
The default constructor.
Definition at line 62994 of file Opc.Ua.DataTypes.cs.
Member Function Documentation
Clone()
virtual object Opc.Ua.SessionDiagnosticsDataType.Clone () inline virtual
Definition at line 64026 of file Opc.Ua.DataTypes.cs.
Decode()
virtual void Opc.Ua.SessionDiagnosticsDataType.Decode (IDecoder decoder) inline virtual
Definition at line 63911 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
Encode()
virtual void Opc.Ua.SessionDiagnosticsDataType.Encode (IEncoder encoder) inline virtual
Definition at line 63859 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
IsEqual()
virtual bool Opc.Ua.SessionDiagnosticsDataType.IsEqual (IEncodeable encodeable) inline virtual
Definition at line 63963 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Object.
MemberwiseClone()
new object Opc.Ua.SessionDiagnosticsDataType.MemberwiseClone () inline
Definition at line 64033 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.ApplicationDescription.Clone(), Opc.Ua.ServiceCounterDataType.Clone(), Opc.Ua.SessionDiagnosticsDataType.MemberwiseClone(), Opc.Ua.NodeId, and Opc.Ua.Namespaces.OpcUaXsd.
Referenced by Opc.Ua.SessionDiagnosticsDataType.MemberwiseClone().
Property Documentation
ActualSessionTimeout
double Opc.Ua.SessionDiagnosticsDataType.ActualSessionTimeout get set
Definition at line 63139 of file Opc.Ua.DataTypes.cs.
AddNodesCount
ServiceCounterDataType Opc.Ua.SessionDiagnosticsDataType.AddNodesCount get set
Definition at line 63601 of file Opc.Ua.DataTypes.cs.
AddReferencesCount
ServiceCounterDataType Opc.Ua.SessionDiagnosticsDataType.AddReferencesCount get set
Definition at line 63623 of file Opc.Ua.DataTypes.cs.
BinaryEncodingId
virtual ExpandedNodeId Opc.Ua.SessionDiagnosticsDataType.BinaryEncodingId get
Definition at line 63848 of file Opc.Ua.DataTypes.cs.
BrowseCount
ServiceCounterDataType Opc.Ua.SessionDiagnosticsDataType.BrowseCount get set
Definition at line 63689 of file Opc.Ua.DataTypes.cs.
BrowseNextCount
ServiceCounterDataType Opc.Ua.SessionDiagnosticsDataType.BrowseNextCount get set
Definition at line 63711 of file Opc.Ua.DataTypes.cs.
CallCount
ServiceCounterDataType Opc.Ua.SessionDiagnosticsDataType.CallCount get set
Definition at line 63315 of file Opc.Ua.DataTypes.cs.
ClientConnectionTime
DateTime Opc.Ua.SessionDiagnosticsDataType.ClientConnectionTime get set
Definition at line 63155 of file Opc.Ua.DataTypes.cs.
ClientDescription
ApplicationDescription Opc.Ua.SessionDiagnosticsDataType.ClientDescription get set
Definition at line 63081 of file Opc.Ua.DataTypes.cs.
ClientLastContactTime
DateTime Opc.Ua.SessionDiagnosticsDataType.ClientLastContactTime get set
Definition at line 63163 of file Opc.Ua.DataTypes.cs.
CreateMonitoredItemsCount
ServiceCounterDataType Opc.Ua.SessionDiagnosticsDataType.CreateMonitoredItemsCount get set
Definition at line 63337 of file Opc.Ua.DataTypes.cs.
CreateSubscriptionCount
ServiceCounterDataType Opc.Ua.SessionDiagnosticsDataType.CreateSubscriptionCount get set
Definition at line 63447 of file Opc.Ua.DataTypes.cs.
CurrentMonitoredItemsCount
uint Opc.Ua.SessionDiagnosticsDataType.CurrentMonitoredItemsCount get set
Definition at line 63179 of file Opc.Ua.DataTypes.cs.
CurrentPublishRequestsInQueue
uint Opc.Ua.SessionDiagnosticsDataType.CurrentPublishRequestsInQueue get set
Definition at line 63187 of file Opc.Ua.DataTypes.cs.
CurrentSubscriptionsCount
uint Opc.Ua.SessionDiagnosticsDataType.CurrentSubscriptionsCount get set
Definition at line 63171 of file Opc.Ua.DataTypes.cs.
DeleteMonitoredItemsCount
ServiceCounterDataType Opc.Ua.SessionDiagnosticsDataType.DeleteMonitoredItemsCount get set
Definition at line 63425 of file Opc.Ua.DataTypes.cs.
DeleteNodesCount
ServiceCounterDataType Opc.Ua.SessionDiagnosticsDataType.DeleteNodesCount get set
Definition at line 63645 of file Opc.Ua.DataTypes.cs.
DeleteReferencesCount
ServiceCounterDataType Opc.Ua.SessionDiagnosticsDataType.DeleteReferencesCount get set
Definition at line 63667 of file Opc.Ua.DataTypes.cs.
DeleteSubscriptionsCount
ServiceCounterDataType Opc.Ua.SessionDiagnosticsDataType.DeleteSubscriptionsCount get set
Definition at line 63579 of file Opc.Ua.DataTypes.cs.
EndpointUrl
string Opc.Ua.SessionDiagnosticsDataType.EndpointUrl get set
Definition at line 63109 of file Opc.Ua.DataTypes.cs.
HistoryReadCount
ServiceCounterDataType Opc.Ua.SessionDiagnosticsDataType.HistoryReadCount get set
Definition at line 63249 of file Opc.Ua.DataTypes.cs.
HistoryUpdateCount
ServiceCounterDataType Opc.Ua.SessionDiagnosticsDataType.HistoryUpdateCount get set
Definition at line 63293 of file Opc.Ua.DataTypes.cs.
LocaleIds
StringCollection Opc.Ua.SessionDiagnosticsDataType.LocaleIds get set
Definition at line 63119 of file Opc.Ua.DataTypes.cs.
MaxResponseMessageSize
uint Opc.Ua.SessionDiagnosticsDataType.MaxResponseMessageSize get set
Definition at line 63147 of file Opc.Ua.DataTypes.cs.
ModifyMonitoredItemsCount
ServiceCounterDataType Opc.Ua.SessionDiagnosticsDataType.ModifyMonitoredItemsCount get set
Definition at line 63359 of file Opc.Ua.DataTypes.cs.
ModifySubscriptionCount
ServiceCounterDataType Opc.Ua.SessionDiagnosticsDataType.ModifySubscriptionCount get set
Definition at line 63469 of file Opc.Ua.DataTypes.cs.
PublishCount
ServiceCounterDataType Opc.Ua.SessionDiagnosticsDataType.PublishCount get set
Definition at line 63513 of file Opc.Ua.DataTypes.cs.
QueryFirstCount
ServiceCounterDataType Opc.Ua.SessionDiagnosticsDataType.QueryFirstCount get set
Definition at line 63755 of file Opc.Ua.DataTypes.cs.
QueryNextCount
ServiceCounterDataType Opc.Ua.SessionDiagnosticsDataType.QueryNextCount get set
Definition at line 63777 of file Opc.Ua.DataTypes.cs.
ReadCount
ServiceCounterDataType Opc.Ua.SessionDiagnosticsDataType.ReadCount get set
Definition at line 63227 of file Opc.Ua.DataTypes.cs.
RegisterNodesCount
ServiceCounterDataType Opc.Ua.SessionDiagnosticsDataType.RegisterNodesCount get set
Definition at line 63799 of file Opc.Ua.DataTypes.cs.
RepublishCount
ServiceCounterDataType Opc.Ua.SessionDiagnosticsDataType.RepublishCount get set
Definition at line 63535 of file Opc.Ua.DataTypes.cs.
ServerUri
string Opc.Ua.SessionDiagnosticsDataType.ServerUri get set
Definition at line 63101 of file Opc.Ua.DataTypes.cs.
SessionId
NodeId Opc.Ua.SessionDiagnosticsDataType.SessionId get set
Definition at line 63063 of file Opc.Ua.DataTypes.cs.
SessionName
string Opc.Ua.SessionDiagnosticsDataType.SessionName get set
Definition at line 63071 of file Opc.Ua.DataTypes.cs.
SetMonitoringModeCount
ServiceCounterDataType Opc.Ua.SessionDiagnosticsDataType.SetMonitoringModeCount get set
Definition at line 63381 of file Opc.Ua.DataTypes.cs.
SetPublishingModeCount
ServiceCounterDataType Opc.Ua.SessionDiagnosticsDataType.SetPublishingModeCount get set
Definition at line 63491 of file Opc.Ua.DataTypes.cs.
SetTriggeringCount
ServiceCounterDataType Opc.Ua.SessionDiagnosticsDataType.SetTriggeringCount get set
Definition at line 63403 of file Opc.Ua.DataTypes.cs.
TotalRequestCount
ServiceCounterDataType Opc.Ua.SessionDiagnosticsDataType.TotalRequestCount get set
Definition at line 63197 of file Opc.Ua.DataTypes.cs.
TransferSubscriptionsCount
ServiceCounterDataType Opc.Ua.SessionDiagnosticsDataType.TransferSubscriptionsCount get set
Definition at line 63557 of file Opc.Ua.DataTypes.cs.
TranslateBrowsePathsToNodeIdsCount
ServiceCounterDataType Opc.Ua.SessionDiagnosticsDataType.TranslateBrowsePathsToNodeIdsCount get set
Definition at line 63733 of file Opc.Ua.DataTypes.cs.
TypeId
virtual ExpandedNodeId Opc.Ua.SessionDiagnosticsDataType.TypeId get
Definition at line 63842 of file Opc.Ua.DataTypes.cs.
UnauthorizedRequestCount
uint Opc.Ua.SessionDiagnosticsDataType.UnauthorizedRequestCount get set
Definition at line 63217 of file Opc.Ua.DataTypes.cs.
UnregisterNodesCount
ServiceCounterDataType Opc.Ua.SessionDiagnosticsDataType.UnregisterNodesCount get set
Definition at line 63821 of file Opc.Ua.DataTypes.cs.
WriteCount
ServiceCounterDataType Opc.Ua.SessionDiagnosticsDataType.WriteCount get set
Definition at line 63271 of file Opc.Ua.DataTypes.cs.
XmlEncodingId
virtual ExpandedNodeId Opc.Ua.SessionDiagnosticsDataType.XmlEncodingId get
Definition at line 63854 of file Opc.Ua.DataTypes.cs.
The documentation for this class was generated from the following file:
Opc.Ua.DataTypes.cs