Project Template: Opc.Ua.MonitoringParameters Class Reference
Opc.Ua.MonitoringParameters Class Reference
Public Member Functions
MonitoringParameters ()
The default constructor.
virtual void Encode (IEncoder encoder)
virtual void Decode (IDecoder decoder)
virtual bool IsEqual (IEncodeable encodeable)
virtual object Clone ()
new object MemberwiseClone ()
Properties
uint ClientHandle [get, set]
double SamplingInterval [get, set]
ExtensionObject Filter [get, set]
uint QueueSize [get, set]
bool DiscardOldest [get, set]
virtual ExpandedNodeId TypeId [get]
virtual ExpandedNodeId BinaryEncodingId [get]
virtual ExpandedNodeId XmlEncodingId [get]
Detailed Description
<exclude>
Definition at line 53123 of file Opc.Ua.DataTypes.cs.
Constructor & Destructor Documentation
MonitoringParameters()
Opc.Ua.MonitoringParameters.MonitoringParameters () inline
The default constructor.
Definition at line 53129 of file Opc.Ua.DataTypes.cs.
Member Function Documentation
Clone()
virtual object Opc.Ua.MonitoringParameters.Clone () inline virtual
Definition at line 53271 of file Opc.Ua.DataTypes.cs.
Referenced by Opc.Ua.MonitoredItemCreateRequest.MemberwiseClone(), and Opc.Ua.MonitoredItemModifyRequest.MemberwiseClone().
Decode()
virtual void Opc.Ua.MonitoringParameters.Decode (IDecoder decoder) inline virtual
Definition at line 53232 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
Encode()
virtual void Opc.Ua.MonitoringParameters.Encode (IEncoder encoder) inline virtual
Definition at line 53218 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
IsEqual()
virtual bool Opc.Ua.MonitoringParameters.IsEqual (IEncodeable encodeable) inline virtual
Definition at line 53246 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Object.
MemberwiseClone()
new object Opc.Ua.MonitoringParameters.MemberwiseClone () inline
Definition at line 53278 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.MonitoringParameters.MemberwiseClone(), and Opc.Ua.Namespaces.OpcUaXsd.
Referenced by Opc.Ua.MonitoringParameters.MemberwiseClone().
Property Documentation
BinaryEncodingId
virtual ExpandedNodeId Opc.Ua.MonitoringParameters.BinaryEncodingId get
Definition at line 53207 of file Opc.Ua.DataTypes.cs.
ClientHandle
uint Opc.Ua.MonitoringParameters.ClientHandle get set
Definition at line 53160 of file Opc.Ua.DataTypes.cs.
DiscardOldest
bool Opc.Ua.MonitoringParameters.DiscardOldest get set
Definition at line 53192 of file Opc.Ua.DataTypes.cs.
Filter
ExtensionObject Opc.Ua.MonitoringParameters.Filter get set
Definition at line 53176 of file Opc.Ua.DataTypes.cs.
QueueSize
uint Opc.Ua.MonitoringParameters.QueueSize get set
Definition at line 53184 of file Opc.Ua.DataTypes.cs.
SamplingInterval
double Opc.Ua.MonitoringParameters.SamplingInterval get set
Definition at line 53168 of file Opc.Ua.DataTypes.cs.
TypeId
virtual ExpandedNodeId Opc.Ua.MonitoringParameters.TypeId get
Definition at line 53201 of file Opc.Ua.DataTypes.cs.
XmlEncodingId
virtual ExpandedNodeId Opc.Ua.MonitoringParameters.XmlEncodingId get
Definition at line 53213 of file Opc.Ua.DataTypes.cs.
The documentation for this class was generated from the following file:
Opc.Ua.DataTypes.cs