Project Template: types.h File Reference
types.h File Reference
Data Structures
struct UA_String
struct UA_DateTimeStruct
struct UA_Guid
struct UA_NodeId
struct UA_ExpandedNodeId
struct UA_QualifiedName
struct UA_LocalizedText
struct UA_NumericRangeDimension
struct UA_NumericRange
struct UA_Variant
struct UA_ExtensionObject
struct UA_DataValue
struct UA_DiagnosticInfo
struct UA_DataTypeMember
struct UA_DataType
struct UA_DataTypeArray
Typedefs
typedef bool UA_Boolean
typedef int8_t UA_SByte
typedef uint8_t UA_Byte
typedef int16_t UA_Int16
typedef uint16_t UA_UInt16
typedef int32_t UA_Int32
typedef uint32_t UA_UInt32
typedef int64_t UA_Int64
typedef uint64_t UA_UInt64
typedef float UA_Float
typedef double UA_Double
typedef uint32_t UA_StatusCode
typedef int64_t UA_DateTime
typedef struct UA_DateTimeStruct UA_DateTimeStruct
typedef UA_String UA_ByteString
typedef UA_String UA_XmlElement
typedef struct UA_DataType UA_DataType
typedef struct UA_DiagnosticInfo UA_DiagnosticInfo
typedef struct UA_DataTypeArray UA_DataTypeArray
Enumerations
enum UA_NodeIdType { UA_NODEIDTYPE_NUMERIC = 0, UA_NODEIDTYPE_STRING = 3, UA_NODEIDTYPE_GUID = 4, UA_NODEIDTYPE_BYTESTRING = 5 }
enum UA_VariantStorageType { UA_VARIANT_DATA, UA_VARIANT_DATA_NODELETE }
enum UA_ExtensionObjectEncoding {
UA_EXTENSIONOBJECT_ENCODED_NOBODY = 0, UA_EXTENSIONOBJECT_ENCODED_BYTESTRING = 1, UA_EXTENSIONOBJECT_ENCODED_XML = 2, UA_EXTENSIONOBJECT_DECODED = 3,
UA_EXTENSIONOBJECT_DECODED_NODELETE = 4
}
enum UA_DataTypeKind {
UA_DATATYPEKIND_BOOLEAN = 0, UA_DATATYPEKIND_SBYTE = 1, UA_DATATYPEKIND_BYTE = 2, UA_DATATYPEKIND_INT16 = 3,
UA_DATATYPEKIND_UINT16 = 4, UA_DATATYPEKIND_INT32 = 5, UA_DATATYPEKIND_UINT32 = 6, UA_DATATYPEKIND_INT64 = 7,
UA_DATATYPEKIND_UINT64 = 8, UA_DATATYPEKIND_FLOAT = 9, UA_DATATYPEKIND_DOUBLE = 10, UA_DATATYPEKIND_STRING = 11,
UA_DATATYPEKIND_DATETIME = 12, UA_DATATYPEKIND_GUID = 13, UA_DATATYPEKIND_BYTESTRING = 14, UA_DATATYPEKIND_XMLELEMENT = 15,
UA_DATATYPEKIND_NODEID = 16, UA_DATATYPEKIND_EXPANDEDNODEID = 17, UA_DATATYPEKIND_STATUSCODE = 18, UA_DATATYPEKIND_QUALIFIEDNAME = 19,
UA_DATATYPEKIND_LOCALIZEDTEXT = 20, UA_DATATYPEKIND_EXTENSIONOBJECT = 21, UA_DATATYPEKIND_DATAVALUE = 22, UA_DATATYPEKIND_VARIANT = 23,
UA_DATATYPEKIND_DIAGNOSTICINFO = 24, UA_DATATYPEKIND_DECIMAL = 25, UA_DATATYPEKIND_ENUM = 26, UA_DATATYPEKIND_STRUCTURE = 27,
UA_DATATYPEKIND_OPTSTRUCT = 28, UA_DATATYPEKIND_UNION = 29, UA_DATATYPEKIND_BITFIELDCLUSTER = 30
}
Functions
UA_EXPORT const char * UA_StatusCode_name (UA_StatusCode code)
UA_String UA_EXPORT UA_String_fromChars (const char *src) UA_FUNC_ATTR_WARN_UNUSED_RESULT
UA_Boolean UA_EXPORT UA_String_equal (const UA_String *s1, const UA_String *s2)
static UA_INLINE UA_String UA_STRING (char *chars)
UA_DateTime UA_EXPORT UA_DateTime_now (void)
UA_Int64 UA_EXPORT UA_DateTime_localTimeUtcOffset (void)
UA_DateTime UA_EXPORT UA_DateTime_nowMonotonic (void)
UA_DateTimeStruct UA_EXPORT UA_DateTime_toStruct (UA_DateTime t)
static UA_INLINE UA_Int64 UA_DateTime_toUnixTime (UA_DateTime date)
static UA_INLINE UA_DateTime UA_DateTime_fromUnixTime (UA_Int64 unixDate)
UA_Boolean UA_EXPORT UA_Guid_equal (const UA_Guid *g1, const UA_Guid *g2)
static UA_INLINE UA_Boolean UA_ByteString_equal (const UA_ByteString *string1, const UA_ByteString *string2)
UA_StatusCode UA_EXPORT UA_ByteString_allocBuffer (UA_ByteString *bs, size_t length)
static UA_INLINE UA_ByteString UA_BYTESTRING (char *chars)
static UA_INLINE UA_ByteString UA_BYTESTRING_ALLOC (const char *chars)
UA_Boolean UA_EXPORT UA_NodeId_isNull (const UA_NodeId *p)
UA_Order UA_EXPORT UA_NodeId_order (const UA_NodeId *n1, const UA_NodeId *n2)
static UA_INLINE UA_Boolean UA_NodeId_equal (const UA_NodeId *n1, const UA_NodeId *n2)
UA_UInt32 UA_EXPORT UA_NodeId_hash (const UA_NodeId *n)
static UA_INLINE UA_NodeId UA_NODEID_NUMERIC (UA_UInt16 nsIndex, UA_UInt32 identifier)
static UA_INLINE UA_NodeId UA_NODEID_STRING (UA_UInt16 nsIndex, char *chars)
static UA_INLINE UA_NodeId UA_NODEID_STRING_ALLOC (UA_UInt16 nsIndex, const char *chars)
static UA_INLINE UA_NodeId UA_NODEID_GUID (UA_UInt16 nsIndex, UA_Guid guid)
static UA_INLINE UA_NodeId UA_NODEID_BYTESTRING (UA_UInt16 nsIndex, char *chars)
static UA_INLINE UA_NodeId UA_NODEID_BYTESTRING_ALLOC (UA_UInt16 nsIndex, const char *chars)
UA_Order UA_EXPORT UA_ExpandedNodeId_order (const UA_ExpandedNodeId *n1, const UA_ExpandedNodeId *n2)
static UA_INLINE UA_Boolean UA_ExpandedNodeId_equal (const UA_ExpandedNodeId *n1, const UA_ExpandedNodeId *n2)
UA_UInt32 UA_EXPORT UA_ExpandedNodeId_hash (const UA_ExpandedNodeId *n)
static UA_INLINE UA_ExpandedNodeId UA_EXPANDEDNODEID_NUMERIC (UA_UInt16 nsIndex, UA_UInt32 identifier)
static UA_INLINE UA_ExpandedNodeId UA_EXPANDEDNODEID_STRING (UA_UInt16 nsIndex, char *chars)
static UA_INLINE UA_ExpandedNodeId UA_EXPANDEDNODEID_STRING_ALLOC (UA_UInt16 nsIndex, const char *chars)
static UA_INLINE UA_ExpandedNodeId UA_EXPANDEDNODEID_STRING_GUID (UA_UInt16 nsIndex, UA_Guid guid)
static UA_INLINE UA_ExpandedNodeId UA_EXPANDEDNODEID_BYTESTRING (UA_UInt16 nsIndex, char *chars)
static UA_INLINE UA_ExpandedNodeId UA_EXPANDEDNODEID_BYTESTRING_ALLOC (UA_UInt16 nsIndex, const char *chars)
static UA_INLINE UA_Boolean UA_QualifiedName_isNull (const UA_QualifiedName *q)
static UA_INLINE UA_QualifiedName UA_QUALIFIEDNAME (UA_UInt16 nsIndex, char *chars)
static UA_INLINE UA_QualifiedName UA_QUALIFIEDNAME_ALLOC (UA_UInt16 nsIndex, const char *chars)
UA_Boolean UA_EXPORT UA_QualifiedName_equal (const UA_QualifiedName *qn1, const UA_QualifiedName *qn2)
static UA_INLINE UA_LocalizedText UA_LOCALIZEDTEXT (char *locale, char *text)
static UA_INLINE UA_LocalizedText UA_LOCALIZEDTEXT_ALLOC (const char *locale, const char *text)
UA_StatusCode UA_EXPORT UA_NumericRange_parseFromString (UA_NumericRange *range, const UA_String *str)
static UA_INLINE UA_Boolean UA_Variant_isEmpty (const UA_Variant *v)
static UA_INLINE UA_Boolean UA_Variant_isScalar (const UA_Variant *v)
static UA_INLINE UA_Boolean UA_Variant_hasScalarType (const UA_Variant *v, const UA_DataType *type)
static UA_INLINE UA_Boolean UA_Variant_hasArrayType (const UA_Variant *v, const UA_DataType *type)
void UA_EXPORT UA_Variant_setScalar (UA_Variant *v, void *UA_RESTRICT p, const UA_DataType *type)
UA_StatusCode UA_EXPORT UA_Variant_setScalarCopy (UA_Variant *v, const void *p, const UA_DataType *type)
void UA_EXPORT UA_Variant_setArray (UA_Variant *v, void *UA_RESTRICT array, size_t arraySize, const UA_DataType *type)
UA_StatusCode UA_EXPORT UA_Variant_setArrayCopy (UA_Variant *v, const void *array, size_t arraySize, const UA_DataType *type)
UA_StatusCode UA_EXPORT UA_Variant_copyRange (const UA_Variant *src, UA_Variant *dst, const UA_NumericRange range)
UA_StatusCode UA_EXPORT UA_Variant_setRange (UA_Variant *v, void *UA_RESTRICT array, size_t arraySize, const UA_NumericRange range)
UA_StatusCode UA_EXPORT UA_Variant_setRangeCopy (UA_Variant *v, const void *array, size_t arraySize, const UA_NumericRange range)
UA_Boolean UA_DataType_isNumeric (const UA_DataType *type)
const UA_DataType UA_EXPORT * UA_findDataType (const UA_NodeId *typeId)
void UA_EXPORT * UA_new (const UA_DataType *type) UA_FUNC_ATTR_MALLOC
static UA_INLINE void UA_init (void *p, const UA_DataType *type)
UA_StatusCode UA_EXPORT UA_copy (const void *src, void *dst, const UA_DataType *type)
void UA_EXPORT UA_clear (void *p, const UA_DataType *type)
void UA_EXPORT UA_delete (void *p, const UA_DataType *type)
void UA_EXPORT * UA_Array_new (size_t size, const UA_DataType *type) UA_FUNC_ATTR_MALLOC
UA_StatusCode UA_EXPORT UA_Array_copy (const void *src, size_t size, void **dst, const UA_DataType *type) UA_FUNC_ATTR_WARN_UNUSED_RESULT
void UA_EXPORT UA_Array_delete (void *p, size_t size, const UA_DataType *type)
void UA_EXPORT UA_random_seed (UA_UInt64 seed)
UA_UInt32 UA_EXPORT UA_UInt32_random (void)
UA_Guid UA_EXPORT UA_Guid_random (void)
Variables
UA_EXPORT const UA_String UA_STRING_NULL
UA_EXPORT const UA_Guid UA_GUID_NULL
UA_EXPORT const UA_ByteString UA_BYTESTRING_NULL
UA_EXPORT const UA_NodeId UA_NODEID_NULL
UA_EXPORT const UA_ExpandedNodeId UA_EXPANDEDNODEID_NULL
Typedef Documentation
UA_Boolean
typedef bool UA_Boolean
.. _types:
Data Types
The OPC UA protocol defines 25 builtin data types and three ways of combining them into higher-order types: arrays, structures and unions. In open62541, only the builtin data types are defined manually. All other data types are generated from standard XML definitions. Their exact definitions can be looked up at https://opcfoundation.org/UA/schemas/Opc.Ua.Types.bsd.
For users that are new to open62541, take a look at the :ref:tutorial for working with data types<types-tutorial> before diving into the implementation details.
Builtin Types
Boolean ^^^^^^^ A two-state logical value (true or false).
Definition at line 49 of file types.h.
UA_Byte
typedef uint8_t UA_Byte
Byte ^^^^ An integer value between 0 and 255.
Definition at line 65 of file types.h.
UA_ByteString
typedef UA_String UA_ByteString
ByteString ^^^^^^^^^^ A sequence of octets.
Definition at line 262 of file types.h.
UA_DataType
typedef struct UA_DataType UA_DataType
Definition at line 555 of file types.h.
UA_DataTypeArray
typedef struct UA_DataTypeArray UA_DataTypeArray
UA_DateTime
typedef int64_t UA_DateTime
.. _datetime:
DateTime ^^^^^^^^ An instance in time. A DateTime value is encoded as a 64-bit signed integer which represents the number of 100 nanosecond intervals since January 1, 1601 (UTC).
The methods providing an interface to the system clock are provided by a "plugin" that is statically linked with the library.
Definition at line 193 of file types.h.
UA_DateTimeStruct
typedef struct UA_DateTimeStruct UA_DateTimeStruct
UA_DiagnosticInfo
typedef struct UA_DiagnosticInfo UA_DiagnosticInfo
DiagnosticInfo ^^^^^^^^^^^^^^ A structure that contains detailed error and diagnostic information associated with a StatusCode.
UA_Double
typedef double UA_Double
Double ^^^^^^ An IEEE double precision (64 bit) floating point value.
Definition at line 128 of file types.h.
UA_Float
typedef float UA_Float
Float ^^^^^ An IEEE single precision (32 bit) floating point value.
Definition at line 122 of file types.h.
UA_Int16
typedef int16_t UA_Int16
Int16 ^^^^^ An integer value between -32 768 and 32 767.
Definition at line 73 of file types.h.
UA_Int32
typedef int32_t UA_Int32
Int32 ^^^^^ An integer value between -2 147 483 648 and 2 147 483 647.
Definition at line 89 of file types.h.
UA_Int64
typedef int64_t UA_Int64
Int64 ^^^^^ An integer value between -9 223 372 036 854 775 808 and 9 223 372 036 854 775 807.
Definition at line 106 of file types.h.
UA_SByte
typedef int8_t UA_SByte
SByte ^^^^^ An integer value between -128 and 127.
Definition at line 57 of file types.h.
UA_StatusCode
typedef uint32_t UA_StatusCode
.. _statuscode:
StatusCode ^^^^^^^^^^ A numeric identifier for a error or condition that is associated with a value or an operation. See the section :ref:statuscodes for the meaning of a specific code.
Definition at line 138 of file types.h.
UA_UInt16
typedef uint16_t UA_UInt16
UInt16 ^^^^^^ An integer value between 0 and 65 535.
Definition at line 81 of file types.h.
UA_UInt32
typedef uint32_t UA_UInt32
UInt32 ^^^^^^ An integer value between 0 and 4 294 967 295.
Definition at line 97 of file types.h.
UA_UInt64
typedef uint64_t UA_UInt64
UInt64 ^^^^^^ An integer value between 0 and 18 446 744 073 709 551 615.
Definition at line 114 of file types.h.
UA_XmlElement
typedef UA_String UA_XmlElement
XmlElement ^^^^^^^^^^ An XML element.
Definition at line 296 of file types.h.
Enumeration Type Documentation
UA_DataTypeKind
enum UA_DataTypeKind
Enumerator
UA_DATATYPEKIND_BOOLEAN
UA_DATATYPEKIND_SBYTE
UA_DATATYPEKIND_BYTE
UA_DATATYPEKIND_INT16
UA_DATATYPEKIND_UINT16
UA_DATATYPEKIND_INT32
UA_DATATYPEKIND_UINT32
UA_DATATYPEKIND_INT64
UA_DATATYPEKIND_UINT64
UA_DATATYPEKIND_FLOAT
UA_DATATYPEKIND_DOUBLE
UA_DATATYPEKIND_STRING
UA_DATATYPEKIND_DATETIME
UA_DATATYPEKIND_GUID
UA_DATATYPEKIND_BYTESTRING
UA_DATATYPEKIND_XMLELEMENT
UA_DATATYPEKIND_NODEID
UA_DATATYPEKIND_EXPANDEDNODEID
UA_DATATYPEKIND_STATUSCODE
UA_DATATYPEKIND_QUALIFIEDNAME
UA_DATATYPEKIND_LOCALIZEDTEXT
UA_DATATYPEKIND_EXTENSIONOBJECT
UA_DATATYPEKIND_DATAVALUE
UA_DATATYPEKIND_VARIANT
UA_DATATYPEKIND_DIAGNOSTICINFO
UA_DATATYPEKIND_DECIMAL
UA_DATATYPEKIND_ENUM
UA_DATATYPEKIND_STRUCTURE
UA_DATATYPEKIND_OPTSTRUCT
UA_DATATYPEKIND_UNION
UA_DATATYPEKIND_BITFIELDCLUSTER
Definition at line 820 of file types.h.
UA_ExtensionObjectEncoding
enum UA_ExtensionObjectEncoding
.. _extensionobject:
ExtensionObject ^^^^^^^^^^^^^^^
ExtensionObjects may contain scalars of any data type. Even those that are unknown to the receiver. See the section on :ref:generic-types on how types are described. If the received data type is unknown, the encoded string and target NodeId is stored instead of the decoded value.
Enumerator
UA_EXTENSIONOBJECT_ENCODED_NOBODY
UA_EXTENSIONOBJECT_ENCODED_BYTESTRING
UA_EXTENSIONOBJECT_ENCODED_XML
UA_EXTENSIONOBJECT_DECODED
UA_EXTENSIONOBJECT_DECODED_NODELETE
Definition at line 705 of file types.h.
UA_NodeIdType
enum UA_NodeIdType
.. _nodeid:
NodeId ^^^^^^ An identifier for a node in the address space of an OPC UA Server.
Enumerator
UA_NODEIDTYPE_NUMERIC
UA_NODEIDTYPE_STRING
UA_NODEIDTYPE_GUID
UA_NODEIDTYPE_BYTESTRING
Definition at line 304 of file types.h.
UA_VariantStorageType
enum UA_VariantStorageType
Enumerator
UA_VARIANT_DATA
UA_VARIANT_DATA_NODELETE
Definition at line 559 of file types.h.
Function Documentation
UA_Array_copy()
UA_StatusCode UA_EXPORT UA_Array_copy (const void * src, size_t size, void ** dst, const UA_DataType * type)
Referenced by UA_init().
UA_Array_delete()
void UA_EXPORT UA_Array_delete (void * p, size_t size, const UA_DataType * type)
Referenced by UA_init().
UA_Array_new()
void UA_EXPORT* UA_Array_new (size_t size, const UA_DataType * type)
.. _array-handling:
Array handling
In OPC UA, arrays can have a length of zero or more with the usual meaning. In addition, arrays can be undefined. Then, they don't even have a length. In the binary encoding, this is indicated by an array of length -1.
In open62541 however, we use size_t for array lengths. An undefined array has length 0 and the data pointer is NULL. An array of length 0 also has length 0 but a data pointer UA_EMPTY_ARRAY_SENTINEL.
Referenced by UA_init().
UA_BYTESTRING()
static UA_INLINE UA_ByteString UA_BYTESTRING (char * chars) static
Definition at line 279 of file types.h.
References UA_String::data, and UA_String::length.
Referenced by UA_NODEID_BYTESTRING().
UA_BYTESTRING_ALLOC()
static UA_INLINE UA_ByteString UA_BYTESTRING_ALLOC (const char * chars) static
Definition at line 287 of file types.h.
References UA_String::data, UA_String::length, and UA_String_fromChars().
Referenced by UA_NODEID_BYTESTRING_ALLOC().
UA_ByteString_allocBuffer()
UA_StatusCode UA_EXPORT UA_ByteString_allocBuffer (UA_ByteString * bs, size_t length)
Referenced by UA_ByteString_equal().
UA_ByteString_equal()
static UA_INLINE UA_Boolean UA_ByteString_equal (const UA_ByteString * string1, const UA_ByteString * string2) static
Definition at line 265 of file types.h.
References UA_ByteString_allocBuffer(), UA_BYTESTRING_NULL, and UA_String_equal().
UA_clear()
void UA_EXPORT UA_clear (void * p, const UA_DataType * type)
Referenced by UA_ActivateSessionRequest_clear(), UA_ActivateSessionRequest_deleteMembers(), UA_ActivateSessionResponse_clear(), UA_ActivateSessionResponse_deleteMembers(), UA_AddNodesItem_clear(), UA_AddNodesItem_deleteMembers(), UA_AddNodesRequest_clear(), UA_AddNodesRequest_deleteMembers(), UA_AddNodesResponse_clear(), UA_AddNodesResponse_deleteMembers(), UA_AddNodesResult_clear(), UA_AddNodesResult_deleteMembers(), UA_AddReferencesItem_clear(), UA_AddReferencesItem_deleteMembers(), UA_AddReferencesRequest_clear(), UA_AddReferencesRequest_deleteMembers(), UA_AddReferencesResponse_clear(), UA_AddReferencesResponse_deleteMembers(), UA_AggregateFilter_clear(), UA_AggregateFilter_deleteMembers(), UA_AnonymousIdentityToken_clear(), UA_AnonymousIdentityToken_deleteMembers(), UA_ApplicationDescription_clear(), UA_ApplicationDescription_deleteMembers(), UA_Argument_clear(), UA_Argument_deleteMembers(), UA_AsymmetricAlgorithmSecurityHeader_clear(), UA_AsymmetricAlgorithmSecurityHeader_deleteMembers(), UA_AttributeOperand_clear(), UA_AttributeOperand_deleteMembers(), UA_BrowseDescription_clear(), UA_BrowseDescription_deleteMembers(), UA_BrowseNextRequest_clear(), UA_BrowseNextRequest_deleteMembers(), UA_BrowseNextResponse_clear(), UA_BrowseNextResponse_deleteMembers(), UA_BrowsePath_clear(), UA_BrowsePath_deleteMembers(), UA_BrowsePathResult_clear(), UA_BrowsePathResult_deleteMembers(), UA_BrowsePathTarget_clear(), UA_BrowsePathTarget_deleteMembers(), UA_BrowseRequest_clear(), UA_BrowseRequest_deleteMembers(), UA_BrowseResponse_clear(), UA_BrowseResponse_deleteMembers(), UA_BrowseResult_clear(), UA_BrowseResult_deleteMembers(), UA_BuildInfo_clear(), UA_BuildInfo_deleteMembers(), UA_ByteString_clear(), UA_ByteString_deleteMembers(), UA_CallMethodRequest_clear(), UA_CallMethodRequest_deleteMembers(), UA_CallMethodResult_clear(), UA_CallMethodResult_deleteMembers(), UA_CallRequest_clear(), UA_CallRequest_deleteMembers(), UA_CallResponse_clear(), UA_CallResponse_deleteMembers(), UA_CloseSecureChannelRequest_clear(), UA_CloseSecureChannelRequest_deleteMembers(), UA_CloseSecureChannelResponse_clear(), UA_CloseSecureChannelResponse_deleteMembers(), UA_CloseSessionRequest_clear(), UA_CloseSessionRequest_deleteMembers(), UA_CloseSessionResponse_clear(), UA_CloseSessionResponse_deleteMembers(), UA_ContentFilter_clear(), UA_ContentFilter_deleteMembers(), UA_ContentFilterElement_clear(), UA_ContentFilterElement_deleteMembers(), UA_ContentFilterElementResult_clear(), UA_ContentFilterElementResult_deleteMembers(), UA_ContentFilterResult_clear(), UA_ContentFilterResult_deleteMembers(), UA_CreateMonitoredItemsRequest_clear(), UA_CreateMonitoredItemsRequest_deleteMembers(), UA_CreateMonitoredItemsResponse_clear(), UA_CreateMonitoredItemsResponse_deleteMembers(), UA_CreateSessionRequest_clear(), UA_CreateSessionRequest_deleteMembers(), UA_CreateSessionResponse_clear(), UA_CreateSessionResponse_deleteMembers(), UA_CreateSubscriptionRequest_clear(), UA_CreateSubscriptionRequest_deleteMembers(), UA_CreateSubscriptionResponse_clear(), UA_CreateSubscriptionResponse_deleteMembers(), UA_DataChangeNotification_clear(), UA_DataChangeNotification_deleteMembers(), UA_DataTypeAttributes_clear(), UA_DataTypeAttributes_deleteMembers(), UA_DataValue_clear(), UA_DataValue_deleteMembers(), UA_DeleteMonitoredItemsRequest_clear(), UA_DeleteMonitoredItemsRequest_deleteMembers(), UA_DeleteMonitoredItemsResponse_clear(), UA_DeleteMonitoredItemsResponse_deleteMembers(), UA_DeleteNodesItem_clear(), UA_DeleteNodesItem_deleteMembers(), UA_DeleteNodesRequest_clear(), UA_DeleteNodesRequest_deleteMembers(), UA_DeleteNodesResponse_clear(), UA_DeleteNodesResponse_deleteMembers(), UA_DeleteReferencesItem_clear(), UA_DeleteReferencesItem_deleteMembers(), UA_DeleteReferencesRequest_clear(), UA_DeleteReferencesRequest_deleteMembers(), UA_DeleteReferencesResponse_clear(), UA_DeleteReferencesResponse_deleteMembers(), UA_DeleteSubscriptionsRequest_clear(), UA_DeleteSubscriptionsRequest_deleteMembers(), UA_DeleteSubscriptionsResponse_clear(), UA_DeleteSubscriptionsResponse_deleteMembers(), UA_DiagnosticInfo_clear(), UA_DiagnosticInfo_deleteMembers(), UA_Duration_clear(), UA_Duration_deleteMembers(), UA_EndpointDescription_clear(), UA_EndpointDescription_deleteMembers(), UA_EnumValueType_clear(), UA_EnumValueType_deleteMembers(), UA_EventFieldList_clear(), UA_EventFieldList_deleteMembers(), UA_EventFilter_clear(), UA_EventFilter_deleteMembers(), UA_EventFilterResult_clear(), UA_EventFilterResult_deleteMembers(), UA_EventNotificationList_clear(), UA_EventNotificationList_deleteMembers(), UA_ExpandedNodeId_clear(), UA_ExpandedNodeId_deleteMembers(), UA_ExtensionObject_clear(), UA_ExtensionObject_deleteMembers(), UA_FindServersOnNetworkRequest_clear(), UA_FindServersOnNetworkRequest_deleteMembers(), UA_FindServersOnNetworkResponse_clear(), UA_FindServersOnNetworkResponse_deleteMembers(), UA_FindServersRequest_clear(), UA_FindServersRequest_deleteMembers(), UA_FindServersResponse_clear(), UA_FindServersResponse_deleteMembers(), UA_GetEndpointsRequest_clear(), UA_GetEndpointsRequest_deleteMembers(), UA_GetEndpointsResponse_clear(), UA_GetEndpointsResponse_deleteMembers(), UA_init(), UA_IssuedIdentityToken_clear(), UA_IssuedIdentityToken_deleteMembers(), UA_LiteralOperand_clear(), UA_LiteralOperand_deleteMembers(), UA_LocaleId_clear(), UA_LocaleId_deleteMembers(), UA_LocalizedText_clear(), UA_LocalizedText_deleteMembers(), UA_MdnsDiscoveryConfiguration_clear(), UA_MdnsDiscoveryConfiguration_deleteMembers(), UA_MethodAttributes_clear(), UA_MethodAttributes_deleteMembers(), UA_ModifyMonitoredItemsRequest_clear(), UA_ModifyMonitoredItemsRequest_deleteMembers(), UA_ModifyMonitoredItemsResponse_clear(), UA_ModifyMonitoredItemsResponse_deleteMembers(), UA_ModifySubscriptionRequest_clear(), UA_ModifySubscriptionRequest_deleteMembers(), UA_ModifySubscriptionResponse_clear(), UA_ModifySubscriptionResponse_deleteMembers(), UA_MonitoredItemCreateRequest_clear(), UA_MonitoredItemCreateRequest_deleteMembers(), UA_MonitoredItemCreateResult_clear(), UA_MonitoredItemCreateResult_deleteMembers(), UA_MonitoredItemModifyRequest_clear(), UA_MonitoredItemModifyRequest_deleteMembers(), UA_MonitoredItemModifyResult_clear(), UA_MonitoredItemModifyResult_deleteMembers(), UA_MonitoredItemNotification_clear(), UA_MonitoredItemNotification_deleteMembers(), UA_MonitoringParameters_clear(), UA_MonitoringParameters_deleteMembers(), UA_NodeAttributes_clear(), UA_NodeAttributes_deleteMembers(), UA_NodeId_clear(), UA_NodeId_deleteMembers(), UA_NotificationMessage_clear(), UA_NotificationMessage_deleteMembers(), UA_ObjectAttributes_clear(), UA_ObjectAttributes_deleteMembers(), UA_ObjectTypeAttributes_clear(), UA_ObjectTypeAttributes_deleteMembers(), UA_OpenSecureChannelRequest_clear(), UA_OpenSecureChannelRequest_deleteMembers(), UA_OpenSecureChannelResponse_clear(), UA_OpenSecureChannelResponse_deleteMembers(), UA_PublishRequest_clear(), UA_PublishRequest_deleteMembers(), UA_PublishResponse_clear(), UA_PublishResponse_deleteMembers(), UA_QualifiedName_clear(), UA_QualifiedName_deleteMembers(), UA_ReadRequest_clear(), UA_ReadRequest_deleteMembers(), UA_ReadResponse_clear(), UA_ReadResponse_deleteMembers(), UA_ReadValueId_clear(), UA_ReadValueId_deleteMembers(), UA_ReferenceDescription_clear(), UA_ReferenceDescription_deleteMembers(), UA_ReferenceTypeAttributes_clear(), UA_ReferenceTypeAttributes_deleteMembers(), UA_RegisteredServer_clear(), UA_RegisteredServer_deleteMembers(), UA_RegisterNodesRequest_clear(), UA_RegisterNodesRequest_deleteMembers(), UA_RegisterNodesResponse_clear(), UA_RegisterNodesResponse_deleteMembers(), UA_RegisterServer2Request_clear(), UA_RegisterServer2Request_deleteMembers(), UA_RegisterServer2Response_clear(), UA_RegisterServer2Response_deleteMembers(), UA_RegisterServerRequest_clear(), UA_RegisterServerRequest_deleteMembers(), UA_RegisterServerResponse_clear(), UA_RegisterServerResponse_deleteMembers(), UA_RelativePath_clear(), UA_RelativePath_deleteMembers(), UA_RelativePathElement_clear(), UA_RelativePathElement_deleteMembers(), UA_RepublishRequest_clear(), UA_RepublishRequest_deleteMembers(), UA_RepublishResponse_clear(), UA_RepublishResponse_deleteMembers(), UA_RequestHeader_clear(), UA_RequestHeader_deleteMembers(), UA_ResponseHeader_clear(), UA_ResponseHeader_deleteMembers(), UA_SecureConversationMessageAbortBody_clear(), UA_SecureConversationMessageAbortBody_deleteMembers(), UA_SecureConversationMessageFooter_clear(), UA_SecureConversationMessageFooter_deleteMembers(), UA_ServerOnNetwork_clear(), UA_ServerOnNetwork_deleteMembers(), UA_ServerStatusDataType_clear(), UA_ServerStatusDataType_deleteMembers(), UA_ServiceFault_clear(), UA_ServiceFault_deleteMembers(), UA_SetMonitoringModeRequest_clear(), UA_SetMonitoringModeRequest_deleteMembers(), UA_SetMonitoringModeResponse_clear(), UA_SetMonitoringModeResponse_deleteMembers(), UA_SetPublishingModeRequest_clear(), UA_SetPublishingModeRequest_deleteMembers(), UA_SetPublishingModeResponse_clear(), UA_SetPublishingModeResponse_deleteMembers(), UA_SetTriggeringRequest_clear(), UA_SetTriggeringRequest_deleteMembers(), UA_SetTriggeringResponse_clear(), UA_SetTriggeringResponse_deleteMembers(), UA_SignatureData_clear(), UA_SignatureData_deleteMembers(), UA_SignedSoftwareCertificate_clear(), UA_SignedSoftwareCertificate_deleteMembers(), UA_SimpleAttributeOperand_clear(), UA_SimpleAttributeOperand_deleteMembers(), UA_StatusChangeNotification_clear(), UA_StatusChangeNotification_deleteMembers(), UA_String_clear(), UA_String_deleteMembers(), UA_TcpErrorMessage_clear(), UA_TcpErrorMessage_deleteMembers(), UA_TcpHelloMessage_clear(), UA_TcpHelloMessage_deleteMembers(), UA_TranslateBrowsePathsToNodeIdsRequest_clear(), UA_TranslateBrowsePathsToNodeIdsRequest_deleteMembers(), UA_TranslateBrowsePathsToNodeIdsResponse_clear(), UA_TranslateBrowsePathsToNodeIdsResponse_deleteMembers(), UA_UnregisterNodesRequest_clear(), UA_UnregisterNodesRequest_deleteMembers(), UA_UnregisterNodesResponse_clear(), UA_UnregisterNodesResponse_deleteMembers(), UA_UserIdentityToken_clear(), UA_UserIdentityToken_deleteMembers(), UA_UserNameIdentityToken_clear(), UA_UserNameIdentityToken_deleteMembers(), UA_UserTokenPolicy_clear(), UA_UserTokenPolicy_deleteMembers(), UA_UtcTime_clear(), UA_UtcTime_deleteMembers(), UA_VariableAttributes_clear(), UA_VariableAttributes_deleteMembers(), UA_VariableTypeAttributes_clear(), UA_VariableTypeAttributes_deleteMembers(), UA_Variant_clear(), UA_Variant_deleteMembers(), UA_ViewAttributes_clear(), UA_ViewAttributes_deleteMembers(), UA_ViewDescription_clear(), UA_ViewDescription_deleteMembers(), UA_WriteRequest_clear(), UA_WriteRequest_deleteMembers(), UA_WriteResponse_clear(), UA_WriteResponse_deleteMembers(), UA_WriteValue_clear(), UA_WriteValue_deleteMembers(), UA_X509IdentityToken_clear(), UA_X509IdentityToken_deleteMembers(), UA_XmlElement_clear(), and UA_XmlElement_deleteMembers().
UA_copy()
UA_StatusCode UA_EXPORT UA_copy (const void * src, void * dst, const UA_DataType * type)
Referenced by UA_ActivateSessionRequest_copy(), UA_ActivateSessionResponse_copy(), UA_AddNodesItem_copy(), UA_AddNodesRequest_copy(), UA_AddNodesResponse_copy(), UA_AddNodesResult_copy(), UA_AddReferencesItem_copy(), UA_AddReferencesRequest_copy(), UA_AddReferencesResponse_copy(), UA_AggregateFilter_copy(), UA_AnonymousIdentityToken_copy(), UA_ApplicationDescription_copy(), UA_Argument_copy(), UA_AsymmetricAlgorithmSecurityHeader_copy(), UA_AttributeOperand_copy(), UA_BrowseDescription_copy(), UA_BrowseNextRequest_copy(), UA_BrowseNextResponse_copy(), UA_BrowsePath_copy(), UA_BrowsePathResult_copy(), UA_BrowsePathTarget_copy(), UA_BrowseRequest_copy(), UA_BrowseResponse_copy(), UA_BrowseResult_copy(), UA_BuildInfo_copy(), UA_ByteString_copy(), UA_CallMethodRequest_copy(), UA_CallMethodResult_copy(), UA_CallRequest_copy(), UA_CallResponse_copy(), UA_CloseSecureChannelRequest_copy(), UA_CloseSecureChannelResponse_copy(), UA_CloseSessionRequest_copy(), UA_CloseSessionResponse_copy(), UA_ContentFilter_copy(), UA_ContentFilterElement_copy(), UA_ContentFilterElementResult_copy(), UA_ContentFilterResult_copy(), UA_CreateMonitoredItemsRequest_copy(), UA_CreateMonitoredItemsResponse_copy(), UA_CreateSessionRequest_copy(), UA_CreateSessionResponse_copy(), UA_CreateSubscriptionRequest_copy(), UA_CreateSubscriptionResponse_copy(), UA_DataChangeNotification_copy(), UA_DataTypeAttributes_copy(), UA_DataValue_copy(), UA_DeleteMonitoredItemsRequest_copy(), UA_DeleteMonitoredItemsResponse_copy(), UA_DeleteNodesItem_copy(), UA_DeleteNodesRequest_copy(), UA_DeleteNodesResponse_copy(), UA_DeleteReferencesItem_copy(), UA_DeleteReferencesRequest_copy(), UA_DeleteReferencesResponse_copy(), UA_DeleteSubscriptionsRequest_copy(), UA_DeleteSubscriptionsResponse_copy(), UA_DiagnosticInfo_copy(), UA_Duration_copy(), UA_EndpointDescription_copy(), UA_EnumValueType_copy(), UA_EventFieldList_copy(), UA_EventFilter_copy(), UA_EventFilterResult_copy(), UA_EventNotificationList_copy(), UA_ExpandedNodeId_copy(), UA_ExtensionObject_copy(), UA_FindServersOnNetworkRequest_copy(), UA_FindServersOnNetworkResponse_copy(), UA_FindServersRequest_copy(), UA_FindServersResponse_copy(), UA_GetEndpointsRequest_copy(), UA_GetEndpointsResponse_copy(), UA_init(), UA_IssuedIdentityToken_copy(), UA_LiteralOperand_copy(), UA_LocaleId_copy(), UA_LocalizedText_copy(), UA_MdnsDiscoveryConfiguration_copy(), UA_MethodAttributes_copy(), UA_ModifyMonitoredItemsRequest_copy(), UA_ModifyMonitoredItemsResponse_copy(), UA_ModifySubscriptionRequest_copy(), UA_ModifySubscriptionResponse_copy(), UA_MonitoredItemCreateRequest_copy(), UA_MonitoredItemCreateResult_copy(), UA_MonitoredItemModifyRequest_copy(), UA_MonitoredItemModifyResult_copy(), UA_MonitoredItemNotification_copy(), UA_MonitoringParameters_copy(), UA_NodeAttributes_copy(), UA_NodeId_copy(), UA_NotificationMessage_copy(), UA_ObjectAttributes_copy(), UA_ObjectTypeAttributes_copy(), UA_OpenSecureChannelRequest_copy(), UA_OpenSecureChannelResponse_copy(), UA_PublishRequest_copy(), UA_PublishResponse_copy(), UA_QualifiedName_copy(), UA_ReadRequest_copy(), UA_ReadResponse_copy(), UA_ReadValueId_copy(), UA_ReferenceDescription_copy(), UA_ReferenceTypeAttributes_copy(), UA_RegisteredServer_copy(), UA_RegisterNodesRequest_copy(), UA_RegisterNodesResponse_copy(), UA_RegisterServer2Request_copy(), UA_RegisterServer2Response_copy(), UA_RegisterServerRequest_copy(), UA_RegisterServerResponse_copy(), UA_RelativePath_copy(), UA_RelativePathElement_copy(), UA_RepublishRequest_copy(), UA_RepublishResponse_copy(), UA_RequestHeader_copy(), UA_ResponseHeader_copy(), UA_SecureConversationMessageAbortBody_copy(), UA_SecureConversationMessageFooter_copy(), UA_ServerOnNetwork_copy(), UA_ServerStatusDataType_copy(), UA_ServiceFault_copy(), UA_SetMonitoringModeRequest_copy(), UA_SetMonitoringModeResponse_copy(), UA_SetPublishingModeRequest_copy(), UA_SetPublishingModeResponse_copy(), UA_SetTriggeringRequest_copy(), UA_SetTriggeringResponse_copy(), UA_SignatureData_copy(), UA_SignedSoftwareCertificate_copy(), UA_SimpleAttributeOperand_copy(), UA_StatusChangeNotification_copy(), UA_String_copy(), UA_TcpErrorMessage_copy(), UA_TcpHelloMessage_copy(), UA_TranslateBrowsePathsToNodeIdsRequest_copy(), UA_TranslateBrowsePathsToNodeIdsResponse_copy(), UA_UnregisterNodesRequest_copy(), UA_UnregisterNodesResponse_copy(), UA_UserIdentityToken_copy(), UA_UserNameIdentityToken_copy(), UA_UserTokenPolicy_copy(), UA_UtcTime_copy(), UA_VariableAttributes_copy(), UA_VariableTypeAttributes_copy(), UA_Variant_copy(), UA_ViewAttributes_copy(), UA_ViewDescription_copy(), UA_WriteRequest_copy(), UA_WriteResponse_copy(), UA_WriteValue_copy(), UA_X509IdentityToken_copy(), and UA_XmlElement_copy().
UA_DataType_isNumeric()
UA_Boolean UA_DataType_isNumeric (const UA_DataType * type)
UA_DateTime_fromUnixTime()
static UA_INLINE UA_DateTime UA_DateTime_fromUnixTime (UA_Int64 unixDate) static
Definition at line 239 of file types.h.
UA_DateTime_localTimeUtcOffset()
UA_Int64 UA_EXPORT UA_DateTime_localTimeUtcOffset (void)
UA_DateTime_now()
UA_DateTime UA_EXPORT UA_DateTime_now (void)
UA_DateTime_nowMonotonic()
UA_DateTime UA_EXPORT UA_DateTime_nowMonotonic (void)
UA_DateTime_toStruct()
UA_DateTimeStruct UA_EXPORT UA_DateTime_toStruct (UA_DateTime t)
UA_DateTime_toUnixTime()
static UA_INLINE UA_Int64 UA_DateTime_toUnixTime (UA_DateTime date) static
Definition at line 234 of file types.h.
UA_delete()
void UA_EXPORT UA_delete (void * p, const UA_DataType * type)
Referenced by UA_ActivateSessionRequest_delete(), UA_ActivateSessionResponse_delete(), UA_AddNodesItem_delete(), UA_AddNodesRequest_delete(), UA_AddNodesResponse_delete(), UA_AddNodesResult_delete(), UA_AddReferencesItem_delete(), UA_AddReferencesRequest_delete(), UA_AddReferencesResponse_delete(), UA_AggregateConfiguration_delete(), UA_AggregateFilter_delete(), UA_AnonymousIdentityToken_delete(), UA_ApplicationDescription_delete(), UA_ApplicationType_delete(), UA_Argument_delete(), UA_AsymmetricAlgorithmSecurityHeader_delete(), UA_AttributeOperand_delete(), UA_Boolean_delete(), UA_BrowseDescription_delete(), UA_BrowseDirection_delete(), UA_BrowseNextRequest_delete(), UA_BrowseNextResponse_delete(), UA_BrowsePath_delete(), UA_BrowsePathResult_delete(), UA_BrowsePathTarget_delete(), UA_BrowseRequest_delete(), UA_BrowseResponse_delete(), UA_BrowseResult_delete(), UA_BrowseResultMask_delete(), UA_BuildInfo_delete(), UA_Byte_delete(), UA_ByteString_delete(), UA_CallMethodRequest_delete(), UA_CallMethodResult_delete(), UA_CallRequest_delete(), UA_CallResponse_delete(), UA_ChannelSecurityToken_delete(), UA_ChunkType_delete(), UA_CloseSecureChannelRequest_delete(), UA_CloseSecureChannelResponse_delete(), UA_CloseSessionRequest_delete(), UA_CloseSessionResponse_delete(), UA_ContentFilter_delete(), UA_ContentFilterElement_delete(), UA_ContentFilterElementResult_delete(), UA_ContentFilterResult_delete(), UA_CreateMonitoredItemsRequest_delete(), UA_CreateMonitoredItemsResponse_delete(), UA_CreateSessionRequest_delete(), UA_CreateSessionResponse_delete(), UA_CreateSubscriptionRequest_delete(), UA_CreateSubscriptionResponse_delete(), UA_DataChangeFilter_delete(), UA_DataChangeNotification_delete(), UA_DataChangeTrigger_delete(), UA_DataTypeAttributes_delete(), UA_DataValue_delete(), UA_DateTime_delete(), UA_DeadbandType_delete(), UA_DeleteMonitoredItemsRequest_delete(), UA_DeleteMonitoredItemsResponse_delete(), UA_DeleteNodesItem_delete(), UA_DeleteNodesRequest_delete(), UA_DeleteNodesResponse_delete(), UA_DeleteReferencesItem_delete(), UA_DeleteReferencesRequest_delete(), UA_DeleteReferencesResponse_delete(), UA_DeleteSubscriptionsRequest_delete(), UA_DeleteSubscriptionsResponse_delete(), UA_DiagnosticInfo_delete(), UA_DiscoveryConfiguration_delete(), UA_Double_delete(), UA_Duration_delete(), UA_ElementOperand_delete(), UA_EndpointDescription_delete(), UA_EnumValueType_delete(), UA_EventFieldList_delete(), UA_EventFilter_delete(), UA_EventFilterResult_delete(), UA_EventNotificationList_delete(), UA_ExpandedNodeId_delete(), UA_ExtensionObject_delete(), UA_FilterOperand_delete(), UA_FilterOperator_delete(), UA_FindServersOnNetworkRequest_delete(), UA_FindServersOnNetworkResponse_delete(), UA_FindServersRequest_delete(), UA_FindServersResponse_delete(), UA_Float_delete(), UA_GetEndpointsRequest_delete(), UA_GetEndpointsResponse_delete(), UA_Guid_delete(), UA_init(), UA_Int16_delete(), UA_Int32_delete(), UA_Int64_delete(), UA_IssuedIdentityToken_delete(), UA_LiteralOperand_delete(), UA_LocaleId_delete(), UA_LocalizedText_delete(), UA_MdnsDiscoveryConfiguration_delete(), UA_MessageSecurityMode_delete(), UA_MessageType_delete(), UA_MethodAttributes_delete(), UA_ModifyMonitoredItemsRequest_delete(), UA_ModifyMonitoredItemsResponse_delete(), UA_ModifySubscriptionRequest_delete(), UA_ModifySubscriptionResponse_delete(), UA_MonitoredItemCreateRequest_delete(), UA_MonitoredItemCreateResult_delete(), UA_MonitoredItemModifyRequest_delete(), UA_MonitoredItemModifyResult_delete(), UA_MonitoredItemNotification_delete(), UA_MonitoringMode_delete(), UA_MonitoringParameters_delete(), UA_NodeAttributes_delete(), UA_NodeAttributesMask_delete(), UA_NodeClass_delete(), UA_NodeId_delete(), UA_NotificationMessage_delete(), UA_ObjectAttributes_delete(), UA_ObjectTypeAttributes_delete(), UA_OpenSecureChannelRequest_delete(), UA_OpenSecureChannelResponse_delete(), UA_PublishRequest_delete(), UA_PublishResponse_delete(), UA_QualifiedName_delete(), UA_Range_delete(), UA_ReadRequest_delete(), UA_ReadResponse_delete(), UA_ReadValueId_delete(), UA_RedundancySupport_delete(), UA_ReferenceDescription_delete(), UA_ReferenceTypeAttributes_delete(), UA_RegisteredServer_delete(), UA_RegisterNodesRequest_delete(), UA_RegisterNodesResponse_delete(), UA_RegisterServer2Request_delete(), UA_RegisterServer2Response_delete(), UA_RegisterServerRequest_delete(), UA_RegisterServerResponse_delete(), UA_RelativePath_delete(), UA_RelativePathElement_delete(), UA_RepublishRequest_delete(), UA_RepublishResponse_delete(), UA_RequestHeader_delete(), UA_ResponseHeader_delete(), UA_SByte_delete(), UA_SecureConversationMessageAbortBody_delete(), UA_SecureConversationMessageFooter_delete(), UA_SecureConversationMessageHeader_delete(), UA_SecurityTokenRequestType_delete(), UA_SequenceHeader_delete(), UA_ServerDiagnosticsSummaryDataType_delete(), UA_ServerOnNetwork_delete(), UA_ServerState_delete(), UA_ServerStatusDataType_delete(), UA_ServiceFault_delete(), UA_SetMonitoringModeRequest_delete(), UA_SetMonitoringModeResponse_delete(), UA_SetPublishingModeRequest_delete(), UA_SetPublishingModeResponse_delete(), UA_SetTriggeringRequest_delete(), UA_SetTriggeringResponse_delete(), UA_SignatureData_delete(), UA_SignedSoftwareCertificate_delete(), UA_SimpleAttributeOperand_delete(), UA_StatusChangeNotification_delete(), UA_StatusCode_delete(), UA_String_delete(), UA_SubscriptionAcknowledgement_delete(), UA_SymmetricAlgorithmSecurityHeader_delete(), UA_TcpAcknowledgeMessage_delete(), UA_TcpErrorMessage_delete(), UA_TcpHelloMessage_delete(), UA_TcpMessageHeader_delete(), UA_TimestampsToReturn_delete(), UA_TranslateBrowsePathsToNodeIdsRequest_delete(), UA_TranslateBrowsePathsToNodeIdsResponse_delete(), UA_UInt16_delete(), UA_UInt32_delete(), UA_UInt64_delete(), UA_UnregisterNodesRequest_delete(), UA_UnregisterNodesResponse_delete(), UA_UserIdentityToken_delete(), UA_UserNameIdentityToken_delete(), UA_UserTokenPolicy_delete(), UA_UserTokenType_delete(), UA_UtcTime_delete(), UA_VariableAttributes_delete(), UA_VariableTypeAttributes_delete(), UA_Variant_delete(), UA_ViewAttributes_delete(), UA_ViewDescription_delete(), UA_WriteRequest_delete(), UA_WriteResponse_delete(), UA_WriteValue_delete(), UA_X509IdentityToken_delete(), and UA_XmlElement_delete().
UA_EXPANDEDNODEID_BYTESTRING()
static UA_INLINE UA_ExpandedNodeId UA_EXPANDEDNODEID_BYTESTRING (UA_UInt16 nsIndex, char * chars) static
Definition at line 430 of file types.h.
References nodeset_compiler.nodeset_compiler::id, UA_NODEID_BYTESTRING(), and UA_STRING_NULL.
UA_EXPANDEDNODEID_BYTESTRING_ALLOC()
static UA_INLINE UA_ExpandedNodeId UA_EXPANDEDNODEID_BYTESTRING_ALLOC (UA_UInt16 nsIndex, const char * chars) static
Definition at line 436 of file types.h.
References nodeset_compiler.nodeset_compiler::id, UA_NODEID_BYTESTRING_ALLOC(), and UA_STRING_NULL.
UA_ExpandedNodeId_equal()
static UA_INLINE UA_Boolean UA_ExpandedNodeId_equal (const UA_ExpandedNodeId * n1, const UA_ExpandedNodeId * n2) static
Definition at line 397 of file types.h.
References UA_ExpandedNodeId_hash(), UA_ExpandedNodeId_order(), and UA_ORDER_EQ.
UA_ExpandedNodeId_hash()
UA_UInt32 UA_EXPORT UA_ExpandedNodeId_hash (const UA_ExpandedNodeId * n)
Referenced by UA_ExpandedNodeId_equal().
UA_EXPANDEDNODEID_NUMERIC()
static UA_INLINE UA_ExpandedNodeId UA_EXPANDEDNODEID_NUMERIC (UA_UInt16 nsIndex, UA_UInt32 identifier) static
The following functions are shorthand for creating ExpandedNodeIds.
Definition at line 406 of file types.h.
References nodeset_compiler.nodeset_compiler::id, UA_NODEID_NUMERIC(), and UA_STRING_NULL.
Referenced by function_namespace0_generated_133_begin(), function_namespace0_generated_135_begin(), function_namespace0_generated_137_begin(), function_namespace0_generated_138_begin(), function_namespace0_generated_139_begin(), function_namespace0_generated_140_begin(), function_namespace0_generated_141_begin(), function_namespace0_generated_142_begin(), function_namespace0_generated_143_begin(), function_namespace0_generated_144_begin(), function_namespace0_generated_146_begin(), function_namespace0_generated_69_begin(), function_namespace0_generated_70_begin(), function_namespace0_generated_72_begin(), function_namespace0_generated_74_begin(), function_namespace0_generated_75_begin(), function_namespace0_generated_78_begin(), function_namespace0_generated_81_begin(), function_namespace0_generated_82_begin(), function_namespace0_generated_83_begin(), function_namespace0_generated_84_begin(), function_namespace0_generated_85_begin(), function_namespace0_generated_86_begin(), function_namespace0_generated_87_begin(), function_namespace0_generated_88_begin(), function_namespace0_generated_89_begin(), function_namespace0_generated_90_begin(), function_namespace0_generated_91_begin(), and function_namespace0_generated_92_begin().
UA_ExpandedNodeId_order()
UA_Order UA_EXPORT UA_ExpandedNodeId_order (const UA_ExpandedNodeId * n1, const UA_ExpandedNodeId * n2)
Referenced by UA_ExpandedNodeId_equal().
UA_EXPANDEDNODEID_STRING()
static UA_INLINE UA_ExpandedNodeId UA_EXPANDEDNODEID_STRING (UA_UInt16 nsIndex, char * chars) static
Definition at line 412 of file types.h.
References nodeset_compiler.nodeset_compiler::id, UA_NODEID_STRING(), and UA_STRING_NULL.
UA_EXPANDEDNODEID_STRING_ALLOC()
static UA_INLINE UA_ExpandedNodeId UA_EXPANDEDNODEID_STRING_ALLOC (UA_UInt16 nsIndex, const char * chars) static
Definition at line 418 of file types.h.
References nodeset_compiler.nodeset_compiler::id, UA_NODEID_STRING_ALLOC(), and UA_STRING_NULL.
UA_EXPANDEDNODEID_STRING_GUID()
static UA_INLINE UA_ExpandedNodeId UA_EXPANDEDNODEID_STRING_GUID (UA_UInt16 nsIndex, UA_Guid guid) static
Definition at line 424 of file types.h.
References nodeset_compiler.nodeset_compiler::id, UA_NODEID_GUID(), and UA_STRING_NULL.
UA_findDataType()
const UA_DataType UA_EXPORT* UA_findDataType (const UA_NodeId * typeId)
Builtin data types can be accessed as UA_TYPES[UA_TYPES_XXX], where XXX is the name of the data type. If only the NodeId of a type is known, use the following method to retrieve the data type description.
UA_Guid_equal()
UA_Boolean UA_EXPORT UA_Guid_equal (const UA_Guid * g1, const UA_Guid * g2)
UA_Guid_random()
UA_Guid UA_EXPORT UA_Guid_random (void)
Referenced by UA_init().
UA_init()
static UA_INLINE void UA_init (void * p, const UA_DataType * type) static
Definition at line 902 of file types.h.
References UA_DataType::memSize, UA_Array_copy(), UA_Array_delete(), UA_Array_new(), UA_clear(), UA_copy(), UA_delete(), UA_Guid_random(), UA_random_seed(), and UA_UInt32_random().
Referenced by function_namespace0_generated_34_begin(), function_namespace0_generated_97_begin(), and function_namespace0_generated_98_begin().
UA_LOCALIZEDTEXT()
static UA_INLINE UA_LocalizedText UA_LOCALIZEDTEXT (char * locale, char * text) static
Definition at line 483 of file types.h.
References UA_LocalizedText::locale, UA_LocalizedText::text, and UA_STRING().
Referenced by addDeviceNode(), addGroupNode(), addMetricNode(), function_namespace0_generated_0_begin(), function_namespace0_generated_100_begin(), function_namespace0_generated_101_begin(), function_namespace0_generated_102_begin(), function_namespace0_generated_103_begin(), function_namespace0_generated_104_begin(), function_namespace0_generated_105_begin(), function_namespace0_generated_106_begin(), function_namespace0_generated_107_begin(), function_namespace0_generated_108_begin(), function_namespace0_generated_109_begin(), function_namespace0_generated_10_begin(), function_namespace0_generated_110_begin(), function_namespace0_generated_111_begin(), function_namespace0_generated_112_begin(), function_namespace0_generated_113_begin(), function_namespace0_generated_114_begin(), function_namespace0_generated_115_begin(), function_namespace0_generated_116_begin(), function_namespace0_generated_117_begin(), function_namespace0_generated_118_begin(), function_namespace0_generated_119_begin(), function_namespace0_generated_11_begin(), function_namespace0_generated_120_begin(), function_namespace0_generated_121_begin(), function_namespace0_generated_122_begin(), function_namespace0_generated_123_begin(), function_namespace0_generated_124_begin(), function_namespace0_generated_125_begin(), function_namespace0_generated_126_begin(), function_namespace0_generated_127_begin(), function_namespace0_generated_128_begin(), function_namespace0_generated_129_begin(), function_namespace0_generated_12_begin(), function_namespace0_generated_130_begin(), function_namespace0_generated_131_begin(), function_namespace0_generated_132_begin(), function_namespace0_generated_133_begin(), function_namespace0_generated_134_begin(), function_namespace0_generated_135_begin(), function_namespace0_generated_136_begin(), function_namespace0_generated_137_begin(), function_namespace0_generated_138_begin(), function_namespace0_generated_139_begin(), function_namespace0_generated_13_begin(), function_namespace0_generated_140_begin(), function_namespace0_generated_141_begin(), function_namespace0_generated_142_begin(), function_namespace0_generated_143_begin(), function_namespace0_generated_144_begin(), function_namespace0_generated_145_begin(), function_namespace0_generated_146_begin(), function_namespace0_generated_147_begin(), function_namespace0_generated_148_begin(), function_namespace0_generated_149_begin(), function_namespace0_generated_14_begin(), function_namespace0_generated_150_begin(), function_namespace0_generated_151_begin(), function_namespace0_generated_152_begin(), function_namespace0_generated_153_begin(), function_namespace0_generated_154_begin(), function_namespace0_generated_155_begin(), function_namespace0_generated_156_begin(), function_namespace0_generated_157_begin(), function_namespace0_generated_158_begin(), function_namespace0_generated_159_begin(), function_namespace0_generated_15_begin(), function_namespace0_generated_160_begin(), function_namespace0_generated_161_begin(), function_namespace0_generated_162_begin(), function_namespace0_generated_163_begin(), function_namespace0_generated_164_begin(), function_namespace0_generated_165_begin(), function_namespace0_generated_16_begin(), function_namespace0_generated_17_begin(), function_namespace0_generated_18_begin(), function_namespace0_generated_19_begin(), function_namespace0_generated_1_begin(), function_namespace0_generated_20_begin(), function_namespace0_generated_21_begin(), function_namespace0_generated_22_begin(), function_namespace0_generated_23_begin(), function_namespace0_generated_24_begin(), function_namespace0_generated_25_begin(), function_namespace0_generated_26_begin(), function_namespace0_generated_27_begin(), function_namespace0_generated_28_begin(), function_namespace0_generated_29_begin(), function_namespace0_generated_2_begin(), function_namespace0_generated_30_begin(), function_namespace0_generated_31_begin(), function_namespace0_generated_32_begin(), function_namespace0_generated_33_begin(), function_namespace0_generated_34_begin(), function_namespace0_generated_35_begin(), function_namespace0_generated_36_begin(), function_namespace0_generated_37_begin(), function_namespace0_generated_38_begin(), function_namespace0_generated_39_begin(), function_namespace0_generated_3_begin(), function_namespace0_generated_40_begin(), function_namespace0_generated_41_begin(), function_namespace0_generated_42_begin(), function_namespace0_generated_43_begin(), function_namespace0_generated_44_begin(), function_namespace0_generated_45_begin(), function_namespace0_generated_46_begin(), function_namespace0_generated_47_begin(), function_namespace0_generated_48_begin(), function_namespace0_generated_49_begin(), function_namespace0_generated_4_begin(), function_namespace0_generated_50_begin(), function_namespace0_generated_51_begin(), function_namespace0_generated_52_begin(), function_namespace0_generated_53_begin(), function_namespace0_generated_54_begin(), function_namespace0_generated_55_begin(), function_namespace0_generated_56_begin(), function_namespace0_generated_57_begin(), function_namespace0_generated_58_begin(), function_namespace0_generated_59_begin(), function_namespace0_generated_5_begin(), function_namespace0_generated_60_begin(), function_namespace0_generated_61_begin(), function_namespace0_generated_62_begin(), function_namespace0_generated_63_begin(), function_namespace0_generated_64_begin(), function_namespace0_generated_65_begin(), function_namespace0_generated_66_begin(), function_namespace0_generated_67_begin(), function_namespace0_generated_68_begin(), function_namespace0_generated_69_begin(), function_namespace0_generated_6_begin(), function_namespace0_generated_70_begin(), function_namespace0_generated_71_begin(), function_namespace0_generated_72_begin(), function_namespace0_generated_73_begin(), function_namespace0_generated_74_begin(), function_namespace0_generated_75_begin(), function_namespace0_generated_76_begin(), function_namespace0_generated_77_begin(), function_namespace0_generated_78_begin(), function_namespace0_generated_79_begin(), function_namespace0_generated_7_begin(), function_namespace0_generated_80_begin(), function_namespace0_generated_81_begin(), function_namespace0_generated_82_begin(), function_namespace0_generated_83_begin(), function_namespace0_generated_84_begin(), function_namespace0_generated_85_begin(), function_namespace0_generated_86_begin(), function_namespace0_generated_87_begin(), function_namespace0_generated_88_begin(), function_namespace0_generated_89_begin(), function_namespace0_generated_8_begin(), function_namespace0_generated_90_begin(), function_namespace0_generated_91_begin(), function_namespace0_generated_92_begin(), function_namespace0_generated_93_begin(), function_namespace0_generated_94_begin(), function_namespace0_generated_95_begin(), function_namespace0_generated_96_begin(), function_namespace0_generated_97_begin(), function_namespace0_generated_98_begin(), function_namespace0_generated_99_begin(), and function_namespace0_generated_9_begin().
UA_LOCALIZEDTEXT_ALLOC()
static UA_INLINE UA_LocalizedText UA_LOCALIZEDTEXT_ALLOC (const char * locale, const char * text) static
Definition at line 489 of file types.h.
References UA_LocalizedText::locale, and UA_LocalizedText::text.
UA_new()
void UA_EXPORT* UA_new (const UA_DataType * type)
The following functions are used for generic handling of data types.
Referenced by UA_ActivateSessionRequest_new(), UA_ActivateSessionResponse_new(), UA_AddNodesItem_new(), UA_AddNodesRequest_new(), UA_AddNodesResponse_new(), UA_AddNodesResult_new(), UA_AddReferencesItem_new(), UA_AddReferencesRequest_new(), UA_AddReferencesResponse_new(), UA_AggregateConfiguration_new(), UA_AggregateFilter_new(), UA_AnonymousIdentityToken_new(), UA_ApplicationDescription_new(), UA_ApplicationType_new(), UA_Argument_new(), UA_AsymmetricAlgorithmSecurityHeader_new(), UA_AttributeOperand_new(), UA_Boolean_new(), UA_BrowseDescription_new(), UA_BrowseDirection_new(), UA_BrowseNextRequest_new(), UA_BrowseNextResponse_new(), UA_BrowsePath_new(), UA_BrowsePathResult_new(), UA_BrowsePathTarget_new(), UA_BrowseRequest_new(), UA_BrowseResponse_new(), UA_BrowseResult_new(), UA_BrowseResultMask_new(), UA_BuildInfo_new(), UA_Byte_new(), UA_ByteString_new(), UA_CallMethodRequest_new(), UA_CallMethodResult_new(), UA_CallRequest_new(), UA_CallResponse_new(), UA_ChannelSecurityToken_new(), UA_ChunkType_new(), UA_CloseSecureChannelRequest_new(), UA_CloseSecureChannelResponse_new(), UA_CloseSessionRequest_new(), UA_CloseSessionResponse_new(), UA_ContentFilter_new(), UA_ContentFilterElement_new(), UA_ContentFilterElementResult_new(), UA_ContentFilterResult_new(), UA_CreateMonitoredItemsRequest_new(), UA_CreateMonitoredItemsResponse_new(), UA_CreateSessionRequest_new(), UA_CreateSessionResponse_new(), UA_CreateSubscriptionRequest_new(), UA_CreateSubscriptionResponse_new(), UA_DataChangeFilter_new(), UA_DataChangeNotification_new(), UA_DataChangeTrigger_new(), UA_DataTypeAttributes_new(), UA_DataValue_new(), UA_DateTime_new(), UA_DeadbandType_new(), UA_DeleteMonitoredItemsRequest_new(), UA_DeleteMonitoredItemsResponse_new(), UA_DeleteNodesItem_new(), UA_DeleteNodesRequest_new(), UA_DeleteNodesResponse_new(), UA_DeleteReferencesItem_new(), UA_DeleteReferencesRequest_new(), UA_DeleteReferencesResponse_new(), UA_DeleteSubscriptionsRequest_new(), UA_DeleteSubscriptionsResponse_new(), UA_DiagnosticInfo_new(), UA_DiscoveryConfiguration_new(), UA_Double_new(), UA_Duration_new(), UA_ElementOperand_new(), UA_EndpointDescription_new(), UA_EnumValueType_new(), UA_EventFieldList_new(), UA_EventFilter_new(), UA_EventFilterResult_new(), UA_EventNotificationList_new(), UA_ExpandedNodeId_new(), UA_ExtensionObject_new(), UA_FilterOperand_new(), UA_FilterOperator_new(), UA_FindServersOnNetworkRequest_new(), UA_FindServersOnNetworkResponse_new(), UA_FindServersRequest_new(), UA_FindServersResponse_new(), UA_Float_new(), UA_GetEndpointsRequest_new(), UA_GetEndpointsResponse_new(), UA_Guid_new(), UA_Int16_new(), UA_Int32_new(), UA_Int64_new(), UA_IssuedIdentityToken_new(), UA_LiteralOperand_new(), UA_LocaleId_new(), UA_LocalizedText_new(), UA_MdnsDiscoveryConfiguration_new(), UA_MessageSecurityMode_new(), UA_MessageType_new(), UA_MethodAttributes_new(), UA_ModifyMonitoredItemsRequest_new(), UA_ModifyMonitoredItemsResponse_new(), UA_ModifySubscriptionRequest_new(), UA_ModifySubscriptionResponse_new(), UA_MonitoredItemCreateRequest_new(), UA_MonitoredItemCreateResult_new(), UA_MonitoredItemModifyRequest_new(), UA_MonitoredItemModifyResult_new(), UA_MonitoredItemNotification_new(), UA_MonitoringMode_new(), UA_MonitoringParameters_new(), UA_NodeAttributes_new(), UA_NodeAttributesMask_new(), UA_NodeClass_new(), UA_NodeId_new(), UA_NotificationMessage_new(), UA_ObjectAttributes_new(), UA_ObjectTypeAttributes_new(), UA_OpenSecureChannelRequest_new(), UA_OpenSecureChannelResponse_new(), UA_PublishRequest_new(), UA_PublishResponse_new(), UA_QualifiedName_new(), UA_Range_new(), UA_ReadRequest_new(), UA_ReadResponse_new(), UA_ReadValueId_new(), UA_RedundancySupport_new(), UA_ReferenceDescription_new(), UA_ReferenceTypeAttributes_new(), UA_RegisteredServer_new(), UA_RegisterNodesRequest_new(), UA_RegisterNodesResponse_new(), UA_RegisterServer2Request_new(), UA_RegisterServer2Response_new(), UA_RegisterServerRequest_new(), UA_RegisterServerResponse_new(), UA_RelativePath_new(), UA_RelativePathElement_new(), UA_RepublishRequest_new(), UA_RepublishResponse_new(), UA_RequestHeader_new(), UA_ResponseHeader_new(), UA_SByte_new(), UA_SecureConversationMessageAbortBody_new(), UA_SecureConversationMessageFooter_new(), UA_SecureConversationMessageHeader_new(), UA_SecurityTokenRequestType_new(), UA_SequenceHeader_new(), UA_ServerDiagnosticsSummaryDataType_new(), UA_ServerOnNetwork_new(), UA_ServerState_new(), UA_ServerStatusDataType_new(), UA_ServiceFault_new(), UA_SetMonitoringModeRequest_new(), UA_SetMonitoringModeResponse_new(), UA_SetPublishingModeRequest_new(), UA_SetPublishingModeResponse_new(), UA_SetTriggeringRequest_new(), UA_SetTriggeringResponse_new(), UA_SignatureData_new(), UA_SignedSoftwareCertificate_new(), UA_SimpleAttributeOperand_new(), UA_StatusChangeNotification_new(), UA_StatusCode_new(), UA_String_new(), UA_SubscriptionAcknowledgement_new(), UA_SymmetricAlgorithmSecurityHeader_new(), UA_TcpAcknowledgeMessage_new(), UA_TcpErrorMessage_new(), UA_TcpHelloMessage_new(), UA_TcpMessageHeader_new(), UA_TimestampsToReturn_new(), UA_TranslateBrowsePathsToNodeIdsRequest_new(), UA_TranslateBrowsePathsToNodeIdsResponse_new(), UA_UInt16_new(), UA_UInt32_new(), UA_UInt64_new(), UA_UnregisterNodesRequest_new(), UA_UnregisterNodesResponse_new(), UA_UserIdentityToken_new(), UA_UserNameIdentityToken_new(), UA_UserTokenPolicy_new(), UA_UserTokenType_new(), UA_UtcTime_new(), UA_VariableAttributes_new(), UA_VariableTypeAttributes_new(), UA_Variant_new(), UA_ViewAttributes_new(), UA_ViewDescription_new(), UA_WriteRequest_new(), UA_WriteResponse_new(), UA_WriteValue_new(), UA_X509IdentityToken_new(), and UA_XmlElement_new().
UA_NODEID_BYTESTRING()
static UA_INLINE UA_NodeId UA_NODEID_BYTESTRING (UA_UInt16 nsIndex, char * chars) static
Definition at line 368 of file types.h.
References nodeset_compiler.nodeset_compiler::id, UA_BYTESTRING(), and UA_NODEIDTYPE_BYTESTRING.
Referenced by UA_EXPANDEDNODEID_BYTESTRING().
UA_NODEID_BYTESTRING_ALLOC()
static UA_INLINE UA_NodeId UA_NODEID_BYTESTRING_ALLOC (UA_UInt16 nsIndex, const char * chars) static
Definition at line 375 of file types.h.
References nodeset_compiler.nodeset_compiler::id, UA_BYTESTRING_ALLOC(), and UA_NODEIDTYPE_BYTESTRING.
Referenced by UA_EXPANDEDNODEID_BYTESTRING_ALLOC().
UA_NodeId_equal()
static UA_INLINE UA_Boolean UA_NodeId_equal (const UA_NodeId * n1, const UA_NodeId * n2) static
Definition at line 331 of file types.h.
References UA_NodeId_hash(), UA_NodeId_order(), and UA_ORDER_EQ.
UA_NODEID_GUID()
static UA_INLINE UA_NodeId UA_NODEID_GUID (UA_UInt16 nsIndex, UA_Guid guid) static
Definition at line 361 of file types.h.
References nodeset_compiler.nodeset_compiler::id, and UA_NODEIDTYPE_GUID.
Referenced by UA_EXPANDEDNODEID_STRING_GUID().
UA_NodeId_hash()
UA_UInt32 UA_EXPORT UA_NodeId_hash (const UA_NodeId * n)
Referenced by UA_NodeId_equal().
UA_NodeId_isNull()
UA_Boolean UA_EXPORT UA_NodeId_isNull (const UA_NodeId * p)
UA_NODEID_NUMERIC()
static UA_INLINE UA_NodeId UA_NODEID_NUMERIC (UA_UInt16 nsIndex, UA_UInt32 identifier) static
The following functions are shorthand for creating NodeIds.
Definition at line 340 of file types.h.
References nodeset_compiler.nodeset_compiler::id, and UA_NODEIDTYPE_NUMERIC.
Referenced by addDeviceNode(), addGroupNode(), addMetricNode(), function_namespace0_generated_0_begin(), function_namespace0_generated_0_finish(), function_namespace0_generated_100_begin(), function_namespace0_generated_100_finish(), function_namespace0_generated_101_begin(), function_namespace0_generated_101_finish(), function_namespace0_generated_102_begin(), function_namespace0_generated_102_finish(), function_namespace0_generated_103_begin(), function_namespace0_generated_103_finish(), function_namespace0_generated_104_begin(), function_namespace0_generated_104_finish(), function_namespace0_generated_105_begin(), function_namespace0_generated_105_finish(), function_namespace0_generated_106_begin(), function_namespace0_generated_106_finish(), function_namespace0_generated_107_begin(), function_namespace0_generated_107_finish(), function_namespace0_generated_108_begin(), function_namespace0_generated_108_finish(), function_namespace0_generated_109_begin(), function_namespace0_generated_109_finish(), function_namespace0_generated_10_begin(), function_namespace0_generated_10_finish(), function_namespace0_generated_110_begin(), function_namespace0_generated_110_finish(), function_namespace0_generated_111_begin(), function_namespace0_generated_111_finish(), function_namespace0_generated_112_begin(), function_namespace0_generated_112_finish(), function_namespace0_generated_113_begin(), function_namespace0_generated_113_finish(), function_namespace0_generated_114_begin(), function_namespace0_generated_114_finish(), function_namespace0_generated_115_begin(), function_namespace0_generated_115_finish(), function_namespace0_generated_116_begin(), function_namespace0_generated_116_finish(), function_namespace0_generated_117_begin(), function_namespace0_generated_117_finish(), function_namespace0_generated_118_begin(), function_namespace0_generated_118_finish(), function_namespace0_generated_119_begin(), function_namespace0_generated_119_finish(), function_namespace0_generated_11_begin(), function_namespace0_generated_11_finish(), function_namespace0_generated_120_begin(), function_namespace0_generated_120_finish(), function_namespace0_generated_121_begin(), function_namespace0_generated_121_finish(), function_namespace0_generated_122_begin(), function_namespace0_generated_122_finish(), function_namespace0_generated_123_begin(), function_namespace0_generated_123_finish(), function_namespace0_generated_124_begin(), function_namespace0_generated_124_finish(), function_namespace0_generated_125_begin(), function_namespace0_generated_125_finish(), function_namespace0_generated_126_begin(), function_namespace0_generated_126_finish(), function_namespace0_generated_127_begin(), function_namespace0_generated_127_finish(), function_namespace0_generated_128_begin(), function_namespace0_generated_128_finish(), function_namespace0_generated_129_begin(), function_namespace0_generated_129_finish(), function_namespace0_generated_12_begin(), function_namespace0_generated_12_finish(), function_namespace0_generated_130_begin(), function_namespace0_generated_130_finish(), function_namespace0_generated_131_begin(), function_namespace0_generated_131_finish(), function_namespace0_generated_132_begin(), function_namespace0_generated_132_finish(), function_namespace0_generated_133_begin(), function_namespace0_generated_133_finish(), function_namespace0_generated_134_begin(), function_namespace0_generated_134_finish(), function_namespace0_generated_135_begin(), function_namespace0_generated_135_finish(), function_namespace0_generated_136_begin(), function_namespace0_generated_136_finish(), function_namespace0_generated_137_begin(), function_namespace0_generated_137_finish(), function_namespace0_generated_138_begin(), function_namespace0_generated_138_finish(), function_namespace0_generated_139_begin(), function_namespace0_generated_139_finish(), function_namespace0_generated_13_begin(), function_namespace0_generated_13_finish(), function_namespace0_generated_140_begin(), function_namespace0_generated_140_finish(), function_namespace0_generated_141_begin(), function_namespace0_generated_141_finish(), function_namespace0_generated_142_begin(), function_namespace0_generated_142_finish(), function_namespace0_generated_143_begin(), function_namespace0_generated_143_finish(), function_namespace0_generated_144_begin(), function_namespace0_generated_144_finish(), function_namespace0_generated_145_begin(), function_namespace0_generated_145_finish(), function_namespace0_generated_146_begin(), function_namespace0_generated_146_finish(), function_namespace0_generated_147_begin(), function_namespace0_generated_147_finish(), function_namespace0_generated_148_begin(), function_namespace0_generated_148_finish(), function_namespace0_generated_149_begin(), function_namespace0_generated_149_finish(), function_namespace0_generated_14_begin(), function_namespace0_generated_14_finish(), function_namespace0_generated_150_begin(), function_namespace0_generated_150_finish(), function_namespace0_generated_151_begin(), function_namespace0_generated_151_finish(), function_namespace0_generated_152_begin(), function_namespace0_generated_152_finish(), function_namespace0_generated_153_begin(), function_namespace0_generated_153_finish(), function_namespace0_generated_154_begin(), function_namespace0_generated_154_finish(), function_namespace0_generated_155_begin(), function_namespace0_generated_155_finish(), function_namespace0_generated_156_begin(), function_namespace0_generated_156_finish(), function_namespace0_generated_157_begin(), function_namespace0_generated_157_finish(), function_namespace0_generated_158_begin(), function_namespace0_generated_158_finish(), function_namespace0_generated_159_begin(), function_namespace0_generated_159_finish(), function_namespace0_generated_15_begin(), function_namespace0_generated_15_finish(), function_namespace0_generated_160_begin(), function_namespace0_generated_160_finish(), function_namespace0_generated_161_begin(), function_namespace0_generated_161_finish(), function_namespace0_generated_162_begin(), function_namespace0_generated_162_finish(), function_namespace0_generated_163_begin(), function_namespace0_generated_163_finish(), function_namespace0_generated_164_begin(), function_namespace0_generated_164_finish(), function_namespace0_generated_165_begin(), function_namespace0_generated_165_finish(), function_namespace0_generated_16_begin(), function_namespace0_generated_16_finish(), function_namespace0_generated_17_begin(), function_namespace0_generated_17_finish(), function_namespace0_generated_18_begin(), function_namespace0_generated_18_finish(), function_namespace0_generated_19_begin(), function_namespace0_generated_19_finish(), function_namespace0_generated_1_begin(), function_namespace0_generated_1_finish(), function_namespace0_generated_20_begin(), function_namespace0_generated_20_finish(), function_namespace0_generated_21_begin(), function_namespace0_generated_21_finish(), function_namespace0_generated_22_begin(), function_namespace0_generated_22_finish(), function_namespace0_generated_23_begin(), function_namespace0_generated_23_finish(), function_namespace0_generated_24_begin(), function_namespace0_generated_24_finish(), function_namespace0_generated_25_begin(), function_namespace0_generated_25_finish(), function_namespace0_generated_26_begin(), function_namespace0_generated_26_finish(), function_namespace0_generated_27_begin(), function_namespace0_generated_27_finish(), function_namespace0_generated_28_begin(), function_namespace0_generated_28_finish(), function_namespace0_generated_29_begin(), function_namespace0_generated_29_finish(), function_namespace0_generated_2_begin(), function_namespace0_generated_2_finish(), function_namespace0_generated_30_begin(), function_namespace0_generated_30_finish(), function_namespace0_generated_31_begin(), function_namespace0_generated_31_finish(), function_namespace0_generated_32_begin(), function_namespace0_generated_32_finish(), function_namespace0_generated_33_begin(), function_namespace0_generated_33_finish(), function_namespace0_generated_34_begin(), function_namespace0_generated_34_finish(), function_namespace0_generated_35_begin(), function_namespace0_generated_35_finish(), function_namespace0_generated_36_begin(), function_namespace0_generated_36_finish(), function_namespace0_generated_37_begin(), function_namespace0_generated_37_finish(), function_namespace0_generated_38_begin(), function_namespace0_generated_38_finish(), function_namespace0_generated_39_begin(), function_namespace0_generated_39_finish(), function_namespace0_generated_3_begin(), function_namespace0_generated_3_finish(), function_namespace0_generated_40_begin(), function_namespace0_generated_40_finish(), function_namespace0_generated_41_begin(), function_namespace0_generated_41_finish(), function_namespace0_generated_42_begin(), function_namespace0_generated_42_finish(), function_namespace0_generated_43_begin(), function_namespace0_generated_43_finish(), function_namespace0_generated_44_begin(), function_namespace0_generated_44_finish(), function_namespace0_generated_45_begin(), function_namespace0_generated_45_finish(), function_namespace0_generated_46_begin(), function_namespace0_generated_46_finish(), function_namespace0_generated_47_begin(), function_namespace0_generated_47_finish(), function_namespace0_generated_48_begin(), function_namespace0_generated_48_finish(), function_namespace0_generated_49_begin(), function_namespace0_generated_49_finish(), function_namespace0_generated_4_begin(), function_namespace0_generated_4_finish(), function_namespace0_generated_50_begin(), function_namespace0_generated_50_finish(), function_namespace0_generated_51_begin(), function_namespace0_generated_51_finish(), function_namespace0_generated_52_begin(), function_namespace0_generated_52_finish(), function_namespace0_generated_53_begin(), function_namespace0_generated_53_finish(), function_namespace0_generated_54_begin(), function_namespace0_generated_54_finish(), function_namespace0_generated_55_begin(), function_namespace0_generated_55_finish(), function_namespace0_generated_56_begin(), function_namespace0_generated_56_finish(), function_namespace0_generated_57_begin(), function_namespace0_generated_57_finish(), function_namespace0_generated_58_begin(), function_namespace0_generated_58_finish(), function_namespace0_generated_59_begin(), function_namespace0_generated_59_finish(), function_namespace0_generated_5_begin(), function_namespace0_generated_5_finish(), function_namespace0_generated_60_begin(), function_namespace0_generated_60_finish(), function_namespace0_generated_61_begin(), function_namespace0_generated_61_finish(), function_namespace0_generated_62_begin(), function_namespace0_generated_62_finish(), function_namespace0_generated_63_begin(), function_namespace0_generated_63_finish(), function_namespace0_generated_64_begin(), function_namespace0_generated_64_finish(), function_namespace0_generated_65_begin(), function_namespace0_generated_65_finish(), function_namespace0_generated_66_begin(), function_namespace0_generated_66_finish(), function_namespace0_generated_67_begin(), function_namespace0_generated_67_finish(), function_namespace0_generated_68_begin(), function_namespace0_generated_68_finish(), function_namespace0_generated_69_begin(), function_namespace0_generated_69_finish(), function_namespace0_generated_6_begin(), function_namespace0_generated_6_finish(), function_namespace0_generated_70_begin(), function_namespace0_generated_70_finish(), function_namespace0_generated_71_begin(), function_namespace0_generated_71_finish(), function_namespace0_generated_72_begin(), function_namespace0_generated_72_finish(), function_namespace0_generated_73_begin(), function_namespace0_generated_73_finish(), function_namespace0_generated_74_begin(), function_namespace0_generated_74_finish(), function_namespace0_generated_75_begin(), function_namespace0_generated_75_finish(), function_namespace0_generated_76_begin(), function_namespace0_generated_76_finish(), function_namespace0_generated_77_begin(), function_namespace0_generated_77_finish(), function_namespace0_generated_78_begin(), function_namespace0_generated_78_finish(), function_namespace0_generated_79_begin(), function_namespace0_generated_79_finish(), function_namespace0_generated_7_begin(), function_namespace0_generated_7_finish(), function_namespace0_generated_80_begin(), function_namespace0_generated_80_finish(), function_namespace0_generated_81_begin(), function_namespace0_generated_81_finish(), function_namespace0_generated_82_begin(), function_namespace0_generated_82_finish(), function_namespace0_generated_83_begin(), function_namespace0_generated_83_finish(), function_namespace0_generated_84_begin(), function_namespace0_generated_84_finish(), function_namespace0_generated_85_begin(), function_namespace0_generated_85_finish(), function_namespace0_generated_86_begin(), function_namespace0_generated_86_finish(), function_namespace0_generated_87_begin(), function_namespace0_generated_87_finish(), function_namespace0_generated_88_begin(), function_namespace0_generated_88_finish(), function_namespace0_generated_89_begin(), function_namespace0_generated_89_finish(), function_namespace0_generated_8_begin(), function_namespace0_generated_8_finish(), function_namespace0_generated_90_begin(), function_namespace0_generated_90_finish(), function_namespace0_generated_91_begin(), function_namespace0_generated_91_finish(), function_namespace0_generated_92_begin(), function_namespace0_generated_92_finish(), function_namespace0_generated_93_begin(), function_namespace0_generated_93_finish(), function_namespace0_generated_94_begin(), function_namespace0_generated_94_finish(), function_namespace0_generated_95_begin(), function_namespace0_generated_95_finish(), function_namespace0_generated_96_begin(), function_namespace0_generated_96_finish(), function_namespace0_generated_97_begin(), function_namespace0_generated_97_finish(), function_namespace0_generated_98_begin(), function_namespace0_generated_98_finish(), function_namespace0_generated_99_begin(), function_namespace0_generated_99_finish(), function_namespace0_generated_9_begin(), function_namespace0_generated_9_finish(), and UA_EXPANDEDNODEID_NUMERIC().
UA_NodeId_order()
UA_Order UA_EXPORT UA_NodeId_order (const UA_NodeId * n1, const UA_NodeId * n2)
Referenced by UA_NodeId_equal().
UA_NODEID_STRING()
static UA_INLINE UA_NodeId UA_NODEID_STRING (UA_UInt16 nsIndex, char * chars) static
Definition at line 347 of file types.h.
References nodeset_compiler.nodeset_compiler::id, UA_NODEIDTYPE_STRING, and UA_STRING().
Referenced by addDeviceNode(), addGroupNode(), addMetricNode(), and UA_EXPANDEDNODEID_STRING().
UA_NODEID_STRING_ALLOC()
static UA_INLINE UA_NodeId UA_NODEID_STRING_ALLOC (UA_UInt16 nsIndex, const char * chars) static
Definition at line 354 of file types.h.
References nodeset_compiler.nodeset_compiler::id, and UA_NODEIDTYPE_STRING.
Referenced by UA_EXPANDEDNODEID_STRING_ALLOC().
UA_NumericRange_parseFromString()
UA_StatusCode UA_EXPORT UA_NumericRange_parseFromString (UA_NumericRange * range, const UA_String * str)
UA_QUALIFIEDNAME()
static UA_INLINE UA_QualifiedName UA_QUALIFIEDNAME (UA_UInt16 nsIndex, char * chars) static
Definition at line 458 of file types.h.
References UA_QualifiedName::name, UA_QualifiedName::namespaceIndex, and UA_STRING().
Referenced by addDeviceNode(), addGroupNode(), addMetricNode(), function_namespace0_generated_0_begin(), function_namespace0_generated_100_begin(), function_namespace0_generated_101_begin(), function_namespace0_generated_102_begin(), function_namespace0_generated_103_begin(), function_namespace0_generated_104_begin(), function_namespace0_generated_105_begin(), function_namespace0_generated_106_begin(), function_namespace0_generated_107_begin(), function_namespace0_generated_108_begin(), function_namespace0_generated_109_begin(), function_namespace0_generated_10_begin(), function_namespace0_generated_110_begin(), function_namespace0_generated_111_begin(), function_namespace0_generated_112_begin(), function_namespace0_generated_113_begin(), function_namespace0_generated_114_begin(), function_namespace0_generated_115_begin(), function_namespace0_generated_116_begin(), function_namespace0_generated_117_begin(), function_namespace0_generated_118_begin(), function_namespace0_generated_119_begin(), function_namespace0_generated_11_begin(), function_namespace0_generated_120_begin(), function_namespace0_generated_121_begin(), function_namespace0_generated_122_begin(), function_namespace0_generated_123_begin(), function_namespace0_generated_124_begin(), function_namespace0_generated_125_begin(), function_namespace0_generated_126_begin(), function_namespace0_generated_127_begin(), function_namespace0_generated_128_begin(), function_namespace0_generated_129_begin(), function_namespace0_generated_12_begin(), function_namespace0_generated_130_begin(), function_namespace0_generated_131_begin(), function_namespace0_generated_132_begin(), function_namespace0_generated_133_begin(), function_namespace0_generated_134_begin(), function_namespace0_generated_135_begin(), function_namespace0_generated_136_begin(), function_namespace0_generated_137_begin(), function_namespace0_generated_138_begin(), function_namespace0_generated_139_begin(), function_namespace0_generated_13_begin(), function_namespace0_generated_140_begin(), function_namespace0_generated_141_begin(), function_namespace0_generated_142_begin(), function_namespace0_generated_143_begin(), function_namespace0_generated_144_begin(), function_namespace0_generated_145_begin(), function_namespace0_generated_146_begin(), function_namespace0_generated_147_begin(), function_namespace0_generated_148_begin(), function_namespace0_generated_149_begin(), function_namespace0_generated_14_begin(), function_namespace0_generated_150_begin(), function_namespace0_generated_151_begin(), function_namespace0_generated_152_begin(), function_namespace0_generated_153_begin(), function_namespace0_generated_154_begin(), function_namespace0_generated_155_begin(), function_namespace0_generated_156_begin(), function_namespace0_generated_157_begin(), function_namespace0_generated_158_begin(), function_namespace0_generated_159_begin(), function_namespace0_generated_15_begin(), function_namespace0_generated_160_begin(), function_namespace0_generated_161_begin(), function_namespace0_generated_162_begin(), function_namespace0_generated_163_begin(), function_namespace0_generated_164_begin(), function_namespace0_generated_165_begin(), function_namespace0_generated_16_begin(), function_namespace0_generated_17_begin(), function_namespace0_generated_18_begin(), function_namespace0_generated_19_begin(), function_namespace0_generated_1_begin(), function_namespace0_generated_20_begin(), function_namespace0_generated_21_begin(), function_namespace0_generated_22_begin(), function_namespace0_generated_23_begin(), function_namespace0_generated_24_begin(), function_namespace0_generated_25_begin(), function_namespace0_generated_26_begin(), function_namespace0_generated_27_begin(), function_namespace0_generated_28_begin(), function_namespace0_generated_29_begin(), function_namespace0_generated_2_begin(), function_namespace0_generated_30_begin(), function_namespace0_generated_31_begin(), function_namespace0_generated_32_begin(), function_namespace0_generated_33_begin(), function_namespace0_generated_34_begin(), function_namespace0_generated_35_begin(), function_namespace0_generated_36_begin(), function_namespace0_generated_37_begin(), function_namespace0_generated_38_begin(), function_namespace0_generated_39_begin(), function_namespace0_generated_3_begin(), function_namespace0_generated_40_begin(), function_namespace0_generated_41_begin(), function_namespace0_generated_42_begin(), function_namespace0_generated_43_begin(), function_namespace0_generated_44_begin(), function_namespace0_generated_45_begin(), function_namespace0_generated_46_begin(), function_namespace0_generated_47_begin(), function_namespace0_generated_48_begin(), function_namespace0_generated_49_begin(), function_namespace0_generated_4_begin(), function_namespace0_generated_50_begin(), function_namespace0_generated_51_begin(), function_namespace0_generated_52_begin(), function_namespace0_generated_53_begin(), function_namespace0_generated_54_begin(), function_namespace0_generated_55_begin(), function_namespace0_generated_56_begin(), function_namespace0_generated_57_begin(), function_namespace0_generated_58_begin(), function_namespace0_generated_59_begin(), function_namespace0_generated_5_begin(), function_namespace0_generated_60_begin(), function_namespace0_generated_61_begin(), function_namespace0_generated_62_begin(), function_namespace0_generated_63_begin(), function_namespace0_generated_64_begin(), function_namespace0_generated_65_begin(), function_namespace0_generated_66_begin(), function_namespace0_generated_67_begin(), function_namespace0_generated_68_begin(), function_namespace0_generated_69_begin(), function_namespace0_generated_6_begin(), function_namespace0_generated_70_begin(), function_namespace0_generated_71_begin(), function_namespace0_generated_72_begin(), function_namespace0_generated_73_begin(), function_namespace0_generated_74_begin(), function_namespace0_generated_75_begin(), function_namespace0_generated_76_begin(), function_namespace0_generated_77_begin(), function_namespace0_generated_78_begin(), function_namespace0_generated_79_begin(), function_namespace0_generated_7_begin(), function_namespace0_generated_80_begin(), function_namespace0_generated_81_begin(), function_namespace0_generated_82_begin(), function_namespace0_generated_83_begin(), function_namespace0_generated_84_begin(), function_namespace0_generated_85_begin(), function_namespace0_generated_86_begin(), function_namespace0_generated_87_begin(), function_namespace0_generated_88_begin(), function_namespace0_generated_89_begin(), function_namespace0_generated_8_begin(), function_namespace0_generated_90_begin(), function_namespace0_generated_91_begin(), function_namespace0_generated_92_begin(), function_namespace0_generated_93_begin(), function_namespace0_generated_94_begin(), function_namespace0_generated_95_begin(), function_namespace0_generated_96_begin(), function_namespace0_generated_97_begin(), function_namespace0_generated_98_begin(), function_namespace0_generated_99_begin(), and function_namespace0_generated_9_begin().
UA_QUALIFIEDNAME_ALLOC()
static UA_INLINE UA_QualifiedName UA_QUALIFIEDNAME_ALLOC (UA_UInt16 nsIndex, const char * chars) static
Definition at line 464 of file types.h.
References UA_QualifiedName::name, UA_QualifiedName::namespaceIndex, and UA_QualifiedName_equal().
UA_QualifiedName_equal()
UA_Boolean UA_EXPORT UA_QualifiedName_equal (const UA_QualifiedName * qn1, const UA_QualifiedName * qn2)
Referenced by UA_QUALIFIEDNAME_ALLOC().
UA_QualifiedName_isNull()
static UA_INLINE UA_Boolean UA_QualifiedName_isNull (const UA_QualifiedName * q) static
Definition at line 453 of file types.h.
References UA_String::length, UA_QualifiedName::name, and UA_QualifiedName::namespaceIndex.
UA_random_seed()
void UA_EXPORT UA_random_seed (UA_UInt64 seed)
Random Number Generator
If UA_ENABLE_MULTITHREADING is defined, then the seed is stored in thread local storage. The seed is initialized for every thread in the server/client.
Referenced by UA_init().
UA_StatusCode_name()
const char * UA_StatusCode_name (UA_StatusCode code)
Definition at line 260 of file statuscodes.c.
References emptyStatusCodeName, UA_StatusCodeName::name, and statusCodeDescriptionsSize.
UA_STRING()
static UA_INLINE UA_String UA_STRING (char * chars) static
UA_STRING returns a string pointing to the original char-array. UA_STRING_ALLOC is shorthand for UA_String_fromChars and makes a copy of the char-array.
Definition at line 169 of file types.h.
References UA_String::data, and UA_String::length.
Referenced by function_namespace0_generated_97_begin(), function_namespace0_generated_98_begin(), UA_LOCALIZEDTEXT(), UA_NODEID_STRING(), and UA_QUALIFIEDNAME().
UA_String_equal()
UA_Boolean UA_EXPORT UA_String_equal (const UA_String * s1, const UA_String * s2)
Referenced by UA_ByteString_equal().
UA_String_fromChars()
UA_String UA_EXPORT UA_String_fromChars (const char * src)
Referenced by UA_BYTESTRING_ALLOC().
UA_UInt32_random()
UA_UInt32 UA_EXPORT UA_UInt32_random (void)
Referenced by UA_init().
UA_Variant_copyRange()
UA_StatusCode UA_EXPORT UA_Variant_copyRange (const UA_Variant * src, UA_Variant * dst, const UA_NumericRange range)
Referenced by UA_Variant_hasArrayType().
UA_Variant_hasArrayType()
static UA_INLINE UA_Boolean UA_Variant_hasArrayType (const UA_Variant * v, const UA_DataType * type) static
Definition at line 612 of file types.h.
References generate_datatypes::type, UA_Variant::type, UA_Variant_copyRange(), UA_Variant_isScalar(), UA_Variant_setArray(), UA_Variant_setArrayCopy(), UA_Variant_setRange(), UA_Variant_setRangeCopy(), UA_Variant_setScalar(), and UA_Variant_setScalarCopy().
UA_Variant_hasScalarType()
static UA_INLINE UA_Boolean UA_Variant_hasScalarType (const UA_Variant * v, const UA_DataType * type) static
Definition at line 602 of file types.h.
References UA_Variant::type, and UA_Variant_isScalar().
UA_Variant_isEmpty()
static UA_INLINE UA_Boolean UA_Variant_isEmpty (const UA_Variant * v) static
Definition at line 582 of file types.h.
References UA_Variant::type.
UA_Variant_isScalar()
static UA_INLINE UA_Boolean UA_Variant_isScalar (const UA_Variant * v) static
Definition at line 592 of file types.h.
References UA_Variant::arrayLength, and UA_Variant::data.
Referenced by UA_Variant_hasArrayType(), and UA_Variant_hasScalarType().
UA_Variant_setArray()
void UA_EXPORT UA_Variant_setArray (UA_Variant * v, void *UA_RESTRICT array, size_t arraySize, const UA_DataType * type)
Referenced by function_namespace0_generated_34_begin(), function_namespace0_generated_36_begin(), function_namespace0_generated_97_begin(), function_namespace0_generated_98_begin(), and UA_Variant_hasArrayType().
UA_Variant_setArrayCopy()
UA_StatusCode UA_EXPORT UA_Variant_setArrayCopy (UA_Variant * v, const void * array, size_t arraySize, const UA_DataType * type)
Referenced by UA_Variant_hasArrayType().
UA_Variant_setRange()
UA_StatusCode UA_EXPORT UA_Variant_setRange (UA_Variant * v, void *UA_RESTRICT array, size_t arraySize, const UA_NumericRange range)
Referenced by UA_Variant_hasArrayType().
UA_Variant_setRangeCopy()
UA_StatusCode UA_EXPORT UA_Variant_setRangeCopy (UA_Variant * v, const void * array, size_t arraySize, const UA_NumericRange range)
Referenced by UA_Variant_hasArrayType().
UA_Variant_setScalar()
void UA_EXPORT UA_Variant_setScalar (UA_Variant * v, void *UA_RESTRICT p, const UA_DataType * type)
Referenced by function_namespace0_generated_64_begin(), function_namespace0_generated_65_begin(), function_namespace0_generated_66_begin(), function_namespace0_generated_73_begin(), function_namespace0_generated_74_begin(), function_namespace0_generated_76_begin(), and UA_Variant_hasArrayType().
UA_Variant_setScalarCopy()
UA_StatusCode UA_EXPORT UA_Variant_setScalarCopy (UA_Variant * v, const void * p, const UA_DataType * type)
Referenced by UA_Variant_hasArrayType().
Variable Documentation
UA_BYTESTRING_NULL
UA_EXPORT const UA_ByteString UA_BYTESTRING_NULL
Referenced by function_namespace0_generated_64_begin(), and UA_ByteString_equal().
UA_EXPANDEDNODEID_NULL
UA_EXPORT const UA_ExpandedNodeId UA_EXPANDEDNODEID_NULL
UA_GUID_NULL
UA_EXPORT const UA_Guid UA_GUID_NULL
UA_NODEID_NULL
UA_EXPORT const UA_NodeId UA_NODEID_NULL
Referenced by function_namespace0_generated_0_begin(), function_namespace0_generated_10_begin(), function_namespace0_generated_11_begin(), function_namespace0_generated_12_begin(), function_namespace0_generated_135_begin(), function_namespace0_generated_136_begin(), function_namespace0_generated_13_begin(), function_namespace0_generated_145_begin(), function_namespace0_generated_14_begin(), function_namespace0_generated_15_begin(), function_namespace0_generated_16_begin(), function_namespace0_generated_17_begin(), function_namespace0_generated_18_begin(), function_namespace0_generated_19_begin(), function_namespace0_generated_1_begin(), function_namespace0_generated_20_begin(), function_namespace0_generated_21_begin(), function_namespace0_generated_22_begin(), function_namespace0_generated_23_begin(), function_namespace0_generated_24_begin(), function_namespace0_generated_25_begin(), function_namespace0_generated_26_begin(), function_namespace0_generated_27_begin(), function_namespace0_generated_28_begin(), function_namespace0_generated_29_begin(), function_namespace0_generated_2_begin(), function_namespace0_generated_30_begin(), function_namespace0_generated_31_begin(), function_namespace0_generated_32_begin(), function_namespace0_generated_33_begin(), function_namespace0_generated_35_begin(), function_namespace0_generated_37_begin(), function_namespace0_generated_38_begin(), function_namespace0_generated_39_begin(), function_namespace0_generated_3_begin(), function_namespace0_generated_40_begin(), function_namespace0_generated_41_begin(), function_namespace0_generated_42_begin(), function_namespace0_generated_43_begin(), function_namespace0_generated_44_begin(), function_namespace0_generated_45_begin(), function_namespace0_generated_46_begin(), function_namespace0_generated_47_begin(), function_namespace0_generated_48_begin(), function_namespace0_generated_49_begin(), function_namespace0_generated_4_begin(), function_namespace0_generated_50_begin(), function_namespace0_generated_51_begin(), function_namespace0_generated_55_begin(), function_namespace0_generated_5_begin(), function_namespace0_generated_62_begin(), function_namespace0_generated_68_begin(), function_namespace0_generated_6_begin(), function_namespace0_generated_71_begin(), function_namespace0_generated_77_begin(), function_namespace0_generated_7_begin(), function_namespace0_generated_8_begin(), function_namespace0_generated_93_begin(), function_namespace0_generated_96_begin(), function_namespace0_generated_9_begin(), UA_Client_addDataTypeNode(), UA_Client_addDataTypeNode_async(), UA_Client_addMethodNode(), UA_Client_addMethodNode_async(), UA_Client_addObjectTypeNode(), UA_Client_addObjectTypeNode_async(), UA_Client_addReferenceTypeNode(), UA_Client_addReferenceTypeNode_async(), UA_Client_addVariableTypeNode(), UA_Client_addVariableTypeNode_async(), UA_Client_addViewNode(), UA_Client_addViewNode_async(), UA_Server_addDataTypeNode(), UA_Server_addMethodNode(), UA_Server_addObjectTypeNode(), UA_Server_addReferenceTypeNode(), and UA_Server_addViewNode().
UA_STRING_NULL
UA_EXPORT const UA_String UA_STRING_NULL
Referenced by UA_EXPANDEDNODEID_BYTESTRING(), UA_EXPANDEDNODEID_BYTESTRING_ALLOC(), UA_EXPANDEDNODEID_NUMERIC(), UA_EXPANDEDNODEID_STRING(), UA_EXPANDEDNODEID_STRING_ALLOC(), and UA_EXPANDEDNODEID_STRING_GUID().