Project Template: Opc.Ua.CloseSecureChannelRequest Class Reference
Opc.Ua.CloseSecureChannelRequest Class Reference
Public Member Functions
CloseSecureChannelRequest ()
The default constructor.
virtual void Encode (IEncoder encoder)
virtual void Decode (IDecoder decoder)
virtual bool IsEqual (IEncodeable encodeable)
virtual object Clone ()
new object MemberwiseClone ()
Properties
RequestHeader RequestHeader [get, set]
virtual ExpandedNodeId TypeId [get]
virtual ExpandedNodeId BinaryEncodingId [get]
virtual ExpandedNodeId XmlEncodingId [get]
Detailed Description
<exclude>
Definition at line 682 of file Opc.Ua.Messages.cs.
Constructor & Destructor Documentation
CloseSecureChannelRequest()
Opc.Ua.CloseSecureChannelRequest.CloseSecureChannelRequest () inline
The default constructor.
Definition at line 28529 of file Opc.Ua.DataTypes.cs.
Member Function Documentation
Clone()
virtual object Opc.Ua.CloseSecureChannelRequest.Clone () inline virtual
Definition at line 28637 of file Opc.Ua.DataTypes.cs.
Decode()
virtual void Opc.Ua.CloseSecureChannelRequest.Decode (IDecoder decoder) inline virtual
Definition at line 28606 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
Encode()
virtual void Opc.Ua.CloseSecureChannelRequest.Encode (IEncoder encoder) inline virtual
Definition at line 28596 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
IsEqual()
virtual bool Opc.Ua.CloseSecureChannelRequest.IsEqual (IEncodeable encodeable) inline virtual
Definition at line 28616 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Object.
MemberwiseClone()
new object Opc.Ua.CloseSecureChannelRequest.MemberwiseClone () inline
Definition at line 28644 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.RequestHeader.Clone(), Opc.Ua.CloseSecureChannelRequest.MemberwiseClone(), and Opc.Ua.Namespaces.OpcUaXsd.
Referenced by Opc.Ua.CloseSecureChannelRequest.MemberwiseClone().
Property Documentation
BinaryEncodingId
virtual ExpandedNodeId Opc.Ua.CloseSecureChannelRequest.BinaryEncodingId get
Definition at line 28585 of file Opc.Ua.DataTypes.cs.
RequestHeader
RequestHeader Opc.Ua.CloseSecureChannelRequest.RequestHeader get set
Definition at line 28558 of file Opc.Ua.DataTypes.cs.
TypeId
virtual ExpandedNodeId Opc.Ua.CloseSecureChannelRequest.TypeId get
Definition at line 28579 of file Opc.Ua.DataTypes.cs.
XmlEncodingId
virtual ExpandedNodeId Opc.Ua.CloseSecureChannelRequest.XmlEncodingId get
Definition at line 28591 of file Opc.Ua.DataTypes.cs.
The documentation for this class was generated from the following files:
Opc.Ua.Messages.cs
Opc.Ua.DataTypes.cs