Information Modeller: Model_Factory::DeviceImpl Class Reference
Model_Factory::DeviceImpl Class Reference
This class is an implementation of Information_Model::Device It contains all of the virtual method implementations and the building mechanism for Information_Model::Device instances.
#include <DeviceImpl.hpp>
Public Member Functions
DeviceImpl (const std::string REF_ID, const std::string NAME, const std::string DESC)
std::string addDeviceElementGroup (const std::string NAME, const std::string DESC)
This sets the DeviceImpl: DeviceImpl::device_element_group field.
Information_Model::DeviceElementGroup * getDeviceElementGroup ()
Public Member Functions inherited from Information_Model::NamedElement
const std::string getElementName ()
const std::string getElementDescription ()
const std::string getElementRefId ()
virtual ~NamedElement ()=default
Additional Inherited Members
Protected Member Functions inherited from Information_Model::Device
Device (const std::string REF_ID, const std::string NAME, const std::string DESC)
Protected Member Functions inherited from Information_Model::NamedElement
NamedElement (const std::string REF_ID, const std::string NAME, const std::string DESC)
Detailed Description
This class is an implementation of Information_Model::Device It contains all of the virtual method implementations and the building mechanism for Information_Model::Device instances.
Author
Dovydas Girdvainis
Date
18.07.2019
Definition at line 20 of file DeviceImpl.hpp.
Constructor & Destructor Documentation
DeviceImpl()
Model_Factory::DeviceImpl::DeviceImpl (const std::string REF_ID, const std::string NAME, const std::string DESC) inline
Definition at line 26 of file DeviceImpl.hpp.
References addDeviceElementGroup(), and getDeviceElementGroup().
Member Function Documentation
addDeviceElementGroup()
string DeviceImpl::addDeviceElementGroup (const std::string NAME, const std::string DESC)
This sets the DeviceImpl: DeviceImpl::device_element_group field.
Attention
. This method should be only called once per device construction! If called more than once, it will override the previous instance of DeviceImpl: DeviceImpl::device_element_group
Parameters
NAME
DESC
Returns
std::string Reference ID of DeviceImpl: DeviceImpl::device_element_group
Definition at line 9 of file DeviceImpl.cpp.
Referenced by Model_Factory::DeviceBuilder::addDeviceElementGroup(), and DeviceImpl().
getDeviceElementGroup()
Information_Model::DeviceElementGroup * DeviceImpl::getDeviceElementGroup () virtual
Implements Information_Model::Device.
Definition at line 22 of file DeviceImpl.cpp.
Referenced by DeviceImpl().
The documentation for this class was generated from the following files:
DeviceImpl.hpp
DeviceImpl.cpp