Project Template: Opc.Ua Namespace Reference
Opc.Ua Namespace Reference
Namespaces
namespace Adi
namespace Di
namespace Fdi5
namespace Fdi7
namespace Gds
namespace MTConnect
namespace Plc
Data Structures
class AcknowledgeableConditionState
Stores an instance of the AcknowledgeableConditionType ObjectType.
class ActivateSessionMessage
The message contract for the ActivateSession service.
class ActivateSessionRequest
class ActivateSessionResponse
class ActivateSessionResponseMessage
The message contract for the ActivateSession service response.
class AddApplicationMethodState
Stores an instance of the AddApplicationMethodType Method.
class AddCertificateMethodState
Stores an instance of the AddCertificateMethodType Method.
class AddCommentMethodState
Stores an instance of the AddCommentMethodType Method.
class AddConnectionMethodState
Stores an instance of the AddConnectionMethodType Method.
class AddDataSetFolderMethodState
Stores an instance of the AddDataSetFolderMethodType Method.
class AddEndpointMethodState
Stores an instance of the AddEndpointMethodType Method.
class AddExtensionFieldMethodState
Stores an instance of the AddExtensionFieldMethodType Method.
class AddIdentityMethodState
Stores an instance of the AddIdentityMethodType Method.
class AddNodesItem
class AddNodesItemCollection
A collection of AddNodesItem objects.
class AddNodesMessage
The message contract for the AddNodes service.
class AddNodesRequest
class AddNodesResponse
class AddNodesResponseMessage
The message contract for the AddNodes service response.
class AddNodesResult
class AddNodesResultCollection
A collection of AddNodesResult objects.
class AddPublishedDataItemsMethodState
Stores an instance of the AddPublishedDataItemsMethodType Method.
class AddPublishedDataItemsTemplateMethodState
Stores an instance of the AddPublishedDataItemsTemplateMethodType Method.
class AddPublishedEventsMethodState
Stores an instance of the AddPublishedEventsMethodType Method.
class AddPublishedEventsTemplateMethodState
Stores an instance of the AddPublishedEventsTemplateMethodType Method.
class AddReferencesItem
class AddReferencesItemCollection
A collection of AddReferencesItem objects.
class AddReferencesMessage
The message contract for the AddReferences service.
class AddReferencesRequest
class AddReferencesResponse
class AddReferencesResponseMessage
The message contract for the AddReferences service response.
class AddressSpaceFileState
Stores an instance of the AddressSpaceFileType ObjectType.
class AddRoleMethodState
Stores an instance of the AddRoleMethodType Method.
class AddSecurityGroupMethodState
Stores an instance of the AddSecurityGroupMethodType Method.
class AggregateConfiguration
class AggregateConfigurationState
Stores an instance of the AggregateConfigurationType ObjectType.
class AggregateFilter
class AggregateFilterResult
class AggregateFunctionState
Stores an instance of the AggregateFunctionType ObjectType.
class AlarmConditionState
Stores an instance of the AlarmConditionType ObjectType.
class AlarmGroupState
Stores an instance of the AlarmGroupType ObjectType.
class AlarmMetricsState
Stores an instance of the AlarmMetricsType ObjectType.
class AlarmRateVariableState
Stores an instance of the AlarmRateVariableType VariableType.
class AnalogItemState
Stores an instance of the AnalogItemType VariableType.
class AnalogUnitRangeState
Stores an instance of the AnalogUnitRangeType VariableType.
class AnalogUnitState
Stores an instance of the AnalogUnitType VariableType.
class Annotation
class AnonymousIdentityToken
class ApplicationCertificateState
Stores an instance of the ApplicationCertificateType ObjectType.
class ApplicationDescription
class ApplicationDescriptionCollection
A collection of ApplicationDescription objects.
class Argument
class ArgumentCollection
A collection of Argument objects.
class ArrayItemState
Stores an instance of the ArrayItemType VariableType.
class AttributeOperand
class Attributes
A class that defines constants used by UA applications.
class AudioVariableState
Stores an instance of the AudioVariableType VariableType.
class AuditActivateSessionEventState
Stores an instance of the AuditActivateSessionEventType ObjectType.
class AuditAddNodesEventState
Stores an instance of the AuditAddNodesEventType ObjectType.
class AuditAddReferencesEventState
Stores an instance of the AuditAddReferencesEventType ObjectType.
class AuditCancelEventState
Stores an instance of the AuditCancelEventType ObjectType.
class AuditCertificateDataMismatchEventState
Stores an instance of the AuditCertificateDataMismatchEventType ObjectType.
class AuditCertificateEventState
Stores an instance of the AuditCertificateEventType ObjectType.
class AuditCertificateExpiredEventState
Stores an instance of the AuditCertificateExpiredEventType ObjectType.
class AuditCertificateInvalidEventState
Stores an instance of the AuditCertificateInvalidEventType ObjectType.
class AuditCertificateMismatchEventState
Stores an instance of the AuditCertificateMismatchEventType ObjectType.
class AuditCertificateRevokedEventState
Stores an instance of the AuditCertificateRevokedEventType ObjectType.
class AuditCertificateUntrustedEventState
Stores an instance of the AuditCertificateUntrustedEventType ObjectType.
class AuditChannelEventState
Stores an instance of the AuditChannelEventType ObjectType.
class AuditConditionAcknowledgeEventState
Stores an instance of the AuditConditionAcknowledgeEventType ObjectType.
class AuditConditionCommentEventState
Stores an instance of the AuditConditionCommentEventType ObjectType.
class AuditConditionConfirmEventState
Stores an instance of the AuditConditionConfirmEventType ObjectType.
class AuditConditionEnableEventState
Stores an instance of the AuditConditionEnableEventType ObjectType.
class AuditConditionEventState
Stores an instance of the AuditConditionEventType ObjectType.
class AuditConditionOutOfServiceEventState
Stores an instance of the AuditConditionOutOfServiceEventType ObjectType.
class AuditConditionResetEventState
Stores an instance of the AuditConditionResetEventType ObjectType.
class AuditConditionRespondEventState
Stores an instance of the AuditConditionRespondEventType ObjectType.
class AuditConditionShelvingEventState
Stores an instance of the AuditConditionShelvingEventType ObjectType.
class AuditConditionSilenceEventState
Stores an instance of the AuditConditionSilenceEventType ObjectType.
class AuditConditionSuppressionEventState
Stores an instance of the AuditConditionSuppressionEventType ObjectType.
class AuditCreateSessionEventState
Stores an instance of the AuditCreateSessionEventType ObjectType.
class AuditDeleteNodesEventState
Stores an instance of the AuditDeleteNodesEventType ObjectType.
class AuditDeleteReferencesEventState
Stores an instance of the AuditDeleteReferencesEventType ObjectType.
class AuditEventState
Stores an instance of the AuditEventType ObjectType.
class AuditHistoryAtTimeDeleteEventState
Stores an instance of the AuditHistoryAtTimeDeleteEventType ObjectType.
class AuditHistoryDeleteEventState
Stores an instance of the AuditHistoryDeleteEventType ObjectType.
class AuditHistoryEventDeleteEventState
Stores an instance of the AuditHistoryEventDeleteEventType ObjectType.
class AuditHistoryEventUpdateEventState
Stores an instance of the AuditHistoryEventUpdateEventType ObjectType.
class AuditHistoryRawModifyDeleteEventState
Stores an instance of the AuditHistoryRawModifyDeleteEventType ObjectType.
class AuditHistoryUpdateEventState
Stores an instance of the AuditHistoryUpdateEventType ObjectType.
class AuditHistoryValueUpdateEventState
Stores an instance of the AuditHistoryValueUpdateEventType ObjectType.
class AuditNodeManagementEventState
Stores an instance of the AuditNodeManagementEventType ObjectType.
class AuditOpenSecureChannelEventState
Stores an instance of the AuditOpenSecureChannelEventType ObjectType.
class AuditProgramTransitionEventState
Stores an instance of the AuditProgramTransitionEventType ObjectType.
class AuditSecurityEventState
Stores an instance of the AuditSecurityEventType ObjectType.
class AuditSessionEventState
Stores an instance of the AuditSessionEventType ObjectType.
class AuditUpdateEventState
Stores an instance of the AuditUpdateEventType ObjectType.
class AuditUpdateMethodEventState
Stores an instance of the AuditUpdateMethodEventType ObjectType.
class AuditUpdateStateEventState
Stores an instance of the AuditUpdateStateEventType ObjectType.
class AuditUrlMismatchEventState
Stores an instance of the AuditUrlMismatchEventType ObjectType.
class AuditWriteUpdateEventState
Stores an instance of the AuditWriteUpdateEventType ObjectType.
class AuthorizationServiceConfigurationState
Stores an instance of the AuthorizationServiceConfigurationType ObjectType.
class AxisInformation
class BaseAnalogState
Stores an instance of the BaseAnalogType VariableType.
class BaseConditionClassState
Stores an instance of the BaseConditionClassType ObjectType.
class BaseEventState
Stores an instance of the BaseEventType ObjectType.
class BaseInterfaceState
Stores an instance of the BaseInterfaceType ObjectType.
class BaseModelChangeEventState
Stores an instance of the BaseModelChangeEventType ObjectType.
class BrokerConnectionTransportDataType
class BrokerConnectionTransportDataTypeCollection
A collection of BrokerConnectionTransportDataType objects.
class BrokerConnectionTransportState
Stores an instance of the BrokerConnectionTransportType ObjectType.
class BrokerDataSetReaderTransportDataType
class BrokerDataSetReaderTransportDataTypeCollection
A collection of BrokerDataSetReaderTransportDataType objects.
class BrokerDataSetReaderTransportState
Stores an instance of the BrokerDataSetReaderTransportType ObjectType.
class BrokerDataSetWriterTransportDataType
class BrokerDataSetWriterTransportDataTypeCollection
A collection of BrokerDataSetWriterTransportDataType objects.
class BrokerDataSetWriterTransportState
Stores an instance of the BrokerDataSetWriterTransportType ObjectType.
class BrokerTransportQualityOfServiceCollection
A collection of BrokerTransportQualityOfService objects.
class BrokerWriterGroupTransportDataType
class BrokerWriterGroupTransportDataTypeCollection
A collection of BrokerWriterGroupTransportDataType objects.
class BrokerWriterGroupTransportState
Stores an instance of the BrokerWriterGroupTransportType ObjectType.
class BrowseDescription
class BrowseDescriptionCollection
A collection of BrowseDescription objects.
class BrowseMessage
The message contract for the Browse service.
class BrowseNames
Declares all of the BrowseNames used in the Model Design.
class BrowseNextMessage
The message contract for the BrowseNext service.
class BrowseNextRequest
class BrowseNextResponse
class BrowseNextResponseMessage
The message contract for the BrowseNext service response.
class BrowsePath
class BrowsePathCollection
A collection of BrowsePath objects.
class BrowsePathResult
class BrowsePathResultCollection
A collection of BrowsePathResult objects.
class BrowsePathTarget
class BrowsePathTargetCollection
A collection of BrowsePathTarget objects.
class BrowseRequest
class BrowseResponse
class BrowseResponseMessage
The message contract for the Browse service response.
class BrowseResult
class BrowseResultCollection
A collection of BrowseResult objects.
class BuildInfo
class BuildInfoVariableState
Stores an instance of the BuildInfoType VariableType.
class BuildInfoVariableValue
A typed version of the BrowseName variable.
class CallMessage
The message contract for the Call service.
class CallMethodRequest
class CallMethodRequestCollection
A collection of CallMethodRequest objects.
class CallMethodResult
class CallMethodResultCollection
A collection of CallMethodResult objects.
class CallRequest
class CallResponse
class CallResponseMessage
The message contract for the Call service response.
class CancelMessage
The message contract for the Cancel service.
class CancelRequest
class CancelResponse
class CancelResponseMessage
The message contract for the Cancel service response.
class CartesianCoordinates
class CartesianCoordinatesCollection
A collection of CartesianCoordinates objects.
class CartesianCoordinatesState
Stores an instance of the CartesianCoordinatesType VariableType.
class CertificateExpirationAlarmState
Stores an instance of the CertificateExpirationAlarmType ObjectType.
class CertificateGroupFolderState
Stores an instance of the CertificateGroupFolderType ObjectType.
class CertificateGroupState
Stores an instance of the CertificateGroupType ObjectType.
class CertificateState
Stores an instance of the CertificateType ObjectType.
class CertificateUpdatedAuditEventState
Stores an instance of the CertificateUpdatedAuditEventType ObjectType.
class ChannelSecurityToken
class CloseAndCommitMethodState
Stores an instance of the CloseAndCommitMethodType Method.
class CloseAndUpdateMethodState
Stores an instance of the CloseAndUpdateMethodType Method.
class CloseMethodState
Stores an instance of the CloseMethodType Method.
class CloseSecureChannelMessage
The message contract for the CloseSecureChannel service.
class CloseSecureChannelRequest
class CloseSecureChannelResponse
class CloseSecureChannelResponseMessage
The message contract for the CloseSecureChannel service response.
class CloseSessionMessage
The message contract for the CloseSession service.
class CloseSessionRequest
class CloseSessionResponse
class CloseSessionResponseMessage
The message contract for the CloseSession service response.
class ComplexNumberType
class ConditionRefresh2MethodState
Stores an instance of the ConditionRefresh2MethodType Method.
class ConditionRefreshMethodState
Stores an instance of the ConditionRefreshMethodType Method.
class ConditionState
Stores an instance of the ConditionType ObjectType.
class ConditionVariableState
Stores an instance of the ConditionVariableType VariableType.
class ConfigurationVersionDataType
class ConfigurationVersionDataTypeCollection
A collection of ConfigurationVersionDataType objects.
class ConnectionTransportDataType
class ConnectionTransportDataTypeCollection
A collection of ConnectionTransportDataType objects.
class ConnectionTransportState
Stores an instance of the ConnectionTransportType ObjectType.
class ContentFilter
class ContentFilterCollection
A collection of ContentFilter objects.
class ContentFilterElement
class ContentFilterElementCollection
A collection of ContentFilterElement objects.
class ContentFilterElementResult
class ContentFilterElementResultCollection
A collection of ContentFilterElementResult objects.
class ContentFilterResult
class CreateCredentialMethodState
Stores an instance of the CreateCredentialMethodType Method.
class CreateDirectoryMethodState
Stores an instance of the CreateDirectoryMethodType Method.
class CreateFileMethodState
Stores an instance of the CreateFileMethodType Method.
class CreateMonitoredItemsMessage
The message contract for the CreateMonitoredItems service.
class CreateMonitoredItemsRequest
class CreateMonitoredItemsResponse
class CreateMonitoredItemsResponseMessage
The message contract for the CreateMonitoredItems service response.
class CreateSessionMessage
The message contract for the CreateSession service.
class CreateSessionRequest
class CreateSessionResponse
class CreateSessionResponseMessage
The message contract for the CreateSession service response.
class CreateSigningRequestMethodState
Stores an instance of the CreateSigningRequestMethodType Method.
class CreateSubscriptionMessage
The message contract for the CreateSubscription service.
class CreateSubscriptionRequest
class CreateSubscriptionResponse
class CreateSubscriptionResponseMessage
The message contract for the CreateSubscription service response.
class CubeItemState
Stores an instance of the CubeItemType VariableType.
class DataChangeFilter
class DataChangeNotification
class DatagramConnectionTransportDataType
class DatagramConnectionTransportDataTypeCollection
A collection of DatagramConnectionTransportDataType objects.
class DatagramConnectionTransportState
Stores an instance of the DatagramConnectionTransportType ObjectType.
class DatagramWriterGroupTransportDataType
class DatagramWriterGroupTransportDataTypeCollection
A collection of DatagramWriterGroupTransportDataType objects.
class DatagramWriterGroupTransportState
Stores an instance of the DatagramWriterGroupTransportType ObjectType.
class DataItemState
Stores an instance of the DataItemType VariableType.
class DataSetFieldContentMaskCollection
A collection of DataSetFieldContentMask objects.
class DataSetFolderState
Stores an instance of the DataSetFolderType ObjectType.
class DataSetMetaDataType
class DataSetMetaDataTypeCollection
A collection of DataSetMetaDataType objects.
class DataSetOrderingTypeCollection
A collection of DataSetOrderingType objects.
class DataSetReaderDataType
class DataSetReaderDataTypeCollection
A collection of DataSetReaderDataType objects.
class DataSetReaderMessageDataType
class DataSetReaderMessageDataTypeCollection
A collection of DataSetReaderMessageDataType objects.
class DataSetReaderMessageState
Stores an instance of the DataSetReaderMessageType ObjectType.
class DataSetReaderState
Stores an instance of the DataSetReaderType ObjectType.
class DataSetReaderTransportDataType
class DataSetReaderTransportDataTypeCollection
A collection of DataSetReaderTransportDataType objects.
class DataSetReaderTransportState
Stores an instance of the DataSetReaderTransportType ObjectType.
class DataSetReaderTypeCreateDataSetMirrorMethodState
Stores an instance of the DataSetReaderTypeCreateDataSetMirrorMethodType Method.
class DataSetReaderTypeCreateTargetVariablesMethodState
Stores an instance of the DataSetReaderTypeCreateTargetVariablesMethodType Method.
class DataSetWriterDataType
class DataSetWriterDataTypeCollection
A collection of DataSetWriterDataType objects.
class DataSetWriterMessageDataType
class DataSetWriterMessageDataTypeCollection
A collection of DataSetWriterMessageDataType objects.
class DataSetWriterMessageState
Stores an instance of the DataSetWriterMessageType ObjectType.
class DataSetWriterState
Stores an instance of the DataSetWriterType ObjectType.
class DataSetWriterTransportDataType
class DataSetWriterTransportDataTypeCollection
A collection of DataSetWriterTransportDataType objects.
class DataSetWriterTransportState
Stores an instance of the DataSetWriterTransportType ObjectType.
class DataTypeAttributes
class DataTypeDefinition
class DataTypeDefinitionCollection
A collection of DataTypeDefinition objects.
class DataTypeDescription
class DataTypeDescriptionCollection
A collection of DataTypeDescription objects.
class DataTypeIds
A class that declares constants for all DataTypes in the Model Design.
class DataTypeNode
class DataTypes
A class that declares constants for all DataTypes in the Model Design.
class DataTypeSchemaHeader
class DataTypeSchemaHeaderCollection
A collection of DataTypeSchemaHeader objects.
class DecimalDataType
class DeleteAtTimeDetails
class DeleteEventDetails
class DeleteFileMethodState
Stores an instance of the DeleteFileMethodType Method.
class DeleteMonitoredItemsMessage
The message contract for the DeleteMonitoredItems service.
class DeleteMonitoredItemsRequest
class DeleteMonitoredItemsResponse
class DeleteMonitoredItemsResponseMessage
The message contract for the DeleteMonitoredItems service response.
class DeleteNodesItem
class DeleteNodesItemCollection
A collection of DeleteNodesItem objects.
class DeleteNodesMessage
The message contract for the DeleteNodes service.
class DeleteNodesRequest
class DeleteNodesResponse
class DeleteNodesResponseMessage
The message contract for the DeleteNodes service response.
class DeleteRawModifiedDetails
class DeleteReferencesItem
class DeleteReferencesItemCollection
A collection of DeleteReferencesItem objects.
class DeleteReferencesMessage
The message contract for the DeleteReferences service.
class DeleteReferencesRequest
class DeleteReferencesResponse
class DeleteReferencesResponseMessage
The message contract for the DeleteReferences service response.
class DeleteSubscriptionsMessage
The message contract for the DeleteSubscriptions service.
class DeleteSubscriptionsRequest
class DeleteSubscriptionsResponse
class DeleteSubscriptionsResponseMessage
The message contract for the DeleteSubscriptions service response.
class DeviceFailureEventState
Stores an instance of the DeviceFailureEventType ObjectType.
class DiagnosticsLevelCollection
A collection of DiagnosticsLevel objects.
class DialogConditionState
Stores an instance of the DialogConditionType ObjectType.
class DialogResponseMethodState
Stores an instance of the DialogResponseMethodType Method.
class DictionaryEntryState
Stores an instance of the DictionaryEntryType ObjectType.
class DictionaryFolderState
Stores an instance of the DictionaryFolderType ObjectType.
class DiscoveryChannel
A channel object used by clients to access a UA service.
class DiscoveryClient
The client side interface for a UA server.
class DiscoveryConfiguration
class DiscoveryEndpoint
A endpoint object used by clients to access a UA service.
class DiscoveryServerBase
A basic implementation of the UA server.
class DiscrepancyAlarmState
Stores an instance of the DiscrepancyAlarmType ObjectType.
class DiscreteAlarmState
Stores an instance of the DiscreteAlarmType ObjectType.
class DiscreteItemState
Stores an instance of the DiscreteItemType VariableType.
class DoubleComplexNumberType
class ElementOperand
class ElseGuardVariableState
Stores an instance of the ElseGuardVariableType VariableType.
class EndpointConfiguration
class EndpointConfigurationCollection
A collection of EndpointConfiguration objects.
class EndpointDescription
class EndpointDescriptionCollection
A collection of EndpointDescription objects.
class EndpointType
class EndpointTypeCollection
A collection of EndpointType objects.
class EndpointUrlListDataType
class EndpointUrlListDataTypeCollection
A collection of EndpointUrlListDataType objects.
class EnumDefinition
class EnumDefinitionCollection
A collection of EnumDefinition objects.
class EnumDescription
class EnumDescriptionCollection
A collection of EnumDescription objects.
class EnumerationCollection
A collection of Enumeration objects.
class EnumField
class EnumFieldCollection
A collection of EnumField objects.
class EnumValueType
class EnumValueTypeCollection
A collection of EnumValueType objects.
class EUInformation
class EventFieldList
class EventFieldListCollection
A collection of EventFieldList objects.
class EventFilter
class EventFilterResult
class EventNotificationList
class EventQueueOverflowEventState
Stores an instance of the EventQueueOverflowEventType ObjectType.
class ExclusiveDeviationAlarmState
Stores an instance of the ExclusiveDeviationAlarmType ObjectType.
class ExclusiveLevelAlarmState
Stores an instance of the ExclusiveLevelAlarmType ObjectType.
class ExclusiveLimitAlarmState
Stores an instance of the ExclusiveLimitAlarmType ObjectType.
class ExclusiveLimitStateMachineState
Stores an instance of the ExclusiveLimitStateMachineType ObjectType.
class ExclusiveRateOfChangeAlarmState
Stores an instance of the ExclusiveRateOfChangeAlarmType ObjectType.
class ExpressionGuardVariableState
Stores an instance of the ExpressionGuardVariableType VariableType.
class ExtensionFieldsState
Stores an instance of the ExtensionFieldsType ObjectType.
class FieldMetaData
class FieldMetaDataCollection
A collection of FieldMetaData objects.
class FieldTargetDataType
class FieldTargetDataTypeCollection
A collection of FieldTargetDataType objects.
class FileDirectoryState
Stores an instance of the FileDirectoryType ObjectType.
class FileState
Stores an instance of the FileType ObjectType.
class FileTransferStateMachineState
Stores an instance of the FileTransferStateMachineType ObjectType.
class FilterOperand
class FindServersMessage
The message contract for the FindServers service.
class FindServersOnNetworkMessage
The message contract for the FindServersOnNetwork service.
class FindServersOnNetworkRequest
class FindServersOnNetworkResponse
class FindServersOnNetworkResponseMessage
The message contract for the FindServersOnNetwork service response.
class FindServersRequest
class FindServersResponse
class FindServersResponseMessage
The message contract for the FindServers service response.
class FiniteStateMachineState
Stores an instance of the FiniteStateMachineType ObjectType.
class FiniteStateVariableState
Stores an instance of the FiniteStateVariableType VariableType.
class FiniteTransitionVariableState
Stores an instance of the FiniteTransitionVariableType VariableType.
class Frame
class FrameCollection
A collection of Frame objects.
class FrameState
Stores an instance of the FrameType VariableType.
class GeneralModelChangeEventState
Stores an instance of the GeneralModelChangeEventType ObjectType.
class GenerateFileForReadMethodState
Stores an instance of the GenerateFileForReadMethodType Method.
class GenerateFileForWriteMethodState
Stores an instance of the GenerateFileForWriteMethodType Method.
class GenericAttributes
class GenericAttributeValue
class GenericAttributeValueCollection
A collection of GenericAttributeValue objects.
class GetEncryptingKeyMethodState
Stores an instance of the GetEncryptingKeyMethodType Method.
class GetEndpointsMessage
The message contract for the GetEndpoints service.
class GetEndpointsRequest
class GetEndpointsResponse
class GetEndpointsResponseMessage
The message contract for the GetEndpoints service response.
class GetMonitoredItemsMethodState
Stores an instance of the GetMonitoredItemsMethodType Method.
class GetPositionMethodState
Stores an instance of the GetPositionMethodType Method.
class GetRejectedListMethodState
Stores an instance of the GetRejectedListMethodType Method.
class GetSecurityGroupMethodState
Stores an instance of the GetSecurityGroupMethodType Method.
class GetSecurityKeysMethodState
Stores an instance of the GetSecurityKeysMethodType Method.
class GuardVariableState
Stores an instance of the GuardVariableType VariableType.
class HighlyManagedAlarmConditionClassState
Stores an instance of the HighlyManagedAlarmConditionClassType ObjectType.
class HistoricalDataConfigurationState
Stores an instance of the HistoricalDataConfigurationType ObjectType.
class HistoryData
class HistoryEvent
class HistoryEventFieldList
class HistoryEventFieldListCollection
A collection of HistoryEventFieldList objects.
class HistoryModifiedData
class HistoryReadDetails
class HistoryReadMessage
The message contract for the HistoryRead service.
class HistoryReadRequest
class HistoryReadResponse
class HistoryReadResponseMessage
The message contract for the HistoryRead service response.
class HistoryReadResult
class HistoryReadResultCollection
A collection of HistoryReadResult objects.
class HistoryReadValueId
class HistoryReadValueIdCollection
A collection of HistoryReadValueId objects.
class HistoryServerCapabilitiesState
Stores an instance of the HistoryServerCapabilitiesType ObjectType.
class HistoryUpdateDetails
class HistoryUpdateMessage
The message contract for the HistoryUpdate service.
class HistoryUpdateRequest
class HistoryUpdateResponse
class HistoryUpdateResponseMessage
The message contract for the HistoryUpdate service response.
class HistoryUpdateResult
class HistoryUpdateResultCollection
A collection of HistoryUpdateResult objects.
class HttpsCertificateState
Stores an instance of the HttpsCertificateType ObjectType.
class IdentityCriteriaTypeCollection
A collection of IdentityCriteriaType objects.
class IdentityMappingRuleType
class IdentityMappingRuleTypeCollection
A collection of IdentityMappingRuleType objects.
interface IDiscoveryChannel
An interface used by by clients to access a UA server.
interface IDiscoveryEndpoint
The service contract which must be implemented by all UA servers.
interface IDiscoveryServer
An interface to a UA server implementation.
class IdTypeCollection
A collection of IdType objects.
class ImageItemState
Stores an instance of the ImageItemType VariableType.
class InstanceNode
class InstrumentDiagnosticAlarmState
Stores an instance of the InstrumentDiagnosticAlarmType ObjectType.
class IrdiDictionaryEntryState
Stores an instance of the IrdiDictionaryEntryType ObjectType.
interface IRegistrationChannel
An interface used by by clients to access a UA server.
interface IRegistrationEndpoint
The service contract which must be implemented by all UA servers.
interface ISessionChannel
An interface used by by clients to access a UA server.
interface ISessionEndpoint
The service contract which must be implemented by all UA servers.
interface ISessionServer
An interface to a UA server implementation.
class IssuedIdentityToken
class JsonDataSetMessageContentMaskCollection
A collection of JsonDataSetMessageContentMask objects.
class JsonDataSetReaderMessageDataType
class JsonDataSetReaderMessageDataTypeCollection
A collection of JsonDataSetReaderMessageDataType objects.
class JsonDataSetReaderMessageState
Stores an instance of the JsonDataSetReaderMessageType ObjectType.
class JsonDataSetWriterMessageDataType
class JsonDataSetWriterMessageDataTypeCollection
A collection of JsonDataSetWriterMessageDataType objects.
class JsonDataSetWriterMessageState
Stores an instance of the JsonDataSetWriterMessageType ObjectType.
class JsonNetworkMessageContentMaskCollection
A collection of JsonNetworkMessageContentMask objects.
class JsonWriterGroupMessageDataType
class JsonWriterGroupMessageDataTypeCollection
A collection of JsonWriterGroupMessageDataType objects.
class JsonWriterGroupMessageState
Stores an instance of the JsonWriterGroupMessageType ObjectType.
class KeyCredentialAuditEventState
Stores an instance of the KeyCredentialAuditEventType ObjectType.
class KeyCredentialConfigurationFolderState
Stores an instance of the KeyCredentialConfigurationFolderType ObjectType.
class KeyCredentialConfigurationState
Stores an instance of the KeyCredentialConfigurationType ObjectType.
class KeyCredentialDeletedAuditEventState
Stores an instance of the KeyCredentialDeletedAuditEventType ObjectType.
class KeyCredentialUpdatedAuditEventState
Stores an instance of the KeyCredentialUpdatedAuditEventType ObjectType.
class KeyCredentialUpdateMethodState
Stores an instance of the KeyCredentialUpdateMethodType Method.
class KeyValuePair
class KeyValuePairCollection
A collection of KeyValuePair objects.
class LimitAlarmState
Stores an instance of the LimitAlarmType ObjectType.
class LiteralOperand
class MaintenanceConditionClassState
Stores an instance of the MaintenanceConditionClassType ObjectType.
class MdnsDiscoveryConfiguration
class MethodAttributes
class MethodIds
A class that declares constants for all Methods in the Model Design.
class MethodNode
class Methods
A class that declares constants for all Methods in the Model Design.
class ModelChangeStructureDataType
class ModelChangeStructureDataTypeCollection
A collection of ModelChangeStructureDataType objects.
class ModificationInfo
class ModificationInfoCollection
A collection of ModificationInfo objects.
class ModifyMonitoredItemsMessage
The message contract for the ModifyMonitoredItems service.
class ModifyMonitoredItemsRequest
class ModifyMonitoredItemsResponse
class ModifyMonitoredItemsResponseMessage
The message contract for the ModifyMonitoredItems service response.
class ModifySubscriptionMessage
The message contract for the ModifySubscription service.
class ModifySubscriptionRequest
class ModifySubscriptionResponse
class ModifySubscriptionResponseMessage
The message contract for the ModifySubscription service response.
class MonitoredItemCreateRequest
class MonitoredItemCreateRequestCollection
A collection of MonitoredItemCreateRequest objects.
class MonitoredItemCreateResult
class MonitoredItemCreateResultCollection
A collection of MonitoredItemCreateResult objects.
class MonitoredItemModifyRequest
class MonitoredItemModifyRequestCollection
A collection of MonitoredItemModifyRequest objects.
class MonitoredItemModifyResult
class MonitoredItemModifyResultCollection
A collection of MonitoredItemModifyResult objects.
class MonitoredItemNotification
class MonitoredItemNotificationCollection
A collection of MonitoredItemNotification objects.
class MonitoringFilter
class MonitoringFilterResult
class MonitoringParameters
class MoveOrCopyMethodState
Stores an instance of the MoveOrCopyMethodType Method.
class MultiStateDiscreteState
Stores an instance of the MultiStateDiscreteType VariableType.
class MultiStateValueDiscreteState
Stores an instance of the MultiStateValueDiscreteType VariableType.
class NamespaceMetadataState
Stores an instance of the NamespaceMetadataType ObjectType.
class Namespaces
Defines constants for all namespaces referenced by the model design.
class NamespacesState
Stores an instance of the NamespacesType ObjectType.
class NamingRuleTypeCollection
A collection of NamingRuleType objects.
class NDimensionArrayItemState
Stores an instance of the NDimensionArrayItemType VariableType.
class NetworkAddressDataType
class NetworkAddressDataTypeCollection
A collection of NetworkAddressDataType objects.
class NetworkAddressState
Stores an instance of the NetworkAddressType ObjectType.
class NetworkAddressUrlDataType
class NetworkAddressUrlDataTypeCollection
A collection of NetworkAddressUrlDataType objects.
class NetworkAddressUrlState
Stores an instance of the NetworkAddressUrlType ObjectType.
class NetworkGroupDataType
class NetworkGroupDataTypeCollection
A collection of NetworkGroupDataType objects.
class Node
class NodeAttributes
class NodeCollection
A collection of Node objects.
class NodeReference
class NodeReferenceCollection
A collection of NodeReference objects.
class NodeTypeDescription
class NodeTypeDescriptionCollection
A collection of NodeTypeDescription objects.
class NonExclusiveDeviationAlarmState
Stores an instance of the NonExclusiveDeviationAlarmType ObjectType.
class NonExclusiveLevelAlarmState
Stores an instance of the NonExclusiveLevelAlarmType ObjectType.
class NonExclusiveLimitAlarmState
Stores an instance of the NonExclusiveLimitAlarmType ObjectType.
class NonExclusiveRateOfChangeAlarmState
Stores an instance of the NonExclusiveRateOfChangeAlarmType ObjectType.
class NonTransparentNetworkRedundancyState
Stores an instance of the NonTransparentNetworkRedundancyType ObjectType.
class NonTransparentRedundancyState
Stores an instance of the NonTransparentRedundancyType ObjectType.
class NotificationData
class NotificationMessage
class ObjectAttributes
class ObjectIds
A class that declares constants for all Objects in the Model Design.
class ObjectNode
class Objects
A class that declares constants for all Objects in the Model Design.
class ObjectTypeAttributes
class ObjectTypeIds
A class that declares constants for all ObjectTypes in the Model Design.
class ObjectTypeNode
class ObjectTypes
A class that declares constants for all ObjectTypes in the Model Design.
class OffNormalAlarmState
Stores an instance of the OffNormalAlarmType ObjectType.
class OpenFileModeCollection
A collection of OpenFileMode objects.
class OpenMethodState
Stores an instance of the OpenMethodType Method.
class OpenSecureChannelMessage
The message contract for the OpenSecureChannel service.
class OpenSecureChannelRequest
class OpenSecureChannelResponse
class OpenSecureChannelResponseMessage
The message contract for the OpenSecureChannel service response.
class OpenWithMasksMethodState
Stores an instance of the OpenWithMasksMethodType Method.
class OperationLimitsState
Stores an instance of the OperationLimitsType ObjectType.
class OptionSet
class OptionSetCollection
A collection of OptionSet objects.
class OptionSetState
Stores an instance of the OptionSetType VariableType.
class Orientation
class OrientationCollection
A collection of Orientation objects.
class OrientationState
Stores an instance of the OrientationType VariableType.
class OverrideValueHandlingCollection
A collection of OverrideValueHandling objects.
class ParsingResult
class ParsingResultCollection
A collection of ParsingResult objects.
class ProcessConditionClassState
Stores an instance of the ProcessConditionClassType ObjectType.
class ProgramDiagnostic2DataType
class ProgramDiagnostic2State
Stores an instance of the ProgramDiagnostic2Type VariableType.
class ProgramDiagnostic2Value
A typed version of the BrowseName variable.
class ProgramDiagnosticDataType
class ProgramDiagnosticState
Stores an instance of the ProgramDiagnosticType VariableType.
class ProgramDiagnosticValue
A typed version of the BrowseName variable.
class ProgramStateMachineState
Stores an instance of the ProgramStateMachineType ObjectType.
class ProgramTransitionAuditEventState
Stores an instance of the ProgramTransitionAuditEventType ObjectType.
class ProgramTransitionEventState
Stores an instance of the ProgramTransitionEventType ObjectType.
class ProgressEventState
Stores an instance of the ProgressEventType ObjectType.
class PublishedDataItemsAddVariablesMethodState
Stores an instance of the PublishedDataItemsAddVariablesMethodType Method.
class PublishedDataItemsDataType
class PublishedDataItemsDataTypeCollection
A collection of PublishedDataItemsDataType objects.
class PublishedDataItemsRemoveVariablesMethodState
Stores an instance of the PublishedDataItemsRemoveVariablesMethodType Method.
class PublishedDataItemsState
Stores an instance of the PublishedDataItemsType ObjectType.
class PublishedDataSetDataType
class PublishedDataSetDataTypeCollection
A collection of PublishedDataSetDataType objects.
class PublishedDataSetSourceDataType
class PublishedDataSetSourceDataTypeCollection
A collection of PublishedDataSetSourceDataType objects.
class PublishedDataSetState
Stores an instance of the PublishedDataSetType ObjectType.
class PublishedEventsDataType
class PublishedEventsDataTypeCollection
A collection of PublishedEventsDataType objects.
class PublishedEventsState
Stores an instance of the PublishedEventsType ObjectType.
class PublishedEventsTypeModifyFieldSelectionMethodState
Stores an instance of the PublishedEventsTypeModifyFieldSelectionMethodType Method.
class PublishedVariableDataType
class PublishedVariableDataTypeCollection
A collection of PublishedVariableDataType objects.
class PublishMessage
The message contract for the Publish service.
class PublishRequest
class PublishResponse
class PublishResponseMessage
The message contract for the Publish service response.
class PublishSubscribeState
Stores an instance of the PublishSubscribeType ObjectType.
class PubSubCommunicationFailureEventState
Stores an instance of the PubSubCommunicationFailureEventType ObjectType.
class PubSubConfigurationDataType
class PubSubConfigurationDataTypeCollection
A collection of PubSubConfigurationDataType objects.
class PubSubConnectionAddReaderGroupGroupMethodState
Stores an instance of the PubSubConnectionAddReaderGroupGroupMethodType Method.
class PubSubConnectionDataType
class PubSubConnectionDataTypeCollection
A collection of PubSubConnectionDataType objects.
class PubSubConnectionState
Stores an instance of the PubSubConnectionType ObjectType.
class PubSubConnectionTypeAddWriterGroupMethodState
Stores an instance of the PubSubConnectionTypeAddWriterGroupMethodType Method.
class PubSubConnectionTypeRemoveGroupMethodState
Stores an instance of the PubSubConnectionTypeRemoveGroupMethodType Method.
class PubSubDiagnosticsConnectionState
Stores an instance of the PubSubDiagnosticsConnectionType ObjectType.
class PubSubDiagnosticsCounterClassificationCollection
A collection of PubSubDiagnosticsCounterClassification objects.
class PubSubDiagnosticsCounterState
Stores an instance of the PubSubDiagnosticsCounterType VariableType.
class PubSubDiagnosticsDataSetReaderState
Stores an instance of the PubSubDiagnosticsDataSetReaderType ObjectType.
class PubSubDiagnosticsDataSetWriterState
Stores an instance of the PubSubDiagnosticsDataSetWriterType ObjectType.
class PubSubDiagnosticsReaderGroupState
Stores an instance of the PubSubDiagnosticsReaderGroupType ObjectType.
class PubSubDiagnosticsRootState
Stores an instance of the PubSubDiagnosticsRootType ObjectType.
class PubSubDiagnosticsState
Stores an instance of the PubSubDiagnosticsType ObjectType.
class PubSubDiagnosticsWriterGroupState
Stores an instance of the PubSubDiagnosticsWriterGroupType ObjectType.
class PubSubGroupDataType
class PubSubGroupDataTypeCollection
A collection of PubSubGroupDataType objects.
class PubSubGroupState
Stores an instance of the PubSubGroupType ObjectType.
class PubSubGroupTypeAddReaderMethodState
Stores an instance of the PubSubGroupTypeAddReaderMethodType Method.
class PubSubGroupTypeAddWriterrMethodState
Stores an instance of the PubSubGroupTypeAddWriterrMethodType Method.
class PubSubGroupTypeRemoveReaderMethodState
Stores an instance of the PubSubGroupTypeRemoveReaderMethodType Method.
class PubSubGroupTypeRemoveWriterMethodState
Stores an instance of the PubSubGroupTypeRemoveWriterMethodType Method.
class PubSubKeyServiceState
Stores an instance of the PubSubKeyServiceType ObjectType.
class PubSubStateCollection
A collection of PubSubState objects.
class PubSubStatusEventState
Stores an instance of the PubSubStatusEventType ObjectType.
class PubSubStatusState
Stores an instance of the PubSubStatusType ObjectType.
class PubSubTransportLimitsExceedEventState
Stores an instance of the PubSubTransportLimitsExceedEventType ObjectType.
class QueryDataDescription
class QueryDataDescriptionCollection
A collection of QueryDataDescription objects.
class QueryDataSet
class QueryDataSetCollection
A collection of QueryDataSet objects.
class QueryFirstMessage
The message contract for the QueryFirst service.
class QueryFirstRequest
class QueryFirstResponse
class QueryFirstResponseMessage
The message contract for the QueryFirst service response.
class QueryNextMessage
The message contract for the QueryNext service.
class QueryNextRequest
class QueryNextResponse
class QueryNextResponseMessage
The message contract for the QueryNext service response.
class Range
class RationalNumber
class RationalNumberCollection
A collection of RationalNumber objects.
class RationalNumberState
Stores an instance of the RationalNumberType VariableType.
class RationalNumberValue
A typed version of the BrowseName variable.
class ReadAtTimeDetails
class ReaderGroupDataType
class ReaderGroupDataTypeCollection
A collection of ReaderGroupDataType objects.
class ReaderGroupMessageDataType
class ReaderGroupMessageDataTypeCollection
A collection of ReaderGroupMessageDataType objects.
class ReaderGroupMessageState
Stores an instance of the ReaderGroupMessageType ObjectType.
class ReaderGroupState
Stores an instance of the ReaderGroupType ObjectType.
class ReaderGroupTransportDataType
class ReaderGroupTransportDataTypeCollection
A collection of ReaderGroupTransportDataType objects.
class ReaderGroupTransportState
Stores an instance of the ReaderGroupTransportType ObjectType.
class ReadEventDetails
class ReadMessage
The message contract for the Read service.
class ReadMethodState
Stores an instance of the ReadMethodType Method.
class ReadProcessedDetails
class ReadRawModifiedDetails
class ReadRequest
class ReadResponse
class ReadResponseMessage
The message contract for the Read service response.
class ReadValueId
class ReadValueIdCollection
A collection of ReadValueId objects.
class RedundantServerDataType
class RedundantServerDataTypeCollection
A collection of RedundantServerDataType objects.
class ReferenceDescription
class ReferenceDescriptionCollection
A collection of ReferenceDescription objects.
class ReferenceNode
class ReferenceNodeCollection
A collection of ReferenceNode objects.
class ReferenceTypeAttributes
class ReferenceTypeIds
A class that declares constants for all ReferenceTypes in the Model Design.
class ReferenceTypeNode
class ReferenceTypes
A class that declares constants for all ReferenceTypes in the Model Design.
class RefreshEndEventState
Stores an instance of the RefreshEndEventType ObjectType.
class RefreshRequiredEventState
Stores an instance of the RefreshRequiredEventType ObjectType.
class RefreshStartEventState
Stores an instance of the RefreshStartEventType ObjectType.
class RegisteredServer
class RegisteredServerCollection
A collection of RegisteredServer objects.
class RegisterNodesMessage
The message contract for the RegisterNodes service.
class RegisterNodesRequest
class RegisterNodesResponse
class RegisterNodesResponseMessage
The message contract for the RegisterNodes service response.
class RegisterServer2Message
The message contract for the RegisterServer2 service.
class RegisterServer2Request
class RegisterServer2Response
class RegisterServer2ResponseMessage
The message contract for the RegisterServer2 service response.
class RegisterServerMessage
The message contract for the RegisterServer service.
class RegisterServerRequest
class RegisterServerResponse
class RegisterServerResponseMessage
The message contract for the RegisterServer service response.
class RegistrationChannel
A channel object used by clients to access a UA service.
class RegistrationClient
The client side interface for a UA server.
class RelativePath
class RelativePathElement
class RelativePathElementCollection
A collection of RelativePathElement objects.
class RemoveApplicationMethodState
Stores an instance of the RemoveApplicationMethodType Method.
class RemoveCertificateMethodState
Stores an instance of the RemoveCertificateMethodType Method.
class RemoveConnectionMethodState
Stores an instance of the RemoveConnectionMethodType Method.
class RemoveDataSetFolderMethodState
Stores an instance of the RemoveDataSetFolderMethodType Method.
class RemoveEndpointMethodState
Stores an instance of the RemoveEndpointMethodType Method.
class RemoveExtensionFieldMethodState
Stores an instance of the RemoveExtensionFieldMethodType Method.
class RemoveIdentityMethodState
Stores an instance of the RemoveIdentityMethodType Method.
class RemovePublishedDataSetMethodState
Stores an instance of the RemovePublishedDataSetMethodType Method.
class RemoveRoleMethodState
Stores an instance of the RemoveRoleMethodType Method.
class RemoveSecurityGroupMethodState
Stores an instance of the RemoveSecurityGroupMethodType Method.
class RepublishMessage
The message contract for the Republish service.
class RepublishRequest
class RepublishResponse
class RepublishResponseMessage
The message contract for the Republish service response.
class RequestHeader
class RequestServerStateChangeMethodState
Stores an instance of the RequestServerStateChangeMethodType Method.
class ResendDataMethodState
Stores an instance of the ResendDataMethodType Method.
class ResponseHeader
class RoleMappingRuleChangedAuditEventState
Stores an instance of the RoleMappingRuleChangedAuditEventType ObjectType.
class RolePermissionType
class RolePermissionTypeCollection
A collection of RolePermissionType objects.
class RoleSetState
Stores an instance of the RoleSetType ObjectType.
class RoleState
Stores an instance of the RoleType ObjectType.
class RsaMinApplicationCertificateState
Stores an instance of the RsaMinApplicationCertificateType ObjectType.
class RsaSha256ApplicationCertificateState
Stores an instance of the RsaSha256ApplicationCertificateType ObjectType.
class SafetyConditionClassState
Stores an instance of the SafetyConditionClassType ObjectType.
class SamplingIntervalDiagnosticsArrayState
Stores an instance of the SamplingIntervalDiagnosticsArrayType VariableType.
class SamplingIntervalDiagnosticsDataType
class SamplingIntervalDiagnosticsDataTypeCollection
A collection of SamplingIntervalDiagnosticsDataType objects.
class SamplingIntervalDiagnosticsState
Stores an instance of the SamplingIntervalDiagnosticsType VariableType.
class SamplingIntervalDiagnosticsValue
A typed version of the BrowseName variable.
class SecurityGroupFolderState
Stores an instance of the SecurityGroupFolderType ObjectType.
class SecurityGroupState
Stores an instance of the SecurityGroupType ObjectType.
class SelectionListState
Stores an instance of the SelectionListType VariableType.
class SemanticChangeEventState
Stores an instance of the SemanticChangeEventType ObjectType.
class SemanticChangeStructureDataType
class SemanticChangeStructureDataTypeCollection
A collection of SemanticChangeStructureDataType objects.
class ServerCapabilitiesState
Stores an instance of the ServerCapabilitiesType ObjectType.
class ServerConfigurationState
Stores an instance of the ServerConfigurationType ObjectType.
class ServerDiagnosticsState
Stores an instance of the ServerDiagnosticsType ObjectType.
class ServerDiagnosticsSummaryDataType
class ServerDiagnosticsSummaryState
Stores an instance of the ServerDiagnosticsSummaryType VariableType.
class ServerDiagnosticsSummaryValue
A typed version of the BrowseName variable.
class ServerObjectState
Stores an instance of the ServerType ObjectType.
class ServerOnNetwork
class ServerOnNetworkCollection
A collection of ServerOnNetwork objects.
class ServerRedundancyState
Stores an instance of the ServerRedundancyType ObjectType.
class ServerStatusDataType
class ServerStatusState
Stores an instance of the ServerStatusType VariableType.
class ServerStatusValue
A typed version of the BrowseName variable.
class ServerVendorCapabilityState
Stores an instance of the ServerVendorCapabilityType VariableType.
class ServiceCounterDataType
class ServiceFault
class SessionChannel
A channel object used by clients to access a UA service.
class SessionClient
The client side interface for a UA server.
class SessionDiagnosticsArrayState
Stores an instance of the SessionDiagnosticsArrayType VariableType.
class SessionDiagnosticsDataType
class SessionDiagnosticsDataTypeCollection
A collection of SessionDiagnosticsDataType objects.
class SessionDiagnosticsObjectState
Stores an instance of the SessionDiagnosticsObjectType ObjectType.
class SessionDiagnosticsVariableState
Stores an instance of the SessionDiagnosticsVariableType VariableType.
class SessionDiagnosticsVariableValue
A typed version of the BrowseName variable.
class SessionEndpoint
A endpoint object used by clients to access a UA service.
class SessionlessInvokeRequestType
class SessionlessInvokeResponseType
class SessionsDiagnosticsSummaryState
Stores an instance of the SessionsDiagnosticsSummaryType ObjectType.
class SessionSecurityDiagnosticsArrayState
Stores an instance of the SessionSecurityDiagnosticsArrayType VariableType.
class SessionSecurityDiagnosticsDataType
class SessionSecurityDiagnosticsDataTypeCollection
A collection of SessionSecurityDiagnosticsDataType objects.
class SessionSecurityDiagnosticsState
Stores an instance of the SessionSecurityDiagnosticsType VariableType.
class SessionSecurityDiagnosticsValue
A typed version of the BrowseName variable.
class SessionServerBase
A basic implementation of the UA server.
class SetMonitoringModeMessage
The message contract for the SetMonitoringMode service.
class SetMonitoringModeRequest
class SetMonitoringModeResponse
class SetMonitoringModeResponseMessage
The message contract for the SetMonitoringMode service response.
class SetPositionMethodState
Stores an instance of the SetPositionMethodType Method.
class SetPublishingModeMessage
The message contract for the SetPublishingMode service.
class SetPublishingModeRequest
class SetPublishingModeResponse
class SetPublishingModeResponseMessage
The message contract for the SetPublishingMode service response.
class SetSecurityKeysMethodState
Stores an instance of the SetSecurityKeysMethodType Method.
class SetSubscriptionDurableMethodState
Stores an instance of the SetSubscriptionDurableMethodType Method.
class SetTriggeringMessage
The message contract for the SetTriggering service.
class SetTriggeringRequest
class SetTriggeringResponse
class SetTriggeringResponseMessage
The message contract for the SetTriggering service response.
class ShelvedStateMachineState
Stores an instance of the ShelvedStateMachineType ObjectType.
class SignatureData
class SignedSoftwareCertificate
class SignedSoftwareCertificateCollection
A collection of SignedSoftwareCertificate objects.
class SimpleAttributeOperand
class SimpleAttributeOperandCollection
A collection of SimpleAttributeOperand objects.
class SimpleTypeDescription
class SimpleTypeDescriptionCollection
A collection of SimpleTypeDescription objects.
class StateMachineChoiceStateTypeState
Stores an instance of the ChoiceStateType ObjectType.
class StateMachineInitialStateState
Stores an instance of the InitialStateType ObjectType.
class StateMachineState
Stores an instance of the StateMachineType ObjectType.
class StateMachineStateState
Stores an instance of the StateType ObjectType.
class StateMachineTransitionState
Stores an instance of the TransitionType ObjectType.
class StateVariableState
Stores an instance of the StateVariableType VariableType.
class StatisticalConditionClassState
Stores an instance of the StatisticalConditionClassType ObjectType.
class StatusChangeNotification
class StatusCodes
A class that defines constants used by UA applications.
class StatusResult
class StatusResultCollection
A collection of StatusResult objects.
class StructureDefinition
class StructureDefinitionCollection
A collection of StructureDefinition objects.
class StructureDescription
class StructureDescriptionCollection
A collection of StructureDescription objects.
class StructureField
class StructureFieldCollection
A collection of StructureField objects.
class SubscribedDataSetDataType
class SubscribedDataSetDataTypeCollection
A collection of SubscribedDataSetDataType objects.
class SubscribedDataSetMirrorDataType
class SubscribedDataSetMirrorDataTypeCollection
A collection of SubscribedDataSetMirrorDataType objects.
class SubscribedDataSetMirrorState
Stores an instance of the SubscribedDataSetMirrorType ObjectType.
class SubscribedDataSetState
Stores an instance of the SubscribedDataSetType ObjectType.
class SubscriptionAcknowledgement
class SubscriptionAcknowledgementCollection
A collection of SubscriptionAcknowledgement objects.
class SubscriptionDiagnosticsArrayState
Stores an instance of the SubscriptionDiagnosticsArrayType VariableType.
class SubscriptionDiagnosticsDataType
class SubscriptionDiagnosticsDataTypeCollection
A collection of SubscriptionDiagnosticsDataType objects.
class SubscriptionDiagnosticsState
Stores an instance of the SubscriptionDiagnosticsType VariableType.
class SubscriptionDiagnosticsValue
A typed version of the BrowseName variable.
class SystemConditionClassState
Stores an instance of the SystemConditionClassType ObjectType.
class SystemDiagnosticAlarmState
Stores an instance of the SystemDiagnosticAlarmType ObjectType.
class SystemEventState
Stores an instance of the SystemEventType ObjectType.
class SystemOffNormalAlarmState
Stores an instance of the SystemOffNormalAlarmType ObjectType.
class SystemStatusChangeEventState
Stores an instance of the SystemStatusChangeEventType ObjectType.
class TargetVariablesDataType
class TargetVariablesDataTypeCollection
A collection of TargetVariablesDataType objects.
class TargetVariablesState
Stores an instance of the TargetVariablesType ObjectType.
class TargetVariablesTypeAddTargetVariablesMethodState
Stores an instance of the TargetVariablesTypeAddTargetVariablesMethodType Method.
class TargetVariablesTypeRemoveTargetVariablesMethodState
Stores an instance of the TargetVariablesTypeRemoveTargetVariablesMethodType Method.
class TemporaryFileTransferState
Stores an instance of the TemporaryFileTransferType ObjectType.
class TestingConditionSubClassState
Stores an instance of the TestingConditionSubClassType ObjectType.
class ThreeDCartesianCoordinates
class ThreeDCartesianCoordinatesCollection
A collection of ThreeDCartesianCoordinates objects.
class ThreeDCartesianCoordinatesState
Stores an instance of the ThreeDCartesianCoordinatesType VariableType.
class ThreeDCartesianCoordinatesValue
A typed version of the BrowseName variable.
class ThreeDFrame
class ThreeDFrameCollection
A collection of ThreeDFrame objects.
class ThreeDFrameState
Stores an instance of the ThreeDFrameType VariableType.
class ThreeDFrameValue
A typed version of the BrowseName variable.
class ThreeDOrientation
class ThreeDOrientationCollection
A collection of ThreeDOrientation objects.
class ThreeDOrientationState
Stores an instance of the ThreeDOrientationType VariableType.
class ThreeDOrientationValue
A typed version of the BrowseName variable.
class ThreeDVector
class ThreeDVectorCollection
A collection of ThreeDVector objects.
class ThreeDVectorState
Stores an instance of the ThreeDVectorType VariableType.
class ThreeDVectorValue
A typed version of the BrowseName variable.
class TimedShelveMethodState
Stores an instance of the TimedShelveMethodType Method.
class TimeZoneDataType
class TimeZoneDataTypeCollection
A collection of TimeZoneDataType objects.
class TrainingConditionClassState
Stores an instance of the TrainingConditionClassType ObjectType.
class TransferResult
class TransferResultCollection
A collection of TransferResult objects.
class TransferSubscriptionsMessage
The message contract for the TransferSubscriptions service.
class TransferSubscriptionsRequest
class TransferSubscriptionsResponse
class TransferSubscriptionsResponseMessage
The message contract for the TransferSubscriptions service response.
class TransitionEventState
Stores an instance of the TransitionEventType ObjectType.
class TransitionVariableState
Stores an instance of the TransitionVariableType VariableType.
class TranslateBrowsePathsToNodeIdsMessage
The message contract for the TranslateBrowsePathsToNodeIds service.
class TranslateBrowsePathsToNodeIdsRequest
class TranslateBrowsePathsToNodeIdsResponse
class TranslateBrowsePathsToNodeIdsResponseMessage
The message contract for the TranslateBrowsePathsToNodeIds service response.
class TransparentRedundancyState
Stores an instance of the TransparentRedundancyType ObjectType.
class TripAlarmState
Stores an instance of the TripAlarmType ObjectType.
class TrustListDataType
class TrustListDataTypeCollection
A collection of TrustListDataType objects.
class TrustListState
Stores an instance of the TrustListType ObjectType.
class TrustListUpdatedAuditEventState
Stores an instance of the TrustListUpdatedAuditEventType ObjectType.
class TwoStateDiscreteState
Stores an instance of the TwoStateDiscreteType VariableType.
class TwoStateVariableState
Stores an instance of the TwoStateVariableType VariableType.
class TypeNode
class UABinaryFileDataType
class UABinaryFileDataTypeCollection
A collection of UABinaryFileDataType objects.
class UadpDataSetMessageContentMaskCollection
A collection of UadpDataSetMessageContentMask objects.
class UadpDataSetReaderMessageDataType
class UadpDataSetReaderMessageDataTypeCollection
A collection of UadpDataSetReaderMessageDataType objects.
class UadpDataSetReaderMessageState
Stores an instance of the UadpDataSetReaderMessageType ObjectType.
class UadpDataSetWriterMessageDataType
class UadpDataSetWriterMessageDataTypeCollection
A collection of UadpDataSetWriterMessageDataType objects.
class UadpDataSetWriterMessageState
Stores an instance of the UadpDataSetWriterMessageType ObjectType.
class UadpNetworkMessageContentMaskCollection
A collection of UadpNetworkMessageContentMask objects.
class UadpWriterGroupMessageDataType
class UadpWriterGroupMessageDataTypeCollection
A collection of UadpWriterGroupMessageDataType objects.
class UadpWriterGroupMessageState
Stores an instance of the UadpWriterGroupMessageType ObjectType.
class Union
class UnionCollection
A collection of Union objects.
class UnregisterNodesMessage
The message contract for the UnregisterNodes service.
class UnregisterNodesRequest
class UnregisterNodesResponse
class UnregisterNodesResponseMessage
The message contract for the UnregisterNodes service response.
class UpdateCertificateMethodState
Stores an instance of the UpdateCertificateMethodType Method.
class UpdateDataDetails
class UpdateEventDetails
class UpdateStructureDataDetails
class UriDictionaryEntryState
Stores an instance of the UriDictionaryEntryType ObjectType.
class UserCredentialCertificateState
Stores an instance of the UserCredentialCertificateType ObjectType.
class UserIdentityToken
class UserNameIdentityToken
class UserTokenPolicy
class UserTokenPolicyCollection
A collection of UserTokenPolicy objects.
class VariableAttributes
class VariableIds
A class that declares constants for all Variables in the Model Design.
class VariableNode
class Variables
A class that declares constants for all Variables in the Model Design.
class VariableTypeAttributes
class VariableTypeIds
A class that declares constants for all VariableTypes in the Model Design.
class VariableTypeNode
class VariableTypes
A class that declares constants for all VariableTypes in the Model Design.
class Vector
class VectorCollection
A collection of Vector objects.
class VectorState
Stores an instance of the VectorType VariableType.
class VendorServerInfoState
Stores an instance of the VendorServerInfoType ObjectType.
class ViewAttributes
class ViewDescription
class ViewNode
class WriteMessage
The message contract for the Write service.
class WriteMethodState
Stores an instance of the WriteMethodType Method.
class WriteRequest
class WriteResponse
class WriteResponseMessage
The message contract for the Write service response.
class WriterGroupDataType
class WriterGroupDataTypeCollection
A collection of WriterGroupDataType objects.
class WriterGroupMessageDataType
class WriterGroupMessageDataTypeCollection
A collection of WriterGroupMessageDataType objects.
class WriterGroupMessageState
Stores an instance of the WriterGroupMessageType ObjectType.
class WriterGroupState
Stores an instance of the WriterGroupType ObjectType.
class WriterGroupTransportDataType
class WriterGroupTransportDataTypeCollection
A collection of WriterGroupTransportDataType objects.
class WriterGroupTransportState
Stores an instance of the WriterGroupTransportType ObjectType.
class WriteValue
class WriteValueCollection
A collection of WriteValue objects.
class X509IdentityToken
class XVType
class XYArrayItemState
Stores an instance of the XYArrayItemType VariableType.
class YArrayItemState
Stores an instance of the YArrayItemType VariableType.
Enumerations
enum Enumeration
enum NamingRuleType { NamingRuleType.Mandatory = 1, NamingRuleType.Optional = 2, NamingRuleType.Constraint = 3 }
enum OpenFileMode { OpenFileMode.Read = 1, OpenFileMode.Write = 2, OpenFileMode.EraseExisting = 4, OpenFileMode.Append = 8 }
enum IdentityCriteriaType {
IdentityCriteriaType.UserName = 1, IdentityCriteriaType.Thumbprint = 2, IdentityCriteriaType.Role = 3, IdentityCriteriaType.GroupId = 4,
IdentityCriteriaType.Anonymous = 5, IdentityCriteriaType.AuthenticatedUser = 6
}
enum TrustListMasks {
TrustListMasks.None = 0, TrustListMasks.TrustedCertificates = 1, TrustListMasks.TrustedCrls = 2, TrustListMasks.IssuerCertificates = 4,
TrustListMasks.IssuerCrls = 8, TrustListMasks.All = 15
}
enum PubSubState { PubSubState.Disabled = 0, PubSubState.Paused = 1, PubSubState.Operational = 2, PubSubState.Error = 3 }
enum DataSetFieldFlags : UInt16 { DataSetFieldFlags.None = 0, DataSetFieldFlags.PromotedField = 1 }
enum DataSetFieldContentMask : UInt32 {
DataSetFieldContentMask.None = 0, DataSetFieldContentMask.StatusCode = 1, DataSetFieldContentMask.SourceTimestamp = 2, DataSetFieldContentMask.ServerTimestamp = 4,
DataSetFieldContentMask.SourcePicoSeconds = 8, DataSetFieldContentMask.ServerPicoSeconds = 16, DataSetFieldContentMask.RawData = 32
}
enum OverrideValueHandling { OverrideValueHandling.Disabled = 0, OverrideValueHandling.LastUsableValue = 1, OverrideValueHandling.OverrideValue = 2 }
enum DataSetOrderingType { DataSetOrderingType.Undefined = 0, DataSetOrderingType.AscendingWriterId = 1, DataSetOrderingType.AscendingWriterIdSingle = 2 }
enum UadpNetworkMessageContentMask : UInt32 {
UadpNetworkMessageContentMask.None = 0, UadpNetworkMessageContentMask.PublisherId = 1, UadpNetworkMessageContentMask.GroupHeader = 2, UadpNetworkMessageContentMask.WriterGroupId = 4,
UadpNetworkMessageContentMask.GroupVersion = 8, UadpNetworkMessageContentMask.NetworkMessageNumber = 16, UadpNetworkMessageContentMask.SequenceNumber = 32, UadpNetworkMessageContentMask.PayloadHeader = 64,
UadpNetworkMessageContentMask.Timestamp = 128, UadpNetworkMessageContentMask.PicoSeconds = 256, UadpNetworkMessageContentMask.DataSetClassId = 512, UadpNetworkMessageContentMask.PromotedFields = 1024
}
enum UadpDataSetMessageContentMask : UInt32 {
UadpDataSetMessageContentMask.None = 0, UadpDataSetMessageContentMask.Timestamp = 1, UadpDataSetMessageContentMask.PicoSeconds = 2, UadpDataSetMessageContentMask.Status = 4,
UadpDataSetMessageContentMask.MajorVersion = 8, UadpDataSetMessageContentMask.MinorVersion = 16, UadpDataSetMessageContentMask.SequenceNumber = 32
}
enum JsonNetworkMessageContentMask : UInt32 {
JsonNetworkMessageContentMask.None = 0, JsonNetworkMessageContentMask.NetworkMessageHeader = 1, JsonNetworkMessageContentMask.DataSetMessageHeader = 2, JsonNetworkMessageContentMask.SingleDataSetMessage = 4,
JsonNetworkMessageContentMask.PublisherId = 8, JsonNetworkMessageContentMask.DataSetClassId = 16, JsonNetworkMessageContentMask.ReplyTo = 32
}
enum JsonDataSetMessageContentMask : UInt32 {
JsonDataSetMessageContentMask.None = 0, JsonDataSetMessageContentMask.DataSetWriterId = 1, JsonDataSetMessageContentMask.MetaDataVersion = 2, JsonDataSetMessageContentMask.SequenceNumber = 4,
JsonDataSetMessageContentMask.Timestamp = 8, JsonDataSetMessageContentMask.Status = 16
}
enum BrokerTransportQualityOfService {
BrokerTransportQualityOfService.NotSpecified = 0, BrokerTransportQualityOfService.BestEffort = 1, BrokerTransportQualityOfService.AtLeastOnce = 2, BrokerTransportQualityOfService.AtMostOnce = 3,
BrokerTransportQualityOfService.ExactlyOnce = 4
}
enum DiagnosticsLevel {
DiagnosticsLevel.Basic = 0, DiagnosticsLevel.Advanced = 1, DiagnosticsLevel.Info = 2, DiagnosticsLevel.Log = 3,
DiagnosticsLevel.Debug = 4
}
enum PubSubDiagnosticsCounterClassification { PubSubDiagnosticsCounterClassification.Information = 0, PubSubDiagnosticsCounterClassification.Error = 1 }
enum IdType { IdType.Numeric = 0, IdType.String = 1, IdType.Guid = 2, IdType.Opaque = 3 }
enum NodeClass {
NodeClass.Unspecified = 0, NodeClass.Object = 1, NodeClass.Variable = 2, NodeClass.Method = 4,
NodeClass.ObjectType = 8, NodeClass.VariableType = 16, NodeClass.ReferenceType = 32, NodeClass.DataType = 64,
NodeClass.View = 128
}
enum PermissionType : UInt32 {
PermissionType.None = 0, PermissionType.Browse = 1, PermissionType.ReadRolePermissions = 2, PermissionType.WriteAttribute = 4,
PermissionType.WriteRolePermissions = 8, PermissionType.WriteHistorizing = 16, PermissionType.Read = 32, PermissionType.Write = 64,
PermissionType.ReadHistory = 128, PermissionType.InsertHistory = 256, PermissionType.ModifyHistory = 512, PermissionType.DeleteHistory = 1024,
PermissionType.ReceiveEvents = 2048, PermissionType.Call = 4096, PermissionType.AddReference = 8192, PermissionType.RemoveReference = 16384,
PermissionType.DeleteNode = 32768, PermissionType.AddNode = 65536
}
enum AccessLevelType : Byte {
AccessLevelType.None = 0, AccessLevelType.CurrentRead = 1, AccessLevelType.CurrentWrite = 2, AccessLevelType.HistoryRead = 4,
AccessLevelType.HistoryWrite = 8, AccessLevelType.SemanticChange = 16, AccessLevelType.StatusWrite = 32, AccessLevelType.TimestampWrite = 64
}
enum AccessLevelExType : UInt32 {
AccessLevelExType.None = 0, AccessLevelExType.CurrentRead = 1, AccessLevelExType.CurrentWrite = 2, AccessLevelExType.HistoryRead = 4,
AccessLevelExType.HistoryWrite = 8, AccessLevelExType.SemanticChange = 16, AccessLevelExType.StatusWrite = 32, AccessLevelExType.TimestampWrite = 64,
AccessLevelExType.NonatomicRead = 256, AccessLevelExType.NonatomicWrite = 512, AccessLevelExType.WriteFullArrayOnly = 1024
}
enum EventNotifierType : Byte { EventNotifierType.None = 0, EventNotifierType.SubscribeToEvents = 1, EventNotifierType.HistoryRead = 4, EventNotifierType.HistoryWrite = 8 }
enum AccessRestrictionType : UInt32 { AccessRestrictionType.None = 0, AccessRestrictionType.SigningRequired = 1, AccessRestrictionType.EncryptionRequired = 2, AccessRestrictionType.SessionRequired = 4 }
enum StructureType { StructureType.Structure = 0, StructureType.StructureWithOptionalFields = 1, StructureType.Union = 2 }
enum ApplicationType { ApplicationType.Server = 0, ApplicationType.Client = 1, ApplicationType.ClientAndServer = 2, ApplicationType.DiscoveryServer = 3 }
enum MessageSecurityMode { MessageSecurityMode.Invalid = 0, MessageSecurityMode.None = 1, MessageSecurityMode.Sign = 2, MessageSecurityMode.SignAndEncrypt = 3 }
enum UserTokenType { UserTokenType.Anonymous = 0, UserTokenType.UserName = 1, UserTokenType.Certificate = 2, UserTokenType.IssuedToken = 3 }
enum SecurityTokenRequestType { SecurityTokenRequestType.Issue = 0, SecurityTokenRequestType.Renew = 1 }
enum NodeAttributesMask {
NodeAttributesMask.None = 0, NodeAttributesMask.AccessLevel = 1, NodeAttributesMask.ArrayDimensions = 2, NodeAttributesMask.BrowseName = 4,
NodeAttributesMask.ContainsNoLoops = 8, NodeAttributesMask.DataType = 16, NodeAttributesMask.Description = 32, NodeAttributesMask.DisplayName = 64,
NodeAttributesMask.EventNotifier = 128, NodeAttributesMask.Executable = 256, NodeAttributesMask.Historizing = 512, NodeAttributesMask.InverseName = 1024,
NodeAttributesMask.IsAbstract = 2048, NodeAttributesMask.MinimumSamplingInterval = 4096, NodeAttributesMask.NodeClass = 8192, NodeAttributesMask.NodeId = 16384,
NodeAttributesMask.Symmetric = 32768, NodeAttributesMask.UserAccessLevel = 65536, NodeAttributesMask.UserExecutable = 131072, NodeAttributesMask.UserWriteMask = 262144,
NodeAttributesMask.ValueRank = 524288, NodeAttributesMask.WriteMask = 1048576, NodeAttributesMask.Value = 2097152, NodeAttributesMask.DataTypeDefinition = 4194304,
NodeAttributesMask.RolePermissions = 8388608, NodeAttributesMask.AccessRestrictions = 16777216, NodeAttributesMask.All = 33554431, NodeAttributesMask.BaseNode = 26501220,
NodeAttributesMask.Object = 26501348, NodeAttributesMask.ObjectType = 26503268, NodeAttributesMask.Variable = 26571383, NodeAttributesMask.VariableType = 28600438,
NodeAttributesMask.Method = 26632548, NodeAttributesMask.ReferenceType = 26537060, NodeAttributesMask.View = 26501356
}
enum AttributeWriteMask : UInt32 {
AttributeWriteMask.None = 0, AttributeWriteMask.AccessLevel = 1, AttributeWriteMask.ArrayDimensions = 2, AttributeWriteMask.BrowseName = 4,
AttributeWriteMask.ContainsNoLoops = 8, AttributeWriteMask.DataType = 16, AttributeWriteMask.Description = 32, AttributeWriteMask.DisplayName = 64,
AttributeWriteMask.EventNotifier = 128, AttributeWriteMask.Executable = 256, AttributeWriteMask.Historizing = 512, AttributeWriteMask.InverseName = 1024,
AttributeWriteMask.IsAbstract = 2048, AttributeWriteMask.MinimumSamplingInterval = 4096, AttributeWriteMask.NodeClass = 8192, AttributeWriteMask.NodeId = 16384,
AttributeWriteMask.Symmetric = 32768, AttributeWriteMask.UserAccessLevel = 65536, AttributeWriteMask.UserExecutable = 131072, AttributeWriteMask.UserWriteMask = 262144,
AttributeWriteMask.ValueRank = 524288, AttributeWriteMask.WriteMask = 1048576, AttributeWriteMask.ValueForVariableType = 2097152, AttributeWriteMask.DataTypeDefinition = 4194304,
AttributeWriteMask.RolePermissions = 8388608, AttributeWriteMask.AccessRestrictions = 16777216, AttributeWriteMask.AccessLevelEx = 33554432
}
enum BrowseDirection { BrowseDirection.Forward = 0, BrowseDirection.Inverse = 1, BrowseDirection.Both = 2, BrowseDirection.Invalid = 3 }
enum BrowseResultMask {
BrowseResultMask.None = 0, BrowseResultMask.ReferenceTypeId = 1, BrowseResultMask.IsForward = 2, BrowseResultMask.NodeClass = 4,
BrowseResultMask.BrowseName = 8, BrowseResultMask.DisplayName = 16, BrowseResultMask.TypeDefinition = 32, BrowseResultMask.All = 63,
BrowseResultMask.ReferenceTypeInfo = 3, BrowseResultMask.TargetInfo = 60
}
enum FilterOperator {
FilterOperator.Equals = 0, FilterOperator.IsNull = 1, FilterOperator.GreaterThan = 2, FilterOperator.LessThan = 3,
FilterOperator.GreaterThanOrEqual = 4, FilterOperator.LessThanOrEqual = 5, FilterOperator.Like = 6, FilterOperator.Not = 7,
FilterOperator.Between = 8, FilterOperator.InList = 9, FilterOperator.And = 10, FilterOperator.Or = 11,
FilterOperator.Cast = 12, FilterOperator.InView = 13, FilterOperator.OfType = 14, FilterOperator.RelatedTo = 15,
FilterOperator.BitwiseAnd = 16, FilterOperator.BitwiseOr = 17
}
enum TimestampsToReturn {
TimestampsToReturn.Source = 0, TimestampsToReturn.Server = 1, TimestampsToReturn.Both = 2, TimestampsToReturn.Neither = 3,
TimestampsToReturn.Invalid = 4
}
enum HistoryUpdateType { HistoryUpdateType.Insert = 1, HistoryUpdateType.Replace = 2, HistoryUpdateType.Update = 3, HistoryUpdateType.Delete = 4 }
enum PerformUpdateType { PerformUpdateType.Insert = 1, PerformUpdateType.Replace = 2, PerformUpdateType.Update = 3, PerformUpdateType.Remove = 4 }
enum MonitoringMode { MonitoringMode.Disabled = 0, MonitoringMode.Sampling = 1, MonitoringMode.Reporting = 2 }
enum DataChangeTrigger { DataChangeTrigger.Status = 0, DataChangeTrigger.StatusValue = 1, DataChangeTrigger.StatusValueTimestamp = 2 }
enum DeadbandType { DeadbandType.None = 0, DeadbandType.Absolute = 1, DeadbandType.Percent = 2 }
enum RedundancySupport {
RedundancySupport.None = 0, RedundancySupport.Cold = 1, RedundancySupport.Warm = 2, RedundancySupport.Hot = 3,
RedundancySupport.Transparent = 4, RedundancySupport.HotAndMirrored = 5
}
enum ServerState {
ServerState.Running = 0, ServerState.Failed = 1, ServerState.NoConfiguration = 2, ServerState.Suspended = 3,
ServerState.Shutdown = 4, ServerState.Test = 5, ServerState.CommunicationFault = 6, ServerState.Unknown = 7
}
enum ModelChangeStructureVerbMask {
ModelChangeStructureVerbMask.NodeAdded = 1, ModelChangeStructureVerbMask.NodeDeleted = 2, ModelChangeStructureVerbMask.ReferenceAdded = 4, ModelChangeStructureVerbMask.ReferenceDeleted = 8,
ModelChangeStructureVerbMask.DataTypeChanged = 16
}
enum AxisScaleEnumeration { AxisScaleEnumeration.Linear = 0, AxisScaleEnumeration.Log = 1, AxisScaleEnumeration.Ln = 2 }
enum ExceptionDeviationFormat {
ExceptionDeviationFormat.AbsoluteValue = 0, ExceptionDeviationFormat.PercentOfValue = 1, ExceptionDeviationFormat.PercentOfRange = 2, ExceptionDeviationFormat.PercentOfEURange = 3,
ExceptionDeviationFormat.Unknown = 4
}
Functions
delegate ServiceResult GetMonitoredItemsMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, uint subscriptionId, ref uint[] serverHandles, ref uint[] clientHandles)
Used to receive notifications when the method is called.
delegate ServiceResult ResendDataMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, uint subscriptionId)
Used to receive notifications when the method is called.
delegate ServiceResult SetSubscriptionDurableMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, uint subscriptionId, uint lifetimeInHours, ref uint revisedLifetimeInHours)
Used to receive notifications when the method is called.
delegate ServiceResult RequestServerStateChangeMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, ServerState state, DateTime estimatedReturnTime, uint secondsTillShutdown, LocalizedText reason, bool restart)
Used to receive notifications when the method is called.
delegate ServiceResult OpenMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, byte mode, ref uint fileHandle)
Used to receive notifications when the method is called.
delegate ServiceResult CloseMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, uint fileHandle)
Used to receive notifications when the method is called.
delegate ServiceResult ReadMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, uint fileHandle, int length, ref byte[] data)
Used to receive notifications when the method is called.
delegate ServiceResult WriteMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, uint fileHandle, byte[] data)
Used to receive notifications when the method is called.
delegate ServiceResult GetPositionMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, uint fileHandle, ref ulong position)
Used to receive notifications when the method is called.
delegate ServiceResult SetPositionMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, uint fileHandle, ulong position)
Used to receive notifications when the method is called.
delegate ServiceResult CreateDirectoryMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, string directoryName, ref NodeId directoryNodeId)
Used to receive notifications when the method is called.
delegate ServiceResult CreateFileMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, string fileName, bool requestFileOpen, ref NodeId fileNodeId, ref uint fileHandle)
Used to receive notifications when the method is called.
delegate ServiceResult DeleteFileMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, NodeId objectToDelete)
Used to receive notifications when the method is called.
delegate ServiceResult MoveOrCopyMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, NodeId objectToMoveOrCopy, NodeId targetDirectory, bool createCopy, string newName, ref NodeId newNodeId)
Used to receive notifications when the method is called.
delegate ServiceResult GenerateFileForReadMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, object generateOptions, ref NodeId fileNodeId, ref uint fileHandle, ref NodeId completionStateMachine)
Used to receive notifications when the method is called.
delegate ServiceResult GenerateFileForWriteMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, object generateOptions, ref NodeId fileNodeId, ref uint fileHandle)
Used to receive notifications when the method is called.
delegate ServiceResult CloseAndCommitMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, uint fileHandle, ref NodeId completionStateMachine)
Used to receive notifications when the method is called.
delegate ServiceResult AddRoleMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, string roleName, string namespaceUri, ref NodeId roleNodeId)
Used to receive notifications when the method is called.
delegate ServiceResult RemoveRoleMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, NodeId roleNodeId)
Used to receive notifications when the method is called.
delegate ServiceResult AddIdentityMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, IdentityMappingRuleType rule)
Used to receive notifications when the method is called.
delegate ServiceResult RemoveIdentityMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, IdentityMappingRuleType rule)
Used to receive notifications when the method is called.
delegate ServiceResult AddApplicationMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, string applicationUri)
Used to receive notifications when the method is called.
delegate ServiceResult RemoveApplicationMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, string applicationUri)
Used to receive notifications when the method is called.
delegate ServiceResult AddEndpointMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, EndpointType endpoint)
Used to receive notifications when the method is called.
delegate ServiceResult RemoveEndpointMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, EndpointType endpoint)
Used to receive notifications when the method is called.
delegate ServiceResult ConditionRefresh2MethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, uint subscriptionId, uint monitoredItemId)
Used to receive notifications when the method is called.
delegate ServiceResult ConditionRefreshMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, uint subscriptionId)
Used to receive notifications when the method is called.
delegate ServiceResult AddCommentMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, byte[] eventId, LocalizedText comment)
Used to receive notifications when the method is called.
delegate ServiceResult DialogResponseMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, int selectedResponse)
Used to receive notifications when the method is called.
delegate ServiceResult TimedShelveMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, double shelvingTime)
Used to receive notifications when the method is called.
delegate ServiceResult OpenWithMasksMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, uint masks, ref uint fileHandle)
Used to receive notifications when the method is called.
delegate ServiceResult CloseAndUpdateMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, uint fileHandle, ref bool applyChangesRequired)
Used to receive notifications when the method is called.
delegate ServiceResult AddCertificateMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, byte[] certificate, bool isTrustedCertificate)
Used to receive notifications when the method is called.
delegate ServiceResult RemoveCertificateMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, string thumbprint, bool isTrustedCertificate)
Used to receive notifications when the method is called.
delegate ServiceResult UpdateCertificateMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, NodeId certificateGroupId, NodeId certificateTypeId, byte[] certificate, byte[][] issuerCertificates, string privateKeyFormat, byte[] privateKey, ref bool applyChangesRequired)
Used to receive notifications when the method is called.
delegate ServiceResult CreateSigningRequestMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, NodeId certificateGroupId, NodeId certificateTypeId, string subjectName, bool regeneratePrivateKey, byte[] nonce, ref byte[] certificateRequest)
Used to receive notifications when the method is called.
delegate ServiceResult GetRejectedListMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, ref byte[][] certificates)
Used to receive notifications when the method is called.
delegate ServiceResult CreateCredentialMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, string resourceUri, string profileUri, string[] endpointUrls, ref NodeId credentialNodeId)
Used to receive notifications when the method is called.
delegate ServiceResult GetEncryptingKeyMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, string credentialId, string requestedSecurityPolicyUri, ref byte[] publicKey, ref NodeId revisedSecurityPolicyUri)
Used to receive notifications when the method is called.
delegate ServiceResult KeyCredentialUpdateMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, string credentialId, byte[] credentialSecret, string certificateThumbprint, string securityPolicyUri)
Used to receive notifications when the method is called.
delegate ServiceResult GetSecurityKeysMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, string securityGroupId, uint startingTokenId, uint requestedKeyCount, ref string securityPolicyUri, ref uint firstTokenId, ref byte[][] keys, ref double timeToNextKey, ref double keyLifetime)
Used to receive notifications when the method is called.
delegate ServiceResult GetSecurityGroupMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, string securityGroupId, ref NodeId securityGroupNodeId)
Used to receive notifications when the method is called.
delegate ServiceResult AddSecurityGroupMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, string securityGroupName, double keyLifetime, string securityPolicyUri, uint maxFutureKeyCount, uint maxPastKeyCount, ref string securityGroupId, ref NodeId securityGroupNodeId)
Used to receive notifications when the method is called.
delegate ServiceResult RemoveSecurityGroupMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, NodeId securityGroupNodeId)
Used to receive notifications when the method is called.
delegate ServiceResult SetSecurityKeysMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, string securityGroupId, string securityPolicyUri, uint currentTokenId, byte[] currentKey, byte[][] futureKeys, double timeToNextKey, double keyLifetime)
Used to receive notifications when the method is called.
delegate ServiceResult AddConnectionMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, PubSubConnectionDataType configuration, ref NodeId connectionId)
Used to receive notifications when the method is called.
delegate ServiceResult RemoveConnectionMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, NodeId connectionId)
Used to receive notifications when the method is called.
delegate ServiceResult AddExtensionFieldMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, QualifiedName fieldName, object fieldValue, ref NodeId fieldId)
Used to receive notifications when the method is called.
delegate ServiceResult RemoveExtensionFieldMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, NodeId fieldId)
Used to receive notifications when the method is called.
delegate ServiceResult PublishedDataItemsAddVariablesMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, ConfigurationVersionDataType configurationVersion, string[] fieldNameAliases, bool[] promotedFields, PublishedVariableDataType[] variablesToAdd, ref ConfigurationVersionDataType newConfigurationVersion, ref StatusCode[] addResults)
Used to receive notifications when the method is called.
delegate ServiceResult PublishedDataItemsRemoveVariablesMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, ConfigurationVersionDataType configurationVersion, uint[] variablesToRemove, ref ConfigurationVersionDataType newConfigurationVersion, ref StatusCode[] removeResults)
Used to receive notifications when the method is called.
delegate ServiceResult PublishedEventsTypeModifyFieldSelectionMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, ConfigurationVersionDataType configurationVersion, string[] fieldNameAliases, bool[] promotedFields, SimpleAttributeOperand[] selectedFields, ref ConfigurationVersionDataType newConfigurationVersion)
Used to receive notifications when the method is called.
delegate ServiceResult AddPublishedDataItemsMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, string name, string[] fieldNameAliases, ushort[] fieldFlags, PublishedVariableDataType[] variablesToAdd, ref NodeId dataSetNodeId, ref ConfigurationVersionDataType configurationVersion, ref StatusCode[] addResults)
Used to receive notifications when the method is called.
delegate ServiceResult AddPublishedEventsMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, string name, NodeId eventNotifier, string[] fieldNameAliases, ushort[] fieldFlags, SimpleAttributeOperand[] selectedFields, ContentFilter filter, ref ConfigurationVersionDataType configurationVersion, ref NodeId dataSetNodeId)
Used to receive notifications when the method is called.
delegate ServiceResult AddPublishedDataItemsTemplateMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, string name, DataSetMetaDataType dataSetMetaData, PublishedVariableDataType[] variablesToAdd, ref NodeId dataSetNodeId, ref StatusCode[] addResults)
Used to receive notifications when the method is called.
delegate ServiceResult AddPublishedEventsTemplateMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, string name, DataSetMetaDataType dataSetMetaData, NodeId eventNotifier, SimpleAttributeOperand[] selectedFields, ContentFilter filter, ref NodeId dataSetNodeId)
Used to receive notifications when the method is called.
delegate ServiceResult RemovePublishedDataSetMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, NodeId dataSetNodeId)
Used to receive notifications when the method is called.
delegate ServiceResult AddDataSetFolderMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, string name, ref NodeId dataSetFolderNodeId)
Used to receive notifications when the method is called.
delegate ServiceResult RemoveDataSetFolderMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, NodeId dataSetFolderNodeId)
Used to receive notifications when the method is called.
delegate ServiceResult PubSubConnectionTypeAddWriterGroupMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, WriterGroupDataType configuration, ref NodeId groupId)
Used to receive notifications when the method is called.
delegate ServiceResult PubSubConnectionAddReaderGroupGroupMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, ReaderGroupDataType configuration, ref NodeId groupId)
Used to receive notifications when the method is called.
delegate ServiceResult PubSubConnectionTypeRemoveGroupMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, NodeId groupId)
Used to receive notifications when the method is called.
delegate ServiceResult PubSubGroupTypeAddWriterrMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, DataSetWriterDataType configuration, ref NodeId dataSetWriterNodeId)
Used to receive notifications when the method is called.
delegate ServiceResult PubSubGroupTypeRemoveWriterMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, NodeId dataSetWriterNodeId)
Used to receive notifications when the method is called.
delegate ServiceResult PubSubGroupTypeAddReaderMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, DataSetReaderDataType configuration, ref NodeId dataSetReaderNodeId)
Used to receive notifications when the method is called.
delegate ServiceResult PubSubGroupTypeRemoveReaderMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, NodeId dataSetReaderNodeId)
Used to receive notifications when the method is called.
delegate ServiceResult DataSetReaderTypeCreateTargetVariablesMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, ConfigurationVersionDataType configurationVersion, FieldTargetDataType[] targetVariablesToAdd, ref StatusCode[] addResults)
Used to receive notifications when the method is called.
delegate ServiceResult DataSetReaderTypeCreateDataSetMirrorMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, string parentNodeName, RolePermissionType[] rolePermissions, ref NodeId parentNodeId)
Used to receive notifications when the method is called.
delegate ServiceResult TargetVariablesTypeAddTargetVariablesMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, ConfigurationVersionDataType configurationVersion, FieldTargetDataType[] targetVariablesToAdd, ref StatusCode[] addResults)
Used to receive notifications when the method is called.
delegate ServiceResult TargetVariablesTypeRemoveTargetVariablesMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, ConfigurationVersionDataType configurationVersion, uint[] targetsToRemove, ref StatusCode[] removeResults)
Used to receive notifications when the method is called.
Enumeration Type Documentation
AccessLevelExType
enum Opc.Ua.AccessLevelExType : UInt32 strong
<exclude>
Enumerator
None
CurrentRead
CurrentWrite
HistoryRead
HistoryWrite
SemanticChange
StatusWrite
TimestampWrite
NonatomicRead
NonatomicWrite
WriteFullArrayOnly
Definition at line 18012 of file Opc.Ua.DataTypes.cs.
AccessLevelType
enum Opc.Ua.AccessLevelType : Byte strong
<exclude>
Enumerator
None
CurrentRead
CurrentWrite
HistoryRead
HistoryWrite
SemanticChange
StatusWrite
TimestampWrite
Definition at line 17967 of file Opc.Ua.DataTypes.cs.
AccessRestrictionType
enum Opc.Ua.AccessRestrictionType : UInt32 strong
<exclude>
Enumerator
None
SigningRequired
EncryptionRequired
SessionRequired
Definition at line 18098 of file Opc.Ua.DataTypes.cs.
ApplicationType
enum Opc.Ua.ApplicationType strong
<exclude>
Enumerator
Server
Client
ClientAndServer
DiscoveryServer
Definition at line 23088 of file Opc.Ua.DataTypes.cs.
AttributeWriteMask
enum Opc.Ua.AttributeWriteMask : UInt32 strong
<exclude>
Enumerator
None
AccessLevel
ArrayDimensions
BrowseName
ContainsNoLoops
DataType
Description
DisplayName
EventNotifier
Executable
Historizing
InverseName
IsAbstract
MinimumSamplingInterval
NodeClass
NodeId
Symmetric
UserAccessLevel
UserExecutable
UserWriteMask
ValueRank
WriteMask
ValueForVariableType
DataTypeDefinition
RolePermissions
AccessRestrictions
AccessLevelEx
Definition at line 36484 of file Opc.Ua.DataTypes.cs.
AxisScaleEnumeration
enum Opc.Ua.AxisScaleEnumeration strong
<exclude>
Enumerator
Linear
Log
Ln
Definition at line 66413 of file Opc.Ua.DataTypes.cs.
BrokerTransportQualityOfService
enum Opc.Ua.BrokerTransportQualityOfService strong
<exclude>
Enumerator
NotSpecified
BestEffort
AtLeastOnce
AtMostOnce
ExactlyOnce
Definition at line 16543 of file Opc.Ua.DataTypes.cs.
BrowseDirection
enum Opc.Ua.BrowseDirection strong
<exclude>
Enumerator
Forward
Inverse
Both
Invalid
Definition at line 36605 of file Opc.Ua.DataTypes.cs.
BrowseResultMask
enum Opc.Ua.BrowseResultMask strong
<exclude>
Enumerator
None
ReferenceTypeId
IsForward
NodeClass
BrowseName
DisplayName
TypeDefinition
All
ReferenceTypeInfo
TargetInfo
Definition at line 37081 of file Opc.Ua.DataTypes.cs.
DataChangeTrigger
enum Opc.Ua.DataChangeTrigger strong
<exclude>
Enumerator
Status
StatusValue
StatusValueTimestamp
Definition at line 51724 of file Opc.Ua.DataTypes.cs.
DataSetFieldContentMask
enum Opc.Ua.DataSetFieldContentMask : UInt32 strong
<exclude>
Enumerator
None
StatusCode
SourceTimestamp
ServerTimestamp
SourcePicoSeconds
ServerPicoSeconds
RawData
Definition at line 7722 of file Opc.Ua.DataTypes.cs.
DataSetFieldFlags
enum Opc.Ua.DataSetFieldFlags : UInt16 strong
<exclude>
Enumerator
None
PromotedField
Definition at line 6108 of file Opc.Ua.DataTypes.cs.
DataSetOrderingType
enum Opc.Ua.DataSetOrderingType strong
<exclude>
Enumerator
Undefined
AscendingWriterId
AscendingWriterIdSingle
Definition at line 13649 of file Opc.Ua.DataTypes.cs.
DeadbandType
enum Opc.Ua.DeadbandType strong
<exclude>
Enumerator
None
Absolute
Percent
Definition at line 51749 of file Opc.Ua.DataTypes.cs.
DiagnosticsLevel
enum Opc.Ua.DiagnosticsLevel strong
<exclude>
Enumerator
Basic
Advanced
Info
Log
Debug
Definition at line 17495 of file Opc.Ua.DataTypes.cs.
Enumeration
enum Opc.Ua.Enumeration strong
<exclude>
Definition at line 46 of file Opc.Ua.DataTypes.cs.
EventNotifierType
enum Opc.Ua.EventNotifierType : Byte strong
<exclude>
Enumerator
None
SubscribeToEvents
HistoryRead
HistoryWrite
Definition at line 18069 of file Opc.Ua.DataTypes.cs.
ExceptionDeviationFormat
enum Opc.Ua.ExceptionDeviationFormat strong
<exclude>
Enumerator
AbsoluteValue
PercentOfValue
PercentOfRange
PercentOfEURange
Unknown
Definition at line 67922 of file Opc.Ua.DataTypes.cs.
FilterOperator
enum Opc.Ua.FilterOperator strong
<exclude>
Enumerator
Equals
IsNull
GreaterThan
LessThan
GreaterThanOrEqual
LessThanOrEqual
Like
Not
Between
InList
And
Or
Cast
InView
OfType
RelatedTo
BitwiseAnd
BitwiseOr
Definition at line 41519 of file Opc.Ua.DataTypes.cs.
HistoryUpdateType
enum Opc.Ua.HistoryUpdateType strong
<exclude>
Enumerator
Insert
Replace
Update
Delete
Definition at line 49066 of file Opc.Ua.DataTypes.cs.
IdentityCriteriaType
enum Opc.Ua.IdentityCriteriaType strong
<exclude>
Enumerator
UserName
Thumbprint
Role
GroupId
Anonymous
AuthenticatedUser
Definition at line 2920 of file Opc.Ua.DataTypes.cs.
IdType
enum Opc.Ua.IdType strong
<exclude>
Enumerator
Numeric
String
Guid
Opaque
Definition at line 17719 of file Opc.Ua.DataTypes.cs.
JsonDataSetMessageContentMask
enum Opc.Ua.JsonDataSetMessageContentMask : UInt32 strong
<exclude>
Enumerator
None
DataSetWriterId
MetaDataVersion
SequenceNumber
Timestamp
Status
Definition at line 15269 of file Opc.Ua.DataTypes.cs.
JsonNetworkMessageContentMask
enum Opc.Ua.JsonNetworkMessageContentMask : UInt32 strong
<exclude>
Enumerator
None
NetworkMessageHeader
DataSetMessageHeader
SingleDataSetMessage
PublisherId
DataSetClassId
ReplyTo
Definition at line 14921 of file Opc.Ua.DataTypes.cs.
MessageSecurityMode
enum Opc.Ua.MessageSecurityMode strong
<exclude>
Enumerator
Invalid
None
Sign
SignAndEncrypt
Definition at line 25495 of file Opc.Ua.DataTypes.cs.
ModelChangeStructureVerbMask
enum Opc.Ua.ModelChangeStructureVerbMask strong
<exclude>
Enumerator
NodeAdded
NodeDeleted
ReferenceAdded
ReferenceDeleted
DataTypeChanged
Definition at line 65584 of file Opc.Ua.DataTypes.cs.
MonitoringMode
enum Opc.Ua.MonitoringMode strong
<exclude>
Enumerator
Disabled
Sampling
Reporting
Definition at line 51699 of file Opc.Ua.DataTypes.cs.
NamingRuleType
enum Opc.Ua.NamingRuleType strong
<exclude>
Enumerator
Mandatory
Optional
Constraint
Definition at line 145 of file Opc.Ua.DataTypes.cs.
NodeAttributesMask
enum Opc.Ua.NodeAttributesMask strong
<exclude>
Enumerator
None
AccessLevel
ArrayDimensions
BrowseName
ContainsNoLoops
DataType
Description
DisplayName
EventNotifier
Executable
Historizing
InverseName
IsAbstract
MinimumSamplingInterval
NodeClass
NodeId
Symmetric
UserAccessLevel
UserExecutable
UserWriteMask
ValueRank
WriteMask
Value
DataTypeDefinition
RolePermissions
AccessRestrictions
All
BaseNode
Object
ObjectType
Variable
VariableType
Method
ReferenceType
View
Definition at line 31600 of file Opc.Ua.DataTypes.cs.
NodeClass
enum Opc.Ua.NodeClass strong
<exclude>
Enumerator
Unspecified
Object
Variable
Method
ObjectType
VariableType
ReferenceType
DataType
View
Definition at line 17833 of file Opc.Ua.DataTypes.cs.
OpenFileMode
enum Opc.Ua.OpenFileMode strong
<exclude>
Enumerator
Read
Write
EraseExisting
Append
Definition at line 2806 of file Opc.Ua.DataTypes.cs.
OverrideValueHandling
enum Opc.Ua.OverrideValueHandling strong
<exclude>
Enumerator
Disabled
LastUsableValue
OverrideValue
Definition at line 13016 of file Opc.Ua.DataTypes.cs.
PerformUpdateType
enum Opc.Ua.PerformUpdateType strong
<exclude>
Enumerator
Insert
Replace
Update
Remove
Definition at line 49095 of file Opc.Ua.DataTypes.cs.
PermissionType
enum Opc.Ua.PermissionType : UInt32 strong
<exclude>
Enumerator
None
Browse
ReadRolePermissions
WriteAttribute
WriteRolePermissions
WriteHistorizing
Read
Write
ReadHistory
InsertHistory
ModifyHistory
DeleteHistory
ReceiveEvents
Call
AddReference
RemoveReference
DeleteNode
AddNode
Definition at line 17882 of file Opc.Ua.DataTypes.cs.
PubSubDiagnosticsCounterClassification
enum Opc.Ua.PubSubDiagnosticsCounterClassification strong
<exclude>
Enumerator
Information
Error
Definition at line 17613 of file Opc.Ua.DataTypes.cs.
PubSubState
enum Opc.Ua.PubSubState strong
<exclude>
Enumerator
Disabled
Paused
Operational
Error
Definition at line 5317 of file Opc.Ua.DataTypes.cs.
RedundancySupport
enum Opc.Ua.RedundancySupport strong
<exclude>
Enumerator
None
Cold
Warm
Hot
Transparent
HotAndMirrored
Definition at line 61424 of file Opc.Ua.DataTypes.cs.
SecurityTokenRequestType
enum Opc.Ua.SecurityTokenRequestType strong
<exclude>
Enumerator
Issue
Renew
Definition at line 27910 of file Opc.Ua.DataTypes.cs.
ServerState
enum Opc.Ua.ServerState strong
<exclude>
Enumerator
Running
Failed
NoConfiguration
Suspended
Shutdown
Test
CommunicationFault
Unknown
Definition at line 61461 of file Opc.Ua.DataTypes.cs.
StructureType
enum Opc.Ua.StructureType strong
<exclude>
Enumerator
Structure
StructureWithOptionalFields
Union
Definition at line 18562 of file Opc.Ua.DataTypes.cs.
TimestampsToReturn
enum Opc.Ua.TimestampsToReturn strong
<exclude>
Enumerator
Source
Server
Both
Neither
Invalid
Definition at line 45102 of file Opc.Ua.DataTypes.cs.
TrustListMasks
enum Opc.Ua.TrustListMasks strong
<exclude>
Enumerator
None
TrustedCertificates
TrustedCrls
IssuerCertificates
IssuerCrls
All
Definition at line 3273 of file Opc.Ua.DataTypes.cs.
UadpDataSetMessageContentMask
enum Opc.Ua.UadpDataSetMessageContentMask : UInt32 strong
<exclude>
Enumerator
None
Timestamp
PicoSeconds
Status
MajorVersion
MinorVersion
SequenceNumber
Definition at line 14197 of file Opc.Ua.DataTypes.cs.
UadpNetworkMessageContentMask
enum Opc.Ua.UadpNetworkMessageContentMask : UInt32 strong
<exclude>
Enumerator
None
PublisherId
GroupHeader
WriterGroupId
GroupVersion
NetworkMessageNumber
SequenceNumber
PayloadHeader
Timestamp
PicoSeconds
DataSetClassId
PromotedFields
Definition at line 13759 of file Opc.Ua.DataTypes.cs.
UserTokenType
enum Opc.Ua.UserTokenType strong
<exclude>
Enumerator
Anonymous
UserName
Certificate
IssuedToken
Definition at line 25524 of file Opc.Ua.DataTypes.cs.
Function Documentation
AddApplicationMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.AddApplicationMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, string applicationUri)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.AddApplicationMethodState.InitializeOptionalChildren().
AddCertificateMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.AddCertificateMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, byte [] certificate, bool isTrustedCertificate)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.AddCertificateMethodState.InitializeOptionalChildren().
AddCommentMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.AddCommentMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, byte [] eventId, LocalizedText comment)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.AddCommentMethodState.InitializeOptionalChildren().
AddConnectionMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.AddConnectionMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, PubSubConnectionDataType configuration, ref NodeId connectionId)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.AddConnectionMethodState.InitializeOptionalChildren().
AddDataSetFolderMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.AddDataSetFolderMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, string name, ref NodeId dataSetFolderNodeId)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.AddDataSetFolderMethodState.InitializeOptionalChildren().
AddEndpointMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.AddEndpointMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, EndpointType endpoint)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.AddEndpointMethodState.InitializeOptionalChildren().
AddExtensionFieldMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.AddExtensionFieldMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, QualifiedName fieldName, object fieldValue, ref NodeId fieldId)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.AddExtensionFieldMethodState.InitializeOptionalChildren().
AddIdentityMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.AddIdentityMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, IdentityMappingRuleType rule)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.AddIdentityMethodState.InitializeOptionalChildren().
AddPublishedDataItemsMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.AddPublishedDataItemsMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, string name, string [] fieldNameAliases, ushort [] fieldFlags, PublishedVariableDataType [] variablesToAdd, ref NodeId dataSetNodeId, ref ConfigurationVersionDataType configurationVersion, ref StatusCode [] addResults)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.AddPublishedDataItemsMethodState.InitializeOptionalChildren().
AddPublishedDataItemsTemplateMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.AddPublishedDataItemsTemplateMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, string name, DataSetMetaDataType dataSetMetaData, PublishedVariableDataType [] variablesToAdd, ref NodeId dataSetNodeId, ref StatusCode [] addResults)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.AddPublishedDataItemsTemplateMethodState.InitializeOptionalChildren().
AddPublishedEventsMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.AddPublishedEventsMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, string name, NodeId eventNotifier, string [] fieldNameAliases, ushort [] fieldFlags, SimpleAttributeOperand [] selectedFields, ContentFilter filter, ref ConfigurationVersionDataType configurationVersion, ref NodeId dataSetNodeId)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.AddPublishedEventsMethodState.InitializeOptionalChildren().
AddPublishedEventsTemplateMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.AddPublishedEventsTemplateMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, string name, DataSetMetaDataType dataSetMetaData, NodeId eventNotifier, SimpleAttributeOperand [] selectedFields, ContentFilter filter, ref NodeId dataSetNodeId)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.AddPublishedEventsTemplateMethodState.InitializeOptionalChildren().
AddRoleMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.AddRoleMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, string roleName, string namespaceUri, ref NodeId roleNodeId)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.AddRoleMethodState.InitializeOptionalChildren().
AddSecurityGroupMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.AddSecurityGroupMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, string securityGroupName, double keyLifetime, string securityPolicyUri, uint maxFutureKeyCount, uint maxPastKeyCount, ref string securityGroupId, ref NodeId securityGroupNodeId)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.AddSecurityGroupMethodState.InitializeOptionalChildren().
CloseAndCommitMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.CloseAndCommitMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, uint fileHandle, ref NodeId completionStateMachine)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.CloseAndCommitMethodState.InitializeOptionalChildren().
CloseAndUpdateMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.CloseAndUpdateMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, uint fileHandle, ref bool applyChangesRequired)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.CloseAndUpdateMethodState.InitializeOptionalChildren().
CloseMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.CloseMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, uint fileHandle)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.CloseMethodState.InitializeOptionalChildren().
ConditionRefresh2MethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.ConditionRefresh2MethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, uint subscriptionId, uint monitoredItemId)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.ConditionRefresh2MethodState.InitializeOptionalChildren().
ConditionRefreshMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.ConditionRefreshMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, uint subscriptionId)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.ConditionRefreshMethodState.InitializeOptionalChildren().
CreateCredentialMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.CreateCredentialMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, string resourceUri, string profileUri, string [] endpointUrls, ref NodeId credentialNodeId)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.CreateCredentialMethodState.InitializeOptionalChildren().
CreateDirectoryMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.CreateDirectoryMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, string directoryName, ref NodeId directoryNodeId)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.CreateDirectoryMethodState.InitializeOptionalChildren().
CreateFileMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.CreateFileMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, string fileName, bool requestFileOpen, ref NodeId fileNodeId, ref uint fileHandle)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.CreateFileMethodState.InitializeOptionalChildren().
CreateSigningRequestMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.CreateSigningRequestMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, NodeId certificateGroupId, NodeId certificateTypeId, string subjectName, bool regeneratePrivateKey, byte [] nonce, ref byte [] certificateRequest)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.CreateSigningRequestMethodState.InitializeOptionalChildren().
DataSetReaderTypeCreateDataSetMirrorMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.DataSetReaderTypeCreateDataSetMirrorMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, string parentNodeName, RolePermissionType [] rolePermissions, ref NodeId parentNodeId)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.DataSetReaderTypeCreateDataSetMirrorMethodState.InitializeOptionalChildren().
DataSetReaderTypeCreateTargetVariablesMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.DataSetReaderTypeCreateTargetVariablesMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, ConfigurationVersionDataType configurationVersion, FieldTargetDataType [] targetVariablesToAdd, ref StatusCode [] addResults)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.DataSetReaderTypeCreateTargetVariablesMethodState.InitializeOptionalChildren().
DeleteFileMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.DeleteFileMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, NodeId objectToDelete)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.DeleteFileMethodState.InitializeOptionalChildren().
DialogResponseMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.DialogResponseMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, int selectedResponse)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.DialogResponseMethodState.InitializeOptionalChildren().
GenerateFileForReadMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.GenerateFileForReadMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, object generateOptions, ref NodeId fileNodeId, ref uint fileHandle, ref NodeId completionStateMachine)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.GenerateFileForReadMethodState.InitializeOptionalChildren().
GenerateFileForWriteMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.GenerateFileForWriteMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, object generateOptions, ref NodeId fileNodeId, ref uint fileHandle)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.GenerateFileForWriteMethodState.InitializeOptionalChildren().
GetEncryptingKeyMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.GetEncryptingKeyMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, string credentialId, string requestedSecurityPolicyUri, ref byte [] publicKey, ref NodeId revisedSecurityPolicyUri)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.GetEncryptingKeyMethodState.InitializeOptionalChildren().
GetMonitoredItemsMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.GetMonitoredItemsMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, uint subscriptionId, ref uint [] serverHandles, ref uint [] clientHandles)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.GetMonitoredItemsMethodState.InitializeOptionalChildren().
GetPositionMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.GetPositionMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, uint fileHandle, ref ulong position)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.GetPositionMethodState.InitializeOptionalChildren().
GetRejectedListMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.GetRejectedListMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, ref byte certificates[][])
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.GetRejectedListMethodState.InitializeOptionalChildren().
GetSecurityGroupMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.GetSecurityGroupMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, string securityGroupId, ref NodeId securityGroupNodeId)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.GetSecurityGroupMethodState.InitializeOptionalChildren().
GetSecurityKeysMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.GetSecurityKeysMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, string securityGroupId, uint startingTokenId, uint requestedKeyCount, ref string securityPolicyUri, ref uint firstTokenId, ref byte keys[][], ref double timeToNextKey, ref double keyLifetime)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.GetSecurityKeysMethodState.InitializeOptionalChildren().
KeyCredentialUpdateMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.KeyCredentialUpdateMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, string credentialId, byte [] credentialSecret, string certificateThumbprint, string securityPolicyUri)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.KeyCredentialUpdateMethodState.InitializeOptionalChildren().
MoveOrCopyMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.MoveOrCopyMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, NodeId objectToMoveOrCopy, NodeId targetDirectory, bool createCopy, string newName, ref NodeId newNodeId)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.MoveOrCopyMethodState.InitializeOptionalChildren().
OpenMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.OpenMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, byte mode, ref uint fileHandle)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.OpenMethodState.InitializeOptionalChildren().
OpenWithMasksMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.OpenWithMasksMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, uint masks, ref uint fileHandle)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.OpenWithMasksMethodState.InitializeOptionalChildren().
PublishedDataItemsAddVariablesMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.PublishedDataItemsAddVariablesMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, ConfigurationVersionDataType configurationVersion, string [] fieldNameAliases, bool [] promotedFields, PublishedVariableDataType [] variablesToAdd, ref ConfigurationVersionDataType newConfigurationVersion, ref StatusCode [] addResults)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.PublishedDataItemsAddVariablesMethodState.InitializeOptionalChildren().
PublishedDataItemsRemoveVariablesMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.PublishedDataItemsRemoveVariablesMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, ConfigurationVersionDataType configurationVersion, uint [] variablesToRemove, ref ConfigurationVersionDataType newConfigurationVersion, ref StatusCode [] removeResults)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.PublishedDataItemsRemoveVariablesMethodState.InitializeOptionalChildren().
PublishedEventsTypeModifyFieldSelectionMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.PublishedEventsTypeModifyFieldSelectionMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, ConfigurationVersionDataType configurationVersion, string [] fieldNameAliases, bool [] promotedFields, SimpleAttributeOperand [] selectedFields, ref ConfigurationVersionDataType newConfigurationVersion)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.PublishedEventsTypeModifyFieldSelectionMethodState.InitializeOptionalChildren().
PubSubConnectionAddReaderGroupGroupMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.PubSubConnectionAddReaderGroupGroupMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, ReaderGroupDataType configuration, ref NodeId groupId)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.PubSubConnectionAddReaderGroupGroupMethodState.InitializeOptionalChildren().
PubSubConnectionTypeAddWriterGroupMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.PubSubConnectionTypeAddWriterGroupMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, WriterGroupDataType configuration, ref NodeId groupId)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.PubSubConnectionTypeAddWriterGroupMethodState.InitializeOptionalChildren().
PubSubConnectionTypeRemoveGroupMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.PubSubConnectionTypeRemoveGroupMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, NodeId groupId)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.PubSubConnectionTypeRemoveGroupMethodState.InitializeOptionalChildren().
PubSubGroupTypeAddReaderMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.PubSubGroupTypeAddReaderMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, DataSetReaderDataType configuration, ref NodeId dataSetReaderNodeId)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.PubSubGroupTypeAddReaderMethodState.InitializeOptionalChildren().
PubSubGroupTypeAddWriterrMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.PubSubGroupTypeAddWriterrMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, DataSetWriterDataType configuration, ref NodeId dataSetWriterNodeId)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.PubSubGroupTypeAddWriterrMethodState.InitializeOptionalChildren().
PubSubGroupTypeRemoveReaderMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.PubSubGroupTypeRemoveReaderMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, NodeId dataSetReaderNodeId)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.PubSubGroupTypeRemoveReaderMethodState.InitializeOptionalChildren().
PubSubGroupTypeRemoveWriterMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.PubSubGroupTypeRemoveWriterMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, NodeId dataSetWriterNodeId)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.PubSubGroupTypeRemoveWriterMethodState.InitializeOptionalChildren().
ReadMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.ReadMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, uint fileHandle, int length, ref byte [] data)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.ReadMethodState.InitializeOptionalChildren().
RemoveApplicationMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.RemoveApplicationMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, string applicationUri)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.RemoveApplicationMethodState.InitializeOptionalChildren().
RemoveCertificateMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.RemoveCertificateMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, string thumbprint, bool isTrustedCertificate)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.RemoveCertificateMethodState.InitializeOptionalChildren().
RemoveConnectionMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.RemoveConnectionMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, NodeId connectionId)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.RemoveConnectionMethodState.InitializeOptionalChildren().
RemoveDataSetFolderMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.RemoveDataSetFolderMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, NodeId dataSetFolderNodeId)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.RemoveDataSetFolderMethodState.InitializeOptionalChildren().
RemoveEndpointMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.RemoveEndpointMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, EndpointType endpoint)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.RemoveEndpointMethodState.InitializeOptionalChildren().
RemoveExtensionFieldMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.RemoveExtensionFieldMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, NodeId fieldId)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.RemoveExtensionFieldMethodState.InitializeOptionalChildren().
RemoveIdentityMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.RemoveIdentityMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, IdentityMappingRuleType rule)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.RemoveIdentityMethodState.InitializeOptionalChildren().
RemovePublishedDataSetMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.RemovePublishedDataSetMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, NodeId dataSetNodeId)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.RemovePublishedDataSetMethodState.InitializeOptionalChildren().
RemoveRoleMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.RemoveRoleMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, NodeId roleNodeId)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.RemoveRoleMethodState.InitializeOptionalChildren().
RemoveSecurityGroupMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.RemoveSecurityGroupMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, NodeId securityGroupNodeId)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.RemoveSecurityGroupMethodState.InitializeOptionalChildren().
RequestServerStateChangeMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.RequestServerStateChangeMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, ServerState state, DateTime estimatedReturnTime, uint secondsTillShutdown, LocalizedText reason, bool restart)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.RequestServerStateChangeMethodState.InitializeOptionalChildren().
ResendDataMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.ResendDataMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, uint subscriptionId)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.ResendDataMethodState.InitializeOptionalChildren().
SetPositionMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.SetPositionMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, uint fileHandle, ulong position)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.SetPositionMethodState.InitializeOptionalChildren().
SetSecurityKeysMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.SetSecurityKeysMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, string securityGroupId, string securityPolicyUri, uint currentTokenId, byte [] currentKey, byte futureKeys[][], double timeToNextKey, double keyLifetime)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.SetSecurityKeysMethodState.InitializeOptionalChildren().
SetSubscriptionDurableMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.SetSubscriptionDurableMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, uint subscriptionId, uint lifetimeInHours, ref uint revisedLifetimeInHours)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.SetSubscriptionDurableMethodState.InitializeOptionalChildren().
TargetVariablesTypeAddTargetVariablesMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.TargetVariablesTypeAddTargetVariablesMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, ConfigurationVersionDataType configurationVersion, FieldTargetDataType [] targetVariablesToAdd, ref StatusCode [] addResults)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.TargetVariablesTypeAddTargetVariablesMethodState.InitializeOptionalChildren().
TargetVariablesTypeRemoveTargetVariablesMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.TargetVariablesTypeRemoveTargetVariablesMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, ConfigurationVersionDataType configurationVersion, uint [] targetsToRemove, ref StatusCode [] removeResults)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.TargetVariablesTypeRemoveTargetVariablesMethodState.InitializeOptionalChildren().
TimedShelveMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.TimedShelveMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, double shelvingTime)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.TimedShelveMethodState.InitializeOptionalChildren().
UpdateCertificateMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.UpdateCertificateMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, NodeId certificateGroupId, NodeId certificateTypeId, byte [] certificate, byte issuerCertificates[][], string privateKeyFormat, byte [] privateKey, ref bool applyChangesRequired)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.UpdateCertificateMethodState.InitializeOptionalChildren().
WriteMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.WriteMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, uint fileHandle, byte [] data)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.WriteMethodState.InitializeOptionalChildren().