Project Template: Opc.Ua.Node Class Reference
Opc.Ua.Node Class Reference
Public Member Functions
Node ()
The default constructor.
virtual void Encode (IEncoder encoder)
virtual void Decode (IDecoder decoder)
virtual bool IsEqual (IEncodeable encodeable)
virtual object Clone ()
new object MemberwiseClone ()
Properties
NodeId NodeId [get, set]
NodeClass NodeClass [get, set]
QualifiedName BrowseName [get, set]
LocalizedText DisplayName [get, set]
LocalizedText Description [get, set]
uint WriteMask [get, set]
uint UserWriteMask [get, set]
RolePermissionTypeCollection RolePermissions [get, set]
RolePermissionTypeCollection UserRolePermissions [get, set]
ushort AccessRestrictions [get, set]
ReferenceNodeCollection References [get, set]
virtual ExpandedNodeId TypeId [get]
virtual ExpandedNodeId BinaryEncodingId [get]
virtual ExpandedNodeId XmlEncodingId [get]
Detailed Description
<exclude>
Definition at line 19416 of file Opc.Ua.DataTypes.cs.
Constructor & Destructor Documentation
Node()
Opc.Ua.Node.Node () inline
The default constructor.
Definition at line 19422 of file Opc.Ua.DataTypes.cs.
Member Function Documentation
Clone()
virtual object Opc.Ua.Node.Clone () inline virtual
Reimplemented in Opc.Ua.DataTypeNode, Opc.Ua.ViewNode, Opc.Ua.MethodNode, Opc.Ua.ReferenceTypeNode, Opc.Ua.VariableTypeNode, Opc.Ua.VariableNode, Opc.Ua.ObjectTypeNode, Opc.Ua.ObjectNode, Opc.Ua.TypeNode, and Opc.Ua.InstanceNode.
Definition at line 19678 of file Opc.Ua.DataTypes.cs.
Decode()
virtual void Opc.Ua.Node.Decode (IDecoder decoder) inline virtual
Reimplemented in Opc.Ua.DataTypeNode, Opc.Ua.ViewNode, Opc.Ua.MethodNode, Opc.Ua.ReferenceTypeNode, Opc.Ua.VariableTypeNode, Opc.Ua.VariableNode, Opc.Ua.ObjectTypeNode, Opc.Ua.ObjectNode, Opc.Ua.TypeNode, and Opc.Ua.InstanceNode.
Definition at line 19627 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.AccessRestrictions, Opc.Ua.BrowseName, Opc.Ua.Description, Opc.Ua.DisplayName, Opc.Ua.NodeId, Opc.Ua.Namespaces.OpcUaXsd, Opc.Ua.RolePermissions, Opc.Ua.UserWriteMask, and Opc.Ua.WriteMask.
Encode()
virtual void Opc.Ua.Node.Encode (IEncoder encoder) inline virtual
Reimplemented in Opc.Ua.DataTypeNode, Opc.Ua.ViewNode, Opc.Ua.MethodNode, Opc.Ua.ReferenceTypeNode, Opc.Ua.VariableTypeNode, Opc.Ua.VariableNode, Opc.Ua.ObjectTypeNode, Opc.Ua.ObjectNode, Opc.Ua.TypeNode, and Opc.Ua.InstanceNode.
Definition at line 19607 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.AccessRestrictions, Opc.Ua.BrowseName, Opc.Ua.Description, Opc.Ua.DisplayName, Opc.Ua.NodeId, Opc.Ua.Namespaces.OpcUaXsd, Opc.Ua.RolePermissions, Opc.Ua.UserWriteMask, and Opc.Ua.WriteMask.
IsEqual()
virtual bool Opc.Ua.Node.IsEqual (IEncodeable encodeable) inline virtual
Reimplemented in Opc.Ua.DataTypeNode, Opc.Ua.ViewNode, Opc.Ua.MethodNode, Opc.Ua.ReferenceTypeNode, Opc.Ua.VariableTypeNode, Opc.Ua.VariableNode, Opc.Ua.ObjectTypeNode, Opc.Ua.ObjectNode, Opc.Ua.TypeNode, and Opc.Ua.InstanceNode.
Definition at line 19647 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Object.
MemberwiseClone()
new object Opc.Ua.Node.MemberwiseClone () inline
Definition at line 19685 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.RolePermissionTypeCollection.Clone(), Opc.Ua.ReferenceNodeCollection.Clone(), Opc.Ua.Node.MemberwiseClone(), Opc.Ua.NodeId, and Opc.Ua.Namespaces.OpcUaXsd.
Referenced by Opc.Ua.Node.MemberwiseClone().
Property Documentation
AccessRestrictions
ushort Opc.Ua.Node.AccessRestrictions get set
Definition at line 19559 of file Opc.Ua.DataTypes.cs.
BinaryEncodingId
virtual ExpandedNodeId Opc.Ua.Node.BinaryEncodingId get
Definition at line 19596 of file Opc.Ua.DataTypes.cs.
BrowseName
QualifiedName Opc.Ua.Node.BrowseName get set
Definition at line 19475 of file Opc.Ua.DataTypes.cs.
Description
LocalizedText Opc.Ua.Node.Description get set
Definition at line 19491 of file Opc.Ua.DataTypes.cs.
DisplayName
LocalizedText Opc.Ua.Node.DisplayName get set
Definition at line 19483 of file Opc.Ua.DataTypes.cs.
NodeClass
NodeClass Opc.Ua.Node.NodeClass get set
Definition at line 19467 of file Opc.Ua.DataTypes.cs.
NodeId
NodeId Opc.Ua.Node.NodeId get set
Definition at line 19459 of file Opc.Ua.DataTypes.cs.
References
ReferenceNodeCollection Opc.Ua.Node.References get set
Definition at line 19569 of file Opc.Ua.DataTypes.cs.
RolePermissions
RolePermissionTypeCollection Opc.Ua.Node.RolePermissions get set
Definition at line 19517 of file Opc.Ua.DataTypes.cs.
TypeId
virtual ExpandedNodeId Opc.Ua.Node.TypeId get
Definition at line 19590 of file Opc.Ua.DataTypes.cs.
UserRolePermissions
RolePermissionTypeCollection Opc.Ua.Node.UserRolePermissions get set
Definition at line 19539 of file Opc.Ua.DataTypes.cs.
UserWriteMask
uint Opc.Ua.Node.UserWriteMask get set
Definition at line 19507 of file Opc.Ua.DataTypes.cs.
WriteMask
uint Opc.Ua.Node.WriteMask get set
Definition at line 19499 of file Opc.Ua.DataTypes.cs.
XmlEncodingId
virtual ExpandedNodeId Opc.Ua.Node.XmlEncodingId get
Definition at line 19602 of file Opc.Ua.DataTypes.cs.
The documentation for this class was generated from the following file:
Opc.Ua.DataTypes.cs