Project Template: Opc.Ua.DeleteNodesRequest Class Reference
Opc.Ua.DeleteNodesRequest Class Reference
Public Member Functions
DeleteNodesRequest ()
The default constructor.
virtual void Encode (IEncoder encoder)
virtual void Decode (IDecoder decoder)
virtual bool IsEqual (IEncodeable encodeable)
virtual object Clone ()
new object MemberwiseClone ()
Properties
RequestHeader RequestHeader [get, set]
DeleteNodesItemCollection NodesToDelete [get, set]
virtual ExpandedNodeId TypeId [get]
virtual ExpandedNodeId BinaryEncodingId [get]
virtual ExpandedNodeId XmlEncodingId [get]
Detailed Description
<exclude>
Definition at line 1431 of file Opc.Ua.Messages.cs.
Constructor & Destructor Documentation
DeleteNodesRequest()
Opc.Ua.DeleteNodesRequest.DeleteNodesRequest () inline
The default constructor.
Definition at line 35465 of file Opc.Ua.DataTypes.cs.
Member Function Documentation
Clone()
virtual object Opc.Ua.DeleteNodesRequest.Clone () inline virtual
Definition at line 35599 of file Opc.Ua.DataTypes.cs.
Decode()
virtual void Opc.Ua.DeleteNodesRequest.Decode (IDecoder decoder) inline virtual
Definition at line 35566 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
Encode()
virtual void Opc.Ua.DeleteNodesRequest.Encode (IEncoder encoder) inline virtual
Definition at line 35555 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
IsEqual()
virtual bool Opc.Ua.DeleteNodesRequest.IsEqual (IEncodeable encodeable) inline virtual
Definition at line 35577 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Object.
MemberwiseClone()
new object Opc.Ua.DeleteNodesRequest.MemberwiseClone () inline
Definition at line 35606 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.RequestHeader.Clone(), Opc.Ua.DeleteNodesItemCollection.Clone(), Opc.Ua.DeleteNodesRequest.MemberwiseClone(), and Opc.Ua.Namespaces.OpcUaXsd.
Referenced by Opc.Ua.DeleteNodesRequest.MemberwiseClone().
Property Documentation
BinaryEncodingId
virtual ExpandedNodeId Opc.Ua.DeleteNodesRequest.BinaryEncodingId get
Definition at line 35544 of file Opc.Ua.DataTypes.cs.
NodesToDelete
DeleteNodesItemCollection Opc.Ua.DeleteNodesRequest.NodesToDelete get set
Definition at line 35517 of file Opc.Ua.DataTypes.cs.
Referenced by Opc.Ua.SessionClient.BeginDeleteNodes(), Opc.Ua.SessionClient.EndAddReferences(), and Opc.Ua.SessionEndpoint.EndAddReferences().
RequestHeader
RequestHeader Opc.Ua.DeleteNodesRequest.RequestHeader get set
Definition at line 35495 of file Opc.Ua.DataTypes.cs.
Referenced by Opc.Ua.SessionClient.BeginDeleteNodes(), Opc.Ua.SessionClient.EndAddReferences(), and Opc.Ua.SessionEndpoint.EndAddReferences().
TypeId
virtual ExpandedNodeId Opc.Ua.DeleteNodesRequest.TypeId get
Definition at line 35538 of file Opc.Ua.DataTypes.cs.
XmlEncodingId
virtual ExpandedNodeId Opc.Ua.DeleteNodesRequest.XmlEncodingId get
Definition at line 35550 of file Opc.Ua.DataTypes.cs.
The documentation for this class was generated from the following files:
Opc.Ua.Messages.cs
Opc.Ua.DataTypes.cs