Project Template: Opc.Ua.ThreeDCartesianCoordinates Class Reference
Opc.Ua.ThreeDCartesianCoordinates Class Reference
Public Member Functions
ThreeDCartesianCoordinates ()
The default constructor.
override void Encode (IEncoder encoder)
override void Decode (IDecoder decoder)
override bool IsEqual (IEncodeable encodeable)
override object Clone ()
new object MemberwiseClone ()
Public Member Functions inherited from Opc.Ua.CartesianCoordinates
CartesianCoordinates ()
The default constructor.
new object MemberwiseClone ()
Properties
double X [get, set]
double Y [get, set]
double Z [get, set]
override ExpandedNodeId TypeId [get]
override ExpandedNodeId BinaryEncodingId [get]
override ExpandedNodeId XmlEncodingId [get]
Properties inherited from Opc.Ua.CartesianCoordinates
virtual ExpandedNodeId TypeId [get]
virtual ExpandedNodeId BinaryEncodingId [get]
virtual ExpandedNodeId XmlEncodingId [get]
Detailed Description
<exclude>
Definition at line 1634 of file Opc.Ua.DataTypes.cs.
Constructor & Destructor Documentation
ThreeDCartesianCoordinates()
Opc.Ua.ThreeDCartesianCoordinates.ThreeDCartesianCoordinates () inline
The default constructor.
Definition at line 1640 of file Opc.Ua.DataTypes.cs.
Member Function Documentation
Clone()
override object Opc.Ua.ThreeDCartesianCoordinates.Clone () inline virtual
Reimplemented from Opc.Ua.CartesianCoordinates.
Definition at line 1763 of file Opc.Ua.DataTypes.cs.
Referenced by Opc.Ua.ThreeDFrame.MemberwiseClone().
Decode()
override void Opc.Ua.ThreeDCartesianCoordinates.Decode (IDecoder decoder) inline virtual
Reimplemented from Opc.Ua.CartesianCoordinates.
Definition at line 1725 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
Encode()
override void Opc.Ua.ThreeDCartesianCoordinates.Encode (IEncoder encoder) inline virtual
Reimplemented from Opc.Ua.CartesianCoordinates.
Definition at line 1711 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
IsEqual()
override bool Opc.Ua.ThreeDCartesianCoordinates.IsEqual (IEncodeable encodeable) inline virtual
Reimplemented from Opc.Ua.CartesianCoordinates.
Definition at line 1739 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Object.
MemberwiseClone()
new object Opc.Ua.ThreeDCartesianCoordinates.MemberwiseClone () inline
Definition at line 1770 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.ThreeDCartesianCoordinates.MemberwiseClone(), and Opc.Ua.Namespaces.OpcUaXsd.
Referenced by Opc.Ua.ThreeDCartesianCoordinates.MemberwiseClone().
Property Documentation
BinaryEncodingId
override ExpandedNodeId Opc.Ua.ThreeDCartesianCoordinates.BinaryEncodingId get
Definition at line 1700 of file Opc.Ua.DataTypes.cs.
TypeId
override ExpandedNodeId Opc.Ua.ThreeDCartesianCoordinates.TypeId get
Definition at line 1694 of file Opc.Ua.DataTypes.cs.
X
double Opc.Ua.ThreeDCartesianCoordinates.X get set
Definition at line 1669 of file Opc.Ua.DataTypes.cs.
XmlEncodingId
override ExpandedNodeId Opc.Ua.ThreeDCartesianCoordinates.XmlEncodingId get
Definition at line 1706 of file Opc.Ua.DataTypes.cs.
Y
double Opc.Ua.ThreeDCartesianCoordinates.Y get set
Definition at line 1677 of file Opc.Ua.DataTypes.cs.
Z
double Opc.Ua.ThreeDCartesianCoordinates.Z get set
Definition at line 1685 of file Opc.Ua.DataTypes.cs.
The documentation for this class was generated from the following file:
Opc.Ua.DataTypes.cs