Project Template: Opc.Ua.ThreeDOrientation Class Reference
Opc.Ua.ThreeDOrientation Class Reference
Public Member Functions
ThreeDOrientation ()
The default constructor.
override void Encode (IEncoder encoder)
override void Decode (IDecoder decoder)
override bool IsEqual (IEncodeable encodeable)
override object Clone ()
new object MemberwiseClone ()
Public Member Functions inherited from Opc.Ua.Orientation
Orientation ()
The default constructor.
new object MemberwiseClone ()
Properties
double A [get, set]
double B [get, set]
double C [get, set]
override ExpandedNodeId TypeId [get]
override ExpandedNodeId BinaryEncodingId [get]
override ExpandedNodeId XmlEncodingId [get]
Properties inherited from Opc.Ua.Orientation
virtual ExpandedNodeId TypeId [get]
virtual ExpandedNodeId BinaryEncodingId [get]
virtual ExpandedNodeId XmlEncodingId [get]
Detailed Description
<exclude>
Definition at line 2088 of file Opc.Ua.DataTypes.cs.
Constructor & Destructor Documentation
ThreeDOrientation()
Opc.Ua.ThreeDOrientation.ThreeDOrientation () inline
The default constructor.
Definition at line 2094 of file Opc.Ua.DataTypes.cs.
Member Function Documentation
Clone()
override object Opc.Ua.ThreeDOrientation.Clone () inline virtual
Reimplemented from Opc.Ua.Orientation.
Definition at line 2217 of file Opc.Ua.DataTypes.cs.
Referenced by Opc.Ua.ThreeDFrame.MemberwiseClone().
Decode()
override void Opc.Ua.ThreeDOrientation.Decode (IDecoder decoder) inline virtual
Reimplemented from Opc.Ua.Orientation.
Definition at line 2179 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
Encode()
override void Opc.Ua.ThreeDOrientation.Encode (IEncoder encoder) inline virtual
Reimplemented from Opc.Ua.Orientation.
Definition at line 2165 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
IsEqual()
override bool Opc.Ua.ThreeDOrientation.IsEqual (IEncodeable encodeable) inline virtual
Reimplemented from Opc.Ua.Orientation.
Definition at line 2193 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Object.
MemberwiseClone()
new object Opc.Ua.ThreeDOrientation.MemberwiseClone () inline
Definition at line 2224 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.ThreeDOrientation.MemberwiseClone(), and Opc.Ua.Namespaces.OpcUaXsd.
Referenced by Opc.Ua.ThreeDOrientation.MemberwiseClone().
Property Documentation
A
double Opc.Ua.ThreeDOrientation.A get set
Definition at line 2123 of file Opc.Ua.DataTypes.cs.
B
double Opc.Ua.ThreeDOrientation.B get set
Definition at line 2131 of file Opc.Ua.DataTypes.cs.
BinaryEncodingId
override ExpandedNodeId Opc.Ua.ThreeDOrientation.BinaryEncodingId get
Definition at line 2154 of file Opc.Ua.DataTypes.cs.
C
double Opc.Ua.ThreeDOrientation.C get set
Definition at line 2139 of file Opc.Ua.DataTypes.cs.
TypeId
override ExpandedNodeId Opc.Ua.ThreeDOrientation.TypeId get
Definition at line 2148 of file Opc.Ua.DataTypes.cs.
XmlEncodingId
override ExpandedNodeId Opc.Ua.ThreeDOrientation.XmlEncodingId get
Definition at line 2160 of file Opc.Ua.DataTypes.cs.
The documentation for this class was generated from the following file:
Opc.Ua.DataTypes.cs