Project Template: server.h File Reference
server.h File Reference
Data Structures
struct UA_GlobalNodeLifecycle
struct UA_NodeTypeLifecycle
struct UA_DataSource
struct UA_ValueCallback
Typedefs
typedef struct UA_ServerConfig UA_ServerConfig
typedef struct UA_Server UA_Server
typedef void(* UA_ServerCallback) (UA_Server *server, void *data)
typedef UA_StatusCode(* UA_NodeIteratorCallback) (UA_NodeId childId, UA_Boolean isInverse, UA_NodeId referenceTypeId, void *handle)
typedef void(* UA_Server_registerServerCallback) (const UA_RegisteredServer *registeredServer, void *data)
typedef void(* UA_Server_serverOnNetworkCallback) (const UA_ServerOnNetwork *serverOnNetwork, UA_Boolean isServerAnnounce, UA_Boolean isTxtReceived, void *data)
typedef void(* UA_Server_DataChangeNotificationCallback) (UA_Server *server, UA_UInt32 monitoredItemId, void *monitoredItemContext, const UA_NodeId *nodeId, void *nodeContext, UA_UInt32 attributeId, const UA_DataValue *value)
typedef void(* UA_Server_EventNotificationCallback) (UA_Server *server, UA_UInt32 monId, void *monContext, size_t nEventFields, const UA_Variant *eventFields)
typedef UA_StatusCode(* UA_MethodCallback) (UA_Server *server, const UA_NodeId *sessionId, void *sessionContext, const UA_NodeId *methodId, void *methodContext, const UA_NodeId *objectId, void *objectContext, size_t inputSize, const UA_Variant *input, size_t outputSize, UA_Variant *output)
Functions
UA_Server UA_EXPORT * UA_Server_new (void)
UA_Server UA_EXPORT * UA_Server_newWithConfig (const UA_ServerConfig *config)
void UA_EXPORT UA_Server_delete (UA_Server *server)
UA_ServerConfig UA_EXPORT * UA_Server_getConfig (UA_Server *server)
UA_StatusCode UA_EXPORT UA_Server_run (UA_Server *server, const volatile UA_Boolean *running)
UA_StatusCode UA_EXPORT UA_Server_run_startup (UA_Server *server)
UA_UInt16 UA_EXPORT UA_Server_run_iterate (UA_Server *server, UA_Boolean waitInternal)
UA_StatusCode UA_EXPORT UA_Server_run_shutdown (UA_Server *server)
UA_StatusCode UA_EXPORT UA_Server_addTimedCallback (UA_Server *server, UA_ServerCallback callback, void *data, UA_DateTime date, UA_UInt64 *callbackId)
UA_StatusCode UA_EXPORT UA_Server_addRepeatedCallback (UA_Server *server, UA_ServerCallback callback, void *data, UA_Double interval_ms, UA_UInt64 *callbackId)
UA_StatusCode UA_EXPORT UA_Server_changeRepeatedCallbackInterval (UA_Server *server, UA_UInt64 callbackId, UA_Double interval_ms)
void UA_EXPORT UA_Server_removeCallback (UA_Server *server, UA_UInt64 callbackId)
UA_DataValue UA_EXPORT UA_Server_read (UA_Server *server, const UA_ReadValueId *item, UA_TimestampsToReturn timestamps)
UA_StatusCode UA_EXPORT __UA_Server_read (UA_Server *server, const UA_NodeId *nodeId, UA_AttributeId attributeId, void *v)
static UA_INLINE UA_StatusCode UA_Server_readNodeId (UA_Server *server, const UA_NodeId nodeId, UA_NodeId *outNodeId)
static UA_INLINE UA_StatusCode UA_Server_readNodeClass (UA_Server *server, const UA_NodeId nodeId, UA_NodeClass *outNodeClass)
static UA_INLINE UA_StatusCode UA_Server_readBrowseName (UA_Server *server, const UA_NodeId nodeId, UA_QualifiedName *outBrowseName)
static UA_INLINE UA_StatusCode UA_Server_readDisplayName (UA_Server *server, const UA_NodeId nodeId, UA_LocalizedText *outDisplayName)
static UA_INLINE UA_StatusCode UA_Server_readDescription (UA_Server *server, const UA_NodeId nodeId, UA_LocalizedText *outDescription)
static UA_INLINE UA_StatusCode UA_Server_readWriteMask (UA_Server *server, const UA_NodeId nodeId, UA_UInt32 *outWriteMask)
static UA_INLINE UA_StatusCode UA_Server_readIsAbstract (UA_Server *server, const UA_NodeId nodeId, UA_Boolean *outIsAbstract)
static UA_INLINE UA_StatusCode UA_Server_readSymmetric (UA_Server *server, const UA_NodeId nodeId, UA_Boolean *outSymmetric)
static UA_INLINE UA_StatusCode UA_Server_readInverseName (UA_Server *server, const UA_NodeId nodeId, UA_LocalizedText *outInverseName)
static UA_INLINE UA_StatusCode UA_Server_readContainsNoLoop (UA_Server *server, const UA_NodeId nodeId, UA_Boolean *outContainsNoLoops)
static UA_INLINE UA_StatusCode UA_Server_readEventNotifier (UA_Server *server, const UA_NodeId nodeId, UA_Byte *outEventNotifier)
static UA_INLINE UA_StatusCode UA_Server_readValue (UA_Server *server, const UA_NodeId nodeId, UA_Variant *outValue)
static UA_INLINE UA_StatusCode UA_Server_readDataType (UA_Server *server, const UA_NodeId nodeId, UA_NodeId *outDataType)
static UA_INLINE UA_StatusCode UA_Server_readValueRank (UA_Server *server, const UA_NodeId nodeId, UA_Int32 *outValueRank)
static UA_INLINE UA_StatusCode UA_Server_readArrayDimensions (UA_Server *server, const UA_NodeId nodeId, UA_Variant *outArrayDimensions)
static UA_INLINE UA_StatusCode UA_Server_readAccessLevel (UA_Server *server, const UA_NodeId nodeId, UA_Byte *outAccessLevel)
static UA_INLINE UA_StatusCode UA_Server_readMinimumSamplingInterval (UA_Server *server, const UA_NodeId nodeId, UA_Double *outMinimumSamplingInterval)
static UA_INLINE UA_StatusCode UA_Server_readHistorizing (UA_Server *server, const UA_NodeId nodeId, UA_Boolean *outHistorizing)
static UA_INLINE UA_StatusCode UA_Server_readExecutable (UA_Server *server, const UA_NodeId nodeId, UA_Boolean *outExecutable)
UA_StatusCode UA_EXPORT UA_Server_write (UA_Server *server, const UA_WriteValue *value)
UA_StatusCode UA_EXPORT __UA_Server_write (UA_Server *server, const UA_NodeId *nodeId, const UA_AttributeId attributeId, const UA_DataType *attr_type, const void *attr)
static UA_INLINE UA_StatusCode UA_Server_writeBrowseName (UA_Server *server, const UA_NodeId nodeId, const UA_QualifiedName browseName)
static UA_INLINE UA_StatusCode UA_Server_writeDisplayName (UA_Server *server, const UA_NodeId nodeId, const UA_LocalizedText displayName)
static UA_INLINE UA_StatusCode UA_Server_writeDescription (UA_Server *server, const UA_NodeId nodeId, const UA_LocalizedText description)
static UA_INLINE UA_StatusCode UA_Server_writeWriteMask (UA_Server *server, const UA_NodeId nodeId, const UA_UInt32 writeMask)
static UA_INLINE UA_StatusCode UA_Server_writeIsAbstract (UA_Server *server, const UA_NodeId nodeId, const UA_Boolean isAbstract)
static UA_INLINE UA_StatusCode UA_Server_writeInverseName (UA_Server *server, const UA_NodeId nodeId, const UA_LocalizedText inverseName)
static UA_INLINE UA_StatusCode UA_Server_writeEventNotifier (UA_Server *server, const UA_NodeId nodeId, const UA_Byte eventNotifier)
static UA_INLINE UA_StatusCode UA_Server_writeValue (UA_Server *server, const UA_NodeId nodeId, const UA_Variant value)
static UA_INLINE UA_StatusCode UA_Server_writeDataType (UA_Server *server, const UA_NodeId nodeId, const UA_NodeId dataType)
static UA_INLINE UA_StatusCode UA_Server_writeValueRank (UA_Server *server, const UA_NodeId nodeId, const UA_Int32 valueRank)
static UA_INLINE UA_StatusCode UA_Server_writeArrayDimensions (UA_Server *server, const UA_NodeId nodeId, const UA_Variant arrayDimensions)
static UA_INLINE UA_StatusCode UA_Server_writeAccessLevel (UA_Server *server, const UA_NodeId nodeId, const UA_Byte accessLevel)
static UA_INLINE UA_StatusCode UA_Server_writeMinimumSamplingInterval (UA_Server *server, const UA_NodeId nodeId, const UA_Double miniumSamplingInterval)
static UA_INLINE UA_StatusCode UA_Server_writeHistorizing (UA_Server *server, const UA_NodeId nodeId, const UA_Boolean historizing)
static UA_INLINE UA_StatusCode UA_Server_writeExecutable (UA_Server *server, const UA_NodeId nodeId, const UA_Boolean executable)
UA_BrowseResult UA_EXPORT UA_Server_browse (UA_Server *server, UA_UInt32 maxReferences, const UA_BrowseDescription *bd)
UA_BrowseResult UA_EXPORT UA_Server_browseNext (UA_Server *server, UA_Boolean releaseContinuationPoint, const UA_ByteString *continuationPoint)
UA_StatusCode UA_EXPORT UA_Server_browseRecursive (UA_Server *server, const UA_BrowseDescription *bd, size_t *resultsSize, UA_ExpandedNodeId *results)
UA_BrowsePathResult UA_EXPORT UA_Server_translateBrowsePathToNodeIds (UA_Server *server, const UA_BrowsePath *browsePath)
UA_BrowsePathResult UA_EXPORT UA_Server_browseSimplifiedBrowsePath (UA_Server *server, const UA_NodeId origin, size_t browsePathSize, const UA_QualifiedName *browsePath)
UA_StatusCode UA_EXPORT UA_Server_forEachChildNodeCall (UA_Server *server, UA_NodeId parentNodeId, UA_NodeIteratorCallback callback, void *handle)
UA_StatusCode UA_EXPORT UA_Server_register_discovery (UA_Server *server, struct UA_Client *client, const char *semaphoreFilePath)
UA_StatusCode UA_EXPORT UA_Server_unregister_discovery (UA_Server *server, struct UA_Client *client)
UA_StatusCode UA_EXPORT UA_Server_addPeriodicServerRegisterCallback (UA_Server *server, struct UA_Client *client, const char *discoveryServerUrl, UA_Double intervalMs, UA_Double delayFirstRegisterMs, UA_UInt64 *periodicCallbackId)
void UA_EXPORT UA_Server_setRegisterServerCallback (UA_Server *server, UA_Server_registerServerCallback cb, void *data)
void UA_EXPORT UA_Server_setServerOnNetworkCallback (UA_Server *server, UA_Server_serverOnNetworkCallback cb, void *data)
UA_StatusCode UA_EXPORT UA_Server_setNodeTypeLifecycle (UA_Server *server, UA_NodeId nodeId, UA_NodeTypeLifecycle lifecycle)
UA_StatusCode UA_EXPORT UA_Server_getNodeContext (UA_Server *server, UA_NodeId nodeId, void **nodeContext)
UA_StatusCode UA_EXPORT UA_Server_setNodeContext (UA_Server *server, UA_NodeId nodeId, void *nodeContext)
UA_StatusCode UA_EXPORT UA_Server_setVariableNode_dataSource (UA_Server *server, const UA_NodeId nodeId, const UA_DataSource dataSource)
UA_StatusCode UA_EXPORT UA_Server_setVariableNode_valueCallback (UA_Server *server, const UA_NodeId nodeId, const UA_ValueCallback callback)
UA_MonitoredItemCreateResult UA_EXPORT UA_Server_createDataChangeMonitoredItem (UA_Server *server, UA_TimestampsToReturn timestampsToReturn, const UA_MonitoredItemCreateRequest item, void *monitoredItemContext, UA_Server_DataChangeNotificationCallback callback)
UA_StatusCode UA_EXPORT UA_Server_deleteMonitoredItem (UA_Server *server, UA_UInt32 monitoredItemId)
UA_StatusCode UA_EXPORT UA_Server_setMethodNode_callback (UA_Server *server, const UA_NodeId methodNodeId, UA_MethodCallback methodCallback)
UA_StatusCode UA_EXPORT UA_Server_writeObjectProperty (UA_Server *server, const UA_NodeId objectId, const UA_QualifiedName propertyName, const UA_Variant value)
UA_StatusCode UA_EXPORT UA_Server_writeObjectProperty_scalar (UA_Server *server, const UA_NodeId objectId, const UA_QualifiedName propertyName, const void *value, const UA_DataType *type)
UA_StatusCode UA_EXPORT UA_Server_readObjectProperty (UA_Server *server, const UA_NodeId objectId, const UA_QualifiedName propertyName, UA_Variant *value)
UA_CallMethodResult UA_EXPORT UA_Server_call (UA_Server *server, const UA_CallMethodRequest *request)
UA_StatusCode UA_EXPORT __UA_Server_addNode (UA_Server *server, const UA_NodeClass nodeClass, const UA_NodeId *requestedNewNodeId, const UA_NodeId *parentNodeId, const UA_NodeId *referenceTypeId, const UA_QualifiedName browseName, const UA_NodeId *typeDefinition, const UA_NodeAttributes *attr, const UA_DataType *attributeType, void *nodeContext, UA_NodeId *outNewNodeId)
static UA_INLINE UA_StatusCode UA_Server_addVariableNode (UA_Server *server, const UA_NodeId requestedNewNodeId, const UA_NodeId parentNodeId, const UA_NodeId referenceTypeId, const UA_QualifiedName browseName, const UA_NodeId typeDefinition, const UA_VariableAttributes attr, void *nodeContext, UA_NodeId *outNewNodeId)
static UA_INLINE UA_StatusCode UA_Server_addVariableTypeNode (UA_Server *server, const UA_NodeId requestedNewNodeId, const UA_NodeId parentNodeId, const UA_NodeId referenceTypeId, const UA_QualifiedName browseName, const UA_NodeId typeDefinition, const UA_VariableTypeAttributes attr, void *nodeContext, UA_NodeId *outNewNodeId)
static UA_INLINE UA_StatusCode UA_Server_addObjectNode (UA_Server *server, const UA_NodeId requestedNewNodeId, const UA_NodeId parentNodeId, const UA_NodeId referenceTypeId, const UA_QualifiedName browseName, const UA_NodeId typeDefinition, const UA_ObjectAttributes attr, void *nodeContext, UA_NodeId *outNewNodeId)
static UA_INLINE UA_StatusCode UA_Server_addObjectTypeNode (UA_Server *server, const UA_NodeId requestedNewNodeId, const UA_NodeId parentNodeId, const UA_NodeId referenceTypeId, const UA_QualifiedName browseName, const UA_ObjectTypeAttributes attr, void *nodeContext, UA_NodeId *outNewNodeId)
static UA_INLINE UA_StatusCode UA_Server_addViewNode (UA_Server *server, const UA_NodeId requestedNewNodeId, const UA_NodeId parentNodeId, const UA_NodeId referenceTypeId, const UA_QualifiedName browseName, const UA_ViewAttributes attr, void *nodeContext, UA_NodeId *outNewNodeId)
static UA_INLINE UA_StatusCode UA_Server_addReferenceTypeNode (UA_Server *server, const UA_NodeId requestedNewNodeId, const UA_NodeId parentNodeId, const UA_NodeId referenceTypeId, const UA_QualifiedName browseName, const UA_ReferenceTypeAttributes attr, void *nodeContext, UA_NodeId *outNewNodeId)
static UA_INLINE UA_StatusCode UA_Server_addDataTypeNode (UA_Server *server, const UA_NodeId requestedNewNodeId, const UA_NodeId parentNodeId, const UA_NodeId referenceTypeId, const UA_QualifiedName browseName, const UA_DataTypeAttributes attr, void *nodeContext, UA_NodeId *outNewNodeId)
UA_StatusCode UA_EXPORT UA_Server_addDataSourceVariableNode (UA_Server *server, const UA_NodeId requestedNewNodeId, const UA_NodeId parentNodeId, const UA_NodeId referenceTypeId, const UA_QualifiedName browseName, const UA_NodeId typeDefinition, const UA_VariableAttributes attr, const UA_DataSource dataSource, void *nodeContext, UA_NodeId *outNewNodeId)
UA_StatusCode UA_EXPORT UA_Server_addMethodNodeEx (UA_Server *server, const UA_NodeId requestedNewNodeId, const UA_NodeId parentNodeId, const UA_NodeId referenceTypeId, const UA_QualifiedName browseName, const UA_MethodAttributes attr, UA_MethodCallback method, size_t inputArgumentsSize, const UA_Argument *inputArguments, const UA_NodeId inputArgumentsRequestedNewNodeId, UA_NodeId *inputArgumentsOutNewNodeId, size_t outputArgumentsSize, const UA_Argument *outputArguments, const UA_NodeId outputArgumentsRequestedNewNodeId, UA_NodeId *outputArgumentsOutNewNodeId, void *nodeContext, UA_NodeId *outNewNodeId)
static UA_INLINE UA_StatusCode UA_Server_addMethodNode (UA_Server *server, const UA_NodeId requestedNewNodeId, const UA_NodeId parentNodeId, const UA_NodeId referenceTypeId, const UA_QualifiedName browseName, const UA_MethodAttributes attr, UA_MethodCallback method, size_t inputArgumentsSize, const UA_Argument *inputArguments, size_t outputArgumentsSize, const UA_Argument *outputArguments, void *nodeContext, UA_NodeId *outNewNodeId)
UA_StatusCode UA_EXPORT UA_Server_addNode_begin (UA_Server *server, const UA_NodeClass nodeClass, const UA_NodeId requestedNewNodeId, const UA_NodeId parentNodeId, const UA_NodeId referenceTypeId, const UA_QualifiedName browseName, const UA_NodeId typeDefinition, const void *attr, const UA_DataType *attributeType, void *nodeContext, UA_NodeId *outNewNodeId)
UA_StatusCode UA_EXPORT UA_Server_addNode_finish (UA_Server *server, const UA_NodeId nodeId)
UA_StatusCode UA_EXPORT UA_Server_addMethodNode_finish (UA_Server *server, const UA_NodeId nodeId, UA_MethodCallback method, size_t inputArgumentsSize, const UA_Argument *inputArguments, size_t outputArgumentsSize, const UA_Argument *outputArguments)
UA_StatusCode UA_EXPORT UA_Server_deleteNode (UA_Server *server, const UA_NodeId nodeId, UA_Boolean deleteReferences)
UA_StatusCode UA_EXPORT UA_Server_addReference (UA_Server *server, const UA_NodeId sourceId, const UA_NodeId refTypeId, const UA_ExpandedNodeId targetId, UA_Boolean isForward)
UA_StatusCode UA_EXPORT UA_Server_deleteReference (UA_Server *server, const UA_NodeId sourceNodeId, const UA_NodeId referenceTypeId, UA_Boolean isForward, const UA_ExpandedNodeId targetNodeId, UA_Boolean deleteBidirectional)
UA_StatusCode UA_EXPORT UA_Server_createEvent (UA_Server *server, const UA_NodeId eventType, UA_NodeId *outNodeId)
UA_StatusCode UA_EXPORT UA_Server_triggerEvent (UA_Server *server, const UA_NodeId eventNodeId, const UA_NodeId originId, UA_ByteString *outEventId, const UA_Boolean deleteEventNode)
UA_StatusCode UA_EXPORT UA_Server_updateCertificate (UA_Server *server, const UA_ByteString *oldCertificate, const UA_ByteString *newCertificate, const UA_ByteString *newPrivateKey, UA_Boolean closeSessions, UA_Boolean closeSecureChannels)
UA_UInt16 UA_EXPORT UA_Server_addNamespace (UA_Server *server, const char *name)
UA_StatusCode UA_EXPORT UA_Server_getNamespaceByName (UA_Server *server, const UA_String namespaceUri, size_t *foundIndex)
UA_Boolean UA_EXPORT UA_Server_AccessControl_allowHistoryUpdateUpdateData (UA_Server *server, const UA_NodeId *sessionId, void *sessionContext, const UA_NodeId *nodeId, UA_PerformUpdateType performInsertReplace, const UA_DataValue *value)
UA_Boolean UA_EXPORT UA_Server_AccessControl_allowHistoryUpdateDeleteRawModified (UA_Server *server, const UA_NodeId *sessionId, void *sessionContext, const UA_NodeId *nodeId, UA_DateTime startTimestamp, UA_DateTime endTimestamp, bool isDeleteModified)
Variables
UA_EXPORT const UA_VariableAttributes UA_VariableAttributes_default
UA_EXPORT const UA_VariableTypeAttributes UA_VariableTypeAttributes_default
UA_EXPORT const UA_MethodAttributes UA_MethodAttributes_default
UA_EXPORT const UA_ObjectAttributes UA_ObjectAttributes_default
UA_EXPORT const UA_ObjectTypeAttributes UA_ObjectTypeAttributes_default
UA_EXPORT const UA_ReferenceTypeAttributes UA_ReferenceTypeAttributes_default
UA_EXPORT const UA_DataTypeAttributes UA_DataTypeAttributes_default
UA_EXPORT const UA_ViewAttributes UA_ViewAttributes_default
Typedef Documentation
UA_MethodCallback
typedef UA_StatusCode(* UA_MethodCallback) (UA_Server *server, const UA_NodeId *sessionId, void *sessionContext, const UA_NodeId *methodId, void *methodContext, const UA_NodeId *objectId, void *objectContext, size_t inputSize, const UA_Variant *input, size_t outputSize, UA_Variant *output)
Method Callbacks ^^^^^^^^^^^^^^^^ Method callbacks are set to NULL (not executable) when a method node is added over the network. In theory, it is possible to add a callback via UA_Server_setMethodNode_callback within the global constructor when adding methods over the network is really wanted. See the Section :ref:object-interaction for calling methods on an object.
Definition at line 897 of file server.h.
UA_NodeIteratorCallback
typedef UA_StatusCode(* UA_NodeIteratorCallback) (UA_NodeId childId, UA_Boolean isInverse, UA_NodeId referenceTypeId, void *handle)
Definition at line 495 of file server.h.
UA_Server
typedef struct UA_Server UA_Server
Definition at line 28 of file server.h.
UA_Server_DataChangeNotificationCallback
typedef void(* UA_Server_DataChangeNotificationCallback) (UA_Server *server, UA_UInt32 monitoredItemId, void *monitoredItemContext, const UA_NodeId *nodeId, void *nodeContext, UA_UInt32 attributeId, const UA_DataValue *value)
.. _local-monitoreditems:
Local MonitoredItems ^^^^^^^^^^^^^^^^^^^^
MonitoredItems are used with the Subscription mechanism of OPC UA to transported notifications for data changes and events. MonitoredItems can also be registered locally. Notifications are then forwarded to a user-defined callback instead of a remote client.
Definition at line 846 of file server.h.
UA_Server_EventNotificationCallback
typedef void(* UA_Server_EventNotificationCallback) (UA_Server *server, UA_UInt32 monId, void *monContext, size_t nEventFields, const UA_Variant *eventFields)
Definition at line 851 of file server.h.
UA_Server_registerServerCallback
typedef void(* UA_Server_registerServerCallback) (const UA_RegisteredServer *registeredServer, void *data)
Definition at line 563 of file server.h.
UA_Server_serverOnNetworkCallback
typedef void(* UA_Server_serverOnNetworkCallback) (const UA_ServerOnNetwork *serverOnNetwork, UA_Boolean isServerAnnounce, UA_Boolean isTxtReceived, void *data)
Definition at line 587 of file server.h.
UA_ServerCallback
typedef void(* UA_ServerCallback) (UA_Server *server, void *data)
Timed Callbacks
Definition at line 91 of file server.h.
UA_ServerConfig
typedef struct UA_ServerConfig UA_ServerConfig
Definition at line 25 of file server.h.
Function Documentation
__UA_Server_addNode()
UA_StatusCode UA_EXPORT __UA_Server_addNode (UA_Server * server, const UA_NodeClass nodeClass, const UA_NodeId * requestedNewNodeId, const UA_NodeId * parentNodeId, const UA_NodeId * referenceTypeId, const UA_QualifiedName browseName, const UA_NodeId * typeDefinition, const UA_NodeAttributes * attr, const UA_DataType * attributeType, void * nodeContext, UA_NodeId * outNewNodeId)
Referenced by UA_Server_addDataTypeNode(), UA_Server_addObjectNode(), UA_Server_addObjectTypeNode(), UA_Server_addReferenceTypeNode(), UA_Server_addVariableNode(), UA_Server_addVariableTypeNode(), and UA_Server_addViewNode().
__UA_Server_read()
UA_StatusCode UA_EXPORT __UA_Server_read (UA_Server * server, const UA_NodeId * nodeId, UA_AttributeId attributeId, void * v)
Referenced by UA_Server_readAccessLevel(), UA_Server_readArrayDimensions(), UA_Server_readBrowseName(), UA_Server_readContainsNoLoop(), UA_Server_readDataType(), UA_Server_readDescription(), UA_Server_readDisplayName(), UA_Server_readEventNotifier(), UA_Server_readExecutable(), UA_Server_readHistorizing(), UA_Server_readInverseName(), UA_Server_readIsAbstract(), UA_Server_readMinimumSamplingInterval(), UA_Server_readNodeClass(), UA_Server_readNodeId(), UA_Server_readSymmetric(), UA_Server_readValue(), UA_Server_readValueRank(), and UA_Server_readWriteMask().
__UA_Server_write()
UA_StatusCode UA_EXPORT __UA_Server_write (UA_Server * server, const UA_NodeId * nodeId, const UA_AttributeId attributeId, const UA_DataType * attr_type, const void * attr)
Referenced by UA_Server_readExecutable(), UA_Server_writeAccessLevel(), UA_Server_writeArrayDimensions(), UA_Server_writeBrowseName(), UA_Server_writeDataType(), UA_Server_writeDescription(), UA_Server_writeDisplayName(), UA_Server_writeEventNotifier(), UA_Server_writeExecutable(), UA_Server_writeHistorizing(), UA_Server_writeInverseName(), UA_Server_writeIsAbstract(), UA_Server_writeMinimumSamplingInterval(), UA_Server_writeValue(), UA_Server_writeValueRank(), and UA_Server_writeWriteMask().
UA_Server_AccessControl_allowHistoryUpdateDeleteRawModified()
UA_Boolean UA_EXPORT UA_Server_AccessControl_allowHistoryUpdateDeleteRawModified (UA_Server * server, const UA_NodeId * sessionId, void * sessionContext, const UA_NodeId * nodeId, UA_DateTime startTimestamp, UA_DateTime endTimestamp, bool isDeleteModified)
Referenced by UA_Server_addMethodNode().
UA_Server_AccessControl_allowHistoryUpdateUpdateData()
UA_Boolean UA_EXPORT UA_Server_AccessControl_allowHistoryUpdateUpdateData (UA_Server * server, const UA_NodeId * sessionId, void * sessionContext, const UA_NodeId * nodeId, UA_PerformUpdateType performInsertReplace, const UA_DataValue * value)
Referenced by UA_Server_addMethodNode().
UA_Server_addDataSourceVariableNode()
UA_StatusCode UA_EXPORT UA_Server_addDataSourceVariableNode (UA_Server * server, const UA_NodeId requestedNewNodeId, const UA_NodeId parentNodeId, const UA_NodeId referenceTypeId, const UA_QualifiedName browseName, const UA_NodeId typeDefinition, const UA_VariableAttributes attr, const UA_DataSource dataSource, void * nodeContext, UA_NodeId * outNewNodeId)
Referenced by UA_Server_addDataTypeNode().
UA_Server_addDataTypeNode()
static UA_INLINE UA_StatusCode UA_Server_addDataTypeNode (UA_Server * server, const UA_NodeId requestedNewNodeId, const UA_NodeId parentNodeId, const UA_NodeId referenceTypeId, const UA_QualifiedName browseName, const UA_DataTypeAttributes attr, void * nodeContext, UA_NodeId * outNewNodeId) static
Definition at line 1104 of file server.h.
References __UA_Server_addNode(), UA_NODECLASS_DATATYPE, UA_NODEID_NULL, UA_Server_addDataSourceVariableNode(), UA_Server_addMethodNodeEx(), and UA_TYPES.
UA_Server_addMethodNode()
static UA_INLINE UA_StatusCode UA_Server_addMethodNode (UA_Server * server, const UA_NodeId requestedNewNodeId, const UA_NodeId parentNodeId, const UA_NodeId referenceTypeId, const UA_QualifiedName browseName, const UA_MethodAttributes attr, UA_MethodCallback method, size_t inputArgumentsSize, const UA_Argument * inputArguments, size_t outputArgumentsSize, const UA_Argument * outputArguments, void * nodeContext, UA_NodeId * outNewNodeId) static
Definition at line 1146 of file server.h.
References UA_NODEID_NULL, UA_Server_AccessControl_allowHistoryUpdateDeleteRawModified(), UA_Server_AccessControl_allowHistoryUpdateUpdateData(), UA_Server_addMethodNode_finish(), UA_Server_addMethodNodeEx(), UA_Server_addNamespace(), UA_Server_addNode_begin(), UA_Server_addNode_finish(), UA_Server_addReference(), UA_Server_createEvent(), UA_Server_deleteNode(), UA_Server_deleteReference(), UA_Server_getNamespaceByName(), UA_Server_triggerEvent(), and UA_Server_updateCertificate().
UA_Server_addMethodNode_finish()
UA_StatusCode UA_EXPORT UA_Server_addMethodNode_finish (UA_Server * server, const UA_NodeId nodeId, UA_MethodCallback method, size_t inputArgumentsSize, const UA_Argument * inputArguments, size_t outputArgumentsSize, const UA_Argument * outputArguments)
Referenced by function_namespace0_generated_96_finish(), and UA_Server_addMethodNode().
UA_Server_addMethodNodeEx()
UA_StatusCode UA_EXPORT UA_Server_addMethodNodeEx (UA_Server * server, const UA_NodeId requestedNewNodeId, const UA_NodeId parentNodeId, const UA_NodeId referenceTypeId, const UA_QualifiedName browseName, const UA_MethodAttributes attr, UA_MethodCallback method, size_t inputArgumentsSize, const UA_Argument * inputArguments, const UA_NodeId inputArgumentsRequestedNewNodeId, UA_NodeId * inputArgumentsOutNewNodeId, size_t outputArgumentsSize, const UA_Argument * outputArguments, const UA_NodeId outputArgumentsRequestedNewNodeId, UA_NodeId * outputArgumentsOutNewNodeId, void * nodeContext, UA_NodeId * outNewNodeId)
Referenced by UA_Server_addDataTypeNode(), and UA_Server_addMethodNode().
UA_Server_addNamespace()
UA_UInt16 UA_EXPORT UA_Server_addNamespace (UA_Server * server, const char * name)
Utility Functions
Referenced by namespace0_generated(), and UA_Server_addMethodNode().
UA_Server_addNode_begin()
UA_StatusCode UA_EXPORT UA_Server_addNode_begin (UA_Server * server, const UA_NodeClass nodeClass, const UA_NodeId requestedNewNodeId, const UA_NodeId parentNodeId, const UA_NodeId referenceTypeId, const UA_QualifiedName browseName, const UA_NodeId typeDefinition, const void * attr, const UA_DataType * attributeType, void * nodeContext, UA_NodeId * outNewNodeId)
The method pair UA_Server_addNode_begin and _finish splits the AddNodes service in two parts. This is useful if the node shall be modified before finish the instantiation. For example to add children with specific NodeIds. Otherwise, mandatory children (e.g. of an ObjectType) are added with pseudo-random unique NodeIds. Existing children are detected during the _finish part via their matching BrowseName.
The _begin method:
prepares the node and adds it to the nodestore
copies some unassigned attributes from the TypeDefinition node internally
adds the references to the parent (and the TypeDefinition if applicable)
performs type-checking of variables.
You can add an object node without a parent if you set the parentNodeId and referenceTypeId to UA_NODE_ID_NULL. Then you need to add the parent reference and hasTypeDef reference yourself before calling the _finish method. Not that this is only allowed for object nodes.
The _finish method:
copies mandatory children
calls the node constructor(s) at the end
may remove the node if it encounters an error.
The special UA_Server_addMethodNode_finish method needs to be used for method nodes, since there you need to explicitly specifiy the input and output arguments which are added in the finish step (if not yet already there)
Referenced by function_namespace0_generated_0_begin(), function_namespace0_generated_100_begin(), function_namespace0_generated_101_begin(), function_namespace0_generated_102_begin(), function_namespace0_generated_103_begin(), function_namespace0_generated_104_begin(), function_namespace0_generated_105_begin(), function_namespace0_generated_106_begin(), function_namespace0_generated_107_begin(), function_namespace0_generated_108_begin(), function_namespace0_generated_109_begin(), function_namespace0_generated_10_begin(), function_namespace0_generated_110_begin(), function_namespace0_generated_111_begin(), function_namespace0_generated_112_begin(), function_namespace0_generated_113_begin(), function_namespace0_generated_114_begin(), function_namespace0_generated_115_begin(), function_namespace0_generated_116_begin(), function_namespace0_generated_117_begin(), function_namespace0_generated_118_begin(), function_namespace0_generated_119_begin(), function_namespace0_generated_11_begin(), function_namespace0_generated_120_begin(), function_namespace0_generated_121_begin(), function_namespace0_generated_122_begin(), function_namespace0_generated_123_begin(), function_namespace0_generated_124_begin(), function_namespace0_generated_125_begin(), function_namespace0_generated_126_begin(), function_namespace0_generated_127_begin(), function_namespace0_generated_128_begin(), function_namespace0_generated_129_begin(), function_namespace0_generated_12_begin(), function_namespace0_generated_130_begin(), function_namespace0_generated_131_begin(), function_namespace0_generated_132_begin(), function_namespace0_generated_133_begin(), function_namespace0_generated_134_begin(), function_namespace0_generated_135_begin(), function_namespace0_generated_136_begin(), function_namespace0_generated_137_begin(), function_namespace0_generated_138_begin(), function_namespace0_generated_139_begin(), function_namespace0_generated_13_begin(), function_namespace0_generated_140_begin(), function_namespace0_generated_141_begin(), function_namespace0_generated_142_begin(), function_namespace0_generated_143_begin(), function_namespace0_generated_144_begin(), function_namespace0_generated_145_begin(), function_namespace0_generated_146_begin(), function_namespace0_generated_147_begin(), function_namespace0_generated_148_begin(), function_namespace0_generated_149_begin(), function_namespace0_generated_14_begin(), function_namespace0_generated_150_begin(), function_namespace0_generated_151_begin(), function_namespace0_generated_152_begin(), function_namespace0_generated_153_begin(), function_namespace0_generated_154_begin(), function_namespace0_generated_155_begin(), function_namespace0_generated_156_begin(), function_namespace0_generated_157_begin(), function_namespace0_generated_158_begin(), function_namespace0_generated_159_begin(), function_namespace0_generated_15_begin(), function_namespace0_generated_160_begin(), function_namespace0_generated_161_begin(), function_namespace0_generated_162_begin(), function_namespace0_generated_163_begin(), function_namespace0_generated_164_begin(), function_namespace0_generated_165_begin(), function_namespace0_generated_16_begin(), function_namespace0_generated_17_begin(), function_namespace0_generated_18_begin(), function_namespace0_generated_19_begin(), function_namespace0_generated_1_begin(), function_namespace0_generated_20_begin(), function_namespace0_generated_21_begin(), function_namespace0_generated_22_begin(), function_namespace0_generated_23_begin(), function_namespace0_generated_24_begin(), function_namespace0_generated_25_begin(), function_namespace0_generated_26_begin(), function_namespace0_generated_27_begin(), function_namespace0_generated_28_begin(), function_namespace0_generated_29_begin(), function_namespace0_generated_2_begin(), function_namespace0_generated_30_begin(), function_namespace0_generated_31_begin(), function_namespace0_generated_32_begin(), function_namespace0_generated_33_begin(), function_namespace0_generated_34_begin(), function_namespace0_generated_35_begin(), function_namespace0_generated_36_begin(), function_namespace0_generated_37_begin(), function_namespace0_generated_38_begin(), function_namespace0_generated_39_begin(), function_namespace0_generated_3_begin(), function_namespace0_generated_40_begin(), function_namespace0_generated_41_begin(), function_namespace0_generated_42_begin(), function_namespace0_generated_43_begin(), function_namespace0_generated_44_begin(), function_namespace0_generated_45_begin(), function_namespace0_generated_46_begin(), function_namespace0_generated_47_begin(), function_namespace0_generated_48_begin(), function_namespace0_generated_49_begin(), function_namespace0_generated_4_begin(), function_namespace0_generated_50_begin(), function_namespace0_generated_51_begin(), function_namespace0_generated_52_begin(), function_namespace0_generated_53_begin(), function_namespace0_generated_54_begin(), function_namespace0_generated_55_begin(), function_namespace0_generated_56_begin(), function_namespace0_generated_57_begin(), function_namespace0_generated_58_begin(), function_namespace0_generated_59_begin(), function_namespace0_generated_5_begin(), function_namespace0_generated_60_begin(), function_namespace0_generated_61_begin(), function_namespace0_generated_62_begin(), function_namespace0_generated_63_begin(), function_namespace0_generated_64_begin(), function_namespace0_generated_65_begin(), function_namespace0_generated_66_begin(), function_namespace0_generated_67_begin(), function_namespace0_generated_68_begin(), function_namespace0_generated_69_begin(), function_namespace0_generated_6_begin(), function_namespace0_generated_70_begin(), function_namespace0_generated_71_begin(), function_namespace0_generated_72_begin(), function_namespace0_generated_73_begin(), function_namespace0_generated_74_begin(), function_namespace0_generated_75_begin(), function_namespace0_generated_76_begin(), function_namespace0_generated_77_begin(), function_namespace0_generated_78_begin(), function_namespace0_generated_79_begin(), function_namespace0_generated_7_begin(), function_namespace0_generated_80_begin(), function_namespace0_generated_81_begin(), function_namespace0_generated_82_begin(), function_namespace0_generated_83_begin(), function_namespace0_generated_84_begin(), function_namespace0_generated_85_begin(), function_namespace0_generated_86_begin(), function_namespace0_generated_87_begin(), function_namespace0_generated_88_begin(), function_namespace0_generated_89_begin(), function_namespace0_generated_8_begin(), function_namespace0_generated_90_begin(), function_namespace0_generated_91_begin(), function_namespace0_generated_92_begin(), function_namespace0_generated_93_begin(), function_namespace0_generated_94_begin(), function_namespace0_generated_95_begin(), function_namespace0_generated_96_begin(), function_namespace0_generated_97_begin(), function_namespace0_generated_98_begin(), function_namespace0_generated_99_begin(), function_namespace0_generated_9_begin(), and UA_Server_addMethodNode().
UA_Server_addNode_finish()
UA_StatusCode UA_EXPORT UA_Server_addNode_finish (UA_Server * server, const UA_NodeId nodeId)
Referenced by function_namespace0_generated_0_finish(), function_namespace0_generated_100_finish(), function_namespace0_generated_101_finish(), function_namespace0_generated_102_finish(), function_namespace0_generated_103_finish(), function_namespace0_generated_104_finish(), function_namespace0_generated_105_finish(), function_namespace0_generated_106_finish(), function_namespace0_generated_107_finish(), function_namespace0_generated_108_finish(), function_namespace0_generated_109_finish(), function_namespace0_generated_10_finish(), function_namespace0_generated_110_finish(), function_namespace0_generated_111_finish(), function_namespace0_generated_112_finish(), function_namespace0_generated_113_finish(), function_namespace0_generated_114_finish(), function_namespace0_generated_115_finish(), function_namespace0_generated_116_finish(), function_namespace0_generated_117_finish(), function_namespace0_generated_118_finish(), function_namespace0_generated_119_finish(), function_namespace0_generated_11_finish(), function_namespace0_generated_120_finish(), function_namespace0_generated_121_finish(), function_namespace0_generated_122_finish(), function_namespace0_generated_123_finish(), function_namespace0_generated_124_finish(), function_namespace0_generated_125_finish(), function_namespace0_generated_126_finish(), function_namespace0_generated_127_finish(), function_namespace0_generated_128_finish(), function_namespace0_generated_129_finish(), function_namespace0_generated_12_finish(), function_namespace0_generated_130_finish(), function_namespace0_generated_131_finish(), function_namespace0_generated_132_finish(), function_namespace0_generated_133_finish(), function_namespace0_generated_134_finish(), function_namespace0_generated_135_finish(), function_namespace0_generated_136_finish(), function_namespace0_generated_137_finish(), function_namespace0_generated_138_finish(), function_namespace0_generated_139_finish(), function_namespace0_generated_13_finish(), function_namespace0_generated_140_finish(), function_namespace0_generated_141_finish(), function_namespace0_generated_142_finish(), function_namespace0_generated_143_finish(), function_namespace0_generated_144_finish(), function_namespace0_generated_145_finish(), function_namespace0_generated_146_finish(), function_namespace0_generated_147_finish(), function_namespace0_generated_148_finish(), function_namespace0_generated_149_finish(), function_namespace0_generated_14_finish(), function_namespace0_generated_150_finish(), function_namespace0_generated_151_finish(), function_namespace0_generated_152_finish(), function_namespace0_generated_153_finish(), function_namespace0_generated_154_finish(), function_namespace0_generated_155_finish(), function_namespace0_generated_156_finish(), function_namespace0_generated_157_finish(), function_namespace0_generated_158_finish(), function_namespace0_generated_159_finish(), function_namespace0_generated_15_finish(), function_namespace0_generated_160_finish(), function_namespace0_generated_161_finish(), function_namespace0_generated_162_finish(), function_namespace0_generated_163_finish(), function_namespace0_generated_164_finish(), function_namespace0_generated_165_finish(), function_namespace0_generated_16_finish(), function_namespace0_generated_17_finish(), function_namespace0_generated_18_finish(), function_namespace0_generated_19_finish(), function_namespace0_generated_1_finish(), function_namespace0_generated_20_finish(), function_namespace0_generated_21_finish(), function_namespace0_generated_22_finish(), function_namespace0_generated_23_finish(), function_namespace0_generated_24_finish(), function_namespace0_generated_25_finish(), function_namespace0_generated_26_finish(), function_namespace0_generated_27_finish(), function_namespace0_generated_28_finish(), function_namespace0_generated_29_finish(), function_namespace0_generated_2_finish(), function_namespace0_generated_30_finish(), function_namespace0_generated_31_finish(), function_namespace0_generated_32_finish(), function_namespace0_generated_33_finish(), function_namespace0_generated_34_finish(), function_namespace0_generated_35_finish(), function_namespace0_generated_36_finish(), function_namespace0_generated_37_finish(), function_namespace0_generated_38_finish(), function_namespace0_generated_39_finish(), function_namespace0_generated_3_finish(), function_namespace0_generated_40_finish(), function_namespace0_generated_41_finish(), function_namespace0_generated_42_finish(), function_namespace0_generated_43_finish(), function_namespace0_generated_44_finish(), function_namespace0_generated_45_finish(), function_namespace0_generated_46_finish(), function_namespace0_generated_47_finish(), function_namespace0_generated_48_finish(), function_namespace0_generated_49_finish(), function_namespace0_generated_4_finish(), function_namespace0_generated_50_finish(), function_namespace0_generated_51_finish(), function_namespace0_generated_52_finish(), function_namespace0_generated_53_finish(), function_namespace0_generated_54_finish(), function_namespace0_generated_55_finish(), function_namespace0_generated_56_finish(), function_namespace0_generated_57_finish(), function_namespace0_generated_58_finish(), function_namespace0_generated_59_finish(), function_namespace0_generated_5_finish(), function_namespace0_generated_60_finish(), function_namespace0_generated_61_finish(), function_namespace0_generated_62_finish(), function_namespace0_generated_63_finish(), function_namespace0_generated_64_finish(), function_namespace0_generated_65_finish(), function_namespace0_generated_66_finish(), function_namespace0_generated_67_finish(), function_namespace0_generated_68_finish(), function_namespace0_generated_69_finish(), function_namespace0_generated_6_finish(), function_namespace0_generated_70_finish(), function_namespace0_generated_71_finish(), function_namespace0_generated_72_finish(), function_namespace0_generated_73_finish(), function_namespace0_generated_74_finish(), function_namespace0_generated_75_finish(), function_namespace0_generated_76_finish(), function_namespace0_generated_77_finish(), function_namespace0_generated_78_finish(), function_namespace0_generated_79_finish(), function_namespace0_generated_7_finish(), function_namespace0_generated_80_finish(), function_namespace0_generated_81_finish(), function_namespace0_generated_82_finish(), function_namespace0_generated_83_finish(), function_namespace0_generated_84_finish(), function_namespace0_generated_85_finish(), function_namespace0_generated_86_finish(), function_namespace0_generated_87_finish(), function_namespace0_generated_88_finish(), function_namespace0_generated_89_finish(), function_namespace0_generated_8_finish(), function_namespace0_generated_90_finish(), function_namespace0_generated_91_finish(), function_namespace0_generated_92_finish(), function_namespace0_generated_93_finish(), function_namespace0_generated_94_finish(), function_namespace0_generated_95_finish(), function_namespace0_generated_97_finish(), function_namespace0_generated_98_finish(), function_namespace0_generated_99_finish(), function_namespace0_generated_9_finish(), and UA_Server_addMethodNode().
UA_Server_addObjectNode()
static UA_INLINE UA_StatusCode UA_Server_addObjectNode (UA_Server * server, const UA_NodeId requestedNewNodeId, const UA_NodeId parentNodeId, const UA_NodeId referenceTypeId, const UA_QualifiedName browseName, const UA_NodeId typeDefinition, const UA_ObjectAttributes attr, void * nodeContext, UA_NodeId * outNewNodeId) static
Definition at line 1045 of file server.h.
References __UA_Server_addNode(), UA_NODECLASS_OBJECT, and UA_TYPES.
Referenced by addDeviceNode(), and addGroupNode().
UA_Server_addObjectTypeNode()
static UA_INLINE UA_StatusCode UA_Server_addObjectTypeNode (UA_Server * server, const UA_NodeId requestedNewNodeId, const UA_NodeId parentNodeId, const UA_NodeId referenceTypeId, const UA_QualifiedName browseName, const UA_ObjectTypeAttributes attr, void * nodeContext, UA_NodeId * outNewNodeId) static
Definition at line 1060 of file server.h.
References __UA_Server_addNode(), UA_NODECLASS_OBJECTTYPE, UA_NODEID_NULL, and UA_TYPES.
UA_Server_addPeriodicServerRegisterCallback()
UA_StatusCode UA_EXPORT UA_Server_addPeriodicServerRegisterCallback (UA_Server * server, struct UA_Client * client, const char * discoveryServerUrl, UA_Double intervalMs, UA_Double delayFirstRegisterMs, UA_UInt64 * periodicCallbackId)
UA_Server_addReference()
UA_StatusCode UA_EXPORT UA_Server_addReference (UA_Server * server, const UA_NodeId sourceId, const UA_NodeId refTypeId, const UA_ExpandedNodeId targetId, UA_Boolean isForward)
Reference Management
Referenced by function_namespace0_generated_133_begin(), function_namespace0_generated_135_begin(), function_namespace0_generated_137_begin(), function_namespace0_generated_138_begin(), function_namespace0_generated_139_begin(), function_namespace0_generated_140_begin(), function_namespace0_generated_141_begin(), function_namespace0_generated_142_begin(), function_namespace0_generated_143_begin(), function_namespace0_generated_144_begin(), function_namespace0_generated_146_begin(), function_namespace0_generated_69_begin(), function_namespace0_generated_70_begin(), function_namespace0_generated_72_begin(), function_namespace0_generated_74_begin(), function_namespace0_generated_75_begin(), function_namespace0_generated_78_begin(), function_namespace0_generated_81_begin(), function_namespace0_generated_82_begin(), function_namespace0_generated_83_begin(), function_namespace0_generated_84_begin(), function_namespace0_generated_85_begin(), function_namespace0_generated_86_begin(), function_namespace0_generated_87_begin(), function_namespace0_generated_88_begin(), function_namespace0_generated_89_begin(), function_namespace0_generated_90_begin(), function_namespace0_generated_91_begin(), function_namespace0_generated_92_begin(), and UA_Server_addMethodNode().
UA_Server_addReferenceTypeNode()
static UA_INLINE UA_StatusCode UA_Server_addReferenceTypeNode (UA_Server * server, const UA_NodeId requestedNewNodeId, const UA_NodeId parentNodeId, const UA_NodeId referenceTypeId, const UA_QualifiedName browseName, const UA_ReferenceTypeAttributes attr, void * nodeContext, UA_NodeId * outNewNodeId) static
Definition at line 1088 of file server.h.
References __UA_Server_addNode(), UA_NODECLASS_REFERENCETYPE, UA_NODEID_NULL, and UA_TYPES.
UA_Server_addRepeatedCallback()
UA_StatusCode UA_EXPORT UA_Server_addRepeatedCallback (UA_Server * server, UA_ServerCallback callback, void * data, UA_Double interval_ms, UA_UInt64 * callbackId)
UA_Server_addTimedCallback()
UA_StatusCode UA_EXPORT UA_Server_addTimedCallback (UA_Server * server, UA_ServerCallback callback, void * data, UA_DateTime date, UA_UInt64 * callbackId)
UA_Server_addVariableNode()
static UA_INLINE UA_StatusCode UA_Server_addVariableNode (UA_Server * server, const UA_NodeId requestedNewNodeId, const UA_NodeId parentNodeId, const UA_NodeId referenceTypeId, const UA_QualifiedName browseName, const UA_NodeId typeDefinition, const UA_VariableAttributes attr, void * nodeContext, UA_NodeId * outNewNodeId) static
Definition at line 1013 of file server.h.
References __UA_Server_addNode(), UA_NODECLASS_VARIABLE, and UA_TYPES.
Referenced by addMetricNode().
UA_Server_addVariableTypeNode()
static UA_INLINE UA_StatusCode UA_Server_addVariableTypeNode (UA_Server * server, const UA_NodeId requestedNewNodeId, const UA_NodeId parentNodeId, const UA_NodeId referenceTypeId, const UA_QualifiedName browseName, const UA_NodeId typeDefinition, const UA_VariableTypeAttributes attr, void * nodeContext, UA_NodeId * outNewNodeId) static
Definition at line 1028 of file server.h.
References __UA_Server_addNode(), UA_NODECLASS_VARIABLETYPE, and UA_TYPES.
UA_Server_addViewNode()
static UA_INLINE UA_StatusCode UA_Server_addViewNode (UA_Server * server, const UA_NodeId requestedNewNodeId, const UA_NodeId parentNodeId, const UA_NodeId referenceTypeId, const UA_QualifiedName browseName, const UA_ViewAttributes attr, void * nodeContext, UA_NodeId * outNewNodeId) static
Definition at line 1074 of file server.h.
References __UA_Server_addNode(), UA_NODECLASS_VIEW, UA_NODEID_NULL, and UA_TYPES.
UA_Server_browse()
UA_BrowseResult UA_EXPORT UA_Server_browse (UA_Server * server, UA_UInt32 maxReferences, const UA_BrowseDescription * bd)
Browsing
Referenced by UA_Server_writeExecutable().
UA_Server_browseNext()
UA_BrowseResult UA_EXPORT UA_Server_browseNext (UA_Server * server, UA_Boolean releaseContinuationPoint, const UA_ByteString * continuationPoint)
Referenced by UA_Server_writeExecutable().
UA_Server_browseRecursive()
UA_StatusCode UA_EXPORT UA_Server_browseRecursive (UA_Server * server, const UA_BrowseDescription * bd, size_t * resultsSize, UA_ExpandedNodeId * results)
Referenced by UA_Server_writeExecutable().
UA_Server_browseSimplifiedBrowsePath()
UA_BrowsePathResult UA_EXPORT UA_Server_browseSimplifiedBrowsePath (UA_Server * server, const UA_NodeId origin, size_t browsePathSize, const UA_QualifiedName * browsePath)
Referenced by UA_Server_writeExecutable().
UA_Server_call()
UA_CallMethodResult UA_EXPORT UA_Server_call (UA_Server * server, const UA_CallMethodRequest * request)
UA_Server_changeRepeatedCallbackInterval()
UA_StatusCode UA_EXPORT UA_Server_changeRepeatedCallbackInterval (UA_Server * server, UA_UInt64 callbackId, UA_Double interval_ms)
UA_Server_createDataChangeMonitoredItem()
UA_MonitoredItemCreateResult UA_EXPORT UA_Server_createDataChangeMonitoredItem (UA_Server * server, UA_TimestampsToReturn timestampsToReturn, const UA_MonitoredItemCreateRequest item, void * monitoredItemContext, UA_Server_DataChangeNotificationCallback callback)
UA_Server_createEvent()
UA_StatusCode UA_EXPORT UA_Server_createEvent (UA_Server * server, const UA_NodeId eventType, UA_NodeId * outNodeId)
Referenced by UA_Server_addMethodNode().
UA_Server_delete()
void UA_EXPORT UA_Server_delete (UA_Server * server)
Referenced by stopServer().
UA_Server_deleteMonitoredItem()
UA_StatusCode UA_EXPORT UA_Server_deleteMonitoredItem (UA_Server * server, UA_UInt32 monitoredItemId)
UA_Server_deleteNode()
UA_StatusCode UA_EXPORT UA_Server_deleteNode (UA_Server * server, const UA_NodeId nodeId, UA_Boolean deleteReferences)
Referenced by UA_Server_addMethodNode().
UA_Server_deleteReference()
UA_StatusCode UA_EXPORT UA_Server_deleteReference (UA_Server * server, const UA_NodeId sourceNodeId, const UA_NodeId referenceTypeId, UA_Boolean isForward, const UA_ExpandedNodeId targetNodeId, UA_Boolean deleteBidirectional)
Referenced by UA_Server_addMethodNode().
UA_Server_forEachChildNodeCall()
UA_StatusCode UA_EXPORT UA_Server_forEachChildNodeCall (UA_Server * server, UA_NodeId parentNodeId, UA_NodeIteratorCallback callback, void * handle)
UA_Server_getConfig()
UA_ServerConfig UA_EXPORT* UA_Server_getConfig (UA_Server * server)
Referenced by startServer().
UA_Server_getNamespaceByName()
UA_StatusCode UA_EXPORT UA_Server_getNamespaceByName (UA_Server * server, const UA_String namespaceUri, size_t * foundIndex)
Referenced by UA_Server_addMethodNode().
UA_Server_getNodeContext()
UA_StatusCode UA_EXPORT UA_Server_getNodeContext (UA_Server * server, UA_NodeId nodeId, void ** nodeContext)
UA_Server_new()
UA_Server UA_EXPORT* UA_Server_new (void)
.. _server:
Server
.. include:: server_config.rst
.. _server-lifecycle:
Server Lifecycle
Referenced by startServer().
UA_Server_newWithConfig()
UA_Server UA_EXPORT* UA_Server_newWithConfig (const UA_ServerConfig * config)
UA_Server_read()
UA_DataValue UA_EXPORT UA_Server_read (UA_Server * server, const UA_ReadValueId * item, UA_TimestampsToReturn timestamps)
Reading and Writing Node Attributes
The functions for reading and writing node attributes call the regular read and write service in the background that are also used over the network.
The following attributes cannot be read, since the local "admin" user always has full rights.
UserWriteMask
UserAccessLevel
UserExecutable
UA_Server_readAccessLevel()
static UA_INLINE UA_StatusCode UA_Server_readAccessLevel (UA_Server * server, const UA_NodeId nodeId, UA_Byte * outAccessLevel) static
Definition at line 279 of file server.h.
References __UA_Server_read(), and UA_ATTRIBUTEID_ACCESSLEVEL.
UA_Server_readArrayDimensions()
static UA_INLINE UA_StatusCode UA_Server_readArrayDimensions (UA_Server * server, const UA_NodeId nodeId, UA_Variant * outArrayDimensions) static
Definition at line 272 of file server.h.
References __UA_Server_read(), and UA_ATTRIBUTEID_ARRAYDIMENSIONS.
UA_Server_readBrowseName()
static UA_INLINE UA_StatusCode UA_Server_readBrowseName (UA_Server * server, const UA_NodeId nodeId, UA_QualifiedName * outBrowseName) static
Definition at line 188 of file server.h.
References __UA_Server_read(), and UA_ATTRIBUTEID_BROWSENAME.
UA_Server_readContainsNoLoop()
static UA_INLINE UA_StatusCode UA_Server_readContainsNoLoop (UA_Server * server, const UA_NodeId nodeId, UA_Boolean * outContainsNoLoops) static
Definition at line 237 of file server.h.
References __UA_Server_read(), and UA_ATTRIBUTEID_CONTAINSNOLOOPS.
UA_Server_readDataType()
static UA_INLINE UA_StatusCode UA_Server_readDataType (UA_Server * server, const UA_NodeId nodeId, UA_NodeId * outDataType) static
Definition at line 257 of file server.h.
References __UA_Server_read(), and UA_ATTRIBUTEID_DATATYPE.
UA_Server_readDescription()
static UA_INLINE UA_StatusCode UA_Server_readDescription (UA_Server * server, const UA_NodeId nodeId, UA_LocalizedText * outDescription) static
Definition at line 202 of file server.h.
References __UA_Server_read(), and UA_ATTRIBUTEID_DESCRIPTION.
UA_Server_readDisplayName()
static UA_INLINE UA_StatusCode UA_Server_readDisplayName (UA_Server * server, const UA_NodeId nodeId, UA_LocalizedText * outDisplayName) static
Definition at line 195 of file server.h.
References __UA_Server_read(), and UA_ATTRIBUTEID_DISPLAYNAME.
UA_Server_readEventNotifier()
static UA_INLINE UA_StatusCode UA_Server_readEventNotifier (UA_Server * server, const UA_NodeId nodeId, UA_Byte * outEventNotifier) static
Definition at line 244 of file server.h.
References __UA_Server_read(), and UA_ATTRIBUTEID_EVENTNOTIFIER.
UA_Server_readExecutable()
static UA_INLINE UA_StatusCode UA_Server_readExecutable (UA_Server * server, const UA_NodeId nodeId, UA_Boolean * outExecutable) static
Definition at line 301 of file server.h.
References __UA_Server_read(), __UA_Server_write(), UA_ATTRIBUTEID_EXECUTABLE, and UA_Server_write().
UA_Server_readHistorizing()
static UA_INLINE UA_StatusCode UA_Server_readHistorizing (UA_Server * server, const UA_NodeId nodeId, UA_Boolean * outHistorizing) static
Definition at line 294 of file server.h.
References __UA_Server_read(), and UA_ATTRIBUTEID_HISTORIZING.
UA_Server_readInverseName()
static UA_INLINE UA_StatusCode UA_Server_readInverseName (UA_Server * server, const UA_NodeId nodeId, UA_LocalizedText * outInverseName) static
Definition at line 230 of file server.h.
References __UA_Server_read(), and UA_ATTRIBUTEID_INVERSENAME.
UA_Server_readIsAbstract()
static UA_INLINE UA_StatusCode UA_Server_readIsAbstract (UA_Server * server, const UA_NodeId nodeId, UA_Boolean * outIsAbstract) static
Definition at line 216 of file server.h.
References __UA_Server_read(), and UA_ATTRIBUTEID_ISABSTRACT.
UA_Server_readMinimumSamplingInterval()
static UA_INLINE UA_StatusCode UA_Server_readMinimumSamplingInterval (UA_Server * server, const UA_NodeId nodeId, UA_Double * outMinimumSamplingInterval) static
Definition at line 286 of file server.h.
References __UA_Server_read(), and UA_ATTRIBUTEID_MINIMUMSAMPLINGINTERVAL.
UA_Server_readNodeClass()
static UA_INLINE UA_StatusCode UA_Server_readNodeClass (UA_Server * server, const UA_NodeId nodeId, UA_NodeClass * outNodeClass) static
Definition at line 181 of file server.h.
References __UA_Server_read(), and UA_ATTRIBUTEID_NODECLASS.
UA_Server_readNodeId()
static UA_INLINE UA_StatusCode UA_Server_readNodeId (UA_Server * server, const UA_NodeId nodeId, UA_NodeId * outNodeId) static
Definition at line 175 of file server.h.
References __UA_Server_read(), and UA_ATTRIBUTEID_NODEID.
UA_Server_readObjectProperty()
UA_StatusCode UA_EXPORT UA_Server_readObjectProperty (UA_Server * server, const UA_NodeId objectId, const UA_QualifiedName propertyName, UA_Variant * value)
UA_Server_readSymmetric()
static UA_INLINE UA_StatusCode UA_Server_readSymmetric (UA_Server * server, const UA_NodeId nodeId, UA_Boolean * outSymmetric) static
Definition at line 223 of file server.h.
References __UA_Server_read(), and UA_ATTRIBUTEID_SYMMETRIC.
UA_Server_readValue()
static UA_INLINE UA_StatusCode UA_Server_readValue (UA_Server * server, const UA_NodeId nodeId, UA_Variant * outValue) static
Definition at line 251 of file server.h.
References __UA_Server_read(), and UA_ATTRIBUTEID_VALUE.
UA_Server_readValueRank()
static UA_INLINE UA_StatusCode UA_Server_readValueRank (UA_Server * server, const UA_NodeId nodeId, UA_Int32 * outValueRank) static
Definition at line 264 of file server.h.
References __UA_Server_read(), and UA_ATTRIBUTEID_VALUERANK.
UA_Server_readWriteMask()
static UA_INLINE UA_StatusCode UA_Server_readWriteMask (UA_Server * server, const UA_NodeId nodeId, UA_UInt32 * outWriteMask) static
Definition at line 209 of file server.h.
References __UA_Server_read(), and UA_ATTRIBUTEID_WRITEMASK.
UA_Server_register_discovery()
UA_StatusCode UA_EXPORT UA_Server_register_discovery (UA_Server * server, struct UA_Client * client, const char * semaphoreFilePath)
Discovery
UA_Server_removeCallback()
void UA_EXPORT UA_Server_removeCallback (UA_Server * server, UA_UInt64 callbackId)
UA_Server_run()
UA_StatusCode UA_EXPORT UA_Server_run (UA_Server * server, const volatile UA_Boolean * running)
Referenced by serverThread().
UA_Server_run_iterate()
UA_UInt16 UA_EXPORT UA_Server_run_iterate (UA_Server * server, UA_Boolean waitInternal)
UA_Server_run_shutdown()
UA_StatusCode UA_EXPORT UA_Server_run_shutdown (UA_Server * server)
Referenced by stopServer().
UA_Server_run_startup()
UA_StatusCode UA_EXPORT UA_Server_run_startup (UA_Server * server)
UA_Server_setMethodNode_callback()
UA_StatusCode UA_EXPORT UA_Server_setMethodNode_callback (UA_Server * server, const UA_NodeId methodNodeId, UA_MethodCallback methodCallback)
UA_Server_setNodeContext()
UA_StatusCode UA_EXPORT UA_Server_setNodeContext (UA_Server * server, UA_NodeId nodeId, void * nodeContext)
UA_Server_setNodeTypeLifecycle()
UA_StatusCode UA_EXPORT UA_Server_setNodeTypeLifecycle (UA_Server * server, UA_NodeId nodeId, UA_NodeTypeLifecycle lifecycle)
UA_Server_setRegisterServerCallback()
void UA_EXPORT UA_Server_setRegisterServerCallback (UA_Server * server, UA_Server_registerServerCallback cb, void * data)
UA_Server_setServerOnNetworkCallback()
void UA_EXPORT UA_Server_setServerOnNetworkCallback (UA_Server * server, UA_Server_serverOnNetworkCallback cb, void * data)
UA_Server_setVariableNode_dataSource()
UA_StatusCode UA_EXPORT UA_Server_setVariableNode_dataSource (UA_Server * server, const UA_NodeId nodeId, const UA_DataSource dataSource)
UA_Server_setVariableNode_valueCallback()
UA_StatusCode UA_EXPORT UA_Server_setVariableNode_valueCallback (UA_Server * server, const UA_NodeId nodeId, const UA_ValueCallback callback)
UA_Server_translateBrowsePathToNodeIds()
UA_BrowsePathResult UA_EXPORT UA_Server_translateBrowsePathToNodeIds (UA_Server * server, const UA_BrowsePath * browsePath)
Referenced by UA_Server_writeExecutable().
UA_Server_triggerEvent()
UA_StatusCode UA_EXPORT UA_Server_triggerEvent (UA_Server * server, const UA_NodeId eventNodeId, const UA_NodeId originId, UA_ByteString * outEventId, const UA_Boolean deleteEventNode)
Referenced by UA_Server_addMethodNode().
UA_Server_unregister_discovery()
UA_StatusCode UA_EXPORT UA_Server_unregister_discovery (UA_Server * server, struct UA_Client * client)
UA_Server_updateCertificate()
UA_StatusCode UA_EXPORT UA_Server_updateCertificate (UA_Server * server, const UA_ByteString * oldCertificate, const UA_ByteString * newCertificate, const UA_ByteString * newPrivateKey, UA_Boolean closeSessions, UA_Boolean closeSecureChannels)
Referenced by UA_Server_addMethodNode().
UA_Server_write()
UA_StatusCode UA_EXPORT UA_Server_write (UA_Server * server, const UA_WriteValue * value)
The following node attributes cannot be changed once a node has been created:
NodeClass
NodeId
Symmetric
ContainsNoLoop
The following attributes cannot be written from the server, as they are specific to the different users and set by the access control callback:
UserWriteMask
UserAccessLevel
UserExecutable
Referenced by UA_Server_readExecutable().
UA_Server_writeAccessLevel()
static UA_INLINE UA_StatusCode UA_Server_writeAccessLevel (UA_Server * server, const UA_NodeId nodeId, const UA_Byte accessLevel) static
Definition at line 421 of file server.h.
References __UA_Server_write(), UA_ATTRIBUTEID_ACCESSLEVEL, and UA_TYPES.
UA_Server_writeArrayDimensions()
static UA_INLINE UA_StatusCode UA_Server_writeArrayDimensions (UA_Server * server, const UA_NodeId nodeId, const UA_Variant arrayDimensions) static
Definition at line 414 of file server.h.
References __UA_Server_write(), UA_ATTRIBUTEID_ARRAYDIMENSIONS, and UA_TYPES.
UA_Server_writeBrowseName()
static UA_INLINE UA_StatusCode UA_Server_writeBrowseName (UA_Server * server, const UA_NodeId nodeId, const UA_QualifiedName browseName) static
Definition at line 344 of file server.h.
References __UA_Server_write(), UA_ATTRIBUTEID_BROWSENAME, and UA_TYPES.
UA_Server_writeDataType()
static UA_INLINE UA_StatusCode UA_Server_writeDataType (UA_Server * server, const UA_NodeId nodeId, const UA_NodeId dataType) static
Definition at line 400 of file server.h.
References __UA_Server_write(), UA_ATTRIBUTEID_DATATYPE, and UA_TYPES.
UA_Server_writeDescription()
static UA_INLINE UA_StatusCode UA_Server_writeDescription (UA_Server * server, const UA_NodeId nodeId, const UA_LocalizedText description) static
Definition at line 358 of file server.h.
References __UA_Server_write(), UA_ATTRIBUTEID_DESCRIPTION, and UA_TYPES.
UA_Server_writeDisplayName()
static UA_INLINE UA_StatusCode UA_Server_writeDisplayName (UA_Server * server, const UA_NodeId nodeId, const UA_LocalizedText displayName) static
Definition at line 351 of file server.h.
References __UA_Server_write(), UA_ATTRIBUTEID_DISPLAYNAME, and UA_TYPES.
UA_Server_writeEventNotifier()
static UA_INLINE UA_StatusCode UA_Server_writeEventNotifier (UA_Server * server, const UA_NodeId nodeId, const UA_Byte eventNotifier) static
Definition at line 386 of file server.h.
References __UA_Server_write(), UA_ATTRIBUTEID_EVENTNOTIFIER, and UA_TYPES.
UA_Server_writeExecutable()
static UA_INLINE UA_StatusCode UA_Server_writeExecutable (UA_Server * server, const UA_NodeId nodeId, const UA_Boolean executable) static
Definition at line 446 of file server.h.
References __UA_Server_write(), UA_ATTRIBUTEID_EXECUTABLE, UA_Server_browse(), UA_Server_browseNext(), UA_Server_browseRecursive(), UA_Server_browseSimplifiedBrowsePath(), UA_Server_translateBrowsePathToNodeIds(), and UA_TYPES.
UA_Server_writeHistorizing()
static UA_INLINE UA_StatusCode UA_Server_writeHistorizing (UA_Server * server, const UA_NodeId nodeId, const UA_Boolean historizing) static
Definition at line 437 of file server.h.
References __UA_Server_write(), UA_ATTRIBUTEID_HISTORIZING, and UA_TYPES.
UA_Server_writeInverseName()
static UA_INLINE UA_StatusCode UA_Server_writeInverseName (UA_Server * server, const UA_NodeId nodeId, const UA_LocalizedText inverseName) static
Definition at line 379 of file server.h.
References __UA_Server_write(), UA_ATTRIBUTEID_INVERSENAME, and UA_TYPES.
UA_Server_writeIsAbstract()
static UA_INLINE UA_StatusCode UA_Server_writeIsAbstract (UA_Server * server, const UA_NodeId nodeId, const UA_Boolean isAbstract) static
Definition at line 372 of file server.h.
References __UA_Server_write(), UA_ATTRIBUTEID_ISABSTRACT, and UA_TYPES.
UA_Server_writeMinimumSamplingInterval()
static UA_INLINE UA_StatusCode UA_Server_writeMinimumSamplingInterval (UA_Server * server, const UA_NodeId nodeId, const UA_Double miniumSamplingInterval) static
Definition at line 428 of file server.h.
References __UA_Server_write(), UA_ATTRIBUTEID_MINIMUMSAMPLINGINTERVAL, and UA_TYPES.
UA_Server_writeObjectProperty()
UA_StatusCode UA_EXPORT UA_Server_writeObjectProperty (UA_Server * server, const UA_NodeId objectId, const UA_QualifiedName propertyName, const UA_Variant value)
.. _object-interaction:
Interacting with Objects
Objects in the information model are represented as ObjectNodes. Some convenience functions are provided to simplify the interaction with objects.
UA_Server_writeObjectProperty_scalar()
UA_StatusCode UA_EXPORT UA_Server_writeObjectProperty_scalar (UA_Server * server, const UA_NodeId objectId, const UA_QualifiedName propertyName, const void * value, const UA_DataType * type)
UA_Server_writeValue()
static UA_INLINE UA_StatusCode UA_Server_writeValue (UA_Server * server, const UA_NodeId nodeId, const UA_Variant value) static
Definition at line 393 of file server.h.
References __UA_Server_write(), UA_ATTRIBUTEID_VALUE, and UA_TYPES.
UA_Server_writeValueRank()
static UA_INLINE UA_StatusCode UA_Server_writeValueRank (UA_Server * server, const UA_NodeId nodeId, const UA_Int32 valueRank) static
Definition at line 407 of file server.h.
References __UA_Server_write(), UA_ATTRIBUTEID_VALUERANK, and UA_TYPES.
UA_Server_writeWriteMask()
static UA_INLINE UA_StatusCode UA_Server_writeWriteMask (UA_Server * server, const UA_NodeId nodeId, const UA_UInt32 writeMask) static
Definition at line 365 of file server.h.
References __UA_Server_write(), UA_ATTRIBUTEID_WRITEMASK, and UA_TYPES.
Variable Documentation
UA_DataTypeAttributes_default
UA_EXPORT const UA_DataTypeAttributes UA_DataTypeAttributes_default
UA_MethodAttributes_default
UA_EXPORT const UA_MethodAttributes UA_MethodAttributes_default
UA_ObjectAttributes_default
UA_EXPORT const UA_ObjectAttributes UA_ObjectAttributes_default
UA_ObjectTypeAttributes_default
UA_EXPORT const UA_ObjectTypeAttributes UA_ObjectTypeAttributes_default
UA_ReferenceTypeAttributes_default
UA_EXPORT const UA_ReferenceTypeAttributes UA_ReferenceTypeAttributes_default
UA_VariableAttributes_default
UA_EXPORT const UA_VariableAttributes UA_VariableAttributes_default
UA_VariableTypeAttributes_default
UA_EXPORT const UA_VariableTypeAttributes UA_VariableTypeAttributes_default
UA_ViewAttributes_default
UA_EXPORT const UA_ViewAttributes UA_ViewAttributes_default