Project Template: Opc.Ua.EndpointDescriptionCollection Class Reference
Opc.Ua.EndpointDescriptionCollection Class Reference
A collection of EndpointDescription objects.
Public Member Functions
EndpointDescriptionCollection ()
Initializes the collection with default values.
EndpointDescriptionCollection (int capacity)
Initializes the collection with an initial capacity.
EndpointDescriptionCollection (IEnumerable< EndpointDescription > collection)
Initializes the collection with another collection.
object Clone ()
Creates a deep copy of the collection.
new object MemberwiseClone ()
Static Public Member Functions
static implicit operator EndpointDescriptionCollection (EndpointDescription[] values)
Converts an array to a collection.
static operator EndpointDescription[] (EndpointDescriptionCollection values)
Converts a collection to an array.
Detailed Description
A collection of EndpointDescription objects.
<exclude>
Definition at line 26082 of file Opc.Ua.DataTypes.cs.
Constructor & Destructor Documentation
EndpointDescriptionCollection() [1/3]
Opc.Ua.EndpointDescriptionCollection.EndpointDescriptionCollection () inline
Initializes the collection with default values.
Definition at line 26091 of file Opc.Ua.DataTypes.cs.
EndpointDescriptionCollection() [2/3]
Opc.Ua.EndpointDescriptionCollection.EndpointDescriptionCollection (int capacity) inline
Initializes the collection with an initial capacity.
Definition at line 26096 of file Opc.Ua.DataTypes.cs.
EndpointDescriptionCollection() [3/3]
Opc.Ua.EndpointDescriptionCollection.EndpointDescriptionCollection (IEnumerable< EndpointDescription > collection) inline
Initializes the collection with another collection.
Definition at line 26101 of file Opc.Ua.DataTypes.cs.
Member Function Documentation
Clone()
object Opc.Ua.EndpointDescriptionCollection.Clone () inline
Creates a deep copy of the collection.
Definition at line 26137 of file Opc.Ua.DataTypes.cs.
Referenced by Opc.Ua.PubSubGroupDataType.MemberwiseClone(), Opc.Ua.DataSetReaderDataType.MemberwiseClone(), Opc.Ua.GetEndpointsResponse.MemberwiseClone(), and Opc.Ua.CreateSessionResponse.MemberwiseClone().
MemberwiseClone()
new object Opc.Ua.EndpointDescriptionCollection.MemberwiseClone () inline
Definition at line 26145 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
operator EndpointDescription[]()
static Opc.Ua.EndpointDescriptionCollection.operator EndpointDescription[] (EndpointDescriptionCollection values) inline explicit static
Converts a collection to an array.
Definition at line 26121 of file Opc.Ua.DataTypes.cs.
operator EndpointDescriptionCollection()
static implicit Opc.Ua.EndpointDescriptionCollection.operator EndpointDescriptionCollection (EndpointDescription [] values) inline static
Converts an array to a collection.
Definition at line 26108 of file Opc.Ua.DataTypes.cs.
The documentation for this class was generated from the following file:
Opc.Ua.DataTypes.cs