Project Template: Opc.Ua.ReadEventDetails Class Reference
Opc.Ua.ReadEventDetails Class Reference
Public Member Functions
ReadEventDetails ()
The default constructor.
override void Encode (IEncoder encoder)
override void Decode (IDecoder decoder)
override bool IsEqual (IEncodeable encodeable)
override object Clone ()
new object MemberwiseClone ()
Public Member Functions inherited from Opc.Ua.HistoryReadDetails
HistoryReadDetails ()
The default constructor.
new object MemberwiseClone ()
Properties
uint NumValuesPerNode [get, set]
DateTime StartTime [get, set]
DateTime EndTime [get, set]
EventFilter Filter [get, set]
override ExpandedNodeId TypeId [get]
override ExpandedNodeId BinaryEncodingId [get]
override ExpandedNodeId XmlEncodingId [get]
Properties inherited from Opc.Ua.HistoryReadDetails
virtual ExpandedNodeId TypeId [get]
virtual ExpandedNodeId BinaryEncodingId [get]
virtual ExpandedNodeId XmlEncodingId [get]
Detailed Description
<exclude>
Definition at line 46421 of file Opc.Ua.DataTypes.cs.
Constructor & Destructor Documentation
ReadEventDetails()
Opc.Ua.ReadEventDetails.ReadEventDetails () inline
The default constructor.
Definition at line 46427 of file Opc.Ua.DataTypes.cs.
Member Function Documentation
Clone()
override object Opc.Ua.ReadEventDetails.Clone () inline virtual
Reimplemented from Opc.Ua.HistoryReadDetails.
Definition at line 46576 of file Opc.Ua.DataTypes.cs.
Decode()
override void Opc.Ua.ReadEventDetails.Decode (IDecoder decoder) inline virtual
Reimplemented from Opc.Ua.HistoryReadDetails.
Definition at line 46536 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
Encode()
override void Opc.Ua.ReadEventDetails.Encode (IEncoder encoder) inline virtual
Reimplemented from Opc.Ua.HistoryReadDetails.
Definition at line 46521 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
IsEqual()
override bool Opc.Ua.ReadEventDetails.IsEqual (IEncodeable encodeable) inline virtual
Reimplemented from Opc.Ua.HistoryReadDetails.
Definition at line 46551 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Object.
MemberwiseClone()
new object Opc.Ua.ReadEventDetails.MemberwiseClone () inline
Definition at line 46583 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.EventFilter.Clone(), Opc.Ua.ReadEventDetails.MemberwiseClone(), and Opc.Ua.Namespaces.OpcUaXsd.
Referenced by Opc.Ua.ReadEventDetails.MemberwiseClone().
Property Documentation
BinaryEncodingId
override ExpandedNodeId Opc.Ua.ReadEventDetails.BinaryEncodingId get
Definition at line 46510 of file Opc.Ua.DataTypes.cs.
EndTime
DateTime Opc.Ua.ReadEventDetails.EndTime get set
Definition at line 46473 of file Opc.Ua.DataTypes.cs.
Filter
EventFilter Opc.Ua.ReadEventDetails.Filter get set
Definition at line 46483 of file Opc.Ua.DataTypes.cs.
NumValuesPerNode
uint Opc.Ua.ReadEventDetails.NumValuesPerNode get set
Definition at line 46457 of file Opc.Ua.DataTypes.cs.
StartTime
DateTime Opc.Ua.ReadEventDetails.StartTime get set
Definition at line 46465 of file Opc.Ua.DataTypes.cs.
TypeId
override ExpandedNodeId Opc.Ua.ReadEventDetails.TypeId get
Definition at line 46504 of file Opc.Ua.DataTypes.cs.
XmlEncodingId
override ExpandedNodeId Opc.Ua.ReadEventDetails.XmlEncodingId get
Definition at line 46516 of file Opc.Ua.DataTypes.cs.
The documentation for this class was generated from the following file:
Opc.Ua.DataTypes.cs