Project Template: client.h File Reference
client.h File Reference
Typedefs
typedef void(* UA_ClientAsyncServiceCallback) (UA_Client *client, void *userdata, UA_UInt32 requestId, void *response)
typedef void(* UA_ClientCallback) (UA_Client *client, void *data)
Functions
_UA_BEGIN_DECLS UA_Client UA_EXPORT * UA_Client_new (void)
UA_ClientState UA_EXPORT UA_Client_getState (UA_Client *client)
UA_EXPORT UA_ClientConfig * UA_Client_getConfig (UA_Client *client)
static UA_INLINE void * UA_Client_getContext (UA_Client *client)
void UA_EXPORT UA_Client_reset (UA_Client *client)
void UA_EXPORT UA_Client_delete (UA_Client *client)
UA_StatusCode UA_EXPORT UA_Client_connect (UA_Client *client, const char *endpointUrl)
UA_StatusCode UA_EXPORT UA_Client_connect_async (UA_Client *client, const char *endpointUrl, UA_ClientAsyncServiceCallback callback, void *userdata)
UA_StatusCode UA_EXPORT UA_Client_connect_noSession (UA_Client *client, const char *endpointUrl)
UA_StatusCode UA_EXPORT UA_Client_connect_username (UA_Client *client, const char *endpointUrl, const char *username, const char *password)
UA_StatusCode UA_EXPORT UA_Client_disconnect (UA_Client *client)
UA_StatusCode UA_EXPORT UA_Client_disconnect_async (UA_Client *client, UA_UInt32 *requestId)
static UA_DEPRECATED UA_INLINE UA_StatusCode UA_Client_close (UA_Client *client)
UA_StatusCode UA_EXPORT UA_Client_getEndpoints (UA_Client *client, const char *serverUrl, size_t *endpointDescriptionsSize, UA_EndpointDescription **endpointDescriptions)
UA_StatusCode UA_EXPORT UA_Client_findServers (UA_Client *client, const char *serverUrl, size_t serverUrisSize, UA_String *serverUris, size_t localeIdsSize, UA_String *localeIds, size_t *registeredServersSize, UA_ApplicationDescription **registeredServers)
UA_StatusCode UA_EXPORT UA_Client_findServersOnNetwork (UA_Client *client, const char *serverUrl, UA_UInt32 startingRecordId, UA_UInt32 maxRecordsToReturn, size_t serverCapabilityFilterSize, UA_String *serverCapabilityFilter, size_t *serverOnNetworkSize, UA_ServerOnNetwork **serverOnNetwork)
void UA_EXPORT __UA_Client_Service (UA_Client *client, const void *request, const UA_DataType *requestType, void *response, const UA_DataType *responseType)
static UA_INLINE UA_ReadResponse UA_Client_Service_read (UA_Client *client, const UA_ReadRequest request)
static UA_INLINE UA_WriteResponse UA_Client_Service_write (UA_Client *client, const UA_WriteRequest request)
static UA_INLINE UA_HistoryReadResponse UA_Client_Service_historyRead (UA_Client *client, const UA_HistoryReadRequest request)
static UA_INLINE UA_HistoryUpdateResponse UA_Client_Service_historyUpdate (UA_Client *client, const UA_HistoryUpdateRequest request)
static UA_INLINE UA_CallResponse UA_Client_Service_call (UA_Client *client, const UA_CallRequest request)
static UA_INLINE UA_AddNodesResponse UA_Client_Service_addNodes (UA_Client *client, const UA_AddNodesRequest request)
static UA_INLINE UA_AddReferencesResponse UA_Client_Service_addReferences (UA_Client *client, const UA_AddReferencesRequest request)
static UA_INLINE UA_DeleteNodesResponse UA_Client_Service_deleteNodes (UA_Client *client, const UA_DeleteNodesRequest request)
static UA_INLINE UA_DeleteReferencesResponse UA_Client_Service_deleteReferences (UA_Client *client, const UA_DeleteReferencesRequest request)
static UA_INLINE UA_BrowseResponse UA_Client_Service_browse (UA_Client *client, const UA_BrowseRequest request)
static UA_INLINE UA_BrowseNextResponse UA_Client_Service_browseNext (UA_Client *client, const UA_BrowseNextRequest request)
static UA_INLINE UA_TranslateBrowsePathsToNodeIdsResponse UA_Client_Service_translateBrowsePathsToNodeIds (UA_Client *client, const UA_TranslateBrowsePathsToNodeIdsRequest request)
static UA_INLINE UA_RegisterNodesResponse UA_Client_Service_registerNodes (UA_Client *client, const UA_RegisterNodesRequest request)
static UA_INLINE UA_UnregisterNodesResponse UA_Client_Service_unregisterNodes (UA_Client *client, const UA_UnregisterNodesRequest request)
static UA_INLINE UA_QueryFirstResponse UA_Client_Service_queryFirst (UA_Client *client, const UA_QueryFirstRequest request)
static UA_INLINE UA_QueryNextResponse UA_Client_Service_queryNext (UA_Client *client, const UA_QueryNextRequest request)
UA_StatusCode UA_EXPORT __UA_Client_AsyncService (UA_Client *client, const void *request, const UA_DataType *requestType, UA_ClientAsyncServiceCallback callback, const UA_DataType *responseType, void *userdata, UA_UInt32 *requestId)
UA_StatusCode UA_EXPORT UA_Client_sendAsyncRequest (UA_Client *client, const void *request, const UA_DataType *requestType, UA_ClientAsyncServiceCallback callback, const UA_DataType *responseType, void *userdata, UA_UInt32 *requestId)
UA_StatusCode UA_EXPORT UA_Client_run_iterate (UA_Client *client, UA_UInt16 timeout)
static UA_DEPRECATED UA_INLINE UA_StatusCode UA_Client_runAsync (UA_Client *client, UA_UInt16 timeout)
static UA_DEPRECATED UA_INLINE UA_StatusCode UA_Client_manuallyRenewSecureChannel (UA_Client *client)
UA_StatusCode UA_EXPORT __UA_Client_AsyncServiceEx (UA_Client *client, const void *request, const UA_DataType *requestType, UA_ClientAsyncServiceCallback callback, const UA_DataType *responseType, void *userdata, UA_UInt32 *requestId, UA_UInt32 timeout)
UA_StatusCode UA_EXPORT UA_Client_addTimedCallback (UA_Client *client, UA_ClientCallback callback, void *data, UA_DateTime date, UA_UInt64 *callbackId)
UA_StatusCode UA_EXPORT UA_Client_addRepeatedCallback (UA_Client *client, UA_ClientCallback callback, void *data, UA_Double interval_ms, UA_UInt64 *callbackId)
UA_StatusCode UA_EXPORT UA_Client_changeRepeatedCallbackInterval (UA_Client *client, UA_UInt64 callbackId, UA_Double interval_ms)
void UA_EXPORT UA_Client_removeCallback (UA_Client *client, UA_UInt64 callbackId)
Typedef Documentation
UA_ClientAsyncServiceCallback
typedef void(* UA_ClientAsyncServiceCallback) (UA_Client *client, void *userdata, UA_UInt32 requestId, void *response)
Connect to a Server
Definition at line 82 of file client.h.
UA_ClientCallback
typedef void(* UA_ClientCallback) (UA_Client *client, void *data)
Timed Callbacks
Repeated callbacks can be attached to a client and will be executed in the defined interval.
Definition at line 472 of file client.h.
Function Documentation
__UA_Client_AsyncService()
UA_StatusCode UA_EXPORT __UA_Client_AsyncService (UA_Client * client, const void * request, const UA_DataType * requestType, UA_ClientAsyncServiceCallback callback, const UA_DataType * responseType, void * userdata, UA_UInt32 * requestId)
.. _client-async-services:
Asynchronous Services
All OPC UA services are asynchronous in nature. So several service calls can be made without waiting for a response first. Responess may come in a different ordering.
Referenced by UA_Client_Service_queryNext().
__UA_Client_AsyncServiceEx()
UA_StatusCode UA_EXPORT __UA_Client_AsyncServiceEx (UA_Client * client, const void * request, const UA_DataType * requestType, UA_ClientAsyncServiceCallback callback, const UA_DataType * responseType, void * userdata, UA_UInt32 * requestId, UA_UInt32 timeout)
Referenced by UA_Client_manuallyRenewSecureChannel().
__UA_Client_Service()
void UA_EXPORT __UA_Client_Service (UA_Client * client, const void * request, const UA_DataType * requestType, void * response, const UA_DataType * responseType)
.. _client-services:
Services
The raw OPC UA services are exposed to the client. But most of them time, it is better to use the convenience functions from ua_client_highlevel.h that wrap the raw services.
Referenced by UA_Client_close(), UA_Client_MonitoredItems_setMonitoringMode(), UA_Client_MonitoredItems_setTriggering(), UA_Client_Service_addNodes(), UA_Client_Service_addReferences(), UA_Client_Service_browse(), UA_Client_Service_browseNext(), UA_Client_Service_call(), UA_Client_Service_deleteNodes(), UA_Client_Service_deleteReferences(), UA_Client_Service_historyRead(), UA_Client_Service_historyUpdate(), UA_Client_Service_queryFirst(), UA_Client_Service_queryNext(), UA_Client_Service_read(), UA_Client_Service_registerNodes(), UA_Client_Service_translateBrowsePathsToNodeIds(), UA_Client_Service_unregisterNodes(), UA_Client_Service_write(), and UA_Client_Subscriptions_setPublishingMode().
UA_Client_addRepeatedCallback()
UA_StatusCode UA_EXPORT UA_Client_addRepeatedCallback (UA_Client * client, UA_ClientCallback callback, void * data, UA_Double interval_ms, UA_UInt64 * callbackId)
UA_Client_addTimedCallback()
UA_StatusCode UA_EXPORT UA_Client_addTimedCallback (UA_Client * client, UA_ClientCallback callback, void * data, UA_DateTime date, UA_UInt64 * callbackId)
UA_Client_changeRepeatedCallbackInterval()
UA_StatusCode UA_EXPORT UA_Client_changeRepeatedCallbackInterval (UA_Client * client, UA_UInt64 callbackId, UA_Double interval_ms)
UA_Client_close()
static UA_DEPRECATED UA_INLINE UA_StatusCode UA_Client_close (UA_Client * client) static
Definition at line 126 of file client.h.
References __UA_Client_Service(), UA_Client_disconnect(), UA_Client_findServers(), UA_Client_findServersOnNetwork(), and UA_Client_getEndpoints().
UA_Client_connect()
UA_StatusCode UA_EXPORT UA_Client_connect (UA_Client * client, const char * endpointUrl)
UA_Client_connect_async()
UA_StatusCode UA_EXPORT UA_Client_connect_async (UA_Client * client, const char * endpointUrl, UA_ClientAsyncServiceCallback callback, void * userdata)
UA_Client_connect_noSession()
UA_StatusCode UA_EXPORT UA_Client_connect_noSession (UA_Client * client, const char * endpointUrl)
UA_Client_connect_username()
UA_StatusCode UA_EXPORT UA_Client_connect_username (UA_Client * client, const char * endpointUrl, const char * username, const char * password)
UA_Client_delete()
void UA_EXPORT UA_Client_delete (UA_Client * client)
Referenced by UA_Client_getContext().
UA_Client_disconnect()
UA_StatusCode UA_EXPORT UA_Client_disconnect (UA_Client * client)
Referenced by UA_Client_close().
UA_Client_disconnect_async()
UA_StatusCode UA_EXPORT UA_Client_disconnect_async (UA_Client * client, UA_UInt32 * requestId)
UA_Client_findServers()
UA_StatusCode UA_EXPORT UA_Client_findServers (UA_Client * client, const char * serverUrl, size_t serverUrisSize, UA_String * serverUris, size_t localeIdsSize, UA_String * localeIds, size_t * registeredServersSize, UA_ApplicationDescription ** registeredServers)
Referenced by UA_Client_close().
UA_Client_findServersOnNetwork()
UA_StatusCode UA_EXPORT UA_Client_findServersOnNetwork (UA_Client * client, const char * serverUrl, UA_UInt32 startingRecordId, UA_UInt32 maxRecordsToReturn, size_t serverCapabilityFilterSize, UA_String * serverCapabilityFilter, size_t * serverOnNetworkSize, UA_ServerOnNetwork ** serverOnNetwork)
Referenced by UA_Client_close().
UA_Client_getConfig()
UA_EXPORT UA_ClientConfig* UA_Client_getConfig (UA_Client * client)
Referenced by UA_Client_getContext().
UA_Client_getContext()
static UA_INLINE void* UA_Client_getContext (UA_Client * client) static
Definition at line 65 of file client.h.
References UA_ClientConfig::clientContext, UA_Client_delete(), UA_Client_getConfig(), and UA_Client_reset().
UA_Client_getEndpoints()
UA_StatusCode UA_EXPORT UA_Client_getEndpoints (UA_Client * client, const char * serverUrl, size_t * endpointDescriptionsSize, UA_EndpointDescription ** endpointDescriptions)
Discovery
Referenced by UA_Client_close().
UA_Client_getState()
UA_ClientState UA_EXPORT UA_Client_getState (UA_Client * client)
UA_Client_manuallyRenewSecureChannel()
static UA_DEPRECATED UA_INLINE UA_StatusCode UA_Client_manuallyRenewSecureChannel (UA_Client * client) static
Definition at line 435 of file client.h.
References __UA_Client_AsyncServiceEx(), and UA_Client_run_iterate().
UA_Client_new()
_UA_BEGIN_DECLS UA_Client UA_EXPORT* UA_Client_new (void)
.. _client:
Client
The client implementation allows remote access to all OPC UA services. For convenience, some functionality has been wrapped in :ref:high-level abstractions <client-highlevel>.
However: At this time, the client does not yet contain its own thread or event-driven main-loop. So the client will not perform any actions automatically in the background. This is especially relevant for subscriptions. The user will have to periodically call UA_Client_Subscriptions_manuallySendPublishRequest. See also :ref:here <client-subscriptions>.
.. include:: client_config.rst
Client Lifecycle
UA_Client_removeCallback()
void UA_EXPORT UA_Client_removeCallback (UA_Client * client, UA_UInt64 callbackId)
UA_Client_reset()
void UA_EXPORT UA_Client_reset (UA_Client * client)
Referenced by UA_Client_getContext().
UA_Client_run_iterate()
UA_StatusCode UA_EXPORT UA_Client_run_iterate (UA_Client * client, UA_UInt16 timeout)
Referenced by UA_Client_manuallyRenewSecureChannel(), UA_Client_runAsync(), and UA_Client_Service_queryNext().
UA_Client_runAsync()
static UA_DEPRECATED UA_INLINE UA_StatusCode UA_Client_runAsync (UA_Client * client, UA_UInt16 timeout) static
Definition at line 430 of file client.h.
References UA_Client_run_iterate().
UA_Client_sendAsyncRequest()
UA_StatusCode UA_EXPORT UA_Client_sendAsyncRequest (UA_Client * client, const void * request, const UA_DataType * requestType, UA_ClientAsyncServiceCallback callback, const UA_DataType * responseType, void * userdata, UA_UInt32 * requestId)
Referenced by UA_Client_sendAsyncBrowseRequest(), UA_Client_sendAsyncReadRequest(), UA_Client_sendAsyncWriteRequest(), and UA_Client_Service_queryNext().
UA_Client_Service_addNodes()
static UA_INLINE UA_AddNodesResponse UA_Client_Service_addNodes (UA_Client * client, const UA_AddNodesRequest request) static
Definition at line 273 of file client.h.
References __UA_Client_Service(), and UA_TYPES.
UA_Client_Service_addReferences()
static UA_INLINE UA_AddReferencesResponse UA_Client_Service_addReferences (UA_Client * client, const UA_AddReferencesRequest request) static
Definition at line 281 of file client.h.
References __UA_Client_Service(), and UA_TYPES.
UA_Client_Service_browse()
static UA_INLINE UA_BrowseResponse UA_Client_Service_browse (UA_Client * client, const UA_BrowseRequest request) static
Definition at line 311 of file client.h.
References __UA_Client_Service(), and UA_TYPES.
UA_Client_Service_browseNext()
static UA_INLINE UA_BrowseNextResponse UA_Client_Service_browseNext (UA_Client * client, const UA_BrowseNextRequest request) static
Definition at line 319 of file client.h.
References __UA_Client_Service(), and UA_TYPES.
UA_Client_Service_call()
static UA_INLINE UA_CallResponse UA_Client_Service_call (UA_Client * client, const UA_CallRequest request) static
Definition at line 261 of file client.h.
References __UA_Client_Service(), and UA_TYPES.
UA_Client_Service_deleteNodes()
static UA_INLINE UA_DeleteNodesResponse UA_Client_Service_deleteNodes (UA_Client * client, const UA_DeleteNodesRequest request) static
Definition at line 290 of file client.h.
References __UA_Client_Service(), and UA_TYPES.
UA_Client_Service_deleteReferences()
static UA_INLINE UA_DeleteReferencesResponse UA_Client_Service_deleteReferences (UA_Client * client, const UA_DeleteReferencesRequest request) static
Definition at line 299 of file client.h.
References __UA_Client_Service(), and UA_TYPES.
UA_Client_Service_historyRead()
static UA_INLINE UA_HistoryReadResponse UA_Client_Service_historyRead (UA_Client * client, const UA_HistoryReadRequest request) static
Definition at line 240 of file client.h.
References __UA_Client_Service(), and UA_TYPES.
UA_Client_Service_historyUpdate()
static UA_INLINE UA_HistoryUpdateResponse UA_Client_Service_historyUpdate (UA_Client * client, const UA_HistoryUpdateRequest request) static
Definition at line 248 of file client.h.
References __UA_Client_Service(), and UA_TYPES.
UA_Client_Service_queryFirst()
static UA_INLINE UA_QueryFirstResponse UA_Client_Service_queryFirst (UA_Client * client, const UA_QueryFirstRequest request) static
Definition at line 363 of file client.h.
References __UA_Client_Service(), and UA_TYPES.
UA_Client_Service_queryNext()
static UA_INLINE UA_QueryNextResponse UA_Client_Service_queryNext (UA_Client * client, const UA_QueryNextRequest request) static
Definition at line 372 of file client.h.
References __UA_Client_AsyncService(), __UA_Client_Service(), UA_Client_run_iterate(), UA_Client_sendAsyncRequest(), and UA_TYPES.
UA_Client_Service_read()
static UA_INLINE UA_ReadResponse UA_Client_Service_read (UA_Client * client, const UA_ReadRequest request) static
Definition at line 220 of file client.h.
References __UA_Client_Service(), and UA_TYPES.
UA_Client_Service_registerNodes()
static UA_INLINE UA_RegisterNodesResponse UA_Client_Service_registerNodes (UA_Client * client, const UA_RegisterNodesRequest request) static
Definition at line 339 of file client.h.
References __UA_Client_Service(), and UA_TYPES.
UA_Client_Service_translateBrowsePathsToNodeIds()
static UA_INLINE UA_TranslateBrowsePathsToNodeIdsResponse UA_Client_Service_translateBrowsePathsToNodeIds (UA_Client * client, const UA_TranslateBrowsePathsToNodeIdsRequest request) static
Definition at line 328 of file client.h.
References __UA_Client_Service(), and UA_TYPES.
UA_Client_Service_unregisterNodes()
static UA_INLINE UA_UnregisterNodesResponse UA_Client_Service_unregisterNodes (UA_Client * client, const UA_UnregisterNodesRequest request) static
Definition at line 348 of file client.h.
References __UA_Client_Service(), and UA_TYPES.
UA_Client_Service_write()
static UA_INLINE UA_WriteResponse UA_Client_Service_write (UA_Client * client, const UA_WriteRequest request) static
Definition at line 228 of file client.h.
References __UA_Client_Service(), and UA_TYPES.