Project Template: Opc.Ua.TranslateBrowsePathsToNodeIdsRequest Class Reference
Opc.Ua.TranslateBrowsePathsToNodeIdsRequest Class Reference
Public Member Functions
TranslateBrowsePathsToNodeIdsRequest ()
The default constructor.
virtual void Encode (IEncoder encoder)
virtual void Decode (IDecoder decoder)
virtual bool IsEqual (IEncodeable encodeable)
virtual object Clone ()
new object MemberwiseClone ()
Properties
RequestHeader RequestHeader [get, set]
BrowsePathCollection BrowsePaths [get, set]
virtual ExpandedNodeId TypeId [get]
virtual ExpandedNodeId BinaryEncodingId [get]
virtual ExpandedNodeId XmlEncodingId [get]
Detailed Description
<exclude>
Definition at line 1859 of file Opc.Ua.Messages.cs.
Constructor & Destructor Documentation
TranslateBrowsePathsToNodeIdsRequest()
Opc.Ua.TranslateBrowsePathsToNodeIdsRequest.TranslateBrowsePathsToNodeIdsRequest () inline
The default constructor.
Definition at line 39634 of file Opc.Ua.DataTypes.cs.
Member Function Documentation
Clone()
virtual object Opc.Ua.TranslateBrowsePathsToNodeIdsRequest.Clone () inline virtual
Definition at line 39768 of file Opc.Ua.DataTypes.cs.
Decode()
virtual void Opc.Ua.TranslateBrowsePathsToNodeIdsRequest.Decode (IDecoder decoder) inline virtual
Definition at line 39735 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
Encode()
virtual void Opc.Ua.TranslateBrowsePathsToNodeIdsRequest.Encode (IEncoder encoder) inline virtual
Definition at line 39724 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
IsEqual()
virtual bool Opc.Ua.TranslateBrowsePathsToNodeIdsRequest.IsEqual (IEncodeable encodeable) inline virtual
Definition at line 39746 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Object.
MemberwiseClone()
new object Opc.Ua.TranslateBrowsePathsToNodeIdsRequest.MemberwiseClone () inline
Definition at line 39775 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.RequestHeader.Clone(), Opc.Ua.BrowsePathCollection.Clone(), Opc.Ua.TranslateBrowsePathsToNodeIdsRequest.MemberwiseClone(), and Opc.Ua.Namespaces.OpcUaXsd.
Referenced by Opc.Ua.TranslateBrowsePathsToNodeIdsRequest.MemberwiseClone().
Property Documentation
BinaryEncodingId
virtual ExpandedNodeId Opc.Ua.TranslateBrowsePathsToNodeIdsRequest.BinaryEncodingId get
Definition at line 39713 of file Opc.Ua.DataTypes.cs.
BrowsePaths
BrowsePathCollection Opc.Ua.TranslateBrowsePathsToNodeIdsRequest.BrowsePaths get set
Definition at line 39686 of file Opc.Ua.DataTypes.cs.
Referenced by Opc.Ua.SessionClient.BeginTranslateBrowsePathsToNodeIds(), Opc.Ua.SessionClient.EndBrowseNext(), and Opc.Ua.SessionEndpoint.EndBrowseNext().
RequestHeader
RequestHeader Opc.Ua.TranslateBrowsePathsToNodeIdsRequest.RequestHeader get set
Definition at line 39664 of file Opc.Ua.DataTypes.cs.
Referenced by Opc.Ua.SessionClient.BeginTranslateBrowsePathsToNodeIds(), Opc.Ua.SessionClient.EndBrowseNext(), and Opc.Ua.SessionEndpoint.EndBrowseNext().
TypeId
virtual ExpandedNodeId Opc.Ua.TranslateBrowsePathsToNodeIdsRequest.TypeId get
Definition at line 39707 of file Opc.Ua.DataTypes.cs.
XmlEncodingId
virtual ExpandedNodeId Opc.Ua.TranslateBrowsePathsToNodeIdsRequest.XmlEncodingId get
Definition at line 39719 of file Opc.Ua.DataTypes.cs.
The documentation for this class was generated from the following files:
Opc.Ua.Messages.cs
Opc.Ua.DataTypes.cs