# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget open62541::open62541)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target open62541::open62541
add_library(open62541::open62541 SHARED IMPORTED)

set_target_properties(open62541::open62541 PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "UA_ARCHITECTURE_POSIX"
  INTERFACE_INCLUDE_DIRECTORIES "/home/saukijan/Documents/HS-OPCUA/open62541-server/libs/open62541/arch;/home/saukijan/Documents/HS-OPCUA/open62541-server/libs/open62541/include;/home/saukijan/Documents/HS-OPCUA/open62541-server/libs/open62541/plugins/include;/home/saukijan/Documents/HS-OPCUA/open62541-server/libs/open62541/deps;/home/saukijan/Documents/HS-OPCUA/open62541-server/libs/open62541/src/pubsub;/home/saukijan/Documents/HS-OPCUA/open62541-server/build/open62541-build/src_generated"
  INTERFACE_LINK_LIBRARIES "m;pthread;rt"
)

# Import target "open62541::open62541" for configuration "RelWithDebInfo"
set_property(TARGET open62541::open62541 APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(open62541::open62541 PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/saukijan/Documents/HS-OPCUA/open62541-server/build/open62541-build/bin/libopen62541.so.1.0.0"
  IMPORTED_SONAME_RELWITHDEBINFO "libopen62541.so.0"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
