Project Template: Opc.Ua.NodeTypeDescription Class Reference
Opc.Ua.NodeTypeDescription Class Reference
Public Member Functions
NodeTypeDescription ()
The default constructor.
virtual void Encode (IEncoder encoder)
virtual void Decode (IDecoder decoder)
virtual bool IsEqual (IEncodeable encodeable)
virtual object Clone ()
new object MemberwiseClone ()
Properties
ExpandedNodeId TypeDefinitionNode [get, set]
bool IncludeSubTypes [get, set]
QueryDataDescriptionCollection DataToReturn [get, set]
virtual ExpandedNodeId TypeId [get]
virtual ExpandedNodeId BinaryEncodingId [get]
virtual ExpandedNodeId XmlEncodingId [get]
Detailed Description
<exclude>
Definition at line 41260 of file Opc.Ua.DataTypes.cs.
Constructor & Destructor Documentation
NodeTypeDescription()
Opc.Ua.NodeTypeDescription.NodeTypeDescription () inline
The default constructor.
Definition at line 41266 of file Opc.Ua.DataTypes.cs.
Member Function Documentation
Clone()
virtual object Opc.Ua.NodeTypeDescription.Clone () inline virtual
Definition at line 41398 of file Opc.Ua.DataTypes.cs.
Decode()
virtual void Opc.Ua.NodeTypeDescription.Decode (IDecoder decoder) inline virtual
Definition at line 41363 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
Encode()
virtual void Opc.Ua.NodeTypeDescription.Encode (IEncoder encoder) inline virtual
Definition at line 41351 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
IsEqual()
virtual bool Opc.Ua.NodeTypeDescription.IsEqual (IEncodeable encodeable) inline virtual
Definition at line 41375 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Object.
MemberwiseClone()
new object Opc.Ua.NodeTypeDescription.MemberwiseClone () inline
Definition at line 41405 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.QueryDataDescriptionCollection.Clone(), Opc.Ua.NodeTypeDescription.MemberwiseClone(), and Opc.Ua.Namespaces.OpcUaXsd.
Referenced by Opc.Ua.NodeTypeDescription.MemberwiseClone().
Property Documentation
BinaryEncodingId
virtual ExpandedNodeId Opc.Ua.NodeTypeDescription.BinaryEncodingId get
Definition at line 41340 of file Opc.Ua.DataTypes.cs.
DataToReturn
QueryDataDescriptionCollection Opc.Ua.NodeTypeDescription.DataToReturn get set
Definition at line 41313 of file Opc.Ua.DataTypes.cs.
IncludeSubTypes
bool Opc.Ua.NodeTypeDescription.IncludeSubTypes get set
Definition at line 41303 of file Opc.Ua.DataTypes.cs.
TypeDefinitionNode
ExpandedNodeId Opc.Ua.NodeTypeDescription.TypeDefinitionNode get set
Definition at line 41295 of file Opc.Ua.DataTypes.cs.
TypeId
virtual ExpandedNodeId Opc.Ua.NodeTypeDescription.TypeId get
Definition at line 41334 of file Opc.Ua.DataTypes.cs.
XmlEncodingId
virtual ExpandedNodeId Opc.Ua.NodeTypeDescription.XmlEncodingId get
Definition at line 41346 of file Opc.Ua.DataTypes.cs.
The documentation for this class was generated from the following file:
Opc.Ua.DataTypes.cs