Project Template: Opc.MDIS Namespace Reference
Opc.MDIS Namespace Reference
Data Structures
class BrowseNames
Declares all of the BrowseNames used in the Model Design.
class ChokeCommandEnumCollection
A collection of ChokeCommandEnum objects.
class ChokeMoveEnumCollection
A collection of ChokeMoveEnum objects.
class ChokeMoveMethodState
Stores an instance of the ChokeMoveMethodType Method.
class ChokeSetCalculatedPositionMethodState
Stores an instance of the ChokeSetCalculatedPositionMethodType Method.
class ChokeStepMethodState
Stores an instance of the ChokeStepMethodType Method.
class CommandEnumCollection
A collection of CommandEnum objects.
class DataTypeIds
A class that declares constants for all DataTypes in the Model Design.
class DataTypes
A class that declares constants for all DataTypes in the Model Design.
class EnableDisableMethodState
Stores an instance of the EnableDisableMethodType Method.
class InterlockVariableState
Stores an instance of the InterlockVariableType VariableType.
class MDISAggregateObjectState
Stores an instance of the MDISAggregateObjectType ObjectType.
class MDISBaseObjectState
Stores an instance of the MDISBaseObjectType ObjectType.
class MDISChokeObjectState
Stores an instance of the MDISChokeObjectType ObjectType.
class MDISDigitalInstrumentObjectState
Stores an instance of the MDISDigitalInstrumentObjectType ObjectType.
class MDISDigitalOutObjectState
Stores an instance of the MDISDigitalOutObjectType ObjectType.
class MDISDiscreteInstrumentObjectState
Stores an instance of the MDISDiscreteInstrumentObjectType ObjectType.
class MDISDiscreteOutObjectState
Stores an instance of the MDISDiscreteOutObjectType ObjectType.
class MDISInformationObjectState
Stores an instance of the MDISInformationObjectType ObjectType.
class MDISInstrumentObjectState
Stores an instance of the MDISInstrumentObjectType ObjectType.
class MDISInstrumentOutObjectState
Stores an instance of the MDISInstrumentOutObjectType ObjectType.
class MDISTimeSyncObjectState
Stores an instance of the MDISTimeSyncObjectType ObjectType.
class MDISValveObjectState
Stores an instance of the MDISValveObjectType ObjectType.
class MDISVersionDataType
class MDISVersionDataTypeCollection
A collection of MDISVersionDataType objects.
class MDISVersionVariableState
Stores an instance of the MDISVersionVariableType VariableType.
class MDISVersionVariableValue
A typed version of the BrowseName variable.
class MethodIds
A class that declares constants for all Methods in the Model Design.
class Methods
A class that declares constants for all Methods in the Model Design.
class MoveMethodState
Stores an instance of the MoveMethodType Method.
class Namespaces
Defines constants for all namespaces referenced by the model design.
class ObjectIds
A class that declares constants for all Objects in the Model Design.
class Objects
A class that declares constants for all Objects in the Model Design.
class ObjectTypeIds
A class that declares constants for all ObjectTypes in the Model Design.
class ObjectTypes
A class that declares constants for all ObjectTypes in the Model Design.
class ReferenceTypeIds
A class that declares constants for all ReferenceTypes in the Model Design.
class ReferenceTypes
A class that declares constants for all ReferenceTypes in the Model Design.
class SEMEnumCollection
A collection of SEMEnum objects.
class SetCalculatedPositionEnumCollection
A collection of SetCalculatedPositionEnum objects.
class SetTimeMethodState
Stores an instance of the SetTimeMethodType Method.
class SignatureStatusEnumCollection
A collection of SignatureStatusEnum objects.
class ValvePositionEnumCollection
A collection of ValvePositionEnum objects.
class VariableIds
A class that declares constants for all Variables in the Model Design.
class Variables
A class that declares constants for all Variables in the Model Design.
class VariableTypeIds
A class that declares constants for all VariableTypes in the Model Design.
class VariableTypes
A class that declares constants for all VariableTypes in the Model Design.
class WriteInstrumentValueMethodState
Stores an instance of the WriteInstrumentValueMethodType Method.
class WriteStateMethodState
Stores an instance of the WriteStateMethodType Method.
class WriteValueMethodState
Stores an instance of the WriteValueMethodType Method.
Enumerations
enum SignatureStatusEnum { SignatureStatusEnum.NotAvailable = 1, SignatureStatusEnum.Completed = 2, SignatureStatusEnum.Failed = 4 }
enum SetCalculatedPositionEnum { SetCalculatedPositionEnum.Initial = 0, SetCalculatedPositionEnum.Inprogress = 1, SetCalculatedPositionEnum.Complete = 2, SetCalculatedPositionEnum.Fault = 4 }
enum CommandEnum { CommandEnum.Close = 1, CommandEnum.Open = 2, CommandEnum.None = 4 }
enum ChokeCommandEnum { ChokeCommandEnum.Close = 1, ChokeCommandEnum.Open = 2 }
enum SEMEnum { SEMEnum.SEM_A = 1, SEMEnum.SEM_B = 2, SEMEnum.Auto = 4 }
enum ValvePositionEnum { ValvePositionEnum.Closed = 1, ValvePositionEnum.Open = 2, ValvePositionEnum.Moving = 4, ValvePositionEnum.Unknown = 8 }
enum ChokeMoveEnum { ChokeMoveEnum.Moving = 1, ChokeMoveEnum.Stopped = 2 }
Functions
delegate ServiceResult EnableDisableMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, bool enable)
Used to receive notifications when the method is called.
delegate ServiceResult MoveMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, CommandEnum direction, bool overrideInterlock, SEMEnum sEM, bool signature, bool shutdownRequest)
Used to receive notifications when the method is called.
delegate ServiceResult ChokeMoveMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, float position, bool overrideInterlock, SEMEnum sEM)
Used to receive notifications when the method is called.
delegate ServiceResult ChokeStepMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, ChokeCommandEnum direction, ushort steps, bool overrideInterlock, SEMEnum sEM)
Used to receive notifications when the method is called.
delegate ServiceResult ChokeSetCalculatedPositionMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, float position)
Used to receive notifications when the method is called.
delegate ServiceResult WriteStateMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, bool state)
Used to receive notifications when the method is called.
delegate ServiceResult WriteValueMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, uint state)
Used to receive notifications when the method is called.
delegate ServiceResult WriteInstrumentValueMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, float value)
Used to receive notifications when the method is called.
delegate ServiceResult SetTimeMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, DateTime targetTime)
Used to receive notifications when the method is called.
Enumeration Type Documentation
ChokeCommandEnum
enum Opc.MDIS.ChokeCommandEnum strong
<exclude>
Enumerator
Close
Open
Definition at line 381 of file Opc.MDIS.DataTypes.cs.
ChokeMoveEnum
enum Opc.MDIS.ChokeMoveEnum strong
<exclude>
Enumerator
Moving
Stopped
Definition at line 711 of file Opc.MDIS.DataTypes.cs.
CommandEnum
enum Opc.MDIS.CommandEnum strong
<exclude>
Enumerator
Close
Open
None
Definition at line 271 of file Opc.MDIS.DataTypes.cs.
SEMEnum
enum Opc.MDIS.SEMEnum strong
<exclude>
Enumerator
SEM_A
SEM_B
Auto
Definition at line 487 of file Opc.MDIS.DataTypes.cs.
SetCalculatedPositionEnum
enum Opc.MDIS.SetCalculatedPositionEnum strong
<exclude>
Enumerator
Initial
Inprogress
Complete
Fault
Definition at line 157 of file Opc.MDIS.DataTypes.cs.
SignatureStatusEnum
enum Opc.MDIS.SignatureStatusEnum strong
<exclude>
Enumerator
NotAvailable
Completed
Failed
Definition at line 47 of file Opc.MDIS.DataTypes.cs.
ValvePositionEnum
enum Opc.MDIS.ValvePositionEnum strong
<exclude>
Enumerator
Closed
Open
Moving
Unknown
Definition at line 597 of file Opc.MDIS.DataTypes.cs.
Function Documentation
ChokeMoveMethodStateMethodCallHandler()
delegate ServiceResult Opc.MDIS.ChokeMoveMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, float position, bool overrideInterlock, SEMEnum sEM)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.MDIS.ChokeMoveMethodState.InitializeOptionalChildren().
ChokeSetCalculatedPositionMethodStateMethodCallHandler()
delegate ServiceResult Opc.MDIS.ChokeSetCalculatedPositionMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, float position)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.MDIS.ChokeSetCalculatedPositionMethodState.InitializeOptionalChildren().
ChokeStepMethodStateMethodCallHandler()
delegate ServiceResult Opc.MDIS.ChokeStepMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, ChokeCommandEnum direction, ushort steps, bool overrideInterlock, SEMEnum sEM)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.MDIS.ChokeStepMethodState.InitializeOptionalChildren().
EnableDisableMethodStateMethodCallHandler()
delegate ServiceResult Opc.MDIS.EnableDisableMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, bool enable)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.MDIS.EnableDisableMethodState.InitializeOptionalChildren().
MoveMethodStateMethodCallHandler()
delegate ServiceResult Opc.MDIS.MoveMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, CommandEnum direction, bool overrideInterlock, SEMEnum sEM, bool signature, bool shutdownRequest)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.MDIS.MoveMethodState.InitializeOptionalChildren().
SetTimeMethodStateMethodCallHandler()
delegate ServiceResult Opc.MDIS.SetTimeMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, DateTime targetTime)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.MDIS.SetTimeMethodState.InitializeOptionalChildren().
WriteInstrumentValueMethodStateMethodCallHandler()
delegate ServiceResult Opc.MDIS.WriteInstrumentValueMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, float value)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.MDIS.WriteInstrumentValueMethodState.InitializeOptionalChildren().
WriteStateMethodStateMethodCallHandler()
delegate ServiceResult Opc.MDIS.WriteStateMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, bool state)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.MDIS.WriteStateMethodState.InitializeOptionalChildren().
WriteValueMethodStateMethodCallHandler()
delegate ServiceResult Opc.MDIS.WriteValueMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, uint state)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.MDIS.WriteValueMethodState.InitializeOptionalChildren().