Project Template: Opc.Ua.Fdi7 Namespace Reference
Opc.Ua.Fdi7 Namespace Reference
Data Structures
class AddComponentMethodState
Stores an instance of the AddComponentMethodType Method.
class BrowseNames
Declares all of the BrowseNames used in the Model Design.
class CommunicationServerState
Stores an instance of the CommunicationServerType ObjectType.
class CommunicationServerTypeInitializeMethodState
Stores an instance of the CommunicationServerTypeInitializeMethodType Method.
class CommunicationServerTypeResetMethodState
Stores an instance of the CommunicationServerTypeResetMethodType Method.
class ConnectionPoint_Foundation_H1State
Stores an instance of the ConnectionPoint_Foundation_H1 ObjectType.
class ConnectionPoint_Foundation_HSEState
Stores an instance of the ConnectionPoint_Foundation_HSE ObjectType.
class ConnectionPoint_HART_TP5State
Stores an instance of the ConnectionPoint_HART_TP5 ObjectType.
class ConnectionPoint_HART_TP6State
Stores an instance of the ConnectionPoint_HART_TP6 ObjectType.
class ConnectionPoint_HART_TP7State
Stores an instance of the ConnectionPoint_HART_TP7 ObjectType.
class ConnectionPoint_ISA100_WirelessState
Stores an instance of the ConnectionPoint_ISA100_Wireless ObjectType.
class ConnectionPoint_Profibus_DPState
Stores an instance of the ConnectionPoint_Profibus_DP ObjectType.
class ConnectionPoint_Profinet_IOState
Stores an instance of the ConnectionPoint_Profinet_IO ObjectType.
class ConnectMethodFFH1MethodState
Stores an instance of the ConnectMethodFFH1Type Method.
class ConnectMethodFFHSEMethodState
Stores an instance of the ConnectMethodFFHSEType Method.
class ConnectMethodGENERICMethodState
Stores an instance of the ConnectMethodGENERICType Method.
class ConnectMethodHARTMethodState
Stores an instance of the ConnectMethodHARTType Method.
class ConnectMethodISA100_WirelessMethodState
Stores an instance of the ConnectMethodISA100_WirelessType Method.
class ConnectMethodPROFIBUSMethodState
Stores an instance of the ConnectMethodPROFIBUSType Method.
class ConnectMethodPROFINETMethodState
Stores an instance of the ConnectMethodPROFINETType Method.
class DataTypeIds
A class that declares constants for all DataTypes in the Model Design.
class DataTypes
A class that declares constants for all DataTypes in the Model Design.
class DisconnectMethodState
Stores an instance of the DisconnectMethodType Method.
class EddDataTypeEnumCollection
A collection of EddDataTypeEnum objects.
class EddDataTypeInfo
class EddDataTypeInfoCollection
A collection of EddDataTypeInfo objects.
class Foundation_H1State
Stores an instance of the Foundation_H1 ObjectType.
class Foundation_HSEState
Stores an instance of the Foundation_HSE ObjectType.
class GenericConnectionPointState
Stores an instance of the GenericConnectionPoint ObjectType.
class GenericProtocolState
Stores an instance of the GenericProtocol ObjectType.
class GetPublishedDataMethodFFH1MethodState
Stores an instance of the GetPublishedDataMethodFFH1Type Method.
class GetPublishedDataMethodFFHSEMethodState
Stores an instance of the GetPublishedDataMethodFFHSEType Method.
class GetPublishedDataMethodHARTMethodState
Stores an instance of the GetPublishedDataMethodHARTType Method.
class GetPublishedDataMethodISA100_WirelessMethodState
Stores an instance of the GetPublishedDataMethodISA100_WirelessType Method.
class HARTState
Stores an instance of the HART ObjectType.
class ISA100_WirelessState
Stores an instance of the ISA100_Wireless ObjectType.
class MethodIds
A class that declares constants for all Methods in the Model Design.
class Methods
A class that declares constants for all Methods in the Model Design.
class Namespaces
Defines constants for all namespaces referenced by the model design.
class ObjectIds
A class that declares constants for all Objects in the Model Design.
class Objects
A class that declares constants for all Objects in the Model Design.
class ObjectTypeIds
A class that declares constants for all ObjectTypes in the Model Design.
class ObjectTypes
A class that declares constants for all ObjectTypes in the Model Design.
class Profibus_DPState
Stores an instance of the Profibus_DP ObjectType.
class Profibus_PAState
Stores an instance of the Profibus_PA ObjectType.
class Profinet_IOState
Stores an instance of the Profinet_IO ObjectType.
class RemoveComponentMethodState
Stores an instance of the RemoveComponentMethodType Method.
class ResetScanMethodState
Stores an instance of the ResetScanMethodType Method.
class ScanMethodState
Stores an instance of the ScanMethodType Method.
class ServerCommunicationDeviceState
Stores an instance of the ServerCommunicationDeviceType ObjectType.
class ServerCommunicationFFH1DeviceState
Stores an instance of the ServerCommunicationFFH1DeviceType ObjectType.
class ServerCommunicationFFH1ServiceState
Stores an instance of the ServerCommunicationFFH1ServiceType ObjectType.
class ServerCommunicationFFHSEDeviceState
Stores an instance of the ServerCommunicationFFHSEDeviceType ObjectType.
class ServerCommunicationFFHSEServiceState
Stores an instance of the ServerCommunicationFFHSEServiceType ObjectType.
class ServerCommunicationGENERICDeviceState
Stores an instance of the ServerCommunicationGENERICDeviceType ObjectType.
class ServerCommunicationGENERICServiceState
Stores an instance of the ServerCommunicationGENERICServiceType ObjectType.
class ServerCommunicationHARState
Stores an instance of the ServerCommunicationHARType ObjectType.
class ServerCommunicationHARTServiceState
Stores an instance of the ServerCommunicationHARTServiceType ObjectType.
class ServerCommunicationISA100_WirelessDeviceState
Stores an instance of the ServerCommunicationISA100_WirelessDeviceType ObjectType.
class ServerCommunicationISA100_WirelessServiceState
Stores an instance of the ServerCommunicationISA100_WirelessServiceType ObjectType.
class ServerCommunicationPROFIBUSDeviceState
Stores an instance of the ServerCommunicationPROFIBUSDeviceType ObjectType.
class ServerCommunicationPROFIBUSServiceState
Stores an instance of the ServerCommunicationPROFIBUSServiceType ObjectType.
class ServerCommunicationPROFINETDeviceState
Stores an instance of the ServerCommunicationPROFINETDeviceType ObjectType.
class ServerCommunicationPROFINETServiceState
Stores an instance of the ServerCommunicationPROFINETServiceType ObjectType.
class ServerCommunicationServiceState
Stores an instance of the ServerCommunicationServiceType ObjectType.
class SetAddressMethodFFH1MethodState
Stores an instance of the SetAddressMethodFFH1Type Method.
class SetAddressMethodFFHSEMethodState
Stores an instance of the SetAddressMethodFFHSEType Method.
class SetAddressMethodGENERICMethodState
Stores an instance of the SetAddressMethodGENERICType Method.
class SetAddressMethodHARTMethodState
Stores an instance of the SetAddressMethodHARTType Method.
class SetAddressMethodPROFIBUSMethodState
Stores an instance of the SetAddressMethodPROFIBUSType Method.
class SetAddressMethodPROFINETMethodState
Stores an instance of the SetAddressMethodPROFINETType Method.
class TransferMethodFFH1MethodState
Stores an instance of the TransferMethodFFH1Type Method.
class TransferMethodFFHSEMethodState
Stores an instance of the TransferMethodFFHSEType Method.
class TransferMethodGENERICMethodState
Stores an instance of the TransferMethodGENERICType Method.
class TransferMethodHARTMethodState
Stores an instance of the TransferMethodHARTType Method.
class TransferMethodISA100_WirelessMethodState
Stores an instance of the TransferMethodISA100_WirelessType Method.
class TransferMethodPROFIBUSMethodState
Stores an instance of the TransferMethodPROFIBUSType Method.
class TransferMethodPROFINETMethodState
Stores an instance of the TransferMethodPROFINETType Method.
class VariableIds
A class that declares constants for all Variables in the Model Design.
class Variables
A class that declares constants for all Variables in the Model Design.
Enumerations
enum EddDataTypeEnum {
EddDataTypeEnum.BOOLEAN = 1, EddDataTypeEnum.DOUBLE = 2, EddDataTypeEnum.FLOAT = 3, EddDataTypeEnum.INTEGER = 4,
EddDataTypeEnum.UNSIGNED_INTEGER = 5, EddDataTypeEnum.DATE = 6, EddDataTypeEnum.DATE_AND_TIME = 7, EddDataTypeEnum.DURATION = 8,
EddDataTypeEnum.TIME = 9, EddDataTypeEnum.TIME_VALUE = 10, EddDataTypeEnum.BIT_ENUMERATED = 11, EddDataTypeEnum.ENUMERATED = 12,
EddDataTypeEnum.ASCII = 13, EddDataTypeEnum.BITSTRING = 14, EddDataTypeEnum.EUC = 15, EddDataTypeEnum.OCTET = 16,
EddDataTypeEnum.PACKED_ASCII = 17, EddDataTypeEnum.PASSWORD = 18, EddDataTypeEnum.VISIBLE = 19
}
Functions
delegate ServiceResult CommunicationServerTypeInitializeMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, ref object serviceError)
Used to receive notifications when the method is called.
delegate ServiceResult CommunicationServerTypeResetMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, ref object serviceError)
Used to receive notifications when the method is called.
delegate ServiceResult AddComponentMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, string moduleTypeName, string instanceName, string instanceLabel, ref NodeId instanceNodeId, ref object serviceError)
Used to receive notifications when the method is called.
delegate ServiceResult RemoveComponentMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, NodeId moduleNodeId, ref object serviceError)
Used to receive notifications when the method is called.
delegate ServiceResult ScanMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, ref XmlElement topologyScanResult, ref object serviceError)
Used to receive notifications when the method is called.
delegate ServiceResult ResetScanMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, ref object serviceError)
Used to receive notifications when the method is called.
delegate ServiceResult SetAddressMethodFFH1MethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, string oPERATION, ushort linkId, byte oldAddress, byte newAddress, string newPDTag, uint serviceId, ref uint delayForNextCall, ref object serviceError)
Used to receive notifications when the method is called.
delegate ServiceResult SetAddressMethodFFHSEMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, string oPERATION, string newPDTag, uint serviceId, ref uint delayForNextCall, ref object serviceError)
Used to receive notifications when the method is called.
delegate ServiceResult SetAddressMethodPROFIBUSMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, byte oldAddress, byte newAddress, ref object serviceError)
Used to receive notifications when the method is called.
delegate ServiceResult SetAddressMethodPROFINETMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, byte[] mAC, byte[] iP, string dNSNAME, byte[] subnetMask, byte[] gateway, ref object serviceError)
Used to receive notifications when the method is called.
delegate ServiceResult SetAddressMethodHARTMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, byte oldPollAddress, byte newPollAddress, ref object serviceError)
Used to receive notifications when the method is called.
delegate ServiceResult SetAddressMethodGENERICMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, byte[] oldAddress, byte[] newAddress, ref object serviceError)
Used to receive notifications when the method is called.
delegate ServiceResult ConnectMethodFFH1MethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, byte[] communicationRelationId, ushort linkId, byte address, int ordinalNumber, bool sIFConnection, uint serviceId, ref uint delayForNextCall, ref object serviceError)
Used to receive notifications when the method is called.
delegate ServiceResult ConnectMethodFFHSEMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, byte[] communicationRelationId, byte[] address, int ordinalNumber, uint serviceId, ref uint delayForNextCall, ref object serviceError)
Used to receive notifications when the method is called.
delegate ServiceResult ConnectMethodPROFIBUSMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, byte[] communicationRelationId, byte address, ushort manufacturerId, ref object serviceError)
Used to receive notifications when the method is called.
delegate ServiceResult ConnectMethodPROFINETMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, byte[] communicationRelationId, string dNSNAME, ushort deviceID, ushort vendorID, ref object serviceError)
Used to receive notifications when the method is called.
delegate ServiceResult ConnectMethodHARTMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, byte[] communicationRelationId, byte[] longAddress, ref object serviceError)
Used to receive notifications when the method is called.
delegate ServiceResult ConnectMethodISA100_WirelessMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, byte[] communicationRelationId, byte[] iPAddress, uint connectType, ref object serviceError)
Used to receive notifications when the method is called.
delegate ServiceResult ConnectMethodGENERICMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, byte[] communicationRelationId, byte[] address, ref object serviceError)
Used to receive notifications when the method is called.
delegate ServiceResult DisconnectMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, byte[] communicationRelationId, ref object serviceError)
Used to receive notifications when the method is called.
delegate ServiceResult TransferMethodFFH1MethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, byte[] communicationRelationId, string oPERATION, string blockTag, uint iNDEX, uint sUB_INDEX, byte[] writeData, uint serviceId, ref byte[] readData, ref uint delayForNextCall, ref object serviceError)
Used to receive notifications when the method is called.
delegate ServiceResult TransferMethodFFHSEMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, byte[] communicationRelationId, string oPERATION, string blockTag, uint iNDEX, uint sUB_INDEX, byte[] writeData, uint serviceId, ref byte[] readData, ref uint delayForNextCall, ref object serviceError)
Used to receive notifications when the method is called.
delegate ServiceResult TransferMethodPROFIBUSMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, byte[] communicationRelationId, string oPERATION, byte sLOT, byte iNDEX, byte[] rEQUEST, ref byte[] rEPLY, ref byte[] rESPONSE_CODES, ref object serviceError)
Used to receive notifications when the method is called.
delegate ServiceResult TransferMethodPROFINETMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, byte[] communicationRelationId, string oPERATION, ushort sLOT, ushort sUBSLOT, ushort iNDEX, uint aPI, byte[] rEQUEST, ref byte[] rEPLY, ref byte[] rESPONSE_CODES, ref object serviceError)
Used to receive notifications when the method is called.
delegate ServiceResult TransferMethodHARTMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, byte[] communicationRelationId, ushort command, byte[] request, ref byte[] reply, ref object serviceError)
Used to receive notifications when the method is called.
delegate ServiceResult TransferMethodISA100_WirelessMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, byte[] communicationRelationId, string oPERATION, ushort appID, ushort objectID, ushort attrOrMethID, uint sUB_INDEX, byte[] writeData, uint requestId, ref byte[] readData, ref object serviceError)
Used to receive notifications when the method is called.
delegate ServiceResult TransferMethodGENERICMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, byte[] communicationRelationId, string header, byte[] requestData, EddDataTypeInfo[] requestDataTypes, EddDataTypeInfo[] responseDataTypes, ref byte[] responseData, ref byte[] rESPONSE_CODES, ref object serviceError)
Used to receive notifications when the method is called.
delegate ServiceResult GetPublishedDataMethodFFH1MethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, byte[] communicationRelationId, uint serviceId, ref string blockTag, ref byte[] alarmEventData, ref NodeId alarmEventType, ref DateTime timeStamp, ref uint delayForNextCall, ref object serviceError)
Used to receive notifications when the method is called.
delegate ServiceResult GetPublishedDataMethodFFHSEMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, byte[] communicationRelationId, uint serviceId, ref string blockTag, ref byte[] alarmEventData, ref NodeId alarmEventType, ref DateTime timeStamp, ref uint delayForNextCall, ref object serviceError)
Used to receive notifications when the method is called.
delegate ServiceResult GetPublishedDataMethodHARTMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, byte[] communicationRelationId, ref ushort command, ref byte[] reply, ref DateTime timeStamp, ref object serviceError)
Used to receive notifications when the method is called.
delegate ServiceResult GetPublishedDataMethodISA100_WirelessMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, byte[] communicationRelationId, ref ushort appID, ref ushort objectID, ref byte[] alarmEventData, ref ushort alarmEventType, ref DateTime timeStamp, ref object serviceError)
Used to receive notifications when the method is called.
Enumeration Type Documentation
EddDataTypeEnum
enum Opc.Ua.Fdi7.EddDataTypeEnum strong
<exclude>
Enumerator
BOOLEAN
DOUBLE
FLOAT
INTEGER
UNSIGNED_INTEGER
DATE
DATE_AND_TIME
DURATION
TIME
TIME_VALUE
BIT_ENUMERATED
ENUMERATED
ASCII
BITSTRING
EUC
OCTET
PACKED_ASCII
PASSWORD
VISIBLE
Definition at line 48 of file Opc.Ua.Fdi7.DataTypes.cs.
Function Documentation
AddComponentMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.Fdi7.AddComponentMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, string moduleTypeName, string instanceName, string instanceLabel, ref NodeId instanceNodeId, ref object serviceError)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.Fdi7.AddComponentMethodState.InitializeOptionalChildren().
CommunicationServerTypeInitializeMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.Fdi7.CommunicationServerTypeInitializeMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, ref object serviceError)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.Fdi7.CommunicationServerTypeInitializeMethodState.InitializeOptionalChildren().
CommunicationServerTypeResetMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.Fdi7.CommunicationServerTypeResetMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, ref object serviceError)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.Fdi7.CommunicationServerTypeResetMethodState.InitializeOptionalChildren().
ConnectMethodFFH1MethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.Fdi7.ConnectMethodFFH1MethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, byte [] communicationRelationId, ushort linkId, byte address, int ordinalNumber, bool sIFConnection, uint serviceId, ref uint delayForNextCall, ref object serviceError)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.Fdi7.ConnectMethodFFH1MethodState.InitializeOptionalChildren().
ConnectMethodFFHSEMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.Fdi7.ConnectMethodFFHSEMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, byte [] communicationRelationId, byte [] address, int ordinalNumber, uint serviceId, ref uint delayForNextCall, ref object serviceError)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.Fdi7.ConnectMethodFFHSEMethodState.InitializeOptionalChildren().
ConnectMethodGENERICMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.Fdi7.ConnectMethodGENERICMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, byte [] communicationRelationId, byte [] address, ref object serviceError)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.Fdi7.ConnectMethodGENERICMethodState.InitializeOptionalChildren().
ConnectMethodHARTMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.Fdi7.ConnectMethodHARTMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, byte [] communicationRelationId, byte [] longAddress, ref object serviceError)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.Fdi7.ConnectMethodHARTMethodState.InitializeOptionalChildren().
ConnectMethodISA100_WirelessMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.Fdi7.ConnectMethodISA100_WirelessMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, byte [] communicationRelationId, byte [] iPAddress, uint connectType, ref object serviceError)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.Fdi7.ConnectMethodISA100_WirelessMethodState.InitializeOptionalChildren().
ConnectMethodPROFIBUSMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.Fdi7.ConnectMethodPROFIBUSMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, byte [] communicationRelationId, byte address, ushort manufacturerId, ref object serviceError)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.Fdi7.ConnectMethodPROFIBUSMethodState.InitializeOptionalChildren().
ConnectMethodPROFINETMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.Fdi7.ConnectMethodPROFINETMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, byte [] communicationRelationId, string dNSNAME, ushort deviceID, ushort vendorID, ref object serviceError)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.Fdi7.ConnectMethodPROFINETMethodState.InitializeOptionalChildren().
DisconnectMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.Fdi7.DisconnectMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, byte [] communicationRelationId, ref object serviceError)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.Fdi7.DisconnectMethodState.InitializeOptionalChildren().
GetPublishedDataMethodFFH1MethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.Fdi7.GetPublishedDataMethodFFH1MethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, byte [] communicationRelationId, uint serviceId, ref string blockTag, ref byte [] alarmEventData, ref NodeId alarmEventType, ref DateTime timeStamp, ref uint delayForNextCall, ref object serviceError)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.Fdi7.GetPublishedDataMethodFFH1MethodState.InitializeOptionalChildren().
GetPublishedDataMethodFFHSEMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.Fdi7.GetPublishedDataMethodFFHSEMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, byte [] communicationRelationId, uint serviceId, ref string blockTag, ref byte [] alarmEventData, ref NodeId alarmEventType, ref DateTime timeStamp, ref uint delayForNextCall, ref object serviceError)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.Fdi7.GetPublishedDataMethodFFHSEMethodState.InitializeOptionalChildren().
GetPublishedDataMethodHARTMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.Fdi7.GetPublishedDataMethodHARTMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, byte [] communicationRelationId, ref ushort command, ref byte [] reply, ref DateTime timeStamp, ref object serviceError)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.Fdi7.GetPublishedDataMethodHARTMethodState.InitializeOptionalChildren().
GetPublishedDataMethodISA100_WirelessMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.Fdi7.GetPublishedDataMethodISA100_WirelessMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, byte [] communicationRelationId, ref ushort appID, ref ushort objectID, ref byte [] alarmEventData, ref ushort alarmEventType, ref DateTime timeStamp, ref object serviceError)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.Fdi7.GetPublishedDataMethodISA100_WirelessMethodState.InitializeOptionalChildren().
RemoveComponentMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.Fdi7.RemoveComponentMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, NodeId moduleNodeId, ref object serviceError)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.Fdi7.RemoveComponentMethodState.InitializeOptionalChildren().
ResetScanMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.Fdi7.ResetScanMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, ref object serviceError)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.Fdi7.ResetScanMethodState.InitializeOptionalChildren().
ScanMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.Fdi7.ScanMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, ref XmlElement topologyScanResult, ref object serviceError)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.Fdi7.ScanMethodState.InitializeOptionalChildren().
SetAddressMethodFFH1MethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.Fdi7.SetAddressMethodFFH1MethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, string oPERATION, ushort linkId, byte oldAddress, byte newAddress, string newPDTag, uint serviceId, ref uint delayForNextCall, ref object serviceError)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.Fdi7.SetAddressMethodFFH1MethodState.InitializeOptionalChildren().
SetAddressMethodFFHSEMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.Fdi7.SetAddressMethodFFHSEMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, string oPERATION, string newPDTag, uint serviceId, ref uint delayForNextCall, ref object serviceError)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.Fdi7.SetAddressMethodFFHSEMethodState.InitializeOptionalChildren().
SetAddressMethodGENERICMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.Fdi7.SetAddressMethodGENERICMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, byte [] oldAddress, byte [] newAddress, ref object serviceError)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.Fdi7.SetAddressMethodGENERICMethodState.InitializeOptionalChildren().
SetAddressMethodHARTMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.Fdi7.SetAddressMethodHARTMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, byte oldPollAddress, byte newPollAddress, ref object serviceError)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.Fdi7.SetAddressMethodHARTMethodState.InitializeOptionalChildren().
SetAddressMethodPROFIBUSMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.Fdi7.SetAddressMethodPROFIBUSMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, byte oldAddress, byte newAddress, ref object serviceError)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.Fdi7.SetAddressMethodPROFIBUSMethodState.InitializeOptionalChildren().
SetAddressMethodPROFINETMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.Fdi7.SetAddressMethodPROFINETMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, byte [] mAC, byte [] iP, string dNSNAME, byte [] subnetMask, byte [] gateway, ref object serviceError)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.Fdi7.SetAddressMethodPROFINETMethodState.InitializeOptionalChildren().
TransferMethodFFH1MethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.Fdi7.TransferMethodFFH1MethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, byte [] communicationRelationId, string oPERATION, string blockTag, uint iNDEX, uint sUB_INDEX, byte [] writeData, uint serviceId, ref byte [] readData, ref uint delayForNextCall, ref object serviceError)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.Fdi7.TransferMethodFFH1MethodState.InitializeOptionalChildren().
TransferMethodFFHSEMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.Fdi7.TransferMethodFFHSEMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, byte [] communicationRelationId, string oPERATION, string blockTag, uint iNDEX, uint sUB_INDEX, byte [] writeData, uint serviceId, ref byte [] readData, ref uint delayForNextCall, ref object serviceError)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.Fdi7.TransferMethodFFHSEMethodState.InitializeOptionalChildren().
TransferMethodGENERICMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.Fdi7.TransferMethodGENERICMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, byte [] communicationRelationId, string header, byte [] requestData, EddDataTypeInfo [] requestDataTypes, EddDataTypeInfo [] responseDataTypes, ref byte [] responseData, ref byte [] rESPONSE_CODES, ref object serviceError)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.Fdi7.TransferMethodGENERICMethodState.InitializeOptionalChildren().
TransferMethodHARTMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.Fdi7.TransferMethodHARTMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, byte [] communicationRelationId, ushort command, byte [] request, ref byte [] reply, ref object serviceError)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.Fdi7.TransferMethodHARTMethodState.InitializeOptionalChildren().
TransferMethodISA100_WirelessMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.Fdi7.TransferMethodISA100_WirelessMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, byte [] communicationRelationId, string oPERATION, ushort appID, ushort objectID, ushort attrOrMethID, uint sUB_INDEX, byte [] writeData, uint requestId, ref byte [] readData, ref object serviceError)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.Fdi7.TransferMethodISA100_WirelessMethodState.InitializeOptionalChildren().
TransferMethodPROFIBUSMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.Fdi7.TransferMethodPROFIBUSMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, byte [] communicationRelationId, string oPERATION, byte sLOT, byte iNDEX, byte [] rEQUEST, ref byte [] rEPLY, ref byte [] rESPONSE_CODES, ref object serviceError)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.Fdi7.TransferMethodPROFIBUSMethodState.InitializeOptionalChildren().
TransferMethodPROFINETMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.Fdi7.TransferMethodPROFINETMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, byte [] communicationRelationId, string oPERATION, ushort sLOT, ushort sUBSLOT, ushort iNDEX, uint aPI, byte [] rEQUEST, ref byte [] rEPLY, ref byte [] rESPONSE_CODES, ref object serviceError)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.Fdi7.TransferMethodPROFINETMethodState.InitializeOptionalChildren().