Project Template: Opc.Ua.Fdi5.ApplyResult Class Reference
Opc.Ua.Fdi5.ApplyResult Class Reference
Public Member Functions
ApplyResult ()
The default constructor.
virtual void Encode (IEncoder encoder)
virtual void Decode (IDecoder decoder)
virtual bool IsEqual (IEncodeable encodeable)
virtual object Clone ()
new object MemberwiseClone ()
Properties
int Status [get, set]
TransferIncidentCollection TransferIncidents [get, set]
virtual ExpandedNodeId TypeId [get]
virtual ExpandedNodeId BinaryEncodingId [get]
virtual ExpandedNodeId XmlEncodingId [get]
Detailed Description
<exclude>
Definition at line 1272 of file Opc.Ua.Fdi5.DataTypes.cs.
Constructor & Destructor Documentation
ApplyResult()
Opc.Ua.Fdi5.ApplyResult.ApplyResult () inline
The default constructor.
Definition at line 1278 of file Opc.Ua.Fdi5.DataTypes.cs.
Member Function Documentation
Clone()
virtual object Opc.Ua.Fdi5.ApplyResult.Clone () inline virtual
Definition at line 1398 of file Opc.Ua.Fdi5.DataTypes.cs.
Decode()
virtual void Opc.Ua.Fdi5.ApplyResult.Decode (IDecoder decoder) inline virtual
Definition at line 1365 of file Opc.Ua.Fdi5.DataTypes.cs.
References Opc.Ua.Fdi5.Namespaces.OpcUaFdi5Xsd, and Opc.Ua.Status.
Encode()
virtual void Opc.Ua.Fdi5.ApplyResult.Encode (IEncoder encoder) inline virtual
Definition at line 1354 of file Opc.Ua.Fdi5.DataTypes.cs.
References Opc.Ua.Fdi5.Namespaces.OpcUaFdi5Xsd, and Opc.Ua.Status.
IsEqual()
virtual bool Opc.Ua.Fdi5.ApplyResult.IsEqual (IEncodeable encodeable) inline virtual
Definition at line 1376 of file Opc.Ua.Fdi5.DataTypes.cs.
References Opc.Ua.Object.
MemberwiseClone()
new object Opc.Ua.Fdi5.ApplyResult.MemberwiseClone () inline
Definition at line 1405 of file Opc.Ua.Fdi5.DataTypes.cs.
References Opc.Ua.Fdi5.TransferIncidentCollection.Clone(), Opc.Ua.Fdi5.ApplyResult.MemberwiseClone(), and Opc.Ua.Fdi5.Namespaces.OpcUaFdi5Xsd.
Referenced by Opc.Ua.Fdi5.ApplyResult.MemberwiseClone().
Property Documentation
BinaryEncodingId
virtual ExpandedNodeId Opc.Ua.Fdi5.ApplyResult.BinaryEncodingId get
Definition at line 1343 of file Opc.Ua.Fdi5.DataTypes.cs.
Status
int Opc.Ua.Fdi5.ApplyResult.Status get set
Definition at line 1306 of file Opc.Ua.Fdi5.DataTypes.cs.
TransferIncidents
TransferIncidentCollection Opc.Ua.Fdi5.ApplyResult.TransferIncidents get set
Definition at line 1316 of file Opc.Ua.Fdi5.DataTypes.cs.
TypeId
virtual ExpandedNodeId Opc.Ua.Fdi5.ApplyResult.TypeId get
Definition at line 1337 of file Opc.Ua.Fdi5.DataTypes.cs.
XmlEncodingId
virtual ExpandedNodeId Opc.Ua.Fdi5.ApplyResult.XmlEncodingId get
Definition at line 1349 of file Opc.Ua.Fdi5.DataTypes.cs.
The documentation for this class was generated from the following file:
Opc.Ua.Fdi5.DataTypes.cs