HaSSL: Information_Model::DataWrapper< T > Class Template Reference
Information_Model::DataWrapper< T > Class Template Reference
A generic data type wrapper for various fundemntal types and data containers.
#include <DataWrapper.hpp>
Public Member Functions
DataWrapper (T value)
Constructs a new Data Wrapper object.
T & getValue ()
Returns the contained value object.
Private Member Functions
void setValue (T value)
void throwNoSpecializationImplemented ()
std::string typeName ()
Demangles given type name and returns it as a readable string.
Private Attributes
T value_
Detailed Description
template<class T>
class Information_Model::DataWrapper< T >
A generic data type wrapper for various fundemntal types and data containers.
Template Parameters
T
Author
Dovydas Girdvainis
Date
18.07.2019
Constructor & Destructor Documentation
DataWrapper()
template<class T> Information_Model::DataWrapper< T >::DataWrapper (T value) inline
Constructs a new Data Wrapper object.
Exceptions
std::runtime_error if no specialization for the given type exists
Parameters
value
References Information_Model::DataWrapper< T >::setValue().
Member Function Documentation
getValue()
template<class T> T& Information_Model::DataWrapper< T >::getValue () inline
Returns the contained value object.
Exceptions
std::runtime_error if no specialization for the given type exists
Returns
T&
References Information_Model::DataWrapper< T >::throwNoSpecializationImplemented(), and Information_Model::DataWrapper< T >::value_.
setValue()
template<class T> void Information_Model::DataWrapper< T >::setValue (T value) inline private
References Information_Model::DataWrapper< T >::throwNoSpecializationImplemented().
Referenced by Information_Model::DataWrapper< T >::DataWrapper().
throwNoSpecializationImplemented()
template<class T> void Information_Model::DataWrapper< T >::throwNoSpecializationImplemented () inline private
References Information_Model::DataWrapper< T >::typeName().
Referenced by Information_Model::DataWrapper< T >::getValue(), and Information_Model::DataWrapper< T >::setValue().
typeName()
template<class T> std::string Information_Model::DataWrapper< T >::typeName () inline private
Demangles given type name and returns it as a readable string.
Kudos to Bunkar & M. Dudley ://stackoverflow.com/questions/1055452/c-get-name-of-type-in-template
Referenced by Information_Model::DataWrapper< T >::throwNoSpecializationImplemented().
Field Documentation
value_
template<class T> T Information_Model::DataWrapper< T >::value_ private
Referenced by Information_Model::DataWrapper< T >::getValue(), and Information_Model::DataWrapper< std::string >::getValue().
The documentation for this class was generated from the following file:
DataWrapper.hpp