Project Template: Opc.Ua.NotificationMessage Class Reference
Opc.Ua.NotificationMessage Class Reference
Public Member Functions
NotificationMessage ()
The default constructor.
virtual void Encode (IEncoder encoder)
virtual void Decode (IDecoder decoder)
virtual bool IsEqual (IEncodeable encodeable)
virtual object Clone ()
new object MemberwiseClone ()
Properties
uint SequenceNumber [get, set]
DateTime PublishTime [get, set]
ExtensionObjectCollection NotificationData [get, set]
virtual ExpandedNodeId TypeId [get]
virtual ExpandedNodeId BinaryEncodingId [get]
virtual ExpandedNodeId XmlEncodingId [get]
Detailed Description
<exclude>
Definition at line 57691 of file Opc.Ua.DataTypes.cs.
Constructor & Destructor Documentation
NotificationMessage()
Opc.Ua.NotificationMessage.NotificationMessage () inline
The default constructor.
Definition at line 57697 of file Opc.Ua.DataTypes.cs.
Member Function Documentation
Clone()
virtual object Opc.Ua.NotificationMessage.Clone () inline virtual
Definition at line 57829 of file Opc.Ua.DataTypes.cs.
Referenced by Opc.Ua.PublishResponse.MemberwiseClone(), and Opc.Ua.RepublishResponse.MemberwiseClone().
Decode()
virtual void Opc.Ua.NotificationMessage.Decode (IDecoder decoder) inline virtual
Definition at line 57794 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd, and Opc.Ua.SequenceNumber.
Encode()
virtual void Opc.Ua.NotificationMessage.Encode (IEncoder encoder) inline virtual
Definition at line 57782 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd, and Opc.Ua.SequenceNumber.
IsEqual()
virtual bool Opc.Ua.NotificationMessage.IsEqual (IEncodeable encodeable) inline virtual
Definition at line 57806 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Object.
MemberwiseClone()
new object Opc.Ua.NotificationMessage.MemberwiseClone () inline
Definition at line 57836 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.NotificationMessage.MemberwiseClone(), and Opc.Ua.Namespaces.OpcUaXsd.
Referenced by Opc.Ua.NotificationMessage.MemberwiseClone().
Property Documentation
BinaryEncodingId
virtual ExpandedNodeId Opc.Ua.NotificationMessage.BinaryEncodingId get
Definition at line 57771 of file Opc.Ua.DataTypes.cs.
NotificationData
ExtensionObjectCollection Opc.Ua.NotificationMessage.NotificationData get set
Definition at line 57744 of file Opc.Ua.DataTypes.cs.
PublishTime
DateTime Opc.Ua.NotificationMessage.PublishTime get set
Definition at line 57734 of file Opc.Ua.DataTypes.cs.
SequenceNumber
uint Opc.Ua.NotificationMessage.SequenceNumber get set
Definition at line 57726 of file Opc.Ua.DataTypes.cs.
TypeId
virtual ExpandedNodeId Opc.Ua.NotificationMessage.TypeId get
Definition at line 57765 of file Opc.Ua.DataTypes.cs.
XmlEncodingId
virtual ExpandedNodeId Opc.Ua.NotificationMessage.XmlEncodingId get
Definition at line 57777 of file Opc.Ua.DataTypes.cs.
The documentation for this class was generated from the following file:
Opc.Ua.DataTypes.cs