HaSSL: HaSLL::LoggerRepository Class Reference
HaSLL::LoggerRepository Class Reference
A singleton class that is used for logger creation, registration and global configuration of all register logger severity levels and output pattern.
#include <LoggerRepository.hpp>
Public Member Functions
~LoggerRepository ()
Destroy the Logger Repository object and clean up the logger registery.
Static Public Member Functions
static LoggerRepository & getInstance ()
Get the Instance of C++11 compliant singleton object.
static std::shared_ptr< Logger > registerLoger (const std::string &logger_name)
Creates and registers a logger within the repository.
template<typename T >
static std::shared_ptr< Logger > registerTypedLoger (T type)
Creates and registers a logger based on a given typename.
static void deregisterLoger (const std::string &logger_name)
Removes a given logger from the registery.
static std::shared_ptr< Logger > getLogger (const std::string &logger_name)
Get the Logger object from the repositroy.
static void configure (SeverityLevel level=SeverityLevel::DEBUG, const std::string &logging_pattern="[%Y-%m-%d-%H:%M:%S:%F %z][%n]%^[%l]: %v%$")
Controls logging level and pattern for all of the registered loggers.
static void configurePattern (const std::string &logging_pattern)
Changes the global logging pattern.
template<typename T >
static std::string getTypeName (T type)
returns a demangeled string from a given typename
Private Member Functions
LoggerRepository ()
Constructs an instace of LoggerRepository object with a null sink.
LoggerRepository (const LoggerConfig &config)
Tries to construct an instance of LoggerRepository object with a rotating file sink, named by LOGFILE_NAME, located at LOG_DIR_PATH.
Static Private Member Functions
static void configureUnguardedPattern (const std::string &logging_pattern)
Non threaded call to change the global logging pattern.
static void configureUnguarded (SeverityLevel level)
Non threaded call to change the global logging level.
static std::shared_ptr< Logger > getUnguardedLogger (const std::string &logger_name)
Non threaded call to get a specific logger from the repository.
Static Private Attributes
static std::vector< std::shared_ptr< spdlog::sinks::sink > > sinks_
static std::unordered_map< std::string, std::shared_ptr< Logger > > loggers_
static SeverityLevel global_level_
static std::string previous_pattern_
Detailed Description
A singleton class that is used for logger creation, registration and global configuration of all register logger severity levels and output pattern.
Attention
This singleton implementation is based on c++11 handling of satic field instantiation and is thread safe.
Constructor & Destructor Documentation
~LoggerRepository()
HaSLL::LoggerRepository::~LoggerRepository ()
Destroy the Logger Repository object and clean up the logger registery.
Referenced by getTypeName().
LoggerRepository() [1/2]
HaSLL::LoggerRepository::LoggerRepository () private
Constructs an instace of LoggerRepository object with a null sink.
All logged messages will be descarded
Referenced by getTypeName().
LoggerRepository() [2/2]
HaSLL::LoggerRepository::LoggerRepository (const LoggerConfig & config) private
Tries to construct an instance of LoggerRepository object with a rotating file sink, named by LOGFILE_NAME, located at LOG_DIR_PATH.
Exceptions
std::runtime_error on failled filesink creation.
Parameters
config
Member Function Documentation
configure()
static void HaSLL::LoggerRepository::configure (SeverityLevel level = SeverityLevel::DEBUG, const std::string & logging_pattern = "[%Y-%m-%d-%H:%M:%S:%F %z][%n]%^[%l]: %v%$") static
Controls logging level and pattern for all of the registered loggers.
This method is thread save, if ASYNC_LOGGING is activated.
Parameters
level
logging_pattern
Referenced by registerTypedLoger().
configurePattern()
static void HaSLL::LoggerRepository::configurePattern (const std::string & logging_pattern) static
Changes the global logging pattern.
This method is thread save, if ASYNC_LOGGING is activated.
Parameters
logging_pattern
Referenced by registerTypedLoger().
configureUnguarded()
static void HaSLL::LoggerRepository::configureUnguarded (SeverityLevel level) static private
Non threaded call to change the global logging level.
Parameters
level
Referenced by getTypeName().
configureUnguardedPattern()
static void HaSLL::LoggerRepository::configureUnguardedPattern (const std::string & logging_pattern) static private
Non threaded call to change the global logging pattern.
Parameters
logging_pattern
Referenced by getTypeName().
deregisterLoger()
static void HaSLL::LoggerRepository::deregisterLoger (const std::string & logger_name) static
Removes a given logger from the registery.
Parameters
logger_name
Referenced by registerTypedLoger().
getInstance()
static LoggerRepository& HaSLL::LoggerRepository::getInstance () static
Get the Instance of C++11 compliant singleton object.
This calls the ctor for the LoggerRepository and will try to create a logfile, specified by LOGFILE_NAME, which will be fou in a director,y specified by LOG_DIR_PATH.
LoggerRepository() LoggerRepository(const std::string&,size_t,size_t);
Attention
If for some reasone the logfile creation fails, the default ctor will be called and a message will be logged to standard error stream.
Returns
LoggerRepository&
getLogger()
static std::shared_ptr<Logger> HaSLL::LoggerRepository::getLogger (const std::string & logger_name) static
Get the Logger object from the repositroy.
This method is thread save, if ASYNC_LOGGING is activated.
Parameters
logger_name
Returns
std::shared_ptr<Logger>
Referenced by registerTypedLoger().
getTypeName()
template<typename T > static std::string HaSLL::LoggerRepository::getTypeName (T type) inline static
returns a demangeled string from a given typename
Parameters
T type - templated type
Kudos to Bunkar & M. Dudley from stackoverflow community for this implementation https://stackoverflow.com/questions/1055452/c-get-name-of-type-in-template
References configureUnguarded(), configureUnguardedPattern(), getUnguardedLogger(), LoggerRepository(), and ~LoggerRepository().
Referenced by registerTypedLoger().
getUnguardedLogger()
static std::shared_ptr<Logger> HaSLL::LoggerRepository::getUnguardedLogger (const std::string & logger_name) static private
Non threaded call to get a specific logger from the repository.
Parameters
logger_name
Returns
std::shared_ptr<Logger>
Referenced by getTypeName().
registerLoger()
static std::shared_ptr<Logger> HaSLL::LoggerRepository::registerLoger (const std::string & logger_name) static
Creates and registers a logger within the repository.
This method is thread save, if ASYNC_LOGGING is activated.
Logger
Parameters
logger_name
Returns
std::shared_ptr<Logger>
Referenced by registerTypedLoger().
registerTypedLoger()
template<typename T > static std::shared_ptr<Logger> HaSLL::LoggerRepository::registerTypedLoger (T type) inline static
Creates and registers a logger based on a given typename.
This method is thread save, if ASYNC_LOGGING is activated.
Template Parameters
T
Parameters
type
Returns
std::shared_ptr<Logger>
References configure(), configurePattern(), deregisterLoger(), getLogger(), getTypeName(), and registerLoger().
Field Documentation
global_level_
SeverityLevel HaSLL::LoggerRepository::global_level_ static private
loggers_
std::unordered_map<std::string, std::shared_ptr<Logger> > HaSLL::LoggerRepository::loggers_ static private
previous_pattern_
std::string HaSLL::LoggerRepository::previous_pattern_ static private
sinks_
std::vector<std::shared_ptr<spdlog::sinks::sink> > HaSLL::LoggerRepository::sinks_ static private
The documentation for this class was generated from the following file:
LoggerRepository.hpp