Project Template: Opc.Ua.ReadValueId Class Reference
Opc.Ua.ReadValueId Class Reference
Public Member Functions
ReadValueId ()
The default constructor.
virtual void Encode (IEncoder encoder)
virtual void Decode (IDecoder decoder)
virtual bool IsEqual (IEncodeable encodeable)
virtual object Clone ()
new object MemberwiseClone ()
Properties
NodeId NodeId [get, set]
uint AttributeId [get, set]
string IndexRange [get, set]
QualifiedName DataEncoding [get, set]
virtual ExpandedNodeId TypeId [get]
virtual ExpandedNodeId BinaryEncodingId [get]
virtual ExpandedNodeId XmlEncodingId [get]
Detailed Description
<exclude>
Definition at line 45135 of file Opc.Ua.DataTypes.cs.
Constructor & Destructor Documentation
ReadValueId()
Opc.Ua.ReadValueId.ReadValueId () inline
The default constructor.
Definition at line 45141 of file Opc.Ua.DataTypes.cs.
Member Function Documentation
Clone()
virtual object Opc.Ua.ReadValueId.Clone () inline virtual
Definition at line 45271 of file Opc.Ua.DataTypes.cs.
Referenced by Opc.Ua.MonitoredItemCreateRequest.MemberwiseClone().
Decode()
virtual void Opc.Ua.ReadValueId.Decode (IDecoder decoder) inline virtual
Definition at line 45234 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.NodeId, and Opc.Ua.Namespaces.OpcUaXsd.
Encode()
virtual void Opc.Ua.ReadValueId.Encode (IEncoder encoder) inline virtual
Definition at line 45221 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.NodeId, and Opc.Ua.Namespaces.OpcUaXsd.
IsEqual()
virtual bool Opc.Ua.ReadValueId.IsEqual (IEncodeable encodeable) inline virtual
Definition at line 45247 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Object.
MemberwiseClone()
new object Opc.Ua.ReadValueId.MemberwiseClone () inline
Definition at line 45278 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.ReadValueId.MemberwiseClone(), Opc.Ua.NodeId, and Opc.Ua.Namespaces.OpcUaXsd.
Referenced by Opc.Ua.ReadValueId.MemberwiseClone().
Property Documentation
AttributeId
uint Opc.Ua.ReadValueId.AttributeId get set
Definition at line 45179 of file Opc.Ua.DataTypes.cs.
BinaryEncodingId
virtual ExpandedNodeId Opc.Ua.ReadValueId.BinaryEncodingId get
Definition at line 45210 of file Opc.Ua.DataTypes.cs.
DataEncoding
QualifiedName Opc.Ua.ReadValueId.DataEncoding get set
Definition at line 45195 of file Opc.Ua.DataTypes.cs.
IndexRange
string Opc.Ua.ReadValueId.IndexRange get set
Definition at line 45187 of file Opc.Ua.DataTypes.cs.
NodeId
NodeId Opc.Ua.ReadValueId.NodeId get set
Definition at line 45171 of file Opc.Ua.DataTypes.cs.
TypeId
virtual ExpandedNodeId Opc.Ua.ReadValueId.TypeId get
Definition at line 45204 of file Opc.Ua.DataTypes.cs.
XmlEncodingId
virtual ExpandedNodeId Opc.Ua.ReadValueId.XmlEncodingId get
Definition at line 45216 of file Opc.Ua.DataTypes.cs.
The documentation for this class was generated from the following file:
Opc.Ua.DataTypes.cs