Project Template: Opc.Ua.Range Class Reference
Opc.Ua.Range Class Reference
Public Member Functions
Range ()
The default constructor.
virtual void Encode (IEncoder encoder)
virtual void Decode (IDecoder decoder)
virtual bool IsEqual (IEncodeable encodeable)
virtual object Clone ()
new object MemberwiseClone ()
Properties
double Low [get, set]
double High [get, set]
virtual ExpandedNodeId TypeId [get]
virtual ExpandedNodeId BinaryEncodingId [get]
virtual ExpandedNodeId XmlEncodingId [get]
Detailed Description
<exclude>
Definition at line 66093 of file Opc.Ua.DataTypes.cs.
Constructor & Destructor Documentation
Range()
Opc.Ua.Range.Range () inline
The default constructor.
Definition at line 66099 of file Opc.Ua.DataTypes.cs.
Member Function Documentation
Clone()
virtual object Opc.Ua.Range.Clone () inline virtual
Definition at line 66205 of file Opc.Ua.DataTypes.cs.
Referenced by Opc.Ua.AxisInformation.MemberwiseClone().
Decode()
virtual void Opc.Ua.Range.Decode (IDecoder decoder) inline virtual
Definition at line 66172 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
Encode()
virtual void Opc.Ua.Range.Encode (IEncoder encoder) inline virtual
Definition at line 66161 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
IsEqual()
virtual bool Opc.Ua.Range.IsEqual (IEncodeable encodeable) inline virtual
Definition at line 66183 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Object.
MemberwiseClone()
new object Opc.Ua.Range.MemberwiseClone () inline
Definition at line 66212 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Range.MemberwiseClone(), and Opc.Ua.Namespaces.OpcUaXsd.
Referenced by Opc.Ua.Range.MemberwiseClone().
Property Documentation
BinaryEncodingId
virtual ExpandedNodeId Opc.Ua.Range.BinaryEncodingId get
Definition at line 66150 of file Opc.Ua.DataTypes.cs.
High
double Opc.Ua.Range.High get set
Definition at line 66135 of file Opc.Ua.DataTypes.cs.
Low
double Opc.Ua.Range.Low get set
Definition at line 66127 of file Opc.Ua.DataTypes.cs.
TypeId
virtual ExpandedNodeId Opc.Ua.Range.TypeId get
Definition at line 66144 of file Opc.Ua.DataTypes.cs.
XmlEncodingId
virtual ExpandedNodeId Opc.Ua.Range.XmlEncodingId get
Definition at line 66156 of file Opc.Ua.DataTypes.cs.
The documentation for this class was generated from the following file:
Opc.Ua.DataTypes.cs