Project Template: Opc.Ua.DataTypeIds Class Reference
Opc.Ua.DataTypeIds Class Reference
A class that declares constants for all DataTypes in the Model Design.
Static Public Attributes
static readonly NodeId BaseDataType = new NodeId(Opc.Ua.DataTypes.BaseDataType)
The identifier for the BaseDataType DataType.
static readonly NodeId Number = new NodeId(Opc.Ua.DataTypes.Number)
The identifier for the Number DataType.
static readonly NodeId Integer = new NodeId(Opc.Ua.DataTypes.Integer)
The identifier for the Integer DataType.
static readonly NodeId UInteger = new NodeId(Opc.Ua.DataTypes.UInteger)
The identifier for the UInteger DataType.
static readonly NodeId Enumeration = new NodeId(Opc.Ua.DataTypes.Enumeration)
The identifier for the Enumeration DataType.
static readonly NodeId Boolean = new NodeId(Opc.Ua.DataTypes.Boolean)
The identifier for the Boolean DataType.
static readonly NodeId SByte = new NodeId(Opc.Ua.DataTypes.SByte)
The identifier for the SByte DataType.
static readonly NodeId Byte = new NodeId(Opc.Ua.DataTypes.Byte)
The identifier for the Byte DataType.
static readonly NodeId Int16 = new NodeId(Opc.Ua.DataTypes.Int16)
The identifier for the Int16 DataType.
static readonly NodeId UInt16 = new NodeId(Opc.Ua.DataTypes.UInt16)
The identifier for the UInt16 DataType.
static readonly NodeId Int32 = new NodeId(Opc.Ua.DataTypes.Int32)
The identifier for the Int32 DataType.
static readonly NodeId UInt32 = new NodeId(Opc.Ua.DataTypes.UInt32)
The identifier for the UInt32 DataType.
static readonly NodeId Int64 = new NodeId(Opc.Ua.DataTypes.Int64)
The identifier for the Int64 DataType.
static readonly NodeId UInt64 = new NodeId(Opc.Ua.DataTypes.UInt64)
The identifier for the UInt64 DataType.
static readonly NodeId Float = new NodeId(Opc.Ua.DataTypes.Float)
The identifier for the Float DataType.
static readonly NodeId Double = new NodeId(Opc.Ua.DataTypes.Double)
The identifier for the Double DataType.
static readonly NodeId String = new NodeId(Opc.Ua.DataTypes.String)
The identifier for the String DataType.
static readonly NodeId DateTime = new NodeId(Opc.Ua.DataTypes.DateTime)
The identifier for the DateTime DataType.
static readonly NodeId Guid = new NodeId(Opc.Ua.DataTypes.Guid)
The identifier for the Guid DataType.
static readonly NodeId ByteString = new NodeId(Opc.Ua.DataTypes.ByteString)
The identifier for the ByteString DataType.
static readonly NodeId XmlElement = new NodeId(Opc.Ua.DataTypes.XmlElement)
The identifier for the XmlElement DataType.
static readonly NodeId NodeId = new NodeId(Opc.Ua.DataTypes.NodeId)
The identifier for the NodeId DataType.
static readonly NodeId ExpandedNodeId = new NodeId(Opc.Ua.DataTypes.ExpandedNodeId)
The identifier for the ExpandedNodeId DataType.
static readonly NodeId StatusCode = new NodeId(Opc.Ua.DataTypes.StatusCode)
The identifier for the StatusCode DataType.
static readonly NodeId QualifiedName = new NodeId(Opc.Ua.DataTypes.QualifiedName)
The identifier for the QualifiedName DataType.
static readonly NodeId LocalizedText = new NodeId(Opc.Ua.DataTypes.LocalizedText)
The identifier for the LocalizedText DataType.
static readonly NodeId Structure = new NodeId(Opc.Ua.DataTypes.Structure)
The identifier for the Structure DataType.
static readonly NodeId DataValue = new NodeId(Opc.Ua.DataTypes.DataValue)
The identifier for the DataValue DataType.
static readonly NodeId DiagnosticInfo = new NodeId(Opc.Ua.DataTypes.DiagnosticInfo)
The identifier for the DiagnosticInfo DataType.
static readonly NodeId Image = new NodeId(Opc.Ua.DataTypes.Image)
The identifier for the Image DataType.
static readonly NodeId Decimal = new NodeId(Opc.Ua.DataTypes.Decimal)
The identifier for the Decimal DataType.
static readonly NodeId NamingRuleType = new NodeId(Opc.Ua.DataTypes.NamingRuleType)
The identifier for the NamingRuleType DataType.
static readonly NodeId ImageBMP = new NodeId(Opc.Ua.DataTypes.ImageBMP)
The identifier for the ImageBMP DataType.
static readonly NodeId ImageGIF = new NodeId(Opc.Ua.DataTypes.ImageGIF)
The identifier for the ImageGIF DataType.
static readonly NodeId ImageJPG = new NodeId(Opc.Ua.DataTypes.ImageJPG)
The identifier for the ImageJPG DataType.
static readonly NodeId ImagePNG = new NodeId(Opc.Ua.DataTypes.ImagePNG)
The identifier for the ImagePNG DataType.
static readonly NodeId AudioDataType = new NodeId(Opc.Ua.DataTypes.AudioDataType)
The identifier for the AudioDataType DataType.
static readonly NodeId BitFieldMaskDataType = new NodeId(Opc.Ua.DataTypes.BitFieldMaskDataType)
The identifier for the BitFieldMaskDataType DataType.
static readonly NodeId KeyValuePair = new NodeId(Opc.Ua.DataTypes.KeyValuePair)
The identifier for the KeyValuePair DataType.
static readonly NodeId EndpointType = new NodeId(Opc.Ua.DataTypes.EndpointType)
The identifier for the EndpointType DataType.
static readonly NodeId RationalNumber = new NodeId(Opc.Ua.DataTypes.RationalNumber)
The identifier for the RationalNumber DataType.
static readonly NodeId Vector = new NodeId(Opc.Ua.DataTypes.Vector)
The identifier for the Vector DataType.
static readonly NodeId ThreeDVector = new NodeId(Opc.Ua.DataTypes.ThreeDVector)
The identifier for the ThreeDVector DataType.
static readonly NodeId CartesianCoordinates = new NodeId(Opc.Ua.DataTypes.CartesianCoordinates)
The identifier for the CartesianCoordinates DataType.
static readonly NodeId ThreeDCartesianCoordinates = new NodeId(Opc.Ua.DataTypes.ThreeDCartesianCoordinates)
The identifier for the ThreeDCartesianCoordinates DataType.
static readonly NodeId Orientation = new NodeId(Opc.Ua.DataTypes.Orientation)
The identifier for the Orientation DataType.
static readonly NodeId ThreeDOrientation = new NodeId(Opc.Ua.DataTypes.ThreeDOrientation)
The identifier for the ThreeDOrientation DataType.
static readonly NodeId Frame = new NodeId(Opc.Ua.DataTypes.Frame)
The identifier for the Frame DataType.
static readonly NodeId ThreeDFrame = new NodeId(Opc.Ua.DataTypes.ThreeDFrame)
The identifier for the ThreeDFrame DataType.
static readonly NodeId OpenFileMode = new NodeId(Opc.Ua.DataTypes.OpenFileMode)
The identifier for the OpenFileMode DataType.
static readonly NodeId IdentityCriteriaType = new NodeId(Opc.Ua.DataTypes.IdentityCriteriaType)
The identifier for the IdentityCriteriaType DataType.
static readonly NodeId IdentityMappingRuleType = new NodeId(Opc.Ua.DataTypes.IdentityMappingRuleType)
The identifier for the IdentityMappingRuleType DataType.
static readonly NodeId TrustListMasks = new NodeId(Opc.Ua.DataTypes.TrustListMasks)
The identifier for the TrustListMasks DataType.
static readonly NodeId TrustListDataType = new NodeId(Opc.Ua.DataTypes.TrustListDataType)
The identifier for the TrustListDataType DataType.
static readonly NodeId DecimalDataType = new NodeId(Opc.Ua.DataTypes.DecimalDataType)
The identifier for the DecimalDataType DataType.
static readonly NodeId DataTypeSchemaHeader = new NodeId(Opc.Ua.DataTypes.DataTypeSchemaHeader)
The identifier for the DataTypeSchemaHeader DataType.
static readonly NodeId DataTypeDescription = new NodeId(Opc.Ua.DataTypes.DataTypeDescription)
The identifier for the DataTypeDescription DataType.
static readonly NodeId StructureDescription = new NodeId(Opc.Ua.DataTypes.StructureDescription)
The identifier for the StructureDescription DataType.
static readonly NodeId EnumDescription = new NodeId(Opc.Ua.DataTypes.EnumDescription)
The identifier for the EnumDescription DataType.
static readonly NodeId SimpleTypeDescription = new NodeId(Opc.Ua.DataTypes.SimpleTypeDescription)
The identifier for the SimpleTypeDescription DataType.
static readonly NodeId UABinaryFileDataType = new NodeId(Opc.Ua.DataTypes.UABinaryFileDataType)
The identifier for the UABinaryFileDataType DataType.
static readonly NodeId PubSubState = new NodeId(Opc.Ua.DataTypes.PubSubState)
The identifier for the PubSubState DataType.
static readonly NodeId DataSetMetaDataType = new NodeId(Opc.Ua.DataTypes.DataSetMetaDataType)
The identifier for the DataSetMetaDataType DataType.
static readonly NodeId FieldMetaData = new NodeId(Opc.Ua.DataTypes.FieldMetaData)
The identifier for the FieldMetaData DataType.
static readonly NodeId DataSetFieldFlags = new NodeId(Opc.Ua.DataTypes.DataSetFieldFlags)
The identifier for the DataSetFieldFlags DataType.
static readonly NodeId ConfigurationVersionDataType = new NodeId(Opc.Ua.DataTypes.ConfigurationVersionDataType)
The identifier for the ConfigurationVersionDataType DataType.
static readonly NodeId PublishedDataSetDataType = new NodeId(Opc.Ua.DataTypes.PublishedDataSetDataType)
The identifier for the PublishedDataSetDataType DataType.
static readonly NodeId PublishedDataSetSourceDataType = new NodeId(Opc.Ua.DataTypes.PublishedDataSetSourceDataType)
The identifier for the PublishedDataSetSourceDataType DataType.
static readonly NodeId PublishedVariableDataType = new NodeId(Opc.Ua.DataTypes.PublishedVariableDataType)
The identifier for the PublishedVariableDataType DataType.
static readonly NodeId PublishedDataItemsDataType = new NodeId(Opc.Ua.DataTypes.PublishedDataItemsDataType)
The identifier for the PublishedDataItemsDataType DataType.
static readonly NodeId PublishedEventsDataType = new NodeId(Opc.Ua.DataTypes.PublishedEventsDataType)
The identifier for the PublishedEventsDataType DataType.
static readonly NodeId DataSetFieldContentMask = new NodeId(Opc.Ua.DataTypes.DataSetFieldContentMask)
The identifier for the DataSetFieldContentMask DataType.
static readonly NodeId DataSetWriterDataType = new NodeId(Opc.Ua.DataTypes.DataSetWriterDataType)
The identifier for the DataSetWriterDataType DataType.
static readonly NodeId DataSetWriterTransportDataType = new NodeId(Opc.Ua.DataTypes.DataSetWriterTransportDataType)
The identifier for the DataSetWriterTransportDataType DataType.
static readonly NodeId DataSetWriterMessageDataType = new NodeId(Opc.Ua.DataTypes.DataSetWriterMessageDataType)
The identifier for the DataSetWriterMessageDataType DataType.
static readonly NodeId PubSubGroupDataType = new NodeId(Opc.Ua.DataTypes.PubSubGroupDataType)
The identifier for the PubSubGroupDataType DataType.
static readonly NodeId WriterGroupDataType = new NodeId(Opc.Ua.DataTypes.WriterGroupDataType)
The identifier for the WriterGroupDataType DataType.
static readonly NodeId WriterGroupTransportDataType = new NodeId(Opc.Ua.DataTypes.WriterGroupTransportDataType)
The identifier for the WriterGroupTransportDataType DataType.
static readonly NodeId WriterGroupMessageDataType = new NodeId(Opc.Ua.DataTypes.WriterGroupMessageDataType)
The identifier for the WriterGroupMessageDataType DataType.
static readonly NodeId PubSubConnectionDataType = new NodeId(Opc.Ua.DataTypes.PubSubConnectionDataType)
The identifier for the PubSubConnectionDataType DataType.
static readonly NodeId ConnectionTransportDataType = new NodeId(Opc.Ua.DataTypes.ConnectionTransportDataType)
The identifier for the ConnectionTransportDataType DataType.
static readonly NodeId NetworkAddressDataType = new NodeId(Opc.Ua.DataTypes.NetworkAddressDataType)
The identifier for the NetworkAddressDataType DataType.
static readonly NodeId NetworkAddressUrlDataType = new NodeId(Opc.Ua.DataTypes.NetworkAddressUrlDataType)
The identifier for the NetworkAddressUrlDataType DataType.
static readonly NodeId ReaderGroupDataType = new NodeId(Opc.Ua.DataTypes.ReaderGroupDataType)
The identifier for the ReaderGroupDataType DataType.
static readonly NodeId ReaderGroupTransportDataType = new NodeId(Opc.Ua.DataTypes.ReaderGroupTransportDataType)
The identifier for the ReaderGroupTransportDataType DataType.
static readonly NodeId ReaderGroupMessageDataType = new NodeId(Opc.Ua.DataTypes.ReaderGroupMessageDataType)
The identifier for the ReaderGroupMessageDataType DataType.
static readonly NodeId DataSetReaderDataType = new NodeId(Opc.Ua.DataTypes.DataSetReaderDataType)
The identifier for the DataSetReaderDataType DataType.
static readonly NodeId DataSetReaderTransportDataType = new NodeId(Opc.Ua.DataTypes.DataSetReaderTransportDataType)
The identifier for the DataSetReaderTransportDataType DataType.
static readonly NodeId DataSetReaderMessageDataType = new NodeId(Opc.Ua.DataTypes.DataSetReaderMessageDataType)
The identifier for the DataSetReaderMessageDataType DataType.
static readonly NodeId SubscribedDataSetDataType = new NodeId(Opc.Ua.DataTypes.SubscribedDataSetDataType)
The identifier for the SubscribedDataSetDataType DataType.
static readonly NodeId TargetVariablesDataType = new NodeId(Opc.Ua.DataTypes.TargetVariablesDataType)
The identifier for the TargetVariablesDataType DataType.
static readonly NodeId FieldTargetDataType = new NodeId(Opc.Ua.DataTypes.FieldTargetDataType)
The identifier for the FieldTargetDataType DataType.
static readonly NodeId OverrideValueHandling = new NodeId(Opc.Ua.DataTypes.OverrideValueHandling)
The identifier for the OverrideValueHandling DataType.
static readonly NodeId SubscribedDataSetMirrorDataType = new NodeId(Opc.Ua.DataTypes.SubscribedDataSetMirrorDataType)
The identifier for the SubscribedDataSetMirrorDataType DataType.
static readonly NodeId PubSubConfigurationDataType = new NodeId(Opc.Ua.DataTypes.PubSubConfigurationDataType)
The identifier for the PubSubConfigurationDataType DataType.
static readonly NodeId DataSetOrderingType = new NodeId(Opc.Ua.DataTypes.DataSetOrderingType)
The identifier for the DataSetOrderingType DataType.
static readonly NodeId UadpNetworkMessageContentMask = new NodeId(Opc.Ua.DataTypes.UadpNetworkMessageContentMask)
The identifier for the UadpNetworkMessageContentMask DataType.
static readonly NodeId UadpWriterGroupMessageDataType = new NodeId(Opc.Ua.DataTypes.UadpWriterGroupMessageDataType)
The identifier for the UadpWriterGroupMessageDataType DataType.
static readonly NodeId UadpDataSetMessageContentMask = new NodeId(Opc.Ua.DataTypes.UadpDataSetMessageContentMask)
The identifier for the UadpDataSetMessageContentMask DataType.
static readonly NodeId UadpDataSetWriterMessageDataType = new NodeId(Opc.Ua.DataTypes.UadpDataSetWriterMessageDataType)
The identifier for the UadpDataSetWriterMessageDataType DataType.
static readonly NodeId UadpDataSetReaderMessageDataType = new NodeId(Opc.Ua.DataTypes.UadpDataSetReaderMessageDataType)
The identifier for the UadpDataSetReaderMessageDataType DataType.
static readonly NodeId JsonNetworkMessageContentMask = new NodeId(Opc.Ua.DataTypes.JsonNetworkMessageContentMask)
The identifier for the JsonNetworkMessageContentMask DataType.
static readonly NodeId JsonWriterGroupMessageDataType = new NodeId(Opc.Ua.DataTypes.JsonWriterGroupMessageDataType)
The identifier for the JsonWriterGroupMessageDataType DataType.
static readonly NodeId JsonDataSetMessageContentMask = new NodeId(Opc.Ua.DataTypes.JsonDataSetMessageContentMask)
The identifier for the JsonDataSetMessageContentMask DataType.
static readonly NodeId JsonDataSetWriterMessageDataType = new NodeId(Opc.Ua.DataTypes.JsonDataSetWriterMessageDataType)
The identifier for the JsonDataSetWriterMessageDataType DataType.
static readonly NodeId JsonDataSetReaderMessageDataType = new NodeId(Opc.Ua.DataTypes.JsonDataSetReaderMessageDataType)
The identifier for the JsonDataSetReaderMessageDataType DataType.
static readonly NodeId DatagramConnectionTransportDataType = new NodeId(Opc.Ua.DataTypes.DatagramConnectionTransportDataType)
The identifier for the DatagramConnectionTransportDataType DataType.
static readonly NodeId DatagramWriterGroupTransportDataType = new NodeId(Opc.Ua.DataTypes.DatagramWriterGroupTransportDataType)
The identifier for the DatagramWriterGroupTransportDataType DataType.
static readonly NodeId BrokerConnectionTransportDataType = new NodeId(Opc.Ua.DataTypes.BrokerConnectionTransportDataType)
The identifier for the BrokerConnectionTransportDataType DataType.
static readonly NodeId BrokerTransportQualityOfService = new NodeId(Opc.Ua.DataTypes.BrokerTransportQualityOfService)
The identifier for the BrokerTransportQualityOfService DataType.
static readonly NodeId BrokerWriterGroupTransportDataType = new NodeId(Opc.Ua.DataTypes.BrokerWriterGroupTransportDataType)
The identifier for the BrokerWriterGroupTransportDataType DataType.
static readonly NodeId BrokerDataSetWriterTransportDataType = new NodeId(Opc.Ua.DataTypes.BrokerDataSetWriterTransportDataType)
The identifier for the BrokerDataSetWriterTransportDataType DataType.
static readonly NodeId BrokerDataSetReaderTransportDataType = new NodeId(Opc.Ua.DataTypes.BrokerDataSetReaderTransportDataType)
The identifier for the BrokerDataSetReaderTransportDataType DataType.
static readonly NodeId DiagnosticsLevel = new NodeId(Opc.Ua.DataTypes.DiagnosticsLevel)
The identifier for the DiagnosticsLevel DataType.
static readonly NodeId PubSubDiagnosticsCounterClassification = new NodeId(Opc.Ua.DataTypes.PubSubDiagnosticsCounterClassification)
The identifier for the PubSubDiagnosticsCounterClassification DataType.
static readonly NodeId IdType = new NodeId(Opc.Ua.DataTypes.IdType)
The identifier for the IdType DataType.
static readonly NodeId NodeClass = new NodeId(Opc.Ua.DataTypes.NodeClass)
The identifier for the NodeClass DataType.
static readonly NodeId PermissionType = new NodeId(Opc.Ua.DataTypes.PermissionType)
The identifier for the PermissionType DataType.
static readonly NodeId AccessLevelType = new NodeId(Opc.Ua.DataTypes.AccessLevelType)
The identifier for the AccessLevelType DataType.
static readonly NodeId AccessLevelExType = new NodeId(Opc.Ua.DataTypes.AccessLevelExType)
The identifier for the AccessLevelExType DataType.
static readonly NodeId EventNotifierType = new NodeId(Opc.Ua.DataTypes.EventNotifierType)
The identifier for the EventNotifierType DataType.
static readonly NodeId AccessRestrictionType = new NodeId(Opc.Ua.DataTypes.AccessRestrictionType)
The identifier for the AccessRestrictionType DataType.
static readonly NodeId RolePermissionType = new NodeId(Opc.Ua.DataTypes.RolePermissionType)
The identifier for the RolePermissionType DataType.
static readonly NodeId DataTypeDefinition = new NodeId(Opc.Ua.DataTypes.DataTypeDefinition)
The identifier for the DataTypeDefinition DataType.
static readonly NodeId StructureType = new NodeId(Opc.Ua.DataTypes.StructureType)
The identifier for the StructureType DataType.
static readonly NodeId StructureField = new NodeId(Opc.Ua.DataTypes.StructureField)
The identifier for the StructureField DataType.
static readonly NodeId StructureDefinition = new NodeId(Opc.Ua.DataTypes.StructureDefinition)
The identifier for the StructureDefinition DataType.
static readonly NodeId EnumDefinition = new NodeId(Opc.Ua.DataTypes.EnumDefinition)
The identifier for the EnumDefinition DataType.
static readonly NodeId Node = new NodeId(Opc.Ua.DataTypes.Node)
The identifier for the Node DataType.
static readonly NodeId InstanceNode = new NodeId(Opc.Ua.DataTypes.InstanceNode)
The identifier for the InstanceNode DataType.
static readonly NodeId TypeNode = new NodeId(Opc.Ua.DataTypes.TypeNode)
The identifier for the TypeNode DataType.
static readonly NodeId ObjectNode = new NodeId(Opc.Ua.DataTypes.ObjectNode)
The identifier for the ObjectNode DataType.
static readonly NodeId ObjectTypeNode = new NodeId(Opc.Ua.DataTypes.ObjectTypeNode)
The identifier for the ObjectTypeNode DataType.
static readonly NodeId VariableNode = new NodeId(Opc.Ua.DataTypes.VariableNode)
The identifier for the VariableNode DataType.
static readonly NodeId VariableTypeNode = new NodeId(Opc.Ua.DataTypes.VariableTypeNode)
The identifier for the VariableTypeNode DataType.
static readonly NodeId ReferenceTypeNode = new NodeId(Opc.Ua.DataTypes.ReferenceTypeNode)
The identifier for the ReferenceTypeNode DataType.
static readonly NodeId MethodNode = new NodeId(Opc.Ua.DataTypes.MethodNode)
The identifier for the MethodNode DataType.
static readonly NodeId ViewNode = new NodeId(Opc.Ua.DataTypes.ViewNode)
The identifier for the ViewNode DataType.
static readonly NodeId DataTypeNode = new NodeId(Opc.Ua.DataTypes.DataTypeNode)
The identifier for the DataTypeNode DataType.
static readonly NodeId ReferenceNode = new NodeId(Opc.Ua.DataTypes.ReferenceNode)
The identifier for the ReferenceNode DataType.
static readonly NodeId Argument = new NodeId(Opc.Ua.DataTypes.Argument)
The identifier for the Argument DataType.
static readonly NodeId EnumValueType = new NodeId(Opc.Ua.DataTypes.EnumValueType)
The identifier for the EnumValueType DataType.
static readonly NodeId EnumField = new NodeId(Opc.Ua.DataTypes.EnumField)
The identifier for the EnumField DataType.
static readonly NodeId OptionSet = new NodeId(Opc.Ua.DataTypes.OptionSet)
The identifier for the OptionSet DataType.
static readonly NodeId Union = new NodeId(Opc.Ua.DataTypes.Union)
The identifier for the Union DataType.
static readonly NodeId NormalizedString = new NodeId(Opc.Ua.DataTypes.NormalizedString)
The identifier for the NormalizedString DataType.
static readonly NodeId DecimalString = new NodeId(Opc.Ua.DataTypes.DecimalString)
The identifier for the DecimalString DataType.
static readonly NodeId DurationString = new NodeId(Opc.Ua.DataTypes.DurationString)
The identifier for the DurationString DataType.
static readonly NodeId TimeString = new NodeId(Opc.Ua.DataTypes.TimeString)
The identifier for the TimeString DataType.
static readonly NodeId DateString = new NodeId(Opc.Ua.DataTypes.DateString)
The identifier for the DateString DataType.
static readonly NodeId Duration = new NodeId(Opc.Ua.DataTypes.Duration)
The identifier for the Duration DataType.
static readonly NodeId UtcTime = new NodeId(Opc.Ua.DataTypes.UtcTime)
The identifier for the UtcTime DataType.
static readonly NodeId LocaleId = new NodeId(Opc.Ua.DataTypes.LocaleId)
The identifier for the LocaleId DataType.
static readonly NodeId TimeZoneDataType = new NodeId(Opc.Ua.DataTypes.TimeZoneDataType)
The identifier for the TimeZoneDataType DataType.
static readonly NodeId Index = new NodeId(Opc.Ua.DataTypes.Index)
The identifier for the Index DataType.
static readonly NodeId IntegerId = new NodeId(Opc.Ua.DataTypes.IntegerId)
The identifier for the IntegerId DataType.
static readonly NodeId ApplicationType = new NodeId(Opc.Ua.DataTypes.ApplicationType)
The identifier for the ApplicationType DataType.
static readonly NodeId ApplicationDescription = new NodeId(Opc.Ua.DataTypes.ApplicationDescription)
The identifier for the ApplicationDescription DataType.
static readonly NodeId RequestHeader = new NodeId(Opc.Ua.DataTypes.RequestHeader)
The identifier for the RequestHeader DataType.
static readonly NodeId ResponseHeader = new NodeId(Opc.Ua.DataTypes.ResponseHeader)
The identifier for the ResponseHeader DataType.
static readonly NodeId VersionTime = new NodeId(Opc.Ua.DataTypes.VersionTime)
The identifier for the VersionTime DataType.
static readonly NodeId ServiceFault = new NodeId(Opc.Ua.DataTypes.ServiceFault)
The identifier for the ServiceFault DataType.
static readonly NodeId SessionlessInvokeRequestType = new NodeId(Opc.Ua.DataTypes.SessionlessInvokeRequestType)
The identifier for the SessionlessInvokeRequestType DataType.
static readonly NodeId SessionlessInvokeResponseType = new NodeId(Opc.Ua.DataTypes.SessionlessInvokeResponseType)
The identifier for the SessionlessInvokeResponseType DataType.
static readonly NodeId FindServersRequest = new NodeId(Opc.Ua.DataTypes.FindServersRequest)
The identifier for the FindServersRequest DataType.
static readonly NodeId FindServersResponse = new NodeId(Opc.Ua.DataTypes.FindServersResponse)
The identifier for the FindServersResponse DataType.
static readonly NodeId ServerOnNetwork = new NodeId(Opc.Ua.DataTypes.ServerOnNetwork)
The identifier for the ServerOnNetwork DataType.
static readonly NodeId FindServersOnNetworkRequest = new NodeId(Opc.Ua.DataTypes.FindServersOnNetworkRequest)
The identifier for the FindServersOnNetworkRequest DataType.
static readonly NodeId FindServersOnNetworkResponse = new NodeId(Opc.Ua.DataTypes.FindServersOnNetworkResponse)
The identifier for the FindServersOnNetworkResponse DataType.
static readonly NodeId ApplicationInstanceCertificate = new NodeId(Opc.Ua.DataTypes.ApplicationInstanceCertificate)
The identifier for the ApplicationInstanceCertificate DataType.
static readonly NodeId MessageSecurityMode = new NodeId(Opc.Ua.DataTypes.MessageSecurityMode)
The identifier for the MessageSecurityMode DataType.
static readonly NodeId UserTokenType = new NodeId(Opc.Ua.DataTypes.UserTokenType)
The identifier for the UserTokenType DataType.
static readonly NodeId UserTokenPolicy = new NodeId(Opc.Ua.DataTypes.UserTokenPolicy)
The identifier for the UserTokenPolicy DataType.
static readonly NodeId EndpointDescription = new NodeId(Opc.Ua.DataTypes.EndpointDescription)
The identifier for the EndpointDescription DataType.
static readonly NodeId GetEndpointsRequest = new NodeId(Opc.Ua.DataTypes.GetEndpointsRequest)
The identifier for the GetEndpointsRequest DataType.
static readonly NodeId GetEndpointsResponse = new NodeId(Opc.Ua.DataTypes.GetEndpointsResponse)
The identifier for the GetEndpointsResponse DataType.
static readonly NodeId RegisteredServer = new NodeId(Opc.Ua.DataTypes.RegisteredServer)
The identifier for the RegisteredServer DataType.
static readonly NodeId RegisterServerRequest = new NodeId(Opc.Ua.DataTypes.RegisterServerRequest)
The identifier for the RegisterServerRequest DataType.
static readonly NodeId RegisterServerResponse = new NodeId(Opc.Ua.DataTypes.RegisterServerResponse)
The identifier for the RegisterServerResponse DataType.
static readonly NodeId DiscoveryConfiguration = new NodeId(Opc.Ua.DataTypes.DiscoveryConfiguration)
The identifier for the DiscoveryConfiguration DataType.
static readonly NodeId MdnsDiscoveryConfiguration = new NodeId(Opc.Ua.DataTypes.MdnsDiscoveryConfiguration)
The identifier for the MdnsDiscoveryConfiguration DataType.
static readonly NodeId RegisterServer2Request = new NodeId(Opc.Ua.DataTypes.RegisterServer2Request)
The identifier for the RegisterServer2Request DataType.
static readonly NodeId RegisterServer2Response = new NodeId(Opc.Ua.DataTypes.RegisterServer2Response)
The identifier for the RegisterServer2Response DataType.
static readonly NodeId SecurityTokenRequestType = new NodeId(Opc.Ua.DataTypes.SecurityTokenRequestType)
The identifier for the SecurityTokenRequestType DataType.
static readonly NodeId ChannelSecurityToken = new NodeId(Opc.Ua.DataTypes.ChannelSecurityToken)
The identifier for the ChannelSecurityToken DataType.
static readonly NodeId OpenSecureChannelRequest = new NodeId(Opc.Ua.DataTypes.OpenSecureChannelRequest)
The identifier for the OpenSecureChannelRequest DataType.
static readonly NodeId OpenSecureChannelResponse = new NodeId(Opc.Ua.DataTypes.OpenSecureChannelResponse)
The identifier for the OpenSecureChannelResponse DataType.
static readonly NodeId CloseSecureChannelRequest = new NodeId(Opc.Ua.DataTypes.CloseSecureChannelRequest)
The identifier for the CloseSecureChannelRequest DataType.
static readonly NodeId CloseSecureChannelResponse = new NodeId(Opc.Ua.DataTypes.CloseSecureChannelResponse)
The identifier for the CloseSecureChannelResponse DataType.
static readonly NodeId SignedSoftwareCertificate = new NodeId(Opc.Ua.DataTypes.SignedSoftwareCertificate)
The identifier for the SignedSoftwareCertificate DataType.
static readonly NodeId SessionAuthenticationToken = new NodeId(Opc.Ua.DataTypes.SessionAuthenticationToken)
The identifier for the SessionAuthenticationToken DataType.
static readonly NodeId SignatureData = new NodeId(Opc.Ua.DataTypes.SignatureData)
The identifier for the SignatureData DataType.
static readonly NodeId CreateSessionRequest = new NodeId(Opc.Ua.DataTypes.CreateSessionRequest)
The identifier for the CreateSessionRequest DataType.
static readonly NodeId CreateSessionResponse = new NodeId(Opc.Ua.DataTypes.CreateSessionResponse)
The identifier for the CreateSessionResponse DataType.
static readonly NodeId UserIdentityToken = new NodeId(Opc.Ua.DataTypes.UserIdentityToken)
The identifier for the UserIdentityToken DataType.
static readonly NodeId AnonymousIdentityToken = new NodeId(Opc.Ua.DataTypes.AnonymousIdentityToken)
The identifier for the AnonymousIdentityToken DataType.
static readonly NodeId UserNameIdentityToken = new NodeId(Opc.Ua.DataTypes.UserNameIdentityToken)
The identifier for the UserNameIdentityToken DataType.
static readonly NodeId X509IdentityToken = new NodeId(Opc.Ua.DataTypes.X509IdentityToken)
The identifier for the X509IdentityToken DataType.
static readonly NodeId IssuedIdentityToken = new NodeId(Opc.Ua.DataTypes.IssuedIdentityToken)
The identifier for the IssuedIdentityToken DataType.
static readonly NodeId RsaEncryptedSecret = new NodeId(Opc.Ua.DataTypes.RsaEncryptedSecret)
The identifier for the RsaEncryptedSecret DataType.
static readonly NodeId ActivateSessionRequest = new NodeId(Opc.Ua.DataTypes.ActivateSessionRequest)
The identifier for the ActivateSessionRequest DataType.
static readonly NodeId ActivateSessionResponse = new NodeId(Opc.Ua.DataTypes.ActivateSessionResponse)
The identifier for the ActivateSessionResponse DataType.
static readonly NodeId CloseSessionRequest = new NodeId(Opc.Ua.DataTypes.CloseSessionRequest)
The identifier for the CloseSessionRequest DataType.
static readonly NodeId CloseSessionResponse = new NodeId(Opc.Ua.DataTypes.CloseSessionResponse)
The identifier for the CloseSessionResponse DataType.
static readonly NodeId CancelRequest = new NodeId(Opc.Ua.DataTypes.CancelRequest)
The identifier for the CancelRequest DataType.
static readonly NodeId CancelResponse = new NodeId(Opc.Ua.DataTypes.CancelResponse)
The identifier for the CancelResponse DataType.
static readonly NodeId NodeAttributesMask = new NodeId(Opc.Ua.DataTypes.NodeAttributesMask)
The identifier for the NodeAttributesMask DataType.
static readonly NodeId NodeAttributes = new NodeId(Opc.Ua.DataTypes.NodeAttributes)
The identifier for the NodeAttributes DataType.
static readonly NodeId ObjectAttributes = new NodeId(Opc.Ua.DataTypes.ObjectAttributes)
The identifier for the ObjectAttributes DataType.
static readonly NodeId VariableAttributes = new NodeId(Opc.Ua.DataTypes.VariableAttributes)
The identifier for the VariableAttributes DataType.
static readonly NodeId MethodAttributes = new NodeId(Opc.Ua.DataTypes.MethodAttributes)
The identifier for the MethodAttributes DataType.
static readonly NodeId ObjectTypeAttributes = new NodeId(Opc.Ua.DataTypes.ObjectTypeAttributes)
The identifier for the ObjectTypeAttributes DataType.
static readonly NodeId VariableTypeAttributes = new NodeId(Opc.Ua.DataTypes.VariableTypeAttributes)
The identifier for the VariableTypeAttributes DataType.
static readonly NodeId ReferenceTypeAttributes = new NodeId(Opc.Ua.DataTypes.ReferenceTypeAttributes)
The identifier for the ReferenceTypeAttributes DataType.
static readonly NodeId DataTypeAttributes = new NodeId(Opc.Ua.DataTypes.DataTypeAttributes)
The identifier for the DataTypeAttributes DataType.
static readonly NodeId ViewAttributes = new NodeId(Opc.Ua.DataTypes.ViewAttributes)
The identifier for the ViewAttributes DataType.
static readonly NodeId GenericAttributeValue = new NodeId(Opc.Ua.DataTypes.GenericAttributeValue)
The identifier for the GenericAttributeValue DataType.
static readonly NodeId GenericAttributes = new NodeId(Opc.Ua.DataTypes.GenericAttributes)
The identifier for the GenericAttributes DataType.
static readonly NodeId AddNodesItem = new NodeId(Opc.Ua.DataTypes.AddNodesItem)
The identifier for the AddNodesItem DataType.
static readonly NodeId AddNodesResult = new NodeId(Opc.Ua.DataTypes.AddNodesResult)
The identifier for the AddNodesResult DataType.
static readonly NodeId AddNodesRequest = new NodeId(Opc.Ua.DataTypes.AddNodesRequest)
The identifier for the AddNodesRequest DataType.
static readonly NodeId AddNodesResponse = new NodeId(Opc.Ua.DataTypes.AddNodesResponse)
The identifier for the AddNodesResponse DataType.
static readonly NodeId AddReferencesItem = new NodeId(Opc.Ua.DataTypes.AddReferencesItem)
The identifier for the AddReferencesItem DataType.
static readonly NodeId AddReferencesRequest = new NodeId(Opc.Ua.DataTypes.AddReferencesRequest)
The identifier for the AddReferencesRequest DataType.
static readonly NodeId AddReferencesResponse = new NodeId(Opc.Ua.DataTypes.AddReferencesResponse)
The identifier for the AddReferencesResponse DataType.
static readonly NodeId DeleteNodesItem = new NodeId(Opc.Ua.DataTypes.DeleteNodesItem)
The identifier for the DeleteNodesItem DataType.
static readonly NodeId DeleteNodesRequest = new NodeId(Opc.Ua.DataTypes.DeleteNodesRequest)
The identifier for the DeleteNodesRequest DataType.
static readonly NodeId DeleteNodesResponse = new NodeId(Opc.Ua.DataTypes.DeleteNodesResponse)
The identifier for the DeleteNodesResponse DataType.
static readonly NodeId DeleteReferencesItem = new NodeId(Opc.Ua.DataTypes.DeleteReferencesItem)
The identifier for the DeleteReferencesItem DataType.
static readonly NodeId DeleteReferencesRequest = new NodeId(Opc.Ua.DataTypes.DeleteReferencesRequest)
The identifier for the DeleteReferencesRequest DataType.
static readonly NodeId DeleteReferencesResponse = new NodeId(Opc.Ua.DataTypes.DeleteReferencesResponse)
The identifier for the DeleteReferencesResponse DataType.
static readonly NodeId AttributeWriteMask = new NodeId(Opc.Ua.DataTypes.AttributeWriteMask)
The identifier for the AttributeWriteMask DataType.
static readonly NodeId BrowseDirection = new NodeId(Opc.Ua.DataTypes.BrowseDirection)
The identifier for the BrowseDirection DataType.
static readonly NodeId ViewDescription = new NodeId(Opc.Ua.DataTypes.ViewDescription)
The identifier for the ViewDescription DataType.
static readonly NodeId BrowseDescription = new NodeId(Opc.Ua.DataTypes.BrowseDescription)
The identifier for the BrowseDescription DataType.
static readonly NodeId BrowseResultMask = new NodeId(Opc.Ua.DataTypes.BrowseResultMask)
The identifier for the BrowseResultMask DataType.
static readonly NodeId ReferenceDescription = new NodeId(Opc.Ua.DataTypes.ReferenceDescription)
The identifier for the ReferenceDescription DataType.
static readonly NodeId ContinuationPoint = new NodeId(Opc.Ua.DataTypes.ContinuationPoint)
The identifier for the ContinuationPoint DataType.
static readonly NodeId BrowseResult = new NodeId(Opc.Ua.DataTypes.BrowseResult)
The identifier for the BrowseResult DataType.
static readonly NodeId BrowseRequest = new NodeId(Opc.Ua.DataTypes.BrowseRequest)
The identifier for the BrowseRequest DataType.
static readonly NodeId BrowseResponse = new NodeId(Opc.Ua.DataTypes.BrowseResponse)
The identifier for the BrowseResponse DataType.
static readonly NodeId BrowseNextRequest = new NodeId(Opc.Ua.DataTypes.BrowseNextRequest)
The identifier for the BrowseNextRequest DataType.
static readonly NodeId BrowseNextResponse = new NodeId(Opc.Ua.DataTypes.BrowseNextResponse)
The identifier for the BrowseNextResponse DataType.
static readonly NodeId RelativePathElement = new NodeId(Opc.Ua.DataTypes.RelativePathElement)
The identifier for the RelativePathElement DataType.
static readonly NodeId RelativePath = new NodeId(Opc.Ua.DataTypes.RelativePath)
The identifier for the RelativePath DataType.
static readonly NodeId BrowsePath = new NodeId(Opc.Ua.DataTypes.BrowsePath)
The identifier for the BrowsePath DataType.
static readonly NodeId BrowsePathTarget = new NodeId(Opc.Ua.DataTypes.BrowsePathTarget)
The identifier for the BrowsePathTarget DataType.
static readonly NodeId BrowsePathResult = new NodeId(Opc.Ua.DataTypes.BrowsePathResult)
The identifier for the BrowsePathResult DataType.
static readonly NodeId TranslateBrowsePathsToNodeIdsRequest = new NodeId(Opc.Ua.DataTypes.TranslateBrowsePathsToNodeIdsRequest)
The identifier for the TranslateBrowsePathsToNodeIdsRequest DataType.
static readonly NodeId TranslateBrowsePathsToNodeIdsResponse = new NodeId(Opc.Ua.DataTypes.TranslateBrowsePathsToNodeIdsResponse)
The identifier for the TranslateBrowsePathsToNodeIdsResponse DataType.
static readonly NodeId RegisterNodesRequest = new NodeId(Opc.Ua.DataTypes.RegisterNodesRequest)
The identifier for the RegisterNodesRequest DataType.
static readonly NodeId RegisterNodesResponse = new NodeId(Opc.Ua.DataTypes.RegisterNodesResponse)
The identifier for the RegisterNodesResponse DataType.
static readonly NodeId UnregisterNodesRequest = new NodeId(Opc.Ua.DataTypes.UnregisterNodesRequest)
The identifier for the UnregisterNodesRequest DataType.
static readonly NodeId UnregisterNodesResponse = new NodeId(Opc.Ua.DataTypes.UnregisterNodesResponse)
The identifier for the UnregisterNodesResponse DataType.
static readonly NodeId Counter = new NodeId(Opc.Ua.DataTypes.Counter)
The identifier for the Counter DataType.
static readonly NodeId NumericRange = new NodeId(Opc.Ua.DataTypes.NumericRange)
The identifier for the NumericRange DataType.
static readonly NodeId Time = new NodeId(Opc.Ua.DataTypes.Time)
The identifier for the Time DataType.
static readonly NodeId Date = new NodeId(Opc.Ua.DataTypes.Date)
The identifier for the Date DataType.
static readonly NodeId EndpointConfiguration = new NodeId(Opc.Ua.DataTypes.EndpointConfiguration)
The identifier for the EndpointConfiguration DataType.
static readonly NodeId QueryDataDescription = new NodeId(Opc.Ua.DataTypes.QueryDataDescription)
The identifier for the QueryDataDescription DataType.
static readonly NodeId NodeTypeDescription = new NodeId(Opc.Ua.DataTypes.NodeTypeDescription)
The identifier for the NodeTypeDescription DataType.
static readonly NodeId FilterOperator = new NodeId(Opc.Ua.DataTypes.FilterOperator)
The identifier for the FilterOperator DataType.
static readonly NodeId QueryDataSet = new NodeId(Opc.Ua.DataTypes.QueryDataSet)
The identifier for the QueryDataSet DataType.
static readonly NodeId NodeReference = new NodeId(Opc.Ua.DataTypes.NodeReference)
The identifier for the NodeReference DataType.
static readonly NodeId ContentFilterElement = new NodeId(Opc.Ua.DataTypes.ContentFilterElement)
The identifier for the ContentFilterElement DataType.
static readonly NodeId ContentFilter = new NodeId(Opc.Ua.DataTypes.ContentFilter)
The identifier for the ContentFilter DataType.
static readonly NodeId FilterOperand = new NodeId(Opc.Ua.DataTypes.FilterOperand)
The identifier for the FilterOperand DataType.
static readonly NodeId ElementOperand = new NodeId(Opc.Ua.DataTypes.ElementOperand)
The identifier for the ElementOperand DataType.
static readonly NodeId LiteralOperand = new NodeId(Opc.Ua.DataTypes.LiteralOperand)
The identifier for the LiteralOperand DataType.
static readonly NodeId AttributeOperand = new NodeId(Opc.Ua.DataTypes.AttributeOperand)
The identifier for the AttributeOperand DataType.
static readonly NodeId SimpleAttributeOperand = new NodeId(Opc.Ua.DataTypes.SimpleAttributeOperand)
The identifier for the SimpleAttributeOperand DataType.
static readonly NodeId ContentFilterElementResult = new NodeId(Opc.Ua.DataTypes.ContentFilterElementResult)
The identifier for the ContentFilterElementResult DataType.
static readonly NodeId ContentFilterResult = new NodeId(Opc.Ua.DataTypes.ContentFilterResult)
The identifier for the ContentFilterResult DataType.
static readonly NodeId ParsingResult = new NodeId(Opc.Ua.DataTypes.ParsingResult)
The identifier for the ParsingResult DataType.
static readonly NodeId QueryFirstRequest = new NodeId(Opc.Ua.DataTypes.QueryFirstRequest)
The identifier for the QueryFirstRequest DataType.
static readonly NodeId QueryFirstResponse = new NodeId(Opc.Ua.DataTypes.QueryFirstResponse)
The identifier for the QueryFirstResponse DataType.
static readonly NodeId QueryNextRequest = new NodeId(Opc.Ua.DataTypes.QueryNextRequest)
The identifier for the QueryNextRequest DataType.
static readonly NodeId QueryNextResponse = new NodeId(Opc.Ua.DataTypes.QueryNextResponse)
The identifier for the QueryNextResponse DataType.
static readonly NodeId TimestampsToReturn = new NodeId(Opc.Ua.DataTypes.TimestampsToReturn)
The identifier for the TimestampsToReturn DataType.
static readonly NodeId ReadValueId = new NodeId(Opc.Ua.DataTypes.ReadValueId)
The identifier for the ReadValueId DataType.
static readonly NodeId ReadRequest = new NodeId(Opc.Ua.DataTypes.ReadRequest)
The identifier for the ReadRequest DataType.
static readonly NodeId ReadResponse = new NodeId(Opc.Ua.DataTypes.ReadResponse)
The identifier for the ReadResponse DataType.
static readonly NodeId HistoryReadValueId = new NodeId(Opc.Ua.DataTypes.HistoryReadValueId)
The identifier for the HistoryReadValueId DataType.
static readonly NodeId HistoryReadResult = new NodeId(Opc.Ua.DataTypes.HistoryReadResult)
The identifier for the HistoryReadResult DataType.
static readonly NodeId HistoryReadDetails = new NodeId(Opc.Ua.DataTypes.HistoryReadDetails)
The identifier for the HistoryReadDetails DataType.
static readonly NodeId ReadEventDetails = new NodeId(Opc.Ua.DataTypes.ReadEventDetails)
The identifier for the ReadEventDetails DataType.
static readonly NodeId ReadRawModifiedDetails = new NodeId(Opc.Ua.DataTypes.ReadRawModifiedDetails)
The identifier for the ReadRawModifiedDetails DataType.
static readonly NodeId ReadProcessedDetails = new NodeId(Opc.Ua.DataTypes.ReadProcessedDetails)
The identifier for the ReadProcessedDetails DataType.
static readonly NodeId ReadAtTimeDetails = new NodeId(Opc.Ua.DataTypes.ReadAtTimeDetails)
The identifier for the ReadAtTimeDetails DataType.
static readonly NodeId HistoryData = new NodeId(Opc.Ua.DataTypes.HistoryData)
The identifier for the HistoryData DataType.
static readonly NodeId ModificationInfo = new NodeId(Opc.Ua.DataTypes.ModificationInfo)
The identifier for the ModificationInfo DataType.
static readonly NodeId HistoryModifiedData = new NodeId(Opc.Ua.DataTypes.HistoryModifiedData)
The identifier for the HistoryModifiedData DataType.
static readonly NodeId HistoryEvent = new NodeId(Opc.Ua.DataTypes.HistoryEvent)
The identifier for the HistoryEvent DataType.
static readonly NodeId HistoryReadRequest = new NodeId(Opc.Ua.DataTypes.HistoryReadRequest)
The identifier for the HistoryReadRequest DataType.
static readonly NodeId HistoryReadResponse = new NodeId(Opc.Ua.DataTypes.HistoryReadResponse)
The identifier for the HistoryReadResponse DataType.
static readonly NodeId WriteValue = new NodeId(Opc.Ua.DataTypes.WriteValue)
The identifier for the WriteValue DataType.
static readonly NodeId WriteRequest = new NodeId(Opc.Ua.DataTypes.WriteRequest)
The identifier for the WriteRequest DataType.
static readonly NodeId WriteResponse = new NodeId(Opc.Ua.DataTypes.WriteResponse)
The identifier for the WriteResponse DataType.
static readonly NodeId HistoryUpdateDetails = new NodeId(Opc.Ua.DataTypes.HistoryUpdateDetails)
The identifier for the HistoryUpdateDetails DataType.
static readonly NodeId HistoryUpdateType = new NodeId(Opc.Ua.DataTypes.HistoryUpdateType)
The identifier for the HistoryUpdateType DataType.
static readonly NodeId PerformUpdateType = new NodeId(Opc.Ua.DataTypes.PerformUpdateType)
The identifier for the PerformUpdateType DataType.
static readonly NodeId UpdateDataDetails = new NodeId(Opc.Ua.DataTypes.UpdateDataDetails)
The identifier for the UpdateDataDetails DataType.
static readonly NodeId UpdateStructureDataDetails = new NodeId(Opc.Ua.DataTypes.UpdateStructureDataDetails)
The identifier for the UpdateStructureDataDetails DataType.
static readonly NodeId UpdateEventDetails = new NodeId(Opc.Ua.DataTypes.UpdateEventDetails)
The identifier for the UpdateEventDetails DataType.
static readonly NodeId DeleteRawModifiedDetails = new NodeId(Opc.Ua.DataTypes.DeleteRawModifiedDetails)
The identifier for the DeleteRawModifiedDetails DataType.
static readonly NodeId DeleteAtTimeDetails = new NodeId(Opc.Ua.DataTypes.DeleteAtTimeDetails)
The identifier for the DeleteAtTimeDetails DataType.
static readonly NodeId DeleteEventDetails = new NodeId(Opc.Ua.DataTypes.DeleteEventDetails)
The identifier for the DeleteEventDetails DataType.
static readonly NodeId HistoryUpdateResult = new NodeId(Opc.Ua.DataTypes.HistoryUpdateResult)
The identifier for the HistoryUpdateResult DataType.
static readonly NodeId HistoryUpdateRequest = new NodeId(Opc.Ua.DataTypes.HistoryUpdateRequest)
The identifier for the HistoryUpdateRequest DataType.
static readonly NodeId HistoryUpdateResponse = new NodeId(Opc.Ua.DataTypes.HistoryUpdateResponse)
The identifier for the HistoryUpdateResponse DataType.
static readonly NodeId CallMethodRequest = new NodeId(Opc.Ua.DataTypes.CallMethodRequest)
The identifier for the CallMethodRequest DataType.
static readonly NodeId CallMethodResult = new NodeId(Opc.Ua.DataTypes.CallMethodResult)
The identifier for the CallMethodResult DataType.
static readonly NodeId CallRequest = new NodeId(Opc.Ua.DataTypes.CallRequest)
The identifier for the CallRequest DataType.
static readonly NodeId CallResponse = new NodeId(Opc.Ua.DataTypes.CallResponse)
The identifier for the CallResponse DataType.
static readonly NodeId MonitoringMode = new NodeId(Opc.Ua.DataTypes.MonitoringMode)
The identifier for the MonitoringMode DataType.
static readonly NodeId DataChangeTrigger = new NodeId(Opc.Ua.DataTypes.DataChangeTrigger)
The identifier for the DataChangeTrigger DataType.
static readonly NodeId DeadbandType = new NodeId(Opc.Ua.DataTypes.DeadbandType)
The identifier for the DeadbandType DataType.
static readonly NodeId MonitoringFilter = new NodeId(Opc.Ua.DataTypes.MonitoringFilter)
The identifier for the MonitoringFilter DataType.
static readonly NodeId DataChangeFilter = new NodeId(Opc.Ua.DataTypes.DataChangeFilter)
The identifier for the DataChangeFilter DataType.
static readonly NodeId EventFilter = new NodeId(Opc.Ua.DataTypes.EventFilter)
The identifier for the EventFilter DataType.
static readonly NodeId AggregateConfiguration = new NodeId(Opc.Ua.DataTypes.AggregateConfiguration)
The identifier for the AggregateConfiguration DataType.
static readonly NodeId AggregateFilter = new NodeId(Opc.Ua.DataTypes.AggregateFilter)
The identifier for the AggregateFilter DataType.
static readonly NodeId MonitoringFilterResult = new NodeId(Opc.Ua.DataTypes.MonitoringFilterResult)
The identifier for the MonitoringFilterResult DataType.
static readonly NodeId EventFilterResult = new NodeId(Opc.Ua.DataTypes.EventFilterResult)
The identifier for the EventFilterResult DataType.
static readonly NodeId AggregateFilterResult = new NodeId(Opc.Ua.DataTypes.AggregateFilterResult)
The identifier for the AggregateFilterResult DataType.
static readonly NodeId MonitoringParameters = new NodeId(Opc.Ua.DataTypes.MonitoringParameters)
The identifier for the MonitoringParameters DataType.
static readonly NodeId MonitoredItemCreateRequest = new NodeId(Opc.Ua.DataTypes.MonitoredItemCreateRequest)
The identifier for the MonitoredItemCreateRequest DataType.
static readonly NodeId MonitoredItemCreateResult = new NodeId(Opc.Ua.DataTypes.MonitoredItemCreateResult)
The identifier for the MonitoredItemCreateResult DataType.
static readonly NodeId CreateMonitoredItemsRequest = new NodeId(Opc.Ua.DataTypes.CreateMonitoredItemsRequest)
The identifier for the CreateMonitoredItemsRequest DataType.
static readonly NodeId CreateMonitoredItemsResponse = new NodeId(Opc.Ua.DataTypes.CreateMonitoredItemsResponse)
The identifier for the CreateMonitoredItemsResponse DataType.
static readonly NodeId MonitoredItemModifyRequest = new NodeId(Opc.Ua.DataTypes.MonitoredItemModifyRequest)
The identifier for the MonitoredItemModifyRequest DataType.
static readonly NodeId MonitoredItemModifyResult = new NodeId(Opc.Ua.DataTypes.MonitoredItemModifyResult)
The identifier for the MonitoredItemModifyResult DataType.
static readonly NodeId ModifyMonitoredItemsRequest = new NodeId(Opc.Ua.DataTypes.ModifyMonitoredItemsRequest)
The identifier for the ModifyMonitoredItemsRequest DataType.
static readonly NodeId ModifyMonitoredItemsResponse = new NodeId(Opc.Ua.DataTypes.ModifyMonitoredItemsResponse)
The identifier for the ModifyMonitoredItemsResponse DataType.
static readonly NodeId SetMonitoringModeRequest = new NodeId(Opc.Ua.DataTypes.SetMonitoringModeRequest)
The identifier for the SetMonitoringModeRequest DataType.
static readonly NodeId SetMonitoringModeResponse = new NodeId(Opc.Ua.DataTypes.SetMonitoringModeResponse)
The identifier for the SetMonitoringModeResponse DataType.
static readonly NodeId SetTriggeringRequest = new NodeId(Opc.Ua.DataTypes.SetTriggeringRequest)
The identifier for the SetTriggeringRequest DataType.
static readonly NodeId SetTriggeringResponse = new NodeId(Opc.Ua.DataTypes.SetTriggeringResponse)
The identifier for the SetTriggeringResponse DataType.
static readonly NodeId DeleteMonitoredItemsRequest = new NodeId(Opc.Ua.DataTypes.DeleteMonitoredItemsRequest)
The identifier for the DeleteMonitoredItemsRequest DataType.
static readonly NodeId DeleteMonitoredItemsResponse = new NodeId(Opc.Ua.DataTypes.DeleteMonitoredItemsResponse)
The identifier for the DeleteMonitoredItemsResponse DataType.
static readonly NodeId CreateSubscriptionRequest = new NodeId(Opc.Ua.DataTypes.CreateSubscriptionRequest)
The identifier for the CreateSubscriptionRequest DataType.
static readonly NodeId CreateSubscriptionResponse = new NodeId(Opc.Ua.DataTypes.CreateSubscriptionResponse)
The identifier for the CreateSubscriptionResponse DataType.
static readonly NodeId ModifySubscriptionRequest = new NodeId(Opc.Ua.DataTypes.ModifySubscriptionRequest)
The identifier for the ModifySubscriptionRequest DataType.
static readonly NodeId ModifySubscriptionResponse = new NodeId(Opc.Ua.DataTypes.ModifySubscriptionResponse)
The identifier for the ModifySubscriptionResponse DataType.
static readonly NodeId SetPublishingModeRequest = new NodeId(Opc.Ua.DataTypes.SetPublishingModeRequest)
The identifier for the SetPublishingModeRequest DataType.
static readonly NodeId SetPublishingModeResponse = new NodeId(Opc.Ua.DataTypes.SetPublishingModeResponse)
The identifier for the SetPublishingModeResponse DataType.
static readonly NodeId NotificationMessage = new NodeId(Opc.Ua.DataTypes.NotificationMessage)
The identifier for the NotificationMessage DataType.
static readonly NodeId NotificationData = new NodeId(Opc.Ua.DataTypes.NotificationData)
The identifier for the NotificationData DataType.
static readonly NodeId DataChangeNotification = new NodeId(Opc.Ua.DataTypes.DataChangeNotification)
The identifier for the DataChangeNotification DataType.
static readonly NodeId MonitoredItemNotification = new NodeId(Opc.Ua.DataTypes.MonitoredItemNotification)
The identifier for the MonitoredItemNotification DataType.
static readonly NodeId EventNotificationList = new NodeId(Opc.Ua.DataTypes.EventNotificationList)
The identifier for the EventNotificationList DataType.
static readonly NodeId EventFieldList = new NodeId(Opc.Ua.DataTypes.EventFieldList)
The identifier for the EventFieldList DataType.
static readonly NodeId HistoryEventFieldList = new NodeId(Opc.Ua.DataTypes.HistoryEventFieldList)
The identifier for the HistoryEventFieldList DataType.
static readonly NodeId StatusChangeNotification = new NodeId(Opc.Ua.DataTypes.StatusChangeNotification)
The identifier for the StatusChangeNotification DataType.
static readonly NodeId SubscriptionAcknowledgement = new NodeId(Opc.Ua.DataTypes.SubscriptionAcknowledgement)
The identifier for the SubscriptionAcknowledgement DataType.
static readonly NodeId PublishRequest = new NodeId(Opc.Ua.DataTypes.PublishRequest)
The identifier for the PublishRequest DataType.
static readonly NodeId PublishResponse = new NodeId(Opc.Ua.DataTypes.PublishResponse)
The identifier for the PublishResponse DataType.
static readonly NodeId RepublishRequest = new NodeId(Opc.Ua.DataTypes.RepublishRequest)
The identifier for the RepublishRequest DataType.
static readonly NodeId RepublishResponse = new NodeId(Opc.Ua.DataTypes.RepublishResponse)
The identifier for the RepublishResponse DataType.
static readonly NodeId TransferResult = new NodeId(Opc.Ua.DataTypes.TransferResult)
The identifier for the TransferResult DataType.
static readonly NodeId TransferSubscriptionsRequest = new NodeId(Opc.Ua.DataTypes.TransferSubscriptionsRequest)
The identifier for the TransferSubscriptionsRequest DataType.
static readonly NodeId TransferSubscriptionsResponse = new NodeId(Opc.Ua.DataTypes.TransferSubscriptionsResponse)
The identifier for the TransferSubscriptionsResponse DataType.
static readonly NodeId DeleteSubscriptionsRequest = new NodeId(Opc.Ua.DataTypes.DeleteSubscriptionsRequest)
The identifier for the DeleteSubscriptionsRequest DataType.
static readonly NodeId DeleteSubscriptionsResponse = new NodeId(Opc.Ua.DataTypes.DeleteSubscriptionsResponse)
The identifier for the DeleteSubscriptionsResponse DataType.
static readonly NodeId BuildInfo = new NodeId(Opc.Ua.DataTypes.BuildInfo)
The identifier for the BuildInfo DataType.
static readonly NodeId RedundancySupport = new NodeId(Opc.Ua.DataTypes.RedundancySupport)
The identifier for the RedundancySupport DataType.
static readonly NodeId ServerState = new NodeId(Opc.Ua.DataTypes.ServerState)
The identifier for the ServerState DataType.
static readonly NodeId RedundantServerDataType = new NodeId(Opc.Ua.DataTypes.RedundantServerDataType)
The identifier for the RedundantServerDataType DataType.
static readonly NodeId EndpointUrlListDataType = new NodeId(Opc.Ua.DataTypes.EndpointUrlListDataType)
The identifier for the EndpointUrlListDataType DataType.
static readonly NodeId NetworkGroupDataType = new NodeId(Opc.Ua.DataTypes.NetworkGroupDataType)
The identifier for the NetworkGroupDataType DataType.
static readonly NodeId SamplingIntervalDiagnosticsDataType = new NodeId(Opc.Ua.DataTypes.SamplingIntervalDiagnosticsDataType)
The identifier for the SamplingIntervalDiagnosticsDataType DataType.
static readonly NodeId ServerDiagnosticsSummaryDataType = new NodeId(Opc.Ua.DataTypes.ServerDiagnosticsSummaryDataType)
The identifier for the ServerDiagnosticsSummaryDataType DataType.
static readonly NodeId ServerStatusDataType = new NodeId(Opc.Ua.DataTypes.ServerStatusDataType)
The identifier for the ServerStatusDataType DataType.
static readonly NodeId SessionDiagnosticsDataType = new NodeId(Opc.Ua.DataTypes.SessionDiagnosticsDataType)
The identifier for the SessionDiagnosticsDataType DataType.
static readonly NodeId SessionSecurityDiagnosticsDataType = new NodeId(Opc.Ua.DataTypes.SessionSecurityDiagnosticsDataType)
The identifier for the SessionSecurityDiagnosticsDataType DataType.
static readonly NodeId ServiceCounterDataType = new NodeId(Opc.Ua.DataTypes.ServiceCounterDataType)
The identifier for the ServiceCounterDataType DataType.
static readonly NodeId StatusResult = new NodeId(Opc.Ua.DataTypes.StatusResult)
The identifier for the StatusResult DataType.
static readonly NodeId SubscriptionDiagnosticsDataType = new NodeId(Opc.Ua.DataTypes.SubscriptionDiagnosticsDataType)
The identifier for the SubscriptionDiagnosticsDataType DataType.
static readonly NodeId ModelChangeStructureVerbMask = new NodeId(Opc.Ua.DataTypes.ModelChangeStructureVerbMask)
The identifier for the ModelChangeStructureVerbMask DataType.
static readonly NodeId ModelChangeStructureDataType = new NodeId(Opc.Ua.DataTypes.ModelChangeStructureDataType)
The identifier for the ModelChangeStructureDataType DataType.
static readonly NodeId SemanticChangeStructureDataType = new NodeId(Opc.Ua.DataTypes.SemanticChangeStructureDataType)
The identifier for the SemanticChangeStructureDataType DataType.
static readonly NodeId Range = new NodeId(Opc.Ua.DataTypes.Range)
The identifier for the Range DataType.
static readonly NodeId EUInformation = new NodeId(Opc.Ua.DataTypes.EUInformation)
The identifier for the EUInformation DataType.
static readonly NodeId AxisScaleEnumeration = new NodeId(Opc.Ua.DataTypes.AxisScaleEnumeration)
The identifier for the AxisScaleEnumeration DataType.
static readonly NodeId ComplexNumberType = new NodeId(Opc.Ua.DataTypes.ComplexNumberType)
The identifier for the ComplexNumberType DataType.
static readonly NodeId DoubleComplexNumberType = new NodeId(Opc.Ua.DataTypes.DoubleComplexNumberType)
The identifier for the DoubleComplexNumberType DataType.
static readonly NodeId AxisInformation = new NodeId(Opc.Ua.DataTypes.AxisInformation)
The identifier for the AxisInformation DataType.
static readonly NodeId XVType = new NodeId(Opc.Ua.DataTypes.XVType)
The identifier for the XVType DataType.
static readonly NodeId ProgramDiagnosticDataType = new NodeId(Opc.Ua.DataTypes.ProgramDiagnosticDataType)
The identifier for the ProgramDiagnosticDataType DataType.
static readonly NodeId ProgramDiagnostic2DataType = new NodeId(Opc.Ua.DataTypes.ProgramDiagnostic2DataType)
The identifier for the ProgramDiagnostic2DataType DataType.
static readonly NodeId Annotation = new NodeId(Opc.Ua.DataTypes.Annotation)
The identifier for the Annotation DataType.
static readonly NodeId ExceptionDeviationFormat = new NodeId(Opc.Ua.DataTypes.ExceptionDeviationFormat)
The identifier for the ExceptionDeviationFormat DataType.
Detailed Description
A class that declares constants for all DataTypes in the Model Design.
<exclude>
Definition at line 29480 of file Opc.Ua.Constants.cs.
Field Documentation
AccessLevelExType
readonly NodeId Opc.Ua.DataTypeIds.AccessLevelExType = new NodeId(Opc.Ua.DataTypes.AccessLevelExType) static
The identifier for the AccessLevelExType DataType.
Definition at line 30080 of file Opc.Ua.Constants.cs.
AccessLevelType
readonly NodeId Opc.Ua.DataTypeIds.AccessLevelType = new NodeId(Opc.Ua.DataTypes.AccessLevelType) static
The identifier for the AccessLevelType DataType.
Definition at line 30075 of file Opc.Ua.Constants.cs.
AccessRestrictionType
readonly NodeId Opc.Ua.DataTypeIds.AccessRestrictionType = new NodeId(Opc.Ua.DataTypes.AccessRestrictionType) static
The identifier for the AccessRestrictionType DataType.
Definition at line 30090 of file Opc.Ua.Constants.cs.
ActivateSessionRequest
readonly NodeId Opc.Ua.DataTypeIds.ActivateSessionRequest = new NodeId(Opc.Ua.DataTypes.ActivateSessionRequest) static
The identifier for the ActivateSessionRequest DataType.
Definition at line 30485 of file Opc.Ua.Constants.cs.
Referenced by Opc.Ua.SessionEndpoint.EndDeleteSubscriptions().
ActivateSessionResponse
readonly NodeId Opc.Ua.DataTypeIds.ActivateSessionResponse = new NodeId(Opc.Ua.DataTypes.ActivateSessionResponse) static
The identifier for the ActivateSessionResponse DataType.
Definition at line 30490 of file Opc.Ua.Constants.cs.
AddNodesItem
readonly NodeId Opc.Ua.DataTypeIds.AddNodesItem = new NodeId(Opc.Ua.DataTypes.AddNodesItem) static
The identifier for the AddNodesItem DataType.
Definition at line 30575 of file Opc.Ua.Constants.cs.
AddNodesRequest
readonly NodeId Opc.Ua.DataTypeIds.AddNodesRequest = new NodeId(Opc.Ua.DataTypes.AddNodesRequest) static
The identifier for the AddNodesRequest DataType.
Definition at line 30585 of file Opc.Ua.Constants.cs.
Referenced by Opc.Ua.SessionEndpoint.EndDeleteSubscriptions().
AddNodesResponse
readonly NodeId Opc.Ua.DataTypeIds.AddNodesResponse = new NodeId(Opc.Ua.DataTypes.AddNodesResponse) static
The identifier for the AddNodesResponse DataType.
Definition at line 30590 of file Opc.Ua.Constants.cs.
AddNodesResult
readonly NodeId Opc.Ua.DataTypeIds.AddNodesResult = new NodeId(Opc.Ua.DataTypes.AddNodesResult) static
The identifier for the AddNodesResult DataType.
Definition at line 30580 of file Opc.Ua.Constants.cs.
AddReferencesItem
readonly NodeId Opc.Ua.DataTypeIds.AddReferencesItem = new NodeId(Opc.Ua.DataTypes.AddReferencesItem) static
The identifier for the AddReferencesItem DataType.
Definition at line 30595 of file Opc.Ua.Constants.cs.
AddReferencesRequest
readonly NodeId Opc.Ua.DataTypeIds.AddReferencesRequest = new NodeId(Opc.Ua.DataTypes.AddReferencesRequest) static
The identifier for the AddReferencesRequest DataType.
Definition at line 30600 of file Opc.Ua.Constants.cs.
Referenced by Opc.Ua.SessionEndpoint.EndDeleteSubscriptions().
AddReferencesResponse
readonly NodeId Opc.Ua.DataTypeIds.AddReferencesResponse = new NodeId(Opc.Ua.DataTypes.AddReferencesResponse) static
The identifier for the AddReferencesResponse DataType.
Definition at line 30605 of file Opc.Ua.Constants.cs.
AggregateConfiguration
readonly NodeId Opc.Ua.DataTypeIds.AggregateConfiguration = new NodeId(Opc.Ua.DataTypes.AggregateConfiguration) static
The identifier for the AggregateConfiguration DataType.
Definition at line 31085 of file Opc.Ua.Constants.cs.
AggregateFilter
readonly NodeId Opc.Ua.DataTypeIds.AggregateFilter = new NodeId(Opc.Ua.DataTypes.AggregateFilter) static
The identifier for the AggregateFilter DataType.
Definition at line 31090 of file Opc.Ua.Constants.cs.
AggregateFilterResult
readonly NodeId Opc.Ua.DataTypeIds.AggregateFilterResult = new NodeId(Opc.Ua.DataTypes.AggregateFilterResult) static
The identifier for the AggregateFilterResult DataType.
Definition at line 31105 of file Opc.Ua.Constants.cs.
Annotation
readonly NodeId Opc.Ua.DataTypeIds.Annotation = new NodeId(Opc.Ua.DataTypes.Annotation) static
The identifier for the Annotation DataType.
Definition at line 31435 of file Opc.Ua.Constants.cs.
AnonymousIdentityToken
readonly NodeId Opc.Ua.DataTypeIds.AnonymousIdentityToken = new NodeId(Opc.Ua.DataTypes.AnonymousIdentityToken) static
The identifier for the AnonymousIdentityToken DataType.
Definition at line 30460 of file Opc.Ua.Constants.cs.
ApplicationDescription
readonly NodeId Opc.Ua.DataTypeIds.ApplicationDescription = new NodeId(Opc.Ua.DataTypes.ApplicationDescription) static
The identifier for the ApplicationDescription DataType.
Definition at line 30270 of file Opc.Ua.Constants.cs.
ApplicationInstanceCertificate
readonly NodeId Opc.Ua.DataTypeIds.ApplicationInstanceCertificate = new NodeId(Opc.Ua.DataTypes.ApplicationInstanceCertificate) static
The identifier for the ApplicationInstanceCertificate DataType.
Definition at line 30330 of file Opc.Ua.Constants.cs.
ApplicationType
readonly NodeId Opc.Ua.DataTypeIds.ApplicationType = new NodeId(Opc.Ua.DataTypes.ApplicationType) static
The identifier for the ApplicationType DataType.
Definition at line 30265 of file Opc.Ua.Constants.cs.
Argument
readonly NodeId Opc.Ua.DataTypeIds.Argument = new NodeId(Opc.Ua.DataTypes.Argument) static
The identifier for the Argument DataType.
Definition at line 30185 of file Opc.Ua.Constants.cs.
AttributeOperand
readonly NodeId Opc.Ua.DataTypeIds.AttributeOperand = new NodeId(Opc.Ua.DataTypes.AttributeOperand) static
The identifier for the AttributeOperand DataType.
Definition at line 30830 of file Opc.Ua.Constants.cs.
AttributeWriteMask
readonly NodeId Opc.Ua.DataTypeIds.AttributeWriteMask = new NodeId(Opc.Ua.DataTypes.AttributeWriteMask) static
The identifier for the AttributeWriteMask DataType.
Definition at line 30640 of file Opc.Ua.Constants.cs.
AudioDataType
readonly NodeId Opc.Ua.DataTypeIds.AudioDataType = new NodeId(Opc.Ua.DataTypes.AudioDataType) static
The identifier for the AudioDataType DataType.
Definition at line 29665 of file Opc.Ua.Constants.cs.
AxisInformation
readonly NodeId Opc.Ua.DataTypeIds.AxisInformation = new NodeId(Opc.Ua.DataTypes.AxisInformation) static
The identifier for the AxisInformation DataType.
Definition at line 31415 of file Opc.Ua.Constants.cs.
AxisScaleEnumeration
readonly NodeId Opc.Ua.DataTypeIds.AxisScaleEnumeration = new NodeId(Opc.Ua.DataTypes.AxisScaleEnumeration) static
The identifier for the AxisScaleEnumeration DataType.
Definition at line 31400 of file Opc.Ua.Constants.cs.
BaseDataType
readonly NodeId Opc.Ua.DataTypeIds.BaseDataType = new NodeId(Opc.Ua.DataTypes.BaseDataType) static
The identifier for the BaseDataType DataType.
Definition at line 29485 of file Opc.Ua.Constants.cs.
BitFieldMaskDataType
readonly NodeId Opc.Ua.DataTypeIds.BitFieldMaskDataType = new NodeId(Opc.Ua.DataTypes.BitFieldMaskDataType) static
The identifier for the BitFieldMaskDataType DataType.
Definition at line 29670 of file Opc.Ua.Constants.cs.
Boolean
readonly NodeId Opc.Ua.DataTypeIds.Boolean = new NodeId(Opc.Ua.DataTypes.Boolean) static
The identifier for the Boolean DataType.
Definition at line 29510 of file Opc.Ua.Constants.cs.
BrokerConnectionTransportDataType
readonly NodeId Opc.Ua.DataTypeIds.BrokerConnectionTransportDataType = new NodeId(Opc.Ua.DataTypes.BrokerConnectionTransportDataType) static
The identifier for the BrokerConnectionTransportDataType DataType.
Definition at line 30025 of file Opc.Ua.Constants.cs.
BrokerDataSetReaderTransportDataType
readonly NodeId Opc.Ua.DataTypeIds.BrokerDataSetReaderTransportDataType = new NodeId(Opc.Ua.DataTypes.BrokerDataSetReaderTransportDataType) static
The identifier for the BrokerDataSetReaderTransportDataType DataType.
Definition at line 30045 of file Opc.Ua.Constants.cs.
BrokerDataSetWriterTransportDataType
readonly NodeId Opc.Ua.DataTypeIds.BrokerDataSetWriterTransportDataType = new NodeId(Opc.Ua.DataTypes.BrokerDataSetWriterTransportDataType) static
The identifier for the BrokerDataSetWriterTransportDataType DataType.
Definition at line 30040 of file Opc.Ua.Constants.cs.
BrokerTransportQualityOfService
readonly NodeId Opc.Ua.DataTypeIds.BrokerTransportQualityOfService = new NodeId(Opc.Ua.DataTypes.BrokerTransportQualityOfService) static
The identifier for the BrokerTransportQualityOfService DataType.
Definition at line 30030 of file Opc.Ua.Constants.cs.
BrokerWriterGroupTransportDataType
readonly NodeId Opc.Ua.DataTypeIds.BrokerWriterGroupTransportDataType = new NodeId(Opc.Ua.DataTypes.BrokerWriterGroupTransportDataType) static
The identifier for the BrokerWriterGroupTransportDataType DataType.
Definition at line 30035 of file Opc.Ua.Constants.cs.
BrowseDescription
readonly NodeId Opc.Ua.DataTypeIds.BrowseDescription = new NodeId(Opc.Ua.DataTypes.BrowseDescription) static
The identifier for the BrowseDescription DataType.
Definition at line 30655 of file Opc.Ua.Constants.cs.
BrowseDirection
readonly NodeId Opc.Ua.DataTypeIds.BrowseDirection = new NodeId(Opc.Ua.DataTypes.BrowseDirection) static
The identifier for the BrowseDirection DataType.
Definition at line 30645 of file Opc.Ua.Constants.cs.
BrowseNextRequest
readonly NodeId Opc.Ua.DataTypeIds.BrowseNextRequest = new NodeId(Opc.Ua.DataTypes.BrowseNextRequest) static
The identifier for the BrowseNextRequest DataType.
Definition at line 30690 of file Opc.Ua.Constants.cs.
Referenced by Opc.Ua.SessionEndpoint.EndDeleteSubscriptions().
BrowseNextResponse
readonly NodeId Opc.Ua.DataTypeIds.BrowseNextResponse = new NodeId(Opc.Ua.DataTypes.BrowseNextResponse) static
The identifier for the BrowseNextResponse DataType.
Definition at line 30695 of file Opc.Ua.Constants.cs.
BrowsePath
readonly NodeId Opc.Ua.DataTypeIds.BrowsePath = new NodeId(Opc.Ua.DataTypes.BrowsePath) static
The identifier for the BrowsePath DataType.
Definition at line 30710 of file Opc.Ua.Constants.cs.
BrowsePathResult
readonly NodeId Opc.Ua.DataTypeIds.BrowsePathResult = new NodeId(Opc.Ua.DataTypes.BrowsePathResult) static
The identifier for the BrowsePathResult DataType.
Definition at line 30720 of file Opc.Ua.Constants.cs.
BrowsePathTarget
readonly NodeId Opc.Ua.DataTypeIds.BrowsePathTarget = new NodeId(Opc.Ua.DataTypes.BrowsePathTarget) static
The identifier for the BrowsePathTarget DataType.
Definition at line 30715 of file Opc.Ua.Constants.cs.
BrowseRequest
readonly NodeId Opc.Ua.DataTypeIds.BrowseRequest = new NodeId(Opc.Ua.DataTypes.BrowseRequest) static
The identifier for the BrowseRequest DataType.
Definition at line 30680 of file Opc.Ua.Constants.cs.
Referenced by Opc.Ua.SessionEndpoint.EndDeleteSubscriptions().
BrowseResponse
readonly NodeId Opc.Ua.DataTypeIds.BrowseResponse = new NodeId(Opc.Ua.DataTypes.BrowseResponse) static
The identifier for the BrowseResponse DataType.
Definition at line 30685 of file Opc.Ua.Constants.cs.
BrowseResult
readonly NodeId Opc.Ua.DataTypeIds.BrowseResult = new NodeId(Opc.Ua.DataTypes.BrowseResult) static
The identifier for the BrowseResult DataType.
Definition at line 30675 of file Opc.Ua.Constants.cs.
BrowseResultMask
readonly NodeId Opc.Ua.DataTypeIds.BrowseResultMask = new NodeId(Opc.Ua.DataTypes.BrowseResultMask) static
The identifier for the BrowseResultMask DataType.
Definition at line 30660 of file Opc.Ua.Constants.cs.
BuildInfo
readonly NodeId Opc.Ua.DataTypeIds.BuildInfo = new NodeId(Opc.Ua.DataTypes.BuildInfo) static
The identifier for the BuildInfo DataType.
Definition at line 31305 of file Opc.Ua.Constants.cs.
Byte
readonly NodeId Opc.Ua.DataTypeIds.Byte = new NodeId(Opc.Ua.DataTypes.Byte) static
The identifier for the Byte DataType.
Definition at line 29520 of file Opc.Ua.Constants.cs.
ByteString
readonly NodeId Opc.Ua.DataTypeIds.ByteString = new NodeId(Opc.Ua.DataTypes.ByteString) static
The identifier for the ByteString DataType.
Definition at line 29580 of file Opc.Ua.Constants.cs.
CallMethodRequest
readonly NodeId Opc.Ua.DataTypeIds.CallMethodRequest = new NodeId(Opc.Ua.DataTypes.CallMethodRequest) static
The identifier for the CallMethodRequest DataType.
Definition at line 31035 of file Opc.Ua.Constants.cs.
CallMethodResult
readonly NodeId Opc.Ua.DataTypeIds.CallMethodResult = new NodeId(Opc.Ua.DataTypes.CallMethodResult) static
The identifier for the CallMethodResult DataType.
Definition at line 31040 of file Opc.Ua.Constants.cs.
CallRequest
readonly NodeId Opc.Ua.DataTypeIds.CallRequest = new NodeId(Opc.Ua.DataTypes.CallRequest) static
The identifier for the CallRequest DataType.
Definition at line 31045 of file Opc.Ua.Constants.cs.
Referenced by Opc.Ua.SessionEndpoint.EndDeleteSubscriptions().
CallResponse
readonly NodeId Opc.Ua.DataTypeIds.CallResponse = new NodeId(Opc.Ua.DataTypes.CallResponse) static
The identifier for the CallResponse DataType.
Definition at line 31050 of file Opc.Ua.Constants.cs.
CancelRequest
readonly NodeId Opc.Ua.DataTypeIds.CancelRequest = new NodeId(Opc.Ua.DataTypes.CancelRequest) static
The identifier for the CancelRequest DataType.
Definition at line 30505 of file Opc.Ua.Constants.cs.
Referenced by Opc.Ua.SessionEndpoint.EndDeleteSubscriptions().
CancelResponse
readonly NodeId Opc.Ua.DataTypeIds.CancelResponse = new NodeId(Opc.Ua.DataTypes.CancelResponse) static
The identifier for the CancelResponse DataType.
Definition at line 30510 of file Opc.Ua.Constants.cs.
CartesianCoordinates
readonly NodeId Opc.Ua.DataTypeIds.CartesianCoordinates = new NodeId(Opc.Ua.DataTypes.CartesianCoordinates) static
The identifier for the CartesianCoordinates DataType.
Definition at line 29700 of file Opc.Ua.Constants.cs.
ChannelSecurityToken
readonly NodeId Opc.Ua.DataTypeIds.ChannelSecurityToken = new NodeId(Opc.Ua.DataTypes.ChannelSecurityToken) static
The identifier for the ChannelSecurityToken DataType.
Definition at line 30405 of file Opc.Ua.Constants.cs.
CloseSecureChannelRequest
readonly NodeId Opc.Ua.DataTypeIds.CloseSecureChannelRequest = new NodeId(Opc.Ua.DataTypes.CloseSecureChannelRequest) static
The identifier for the CloseSecureChannelRequest DataType.
Definition at line 30420 of file Opc.Ua.Constants.cs.
CloseSecureChannelResponse
readonly NodeId Opc.Ua.DataTypeIds.CloseSecureChannelResponse = new NodeId(Opc.Ua.DataTypes.CloseSecureChannelResponse) static
The identifier for the CloseSecureChannelResponse DataType.
Definition at line 30425 of file Opc.Ua.Constants.cs.
CloseSessionRequest
readonly NodeId Opc.Ua.DataTypeIds.CloseSessionRequest = new NodeId(Opc.Ua.DataTypes.CloseSessionRequest) static
The identifier for the CloseSessionRequest DataType.
Definition at line 30495 of file Opc.Ua.Constants.cs.
Referenced by Opc.Ua.SessionEndpoint.EndDeleteSubscriptions().
CloseSessionResponse
readonly NodeId Opc.Ua.DataTypeIds.CloseSessionResponse = new NodeId(Opc.Ua.DataTypes.CloseSessionResponse) static
The identifier for the CloseSessionResponse DataType.
Definition at line 30500 of file Opc.Ua.Constants.cs.
ComplexNumberType
readonly NodeId Opc.Ua.DataTypeIds.ComplexNumberType = new NodeId(Opc.Ua.DataTypes.ComplexNumberType) static
The identifier for the ComplexNumberType DataType.
Definition at line 31405 of file Opc.Ua.Constants.cs.
ConfigurationVersionDataType
readonly NodeId Opc.Ua.DataTypeIds.ConfigurationVersionDataType = new NodeId(Opc.Ua.DataTypes.ConfigurationVersionDataType) static
The identifier for the ConfigurationVersionDataType DataType.
Definition at line 29810 of file Opc.Ua.Constants.cs.
ConnectionTransportDataType
readonly NodeId Opc.Ua.DataTypeIds.ConnectionTransportDataType = new NodeId(Opc.Ua.DataTypes.ConnectionTransportDataType) static
The identifier for the ConnectionTransportDataType DataType.
Definition at line 29885 of file Opc.Ua.Constants.cs.
ContentFilter
readonly NodeId Opc.Ua.DataTypeIds.ContentFilter = new NodeId(Opc.Ua.DataTypes.ContentFilter) static
The identifier for the ContentFilter DataType.
Definition at line 30810 of file Opc.Ua.Constants.cs.
ContentFilterElement
readonly NodeId Opc.Ua.DataTypeIds.ContentFilterElement = new NodeId(Opc.Ua.DataTypes.ContentFilterElement) static
The identifier for the ContentFilterElement DataType.
Definition at line 30805 of file Opc.Ua.Constants.cs.
ContentFilterElementResult
readonly NodeId Opc.Ua.DataTypeIds.ContentFilterElementResult = new NodeId(Opc.Ua.DataTypes.ContentFilterElementResult) static
The identifier for the ContentFilterElementResult DataType.
Definition at line 30840 of file Opc.Ua.Constants.cs.
ContentFilterResult
readonly NodeId Opc.Ua.DataTypeIds.ContentFilterResult = new NodeId(Opc.Ua.DataTypes.ContentFilterResult) static
The identifier for the ContentFilterResult DataType.
Definition at line 30845 of file Opc.Ua.Constants.cs.
ContinuationPoint
readonly NodeId Opc.Ua.DataTypeIds.ContinuationPoint = new NodeId(Opc.Ua.DataTypes.ContinuationPoint) static
The identifier for the ContinuationPoint DataType.
Definition at line 30670 of file Opc.Ua.Constants.cs.
Counter
readonly NodeId Opc.Ua.DataTypeIds.Counter = new NodeId(Opc.Ua.DataTypes.Counter) static
The identifier for the Counter DataType.
Definition at line 30755 of file Opc.Ua.Constants.cs.
CreateMonitoredItemsRequest
readonly NodeId Opc.Ua.DataTypeIds.CreateMonitoredItemsRequest = new NodeId(Opc.Ua.DataTypes.CreateMonitoredItemsRequest) static
The identifier for the CreateMonitoredItemsRequest DataType.
Definition at line 31125 of file Opc.Ua.Constants.cs.
Referenced by Opc.Ua.SessionEndpoint.EndDeleteSubscriptions().
CreateMonitoredItemsResponse
readonly NodeId Opc.Ua.DataTypeIds.CreateMonitoredItemsResponse = new NodeId(Opc.Ua.DataTypes.CreateMonitoredItemsResponse) static
The identifier for the CreateMonitoredItemsResponse DataType.
Definition at line 31130 of file Opc.Ua.Constants.cs.
CreateSessionRequest
readonly NodeId Opc.Ua.DataTypeIds.CreateSessionRequest = new NodeId(Opc.Ua.DataTypes.CreateSessionRequest) static
The identifier for the CreateSessionRequest DataType.
Definition at line 30445 of file Opc.Ua.Constants.cs.
Referenced by Opc.Ua.SessionEndpoint.EndDeleteSubscriptions().
CreateSessionResponse
readonly NodeId Opc.Ua.DataTypeIds.CreateSessionResponse = new NodeId(Opc.Ua.DataTypes.CreateSessionResponse) static
The identifier for the CreateSessionResponse DataType.
Definition at line 30450 of file Opc.Ua.Constants.cs.
CreateSubscriptionRequest
readonly NodeId Opc.Ua.DataTypeIds.CreateSubscriptionRequest = new NodeId(Opc.Ua.DataTypes.CreateSubscriptionRequest) static
The identifier for the CreateSubscriptionRequest DataType.
Definition at line 31185 of file Opc.Ua.Constants.cs.
Referenced by Opc.Ua.SessionEndpoint.EndDeleteSubscriptions().
CreateSubscriptionResponse
readonly NodeId Opc.Ua.DataTypeIds.CreateSubscriptionResponse = new NodeId(Opc.Ua.DataTypes.CreateSubscriptionResponse) static
The identifier for the CreateSubscriptionResponse DataType.
Definition at line 31190 of file Opc.Ua.Constants.cs.
DataChangeFilter
readonly NodeId Opc.Ua.DataTypeIds.DataChangeFilter = new NodeId(Opc.Ua.DataTypes.DataChangeFilter) static
The identifier for the DataChangeFilter DataType.
Definition at line 31075 of file Opc.Ua.Constants.cs.
DataChangeNotification
readonly NodeId Opc.Ua.DataTypeIds.DataChangeNotification = new NodeId(Opc.Ua.DataTypes.DataChangeNotification) static
The identifier for the DataChangeNotification DataType.
Definition at line 31225 of file Opc.Ua.Constants.cs.
DataChangeTrigger
readonly NodeId Opc.Ua.DataTypeIds.DataChangeTrigger = new NodeId(Opc.Ua.DataTypes.DataChangeTrigger) static
The identifier for the DataChangeTrigger DataType.
Definition at line 31060 of file Opc.Ua.Constants.cs.
DatagramConnectionTransportDataType
readonly NodeId Opc.Ua.DataTypeIds.DatagramConnectionTransportDataType = new NodeId(Opc.Ua.DataTypes.DatagramConnectionTransportDataType) static
The identifier for the DatagramConnectionTransportDataType DataType.
Definition at line 30015 of file Opc.Ua.Constants.cs.
DatagramWriterGroupTransportDataType
readonly NodeId Opc.Ua.DataTypeIds.DatagramWriterGroupTransportDataType = new NodeId(Opc.Ua.DataTypes.DatagramWriterGroupTransportDataType) static
The identifier for the DatagramWriterGroupTransportDataType DataType.
Definition at line 30020 of file Opc.Ua.Constants.cs.
DataSetFieldContentMask
readonly NodeId Opc.Ua.DataTypeIds.DataSetFieldContentMask = new NodeId(Opc.Ua.DataTypes.DataSetFieldContentMask) static
The identifier for the DataSetFieldContentMask DataType.
Definition at line 29840 of file Opc.Ua.Constants.cs.
DataSetFieldFlags
readonly NodeId Opc.Ua.DataTypeIds.DataSetFieldFlags = new NodeId(Opc.Ua.DataTypes.DataSetFieldFlags) static
The identifier for the DataSetFieldFlags DataType.
Definition at line 29805 of file Opc.Ua.Constants.cs.
DataSetMetaDataType
readonly NodeId Opc.Ua.DataTypeIds.DataSetMetaDataType = new NodeId(Opc.Ua.DataTypes.DataSetMetaDataType) static
The identifier for the DataSetMetaDataType DataType.
Definition at line 29795 of file Opc.Ua.Constants.cs.
DataSetOrderingType
readonly NodeId Opc.Ua.DataTypeIds.DataSetOrderingType = new NodeId(Opc.Ua.DataTypes.DataSetOrderingType) static
The identifier for the DataSetOrderingType DataType.
Definition at line 29960 of file Opc.Ua.Constants.cs.
DataSetReaderDataType
readonly NodeId Opc.Ua.DataTypeIds.DataSetReaderDataType = new NodeId(Opc.Ua.DataTypes.DataSetReaderDataType) static
The identifier for the DataSetReaderDataType DataType.
Definition at line 29915 of file Opc.Ua.Constants.cs.
DataSetReaderMessageDataType
readonly NodeId Opc.Ua.DataTypeIds.DataSetReaderMessageDataType = new NodeId(Opc.Ua.DataTypes.DataSetReaderMessageDataType) static
The identifier for the DataSetReaderMessageDataType DataType.
Definition at line 29925 of file Opc.Ua.Constants.cs.
DataSetReaderTransportDataType
readonly NodeId Opc.Ua.DataTypeIds.DataSetReaderTransportDataType = new NodeId(Opc.Ua.DataTypes.DataSetReaderTransportDataType) static
The identifier for the DataSetReaderTransportDataType DataType.
Definition at line 29920 of file Opc.Ua.Constants.cs.
DataSetWriterDataType
readonly NodeId Opc.Ua.DataTypeIds.DataSetWriterDataType = new NodeId(Opc.Ua.DataTypes.DataSetWriterDataType) static
The identifier for the DataSetWriterDataType DataType.
Definition at line 29845 of file Opc.Ua.Constants.cs.
DataSetWriterMessageDataType
readonly NodeId Opc.Ua.DataTypeIds.DataSetWriterMessageDataType = new NodeId(Opc.Ua.DataTypes.DataSetWriterMessageDataType) static
The identifier for the DataSetWriterMessageDataType DataType.
Definition at line 29855 of file Opc.Ua.Constants.cs.
DataSetWriterTransportDataType
readonly NodeId Opc.Ua.DataTypeIds.DataSetWriterTransportDataType = new NodeId(Opc.Ua.DataTypes.DataSetWriterTransportDataType) static
The identifier for the DataSetWriterTransportDataType DataType.
Definition at line 29850 of file Opc.Ua.Constants.cs.
DataTypeAttributes
readonly NodeId Opc.Ua.DataTypeIds.DataTypeAttributes = new NodeId(Opc.Ua.DataTypes.DataTypeAttributes) static
The identifier for the DataTypeAttributes DataType.
Definition at line 30555 of file Opc.Ua.Constants.cs.
DataTypeDefinition
readonly NodeId Opc.Ua.DataTypeIds.DataTypeDefinition = new NodeId(Opc.Ua.DataTypes.DataTypeDefinition) static
The identifier for the DataTypeDefinition DataType.
Definition at line 30100 of file Opc.Ua.Constants.cs.
DataTypeDescription
readonly NodeId Opc.Ua.DataTypeIds.DataTypeDescription = new NodeId(Opc.Ua.DataTypes.DataTypeDescription) static
The identifier for the DataTypeDescription DataType.
Definition at line 29765 of file Opc.Ua.Constants.cs.
DataTypeNode
readonly NodeId Opc.Ua.DataTypeIds.DataTypeNode = new NodeId(Opc.Ua.DataTypes.DataTypeNode) static
The identifier for the DataTypeNode DataType.
Definition at line 30175 of file Opc.Ua.Constants.cs.
DataTypeSchemaHeader
readonly NodeId Opc.Ua.DataTypeIds.DataTypeSchemaHeader = new NodeId(Opc.Ua.DataTypes.DataTypeSchemaHeader) static
The identifier for the DataTypeSchemaHeader DataType.
Definition at line 29760 of file Opc.Ua.Constants.cs.
DataValue
readonly NodeId Opc.Ua.DataTypeIds.DataValue = new NodeId(Opc.Ua.DataTypes.DataValue) static
The identifier for the DataValue DataType.
Definition at line 29620 of file Opc.Ua.Constants.cs.
Date
readonly NodeId Opc.Ua.DataTypeIds.Date = new NodeId(Opc.Ua.DataTypes.Date) static
The identifier for the Date DataType.
Definition at line 30770 of file Opc.Ua.Constants.cs.
DateString
readonly NodeId Opc.Ua.DataTypeIds.DateString = new NodeId(Opc.Ua.DataTypes.DateString) static
The identifier for the DateString DataType.
Definition at line 30230 of file Opc.Ua.Constants.cs.
DateTime
readonly NodeId Opc.Ua.DataTypeIds.DateTime = new NodeId(Opc.Ua.DataTypes.DateTime) static
The identifier for the DateTime DataType.
Definition at line 29570 of file Opc.Ua.Constants.cs.
DeadbandType
readonly NodeId Opc.Ua.DataTypeIds.DeadbandType = new NodeId(Opc.Ua.DataTypes.DeadbandType) static
The identifier for the DeadbandType DataType.
Definition at line 31065 of file Opc.Ua.Constants.cs.
Decimal
readonly NodeId Opc.Ua.DataTypeIds.Decimal = new NodeId(Opc.Ua.DataTypes.Decimal) static
The identifier for the Decimal DataType.
Definition at line 29635 of file Opc.Ua.Constants.cs.
DecimalDataType
readonly NodeId Opc.Ua.DataTypeIds.DecimalDataType = new NodeId(Opc.Ua.DataTypes.DecimalDataType) static
The identifier for the DecimalDataType DataType.
Definition at line 29755 of file Opc.Ua.Constants.cs.
DecimalString
readonly NodeId Opc.Ua.DataTypeIds.DecimalString = new NodeId(Opc.Ua.DataTypes.DecimalString) static
The identifier for the DecimalString DataType.
Definition at line 30215 of file Opc.Ua.Constants.cs.
DeleteAtTimeDetails
readonly NodeId Opc.Ua.DataTypeIds.DeleteAtTimeDetails = new NodeId(Opc.Ua.DataTypes.DeleteAtTimeDetails) static
The identifier for the DeleteAtTimeDetails DataType.
Definition at line 31010 of file Opc.Ua.Constants.cs.
DeleteEventDetails
readonly NodeId Opc.Ua.DataTypeIds.DeleteEventDetails = new NodeId(Opc.Ua.DataTypes.DeleteEventDetails) static
The identifier for the DeleteEventDetails DataType.
Definition at line 31015 of file Opc.Ua.Constants.cs.
DeleteMonitoredItemsRequest
readonly NodeId Opc.Ua.DataTypeIds.DeleteMonitoredItemsRequest = new NodeId(Opc.Ua.DataTypes.DeleteMonitoredItemsRequest) static
The identifier for the DeleteMonitoredItemsRequest DataType.
Definition at line 31175 of file Opc.Ua.Constants.cs.
Referenced by Opc.Ua.SessionEndpoint.EndDeleteSubscriptions().
DeleteMonitoredItemsResponse
readonly NodeId Opc.Ua.DataTypeIds.DeleteMonitoredItemsResponse = new NodeId(Opc.Ua.DataTypes.DeleteMonitoredItemsResponse) static
The identifier for the DeleteMonitoredItemsResponse DataType.
Definition at line 31180 of file Opc.Ua.Constants.cs.
DeleteNodesItem
readonly NodeId Opc.Ua.DataTypeIds.DeleteNodesItem = new NodeId(Opc.Ua.DataTypes.DeleteNodesItem) static
The identifier for the DeleteNodesItem DataType.
Definition at line 30610 of file Opc.Ua.Constants.cs.
DeleteNodesRequest
readonly NodeId Opc.Ua.DataTypeIds.DeleteNodesRequest = new NodeId(Opc.Ua.DataTypes.DeleteNodesRequest) static
The identifier for the DeleteNodesRequest DataType.
Definition at line 30615 of file Opc.Ua.Constants.cs.
Referenced by Opc.Ua.SessionEndpoint.EndDeleteSubscriptions().
DeleteNodesResponse
readonly NodeId Opc.Ua.DataTypeIds.DeleteNodesResponse = new NodeId(Opc.Ua.DataTypes.DeleteNodesResponse) static
The identifier for the DeleteNodesResponse DataType.
Definition at line 30620 of file Opc.Ua.Constants.cs.
DeleteRawModifiedDetails
readonly NodeId Opc.Ua.DataTypeIds.DeleteRawModifiedDetails = new NodeId(Opc.Ua.DataTypes.DeleteRawModifiedDetails) static
The identifier for the DeleteRawModifiedDetails DataType.
Definition at line 31005 of file Opc.Ua.Constants.cs.
DeleteReferencesItem
readonly NodeId Opc.Ua.DataTypeIds.DeleteReferencesItem = new NodeId(Opc.Ua.DataTypes.DeleteReferencesItem) static
The identifier for the DeleteReferencesItem DataType.
Definition at line 30625 of file Opc.Ua.Constants.cs.
DeleteReferencesRequest
readonly NodeId Opc.Ua.DataTypeIds.DeleteReferencesRequest = new NodeId(Opc.Ua.DataTypes.DeleteReferencesRequest) static
The identifier for the DeleteReferencesRequest DataType.
Definition at line 30630 of file Opc.Ua.Constants.cs.
Referenced by Opc.Ua.SessionEndpoint.EndDeleteSubscriptions().
DeleteReferencesResponse
readonly NodeId Opc.Ua.DataTypeIds.DeleteReferencesResponse = new NodeId(Opc.Ua.DataTypes.DeleteReferencesResponse) static
The identifier for the DeleteReferencesResponse DataType.
Definition at line 30635 of file Opc.Ua.Constants.cs.
DeleteSubscriptionsRequest
readonly NodeId Opc.Ua.DataTypeIds.DeleteSubscriptionsRequest = new NodeId(Opc.Ua.DataTypes.DeleteSubscriptionsRequest) static
The identifier for the DeleteSubscriptionsRequest DataType.
Definition at line 31295 of file Opc.Ua.Constants.cs.
Referenced by Opc.Ua.SessionEndpoint.EndDeleteSubscriptions().
DeleteSubscriptionsResponse
readonly NodeId Opc.Ua.DataTypeIds.DeleteSubscriptionsResponse = new NodeId(Opc.Ua.DataTypes.DeleteSubscriptionsResponse) static
The identifier for the DeleteSubscriptionsResponse DataType.
Definition at line 31300 of file Opc.Ua.Constants.cs.
DiagnosticInfo
readonly NodeId Opc.Ua.DataTypeIds.DiagnosticInfo = new NodeId(Opc.Ua.DataTypes.DiagnosticInfo) static
The identifier for the DiagnosticInfo DataType.
Definition at line 29625 of file Opc.Ua.Constants.cs.
DiagnosticsLevel
readonly NodeId Opc.Ua.DataTypeIds.DiagnosticsLevel = new NodeId(Opc.Ua.DataTypes.DiagnosticsLevel) static
The identifier for the DiagnosticsLevel DataType.
Definition at line 30050 of file Opc.Ua.Constants.cs.
DiscoveryConfiguration
readonly NodeId Opc.Ua.DataTypeIds.DiscoveryConfiguration = new NodeId(Opc.Ua.DataTypes.DiscoveryConfiguration) static
The identifier for the DiscoveryConfiguration DataType.
Definition at line 30380 of file Opc.Ua.Constants.cs.
Double
readonly NodeId Opc.Ua.DataTypeIds.Double = new NodeId(Opc.Ua.DataTypes.Double) static
The identifier for the Double DataType.
Definition at line 29560 of file Opc.Ua.Constants.cs.
DoubleComplexNumberType
readonly NodeId Opc.Ua.DataTypeIds.DoubleComplexNumberType = new NodeId(Opc.Ua.DataTypes.DoubleComplexNumberType) static
The identifier for the DoubleComplexNumberType DataType.
Definition at line 31410 of file Opc.Ua.Constants.cs.
Duration
readonly NodeId Opc.Ua.DataTypeIds.Duration = new NodeId(Opc.Ua.DataTypes.Duration) static
The identifier for the Duration DataType.
Definition at line 30235 of file Opc.Ua.Constants.cs.
DurationString
readonly NodeId Opc.Ua.DataTypeIds.DurationString = new NodeId(Opc.Ua.DataTypes.DurationString) static
The identifier for the DurationString DataType.
Definition at line 30220 of file Opc.Ua.Constants.cs.
ElementOperand
readonly NodeId Opc.Ua.DataTypeIds.ElementOperand = new NodeId(Opc.Ua.DataTypes.ElementOperand) static
The identifier for the ElementOperand DataType.
Definition at line 30820 of file Opc.Ua.Constants.cs.
EndpointConfiguration
readonly NodeId Opc.Ua.DataTypeIds.EndpointConfiguration = new NodeId(Opc.Ua.DataTypes.EndpointConfiguration) static
The identifier for the EndpointConfiguration DataType.
Definition at line 30775 of file Opc.Ua.Constants.cs.
EndpointDescription
readonly NodeId Opc.Ua.DataTypeIds.EndpointDescription = new NodeId(Opc.Ua.DataTypes.EndpointDescription) static
The identifier for the EndpointDescription DataType.
Definition at line 30350 of file Opc.Ua.Constants.cs.
EndpointType
readonly NodeId Opc.Ua.DataTypeIds.EndpointType = new NodeId(Opc.Ua.DataTypes.EndpointType) static
The identifier for the EndpointType DataType.
Definition at line 29680 of file Opc.Ua.Constants.cs.
EndpointUrlListDataType
readonly NodeId Opc.Ua.DataTypeIds.EndpointUrlListDataType = new NodeId(Opc.Ua.DataTypes.EndpointUrlListDataType) static
The identifier for the EndpointUrlListDataType DataType.
Definition at line 31325 of file Opc.Ua.Constants.cs.
EnumDefinition
readonly NodeId Opc.Ua.DataTypeIds.EnumDefinition = new NodeId(Opc.Ua.DataTypes.EnumDefinition) static
The identifier for the EnumDefinition DataType.
Definition at line 30120 of file Opc.Ua.Constants.cs.
EnumDescription
readonly NodeId Opc.Ua.DataTypeIds.EnumDescription = new NodeId(Opc.Ua.DataTypes.EnumDescription) static
The identifier for the EnumDescription DataType.
Definition at line 29775 of file Opc.Ua.Constants.cs.
Enumeration
readonly NodeId Opc.Ua.DataTypeIds.Enumeration = new NodeId(Opc.Ua.DataTypes.Enumeration) static
The identifier for the Enumeration DataType.
Definition at line 29505 of file Opc.Ua.Constants.cs.
EnumField
readonly NodeId Opc.Ua.DataTypeIds.EnumField = new NodeId(Opc.Ua.DataTypes.EnumField) static
The identifier for the EnumField DataType.
Definition at line 30195 of file Opc.Ua.Constants.cs.
EnumValueType
readonly NodeId Opc.Ua.DataTypeIds.EnumValueType = new NodeId(Opc.Ua.DataTypes.EnumValueType) static
The identifier for the EnumValueType DataType.
Definition at line 30190 of file Opc.Ua.Constants.cs.
EUInformation
readonly NodeId Opc.Ua.DataTypeIds.EUInformation = new NodeId(Opc.Ua.DataTypes.EUInformation) static
The identifier for the EUInformation DataType.
Definition at line 31395 of file Opc.Ua.Constants.cs.
EventFieldList
readonly NodeId Opc.Ua.DataTypeIds.EventFieldList = new NodeId(Opc.Ua.DataTypes.EventFieldList) static
The identifier for the EventFieldList DataType.
Definition at line 31240 of file Opc.Ua.Constants.cs.
EventFilter
readonly NodeId Opc.Ua.DataTypeIds.EventFilter = new NodeId(Opc.Ua.DataTypes.EventFilter) static
The identifier for the EventFilter DataType.
Definition at line 31080 of file Opc.Ua.Constants.cs.
EventFilterResult
readonly NodeId Opc.Ua.DataTypeIds.EventFilterResult = new NodeId(Opc.Ua.DataTypes.EventFilterResult) static
The identifier for the EventFilterResult DataType.
Definition at line 31100 of file Opc.Ua.Constants.cs.
EventNotificationList
readonly NodeId Opc.Ua.DataTypeIds.EventNotificationList = new NodeId(Opc.Ua.DataTypes.EventNotificationList) static
The identifier for the EventNotificationList DataType.
Definition at line 31235 of file Opc.Ua.Constants.cs.
EventNotifierType
readonly NodeId Opc.Ua.DataTypeIds.EventNotifierType = new NodeId(Opc.Ua.DataTypes.EventNotifierType) static
The identifier for the EventNotifierType DataType.
Definition at line 30085 of file Opc.Ua.Constants.cs.
ExceptionDeviationFormat
readonly NodeId Opc.Ua.DataTypeIds.ExceptionDeviationFormat = new NodeId(Opc.Ua.DataTypes.ExceptionDeviationFormat) static
The identifier for the ExceptionDeviationFormat DataType.
Definition at line 31440 of file Opc.Ua.Constants.cs.
ExpandedNodeId
readonly NodeId Opc.Ua.DataTypeIds.ExpandedNodeId = new NodeId(Opc.Ua.DataTypes.ExpandedNodeId) static
The identifier for the ExpandedNodeId DataType.
Definition at line 29595 of file Opc.Ua.Constants.cs.
FieldMetaData
readonly NodeId Opc.Ua.DataTypeIds.FieldMetaData = new NodeId(Opc.Ua.DataTypes.FieldMetaData) static
The identifier for the FieldMetaData DataType.
Definition at line 29800 of file Opc.Ua.Constants.cs.
FieldTargetDataType
readonly NodeId Opc.Ua.DataTypeIds.FieldTargetDataType = new NodeId(Opc.Ua.DataTypes.FieldTargetDataType) static
The identifier for the FieldTargetDataType DataType.
Definition at line 29940 of file Opc.Ua.Constants.cs.
FilterOperand
readonly NodeId Opc.Ua.DataTypeIds.FilterOperand = new NodeId(Opc.Ua.DataTypes.FilterOperand) static
The identifier for the FilterOperand DataType.
Definition at line 30815 of file Opc.Ua.Constants.cs.
FilterOperator
readonly NodeId Opc.Ua.DataTypeIds.FilterOperator = new NodeId(Opc.Ua.DataTypes.FilterOperator) static
The identifier for the FilterOperator DataType.
Definition at line 30790 of file Opc.Ua.Constants.cs.
FindServersOnNetworkRequest
readonly NodeId Opc.Ua.DataTypeIds.FindServersOnNetworkRequest = new NodeId(Opc.Ua.DataTypes.FindServersOnNetworkRequest) static
The identifier for the FindServersOnNetworkRequest DataType.
Definition at line 30320 of file Opc.Ua.Constants.cs.
Referenced by Opc.Ua.SessionEndpoint.EndDeleteSubscriptions(), and Opc.Ua.DiscoveryEndpoint.EndRegisterServer2().
FindServersOnNetworkResponse
readonly NodeId Opc.Ua.DataTypeIds.FindServersOnNetworkResponse = new NodeId(Opc.Ua.DataTypes.FindServersOnNetworkResponse) static
The identifier for the FindServersOnNetworkResponse DataType.
Definition at line 30325 of file Opc.Ua.Constants.cs.
FindServersRequest
readonly NodeId Opc.Ua.DataTypeIds.FindServersRequest = new NodeId(Opc.Ua.DataTypes.FindServersRequest) static
The identifier for the FindServersRequest DataType.
Definition at line 30305 of file Opc.Ua.Constants.cs.
Referenced by Opc.Ua.SessionEndpoint.EndDeleteSubscriptions(), and Opc.Ua.DiscoveryEndpoint.EndRegisterServer2().
FindServersResponse
readonly NodeId Opc.Ua.DataTypeIds.FindServersResponse = new NodeId(Opc.Ua.DataTypes.FindServersResponse) static
The identifier for the FindServersResponse DataType.
Definition at line 30310 of file Opc.Ua.Constants.cs.
Float
readonly NodeId Opc.Ua.DataTypeIds.Float = new NodeId(Opc.Ua.DataTypes.Float) static
The identifier for the Float DataType.
Definition at line 29555 of file Opc.Ua.Constants.cs.
Frame
readonly NodeId Opc.Ua.DataTypeIds.Frame = new NodeId(Opc.Ua.DataTypes.Frame) static
The identifier for the Frame DataType.
Definition at line 29720 of file Opc.Ua.Constants.cs.
GenericAttributes
readonly NodeId Opc.Ua.DataTypeIds.GenericAttributes = new NodeId(Opc.Ua.DataTypes.GenericAttributes) static
The identifier for the GenericAttributes DataType.
Definition at line 30570 of file Opc.Ua.Constants.cs.
GenericAttributeValue
readonly NodeId Opc.Ua.DataTypeIds.GenericAttributeValue = new NodeId(Opc.Ua.DataTypes.GenericAttributeValue) static
The identifier for the GenericAttributeValue DataType.
Definition at line 30565 of file Opc.Ua.Constants.cs.
GetEndpointsRequest
readonly NodeId Opc.Ua.DataTypeIds.GetEndpointsRequest = new NodeId(Opc.Ua.DataTypes.GetEndpointsRequest) static
The identifier for the GetEndpointsRequest DataType.
Definition at line 30355 of file Opc.Ua.Constants.cs.
Referenced by Opc.Ua.SessionEndpoint.EndDeleteSubscriptions(), and Opc.Ua.DiscoveryEndpoint.EndRegisterServer2().
GetEndpointsResponse
readonly NodeId Opc.Ua.DataTypeIds.GetEndpointsResponse = new NodeId(Opc.Ua.DataTypes.GetEndpointsResponse) static
The identifier for the GetEndpointsResponse DataType.
Definition at line 30360 of file Opc.Ua.Constants.cs.
Guid
readonly NodeId Opc.Ua.DataTypeIds.Guid = new NodeId(Opc.Ua.DataTypes.Guid) static
The identifier for the Guid DataType.
Definition at line 29575 of file Opc.Ua.Constants.cs.
HistoryData
readonly NodeId Opc.Ua.DataTypeIds.HistoryData = new NodeId(Opc.Ua.DataTypes.HistoryData) static
The identifier for the HistoryData DataType.
Definition at line 30930 of file Opc.Ua.Constants.cs.
HistoryEvent
readonly NodeId Opc.Ua.DataTypeIds.HistoryEvent = new NodeId(Opc.Ua.DataTypes.HistoryEvent) static
The identifier for the HistoryEvent DataType.
Definition at line 30945 of file Opc.Ua.Constants.cs.
HistoryEventFieldList
readonly NodeId Opc.Ua.DataTypeIds.HistoryEventFieldList = new NodeId(Opc.Ua.DataTypes.HistoryEventFieldList) static
The identifier for the HistoryEventFieldList DataType.
Definition at line 31245 of file Opc.Ua.Constants.cs.
HistoryModifiedData
readonly NodeId Opc.Ua.DataTypeIds.HistoryModifiedData = new NodeId(Opc.Ua.DataTypes.HistoryModifiedData) static
The identifier for the HistoryModifiedData DataType.
Definition at line 30940 of file Opc.Ua.Constants.cs.
HistoryReadDetails
readonly NodeId Opc.Ua.DataTypeIds.HistoryReadDetails = new NodeId(Opc.Ua.DataTypes.HistoryReadDetails) static
The identifier for the HistoryReadDetails DataType.
Definition at line 30905 of file Opc.Ua.Constants.cs.
HistoryReadRequest
readonly NodeId Opc.Ua.DataTypeIds.HistoryReadRequest = new NodeId(Opc.Ua.DataTypes.HistoryReadRequest) static
The identifier for the HistoryReadRequest DataType.
Definition at line 30950 of file Opc.Ua.Constants.cs.
Referenced by Opc.Ua.SessionEndpoint.EndDeleteSubscriptions().
HistoryReadResponse
readonly NodeId Opc.Ua.DataTypeIds.HistoryReadResponse = new NodeId(Opc.Ua.DataTypes.HistoryReadResponse) static
The identifier for the HistoryReadResponse DataType.
Definition at line 30955 of file Opc.Ua.Constants.cs.
HistoryReadResult
readonly NodeId Opc.Ua.DataTypeIds.HistoryReadResult = new NodeId(Opc.Ua.DataTypes.HistoryReadResult) static
The identifier for the HistoryReadResult DataType.
Definition at line 30900 of file Opc.Ua.Constants.cs.
HistoryReadValueId
readonly NodeId Opc.Ua.DataTypeIds.HistoryReadValueId = new NodeId(Opc.Ua.DataTypes.HistoryReadValueId) static
The identifier for the HistoryReadValueId DataType.
Definition at line 30895 of file Opc.Ua.Constants.cs.
HistoryUpdateDetails
readonly NodeId Opc.Ua.DataTypeIds.HistoryUpdateDetails = new NodeId(Opc.Ua.DataTypes.HistoryUpdateDetails) static
The identifier for the HistoryUpdateDetails DataType.
Definition at line 30975 of file Opc.Ua.Constants.cs.
HistoryUpdateRequest
readonly NodeId Opc.Ua.DataTypeIds.HistoryUpdateRequest = new NodeId(Opc.Ua.DataTypes.HistoryUpdateRequest) static
The identifier for the HistoryUpdateRequest DataType.
Definition at line 31025 of file Opc.Ua.Constants.cs.
Referenced by Opc.Ua.SessionEndpoint.EndDeleteSubscriptions().
HistoryUpdateResponse
readonly NodeId Opc.Ua.DataTypeIds.HistoryUpdateResponse = new NodeId(Opc.Ua.DataTypes.HistoryUpdateResponse) static
The identifier for the HistoryUpdateResponse DataType.
Definition at line 31030 of file Opc.Ua.Constants.cs.
HistoryUpdateResult
readonly NodeId Opc.Ua.DataTypeIds.HistoryUpdateResult = new NodeId(Opc.Ua.DataTypes.HistoryUpdateResult) static
The identifier for the HistoryUpdateResult DataType.
Definition at line 31020 of file Opc.Ua.Constants.cs.
HistoryUpdateType
readonly NodeId Opc.Ua.DataTypeIds.HistoryUpdateType = new NodeId(Opc.Ua.DataTypes.HistoryUpdateType) static
The identifier for the HistoryUpdateType DataType.
Definition at line 30980 of file Opc.Ua.Constants.cs.
IdentityCriteriaType
readonly NodeId Opc.Ua.DataTypeIds.IdentityCriteriaType = new NodeId(Opc.Ua.DataTypes.IdentityCriteriaType) static
The identifier for the IdentityCriteriaType DataType.
Definition at line 29735 of file Opc.Ua.Constants.cs.
IdentityMappingRuleType
readonly NodeId Opc.Ua.DataTypeIds.IdentityMappingRuleType = new NodeId(Opc.Ua.DataTypes.IdentityMappingRuleType) static
The identifier for the IdentityMappingRuleType DataType.
Definition at line 29740 of file Opc.Ua.Constants.cs.
IdType
readonly NodeId Opc.Ua.DataTypeIds.IdType = new NodeId(Opc.Ua.DataTypes.IdType) static
The identifier for the IdType DataType.
Definition at line 30060 of file Opc.Ua.Constants.cs.
Image
readonly NodeId Opc.Ua.DataTypeIds.Image = new NodeId(Opc.Ua.DataTypes.Image) static
The identifier for the Image DataType.
Definition at line 29630 of file Opc.Ua.Constants.cs.
ImageBMP
readonly NodeId Opc.Ua.DataTypeIds.ImageBMP = new NodeId(Opc.Ua.DataTypes.ImageBMP) static
The identifier for the ImageBMP DataType.
Definition at line 29645 of file Opc.Ua.Constants.cs.
ImageGIF
readonly NodeId Opc.Ua.DataTypeIds.ImageGIF = new NodeId(Opc.Ua.DataTypes.ImageGIF) static
The identifier for the ImageGIF DataType.
Definition at line 29650 of file Opc.Ua.Constants.cs.
ImageJPG
readonly NodeId Opc.Ua.DataTypeIds.ImageJPG = new NodeId(Opc.Ua.DataTypes.ImageJPG) static
The identifier for the ImageJPG DataType.
Definition at line 29655 of file Opc.Ua.Constants.cs.
ImagePNG
readonly NodeId Opc.Ua.DataTypeIds.ImagePNG = new NodeId(Opc.Ua.DataTypes.ImagePNG) static
The identifier for the ImagePNG DataType.
Definition at line 29660 of file Opc.Ua.Constants.cs.
Index
readonly NodeId Opc.Ua.DataTypeIds.Index = new NodeId(Opc.Ua.DataTypes.Index) static
The identifier for the Index DataType.
Definition at line 30255 of file Opc.Ua.Constants.cs.
InstanceNode
readonly NodeId Opc.Ua.DataTypeIds.InstanceNode = new NodeId(Opc.Ua.DataTypes.InstanceNode) static
The identifier for the InstanceNode DataType.
Definition at line 30130 of file Opc.Ua.Constants.cs.
Int16
readonly NodeId Opc.Ua.DataTypeIds.Int16 = new NodeId(Opc.Ua.DataTypes.Int16) static
The identifier for the Int16 DataType.
Definition at line 29525 of file Opc.Ua.Constants.cs.
Int32
readonly NodeId Opc.Ua.DataTypeIds.Int32 = new NodeId(Opc.Ua.DataTypes.Int32) static
The identifier for the Int32 DataType.
Definition at line 29535 of file Opc.Ua.Constants.cs.
Int64
readonly NodeId Opc.Ua.DataTypeIds.Int64 = new NodeId(Opc.Ua.DataTypes.Int64) static
The identifier for the Int64 DataType.
Definition at line 29545 of file Opc.Ua.Constants.cs.
Integer
readonly NodeId Opc.Ua.DataTypeIds.Integer = new NodeId(Opc.Ua.DataTypes.Integer) static
The identifier for the Integer DataType.
Definition at line 29495 of file Opc.Ua.Constants.cs.
IntegerId
readonly NodeId Opc.Ua.DataTypeIds.IntegerId = new NodeId(Opc.Ua.DataTypes.IntegerId) static
The identifier for the IntegerId DataType.
Definition at line 30260 of file Opc.Ua.Constants.cs.
IssuedIdentityToken
readonly NodeId Opc.Ua.DataTypeIds.IssuedIdentityToken = new NodeId(Opc.Ua.DataTypes.IssuedIdentityToken) static
The identifier for the IssuedIdentityToken DataType.
Definition at line 30475 of file Opc.Ua.Constants.cs.
JsonDataSetMessageContentMask
readonly NodeId Opc.Ua.DataTypeIds.JsonDataSetMessageContentMask = new NodeId(Opc.Ua.DataTypes.JsonDataSetMessageContentMask) static
The identifier for the JsonDataSetMessageContentMask DataType.
Definition at line 30000 of file Opc.Ua.Constants.cs.
JsonDataSetReaderMessageDataType
readonly NodeId Opc.Ua.DataTypeIds.JsonDataSetReaderMessageDataType = new NodeId(Opc.Ua.DataTypes.JsonDataSetReaderMessageDataType) static
The identifier for the JsonDataSetReaderMessageDataType DataType.
Definition at line 30010 of file Opc.Ua.Constants.cs.
JsonDataSetWriterMessageDataType
readonly NodeId Opc.Ua.DataTypeIds.JsonDataSetWriterMessageDataType = new NodeId(Opc.Ua.DataTypes.JsonDataSetWriterMessageDataType) static
The identifier for the JsonDataSetWriterMessageDataType DataType.
Definition at line 30005 of file Opc.Ua.Constants.cs.
JsonNetworkMessageContentMask
readonly NodeId Opc.Ua.DataTypeIds.JsonNetworkMessageContentMask = new NodeId(Opc.Ua.DataTypes.JsonNetworkMessageContentMask) static
The identifier for the JsonNetworkMessageContentMask DataType.
Definition at line 29990 of file Opc.Ua.Constants.cs.
JsonWriterGroupMessageDataType
readonly NodeId Opc.Ua.DataTypeIds.JsonWriterGroupMessageDataType = new NodeId(Opc.Ua.DataTypes.JsonWriterGroupMessageDataType) static
The identifier for the JsonWriterGroupMessageDataType DataType.
Definition at line 29995 of file Opc.Ua.Constants.cs.
KeyValuePair
readonly NodeId Opc.Ua.DataTypeIds.KeyValuePair = new NodeId(Opc.Ua.DataTypes.KeyValuePair) static
The identifier for the KeyValuePair DataType.
Definition at line 29675 of file Opc.Ua.Constants.cs.
LiteralOperand
readonly NodeId Opc.Ua.DataTypeIds.LiteralOperand = new NodeId(Opc.Ua.DataTypes.LiteralOperand) static
The identifier for the LiteralOperand DataType.
Definition at line 30825 of file Opc.Ua.Constants.cs.
LocaleId
readonly NodeId Opc.Ua.DataTypeIds.LocaleId = new NodeId(Opc.Ua.DataTypes.LocaleId) static
The identifier for the LocaleId DataType.
Definition at line 30245 of file Opc.Ua.Constants.cs.
LocalizedText
readonly NodeId Opc.Ua.DataTypeIds.LocalizedText = new NodeId(Opc.Ua.DataTypes.LocalizedText) static
The identifier for the LocalizedText DataType.
Definition at line 29610 of file Opc.Ua.Constants.cs.
MdnsDiscoveryConfiguration
readonly NodeId Opc.Ua.DataTypeIds.MdnsDiscoveryConfiguration = new NodeId(Opc.Ua.DataTypes.MdnsDiscoveryConfiguration) static
The identifier for the MdnsDiscoveryConfiguration DataType.
Definition at line 30385 of file Opc.Ua.Constants.cs.
MessageSecurityMode
readonly NodeId Opc.Ua.DataTypeIds.MessageSecurityMode = new NodeId(Opc.Ua.DataTypes.MessageSecurityMode) static
The identifier for the MessageSecurityMode DataType.
Definition at line 30335 of file Opc.Ua.Constants.cs.
MethodAttributes
readonly NodeId Opc.Ua.DataTypeIds.MethodAttributes = new NodeId(Opc.Ua.DataTypes.MethodAttributes) static
The identifier for the MethodAttributes DataType.
Definition at line 30535 of file Opc.Ua.Constants.cs.
MethodNode
readonly NodeId Opc.Ua.DataTypeIds.MethodNode = new NodeId(Opc.Ua.DataTypes.MethodNode) static
The identifier for the MethodNode DataType.
Definition at line 30165 of file Opc.Ua.Constants.cs.
ModelChangeStructureDataType
readonly NodeId Opc.Ua.DataTypeIds.ModelChangeStructureDataType = new NodeId(Opc.Ua.DataTypes.ModelChangeStructureDataType) static
The identifier for the ModelChangeStructureDataType DataType.
Definition at line 31380 of file Opc.Ua.Constants.cs.
ModelChangeStructureVerbMask
readonly NodeId Opc.Ua.DataTypeIds.ModelChangeStructureVerbMask = new NodeId(Opc.Ua.DataTypes.ModelChangeStructureVerbMask) static
The identifier for the ModelChangeStructureVerbMask DataType.
Definition at line 31375 of file Opc.Ua.Constants.cs.
ModificationInfo
readonly NodeId Opc.Ua.DataTypeIds.ModificationInfo = new NodeId(Opc.Ua.DataTypes.ModificationInfo) static
The identifier for the ModificationInfo DataType.
Definition at line 30935 of file Opc.Ua.Constants.cs.
ModifyMonitoredItemsRequest
readonly NodeId Opc.Ua.DataTypeIds.ModifyMonitoredItemsRequest = new NodeId(Opc.Ua.DataTypes.ModifyMonitoredItemsRequest) static
The identifier for the ModifyMonitoredItemsRequest DataType.
Definition at line 31145 of file Opc.Ua.Constants.cs.
Referenced by Opc.Ua.SessionEndpoint.EndDeleteSubscriptions().
ModifyMonitoredItemsResponse
readonly NodeId Opc.Ua.DataTypeIds.ModifyMonitoredItemsResponse = new NodeId(Opc.Ua.DataTypes.ModifyMonitoredItemsResponse) static
The identifier for the ModifyMonitoredItemsResponse DataType.
Definition at line 31150 of file Opc.Ua.Constants.cs.
ModifySubscriptionRequest
readonly NodeId Opc.Ua.DataTypeIds.ModifySubscriptionRequest = new NodeId(Opc.Ua.DataTypes.ModifySubscriptionRequest) static
The identifier for the ModifySubscriptionRequest DataType.
Definition at line 31195 of file Opc.Ua.Constants.cs.
Referenced by Opc.Ua.SessionEndpoint.EndDeleteSubscriptions().
ModifySubscriptionResponse
readonly NodeId Opc.Ua.DataTypeIds.ModifySubscriptionResponse = new NodeId(Opc.Ua.DataTypes.ModifySubscriptionResponse) static
The identifier for the ModifySubscriptionResponse DataType.
Definition at line 31200 of file Opc.Ua.Constants.cs.
MonitoredItemCreateRequest
readonly NodeId Opc.Ua.DataTypeIds.MonitoredItemCreateRequest = new NodeId(Opc.Ua.DataTypes.MonitoredItemCreateRequest) static
The identifier for the MonitoredItemCreateRequest DataType.
Definition at line 31115 of file Opc.Ua.Constants.cs.
MonitoredItemCreateResult
readonly NodeId Opc.Ua.DataTypeIds.MonitoredItemCreateResult = new NodeId(Opc.Ua.DataTypes.MonitoredItemCreateResult) static
The identifier for the MonitoredItemCreateResult DataType.
Definition at line 31120 of file Opc.Ua.Constants.cs.
MonitoredItemModifyRequest
readonly NodeId Opc.Ua.DataTypeIds.MonitoredItemModifyRequest = new NodeId(Opc.Ua.DataTypes.MonitoredItemModifyRequest) static
The identifier for the MonitoredItemModifyRequest DataType.
Definition at line 31135 of file Opc.Ua.Constants.cs.
MonitoredItemModifyResult
readonly NodeId Opc.Ua.DataTypeIds.MonitoredItemModifyResult = new NodeId(Opc.Ua.DataTypes.MonitoredItemModifyResult) static
The identifier for the MonitoredItemModifyResult DataType.
Definition at line 31140 of file Opc.Ua.Constants.cs.
MonitoredItemNotification
readonly NodeId Opc.Ua.DataTypeIds.MonitoredItemNotification = new NodeId(Opc.Ua.DataTypes.MonitoredItemNotification) static
The identifier for the MonitoredItemNotification DataType.
Definition at line 31230 of file Opc.Ua.Constants.cs.
MonitoringFilter
readonly NodeId Opc.Ua.DataTypeIds.MonitoringFilter = new NodeId(Opc.Ua.DataTypes.MonitoringFilter) static
The identifier for the MonitoringFilter DataType.
Definition at line 31070 of file Opc.Ua.Constants.cs.
MonitoringFilterResult
readonly NodeId Opc.Ua.DataTypeIds.MonitoringFilterResult = new NodeId(Opc.Ua.DataTypes.MonitoringFilterResult) static
The identifier for the MonitoringFilterResult DataType.
Definition at line 31095 of file Opc.Ua.Constants.cs.
MonitoringMode
readonly NodeId Opc.Ua.DataTypeIds.MonitoringMode = new NodeId(Opc.Ua.DataTypes.MonitoringMode) static
The identifier for the MonitoringMode DataType.
Definition at line 31055 of file Opc.Ua.Constants.cs.
MonitoringParameters
readonly NodeId Opc.Ua.DataTypeIds.MonitoringParameters = new NodeId(Opc.Ua.DataTypes.MonitoringParameters) static
The identifier for the MonitoringParameters DataType.
Definition at line 31110 of file Opc.Ua.Constants.cs.
NamingRuleType
readonly NodeId Opc.Ua.DataTypeIds.NamingRuleType = new NodeId(Opc.Ua.DataTypes.NamingRuleType) static
The identifier for the NamingRuleType DataType.
Definition at line 29640 of file Opc.Ua.Constants.cs.
NetworkAddressDataType
readonly NodeId Opc.Ua.DataTypeIds.NetworkAddressDataType = new NodeId(Opc.Ua.DataTypes.NetworkAddressDataType) static
The identifier for the NetworkAddressDataType DataType.
Definition at line 29890 of file Opc.Ua.Constants.cs.
NetworkAddressUrlDataType
readonly NodeId Opc.Ua.DataTypeIds.NetworkAddressUrlDataType = new NodeId(Opc.Ua.DataTypes.NetworkAddressUrlDataType) static
The identifier for the NetworkAddressUrlDataType DataType.
Definition at line 29895 of file Opc.Ua.Constants.cs.
NetworkGroupDataType
readonly NodeId Opc.Ua.DataTypeIds.NetworkGroupDataType = new NodeId(Opc.Ua.DataTypes.NetworkGroupDataType) static
The identifier for the NetworkGroupDataType DataType.
Definition at line 31330 of file Opc.Ua.Constants.cs.
Node
readonly NodeId Opc.Ua.DataTypeIds.Node = new NodeId(Opc.Ua.DataTypes.Node) static
The identifier for the Node DataType.
Definition at line 30125 of file Opc.Ua.Constants.cs.
NodeAttributes
readonly NodeId Opc.Ua.DataTypeIds.NodeAttributes = new NodeId(Opc.Ua.DataTypes.NodeAttributes) static
The identifier for the NodeAttributes DataType.
Definition at line 30520 of file Opc.Ua.Constants.cs.
NodeAttributesMask
readonly NodeId Opc.Ua.DataTypeIds.NodeAttributesMask = new NodeId(Opc.Ua.DataTypes.NodeAttributesMask) static
The identifier for the NodeAttributesMask DataType.
Definition at line 30515 of file Opc.Ua.Constants.cs.
NodeClass
readonly NodeId Opc.Ua.DataTypeIds.NodeClass = new NodeId(Opc.Ua.DataTypes.NodeClass) static
The identifier for the NodeClass DataType.
Definition at line 30065 of file Opc.Ua.Constants.cs.
NodeId
readonly NodeId Opc.Ua.DataTypeIds.NodeId = new NodeId(Opc.Ua.DataTypes.NodeId) static
The identifier for the NodeId DataType.
Definition at line 29590 of file Opc.Ua.Constants.cs.
NodeReference
readonly NodeId Opc.Ua.DataTypeIds.NodeReference = new NodeId(Opc.Ua.DataTypes.NodeReference) static
The identifier for the NodeReference DataType.
Definition at line 30800 of file Opc.Ua.Constants.cs.
NodeTypeDescription
readonly NodeId Opc.Ua.DataTypeIds.NodeTypeDescription = new NodeId(Opc.Ua.DataTypes.NodeTypeDescription) static
The identifier for the NodeTypeDescription DataType.
Definition at line 30785 of file Opc.Ua.Constants.cs.
NormalizedString
readonly NodeId Opc.Ua.DataTypeIds.NormalizedString = new NodeId(Opc.Ua.DataTypes.NormalizedString) static
The identifier for the NormalizedString DataType.
Definition at line 30210 of file Opc.Ua.Constants.cs.
NotificationData
readonly NodeId Opc.Ua.DataTypeIds.NotificationData = new NodeId(Opc.Ua.DataTypes.NotificationData) static
The identifier for the NotificationData DataType.
Definition at line 31220 of file Opc.Ua.Constants.cs.
NotificationMessage
readonly NodeId Opc.Ua.DataTypeIds.NotificationMessage = new NodeId(Opc.Ua.DataTypes.NotificationMessage) static
The identifier for the NotificationMessage DataType.
Definition at line 31215 of file Opc.Ua.Constants.cs.
Number
readonly NodeId Opc.Ua.DataTypeIds.Number = new NodeId(Opc.Ua.DataTypes.Number) static
The identifier for the Number DataType.
Definition at line 29490 of file Opc.Ua.Constants.cs.
NumericRange
readonly NodeId Opc.Ua.DataTypeIds.NumericRange = new NodeId(Opc.Ua.DataTypes.NumericRange) static
The identifier for the NumericRange DataType.
Definition at line 30760 of file Opc.Ua.Constants.cs.
ObjectAttributes
readonly NodeId Opc.Ua.DataTypeIds.ObjectAttributes = new NodeId(Opc.Ua.DataTypes.ObjectAttributes) static
The identifier for the ObjectAttributes DataType.
Definition at line 30525 of file Opc.Ua.Constants.cs.
ObjectNode
readonly NodeId Opc.Ua.DataTypeIds.ObjectNode = new NodeId(Opc.Ua.DataTypes.ObjectNode) static
The identifier for the ObjectNode DataType.
Definition at line 30140 of file Opc.Ua.Constants.cs.
ObjectTypeAttributes
readonly NodeId Opc.Ua.DataTypeIds.ObjectTypeAttributes = new NodeId(Opc.Ua.DataTypes.ObjectTypeAttributes) static
The identifier for the ObjectTypeAttributes DataType.
Definition at line 30540 of file Opc.Ua.Constants.cs.
ObjectTypeNode
readonly NodeId Opc.Ua.DataTypeIds.ObjectTypeNode = new NodeId(Opc.Ua.DataTypes.ObjectTypeNode) static
The identifier for the ObjectTypeNode DataType.
Definition at line 30145 of file Opc.Ua.Constants.cs.
OpenFileMode
readonly NodeId Opc.Ua.DataTypeIds.OpenFileMode = new NodeId(Opc.Ua.DataTypes.OpenFileMode) static
The identifier for the OpenFileMode DataType.
Definition at line 29730 of file Opc.Ua.Constants.cs.
OpenSecureChannelRequest
readonly NodeId Opc.Ua.DataTypeIds.OpenSecureChannelRequest = new NodeId(Opc.Ua.DataTypes.OpenSecureChannelRequest) static
The identifier for the OpenSecureChannelRequest DataType.
Definition at line 30410 of file Opc.Ua.Constants.cs.
OpenSecureChannelResponse
readonly NodeId Opc.Ua.DataTypeIds.OpenSecureChannelResponse = new NodeId(Opc.Ua.DataTypes.OpenSecureChannelResponse) static
The identifier for the OpenSecureChannelResponse DataType.
Definition at line 30415 of file Opc.Ua.Constants.cs.
OptionSet
readonly NodeId Opc.Ua.DataTypeIds.OptionSet = new NodeId(Opc.Ua.DataTypes.OptionSet) static
The identifier for the OptionSet DataType.
Definition at line 30200 of file Opc.Ua.Constants.cs.
Orientation
readonly NodeId Opc.Ua.DataTypeIds.Orientation = new NodeId(Opc.Ua.DataTypes.Orientation) static
The identifier for the Orientation DataType.
Definition at line 29710 of file Opc.Ua.Constants.cs.
OverrideValueHandling
readonly NodeId Opc.Ua.DataTypeIds.OverrideValueHandling = new NodeId(Opc.Ua.DataTypes.OverrideValueHandling) static
The identifier for the OverrideValueHandling DataType.
Definition at line 29945 of file Opc.Ua.Constants.cs.
ParsingResult
readonly NodeId Opc.Ua.DataTypeIds.ParsingResult = new NodeId(Opc.Ua.DataTypes.ParsingResult) static
The identifier for the ParsingResult DataType.
Definition at line 30850 of file Opc.Ua.Constants.cs.
PerformUpdateType
readonly NodeId Opc.Ua.DataTypeIds.PerformUpdateType = new NodeId(Opc.Ua.DataTypes.PerformUpdateType) static
The identifier for the PerformUpdateType DataType.
Definition at line 30985 of file Opc.Ua.Constants.cs.
PermissionType
readonly NodeId Opc.Ua.DataTypeIds.PermissionType = new NodeId(Opc.Ua.DataTypes.PermissionType) static
The identifier for the PermissionType DataType.
Definition at line 30070 of file Opc.Ua.Constants.cs.
ProgramDiagnostic2DataType
readonly NodeId Opc.Ua.DataTypeIds.ProgramDiagnostic2DataType = new NodeId(Opc.Ua.DataTypes.ProgramDiagnostic2DataType) static
The identifier for the ProgramDiagnostic2DataType DataType.
Definition at line 31430 of file Opc.Ua.Constants.cs.
ProgramDiagnosticDataType
readonly NodeId Opc.Ua.DataTypeIds.ProgramDiagnosticDataType = new NodeId(Opc.Ua.DataTypes.ProgramDiagnosticDataType) static
The identifier for the ProgramDiagnosticDataType DataType.
Definition at line 31425 of file Opc.Ua.Constants.cs.
PublishedDataItemsDataType
readonly NodeId Opc.Ua.DataTypeIds.PublishedDataItemsDataType = new NodeId(Opc.Ua.DataTypes.PublishedDataItemsDataType) static
The identifier for the PublishedDataItemsDataType DataType.
Definition at line 29830 of file Opc.Ua.Constants.cs.
PublishedDataSetDataType
readonly NodeId Opc.Ua.DataTypeIds.PublishedDataSetDataType = new NodeId(Opc.Ua.DataTypes.PublishedDataSetDataType) static
The identifier for the PublishedDataSetDataType DataType.
Definition at line 29815 of file Opc.Ua.Constants.cs.
PublishedDataSetSourceDataType
readonly NodeId Opc.Ua.DataTypeIds.PublishedDataSetSourceDataType = new NodeId(Opc.Ua.DataTypes.PublishedDataSetSourceDataType) static
The identifier for the PublishedDataSetSourceDataType DataType.
Definition at line 29820 of file Opc.Ua.Constants.cs.
PublishedEventsDataType
readonly NodeId Opc.Ua.DataTypeIds.PublishedEventsDataType = new NodeId(Opc.Ua.DataTypes.PublishedEventsDataType) static
The identifier for the PublishedEventsDataType DataType.
Definition at line 29835 of file Opc.Ua.Constants.cs.
PublishedVariableDataType
readonly NodeId Opc.Ua.DataTypeIds.PublishedVariableDataType = new NodeId(Opc.Ua.DataTypes.PublishedVariableDataType) static
The identifier for the PublishedVariableDataType DataType.
Definition at line 29825 of file Opc.Ua.Constants.cs.
PublishRequest
readonly NodeId Opc.Ua.DataTypeIds.PublishRequest = new NodeId(Opc.Ua.DataTypes.PublishRequest) static
The identifier for the PublishRequest DataType.
Definition at line 31260 of file Opc.Ua.Constants.cs.
Referenced by Opc.Ua.SessionEndpoint.EndDeleteSubscriptions().
PublishResponse
readonly NodeId Opc.Ua.DataTypeIds.PublishResponse = new NodeId(Opc.Ua.DataTypes.PublishResponse) static
The identifier for the PublishResponse DataType.
Definition at line 31265 of file Opc.Ua.Constants.cs.
PubSubConfigurationDataType
readonly NodeId Opc.Ua.DataTypeIds.PubSubConfigurationDataType = new NodeId(Opc.Ua.DataTypes.PubSubConfigurationDataType) static
The identifier for the PubSubConfigurationDataType DataType.
Definition at line 29955 of file Opc.Ua.Constants.cs.
PubSubConnectionDataType
readonly NodeId Opc.Ua.DataTypeIds.PubSubConnectionDataType = new NodeId(Opc.Ua.DataTypes.PubSubConnectionDataType) static
The identifier for the PubSubConnectionDataType DataType.
Definition at line 29880 of file Opc.Ua.Constants.cs.
PubSubDiagnosticsCounterClassification
readonly NodeId Opc.Ua.DataTypeIds.PubSubDiagnosticsCounterClassification = new NodeId(Opc.Ua.DataTypes.PubSubDiagnosticsCounterClassification) static
The identifier for the PubSubDiagnosticsCounterClassification DataType.
Definition at line 30055 of file Opc.Ua.Constants.cs.
PubSubGroupDataType
readonly NodeId Opc.Ua.DataTypeIds.PubSubGroupDataType = new NodeId(Opc.Ua.DataTypes.PubSubGroupDataType) static
The identifier for the PubSubGroupDataType DataType.
Definition at line 29860 of file Opc.Ua.Constants.cs.
PubSubState
readonly NodeId Opc.Ua.DataTypeIds.PubSubState = new NodeId(Opc.Ua.DataTypes.PubSubState) static
The identifier for the PubSubState DataType.
Definition at line 29790 of file Opc.Ua.Constants.cs.
QualifiedName
readonly NodeId Opc.Ua.DataTypeIds.QualifiedName = new NodeId(Opc.Ua.DataTypes.QualifiedName) static
The identifier for the QualifiedName DataType.
Definition at line 29605 of file Opc.Ua.Constants.cs.
QueryDataDescription
readonly NodeId Opc.Ua.DataTypeIds.QueryDataDescription = new NodeId(Opc.Ua.DataTypes.QueryDataDescription) static
The identifier for the QueryDataDescription DataType.
Definition at line 30780 of file Opc.Ua.Constants.cs.
QueryDataSet
readonly NodeId Opc.Ua.DataTypeIds.QueryDataSet = new NodeId(Opc.Ua.DataTypes.QueryDataSet) static
The identifier for the QueryDataSet DataType.
Definition at line 30795 of file Opc.Ua.Constants.cs.
QueryFirstRequest
readonly NodeId Opc.Ua.DataTypeIds.QueryFirstRequest = new NodeId(Opc.Ua.DataTypes.QueryFirstRequest) static
The identifier for the QueryFirstRequest DataType.
Definition at line 30855 of file Opc.Ua.Constants.cs.
Referenced by Opc.Ua.SessionEndpoint.EndDeleteSubscriptions().
QueryFirstResponse
readonly NodeId Opc.Ua.DataTypeIds.QueryFirstResponse = new NodeId(Opc.Ua.DataTypes.QueryFirstResponse) static
The identifier for the QueryFirstResponse DataType.
Definition at line 30860 of file Opc.Ua.Constants.cs.
QueryNextRequest
readonly NodeId Opc.Ua.DataTypeIds.QueryNextRequest = new NodeId(Opc.Ua.DataTypes.QueryNextRequest) static
The identifier for the QueryNextRequest DataType.
Definition at line 30865 of file Opc.Ua.Constants.cs.
Referenced by Opc.Ua.SessionEndpoint.EndDeleteSubscriptions().
QueryNextResponse
readonly NodeId Opc.Ua.DataTypeIds.QueryNextResponse = new NodeId(Opc.Ua.DataTypes.QueryNextResponse) static
The identifier for the QueryNextResponse DataType.
Definition at line 30870 of file Opc.Ua.Constants.cs.
Range
readonly NodeId Opc.Ua.DataTypeIds.Range = new NodeId(Opc.Ua.DataTypes.Range) static
The identifier for the Range DataType.
Definition at line 31390 of file Opc.Ua.Constants.cs.
RationalNumber
readonly NodeId Opc.Ua.DataTypeIds.RationalNumber = new NodeId(Opc.Ua.DataTypes.RationalNumber) static
The identifier for the RationalNumber DataType.
Definition at line 29685 of file Opc.Ua.Constants.cs.
ReadAtTimeDetails
readonly NodeId Opc.Ua.DataTypeIds.ReadAtTimeDetails = new NodeId(Opc.Ua.DataTypes.ReadAtTimeDetails) static
The identifier for the ReadAtTimeDetails DataType.
Definition at line 30925 of file Opc.Ua.Constants.cs.
ReaderGroupDataType
readonly NodeId Opc.Ua.DataTypeIds.ReaderGroupDataType = new NodeId(Opc.Ua.DataTypes.ReaderGroupDataType) static
The identifier for the ReaderGroupDataType DataType.
Definition at line 29900 of file Opc.Ua.Constants.cs.
ReaderGroupMessageDataType
readonly NodeId Opc.Ua.DataTypeIds.ReaderGroupMessageDataType = new NodeId(Opc.Ua.DataTypes.ReaderGroupMessageDataType) static
The identifier for the ReaderGroupMessageDataType DataType.
Definition at line 29910 of file Opc.Ua.Constants.cs.
ReaderGroupTransportDataType
readonly NodeId Opc.Ua.DataTypeIds.ReaderGroupTransportDataType = new NodeId(Opc.Ua.DataTypes.ReaderGroupTransportDataType) static
The identifier for the ReaderGroupTransportDataType DataType.
Definition at line 29905 of file Opc.Ua.Constants.cs.
ReadEventDetails
readonly NodeId Opc.Ua.DataTypeIds.ReadEventDetails = new NodeId(Opc.Ua.DataTypes.ReadEventDetails) static
The identifier for the ReadEventDetails DataType.
Definition at line 30910 of file Opc.Ua.Constants.cs.
ReadProcessedDetails
readonly NodeId Opc.Ua.DataTypeIds.ReadProcessedDetails = new NodeId(Opc.Ua.DataTypes.ReadProcessedDetails) static
The identifier for the ReadProcessedDetails DataType.
Definition at line 30920 of file Opc.Ua.Constants.cs.
ReadRawModifiedDetails
readonly NodeId Opc.Ua.DataTypeIds.ReadRawModifiedDetails = new NodeId(Opc.Ua.DataTypes.ReadRawModifiedDetails) static
The identifier for the ReadRawModifiedDetails DataType.
Definition at line 30915 of file Opc.Ua.Constants.cs.
ReadRequest
readonly NodeId Opc.Ua.DataTypeIds.ReadRequest = new NodeId(Opc.Ua.DataTypes.ReadRequest) static
The identifier for the ReadRequest DataType.
Definition at line 30885 of file Opc.Ua.Constants.cs.
Referenced by Opc.Ua.SessionEndpoint.EndDeleteSubscriptions().
ReadResponse
readonly NodeId Opc.Ua.DataTypeIds.ReadResponse = new NodeId(Opc.Ua.DataTypes.ReadResponse) static
The identifier for the ReadResponse DataType.
Definition at line 30890 of file Opc.Ua.Constants.cs.
ReadValueId
readonly NodeId Opc.Ua.DataTypeIds.ReadValueId = new NodeId(Opc.Ua.DataTypes.ReadValueId) static
The identifier for the ReadValueId DataType.
Definition at line 30880 of file Opc.Ua.Constants.cs.
RedundancySupport
readonly NodeId Opc.Ua.DataTypeIds.RedundancySupport = new NodeId(Opc.Ua.DataTypes.RedundancySupport) static
The identifier for the RedundancySupport DataType.
Definition at line 31310 of file Opc.Ua.Constants.cs.
RedundantServerDataType
readonly NodeId Opc.Ua.DataTypeIds.RedundantServerDataType = new NodeId(Opc.Ua.DataTypes.RedundantServerDataType) static
The identifier for the RedundantServerDataType DataType.
Definition at line 31320 of file Opc.Ua.Constants.cs.
ReferenceDescription
readonly NodeId Opc.Ua.DataTypeIds.ReferenceDescription = new NodeId(Opc.Ua.DataTypes.ReferenceDescription) static
The identifier for the ReferenceDescription DataType.
Definition at line 30665 of file Opc.Ua.Constants.cs.
ReferenceNode
readonly NodeId Opc.Ua.DataTypeIds.ReferenceNode = new NodeId(Opc.Ua.DataTypes.ReferenceNode) static
The identifier for the ReferenceNode DataType.
Definition at line 30180 of file Opc.Ua.Constants.cs.
ReferenceTypeAttributes
readonly NodeId Opc.Ua.DataTypeIds.ReferenceTypeAttributes = new NodeId(Opc.Ua.DataTypes.ReferenceTypeAttributes) static
The identifier for the ReferenceTypeAttributes DataType.
Definition at line 30550 of file Opc.Ua.Constants.cs.
ReferenceTypeNode
readonly NodeId Opc.Ua.DataTypeIds.ReferenceTypeNode = new NodeId(Opc.Ua.DataTypes.ReferenceTypeNode) static
The identifier for the ReferenceTypeNode DataType.
Definition at line 30160 of file Opc.Ua.Constants.cs.
RegisteredServer
readonly NodeId Opc.Ua.DataTypeIds.RegisteredServer = new NodeId(Opc.Ua.DataTypes.RegisteredServer) static
The identifier for the RegisteredServer DataType.
Definition at line 30365 of file Opc.Ua.Constants.cs.
RegisterNodesRequest
readonly NodeId Opc.Ua.DataTypeIds.RegisterNodesRequest = new NodeId(Opc.Ua.DataTypes.RegisterNodesRequest) static
The identifier for the RegisterNodesRequest DataType.
Definition at line 30735 of file Opc.Ua.Constants.cs.
Referenced by Opc.Ua.SessionEndpoint.EndDeleteSubscriptions().
RegisterNodesResponse
readonly NodeId Opc.Ua.DataTypeIds.RegisterNodesResponse = new NodeId(Opc.Ua.DataTypes.RegisterNodesResponse) static
The identifier for the RegisterNodesResponse DataType.
Definition at line 30740 of file Opc.Ua.Constants.cs.
RegisterServer2Request
readonly NodeId Opc.Ua.DataTypeIds.RegisterServer2Request = new NodeId(Opc.Ua.DataTypes.RegisterServer2Request) static
The identifier for the RegisterServer2Request DataType.
Definition at line 30390 of file Opc.Ua.Constants.cs.
Referenced by Opc.Ua.DiscoveryEndpoint.EndRegisterServer2().
RegisterServer2Response
readonly NodeId Opc.Ua.DataTypeIds.RegisterServer2Response = new NodeId(Opc.Ua.DataTypes.RegisterServer2Response) static
The identifier for the RegisterServer2Response DataType.
Definition at line 30395 of file Opc.Ua.Constants.cs.
RegisterServerRequest
readonly NodeId Opc.Ua.DataTypeIds.RegisterServerRequest = new NodeId(Opc.Ua.DataTypes.RegisterServerRequest) static
The identifier for the RegisterServerRequest DataType.
Definition at line 30370 of file Opc.Ua.Constants.cs.
Referenced by Opc.Ua.DiscoveryEndpoint.EndRegisterServer2().
RegisterServerResponse
readonly NodeId Opc.Ua.DataTypeIds.RegisterServerResponse = new NodeId(Opc.Ua.DataTypes.RegisterServerResponse) static
The identifier for the RegisterServerResponse DataType.
Definition at line 30375 of file Opc.Ua.Constants.cs.
RelativePath
readonly NodeId Opc.Ua.DataTypeIds.RelativePath = new NodeId(Opc.Ua.DataTypes.RelativePath) static
The identifier for the RelativePath DataType.
Definition at line 30705 of file Opc.Ua.Constants.cs.
RelativePathElement
readonly NodeId Opc.Ua.DataTypeIds.RelativePathElement = new NodeId(Opc.Ua.DataTypes.RelativePathElement) static
The identifier for the RelativePathElement DataType.
Definition at line 30700 of file Opc.Ua.Constants.cs.
RepublishRequest
readonly NodeId Opc.Ua.DataTypeIds.RepublishRequest = new NodeId(Opc.Ua.DataTypes.RepublishRequest) static
The identifier for the RepublishRequest DataType.
Definition at line 31270 of file Opc.Ua.Constants.cs.
Referenced by Opc.Ua.SessionEndpoint.EndDeleteSubscriptions().
RepublishResponse
readonly NodeId Opc.Ua.DataTypeIds.RepublishResponse = new NodeId(Opc.Ua.DataTypes.RepublishResponse) static
The identifier for the RepublishResponse DataType.
Definition at line 31275 of file Opc.Ua.Constants.cs.
RequestHeader
readonly NodeId Opc.Ua.DataTypeIds.RequestHeader = new NodeId(Opc.Ua.DataTypes.RequestHeader) static
The identifier for the RequestHeader DataType.
Definition at line 30275 of file Opc.Ua.Constants.cs.
ResponseHeader
readonly NodeId Opc.Ua.DataTypeIds.ResponseHeader = new NodeId(Opc.Ua.DataTypes.ResponseHeader) static
The identifier for the ResponseHeader DataType.
Definition at line 30280 of file Opc.Ua.Constants.cs.
RolePermissionType
readonly NodeId Opc.Ua.DataTypeIds.RolePermissionType = new NodeId(Opc.Ua.DataTypes.RolePermissionType) static
The identifier for the RolePermissionType DataType.
Definition at line 30095 of file Opc.Ua.Constants.cs.
RsaEncryptedSecret
readonly NodeId Opc.Ua.DataTypeIds.RsaEncryptedSecret = new NodeId(Opc.Ua.DataTypes.RsaEncryptedSecret) static
The identifier for the RsaEncryptedSecret DataType.
Definition at line 30480 of file Opc.Ua.Constants.cs.
SamplingIntervalDiagnosticsDataType
readonly NodeId Opc.Ua.DataTypeIds.SamplingIntervalDiagnosticsDataType = new NodeId(Opc.Ua.DataTypes.SamplingIntervalDiagnosticsDataType) static
The identifier for the SamplingIntervalDiagnosticsDataType DataType.
Definition at line 31335 of file Opc.Ua.Constants.cs.
SByte
readonly NodeId Opc.Ua.DataTypeIds.SByte = new NodeId(Opc.Ua.DataTypes.SByte) static
The identifier for the SByte DataType.
Definition at line 29515 of file Opc.Ua.Constants.cs.
SecurityTokenRequestType
readonly NodeId Opc.Ua.DataTypeIds.SecurityTokenRequestType = new NodeId(Opc.Ua.DataTypes.SecurityTokenRequestType) static
The identifier for the SecurityTokenRequestType DataType.
Definition at line 30400 of file Opc.Ua.Constants.cs.
SemanticChangeStructureDataType
readonly NodeId Opc.Ua.DataTypeIds.SemanticChangeStructureDataType = new NodeId(Opc.Ua.DataTypes.SemanticChangeStructureDataType) static
The identifier for the SemanticChangeStructureDataType DataType.
Definition at line 31385 of file Opc.Ua.Constants.cs.
ServerDiagnosticsSummaryDataType
readonly NodeId Opc.Ua.DataTypeIds.ServerDiagnosticsSummaryDataType = new NodeId(Opc.Ua.DataTypes.ServerDiagnosticsSummaryDataType) static
The identifier for the ServerDiagnosticsSummaryDataType DataType.
Definition at line 31340 of file Opc.Ua.Constants.cs.
ServerOnNetwork
readonly NodeId Opc.Ua.DataTypeIds.ServerOnNetwork = new NodeId(Opc.Ua.DataTypes.ServerOnNetwork) static
The identifier for the ServerOnNetwork DataType.
Definition at line 30315 of file Opc.Ua.Constants.cs.
ServerState
readonly NodeId Opc.Ua.DataTypeIds.ServerState = new NodeId(Opc.Ua.DataTypes.ServerState) static
The identifier for the ServerState DataType.
Definition at line 31315 of file Opc.Ua.Constants.cs.
ServerStatusDataType
readonly NodeId Opc.Ua.DataTypeIds.ServerStatusDataType = new NodeId(Opc.Ua.DataTypes.ServerStatusDataType) static
The identifier for the ServerStatusDataType DataType.
Definition at line 31345 of file Opc.Ua.Constants.cs.
ServiceCounterDataType
readonly NodeId Opc.Ua.DataTypeIds.ServiceCounterDataType = new NodeId(Opc.Ua.DataTypes.ServiceCounterDataType) static
The identifier for the ServiceCounterDataType DataType.
Definition at line 31360 of file Opc.Ua.Constants.cs.
ServiceFault
readonly NodeId Opc.Ua.DataTypeIds.ServiceFault = new NodeId(Opc.Ua.DataTypes.ServiceFault) static
The identifier for the ServiceFault DataType.
Definition at line 30290 of file Opc.Ua.Constants.cs.
SessionAuthenticationToken
readonly NodeId Opc.Ua.DataTypeIds.SessionAuthenticationToken = new NodeId(Opc.Ua.DataTypes.SessionAuthenticationToken) static
The identifier for the SessionAuthenticationToken DataType.
Definition at line 30435 of file Opc.Ua.Constants.cs.
SessionDiagnosticsDataType
readonly NodeId Opc.Ua.DataTypeIds.SessionDiagnosticsDataType = new NodeId(Opc.Ua.DataTypes.SessionDiagnosticsDataType) static
The identifier for the SessionDiagnosticsDataType DataType.
Definition at line 31350 of file Opc.Ua.Constants.cs.
SessionlessInvokeRequestType
readonly NodeId Opc.Ua.DataTypeIds.SessionlessInvokeRequestType = new NodeId(Opc.Ua.DataTypes.SessionlessInvokeRequestType) static
The identifier for the SessionlessInvokeRequestType DataType.
Definition at line 30295 of file Opc.Ua.Constants.cs.
SessionlessInvokeResponseType
readonly NodeId Opc.Ua.DataTypeIds.SessionlessInvokeResponseType = new NodeId(Opc.Ua.DataTypes.SessionlessInvokeResponseType) static
The identifier for the SessionlessInvokeResponseType DataType.
Definition at line 30300 of file Opc.Ua.Constants.cs.
SessionSecurityDiagnosticsDataType
readonly NodeId Opc.Ua.DataTypeIds.SessionSecurityDiagnosticsDataType = new NodeId(Opc.Ua.DataTypes.SessionSecurityDiagnosticsDataType) static
The identifier for the SessionSecurityDiagnosticsDataType DataType.
Definition at line 31355 of file Opc.Ua.Constants.cs.
SetMonitoringModeRequest
readonly NodeId Opc.Ua.DataTypeIds.SetMonitoringModeRequest = new NodeId(Opc.Ua.DataTypes.SetMonitoringModeRequest) static
The identifier for the SetMonitoringModeRequest DataType.
Definition at line 31155 of file Opc.Ua.Constants.cs.
Referenced by Opc.Ua.SessionEndpoint.EndDeleteSubscriptions().
SetMonitoringModeResponse
readonly NodeId Opc.Ua.DataTypeIds.SetMonitoringModeResponse = new NodeId(Opc.Ua.DataTypes.SetMonitoringModeResponse) static
The identifier for the SetMonitoringModeResponse DataType.
Definition at line 31160 of file Opc.Ua.Constants.cs.
SetPublishingModeRequest
readonly NodeId Opc.Ua.DataTypeIds.SetPublishingModeRequest = new NodeId(Opc.Ua.DataTypes.SetPublishingModeRequest) static
The identifier for the SetPublishingModeRequest DataType.
Definition at line 31205 of file Opc.Ua.Constants.cs.
Referenced by Opc.Ua.SessionEndpoint.EndDeleteSubscriptions().
SetPublishingModeResponse
readonly NodeId Opc.Ua.DataTypeIds.SetPublishingModeResponse = new NodeId(Opc.Ua.DataTypes.SetPublishingModeResponse) static
The identifier for the SetPublishingModeResponse DataType.
Definition at line 31210 of file Opc.Ua.Constants.cs.
SetTriggeringRequest
readonly NodeId Opc.Ua.DataTypeIds.SetTriggeringRequest = new NodeId(Opc.Ua.DataTypes.SetTriggeringRequest) static
The identifier for the SetTriggeringRequest DataType.
Definition at line 31165 of file Opc.Ua.Constants.cs.
Referenced by Opc.Ua.SessionEndpoint.EndDeleteSubscriptions().
SetTriggeringResponse
readonly NodeId Opc.Ua.DataTypeIds.SetTriggeringResponse = new NodeId(Opc.Ua.DataTypes.SetTriggeringResponse) static
The identifier for the SetTriggeringResponse DataType.
Definition at line 31170 of file Opc.Ua.Constants.cs.
SignatureData
readonly NodeId Opc.Ua.DataTypeIds.SignatureData = new NodeId(Opc.Ua.DataTypes.SignatureData) static
The identifier for the SignatureData DataType.
Definition at line 30440 of file Opc.Ua.Constants.cs.
SignedSoftwareCertificate
readonly NodeId Opc.Ua.DataTypeIds.SignedSoftwareCertificate = new NodeId(Opc.Ua.DataTypes.SignedSoftwareCertificate) static
The identifier for the SignedSoftwareCertificate DataType.
Definition at line 30430 of file Opc.Ua.Constants.cs.
SimpleAttributeOperand
readonly NodeId Opc.Ua.DataTypeIds.SimpleAttributeOperand = new NodeId(Opc.Ua.DataTypes.SimpleAttributeOperand) static
The identifier for the SimpleAttributeOperand DataType.
Definition at line 30835 of file Opc.Ua.Constants.cs.
SimpleTypeDescription
readonly NodeId Opc.Ua.DataTypeIds.SimpleTypeDescription = new NodeId(Opc.Ua.DataTypes.SimpleTypeDescription) static
The identifier for the SimpleTypeDescription DataType.
Definition at line 29780 of file Opc.Ua.Constants.cs.
StatusChangeNotification
readonly NodeId Opc.Ua.DataTypeIds.StatusChangeNotification = new NodeId(Opc.Ua.DataTypes.StatusChangeNotification) static
The identifier for the StatusChangeNotification DataType.
Definition at line 31250 of file Opc.Ua.Constants.cs.
StatusCode
readonly NodeId Opc.Ua.DataTypeIds.StatusCode = new NodeId(Opc.Ua.DataTypes.StatusCode) static
The identifier for the StatusCode DataType.
Definition at line 29600 of file Opc.Ua.Constants.cs.
StatusResult
readonly NodeId Opc.Ua.DataTypeIds.StatusResult = new NodeId(Opc.Ua.DataTypes.StatusResult) static
The identifier for the StatusResult DataType.
Definition at line 31365 of file Opc.Ua.Constants.cs.
String
readonly NodeId Opc.Ua.DataTypeIds.String = new NodeId(Opc.Ua.DataTypes.String) static
The identifier for the String DataType.
Definition at line 29565 of file Opc.Ua.Constants.cs.
Structure
readonly NodeId Opc.Ua.DataTypeIds.Structure = new NodeId(Opc.Ua.DataTypes.Structure) static
The identifier for the Structure DataType.
Definition at line 29615 of file Opc.Ua.Constants.cs.
StructureDefinition
readonly NodeId Opc.Ua.DataTypeIds.StructureDefinition = new NodeId(Opc.Ua.DataTypes.StructureDefinition) static
The identifier for the StructureDefinition DataType.
Definition at line 30115 of file Opc.Ua.Constants.cs.
StructureDescription
readonly NodeId Opc.Ua.DataTypeIds.StructureDescription = new NodeId(Opc.Ua.DataTypes.StructureDescription) static
The identifier for the StructureDescription DataType.
Definition at line 29770 of file Opc.Ua.Constants.cs.
StructureField
readonly NodeId Opc.Ua.DataTypeIds.StructureField = new NodeId(Opc.Ua.DataTypes.StructureField) static
The identifier for the StructureField DataType.
Definition at line 30110 of file Opc.Ua.Constants.cs.
StructureType
readonly NodeId Opc.Ua.DataTypeIds.StructureType = new NodeId(Opc.Ua.DataTypes.StructureType) static
The identifier for the StructureType DataType.
Definition at line 30105 of file Opc.Ua.Constants.cs.
SubscribedDataSetDataType
readonly NodeId Opc.Ua.DataTypeIds.SubscribedDataSetDataType = new NodeId(Opc.Ua.DataTypes.SubscribedDataSetDataType) static
The identifier for the SubscribedDataSetDataType DataType.
Definition at line 29930 of file Opc.Ua.Constants.cs.
SubscribedDataSetMirrorDataType
readonly NodeId Opc.Ua.DataTypeIds.SubscribedDataSetMirrorDataType = new NodeId(Opc.Ua.DataTypes.SubscribedDataSetMirrorDataType) static
The identifier for the SubscribedDataSetMirrorDataType DataType.
Definition at line 29950 of file Opc.Ua.Constants.cs.
SubscriptionAcknowledgement
readonly NodeId Opc.Ua.DataTypeIds.SubscriptionAcknowledgement = new NodeId(Opc.Ua.DataTypes.SubscriptionAcknowledgement) static
The identifier for the SubscriptionAcknowledgement DataType.
Definition at line 31255 of file Opc.Ua.Constants.cs.
SubscriptionDiagnosticsDataType
readonly NodeId Opc.Ua.DataTypeIds.SubscriptionDiagnosticsDataType = new NodeId(Opc.Ua.DataTypes.SubscriptionDiagnosticsDataType) static
The identifier for the SubscriptionDiagnosticsDataType DataType.
Definition at line 31370 of file Opc.Ua.Constants.cs.
TargetVariablesDataType
readonly NodeId Opc.Ua.DataTypeIds.TargetVariablesDataType = new NodeId(Opc.Ua.DataTypes.TargetVariablesDataType) static
The identifier for the TargetVariablesDataType DataType.
Definition at line 29935 of file Opc.Ua.Constants.cs.
ThreeDCartesianCoordinates
readonly NodeId Opc.Ua.DataTypeIds.ThreeDCartesianCoordinates = new NodeId(Opc.Ua.DataTypes.ThreeDCartesianCoordinates) static
The identifier for the ThreeDCartesianCoordinates DataType.
Definition at line 29705 of file Opc.Ua.Constants.cs.
ThreeDFrame
readonly NodeId Opc.Ua.DataTypeIds.ThreeDFrame = new NodeId(Opc.Ua.DataTypes.ThreeDFrame) static
The identifier for the ThreeDFrame DataType.
Definition at line 29725 of file Opc.Ua.Constants.cs.
ThreeDOrientation
readonly NodeId Opc.Ua.DataTypeIds.ThreeDOrientation = new NodeId(Opc.Ua.DataTypes.ThreeDOrientation) static
The identifier for the ThreeDOrientation DataType.
Definition at line 29715 of file Opc.Ua.Constants.cs.
ThreeDVector
readonly NodeId Opc.Ua.DataTypeIds.ThreeDVector = new NodeId(Opc.Ua.DataTypes.ThreeDVector) static
The identifier for the ThreeDVector DataType.
Definition at line 29695 of file Opc.Ua.Constants.cs.
Time
readonly NodeId Opc.Ua.DataTypeIds.Time = new NodeId(Opc.Ua.DataTypes.Time) static
The identifier for the Time DataType.
Definition at line 30765 of file Opc.Ua.Constants.cs.
TimestampsToReturn
readonly NodeId Opc.Ua.DataTypeIds.TimestampsToReturn = new NodeId(Opc.Ua.DataTypes.TimestampsToReturn) static
The identifier for the TimestampsToReturn DataType.
Definition at line 30875 of file Opc.Ua.Constants.cs.
TimeString
readonly NodeId Opc.Ua.DataTypeIds.TimeString = new NodeId(Opc.Ua.DataTypes.TimeString) static
The identifier for the TimeString DataType.
Definition at line 30225 of file Opc.Ua.Constants.cs.
TimeZoneDataType
readonly NodeId Opc.Ua.DataTypeIds.TimeZoneDataType = new NodeId(Opc.Ua.DataTypes.TimeZoneDataType) static
The identifier for the TimeZoneDataType DataType.
Definition at line 30250 of file Opc.Ua.Constants.cs.
TransferResult
readonly NodeId Opc.Ua.DataTypeIds.TransferResult = new NodeId(Opc.Ua.DataTypes.TransferResult) static
The identifier for the TransferResult DataType.
Definition at line 31280 of file Opc.Ua.Constants.cs.
TransferSubscriptionsRequest
readonly NodeId Opc.Ua.DataTypeIds.TransferSubscriptionsRequest = new NodeId(Opc.Ua.DataTypes.TransferSubscriptionsRequest) static
The identifier for the TransferSubscriptionsRequest DataType.
Definition at line 31285 of file Opc.Ua.Constants.cs.
Referenced by Opc.Ua.SessionEndpoint.EndDeleteSubscriptions().
TransferSubscriptionsResponse
readonly NodeId Opc.Ua.DataTypeIds.TransferSubscriptionsResponse = new NodeId(Opc.Ua.DataTypes.TransferSubscriptionsResponse) static
The identifier for the TransferSubscriptionsResponse DataType.
Definition at line 31290 of file Opc.Ua.Constants.cs.
TranslateBrowsePathsToNodeIdsRequest
readonly NodeId Opc.Ua.DataTypeIds.TranslateBrowsePathsToNodeIdsRequest = new NodeId(Opc.Ua.DataTypes.TranslateBrowsePathsToNodeIdsRequest) static
The identifier for the TranslateBrowsePathsToNodeIdsRequest DataType.
Definition at line 30725 of file Opc.Ua.Constants.cs.
Referenced by Opc.Ua.SessionEndpoint.EndDeleteSubscriptions().
TranslateBrowsePathsToNodeIdsResponse
readonly NodeId Opc.Ua.DataTypeIds.TranslateBrowsePathsToNodeIdsResponse = new NodeId(Opc.Ua.DataTypes.TranslateBrowsePathsToNodeIdsResponse) static
The identifier for the TranslateBrowsePathsToNodeIdsResponse DataType.
Definition at line 30730 of file Opc.Ua.Constants.cs.
TrustListDataType
readonly NodeId Opc.Ua.DataTypeIds.TrustListDataType = new NodeId(Opc.Ua.DataTypes.TrustListDataType) static
The identifier for the TrustListDataType DataType.
Definition at line 29750 of file Opc.Ua.Constants.cs.
TrustListMasks
readonly NodeId Opc.Ua.DataTypeIds.TrustListMasks = new NodeId(Opc.Ua.DataTypes.TrustListMasks) static
The identifier for the TrustListMasks DataType.
Definition at line 29745 of file Opc.Ua.Constants.cs.
TypeNode
readonly NodeId Opc.Ua.DataTypeIds.TypeNode = new NodeId(Opc.Ua.DataTypes.TypeNode) static
The identifier for the TypeNode DataType.
Definition at line 30135 of file Opc.Ua.Constants.cs.
UABinaryFileDataType
readonly NodeId Opc.Ua.DataTypeIds.UABinaryFileDataType = new NodeId(Opc.Ua.DataTypes.UABinaryFileDataType) static
The identifier for the UABinaryFileDataType DataType.
Definition at line 29785 of file Opc.Ua.Constants.cs.
UadpDataSetMessageContentMask
readonly NodeId Opc.Ua.DataTypeIds.UadpDataSetMessageContentMask = new NodeId(Opc.Ua.DataTypes.UadpDataSetMessageContentMask) static
The identifier for the UadpDataSetMessageContentMask DataType.
Definition at line 29975 of file Opc.Ua.Constants.cs.
UadpDataSetReaderMessageDataType
readonly NodeId Opc.Ua.DataTypeIds.UadpDataSetReaderMessageDataType = new NodeId(Opc.Ua.DataTypes.UadpDataSetReaderMessageDataType) static
The identifier for the UadpDataSetReaderMessageDataType DataType.
Definition at line 29985 of file Opc.Ua.Constants.cs.
UadpDataSetWriterMessageDataType
readonly NodeId Opc.Ua.DataTypeIds.UadpDataSetWriterMessageDataType = new NodeId(Opc.Ua.DataTypes.UadpDataSetWriterMessageDataType) static
The identifier for the UadpDataSetWriterMessageDataType DataType.
Definition at line 29980 of file Opc.Ua.Constants.cs.
UadpNetworkMessageContentMask
readonly NodeId Opc.Ua.DataTypeIds.UadpNetworkMessageContentMask = new NodeId(Opc.Ua.DataTypes.UadpNetworkMessageContentMask) static
The identifier for the UadpNetworkMessageContentMask DataType.
Definition at line 29965 of file Opc.Ua.Constants.cs.
UadpWriterGroupMessageDataType
readonly NodeId Opc.Ua.DataTypeIds.UadpWriterGroupMessageDataType = new NodeId(Opc.Ua.DataTypes.UadpWriterGroupMessageDataType) static
The identifier for the UadpWriterGroupMessageDataType DataType.
Definition at line 29970 of file Opc.Ua.Constants.cs.
UInt16
readonly NodeId Opc.Ua.DataTypeIds.UInt16 = new NodeId(Opc.Ua.DataTypes.UInt16) static
The identifier for the UInt16 DataType.
Definition at line 29530 of file Opc.Ua.Constants.cs.
UInt32
readonly NodeId Opc.Ua.DataTypeIds.UInt32 = new NodeId(Opc.Ua.DataTypes.UInt32) static
The identifier for the UInt32 DataType.
Definition at line 29540 of file Opc.Ua.Constants.cs.
UInt64
readonly NodeId Opc.Ua.DataTypeIds.UInt64 = new NodeId(Opc.Ua.DataTypes.UInt64) static
The identifier for the UInt64 DataType.
Definition at line 29550 of file Opc.Ua.Constants.cs.
UInteger
readonly NodeId Opc.Ua.DataTypeIds.UInteger = new NodeId(Opc.Ua.DataTypes.UInteger) static
The identifier for the UInteger DataType.
Definition at line 29500 of file Opc.Ua.Constants.cs.
Union
readonly NodeId Opc.Ua.DataTypeIds.Union = new NodeId(Opc.Ua.DataTypes.Union) static
The identifier for the Union DataType.
Definition at line 30205 of file Opc.Ua.Constants.cs.
UnregisterNodesRequest
readonly NodeId Opc.Ua.DataTypeIds.UnregisterNodesRequest = new NodeId(Opc.Ua.DataTypes.UnregisterNodesRequest) static
The identifier for the UnregisterNodesRequest DataType.
Definition at line 30745 of file Opc.Ua.Constants.cs.
Referenced by Opc.Ua.SessionEndpoint.EndDeleteSubscriptions().
UnregisterNodesResponse
readonly NodeId Opc.Ua.DataTypeIds.UnregisterNodesResponse = new NodeId(Opc.Ua.DataTypes.UnregisterNodesResponse) static
The identifier for the UnregisterNodesResponse DataType.
Definition at line 30750 of file Opc.Ua.Constants.cs.
UpdateDataDetails
readonly NodeId Opc.Ua.DataTypeIds.UpdateDataDetails = new NodeId(Opc.Ua.DataTypes.UpdateDataDetails) static
The identifier for the UpdateDataDetails DataType.
Definition at line 30990 of file Opc.Ua.Constants.cs.
UpdateEventDetails
readonly NodeId Opc.Ua.DataTypeIds.UpdateEventDetails = new NodeId(Opc.Ua.DataTypes.UpdateEventDetails) static
The identifier for the UpdateEventDetails DataType.
Definition at line 31000 of file Opc.Ua.Constants.cs.
UpdateStructureDataDetails
readonly NodeId Opc.Ua.DataTypeIds.UpdateStructureDataDetails = new NodeId(Opc.Ua.DataTypes.UpdateStructureDataDetails) static
The identifier for the UpdateStructureDataDetails DataType.
Definition at line 30995 of file Opc.Ua.Constants.cs.
UserIdentityToken
readonly NodeId Opc.Ua.DataTypeIds.UserIdentityToken = new NodeId(Opc.Ua.DataTypes.UserIdentityToken) static
The identifier for the UserIdentityToken DataType.
Definition at line 30455 of file Opc.Ua.Constants.cs.
UserNameIdentityToken
readonly NodeId Opc.Ua.DataTypeIds.UserNameIdentityToken = new NodeId(Opc.Ua.DataTypes.UserNameIdentityToken) static
The identifier for the UserNameIdentityToken DataType.
Definition at line 30465 of file Opc.Ua.Constants.cs.
UserTokenPolicy
readonly NodeId Opc.Ua.DataTypeIds.UserTokenPolicy = new NodeId(Opc.Ua.DataTypes.UserTokenPolicy) static
The identifier for the UserTokenPolicy DataType.
Definition at line 30345 of file Opc.Ua.Constants.cs.
UserTokenType
readonly NodeId Opc.Ua.DataTypeIds.UserTokenType = new NodeId(Opc.Ua.DataTypes.UserTokenType) static
The identifier for the UserTokenType DataType.
Definition at line 30340 of file Opc.Ua.Constants.cs.
UtcTime
readonly NodeId Opc.Ua.DataTypeIds.UtcTime = new NodeId(Opc.Ua.DataTypes.UtcTime) static
The identifier for the UtcTime DataType.
Definition at line 30240 of file Opc.Ua.Constants.cs.
VariableAttributes
readonly NodeId Opc.Ua.DataTypeIds.VariableAttributes = new NodeId(Opc.Ua.DataTypes.VariableAttributes) static
The identifier for the VariableAttributes DataType.
Definition at line 30530 of file Opc.Ua.Constants.cs.
VariableNode
readonly NodeId Opc.Ua.DataTypeIds.VariableNode = new NodeId(Opc.Ua.DataTypes.VariableNode) static
The identifier for the VariableNode DataType.
Definition at line 30150 of file Opc.Ua.Constants.cs.
VariableTypeAttributes
readonly NodeId Opc.Ua.DataTypeIds.VariableTypeAttributes = new NodeId(Opc.Ua.DataTypes.VariableTypeAttributes) static
The identifier for the VariableTypeAttributes DataType.
Definition at line 30545 of file Opc.Ua.Constants.cs.
VariableTypeNode
readonly NodeId Opc.Ua.DataTypeIds.VariableTypeNode = new NodeId(Opc.Ua.DataTypes.VariableTypeNode) static
The identifier for the VariableTypeNode DataType.
Definition at line 30155 of file Opc.Ua.Constants.cs.
Vector
readonly NodeId Opc.Ua.DataTypeIds.Vector = new NodeId(Opc.Ua.DataTypes.Vector) static
The identifier for the Vector DataType.
Definition at line 29690 of file Opc.Ua.Constants.cs.
VersionTime
readonly NodeId Opc.Ua.DataTypeIds.VersionTime = new NodeId(Opc.Ua.DataTypes.VersionTime) static
The identifier for the VersionTime DataType.
Definition at line 30285 of file Opc.Ua.Constants.cs.
ViewAttributes
readonly NodeId Opc.Ua.DataTypeIds.ViewAttributes = new NodeId(Opc.Ua.DataTypes.ViewAttributes) static
The identifier for the ViewAttributes DataType.
Definition at line 30560 of file Opc.Ua.Constants.cs.
ViewDescription
readonly NodeId Opc.Ua.DataTypeIds.ViewDescription = new NodeId(Opc.Ua.DataTypes.ViewDescription) static
The identifier for the ViewDescription DataType.
Definition at line 30650 of file Opc.Ua.Constants.cs.
ViewNode
readonly NodeId Opc.Ua.DataTypeIds.ViewNode = new NodeId(Opc.Ua.DataTypes.ViewNode) static
The identifier for the ViewNode DataType.
Definition at line 30170 of file Opc.Ua.Constants.cs.
WriteRequest
readonly NodeId Opc.Ua.DataTypeIds.WriteRequest = new NodeId(Opc.Ua.DataTypes.WriteRequest) static
The identifier for the WriteRequest DataType.
Definition at line 30965 of file Opc.Ua.Constants.cs.
Referenced by Opc.Ua.SessionEndpoint.EndDeleteSubscriptions().
WriteResponse
readonly NodeId Opc.Ua.DataTypeIds.WriteResponse = new NodeId(Opc.Ua.DataTypes.WriteResponse) static
The identifier for the WriteResponse DataType.
Definition at line 30970 of file Opc.Ua.Constants.cs.
WriterGroupDataType
readonly NodeId Opc.Ua.DataTypeIds.WriterGroupDataType = new NodeId(Opc.Ua.DataTypes.WriterGroupDataType) static
The identifier for the WriterGroupDataType DataType.
Definition at line 29865 of file Opc.Ua.Constants.cs.
WriterGroupMessageDataType
readonly NodeId Opc.Ua.DataTypeIds.WriterGroupMessageDataType = new NodeId(Opc.Ua.DataTypes.WriterGroupMessageDataType) static
The identifier for the WriterGroupMessageDataType DataType.
Definition at line 29875 of file Opc.Ua.Constants.cs.
WriterGroupTransportDataType
readonly NodeId Opc.Ua.DataTypeIds.WriterGroupTransportDataType = new NodeId(Opc.Ua.DataTypes.WriterGroupTransportDataType) static
The identifier for the WriterGroupTransportDataType DataType.
Definition at line 29870 of file Opc.Ua.Constants.cs.
WriteValue
readonly NodeId Opc.Ua.DataTypeIds.WriteValue = new NodeId(Opc.Ua.DataTypes.WriteValue) static
The identifier for the WriteValue DataType.
Definition at line 30960 of file Opc.Ua.Constants.cs.
X509IdentityToken
readonly NodeId Opc.Ua.DataTypeIds.X509IdentityToken = new NodeId(Opc.Ua.DataTypes.X509IdentityToken) static
The identifier for the X509IdentityToken DataType.
Definition at line 30470 of file Opc.Ua.Constants.cs.
XmlElement
readonly NodeId Opc.Ua.DataTypeIds.XmlElement = new NodeId(Opc.Ua.DataTypes.XmlElement) static
The identifier for the XmlElement DataType.
Definition at line 29585 of file Opc.Ua.Constants.cs.
XVType
readonly NodeId Opc.Ua.DataTypeIds.XVType = new NodeId(Opc.Ua.DataTypes.XVType) static
The identifier for the XVType DataType.
Definition at line 31420 of file Opc.Ua.Constants.cs.
The documentation for this class was generated from the following file:
Opc.Ua.Constants.cs