Project Template: Open62541_Server.h File Reference
includes/Open62541_Server/Open62541_Server.h File Reference
Typedefs
typedef enum ReturnStatus OPEN62541_ReturnStatus
Enumerations
enum ReturnStatus { OPEN62541_SUCCESS, OPEN62541_FAILURE, OPEN62541_SUCCESS, OPEN62541_FAILURE }
Functions
bool startServer ()
bool stopServer ()
OPEN62541_ReturnStatus addDeviceNode (NodeDescription *device)
OPEN62541_ReturnStatus addDeviceNodeElement (NodeDescription *element, UA_NodeId parent_id)
OPEN62541_ReturnStatus addGroupNode (NodeDescription *group, UA_NodeId parent_id)
OPEN62541_ReturnStatus addFunctionNode (NodeDescription *function, UA_NodeId parent_id)
OPEN62541_ReturnStatus addMetricNode (NodeDescription *metric, UA_NodeId parent_id)
UA_NodeId getOpcDataType (DataType type)
void update_DataConsumer (NodeDescription *device)
Variables
UA_Server * opcua_server
static UA_UInt16 server_namespace_index = 1
Typedef Documentation
OPEN62541_ReturnStatus
typedef enum ReturnStatus OPEN62541_ReturnStatus
Enumeration Type Documentation
ReturnStatus
enum ReturnStatus
Enumerator
OPEN62541_SUCCESS
OPEN62541_FAILURE
OPEN62541_SUCCESS
OPEN62541_FAILURE
Definition at line 7 of file includes/Open62541_Server/Open62541_Server.h.
Function Documentation
addDeviceNode()
OPEN62541_ReturnStatus addDeviceNode (NodeDescription * device)
Definition at line 74 of file Open62541_Server.c.
References addDeviceNodeElement(), NodeInformation::base_node_descriptor, BaseNodeInformation::browse_name, ObjectNodeInformation::children, ObjectNodeInformation::children_count, BaseNodeInformation::description, UA_ObjectAttributes::description, BaseNodeInformation::display_name, UA_ObjectAttributes::displayName, BaseNodeInformation::locale, NodeInformation::object_node_descriptor, opcua_server, server_namespace_index, UA_LOCALIZEDTEXT(), UA_NODEID_NUMERIC(), UA_NODEID_STRING(), UA_ObjectAttributes_default, UA_QUALIFIEDNAME(), UA_Server_addObjectNode(), and BaseNodeInformation::unique_id.
Referenced by update_DataConsumer().
addDeviceNodeElement()
OPEN62541_ReturnStatus addDeviceNodeElement (NodeDescription * element, UA_NodeId parent_id)
Definition at line 106 of file Open62541_Server.c.
References addFunctionNode(), addGroupNode(), addMetricNode(), NodeInformation::base_node_descriptor, METHOD_NODE, BaseNodeInformation::node_class, OBJECT_NODE, OPEN62541_FAILURE, UNRECOGNIZED_NODE, and VARIABLE_NODE.
Referenced by addDeviceNode(), and addGroupNode().
addFunctionNode()
OPEN62541_ReturnStatus addFunctionNode (NodeDescription * function, UA_NodeId parent_id)
Definition at line 168 of file Open62541_Server.c.
References OPEN62541_FAILURE.
Referenced by addDeviceNodeElement().
addGroupNode()
OPEN62541_ReturnStatus addGroupNode (NodeDescription * group, UA_NodeId parent_id)
Definition at line 136 of file Open62541_Server.c.
References addDeviceNodeElement(), NodeInformation::base_node_descriptor, BaseNodeInformation::browse_name, ObjectNodeInformation::children, ObjectNodeInformation::children_count, BaseNodeInformation::description, UA_ObjectAttributes::description, BaseNodeInformation::display_name, UA_ObjectAttributes::displayName, BaseNodeInformation::locale, NodeInformation::object_node_descriptor, opcua_server, OPEN62541_FAILURE, server_namespace_index, UA_LOCALIZEDTEXT(), UA_NODEID_NUMERIC(), UA_NODEID_STRING(), UA_ObjectAttributes_default, UA_QUALIFIEDNAME(), UA_Server_addObjectNode(), and BaseNodeInformation::unique_id.
Referenced by addDeviceNodeElement().
addMetricNode()
OPEN62541_ReturnStatus addMetricNode (NodeDescription * metric, UA_NodeId parent_id)
Definition at line 175 of file Open62541_Server.c.
References UA_VariableAttributes::accessLevel, NodeInformation::base_node_descriptor, BaseNodeInformation::browse_name, VariableNodeInformation::data, UA_VariableAttributes::dataType, BaseNodeInformation::description, UA_VariableAttributes::description, BaseNodeInformation::display_name, UA_VariableAttributes::displayName, getOpcDataType(), BaseNodeInformation::locale, BaseNodeInformation::node_class, opcua_server, OPEN62541_FAILURE, server_namespace_index, DataValueWrapperStruct::type, UA_LOCALIZEDTEXT(), UA_NODEID_NUMERIC(), UA_NODEID_STRING(), UA_QUALIFIEDNAME(), UA_Server_addVariableNode(), UA_VariableAttributes_default, BaseNodeInformation::unique_id, VARIABLE_NODE, and NodeInformation::variable_node_descriptor.
Referenced by addDeviceNodeElement().
getOpcDataType()
UA_NodeId getOpcDataType (DataType type)
Definition at line 207 of file Open62541_Server.c.
References BOOLEAN, DOUBLE, SIGNED_INTEGER, SIGNED_LONG, SIGNED_SHORT, STRING, UA_DataType::typeId, UA_TYPES, UNKNOWN, UNSIGNED_INTEGER, UNSIGNED_LONG, and UNSIGNED_SHORT.
Referenced by addMetricNode().
startServer()
bool startServer ()
Definition at line 24 of file Open62541_Server.c.
References opcua_server, server_running_flag, serverThread(), stopHandler(), stopServer(), UA_Server_getConfig(), UA_Server_new(), and UA_ServerConfig_setDefault().
stopServer()
bool stopServer ()
Definition at line 54 of file Open62541_Server.c.
References opcua_server, server_running_flag, UA_Server_delete(), and UA_Server_run_shutdown().
Referenced by startServer().
update_DataConsumer()
void update_DataConsumer (NodeDescription * device)
Definition at line 69 of file Open62541_Server.c.
References addDeviceNode().
Variable Documentation
opcua_server
UA_Server* opcua_server
Definition at line 28 of file includes/Open62541_Server/Open62541_Server.h.
server_namespace_index
UA_UInt16 server_namespace_index = 1 static
Definition at line 29 of file includes/Open62541_Server/Open62541_Server.h.