Project Template: Opc.Ua.MonitoredItemCreateRequest Class Reference
Opc.Ua.MonitoredItemCreateRequest Class Reference
Public Member Functions
MonitoredItemCreateRequest ()
The default constructor.
virtual void Encode (IEncoder encoder)
virtual void Decode (IDecoder decoder)
virtual bool IsEqual (IEncodeable encodeable)
virtual object Clone ()
new object MemberwiseClone ()
Properties
ReadValueId ItemToMonitor [get, set]
MonitoringMode MonitoringMode [get, set]
MonitoringParameters RequestedParameters [get, set]
virtual ExpandedNodeId TypeId [get]
virtual ExpandedNodeId BinaryEncodingId [get]
virtual ExpandedNodeId XmlEncodingId [get]
Detailed Description
<exclude>
Definition at line 53311 of file Opc.Ua.DataTypes.cs.
Constructor & Destructor Documentation
MonitoredItemCreateRequest()
Opc.Ua.MonitoredItemCreateRequest.MonitoredItemCreateRequest () inline
The default constructor.
Definition at line 53317 of file Opc.Ua.DataTypes.cs.
Member Function Documentation
Clone()
virtual object Opc.Ua.MonitoredItemCreateRequest.Clone () inline virtual
Definition at line 53463 of file Opc.Ua.DataTypes.cs.
Decode()
virtual void Opc.Ua.MonitoredItemCreateRequest.Decode (IDecoder decoder) inline virtual
Definition at line 53428 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
Encode()
virtual void Opc.Ua.MonitoredItemCreateRequest.Encode (IEncoder encoder) inline virtual
Definition at line 53416 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
IsEqual()
virtual bool Opc.Ua.MonitoredItemCreateRequest.IsEqual (IEncodeable encodeable) inline virtual
Definition at line 53440 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Object.
MemberwiseClone()
new object Opc.Ua.MonitoredItemCreateRequest.MemberwiseClone () inline
Definition at line 53470 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.ReadValueId.Clone(), Opc.Ua.MonitoringParameters.Clone(), Opc.Ua.MonitoredItemCreateRequest.MemberwiseClone(), and Opc.Ua.Namespaces.OpcUaXsd.
Referenced by Opc.Ua.MonitoredItemCreateRequest.MemberwiseClone().
Property Documentation
BinaryEncodingId
virtual ExpandedNodeId Opc.Ua.MonitoredItemCreateRequest.BinaryEncodingId get
Definition at line 53405 of file Opc.Ua.DataTypes.cs.
ItemToMonitor
ReadValueId Opc.Ua.MonitoredItemCreateRequest.ItemToMonitor get set
Definition at line 53348 of file Opc.Ua.DataTypes.cs.
MonitoringMode
MonitoringMode Opc.Ua.MonitoredItemCreateRequest.MonitoringMode get set
Definition at line 53368 of file Opc.Ua.DataTypes.cs.
RequestedParameters
MonitoringParameters Opc.Ua.MonitoredItemCreateRequest.RequestedParameters get set
Definition at line 53378 of file Opc.Ua.DataTypes.cs.
TypeId
virtual ExpandedNodeId Opc.Ua.MonitoredItemCreateRequest.TypeId get
Definition at line 53399 of file Opc.Ua.DataTypes.cs.
XmlEncodingId
virtual ExpandedNodeId Opc.Ua.MonitoredItemCreateRequest.XmlEncodingId get
Definition at line 53411 of file Opc.Ua.DataTypes.cs.
The documentation for this class was generated from the following file:
Opc.Ua.DataTypes.cs