Project Template: Opc.Ua.EventFilter Class Reference
Opc.Ua.EventFilter Class Reference
Public Member Functions
EventFilter ()
The default constructor.
override void Encode (IEncoder encoder)
override void Decode (IDecoder decoder)
override bool IsEqual (IEncodeable encodeable)
override object Clone ()
new object MemberwiseClone ()
Public Member Functions inherited from Opc.Ua.MonitoringFilter
MonitoringFilter ()
The default constructor.
new object MemberwiseClone ()
Properties
SimpleAttributeOperandCollection SelectClauses [get, set]
ContentFilter WhereClause [get, set]
override ExpandedNodeId TypeId [get]
override ExpandedNodeId BinaryEncodingId [get]
override ExpandedNodeId XmlEncodingId [get]
Properties inherited from Opc.Ua.MonitoringFilter
virtual ExpandedNodeId TypeId [get]
virtual ExpandedNodeId BinaryEncodingId [get]
virtual ExpandedNodeId XmlEncodingId [get]
Detailed Description
<exclude>
Definition at line 52058 of file Opc.Ua.DataTypes.cs.
Constructor & Destructor Documentation
EventFilter()
Opc.Ua.EventFilter.EventFilter () inline
The default constructor.
Definition at line 52064 of file Opc.Ua.DataTypes.cs.
Member Function Documentation
Clone()
override object Opc.Ua.EventFilter.Clone () inline virtual
Reimplemented from Opc.Ua.MonitoringFilter.
Definition at line 52203 of file Opc.Ua.DataTypes.cs.
Referenced by Opc.Ua.ReadEventDetails.MemberwiseClone(), and Opc.Ua.UpdateEventDetails.MemberwiseClone().
Decode()
override void Opc.Ua.EventFilter.Decode (IDecoder decoder) inline virtual
Reimplemented from Opc.Ua.MonitoringFilter.
Definition at line 52167 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
Encode()
override void Opc.Ua.EventFilter.Encode (IEncoder encoder) inline virtual
Reimplemented from Opc.Ua.MonitoringFilter.
Definition at line 52154 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
IsEqual()
override bool Opc.Ua.EventFilter.IsEqual (IEncodeable encodeable) inline virtual
Reimplemented from Opc.Ua.MonitoringFilter.
Definition at line 52180 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Object.
MemberwiseClone()
new object Opc.Ua.EventFilter.MemberwiseClone () inline
Definition at line 52210 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.ContentFilter.Clone(), Opc.Ua.SimpleAttributeOperandCollection.Clone(), Opc.Ua.EventFilter.MemberwiseClone(), and Opc.Ua.Namespaces.OpcUaXsd.
Referenced by Opc.Ua.EventFilter.MemberwiseClone().
Property Documentation
BinaryEncodingId
override ExpandedNodeId Opc.Ua.EventFilter.BinaryEncodingId get
Definition at line 52143 of file Opc.Ua.DataTypes.cs.
SelectClauses
SimpleAttributeOperandCollection Opc.Ua.EventFilter.SelectClauses get set
Definition at line 52094 of file Opc.Ua.DataTypes.cs.
TypeId
override ExpandedNodeId Opc.Ua.EventFilter.TypeId get
Definition at line 52137 of file Opc.Ua.DataTypes.cs.
WhereClause
ContentFilter Opc.Ua.EventFilter.WhereClause get set
Definition at line 52116 of file Opc.Ua.DataTypes.cs.
XmlEncodingId
override ExpandedNodeId Opc.Ua.EventFilter.XmlEncodingId get
Definition at line 52149 of file Opc.Ua.DataTypes.cs.
The documentation for this class was generated from the following file:
Opc.Ua.DataTypes.cs