Project Template: Opc.Ua.UnregisterNodesResponse Class Reference
Opc.Ua.UnregisterNodesResponse Class Reference
Public Member Functions
UnregisterNodesResponse ()
The default constructor.
virtual void Encode (IEncoder encoder)
virtual void Decode (IDecoder decoder)
virtual bool IsEqual (IEncodeable encodeable)
virtual object Clone ()
new object MemberwiseClone ()
Properties
ResponseHeader ResponseHeader [get, set]
virtual ExpandedNodeId TypeId [get]
virtual ExpandedNodeId BinaryEncodingId [get]
virtual ExpandedNodeId XmlEncodingId [get]
Detailed Description
<exclude>
Definition at line 2077 of file Opc.Ua.Messages.cs.
Constructor & Destructor Documentation
UnregisterNodesResponse()
Opc.Ua.UnregisterNodesResponse.UnregisterNodesResponse () inline
The default constructor.
Definition at line 40532 of file Opc.Ua.DataTypes.cs.
Member Function Documentation
Clone()
virtual object Opc.Ua.UnregisterNodesResponse.Clone () inline virtual
Definition at line 40640 of file Opc.Ua.DataTypes.cs.
Decode()
virtual void Opc.Ua.UnregisterNodesResponse.Decode (IDecoder decoder) inline virtual
Definition at line 40609 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
Encode()
virtual void Opc.Ua.UnregisterNodesResponse.Encode (IEncoder encoder) inline virtual
Definition at line 40599 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
IsEqual()
virtual bool Opc.Ua.UnregisterNodesResponse.IsEqual (IEncodeable encodeable) inline virtual
Definition at line 40619 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Object.
MemberwiseClone()
new object Opc.Ua.UnregisterNodesResponse.MemberwiseClone () inline
Definition at line 40647 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.ResponseHeader.Clone(), Opc.Ua.UnregisterNodesResponse.MemberwiseClone(), and Opc.Ua.Namespaces.OpcUaXsd.
Referenced by Opc.Ua.UnregisterNodesResponse.MemberwiseClone().
Property Documentation
BinaryEncodingId
virtual ExpandedNodeId Opc.Ua.UnregisterNodesResponse.BinaryEncodingId get
Definition at line 40588 of file Opc.Ua.DataTypes.cs.
ResponseHeader
ResponseHeader Opc.Ua.UnregisterNodesResponse.ResponseHeader get set
Definition at line 40561 of file Opc.Ua.DataTypes.cs.
Referenced by Opc.Ua.UnregisterNodesMessage.CreateResponse(), Opc.Ua.SessionClient.EndRegisterNodes(), Opc.Ua.SessionEndpoint.EndRegisterNodes(), Opc.Ua.SessionClient.EndUnregisterNodes(), and Opc.Ua.UnregisterNodesResponseMessage.UnregisterNodesResponseMessage().
TypeId
virtual ExpandedNodeId Opc.Ua.UnregisterNodesResponse.TypeId get
Definition at line 40582 of file Opc.Ua.DataTypes.cs.
XmlEncodingId
virtual ExpandedNodeId Opc.Ua.UnregisterNodesResponse.XmlEncodingId get
Definition at line 40594 of file Opc.Ua.DataTypes.cs.
The documentation for this class was generated from the following files:
Opc.Ua.Messages.cs
Opc.Ua.DataTypes.cs