Project Template: Opc.Ua.MonitoredItemModifyRequest Class Reference
Opc.Ua.MonitoredItemModifyRequest Class Reference
Public Member Functions
MonitoredItemModifyRequest ()
The default constructor.
virtual void Encode (IEncoder encoder)
virtual void Decode (IDecoder decoder)
virtual bool IsEqual (IEncodeable encodeable)
virtual object Clone ()
new object MemberwiseClone ()
Properties
uint MonitoredItemId [get, set]
MonitoringParameters RequestedParameters [get, set]
virtual ExpandedNodeId TypeId [get]
virtual ExpandedNodeId BinaryEncodingId [get]
virtual ExpandedNodeId XmlEncodingId [get]
Detailed Description
<exclude>
Definition at line 54261 of file Opc.Ua.DataTypes.cs.
Constructor & Destructor Documentation
MonitoredItemModifyRequest()
Opc.Ua.MonitoredItemModifyRequest.MonitoredItemModifyRequest () inline
The default constructor.
Definition at line 54267 of file Opc.Ua.DataTypes.cs.
Member Function Documentation
Clone()
virtual object Opc.Ua.MonitoredItemModifyRequest.Clone () inline virtual
Definition at line 54387 of file Opc.Ua.DataTypes.cs.
Decode()
virtual void Opc.Ua.MonitoredItemModifyRequest.Decode (IDecoder decoder) inline virtual
Definition at line 54354 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
Encode()
virtual void Opc.Ua.MonitoredItemModifyRequest.Encode (IEncoder encoder) inline virtual
Definition at line 54343 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
IsEqual()
virtual bool Opc.Ua.MonitoredItemModifyRequest.IsEqual (IEncodeable encodeable) inline virtual
Definition at line 54365 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Object.
MemberwiseClone()
new object Opc.Ua.MonitoredItemModifyRequest.MemberwiseClone () inline
Definition at line 54394 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.MonitoringParameters.Clone(), Opc.Ua.MonitoredItemModifyRequest.MemberwiseClone(), and Opc.Ua.Namespaces.OpcUaXsd.
Referenced by Opc.Ua.MonitoredItemModifyRequest.MemberwiseClone().
Property Documentation
BinaryEncodingId
virtual ExpandedNodeId Opc.Ua.MonitoredItemModifyRequest.BinaryEncodingId get
Definition at line 54332 of file Opc.Ua.DataTypes.cs.
MonitoredItemId
uint Opc.Ua.MonitoredItemModifyRequest.MonitoredItemId get set
Definition at line 54295 of file Opc.Ua.DataTypes.cs.
RequestedParameters
MonitoringParameters Opc.Ua.MonitoredItemModifyRequest.RequestedParameters get set
Definition at line 54305 of file Opc.Ua.DataTypes.cs.
TypeId
virtual ExpandedNodeId Opc.Ua.MonitoredItemModifyRequest.TypeId get
Definition at line 54326 of file Opc.Ua.DataTypes.cs.
XmlEncodingId
virtual ExpandedNodeId Opc.Ua.MonitoredItemModifyRequest.XmlEncodingId get
Definition at line 54338 of file Opc.Ua.DataTypes.cs.
The documentation for this class was generated from the following file:
Opc.Ua.DataTypes.cs