Project Template: nlohmann::detail::binary_reader< BasicJsonType, SAX > Class Template Reference
nlohmann::detail::binary_reader< BasicJsonType, SAX > Class Template Reference
deserialization of CBOR, MessagePack, and UBJSON values
#include <json.hpp>
Public Member Functions
binary_reader (input_adapter_t adapter)
create a binary reader
binary_reader (const binary_reader &)=delete
binary_reader (binary_reader &&)=default
binary_reader & operator= (const binary_reader &)=delete
binary_reader & operator= (binary_reader &&)=default
~binary_reader ()=default
JSON_HEDLEY_NON_NULL (3) bool sax_parse(const input_format_t format
Data Fields
json_sax_t * sax_
json_sax_t const bool strict
json_sax_t const bool bool InputIsLittleEndian
int current = std::char_traits<char>::eof()
the current character
std::size_t chars_read = 0
the number of characters read
const bool is_little_endian = little_endianess()
whether we can assume little endianess
json_sax_t * sax = nullptr
the SAX parser
Detailed Description
template<typename BasicJsonType, typename SAX = json_sax_dom_parser<BasicJsonType>>
class nlohmann::detail::binary_reader< BasicJsonType, SAX >
deserialization of CBOR, MessagePack, and UBJSON values
Definition at line 5063 of file json.hpp.
Constructor & Destructor Documentation
binary_reader() [1/3]
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> nlohmann::detail::binary_reader< BasicJsonType, SAX >::binary_reader (input_adapter_t adapter) inline explicit
create a binary reader
Parameters
[in] adapter input adapter to read from
Definition at line 5077 of file json.hpp.
References nlohmann::detail::assert(), nlohmann::detail::JSON_HEDLEY_NON_NULL(), and nlohmann::detail::void().
binary_reader() [2/3]
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> nlohmann::detail::binary_reader< BasicJsonType, SAX >::binary_reader (const binary_reader< BasicJsonType, SAX > &) delete
binary_reader() [3/3]
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> nlohmann::detail::binary_reader< BasicJsonType, SAX >::binary_reader (binary_reader< BasicJsonType, SAX > &&) default
~binary_reader()
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> nlohmann::detail::binary_reader< BasicJsonType, SAX >::~binary_reader () default
Member Function Documentation
JSON_HEDLEY_NON_NULL()
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> nlohmann::detail::binary_reader< BasicJsonType, SAX >::JSON_HEDLEY_NON_NULL (3) const
Parameters
[in] format the binary format to parse
[in] sax_ a SAX event processor
[in] strict whether to expect the input to be consumed completed
Returns
operator=() [1/2]
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> binary_reader& nlohmann::detail::binary_reader< BasicJsonType, SAX >::operator= (const binary_reader< BasicJsonType, SAX > &) delete
operator=() [2/2]
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> binary_reader& nlohmann::detail::binary_reader< BasicJsonType, SAX >::operator= (binary_reader< BasicJsonType, SAX > &&) default
Field Documentation
chars_read
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> std::size_t nlohmann::detail::binary_reader< BasicJsonType, SAX >::chars_read = 0
the number of characters read
Definition at line 7002 of file json.hpp.
current
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> int nlohmann::detail::binary_reader< BasicJsonType, SAX >::current = std::char_traits<char>::eof()
the current character
Definition at line 6999 of file json.hpp.
InputIsLittleEndian
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> json_sax_t const bool bool nlohmann::detail::binary_reader< BasicJsonType, SAX >::InputIsLittleEndian
Definition at line 6870 of file json.hpp.
is_little_endian
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> const bool nlohmann::detail::binary_reader< BasicJsonType, SAX >::is_little_endian = little_endianess()
whether we can assume little endianess
Definition at line 7005 of file json.hpp.
sax
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> json_sax_t* nlohmann::detail::binary_reader< BasicJsonType, SAX >::sax = nullptr
the SAX parser
Definition at line 7008 of file json.hpp.
sax_
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> json_sax_t* nlohmann::detail::binary_reader< BasicJsonType, SAX >::sax_
Definition at line 5099 of file json.hpp.
strict
template<typename BasicJsonType , typename SAX = json_sax_dom_parser<BasicJsonType>> json_sax_t const bool nlohmann::detail::binary_reader< BasicJsonType, SAX >::strict
Definition at line 5100 of file json.hpp.
The documentation for this class was generated from the following file:
json.hpp