Project Template: Opc.Ua.AggregateFilter Class Reference
Opc.Ua.AggregateFilter Class Reference
Public Member Functions
AggregateFilter ()
The default constructor.
override void Encode (IEncoder encoder)
override void Decode (IDecoder decoder)
override bool IsEqual (IEncodeable encodeable)
override object Clone ()
new object MemberwiseClone ()
Public Member Functions inherited from Opc.Ua.MonitoringFilter
MonitoringFilter ()
The default constructor.
new object MemberwiseClone ()
Properties
DateTime StartTime [get, set]
NodeId AggregateType [get, set]
double ProcessingInterval [get, set]
AggregateConfiguration AggregateConfiguration [get, set]
override ExpandedNodeId TypeId [get]
override ExpandedNodeId BinaryEncodingId [get]
override ExpandedNodeId XmlEncodingId [get]
Properties inherited from Opc.Ua.MonitoringFilter
virtual ExpandedNodeId TypeId [get]
virtual ExpandedNodeId BinaryEncodingId [get]
virtual ExpandedNodeId XmlEncodingId [get]
Detailed Description
<exclude>
Definition at line 52425 of file Opc.Ua.DataTypes.cs.
Constructor & Destructor Documentation
AggregateFilter()
Opc.Ua.AggregateFilter.AggregateFilter () inline
The default constructor.
Definition at line 52431 of file Opc.Ua.DataTypes.cs.
Member Function Documentation
Clone()
override object Opc.Ua.AggregateFilter.Clone () inline virtual
Reimplemented from Opc.Ua.MonitoringFilter.
Definition at line 52580 of file Opc.Ua.DataTypes.cs.
Decode()
override void Opc.Ua.AggregateFilter.Decode (IDecoder decoder) inline virtual
Reimplemented from Opc.Ua.MonitoringFilter.
Definition at line 52540 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
Encode()
override void Opc.Ua.AggregateFilter.Encode (IEncoder encoder) inline virtual
Reimplemented from Opc.Ua.MonitoringFilter.
Definition at line 52525 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
IsEqual()
override bool Opc.Ua.AggregateFilter.IsEqual (IEncodeable encodeable) inline virtual
Reimplemented from Opc.Ua.MonitoringFilter.
Definition at line 52555 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Object.
MemberwiseClone()
new object Opc.Ua.AggregateFilter.MemberwiseClone () inline
Definition at line 52587 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.AggregateConfiguration.Clone(), Opc.Ua.AggregateFilter.MemberwiseClone(), Opc.Ua.NodeId, and Opc.Ua.Namespaces.OpcUaXsd.
Referenced by Opc.Ua.AggregateFilter.MemberwiseClone().
Property Documentation
AggregateConfiguration
AggregateConfiguration Opc.Ua.AggregateFilter.AggregateConfiguration get set
Definition at line 52487 of file Opc.Ua.DataTypes.cs.
AggregateType
NodeId Opc.Ua.AggregateFilter.AggregateType get set
Definition at line 52469 of file Opc.Ua.DataTypes.cs.
BinaryEncodingId
override ExpandedNodeId Opc.Ua.AggregateFilter.BinaryEncodingId get
Definition at line 52514 of file Opc.Ua.DataTypes.cs.
ProcessingInterval
double Opc.Ua.AggregateFilter.ProcessingInterval get set
Definition at line 52477 of file Opc.Ua.DataTypes.cs.
StartTime
DateTime Opc.Ua.AggregateFilter.StartTime get set
Definition at line 52461 of file Opc.Ua.DataTypes.cs.
TypeId
override ExpandedNodeId Opc.Ua.AggregateFilter.TypeId get
Definition at line 52508 of file Opc.Ua.DataTypes.cs.
XmlEncodingId
override ExpandedNodeId Opc.Ua.AggregateFilter.XmlEncodingId get
Definition at line 52520 of file Opc.Ua.DataTypes.cs.
The documentation for this class was generated from the following file:
Opc.Ua.DataTypes.cs