Project Template: Opc.Ua.AddNodesRequest Class Reference
Opc.Ua.AddNodesRequest Class Reference
Public Member Functions
AddNodesRequest ()
The default constructor.
virtual void Encode (IEncoder encoder)
virtual void Decode (IDecoder decoder)
virtual bool IsEqual (IEncodeable encodeable)
virtual object Clone ()
new object MemberwiseClone ()
Properties
RequestHeader RequestHeader [get, set]
AddNodesItemCollection NodesToAdd [get, set]
virtual ExpandedNodeId TypeId [get]
virtual ExpandedNodeId BinaryEncodingId [get]
virtual ExpandedNodeId XmlEncodingId [get]
Detailed Description
<exclude>
Definition at line 1217 of file Opc.Ua.Messages.cs.
Constructor & Destructor Documentation
AddNodesRequest()
Opc.Ua.AddNodesRequest.AddNodesRequest () inline
The default constructor.
Definition at line 34195 of file Opc.Ua.DataTypes.cs.
Member Function Documentation
Clone()
virtual object Opc.Ua.AddNodesRequest.Clone () inline virtual
Definition at line 34329 of file Opc.Ua.DataTypes.cs.
Decode()
virtual void Opc.Ua.AddNodesRequest.Decode (IDecoder decoder) inline virtual
Definition at line 34296 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
Encode()
virtual void Opc.Ua.AddNodesRequest.Encode (IEncoder encoder) inline virtual
Definition at line 34285 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
IsEqual()
virtual bool Opc.Ua.AddNodesRequest.IsEqual (IEncodeable encodeable) inline virtual
Definition at line 34307 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Object.
MemberwiseClone()
new object Opc.Ua.AddNodesRequest.MemberwiseClone () inline
Definition at line 34336 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.RequestHeader.Clone(), Opc.Ua.AddNodesItemCollection.Clone(), Opc.Ua.AddNodesRequest.MemberwiseClone(), and Opc.Ua.Namespaces.OpcUaXsd.
Referenced by Opc.Ua.AddNodesRequest.MemberwiseClone().
Property Documentation
BinaryEncodingId
virtual ExpandedNodeId Opc.Ua.AddNodesRequest.BinaryEncodingId get
Definition at line 34274 of file Opc.Ua.DataTypes.cs.
NodesToAdd
AddNodesItemCollection Opc.Ua.AddNodesRequest.NodesToAdd get set
Definition at line 34247 of file Opc.Ua.DataTypes.cs.
Referenced by Opc.Ua.SessionClient.BeginAddNodes(), Opc.Ua.SessionClient.EndCancel(), and Opc.Ua.SessionEndpoint.EndCancel().
RequestHeader
RequestHeader Opc.Ua.AddNodesRequest.RequestHeader get set
Definition at line 34225 of file Opc.Ua.DataTypes.cs.
Referenced by Opc.Ua.SessionClient.BeginAddNodes(), Opc.Ua.SessionClient.EndCancel(), and Opc.Ua.SessionEndpoint.EndCancel().
TypeId
virtual ExpandedNodeId Opc.Ua.AddNodesRequest.TypeId get
Definition at line 34268 of file Opc.Ua.DataTypes.cs.
XmlEncodingId
virtual ExpandedNodeId Opc.Ua.AddNodesRequest.XmlEncodingId get
Definition at line 34280 of file Opc.Ua.DataTypes.cs.
The documentation for this class was generated from the following files:
Opc.Ua.Messages.cs
Opc.Ua.DataTypes.cs