Project Template: Opc.Ua.DataSetMetaDataType Class Reference
Opc.Ua.DataSetMetaDataType Class Reference
Public Member Functions
DataSetMetaDataType ()
The default constructor.
override void Encode (IEncoder encoder)
override void Decode (IDecoder decoder)
override bool IsEqual (IEncodeable encodeable)
override object Clone ()
new object MemberwiseClone ()
Public Member Functions inherited from Opc.Ua.DataTypeSchemaHeader
DataTypeSchemaHeader ()
The default constructor.
new object MemberwiseClone ()
Properties
string Name [get, set]
LocalizedText Description [get, set]
FieldMetaDataCollection Fields [get, set]
Uuid DataSetClassId [get, set]
ConfigurationVersionDataType ConfigurationVersion [get, set]
override ExpandedNodeId TypeId [get]
override ExpandedNodeId BinaryEncodingId [get]
override ExpandedNodeId XmlEncodingId [get]
Properties inherited from Opc.Ua.DataTypeSchemaHeader
StringCollection Namespaces [get, set]
StructureDescriptionCollection StructureDataTypes [get, set]
EnumDescriptionCollection EnumDataTypes [get, set]
SimpleTypeDescriptionCollection SimpleDataTypes [get, set]
virtual ExpandedNodeId TypeId [get]
virtual ExpandedNodeId BinaryEncodingId [get]
virtual ExpandedNodeId XmlEncodingId [get]
Detailed Description
<exclude>
Definition at line 5431 of file Opc.Ua.DataTypes.cs.
Constructor & Destructor Documentation
DataSetMetaDataType()
Opc.Ua.DataSetMetaDataType.DataSetMetaDataType () inline
The default constructor.
Definition at line 5437 of file Opc.Ua.DataTypes.cs.
Member Function Documentation
Clone()
override object Opc.Ua.DataSetMetaDataType.Clone () inline virtual
Reimplemented from Opc.Ua.DataTypeSchemaHeader.
Definition at line 5612 of file Opc.Ua.DataTypes.cs.
Referenced by Opc.Ua.PublishedDataSetDataType.MemberwiseClone(), and Opc.Ua.DataSetReaderDataType.MemberwiseClone().
Decode()
override void Opc.Ua.DataSetMetaDataType.Decode (IDecoder decoder) inline virtual
Reimplemented from Opc.Ua.DataTypeSchemaHeader.
Definition at line 5570 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.DataSetClassId, Opc.Ua.Description, and Opc.Ua.Namespaces.OpcUaXsd.
Encode()
override void Opc.Ua.DataSetMetaDataType.Encode (IEncoder encoder) inline virtual
Reimplemented from Opc.Ua.DataTypeSchemaHeader.
Definition at line 5554 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.DataSetClassId, Opc.Ua.Description, and Opc.Ua.Namespaces.OpcUaXsd.
IsEqual()
override bool Opc.Ua.DataSetMetaDataType.IsEqual (IEncodeable encodeable) inline virtual
Reimplemented from Opc.Ua.DataTypeSchemaHeader.
Definition at line 5586 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Object.
MemberwiseClone()
new object Opc.Ua.DataSetMetaDataType.MemberwiseClone () inline
Definition at line 5619 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.FieldMetaDataCollection.Clone(), Opc.Ua.ConfigurationVersionDataType.Clone(), Opc.Ua.DataSetMetaDataType.MemberwiseClone(), and Opc.Ua.Namespaces.OpcUaXsd.
Referenced by Opc.Ua.DataSetMetaDataType.MemberwiseClone().
Property Documentation
BinaryEncodingId
override ExpandedNodeId Opc.Ua.DataSetMetaDataType.BinaryEncodingId get
Definition at line 5543 of file Opc.Ua.DataTypes.cs.
ConfigurationVersion
ConfigurationVersionDataType Opc.Ua.DataSetMetaDataType.ConfigurationVersion get set
Definition at line 5516 of file Opc.Ua.DataTypes.cs.
DataSetClassId
Uuid Opc.Ua.DataSetMetaDataType.DataSetClassId get set
Definition at line 5506 of file Opc.Ua.DataTypes.cs.
Description
LocalizedText Opc.Ua.DataSetMetaDataType.Description get set
Definition at line 5476 of file Opc.Ua.DataTypes.cs.
Fields
FieldMetaDataCollection Opc.Ua.DataSetMetaDataType.Fields get set
Definition at line 5486 of file Opc.Ua.DataTypes.cs.
Name
string Opc.Ua.DataSetMetaDataType.Name get set
Definition at line 5468 of file Opc.Ua.DataTypes.cs.
TypeId
override ExpandedNodeId Opc.Ua.DataSetMetaDataType.TypeId get
Definition at line 5537 of file Opc.Ua.DataTypes.cs.
XmlEncodingId
override ExpandedNodeId Opc.Ua.DataSetMetaDataType.XmlEncodingId get
Definition at line 5549 of file Opc.Ua.DataTypes.cs.
The documentation for this class was generated from the following file:
Opc.Ua.DataTypes.cs