Project Template: namespace0_generated.c File Reference
namespace0_generated.c File Reference
Functions
static UA_StatusCode function_namespace0_generated_0_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_0_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_1_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_1_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_2_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_2_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_3_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_3_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_4_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_4_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_5_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_5_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_6_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_6_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_7_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_7_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_8_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_8_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_9_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_9_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_10_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_10_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_11_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_11_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_12_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_12_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_13_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_13_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_14_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_14_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_15_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_15_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_16_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_16_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_17_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_17_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_18_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_18_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_19_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_19_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_20_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_20_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_21_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_21_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_22_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_22_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_23_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_23_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_24_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_24_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_25_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_25_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_26_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_26_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_27_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_27_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_28_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_28_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_29_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_29_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_30_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_30_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_31_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_31_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_32_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_32_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_33_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_33_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_34_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_34_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_35_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_35_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_36_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_36_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_37_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_37_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_38_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_38_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_39_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_39_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_40_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_40_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_41_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_41_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_42_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_42_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_43_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_43_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_44_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_44_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_45_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_45_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_46_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_46_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_47_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_47_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_48_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_48_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_49_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_49_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_50_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_50_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_51_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_51_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_52_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_52_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_53_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_53_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_54_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_54_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_55_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_55_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_56_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_56_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_57_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_57_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_58_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_58_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_59_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_59_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_60_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_60_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_61_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_61_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_62_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_62_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_63_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_63_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_64_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_64_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_65_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_65_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_66_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_66_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_67_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_67_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_68_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_68_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_69_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_69_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_70_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_70_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_71_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_71_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_72_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_72_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_73_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_73_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_74_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_74_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_75_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_75_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_76_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_76_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_77_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_77_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_78_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_78_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_79_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_79_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_80_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_80_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_81_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_81_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_82_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_82_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_83_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_83_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_84_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_84_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_85_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_85_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_86_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_86_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_87_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_87_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_88_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_88_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_89_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_89_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_90_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_90_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_91_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_91_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_92_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_92_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_93_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_93_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_94_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_94_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_95_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_95_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_96_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_96_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_97_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_97_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_98_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_98_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_99_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_99_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_100_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_100_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_101_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_101_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_102_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_102_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_103_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_103_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_104_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_104_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_105_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_105_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_106_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_106_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_107_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_107_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_108_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_108_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_109_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_109_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_110_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_110_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_111_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_111_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_112_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_112_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_113_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_113_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_114_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_114_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_115_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_115_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_116_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_116_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_117_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_117_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_118_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_118_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_119_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_119_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_120_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_120_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_121_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_121_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_122_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_122_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_123_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_123_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_124_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_124_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_125_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_125_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_126_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_126_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_127_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_127_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_128_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_128_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_129_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_129_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_130_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_130_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_131_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_131_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_132_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_132_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_133_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_133_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_134_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_134_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_135_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_135_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_136_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_136_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_137_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_137_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_138_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_138_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_139_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_139_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_140_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_140_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_141_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_141_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_142_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_142_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_143_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_143_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_144_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_144_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_145_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_145_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_146_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_146_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_147_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_147_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_148_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_148_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_149_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_149_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_150_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_150_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_151_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_151_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_152_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_152_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_153_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_153_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_154_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_154_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_155_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_155_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_156_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_156_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_157_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_157_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_158_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_158_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_159_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_159_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_160_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_160_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_161_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_161_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_162_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_162_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_163_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_163_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_164_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_164_finish (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_165_begin (UA_Server *server, UA_UInt16 *ns)
static UA_StatusCode function_namespace0_generated_165_finish (UA_Server *server, UA_UInt16 *ns)
UA_StatusCode namespace0_generated (UA_Server *server)
Function Documentation
function_namespace0_generated_0_begin()
static UA_StatusCode function_namespace0_generated_0_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 9 of file namespace0_generated.c.
References UA_ReferenceTypeAttributes::displayName, UA_ReferenceTypeAttributes::inverseName, UA_LOCALIZEDTEXT(), UA_NODECLASS_REFERENCETYPE, UA_NODEID_NULL, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_ReferenceTypeAttributes_default, UA_Server_addNode_begin(), and UA_TYPES.
Referenced by namespace0_generated().
function_namespace0_generated_0_finish()
static UA_StatusCode function_namespace0_generated_0_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 24 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_100_begin()
static UA_StatusCode function_namespace0_generated_100_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 2557 of file namespace0_generated.c.
References UA_VariableAttributes::accessLevel, UA_VariableAttributes::dataType, UA_VariableAttributes::displayName, UA_VariableAttributes::minimumSamplingInterval, UA_LOCALIZEDTEXT(), UA_NODECLASS_VARIABLE, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_TYPES, UA_VariableAttributes_default, UA_VariableAttributes::userAccessLevel, and UA_VariableAttributes::valueRank.
Referenced by namespace0_generated().
function_namespace0_generated_100_finish()
static UA_StatusCode function_namespace0_generated_100_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 2577 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_101_begin()
static UA_StatusCode function_namespace0_generated_101_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 2585 of file namespace0_generated.c.
References UA_VariableAttributes::accessLevel, UA_VariableAttributes::dataType, UA_VariableAttributes::displayName, UA_VariableAttributes::minimumSamplingInterval, UA_LOCALIZEDTEXT(), UA_NODECLASS_VARIABLE, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_TYPES, UA_VariableAttributes_default, UA_VariableAttributes::userAccessLevel, and UA_VariableAttributes::valueRank.
Referenced by namespace0_generated().
function_namespace0_generated_101_finish()
static UA_StatusCode function_namespace0_generated_101_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 2605 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_102_begin()
static UA_StatusCode function_namespace0_generated_102_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 2613 of file namespace0_generated.c.
References UA_VariableAttributes::accessLevel, UA_VariableAttributes::dataType, UA_VariableAttributes::displayName, UA_VariableAttributes::minimumSamplingInterval, UA_LOCALIZEDTEXT(), UA_NODECLASS_VARIABLE, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_TYPES, UA_VariableAttributes_default, UA_VariableAttributes::userAccessLevel, and UA_VariableAttributes::valueRank.
Referenced by namespace0_generated().
function_namespace0_generated_102_finish()
static UA_StatusCode function_namespace0_generated_102_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 2633 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_103_begin()
static UA_StatusCode function_namespace0_generated_103_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 2641 of file namespace0_generated.c.
References UA_VariableAttributes::accessLevel, UA_VariableAttributes::dataType, UA_VariableAttributes::displayName, UA_VariableAttributes::minimumSamplingInterval, UA_LOCALIZEDTEXT(), UA_NODECLASS_VARIABLE, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_TYPES, UA_VariableAttributes_default, UA_VariableAttributes::userAccessLevel, and UA_VariableAttributes::valueRank.
Referenced by namespace0_generated().
function_namespace0_generated_103_finish()
static UA_StatusCode function_namespace0_generated_103_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 2661 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_104_begin()
static UA_StatusCode function_namespace0_generated_104_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 2669 of file namespace0_generated.c.
References UA_VariableAttributes::accessLevel, UA_VariableAttributes::dataType, UA_VariableAttributes::displayName, UA_VariableAttributes::minimumSamplingInterval, UA_LOCALIZEDTEXT(), UA_NODECLASS_VARIABLE, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_TYPES, UA_VariableAttributes_default, UA_VariableAttributes::userAccessLevel, and UA_VariableAttributes::valueRank.
Referenced by namespace0_generated().
function_namespace0_generated_104_finish()
static UA_StatusCode function_namespace0_generated_104_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 2689 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_105_begin()
static UA_StatusCode function_namespace0_generated_105_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 2697 of file namespace0_generated.c.
References UA_VariableAttributes::accessLevel, UA_VariableAttributes::dataType, UA_VariableAttributes::displayName, UA_VariableAttributes::minimumSamplingInterval, UA_LOCALIZEDTEXT(), UA_NODECLASS_VARIABLE, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_TYPES, UA_VariableAttributes_default, UA_VariableAttributes::userAccessLevel, and UA_VariableAttributes::valueRank.
Referenced by namespace0_generated().
function_namespace0_generated_105_finish()
static UA_StatusCode function_namespace0_generated_105_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 2717 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_106_begin()
static UA_StatusCode function_namespace0_generated_106_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 2725 of file namespace0_generated.c.
References UA_VariableAttributes::accessLevel, UA_VariableAttributes::dataType, UA_VariableAttributes::displayName, UA_VariableAttributes::minimumSamplingInterval, UA_LOCALIZEDTEXT(), UA_NODECLASS_VARIABLE, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_TYPES, UA_VariableAttributes_default, UA_VariableAttributes::userAccessLevel, and UA_VariableAttributes::valueRank.
Referenced by namespace0_generated().
function_namespace0_generated_106_finish()
static UA_StatusCode function_namespace0_generated_106_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 2745 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_107_begin()
static UA_StatusCode function_namespace0_generated_107_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 2753 of file namespace0_generated.c.
References UA_VariableAttributes::accessLevel, UA_VariableAttributes::dataType, UA_VariableAttributes::displayName, UA_VariableAttributes::minimumSamplingInterval, UA_LOCALIZEDTEXT(), UA_NODECLASS_VARIABLE, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_TYPES, UA_VariableAttributes_default, UA_VariableAttributes::userAccessLevel, and UA_VariableAttributes::valueRank.
Referenced by namespace0_generated().
function_namespace0_generated_107_finish()
static UA_StatusCode function_namespace0_generated_107_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 2773 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_108_begin()
static UA_StatusCode function_namespace0_generated_108_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 2781 of file namespace0_generated.c.
References UA_VariableAttributes::accessLevel, UA_VariableAttributes::dataType, UA_VariableAttributes::displayName, UA_VariableAttributes::minimumSamplingInterval, UA_LOCALIZEDTEXT(), UA_NODECLASS_VARIABLE, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_TYPES, UA_VariableAttributes_default, UA_VariableAttributes::userAccessLevel, and UA_VariableAttributes::valueRank.
Referenced by namespace0_generated().
function_namespace0_generated_108_finish()
static UA_StatusCode function_namespace0_generated_108_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 2801 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_109_begin()
static UA_StatusCode function_namespace0_generated_109_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 2809 of file namespace0_generated.c.
References UA_VariableAttributes::accessLevel, UA_VariableAttributes::dataType, UA_VariableAttributes::displayName, UA_VariableAttributes::minimumSamplingInterval, UA_LOCALIZEDTEXT(), UA_NODECLASS_VARIABLE, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_TYPES, UA_VariableAttributes_default, UA_VariableAttributes::userAccessLevel, and UA_VariableAttributes::valueRank.
Referenced by namespace0_generated().
function_namespace0_generated_109_finish()
static UA_StatusCode function_namespace0_generated_109_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 2829 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_10_begin()
static UA_StatusCode function_namespace0_generated_10_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 233 of file namespace0_generated.c.
References UA_DataTypeAttributes::displayName, UA_DataTypeAttributes_default, UA_LOCALIZEDTEXT(), UA_NODECLASS_DATATYPE, UA_NODEID_NULL, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), and UA_TYPES.
Referenced by namespace0_generated().
function_namespace0_generated_10_finish()
static UA_StatusCode function_namespace0_generated_10_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 247 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_110_begin()
static UA_StatusCode function_namespace0_generated_110_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 2837 of file namespace0_generated.c.
References UA_VariableAttributes::accessLevel, UA_VariableAttributes::dataType, UA_VariableAttributes::displayName, UA_VariableAttributes::minimumSamplingInterval, UA_LOCALIZEDTEXT(), UA_NODECLASS_VARIABLE, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_TYPES, UA_VariableAttributes_default, UA_VariableAttributes::userAccessLevel, and UA_VariableAttributes::valueRank.
Referenced by namespace0_generated().
function_namespace0_generated_110_finish()
static UA_StatusCode function_namespace0_generated_110_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 2857 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_111_begin()
static UA_StatusCode function_namespace0_generated_111_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 2865 of file namespace0_generated.c.
References UA_VariableAttributes::accessLevel, UA_VariableAttributes::dataType, UA_VariableAttributes::displayName, UA_VariableAttributes::minimumSamplingInterval, UA_LOCALIZEDTEXT(), UA_NODECLASS_VARIABLE, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_TYPES, UA_VariableAttributes_default, UA_VariableAttributes::userAccessLevel, and UA_VariableAttributes::valueRank.
Referenced by namespace0_generated().
function_namespace0_generated_111_finish()
static UA_StatusCode function_namespace0_generated_111_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 2885 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_112_begin()
static UA_StatusCode function_namespace0_generated_112_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 2893 of file namespace0_generated.c.
References UA_ObjectAttributes::displayName, UA_LOCALIZEDTEXT(), UA_NODECLASS_OBJECT, UA_NODEID_NUMERIC(), UA_ObjectAttributes_default, UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), and UA_TYPES.
Referenced by namespace0_generated().
function_namespace0_generated_112_finish()
static UA_StatusCode function_namespace0_generated_112_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 2907 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_113_begin()
static UA_StatusCode function_namespace0_generated_113_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 2915 of file namespace0_generated.c.
References UA_VariableAttributes::accessLevel, UA_VariableAttributes::dataType, UA_VariableAttributes::displayName, UA_VariableAttributes::minimumSamplingInterval, UA_LOCALIZEDTEXT(), UA_NODECLASS_VARIABLE, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_TYPES, UA_VariableAttributes_default, UA_VariableAttributes::userAccessLevel, and UA_VariableAttributes::valueRank.
Referenced by namespace0_generated().
function_namespace0_generated_113_finish()
static UA_StatusCode function_namespace0_generated_113_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 2935 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_114_begin()
static UA_StatusCode function_namespace0_generated_114_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 2943 of file namespace0_generated.c.
References UA_VariableAttributes::accessLevel, UA_VariableAttributes::dataType, UA_VariableAttributes::displayName, UA_VariableAttributes::minimumSamplingInterval, UA_LOCALIZEDTEXT(), UA_NODECLASS_VARIABLE, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_TYPES, UA_VariableAttributes_default, UA_VariableAttributes::userAccessLevel, and UA_VariableAttributes::valueRank.
Referenced by namespace0_generated().
function_namespace0_generated_114_finish()
static UA_StatusCode function_namespace0_generated_114_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 2963 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_115_begin()
static UA_StatusCode function_namespace0_generated_115_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 2971 of file namespace0_generated.c.
References UA_VariableAttributes::accessLevel, UA_VariableAttributes::dataType, UA_VariableAttributes::displayName, UA_VariableAttributes::minimumSamplingInterval, UA_LOCALIZEDTEXT(), UA_NODECLASS_VARIABLE, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_TYPES, UA_VariableAttributes_default, UA_VariableAttributes::userAccessLevel, and UA_VariableAttributes::valueRank.
Referenced by namespace0_generated().
function_namespace0_generated_115_finish()
static UA_StatusCode function_namespace0_generated_115_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 2991 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_116_begin()
static UA_StatusCode function_namespace0_generated_116_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 2999 of file namespace0_generated.c.
References UA_VariableAttributes::accessLevel, UA_VariableAttributes::dataType, UA_VariableAttributes::displayName, UA_VariableAttributes::minimumSamplingInterval, UA_LOCALIZEDTEXT(), UA_NODECLASS_VARIABLE, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_TYPES, UA_VariableAttributes_default, UA_VariableAttributes::userAccessLevel, and UA_VariableAttributes::valueRank.
Referenced by namespace0_generated().
function_namespace0_generated_116_finish()
static UA_StatusCode function_namespace0_generated_116_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 3019 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_117_begin()
static UA_StatusCode function_namespace0_generated_117_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 3027 of file namespace0_generated.c.
References UA_VariableAttributes::accessLevel, UA_VariableAttributes::dataType, UA_VariableAttributes::displayName, UA_VariableAttributes::minimumSamplingInterval, UA_LOCALIZEDTEXT(), UA_NODECLASS_VARIABLE, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_TYPES, UA_VariableAttributes_default, UA_VariableAttributes::userAccessLevel, and UA_VariableAttributes::valueRank.
Referenced by namespace0_generated().
function_namespace0_generated_117_finish()
static UA_StatusCode function_namespace0_generated_117_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 3047 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_118_begin()
static UA_StatusCode function_namespace0_generated_118_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 3055 of file namespace0_generated.c.
References UA_VariableAttributes::accessLevel, UA_VariableAttributes::dataType, UA_VariableAttributes::displayName, UA_VariableAttributes::minimumSamplingInterval, UA_LOCALIZEDTEXT(), UA_NODECLASS_VARIABLE, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_TYPES, UA_VariableAttributes_default, UA_VariableAttributes::userAccessLevel, and UA_VariableAttributes::valueRank.
Referenced by namespace0_generated().
function_namespace0_generated_118_finish()
static UA_StatusCode function_namespace0_generated_118_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 3075 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_119_begin()
static UA_StatusCode function_namespace0_generated_119_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 3083 of file namespace0_generated.c.
References UA_VariableAttributes::accessLevel, UA_VariableAttributes::dataType, UA_VariableAttributes::displayName, UA_VariableAttributes::minimumSamplingInterval, UA_LOCALIZEDTEXT(), UA_NODECLASS_VARIABLE, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_TYPES, UA_VariableAttributes_default, UA_VariableAttributes::userAccessLevel, and UA_VariableAttributes::valueRank.
Referenced by namespace0_generated().
function_namespace0_generated_119_finish()
static UA_StatusCode function_namespace0_generated_119_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 3103 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_11_begin()
static UA_StatusCode function_namespace0_generated_11_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 255 of file namespace0_generated.c.
References UA_DataTypeAttributes::displayName, UA_DataTypeAttributes_default, UA_LOCALIZEDTEXT(), UA_NODECLASS_DATATYPE, UA_NODEID_NULL, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), and UA_TYPES.
Referenced by namespace0_generated().
function_namespace0_generated_11_finish()
static UA_StatusCode function_namespace0_generated_11_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 269 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_120_begin()
static UA_StatusCode function_namespace0_generated_120_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 3111 of file namespace0_generated.c.
References UA_VariableAttributes::accessLevel, UA_VariableAttributes::dataType, UA_VariableAttributes::displayName, UA_VariableAttributes::minimumSamplingInterval, UA_LOCALIZEDTEXT(), UA_NODECLASS_VARIABLE, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_TYPES, UA_VariableAttributes_default, UA_VariableAttributes::userAccessLevel, and UA_VariableAttributes::valueRank.
Referenced by namespace0_generated().
function_namespace0_generated_120_finish()
static UA_StatusCode function_namespace0_generated_120_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 3131 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_121_begin()
static UA_StatusCode function_namespace0_generated_121_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 3139 of file namespace0_generated.c.
References UA_VariableAttributes::accessLevel, UA_VariableAttributes::dataType, UA_VariableAttributes::displayName, UA_VariableAttributes::minimumSamplingInterval, UA_LOCALIZEDTEXT(), UA_NODECLASS_VARIABLE, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_TYPES, UA_VariableAttributes_default, UA_VariableAttributes::userAccessLevel, and UA_VariableAttributes::valueRank.
Referenced by namespace0_generated().
function_namespace0_generated_121_finish()
static UA_StatusCode function_namespace0_generated_121_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 3159 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_122_begin()
static UA_StatusCode function_namespace0_generated_122_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 3167 of file namespace0_generated.c.
References UA_VariableAttributes::accessLevel, UA_VariableAttributes::dataType, UA_VariableAttributes::displayName, UA_VariableAttributes::minimumSamplingInterval, UA_LOCALIZEDTEXT(), UA_NODECLASS_VARIABLE, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_TYPES, UA_VariableAttributes_default, UA_VariableAttributes::userAccessLevel, and UA_VariableAttributes::valueRank.
Referenced by namespace0_generated().
function_namespace0_generated_122_finish()
static UA_StatusCode function_namespace0_generated_122_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 3187 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_123_begin()
static UA_StatusCode function_namespace0_generated_123_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 3195 of file namespace0_generated.c.
References UA_VariableAttributes::accessLevel, UA_VariableAttributes::dataType, UA_VariableAttributes::displayName, UA_VariableAttributes::minimumSamplingInterval, UA_LOCALIZEDTEXT(), UA_NODECLASS_VARIABLE, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_TYPES, UA_VariableAttributes_default, UA_VariableAttributes::userAccessLevel, and UA_VariableAttributes::valueRank.
Referenced by namespace0_generated().
function_namespace0_generated_123_finish()
static UA_StatusCode function_namespace0_generated_123_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 3215 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_124_begin()
static UA_StatusCode function_namespace0_generated_124_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 3223 of file namespace0_generated.c.
References UA_VariableAttributes::accessLevel, UA_VariableAttributes::dataType, UA_VariableAttributes::displayName, UA_VariableAttributes::minimumSamplingInterval, UA_LOCALIZEDTEXT(), UA_NODECLASS_VARIABLE, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_TYPES, UA_VariableAttributes_default, UA_VariableAttributes::userAccessLevel, and UA_VariableAttributes::valueRank.
Referenced by namespace0_generated().
function_namespace0_generated_124_finish()
static UA_StatusCode function_namespace0_generated_124_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 3243 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_125_begin()
static UA_StatusCode function_namespace0_generated_125_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 3251 of file namespace0_generated.c.
References UA_VariableAttributes::accessLevel, UA_VariableAttributes::dataType, UA_VariableAttributes::displayName, UA_VariableAttributes::minimumSamplingInterval, UA_LOCALIZEDTEXT(), UA_NODECLASS_VARIABLE, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_TYPES, UA_VariableAttributes_default, UA_VariableAttributes::userAccessLevel, and UA_VariableAttributes::valueRank.
Referenced by namespace0_generated().
function_namespace0_generated_125_finish()
static UA_StatusCode function_namespace0_generated_125_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 3271 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_126_begin()
static UA_StatusCode function_namespace0_generated_126_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 3279 of file namespace0_generated.c.
References UA_VariableAttributes::accessLevel, UA_VariableAttributes::dataType, UA_VariableAttributes::displayName, UA_VariableAttributes::minimumSamplingInterval, UA_LOCALIZEDTEXT(), UA_NODECLASS_VARIABLE, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_TYPES, UA_VariableAttributes_default, UA_VariableAttributes::userAccessLevel, and UA_VariableAttributes::valueRank.
Referenced by namespace0_generated().
function_namespace0_generated_126_finish()
static UA_StatusCode function_namespace0_generated_126_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 3299 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_127_begin()
static UA_StatusCode function_namespace0_generated_127_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 3307 of file namespace0_generated.c.
References UA_ObjectAttributes::displayName, UA_LOCALIZEDTEXT(), UA_NODECLASS_OBJECT, UA_NODEID_NUMERIC(), UA_ObjectAttributes_default, UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), and UA_TYPES.
Referenced by namespace0_generated().
function_namespace0_generated_127_finish()
static UA_StatusCode function_namespace0_generated_127_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 3321 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_128_begin()
static UA_StatusCode function_namespace0_generated_128_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 3329 of file namespace0_generated.c.
References UA_VariableAttributes::accessLevel, UA_VariableAttributes::arrayDimensions, UA_VariableAttributes::arrayDimensionsSize, UA_VariableAttributes::dataType, UA_VariableAttributes::displayName, UA_VariableAttributes::minimumSamplingInterval, UA_LOCALIZEDTEXT(), UA_NODECLASS_VARIABLE, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_TYPES, UA_VariableAttributes_default, UA_VariableAttributes::userAccessLevel, and UA_VariableAttributes::valueRank.
Referenced by namespace0_generated().
function_namespace0_generated_128_finish()
static UA_StatusCode function_namespace0_generated_128_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 3352 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_129_begin()
static UA_StatusCode function_namespace0_generated_129_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 3360 of file namespace0_generated.c.
References UA_VariableAttributes::accessLevel, UA_VariableAttributes::arrayDimensions, UA_VariableAttributes::arrayDimensionsSize, UA_VariableAttributes::dataType, UA_VariableAttributes::displayName, UA_VariableAttributes::minimumSamplingInterval, UA_LOCALIZEDTEXT(), UA_NODECLASS_VARIABLE, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_TYPES, UA_VariableAttributes_default, UA_VariableAttributes::userAccessLevel, and UA_VariableAttributes::valueRank.
Referenced by namespace0_generated().
function_namespace0_generated_129_finish()
static UA_StatusCode function_namespace0_generated_129_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 3383 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_12_begin()
static UA_StatusCode function_namespace0_generated_12_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 277 of file namespace0_generated.c.
References UA_DataTypeAttributes::displayName, UA_DataTypeAttributes_default, UA_LOCALIZEDTEXT(), UA_NODECLASS_DATATYPE, UA_NODEID_NULL, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), and UA_TYPES.
Referenced by namespace0_generated().
function_namespace0_generated_12_finish()
static UA_StatusCode function_namespace0_generated_12_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 291 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_130_begin()
static UA_StatusCode function_namespace0_generated_130_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 3391 of file namespace0_generated.c.
References UA_VariableAttributes::accessLevel, UA_VariableAttributes::dataType, UA_VariableAttributes::displayName, UA_VariableAttributes::minimumSamplingInterval, UA_LOCALIZEDTEXT(), UA_NODECLASS_VARIABLE, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_TYPES, UA_VariableAttributes_default, UA_VariableAttributes::userAccessLevel, and UA_VariableAttributes::valueRank.
Referenced by namespace0_generated().
function_namespace0_generated_130_finish()
static UA_StatusCode function_namespace0_generated_130_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 3411 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_131_begin()
static UA_StatusCode function_namespace0_generated_131_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 3419 of file namespace0_generated.c.
References UA_ObjectAttributes::displayName, UA_LOCALIZEDTEXT(), UA_NODECLASS_OBJECT, UA_NODEID_NUMERIC(), UA_ObjectAttributes_default, UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), and UA_TYPES.
Referenced by namespace0_generated().
function_namespace0_generated_131_finish()
static UA_StatusCode function_namespace0_generated_131_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 3433 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_132_begin()
static UA_StatusCode function_namespace0_generated_132_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 3441 of file namespace0_generated.c.
References UA_VariableAttributes::accessLevel, UA_VariableAttributes::dataType, UA_VariableAttributes::displayName, UA_VariableAttributes::minimumSamplingInterval, UA_LOCALIZEDTEXT(), UA_NODECLASS_VARIABLE, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_TYPES, UA_VariableAttributes_default, UA_VariableAttributes::userAccessLevel, and UA_VariableAttributes::valueRank.
Referenced by namespace0_generated().
function_namespace0_generated_132_finish()
static UA_StatusCode function_namespace0_generated_132_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 3461 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_133_begin()
static UA_StatusCode function_namespace0_generated_133_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 3469 of file namespace0_generated.c.
References UA_ObjectAttributes::displayName, UA_EXPANDEDNODEID_NUMERIC(), UA_LOCALIZEDTEXT(), UA_NODECLASS_OBJECT, UA_NODEID_NUMERIC(), UA_ObjectAttributes_default, UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_Server_addReference(), and UA_TYPES.
Referenced by namespace0_generated().
function_namespace0_generated_133_finish()
static UA_StatusCode function_namespace0_generated_133_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 3484 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_134_begin()
static UA_StatusCode function_namespace0_generated_134_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 3492 of file namespace0_generated.c.
References UA_ObjectAttributes::displayName, UA_LOCALIZEDTEXT(), UA_NODECLASS_OBJECT, UA_NODEID_NUMERIC(), UA_ObjectAttributes_default, UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), and UA_TYPES.
Referenced by namespace0_generated().
function_namespace0_generated_134_finish()
static UA_StatusCode function_namespace0_generated_134_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 3506 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_135_begin()
static UA_StatusCode function_namespace0_generated_135_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 3514 of file namespace0_generated.c.
References UA_ObjectTypeAttributes::displayName, UA_ObjectTypeAttributes::isAbstract, UA_EXPANDEDNODEID_NUMERIC(), UA_LOCALIZEDTEXT(), UA_NODECLASS_OBJECTTYPE, UA_NODEID_NULL, UA_NODEID_NUMERIC(), UA_ObjectTypeAttributes_default, UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_Server_addReference(), and UA_TYPES.
Referenced by namespace0_generated().
function_namespace0_generated_135_finish()
static UA_StatusCode function_namespace0_generated_135_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 3530 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_136_begin()
static UA_StatusCode function_namespace0_generated_136_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 3538 of file namespace0_generated.c.
References UA_ObjectTypeAttributes::displayName, UA_LOCALIZEDTEXT(), UA_NODECLASS_OBJECTTYPE, UA_NODEID_NULL, UA_NODEID_NUMERIC(), UA_ObjectTypeAttributes_default, UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), and UA_TYPES.
Referenced by namespace0_generated().
function_namespace0_generated_136_finish()
static UA_StatusCode function_namespace0_generated_136_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 3552 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_137_begin()
static UA_StatusCode function_namespace0_generated_137_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 3560 of file namespace0_generated.c.
References UA_VariableAttributes::accessLevel, UA_VariableAttributes::dataType, UA_VariableAttributes::displayName, UA_VariableAttributes::minimumSamplingInterval, UA_EXPANDEDNODEID_NUMERIC(), UA_LOCALIZEDTEXT(), UA_NODECLASS_VARIABLE, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_Server_addReference(), UA_TYPES, UA_VariableAttributes_default, UA_VariableAttributes::userAccessLevel, and UA_VariableAttributes::valueRank.
Referenced by namespace0_generated().
function_namespace0_generated_137_finish()
static UA_StatusCode function_namespace0_generated_137_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 3581 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_138_begin()
static UA_StatusCode function_namespace0_generated_138_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 3589 of file namespace0_generated.c.
References UA_VariableAttributes::accessLevel, UA_VariableAttributes::dataType, UA_VariableAttributes::displayName, UA_VariableAttributes::minimumSamplingInterval, UA_EXPANDEDNODEID_NUMERIC(), UA_LOCALIZEDTEXT(), UA_NODECLASS_VARIABLE, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_Server_addReference(), UA_TYPES, UA_VariableAttributes_default, UA_VariableAttributes::userAccessLevel, and UA_VariableAttributes::valueRank.
Referenced by namespace0_generated().
function_namespace0_generated_138_finish()
static UA_StatusCode function_namespace0_generated_138_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 3610 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_139_begin()
static UA_StatusCode function_namespace0_generated_139_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 3618 of file namespace0_generated.c.
References UA_VariableAttributes::accessLevel, UA_VariableAttributes::dataType, UA_VariableAttributes::displayName, UA_VariableAttributes::minimumSamplingInterval, UA_EXPANDEDNODEID_NUMERIC(), UA_LOCALIZEDTEXT(), UA_NODECLASS_VARIABLE, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_Server_addReference(), UA_TYPES, UA_VariableAttributes_default, UA_VariableAttributes::userAccessLevel, and UA_VariableAttributes::valueRank.
Referenced by namespace0_generated().
function_namespace0_generated_139_finish()
static UA_StatusCode function_namespace0_generated_139_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 3639 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_13_begin()
static UA_StatusCode function_namespace0_generated_13_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 299 of file namespace0_generated.c.
References UA_DataTypeAttributes::displayName, UA_DataTypeAttributes_default, UA_LOCALIZEDTEXT(), UA_NODECLASS_DATATYPE, UA_NODEID_NULL, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), and UA_TYPES.
Referenced by namespace0_generated().
function_namespace0_generated_13_finish()
static UA_StatusCode function_namespace0_generated_13_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 313 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_140_begin()
static UA_StatusCode function_namespace0_generated_140_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 3647 of file namespace0_generated.c.
References UA_VariableAttributes::accessLevel, UA_VariableAttributes::dataType, UA_VariableAttributes::displayName, UA_VariableAttributes::minimumSamplingInterval, UA_EXPANDEDNODEID_NUMERIC(), UA_LOCALIZEDTEXT(), UA_NODECLASS_VARIABLE, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_Server_addReference(), UA_TYPES, UA_VariableAttributes_default, UA_VariableAttributes::userAccessLevel, and UA_VariableAttributes::valueRank.
Referenced by namespace0_generated().
function_namespace0_generated_140_finish()
static UA_StatusCode function_namespace0_generated_140_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 3668 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_141_begin()
static UA_StatusCode function_namespace0_generated_141_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 3676 of file namespace0_generated.c.
References UA_VariableAttributes::accessLevel, UA_VariableAttributes::dataType, UA_VariableAttributes::displayName, UA_VariableAttributes::minimumSamplingInterval, UA_EXPANDEDNODEID_NUMERIC(), UA_LOCALIZEDTEXT(), UA_NODECLASS_VARIABLE, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_Server_addReference(), UA_TYPES, UA_VariableAttributes_default, UA_VariableAttributes::userAccessLevel, and UA_VariableAttributes::valueRank.
Referenced by namespace0_generated().
function_namespace0_generated_141_finish()
static UA_StatusCode function_namespace0_generated_141_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 3697 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_142_begin()
static UA_StatusCode function_namespace0_generated_142_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 3705 of file namespace0_generated.c.
References UA_VariableAttributes::accessLevel, UA_VariableAttributes::dataType, UA_VariableAttributes::displayName, UA_VariableAttributes::minimumSamplingInterval, UA_EXPANDEDNODEID_NUMERIC(), UA_LOCALIZEDTEXT(), UA_NODECLASS_VARIABLE, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_Server_addReference(), UA_TYPES, UA_VariableAttributes_default, UA_VariableAttributes::userAccessLevel, and UA_VariableAttributes::valueRank.
Referenced by namespace0_generated().
function_namespace0_generated_142_finish()
static UA_StatusCode function_namespace0_generated_142_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 3726 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_143_begin()
static UA_StatusCode function_namespace0_generated_143_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 3734 of file namespace0_generated.c.
References UA_VariableAttributes::accessLevel, UA_VariableAttributes::dataType, UA_VariableAttributes::displayName, UA_VariableAttributes::minimumSamplingInterval, UA_EXPANDEDNODEID_NUMERIC(), UA_LOCALIZEDTEXT(), UA_NODECLASS_VARIABLE, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_Server_addReference(), UA_TYPES, UA_VariableAttributes_default, UA_VariableAttributes::userAccessLevel, and UA_VariableAttributes::valueRank.
Referenced by namespace0_generated().
function_namespace0_generated_143_finish()
static UA_StatusCode function_namespace0_generated_143_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 3755 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_144_begin()
static UA_StatusCode function_namespace0_generated_144_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 3763 of file namespace0_generated.c.
References UA_VariableAttributes::accessLevel, UA_VariableAttributes::dataType, UA_VariableAttributes::displayName, UA_VariableAttributes::minimumSamplingInterval, UA_EXPANDEDNODEID_NUMERIC(), UA_LOCALIZEDTEXT(), UA_NODECLASS_VARIABLE, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_Server_addReference(), UA_TYPES, UA_VariableAttributes_default, UA_VariableAttributes::userAccessLevel, and UA_VariableAttributes::valueRank.
Referenced by namespace0_generated().
function_namespace0_generated_144_finish()
static UA_StatusCode function_namespace0_generated_144_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 3784 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_145_begin()
static UA_StatusCode function_namespace0_generated_145_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 3792 of file namespace0_generated.c.
References UA_ObjectTypeAttributes::displayName, UA_LOCALIZEDTEXT(), UA_NODECLASS_OBJECTTYPE, UA_NODEID_NULL, UA_NODEID_NUMERIC(), UA_ObjectTypeAttributes_default, UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), and UA_TYPES.
Referenced by namespace0_generated().
function_namespace0_generated_145_finish()
static UA_StatusCode function_namespace0_generated_145_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 3806 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_146_begin()
static UA_StatusCode function_namespace0_generated_146_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 3814 of file namespace0_generated.c.
References UA_ObjectAttributes::displayName, UA_EXPANDEDNODEID_NUMERIC(), UA_LOCALIZEDTEXT(), UA_NODECLASS_OBJECT, UA_NODEID_NUMERIC(), UA_ObjectAttributes_default, UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_Server_addReference(), and UA_TYPES.
Referenced by namespace0_generated().
function_namespace0_generated_146_finish()
static UA_StatusCode function_namespace0_generated_146_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 3829 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_147_begin()
static UA_StatusCode function_namespace0_generated_147_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 3837 of file namespace0_generated.c.
References UA_ObjectAttributes::displayName, UA_LOCALIZEDTEXT(), UA_NODECLASS_OBJECT, UA_NODEID_NUMERIC(), UA_ObjectAttributes_default, UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), and UA_TYPES.
Referenced by namespace0_generated().
function_namespace0_generated_147_finish()
static UA_StatusCode function_namespace0_generated_147_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 3851 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_148_begin()
static UA_StatusCode function_namespace0_generated_148_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 3859 of file namespace0_generated.c.
References UA_VariableAttributes::accessLevel, UA_VariableAttributes::arrayDimensions, UA_VariableAttributes::arrayDimensionsSize, UA_VariableAttributes::dataType, UA_VariableAttributes::displayName, UA_VariableAttributes::minimumSamplingInterval, UA_LOCALIZEDTEXT(), UA_NODECLASS_VARIABLE, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_TYPES, UA_VariableAttributes_default, UA_VariableAttributes::userAccessLevel, and UA_VariableAttributes::valueRank.
Referenced by namespace0_generated().
function_namespace0_generated_148_finish()
static UA_StatusCode function_namespace0_generated_148_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 3882 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_149_begin()
static UA_StatusCode function_namespace0_generated_149_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 3890 of file namespace0_generated.c.
References UA_ObjectAttributes::displayName, UA_LOCALIZEDTEXT(), UA_NODECLASS_OBJECT, UA_NODEID_NUMERIC(), UA_ObjectAttributes_default, UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), and UA_TYPES.
Referenced by namespace0_generated().
function_namespace0_generated_149_finish()
static UA_StatusCode function_namespace0_generated_149_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 3904 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_14_begin()
static UA_StatusCode function_namespace0_generated_14_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 321 of file namespace0_generated.c.
References UA_DataTypeAttributes::displayName, UA_DataTypeAttributes_default, UA_LOCALIZEDTEXT(), UA_NODECLASS_DATATYPE, UA_NODEID_NULL, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), and UA_TYPES.
Referenced by namespace0_generated().
function_namespace0_generated_14_finish()
static UA_StatusCode function_namespace0_generated_14_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 335 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_150_begin()
static UA_StatusCode function_namespace0_generated_150_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 3912 of file namespace0_generated.c.
References UA_ObjectAttributes::displayName, UA_LOCALIZEDTEXT(), UA_NODECLASS_OBJECT, UA_NODEID_NUMERIC(), UA_ObjectAttributes_default, UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), and UA_TYPES.
Referenced by namespace0_generated().
function_namespace0_generated_150_finish()
static UA_StatusCode function_namespace0_generated_150_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 3926 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_151_begin()
static UA_StatusCode function_namespace0_generated_151_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 3934 of file namespace0_generated.c.
References UA_ObjectAttributes::displayName, UA_LOCALIZEDTEXT(), UA_NODECLASS_OBJECT, UA_NODEID_NUMERIC(), UA_ObjectAttributes_default, UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), and UA_TYPES.
Referenced by namespace0_generated().
function_namespace0_generated_151_finish()
static UA_StatusCode function_namespace0_generated_151_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 3948 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_152_begin()
static UA_StatusCode function_namespace0_generated_152_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 3956 of file namespace0_generated.c.
References UA_VariableAttributes::accessLevel, UA_VariableAttributes::dataType, UA_VariableAttributes::displayName, UA_VariableAttributes::minimumSamplingInterval, UA_LOCALIZEDTEXT(), UA_NODECLASS_VARIABLE, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_TYPES, UA_VariableAttributes_default, UA_VariableAttributes::userAccessLevel, and UA_VariableAttributes::valueRank.
Referenced by namespace0_generated().
function_namespace0_generated_152_finish()
static UA_StatusCode function_namespace0_generated_152_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 3976 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_153_begin()
static UA_StatusCode function_namespace0_generated_153_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 3984 of file namespace0_generated.c.
References UA_VariableAttributes::accessLevel, UA_VariableAttributes::dataType, UA_VariableAttributes::displayName, UA_VariableAttributes::minimumSamplingInterval, UA_LOCALIZEDTEXT(), UA_NODECLASS_VARIABLE, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_TYPES, UA_VariableAttributes_default, UA_VariableAttributes::userAccessLevel, and UA_VariableAttributes::valueRank.
Referenced by namespace0_generated().
function_namespace0_generated_153_finish()
static UA_StatusCode function_namespace0_generated_153_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 4004 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_154_begin()
static UA_StatusCode function_namespace0_generated_154_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 4012 of file namespace0_generated.c.
References UA_VariableAttributes::accessLevel, UA_VariableAttributes::dataType, UA_VariableAttributes::displayName, UA_VariableAttributes::minimumSamplingInterval, UA_LOCALIZEDTEXT(), UA_NODECLASS_VARIABLE, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_TYPES, UA_VariableAttributes_default, UA_VariableAttributes::userAccessLevel, and UA_VariableAttributes::valueRank.
Referenced by namespace0_generated().
function_namespace0_generated_154_finish()
static UA_StatusCode function_namespace0_generated_154_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 4032 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_155_begin()
static UA_StatusCode function_namespace0_generated_155_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 4040 of file namespace0_generated.c.
References UA_VariableAttributes::accessLevel, UA_VariableAttributes::dataType, UA_VariableAttributes::displayName, UA_VariableAttributes::minimumSamplingInterval, UA_LOCALIZEDTEXT(), UA_NODECLASS_VARIABLE, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_TYPES, UA_VariableAttributes_default, UA_VariableAttributes::userAccessLevel, and UA_VariableAttributes::valueRank.
Referenced by namespace0_generated().
function_namespace0_generated_155_finish()
static UA_StatusCode function_namespace0_generated_155_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 4060 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_156_begin()
static UA_StatusCode function_namespace0_generated_156_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 4068 of file namespace0_generated.c.
References UA_VariableAttributes::accessLevel, UA_VariableAttributes::dataType, UA_VariableAttributes::displayName, UA_VariableAttributes::minimumSamplingInterval, UA_LOCALIZEDTEXT(), UA_NODECLASS_VARIABLE, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_TYPES, UA_VariableAttributes_default, UA_VariableAttributes::userAccessLevel, and UA_VariableAttributes::valueRank.
Referenced by namespace0_generated().
function_namespace0_generated_156_finish()
static UA_StatusCode function_namespace0_generated_156_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 4088 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_157_begin()
static UA_StatusCode function_namespace0_generated_157_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 4096 of file namespace0_generated.c.
References UA_VariableAttributes::accessLevel, UA_VariableAttributes::dataType, UA_VariableAttributes::displayName, UA_VariableAttributes::minimumSamplingInterval, UA_LOCALIZEDTEXT(), UA_NODECLASS_VARIABLE, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_TYPES, UA_VariableAttributes_default, UA_VariableAttributes::userAccessLevel, and UA_VariableAttributes::valueRank.
Referenced by namespace0_generated().
function_namespace0_generated_157_finish()
static UA_StatusCode function_namespace0_generated_157_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 4116 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_158_begin()
static UA_StatusCode function_namespace0_generated_158_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 4124 of file namespace0_generated.c.
References UA_VariableAttributes::accessLevel, UA_VariableAttributes::dataType, UA_VariableAttributes::displayName, UA_VariableAttributes::minimumSamplingInterval, UA_LOCALIZEDTEXT(), UA_NODECLASS_VARIABLE, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_TYPES, UA_VariableAttributes_default, UA_VariableAttributes::userAccessLevel, and UA_VariableAttributes::valueRank.
Referenced by namespace0_generated().
function_namespace0_generated_158_finish()
static UA_StatusCode function_namespace0_generated_158_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 4144 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_159_begin()
static UA_StatusCode function_namespace0_generated_159_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 4152 of file namespace0_generated.c.
References UA_VariableAttributes::accessLevel, UA_VariableAttributes::dataType, UA_VariableAttributes::displayName, UA_VariableAttributes::minimumSamplingInterval, UA_LOCALIZEDTEXT(), UA_NODECLASS_VARIABLE, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_TYPES, UA_VariableAttributes_default, UA_VariableAttributes::userAccessLevel, and UA_VariableAttributes::valueRank.
Referenced by namespace0_generated().
function_namespace0_generated_159_finish()
static UA_StatusCode function_namespace0_generated_159_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 4172 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_15_begin()
static UA_StatusCode function_namespace0_generated_15_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 343 of file namespace0_generated.c.
References UA_DataTypeAttributes::displayName, UA_DataTypeAttributes_default, UA_LOCALIZEDTEXT(), UA_NODECLASS_DATATYPE, UA_NODEID_NULL, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), and UA_TYPES.
Referenced by namespace0_generated().
function_namespace0_generated_15_finish()
static UA_StatusCode function_namespace0_generated_15_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 357 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_160_begin()
static UA_StatusCode function_namespace0_generated_160_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 4180 of file namespace0_generated.c.
References UA_VariableAttributes::accessLevel, UA_VariableAttributes::arrayDimensions, UA_VariableAttributes::arrayDimensionsSize, UA_VariableAttributes::dataType, UA_VariableAttributes::displayName, UA_VariableAttributes::minimumSamplingInterval, UA_LOCALIZEDTEXT(), UA_NODECLASS_VARIABLE, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_TYPES, UA_VariableAttributes_default, UA_VariableAttributes::userAccessLevel, and UA_VariableAttributes::valueRank.
Referenced by namespace0_generated().
function_namespace0_generated_160_finish()
static UA_StatusCode function_namespace0_generated_160_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 4203 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_161_begin()
static UA_StatusCode function_namespace0_generated_161_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 4211 of file namespace0_generated.c.
References UA_VariableAttributes::accessLevel, UA_VariableAttributes::dataType, UA_VariableAttributes::displayName, UA_VariableAttributes::minimumSamplingInterval, UA_LOCALIZEDTEXT(), UA_NODECLASS_VARIABLE, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_TYPES, UA_VariableAttributes_default, UA_VariableAttributes::userAccessLevel, and UA_VariableAttributes::valueRank.
Referenced by namespace0_generated().
function_namespace0_generated_161_finish()
static UA_StatusCode function_namespace0_generated_161_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 4231 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_162_begin()
static UA_StatusCode function_namespace0_generated_162_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 4239 of file namespace0_generated.c.
References UA_VariableAttributes::accessLevel, UA_VariableAttributes::arrayDimensions, UA_VariableAttributes::arrayDimensionsSize, UA_VariableAttributes::dataType, UA_VariableAttributes::displayName, UA_VariableAttributes::minimumSamplingInterval, UA_LOCALIZEDTEXT(), UA_NODECLASS_VARIABLE, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_TYPES, UA_VariableAttributes_default, UA_VariableAttributes::userAccessLevel, and UA_VariableAttributes::valueRank.
Referenced by namespace0_generated().
function_namespace0_generated_162_finish()
static UA_StatusCode function_namespace0_generated_162_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 4262 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_163_begin()
static UA_StatusCode function_namespace0_generated_163_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 4270 of file namespace0_generated.c.
References UA_VariableAttributes::accessLevel, UA_VariableAttributes::dataType, UA_VariableAttributes::displayName, UA_VariableAttributes::minimumSamplingInterval, UA_LOCALIZEDTEXT(), UA_NODECLASS_VARIABLE, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_TYPES, UA_VariableAttributes_default, UA_VariableAttributes::userAccessLevel, and UA_VariableAttributes::valueRank.
Referenced by namespace0_generated().
function_namespace0_generated_163_finish()
static UA_StatusCode function_namespace0_generated_163_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 4290 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_164_begin()
static UA_StatusCode function_namespace0_generated_164_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 4298 of file namespace0_generated.c.
References UA_VariableAttributes::accessLevel, UA_VariableAttributes::dataType, UA_VariableAttributes::displayName, UA_VariableAttributes::minimumSamplingInterval, UA_LOCALIZEDTEXT(), UA_NODECLASS_VARIABLE, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_TYPES, UA_VariableAttributes_default, UA_VariableAttributes::userAccessLevel, and UA_VariableAttributes::valueRank.
Referenced by namespace0_generated().
function_namespace0_generated_164_finish()
static UA_StatusCode function_namespace0_generated_164_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 4318 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_165_begin()
static UA_StatusCode function_namespace0_generated_165_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 4326 of file namespace0_generated.c.
References UA_VariableAttributes::accessLevel, UA_VariableAttributes::dataType, UA_VariableAttributes::displayName, UA_VariableAttributes::minimumSamplingInterval, UA_LOCALIZEDTEXT(), UA_NODECLASS_VARIABLE, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_TYPES, UA_VariableAttributes_default, UA_VariableAttributes::userAccessLevel, and UA_VariableAttributes::valueRank.
Referenced by namespace0_generated().
function_namespace0_generated_165_finish()
static UA_StatusCode function_namespace0_generated_165_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 4346 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_16_begin()
static UA_StatusCode function_namespace0_generated_16_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 365 of file namespace0_generated.c.
References UA_DataTypeAttributes::displayName, UA_DataTypeAttributes::isAbstract, UA_DataTypeAttributes_default, UA_LOCALIZEDTEXT(), UA_NODECLASS_DATATYPE, UA_NODEID_NULL, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), and UA_TYPES.
Referenced by namespace0_generated().
function_namespace0_generated_16_finish()
static UA_StatusCode function_namespace0_generated_16_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 380 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_17_begin()
static UA_StatusCode function_namespace0_generated_17_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 388 of file namespace0_generated.c.
References UA_DataTypeAttributes::displayName, UA_DataTypeAttributes_default, UA_LOCALIZEDTEXT(), UA_NODECLASS_DATATYPE, UA_NODEID_NULL, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), and UA_TYPES.
Referenced by namespace0_generated().
function_namespace0_generated_17_finish()
static UA_StatusCode function_namespace0_generated_17_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 402 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_18_begin()
static UA_StatusCode function_namespace0_generated_18_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 410 of file namespace0_generated.c.
References UA_DataTypeAttributes::displayName, UA_DataTypeAttributes::isAbstract, UA_DataTypeAttributes_default, UA_LOCALIZEDTEXT(), UA_NODECLASS_DATATYPE, UA_NODEID_NULL, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), and UA_TYPES.
Referenced by namespace0_generated().
function_namespace0_generated_18_finish()
static UA_StatusCode function_namespace0_generated_18_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 425 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_19_begin()
static UA_StatusCode function_namespace0_generated_19_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 433 of file namespace0_generated.c.
References UA_DataTypeAttributes::displayName, UA_DataTypeAttributes_default, UA_LOCALIZEDTEXT(), UA_NODECLASS_DATATYPE, UA_NODEID_NULL, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), and UA_TYPES.
Referenced by namespace0_generated().
function_namespace0_generated_19_finish()
static UA_StatusCode function_namespace0_generated_19_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 447 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_1_begin()
static UA_StatusCode function_namespace0_generated_1_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 32 of file namespace0_generated.c.
References UA_ReferenceTypeAttributes::displayName, UA_ReferenceTypeAttributes::inverseName, UA_LOCALIZEDTEXT(), UA_NODECLASS_REFERENCETYPE, UA_NODEID_NULL, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_ReferenceTypeAttributes_default, UA_Server_addNode_begin(), and UA_TYPES.
Referenced by namespace0_generated().
function_namespace0_generated_1_finish()
static UA_StatusCode function_namespace0_generated_1_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 47 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_20_begin()
static UA_StatusCode function_namespace0_generated_20_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 455 of file namespace0_generated.c.
References UA_DataTypeAttributes::displayName, UA_DataTypeAttributes_default, UA_LOCALIZEDTEXT(), UA_NODECLASS_DATATYPE, UA_NODEID_NULL, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), and UA_TYPES.
Referenced by namespace0_generated().
function_namespace0_generated_20_finish()
static UA_StatusCode function_namespace0_generated_20_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 469 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_21_begin()
static UA_StatusCode function_namespace0_generated_21_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 477 of file namespace0_generated.c.
References UA_DataTypeAttributes::displayName, UA_DataTypeAttributes_default, UA_LOCALIZEDTEXT(), UA_NODECLASS_DATATYPE, UA_NODEID_NULL, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), and UA_TYPES.
Referenced by namespace0_generated().
function_namespace0_generated_21_finish()
static UA_StatusCode function_namespace0_generated_21_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 491 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_22_begin()
static UA_StatusCode function_namespace0_generated_22_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 499 of file namespace0_generated.c.
References UA_DataTypeAttributes::displayName, UA_DataTypeAttributes_default, UA_LOCALIZEDTEXT(), UA_NODECLASS_DATATYPE, UA_NODEID_NULL, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), and UA_TYPES.
Referenced by namespace0_generated().
function_namespace0_generated_22_finish()
static UA_StatusCode function_namespace0_generated_22_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 513 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_23_begin()
static UA_StatusCode function_namespace0_generated_23_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 521 of file namespace0_generated.c.
References UA_DataTypeAttributes::displayName, UA_DataTypeAttributes::isAbstract, UA_DataTypeAttributes_default, UA_LOCALIZEDTEXT(), UA_NODECLASS_DATATYPE, UA_NODEID_NULL, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), and UA_TYPES.
Referenced by namespace0_generated().
function_namespace0_generated_23_finish()
static UA_StatusCode function_namespace0_generated_23_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 536 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_24_begin()
static UA_StatusCode function_namespace0_generated_24_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 544 of file namespace0_generated.c.
References UA_DataTypeAttributes::displayName, UA_DataTypeAttributes_default, UA_LOCALIZEDTEXT(), UA_NODECLASS_DATATYPE, UA_NODEID_NULL, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), and UA_TYPES.
Referenced by namespace0_generated().
function_namespace0_generated_24_finish()
static UA_StatusCode function_namespace0_generated_24_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 558 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_25_begin()
static UA_StatusCode function_namespace0_generated_25_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 566 of file namespace0_generated.c.
References UA_DataTypeAttributes::displayName, UA_DataTypeAttributes_default, UA_LOCALIZEDTEXT(), UA_NODECLASS_DATATYPE, UA_NODEID_NULL, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), and UA_TYPES.
Referenced by namespace0_generated().
function_namespace0_generated_25_finish()
static UA_StatusCode function_namespace0_generated_25_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 580 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_26_begin()
static UA_StatusCode function_namespace0_generated_26_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 588 of file namespace0_generated.c.
References UA_DataTypeAttributes::displayName, UA_DataTypeAttributes_default, UA_LOCALIZEDTEXT(), UA_NODECLASS_DATATYPE, UA_NODEID_NULL, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), and UA_TYPES.
Referenced by namespace0_generated().
function_namespace0_generated_26_finish()
static UA_StatusCode function_namespace0_generated_26_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 602 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_27_begin()
static UA_StatusCode function_namespace0_generated_27_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 610 of file namespace0_generated.c.
References UA_DataTypeAttributes::displayName, UA_DataTypeAttributes_default, UA_LOCALIZEDTEXT(), UA_NODECLASS_DATATYPE, UA_NODEID_NULL, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), and UA_TYPES.
Referenced by namespace0_generated().
function_namespace0_generated_27_finish()
static UA_StatusCode function_namespace0_generated_27_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 624 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_28_begin()
static UA_StatusCode function_namespace0_generated_28_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 632 of file namespace0_generated.c.
References UA_DataTypeAttributes::displayName, UA_DataTypeAttributes_default, UA_LOCALIZEDTEXT(), UA_NODECLASS_DATATYPE, UA_NODEID_NULL, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), and UA_TYPES.
Referenced by namespace0_generated().
function_namespace0_generated_28_finish()
static UA_StatusCode function_namespace0_generated_28_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 646 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_29_begin()
static UA_StatusCode function_namespace0_generated_29_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 654 of file namespace0_generated.c.
References UA_DataTypeAttributes::displayName, UA_DataTypeAttributes_default, UA_LOCALIZEDTEXT(), UA_NODECLASS_DATATYPE, UA_NODEID_NULL, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), and UA_TYPES.
Referenced by namespace0_generated().
function_namespace0_generated_29_finish()
static UA_StatusCode function_namespace0_generated_29_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 668 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_2_begin()
static UA_StatusCode function_namespace0_generated_2_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 55 of file namespace0_generated.c.
References UA_DataTypeAttributes::displayName, UA_DataTypeAttributes_default, UA_LOCALIZEDTEXT(), UA_NODECLASS_DATATYPE, UA_NODEID_NULL, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), and UA_TYPES.
Referenced by namespace0_generated().
function_namespace0_generated_2_finish()
static UA_StatusCode function_namespace0_generated_2_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 69 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_30_begin()
static UA_StatusCode function_namespace0_generated_30_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 676 of file namespace0_generated.c.
References UA_DataTypeAttributes::displayName, UA_DataTypeAttributes_default, UA_LOCALIZEDTEXT(), UA_NODECLASS_DATATYPE, UA_NODEID_NULL, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), and UA_TYPES.
Referenced by namespace0_generated().
function_namespace0_generated_30_finish()
static UA_StatusCode function_namespace0_generated_30_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 690 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_31_begin()
static UA_StatusCode function_namespace0_generated_31_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 698 of file namespace0_generated.c.
References UA_DataTypeAttributes::displayName, UA_DataTypeAttributes_default, UA_LOCALIZEDTEXT(), UA_NODECLASS_DATATYPE, UA_NODEID_NULL, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), and UA_TYPES.
Referenced by namespace0_generated().
function_namespace0_generated_31_finish()
static UA_StatusCode function_namespace0_generated_31_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 712 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_32_begin()
static UA_StatusCode function_namespace0_generated_32_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 720 of file namespace0_generated.c.
References UA_DataTypeAttributes::displayName, UA_DataTypeAttributes::isAbstract, UA_DataTypeAttributes_default, UA_LOCALIZEDTEXT(), UA_NODECLASS_DATATYPE, UA_NODEID_NULL, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), and UA_TYPES.
Referenced by namespace0_generated().
function_namespace0_generated_32_finish()
static UA_StatusCode function_namespace0_generated_32_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 735 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_33_begin()
static UA_StatusCode function_namespace0_generated_33_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 743 of file namespace0_generated.c.
References UA_DataTypeAttributes::displayName, UA_DataTypeAttributes_default, UA_LOCALIZEDTEXT(), UA_NODECLASS_DATATYPE, UA_NODEID_NULL, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), and UA_TYPES.
Referenced by namespace0_generated().
function_namespace0_generated_33_finish()
static UA_StatusCode function_namespace0_generated_33_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 757 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_34_begin()
static UA_StatusCode function_namespace0_generated_34_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 765 of file namespace0_generated.c.
References UA_VariableAttributes::accessLevel, UA_VariableAttributes::arrayDimensions, UA_VariableAttributes::arrayDimensionsSize, UA_VariableAttributes::dataType, UA_EnumValueType::description, UA_VariableAttributes::displayName, UA_EnumValueType::displayName, UA_VariableAttributes::minimumSamplingInterval, UA_init(), UA_LOCALIZEDTEXT(), UA_NODECLASS_VARIABLE, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_TYPES, UA_VariableAttributes_default, UA_Variant_setArray(), UA_VariableAttributes::userAccessLevel, UA_VariableAttributes::value, UA_EnumValueType::value, and UA_VariableAttributes::valueRank.
Referenced by namespace0_generated().
function_namespace0_generated_34_finish()
static UA_StatusCode function_namespace0_generated_34_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 808 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_35_begin()
static UA_StatusCode function_namespace0_generated_35_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 816 of file namespace0_generated.c.
References UA_DataTypeAttributes::displayName, UA_DataTypeAttributes_default, UA_LOCALIZEDTEXT(), UA_NODECLASS_DATATYPE, UA_NODEID_NULL, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), and UA_TYPES.
Referenced by namespace0_generated().
function_namespace0_generated_35_finish()
static UA_StatusCode function_namespace0_generated_35_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 830 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_36_begin()
static UA_StatusCode function_namespace0_generated_36_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 838 of file namespace0_generated.c.
References UA_VariableAttributes::accessLevel, UA_VariableAttributes::arrayDimensions, UA_VariableAttributes::arrayDimensionsSize, UA_VariableAttributes::dataType, UA_VariableAttributes::displayName, UA_VariableAttributes::minimumSamplingInterval, UA_LOCALIZEDTEXT(), UA_NODECLASS_VARIABLE, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_TYPES, UA_VariableAttributes_default, UA_Variant_setArray(), UA_VariableAttributes::userAccessLevel, UA_VariableAttributes::value, and UA_VariableAttributes::valueRank.
Referenced by namespace0_generated().
function_namespace0_generated_36_finish()
static UA_StatusCode function_namespace0_generated_36_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 869 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_37_begin()
static UA_StatusCode function_namespace0_generated_37_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 877 of file namespace0_generated.c.
References UA_DataTypeAttributes::displayName, UA_DataTypeAttributes_default, UA_LOCALIZEDTEXT(), UA_NODECLASS_DATATYPE, UA_NODEID_NULL, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), and UA_TYPES.
Referenced by namespace0_generated().
function_namespace0_generated_37_finish()
static UA_StatusCode function_namespace0_generated_37_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 891 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_38_begin()
static UA_StatusCode function_namespace0_generated_38_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 899 of file namespace0_generated.c.
References UA_ReferenceTypeAttributes::displayName, UA_ReferenceTypeAttributes::inverseName, UA_LOCALIZEDTEXT(), UA_NODECLASS_REFERENCETYPE, UA_NODEID_NULL, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_ReferenceTypeAttributes_default, UA_Server_addNode_begin(), and UA_TYPES.
Referenced by namespace0_generated().
function_namespace0_generated_38_finish()
static UA_StatusCode function_namespace0_generated_38_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 914 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_39_begin()
static UA_StatusCode function_namespace0_generated_39_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 922 of file namespace0_generated.c.
References UA_ReferenceTypeAttributes::displayName, UA_ReferenceTypeAttributes::inverseName, UA_LOCALIZEDTEXT(), UA_NODECLASS_REFERENCETYPE, UA_NODEID_NULL, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_ReferenceTypeAttributes_default, UA_Server_addNode_begin(), and UA_TYPES.
Referenced by namespace0_generated().
function_namespace0_generated_39_finish()
static UA_StatusCode function_namespace0_generated_39_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 937 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_3_begin()
static UA_StatusCode function_namespace0_generated_3_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 77 of file namespace0_generated.c.
References UA_DataTypeAttributes::displayName, UA_DataTypeAttributes_default, UA_LOCALIZEDTEXT(), UA_NODECLASS_DATATYPE, UA_NODEID_NULL, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), and UA_TYPES.
Referenced by namespace0_generated().
function_namespace0_generated_3_finish()
static UA_StatusCode function_namespace0_generated_3_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 91 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_40_begin()
static UA_StatusCode function_namespace0_generated_40_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 945 of file namespace0_generated.c.
References UA_ReferenceTypeAttributes::displayName, UA_ReferenceTypeAttributes::inverseName, UA_LOCALIZEDTEXT(), UA_NODECLASS_REFERENCETYPE, UA_NODEID_NULL, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_ReferenceTypeAttributes_default, UA_Server_addNode_begin(), and UA_TYPES.
Referenced by namespace0_generated().
function_namespace0_generated_40_finish()
static UA_StatusCode function_namespace0_generated_40_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 960 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_41_begin()
static UA_StatusCode function_namespace0_generated_41_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 968 of file namespace0_generated.c.
References UA_ReferenceTypeAttributes::displayName, UA_ReferenceTypeAttributes::inverseName, UA_LOCALIZEDTEXT(), UA_NODECLASS_REFERENCETYPE, UA_NODEID_NULL, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_ReferenceTypeAttributes_default, UA_Server_addNode_begin(), and UA_TYPES.
Referenced by namespace0_generated().
function_namespace0_generated_41_finish()
static UA_StatusCode function_namespace0_generated_41_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 983 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_42_begin()
static UA_StatusCode function_namespace0_generated_42_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 991 of file namespace0_generated.c.
References UA_ReferenceTypeAttributes::displayName, UA_ReferenceTypeAttributes::inverseName, UA_LOCALIZEDTEXT(), UA_NODECLASS_REFERENCETYPE, UA_NODEID_NULL, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_ReferenceTypeAttributes_default, UA_Server_addNode_begin(), and UA_TYPES.
Referenced by namespace0_generated().
function_namespace0_generated_42_finish()
static UA_StatusCode function_namespace0_generated_42_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 1006 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_43_begin()
static UA_StatusCode function_namespace0_generated_43_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 1014 of file namespace0_generated.c.
References UA_DataTypeAttributes::displayName, UA_DataTypeAttributes_default, UA_LOCALIZEDTEXT(), UA_NODECLASS_DATATYPE, UA_NODEID_NULL, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), and UA_TYPES.
Referenced by namespace0_generated().
function_namespace0_generated_43_finish()
static UA_StatusCode function_namespace0_generated_43_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 1028 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_44_begin()
static UA_StatusCode function_namespace0_generated_44_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 1036 of file namespace0_generated.c.
References UA_DataTypeAttributes::displayName, UA_DataTypeAttributes_default, UA_LOCALIZEDTEXT(), UA_NODECLASS_DATATYPE, UA_NODEID_NULL, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), and UA_TYPES.
Referenced by namespace0_generated().
function_namespace0_generated_44_finish()
static UA_StatusCode function_namespace0_generated_44_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 1050 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_45_begin()
static UA_StatusCode function_namespace0_generated_45_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 1058 of file namespace0_generated.c.
References UA_DataTypeAttributes::displayName, UA_DataTypeAttributes_default, UA_LOCALIZEDTEXT(), UA_NODECLASS_DATATYPE, UA_NODEID_NULL, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), and UA_TYPES.
Referenced by namespace0_generated().
function_namespace0_generated_45_finish()
static UA_StatusCode function_namespace0_generated_45_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 1072 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_46_begin()
static UA_StatusCode function_namespace0_generated_46_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 1080 of file namespace0_generated.c.
References UA_DataTypeAttributes::displayName, UA_DataTypeAttributes_default, UA_LOCALIZEDTEXT(), UA_NODECLASS_DATATYPE, UA_NODEID_NULL, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), and UA_TYPES.
Referenced by namespace0_generated().
function_namespace0_generated_46_finish()
static UA_StatusCode function_namespace0_generated_46_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 1094 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_47_begin()
static UA_StatusCode function_namespace0_generated_47_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 1102 of file namespace0_generated.c.
References UA_DataTypeAttributes::displayName, UA_DataTypeAttributes_default, UA_LOCALIZEDTEXT(), UA_NODECLASS_DATATYPE, UA_NODEID_NULL, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), and UA_TYPES.
Referenced by namespace0_generated().
function_namespace0_generated_47_finish()
static UA_StatusCode function_namespace0_generated_47_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 1116 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_48_begin()
static UA_StatusCode function_namespace0_generated_48_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 1124 of file namespace0_generated.c.
References UA_DataTypeAttributes::displayName, UA_DataTypeAttributes_default, UA_LOCALIZEDTEXT(), UA_NODECLASS_DATATYPE, UA_NODEID_NULL, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), and UA_TYPES.
Referenced by namespace0_generated().
function_namespace0_generated_48_finish()
static UA_StatusCode function_namespace0_generated_48_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 1138 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_49_begin()
static UA_StatusCode function_namespace0_generated_49_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 1146 of file namespace0_generated.c.
References UA_DataTypeAttributes::displayName, UA_DataTypeAttributes_default, UA_LOCALIZEDTEXT(), UA_NODECLASS_DATATYPE, UA_NODEID_NULL, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), and UA_TYPES.
Referenced by namespace0_generated().
function_namespace0_generated_49_finish()
static UA_StatusCode function_namespace0_generated_49_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 1160 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_4_begin()
static UA_StatusCode function_namespace0_generated_4_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 99 of file namespace0_generated.c.
References UA_DataTypeAttributes::displayName, UA_DataTypeAttributes_default, UA_LOCALIZEDTEXT(), UA_NODECLASS_DATATYPE, UA_NODEID_NULL, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), and UA_TYPES.
Referenced by namespace0_generated().
function_namespace0_generated_4_finish()
static UA_StatusCode function_namespace0_generated_4_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 113 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_50_begin()
static UA_StatusCode function_namespace0_generated_50_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 1168 of file namespace0_generated.c.
References UA_DataTypeAttributes::displayName, UA_DataTypeAttributes_default, UA_LOCALIZEDTEXT(), UA_NODECLASS_DATATYPE, UA_NODEID_NULL, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), and UA_TYPES.
Referenced by namespace0_generated().
function_namespace0_generated_50_finish()
static UA_StatusCode function_namespace0_generated_50_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 1182 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_51_begin()
static UA_StatusCode function_namespace0_generated_51_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 1190 of file namespace0_generated.c.
References UA_ObjectTypeAttributes::displayName, UA_LOCALIZEDTEXT(), UA_NODECLASS_OBJECTTYPE, UA_NODEID_NULL, UA_NODEID_NUMERIC(), UA_ObjectTypeAttributes_default, UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), and UA_TYPES.
Referenced by namespace0_generated().
function_namespace0_generated_51_finish()
static UA_StatusCode function_namespace0_generated_51_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 1204 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_52_begin()
static UA_StatusCode function_namespace0_generated_52_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 1212 of file namespace0_generated.c.
References UA_ObjectAttributes::displayName, UA_LOCALIZEDTEXT(), UA_NODECLASS_OBJECT, UA_NODEID_NUMERIC(), UA_ObjectAttributes_default, UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), and UA_TYPES.
Referenced by namespace0_generated().
function_namespace0_generated_52_finish()
static UA_StatusCode function_namespace0_generated_52_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 1226 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_53_begin()
static UA_StatusCode function_namespace0_generated_53_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 1234 of file namespace0_generated.c.
References UA_ObjectAttributes::displayName, UA_LOCALIZEDTEXT(), UA_NODECLASS_OBJECT, UA_NODEID_NUMERIC(), UA_ObjectAttributes_default, UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), and UA_TYPES.
Referenced by namespace0_generated().
function_namespace0_generated_53_finish()
static UA_StatusCode function_namespace0_generated_53_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 1248 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_54_begin()
static UA_StatusCode function_namespace0_generated_54_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 1256 of file namespace0_generated.c.
References UA_VariableTypeAttributes::dataType, UA_VariableTypeAttributes::displayName, UA_LOCALIZEDTEXT(), UA_NODECLASS_VARIABLETYPE, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_TYPES, UA_VariableTypeAttributes_default, and UA_VariableTypeAttributes::valueRank.
Referenced by namespace0_generated().
function_namespace0_generated_54_finish()
static UA_StatusCode function_namespace0_generated_54_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 1273 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_55_begin()
static UA_StatusCode function_namespace0_generated_55_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 1281 of file namespace0_generated.c.
References UA_ObjectTypeAttributes::displayName, UA_LOCALIZEDTEXT(), UA_NODECLASS_OBJECTTYPE, UA_NODEID_NULL, UA_NODEID_NUMERIC(), UA_ObjectTypeAttributes_default, UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), and UA_TYPES.
Referenced by namespace0_generated().
function_namespace0_generated_55_finish()
static UA_StatusCode function_namespace0_generated_55_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 1295 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_56_begin()
static UA_StatusCode function_namespace0_generated_56_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 1303 of file namespace0_generated.c.
References UA_VariableTypeAttributes::dataType, UA_VariableTypeAttributes::displayName, UA_LOCALIZEDTEXT(), UA_NODECLASS_VARIABLETYPE, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_TYPES, UA_VariableTypeAttributes_default, and UA_VariableTypeAttributes::valueRank.
Referenced by namespace0_generated().
function_namespace0_generated_56_finish()
static UA_StatusCode function_namespace0_generated_56_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 1320 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_57_begin()
static UA_StatusCode function_namespace0_generated_57_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 1328 of file namespace0_generated.c.
References UA_VariableAttributes::accessLevel, UA_VariableAttributes::dataType, UA_VariableAttributes::displayName, UA_VariableAttributes::minimumSamplingInterval, UA_LOCALIZEDTEXT(), UA_NODECLASS_VARIABLE, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_TYPES, UA_VariableAttributes_default, UA_VariableAttributes::userAccessLevel, and UA_VariableAttributes::valueRank.
Referenced by namespace0_generated().
function_namespace0_generated_57_finish()
static UA_StatusCode function_namespace0_generated_57_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 1348 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_58_begin()
static UA_StatusCode function_namespace0_generated_58_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 1356 of file namespace0_generated.c.
References UA_VariableAttributes::accessLevel, UA_VariableAttributes::dataType, UA_VariableAttributes::displayName, UA_VariableAttributes::minimumSamplingInterval, UA_LOCALIZEDTEXT(), UA_NODECLASS_VARIABLE, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_TYPES, UA_VariableAttributes_default, UA_VariableAttributes::userAccessLevel, and UA_VariableAttributes::valueRank.
Referenced by namespace0_generated().
function_namespace0_generated_58_finish()
static UA_StatusCode function_namespace0_generated_58_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 1376 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_59_begin()
static UA_StatusCode function_namespace0_generated_59_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 1384 of file namespace0_generated.c.
References UA_VariableTypeAttributes::dataType, UA_VariableTypeAttributes::displayName, UA_LOCALIZEDTEXT(), UA_NODECLASS_VARIABLETYPE, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_TYPES, UA_VariableTypeAttributes_default, and UA_VariableTypeAttributes::valueRank.
Referenced by namespace0_generated().
function_namespace0_generated_59_finish()
static UA_StatusCode function_namespace0_generated_59_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 1401 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_5_begin()
static UA_StatusCode function_namespace0_generated_5_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 121 of file namespace0_generated.c.
References UA_DataTypeAttributes::displayName, UA_DataTypeAttributes::isAbstract, UA_DataTypeAttributes_default, UA_LOCALIZEDTEXT(), UA_NODECLASS_DATATYPE, UA_NODEID_NULL, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), and UA_TYPES.
Referenced by namespace0_generated().
function_namespace0_generated_5_finish()
static UA_StatusCode function_namespace0_generated_5_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 136 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_60_begin()
static UA_StatusCode function_namespace0_generated_60_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 1409 of file namespace0_generated.c.
References UA_VariableAttributes::accessLevel, UA_VariableAttributes::dataType, UA_VariableAttributes::description, UA_VariableAttributes::displayName, UA_VariableAttributes::minimumSamplingInterval, UA_LOCALIZEDTEXT(), UA_NODECLASS_VARIABLE, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_TYPES, UA_VariableAttributes_default, UA_VariableAttributes::userAccessLevel, and UA_VariableAttributes::valueRank.
Referenced by namespace0_generated().
function_namespace0_generated_60_finish()
static UA_StatusCode function_namespace0_generated_60_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 1432 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_61_begin()
static UA_StatusCode function_namespace0_generated_61_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 1440 of file namespace0_generated.c.
References UA_VariableAttributes::accessLevel, UA_VariableAttributes::dataType, UA_VariableAttributes::displayName, UA_VariableAttributes::minimumSamplingInterval, UA_LOCALIZEDTEXT(), UA_NODECLASS_VARIABLE, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_TYPES, UA_VariableAttributes_default, UA_VariableAttributes::userAccessLevel, and UA_VariableAttributes::valueRank.
Referenced by namespace0_generated().
function_namespace0_generated_61_finish()
static UA_StatusCode function_namespace0_generated_61_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 1460 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_62_begin()
static UA_StatusCode function_namespace0_generated_62_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 1468 of file namespace0_generated.c.
References UA_ObjectTypeAttributes::displayName, UA_LOCALIZEDTEXT(), UA_NODECLASS_OBJECTTYPE, UA_NODEID_NULL, UA_NODEID_NUMERIC(), UA_ObjectTypeAttributes_default, UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), and UA_TYPES.
Referenced by namespace0_generated().
function_namespace0_generated_62_finish()
static UA_StatusCode function_namespace0_generated_62_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 1482 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_63_begin()
static UA_StatusCode function_namespace0_generated_63_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 1490 of file namespace0_generated.c.
References UA_ObjectAttributes::displayName, UA_LOCALIZEDTEXT(), UA_NODECLASS_OBJECT, UA_NODEID_NUMERIC(), UA_ObjectAttributes_default, UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), and UA_TYPES.
Referenced by namespace0_generated().
function_namespace0_generated_63_finish()
static UA_StatusCode function_namespace0_generated_63_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 1504 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_64_begin()
static UA_StatusCode function_namespace0_generated_64_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 1512 of file namespace0_generated.c.
References UA_VariableAttributes::accessLevel, UA_String::data, UA_VariableAttributes::dataType, UA_VariableAttributes::displayName, UA_String::length, UA_VariableAttributes::minimumSamplingInterval, UA_ByteString_delete(), UA_ByteString_init(), UA_ByteString_new(), UA_BYTESTRING_NULL, UA_LOCALIZEDTEXT(), UA_NODECLASS_VARIABLE, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_TYPES, UA_VariableAttributes_default, UA_Variant_setScalar(), UA_VariableAttributes::userAccessLevel, UA_VariableAttributes::value, and UA_VariableAttributes::valueRank.
Referenced by namespace0_generated().
function_namespace0_generated_64_finish()
static UA_StatusCode function_namespace0_generated_64_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 1540 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_65_begin()
static UA_StatusCode function_namespace0_generated_65_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 1548 of file namespace0_generated.c.
References UA_VariableAttributes::accessLevel, UA_VariableAttributes::dataType, UA_VariableAttributes::displayName, UA_VariableAttributes::minimumSamplingInterval, UA_LOCALIZEDTEXT(), UA_NODECLASS_VARIABLE, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_String_delete(), UA_String_init(), UA_String_new(), UA_TYPES, UA_VariableAttributes_default, UA_Variant_setScalar(), UA_VariableAttributes::userAccessLevel, UA_VariableAttributes::value, and UA_VariableAttributes::valueRank.
Referenced by namespace0_generated().
function_namespace0_generated_65_finish()
static UA_StatusCode function_namespace0_generated_65_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 1574 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_66_begin()
static UA_StatusCode function_namespace0_generated_66_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 1582 of file namespace0_generated.c.
References UA_VariableAttributes::accessLevel, UA_VariableAttributes::dataType, UA_VariableAttributes::displayName, UA_VariableAttributes::minimumSamplingInterval, UA_LOCALIZEDTEXT(), UA_NODECLASS_VARIABLE, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_String_delete(), UA_String_init(), UA_String_new(), UA_TYPES, UA_VariableAttributes_default, UA_Variant_setScalar(), UA_VariableAttributes::userAccessLevel, UA_VariableAttributes::value, and UA_VariableAttributes::valueRank.
Referenced by namespace0_generated().
function_namespace0_generated_66_finish()
static UA_StatusCode function_namespace0_generated_66_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 1608 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_67_begin()
static UA_StatusCode function_namespace0_generated_67_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 1616 of file namespace0_generated.c.
References UA_ObjectAttributes::displayName, UA_LOCALIZEDTEXT(), UA_NODECLASS_OBJECT, UA_NODEID_NUMERIC(), UA_ObjectAttributes_default, UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), and UA_TYPES.
Referenced by namespace0_generated().
function_namespace0_generated_67_finish()
static UA_StatusCode function_namespace0_generated_67_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 1630 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_68_begin()
static UA_StatusCode function_namespace0_generated_68_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 1638 of file namespace0_generated.c.
References UA_ObjectTypeAttributes::displayName, UA_LOCALIZEDTEXT(), UA_NODECLASS_OBJECTTYPE, UA_NODEID_NULL, UA_NODEID_NUMERIC(), UA_ObjectTypeAttributes_default, UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), and UA_TYPES.
Referenced by namespace0_generated().
function_namespace0_generated_68_finish()
static UA_StatusCode function_namespace0_generated_68_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 1652 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_69_begin()
static UA_StatusCode function_namespace0_generated_69_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 1660 of file namespace0_generated.c.
References UA_ObjectAttributes::displayName, UA_EXPANDEDNODEID_NUMERIC(), UA_LOCALIZEDTEXT(), UA_NODECLASS_OBJECT, UA_NODEID_NUMERIC(), UA_ObjectAttributes_default, UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_Server_addReference(), and UA_TYPES.
Referenced by namespace0_generated().
function_namespace0_generated_69_finish()
static UA_StatusCode function_namespace0_generated_69_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 1676 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_6_begin()
static UA_StatusCode function_namespace0_generated_6_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 144 of file namespace0_generated.c.
References UA_DataTypeAttributes::displayName, UA_DataTypeAttributes_default, UA_LOCALIZEDTEXT(), UA_NODECLASS_DATATYPE, UA_NODEID_NULL, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), and UA_TYPES.
Referenced by namespace0_generated().
function_namespace0_generated_6_finish()
static UA_StatusCode function_namespace0_generated_6_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 158 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_70_begin()
static UA_StatusCode function_namespace0_generated_70_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 1684 of file namespace0_generated.c.
References UA_ObjectAttributes::displayName, UA_EXPANDEDNODEID_NUMERIC(), UA_LOCALIZEDTEXT(), UA_NODECLASS_OBJECT, UA_NODEID_NUMERIC(), UA_ObjectAttributes_default, UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_Server_addReference(), and UA_TYPES.
Referenced by namespace0_generated().
function_namespace0_generated_70_finish()
static UA_StatusCode function_namespace0_generated_70_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 1700 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_71_begin()
static UA_StatusCode function_namespace0_generated_71_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 1708 of file namespace0_generated.c.
References UA_ObjectTypeAttributes::displayName, UA_LOCALIZEDTEXT(), UA_NODECLASS_OBJECTTYPE, UA_NODEID_NULL, UA_NODEID_NUMERIC(), UA_ObjectTypeAttributes_default, UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), and UA_TYPES.
Referenced by namespace0_generated().
function_namespace0_generated_71_finish()
static UA_StatusCode function_namespace0_generated_71_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 1722 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_72_begin()
static UA_StatusCode function_namespace0_generated_72_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 1730 of file namespace0_generated.c.
References UA_ObjectAttributes::displayName, UA_EXPANDEDNODEID_NUMERIC(), UA_LOCALIZEDTEXT(), UA_NODECLASS_OBJECT, UA_NODEID_NUMERIC(), UA_ObjectAttributes_default, UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_Server_addReference(), and UA_TYPES.
Referenced by namespace0_generated().
function_namespace0_generated_72_finish()
static UA_StatusCode function_namespace0_generated_72_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 1746 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_73_begin()
static UA_StatusCode function_namespace0_generated_73_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 1754 of file namespace0_generated.c.
References UA_VariableAttributes::accessLevel, UA_VariableAttributes::dataType, UA_VariableAttributes::displayName, UA_VariableAttributes::minimumSamplingInterval, UA_Int32_delete(), UA_Int32_init(), UA_Int32_new(), UA_LOCALIZEDTEXT(), UA_NODECLASS_VARIABLE, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_TYPES, UA_VariableAttributes_default, UA_Variant_setScalar(), UA_VariableAttributes::userAccessLevel, UA_VariableAttributes::value, and UA_VariableAttributes::valueRank.
Referenced by namespace0_generated().
function_namespace0_generated_73_finish()
static UA_StatusCode function_namespace0_generated_73_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 1780 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_74_begin()
static UA_StatusCode function_namespace0_generated_74_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 1788 of file namespace0_generated.c.
References UA_VariableAttributes::accessLevel, UA_VariableAttributes::dataType, UA_VariableAttributes::displayName, UA_VariableAttributes::minimumSamplingInterval, UA_EXPANDEDNODEID_NUMERIC(), UA_Int32_delete(), UA_Int32_init(), UA_Int32_new(), UA_LOCALIZEDTEXT(), UA_NODECLASS_VARIABLE, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_Server_addReference(), UA_TYPES, UA_VariableAttributes_default, UA_Variant_setScalar(), UA_VariableAttributes::userAccessLevel, UA_VariableAttributes::value, and UA_VariableAttributes::valueRank.
Referenced by namespace0_generated().
function_namespace0_generated_74_finish()
static UA_StatusCode function_namespace0_generated_74_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 1815 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_75_begin()
static UA_StatusCode function_namespace0_generated_75_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 1823 of file namespace0_generated.c.
References UA_ObjectAttributes::displayName, UA_EXPANDEDNODEID_NUMERIC(), UA_LOCALIZEDTEXT(), UA_NODECLASS_OBJECT, UA_NODEID_NUMERIC(), UA_ObjectAttributes_default, UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_Server_addReference(), and UA_TYPES.
Referenced by namespace0_generated().
function_namespace0_generated_75_finish()
static UA_StatusCode function_namespace0_generated_75_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 1841 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_76_begin()
static UA_StatusCode function_namespace0_generated_76_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 1849 of file namespace0_generated.c.
References UA_VariableAttributes::accessLevel, UA_VariableAttributes::dataType, UA_VariableAttributes::displayName, UA_VariableAttributes::minimumSamplingInterval, UA_Int32_delete(), UA_Int32_init(), UA_Int32_new(), UA_LOCALIZEDTEXT(), UA_NODECLASS_VARIABLE, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_TYPES, UA_VariableAttributes_default, UA_Variant_setScalar(), UA_VariableAttributes::userAccessLevel, UA_VariableAttributes::value, and UA_VariableAttributes::valueRank.
Referenced by namespace0_generated().
function_namespace0_generated_76_finish()
static UA_StatusCode function_namespace0_generated_76_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 1875 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_77_begin()
static UA_StatusCode function_namespace0_generated_77_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 1883 of file namespace0_generated.c.
References UA_ObjectTypeAttributes::displayName, UA_LOCALIZEDTEXT(), UA_NODECLASS_OBJECTTYPE, UA_NODEID_NULL, UA_NODEID_NUMERIC(), UA_ObjectTypeAttributes_default, UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), and UA_TYPES.
Referenced by namespace0_generated().
function_namespace0_generated_77_finish()
static UA_StatusCode function_namespace0_generated_77_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 1897 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_78_begin()
static UA_StatusCode function_namespace0_generated_78_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 1905 of file namespace0_generated.c.
References UA_VariableAttributes::accessLevel, UA_VariableAttributes::dataType, UA_VariableAttributes::displayName, UA_VariableAttributes::minimumSamplingInterval, UA_EXPANDEDNODEID_NUMERIC(), UA_LOCALIZEDTEXT(), UA_NODECLASS_VARIABLE, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_Server_addReference(), UA_TYPES, UA_VariableAttributes_default, UA_VariableAttributes::userAccessLevel, and UA_VariableAttributes::valueRank.
Referenced by namespace0_generated().
function_namespace0_generated_78_finish()
static UA_StatusCode function_namespace0_generated_78_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 1926 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_79_begin()
static UA_StatusCode function_namespace0_generated_79_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 1934 of file namespace0_generated.c.
References UA_VariableTypeAttributes::dataType, UA_VariableTypeAttributes::displayName, UA_LOCALIZEDTEXT(), UA_NODECLASS_VARIABLETYPE, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_TYPES, UA_VariableTypeAttributes_default, and UA_VariableTypeAttributes::valueRank.
Referenced by namespace0_generated().
function_namespace0_generated_79_finish()
static UA_StatusCode function_namespace0_generated_79_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 1951 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_7_begin()
static UA_StatusCode function_namespace0_generated_7_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 166 of file namespace0_generated.c.
References UA_DataTypeAttributes::displayName, UA_DataTypeAttributes::isAbstract, UA_DataTypeAttributes_default, UA_LOCALIZEDTEXT(), UA_NODECLASS_DATATYPE, UA_NODEID_NULL, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), and UA_TYPES.
Referenced by namespace0_generated().
function_namespace0_generated_7_finish()
static UA_StatusCode function_namespace0_generated_7_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 181 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_80_begin()
static UA_StatusCode function_namespace0_generated_80_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 1959 of file namespace0_generated.c.
References UA_VariableTypeAttributes::dataType, UA_VariableTypeAttributes::displayName, UA_LOCALIZEDTEXT(), UA_NODECLASS_VARIABLETYPE, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_TYPES, UA_VariableTypeAttributes_default, and UA_VariableTypeAttributes::valueRank.
Referenced by namespace0_generated().
function_namespace0_generated_80_finish()
static UA_StatusCode function_namespace0_generated_80_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 1976 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_81_begin()
static UA_StatusCode function_namespace0_generated_81_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 1984 of file namespace0_generated.c.
References UA_VariableAttributes::accessLevel, UA_VariableAttributes::dataType, UA_VariableAttributes::displayName, UA_VariableAttributes::minimumSamplingInterval, UA_EXPANDEDNODEID_NUMERIC(), UA_LOCALIZEDTEXT(), UA_NODECLASS_VARIABLE, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_Server_addReference(), UA_TYPES, UA_VariableAttributes_default, UA_VariableAttributes::userAccessLevel, and UA_VariableAttributes::valueRank.
Referenced by namespace0_generated().
function_namespace0_generated_81_finish()
static UA_StatusCode function_namespace0_generated_81_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 2005 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_82_begin()
static UA_StatusCode function_namespace0_generated_82_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 2013 of file namespace0_generated.c.
References UA_VariableAttributes::accessLevel, UA_VariableAttributes::dataType, UA_VariableAttributes::displayName, UA_VariableAttributes::minimumSamplingInterval, UA_EXPANDEDNODEID_NUMERIC(), UA_LOCALIZEDTEXT(), UA_NODECLASS_VARIABLE, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_Server_addReference(), UA_TYPES, UA_VariableAttributes_default, UA_VariableAttributes::userAccessLevel, and UA_VariableAttributes::valueRank.
Referenced by namespace0_generated().
function_namespace0_generated_82_finish()
static UA_StatusCode function_namespace0_generated_82_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 2034 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_83_begin()
static UA_StatusCode function_namespace0_generated_83_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 2042 of file namespace0_generated.c.
References UA_VariableAttributes::accessLevel, UA_VariableAttributes::dataType, UA_VariableAttributes::displayName, UA_VariableAttributes::minimumSamplingInterval, UA_EXPANDEDNODEID_NUMERIC(), UA_LOCALIZEDTEXT(), UA_NODECLASS_VARIABLE, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_Server_addReference(), UA_TYPES, UA_VariableAttributes_default, UA_VariableAttributes::userAccessLevel, and UA_VariableAttributes::valueRank.
Referenced by namespace0_generated().
function_namespace0_generated_83_finish()
static UA_StatusCode function_namespace0_generated_83_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 2063 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_84_begin()
static UA_StatusCode function_namespace0_generated_84_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 2071 of file namespace0_generated.c.
References UA_VariableAttributes::accessLevel, UA_VariableAttributes::dataType, UA_VariableAttributes::displayName, UA_VariableAttributes::minimumSamplingInterval, UA_EXPANDEDNODEID_NUMERIC(), UA_LOCALIZEDTEXT(), UA_NODECLASS_VARIABLE, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_Server_addReference(), UA_TYPES, UA_VariableAttributes_default, UA_VariableAttributes::userAccessLevel, and UA_VariableAttributes::valueRank.
Referenced by namespace0_generated().
function_namespace0_generated_84_finish()
static UA_StatusCode function_namespace0_generated_84_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 2092 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_85_begin()
static UA_StatusCode function_namespace0_generated_85_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 2100 of file namespace0_generated.c.
References UA_VariableAttributes::accessLevel, UA_VariableAttributes::dataType, UA_VariableAttributes::displayName, UA_VariableAttributes::minimumSamplingInterval, UA_EXPANDEDNODEID_NUMERIC(), UA_LOCALIZEDTEXT(), UA_NODECLASS_VARIABLE, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_Server_addReference(), UA_TYPES, UA_VariableAttributes_default, UA_VariableAttributes::userAccessLevel, and UA_VariableAttributes::valueRank.
Referenced by namespace0_generated().
function_namespace0_generated_85_finish()
static UA_StatusCode function_namespace0_generated_85_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 2121 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_86_begin()
static UA_StatusCode function_namespace0_generated_86_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 2129 of file namespace0_generated.c.
References UA_VariableAttributes::accessLevel, UA_VariableAttributes::dataType, UA_VariableAttributes::displayName, UA_VariableAttributes::minimumSamplingInterval, UA_EXPANDEDNODEID_NUMERIC(), UA_LOCALIZEDTEXT(), UA_NODECLASS_VARIABLE, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_Server_addReference(), UA_TYPES, UA_VariableAttributes_default, UA_VariableAttributes::userAccessLevel, and UA_VariableAttributes::valueRank.
Referenced by namespace0_generated().
function_namespace0_generated_86_finish()
static UA_StatusCode function_namespace0_generated_86_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 2150 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_87_begin()
static UA_StatusCode function_namespace0_generated_87_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 2158 of file namespace0_generated.c.
References UA_VariableAttributes::accessLevel, UA_VariableAttributes::dataType, UA_VariableAttributes::displayName, UA_VariableAttributes::minimumSamplingInterval, UA_EXPANDEDNODEID_NUMERIC(), UA_LOCALIZEDTEXT(), UA_NODECLASS_VARIABLE, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_Server_addReference(), UA_TYPES, UA_VariableAttributes_default, UA_VariableAttributes::userAccessLevel, and UA_VariableAttributes::valueRank.
Referenced by namespace0_generated().
function_namespace0_generated_87_finish()
static UA_StatusCode function_namespace0_generated_87_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 2179 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_88_begin()
static UA_StatusCode function_namespace0_generated_88_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 2187 of file namespace0_generated.c.
References UA_VariableAttributes::accessLevel, UA_VariableAttributes::dataType, UA_VariableAttributes::displayName, UA_VariableAttributes::minimumSamplingInterval, UA_EXPANDEDNODEID_NUMERIC(), UA_LOCALIZEDTEXT(), UA_NODECLASS_VARIABLE, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_Server_addReference(), UA_TYPES, UA_VariableAttributes_default, UA_VariableAttributes::userAccessLevel, and UA_VariableAttributes::valueRank.
Referenced by namespace0_generated().
function_namespace0_generated_88_finish()
static UA_StatusCode function_namespace0_generated_88_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 2208 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_89_begin()
static UA_StatusCode function_namespace0_generated_89_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 2216 of file namespace0_generated.c.
References UA_VariableAttributes::accessLevel, UA_VariableAttributes::dataType, UA_VariableAttributes::displayName, UA_VariableAttributes::minimumSamplingInterval, UA_EXPANDEDNODEID_NUMERIC(), UA_LOCALIZEDTEXT(), UA_NODECLASS_VARIABLE, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_Server_addReference(), UA_TYPES, UA_VariableAttributes_default, UA_VariableAttributes::userAccessLevel, and UA_VariableAttributes::valueRank.
Referenced by namespace0_generated().
function_namespace0_generated_89_finish()
static UA_StatusCode function_namespace0_generated_89_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 2237 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_8_begin()
static UA_StatusCode function_namespace0_generated_8_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 189 of file namespace0_generated.c.
References UA_DataTypeAttributes::displayName, UA_DataTypeAttributes_default, UA_LOCALIZEDTEXT(), UA_NODECLASS_DATATYPE, UA_NODEID_NULL, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), and UA_TYPES.
Referenced by namespace0_generated().
function_namespace0_generated_8_finish()
static UA_StatusCode function_namespace0_generated_8_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 203 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_90_begin()
static UA_StatusCode function_namespace0_generated_90_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 2245 of file namespace0_generated.c.
References UA_VariableAttributes::accessLevel, UA_VariableAttributes::dataType, UA_VariableAttributes::displayName, UA_VariableAttributes::minimumSamplingInterval, UA_EXPANDEDNODEID_NUMERIC(), UA_LOCALIZEDTEXT(), UA_NODECLASS_VARIABLE, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_Server_addReference(), UA_TYPES, UA_VariableAttributes_default, UA_VariableAttributes::userAccessLevel, and UA_VariableAttributes::valueRank.
Referenced by namespace0_generated().
function_namespace0_generated_90_finish()
static UA_StatusCode function_namespace0_generated_90_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 2266 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_91_begin()
static UA_StatusCode function_namespace0_generated_91_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 2274 of file namespace0_generated.c.
References UA_VariableAttributes::accessLevel, UA_VariableAttributes::dataType, UA_VariableAttributes::displayName, UA_VariableAttributes::minimumSamplingInterval, UA_EXPANDEDNODEID_NUMERIC(), UA_LOCALIZEDTEXT(), UA_NODECLASS_VARIABLE, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_Server_addReference(), UA_TYPES, UA_VariableAttributes_default, UA_VariableAttributes::userAccessLevel, and UA_VariableAttributes::valueRank.
Referenced by namespace0_generated().
function_namespace0_generated_91_finish()
static UA_StatusCode function_namespace0_generated_91_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 2295 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_92_begin()
static UA_StatusCode function_namespace0_generated_92_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 2303 of file namespace0_generated.c.
References UA_VariableAttributes::accessLevel, UA_VariableAttributes::dataType, UA_VariableAttributes::displayName, UA_VariableAttributes::minimumSamplingInterval, UA_EXPANDEDNODEID_NUMERIC(), UA_LOCALIZEDTEXT(), UA_NODECLASS_VARIABLE, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_Server_addReference(), UA_TYPES, UA_VariableAttributes_default, UA_VariableAttributes::userAccessLevel, and UA_VariableAttributes::valueRank.
Referenced by namespace0_generated().
function_namespace0_generated_92_finish()
static UA_StatusCode function_namespace0_generated_92_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 2324 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_93_begin()
static UA_StatusCode function_namespace0_generated_93_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 2332 of file namespace0_generated.c.
References UA_ObjectTypeAttributes::displayName, UA_LOCALIZEDTEXT(), UA_NODECLASS_OBJECTTYPE, UA_NODEID_NULL, UA_NODEID_NUMERIC(), UA_ObjectTypeAttributes_default, UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), and UA_TYPES.
Referenced by namespace0_generated().
function_namespace0_generated_93_finish()
static UA_StatusCode function_namespace0_generated_93_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 2346 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_94_begin()
static UA_StatusCode function_namespace0_generated_94_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 2354 of file namespace0_generated.c.
References UA_ObjectAttributes::displayName, UA_ObjectAttributes::eventNotifier, UA_LOCALIZEDTEXT(), UA_NODECLASS_OBJECT, UA_NODEID_NUMERIC(), UA_ObjectAttributes_default, UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), and UA_TYPES.
Referenced by namespace0_generated().
function_namespace0_generated_94_finish()
static UA_StatusCode function_namespace0_generated_94_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 2369 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_95_begin()
static UA_StatusCode function_namespace0_generated_95_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 2377 of file namespace0_generated.c.
References UA_VariableAttributes::accessLevel, UA_VariableAttributes::dataType, UA_VariableAttributes::displayName, UA_VariableAttributes::minimumSamplingInterval, UA_LOCALIZEDTEXT(), UA_NODECLASS_VARIABLE, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_TYPES, UA_VariableAttributes_default, UA_VariableAttributes::userAccessLevel, and UA_VariableAttributes::valueRank.
Referenced by namespace0_generated().
function_namespace0_generated_95_finish()
static UA_StatusCode function_namespace0_generated_95_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 2397 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_96_begin()
static UA_StatusCode function_namespace0_generated_96_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 2405 of file namespace0_generated.c.
References UA_MethodAttributes::displayName, UA_MethodAttributes::executable, UA_LOCALIZEDTEXT(), UA_MethodAttributes_default, UA_NODECLASS_METHOD, UA_NODEID_NULL, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_TYPES, and UA_MethodAttributes::userExecutable.
Referenced by namespace0_generated().
function_namespace0_generated_96_finish()
static UA_StatusCode function_namespace0_generated_96_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 2425 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addMethodNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_97_begin()
static UA_StatusCode function_namespace0_generated_97_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 2437 of file namespace0_generated.c.
References UA_VariableAttributes::accessLevel, UA_VariableAttributes::arrayDimensions, UA_Argument::arrayDimensions, UA_VariableAttributes::arrayDimensionsSize, UA_VariableAttributes::dataType, UA_Argument::dataType, UA_VariableAttributes::displayName, UA_VariableAttributes::minimumSamplingInterval, UA_Argument::name, UA_init(), UA_LOCALIZEDTEXT(), UA_NODECLASS_VARIABLE, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_STRING(), UA_TYPES, UA_VariableAttributes_default, UA_Variant_setArray(), UA_VariableAttributes::userAccessLevel, UA_VariableAttributes::value, UA_VariableAttributes::valueRank, and UA_Argument::valueRank.
Referenced by namespace0_generated().
function_namespace0_generated_97_finish()
static UA_StatusCode function_namespace0_generated_97_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 2482 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_98_begin()
static UA_StatusCode function_namespace0_generated_98_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 2490 of file namespace0_generated.c.
References UA_VariableAttributes::accessLevel, UA_VariableAttributes::arrayDimensions, UA_VariableAttributes::arrayDimensionsSize, UA_VariableAttributes::dataType, UA_Argument::dataType, UA_VariableAttributes::displayName, UA_VariableAttributes::minimumSamplingInterval, UA_Argument::name, UA_init(), UA_LOCALIZEDTEXT(), UA_NODECLASS_VARIABLE, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_STRING(), UA_TYPES, UA_VariableAttributes_default, UA_Variant_setArray(), UA_VariableAttributes::userAccessLevel, UA_VariableAttributes::value, UA_VariableAttributes::valueRank, and UA_Argument::valueRank.
Referenced by namespace0_generated().
function_namespace0_generated_98_finish()
static UA_StatusCode function_namespace0_generated_98_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 2521 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_99_begin()
static UA_StatusCode function_namespace0_generated_99_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 2529 of file namespace0_generated.c.
References UA_VariableAttributes::accessLevel, UA_VariableAttributes::dataType, UA_VariableAttributes::displayName, UA_VariableAttributes::minimumSamplingInterval, UA_LOCALIZEDTEXT(), UA_NODECLASS_VARIABLE, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), UA_TYPES, UA_VariableAttributes_default, UA_VariableAttributes::userAccessLevel, and UA_VariableAttributes::valueRank.
Referenced by namespace0_generated().
function_namespace0_generated_99_finish()
static UA_StatusCode function_namespace0_generated_99_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 2549 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
function_namespace0_generated_9_begin()
static UA_StatusCode function_namespace0_generated_9_begin (UA_Server * server, UA_UInt16 * ns) static
Definition at line 211 of file namespace0_generated.c.
References UA_DataTypeAttributes::displayName, UA_DataTypeAttributes_default, UA_LOCALIZEDTEXT(), UA_NODECLASS_DATATYPE, UA_NODEID_NULL, UA_NODEID_NUMERIC(), UA_QUALIFIEDNAME(), UA_Server_addNode_begin(), and UA_TYPES.
Referenced by namespace0_generated().
function_namespace0_generated_9_finish()
static UA_StatusCode function_namespace0_generated_9_finish (UA_Server * server, UA_UInt16 * ns) static
Definition at line 225 of file namespace0_generated.c.
References UA_NODEID_NUMERIC(), and UA_Server_addNode_finish().
Referenced by namespace0_generated().
namespace0_generated()
UA_StatusCode namespace0_generated (UA_Server * server)
Definition at line 4352 of file namespace0_generated.c.
References function_namespace0_generated_0_begin(), function_namespace0_generated_0_finish(), function_namespace0_generated_100_begin(), function_namespace0_generated_100_finish(), function_namespace0_generated_101_begin(), function_namespace0_generated_101_finish(), function_namespace0_generated_102_begin(), function_namespace0_generated_102_finish(), function_namespace0_generated_103_begin(), function_namespace0_generated_103_finish(), function_namespace0_generated_104_begin(), function_namespace0_generated_104_finish(), function_namespace0_generated_105_begin(), function_namespace0_generated_105_finish(), function_namespace0_generated_106_begin(), function_namespace0_generated_106_finish(), function_namespace0_generated_107_begin(), function_namespace0_generated_107_finish(), function_namespace0_generated_108_begin(), function_namespace0_generated_108_finish(), function_namespace0_generated_109_begin(), function_namespace0_generated_109_finish(), function_namespace0_generated_10_begin(), function_namespace0_generated_10_finish(), function_namespace0_generated_110_begin(), function_namespace0_generated_110_finish(), function_namespace0_generated_111_begin(), function_namespace0_generated_111_finish(), function_namespace0_generated_112_begin(), function_namespace0_generated_112_finish(), function_namespace0_generated_113_begin(), function_namespace0_generated_113_finish(), function_namespace0_generated_114_begin(), function_namespace0_generated_114_finish(), function_namespace0_generated_115_begin(), function_namespace0_generated_115_finish(), function_namespace0_generated_116_begin(), function_namespace0_generated_116_finish(), function_namespace0_generated_117_begin(), function_namespace0_generated_117_finish(), function_namespace0_generated_118_begin(), function_namespace0_generated_118_finish(), function_namespace0_generated_119_begin(), function_namespace0_generated_119_finish(), function_namespace0_generated_11_begin(), function_namespace0_generated_11_finish(), function_namespace0_generated_120_begin(), function_namespace0_generated_120_finish(), function_namespace0_generated_121_begin(), function_namespace0_generated_121_finish(), function_namespace0_generated_122_begin(), function_namespace0_generated_122_finish(), function_namespace0_generated_123_begin(), function_namespace0_generated_123_finish(), function_namespace0_generated_124_begin(), function_namespace0_generated_124_finish(), function_namespace0_generated_125_begin(), function_namespace0_generated_125_finish(), function_namespace0_generated_126_begin(), function_namespace0_generated_126_finish(), function_namespace0_generated_127_begin(), function_namespace0_generated_127_finish(), function_namespace0_generated_128_begin(), function_namespace0_generated_128_finish(), function_namespace0_generated_129_begin(), function_namespace0_generated_129_finish(), function_namespace0_generated_12_begin(), function_namespace0_generated_12_finish(), function_namespace0_generated_130_begin(), function_namespace0_generated_130_finish(), function_namespace0_generated_131_begin(), function_namespace0_generated_131_finish(), function_namespace0_generated_132_begin(), function_namespace0_generated_132_finish(), function_namespace0_generated_133_begin(), function_namespace0_generated_133_finish(), function_namespace0_generated_134_begin(), function_namespace0_generated_134_finish(), function_namespace0_generated_135_begin(), function_namespace0_generated_135_finish(), function_namespace0_generated_136_begin(), function_namespace0_generated_136_finish(), function_namespace0_generated_137_begin(), function_namespace0_generated_137_finish(), function_namespace0_generated_138_begin(), function_namespace0_generated_138_finish(), function_namespace0_generated_139_begin(), function_namespace0_generated_139_finish(), function_namespace0_generated_13_begin(), function_namespace0_generated_13_finish(), function_namespace0_generated_140_begin(), function_namespace0_generated_140_finish(), function_namespace0_generated_141_begin(), function_namespace0_generated_141_finish(), function_namespace0_generated_142_begin(), function_namespace0_generated_142_finish(), function_namespace0_generated_143_begin(), function_namespace0_generated_143_finish(), function_namespace0_generated_144_begin(), function_namespace0_generated_144_finish(), function_namespace0_generated_145_begin(), function_namespace0_generated_145_finish(), function_namespace0_generated_146_begin(), function_namespace0_generated_146_finish(), function_namespace0_generated_147_begin(), function_namespace0_generated_147_finish(), function_namespace0_generated_148_begin(), function_namespace0_generated_148_finish(), function_namespace0_generated_149_begin(), function_namespace0_generated_149_finish(), function_namespace0_generated_14_begin(), function_namespace0_generated_14_finish(), function_namespace0_generated_150_begin(), function_namespace0_generated_150_finish(), function_namespace0_generated_151_begin(), function_namespace0_generated_151_finish(), function_namespace0_generated_152_begin(), function_namespace0_generated_152_finish(), function_namespace0_generated_153_begin(), function_namespace0_generated_153_finish(), function_namespace0_generated_154_begin(), function_namespace0_generated_154_finish(), function_namespace0_generated_155_begin(), function_namespace0_generated_155_finish(), function_namespace0_generated_156_begin(), function_namespace0_generated_156_finish(), function_namespace0_generated_157_begin(), function_namespace0_generated_157_finish(), function_namespace0_generated_158_begin(), function_namespace0_generated_158_finish(), function_namespace0_generated_159_begin(), function_namespace0_generated_159_finish(), function_namespace0_generated_15_begin(), function_namespace0_generated_15_finish(), function_namespace0_generated_160_begin(), function_namespace0_generated_160_finish(), function_namespace0_generated_161_begin(), function_namespace0_generated_161_finish(), function_namespace0_generated_162_begin(), function_namespace0_generated_162_finish(), function_namespace0_generated_163_begin(), function_namespace0_generated_163_finish(), function_namespace0_generated_164_begin(), function_namespace0_generated_164_finish(), function_namespace0_generated_165_begin(), function_namespace0_generated_165_finish(), function_namespace0_generated_16_begin(), function_namespace0_generated_16_finish(), function_namespace0_generated_17_begin(), function_namespace0_generated_17_finish(), function_namespace0_generated_18_begin(), function_namespace0_generated_18_finish(), function_namespace0_generated_19_begin(), function_namespace0_generated_19_finish(), function_namespace0_generated_1_begin(), function_namespace0_generated_1_finish(), function_namespace0_generated_20_begin(), function_namespace0_generated_20_finish(), function_namespace0_generated_21_begin(), function_namespace0_generated_21_finish(), function_namespace0_generated_22_begin(), function_namespace0_generated_22_finish(), function_namespace0_generated_23_begin(), function_namespace0_generated_23_finish(), function_namespace0_generated_24_begin(), function_namespace0_generated_24_finish(), function_namespace0_generated_25_begin(), function_namespace0_generated_25_finish(), function_namespace0_generated_26_begin(), function_namespace0_generated_26_finish(), function_namespace0_generated_27_begin(), function_namespace0_generated_27_finish(), function_namespace0_generated_28_begin(), function_namespace0_generated_28_finish(), function_namespace0_generated_29_begin(), function_namespace0_generated_29_finish(), function_namespace0_generated_2_begin(), function_namespace0_generated_2_finish(), function_namespace0_generated_30_begin(), function_namespace0_generated_30_finish(), function_namespace0_generated_31_begin(), function_namespace0_generated_31_finish(), function_namespace0_generated_32_begin(), function_namespace0_generated_32_finish(), function_namespace0_generated_33_begin(), function_namespace0_generated_33_finish(), function_namespace0_generated_34_begin(), function_namespace0_generated_34_finish(), function_namespace0_generated_35_begin(), function_namespace0_generated_35_finish(), function_namespace0_generated_36_begin(), function_namespace0_generated_36_finish(), function_namespace0_generated_37_begin(), function_namespace0_generated_37_finish(), function_namespace0_generated_38_begin(), function_namespace0_generated_38_finish(), function_namespace0_generated_39_begin(), function_namespace0_generated_39_finish(), function_namespace0_generated_3_begin(), function_namespace0_generated_3_finish(), function_namespace0_generated_40_begin(), function_namespace0_generated_40_finish(), function_namespace0_generated_41_begin(), function_namespace0_generated_41_finish(), function_namespace0_generated_42_begin(), function_namespace0_generated_42_finish(), function_namespace0_generated_43_begin(), function_namespace0_generated_43_finish(), function_namespace0_generated_44_begin(), function_namespace0_generated_44_finish(), function_namespace0_generated_45_begin(), function_namespace0_generated_45_finish(), function_namespace0_generated_46_begin(), function_namespace0_generated_46_finish(), function_namespace0_generated_47_begin(), function_namespace0_generated_47_finish(), function_namespace0_generated_48_begin(), function_namespace0_generated_48_finish(), function_namespace0_generated_49_begin(), function_namespace0_generated_49_finish(), function_namespace0_generated_4_begin(), function_namespace0_generated_4_finish(), function_namespace0_generated_50_begin(), function_namespace0_generated_50_finish(), function_namespace0_generated_51_begin(), function_namespace0_generated_51_finish(), function_namespace0_generated_52_begin(), function_namespace0_generated_52_finish(), function_namespace0_generated_53_begin(), function_namespace0_generated_53_finish(), function_namespace0_generated_54_begin(), function_namespace0_generated_54_finish(), function_namespace0_generated_55_begin(), function_namespace0_generated_55_finish(), function_namespace0_generated_56_begin(), function_namespace0_generated_56_finish(), function_namespace0_generated_57_begin(), function_namespace0_generated_57_finish(), function_namespace0_generated_58_begin(), function_namespace0_generated_58_finish(), function_namespace0_generated_59_begin(), function_namespace0_generated_59_finish(), function_namespace0_generated_5_begin(), function_namespace0_generated_5_finish(), function_namespace0_generated_60_begin(), function_namespace0_generated_60_finish(), function_namespace0_generated_61_begin(), function_namespace0_generated_61_finish(), function_namespace0_generated_62_begin(), function_namespace0_generated_62_finish(), function_namespace0_generated_63_begin(), function_namespace0_generated_63_finish(), function_namespace0_generated_64_begin(), function_namespace0_generated_64_finish(), function_namespace0_generated_65_begin(), function_namespace0_generated_65_finish(), function_namespace0_generated_66_begin(), function_namespace0_generated_66_finish(), function_namespace0_generated_67_begin(), function_namespace0_generated_67_finish(), function_namespace0_generated_68_begin(), function_namespace0_generated_68_finish(), function_namespace0_generated_69_begin(), function_namespace0_generated_69_finish(), function_namespace0_generated_6_begin(), function_namespace0_generated_6_finish(), function_namespace0_generated_70_begin(), function_namespace0_generated_70_finish(), function_namespace0_generated_71_begin(), function_namespace0_generated_71_finish(), function_namespace0_generated_72_begin(), function_namespace0_generated_72_finish(), function_namespace0_generated_73_begin(), function_namespace0_generated_73_finish(), function_namespace0_generated_74_begin(), function_namespace0_generated_74_finish(), function_namespace0_generated_75_begin(), function_namespace0_generated_75_finish(), function_namespace0_generated_76_begin(), function_namespace0_generated_76_finish(), function_namespace0_generated_77_begin(), function_namespace0_generated_77_finish(), function_namespace0_generated_78_begin(), function_namespace0_generated_78_finish(), function_namespace0_generated_79_begin(), function_namespace0_generated_79_finish(), function_namespace0_generated_7_begin(), function_namespace0_generated_7_finish(), function_namespace0_generated_80_begin(), function_namespace0_generated_80_finish(), function_namespace0_generated_81_begin(), function_namespace0_generated_81_finish(), function_namespace0_generated_82_begin(), function_namespace0_generated_82_finish(), function_namespace0_generated_83_begin(), function_namespace0_generated_83_finish(), function_namespace0_generated_84_begin(), function_namespace0_generated_84_finish(), function_namespace0_generated_85_begin(), function_namespace0_generated_85_finish(), function_namespace0_generated_86_begin(), function_namespace0_generated_86_finish(), function_namespace0_generated_87_begin(), function_namespace0_generated_87_finish(), function_namespace0_generated_88_begin(), function_namespace0_generated_88_finish(), function_namespace0_generated_89_begin(), function_namespace0_generated_89_finish(), function_namespace0_generated_8_begin(), function_namespace0_generated_8_finish(), function_namespace0_generated_90_begin(), function_namespace0_generated_90_finish(), function_namespace0_generated_91_begin(), function_namespace0_generated_91_finish(), function_namespace0_generated_92_begin(), function_namespace0_generated_92_finish(), function_namespace0_generated_93_begin(), function_namespace0_generated_93_finish(), function_namespace0_generated_94_begin(), function_namespace0_generated_94_finish(), function_namespace0_generated_95_begin(), function_namespace0_generated_95_finish(), function_namespace0_generated_96_begin(), function_namespace0_generated_96_finish(), function_namespace0_generated_97_begin(), function_namespace0_generated_97_finish(), function_namespace0_generated_98_begin(), function_namespace0_generated_98_finish(), function_namespace0_generated_99_begin(), function_namespace0_generated_99_finish(), function_namespace0_generated_9_begin(), function_namespace0_generated_9_finish(), nodeset_compiler.nodeset_compiler::ns, and UA_Server_addNamespace().