Project Template: Opc.Ua.CloseSessionResponse Class Reference
Opc.Ua.CloseSessionResponse Class Reference
Public Member Functions
CloseSessionResponse ()
The default constructor.
virtual void Encode (IEncoder encoder)
virtual void Decode (IDecoder decoder)
virtual bool IsEqual (IEncodeable encodeable)
virtual object Clone ()
new object MemberwiseClone ()
Properties
ResponseHeader ResponseHeader [get, set]
virtual ExpandedNodeId TypeId [get]
virtual ExpandedNodeId BinaryEncodingId [get]
virtual ExpandedNodeId XmlEncodingId [get]
Detailed Description
<exclude>
Definition at line 1007 of file Opc.Ua.Messages.cs.
Constructor & Destructor Documentation
CloseSessionResponse()
Opc.Ua.CloseSessionResponse.CloseSessionResponse () inline
The default constructor.
Definition at line 31140 of file Opc.Ua.DataTypes.cs.
Member Function Documentation
Clone()
virtual object Opc.Ua.CloseSessionResponse.Clone () inline virtual
Definition at line 31248 of file Opc.Ua.DataTypes.cs.
Decode()
virtual void Opc.Ua.CloseSessionResponse.Decode (IDecoder decoder) inline virtual
Definition at line 31217 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
Encode()
virtual void Opc.Ua.CloseSessionResponse.Encode (IEncoder encoder) inline virtual
Definition at line 31207 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
IsEqual()
virtual bool Opc.Ua.CloseSessionResponse.IsEqual (IEncodeable encodeable) inline virtual
Definition at line 31227 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Object.
MemberwiseClone()
new object Opc.Ua.CloseSessionResponse.MemberwiseClone () inline
Definition at line 31255 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.ResponseHeader.Clone(), Opc.Ua.CloseSessionResponse.MemberwiseClone(), and Opc.Ua.Namespaces.OpcUaXsd.
Referenced by Opc.Ua.CloseSessionResponse.MemberwiseClone().
Property Documentation
BinaryEncodingId
virtual ExpandedNodeId Opc.Ua.CloseSessionResponse.BinaryEncodingId get
Definition at line 31196 of file Opc.Ua.DataTypes.cs.
ResponseHeader
ResponseHeader Opc.Ua.CloseSessionResponse.ResponseHeader get set
Definition at line 31169 of file Opc.Ua.DataTypes.cs.
Referenced by Opc.Ua.CloseSessionResponseMessage.CloseSessionResponseMessage(), Opc.Ua.CloseSessionMessage.CreateResponse(), Opc.Ua.SessionClient.EndActivateSession(), Opc.Ua.SessionEndpoint.EndActivateSession(), and Opc.Ua.SessionClient.EndCloseSession().
TypeId
virtual ExpandedNodeId Opc.Ua.CloseSessionResponse.TypeId get
Definition at line 31190 of file Opc.Ua.DataTypes.cs.
XmlEncodingId
virtual ExpandedNodeId Opc.Ua.CloseSessionResponse.XmlEncodingId get
Definition at line 31202 of file Opc.Ua.DataTypes.cs.
The documentation for this class was generated from the following files:
Opc.Ua.Messages.cs
Opc.Ua.DataTypes.cs