Project Template: Opc.Ua.CloseSessionRequest Class Reference
Opc.Ua.CloseSessionRequest Class Reference
Public Member Functions
CloseSessionRequest ()
The default constructor.
virtual void Encode (IEncoder encoder)
virtual void Decode (IDecoder decoder)
virtual bool IsEqual (IEncodeable encodeable)
virtual object Clone ()
new object MemberwiseClone ()
Properties
RequestHeader RequestHeader [get, set]
bool DeleteSubscriptions [get, set]
virtual ExpandedNodeId TypeId [get]
virtual ExpandedNodeId BinaryEncodingId [get]
virtual ExpandedNodeId XmlEncodingId [get]
Detailed Description
<exclude>
Definition at line 1003 of file Opc.Ua.Messages.cs.
Constructor & Destructor Documentation
CloseSessionRequest()
Opc.Ua.CloseSessionRequest.CloseSessionRequest () inline
The default constructor.
Definition at line 30980 of file Opc.Ua.DataTypes.cs.
Member Function Documentation
Clone()
virtual object Opc.Ua.CloseSessionRequest.Clone () inline virtual
Definition at line 31100 of file Opc.Ua.DataTypes.cs.
Decode()
virtual void Opc.Ua.CloseSessionRequest.Decode (IDecoder decoder) inline virtual
Definition at line 31067 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
Encode()
virtual void Opc.Ua.CloseSessionRequest.Encode (IEncoder encoder) inline virtual
Definition at line 31056 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
IsEqual()
virtual bool Opc.Ua.CloseSessionRequest.IsEqual (IEncodeable encodeable) inline virtual
Definition at line 31078 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Object.
MemberwiseClone()
new object Opc.Ua.CloseSessionRequest.MemberwiseClone () inline
Definition at line 31107 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.RequestHeader.Clone(), Opc.Ua.CloseSessionRequest.MemberwiseClone(), and Opc.Ua.Namespaces.OpcUaXsd.
Referenced by Opc.Ua.CloseSessionRequest.MemberwiseClone().
Property Documentation
BinaryEncodingId
virtual ExpandedNodeId Opc.Ua.CloseSessionRequest.BinaryEncodingId get
Definition at line 31045 of file Opc.Ua.DataTypes.cs.
DeleteSubscriptions
bool Opc.Ua.CloseSessionRequest.DeleteSubscriptions get set
Definition at line 31030 of file Opc.Ua.DataTypes.cs.
Referenced by Opc.Ua.SessionClient.BeginCloseSession(), Opc.Ua.SessionClient.EndActivateSession(), and Opc.Ua.SessionEndpoint.EndActivateSession().
RequestHeader
RequestHeader Opc.Ua.CloseSessionRequest.RequestHeader get set
Definition at line 31010 of file Opc.Ua.DataTypes.cs.
Referenced by Opc.Ua.SessionClient.BeginCloseSession(), Opc.Ua.SessionClient.EndActivateSession(), and Opc.Ua.SessionEndpoint.EndActivateSession().
TypeId
virtual ExpandedNodeId Opc.Ua.CloseSessionRequest.TypeId get
Definition at line 31039 of file Opc.Ua.DataTypes.cs.
XmlEncodingId
virtual ExpandedNodeId Opc.Ua.CloseSessionRequest.XmlEncodingId get
Definition at line 31051 of file Opc.Ua.DataTypes.cs.
The documentation for this class was generated from the following files:
Opc.Ua.Messages.cs
Opc.Ua.DataTypes.cs