Project Template: Opc.Ua.BrowsePath Class Reference
Opc.Ua.BrowsePath Class Reference
Public Member Functions
BrowsePath ()
The default constructor.
virtual void Encode (IEncoder encoder)
virtual void Decode (IDecoder decoder)
virtual bool IsEqual (IEncodeable encodeable)
virtual object Clone ()
new object MemberwiseClone ()
Properties
NodeId StartingNode [get, set]
RelativePath RelativePath [get, set]
virtual ExpandedNodeId TypeId [get]
virtual ExpandedNodeId BinaryEncodingId [get]
virtual ExpandedNodeId XmlEncodingId [get]
Detailed Description
<exclude>
Definition at line 38907 of file Opc.Ua.DataTypes.cs.
Constructor & Destructor Documentation
BrowsePath()
Opc.Ua.BrowsePath.BrowsePath () inline
The default constructor.
Definition at line 38913 of file Opc.Ua.DataTypes.cs.
Member Function Documentation
Clone()
virtual object Opc.Ua.BrowsePath.Clone () inline virtual
Definition at line 39033 of file Opc.Ua.DataTypes.cs.
Decode()
virtual void Opc.Ua.BrowsePath.Decode (IDecoder decoder) inline virtual
Definition at line 39000 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
Encode()
virtual void Opc.Ua.BrowsePath.Encode (IEncoder encoder) inline virtual
Definition at line 38989 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
IsEqual()
virtual bool Opc.Ua.BrowsePath.IsEqual (IEncodeable encodeable) inline virtual
Definition at line 39011 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Object.
MemberwiseClone()
new object Opc.Ua.BrowsePath.MemberwiseClone () inline
Definition at line 39040 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.RelativePath.Clone(), Opc.Ua.BrowsePath.MemberwiseClone(), Opc.Ua.NodeId, and Opc.Ua.Namespaces.OpcUaXsd.
Referenced by Opc.Ua.BrowsePath.MemberwiseClone().
Property Documentation
BinaryEncodingId
virtual ExpandedNodeId Opc.Ua.BrowsePath.BinaryEncodingId get
Definition at line 38978 of file Opc.Ua.DataTypes.cs.
RelativePath
RelativePath Opc.Ua.BrowsePath.RelativePath get set
Definition at line 38951 of file Opc.Ua.DataTypes.cs.
StartingNode
NodeId Opc.Ua.BrowsePath.StartingNode get set
Definition at line 38941 of file Opc.Ua.DataTypes.cs.
TypeId
virtual ExpandedNodeId Opc.Ua.BrowsePath.TypeId get
Definition at line 38972 of file Opc.Ua.DataTypes.cs.
XmlEncodingId
virtual ExpandedNodeId Opc.Ua.BrowsePath.XmlEncodingId get
Definition at line 38984 of file Opc.Ua.DataTypes.cs.
The documentation for this class was generated from the following file:
Opc.Ua.DataTypes.cs