Project Template: Opc.Ua.OpenSecureChannelResponse Class Reference
Opc.Ua.OpenSecureChannelResponse Class Reference
Public Member Functions
OpenSecureChannelResponse ()
The default constructor.
virtual void Encode (IEncoder encoder)
virtual void Decode (IDecoder decoder)
virtual bool IsEqual (IEncodeable encodeable)
virtual object Clone ()
new object MemberwiseClone ()
Properties
ResponseHeader ResponseHeader [get, set]
uint ServerProtocolVersion [get, set]
ChannelSecurityToken SecurityToken [get, set]
byte [] ServerNonce [get, set]
virtual ExpandedNodeId TypeId [get]
virtual ExpandedNodeId BinaryEncodingId [get]
virtual ExpandedNodeId XmlEncodingId [get]
Detailed Description
<exclude>
Definition at line 579 of file Opc.Ua.Messages.cs.
Constructor & Destructor Documentation
OpenSecureChannelResponse()
Opc.Ua.OpenSecureChannelResponse.OpenSecureChannelResponse () inline
The default constructor.
Definition at line 28327 of file Opc.Ua.DataTypes.cs.
Member Function Documentation
Clone()
virtual object Opc.Ua.OpenSecureChannelResponse.Clone () inline virtual
Definition at line 28485 of file Opc.Ua.DataTypes.cs.
Decode()
virtual void Opc.Ua.OpenSecureChannelResponse.Decode (IDecoder decoder) inline virtual
Definition at line 28448 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
Encode()
virtual void Opc.Ua.OpenSecureChannelResponse.Encode (IEncoder encoder) inline virtual
Definition at line 28435 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
IsEqual()
virtual bool Opc.Ua.OpenSecureChannelResponse.IsEqual (IEncodeable encodeable) inline virtual
Definition at line 28461 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Object.
MemberwiseClone()
new object Opc.Ua.OpenSecureChannelResponse.MemberwiseClone () inline
Definition at line 28492 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.ResponseHeader.Clone(), Opc.Ua.ChannelSecurityToken.Clone(), Opc.Ua.OpenSecureChannelResponse.MemberwiseClone(), and Opc.Ua.Namespaces.OpcUaXsd.
Referenced by Opc.Ua.OpenSecureChannelResponse.MemberwiseClone().
Property Documentation
BinaryEncodingId
virtual ExpandedNodeId Opc.Ua.OpenSecureChannelResponse.BinaryEncodingId get
Definition at line 28424 of file Opc.Ua.DataTypes.cs.
ResponseHeader
ResponseHeader Opc.Ua.OpenSecureChannelResponse.ResponseHeader get set
Definition at line 28359 of file Opc.Ua.DataTypes.cs.
Referenced by Opc.Ua.OpenSecureChannelMessage.CreateResponse(), and Opc.Ua.OpenSecureChannelResponseMessage.OpenSecureChannelResponseMessage().
SecurityToken
ChannelSecurityToken Opc.Ua.OpenSecureChannelResponse.SecurityToken get set
Definition at line 28389 of file Opc.Ua.DataTypes.cs.
ServerNonce
byte [] Opc.Ua.OpenSecureChannelResponse.ServerNonce get set
Definition at line 28409 of file Opc.Ua.DataTypes.cs.
ServerProtocolVersion
uint Opc.Ua.OpenSecureChannelResponse.ServerProtocolVersion get set
Definition at line 28379 of file Opc.Ua.DataTypes.cs.
TypeId
virtual ExpandedNodeId Opc.Ua.OpenSecureChannelResponse.TypeId get
Definition at line 28418 of file Opc.Ua.DataTypes.cs.
XmlEncodingId
virtual ExpandedNodeId Opc.Ua.OpenSecureChannelResponse.XmlEncodingId get
Definition at line 28430 of file Opc.Ua.DataTypes.cs.
The documentation for this class was generated from the following files:
Opc.Ua.Messages.cs
Opc.Ua.DataTypes.cs