Project Template: nodeset_compiler.datatypes Namespace Reference
nodeset_compiler.datatypes Namespace Reference
Data Structures
class Boolean
class Byte
class ByteString
class DateTime
class DiagnosticInfo
class Double
class ExpandedNodeId
class ExtensionObject
class Float
class Guid
class Int16
class Int32
class Int64
class Integer
class LocalizedText
class NodeId
class Number
class QualifiedName
class SByte
class StatusCode
class String
class UInt16
class UInt32
class UInt64
class UInteger
class Value
class XmlElement
Functions
def unicode (s)
def getNextElementNode (xmlvalue)
def valueIsInternalType (valueTypeString)
def getXmlTextTrimmed (xmlNode)
Variables
logger = logging.getLogger(__name__)
string_types = str
Function Documentation
getNextElementNode()
def nodeset_compiler.datatypes.getNextElementNode (xmlvalue)
Definition at line 44 of file datatypes.py.
Referenced by nodeset_compiler.datatypes.Value.parseXMLEncoding().
getXmlTextTrimmed()
def nodeset_compiler.datatypes.getXmlTextTrimmed (xmlNode)
Definition at line 313 of file datatypes.py.
References nodeset_compiler.datatypes.unicode().
Referenced by nodeset_compiler.datatypes.Boolean.parseXML(), nodeset_compiler.datatypes.Number.parseXML(), nodeset_compiler.datatypes.Float.parseXML(), nodeset_compiler.datatypes.DateTime.parseXML(), and nodeset_compiler.datatypes.Guid.parseXML().
unicode()
def nodeset_compiler.datatypes.unicode (s)
Definition at line 37 of file datatypes.py.
Referenced by nodeset_compiler.datatypes.getXmlTextTrimmed(), and nodeset_compiler.datatypes.String.pack().
valueIsInternalType()
def nodeset_compiler.datatypes.valueIsInternalType (valueTypeString)
Definition at line 52 of file datatypes.py.
Referenced by nodeset_compiler.nodes.DataTypeNode.buildEncoding(), nodeset_compiler.nodeset.NodeSet.getDataTypeNode(), and nodeset_compiler.datatypes.Value.parseXMLEncoding().
Variable Documentation
logger
nodeset_compiler.datatypes.logger = logging.getLogger(__name__)
Definition at line 33 of file datatypes.py.
string_types
nodeset_compiler.datatypes.string_types = str
Definition at line 40 of file datatypes.py.