Project Template: Opc.Ua.RequestHeader Class Reference
Opc.Ua.RequestHeader Class Reference
Public Member Functions
RequestHeader ()
The default constructor.
virtual void Encode (IEncoder encoder)
virtual void Decode (IDecoder decoder)
virtual bool IsEqual (IEncodeable encodeable)
virtual object Clone ()
new object MemberwiseClone ()
Properties
NodeId AuthenticationToken [get, set]
DateTime Timestamp [get, set]
uint RequestHandle [get, set]
uint ReturnDiagnostics [get, set]
string AuditEntryId [get, set]
uint TimeoutHint [get, set]
ExtensionObject AdditionalHeader [get, set]
virtual ExpandedNodeId TypeId [get]
virtual ExpandedNodeId BinaryEncodingId [get]
virtual ExpandedNodeId XmlEncodingId [get]
Detailed Description
<exclude>
Definition at line 23432 of file Opc.Ua.DataTypes.cs.
Constructor & Destructor Documentation
RequestHeader()
Opc.Ua.RequestHeader.RequestHeader () inline
The default constructor.
Definition at line 23438 of file Opc.Ua.DataTypes.cs.
Member Function Documentation
Clone()
virtual object Opc.Ua.RequestHeader.Clone () inline virtual
Definition at line 23604 of file Opc.Ua.DataTypes.cs.
Referenced by Opc.Ua.FindServersRequest.MemberwiseClone(), Opc.Ua.FindServersOnNetworkRequest.MemberwiseClone(), Opc.Ua.GetEndpointsRequest.MemberwiseClone(), Opc.Ua.RegisterServerRequest.MemberwiseClone(), Opc.Ua.RegisterServer2Request.MemberwiseClone(), Opc.Ua.OpenSecureChannelRequest.MemberwiseClone(), Opc.Ua.CloseSecureChannelRequest.MemberwiseClone(), Opc.Ua.CreateSessionRequest.MemberwiseClone(), Opc.Ua.ActivateSessionRequest.MemberwiseClone(), Opc.Ua.CloseSessionRequest.MemberwiseClone(), Opc.Ua.CancelRequest.MemberwiseClone(), Opc.Ua.AddNodesRequest.MemberwiseClone(), Opc.Ua.AddReferencesRequest.MemberwiseClone(), Opc.Ua.DeleteNodesRequest.MemberwiseClone(), Opc.Ua.DeleteReferencesRequest.MemberwiseClone(), Opc.Ua.BrowseRequest.MemberwiseClone(), Opc.Ua.BrowseNextRequest.MemberwiseClone(), Opc.Ua.TranslateBrowsePathsToNodeIdsRequest.MemberwiseClone(), Opc.Ua.RegisterNodesRequest.MemberwiseClone(), Opc.Ua.UnregisterNodesRequest.MemberwiseClone(), Opc.Ua.QueryFirstRequest.MemberwiseClone(), Opc.Ua.QueryNextRequest.MemberwiseClone(), Opc.Ua.ReadRequest.MemberwiseClone(), Opc.Ua.HistoryReadRequest.MemberwiseClone(), Opc.Ua.WriteRequest.MemberwiseClone(), Opc.Ua.HistoryUpdateRequest.MemberwiseClone(), Opc.Ua.CallRequest.MemberwiseClone(), Opc.Ua.CreateMonitoredItemsRequest.MemberwiseClone(), Opc.Ua.ModifyMonitoredItemsRequest.MemberwiseClone(), Opc.Ua.SetMonitoringModeRequest.MemberwiseClone(), Opc.Ua.SetTriggeringRequest.MemberwiseClone(), Opc.Ua.DeleteMonitoredItemsRequest.MemberwiseClone(), Opc.Ua.CreateSubscriptionRequest.MemberwiseClone(), Opc.Ua.ModifySubscriptionRequest.MemberwiseClone(), Opc.Ua.SetPublishingModeRequest.MemberwiseClone(), Opc.Ua.PublishRequest.MemberwiseClone(), Opc.Ua.RepublishRequest.MemberwiseClone(), Opc.Ua.TransferSubscriptionsRequest.MemberwiseClone(), and Opc.Ua.DeleteSubscriptionsRequest.MemberwiseClone().
Decode()
virtual void Opc.Ua.RequestHeader.Decode (IDecoder decoder) inline virtual
Definition at line 23561 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd, and Opc.Ua.Timestamp.
Encode()
virtual void Opc.Ua.RequestHeader.Encode (IEncoder encoder) inline virtual
Definition at line 23545 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd, and Opc.Ua.Timestamp.
IsEqual()
virtual bool Opc.Ua.RequestHeader.IsEqual (IEncodeable encodeable) inline virtual
Definition at line 23577 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Object.
MemberwiseClone()
new object Opc.Ua.RequestHeader.MemberwiseClone () inline
Definition at line 23611 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.RequestHeader.MemberwiseClone(), Opc.Ua.NodeId, and Opc.Ua.Namespaces.OpcUaXsd.
Referenced by Opc.Ua.RequestHeader.MemberwiseClone().
Property Documentation
AdditionalHeader
ExtensionObject Opc.Ua.RequestHeader.AdditionalHeader get set
Definition at line 23519 of file Opc.Ua.DataTypes.cs.
AuditEntryId
string Opc.Ua.RequestHeader.AuditEntryId get set
Definition at line 23503 of file Opc.Ua.DataTypes.cs.
AuthenticationToken
NodeId Opc.Ua.RequestHeader.AuthenticationToken get set
Definition at line 23471 of file Opc.Ua.DataTypes.cs.
BinaryEncodingId
virtual ExpandedNodeId Opc.Ua.RequestHeader.BinaryEncodingId get
Definition at line 23534 of file Opc.Ua.DataTypes.cs.
RequestHandle
uint Opc.Ua.RequestHeader.RequestHandle get set
Definition at line 23487 of file Opc.Ua.DataTypes.cs.
ReturnDiagnostics
uint Opc.Ua.RequestHeader.ReturnDiagnostics get set
Definition at line 23495 of file Opc.Ua.DataTypes.cs.
TimeoutHint
uint Opc.Ua.RequestHeader.TimeoutHint get set
Definition at line 23511 of file Opc.Ua.DataTypes.cs.
Timestamp
DateTime Opc.Ua.RequestHeader.Timestamp get set
Definition at line 23479 of file Opc.Ua.DataTypes.cs.
TypeId
virtual ExpandedNodeId Opc.Ua.RequestHeader.TypeId get
Definition at line 23528 of file Opc.Ua.DataTypes.cs.
XmlEncodingId
virtual ExpandedNodeId Opc.Ua.RequestHeader.XmlEncodingId get
Definition at line 23540 of file Opc.Ua.DataTypes.cs.
The documentation for this class was generated from the following file:
Opc.Ua.DataTypes.cs