Project Template: Opc.Ua.PubSubConnectionDataType Class Reference
Opc.Ua.PubSubConnectionDataType Class Reference
Public Member Functions
PubSubConnectionDataType ()
The default constructor.
virtual void Encode (IEncoder encoder)
virtual void Decode (IDecoder decoder)
virtual bool IsEqual (IEncodeable encodeable)
virtual object Clone ()
new object MemberwiseClone ()
Properties
string Name [get, set]
bool Enabled [get, set]
Variant PublisherId [get, set]
string TransportProfileUri [get, set]
ExtensionObject Address [get, set]
KeyValuePairCollection ConnectionProperties [get, set]
ExtensionObject TransportSettings [get, set]
WriterGroupDataTypeCollection WriterGroups [get, set]
ReaderGroupDataTypeCollection ReaderGroups [get, set]
virtual ExpandedNodeId TypeId [get]
virtual ExpandedNodeId BinaryEncodingId [get]
virtual ExpandedNodeId XmlEncodingId [get]
Detailed Description
<exclude>
Definition at line 9698 of file Opc.Ua.DataTypes.cs.
Constructor & Destructor Documentation
PubSubConnectionDataType()
Opc.Ua.PubSubConnectionDataType.PubSubConnectionDataType () inline
The default constructor.
Definition at line 9704 of file Opc.Ua.DataTypes.cs.
Member Function Documentation
Clone()
virtual object Opc.Ua.PubSubConnectionDataType.Clone () inline virtual
Definition at line 9936 of file Opc.Ua.DataTypes.cs.
Decode()
virtual void Opc.Ua.PubSubConnectionDataType.Decode (IDecoder decoder) inline virtual
Definition at line 9889 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd, and Opc.Ua.PublisherId.
Encode()
virtual void Opc.Ua.PubSubConnectionDataType.Encode (IEncoder encoder) inline virtual
Definition at line 9871 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd, and Opc.Ua.PublisherId.
IsEqual()
virtual bool Opc.Ua.PubSubConnectionDataType.IsEqual (IEncodeable encodeable) inline virtual
Definition at line 9907 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Object.
MemberwiseClone()
new object Opc.Ua.PubSubConnectionDataType.MemberwiseClone () inline
Definition at line 9943 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.KeyValuePairCollection.Clone(), Opc.Ua.WriterGroupDataTypeCollection.Clone(), Opc.Ua.ReaderGroupDataTypeCollection.Clone(), Opc.Ua.PubSubConnectionDataType.MemberwiseClone(), and Opc.Ua.Namespaces.OpcUaXsd.
Referenced by Opc.Ua.PubSubConnectionDataType.MemberwiseClone().
Property Documentation
Address
ExtensionObject Opc.Ua.PubSubConnectionDataType.Address get set
Definition at line 9771 of file Opc.Ua.DataTypes.cs.
BinaryEncodingId
virtual ExpandedNodeId Opc.Ua.PubSubConnectionDataType.BinaryEncodingId get
Definition at line 9860 of file Opc.Ua.DataTypes.cs.
ConnectionProperties
KeyValuePairCollection Opc.Ua.PubSubConnectionDataType.ConnectionProperties get set
Definition at line 9781 of file Opc.Ua.DataTypes.cs.
Enabled
bool Opc.Ua.PubSubConnectionDataType.Enabled get set
Definition at line 9747 of file Opc.Ua.DataTypes.cs.
Name
string Opc.Ua.PubSubConnectionDataType.Name get set
Definition at line 9739 of file Opc.Ua.DataTypes.cs.
PublisherId
Variant Opc.Ua.PubSubConnectionDataType.PublisherId get set
Definition at line 9755 of file Opc.Ua.DataTypes.cs.
ReaderGroups
ReaderGroupDataTypeCollection Opc.Ua.PubSubConnectionDataType.ReaderGroups get set
Definition at line 9833 of file Opc.Ua.DataTypes.cs.
TransportProfileUri
string Opc.Ua.PubSubConnectionDataType.TransportProfileUri get set
Definition at line 9763 of file Opc.Ua.DataTypes.cs.
TransportSettings
ExtensionObject Opc.Ua.PubSubConnectionDataType.TransportSettings get set
Definition at line 9801 of file Opc.Ua.DataTypes.cs.
TypeId
virtual ExpandedNodeId Opc.Ua.PubSubConnectionDataType.TypeId get
Definition at line 9854 of file Opc.Ua.DataTypes.cs.
WriterGroups
WriterGroupDataTypeCollection Opc.Ua.PubSubConnectionDataType.WriterGroups get set
Definition at line 9811 of file Opc.Ua.DataTypes.cs.
XmlEncodingId
virtual ExpandedNodeId Opc.Ua.PubSubConnectionDataType.XmlEncodingId get
Definition at line 9866 of file Opc.Ua.DataTypes.cs.
The documentation for this class was generated from the following file:
Opc.Ua.DataTypes.cs