Project Template: Opc.Ua.StatusResult Class Reference
Opc.Ua.StatusResult Class Reference
Public Member Functions
StatusResult ()
The default constructor.
virtual void Encode (IEncoder encoder)
virtual void Decode (IDecoder decoder)
virtual bool IsEqual (IEncodeable encodeable)
virtual object Clone ()
new object MemberwiseClone ()
Properties
StatusCode StatusCode [get, set]
DiagnosticInfo DiagnosticInfo [get, set]
virtual ExpandedNodeId TypeId [get]
virtual ExpandedNodeId BinaryEncodingId [get]
virtual ExpandedNodeId XmlEncodingId [get]
Detailed Description
<exclude>
Definition at line 64716 of file Opc.Ua.DataTypes.cs.
Constructor & Destructor Documentation
StatusResult()
Opc.Ua.StatusResult.StatusResult () inline
The default constructor.
Definition at line 64722 of file Opc.Ua.DataTypes.cs.
Member Function Documentation
Clone()
virtual object Opc.Ua.StatusResult.Clone () inline virtual
Definition at line 64828 of file Opc.Ua.DataTypes.cs.
Referenced by Opc.Ua.ProgramDiagnosticDataType.MemberwiseClone(), and Opc.Ua.ProgramDiagnostic2DataType.MemberwiseClone().
Decode()
virtual void Opc.Ua.StatusResult.Decode (IDecoder decoder) inline virtual
Definition at line 64795 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd, and Opc.Ua.StatusCode.
Encode()
virtual void Opc.Ua.StatusResult.Encode (IEncoder encoder) inline virtual
Definition at line 64784 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd, and Opc.Ua.StatusCode.
IsEqual()
virtual bool Opc.Ua.StatusResult.IsEqual (IEncodeable encodeable) inline virtual
Definition at line 64806 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Object.
MemberwiseClone()
new object Opc.Ua.StatusResult.MemberwiseClone () inline
Definition at line 64835 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.StatusResult.MemberwiseClone(), Opc.Ua.Namespaces.OpcUaXsd, and Opc.Ua.StatusCode.
Referenced by Opc.Ua.StatusResult.MemberwiseClone().
Property Documentation
BinaryEncodingId
virtual ExpandedNodeId Opc.Ua.StatusResult.BinaryEncodingId get
Definition at line 64773 of file Opc.Ua.DataTypes.cs.
DiagnosticInfo
DiagnosticInfo Opc.Ua.StatusResult.DiagnosticInfo get set
Definition at line 64758 of file Opc.Ua.DataTypes.cs.
StatusCode
StatusCode Opc.Ua.StatusResult.StatusCode get set
Definition at line 64750 of file Opc.Ua.DataTypes.cs.
TypeId
virtual ExpandedNodeId Opc.Ua.StatusResult.TypeId get
Definition at line 64767 of file Opc.Ua.DataTypes.cs.
XmlEncodingId
virtual ExpandedNodeId Opc.Ua.StatusResult.XmlEncodingId get
Definition at line 64779 of file Opc.Ua.DataTypes.cs.
The documentation for this class was generated from the following file:
Opc.Ua.DataTypes.cs