Project Template: Opc.Ua.ServerStatusDataType Class Reference
Opc.Ua.ServerStatusDataType Class Reference
Public Member Functions
ServerStatusDataType ()
The default constructor.
virtual void Encode (IEncoder encoder)
virtual void Decode (IDecoder decoder)
virtual bool IsEqual (IEncodeable encodeable)
virtual object Clone ()
new object MemberwiseClone ()
Properties
DateTime StartTime [get, set]
DateTime CurrentTime [get, set]
ServerState State [get, set]
BuildInfo BuildInfo [get, set]
uint SecondsTillShutdown [get, set]
LocalizedText ShutdownReason [get, set]
virtual ExpandedNodeId TypeId [get]
virtual ExpandedNodeId BinaryEncodingId [get]
virtual ExpandedNodeId XmlEncodingId [get]
Detailed Description
<exclude>
Definition at line 62772 of file Opc.Ua.DataTypes.cs.
Constructor & Destructor Documentation
ServerStatusDataType()
Opc.Ua.ServerStatusDataType.ServerStatusDataType () inline
The default constructor.
Definition at line 62778 of file Opc.Ua.DataTypes.cs.
Member Function Documentation
Clone()
virtual object Opc.Ua.ServerStatusDataType.Clone () inline virtual
Definition at line 62946 of file Opc.Ua.DataTypes.cs.
Decode()
virtual void Opc.Ua.ServerStatusDataType.Decode (IDecoder decoder) inline virtual
Definition at line 62905 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
Encode()
virtual void Opc.Ua.ServerStatusDataType.Encode (IEncoder encoder) inline virtual
Definition at line 62890 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
IsEqual()
virtual bool Opc.Ua.ServerStatusDataType.IsEqual (IEncodeable encodeable) inline virtual
Definition at line 62920 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Object.
MemberwiseClone()
new object Opc.Ua.ServerStatusDataType.MemberwiseClone () inline
Definition at line 62953 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.BuildInfo.Clone(), Opc.Ua.ServerStatusDataType.MemberwiseClone(), and Opc.Ua.Namespaces.OpcUaXsd.
Referenced by Opc.Ua.ServerStatusDataType.MemberwiseClone().
Property Documentation
BinaryEncodingId
virtual ExpandedNodeId Opc.Ua.ServerStatusDataType.BinaryEncodingId get
Definition at line 62879 of file Opc.Ua.DataTypes.cs.
BuildInfo
BuildInfo Opc.Ua.ServerStatusDataType.BuildInfo get set
Definition at line 62836 of file Opc.Ua.DataTypes.cs.
CurrentTime
DateTime Opc.Ua.ServerStatusDataType.CurrentTime get set
Definition at line 62818 of file Opc.Ua.DataTypes.cs.
SecondsTillShutdown
uint Opc.Ua.ServerStatusDataType.SecondsTillShutdown get set
Definition at line 62856 of file Opc.Ua.DataTypes.cs.
ShutdownReason
LocalizedText Opc.Ua.ServerStatusDataType.ShutdownReason get set
Definition at line 62864 of file Opc.Ua.DataTypes.cs.
StartTime
DateTime Opc.Ua.ServerStatusDataType.StartTime get set
Definition at line 62810 of file Opc.Ua.DataTypes.cs.
State
ServerState Opc.Ua.ServerStatusDataType.State get set
Definition at line 62826 of file Opc.Ua.DataTypes.cs.
TypeId
virtual ExpandedNodeId Opc.Ua.ServerStatusDataType.TypeId get
Definition at line 62873 of file Opc.Ua.DataTypes.cs.
XmlEncodingId
virtual ExpandedNodeId Opc.Ua.ServerStatusDataType.XmlEncodingId get
Definition at line 62885 of file Opc.Ua.DataTypes.cs.
The documentation for this class was generated from the following file:
Opc.Ua.DataTypes.cs