Project Template: Opc.Ua.BrowseResult Class Reference
Opc.Ua.BrowseResult Class Reference
Public Member Functions
BrowseResult ()
The default constructor.
virtual void Encode (IEncoder encoder)
virtual void Decode (IDecoder decoder)
virtual bool IsEqual (IEncodeable encodeable)
virtual object Clone ()
new object MemberwiseClone ()
Properties
StatusCode StatusCode [get, set]
byte [] ContinuationPoint [get, set]
ReferenceDescriptionCollection References [get, set]
virtual ExpandedNodeId TypeId [get]
virtual ExpandedNodeId BinaryEncodingId [get]
virtual ExpandedNodeId XmlEncodingId [get]
Detailed Description
<exclude>
Definition at line 37435 of file Opc.Ua.DataTypes.cs.
Constructor & Destructor Documentation
BrowseResult()
Opc.Ua.BrowseResult.BrowseResult () inline
The default constructor.
Definition at line 37441 of file Opc.Ua.DataTypes.cs.
Member Function Documentation
Clone()
virtual object Opc.Ua.BrowseResult.Clone () inline virtual
Definition at line 37573 of file Opc.Ua.DataTypes.cs.
Decode()
virtual void Opc.Ua.BrowseResult.Decode (IDecoder decoder) inline virtual
Definition at line 37538 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd, and Opc.Ua.StatusCode.
Encode()
virtual void Opc.Ua.BrowseResult.Encode (IEncoder encoder) inline virtual
Definition at line 37526 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd, and Opc.Ua.StatusCode.
IsEqual()
virtual bool Opc.Ua.BrowseResult.IsEqual (IEncodeable encodeable) inline virtual
Definition at line 37550 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Object.
MemberwiseClone()
new object Opc.Ua.BrowseResult.MemberwiseClone () inline
Definition at line 37580 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.ReferenceDescriptionCollection.Clone(), Opc.Ua.BrowseResult.MemberwiseClone(), Opc.Ua.Namespaces.OpcUaXsd, and Opc.Ua.StatusCode.
Referenced by Opc.Ua.BrowseResult.MemberwiseClone().
Property Documentation
BinaryEncodingId
virtual ExpandedNodeId Opc.Ua.BrowseResult.BinaryEncodingId get
Definition at line 37515 of file Opc.Ua.DataTypes.cs.
ContinuationPoint
byte [] Opc.Ua.BrowseResult.ContinuationPoint get set
Definition at line 37478 of file Opc.Ua.DataTypes.cs.
References
ReferenceDescriptionCollection Opc.Ua.BrowseResult.References get set
Definition at line 37488 of file Opc.Ua.DataTypes.cs.
StatusCode
StatusCode Opc.Ua.BrowseResult.StatusCode get set
Definition at line 37470 of file Opc.Ua.DataTypes.cs.
TypeId
virtual ExpandedNodeId Opc.Ua.BrowseResult.TypeId get
Definition at line 37509 of file Opc.Ua.DataTypes.cs.
XmlEncodingId
virtual ExpandedNodeId Opc.Ua.BrowseResult.XmlEncodingId get
Definition at line 37521 of file Opc.Ua.DataTypes.cs.
The documentation for this class was generated from the following file:
Opc.Ua.DataTypes.cs