Project Template: Opc.Ua.PublishedEventsDataType Class Reference
Opc.Ua.PublishedEventsDataType Class Reference
Public Member Functions
PublishedEventsDataType ()
The default constructor.
override void Encode (IEncoder encoder)
override void Decode (IDecoder decoder)
override bool IsEqual (IEncodeable encodeable)
override object Clone ()
new object MemberwiseClone ()
Public Member Functions inherited from Opc.Ua.PublishedDataSetSourceDataType
PublishedDataSetSourceDataType ()
The default constructor.
new object MemberwiseClone ()
Properties
NodeId EventNotifier [get, set]
SimpleAttributeOperandCollection SelectedFields [get, set]
ContentFilter Filter [get, set]
override ExpandedNodeId TypeId [get]
override ExpandedNodeId BinaryEncodingId [get]
override ExpandedNodeId XmlEncodingId [get]
Properties inherited from Opc.Ua.PublishedDataSetSourceDataType
virtual ExpandedNodeId TypeId [get]
virtual ExpandedNodeId BinaryEncodingId [get]
virtual ExpandedNodeId XmlEncodingId [get]
Detailed Description
<exclude>
Definition at line 7444 of file Opc.Ua.DataTypes.cs.
Constructor & Destructor Documentation
PublishedEventsDataType()
Opc.Ua.PublishedEventsDataType.PublishedEventsDataType () inline
The default constructor.
Definition at line 7450 of file Opc.Ua.DataTypes.cs.
Member Function Documentation
Clone()
override object Opc.Ua.PublishedEventsDataType.Clone () inline virtual
Reimplemented from Opc.Ua.PublishedDataSetSourceDataType.
Definition at line 7601 of file Opc.Ua.DataTypes.cs.
Decode()
override void Opc.Ua.PublishedEventsDataType.Decode (IDecoder decoder) inline virtual
Reimplemented from Opc.Ua.PublishedDataSetSourceDataType.
Definition at line 7563 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.EventNotifier, and Opc.Ua.Namespaces.OpcUaXsd.
Encode()
override void Opc.Ua.PublishedEventsDataType.Encode (IEncoder encoder) inline virtual
Reimplemented from Opc.Ua.PublishedDataSetSourceDataType.
Definition at line 7549 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.EventNotifier, and Opc.Ua.Namespaces.OpcUaXsd.
IsEqual()
override bool Opc.Ua.PublishedEventsDataType.IsEqual (IEncodeable encodeable) inline virtual
Reimplemented from Opc.Ua.PublishedDataSetSourceDataType.
Definition at line 7577 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Object.
MemberwiseClone()
new object Opc.Ua.PublishedEventsDataType.MemberwiseClone () inline
Definition at line 7608 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.ContentFilter.Clone(), Opc.Ua.SimpleAttributeOperandCollection.Clone(), Opc.Ua.PublishedEventsDataType.MemberwiseClone(), Opc.Ua.NodeId, and Opc.Ua.Namespaces.OpcUaXsd.
Referenced by Opc.Ua.PublishedEventsDataType.MemberwiseClone().
Property Documentation
BinaryEncodingId
override ExpandedNodeId Opc.Ua.PublishedEventsDataType.BinaryEncodingId get
Definition at line 7538 of file Opc.Ua.DataTypes.cs.
EventNotifier
NodeId Opc.Ua.PublishedEventsDataType.EventNotifier get set
Definition at line 7479 of file Opc.Ua.DataTypes.cs.
Filter
ContentFilter Opc.Ua.PublishedEventsDataType.Filter get set
Definition at line 7511 of file Opc.Ua.DataTypes.cs.
SelectedFields
SimpleAttributeOperandCollection Opc.Ua.PublishedEventsDataType.SelectedFields get set
Definition at line 7489 of file Opc.Ua.DataTypes.cs.
TypeId
override ExpandedNodeId Opc.Ua.PublishedEventsDataType.TypeId get
Definition at line 7532 of file Opc.Ua.DataTypes.cs.
XmlEncodingId
override ExpandedNodeId Opc.Ua.PublishedEventsDataType.XmlEncodingId get
Definition at line 7544 of file Opc.Ua.DataTypes.cs.
The documentation for this class was generated from the following file:
Opc.Ua.DataTypes.cs