Project Template: Opc.Ua.ContentFilter Class Reference
Opc.Ua.ContentFilter Class Reference
Public Member Functions
ContentFilter ()
The default constructor.
virtual void Encode (IEncoder encoder)
virtual void Decode (IDecoder decoder)
virtual bool IsEqual (IEncodeable encodeable)
virtual object Clone ()
new object MemberwiseClone ()
Properties
ContentFilterElementCollection Elements [get, set]
virtual ExpandedNodeId TypeId [get]
virtual ExpandedNodeId BinaryEncodingId [get]
virtual ExpandedNodeId XmlEncodingId [get]
Detailed Description
<exclude>
Definition at line 42381 of file Opc.Ua.DataTypes.cs.
Constructor & Destructor Documentation
ContentFilter()
Opc.Ua.ContentFilter.ContentFilter () inline
The default constructor.
Definition at line 42387 of file Opc.Ua.DataTypes.cs.
Member Function Documentation
Clone()
virtual object Opc.Ua.ContentFilter.Clone () inline virtual
Definition at line 42495 of file Opc.Ua.DataTypes.cs.
Referenced by Opc.Ua.PublishedEventsDataType.MemberwiseClone(), Opc.Ua.QueryFirstRequest.MemberwiseClone(), and Opc.Ua.EventFilter.MemberwiseClone().
Decode()
virtual void Opc.Ua.ContentFilter.Decode (IDecoder decoder) inline virtual
Definition at line 42464 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
Encode()
virtual void Opc.Ua.ContentFilter.Encode (IEncoder encoder) inline virtual
Definition at line 42454 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
IsEqual()
virtual bool Opc.Ua.ContentFilter.IsEqual (IEncodeable encodeable) inline virtual
Definition at line 42474 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Object.
MemberwiseClone()
new object Opc.Ua.ContentFilter.MemberwiseClone () inline
Definition at line 42502 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.ContentFilterElementCollection.Clone(), Opc.Ua.ContentFilter.MemberwiseClone(), and Opc.Ua.Namespaces.OpcUaXsd.
Referenced by Opc.Ua.ContentFilter.MemberwiseClone().
Property Documentation
BinaryEncodingId
virtual ExpandedNodeId Opc.Ua.ContentFilter.BinaryEncodingId get
Definition at line 42443 of file Opc.Ua.DataTypes.cs.
Elements
ContentFilterElementCollection Opc.Ua.ContentFilter.Elements get set
Definition at line 42416 of file Opc.Ua.DataTypes.cs.
TypeId
virtual ExpandedNodeId Opc.Ua.ContentFilter.TypeId get
Definition at line 42437 of file Opc.Ua.DataTypes.cs.
XmlEncodingId
virtual ExpandedNodeId Opc.Ua.ContentFilter.XmlEncodingId get
Definition at line 42449 of file Opc.Ua.DataTypes.cs.
The documentation for this class was generated from the following file:
Opc.Ua.DataTypes.cs