Project Template: Opc.Ua.ResponseHeader Class Reference
Opc.Ua.ResponseHeader Class Reference
Public Member Functions
ResponseHeader ()
The default constructor.
virtual void Encode (IEncoder encoder)
virtual void Decode (IDecoder decoder)
virtual bool IsEqual (IEncodeable encodeable)
virtual object Clone ()
new object MemberwiseClone ()
Properties
DateTime Timestamp [get, set]
uint RequestHandle [get, set]
StatusCode ServiceResult [get, set]
DiagnosticInfo ServiceDiagnostics [get, set]
StringCollection StringTable [get, set]
ExtensionObject AdditionalHeader [get, set]
virtual ExpandedNodeId TypeId [get]
virtual ExpandedNodeId BinaryEncodingId [get]
virtual ExpandedNodeId XmlEncodingId [get]
Detailed Description
<exclude>
Definition at line 23648 of file Opc.Ua.DataTypes.cs.
Constructor & Destructor Documentation
ResponseHeader()
Opc.Ua.ResponseHeader.ResponseHeader () inline
The default constructor.
Definition at line 23654 of file Opc.Ua.DataTypes.cs.
Referenced by Opc.Ua.FindServersMessage.CreateResponse(), Opc.Ua.FindServersOnNetworkMessage.CreateResponse(), Opc.Ua.GetEndpointsMessage.CreateResponse(), Opc.Ua.RegisterServerMessage.CreateResponse(), Opc.Ua.RegisterServer2Message.CreateResponse(), Opc.Ua.OpenSecureChannelMessage.CreateResponse(), Opc.Ua.CloseSecureChannelMessage.CreateResponse(), Opc.Ua.CreateSessionMessage.CreateResponse(), Opc.Ua.ActivateSessionMessage.CreateResponse(), Opc.Ua.CloseSessionMessage.CreateResponse(), Opc.Ua.CancelMessage.CreateResponse(), Opc.Ua.AddNodesMessage.CreateResponse(), Opc.Ua.AddReferencesMessage.CreateResponse(), Opc.Ua.DeleteNodesMessage.CreateResponse(), Opc.Ua.DeleteReferencesMessage.CreateResponse(), Opc.Ua.BrowseMessage.CreateResponse(), Opc.Ua.BrowseNextMessage.CreateResponse(), Opc.Ua.TranslateBrowsePathsToNodeIdsMessage.CreateResponse(), Opc.Ua.RegisterNodesMessage.CreateResponse(), Opc.Ua.UnregisterNodesMessage.CreateResponse(), Opc.Ua.QueryFirstMessage.CreateResponse(), Opc.Ua.QueryNextMessage.CreateResponse(), Opc.Ua.ReadMessage.CreateResponse(), Opc.Ua.HistoryReadMessage.CreateResponse(), Opc.Ua.WriteMessage.CreateResponse(), Opc.Ua.HistoryUpdateMessage.CreateResponse(), Opc.Ua.CallMessage.CreateResponse(), Opc.Ua.CreateMonitoredItemsMessage.CreateResponse(), Opc.Ua.ModifyMonitoredItemsMessage.CreateResponse(), Opc.Ua.SetMonitoringModeMessage.CreateResponse(), Opc.Ua.SetTriggeringMessage.CreateResponse(), Opc.Ua.DeleteMonitoredItemsMessage.CreateResponse(), Opc.Ua.CreateSubscriptionMessage.CreateResponse(), Opc.Ua.ModifySubscriptionMessage.CreateResponse(), Opc.Ua.SetPublishingModeMessage.CreateResponse(), Opc.Ua.PublishMessage.CreateResponse(), Opc.Ua.RepublishMessage.CreateResponse(), Opc.Ua.TransferSubscriptionsMessage.CreateResponse(), and Opc.Ua.DeleteSubscriptionsMessage.CreateResponse().
Member Function Documentation
Clone()
virtual object Opc.Ua.ResponseHeader.Clone () inline virtual
Definition at line 23822 of file Opc.Ua.DataTypes.cs.
Referenced by Opc.Ua.ServiceFault.MemberwiseClone(), Opc.Ua.FindServersResponse.MemberwiseClone(), Opc.Ua.FindServersOnNetworkResponse.MemberwiseClone(), Opc.Ua.GetEndpointsResponse.MemberwiseClone(), Opc.Ua.RegisterServerResponse.MemberwiseClone(), Opc.Ua.RegisterServer2Response.MemberwiseClone(), Opc.Ua.OpenSecureChannelResponse.MemberwiseClone(), Opc.Ua.CloseSecureChannelResponse.MemberwiseClone(), Opc.Ua.CreateSessionResponse.MemberwiseClone(), Opc.Ua.ActivateSessionResponse.MemberwiseClone(), Opc.Ua.CloseSessionResponse.MemberwiseClone(), Opc.Ua.CancelResponse.MemberwiseClone(), Opc.Ua.AddNodesResponse.MemberwiseClone(), Opc.Ua.AddReferencesResponse.MemberwiseClone(), Opc.Ua.DeleteNodesResponse.MemberwiseClone(), Opc.Ua.DeleteReferencesResponse.MemberwiseClone(), Opc.Ua.BrowseResponse.MemberwiseClone(), Opc.Ua.BrowseNextResponse.MemberwiseClone(), Opc.Ua.TranslateBrowsePathsToNodeIdsResponse.MemberwiseClone(), Opc.Ua.RegisterNodesResponse.MemberwiseClone(), Opc.Ua.UnregisterNodesResponse.MemberwiseClone(), Opc.Ua.QueryFirstResponse.MemberwiseClone(), Opc.Ua.QueryNextResponse.MemberwiseClone(), Opc.Ua.ReadResponse.MemberwiseClone(), Opc.Ua.HistoryReadResponse.MemberwiseClone(), Opc.Ua.WriteResponse.MemberwiseClone(), Opc.Ua.HistoryUpdateResponse.MemberwiseClone(), Opc.Ua.CallResponse.MemberwiseClone(), Opc.Ua.CreateMonitoredItemsResponse.MemberwiseClone(), Opc.Ua.ModifyMonitoredItemsResponse.MemberwiseClone(), Opc.Ua.SetMonitoringModeResponse.MemberwiseClone(), Opc.Ua.SetTriggeringResponse.MemberwiseClone(), Opc.Ua.DeleteMonitoredItemsResponse.MemberwiseClone(), Opc.Ua.CreateSubscriptionResponse.MemberwiseClone(), Opc.Ua.ModifySubscriptionResponse.MemberwiseClone(), Opc.Ua.SetPublishingModeResponse.MemberwiseClone(), Opc.Ua.PublishResponse.MemberwiseClone(), Opc.Ua.RepublishResponse.MemberwiseClone(), Opc.Ua.TransferSubscriptionsResponse.MemberwiseClone(), and Opc.Ua.DeleteSubscriptionsResponse.MemberwiseClone().
Decode()
virtual void Opc.Ua.ResponseHeader.Decode (IDecoder decoder) inline virtual
Definition at line 23781 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd, and Opc.Ua.Timestamp.
Encode()
virtual void Opc.Ua.ResponseHeader.Encode (IEncoder encoder) inline virtual
Definition at line 23766 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd, and Opc.Ua.Timestamp.
IsEqual()
virtual bool Opc.Ua.ResponseHeader.IsEqual (IEncodeable encodeable) inline virtual
Definition at line 23796 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Object.
MemberwiseClone()
new object Opc.Ua.ResponseHeader.MemberwiseClone () inline
Definition at line 23829 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.ResponseHeader.MemberwiseClone(), Opc.Ua.Namespaces.OpcUaXsd, and Opc.Ua.StatusCode.
Referenced by Opc.Ua.ResponseHeader.MemberwiseClone().
Property Documentation
AdditionalHeader
ExtensionObject Opc.Ua.ResponseHeader.AdditionalHeader get set
Definition at line 23740 of file Opc.Ua.DataTypes.cs.
BinaryEncodingId
virtual ExpandedNodeId Opc.Ua.ResponseHeader.BinaryEncodingId get
Definition at line 23755 of file Opc.Ua.DataTypes.cs.
RequestHandle
uint Opc.Ua.ResponseHeader.RequestHandle get set
Definition at line 23694 of file Opc.Ua.DataTypes.cs.
ServiceDiagnostics
DiagnosticInfo Opc.Ua.ResponseHeader.ServiceDiagnostics get set
Definition at line 23710 of file Opc.Ua.DataTypes.cs.
ServiceResult
StatusCode Opc.Ua.ResponseHeader.ServiceResult get set
Definition at line 23702 of file Opc.Ua.DataTypes.cs.
StringTable
StringCollection Opc.Ua.ResponseHeader.StringTable get set
Definition at line 23720 of file Opc.Ua.DataTypes.cs.
Timestamp
DateTime Opc.Ua.ResponseHeader.Timestamp get set
Definition at line 23686 of file Opc.Ua.DataTypes.cs.
TypeId
virtual ExpandedNodeId Opc.Ua.ResponseHeader.TypeId get
Definition at line 23749 of file Opc.Ua.DataTypes.cs.
XmlEncodingId
virtual ExpandedNodeId Opc.Ua.ResponseHeader.XmlEncodingId get
Definition at line 23761 of file Opc.Ua.DataTypes.cs.
The documentation for this class was generated from the following file:
Opc.Ua.DataTypes.cs