Project Template: Opc.Ua.AggregateFilterResult Class Reference
Opc.Ua.AggregateFilterResult Class Reference
Public Member Functions
AggregateFilterResult ()
The default constructor.
override void Encode (IEncoder encoder)
override void Decode (IDecoder decoder)
override bool IsEqual (IEncodeable encodeable)
override object Clone ()
new object MemberwiseClone ()
Public Member Functions inherited from Opc.Ua.MonitoringFilterResult
MonitoringFilterResult ()
The default constructor.
new object MemberwiseClone ()
Properties
DateTime RevisedStartTime [get, set]
double RevisedProcessingInterval [get, set]
AggregateConfiguration RevisedAggregateConfiguration [get, set]
override ExpandedNodeId TypeId [get]
override ExpandedNodeId BinaryEncodingId [get]
override ExpandedNodeId XmlEncodingId [get]
Properties inherited from Opc.Ua.MonitoringFilterResult
virtual ExpandedNodeId TypeId [get]
virtual ExpandedNodeId BinaryEncodingId [get]
virtual ExpandedNodeId XmlEncodingId [get]
Detailed Description
<exclude>
Definition at line 52944 of file Opc.Ua.DataTypes.cs.
Constructor & Destructor Documentation
AggregateFilterResult()
Opc.Ua.AggregateFilterResult.AggregateFilterResult () inline
The default constructor.
Definition at line 52950 of file Opc.Ua.DataTypes.cs.
Member Function Documentation
Clone()
override object Opc.Ua.AggregateFilterResult.Clone () inline virtual
Reimplemented from Opc.Ua.MonitoringFilterResult.
Definition at line 53087 of file Opc.Ua.DataTypes.cs.
Decode()
override void Opc.Ua.AggregateFilterResult.Decode (IDecoder decoder) inline virtual
Reimplemented from Opc.Ua.MonitoringFilterResult.
Definition at line 53049 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
Encode()
override void Opc.Ua.AggregateFilterResult.Encode (IEncoder encoder) inline virtual
Reimplemented from Opc.Ua.MonitoringFilterResult.
Definition at line 53035 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
IsEqual()
override bool Opc.Ua.AggregateFilterResult.IsEqual (IEncodeable encodeable) inline virtual
Reimplemented from Opc.Ua.MonitoringFilterResult.
Definition at line 53063 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Object.
MemberwiseClone()
new object Opc.Ua.AggregateFilterResult.MemberwiseClone () inline
Definition at line 53094 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.AggregateConfiguration.Clone(), Opc.Ua.AggregateFilterResult.MemberwiseClone(), and Opc.Ua.Namespaces.OpcUaXsd.
Referenced by Opc.Ua.AggregateFilterResult.MemberwiseClone().
Property Documentation
BinaryEncodingId
override ExpandedNodeId Opc.Ua.AggregateFilterResult.BinaryEncodingId get
Definition at line 53024 of file Opc.Ua.DataTypes.cs.
RevisedAggregateConfiguration
AggregateConfiguration Opc.Ua.AggregateFilterResult.RevisedAggregateConfiguration get set
Definition at line 52997 of file Opc.Ua.DataTypes.cs.
RevisedProcessingInterval
double Opc.Ua.AggregateFilterResult.RevisedProcessingInterval get set
Definition at line 52987 of file Opc.Ua.DataTypes.cs.
RevisedStartTime
DateTime Opc.Ua.AggregateFilterResult.RevisedStartTime get set
Definition at line 52979 of file Opc.Ua.DataTypes.cs.
TypeId
override ExpandedNodeId Opc.Ua.AggregateFilterResult.TypeId get
Definition at line 53018 of file Opc.Ua.DataTypes.cs.
XmlEncodingId
override ExpandedNodeId Opc.Ua.AggregateFilterResult.XmlEncodingId get
Definition at line 53030 of file Opc.Ua.DataTypes.cs.
The documentation for this class was generated from the following file:
Opc.Ua.DataTypes.cs