# Pass your lists in quations, for example:
# PRINT_FILES("${file_list}")
MACRO(PRINT_FILES file_list)
    foreach(thing ${file_list})
        message(STATUS " |-- ${thing}")
    endforeach()
    message("----------------------------------------------------------------------------------------------------------------")
    message(" ")
ENDMACRO()

MACRO(PRINT_MODULE_FILES module_name sources_list includes_list)
    if(VERBOSE_FILE_INCLUSION)
        message(STATUS "${module_name} library files are:")
        message(STATUS "=====Source Files=====")
        PRINT_FILES("${sources_list}")
        message(STATUS "=====Include Files=====")
        PRINT_FILES("${includes_list}")
    endif()
ENDMACRO()