Project Template: nodeset_compiler.backend_open62541 Namespace Reference
nodeset_compiler.backend_open62541 Namespace Reference
Functions
def unicode (s)
def sortNodes (nodeset)
def generateOpen62541Code (nodeset, outfilename, internal_headers=False, typesArray=[])
Generate C Code #.
Variables
logger = logging.getLogger(__name__)
Function Documentation
generateOpen62541Code()
def nodeset_compiler.backend_open62541.generateOpen62541Code (nodeset, outfilename, internal_headers = False, typesArray = [])
Generate C Code #.
Definition at line 133 of file backend_open62541.py.
References nodeset_compiler.backend_open62541_nodes.generateNodeCode_begin(), nodeset_compiler.backend_open62541_nodes.generateNodeCode_finish(), nodeset_compiler.backend_open62541_nodes.generateReferenceCode(), nodeset_compiler.backend_open62541.sortNodes(), and nodeset_compiler.backend_open62541.unicode().
sortNodes()
def nodeset_compiler.backend_open62541.sortNodes (nodeset)
Definition at line 45 of file backend_open62541.py.
Referenced by nodeset_compiler.backend_open62541.generateOpen62541Code().
unicode()
def nodeset_compiler.backend_open62541.unicode (s)
Definition at line 34 of file backend_open62541.py.
Referenced by nodeset_compiler.backend_open62541.generateOpen62541Code().
Variable Documentation
logger
nodeset_compiler.backend_open62541.logger = logging.getLogger(__name__)
Definition at line 37 of file backend_open62541.py.