Project Template: Opc.Ua.EventFilterResult Class Reference
Opc.Ua.EventFilterResult Class Reference
Public Member Functions
EventFilterResult ()
The default constructor.
override void Encode (IEncoder encoder)
override void Decode (IDecoder decoder)
override bool IsEqual (IEncodeable encodeable)
override object Clone ()
new object MemberwiseClone ()
Public Member Functions inherited from Opc.Ua.MonitoringFilterResult
MonitoringFilterResult ()
The default constructor.
new object MemberwiseClone ()
Properties
StatusCodeCollection SelectClauseResults [get, set]
DiagnosticInfoCollection SelectClauseDiagnosticInfos [get, set]
ContentFilterResult WhereClauseResult [get, set]
override ExpandedNodeId TypeId [get]
override ExpandedNodeId BinaryEncodingId [get]
override ExpandedNodeId XmlEncodingId [get]
Properties inherited from Opc.Ua.MonitoringFilterResult
virtual ExpandedNodeId TypeId [get]
virtual ExpandedNodeId BinaryEncodingId [get]
virtual ExpandedNodeId XmlEncodingId [get]
Detailed Description
<exclude>
Definition at line 52737 of file Opc.Ua.DataTypes.cs.
Constructor & Destructor Documentation
EventFilterResult()
Opc.Ua.EventFilterResult.EventFilterResult () inline
The default constructor.
Definition at line 52743 of file Opc.Ua.DataTypes.cs.
Member Function Documentation
Clone()
override object Opc.Ua.EventFilterResult.Clone () inline virtual
Reimplemented from Opc.Ua.MonitoringFilterResult.
Definition at line 52908 of file Opc.Ua.DataTypes.cs.
Decode()
override void Opc.Ua.EventFilterResult.Decode (IDecoder decoder) inline virtual
Reimplemented from Opc.Ua.MonitoringFilterResult.
Definition at line 52870 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
Encode()
override void Opc.Ua.EventFilterResult.Encode (IEncoder encoder) inline virtual
Reimplemented from Opc.Ua.MonitoringFilterResult.
Definition at line 52856 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
IsEqual()
override bool Opc.Ua.EventFilterResult.IsEqual (IEncodeable encodeable) inline virtual
Reimplemented from Opc.Ua.MonitoringFilterResult.
Definition at line 52884 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Object.
MemberwiseClone()
new object Opc.Ua.EventFilterResult.MemberwiseClone () inline
Definition at line 52915 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.ContentFilterResult.Clone(), Opc.Ua.EventFilterResult.MemberwiseClone(), and Opc.Ua.Namespaces.OpcUaXsd.
Referenced by Opc.Ua.EventFilterResult.MemberwiseClone().
Property Documentation
BinaryEncodingId
override ExpandedNodeId Opc.Ua.EventFilterResult.BinaryEncodingId get
Definition at line 52845 of file Opc.Ua.DataTypes.cs.
SelectClauseDiagnosticInfos
DiagnosticInfoCollection Opc.Ua.EventFilterResult.SelectClauseDiagnosticInfos get set
Definition at line 52796 of file Opc.Ua.DataTypes.cs.
SelectClauseResults
StatusCodeCollection Opc.Ua.EventFilterResult.SelectClauseResults get set
Definition at line 52774 of file Opc.Ua.DataTypes.cs.
TypeId
override ExpandedNodeId Opc.Ua.EventFilterResult.TypeId get
Definition at line 52839 of file Opc.Ua.DataTypes.cs.
WhereClauseResult
ContentFilterResult Opc.Ua.EventFilterResult.WhereClauseResult get set
Definition at line 52818 of file Opc.Ua.DataTypes.cs.
XmlEncodingId
override ExpandedNodeId Opc.Ua.EventFilterResult.XmlEncodingId get
Definition at line 52851 of file Opc.Ua.DataTypes.cs.
The documentation for this class was generated from the following file:
Opc.Ua.DataTypes.cs