Project Template: Opc.Ua.Gds Namespace Reference
Opc.Ua.Gds Namespace Reference
Data Structures
class AccessTokenAuditIssuedAuditEventState
Stores an instance of the AccessTokenAuditIssuedAuditEventType ObjectType.
class ApplicationRecordDataType
class ApplicationRecordDataTypeCollection
A collection of ApplicationRecordDataType objects.
class ApplicationRegistrationChangedAuditEventState
Stores an instance of the ApplicationRegistrationChangedAuditEventType ObjectType.
class AuthorizationServiceState
Stores an instance of the AuthorizationServiceType ObjectType.
class BrowseNames
Declares all of the BrowseNames used in the Model Design.
class CertificateDeliveredAuditEventState
Stores an instance of the CertificateDeliveredAuditEventType ObjectType.
class CertificateDirectoryState
Stores an instance of the CertificateDirectoryType ObjectType.
class CertificateRequestedAuditEventState
Stores an instance of the CertificateRequestedAuditEventType ObjectType.
class DataTypeIds
A class that declares constants for all DataTypes in the Model Design.
class DataTypes
A class that declares constants for all DataTypes in the Model Design.
class DirectoryState
Stores an instance of the DirectoryType ObjectType.
class FindApplicationsMethodState
Stores an instance of the FindApplicationsMethodType Method.
class FinishRequestMethodState
Stores an instance of the FinishRequestMethodType Method.
class GetApplicationMethodState
Stores an instance of the GetApplicationMethodType Method.
class GetCertificateGroupsMethodState
Stores an instance of the GetCertificateGroupsMethodType Method.
class GetCertificateStatusMethodState
Stores an instance of the GetCertificateStatusMethodType Method.
class GetServiceDescriptionMethodState
Stores an instance of the GetServiceDescriptionMethodType Method.
class GetTrustListMethodState
Stores an instance of the GetTrustListMethodType Method.
class KeyCredentialDeliveredAuditEventState
Stores an instance of the KeyCredentialDeliveredAuditEventType ObjectType.
class KeyCredentialFinishRequestMethodState
Stores an instance of the KeyCredentialFinishRequestMethodType Method.
class KeyCredentialRequestedAuditEventState
Stores an instance of the KeyCredentialRequestedAuditEventType ObjectType.
class KeyCredentialRevokedAuditEventState
Stores an instance of the KeyCredentialRevokedAuditEventType ObjectType.
class KeyCredentialRevokeMethodState
Stores an instance of the KeyCredentialRevokeMethodType Method.
class KeyCredentialServiceState
Stores an instance of the KeyCredentialServiceType ObjectType.
class KeyCredentialStartRequestMethodState
Stores an instance of the KeyCredentialStartRequestMethodType Method.
class MethodIds
A class that declares constants for all Methods in the Model Design.
class Methods
A class that declares constants for all Methods in the Model Design.
class Namespaces
Defines constants for all namespaces referenced by the model design.
class ObjectIds
A class that declares constants for all Objects in the Model Design.
class Objects
A class that declares constants for all Objects in the Model Design.
class ObjectTypeIds
A class that declares constants for all ObjectTypes in the Model Design.
class ObjectTypes
A class that declares constants for all ObjectTypes in the Model Design.
class QueryApplicationsMethodState
Stores an instance of the QueryApplicationsMethodType Method.
class QueryServersMethodState
Stores an instance of the QueryServersMethodType Method.
class RegisterApplicationMethodState
Stores an instance of the RegisterApplicationMethodType Method.
class RequestAccessTokenMethodState
Stores an instance of the RequestAccessTokenMethodType Method.
class RevokeCertificateMethodState
Stores an instance of the RevokeCertificateMethodType Method.
class StartNewKeyPairRequestMethodState
Stores an instance of the StartNewKeyPairRequestMethodType Method.
class StartSigningRequestMethodState
Stores an instance of the StartSigningRequestMethodType Method.
class UnregisterApplicationMethodState
Stores an instance of the UnregisterApplicationMethodType Method.
class UpdateApplicationMethodState
Stores an instance of the UpdateApplicationMethodType Method.
class VariableIds
A class that declares constants for all Variables in the Model Design.
class Variables
A class that declares constants for all Variables in the Model Design.
Functions
delegate ServiceResult FindApplicationsMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, string applicationUri, ref ApplicationRecordDataType[] applications)
Used to receive notifications when the method is called.
delegate ServiceResult RegisterApplicationMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, ApplicationRecordDataType application, ref NodeId applicationId)
Used to receive notifications when the method is called.
delegate ServiceResult UpdateApplicationMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, ApplicationRecordDataType application)
Used to receive notifications when the method is called.
delegate ServiceResult UnregisterApplicationMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, NodeId applicationId)
Used to receive notifications when the method is called.
delegate ServiceResult GetApplicationMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, NodeId applicationId, ref ApplicationRecordDataType application)
Used to receive notifications when the method is called.
delegate ServiceResult QueryApplicationsMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, uint startingRecordId, uint maxRecordsToReturn, string applicationName, string applicationUri, uint applicationType, string productUri, string[] capabilities, ref DateTime lastCounterResetTime, ref uint nextRecordId, ref ApplicationDescription[] applications)
Used to receive notifications when the method is called.
delegate ServiceResult QueryServersMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, uint startingRecordId, uint maxRecordsToReturn, string applicationName, string applicationUri, string productUri, string[] serverCapabilities, ref DateTime lastCounterResetTime, ref ServerOnNetwork[] servers)
Used to receive notifications when the method is called.
delegate ServiceResult StartSigningRequestMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, NodeId applicationId, NodeId certificateGroupId, NodeId certificateTypeId, byte[] certificateRequest, ref NodeId requestId)
Used to receive notifications when the method is called.
delegate ServiceResult StartNewKeyPairRequestMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, NodeId applicationId, NodeId certificateGroupId, NodeId certificateTypeId, string subjectName, string[] domainNames, string privateKeyFormat, string privateKeyPassword, ref NodeId requestId)
Used to receive notifications when the method is called.
delegate ServiceResult FinishRequestMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, NodeId applicationId, NodeId requestId, ref byte[] certificate, ref byte[] privateKey, ref byte[][] issuerCertificates)
Used to receive notifications when the method is called.
delegate ServiceResult GetCertificateGroupsMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, NodeId applicationId, ref NodeId[] certificateGroupIds)
Used to receive notifications when the method is called.
delegate ServiceResult GetTrustListMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, NodeId applicationId, NodeId certificateGroupId, ref NodeId trustListId)
Used to receive notifications when the method is called.
delegate ServiceResult RevokeCertificateMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, NodeId applicationId, byte[] certificate)
Used to receive notifications when the method is called.
delegate ServiceResult GetCertificateStatusMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, NodeId applicationId, NodeId certificateGroupId, NodeId certificateTypeId, ref bool updateRequired)
Used to receive notifications when the method is called.
delegate ServiceResult KeyCredentialStartRequestMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, string applicationUri, byte[] publicKey, string securityPolicyUri, NodeId[] requestedRoles, ref NodeId requestId)
Used to receive notifications when the method is called.
delegate ServiceResult KeyCredentialFinishRequestMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, NodeId requestId, bool cancelRequest, ref string credentialId, ref byte[] credentialSecret, ref string certificateThumbprint, ref string securityPolicyUri, ref NodeId[] grantedRoles)
Used to receive notifications when the method is called.
delegate ServiceResult KeyCredentialRevokeMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, string credentialId)
Used to receive notifications when the method is called.
delegate ServiceResult GetServiceDescriptionMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, ref string serviceUri, ref byte[] serviceCertificate, ref UserTokenPolicy[] userTokenPolicies)
Used to receive notifications when the method is called.
delegate ServiceResult RequestAccessTokenMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, UserIdentityToken identityToken, string resourceId, ref string accessToken)
Used to receive notifications when the method is called.
Function Documentation
FindApplicationsMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.Gds.FindApplicationsMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, string applicationUri, ref ApplicationRecordDataType [] applications)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.Gds.FindApplicationsMethodState.InitializeOptionalChildren().
FinishRequestMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.Gds.FinishRequestMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, NodeId applicationId, NodeId requestId, ref byte [] certificate, ref byte [] privateKey, ref byte issuerCertificates[][])
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.Gds.FinishRequestMethodState.InitializeOptionalChildren().
GetApplicationMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.Gds.GetApplicationMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, NodeId applicationId, ref ApplicationRecordDataType application)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.Gds.GetApplicationMethodState.InitializeOptionalChildren().
GetCertificateGroupsMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.Gds.GetCertificateGroupsMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, NodeId applicationId, ref NodeId [] certificateGroupIds)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.Gds.GetCertificateGroupsMethodState.InitializeOptionalChildren().
GetCertificateStatusMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.Gds.GetCertificateStatusMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, NodeId applicationId, NodeId certificateGroupId, NodeId certificateTypeId, ref bool updateRequired)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.Gds.GetCertificateStatusMethodState.InitializeOptionalChildren().
GetServiceDescriptionMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.Gds.GetServiceDescriptionMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, ref string serviceUri, ref byte [] serviceCertificate, ref UserTokenPolicy [] userTokenPolicies)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.Gds.GetServiceDescriptionMethodState.InitializeOptionalChildren().
GetTrustListMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.Gds.GetTrustListMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, NodeId applicationId, NodeId certificateGroupId, ref NodeId trustListId)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.Gds.GetTrustListMethodState.InitializeOptionalChildren().
KeyCredentialFinishRequestMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.Gds.KeyCredentialFinishRequestMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, NodeId requestId, bool cancelRequest, ref string credentialId, ref byte [] credentialSecret, ref string certificateThumbprint, ref string securityPolicyUri, ref NodeId [] grantedRoles)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.Gds.KeyCredentialFinishRequestMethodState.InitializeOptionalChildren().
KeyCredentialRevokeMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.Gds.KeyCredentialRevokeMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, string credentialId)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.Gds.KeyCredentialRevokeMethodState.InitializeOptionalChildren().
KeyCredentialStartRequestMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.Gds.KeyCredentialStartRequestMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, string applicationUri, byte [] publicKey, string securityPolicyUri, NodeId [] requestedRoles, ref NodeId requestId)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.Gds.KeyCredentialStartRequestMethodState.InitializeOptionalChildren().
QueryApplicationsMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.Gds.QueryApplicationsMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, uint startingRecordId, uint maxRecordsToReturn, string applicationName, string applicationUri, uint applicationType, string productUri, string [] capabilities, ref DateTime lastCounterResetTime, ref uint nextRecordId, ref ApplicationDescription [] applications)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.Gds.QueryApplicationsMethodState.InitializeOptionalChildren().
QueryServersMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.Gds.QueryServersMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, uint startingRecordId, uint maxRecordsToReturn, string applicationName, string applicationUri, string productUri, string [] serverCapabilities, ref DateTime lastCounterResetTime, ref ServerOnNetwork [] servers)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.Gds.QueryServersMethodState.InitializeOptionalChildren().
RegisterApplicationMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.Gds.RegisterApplicationMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, ApplicationRecordDataType application, ref NodeId applicationId)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.Gds.RegisterApplicationMethodState.InitializeOptionalChildren().
RequestAccessTokenMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.Gds.RequestAccessTokenMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, UserIdentityToken identityToken, string resourceId, ref string accessToken)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.Gds.RequestAccessTokenMethodState.InitializeOptionalChildren().
RevokeCertificateMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.Gds.RevokeCertificateMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, NodeId applicationId, byte [] certificate)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.Gds.RevokeCertificateMethodState.InitializeOptionalChildren().
StartNewKeyPairRequestMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.Gds.StartNewKeyPairRequestMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, NodeId applicationId, NodeId certificateGroupId, NodeId certificateTypeId, string subjectName, string [] domainNames, string privateKeyFormat, string privateKeyPassword, ref NodeId requestId)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.Gds.StartNewKeyPairRequestMethodState.InitializeOptionalChildren().
StartSigningRequestMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.Gds.StartSigningRequestMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, NodeId applicationId, NodeId certificateGroupId, NodeId certificateTypeId, byte [] certificateRequest, ref NodeId requestId)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.Gds.StartSigningRequestMethodState.InitializeOptionalChildren().
UnregisterApplicationMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.Gds.UnregisterApplicationMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, NodeId applicationId)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.Gds.UnregisterApplicationMethodState.InitializeOptionalChildren().
UpdateApplicationMethodStateMethodCallHandler()
delegate ServiceResult Opc.Ua.Gds.UpdateApplicationMethodStateMethodCallHandler (ISystemContext context, MethodState method, NodeId objectId, ApplicationRecordDataType application)
Used to receive notifications when the method is called.
<exclude>
Referenced by Opc.Ua.Gds.UpdateApplicationMethodState.InitializeOptionalChildren().