Project Template: Opc.Ua.EventNotificationList Class Reference
Opc.Ua.EventNotificationList Class Reference
Public Member Functions
EventNotificationList ()
The default constructor.
override void Encode (IEncoder encoder)
override void Decode (IDecoder decoder)
override bool IsEqual (IEncodeable encodeable)
override object Clone ()
new object MemberwiseClone ()
Public Member Functions inherited from Opc.Ua.NotificationData
NotificationData ()
The default constructor.
new object MemberwiseClone ()
Properties
EventFieldListCollection Events [get, set]
override ExpandedNodeId TypeId [get]
override ExpandedNodeId BinaryEncodingId [get]
override ExpandedNodeId XmlEncodingId [get]
Properties inherited from Opc.Ua.NotificationData
virtual ExpandedNodeId TypeId [get]
virtual ExpandedNodeId BinaryEncodingId [get]
virtual ExpandedNodeId XmlEncodingId [get]
Detailed Description
<exclude>
Definition at line 58394 of file Opc.Ua.DataTypes.cs.
Constructor & Destructor Documentation
EventNotificationList()
Opc.Ua.EventNotificationList.EventNotificationList () inline
The default constructor.
Definition at line 58400 of file Opc.Ua.DataTypes.cs.
Member Function Documentation
Clone()
override object Opc.Ua.EventNotificationList.Clone () inline virtual
Reimplemented from Opc.Ua.NotificationData.
Definition at line 58513 of file Opc.Ua.DataTypes.cs.
Decode()
override void Opc.Ua.EventNotificationList.Decode (IDecoder decoder) inline virtual
Reimplemented from Opc.Ua.NotificationData.
Definition at line 58479 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
Encode()
override void Opc.Ua.EventNotificationList.Encode (IEncoder encoder) inline virtual
Reimplemented from Opc.Ua.NotificationData.
Definition at line 58467 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
IsEqual()
override bool Opc.Ua.EventNotificationList.IsEqual (IEncodeable encodeable) inline virtual
Reimplemented from Opc.Ua.NotificationData.
Definition at line 58491 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Object.
MemberwiseClone()
new object Opc.Ua.EventNotificationList.MemberwiseClone () inline
Definition at line 58520 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.EventFieldListCollection.Clone(), Opc.Ua.EventNotificationList.MemberwiseClone(), and Opc.Ua.Namespaces.OpcUaXsd.
Referenced by Opc.Ua.EventNotificationList.MemberwiseClone().
Property Documentation
BinaryEncodingId
override ExpandedNodeId Opc.Ua.EventNotificationList.BinaryEncodingId get
Definition at line 58456 of file Opc.Ua.DataTypes.cs.
Events
EventFieldListCollection Opc.Ua.EventNotificationList.Events get set
Definition at line 58429 of file Opc.Ua.DataTypes.cs.
TypeId
override ExpandedNodeId Opc.Ua.EventNotificationList.TypeId get
Definition at line 58450 of file Opc.Ua.DataTypes.cs.
XmlEncodingId
override ExpandedNodeId Opc.Ua.EventNotificationList.XmlEncodingId get
Definition at line 58462 of file Opc.Ua.DataTypes.cs.
The documentation for this class was generated from the following file:
Opc.Ua.DataTypes.cs