Project Template: Opc.Ua.ServiceCounterDataType Class Reference
Opc.Ua.ServiceCounterDataType Class Reference
Public Member Functions
ServiceCounterDataType ()
The default constructor.
virtual void Encode (IEncoder encoder)
virtual void Decode (IDecoder decoder)
virtual bool IsEqual (IEncodeable encodeable)
virtual object Clone ()
new object MemberwiseClone ()
Properties
uint TotalCount [get, set]
uint ErrorCount [get, set]
virtual ExpandedNodeId TypeId [get]
virtual ExpandedNodeId BinaryEncodingId [get]
virtual ExpandedNodeId XmlEncodingId [get]
Detailed Description
<exclude>
Definition at line 64570 of file Opc.Ua.DataTypes.cs.
Constructor & Destructor Documentation
ServiceCounterDataType()
Opc.Ua.ServiceCounterDataType.ServiceCounterDataType () inline
The default constructor.
Definition at line 64576 of file Opc.Ua.DataTypes.cs.
Member Function Documentation
Clone()
virtual object Opc.Ua.ServiceCounterDataType.Clone () inline virtual
Definition at line 64682 of file Opc.Ua.DataTypes.cs.
Referenced by Opc.Ua.SessionDiagnosticsDataType.MemberwiseClone().
Decode()
virtual void Opc.Ua.ServiceCounterDataType.Decode (IDecoder decoder) inline virtual
Definition at line 64649 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
Encode()
virtual void Opc.Ua.ServiceCounterDataType.Encode (IEncoder encoder) inline virtual
Definition at line 64638 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
IsEqual()
virtual bool Opc.Ua.ServiceCounterDataType.IsEqual (IEncodeable encodeable) inline virtual
Definition at line 64660 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Object.
MemberwiseClone()
new object Opc.Ua.ServiceCounterDataType.MemberwiseClone () inline
Definition at line 64689 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.ServiceCounterDataType.MemberwiseClone(), and Opc.Ua.Namespaces.OpcUaXsd.
Referenced by Opc.Ua.ServiceCounterDataType.MemberwiseClone().
Property Documentation
BinaryEncodingId
virtual ExpandedNodeId Opc.Ua.ServiceCounterDataType.BinaryEncodingId get
Definition at line 64627 of file Opc.Ua.DataTypes.cs.
ErrorCount
uint Opc.Ua.ServiceCounterDataType.ErrorCount get set
Definition at line 64612 of file Opc.Ua.DataTypes.cs.
TotalCount
uint Opc.Ua.ServiceCounterDataType.TotalCount get set
Definition at line 64604 of file Opc.Ua.DataTypes.cs.
TypeId
virtual ExpandedNodeId Opc.Ua.ServiceCounterDataType.TypeId get
Definition at line 64621 of file Opc.Ua.DataTypes.cs.
XmlEncodingId
virtual ExpandedNodeId Opc.Ua.ServiceCounterDataType.XmlEncodingId get
Definition at line 64633 of file Opc.Ua.DataTypes.cs.
The documentation for this class was generated from the following file:
Opc.Ua.DataTypes.cs