Project Template: Opc.Ua.HistoryEvent Class Reference
Opc.Ua.HistoryEvent Class Reference
Public Member Functions
HistoryEvent ()
The default constructor.
virtual void Encode (IEncoder encoder)
virtual void Decode (IDecoder decoder)
virtual bool IsEqual (IEncodeable encodeable)
virtual object Clone ()
new object MemberwiseClone ()
Properties
HistoryEventFieldListCollection Events [get, set]
virtual ExpandedNodeId TypeId [get]
virtual ExpandedNodeId BinaryEncodingId [get]
virtual ExpandedNodeId XmlEncodingId [get]
Detailed Description
<exclude>
Definition at line 47735 of file Opc.Ua.DataTypes.cs.
Constructor & Destructor Documentation
HistoryEvent()
Opc.Ua.HistoryEvent.HistoryEvent () inline
The default constructor.
Definition at line 47741 of file Opc.Ua.DataTypes.cs.
Member Function Documentation
Clone()
virtual object Opc.Ua.HistoryEvent.Clone () inline virtual
Definition at line 47849 of file Opc.Ua.DataTypes.cs.
Decode()
virtual void Opc.Ua.HistoryEvent.Decode (IDecoder decoder) inline virtual
Definition at line 47818 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
Encode()
virtual void Opc.Ua.HistoryEvent.Encode (IEncoder encoder) inline virtual
Definition at line 47808 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
IsEqual()
virtual bool Opc.Ua.HistoryEvent.IsEqual (IEncodeable encodeable) inline virtual
Definition at line 47828 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Object.
MemberwiseClone()
new object Opc.Ua.HistoryEvent.MemberwiseClone () inline
Definition at line 47856 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.HistoryEventFieldListCollection.Clone(), Opc.Ua.HistoryEvent.MemberwiseClone(), and Opc.Ua.Namespaces.OpcUaXsd.
Referenced by Opc.Ua.HistoryEvent.MemberwiseClone().
Property Documentation
BinaryEncodingId
virtual ExpandedNodeId Opc.Ua.HistoryEvent.BinaryEncodingId get
Definition at line 47797 of file Opc.Ua.DataTypes.cs.
Events
HistoryEventFieldListCollection Opc.Ua.HistoryEvent.Events get set
Definition at line 47770 of file Opc.Ua.DataTypes.cs.
TypeId
virtual ExpandedNodeId Opc.Ua.HistoryEvent.TypeId get
Definition at line 47791 of file Opc.Ua.DataTypes.cs.
XmlEncodingId
virtual ExpandedNodeId Opc.Ua.HistoryEvent.XmlEncodingId get
Definition at line 47803 of file Opc.Ua.DataTypes.cs.
The documentation for this class was generated from the following file:
Opc.Ua.DataTypes.cs