Project Template: Opc.Ua.EUInformation Class Reference
Opc.Ua.EUInformation Class Reference
Public Member Functions
EUInformation ()
The default constructor.
virtual void Encode (IEncoder encoder)
virtual void Decode (IDecoder decoder)
virtual bool IsEqual (IEncodeable encodeable)
virtual object Clone ()
new object MemberwiseClone ()
Properties
string NamespaceUri [get, set]
int UnitId [get, set]
LocalizedText DisplayName [get, set]
LocalizedText Description [get, set]
virtual ExpandedNodeId TypeId [get]
virtual ExpandedNodeId BinaryEncodingId [get]
virtual ExpandedNodeId XmlEncodingId [get]
Detailed Description
<exclude>
Definition at line 66239 of file Opc.Ua.DataTypes.cs.
Constructor & Destructor Documentation
EUInformation()
Opc.Ua.EUInformation.EUInformation () inline
The default constructor.
Definition at line 66245 of file Opc.Ua.DataTypes.cs.
Member Function Documentation
Clone()
virtual object Opc.Ua.EUInformation.Clone () inline virtual
Definition at line 66375 of file Opc.Ua.DataTypes.cs.
Referenced by Opc.Ua.AxisInformation.MemberwiseClone().
Decode()
virtual void Opc.Ua.EUInformation.Decode (IDecoder decoder) inline virtual
Definition at line 66338 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Description, Opc.Ua.DisplayName, and Opc.Ua.Namespaces.OpcUaXsd.
Encode()
virtual void Opc.Ua.EUInformation.Encode (IEncoder encoder) inline virtual
Definition at line 66325 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Description, Opc.Ua.DisplayName, and Opc.Ua.Namespaces.OpcUaXsd.
IsEqual()
virtual bool Opc.Ua.EUInformation.IsEqual (IEncodeable encodeable) inline virtual
Definition at line 66351 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Object.
MemberwiseClone()
new object Opc.Ua.EUInformation.MemberwiseClone () inline
Definition at line 66382 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.EUInformation.MemberwiseClone(), and Opc.Ua.Namespaces.OpcUaXsd.
Referenced by Opc.Ua.EUInformation.MemberwiseClone().
Property Documentation
BinaryEncodingId
virtual ExpandedNodeId Opc.Ua.EUInformation.BinaryEncodingId get
Definition at line 66314 of file Opc.Ua.DataTypes.cs.
Description
LocalizedText Opc.Ua.EUInformation.Description get set
Definition at line 66299 of file Opc.Ua.DataTypes.cs.
DisplayName
LocalizedText Opc.Ua.EUInformation.DisplayName get set
Definition at line 66291 of file Opc.Ua.DataTypes.cs.
NamespaceUri
string Opc.Ua.EUInformation.NamespaceUri get set
Definition at line 66275 of file Opc.Ua.DataTypes.cs.
TypeId
virtual ExpandedNodeId Opc.Ua.EUInformation.TypeId get
Definition at line 66308 of file Opc.Ua.DataTypes.cs.
UnitId
int Opc.Ua.EUInformation.UnitId get set
Definition at line 66283 of file Opc.Ua.DataTypes.cs.
XmlEncodingId
virtual ExpandedNodeId Opc.Ua.EUInformation.XmlEncodingId get
Definition at line 66320 of file Opc.Ua.DataTypes.cs.
The documentation for this class was generated from the following file:
Opc.Ua.DataTypes.cs