HaSSL: Information_Model::Device Class Reference
Information_Model::Device Class Reference abstract
This class models a Device.
#include <Device.hpp>
Public Member Functions
virtual std::shared_ptr< Information_Model::DeviceElementGroup > getDeviceElementGroup ()=0
Public Member Functions inherited from Information_Model::NamedElement
const std::string getElementName ()
const std::string getElementDescription ()
const std::string getElementRefId ()
virtual ~NamedElement ()=default
Protected Member Functions
Device (const std::string REF_ID, const std::string NAME, const std::string DESC)
Protected Member Functions inherited from Information_Model::NamedElement
NamedElement (const std::string REF_ID, const std::string NAME, const std::string DESC)
Detailed Description
This class models a Device.
It contains a single instance of Information_Model::DeviceElementGroup, which has all of the elements that this device uses.
Attention
This class should be built by Model_Factory::DeviceBuilder only!
Author
Dovydas Girdvainis
Date
18.07.2019
Constructor & Destructor Documentation
Device()
Information_Model::Device::Device (const std::string REF_ID, const std::string NAME, const std::string DESC) inline protected
References getDeviceElementGroup().
Member Function Documentation
getDeviceElementGroup()
virtual std::shared_ptr<Information_Model::DeviceElementGroup> Information_Model::Device::getDeviceElementGroup () pure virtual
Referenced by Device(), and MockDevice::MockDevice().
The documentation for this class was generated from the following file:
Device.hpp