Project Template: types_generated_handling.h File Reference
libs/include/open62541/types_generated_handling.h File Reference
Functions
static _UA_BEGIN_DECLS UA_INLINE void UA_Boolean_init (UA_Boolean *p)
static UA_INLINE UA_Boolean * UA_Boolean_new (void)
static UA_INLINE UA_StatusCode UA_Boolean_copy (const UA_Boolean *src, UA_Boolean *dst)
static UA_INLINE void UA_Boolean_deleteMembers (UA_Boolean *p)
static UA_INLINE void UA_Boolean_clear (UA_Boolean *p)
static UA_INLINE void UA_Boolean_delete (UA_Boolean *p)
static UA_INLINE void UA_SByte_init (UA_SByte *p)
static UA_INLINE UA_SByte * UA_SByte_new (void)
static UA_INLINE UA_StatusCode UA_SByte_copy (const UA_SByte *src, UA_SByte *dst)
static UA_INLINE void UA_SByte_deleteMembers (UA_SByte *p)
static UA_INLINE void UA_SByte_clear (UA_SByte *p)
static UA_INLINE void UA_SByte_delete (UA_SByte *p)
static UA_INLINE void UA_Byte_init (UA_Byte *p)
static UA_INLINE UA_Byte * UA_Byte_new (void)
static UA_INLINE UA_StatusCode UA_Byte_copy (const UA_Byte *src, UA_Byte *dst)
static UA_INLINE void UA_Byte_deleteMembers (UA_Byte *p)
static UA_INLINE void UA_Byte_clear (UA_Byte *p)
static UA_INLINE void UA_Byte_delete (UA_Byte *p)
static UA_INLINE void UA_Int16_init (UA_Int16 *p)
static UA_INLINE UA_Int16 * UA_Int16_new (void)
static UA_INLINE UA_StatusCode UA_Int16_copy (const UA_Int16 *src, UA_Int16 *dst)
static UA_INLINE void UA_Int16_deleteMembers (UA_Int16 *p)
static UA_INLINE void UA_Int16_clear (UA_Int16 *p)
static UA_INLINE void UA_Int16_delete (UA_Int16 *p)
static UA_INLINE void UA_UInt16_init (UA_UInt16 *p)
static UA_INLINE UA_UInt16 * UA_UInt16_new (void)
static UA_INLINE UA_StatusCode UA_UInt16_copy (const UA_UInt16 *src, UA_UInt16 *dst)
static UA_INLINE void UA_UInt16_deleteMembers (UA_UInt16 *p)
static UA_INLINE void UA_UInt16_clear (UA_UInt16 *p)
static UA_INLINE void UA_UInt16_delete (UA_UInt16 *p)
static UA_INLINE void UA_Int32_init (UA_Int32 *p)
static UA_INLINE UA_Int32 * UA_Int32_new (void)
static UA_INLINE UA_StatusCode UA_Int32_copy (const UA_Int32 *src, UA_Int32 *dst)
static UA_INLINE void UA_Int32_deleteMembers (UA_Int32 *p)
static UA_INLINE void UA_Int32_clear (UA_Int32 *p)
static UA_INLINE void UA_Int32_delete (UA_Int32 *p)
static UA_INLINE void UA_UInt32_init (UA_UInt32 *p)
static UA_INLINE UA_UInt32 * UA_UInt32_new (void)
static UA_INLINE UA_StatusCode UA_UInt32_copy (const UA_UInt32 *src, UA_UInt32 *dst)
static UA_INLINE void UA_UInt32_deleteMembers (UA_UInt32 *p)
static UA_INLINE void UA_UInt32_clear (UA_UInt32 *p)
static UA_INLINE void UA_UInt32_delete (UA_UInt32 *p)
static UA_INLINE void UA_Int64_init (UA_Int64 *p)
static UA_INLINE UA_Int64 * UA_Int64_new (void)
static UA_INLINE UA_StatusCode UA_Int64_copy (const UA_Int64 *src, UA_Int64 *dst)
static UA_INLINE void UA_Int64_deleteMembers (UA_Int64 *p)
static UA_INLINE void UA_Int64_clear (UA_Int64 *p)
static UA_INLINE void UA_Int64_delete (UA_Int64 *p)
static UA_INLINE void UA_UInt64_init (UA_UInt64 *p)
static UA_INLINE UA_UInt64 * UA_UInt64_new (void)
static UA_INLINE UA_StatusCode UA_UInt64_copy (const UA_UInt64 *src, UA_UInt64 *dst)
static UA_INLINE void UA_UInt64_deleteMembers (UA_UInt64 *p)
static UA_INLINE void UA_UInt64_clear (UA_UInt64 *p)
static UA_INLINE void UA_UInt64_delete (UA_UInt64 *p)
static UA_INLINE void UA_Float_init (UA_Float *p)
static UA_INLINE UA_Float * UA_Float_new (void)
static UA_INLINE UA_StatusCode UA_Float_copy (const UA_Float *src, UA_Float *dst)
static UA_INLINE void UA_Float_deleteMembers (UA_Float *p)
static UA_INLINE void UA_Float_clear (UA_Float *p)
static UA_INLINE void UA_Float_delete (UA_Float *p)
static UA_INLINE void UA_Double_init (UA_Double *p)
static UA_INLINE UA_Double * UA_Double_new (void)
static UA_INLINE UA_StatusCode UA_Double_copy (const UA_Double *src, UA_Double *dst)
static UA_INLINE void UA_Double_deleteMembers (UA_Double *p)
static UA_INLINE void UA_Double_clear (UA_Double *p)
static UA_INLINE void UA_Double_delete (UA_Double *p)
static UA_INLINE void UA_String_init (UA_String *p)
static UA_INLINE UA_String * UA_String_new (void)
static UA_INLINE UA_StatusCode UA_String_copy (const UA_String *src, UA_String *dst)
static UA_INLINE void UA_String_deleteMembers (UA_String *p)
static UA_INLINE void UA_String_clear (UA_String *p)
static UA_INLINE void UA_String_delete (UA_String *p)
static UA_INLINE void UA_DateTime_init (UA_DateTime *p)
static UA_INLINE UA_DateTime * UA_DateTime_new (void)
static UA_INLINE UA_StatusCode UA_DateTime_copy (const UA_DateTime *src, UA_DateTime *dst)
static UA_INLINE void UA_DateTime_deleteMembers (UA_DateTime *p)
static UA_INLINE void UA_DateTime_clear (UA_DateTime *p)
static UA_INLINE void UA_DateTime_delete (UA_DateTime *p)
static UA_INLINE void UA_Guid_init (UA_Guid *p)
static UA_INLINE UA_Guid * UA_Guid_new (void)
static UA_INLINE UA_StatusCode UA_Guid_copy (const UA_Guid *src, UA_Guid *dst)
static UA_INLINE void UA_Guid_deleteMembers (UA_Guid *p)
static UA_INLINE void UA_Guid_clear (UA_Guid *p)
static UA_INLINE void UA_Guid_delete (UA_Guid *p)
static UA_INLINE void UA_ByteString_init (UA_ByteString *p)
static UA_INLINE UA_ByteString * UA_ByteString_new (void)
static UA_INLINE UA_StatusCode UA_ByteString_copy (const UA_ByteString *src, UA_ByteString *dst)
static UA_INLINE void UA_ByteString_deleteMembers (UA_ByteString *p)
static UA_INLINE void UA_ByteString_clear (UA_ByteString *p)
static UA_INLINE void UA_ByteString_delete (UA_ByteString *p)
static UA_INLINE void UA_XmlElement_init (UA_XmlElement *p)
static UA_INLINE UA_XmlElement * UA_XmlElement_new (void)
static UA_INLINE UA_StatusCode UA_XmlElement_copy (const UA_XmlElement *src, UA_XmlElement *dst)
static UA_INLINE void UA_XmlElement_deleteMembers (UA_XmlElement *p)
static UA_INLINE void UA_XmlElement_clear (UA_XmlElement *p)
static UA_INLINE void UA_XmlElement_delete (UA_XmlElement *p)
static UA_INLINE void UA_NodeId_init (UA_NodeId *p)
static UA_INLINE UA_NodeId * UA_NodeId_new (void)
static UA_INLINE UA_StatusCode UA_NodeId_copy (const UA_NodeId *src, UA_NodeId *dst)
static UA_INLINE void UA_NodeId_deleteMembers (UA_NodeId *p)
static UA_INLINE void UA_NodeId_clear (UA_NodeId *p)
static UA_INLINE void UA_NodeId_delete (UA_NodeId *p)
static UA_INLINE void UA_ExpandedNodeId_init (UA_ExpandedNodeId *p)
static UA_INLINE UA_ExpandedNodeId * UA_ExpandedNodeId_new (void)
static UA_INLINE UA_StatusCode UA_ExpandedNodeId_copy (const UA_ExpandedNodeId *src, UA_ExpandedNodeId *dst)
static UA_INLINE void UA_ExpandedNodeId_deleteMembers (UA_ExpandedNodeId *p)
static UA_INLINE void UA_ExpandedNodeId_clear (UA_ExpandedNodeId *p)
static UA_INLINE void UA_ExpandedNodeId_delete (UA_ExpandedNodeId *p)
static UA_INLINE void UA_StatusCode_init (UA_StatusCode *p)
static UA_INLINE UA_StatusCode * UA_StatusCode_new (void)
static UA_INLINE UA_StatusCode UA_StatusCode_copy (const UA_StatusCode *src, UA_StatusCode *dst)
static UA_INLINE void UA_StatusCode_deleteMembers (UA_StatusCode *p)
static UA_INLINE void UA_StatusCode_clear (UA_StatusCode *p)
static UA_INLINE void UA_StatusCode_delete (UA_StatusCode *p)
static UA_INLINE void UA_QualifiedName_init (UA_QualifiedName *p)
static UA_INLINE UA_QualifiedName * UA_QualifiedName_new (void)
static UA_INLINE UA_StatusCode UA_QualifiedName_copy (const UA_QualifiedName *src, UA_QualifiedName *dst)
static UA_INLINE void UA_QualifiedName_deleteMembers (UA_QualifiedName *p)
static UA_INLINE void UA_QualifiedName_clear (UA_QualifiedName *p)
static UA_INLINE void UA_QualifiedName_delete (UA_QualifiedName *p)
static UA_INLINE void UA_LocalizedText_init (UA_LocalizedText *p)
static UA_INLINE UA_LocalizedText * UA_LocalizedText_new (void)
static UA_INLINE UA_StatusCode UA_LocalizedText_copy (const UA_LocalizedText *src, UA_LocalizedText *dst)
static UA_INLINE void UA_LocalizedText_deleteMembers (UA_LocalizedText *p)
static UA_INLINE void UA_LocalizedText_clear (UA_LocalizedText *p)
static UA_INLINE void UA_LocalizedText_delete (UA_LocalizedText *p)
static UA_INLINE void UA_ExtensionObject_init (UA_ExtensionObject *p)
static UA_INLINE UA_ExtensionObject * UA_ExtensionObject_new (void)
static UA_INLINE UA_StatusCode UA_ExtensionObject_copy (const UA_ExtensionObject *src, UA_ExtensionObject *dst)
static UA_INLINE void UA_ExtensionObject_deleteMembers (UA_ExtensionObject *p)
static UA_INLINE void UA_ExtensionObject_clear (UA_ExtensionObject *p)
static UA_INLINE void UA_ExtensionObject_delete (UA_ExtensionObject *p)
static UA_INLINE void UA_DataValue_init (UA_DataValue *p)
static UA_INLINE UA_DataValue * UA_DataValue_new (void)
static UA_INLINE UA_StatusCode UA_DataValue_copy (const UA_DataValue *src, UA_DataValue *dst)
static UA_INLINE void UA_DataValue_deleteMembers (UA_DataValue *p)
static UA_INLINE void UA_DataValue_clear (UA_DataValue *p)
static UA_INLINE void UA_DataValue_delete (UA_DataValue *p)
static UA_INLINE void UA_Variant_init (UA_Variant *p)
static UA_INLINE UA_Variant * UA_Variant_new (void)
static UA_INLINE UA_StatusCode UA_Variant_copy (const UA_Variant *src, UA_Variant *dst)
static UA_INLINE void UA_Variant_deleteMembers (UA_Variant *p)
static UA_INLINE void UA_Variant_clear (UA_Variant *p)
static UA_INLINE void UA_Variant_delete (UA_Variant *p)
static UA_INLINE void UA_DiagnosticInfo_init (UA_DiagnosticInfo *p)
static UA_INLINE UA_DiagnosticInfo * UA_DiagnosticInfo_new (void)
static UA_INLINE UA_StatusCode UA_DiagnosticInfo_copy (const UA_DiagnosticInfo *src, UA_DiagnosticInfo *dst)
static UA_INLINE void UA_DiagnosticInfo_deleteMembers (UA_DiagnosticInfo *p)
static UA_INLINE void UA_DiagnosticInfo_clear (UA_DiagnosticInfo *p)
static UA_INLINE void UA_DiagnosticInfo_delete (UA_DiagnosticInfo *p)
static UA_INLINE void UA_ViewAttributes_init (UA_ViewAttributes *p)
static UA_INLINE UA_ViewAttributes * UA_ViewAttributes_new (void)
static UA_INLINE UA_StatusCode UA_ViewAttributes_copy (const UA_ViewAttributes *src, UA_ViewAttributes *dst)
static UA_INLINE void UA_ViewAttributes_deleteMembers (UA_ViewAttributes *p)
static UA_INLINE void UA_ViewAttributes_clear (UA_ViewAttributes *p)
static UA_INLINE void UA_ViewAttributes_delete (UA_ViewAttributes *p)
static UA_INLINE void UA_ElementOperand_init (UA_ElementOperand *p)
static UA_INLINE UA_ElementOperand * UA_ElementOperand_new (void)
static UA_INLINE UA_StatusCode UA_ElementOperand_copy (const UA_ElementOperand *src, UA_ElementOperand *dst)
static UA_INLINE void UA_ElementOperand_deleteMembers (UA_ElementOperand *p)
static UA_INLINE void UA_ElementOperand_clear (UA_ElementOperand *p)
static UA_INLINE void UA_ElementOperand_delete (UA_ElementOperand *p)
static UA_INLINE void UA_VariableAttributes_init (UA_VariableAttributes *p)
static UA_INLINE UA_VariableAttributes * UA_VariableAttributes_new (void)
static UA_INLINE UA_StatusCode UA_VariableAttributes_copy (const UA_VariableAttributes *src, UA_VariableAttributes *dst)
static UA_INLINE void UA_VariableAttributes_deleteMembers (UA_VariableAttributes *p)
static UA_INLINE void UA_VariableAttributes_clear (UA_VariableAttributes *p)
static UA_INLINE void UA_VariableAttributes_delete (UA_VariableAttributes *p)
static UA_INLINE void UA_EnumValueType_init (UA_EnumValueType *p)
static UA_INLINE UA_EnumValueType * UA_EnumValueType_new (void)
static UA_INLINE UA_StatusCode UA_EnumValueType_copy (const UA_EnumValueType *src, UA_EnumValueType *dst)
static UA_INLINE void UA_EnumValueType_deleteMembers (UA_EnumValueType *p)
static UA_INLINE void UA_EnumValueType_clear (UA_EnumValueType *p)
static UA_INLINE void UA_EnumValueType_delete (UA_EnumValueType *p)
static UA_INLINE void UA_EventFieldList_init (UA_EventFieldList *p)
static UA_INLINE UA_EventFieldList * UA_EventFieldList_new (void)
static UA_INLINE UA_StatusCode UA_EventFieldList_copy (const UA_EventFieldList *src, UA_EventFieldList *dst)
static UA_INLINE void UA_EventFieldList_deleteMembers (UA_EventFieldList *p)
static UA_INLINE void UA_EventFieldList_clear (UA_EventFieldList *p)
static UA_INLINE void UA_EventFieldList_delete (UA_EventFieldList *p)
static UA_INLINE void UA_MonitoredItemCreateResult_init (UA_MonitoredItemCreateResult *p)
static UA_INLINE UA_MonitoredItemCreateResult * UA_MonitoredItemCreateResult_new (void)
static UA_INLINE UA_StatusCode UA_MonitoredItemCreateResult_copy (const UA_MonitoredItemCreateResult *src, UA_MonitoredItemCreateResult *dst)
static UA_INLINE void UA_MonitoredItemCreateResult_deleteMembers (UA_MonitoredItemCreateResult *p)
static UA_INLINE void UA_MonitoredItemCreateResult_clear (UA_MonitoredItemCreateResult *p)
static UA_INLINE void UA_MonitoredItemCreateResult_delete (UA_MonitoredItemCreateResult *p)
static UA_INLINE void UA_ServerDiagnosticsSummaryDataType_init (UA_ServerDiagnosticsSummaryDataType *p)
static UA_INLINE UA_ServerDiagnosticsSummaryDataType * UA_ServerDiagnosticsSummaryDataType_new (void)
static UA_INLINE UA_StatusCode UA_ServerDiagnosticsSummaryDataType_copy (const UA_ServerDiagnosticsSummaryDataType *src, UA_ServerDiagnosticsSummaryDataType *dst)
static UA_INLINE void UA_ServerDiagnosticsSummaryDataType_deleteMembers (UA_ServerDiagnosticsSummaryDataType *p)
static UA_INLINE void UA_ServerDiagnosticsSummaryDataType_clear (UA_ServerDiagnosticsSummaryDataType *p)
static UA_INLINE void UA_ServerDiagnosticsSummaryDataType_delete (UA_ServerDiagnosticsSummaryDataType *p)
static UA_INLINE void UA_ContentFilterElementResult_init (UA_ContentFilterElementResult *p)
static UA_INLINE UA_ContentFilterElementResult * UA_ContentFilterElementResult_new (void)
static UA_INLINE UA_StatusCode UA_ContentFilterElementResult_copy (const UA_ContentFilterElementResult *src, UA_ContentFilterElementResult *dst)
static UA_INLINE void UA_ContentFilterElementResult_deleteMembers (UA_ContentFilterElementResult *p)
static UA_INLINE void UA_ContentFilterElementResult_clear (UA_ContentFilterElementResult *p)
static UA_INLINE void UA_ContentFilterElementResult_delete (UA_ContentFilterElementResult *p)
static UA_INLINE void UA_LiteralOperand_init (UA_LiteralOperand *p)
static UA_INLINE UA_LiteralOperand * UA_LiteralOperand_new (void)
static UA_INLINE UA_StatusCode UA_LiteralOperand_copy (const UA_LiteralOperand *src, UA_LiteralOperand *dst)
static UA_INLINE void UA_LiteralOperand_deleteMembers (UA_LiteralOperand *p)
static UA_INLINE void UA_LiteralOperand_clear (UA_LiteralOperand *p)
static UA_INLINE void UA_LiteralOperand_delete (UA_LiteralOperand *p)
static UA_INLINE void UA_MessageSecurityMode_init (UA_MessageSecurityMode *p)
static UA_INLINE UA_MessageSecurityMode * UA_MessageSecurityMode_new (void)
static UA_INLINE UA_StatusCode UA_MessageSecurityMode_copy (const UA_MessageSecurityMode *src, UA_MessageSecurityMode *dst)
static UA_INLINE void UA_MessageSecurityMode_deleteMembers (UA_MessageSecurityMode *p)
static UA_INLINE void UA_MessageSecurityMode_clear (UA_MessageSecurityMode *p)
static UA_INLINE void UA_MessageSecurityMode_delete (UA_MessageSecurityMode *p)
static UA_INLINE void UA_UtcTime_init (UA_UtcTime *p)
static UA_INLINE UA_UtcTime * UA_UtcTime_new (void)
static UA_INLINE UA_StatusCode UA_UtcTime_copy (const UA_UtcTime *src, UA_UtcTime *dst)
static UA_INLINE void UA_UtcTime_deleteMembers (UA_UtcTime *p)
static UA_INLINE void UA_UtcTime_clear (UA_UtcTime *p)
static UA_INLINE void UA_UtcTime_delete (UA_UtcTime *p)
static UA_INLINE void UA_UserIdentityToken_init (UA_UserIdentityToken *p)
static UA_INLINE UA_UserIdentityToken * UA_UserIdentityToken_new (void)
static UA_INLINE UA_StatusCode UA_UserIdentityToken_copy (const UA_UserIdentityToken *src, UA_UserIdentityToken *dst)
static UA_INLINE void UA_UserIdentityToken_deleteMembers (UA_UserIdentityToken *p)
static UA_INLINE void UA_UserIdentityToken_clear (UA_UserIdentityToken *p)
static UA_INLINE void UA_UserIdentityToken_delete (UA_UserIdentityToken *p)
static UA_INLINE void UA_X509IdentityToken_init (UA_X509IdentityToken *p)
static UA_INLINE UA_X509IdentityToken * UA_X509IdentityToken_new (void)
static UA_INLINE UA_StatusCode UA_X509IdentityToken_copy (const UA_X509IdentityToken *src, UA_X509IdentityToken *dst)
static UA_INLINE void UA_X509IdentityToken_deleteMembers (UA_X509IdentityToken *p)
static UA_INLINE void UA_X509IdentityToken_clear (UA_X509IdentityToken *p)
static UA_INLINE void UA_X509IdentityToken_delete (UA_X509IdentityToken *p)
static UA_INLINE void UA_MonitoredItemNotification_init (UA_MonitoredItemNotification *p)
static UA_INLINE UA_MonitoredItemNotification * UA_MonitoredItemNotification_new (void)
static UA_INLINE UA_StatusCode UA_MonitoredItemNotification_copy (const UA_MonitoredItemNotification *src, UA_MonitoredItemNotification *dst)
static UA_INLINE void UA_MonitoredItemNotification_deleteMembers (UA_MonitoredItemNotification *p)
static UA_INLINE void UA_MonitoredItemNotification_clear (UA_MonitoredItemNotification *p)
static UA_INLINE void UA_MonitoredItemNotification_delete (UA_MonitoredItemNotification *p)
static UA_INLINE void UA_ResponseHeader_init (UA_ResponseHeader *p)
static UA_INLINE UA_ResponseHeader * UA_ResponseHeader_new (void)
static UA_INLINE UA_StatusCode UA_ResponseHeader_copy (const UA_ResponseHeader *src, UA_ResponseHeader *dst)
static UA_INLINE void UA_ResponseHeader_deleteMembers (UA_ResponseHeader *p)
static UA_INLINE void UA_ResponseHeader_clear (UA_ResponseHeader *p)
static UA_INLINE void UA_ResponseHeader_delete (UA_ResponseHeader *p)
static UA_INLINE void UA_SignatureData_init (UA_SignatureData *p)
static UA_INLINE UA_SignatureData * UA_SignatureData_new (void)
static UA_INLINE UA_StatusCode UA_SignatureData_copy (const UA_SignatureData *src, UA_SignatureData *dst)
static UA_INLINE void UA_SignatureData_deleteMembers (UA_SignatureData *p)
static UA_INLINE void UA_SignatureData_clear (UA_SignatureData *p)
static UA_INLINE void UA_SignatureData_delete (UA_SignatureData *p)
static UA_INLINE void UA_ModifySubscriptionResponse_init (UA_ModifySubscriptionResponse *p)
static UA_INLINE UA_ModifySubscriptionResponse * UA_ModifySubscriptionResponse_new (void)
static UA_INLINE UA_StatusCode UA_ModifySubscriptionResponse_copy (const UA_ModifySubscriptionResponse *src, UA_ModifySubscriptionResponse *dst)
static UA_INLINE void UA_ModifySubscriptionResponse_deleteMembers (UA_ModifySubscriptionResponse *p)
static UA_INLINE void UA_ModifySubscriptionResponse_clear (UA_ModifySubscriptionResponse *p)
static UA_INLINE void UA_ModifySubscriptionResponse_delete (UA_ModifySubscriptionResponse *p)
static UA_INLINE void UA_NodeAttributes_init (UA_NodeAttributes *p)
static UA_INLINE UA_NodeAttributes * UA_NodeAttributes_new (void)
static UA_INLINE UA_StatusCode UA_NodeAttributes_copy (const UA_NodeAttributes *src, UA_NodeAttributes *dst)
static UA_INLINE void UA_NodeAttributes_deleteMembers (UA_NodeAttributes *p)
static UA_INLINE void UA_NodeAttributes_clear (UA_NodeAttributes *p)
static UA_INLINE void UA_NodeAttributes_delete (UA_NodeAttributes *p)
static UA_INLINE void UA_ActivateSessionResponse_init (UA_ActivateSessionResponse *p)
static UA_INLINE UA_ActivateSessionResponse * UA_ActivateSessionResponse_new (void)
static UA_INLINE UA_StatusCode UA_ActivateSessionResponse_copy (const UA_ActivateSessionResponse *src, UA_ActivateSessionResponse *dst)
static UA_INLINE void UA_ActivateSessionResponse_deleteMembers (UA_ActivateSessionResponse *p)
static UA_INLINE void UA_ActivateSessionResponse_clear (UA_ActivateSessionResponse *p)
static UA_INLINE void UA_ActivateSessionResponse_delete (UA_ActivateSessionResponse *p)
static UA_INLINE void UA_VariableTypeAttributes_init (UA_VariableTypeAttributes *p)
static UA_INLINE UA_VariableTypeAttributes * UA_VariableTypeAttributes_new (void)
static UA_INLINE UA_StatusCode UA_VariableTypeAttributes_copy (const UA_VariableTypeAttributes *src, UA_VariableTypeAttributes *dst)
static UA_INLINE void UA_VariableTypeAttributes_deleteMembers (UA_VariableTypeAttributes *p)
static UA_INLINE void UA_VariableTypeAttributes_clear (UA_VariableTypeAttributes *p)
static UA_INLINE void UA_VariableTypeAttributes_delete (UA_VariableTypeAttributes *p)
static UA_INLINE void UA_CallMethodResult_init (UA_CallMethodResult *p)
static UA_INLINE UA_CallMethodResult * UA_CallMethodResult_new (void)
static UA_INLINE UA_StatusCode UA_CallMethodResult_copy (const UA_CallMethodResult *src, UA_CallMethodResult *dst)
static UA_INLINE void UA_CallMethodResult_deleteMembers (UA_CallMethodResult *p)
static UA_INLINE void UA_CallMethodResult_clear (UA_CallMethodResult *p)
static UA_INLINE void UA_CallMethodResult_delete (UA_CallMethodResult *p)
static UA_INLINE void UA_MonitoringMode_init (UA_MonitoringMode *p)
static UA_INLINE UA_MonitoringMode * UA_MonitoringMode_new (void)
static UA_INLINE UA_StatusCode UA_MonitoringMode_copy (const UA_MonitoringMode *src, UA_MonitoringMode *dst)
static UA_INLINE void UA_MonitoringMode_deleteMembers (UA_MonitoringMode *p)
static UA_INLINE void UA_MonitoringMode_clear (UA_MonitoringMode *p)
static UA_INLINE void UA_MonitoringMode_delete (UA_MonitoringMode *p)
static UA_INLINE void UA_SetMonitoringModeResponse_init (UA_SetMonitoringModeResponse *p)
static UA_INLINE UA_SetMonitoringModeResponse * UA_SetMonitoringModeResponse_new (void)
static UA_INLINE UA_StatusCode UA_SetMonitoringModeResponse_copy (const UA_SetMonitoringModeResponse *src, UA_SetMonitoringModeResponse *dst)
static UA_INLINE void UA_SetMonitoringModeResponse_deleteMembers (UA_SetMonitoringModeResponse *p)
static UA_INLINE void UA_SetMonitoringModeResponse_clear (UA_SetMonitoringModeResponse *p)
static UA_INLINE void UA_SetMonitoringModeResponse_delete (UA_SetMonitoringModeResponse *p)
static UA_INLINE void UA_BrowseResultMask_init (UA_BrowseResultMask *p)
static UA_INLINE UA_BrowseResultMask * UA_BrowseResultMask_new (void)
static UA_INLINE UA_StatusCode UA_BrowseResultMask_copy (const UA_BrowseResultMask *src, UA_BrowseResultMask *dst)
static UA_INLINE void UA_BrowseResultMask_deleteMembers (UA_BrowseResultMask *p)
static UA_INLINE void UA_BrowseResultMask_clear (UA_BrowseResultMask *p)
static UA_INLINE void UA_BrowseResultMask_delete (UA_BrowseResultMask *p)
static UA_INLINE void UA_RequestHeader_init (UA_RequestHeader *p)
static UA_INLINE UA_RequestHeader * UA_RequestHeader_new (void)
static UA_INLINE UA_StatusCode UA_RequestHeader_copy (const UA_RequestHeader *src, UA_RequestHeader *dst)
static UA_INLINE void UA_RequestHeader_deleteMembers (UA_RequestHeader *p)
static UA_INLINE void UA_RequestHeader_clear (UA_RequestHeader *p)
static UA_INLINE void UA_RequestHeader_delete (UA_RequestHeader *p)
static UA_INLINE void UA_MonitoredItemModifyResult_init (UA_MonitoredItemModifyResult *p)
static UA_INLINE UA_MonitoredItemModifyResult * UA_MonitoredItemModifyResult_new (void)
static UA_INLINE UA_StatusCode UA_MonitoredItemModifyResult_copy (const UA_MonitoredItemModifyResult *src, UA_MonitoredItemModifyResult *dst)
static UA_INLINE void UA_MonitoredItemModifyResult_deleteMembers (UA_MonitoredItemModifyResult *p)
static UA_INLINE void UA_MonitoredItemModifyResult_clear (UA_MonitoredItemModifyResult *p)
static UA_INLINE void UA_MonitoredItemModifyResult_delete (UA_MonitoredItemModifyResult *p)
static UA_INLINE void UA_CloseSecureChannelRequest_init (UA_CloseSecureChannelRequest *p)
static UA_INLINE UA_CloseSecureChannelRequest * UA_CloseSecureChannelRequest_new (void)
static UA_INLINE UA_StatusCode UA_CloseSecureChannelRequest_copy (const UA_CloseSecureChannelRequest *src, UA_CloseSecureChannelRequest *dst)
static UA_INLINE void UA_CloseSecureChannelRequest_deleteMembers (UA_CloseSecureChannelRequest *p)
static UA_INLINE void UA_CloseSecureChannelRequest_clear (UA_CloseSecureChannelRequest *p)
static UA_INLINE void UA_CloseSecureChannelRequest_delete (UA_CloseSecureChannelRequest *p)
static UA_INLINE void UA_NotificationMessage_init (UA_NotificationMessage *p)
static UA_INLINE UA_NotificationMessage * UA_NotificationMessage_new (void)
static UA_INLINE UA_StatusCode UA_NotificationMessage_copy (const UA_NotificationMessage *src, UA_NotificationMessage *dst)
static UA_INLINE void UA_NotificationMessage_deleteMembers (UA_NotificationMessage *p)
static UA_INLINE void UA_NotificationMessage_clear (UA_NotificationMessage *p)
static UA_INLINE void UA_NotificationMessage_delete (UA_NotificationMessage *p)
static UA_INLINE void UA_CreateSubscriptionResponse_init (UA_CreateSubscriptionResponse *p)
static UA_INLINE UA_CreateSubscriptionResponse * UA_CreateSubscriptionResponse_new (void)
static UA_INLINE UA_StatusCode UA_CreateSubscriptionResponse_copy (const UA_CreateSubscriptionResponse *src, UA_CreateSubscriptionResponse *dst)
static UA_INLINE void UA_CreateSubscriptionResponse_deleteMembers (UA_CreateSubscriptionResponse *p)
static UA_INLINE void UA_CreateSubscriptionResponse_clear (UA_CreateSubscriptionResponse *p)
static UA_INLINE void UA_CreateSubscriptionResponse_delete (UA_CreateSubscriptionResponse *p)
static UA_INLINE void UA_MdnsDiscoveryConfiguration_init (UA_MdnsDiscoveryConfiguration *p)
static UA_INLINE UA_MdnsDiscoveryConfiguration * UA_MdnsDiscoveryConfiguration_new (void)
static UA_INLINE UA_StatusCode UA_MdnsDiscoveryConfiguration_copy (const UA_MdnsDiscoveryConfiguration *src, UA_MdnsDiscoveryConfiguration *dst)
static UA_INLINE void UA_MdnsDiscoveryConfiguration_deleteMembers (UA_MdnsDiscoveryConfiguration *p)
static UA_INLINE void UA_MdnsDiscoveryConfiguration_clear (UA_MdnsDiscoveryConfiguration *p)
static UA_INLINE void UA_MdnsDiscoveryConfiguration_delete (UA_MdnsDiscoveryConfiguration *p)
static UA_INLINE void UA_BrowseDirection_init (UA_BrowseDirection *p)
static UA_INLINE UA_BrowseDirection * UA_BrowseDirection_new (void)
static UA_INLINE UA_StatusCode UA_BrowseDirection_copy (const UA_BrowseDirection *src, UA_BrowseDirection *dst)
static UA_INLINE void UA_BrowseDirection_deleteMembers (UA_BrowseDirection *p)
static UA_INLINE void UA_BrowseDirection_clear (UA_BrowseDirection *p)
static UA_INLINE void UA_BrowseDirection_delete (UA_BrowseDirection *p)
static UA_INLINE void UA_CallMethodRequest_init (UA_CallMethodRequest *p)
static UA_INLINE UA_CallMethodRequest * UA_CallMethodRequest_new (void)
static UA_INLINE UA_StatusCode UA_CallMethodRequest_copy (const UA_CallMethodRequest *src, UA_CallMethodRequest *dst)
static UA_INLINE void UA_CallMethodRequest_deleteMembers (UA_CallMethodRequest *p)
static UA_INLINE void UA_CallMethodRequest_clear (UA_CallMethodRequest *p)
static UA_INLINE void UA_CallMethodRequest_delete (UA_CallMethodRequest *p)
static UA_INLINE void UA_ReadResponse_init (UA_ReadResponse *p)
static UA_INLINE UA_ReadResponse * UA_ReadResponse_new (void)
static UA_INLINE UA_StatusCode UA_ReadResponse_copy (const UA_ReadResponse *src, UA_ReadResponse *dst)
static UA_INLINE void UA_ReadResponse_deleteMembers (UA_ReadResponse *p)
static UA_INLINE void UA_ReadResponse_clear (UA_ReadResponse *p)
static UA_INLINE void UA_ReadResponse_delete (UA_ReadResponse *p)
static UA_INLINE void UA_TimestampsToReturn_init (UA_TimestampsToReturn *p)
static UA_INLINE UA_TimestampsToReturn * UA_TimestampsToReturn_new (void)
static UA_INLINE UA_StatusCode UA_TimestampsToReturn_copy (const UA_TimestampsToReturn *src, UA_TimestampsToReturn *dst)
static UA_INLINE void UA_TimestampsToReturn_deleteMembers (UA_TimestampsToReturn *p)
static UA_INLINE void UA_TimestampsToReturn_clear (UA_TimestampsToReturn *p)
static UA_INLINE void UA_TimestampsToReturn_delete (UA_TimestampsToReturn *p)
static UA_INLINE void UA_NodeClass_init (UA_NodeClass *p)
static UA_INLINE UA_NodeClass * UA_NodeClass_new (void)
static UA_INLINE UA_StatusCode UA_NodeClass_copy (const UA_NodeClass *src, UA_NodeClass *dst)
static UA_INLINE void UA_NodeClass_deleteMembers (UA_NodeClass *p)
static UA_INLINE void UA_NodeClass_clear (UA_NodeClass *p)
static UA_INLINE void UA_NodeClass_delete (UA_NodeClass *p)
static UA_INLINE void UA_ObjectTypeAttributes_init (UA_ObjectTypeAttributes *p)
static UA_INLINE UA_ObjectTypeAttributes * UA_ObjectTypeAttributes_new (void)
static UA_INLINE UA_StatusCode UA_ObjectTypeAttributes_copy (const UA_ObjectTypeAttributes *src, UA_ObjectTypeAttributes *dst)
static UA_INLINE void UA_ObjectTypeAttributes_deleteMembers (UA_ObjectTypeAttributes *p)
static UA_INLINE void UA_ObjectTypeAttributes_clear (UA_ObjectTypeAttributes *p)
static UA_INLINE void UA_ObjectTypeAttributes_delete (UA_ObjectTypeAttributes *p)
static UA_INLINE void UA_SecurityTokenRequestType_init (UA_SecurityTokenRequestType *p)
static UA_INLINE UA_SecurityTokenRequestType * UA_SecurityTokenRequestType_new (void)
static UA_INLINE UA_StatusCode UA_SecurityTokenRequestType_copy (const UA_SecurityTokenRequestType *src, UA_SecurityTokenRequestType *dst)
static UA_INLINE void UA_SecurityTokenRequestType_deleteMembers (UA_SecurityTokenRequestType *p)
static UA_INLINE void UA_SecurityTokenRequestType_clear (UA_SecurityTokenRequestType *p)
static UA_INLINE void UA_SecurityTokenRequestType_delete (UA_SecurityTokenRequestType *p)
static UA_INLINE void UA_CloseSessionResponse_init (UA_CloseSessionResponse *p)
static UA_INLINE UA_CloseSessionResponse * UA_CloseSessionResponse_new (void)
static UA_INLINE UA_StatusCode UA_CloseSessionResponse_copy (const UA_CloseSessionResponse *src, UA_CloseSessionResponse *dst)
static UA_INLINE void UA_CloseSessionResponse_deleteMembers (UA_CloseSessionResponse *p)
static UA_INLINE void UA_CloseSessionResponse_clear (UA_CloseSessionResponse *p)
static UA_INLINE void UA_CloseSessionResponse_delete (UA_CloseSessionResponse *p)
static UA_INLINE void UA_SetPublishingModeRequest_init (UA_SetPublishingModeRequest *p)
static UA_INLINE UA_SetPublishingModeRequest * UA_SetPublishingModeRequest_new (void)
static UA_INLINE UA_StatusCode UA_SetPublishingModeRequest_copy (const UA_SetPublishingModeRequest *src, UA_SetPublishingModeRequest *dst)
static UA_INLINE void UA_SetPublishingModeRequest_deleteMembers (UA_SetPublishingModeRequest *p)
static UA_INLINE void UA_SetPublishingModeRequest_clear (UA_SetPublishingModeRequest *p)
static UA_INLINE void UA_SetPublishingModeRequest_delete (UA_SetPublishingModeRequest *p)
static UA_INLINE void UA_IssuedIdentityToken_init (UA_IssuedIdentityToken *p)
static UA_INLINE UA_IssuedIdentityToken * UA_IssuedIdentityToken_new (void)
static UA_INLINE UA_StatusCode UA_IssuedIdentityToken_copy (const UA_IssuedIdentityToken *src, UA_IssuedIdentityToken *dst)
static UA_INLINE void UA_IssuedIdentityToken_deleteMembers (UA_IssuedIdentityToken *p)
static UA_INLINE void UA_IssuedIdentityToken_clear (UA_IssuedIdentityToken *p)
static UA_INLINE void UA_IssuedIdentityToken_delete (UA_IssuedIdentityToken *p)
static UA_INLINE void UA_ServerOnNetwork_init (UA_ServerOnNetwork *p)
static UA_INLINE UA_ServerOnNetwork * UA_ServerOnNetwork_new (void)
static UA_INLINE UA_StatusCode UA_ServerOnNetwork_copy (const UA_ServerOnNetwork *src, UA_ServerOnNetwork *dst)
static UA_INLINE void UA_ServerOnNetwork_deleteMembers (UA_ServerOnNetwork *p)
static UA_INLINE void UA_ServerOnNetwork_clear (UA_ServerOnNetwork *p)
static UA_INLINE void UA_ServerOnNetwork_delete (UA_ServerOnNetwork *p)
static UA_INLINE void UA_DeleteMonitoredItemsResponse_init (UA_DeleteMonitoredItemsResponse *p)
static UA_INLINE UA_DeleteMonitoredItemsResponse * UA_DeleteMonitoredItemsResponse_new (void)
static UA_INLINE UA_StatusCode UA_DeleteMonitoredItemsResponse_copy (const UA_DeleteMonitoredItemsResponse *src, UA_DeleteMonitoredItemsResponse *dst)
static UA_INLINE void UA_DeleteMonitoredItemsResponse_deleteMembers (UA_DeleteMonitoredItemsResponse *p)
static UA_INLINE void UA_DeleteMonitoredItemsResponse_clear (UA_DeleteMonitoredItemsResponse *p)
static UA_INLINE void UA_DeleteMonitoredItemsResponse_delete (UA_DeleteMonitoredItemsResponse *p)
static UA_INLINE void UA_ApplicationType_init (UA_ApplicationType *p)
static UA_INLINE UA_ApplicationType * UA_ApplicationType_new (void)
static UA_INLINE UA_StatusCode UA_ApplicationType_copy (const UA_ApplicationType *src, UA_ApplicationType *dst)
static UA_INLINE void UA_ApplicationType_deleteMembers (UA_ApplicationType *p)
static UA_INLINE void UA_ApplicationType_clear (UA_ApplicationType *p)
static UA_INLINE void UA_ApplicationType_delete (UA_ApplicationType *p)
static UA_INLINE void UA_DiscoveryConfiguration_init (UA_DiscoveryConfiguration *p)
static UA_INLINE UA_DiscoveryConfiguration * UA_DiscoveryConfiguration_new (void)
static UA_INLINE UA_StatusCode UA_DiscoveryConfiguration_copy (const UA_DiscoveryConfiguration *src, UA_DiscoveryConfiguration *dst)
static UA_INLINE void UA_DiscoveryConfiguration_deleteMembers (UA_DiscoveryConfiguration *p)
static UA_INLINE void UA_DiscoveryConfiguration_clear (UA_DiscoveryConfiguration *p)
static UA_INLINE void UA_DiscoveryConfiguration_delete (UA_DiscoveryConfiguration *p)
static UA_INLINE void UA_BrowseNextRequest_init (UA_BrowseNextRequest *p)
static UA_INLINE UA_BrowseNextRequest * UA_BrowseNextRequest_new (void)
static UA_INLINE UA_StatusCode UA_BrowseNextRequest_copy (const UA_BrowseNextRequest *src, UA_BrowseNextRequest *dst)
static UA_INLINE void UA_BrowseNextRequest_deleteMembers (UA_BrowseNextRequest *p)
static UA_INLINE void UA_BrowseNextRequest_clear (UA_BrowseNextRequest *p)
static UA_INLINE void UA_BrowseNextRequest_delete (UA_BrowseNextRequest *p)
static UA_INLINE void UA_ModifySubscriptionRequest_init (UA_ModifySubscriptionRequest *p)
static UA_INLINE UA_ModifySubscriptionRequest * UA_ModifySubscriptionRequest_new (void)
static UA_INLINE UA_StatusCode UA_ModifySubscriptionRequest_copy (const UA_ModifySubscriptionRequest *src, UA_ModifySubscriptionRequest *dst)
static UA_INLINE void UA_ModifySubscriptionRequest_deleteMembers (UA_ModifySubscriptionRequest *p)
static UA_INLINE void UA_ModifySubscriptionRequest_clear (UA_ModifySubscriptionRequest *p)
static UA_INLINE void UA_ModifySubscriptionRequest_delete (UA_ModifySubscriptionRequest *p)
static UA_INLINE void UA_BrowseDescription_init (UA_BrowseDescription *p)
static UA_INLINE UA_BrowseDescription * UA_BrowseDescription_new (void)
static UA_INLINE UA_StatusCode UA_BrowseDescription_copy (const UA_BrowseDescription *src, UA_BrowseDescription *dst)
static UA_INLINE void UA_BrowseDescription_deleteMembers (UA_BrowseDescription *p)
static UA_INLINE void UA_BrowseDescription_clear (UA_BrowseDescription *p)
static UA_INLINE void UA_BrowseDescription_delete (UA_BrowseDescription *p)
static UA_INLINE void UA_SignedSoftwareCertificate_init (UA_SignedSoftwareCertificate *p)
static UA_INLINE UA_SignedSoftwareCertificate * UA_SignedSoftwareCertificate_new (void)
static UA_INLINE UA_StatusCode UA_SignedSoftwareCertificate_copy (const UA_SignedSoftwareCertificate *src, UA_SignedSoftwareCertificate *dst)
static UA_INLINE void UA_SignedSoftwareCertificate_deleteMembers (UA_SignedSoftwareCertificate *p)
static UA_INLINE void UA_SignedSoftwareCertificate_clear (UA_SignedSoftwareCertificate *p)
static UA_INLINE void UA_SignedSoftwareCertificate_delete (UA_SignedSoftwareCertificate *p)
static UA_INLINE void UA_BrowsePathTarget_init (UA_BrowsePathTarget *p)
static UA_INLINE UA_BrowsePathTarget * UA_BrowsePathTarget_new (void)
static UA_INLINE UA_StatusCode UA_BrowsePathTarget_copy (const UA_BrowsePathTarget *src, UA_BrowsePathTarget *dst)
static UA_INLINE void UA_BrowsePathTarget_deleteMembers (UA_BrowsePathTarget *p)
static UA_INLINE void UA_BrowsePathTarget_clear (UA_BrowsePathTarget *p)
static UA_INLINE void UA_BrowsePathTarget_delete (UA_BrowsePathTarget *p)
static UA_INLINE void UA_WriteResponse_init (UA_WriteResponse *p)
static UA_INLINE UA_WriteResponse * UA_WriteResponse_new (void)
static UA_INLINE UA_StatusCode UA_WriteResponse_copy (const UA_WriteResponse *src, UA_WriteResponse *dst)
static UA_INLINE void UA_WriteResponse_deleteMembers (UA_WriteResponse *p)
static UA_INLINE void UA_WriteResponse_clear (UA_WriteResponse *p)
static UA_INLINE void UA_WriteResponse_delete (UA_WriteResponse *p)
static UA_INLINE void UA_AddNodesResult_init (UA_AddNodesResult *p)
static UA_INLINE UA_AddNodesResult * UA_AddNodesResult_new (void)
static UA_INLINE UA_StatusCode UA_AddNodesResult_copy (const UA_AddNodesResult *src, UA_AddNodesResult *dst)
static UA_INLINE void UA_AddNodesResult_deleteMembers (UA_AddNodesResult *p)
static UA_INLINE void UA_AddNodesResult_clear (UA_AddNodesResult *p)
static UA_INLINE void UA_AddNodesResult_delete (UA_AddNodesResult *p)
static UA_INLINE void UA_RegisterServerResponse_init (UA_RegisterServerResponse *p)
static UA_INLINE UA_RegisterServerResponse * UA_RegisterServerResponse_new (void)
static UA_INLINE UA_StatusCode UA_RegisterServerResponse_copy (const UA_RegisterServerResponse *src, UA_RegisterServerResponse *dst)
static UA_INLINE void UA_RegisterServerResponse_deleteMembers (UA_RegisterServerResponse *p)
static UA_INLINE void UA_RegisterServerResponse_clear (UA_RegisterServerResponse *p)
static UA_INLINE void UA_RegisterServerResponse_delete (UA_RegisterServerResponse *p)
static UA_INLINE void UA_AddReferencesItem_init (UA_AddReferencesItem *p)
static UA_INLINE UA_AddReferencesItem * UA_AddReferencesItem_new (void)
static UA_INLINE UA_StatusCode UA_AddReferencesItem_copy (const UA_AddReferencesItem *src, UA_AddReferencesItem *dst)
static UA_INLINE void UA_AddReferencesItem_deleteMembers (UA_AddReferencesItem *p)
static UA_INLINE void UA_AddReferencesItem_clear (UA_AddReferencesItem *p)
static UA_INLINE void UA_AddReferencesItem_delete (UA_AddReferencesItem *p)
static UA_INLINE void UA_RegisterServer2Response_init (UA_RegisterServer2Response *p)
static UA_INLINE UA_RegisterServer2Response * UA_RegisterServer2Response_new (void)
static UA_INLINE UA_StatusCode UA_RegisterServer2Response_copy (const UA_RegisterServer2Response *src, UA_RegisterServer2Response *dst)
static UA_INLINE void UA_RegisterServer2Response_deleteMembers (UA_RegisterServer2Response *p)
static UA_INLINE void UA_RegisterServer2Response_clear (UA_RegisterServer2Response *p)
static UA_INLINE void UA_RegisterServer2Response_delete (UA_RegisterServer2Response *p)
static UA_INLINE void UA_DeleteReferencesResponse_init (UA_DeleteReferencesResponse *p)
static UA_INLINE UA_DeleteReferencesResponse * UA_DeleteReferencesResponse_new (void)
static UA_INLINE UA_StatusCode UA_DeleteReferencesResponse_copy (const UA_DeleteReferencesResponse *src, UA_DeleteReferencesResponse *dst)
static UA_INLINE void UA_DeleteReferencesResponse_deleteMembers (UA_DeleteReferencesResponse *p)
static UA_INLINE void UA_DeleteReferencesResponse_clear (UA_DeleteReferencesResponse *p)
static UA_INLINE void UA_DeleteReferencesResponse_delete (UA_DeleteReferencesResponse *p)
static UA_INLINE void UA_RelativePathElement_init (UA_RelativePathElement *p)
static UA_INLINE UA_RelativePathElement * UA_RelativePathElement_new (void)
static UA_INLINE UA_StatusCode UA_RelativePathElement_copy (const UA_RelativePathElement *src, UA_RelativePathElement *dst)
static UA_INLINE void UA_RelativePathElement_deleteMembers (UA_RelativePathElement *p)
static UA_INLINE void UA_RelativePathElement_clear (UA_RelativePathElement *p)
static UA_INLINE void UA_RelativePathElement_delete (UA_RelativePathElement *p)
static UA_INLINE void UA_SubscriptionAcknowledgement_init (UA_SubscriptionAcknowledgement *p)
static UA_INLINE UA_SubscriptionAcknowledgement * UA_SubscriptionAcknowledgement_new (void)
static UA_INLINE UA_StatusCode UA_SubscriptionAcknowledgement_copy (const UA_SubscriptionAcknowledgement *src, UA_SubscriptionAcknowledgement *dst)
static UA_INLINE void UA_SubscriptionAcknowledgement_deleteMembers (UA_SubscriptionAcknowledgement *p)
static UA_INLINE void UA_SubscriptionAcknowledgement_clear (UA_SubscriptionAcknowledgement *p)
static UA_INLINE void UA_SubscriptionAcknowledgement_delete (UA_SubscriptionAcknowledgement *p)
static UA_INLINE void UA_CreateMonitoredItemsResponse_init (UA_CreateMonitoredItemsResponse *p)
static UA_INLINE UA_CreateMonitoredItemsResponse * UA_CreateMonitoredItemsResponse_new (void)
static UA_INLINE UA_StatusCode UA_CreateMonitoredItemsResponse_copy (const UA_CreateMonitoredItemsResponse *src, UA_CreateMonitoredItemsResponse *dst)
static UA_INLINE void UA_CreateMonitoredItemsResponse_deleteMembers (UA_CreateMonitoredItemsResponse *p)
static UA_INLINE void UA_CreateMonitoredItemsResponse_clear (UA_CreateMonitoredItemsResponse *p)
static UA_INLINE void UA_CreateMonitoredItemsResponse_delete (UA_CreateMonitoredItemsResponse *p)
static UA_INLINE void UA_DeleteReferencesItem_init (UA_DeleteReferencesItem *p)
static UA_INLINE UA_DeleteReferencesItem * UA_DeleteReferencesItem_new (void)
static UA_INLINE UA_StatusCode UA_DeleteReferencesItem_copy (const UA_DeleteReferencesItem *src, UA_DeleteReferencesItem *dst)
static UA_INLINE void UA_DeleteReferencesItem_deleteMembers (UA_DeleteReferencesItem *p)
static UA_INLINE void UA_DeleteReferencesItem_clear (UA_DeleteReferencesItem *p)
static UA_INLINE void UA_DeleteReferencesItem_delete (UA_DeleteReferencesItem *p)
static UA_INLINE void UA_WriteValue_init (UA_WriteValue *p)
static UA_INLINE UA_WriteValue * UA_WriteValue_new (void)
static UA_INLINE UA_StatusCode UA_WriteValue_copy (const UA_WriteValue *src, UA_WriteValue *dst)
static UA_INLINE void UA_WriteValue_deleteMembers (UA_WriteValue *p)
static UA_INLINE void UA_WriteValue_clear (UA_WriteValue *p)
static UA_INLINE void UA_WriteValue_delete (UA_WriteValue *p)
static UA_INLINE void UA_DataTypeAttributes_init (UA_DataTypeAttributes *p)
static UA_INLINE UA_DataTypeAttributes * UA_DataTypeAttributes_new (void)
static UA_INLINE UA_StatusCode UA_DataTypeAttributes_copy (const UA_DataTypeAttributes *src, UA_DataTypeAttributes *dst)
static UA_INLINE void UA_DataTypeAttributes_deleteMembers (UA_DataTypeAttributes *p)
static UA_INLINE void UA_DataTypeAttributes_clear (UA_DataTypeAttributes *p)
static UA_INLINE void UA_DataTypeAttributes_delete (UA_DataTypeAttributes *p)
static UA_INLINE void UA_AddReferencesResponse_init (UA_AddReferencesResponse *p)
static UA_INLINE UA_AddReferencesResponse * UA_AddReferencesResponse_new (void)
static UA_INLINE UA_StatusCode UA_AddReferencesResponse_copy (const UA_AddReferencesResponse *src, UA_AddReferencesResponse *dst)
static UA_INLINE void UA_AddReferencesResponse_deleteMembers (UA_AddReferencesResponse *p)
static UA_INLINE void UA_AddReferencesResponse_clear (UA_AddReferencesResponse *p)
static UA_INLINE void UA_AddReferencesResponse_delete (UA_AddReferencesResponse *p)
static UA_INLINE void UA_DeadbandType_init (UA_DeadbandType *p)
static UA_INLINE UA_DeadbandType * UA_DeadbandType_new (void)
static UA_INLINE UA_StatusCode UA_DeadbandType_copy (const UA_DeadbandType *src, UA_DeadbandType *dst)
static UA_INLINE void UA_DeadbandType_deleteMembers (UA_DeadbandType *p)
static UA_INLINE void UA_DeadbandType_clear (UA_DeadbandType *p)
static UA_INLINE void UA_DeadbandType_delete (UA_DeadbandType *p)
static UA_INLINE void UA_DataChangeTrigger_init (UA_DataChangeTrigger *p)
static UA_INLINE UA_DataChangeTrigger * UA_DataChangeTrigger_new (void)
static UA_INLINE UA_StatusCode UA_DataChangeTrigger_copy (const UA_DataChangeTrigger *src, UA_DataChangeTrigger *dst)
static UA_INLINE void UA_DataChangeTrigger_deleteMembers (UA_DataChangeTrigger *p)
static UA_INLINE void UA_DataChangeTrigger_clear (UA_DataChangeTrigger *p)
static UA_INLINE void UA_DataChangeTrigger_delete (UA_DataChangeTrigger *p)
static UA_INLINE void UA_BuildInfo_init (UA_BuildInfo *p)
static UA_INLINE UA_BuildInfo * UA_BuildInfo_new (void)
static UA_INLINE UA_StatusCode UA_BuildInfo_copy (const UA_BuildInfo *src, UA_BuildInfo *dst)
static UA_INLINE void UA_BuildInfo_deleteMembers (UA_BuildInfo *p)
static UA_INLINE void UA_BuildInfo_clear (UA_BuildInfo *p)
static UA_INLINE void UA_BuildInfo_delete (UA_BuildInfo *p)
static UA_INLINE void UA_FilterOperand_init (UA_FilterOperand *p)
static UA_INLINE UA_FilterOperand * UA_FilterOperand_new (void)
static UA_INLINE UA_StatusCode UA_FilterOperand_copy (const UA_FilterOperand *src, UA_FilterOperand *dst)
static UA_INLINE void UA_FilterOperand_deleteMembers (UA_FilterOperand *p)
static UA_INLINE void UA_FilterOperand_clear (UA_FilterOperand *p)
static UA_INLINE void UA_FilterOperand_delete (UA_FilterOperand *p)
static UA_INLINE void UA_MonitoringParameters_init (UA_MonitoringParameters *p)
static UA_INLINE UA_MonitoringParameters * UA_MonitoringParameters_new (void)
static UA_INLINE UA_StatusCode UA_MonitoringParameters_copy (const UA_MonitoringParameters *src, UA_MonitoringParameters *dst)
static UA_INLINE void UA_MonitoringParameters_deleteMembers (UA_MonitoringParameters *p)
static UA_INLINE void UA_MonitoringParameters_clear (UA_MonitoringParameters *p)
static UA_INLINE void UA_MonitoringParameters_delete (UA_MonitoringParameters *p)
static UA_INLINE void UA_DeleteNodesItem_init (UA_DeleteNodesItem *p)
static UA_INLINE UA_DeleteNodesItem * UA_DeleteNodesItem_new (void)
static UA_INLINE UA_StatusCode UA_DeleteNodesItem_copy (const UA_DeleteNodesItem *src, UA_DeleteNodesItem *dst)
static UA_INLINE void UA_DeleteNodesItem_deleteMembers (UA_DeleteNodesItem *p)
static UA_INLINE void UA_DeleteNodesItem_clear (UA_DeleteNodesItem *p)
static UA_INLINE void UA_DeleteNodesItem_delete (UA_DeleteNodesItem *p)
static UA_INLINE void UA_ReadValueId_init (UA_ReadValueId *p)
static UA_INLINE UA_ReadValueId * UA_ReadValueId_new (void)
static UA_INLINE UA_StatusCode UA_ReadValueId_copy (const UA_ReadValueId *src, UA_ReadValueId *dst)
static UA_INLINE void UA_ReadValueId_deleteMembers (UA_ReadValueId *p)
static UA_INLINE void UA_ReadValueId_clear (UA_ReadValueId *p)
static UA_INLINE void UA_ReadValueId_delete (UA_ReadValueId *p)
static UA_INLINE void UA_CallRequest_init (UA_CallRequest *p)
static UA_INLINE UA_CallRequest * UA_CallRequest_new (void)
static UA_INLINE UA_StatusCode UA_CallRequest_copy (const UA_CallRequest *src, UA_CallRequest *dst)
static UA_INLINE void UA_CallRequest_deleteMembers (UA_CallRequest *p)
static UA_INLINE void UA_CallRequest_clear (UA_CallRequest *p)
static UA_INLINE void UA_CallRequest_delete (UA_CallRequest *p)
static UA_INLINE void UA_RelativePath_init (UA_RelativePath *p)
static UA_INLINE UA_RelativePath * UA_RelativePath_new (void)
static UA_INLINE UA_StatusCode UA_RelativePath_copy (const UA_RelativePath *src, UA_RelativePath *dst)
static UA_INLINE void UA_RelativePath_deleteMembers (UA_RelativePath *p)
static UA_INLINE void UA_RelativePath_clear (UA_RelativePath *p)
static UA_INLINE void UA_RelativePath_delete (UA_RelativePath *p)
static UA_INLINE void UA_DeleteNodesRequest_init (UA_DeleteNodesRequest *p)
static UA_INLINE UA_DeleteNodesRequest * UA_DeleteNodesRequest_new (void)
static UA_INLINE UA_StatusCode UA_DeleteNodesRequest_copy (const UA_DeleteNodesRequest *src, UA_DeleteNodesRequest *dst)
static UA_INLINE void UA_DeleteNodesRequest_deleteMembers (UA_DeleteNodesRequest *p)
static UA_INLINE void UA_DeleteNodesRequest_clear (UA_DeleteNodesRequest *p)
static UA_INLINE void UA_DeleteNodesRequest_delete (UA_DeleteNodesRequest *p)
static UA_INLINE void UA_MonitoredItemModifyRequest_init (UA_MonitoredItemModifyRequest *p)
static UA_INLINE UA_MonitoredItemModifyRequest * UA_MonitoredItemModifyRequest_new (void)
static UA_INLINE UA_StatusCode UA_MonitoredItemModifyRequest_copy (const UA_MonitoredItemModifyRequest *src, UA_MonitoredItemModifyRequest *dst)
static UA_INLINE void UA_MonitoredItemModifyRequest_deleteMembers (UA_MonitoredItemModifyRequest *p)
static UA_INLINE void UA_MonitoredItemModifyRequest_clear (UA_MonitoredItemModifyRequest *p)
static UA_INLINE void UA_MonitoredItemModifyRequest_delete (UA_MonitoredItemModifyRequest *p)
static UA_INLINE void UA_UserTokenType_init (UA_UserTokenType *p)
static UA_INLINE UA_UserTokenType * UA_UserTokenType_new (void)
static UA_INLINE UA_StatusCode UA_UserTokenType_copy (const UA_UserTokenType *src, UA_UserTokenType *dst)
static UA_INLINE void UA_UserTokenType_deleteMembers (UA_UserTokenType *p)
static UA_INLINE void UA_UserTokenType_clear (UA_UserTokenType *p)
static UA_INLINE void UA_UserTokenType_delete (UA_UserTokenType *p)
static UA_INLINE void UA_AggregateConfiguration_init (UA_AggregateConfiguration *p)
static UA_INLINE UA_AggregateConfiguration * UA_AggregateConfiguration_new (void)
static UA_INLINE UA_StatusCode UA_AggregateConfiguration_copy (const UA_AggregateConfiguration *src, UA_AggregateConfiguration *dst)
static UA_INLINE void UA_AggregateConfiguration_deleteMembers (UA_AggregateConfiguration *p)
static UA_INLINE void UA_AggregateConfiguration_clear (UA_AggregateConfiguration *p)
static UA_INLINE void UA_AggregateConfiguration_delete (UA_AggregateConfiguration *p)
static UA_INLINE void UA_LocaleId_init (UA_LocaleId *p)
static UA_INLINE UA_LocaleId * UA_LocaleId_new (void)
static UA_INLINE UA_StatusCode UA_LocaleId_copy (const UA_LocaleId *src, UA_LocaleId *dst)
static UA_INLINE void UA_LocaleId_deleteMembers (UA_LocaleId *p)
static UA_INLINE void UA_LocaleId_clear (UA_LocaleId *p)
static UA_INLINE void UA_LocaleId_delete (UA_LocaleId *p)
static UA_INLINE void UA_UnregisterNodesResponse_init (UA_UnregisterNodesResponse *p)
static UA_INLINE UA_UnregisterNodesResponse * UA_UnregisterNodesResponse_new (void)
static UA_INLINE UA_StatusCode UA_UnregisterNodesResponse_copy (const UA_UnregisterNodesResponse *src, UA_UnregisterNodesResponse *dst)
static UA_INLINE void UA_UnregisterNodesResponse_deleteMembers (UA_UnregisterNodesResponse *p)
static UA_INLINE void UA_UnregisterNodesResponse_clear (UA_UnregisterNodesResponse *p)
static UA_INLINE void UA_UnregisterNodesResponse_delete (UA_UnregisterNodesResponse *p)
static UA_INLINE void UA_ContentFilterResult_init (UA_ContentFilterResult *p)
static UA_INLINE UA_ContentFilterResult * UA_ContentFilterResult_new (void)
static UA_INLINE UA_StatusCode UA_ContentFilterResult_copy (const UA_ContentFilterResult *src, UA_ContentFilterResult *dst)
static UA_INLINE void UA_ContentFilterResult_deleteMembers (UA_ContentFilterResult *p)
static UA_INLINE void UA_ContentFilterResult_clear (UA_ContentFilterResult *p)
static UA_INLINE void UA_ContentFilterResult_delete (UA_ContentFilterResult *p)
static UA_INLINE void UA_UserTokenPolicy_init (UA_UserTokenPolicy *p)
static UA_INLINE UA_UserTokenPolicy * UA_UserTokenPolicy_new (void)
static UA_INLINE UA_StatusCode UA_UserTokenPolicy_copy (const UA_UserTokenPolicy *src, UA_UserTokenPolicy *dst)
static UA_INLINE void UA_UserTokenPolicy_deleteMembers (UA_UserTokenPolicy *p)
static UA_INLINE void UA_UserTokenPolicy_clear (UA_UserTokenPolicy *p)
static UA_INLINE void UA_UserTokenPolicy_delete (UA_UserTokenPolicy *p)
static UA_INLINE void UA_DeleteMonitoredItemsRequest_init (UA_DeleteMonitoredItemsRequest *p)
static UA_INLINE UA_DeleteMonitoredItemsRequest * UA_DeleteMonitoredItemsRequest_new (void)
static UA_INLINE UA_StatusCode UA_DeleteMonitoredItemsRequest_copy (const UA_DeleteMonitoredItemsRequest *src, UA_DeleteMonitoredItemsRequest *dst)
static UA_INLINE void UA_DeleteMonitoredItemsRequest_deleteMembers (UA_DeleteMonitoredItemsRequest *p)
static UA_INLINE void UA_DeleteMonitoredItemsRequest_clear (UA_DeleteMonitoredItemsRequest *p)
static UA_INLINE void UA_DeleteMonitoredItemsRequest_delete (UA_DeleteMonitoredItemsRequest *p)
static UA_INLINE void UA_SetMonitoringModeRequest_init (UA_SetMonitoringModeRequest *p)
static UA_INLINE UA_SetMonitoringModeRequest * UA_SetMonitoringModeRequest_new (void)
static UA_INLINE UA_StatusCode UA_SetMonitoringModeRequest_copy (const UA_SetMonitoringModeRequest *src, UA_SetMonitoringModeRequest *dst)
static UA_INLINE void UA_SetMonitoringModeRequest_deleteMembers (UA_SetMonitoringModeRequest *p)
static UA_INLINE void UA_SetMonitoringModeRequest_clear (UA_SetMonitoringModeRequest *p)
static UA_INLINE void UA_SetMonitoringModeRequest_delete (UA_SetMonitoringModeRequest *p)
static UA_INLINE void UA_Duration_init (UA_Duration *p)
static UA_INLINE UA_Duration * UA_Duration_new (void)
static UA_INLINE UA_StatusCode UA_Duration_copy (const UA_Duration *src, UA_Duration *dst)
static UA_INLINE void UA_Duration_deleteMembers (UA_Duration *p)
static UA_INLINE void UA_Duration_clear (UA_Duration *p)
static UA_INLINE void UA_Duration_delete (UA_Duration *p)
static UA_INLINE void UA_ReferenceTypeAttributes_init (UA_ReferenceTypeAttributes *p)
static UA_INLINE UA_ReferenceTypeAttributes * UA_ReferenceTypeAttributes_new (void)
static UA_INLINE UA_StatusCode UA_ReferenceTypeAttributes_copy (const UA_ReferenceTypeAttributes *src, UA_ReferenceTypeAttributes *dst)
static UA_INLINE void UA_ReferenceTypeAttributes_deleteMembers (UA_ReferenceTypeAttributes *p)
static UA_INLINE void UA_ReferenceTypeAttributes_clear (UA_ReferenceTypeAttributes *p)
static UA_INLINE void UA_ReferenceTypeAttributes_delete (UA_ReferenceTypeAttributes *p)
static UA_INLINE void UA_GetEndpointsRequest_init (UA_GetEndpointsRequest *p)
static UA_INLINE UA_GetEndpointsRequest * UA_GetEndpointsRequest_new (void)
static UA_INLINE UA_StatusCode UA_GetEndpointsRequest_copy (const UA_GetEndpointsRequest *src, UA_GetEndpointsRequest *dst)
static UA_INLINE void UA_GetEndpointsRequest_deleteMembers (UA_GetEndpointsRequest *p)
static UA_INLINE void UA_GetEndpointsRequest_clear (UA_GetEndpointsRequest *p)
static UA_INLINE void UA_GetEndpointsRequest_delete (UA_GetEndpointsRequest *p)
static UA_INLINE void UA_CloseSecureChannelResponse_init (UA_CloseSecureChannelResponse *p)
static UA_INLINE UA_CloseSecureChannelResponse * UA_CloseSecureChannelResponse_new (void)
static UA_INLINE UA_StatusCode UA_CloseSecureChannelResponse_copy (const UA_CloseSecureChannelResponse *src, UA_CloseSecureChannelResponse *dst)
static UA_INLINE void UA_CloseSecureChannelResponse_deleteMembers (UA_CloseSecureChannelResponse *p)
static UA_INLINE void UA_CloseSecureChannelResponse_clear (UA_CloseSecureChannelResponse *p)
static UA_INLINE void UA_CloseSecureChannelResponse_delete (UA_CloseSecureChannelResponse *p)
static UA_INLINE void UA_ViewDescription_init (UA_ViewDescription *p)
static UA_INLINE UA_ViewDescription * UA_ViewDescription_new (void)
static UA_INLINE UA_StatusCode UA_ViewDescription_copy (const UA_ViewDescription *src, UA_ViewDescription *dst)
static UA_INLINE void UA_ViewDescription_deleteMembers (UA_ViewDescription *p)
static UA_INLINE void UA_ViewDescription_clear (UA_ViewDescription *p)
static UA_INLINE void UA_ViewDescription_delete (UA_ViewDescription *p)
static UA_INLINE void UA_SetPublishingModeResponse_init (UA_SetPublishingModeResponse *p)
static UA_INLINE UA_SetPublishingModeResponse * UA_SetPublishingModeResponse_new (void)
static UA_INLINE UA_StatusCode UA_SetPublishingModeResponse_copy (const UA_SetPublishingModeResponse *src, UA_SetPublishingModeResponse *dst)
static UA_INLINE void UA_SetPublishingModeResponse_deleteMembers (UA_SetPublishingModeResponse *p)
static UA_INLINE void UA_SetPublishingModeResponse_clear (UA_SetPublishingModeResponse *p)
static UA_INLINE void UA_SetPublishingModeResponse_delete (UA_SetPublishingModeResponse *p)
static UA_INLINE void UA_StatusChangeNotification_init (UA_StatusChangeNotification *p)
static UA_INLINE UA_StatusChangeNotification * UA_StatusChangeNotification_new (void)
static UA_INLINE UA_StatusCode UA_StatusChangeNotification_copy (const UA_StatusChangeNotification *src, UA_StatusChangeNotification *dst)
static UA_INLINE void UA_StatusChangeNotification_deleteMembers (UA_StatusChangeNotification *p)
static UA_INLINE void UA_StatusChangeNotification_clear (UA_StatusChangeNotification *p)
static UA_INLINE void UA_StatusChangeNotification_delete (UA_StatusChangeNotification *p)
static UA_INLINE void UA_NodeAttributesMask_init (UA_NodeAttributesMask *p)
static UA_INLINE UA_NodeAttributesMask * UA_NodeAttributesMask_new (void)
static UA_INLINE UA_StatusCode UA_NodeAttributesMask_copy (const UA_NodeAttributesMask *src, UA_NodeAttributesMask *dst)
static UA_INLINE void UA_NodeAttributesMask_deleteMembers (UA_NodeAttributesMask *p)
static UA_INLINE void UA_NodeAttributesMask_clear (UA_NodeAttributesMask *p)
static UA_INLINE void UA_NodeAttributesMask_delete (UA_NodeAttributesMask *p)
static UA_INLINE void UA_EventFilterResult_init (UA_EventFilterResult *p)
static UA_INLINE UA_EventFilterResult * UA_EventFilterResult_new (void)
static UA_INLINE UA_StatusCode UA_EventFilterResult_copy (const UA_EventFilterResult *src, UA_EventFilterResult *dst)
static UA_INLINE void UA_EventFilterResult_deleteMembers (UA_EventFilterResult *p)
static UA_INLINE void UA_EventFilterResult_clear (UA_EventFilterResult *p)
static UA_INLINE void UA_EventFilterResult_delete (UA_EventFilterResult *p)
static UA_INLINE void UA_MonitoredItemCreateRequest_init (UA_MonitoredItemCreateRequest *p)
static UA_INLINE UA_MonitoredItemCreateRequest * UA_MonitoredItemCreateRequest_new (void)
static UA_INLINE UA_StatusCode UA_MonitoredItemCreateRequest_copy (const UA_MonitoredItemCreateRequest *src, UA_MonitoredItemCreateRequest *dst)
static UA_INLINE void UA_MonitoredItemCreateRequest_deleteMembers (UA_MonitoredItemCreateRequest *p)
static UA_INLINE void UA_MonitoredItemCreateRequest_clear (UA_MonitoredItemCreateRequest *p)
static UA_INLINE void UA_MonitoredItemCreateRequest_delete (UA_MonitoredItemCreateRequest *p)
static UA_INLINE void UA_Range_init (UA_Range *p)
static UA_INLINE UA_Range * UA_Range_new (void)
static UA_INLINE UA_StatusCode UA_Range_copy (const UA_Range *src, UA_Range *dst)
static UA_INLINE void UA_Range_deleteMembers (UA_Range *p)
static UA_INLINE void UA_Range_clear (UA_Range *p)
static UA_INLINE void UA_Range_delete (UA_Range *p)
static UA_INLINE void UA_DataChangeNotification_init (UA_DataChangeNotification *p)
static UA_INLINE UA_DataChangeNotification * UA_DataChangeNotification_new (void)
static UA_INLINE UA_StatusCode UA_DataChangeNotification_copy (const UA_DataChangeNotification *src, UA_DataChangeNotification *dst)
static UA_INLINE void UA_DataChangeNotification_deleteMembers (UA_DataChangeNotification *p)
static UA_INLINE void UA_DataChangeNotification_clear (UA_DataChangeNotification *p)
static UA_INLINE void UA_DataChangeNotification_delete (UA_DataChangeNotification *p)
static UA_INLINE void UA_Argument_init (UA_Argument *p)
static UA_INLINE UA_Argument * UA_Argument_new (void)
static UA_INLINE UA_StatusCode UA_Argument_copy (const UA_Argument *src, UA_Argument *dst)
static UA_INLINE void UA_Argument_deleteMembers (UA_Argument *p)
static UA_INLINE void UA_Argument_clear (UA_Argument *p)
static UA_INLINE void UA_Argument_delete (UA_Argument *p)
static UA_INLINE void UA_ChannelSecurityToken_init (UA_ChannelSecurityToken *p)
static UA_INLINE UA_ChannelSecurityToken * UA_ChannelSecurityToken_new (void)
static UA_INLINE UA_StatusCode UA_ChannelSecurityToken_copy (const UA_ChannelSecurityToken *src, UA_ChannelSecurityToken *dst)
static UA_INLINE void UA_ChannelSecurityToken_deleteMembers (UA_ChannelSecurityToken *p)
static UA_INLINE void UA_ChannelSecurityToken_clear (UA_ChannelSecurityToken *p)
static UA_INLINE void UA_ChannelSecurityToken_delete (UA_ChannelSecurityToken *p)
static UA_INLINE void UA_ServerState_init (UA_ServerState *p)
static UA_INLINE UA_ServerState * UA_ServerState_new (void)
static UA_INLINE UA_StatusCode UA_ServerState_copy (const UA_ServerState *src, UA_ServerState *dst)
static UA_INLINE void UA_ServerState_deleteMembers (UA_ServerState *p)
static UA_INLINE void UA_ServerState_clear (UA_ServerState *p)
static UA_INLINE void UA_ServerState_delete (UA_ServerState *p)
static UA_INLINE void UA_EventNotificationList_init (UA_EventNotificationList *p)
static UA_INLINE UA_EventNotificationList * UA_EventNotificationList_new (void)
static UA_INLINE UA_StatusCode UA_EventNotificationList_copy (const UA_EventNotificationList *src, UA_EventNotificationList *dst)
static UA_INLINE void UA_EventNotificationList_deleteMembers (UA_EventNotificationList *p)
static UA_INLINE void UA_EventNotificationList_clear (UA_EventNotificationList *p)
static UA_INLINE void UA_EventNotificationList_delete (UA_EventNotificationList *p)
static UA_INLINE void UA_AnonymousIdentityToken_init (UA_AnonymousIdentityToken *p)
static UA_INLINE UA_AnonymousIdentityToken * UA_AnonymousIdentityToken_new (void)
static UA_INLINE UA_StatusCode UA_AnonymousIdentityToken_copy (const UA_AnonymousIdentityToken *src, UA_AnonymousIdentityToken *dst)
static UA_INLINE void UA_AnonymousIdentityToken_deleteMembers (UA_AnonymousIdentityToken *p)
static UA_INLINE void UA_AnonymousIdentityToken_clear (UA_AnonymousIdentityToken *p)
static UA_INLINE void UA_AnonymousIdentityToken_delete (UA_AnonymousIdentityToken *p)
static UA_INLINE void UA_FilterOperator_init (UA_FilterOperator *p)
static UA_INLINE UA_FilterOperator * UA_FilterOperator_new (void)
static UA_INLINE UA_StatusCode UA_FilterOperator_copy (const UA_FilterOperator *src, UA_FilterOperator *dst)
static UA_INLINE void UA_FilterOperator_deleteMembers (UA_FilterOperator *p)
static UA_INLINE void UA_FilterOperator_clear (UA_FilterOperator *p)
static UA_INLINE void UA_FilterOperator_delete (UA_FilterOperator *p)
static UA_INLINE void UA_AggregateFilter_init (UA_AggregateFilter *p)
static UA_INLINE UA_AggregateFilter * UA_AggregateFilter_new (void)
static UA_INLINE UA_StatusCode UA_AggregateFilter_copy (const UA_AggregateFilter *src, UA_AggregateFilter *dst)
static UA_INLINE void UA_AggregateFilter_deleteMembers (UA_AggregateFilter *p)
static UA_INLINE void UA_AggregateFilter_clear (UA_AggregateFilter *p)
static UA_INLINE void UA_AggregateFilter_delete (UA_AggregateFilter *p)
static UA_INLINE void UA_RepublishResponse_init (UA_RepublishResponse *p)
static UA_INLINE UA_RepublishResponse * UA_RepublishResponse_new (void)
static UA_INLINE UA_StatusCode UA_RepublishResponse_copy (const UA_RepublishResponse *src, UA_RepublishResponse *dst)
static UA_INLINE void UA_RepublishResponse_deleteMembers (UA_RepublishResponse *p)
static UA_INLINE void UA_RepublishResponse_clear (UA_RepublishResponse *p)
static UA_INLINE void UA_RepublishResponse_delete (UA_RepublishResponse *p)
static UA_INLINE void UA_DeleteSubscriptionsResponse_init (UA_DeleteSubscriptionsResponse *p)
static UA_INLINE UA_DeleteSubscriptionsResponse * UA_DeleteSubscriptionsResponse_new (void)
static UA_INLINE UA_StatusCode UA_DeleteSubscriptionsResponse_copy (const UA_DeleteSubscriptionsResponse *src, UA_DeleteSubscriptionsResponse *dst)
static UA_INLINE void UA_DeleteSubscriptionsResponse_deleteMembers (UA_DeleteSubscriptionsResponse *p)
static UA_INLINE void UA_DeleteSubscriptionsResponse_clear (UA_DeleteSubscriptionsResponse *p)
static UA_INLINE void UA_DeleteSubscriptionsResponse_delete (UA_DeleteSubscriptionsResponse *p)
static UA_INLINE void UA_RegisterNodesRequest_init (UA_RegisterNodesRequest *p)
static UA_INLINE UA_RegisterNodesRequest * UA_RegisterNodesRequest_new (void)
static UA_INLINE UA_StatusCode UA_RegisterNodesRequest_copy (const UA_RegisterNodesRequest *src, UA_RegisterNodesRequest *dst)
static UA_INLINE void UA_RegisterNodesRequest_deleteMembers (UA_RegisterNodesRequest *p)
static UA_INLINE void UA_RegisterNodesRequest_clear (UA_RegisterNodesRequest *p)
static UA_INLINE void UA_RegisterNodesRequest_delete (UA_RegisterNodesRequest *p)
static UA_INLINE void UA_MethodAttributes_init (UA_MethodAttributes *p)
static UA_INLINE UA_MethodAttributes * UA_MethodAttributes_new (void)
static UA_INLINE UA_StatusCode UA_MethodAttributes_copy (const UA_MethodAttributes *src, UA_MethodAttributes *dst)
static UA_INLINE void UA_MethodAttributes_deleteMembers (UA_MethodAttributes *p)
static UA_INLINE void UA_MethodAttributes_clear (UA_MethodAttributes *p)
static UA_INLINE void UA_MethodAttributes_delete (UA_MethodAttributes *p)
static UA_INLINE void UA_UserNameIdentityToken_init (UA_UserNameIdentityToken *p)
static UA_INLINE UA_UserNameIdentityToken * UA_UserNameIdentityToken_new (void)
static UA_INLINE UA_StatusCode UA_UserNameIdentityToken_copy (const UA_UserNameIdentityToken *src, UA_UserNameIdentityToken *dst)
static UA_INLINE void UA_UserNameIdentityToken_deleteMembers (UA_UserNameIdentityToken *p)
static UA_INLINE void UA_UserNameIdentityToken_clear (UA_UserNameIdentityToken *p)
static UA_INLINE void UA_UserNameIdentityToken_delete (UA_UserNameIdentityToken *p)
static UA_INLINE void UA_UnregisterNodesRequest_init (UA_UnregisterNodesRequest *p)
static UA_INLINE UA_UnregisterNodesRequest * UA_UnregisterNodesRequest_new (void)
static UA_INLINE UA_StatusCode UA_UnregisterNodesRequest_copy (const UA_UnregisterNodesRequest *src, UA_UnregisterNodesRequest *dst)
static UA_INLINE void UA_UnregisterNodesRequest_deleteMembers (UA_UnregisterNodesRequest *p)
static UA_INLINE void UA_UnregisterNodesRequest_clear (UA_UnregisterNodesRequest *p)
static UA_INLINE void UA_UnregisterNodesRequest_delete (UA_UnregisterNodesRequest *p)
static UA_INLINE void UA_OpenSecureChannelResponse_init (UA_OpenSecureChannelResponse *p)
static UA_INLINE UA_OpenSecureChannelResponse * UA_OpenSecureChannelResponse_new (void)
static UA_INLINE UA_StatusCode UA_OpenSecureChannelResponse_copy (const UA_OpenSecureChannelResponse *src, UA_OpenSecureChannelResponse *dst)
static UA_INLINE void UA_OpenSecureChannelResponse_deleteMembers (UA_OpenSecureChannelResponse *p)
static UA_INLINE void UA_OpenSecureChannelResponse_clear (UA_OpenSecureChannelResponse *p)
static UA_INLINE void UA_OpenSecureChannelResponse_delete (UA_OpenSecureChannelResponse *p)
static UA_INLINE void UA_SetTriggeringResponse_init (UA_SetTriggeringResponse *p)
static UA_INLINE UA_SetTriggeringResponse * UA_SetTriggeringResponse_new (void)
static UA_INLINE UA_StatusCode UA_SetTriggeringResponse_copy (const UA_SetTriggeringResponse *src, UA_SetTriggeringResponse *dst)
static UA_INLINE void UA_SetTriggeringResponse_deleteMembers (UA_SetTriggeringResponse *p)
static UA_INLINE void UA_SetTriggeringResponse_clear (UA_SetTriggeringResponse *p)
static UA_INLINE void UA_SetTriggeringResponse_delete (UA_SetTriggeringResponse *p)
static UA_INLINE void UA_SimpleAttributeOperand_init (UA_SimpleAttributeOperand *p)
static UA_INLINE UA_SimpleAttributeOperand * UA_SimpleAttributeOperand_new (void)
static UA_INLINE UA_StatusCode UA_SimpleAttributeOperand_copy (const UA_SimpleAttributeOperand *src, UA_SimpleAttributeOperand *dst)
static UA_INLINE void UA_SimpleAttributeOperand_deleteMembers (UA_SimpleAttributeOperand *p)
static UA_INLINE void UA_SimpleAttributeOperand_clear (UA_SimpleAttributeOperand *p)
static UA_INLINE void UA_SimpleAttributeOperand_delete (UA_SimpleAttributeOperand *p)
static UA_INLINE void UA_RepublishRequest_init (UA_RepublishRequest *p)
static UA_INLINE UA_RepublishRequest * UA_RepublishRequest_new (void)
static UA_INLINE UA_StatusCode UA_RepublishRequest_copy (const UA_RepublishRequest *src, UA_RepublishRequest *dst)
static UA_INLINE void UA_RepublishRequest_deleteMembers (UA_RepublishRequest *p)
static UA_INLINE void UA_RepublishRequest_clear (UA_RepublishRequest *p)
static UA_INLINE void UA_RepublishRequest_delete (UA_RepublishRequest *p)
static UA_INLINE void UA_RegisterNodesResponse_init (UA_RegisterNodesResponse *p)
static UA_INLINE UA_RegisterNodesResponse * UA_RegisterNodesResponse_new (void)
static UA_INLINE UA_StatusCode UA_RegisterNodesResponse_copy (const UA_RegisterNodesResponse *src, UA_RegisterNodesResponse *dst)
static UA_INLINE void UA_RegisterNodesResponse_deleteMembers (UA_RegisterNodesResponse *p)
static UA_INLINE void UA_RegisterNodesResponse_clear (UA_RegisterNodesResponse *p)
static UA_INLINE void UA_RegisterNodesResponse_delete (UA_RegisterNodesResponse *p)
static UA_INLINE void UA_ModifyMonitoredItemsResponse_init (UA_ModifyMonitoredItemsResponse *p)
static UA_INLINE UA_ModifyMonitoredItemsResponse * UA_ModifyMonitoredItemsResponse_new (void)
static UA_INLINE UA_StatusCode UA_ModifyMonitoredItemsResponse_copy (const UA_ModifyMonitoredItemsResponse *src, UA_ModifyMonitoredItemsResponse *dst)
static UA_INLINE void UA_ModifyMonitoredItemsResponse_deleteMembers (UA_ModifyMonitoredItemsResponse *p)
static UA_INLINE void UA_ModifyMonitoredItemsResponse_clear (UA_ModifyMonitoredItemsResponse *p)
static UA_INLINE void UA_ModifyMonitoredItemsResponse_delete (UA_ModifyMonitoredItemsResponse *p)
static UA_INLINE void UA_DeleteSubscriptionsRequest_init (UA_DeleteSubscriptionsRequest *p)
static UA_INLINE UA_DeleteSubscriptionsRequest * UA_DeleteSubscriptionsRequest_new (void)
static UA_INLINE UA_StatusCode UA_DeleteSubscriptionsRequest_copy (const UA_DeleteSubscriptionsRequest *src, UA_DeleteSubscriptionsRequest *dst)
static UA_INLINE void UA_DeleteSubscriptionsRequest_deleteMembers (UA_DeleteSubscriptionsRequest *p)
static UA_INLINE void UA_DeleteSubscriptionsRequest_clear (UA_DeleteSubscriptionsRequest *p)
static UA_INLINE void UA_DeleteSubscriptionsRequest_delete (UA_DeleteSubscriptionsRequest *p)
static UA_INLINE void UA_RedundancySupport_init (UA_RedundancySupport *p)
static UA_INLINE UA_RedundancySupport * UA_RedundancySupport_new (void)
static UA_INLINE UA_StatusCode UA_RedundancySupport_copy (const UA_RedundancySupport *src, UA_RedundancySupport *dst)
static UA_INLINE void UA_RedundancySupport_deleteMembers (UA_RedundancySupport *p)
static UA_INLINE void UA_RedundancySupport_clear (UA_RedundancySupport *p)
static UA_INLINE void UA_RedundancySupport_delete (UA_RedundancySupport *p)
static UA_INLINE void UA_BrowsePath_init (UA_BrowsePath *p)
static UA_INLINE UA_BrowsePath * UA_BrowsePath_new (void)
static UA_INLINE UA_StatusCode UA_BrowsePath_copy (const UA_BrowsePath *src, UA_BrowsePath *dst)
static UA_INLINE void UA_BrowsePath_deleteMembers (UA_BrowsePath *p)
static UA_INLINE void UA_BrowsePath_clear (UA_BrowsePath *p)
static UA_INLINE void UA_BrowsePath_delete (UA_BrowsePath *p)
static UA_INLINE void UA_ObjectAttributes_init (UA_ObjectAttributes *p)
static UA_INLINE UA_ObjectAttributes * UA_ObjectAttributes_new (void)
static UA_INLINE UA_StatusCode UA_ObjectAttributes_copy (const UA_ObjectAttributes *src, UA_ObjectAttributes *dst)
static UA_INLINE void UA_ObjectAttributes_deleteMembers (UA_ObjectAttributes *p)
static UA_INLINE void UA_ObjectAttributes_clear (UA_ObjectAttributes *p)
static UA_INLINE void UA_ObjectAttributes_delete (UA_ObjectAttributes *p)
static UA_INLINE void UA_PublishRequest_init (UA_PublishRequest *p)
static UA_INLINE UA_PublishRequest * UA_PublishRequest_new (void)
static UA_INLINE UA_StatusCode UA_PublishRequest_copy (const UA_PublishRequest *src, UA_PublishRequest *dst)
static UA_INLINE void UA_PublishRequest_deleteMembers (UA_PublishRequest *p)
static UA_INLINE void UA_PublishRequest_clear (UA_PublishRequest *p)
static UA_INLINE void UA_PublishRequest_delete (UA_PublishRequest *p)
static UA_INLINE void UA_FindServersRequest_init (UA_FindServersRequest *p)
static UA_INLINE UA_FindServersRequest * UA_FindServersRequest_new (void)
static UA_INLINE UA_StatusCode UA_FindServersRequest_copy (const UA_FindServersRequest *src, UA_FindServersRequest *dst)
static UA_INLINE void UA_FindServersRequest_deleteMembers (UA_FindServersRequest *p)
static UA_INLINE void UA_FindServersRequest_clear (UA_FindServersRequest *p)
static UA_INLINE void UA_FindServersRequest_delete (UA_FindServersRequest *p)
static UA_INLINE void UA_FindServersOnNetworkResponse_init (UA_FindServersOnNetworkResponse *p)
static UA_INLINE UA_FindServersOnNetworkResponse * UA_FindServersOnNetworkResponse_new (void)
static UA_INLINE UA_StatusCode UA_FindServersOnNetworkResponse_copy (const UA_FindServersOnNetworkResponse *src, UA_FindServersOnNetworkResponse *dst)
static UA_INLINE void UA_FindServersOnNetworkResponse_deleteMembers (UA_FindServersOnNetworkResponse *p)
static UA_INLINE void UA_FindServersOnNetworkResponse_clear (UA_FindServersOnNetworkResponse *p)
static UA_INLINE void UA_FindServersOnNetworkResponse_delete (UA_FindServersOnNetworkResponse *p)
static UA_INLINE void UA_ReferenceDescription_init (UA_ReferenceDescription *p)
static UA_INLINE UA_ReferenceDescription * UA_ReferenceDescription_new (void)
static UA_INLINE UA_StatusCode UA_ReferenceDescription_copy (const UA_ReferenceDescription *src, UA_ReferenceDescription *dst)
static UA_INLINE void UA_ReferenceDescription_deleteMembers (UA_ReferenceDescription *p)
static UA_INLINE void UA_ReferenceDescription_clear (UA_ReferenceDescription *p)
static UA_INLINE void UA_ReferenceDescription_delete (UA_ReferenceDescription *p)
static UA_INLINE void UA_CreateSubscriptionRequest_init (UA_CreateSubscriptionRequest *p)
static UA_INLINE UA_CreateSubscriptionRequest * UA_CreateSubscriptionRequest_new (void)
static UA_INLINE UA_StatusCode UA_CreateSubscriptionRequest_copy (const UA_CreateSubscriptionRequest *src, UA_CreateSubscriptionRequest *dst)
static UA_INLINE void UA_CreateSubscriptionRequest_deleteMembers (UA_CreateSubscriptionRequest *p)
static UA_INLINE void UA_CreateSubscriptionRequest_clear (UA_CreateSubscriptionRequest *p)
static UA_INLINE void UA_CreateSubscriptionRequest_delete (UA_CreateSubscriptionRequest *p)
static UA_INLINE void UA_FindServersOnNetworkRequest_init (UA_FindServersOnNetworkRequest *p)
static UA_INLINE UA_FindServersOnNetworkRequest * UA_FindServersOnNetworkRequest_new (void)
static UA_INLINE UA_StatusCode UA_FindServersOnNetworkRequest_copy (const UA_FindServersOnNetworkRequest *src, UA_FindServersOnNetworkRequest *dst)
static UA_INLINE void UA_FindServersOnNetworkRequest_deleteMembers (UA_FindServersOnNetworkRequest *p)
static UA_INLINE void UA_FindServersOnNetworkRequest_clear (UA_FindServersOnNetworkRequest *p)
static UA_INLINE void UA_FindServersOnNetworkRequest_delete (UA_FindServersOnNetworkRequest *p)
static UA_INLINE void UA_CallResponse_init (UA_CallResponse *p)
static UA_INLINE UA_CallResponse * UA_CallResponse_new (void)
static UA_INLINE UA_StatusCode UA_CallResponse_copy (const UA_CallResponse *src, UA_CallResponse *dst)
static UA_INLINE void UA_CallResponse_deleteMembers (UA_CallResponse *p)
static UA_INLINE void UA_CallResponse_clear (UA_CallResponse *p)
static UA_INLINE void UA_CallResponse_delete (UA_CallResponse *p)
static UA_INLINE void UA_DeleteNodesResponse_init (UA_DeleteNodesResponse *p)
static UA_INLINE UA_DeleteNodesResponse * UA_DeleteNodesResponse_new (void)
static UA_INLINE UA_StatusCode UA_DeleteNodesResponse_copy (const UA_DeleteNodesResponse *src, UA_DeleteNodesResponse *dst)
static UA_INLINE void UA_DeleteNodesResponse_deleteMembers (UA_DeleteNodesResponse *p)
static UA_INLINE void UA_DeleteNodesResponse_clear (UA_DeleteNodesResponse *p)
static UA_INLINE void UA_DeleteNodesResponse_delete (UA_DeleteNodesResponse *p)
static UA_INLINE void UA_ModifyMonitoredItemsRequest_init (UA_ModifyMonitoredItemsRequest *p)
static UA_INLINE UA_ModifyMonitoredItemsRequest * UA_ModifyMonitoredItemsRequest_new (void)
static UA_INLINE UA_StatusCode UA_ModifyMonitoredItemsRequest_copy (const UA_ModifyMonitoredItemsRequest *src, UA_ModifyMonitoredItemsRequest *dst)
static UA_INLINE void UA_ModifyMonitoredItemsRequest_deleteMembers (UA_ModifyMonitoredItemsRequest *p)
static UA_INLINE void UA_ModifyMonitoredItemsRequest_clear (UA_ModifyMonitoredItemsRequest *p)
static UA_INLINE void UA_ModifyMonitoredItemsRequest_delete (UA_ModifyMonitoredItemsRequest *p)
static UA_INLINE void UA_ServiceFault_init (UA_ServiceFault *p)
static UA_INLINE UA_ServiceFault * UA_ServiceFault_new (void)
static UA_INLINE UA_StatusCode UA_ServiceFault_copy (const UA_ServiceFault *src, UA_ServiceFault *dst)
static UA_INLINE void UA_ServiceFault_deleteMembers (UA_ServiceFault *p)
static UA_INLINE void UA_ServiceFault_clear (UA_ServiceFault *p)
static UA_INLINE void UA_ServiceFault_delete (UA_ServiceFault *p)
static UA_INLINE void UA_PublishResponse_init (UA_PublishResponse *p)
static UA_INLINE UA_PublishResponse * UA_PublishResponse_new (void)
static UA_INLINE UA_StatusCode UA_PublishResponse_copy (const UA_PublishResponse *src, UA_PublishResponse *dst)
static UA_INLINE void UA_PublishResponse_deleteMembers (UA_PublishResponse *p)
static UA_INLINE void UA_PublishResponse_clear (UA_PublishResponse *p)
static UA_INLINE void UA_PublishResponse_delete (UA_PublishResponse *p)
static UA_INLINE void UA_CreateMonitoredItemsRequest_init (UA_CreateMonitoredItemsRequest *p)
static UA_INLINE UA_CreateMonitoredItemsRequest * UA_CreateMonitoredItemsRequest_new (void)
static UA_INLINE UA_StatusCode UA_CreateMonitoredItemsRequest_copy (const UA_CreateMonitoredItemsRequest *src, UA_CreateMonitoredItemsRequest *dst)
static UA_INLINE void UA_CreateMonitoredItemsRequest_deleteMembers (UA_CreateMonitoredItemsRequest *p)
static UA_INLINE void UA_CreateMonitoredItemsRequest_clear (UA_CreateMonitoredItemsRequest *p)
static UA_INLINE void UA_CreateMonitoredItemsRequest_delete (UA_CreateMonitoredItemsRequest *p)
static UA_INLINE void UA_OpenSecureChannelRequest_init (UA_OpenSecureChannelRequest *p)
static UA_INLINE UA_OpenSecureChannelRequest * UA_OpenSecureChannelRequest_new (void)
static UA_INLINE UA_StatusCode UA_OpenSecureChannelRequest_copy (const UA_OpenSecureChannelRequest *src, UA_OpenSecureChannelRequest *dst)
static UA_INLINE void UA_OpenSecureChannelRequest_deleteMembers (UA_OpenSecureChannelRequest *p)
static UA_INLINE void UA_OpenSecureChannelRequest_clear (UA_OpenSecureChannelRequest *p)
static UA_INLINE void UA_OpenSecureChannelRequest_delete (UA_OpenSecureChannelRequest *p)
static UA_INLINE void UA_CloseSessionRequest_init (UA_CloseSessionRequest *p)
static UA_INLINE UA_CloseSessionRequest * UA_CloseSessionRequest_new (void)
static UA_INLINE UA_StatusCode UA_CloseSessionRequest_copy (const UA_CloseSessionRequest *src, UA_CloseSessionRequest *dst)
static UA_INLINE void UA_CloseSessionRequest_deleteMembers (UA_CloseSessionRequest *p)
static UA_INLINE void UA_CloseSessionRequest_clear (UA_CloseSessionRequest *p)
static UA_INLINE void UA_CloseSessionRequest_delete (UA_CloseSessionRequest *p)
static UA_INLINE void UA_SetTriggeringRequest_init (UA_SetTriggeringRequest *p)
static UA_INLINE UA_SetTriggeringRequest * UA_SetTriggeringRequest_new (void)
static UA_INLINE UA_StatusCode UA_SetTriggeringRequest_copy (const UA_SetTriggeringRequest *src, UA_SetTriggeringRequest *dst)
static UA_INLINE void UA_SetTriggeringRequest_deleteMembers (UA_SetTriggeringRequest *p)
static UA_INLINE void UA_SetTriggeringRequest_clear (UA_SetTriggeringRequest *p)
static UA_INLINE void UA_SetTriggeringRequest_delete (UA_SetTriggeringRequest *p)
static UA_INLINE void UA_BrowseResult_init (UA_BrowseResult *p)
static UA_INLINE UA_BrowseResult * UA_BrowseResult_new (void)
static UA_INLINE UA_StatusCode UA_BrowseResult_copy (const UA_BrowseResult *src, UA_BrowseResult *dst)
static UA_INLINE void UA_BrowseResult_deleteMembers (UA_BrowseResult *p)
static UA_INLINE void UA_BrowseResult_clear (UA_BrowseResult *p)
static UA_INLINE void UA_BrowseResult_delete (UA_BrowseResult *p)
static UA_INLINE void UA_AddReferencesRequest_init (UA_AddReferencesRequest *p)
static UA_INLINE UA_AddReferencesRequest * UA_AddReferencesRequest_new (void)
static UA_INLINE UA_StatusCode UA_AddReferencesRequest_copy (const UA_AddReferencesRequest *src, UA_AddReferencesRequest *dst)
static UA_INLINE void UA_AddReferencesRequest_deleteMembers (UA_AddReferencesRequest *p)
static UA_INLINE void UA_AddReferencesRequest_clear (UA_AddReferencesRequest *p)
static UA_INLINE void UA_AddReferencesRequest_delete (UA_AddReferencesRequest *p)
static UA_INLINE void UA_AddNodesItem_init (UA_AddNodesItem *p)
static UA_INLINE UA_AddNodesItem * UA_AddNodesItem_new (void)
static UA_INLINE UA_StatusCode UA_AddNodesItem_copy (const UA_AddNodesItem *src, UA_AddNodesItem *dst)
static UA_INLINE void UA_AddNodesItem_deleteMembers (UA_AddNodesItem *p)
static UA_INLINE void UA_AddNodesItem_clear (UA_AddNodesItem *p)
static UA_INLINE void UA_AddNodesItem_delete (UA_AddNodesItem *p)
static UA_INLINE void UA_ServerStatusDataType_init (UA_ServerStatusDataType *p)
static UA_INLINE UA_ServerStatusDataType * UA_ServerStatusDataType_new (void)
static UA_INLINE UA_StatusCode UA_ServerStatusDataType_copy (const UA_ServerStatusDataType *src, UA_ServerStatusDataType *dst)
static UA_INLINE void UA_ServerStatusDataType_deleteMembers (UA_ServerStatusDataType *p)
static UA_INLINE void UA_ServerStatusDataType_clear (UA_ServerStatusDataType *p)
static UA_INLINE void UA_ServerStatusDataType_delete (UA_ServerStatusDataType *p)
static UA_INLINE void UA_BrowseNextResponse_init (UA_BrowseNextResponse *p)
static UA_INLINE UA_BrowseNextResponse * UA_BrowseNextResponse_new (void)
static UA_INLINE UA_StatusCode UA_BrowseNextResponse_copy (const UA_BrowseNextResponse *src, UA_BrowseNextResponse *dst)
static UA_INLINE void UA_BrowseNextResponse_deleteMembers (UA_BrowseNextResponse *p)
static UA_INLINE void UA_BrowseNextResponse_clear (UA_BrowseNextResponse *p)
static UA_INLINE void UA_BrowseNextResponse_delete (UA_BrowseNextResponse *p)
static UA_INLINE void UA_RegisteredServer_init (UA_RegisteredServer *p)
static UA_INLINE UA_RegisteredServer * UA_RegisteredServer_new (void)
static UA_INLINE UA_StatusCode UA_RegisteredServer_copy (const UA_RegisteredServer *src, UA_RegisteredServer *dst)
static UA_INLINE void UA_RegisteredServer_deleteMembers (UA_RegisteredServer *p)
static UA_INLINE void UA_RegisteredServer_clear (UA_RegisteredServer *p)
static UA_INLINE void UA_RegisteredServer_delete (UA_RegisteredServer *p)
static UA_INLINE void UA_ApplicationDescription_init (UA_ApplicationDescription *p)
static UA_INLINE UA_ApplicationDescription * UA_ApplicationDescription_new (void)
static UA_INLINE UA_StatusCode UA_ApplicationDescription_copy (const UA_ApplicationDescription *src, UA_ApplicationDescription *dst)
static UA_INLINE void UA_ApplicationDescription_deleteMembers (UA_ApplicationDescription *p)
static UA_INLINE void UA_ApplicationDescription_clear (UA_ApplicationDescription *p)
static UA_INLINE void UA_ApplicationDescription_delete (UA_ApplicationDescription *p)
static UA_INLINE void UA_ReadRequest_init (UA_ReadRequest *p)
static UA_INLINE UA_ReadRequest * UA_ReadRequest_new (void)
static UA_INLINE UA_StatusCode UA_ReadRequest_copy (const UA_ReadRequest *src, UA_ReadRequest *dst)
static UA_INLINE void UA_ReadRequest_deleteMembers (UA_ReadRequest *p)
static UA_INLINE void UA_ReadRequest_clear (UA_ReadRequest *p)
static UA_INLINE void UA_ReadRequest_delete (UA_ReadRequest *p)
static UA_INLINE void UA_ActivateSessionRequest_init (UA_ActivateSessionRequest *p)
static UA_INLINE UA_ActivateSessionRequest * UA_ActivateSessionRequest_new (void)
static UA_INLINE UA_StatusCode UA_ActivateSessionRequest_copy (const UA_ActivateSessionRequest *src, UA_ActivateSessionRequest *dst)
static UA_INLINE void UA_ActivateSessionRequest_deleteMembers (UA_ActivateSessionRequest *p)
static UA_INLINE void UA_ActivateSessionRequest_clear (UA_ActivateSessionRequest *p)
static UA_INLINE void UA_ActivateSessionRequest_delete (UA_ActivateSessionRequest *p)
static UA_INLINE void UA_BrowsePathResult_init (UA_BrowsePathResult *p)
static UA_INLINE UA_BrowsePathResult * UA_BrowsePathResult_new (void)
static UA_INLINE UA_StatusCode UA_BrowsePathResult_copy (const UA_BrowsePathResult *src, UA_BrowsePathResult *dst)
static UA_INLINE void UA_BrowsePathResult_deleteMembers (UA_BrowsePathResult *p)
static UA_INLINE void UA_BrowsePathResult_clear (UA_BrowsePathResult *p)
static UA_INLINE void UA_BrowsePathResult_delete (UA_BrowsePathResult *p)
static UA_INLINE void UA_AddNodesRequest_init (UA_AddNodesRequest *p)
static UA_INLINE UA_AddNodesRequest * UA_AddNodesRequest_new (void)
static UA_INLINE UA_StatusCode UA_AddNodesRequest_copy (const UA_AddNodesRequest *src, UA_AddNodesRequest *dst)
static UA_INLINE void UA_AddNodesRequest_deleteMembers (UA_AddNodesRequest *p)
static UA_INLINE void UA_AddNodesRequest_clear (UA_AddNodesRequest *p)
static UA_INLINE void UA_AddNodesRequest_delete (UA_AddNodesRequest *p)
static UA_INLINE void UA_BrowseRequest_init (UA_BrowseRequest *p)
static UA_INLINE UA_BrowseRequest * UA_BrowseRequest_new (void)
static UA_INLINE UA_StatusCode UA_BrowseRequest_copy (const UA_BrowseRequest *src, UA_BrowseRequest *dst)
static UA_INLINE void UA_BrowseRequest_deleteMembers (UA_BrowseRequest *p)
static UA_INLINE void UA_BrowseRequest_clear (UA_BrowseRequest *p)
static UA_INLINE void UA_BrowseRequest_delete (UA_BrowseRequest *p)
static UA_INLINE void UA_WriteRequest_init (UA_WriteRequest *p)
static UA_INLINE UA_WriteRequest * UA_WriteRequest_new (void)
static UA_INLINE UA_StatusCode UA_WriteRequest_copy (const UA_WriteRequest *src, UA_WriteRequest *dst)
static UA_INLINE void UA_WriteRequest_deleteMembers (UA_WriteRequest *p)
static UA_INLINE void UA_WriteRequest_clear (UA_WriteRequest *p)
static UA_INLINE void UA_WriteRequest_delete (UA_WriteRequest *p)
static UA_INLINE void UA_AddNodesResponse_init (UA_AddNodesResponse *p)
static UA_INLINE UA_AddNodesResponse * UA_AddNodesResponse_new (void)
static UA_INLINE UA_StatusCode UA_AddNodesResponse_copy (const UA_AddNodesResponse *src, UA_AddNodesResponse *dst)
static UA_INLINE void UA_AddNodesResponse_deleteMembers (UA_AddNodesResponse *p)
static UA_INLINE void UA_AddNodesResponse_clear (UA_AddNodesResponse *p)
static UA_INLINE void UA_AddNodesResponse_delete (UA_AddNodesResponse *p)
static UA_INLINE void UA_RegisterServer2Request_init (UA_RegisterServer2Request *p)
static UA_INLINE UA_RegisterServer2Request * UA_RegisterServer2Request_new (void)
static UA_INLINE UA_StatusCode UA_RegisterServer2Request_copy (const UA_RegisterServer2Request *src, UA_RegisterServer2Request *dst)
static UA_INLINE void UA_RegisterServer2Request_deleteMembers (UA_RegisterServer2Request *p)
static UA_INLINE void UA_RegisterServer2Request_clear (UA_RegisterServer2Request *p)
static UA_INLINE void UA_RegisterServer2Request_delete (UA_RegisterServer2Request *p)
static UA_INLINE void UA_AttributeOperand_init (UA_AttributeOperand *p)
static UA_INLINE UA_AttributeOperand * UA_AttributeOperand_new (void)
static UA_INLINE UA_StatusCode UA_AttributeOperand_copy (const UA_AttributeOperand *src, UA_AttributeOperand *dst)
static UA_INLINE void UA_AttributeOperand_deleteMembers (UA_AttributeOperand *p)
static UA_INLINE void UA_AttributeOperand_clear (UA_AttributeOperand *p)
static UA_INLINE void UA_AttributeOperand_delete (UA_AttributeOperand *p)
static UA_INLINE void UA_DataChangeFilter_init (UA_DataChangeFilter *p)
static UA_INLINE UA_DataChangeFilter * UA_DataChangeFilter_new (void)
static UA_INLINE UA_StatusCode UA_DataChangeFilter_copy (const UA_DataChangeFilter *src, UA_DataChangeFilter *dst)
static UA_INLINE void UA_DataChangeFilter_deleteMembers (UA_DataChangeFilter *p)
static UA_INLINE void UA_DataChangeFilter_clear (UA_DataChangeFilter *p)
static UA_INLINE void UA_DataChangeFilter_delete (UA_DataChangeFilter *p)
static UA_INLINE void UA_EndpointDescription_init (UA_EndpointDescription *p)
static UA_INLINE UA_EndpointDescription * UA_EndpointDescription_new (void)
static UA_INLINE UA_StatusCode UA_EndpointDescription_copy (const UA_EndpointDescription *src, UA_EndpointDescription *dst)
static UA_INLINE void UA_EndpointDescription_deleteMembers (UA_EndpointDescription *p)
static UA_INLINE void UA_EndpointDescription_clear (UA_EndpointDescription *p)
static UA_INLINE void UA_EndpointDescription_delete (UA_EndpointDescription *p)
static UA_INLINE void UA_DeleteReferencesRequest_init (UA_DeleteReferencesRequest *p)
static UA_INLINE UA_DeleteReferencesRequest * UA_DeleteReferencesRequest_new (void)
static UA_INLINE UA_StatusCode UA_DeleteReferencesRequest_copy (const UA_DeleteReferencesRequest *src, UA_DeleteReferencesRequest *dst)
static UA_INLINE void UA_DeleteReferencesRequest_deleteMembers (UA_DeleteReferencesRequest *p)
static UA_INLINE void UA_DeleteReferencesRequest_clear (UA_DeleteReferencesRequest *p)
static UA_INLINE void UA_DeleteReferencesRequest_delete (UA_DeleteReferencesRequest *p)
static UA_INLINE void UA_TranslateBrowsePathsToNodeIdsRequest_init (UA_TranslateBrowsePathsToNodeIdsRequest *p)
static UA_INLINE UA_TranslateBrowsePathsToNodeIdsRequest * UA_TranslateBrowsePathsToNodeIdsRequest_new (void)
static UA_INLINE UA_StatusCode UA_TranslateBrowsePathsToNodeIdsRequest_copy (const UA_TranslateBrowsePathsToNodeIdsRequest *src, UA_TranslateBrowsePathsToNodeIdsRequest *dst)
static UA_INLINE void UA_TranslateBrowsePathsToNodeIdsRequest_deleteMembers (UA_TranslateBrowsePathsToNodeIdsRequest *p)
static UA_INLINE void UA_TranslateBrowsePathsToNodeIdsRequest_clear (UA_TranslateBrowsePathsToNodeIdsRequest *p)
static UA_INLINE void UA_TranslateBrowsePathsToNodeIdsRequest_delete (UA_TranslateBrowsePathsToNodeIdsRequest *p)
static UA_INLINE void UA_FindServersResponse_init (UA_FindServersResponse *p)
static UA_INLINE UA_FindServersResponse * UA_FindServersResponse_new (void)
static UA_INLINE UA_StatusCode UA_FindServersResponse_copy (const UA_FindServersResponse *src, UA_FindServersResponse *dst)
static UA_INLINE void UA_FindServersResponse_deleteMembers (UA_FindServersResponse *p)
static UA_INLINE void UA_FindServersResponse_clear (UA_FindServersResponse *p)
static UA_INLINE void UA_FindServersResponse_delete (UA_FindServersResponse *p)
static UA_INLINE void UA_CreateSessionRequest_init (UA_CreateSessionRequest *p)
static UA_INLINE UA_CreateSessionRequest * UA_CreateSessionRequest_new (void)
static UA_INLINE UA_StatusCode UA_CreateSessionRequest_copy (const UA_CreateSessionRequest *src, UA_CreateSessionRequest *dst)
static UA_INLINE void UA_CreateSessionRequest_deleteMembers (UA_CreateSessionRequest *p)
static UA_INLINE void UA_CreateSessionRequest_clear (UA_CreateSessionRequest *p)
static UA_INLINE void UA_CreateSessionRequest_delete (UA_CreateSessionRequest *p)
static UA_INLINE void UA_ContentFilterElement_init (UA_ContentFilterElement *p)
static UA_INLINE UA_ContentFilterElement * UA_ContentFilterElement_new (void)
static UA_INLINE UA_StatusCode UA_ContentFilterElement_copy (const UA_ContentFilterElement *src, UA_ContentFilterElement *dst)
static UA_INLINE void UA_ContentFilterElement_deleteMembers (UA_ContentFilterElement *p)
static UA_INLINE void UA_ContentFilterElement_clear (UA_ContentFilterElement *p)
static UA_INLINE void UA_ContentFilterElement_delete (UA_ContentFilterElement *p)
static UA_INLINE void UA_RegisterServerRequest_init (UA_RegisterServerRequest *p)
static UA_INLINE UA_RegisterServerRequest * UA_RegisterServerRequest_new (void)
static UA_INLINE UA_StatusCode UA_RegisterServerRequest_copy (const UA_RegisterServerRequest *src, UA_RegisterServerRequest *dst)
static UA_INLINE void UA_RegisterServerRequest_deleteMembers (UA_RegisterServerRequest *p)
static UA_INLINE void UA_RegisterServerRequest_clear (UA_RegisterServerRequest *p)
static UA_INLINE void UA_RegisterServerRequest_delete (UA_RegisterServerRequest *p)
static UA_INLINE void UA_TranslateBrowsePathsToNodeIdsResponse_init (UA_TranslateBrowsePathsToNodeIdsResponse *p)
static UA_INLINE UA_TranslateBrowsePathsToNodeIdsResponse * UA_TranslateBrowsePathsToNodeIdsResponse_new (void)
static UA_INLINE UA_StatusCode UA_TranslateBrowsePathsToNodeIdsResponse_copy (const UA_TranslateBrowsePathsToNodeIdsResponse *src, UA_TranslateBrowsePathsToNodeIdsResponse *dst)
static UA_INLINE void UA_TranslateBrowsePathsToNodeIdsResponse_deleteMembers (UA_TranslateBrowsePathsToNodeIdsResponse *p)
static UA_INLINE void UA_TranslateBrowsePathsToNodeIdsResponse_clear (UA_TranslateBrowsePathsToNodeIdsResponse *p)
static UA_INLINE void UA_TranslateBrowsePathsToNodeIdsResponse_delete (UA_TranslateBrowsePathsToNodeIdsResponse *p)
static UA_INLINE void UA_BrowseResponse_init (UA_BrowseResponse *p)
static UA_INLINE UA_BrowseResponse * UA_BrowseResponse_new (void)
static UA_INLINE UA_StatusCode UA_BrowseResponse_copy (const UA_BrowseResponse *src, UA_BrowseResponse *dst)
static UA_INLINE void UA_BrowseResponse_deleteMembers (UA_BrowseResponse *p)
static UA_INLINE void UA_BrowseResponse_clear (UA_BrowseResponse *p)
static UA_INLINE void UA_BrowseResponse_delete (UA_BrowseResponse *p)
static UA_INLINE void UA_CreateSessionResponse_init (UA_CreateSessionResponse *p)
static UA_INLINE UA_CreateSessionResponse * UA_CreateSessionResponse_new (void)
static UA_INLINE UA_StatusCode UA_CreateSessionResponse_copy (const UA_CreateSessionResponse *src, UA_CreateSessionResponse *dst)
static UA_INLINE void UA_CreateSessionResponse_deleteMembers (UA_CreateSessionResponse *p)
static UA_INLINE void UA_CreateSessionResponse_clear (UA_CreateSessionResponse *p)
static UA_INLINE void UA_CreateSessionResponse_delete (UA_CreateSessionResponse *p)
static UA_INLINE void UA_ContentFilter_init (UA_ContentFilter *p)
static UA_INLINE UA_ContentFilter * UA_ContentFilter_new (void)
static UA_INLINE UA_StatusCode UA_ContentFilter_copy (const UA_ContentFilter *src, UA_ContentFilter *dst)
static UA_INLINE void UA_ContentFilter_deleteMembers (UA_ContentFilter *p)
static UA_INLINE void UA_ContentFilter_clear (UA_ContentFilter *p)
static UA_INLINE void UA_ContentFilter_delete (UA_ContentFilter *p)
static UA_INLINE void UA_GetEndpointsResponse_init (UA_GetEndpointsResponse *p)
static UA_INLINE UA_GetEndpointsResponse * UA_GetEndpointsResponse_new (void)
static UA_INLINE UA_StatusCode UA_GetEndpointsResponse_copy (const UA_GetEndpointsResponse *src, UA_GetEndpointsResponse *dst)
static UA_INLINE void UA_GetEndpointsResponse_deleteMembers (UA_GetEndpointsResponse *p)
static UA_INLINE void UA_GetEndpointsResponse_clear (UA_GetEndpointsResponse *p)
static UA_INLINE void UA_GetEndpointsResponse_delete (UA_GetEndpointsResponse *p)
static UA_INLINE void UA_EventFilter_init (UA_EventFilter *p)
static UA_INLINE UA_EventFilter * UA_EventFilter_new (void)
static UA_INLINE UA_StatusCode UA_EventFilter_copy (const UA_EventFilter *src, UA_EventFilter *dst)
static UA_INLINE void UA_EventFilter_deleteMembers (UA_EventFilter *p)
static UA_INLINE void UA_EventFilter_clear (UA_EventFilter *p)
static UA_INLINE void UA_EventFilter_delete (UA_EventFilter *p)
Function Documentation
UA_ActivateSessionRequest_clear()
static UA_INLINE void UA_ActivateSessionRequest_clear (UA_ActivateSessionRequest * p) static
Definition at line 5161 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_ActivateSessionRequest_copy()
static UA_INLINE UA_StatusCode UA_ActivateSessionRequest_copy (const UA_ActivateSessionRequest * src, UA_ActivateSessionRequest * dst) static
Definition at line 5151 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_ActivateSessionRequest_delete()
static UA_INLINE void UA_ActivateSessionRequest_delete (UA_ActivateSessionRequest * p) static
Definition at line 5166 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_ActivateSessionRequest_deleteMembers()
static UA_INLINE void UA_ActivateSessionRequest_deleteMembers (UA_ActivateSessionRequest * p) static
Definition at line 5156 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_ActivateSessionRequest_init()
static UA_INLINE void UA_ActivateSessionRequest_init (UA_ActivateSessionRequest * p) static
Definition at line 5141 of file libs/include/open62541/types_generated_handling.h.
UA_ActivateSessionRequest_new()
static UA_INLINE UA_ActivateSessionRequest* UA_ActivateSessionRequest_new (void) static
Definition at line 5146 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_ActivateSessionResponse_clear()
static UA_INLINE void UA_ActivateSessionResponse_clear (UA_ActivateSessionResponse * p) static
Definition at line 1390 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_ActivateSessionResponse_copy()
static UA_INLINE UA_StatusCode UA_ActivateSessionResponse_copy (const UA_ActivateSessionResponse * src, UA_ActivateSessionResponse * dst) static
Definition at line 1380 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_ActivateSessionResponse_delete()
static UA_INLINE void UA_ActivateSessionResponse_delete (UA_ActivateSessionResponse * p) static
Definition at line 1395 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_ActivateSessionResponse_deleteMembers()
static UA_INLINE void UA_ActivateSessionResponse_deleteMembers (UA_ActivateSessionResponse * p) static
Definition at line 1385 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_ActivateSessionResponse_init()
static UA_INLINE void UA_ActivateSessionResponse_init (UA_ActivateSessionResponse * p) static
Definition at line 1370 of file libs/include/open62541/types_generated_handling.h.
UA_ActivateSessionResponse_new()
static UA_INLINE UA_ActivateSessionResponse* UA_ActivateSessionResponse_new (void) static
Definition at line 1375 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_AddNodesItem_clear()
static UA_INLINE void UA_AddNodesItem_clear (UA_AddNodesItem * p) static
Definition at line 4975 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_AddNodesItem_copy()
static UA_INLINE UA_StatusCode UA_AddNodesItem_copy (const UA_AddNodesItem * src, UA_AddNodesItem * dst) static
Definition at line 4965 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_AddNodesItem_delete()
static UA_INLINE void UA_AddNodesItem_delete (UA_AddNodesItem * p) static
Definition at line 4980 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_AddNodesItem_deleteMembers()
static UA_INLINE void UA_AddNodesItem_deleteMembers (UA_AddNodesItem * p) static
Definition at line 4970 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_AddNodesItem_init()
static UA_INLINE void UA_AddNodesItem_init (UA_AddNodesItem * p) static
Definition at line 4955 of file libs/include/open62541/types_generated_handling.h.
UA_AddNodesItem_new()
static UA_INLINE UA_AddNodesItem* UA_AddNodesItem_new (void) static
Definition at line 4960 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_AddNodesRequest_clear()
static UA_INLINE void UA_AddNodesRequest_clear (UA_AddNodesRequest * p) static
Definition at line 5223 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_AddNodesRequest_copy()
static UA_INLINE UA_StatusCode UA_AddNodesRequest_copy (const UA_AddNodesRequest * src, UA_AddNodesRequest * dst) static
Definition at line 5213 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_AddNodesRequest_delete()
static UA_INLINE void UA_AddNodesRequest_delete (UA_AddNodesRequest * p) static
Definition at line 5228 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_AddNodesRequest_deleteMembers()
static UA_INLINE void UA_AddNodesRequest_deleteMembers (UA_AddNodesRequest * p) static
Definition at line 5218 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_AddNodesRequest_init()
static UA_INLINE void UA_AddNodesRequest_init (UA_AddNodesRequest * p) static
Definition at line 5203 of file libs/include/open62541/types_generated_handling.h.
UA_AddNodesRequest_new()
static UA_INLINE UA_AddNodesRequest* UA_AddNodesRequest_new (void) static
Definition at line 5208 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_AddNodesResponse_clear()
static UA_INLINE void UA_AddNodesResponse_clear (UA_AddNodesResponse * p) static
Definition at line 5316 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_AddNodesResponse_copy()
static UA_INLINE UA_StatusCode UA_AddNodesResponse_copy (const UA_AddNodesResponse * src, UA_AddNodesResponse * dst) static
Definition at line 5306 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_AddNodesResponse_delete()
static UA_INLINE void UA_AddNodesResponse_delete (UA_AddNodesResponse * p) static
Definition at line 5321 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_AddNodesResponse_deleteMembers()
static UA_INLINE void UA_AddNodesResponse_deleteMembers (UA_AddNodesResponse * p) static
Definition at line 5311 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_AddNodesResponse_init()
static UA_INLINE void UA_AddNodesResponse_init (UA_AddNodesResponse * p) static
Definition at line 5296 of file libs/include/open62541/types_generated_handling.h.
UA_AddNodesResponse_new()
static UA_INLINE UA_AddNodesResponse* UA_AddNodesResponse_new (void) static
Definition at line 5301 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_AddNodesResult_clear()
static UA_INLINE void UA_AddNodesResult_clear (UA_AddNodesResult * p) static
Definition at line 2390 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_AddNodesResult_copy()
static UA_INLINE UA_StatusCode UA_AddNodesResult_copy (const UA_AddNodesResult * src, UA_AddNodesResult * dst) static
Definition at line 2380 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_AddNodesResult_delete()
static UA_INLINE void UA_AddNodesResult_delete (UA_AddNodesResult * p) static
Definition at line 2395 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_AddNodesResult_deleteMembers()
static UA_INLINE void UA_AddNodesResult_deleteMembers (UA_AddNodesResult * p) static
Definition at line 2385 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_AddNodesResult_init()
static UA_INLINE void UA_AddNodesResult_init (UA_AddNodesResult * p) static
Definition at line 2370 of file libs/include/open62541/types_generated_handling.h.
UA_AddNodesResult_new()
static UA_INLINE UA_AddNodesResult* UA_AddNodesResult_new (void) static
Definition at line 2375 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_AddReferencesItem_clear()
static UA_INLINE void UA_AddReferencesItem_clear (UA_AddReferencesItem * p) static
Definition at line 2452 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_AddReferencesItem_copy()
static UA_INLINE UA_StatusCode UA_AddReferencesItem_copy (const UA_AddReferencesItem * src, UA_AddReferencesItem * dst) static
Definition at line 2442 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_AddReferencesItem_delete()
static UA_INLINE void UA_AddReferencesItem_delete (UA_AddReferencesItem * p) static
Definition at line 2457 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_AddReferencesItem_deleteMembers()
static UA_INLINE void UA_AddReferencesItem_deleteMembers (UA_AddReferencesItem * p) static
Definition at line 2447 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_AddReferencesItem_init()
static UA_INLINE void UA_AddReferencesItem_init (UA_AddReferencesItem * p) static
Definition at line 2432 of file libs/include/open62541/types_generated_handling.h.
UA_AddReferencesItem_new()
static UA_INLINE UA_AddReferencesItem* UA_AddReferencesItem_new (void) static
Definition at line 2437 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_AddReferencesRequest_clear()
static UA_INLINE void UA_AddReferencesRequest_clear (UA_AddReferencesRequest * p) static
Definition at line 4944 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_AddReferencesRequest_copy()
static UA_INLINE UA_StatusCode UA_AddReferencesRequest_copy (const UA_AddReferencesRequest * src, UA_AddReferencesRequest * dst) static
Definition at line 4934 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_AddReferencesRequest_delete()
static UA_INLINE void UA_AddReferencesRequest_delete (UA_AddReferencesRequest * p) static
Definition at line 4949 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_AddReferencesRequest_deleteMembers()
static UA_INLINE void UA_AddReferencesRequest_deleteMembers (UA_AddReferencesRequest * p) static
Definition at line 4939 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_AddReferencesRequest_init()
static UA_INLINE void UA_AddReferencesRequest_init (UA_AddReferencesRequest * p) static
Definition at line 4924 of file libs/include/open62541/types_generated_handling.h.
UA_AddReferencesRequest_new()
static UA_INLINE UA_AddReferencesRequest* UA_AddReferencesRequest_new (void) static
Definition at line 4929 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_AddReferencesResponse_clear()
static UA_INLINE void UA_AddReferencesResponse_clear (UA_AddReferencesResponse * p) static
Definition at line 2732 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_AddReferencesResponse_copy()
static UA_INLINE UA_StatusCode UA_AddReferencesResponse_copy (const UA_AddReferencesResponse * src, UA_AddReferencesResponse * dst) static
Definition at line 2722 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_AddReferencesResponse_delete()
static UA_INLINE void UA_AddReferencesResponse_delete (UA_AddReferencesResponse * p) static
Definition at line 2737 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_AddReferencesResponse_deleteMembers()
static UA_INLINE void UA_AddReferencesResponse_deleteMembers (UA_AddReferencesResponse * p) static
Definition at line 2727 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_AddReferencesResponse_init()
static UA_INLINE void UA_AddReferencesResponse_init (UA_AddReferencesResponse * p) static
Definition at line 2712 of file libs/include/open62541/types_generated_handling.h.
UA_AddReferencesResponse_new()
static UA_INLINE UA_AddReferencesResponse* UA_AddReferencesResponse_new (void) static
Definition at line 2717 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_AggregateConfiguration_clear()
static UA_INLINE void UA_AggregateConfiguration_clear (UA_AggregateConfiguration * p) static
Definition at line 3140 of file libs/include/open62541/types_generated_handling.h.
UA_AggregateConfiguration_copy()
static UA_INLINE UA_StatusCode UA_AggregateConfiguration_copy (const UA_AggregateConfiguration * src, UA_AggregateConfiguration * dst) static
Definition at line 3129 of file libs/include/open62541/types_generated_handling.h.
UA_AggregateConfiguration_delete()
static UA_INLINE void UA_AggregateConfiguration_delete (UA_AggregateConfiguration * p) static
Definition at line 3145 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_AggregateConfiguration_deleteMembers()
static UA_INLINE void UA_AggregateConfiguration_deleteMembers (UA_AggregateConfiguration * p) static
Definition at line 3135 of file libs/include/open62541/types_generated_handling.h.
UA_AggregateConfiguration_init()
static UA_INLINE void UA_AggregateConfiguration_init (UA_AggregateConfiguration * p) static
Definition at line 3119 of file libs/include/open62541/types_generated_handling.h.
UA_AggregateConfiguration_new()
static UA_INLINE UA_AggregateConfiguration* UA_AggregateConfiguration_new (void) static
Definition at line 3124 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_AggregateFilter_clear()
static UA_INLINE void UA_AggregateFilter_clear (UA_AggregateFilter * p) static
Definition at line 3920 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_AggregateFilter_copy()
static UA_INLINE UA_StatusCode UA_AggregateFilter_copy (const UA_AggregateFilter * src, UA_AggregateFilter * dst) static
Definition at line 3910 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_AggregateFilter_delete()
static UA_INLINE void UA_AggregateFilter_delete (UA_AggregateFilter * p) static
Definition at line 3925 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_AggregateFilter_deleteMembers()
static UA_INLINE void UA_AggregateFilter_deleteMembers (UA_AggregateFilter * p) static
Definition at line 3915 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_AggregateFilter_init()
static UA_INLINE void UA_AggregateFilter_init (UA_AggregateFilter * p) static
Definition at line 3900 of file libs/include/open62541/types_generated_handling.h.
UA_AggregateFilter_new()
static UA_INLINE UA_AggregateFilter* UA_AggregateFilter_new (void) static
Definition at line 3905 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_AnonymousIdentityToken_clear()
static UA_INLINE void UA_AnonymousIdentityToken_clear (UA_AnonymousIdentityToken * p) static
Definition at line 3857 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_AnonymousIdentityToken_copy()
static UA_INLINE UA_StatusCode UA_AnonymousIdentityToken_copy (const UA_AnonymousIdentityToken * src, UA_AnonymousIdentityToken * dst) static
Definition at line 3847 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_AnonymousIdentityToken_delete()
static UA_INLINE void UA_AnonymousIdentityToken_delete (UA_AnonymousIdentityToken * p) static
Definition at line 3862 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_AnonymousIdentityToken_deleteMembers()
static UA_INLINE void UA_AnonymousIdentityToken_deleteMembers (UA_AnonymousIdentityToken * p) static
Definition at line 3852 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_AnonymousIdentityToken_init()
static UA_INLINE void UA_AnonymousIdentityToken_init (UA_AnonymousIdentityToken * p) static
Definition at line 3837 of file libs/include/open62541/types_generated_handling.h.
UA_AnonymousIdentityToken_new()
static UA_INLINE UA_AnonymousIdentityToken* UA_AnonymousIdentityToken_new (void) static
Definition at line 3842 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_ApplicationDescription_clear()
static UA_INLINE void UA_ApplicationDescription_clear (UA_ApplicationDescription * p) static
Definition at line 5099 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_ApplicationDescription_copy()
static UA_INLINE UA_StatusCode UA_ApplicationDescription_copy (const UA_ApplicationDescription * src, UA_ApplicationDescription * dst) static
Definition at line 5089 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_ApplicationDescription_delete()
static UA_INLINE void UA_ApplicationDescription_delete (UA_ApplicationDescription * p) static
Definition at line 5104 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_ApplicationDescription_deleteMembers()
static UA_INLINE void UA_ApplicationDescription_deleteMembers (UA_ApplicationDescription * p) static
Definition at line 5094 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_ApplicationDescription_init()
static UA_INLINE void UA_ApplicationDescription_init (UA_ApplicationDescription * p) static
Definition at line 5079 of file libs/include/open62541/types_generated_handling.h.
UA_ApplicationDescription_new()
static UA_INLINE UA_ApplicationDescription* UA_ApplicationDescription_new (void) static
Definition at line 5084 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_ApplicationType_clear()
static UA_INLINE void UA_ApplicationType_clear (UA_ApplicationType * p) static
Definition at line 2141 of file libs/include/open62541/types_generated_handling.h.
UA_ApplicationType_copy()
static UA_INLINE UA_StatusCode UA_ApplicationType_copy (const UA_ApplicationType * src, UA_ApplicationType * dst) static
Definition at line 2130 of file libs/include/open62541/types_generated_handling.h.
UA_ApplicationType_delete()
static UA_INLINE void UA_ApplicationType_delete (UA_ApplicationType * p) static
Definition at line 2146 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_ApplicationType_deleteMembers()
static UA_INLINE void UA_ApplicationType_deleteMembers (UA_ApplicationType * p) static
Definition at line 2136 of file libs/include/open62541/types_generated_handling.h.
UA_ApplicationType_init()
static UA_INLINE void UA_ApplicationType_init (UA_ApplicationType * p) static
Definition at line 2120 of file libs/include/open62541/types_generated_handling.h.
UA_ApplicationType_new()
static UA_INLINE UA_ApplicationType* UA_ApplicationType_new (void) static
Definition at line 2125 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_Argument_clear()
static UA_INLINE void UA_Argument_clear (UA_Argument * p) static
Definition at line 3731 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_Argument_copy()
static UA_INLINE UA_StatusCode UA_Argument_copy (const UA_Argument * src, UA_Argument * dst) static
Definition at line 3721 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_Argument_delete()
static UA_INLINE void UA_Argument_delete (UA_Argument * p) static
Definition at line 3736 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_Argument_deleteMembers()
static UA_INLINE void UA_Argument_deleteMembers (UA_Argument * p) static
Definition at line 3726 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_Argument_init()
static UA_INLINE void UA_Argument_init (UA_Argument * p) static
Definition at line 3711 of file libs/include/open62541/types_generated_handling.h.
UA_Argument_new()
static UA_INLINE UA_Argument* UA_Argument_new (void) static
Definition at line 3716 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_AttributeOperand_clear()
static UA_INLINE void UA_AttributeOperand_clear (UA_AttributeOperand * p) static
Definition at line 5378 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_AttributeOperand_copy()
static UA_INLINE UA_StatusCode UA_AttributeOperand_copy (const UA_AttributeOperand * src, UA_AttributeOperand * dst) static
Definition at line 5368 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_AttributeOperand_delete()
static UA_INLINE void UA_AttributeOperand_delete (UA_AttributeOperand * p) static
Definition at line 5383 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_AttributeOperand_deleteMembers()
static UA_INLINE void UA_AttributeOperand_deleteMembers (UA_AttributeOperand * p) static
Definition at line 5373 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_AttributeOperand_init()
static UA_INLINE void UA_AttributeOperand_init (UA_AttributeOperand * p) static
Definition at line 5358 of file libs/include/open62541/types_generated_handling.h.
UA_AttributeOperand_new()
static UA_INLINE UA_AttributeOperand* UA_AttributeOperand_new (void) static
Definition at line 5363 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_Boolean_clear()
static UA_INLINE void UA_Boolean_clear (UA_Boolean * p) static
Definition at line 41 of file libs/include/open62541/types_generated_handling.h.
UA_Boolean_copy()
static UA_INLINE UA_StatusCode UA_Boolean_copy (const UA_Boolean * src, UA_Boolean * dst) static
Definition at line 30 of file libs/include/open62541/types_generated_handling.h.
UA_Boolean_delete()
static UA_INLINE void UA_Boolean_delete (UA_Boolean * p) static
Definition at line 46 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_Boolean_deleteMembers()
static UA_INLINE void UA_Boolean_deleteMembers (UA_Boolean * p) static
Definition at line 36 of file libs/include/open62541/types_generated_handling.h.
UA_Boolean_init()
static _UA_BEGIN_DECLS UA_INLINE void UA_Boolean_init (UA_Boolean * p) static
Definition at line 20 of file libs/include/open62541/types_generated_handling.h.
UA_Boolean_new()
static UA_INLINE UA_Boolean* UA_Boolean_new (void) static
Definition at line 25 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_BrowseDescription_clear()
static UA_INLINE void UA_BrowseDescription_clear (UA_BrowseDescription * p) static
Definition at line 2266 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_BrowseDescription_copy()
static UA_INLINE UA_StatusCode UA_BrowseDescription_copy (const UA_BrowseDescription * src, UA_BrowseDescription * dst) static
Definition at line 2256 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_BrowseDescription_delete()
static UA_INLINE void UA_BrowseDescription_delete (UA_BrowseDescription * p) static
Definition at line 2271 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_BrowseDescription_deleteMembers()
static UA_INLINE void UA_BrowseDescription_deleteMembers (UA_BrowseDescription * p) static
Definition at line 2261 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_BrowseDescription_init()
static UA_INLINE void UA_BrowseDescription_init (UA_BrowseDescription * p) static
Definition at line 2246 of file libs/include/open62541/types_generated_handling.h.
UA_BrowseDescription_new()
static UA_INLINE UA_BrowseDescription* UA_BrowseDescription_new (void) static
Definition at line 2251 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_BrowseDirection_clear()
static UA_INLINE void UA_BrowseDirection_clear (UA_BrowseDirection * p) static
Definition at line 1765 of file libs/include/open62541/types_generated_handling.h.
UA_BrowseDirection_copy()
static UA_INLINE UA_StatusCode UA_BrowseDirection_copy (const UA_BrowseDirection * src, UA_BrowseDirection * dst) static
Definition at line 1754 of file libs/include/open62541/types_generated_handling.h.
UA_BrowseDirection_delete()
static UA_INLINE void UA_BrowseDirection_delete (UA_BrowseDirection * p) static
Definition at line 1770 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_BrowseDirection_deleteMembers()
static UA_INLINE void UA_BrowseDirection_deleteMembers (UA_BrowseDirection * p) static
Definition at line 1760 of file libs/include/open62541/types_generated_handling.h.
UA_BrowseDirection_init()
static UA_INLINE void UA_BrowseDirection_init (UA_BrowseDirection * p) static
Definition at line 1744 of file libs/include/open62541/types_generated_handling.h.
UA_BrowseDirection_new()
static UA_INLINE UA_BrowseDirection* UA_BrowseDirection_new (void) static
Definition at line 1749 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_BrowseNextRequest_clear()
static UA_INLINE void UA_BrowseNextRequest_clear (UA_BrowseNextRequest * p) static
Definition at line 2204 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_BrowseNextRequest_copy()
static UA_INLINE UA_StatusCode UA_BrowseNextRequest_copy (const UA_BrowseNextRequest * src, UA_BrowseNextRequest * dst) static
Definition at line 2194 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_BrowseNextRequest_delete()
static UA_INLINE void UA_BrowseNextRequest_delete (UA_BrowseNextRequest * p) static
Definition at line 2209 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_BrowseNextRequest_deleteMembers()
static UA_INLINE void UA_BrowseNextRequest_deleteMembers (UA_BrowseNextRequest * p) static
Definition at line 2199 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_BrowseNextRequest_init()
static UA_INLINE void UA_BrowseNextRequest_init (UA_BrowseNextRequest * p) static
Definition at line 2184 of file libs/include/open62541/types_generated_handling.h.
UA_BrowseNextRequest_new()
static UA_INLINE UA_BrowseNextRequest* UA_BrowseNextRequest_new (void) static
Definition at line 2189 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_BrowseNextResponse_clear()
static UA_INLINE void UA_BrowseNextResponse_clear (UA_BrowseNextResponse * p) static
Definition at line 5037 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_BrowseNextResponse_copy()
static UA_INLINE UA_StatusCode UA_BrowseNextResponse_copy (const UA_BrowseNextResponse * src, UA_BrowseNextResponse * dst) static
Definition at line 5027 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_BrowseNextResponse_delete()
static UA_INLINE void UA_BrowseNextResponse_delete (UA_BrowseNextResponse * p) static
Definition at line 5042 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_BrowseNextResponse_deleteMembers()
static UA_INLINE void UA_BrowseNextResponse_deleteMembers (UA_BrowseNextResponse * p) static
Definition at line 5032 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_BrowseNextResponse_init()
static UA_INLINE void UA_BrowseNextResponse_init (UA_BrowseNextResponse * p) static
Definition at line 5017 of file libs/include/open62541/types_generated_handling.h.
UA_BrowseNextResponse_new()
static UA_INLINE UA_BrowseNextResponse* UA_BrowseNextResponse_new (void) static
Definition at line 5022 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_BrowsePath_clear()
static UA_INLINE void UA_BrowsePath_clear (UA_BrowsePath * p) static
Definition at line 4386 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_BrowsePath_copy()
static UA_INLINE UA_StatusCode UA_BrowsePath_copy (const UA_BrowsePath * src, UA_BrowsePath * dst) static
Definition at line 4376 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_BrowsePath_delete()
static UA_INLINE void UA_BrowsePath_delete (UA_BrowsePath * p) static
Definition at line 4391 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_BrowsePath_deleteMembers()
static UA_INLINE void UA_BrowsePath_deleteMembers (UA_BrowsePath * p) static
Definition at line 4381 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_BrowsePath_init()
static UA_INLINE void UA_BrowsePath_init (UA_BrowsePath * p) static
Definition at line 4366 of file libs/include/open62541/types_generated_handling.h.
UA_BrowsePath_new()
static UA_INLINE UA_BrowsePath* UA_BrowsePath_new (void) static
Definition at line 4371 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_BrowsePathResult_clear()
static UA_INLINE void UA_BrowsePathResult_clear (UA_BrowsePathResult * p) static
Definition at line 5192 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_BrowsePathResult_copy()
static UA_INLINE UA_StatusCode UA_BrowsePathResult_copy (const UA_BrowsePathResult * src, UA_BrowsePathResult * dst) static
Definition at line 5182 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_BrowsePathResult_delete()
static UA_INLINE void UA_BrowsePathResult_delete (UA_BrowsePathResult * p) static
Definition at line 5197 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_BrowsePathResult_deleteMembers()
static UA_INLINE void UA_BrowsePathResult_deleteMembers (UA_BrowsePathResult * p) static
Definition at line 5187 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_BrowsePathResult_init()
static UA_INLINE void UA_BrowsePathResult_init (UA_BrowsePathResult * p) static
Definition at line 5172 of file libs/include/open62541/types_generated_handling.h.
UA_BrowsePathResult_new()
static UA_INLINE UA_BrowsePathResult* UA_BrowsePathResult_new (void) static
Definition at line 5177 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_BrowsePathTarget_clear()
static UA_INLINE void UA_BrowsePathTarget_clear (UA_BrowsePathTarget * p) static
Definition at line 2328 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_BrowsePathTarget_copy()
static UA_INLINE UA_StatusCode UA_BrowsePathTarget_copy (const UA_BrowsePathTarget * src, UA_BrowsePathTarget * dst) static
Definition at line 2318 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_BrowsePathTarget_delete()
static UA_INLINE void UA_BrowsePathTarget_delete (UA_BrowsePathTarget * p) static
Definition at line 2333 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_BrowsePathTarget_deleteMembers()
static UA_INLINE void UA_BrowsePathTarget_deleteMembers (UA_BrowsePathTarget * p) static
Definition at line 2323 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_BrowsePathTarget_init()
static UA_INLINE void UA_BrowsePathTarget_init (UA_BrowsePathTarget * p) static
Definition at line 2308 of file libs/include/open62541/types_generated_handling.h.
UA_BrowsePathTarget_new()
static UA_INLINE UA_BrowsePathTarget* UA_BrowsePathTarget_new (void) static
Definition at line 2313 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_BrowseRequest_clear()
static UA_INLINE void UA_BrowseRequest_clear (UA_BrowseRequest * p) static
Definition at line 5254 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_BrowseRequest_copy()
static UA_INLINE UA_StatusCode UA_BrowseRequest_copy (const UA_BrowseRequest * src, UA_BrowseRequest * dst) static
Definition at line 5244 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_BrowseRequest_delete()
static UA_INLINE void UA_BrowseRequest_delete (UA_BrowseRequest * p) static
Definition at line 5259 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_BrowseRequest_deleteMembers()
static UA_INLINE void UA_BrowseRequest_deleteMembers (UA_BrowseRequest * p) static
Definition at line 5249 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_BrowseRequest_init()
static UA_INLINE void UA_BrowseRequest_init (UA_BrowseRequest * p) static
Definition at line 5234 of file libs/include/open62541/types_generated_handling.h.
UA_BrowseRequest_new()
static UA_INLINE UA_BrowseRequest* UA_BrowseRequest_new (void) static
Definition at line 5239 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_BrowseResponse_clear()
static UA_INLINE void UA_BrowseResponse_clear (UA_BrowseResponse * p) static
Definition at line 5689 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_BrowseResponse_copy()
static UA_INLINE UA_StatusCode UA_BrowseResponse_copy (const UA_BrowseResponse * src, UA_BrowseResponse * dst) static
Definition at line 5679 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_BrowseResponse_delete()
static UA_INLINE void UA_BrowseResponse_delete (UA_BrowseResponse * p) static
Definition at line 5694 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_BrowseResponse_deleteMembers()
static UA_INLINE void UA_BrowseResponse_deleteMembers (UA_BrowseResponse * p) static
Definition at line 5684 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_BrowseResponse_init()
static UA_INLINE void UA_BrowseResponse_init (UA_BrowseResponse * p) static
Definition at line 5669 of file libs/include/open62541/types_generated_handling.h.
UA_BrowseResponse_new()
static UA_INLINE UA_BrowseResponse* UA_BrowseResponse_new (void) static
Definition at line 5674 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_BrowseResult_clear()
static UA_INLINE void UA_BrowseResult_clear (UA_BrowseResult * p) static
Definition at line 4913 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_BrowseResult_copy()
static UA_INLINE UA_StatusCode UA_BrowseResult_copy (const UA_BrowseResult * src, UA_BrowseResult * dst) static
Definition at line 4903 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_BrowseResult_delete()
static UA_INLINE void UA_BrowseResult_delete (UA_BrowseResult * p) static
Definition at line 4918 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_BrowseResult_deleteMembers()
static UA_INLINE void UA_BrowseResult_deleteMembers (UA_BrowseResult * p) static
Definition at line 4908 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_BrowseResult_init()
static UA_INLINE void UA_BrowseResult_init (UA_BrowseResult * p) static
Definition at line 4893 of file libs/include/open62541/types_generated_handling.h.
UA_BrowseResult_new()
static UA_INLINE UA_BrowseResult* UA_BrowseResult_new (void) static
Definition at line 4898 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_BrowseResultMask_clear()
static UA_INLINE void UA_BrowseResultMask_clear (UA_BrowseResultMask * p) static
Definition at line 1547 of file libs/include/open62541/types_generated_handling.h.
UA_BrowseResultMask_copy()
static UA_INLINE UA_StatusCode UA_BrowseResultMask_copy (const UA_BrowseResultMask * src, UA_BrowseResultMask * dst) static
Definition at line 1536 of file libs/include/open62541/types_generated_handling.h.
UA_BrowseResultMask_delete()
static UA_INLINE void UA_BrowseResultMask_delete (UA_BrowseResultMask * p) static
Definition at line 1552 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_BrowseResultMask_deleteMembers()
static UA_INLINE void UA_BrowseResultMask_deleteMembers (UA_BrowseResultMask * p) static
Definition at line 1542 of file libs/include/open62541/types_generated_handling.h.
UA_BrowseResultMask_init()
static UA_INLINE void UA_BrowseResultMask_init (UA_BrowseResultMask * p) static
Definition at line 1526 of file libs/include/open62541/types_generated_handling.h.
UA_BrowseResultMask_new()
static UA_INLINE UA_BrowseResultMask* UA_BrowseResultMask_new (void) static
Definition at line 1531 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_BuildInfo_clear()
static UA_INLINE void UA_BuildInfo_clear (UA_BuildInfo * p) static
Definition at line 2827 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_BuildInfo_copy()
static UA_INLINE UA_StatusCode UA_BuildInfo_copy (const UA_BuildInfo * src, UA_BuildInfo * dst) static
Definition at line 2817 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_BuildInfo_delete()
static UA_INLINE void UA_BuildInfo_delete (UA_BuildInfo * p) static
Definition at line 2832 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_BuildInfo_deleteMembers()
static UA_INLINE void UA_BuildInfo_deleteMembers (UA_BuildInfo * p) static
Definition at line 2822 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_BuildInfo_init()
static UA_INLINE void UA_BuildInfo_init (UA_BuildInfo * p) static
Definition at line 2807 of file libs/include/open62541/types_generated_handling.h.
UA_BuildInfo_new()
static UA_INLINE UA_BuildInfo* UA_BuildInfo_new (void) static
Definition at line 2812 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_Byte_clear()
static UA_INLINE void UA_Byte_clear (UA_Byte * p) static
Definition at line 105 of file libs/include/open62541/types_generated_handling.h.
UA_Byte_copy()
static UA_INLINE UA_StatusCode UA_Byte_copy (const UA_Byte * src, UA_Byte * dst) static
Definition at line 94 of file libs/include/open62541/types_generated_handling.h.
UA_Byte_delete()
static UA_INLINE void UA_Byte_delete (UA_Byte * p) static
Definition at line 110 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_Byte_deleteMembers()
static UA_INLINE void UA_Byte_deleteMembers (UA_Byte * p) static
Definition at line 100 of file libs/include/open62541/types_generated_handling.h.
UA_Byte_init()
static UA_INLINE void UA_Byte_init (UA_Byte * p) static
Definition at line 84 of file libs/include/open62541/types_generated_handling.h.
UA_Byte_new()
static UA_INLINE UA_Byte* UA_Byte_new (void) static
Definition at line 89 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_ByteString_clear()
static UA_INLINE void UA_ByteString_clear (UA_ByteString * p) static
Definition at line 487 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_ByteString_copy()
static UA_INLINE UA_StatusCode UA_ByteString_copy (const UA_ByteString * src, UA_ByteString * dst) static
Definition at line 477 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_ByteString_delete()
static UA_INLINE void UA_ByteString_delete (UA_ByteString * p) static
Definition at line 492 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
Referenced by function_namespace0_generated_64_begin().
UA_ByteString_deleteMembers()
static UA_INLINE void UA_ByteString_deleteMembers (UA_ByteString * p) static
Definition at line 482 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_ByteString_init()
static UA_INLINE void UA_ByteString_init (UA_ByteString * p) static
Definition at line 467 of file libs/include/open62541/types_generated_handling.h.
Referenced by function_namespace0_generated_64_begin().
UA_ByteString_new()
static UA_INLINE UA_ByteString* UA_ByteString_new (void) static
Definition at line 472 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
Referenced by function_namespace0_generated_64_begin().
UA_CallMethodRequest_clear()
static UA_INLINE void UA_CallMethodRequest_clear (UA_CallMethodRequest * p) static
Definition at line 1796 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_CallMethodRequest_copy()
static UA_INLINE UA_StatusCode UA_CallMethodRequest_copy (const UA_CallMethodRequest * src, UA_CallMethodRequest * dst) static
Definition at line 1786 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_CallMethodRequest_delete()
static UA_INLINE void UA_CallMethodRequest_delete (UA_CallMethodRequest * p) static
Definition at line 1801 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_CallMethodRequest_deleteMembers()
static UA_INLINE void UA_CallMethodRequest_deleteMembers (UA_CallMethodRequest * p) static
Definition at line 1791 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_CallMethodRequest_init()
static UA_INLINE void UA_CallMethodRequest_init (UA_CallMethodRequest * p) static
Definition at line 1776 of file libs/include/open62541/types_generated_handling.h.
UA_CallMethodRequest_new()
static UA_INLINE UA_CallMethodRequest* UA_CallMethodRequest_new (void) static
Definition at line 1781 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_CallMethodResult_clear()
static UA_INLINE void UA_CallMethodResult_clear (UA_CallMethodResult * p) static
Definition at line 1452 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_CallMethodResult_copy()
static UA_INLINE UA_StatusCode UA_CallMethodResult_copy (const UA_CallMethodResult * src, UA_CallMethodResult * dst) static
Definition at line 1442 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_CallMethodResult_delete()
static UA_INLINE void UA_CallMethodResult_delete (UA_CallMethodResult * p) static
Definition at line 1457 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_CallMethodResult_deleteMembers()
static UA_INLINE void UA_CallMethodResult_deleteMembers (UA_CallMethodResult * p) static
Definition at line 1447 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_CallMethodResult_init()
static UA_INLINE void UA_CallMethodResult_init (UA_CallMethodResult * p) static
Definition at line 1432 of file libs/include/open62541/types_generated_handling.h.
UA_CallMethodResult_new()
static UA_INLINE UA_CallMethodResult* UA_CallMethodResult_new (void) static
Definition at line 1437 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_CallRequest_clear()
static UA_INLINE void UA_CallRequest_clear (UA_CallRequest * p) static
Definition at line 2983 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_CallRequest_copy()
static UA_INLINE UA_StatusCode UA_CallRequest_copy (const UA_CallRequest * src, UA_CallRequest * dst) static
Definition at line 2973 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_CallRequest_delete()
static UA_INLINE void UA_CallRequest_delete (UA_CallRequest * p) static
Definition at line 2988 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_CallRequest_deleteMembers()
static UA_INLINE void UA_CallRequest_deleteMembers (UA_CallRequest * p) static
Definition at line 2978 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_CallRequest_init()
static UA_INLINE void UA_CallRequest_init (UA_CallRequest * p) static
Definition at line 2963 of file libs/include/open62541/types_generated_handling.h.
UA_CallRequest_new()
static UA_INLINE UA_CallRequest* UA_CallRequest_new (void) static
Definition at line 2968 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_CallResponse_clear()
static UA_INLINE void UA_CallResponse_clear (UA_CallResponse * p) static
Definition at line 4634 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_CallResponse_copy()
static UA_INLINE UA_StatusCode UA_CallResponse_copy (const UA_CallResponse * src, UA_CallResponse * dst) static
Definition at line 4624 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_CallResponse_delete()
static UA_INLINE void UA_CallResponse_delete (UA_CallResponse * p) static
Definition at line 4639 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_CallResponse_deleteMembers()
static UA_INLINE void UA_CallResponse_deleteMembers (UA_CallResponse * p) static
Definition at line 4629 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_CallResponse_init()
static UA_INLINE void UA_CallResponse_init (UA_CallResponse * p) static
Definition at line 4614 of file libs/include/open62541/types_generated_handling.h.
UA_CallResponse_new()
static UA_INLINE UA_CallResponse* UA_CallResponse_new (void) static
Definition at line 4619 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_ChannelSecurityToken_clear()
static UA_INLINE void UA_ChannelSecurityToken_clear (UA_ChannelSecurityToken * p) static
Definition at line 3763 of file libs/include/open62541/types_generated_handling.h.
UA_ChannelSecurityToken_copy()
static UA_INLINE UA_StatusCode UA_ChannelSecurityToken_copy (const UA_ChannelSecurityToken * src, UA_ChannelSecurityToken * dst) static
Definition at line 3752 of file libs/include/open62541/types_generated_handling.h.
UA_ChannelSecurityToken_delete()
static UA_INLINE void UA_ChannelSecurityToken_delete (UA_ChannelSecurityToken * p) static
Definition at line 3768 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_ChannelSecurityToken_deleteMembers()
static UA_INLINE void UA_ChannelSecurityToken_deleteMembers (UA_ChannelSecurityToken * p) static
Definition at line 3758 of file libs/include/open62541/types_generated_handling.h.
UA_ChannelSecurityToken_init()
static UA_INLINE void UA_ChannelSecurityToken_init (UA_ChannelSecurityToken * p) static
Definition at line 3742 of file libs/include/open62541/types_generated_handling.h.
UA_ChannelSecurityToken_new()
static UA_INLINE UA_ChannelSecurityToken* UA_ChannelSecurityToken_new (void) static
Definition at line 3747 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_CloseSecureChannelRequest_clear()
static UA_INLINE void UA_CloseSecureChannelRequest_clear (UA_CloseSecureChannelRequest * p) static
Definition at line 1640 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_CloseSecureChannelRequest_copy()
static UA_INLINE UA_StatusCode UA_CloseSecureChannelRequest_copy (const UA_CloseSecureChannelRequest * src, UA_CloseSecureChannelRequest * dst) static
Definition at line 1630 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_CloseSecureChannelRequest_delete()
static UA_INLINE void UA_CloseSecureChannelRequest_delete (UA_CloseSecureChannelRequest * p) static
Definition at line 1645 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_CloseSecureChannelRequest_deleteMembers()
static UA_INLINE void UA_CloseSecureChannelRequest_deleteMembers (UA_CloseSecureChannelRequest * p) static
Definition at line 1635 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_CloseSecureChannelRequest_init()
static UA_INLINE void UA_CloseSecureChannelRequest_init (UA_CloseSecureChannelRequest * p) static
Definition at line 1620 of file libs/include/open62541/types_generated_handling.h.
UA_CloseSecureChannelRequest_new()
static UA_INLINE UA_CloseSecureChannelRequest* UA_CloseSecureChannelRequest_new (void) static
Definition at line 1625 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_CloseSecureChannelResponse_clear()
static UA_INLINE void UA_CloseSecureChannelResponse_clear (UA_CloseSecureChannelResponse * p) static
Definition at line 3450 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_CloseSecureChannelResponse_copy()
static UA_INLINE UA_StatusCode UA_CloseSecureChannelResponse_copy (const UA_CloseSecureChannelResponse * src, UA_CloseSecureChannelResponse * dst) static
Definition at line 3440 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_CloseSecureChannelResponse_delete()
static UA_INLINE void UA_CloseSecureChannelResponse_delete (UA_CloseSecureChannelResponse * p) static
Definition at line 3455 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_CloseSecureChannelResponse_deleteMembers()
static UA_INLINE void UA_CloseSecureChannelResponse_deleteMembers (UA_CloseSecureChannelResponse * p) static
Definition at line 3445 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_CloseSecureChannelResponse_init()
static UA_INLINE void UA_CloseSecureChannelResponse_init (UA_CloseSecureChannelResponse * p) static
Definition at line 3430 of file libs/include/open62541/types_generated_handling.h.
UA_CloseSecureChannelResponse_new()
static UA_INLINE UA_CloseSecureChannelResponse* UA_CloseSecureChannelResponse_new (void) static
Definition at line 3435 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_CloseSessionRequest_clear()
static UA_INLINE void UA_CloseSessionRequest_clear (UA_CloseSessionRequest * p) static
Definition at line 4851 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_CloseSessionRequest_copy()
static UA_INLINE UA_StatusCode UA_CloseSessionRequest_copy (const UA_CloseSessionRequest * src, UA_CloseSessionRequest * dst) static
Definition at line 4841 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_CloseSessionRequest_delete()
static UA_INLINE void UA_CloseSessionRequest_delete (UA_CloseSessionRequest * p) static
Definition at line 4856 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_CloseSessionRequest_deleteMembers()
static UA_INLINE void UA_CloseSessionRequest_deleteMembers (UA_CloseSessionRequest * p) static
Definition at line 4846 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_CloseSessionRequest_init()
static UA_INLINE void UA_CloseSessionRequest_init (UA_CloseSessionRequest * p) static
Definition at line 4831 of file libs/include/open62541/types_generated_handling.h.
UA_CloseSessionRequest_new()
static UA_INLINE UA_CloseSessionRequest* UA_CloseSessionRequest_new (void) static
Definition at line 4836 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_CloseSessionResponse_clear()
static UA_INLINE void UA_CloseSessionResponse_clear (UA_CloseSessionResponse * p) static
Definition at line 1985 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_CloseSessionResponse_copy()
static UA_INLINE UA_StatusCode UA_CloseSessionResponse_copy (const UA_CloseSessionResponse * src, UA_CloseSessionResponse * dst) static
Definition at line 1975 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_CloseSessionResponse_delete()
static UA_INLINE void UA_CloseSessionResponse_delete (UA_CloseSessionResponse * p) static
Definition at line 1990 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_CloseSessionResponse_deleteMembers()
static UA_INLINE void UA_CloseSessionResponse_deleteMembers (UA_CloseSessionResponse * p) static
Definition at line 1980 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_CloseSessionResponse_init()
static UA_INLINE void UA_CloseSessionResponse_init (UA_CloseSessionResponse * p) static
Definition at line 1965 of file libs/include/open62541/types_generated_handling.h.
UA_CloseSessionResponse_new()
static UA_INLINE UA_CloseSessionResponse* UA_CloseSessionResponse_new (void) static
Definition at line 1970 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_ContentFilter_clear()
static UA_INLINE void UA_ContentFilter_clear (UA_ContentFilter * p) static
Definition at line 5751 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_ContentFilter_copy()
static UA_INLINE UA_StatusCode UA_ContentFilter_copy (const UA_ContentFilter * src, UA_ContentFilter * dst) static
Definition at line 5741 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_ContentFilter_delete()
static UA_INLINE void UA_ContentFilter_delete (UA_ContentFilter * p) static
Definition at line 5756 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_ContentFilter_deleteMembers()
static UA_INLINE void UA_ContentFilter_deleteMembers (UA_ContentFilter * p) static
Definition at line 5746 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_ContentFilter_init()
static UA_INLINE void UA_ContentFilter_init (UA_ContentFilter * p) static
Definition at line 5731 of file libs/include/open62541/types_generated_handling.h.
UA_ContentFilter_new()
static UA_INLINE UA_ContentFilter* UA_ContentFilter_new (void) static
Definition at line 5736 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_ContentFilterElement_clear()
static UA_INLINE void UA_ContentFilterElement_clear (UA_ContentFilterElement * p) static
Definition at line 5596 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_ContentFilterElement_copy()
static UA_INLINE UA_StatusCode UA_ContentFilterElement_copy (const UA_ContentFilterElement * src, UA_ContentFilterElement * dst) static
Definition at line 5586 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_ContentFilterElement_delete()
static UA_INLINE void UA_ContentFilterElement_delete (UA_ContentFilterElement * p) static
Definition at line 5601 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_ContentFilterElement_deleteMembers()
static UA_INLINE void UA_ContentFilterElement_deleteMembers (UA_ContentFilterElement * p) static
Definition at line 5591 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_ContentFilterElement_init()
static UA_INLINE void UA_ContentFilterElement_init (UA_ContentFilterElement * p) static
Definition at line 5576 of file libs/include/open62541/types_generated_handling.h.
UA_ContentFilterElement_new()
static UA_INLINE UA_ContentFilterElement* UA_ContentFilterElement_new (void) static
Definition at line 5581 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_ContentFilterElementResult_clear()
static UA_INLINE void UA_ContentFilterElementResult_clear (UA_ContentFilterElementResult * p) static
Definition at line 1048 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_ContentFilterElementResult_copy()
static UA_INLINE UA_StatusCode UA_ContentFilterElementResult_copy (const UA_ContentFilterElementResult * src, UA_ContentFilterElementResult * dst) static
Definition at line 1038 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_ContentFilterElementResult_delete()
static UA_INLINE void UA_ContentFilterElementResult_delete (UA_ContentFilterElementResult * p) static
Definition at line 1053 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_ContentFilterElementResult_deleteMembers()
static UA_INLINE void UA_ContentFilterElementResult_deleteMembers (UA_ContentFilterElementResult * p) static
Definition at line 1043 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_ContentFilterElementResult_init()
static UA_INLINE void UA_ContentFilterElementResult_init (UA_ContentFilterElementResult * p) static
Definition at line 1028 of file libs/include/open62541/types_generated_handling.h.
UA_ContentFilterElementResult_new()
static UA_INLINE UA_ContentFilterElementResult* UA_ContentFilterElementResult_new (void) static
Definition at line 1033 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_ContentFilterResult_clear()
static UA_INLINE void UA_ContentFilterResult_clear (UA_ContentFilterResult * p) static
Definition at line 3233 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_ContentFilterResult_copy()
static UA_INLINE UA_StatusCode UA_ContentFilterResult_copy (const UA_ContentFilterResult * src, UA_ContentFilterResult * dst) static
Definition at line 3223 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_ContentFilterResult_delete()
static UA_INLINE void UA_ContentFilterResult_delete (UA_ContentFilterResult * p) static
Definition at line 3238 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_ContentFilterResult_deleteMembers()
static UA_INLINE void UA_ContentFilterResult_deleteMembers (UA_ContentFilterResult * p) static
Definition at line 3228 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_ContentFilterResult_init()
static UA_INLINE void UA_ContentFilterResult_init (UA_ContentFilterResult * p) static
Definition at line 3213 of file libs/include/open62541/types_generated_handling.h.
UA_ContentFilterResult_new()
static UA_INLINE UA_ContentFilterResult* UA_ContentFilterResult_new (void) static
Definition at line 3218 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_CreateMonitoredItemsRequest_clear()
static UA_INLINE void UA_CreateMonitoredItemsRequest_clear (UA_CreateMonitoredItemsRequest * p) static
Definition at line 4789 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_CreateMonitoredItemsRequest_copy()
static UA_INLINE UA_StatusCode UA_CreateMonitoredItemsRequest_copy (const UA_CreateMonitoredItemsRequest * src, UA_CreateMonitoredItemsRequest * dst) static
Definition at line 4779 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_CreateMonitoredItemsRequest_delete()
static UA_INLINE void UA_CreateMonitoredItemsRequest_delete (UA_CreateMonitoredItemsRequest * p) static
Definition at line 4794 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_CreateMonitoredItemsRequest_deleteMembers()
static UA_INLINE void UA_CreateMonitoredItemsRequest_deleteMembers (UA_CreateMonitoredItemsRequest * p) static
Definition at line 4784 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_CreateMonitoredItemsRequest_init()
static UA_INLINE void UA_CreateMonitoredItemsRequest_init (UA_CreateMonitoredItemsRequest * p) static
Definition at line 4769 of file libs/include/open62541/types_generated_handling.h.
UA_CreateMonitoredItemsRequest_new()
static UA_INLINE UA_CreateMonitoredItemsRequest* UA_CreateMonitoredItemsRequest_new (void) static
Definition at line 4774 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_CreateMonitoredItemsResponse_clear()
static UA_INLINE void UA_CreateMonitoredItemsResponse_clear (UA_CreateMonitoredItemsResponse * p) static
Definition at line 2608 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_CreateMonitoredItemsResponse_copy()
static UA_INLINE UA_StatusCode UA_CreateMonitoredItemsResponse_copy (const UA_CreateMonitoredItemsResponse * src, UA_CreateMonitoredItemsResponse * dst) static
Definition at line 2598 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_CreateMonitoredItemsResponse_delete()
static UA_INLINE void UA_CreateMonitoredItemsResponse_delete (UA_CreateMonitoredItemsResponse * p) static
Definition at line 2613 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_CreateMonitoredItemsResponse_deleteMembers()
static UA_INLINE void UA_CreateMonitoredItemsResponse_deleteMembers (UA_CreateMonitoredItemsResponse * p) static
Definition at line 2603 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_CreateMonitoredItemsResponse_init()
static UA_INLINE void UA_CreateMonitoredItemsResponse_init (UA_CreateMonitoredItemsResponse * p) static
Definition at line 2588 of file libs/include/open62541/types_generated_handling.h.
UA_CreateMonitoredItemsResponse_new()
static UA_INLINE UA_CreateMonitoredItemsResponse* UA_CreateMonitoredItemsResponse_new (void) static
Definition at line 2593 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_CreateSessionRequest_clear()
static UA_INLINE void UA_CreateSessionRequest_clear (UA_CreateSessionRequest * p) static
Definition at line 5565 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_CreateSessionRequest_copy()
static UA_INLINE UA_StatusCode UA_CreateSessionRequest_copy (const UA_CreateSessionRequest * src, UA_CreateSessionRequest * dst) static
Definition at line 5555 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_CreateSessionRequest_delete()
static UA_INLINE void UA_CreateSessionRequest_delete (UA_CreateSessionRequest * p) static
Definition at line 5570 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_CreateSessionRequest_deleteMembers()
static UA_INLINE void UA_CreateSessionRequest_deleteMembers (UA_CreateSessionRequest * p) static
Definition at line 5560 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_CreateSessionRequest_init()
static UA_INLINE void UA_CreateSessionRequest_init (UA_CreateSessionRequest * p) static
Definition at line 5545 of file libs/include/open62541/types_generated_handling.h.
UA_CreateSessionRequest_new()
static UA_INLINE UA_CreateSessionRequest* UA_CreateSessionRequest_new (void) static
Definition at line 5550 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_CreateSessionResponse_clear()
static UA_INLINE void UA_CreateSessionResponse_clear (UA_CreateSessionResponse * p) static
Definition at line 5720 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_CreateSessionResponse_copy()
static UA_INLINE UA_StatusCode UA_CreateSessionResponse_copy (const UA_CreateSessionResponse * src, UA_CreateSessionResponse * dst) static
Definition at line 5710 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_CreateSessionResponse_delete()
static UA_INLINE void UA_CreateSessionResponse_delete (UA_CreateSessionResponse * p) static
Definition at line 5725 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_CreateSessionResponse_deleteMembers()
static UA_INLINE void UA_CreateSessionResponse_deleteMembers (UA_CreateSessionResponse * p) static
Definition at line 5715 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_CreateSessionResponse_init()
static UA_INLINE void UA_CreateSessionResponse_init (UA_CreateSessionResponse * p) static
Definition at line 5700 of file libs/include/open62541/types_generated_handling.h.
UA_CreateSessionResponse_new()
static UA_INLINE UA_CreateSessionResponse* UA_CreateSessionResponse_new (void) static
Definition at line 5705 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_CreateSubscriptionRequest_clear()
static UA_INLINE void UA_CreateSubscriptionRequest_clear (UA_CreateSubscriptionRequest * p) static
Definition at line 4572 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_CreateSubscriptionRequest_copy()
static UA_INLINE UA_StatusCode UA_CreateSubscriptionRequest_copy (const UA_CreateSubscriptionRequest * src, UA_CreateSubscriptionRequest * dst) static
Definition at line 4562 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_CreateSubscriptionRequest_delete()
static UA_INLINE void UA_CreateSubscriptionRequest_delete (UA_CreateSubscriptionRequest * p) static
Definition at line 4577 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_CreateSubscriptionRequest_deleteMembers()
static UA_INLINE void UA_CreateSubscriptionRequest_deleteMembers (UA_CreateSubscriptionRequest * p) static
Definition at line 4567 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_CreateSubscriptionRequest_init()
static UA_INLINE void UA_CreateSubscriptionRequest_init (UA_CreateSubscriptionRequest * p) static
Definition at line 4552 of file libs/include/open62541/types_generated_handling.h.
Referenced by UA_CreateSubscriptionRequest_default().
UA_CreateSubscriptionRequest_new()
static UA_INLINE UA_CreateSubscriptionRequest* UA_CreateSubscriptionRequest_new (void) static
Definition at line 4557 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_CreateSubscriptionResponse_clear()
static UA_INLINE void UA_CreateSubscriptionResponse_clear (UA_CreateSubscriptionResponse * p) static
Definition at line 1702 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_CreateSubscriptionResponse_copy()
static UA_INLINE UA_StatusCode UA_CreateSubscriptionResponse_copy (const UA_CreateSubscriptionResponse * src, UA_CreateSubscriptionResponse * dst) static
Definition at line 1692 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_CreateSubscriptionResponse_delete()
static UA_INLINE void UA_CreateSubscriptionResponse_delete (UA_CreateSubscriptionResponse * p) static
Definition at line 1707 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_CreateSubscriptionResponse_deleteMembers()
static UA_INLINE void UA_CreateSubscriptionResponse_deleteMembers (UA_CreateSubscriptionResponse * p) static
Definition at line 1697 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_CreateSubscriptionResponse_init()
static UA_INLINE void UA_CreateSubscriptionResponse_init (UA_CreateSubscriptionResponse * p) static
Definition at line 1682 of file libs/include/open62541/types_generated_handling.h.
UA_CreateSubscriptionResponse_new()
static UA_INLINE UA_CreateSubscriptionResponse* UA_CreateSubscriptionResponse_new (void) static
Definition at line 1687 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_DataChangeFilter_clear()
static UA_INLINE void UA_DataChangeFilter_clear (UA_DataChangeFilter * p) static
Definition at line 5410 of file libs/include/open62541/types_generated_handling.h.
UA_DataChangeFilter_copy()
static UA_INLINE UA_StatusCode UA_DataChangeFilter_copy (const UA_DataChangeFilter * src, UA_DataChangeFilter * dst) static
Definition at line 5399 of file libs/include/open62541/types_generated_handling.h.
UA_DataChangeFilter_delete()
static UA_INLINE void UA_DataChangeFilter_delete (UA_DataChangeFilter * p) static
Definition at line 5415 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_DataChangeFilter_deleteMembers()
static UA_INLINE void UA_DataChangeFilter_deleteMembers (UA_DataChangeFilter * p) static
Definition at line 5405 of file libs/include/open62541/types_generated_handling.h.
UA_DataChangeFilter_init()
static UA_INLINE void UA_DataChangeFilter_init (UA_DataChangeFilter * p) static
Definition at line 5389 of file libs/include/open62541/types_generated_handling.h.
UA_DataChangeFilter_new()
static UA_INLINE UA_DataChangeFilter* UA_DataChangeFilter_new (void) static
Definition at line 5394 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_DataChangeNotification_clear()
static UA_INLINE void UA_DataChangeNotification_clear (UA_DataChangeNotification * p) static
Definition at line 3700 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_DataChangeNotification_copy()
static UA_INLINE UA_StatusCode UA_DataChangeNotification_copy (const UA_DataChangeNotification * src, UA_DataChangeNotification * dst) static
Definition at line 3690 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_DataChangeNotification_delete()
static UA_INLINE void UA_DataChangeNotification_delete (UA_DataChangeNotification * p) static
Definition at line 3705 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_DataChangeNotification_deleteMembers()
static UA_INLINE void UA_DataChangeNotification_deleteMembers (UA_DataChangeNotification * p) static
Definition at line 3695 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_DataChangeNotification_init()
static UA_INLINE void UA_DataChangeNotification_init (UA_DataChangeNotification * p) static
Definition at line 3680 of file libs/include/open62541/types_generated_handling.h.
UA_DataChangeNotification_new()
static UA_INLINE UA_DataChangeNotification* UA_DataChangeNotification_new (void) static
Definition at line 3685 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_DataChangeTrigger_clear()
static UA_INLINE void UA_DataChangeTrigger_clear (UA_DataChangeTrigger * p) static
Definition at line 2796 of file libs/include/open62541/types_generated_handling.h.
UA_DataChangeTrigger_copy()
static UA_INLINE UA_StatusCode UA_DataChangeTrigger_copy (const UA_DataChangeTrigger * src, UA_DataChangeTrigger * dst) static
Definition at line 2785 of file libs/include/open62541/types_generated_handling.h.
UA_DataChangeTrigger_delete()
static UA_INLINE void UA_DataChangeTrigger_delete (UA_DataChangeTrigger * p) static
Definition at line 2801 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_DataChangeTrigger_deleteMembers()
static UA_INLINE void UA_DataChangeTrigger_deleteMembers (UA_DataChangeTrigger * p) static
Definition at line 2791 of file libs/include/open62541/types_generated_handling.h.
UA_DataChangeTrigger_init()
static UA_INLINE void UA_DataChangeTrigger_init (UA_DataChangeTrigger * p) static
Definition at line 2775 of file libs/include/open62541/types_generated_handling.h.
UA_DataChangeTrigger_new()
static UA_INLINE UA_DataChangeTrigger* UA_DataChangeTrigger_new (void) static
Definition at line 2780 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_DataTypeAttributes_clear()
static UA_INLINE void UA_DataTypeAttributes_clear (UA_DataTypeAttributes * p) static
Definition at line 2701 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_DataTypeAttributes_copy()
static UA_INLINE UA_StatusCode UA_DataTypeAttributes_copy (const UA_DataTypeAttributes * src, UA_DataTypeAttributes * dst) static
Definition at line 2691 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_DataTypeAttributes_delete()
static UA_INLINE void UA_DataTypeAttributes_delete (UA_DataTypeAttributes * p) static
Definition at line 2706 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_DataTypeAttributes_deleteMembers()
static UA_INLINE void UA_DataTypeAttributes_deleteMembers (UA_DataTypeAttributes * p) static
Definition at line 2696 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_DataTypeAttributes_init()
static UA_INLINE void UA_DataTypeAttributes_init (UA_DataTypeAttributes * p) static
Definition at line 2681 of file libs/include/open62541/types_generated_handling.h.
UA_DataTypeAttributes_new()
static UA_INLINE UA_DataTypeAttributes* UA_DataTypeAttributes_new (void) static
Definition at line 2686 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_DataValue_clear()
static UA_INLINE void UA_DataValue_clear (UA_DataValue * p) static
Definition at line 736 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_DataValue_copy()
static UA_INLINE UA_StatusCode UA_DataValue_copy (const UA_DataValue * src, UA_DataValue * dst) static
Definition at line 726 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_DataValue_delete()
static UA_INLINE void UA_DataValue_delete (UA_DataValue * p) static
Definition at line 741 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_DataValue_deleteMembers()
static UA_INLINE void UA_DataValue_deleteMembers (UA_DataValue * p) static
Definition at line 731 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_DataValue_init()
static UA_INLINE void UA_DataValue_init (UA_DataValue * p) static
Definition at line 716 of file libs/include/open62541/types_generated_handling.h.
UA_DataValue_new()
static UA_INLINE UA_DataValue* UA_DataValue_new (void) static
Definition at line 721 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_DateTime_clear()
static UA_INLINE void UA_DateTime_clear (UA_DateTime * p) static
Definition at line 424 of file libs/include/open62541/types_generated_handling.h.
UA_DateTime_copy()
static UA_INLINE UA_StatusCode UA_DateTime_copy (const UA_DateTime * src, UA_DateTime * dst) static
Definition at line 413 of file libs/include/open62541/types_generated_handling.h.
UA_DateTime_delete()
static UA_INLINE void UA_DateTime_delete (UA_DateTime * p) static
Definition at line 429 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_DateTime_deleteMembers()
static UA_INLINE void UA_DateTime_deleteMembers (UA_DateTime * p) static
Definition at line 419 of file libs/include/open62541/types_generated_handling.h.
UA_DateTime_init()
static UA_INLINE void UA_DateTime_init (UA_DateTime * p) static
Definition at line 403 of file libs/include/open62541/types_generated_handling.h.
UA_DateTime_new()
static UA_INLINE UA_DateTime* UA_DateTime_new (void) static
Definition at line 408 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_DeadbandType_clear()
static UA_INLINE void UA_DeadbandType_clear (UA_DeadbandType * p) static
Definition at line 2764 of file libs/include/open62541/types_generated_handling.h.
UA_DeadbandType_copy()
static UA_INLINE UA_StatusCode UA_DeadbandType_copy (const UA_DeadbandType * src, UA_DeadbandType * dst) static
Definition at line 2753 of file libs/include/open62541/types_generated_handling.h.
UA_DeadbandType_delete()
static UA_INLINE void UA_DeadbandType_delete (UA_DeadbandType * p) static
Definition at line 2769 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_DeadbandType_deleteMembers()
static UA_INLINE void UA_DeadbandType_deleteMembers (UA_DeadbandType * p) static
Definition at line 2759 of file libs/include/open62541/types_generated_handling.h.
UA_DeadbandType_init()
static UA_INLINE void UA_DeadbandType_init (UA_DeadbandType * p) static
Definition at line 2743 of file libs/include/open62541/types_generated_handling.h.
UA_DeadbandType_new()
static UA_INLINE UA_DeadbandType* UA_DeadbandType_new (void) static
Definition at line 2748 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_DeleteMonitoredItemsRequest_clear()
static UA_INLINE void UA_DeleteMonitoredItemsRequest_clear (UA_DeleteMonitoredItemsRequest * p) static
Definition at line 3295 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_DeleteMonitoredItemsRequest_copy()
static UA_INLINE UA_StatusCode UA_DeleteMonitoredItemsRequest_copy (const UA_DeleteMonitoredItemsRequest * src, UA_DeleteMonitoredItemsRequest * dst) static
Definition at line 3285 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_DeleteMonitoredItemsRequest_delete()
static UA_INLINE void UA_DeleteMonitoredItemsRequest_delete (UA_DeleteMonitoredItemsRequest * p) static
Definition at line 3300 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_DeleteMonitoredItemsRequest_deleteMembers()
static UA_INLINE void UA_DeleteMonitoredItemsRequest_deleteMembers (UA_DeleteMonitoredItemsRequest * p) static
Definition at line 3290 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_DeleteMonitoredItemsRequest_init()
static UA_INLINE void UA_DeleteMonitoredItemsRequest_init (UA_DeleteMonitoredItemsRequest * p) static
Definition at line 3275 of file libs/include/open62541/types_generated_handling.h.
UA_DeleteMonitoredItemsRequest_new()
static UA_INLINE UA_DeleteMonitoredItemsRequest* UA_DeleteMonitoredItemsRequest_new (void) static
Definition at line 3280 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_DeleteMonitoredItemsResponse_clear()
static UA_INLINE void UA_DeleteMonitoredItemsResponse_clear (UA_DeleteMonitoredItemsResponse * p) static
Definition at line 2109 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_DeleteMonitoredItemsResponse_copy()
static UA_INLINE UA_StatusCode UA_DeleteMonitoredItemsResponse_copy (const UA_DeleteMonitoredItemsResponse * src, UA_DeleteMonitoredItemsResponse * dst) static
Definition at line 2099 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_DeleteMonitoredItemsResponse_delete()
static UA_INLINE void UA_DeleteMonitoredItemsResponse_delete (UA_DeleteMonitoredItemsResponse * p) static
Definition at line 2114 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_DeleteMonitoredItemsResponse_deleteMembers()
static UA_INLINE void UA_DeleteMonitoredItemsResponse_deleteMembers (UA_DeleteMonitoredItemsResponse * p) static
Definition at line 2104 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_DeleteMonitoredItemsResponse_init()
static UA_INLINE void UA_DeleteMonitoredItemsResponse_init (UA_DeleteMonitoredItemsResponse * p) static
Definition at line 2089 of file libs/include/open62541/types_generated_handling.h.
UA_DeleteMonitoredItemsResponse_new()
static UA_INLINE UA_DeleteMonitoredItemsResponse* UA_DeleteMonitoredItemsResponse_new (void) static
Definition at line 2094 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_DeleteNodesItem_clear()
static UA_INLINE void UA_DeleteNodesItem_clear (UA_DeleteNodesItem * p) static
Definition at line 2921 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_DeleteNodesItem_copy()
static UA_INLINE UA_StatusCode UA_DeleteNodesItem_copy (const UA_DeleteNodesItem * src, UA_DeleteNodesItem * dst) static
Definition at line 2911 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_DeleteNodesItem_delete()
static UA_INLINE void UA_DeleteNodesItem_delete (UA_DeleteNodesItem * p) static
Definition at line 2926 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_DeleteNodesItem_deleteMembers()
static UA_INLINE void UA_DeleteNodesItem_deleteMembers (UA_DeleteNodesItem * p) static
Definition at line 2916 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_DeleteNodesItem_init()
static UA_INLINE void UA_DeleteNodesItem_init (UA_DeleteNodesItem * p) static
Definition at line 2901 of file libs/include/open62541/types_generated_handling.h.
UA_DeleteNodesItem_new()
static UA_INLINE UA_DeleteNodesItem* UA_DeleteNodesItem_new (void) static
Definition at line 2906 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_DeleteNodesRequest_clear()
static UA_INLINE void UA_DeleteNodesRequest_clear (UA_DeleteNodesRequest * p) static
Definition at line 3045 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_DeleteNodesRequest_copy()
static UA_INLINE UA_StatusCode UA_DeleteNodesRequest_copy (const UA_DeleteNodesRequest * src, UA_DeleteNodesRequest * dst) static
Definition at line 3035 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_DeleteNodesRequest_delete()
static UA_INLINE void UA_DeleteNodesRequest_delete (UA_DeleteNodesRequest * p) static
Definition at line 3050 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_DeleteNodesRequest_deleteMembers()
static UA_INLINE void UA_DeleteNodesRequest_deleteMembers (UA_DeleteNodesRequest * p) static
Definition at line 3040 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_DeleteNodesRequest_init()
static UA_INLINE void UA_DeleteNodesRequest_init (UA_DeleteNodesRequest * p) static
Definition at line 3025 of file libs/include/open62541/types_generated_handling.h.
UA_DeleteNodesRequest_new()
static UA_INLINE UA_DeleteNodesRequest* UA_DeleteNodesRequest_new (void) static
Definition at line 3030 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_DeleteNodesResponse_clear()
static UA_INLINE void UA_DeleteNodesResponse_clear (UA_DeleteNodesResponse * p) static
Definition at line 4665 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_DeleteNodesResponse_copy()
static UA_INLINE UA_StatusCode UA_DeleteNodesResponse_copy (const UA_DeleteNodesResponse * src, UA_DeleteNodesResponse * dst) static
Definition at line 4655 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_DeleteNodesResponse_delete()
static UA_INLINE void UA_DeleteNodesResponse_delete (UA_DeleteNodesResponse * p) static
Definition at line 4670 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_DeleteNodesResponse_deleteMembers()
static UA_INLINE void UA_DeleteNodesResponse_deleteMembers (UA_DeleteNodesResponse * p) static
Definition at line 4660 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_DeleteNodesResponse_init()
static UA_INLINE void UA_DeleteNodesResponse_init (UA_DeleteNodesResponse * p) static
Definition at line 4645 of file libs/include/open62541/types_generated_handling.h.
UA_DeleteNodesResponse_new()
static UA_INLINE UA_DeleteNodesResponse* UA_DeleteNodesResponse_new (void) static
Definition at line 4650 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_DeleteReferencesItem_clear()
static UA_INLINE void UA_DeleteReferencesItem_clear (UA_DeleteReferencesItem * p) static
Definition at line 2639 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_DeleteReferencesItem_copy()
static UA_INLINE UA_StatusCode UA_DeleteReferencesItem_copy (const UA_DeleteReferencesItem * src, UA_DeleteReferencesItem * dst) static
Definition at line 2629 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_DeleteReferencesItem_delete()
static UA_INLINE void UA_DeleteReferencesItem_delete (UA_DeleteReferencesItem * p) static
Definition at line 2644 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_DeleteReferencesItem_deleteMembers()
static UA_INLINE void UA_DeleteReferencesItem_deleteMembers (UA_DeleteReferencesItem * p) static
Definition at line 2634 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_DeleteReferencesItem_init()
static UA_INLINE void UA_DeleteReferencesItem_init (UA_DeleteReferencesItem * p) static
Definition at line 2619 of file libs/include/open62541/types_generated_handling.h.
UA_DeleteReferencesItem_new()
static UA_INLINE UA_DeleteReferencesItem* UA_DeleteReferencesItem_new (void) static
Definition at line 2624 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_DeleteReferencesRequest_clear()
static UA_INLINE void UA_DeleteReferencesRequest_clear (UA_DeleteReferencesRequest * p) static
Definition at line 5472 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_DeleteReferencesRequest_copy()
static UA_INLINE UA_StatusCode UA_DeleteReferencesRequest_copy (const UA_DeleteReferencesRequest * src, UA_DeleteReferencesRequest * dst) static
Definition at line 5462 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_DeleteReferencesRequest_delete()
static UA_INLINE void UA_DeleteReferencesRequest_delete (UA_DeleteReferencesRequest * p) static
Definition at line 5477 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_DeleteReferencesRequest_deleteMembers()
static UA_INLINE void UA_DeleteReferencesRequest_deleteMembers (UA_DeleteReferencesRequest * p) static
Definition at line 5467 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_DeleteReferencesRequest_init()
static UA_INLINE void UA_DeleteReferencesRequest_init (UA_DeleteReferencesRequest * p) static
Definition at line 5452 of file libs/include/open62541/types_generated_handling.h.
UA_DeleteReferencesRequest_new()
static UA_INLINE UA_DeleteReferencesRequest* UA_DeleteReferencesRequest_new (void) static
Definition at line 5457 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_DeleteReferencesResponse_clear()
static UA_INLINE void UA_DeleteReferencesResponse_clear (UA_DeleteReferencesResponse * p) static
Definition at line 2514 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_DeleteReferencesResponse_copy()
static UA_INLINE UA_StatusCode UA_DeleteReferencesResponse_copy (const UA_DeleteReferencesResponse * src, UA_DeleteReferencesResponse * dst) static
Definition at line 2504 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_DeleteReferencesResponse_delete()
static UA_INLINE void UA_DeleteReferencesResponse_delete (UA_DeleteReferencesResponse * p) static
Definition at line 2519 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_DeleteReferencesResponse_deleteMembers()
static UA_INLINE void UA_DeleteReferencesResponse_deleteMembers (UA_DeleteReferencesResponse * p) static
Definition at line 2509 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_DeleteReferencesResponse_init()
static UA_INLINE void UA_DeleteReferencesResponse_init (UA_DeleteReferencesResponse * p) static
Definition at line 2494 of file libs/include/open62541/types_generated_handling.h.
UA_DeleteReferencesResponse_new()
static UA_INLINE UA_DeleteReferencesResponse* UA_DeleteReferencesResponse_new (void) static
Definition at line 2499 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_DeleteSubscriptionsRequest_clear()
static UA_INLINE void UA_DeleteSubscriptionsRequest_clear (UA_DeleteSubscriptionsRequest * p) static
Definition at line 4323 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_DeleteSubscriptionsRequest_copy()
static UA_INLINE UA_StatusCode UA_DeleteSubscriptionsRequest_copy (const UA_DeleteSubscriptionsRequest * src, UA_DeleteSubscriptionsRequest * dst) static
Definition at line 4313 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_DeleteSubscriptionsRequest_delete()
static UA_INLINE void UA_DeleteSubscriptionsRequest_delete (UA_DeleteSubscriptionsRequest * p) static
Definition at line 4328 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_DeleteSubscriptionsRequest_deleteMembers()
static UA_INLINE void UA_DeleteSubscriptionsRequest_deleteMembers (UA_DeleteSubscriptionsRequest * p) static
Definition at line 4318 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_DeleteSubscriptionsRequest_init()
static UA_INLINE void UA_DeleteSubscriptionsRequest_init (UA_DeleteSubscriptionsRequest * p) static
Definition at line 4303 of file libs/include/open62541/types_generated_handling.h.
UA_DeleteSubscriptionsRequest_new()
static UA_INLINE UA_DeleteSubscriptionsRequest* UA_DeleteSubscriptionsRequest_new (void) static
Definition at line 4308 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_DeleteSubscriptionsResponse_clear()
static UA_INLINE void UA_DeleteSubscriptionsResponse_clear (UA_DeleteSubscriptionsResponse * p) static
Definition at line 3982 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_DeleteSubscriptionsResponse_copy()
static UA_INLINE UA_StatusCode UA_DeleteSubscriptionsResponse_copy (const UA_DeleteSubscriptionsResponse * src, UA_DeleteSubscriptionsResponse * dst) static
Definition at line 3972 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_DeleteSubscriptionsResponse_delete()
static UA_INLINE void UA_DeleteSubscriptionsResponse_delete (UA_DeleteSubscriptionsResponse * p) static
Definition at line 3987 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_DeleteSubscriptionsResponse_deleteMembers()
static UA_INLINE void UA_DeleteSubscriptionsResponse_deleteMembers (UA_DeleteSubscriptionsResponse * p) static
Definition at line 3977 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_DeleteSubscriptionsResponse_init()
static UA_INLINE void UA_DeleteSubscriptionsResponse_init (UA_DeleteSubscriptionsResponse * p) static
Definition at line 3962 of file libs/include/open62541/types_generated_handling.h.
UA_DeleteSubscriptionsResponse_new()
static UA_INLINE UA_DeleteSubscriptionsResponse* UA_DeleteSubscriptionsResponse_new (void) static
Definition at line 3967 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_DiagnosticInfo_clear()
static UA_INLINE void UA_DiagnosticInfo_clear (UA_DiagnosticInfo * p) static
Definition at line 798 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_DiagnosticInfo_copy()
static UA_INLINE UA_StatusCode UA_DiagnosticInfo_copy (const UA_DiagnosticInfo * src, UA_DiagnosticInfo * dst) static
Definition at line 788 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_DiagnosticInfo_delete()
static UA_INLINE void UA_DiagnosticInfo_delete (UA_DiagnosticInfo * p) static
Definition at line 803 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_DiagnosticInfo_deleteMembers()
static UA_INLINE void UA_DiagnosticInfo_deleteMembers (UA_DiagnosticInfo * p) static
Definition at line 793 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_DiagnosticInfo_init()
static UA_INLINE void UA_DiagnosticInfo_init (UA_DiagnosticInfo * p) static
Definition at line 778 of file libs/include/open62541/types_generated_handling.h.
UA_DiagnosticInfo_new()
static UA_INLINE UA_DiagnosticInfo* UA_DiagnosticInfo_new (void) static
Definition at line 783 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_DiscoveryConfiguration_clear()
static UA_INLINE void UA_DiscoveryConfiguration_clear (UA_DiscoveryConfiguration * p) static
Definition at line 2173 of file libs/include/open62541/types_generated_handling.h.
UA_DiscoveryConfiguration_copy()
static UA_INLINE UA_StatusCode UA_DiscoveryConfiguration_copy (const UA_DiscoveryConfiguration * src, UA_DiscoveryConfiguration * dst) static
Definition at line 2162 of file libs/include/open62541/types_generated_handling.h.
UA_DiscoveryConfiguration_delete()
static UA_INLINE void UA_DiscoveryConfiguration_delete (UA_DiscoveryConfiguration * p) static
Definition at line 2178 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_DiscoveryConfiguration_deleteMembers()
static UA_INLINE void UA_DiscoveryConfiguration_deleteMembers (UA_DiscoveryConfiguration * p) static
Definition at line 2168 of file libs/include/open62541/types_generated_handling.h.
UA_DiscoveryConfiguration_init()
static UA_INLINE void UA_DiscoveryConfiguration_init (UA_DiscoveryConfiguration * p) static
Definition at line 2152 of file libs/include/open62541/types_generated_handling.h.
UA_DiscoveryConfiguration_new()
static UA_INLINE UA_DiscoveryConfiguration* UA_DiscoveryConfiguration_new (void) static
Definition at line 2157 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_Double_clear()
static UA_INLINE void UA_Double_clear (UA_Double * p) static
Definition at line 361 of file libs/include/open62541/types_generated_handling.h.
UA_Double_copy()
static UA_INLINE UA_StatusCode UA_Double_copy (const UA_Double * src, UA_Double * dst) static
Definition at line 350 of file libs/include/open62541/types_generated_handling.h.
UA_Double_delete()
static UA_INLINE void UA_Double_delete (UA_Double * p) static
Definition at line 366 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_Double_deleteMembers()
static UA_INLINE void UA_Double_deleteMembers (UA_Double * p) static
Definition at line 356 of file libs/include/open62541/types_generated_handling.h.
UA_Double_init()
static UA_INLINE void UA_Double_init (UA_Double * p) static
Definition at line 340 of file libs/include/open62541/types_generated_handling.h.
UA_Double_new()
static UA_INLINE UA_Double* UA_Double_new (void) static
Definition at line 345 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_Duration_clear()
static UA_INLINE void UA_Duration_clear (UA_Duration * p) static
Definition at line 3357 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_Duration_copy()
static UA_INLINE UA_StatusCode UA_Duration_copy (const UA_Duration * src, UA_Duration * dst) static
Definition at line 3347 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_Duration_delete()
static UA_INLINE void UA_Duration_delete (UA_Duration * p) static
Definition at line 3362 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_Duration_deleteMembers()
static UA_INLINE void UA_Duration_deleteMembers (UA_Duration * p) static
Definition at line 3352 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_Duration_init()
static UA_INLINE void UA_Duration_init (UA_Duration * p) static
Definition at line 3337 of file libs/include/open62541/types_generated_handling.h.
UA_Duration_new()
static UA_INLINE UA_Duration* UA_Duration_new (void) static
Definition at line 3342 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_ElementOperand_clear()
static UA_INLINE void UA_ElementOperand_clear (UA_ElementOperand * p) static
Definition at line 861 of file libs/include/open62541/types_generated_handling.h.
UA_ElementOperand_copy()
static UA_INLINE UA_StatusCode UA_ElementOperand_copy (const UA_ElementOperand * src, UA_ElementOperand * dst) static
Definition at line 850 of file libs/include/open62541/types_generated_handling.h.
UA_ElementOperand_delete()
static UA_INLINE void UA_ElementOperand_delete (UA_ElementOperand * p) static
Definition at line 866 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_ElementOperand_deleteMembers()
static UA_INLINE void UA_ElementOperand_deleteMembers (UA_ElementOperand * p) static
Definition at line 856 of file libs/include/open62541/types_generated_handling.h.
UA_ElementOperand_init()
static UA_INLINE void UA_ElementOperand_init (UA_ElementOperand * p) static
Definition at line 840 of file libs/include/open62541/types_generated_handling.h.
UA_ElementOperand_new()
static UA_INLINE UA_ElementOperand* UA_ElementOperand_new (void) static
Definition at line 845 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_EndpointDescription_clear()
static UA_INLINE void UA_EndpointDescription_clear (UA_EndpointDescription * p) static
Definition at line 5441 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_EndpointDescription_copy()
static UA_INLINE UA_StatusCode UA_EndpointDescription_copy (const UA_EndpointDescription * src, UA_EndpointDescription * dst) static
Definition at line 5431 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_EndpointDescription_delete()
static UA_INLINE void UA_EndpointDescription_delete (UA_EndpointDescription * p) static
Definition at line 5446 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_EndpointDescription_deleteMembers()
static UA_INLINE void UA_EndpointDescription_deleteMembers (UA_EndpointDescription * p) static
Definition at line 5436 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_EndpointDescription_init()
static UA_INLINE void UA_EndpointDescription_init (UA_EndpointDescription * p) static
Definition at line 5421 of file libs/include/open62541/types_generated_handling.h.
UA_EndpointDescription_new()
static UA_INLINE UA_EndpointDescription* UA_EndpointDescription_new (void) static
Definition at line 5426 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_EnumValueType_clear()
static UA_INLINE void UA_EnumValueType_clear (UA_EnumValueType * p) static
Definition at line 923 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_EnumValueType_copy()
static UA_INLINE UA_StatusCode UA_EnumValueType_copy (const UA_EnumValueType * src, UA_EnumValueType * dst) static
Definition at line 913 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_EnumValueType_delete()
static UA_INLINE void UA_EnumValueType_delete (UA_EnumValueType * p) static
Definition at line 928 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_EnumValueType_deleteMembers()
static UA_INLINE void UA_EnumValueType_deleteMembers (UA_EnumValueType * p) static
Definition at line 918 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_EnumValueType_init()
static UA_INLINE void UA_EnumValueType_init (UA_EnumValueType * p) static
Definition at line 903 of file libs/include/open62541/types_generated_handling.h.
UA_EnumValueType_new()
static UA_INLINE UA_EnumValueType* UA_EnumValueType_new (void) static
Definition at line 908 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_EventFieldList_clear()
static UA_INLINE void UA_EventFieldList_clear (UA_EventFieldList * p) static
Definition at line 954 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_EventFieldList_copy()
static UA_INLINE UA_StatusCode UA_EventFieldList_copy (const UA_EventFieldList * src, UA_EventFieldList * dst) static
Definition at line 944 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_EventFieldList_delete()
static UA_INLINE void UA_EventFieldList_delete (UA_EventFieldList * p) static
Definition at line 959 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_EventFieldList_deleteMembers()
static UA_INLINE void UA_EventFieldList_deleteMembers (UA_EventFieldList * p) static
Definition at line 949 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_EventFieldList_init()
static UA_INLINE void UA_EventFieldList_init (UA_EventFieldList * p) static
Definition at line 934 of file libs/include/open62541/types_generated_handling.h.
UA_EventFieldList_new()
static UA_INLINE UA_EventFieldList* UA_EventFieldList_new (void) static
Definition at line 939 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_EventFilter_clear()
static UA_INLINE void UA_EventFilter_clear (UA_EventFilter * p) static
Definition at line 5813 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_EventFilter_copy()
static UA_INLINE UA_StatusCode UA_EventFilter_copy (const UA_EventFilter * src, UA_EventFilter * dst) static
Definition at line 5803 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_EventFilter_delete()
static UA_INLINE void UA_EventFilter_delete (UA_EventFilter * p) static
Definition at line 5818 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_EventFilter_deleteMembers()
static UA_INLINE void UA_EventFilter_deleteMembers (UA_EventFilter * p) static
Definition at line 5808 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_EventFilter_init()
static UA_INLINE void UA_EventFilter_init (UA_EventFilter * p) static
Definition at line 5793 of file libs/include/open62541/types_generated_handling.h.
UA_EventFilter_new()
static UA_INLINE UA_EventFilter* UA_EventFilter_new (void) static
Definition at line 5798 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_EventFilterResult_clear()
static UA_INLINE void UA_EventFilterResult_clear (UA_EventFilterResult * p) static
Definition at line 3606 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_EventFilterResult_copy()
static UA_INLINE UA_StatusCode UA_EventFilterResult_copy (const UA_EventFilterResult * src, UA_EventFilterResult * dst) static
Definition at line 3596 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_EventFilterResult_delete()
static UA_INLINE void UA_EventFilterResult_delete (UA_EventFilterResult * p) static
Definition at line 3611 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_EventFilterResult_deleteMembers()
static UA_INLINE void UA_EventFilterResult_deleteMembers (UA_EventFilterResult * p) static
Definition at line 3601 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_EventFilterResult_init()
static UA_INLINE void UA_EventFilterResult_init (UA_EventFilterResult * p) static
Definition at line 3586 of file libs/include/open62541/types_generated_handling.h.
UA_EventFilterResult_new()
static UA_INLINE UA_EventFilterResult* UA_EventFilterResult_new (void) static
Definition at line 3591 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_EventNotificationList_clear()
static UA_INLINE void UA_EventNotificationList_clear (UA_EventNotificationList * p) static
Definition at line 3826 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_EventNotificationList_copy()
static UA_INLINE UA_StatusCode UA_EventNotificationList_copy (const UA_EventNotificationList * src, UA_EventNotificationList * dst) static
Definition at line 3816 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_EventNotificationList_delete()
static UA_INLINE void UA_EventNotificationList_delete (UA_EventNotificationList * p) static
Definition at line 3831 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_EventNotificationList_deleteMembers()
static UA_INLINE void UA_EventNotificationList_deleteMembers (UA_EventNotificationList * p) static
Definition at line 3821 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_EventNotificationList_init()
static UA_INLINE void UA_EventNotificationList_init (UA_EventNotificationList * p) static
Definition at line 3806 of file libs/include/open62541/types_generated_handling.h.
UA_EventNotificationList_new()
static UA_INLINE UA_EventNotificationList* UA_EventNotificationList_new (void) static
Definition at line 3811 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_ExpandedNodeId_clear()
static UA_INLINE void UA_ExpandedNodeId_clear (UA_ExpandedNodeId * p) static
Definition at line 580 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_ExpandedNodeId_copy()
static UA_INLINE UA_StatusCode UA_ExpandedNodeId_copy (const UA_ExpandedNodeId * src, UA_ExpandedNodeId * dst) static
Definition at line 570 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_ExpandedNodeId_delete()
static UA_INLINE void UA_ExpandedNodeId_delete (UA_ExpandedNodeId * p) static
Definition at line 585 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_ExpandedNodeId_deleteMembers()
static UA_INLINE void UA_ExpandedNodeId_deleteMembers (UA_ExpandedNodeId * p) static
Definition at line 575 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_ExpandedNodeId_init()
static UA_INLINE void UA_ExpandedNodeId_init (UA_ExpandedNodeId * p) static
Definition at line 560 of file libs/include/open62541/types_generated_handling.h.
UA_ExpandedNodeId_new()
static UA_INLINE UA_ExpandedNodeId* UA_ExpandedNodeId_new (void) static
Definition at line 565 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_ExtensionObject_clear()
static UA_INLINE void UA_ExtensionObject_clear (UA_ExtensionObject * p) static
Definition at line 705 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_ExtensionObject_copy()
static UA_INLINE UA_StatusCode UA_ExtensionObject_copy (const UA_ExtensionObject * src, UA_ExtensionObject * dst) static
Definition at line 695 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_ExtensionObject_delete()
static UA_INLINE void UA_ExtensionObject_delete (UA_ExtensionObject * p) static
Definition at line 710 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_ExtensionObject_deleteMembers()
static UA_INLINE void UA_ExtensionObject_deleteMembers (UA_ExtensionObject * p) static
Definition at line 700 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_ExtensionObject_init()
static UA_INLINE void UA_ExtensionObject_init (UA_ExtensionObject * p) static
Definition at line 685 of file libs/include/open62541/types_generated_handling.h.
UA_ExtensionObject_new()
static UA_INLINE UA_ExtensionObject* UA_ExtensionObject_new (void) static
Definition at line 690 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_FilterOperand_clear()
static UA_INLINE void UA_FilterOperand_clear (UA_FilterOperand * p) static
Definition at line 2859 of file libs/include/open62541/types_generated_handling.h.
UA_FilterOperand_copy()
static UA_INLINE UA_StatusCode UA_FilterOperand_copy (const UA_FilterOperand * src, UA_FilterOperand * dst) static
Definition at line 2848 of file libs/include/open62541/types_generated_handling.h.
UA_FilterOperand_delete()
static UA_INLINE void UA_FilterOperand_delete (UA_FilterOperand * p) static
Definition at line 2864 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_FilterOperand_deleteMembers()
static UA_INLINE void UA_FilterOperand_deleteMembers (UA_FilterOperand * p) static
Definition at line 2854 of file libs/include/open62541/types_generated_handling.h.
UA_FilterOperand_init()
static UA_INLINE void UA_FilterOperand_init (UA_FilterOperand * p) static
Definition at line 2838 of file libs/include/open62541/types_generated_handling.h.
UA_FilterOperand_new()
static UA_INLINE UA_FilterOperand* UA_FilterOperand_new (void) static
Definition at line 2843 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_FilterOperator_clear()
static UA_INLINE void UA_FilterOperator_clear (UA_FilterOperator * p) static
Definition at line 3889 of file libs/include/open62541/types_generated_handling.h.
UA_FilterOperator_copy()
static UA_INLINE UA_StatusCode UA_FilterOperator_copy (const UA_FilterOperator * src, UA_FilterOperator * dst) static
Definition at line 3878 of file libs/include/open62541/types_generated_handling.h.
UA_FilterOperator_delete()
static UA_INLINE void UA_FilterOperator_delete (UA_FilterOperator * p) static
Definition at line 3894 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_FilterOperator_deleteMembers()
static UA_INLINE void UA_FilterOperator_deleteMembers (UA_FilterOperator * p) static
Definition at line 3884 of file libs/include/open62541/types_generated_handling.h.
UA_FilterOperator_init()
static UA_INLINE void UA_FilterOperator_init (UA_FilterOperator * p) static
Definition at line 3868 of file libs/include/open62541/types_generated_handling.h.
UA_FilterOperator_new()
static UA_INLINE UA_FilterOperator* UA_FilterOperator_new (void) static
Definition at line 3873 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_FindServersOnNetworkRequest_clear()
static UA_INLINE void UA_FindServersOnNetworkRequest_clear (UA_FindServersOnNetworkRequest * p) static
Definition at line 4603 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_FindServersOnNetworkRequest_copy()
static UA_INLINE UA_StatusCode UA_FindServersOnNetworkRequest_copy (const UA_FindServersOnNetworkRequest * src, UA_FindServersOnNetworkRequest * dst) static
Definition at line 4593 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_FindServersOnNetworkRequest_delete()
static UA_INLINE void UA_FindServersOnNetworkRequest_delete (UA_FindServersOnNetworkRequest * p) static
Definition at line 4608 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_FindServersOnNetworkRequest_deleteMembers()
static UA_INLINE void UA_FindServersOnNetworkRequest_deleteMembers (UA_FindServersOnNetworkRequest * p) static
Definition at line 4598 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_FindServersOnNetworkRequest_init()
static UA_INLINE void UA_FindServersOnNetworkRequest_init (UA_FindServersOnNetworkRequest * p) static
Definition at line 4583 of file libs/include/open62541/types_generated_handling.h.
UA_FindServersOnNetworkRequest_new()
static UA_INLINE UA_FindServersOnNetworkRequest* UA_FindServersOnNetworkRequest_new (void) static
Definition at line 4588 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_FindServersOnNetworkResponse_clear()
static UA_INLINE void UA_FindServersOnNetworkResponse_clear (UA_FindServersOnNetworkResponse * p) static
Definition at line 4510 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_FindServersOnNetworkResponse_copy()
static UA_INLINE UA_StatusCode UA_FindServersOnNetworkResponse_copy (const UA_FindServersOnNetworkResponse * src, UA_FindServersOnNetworkResponse * dst) static
Definition at line 4500 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_FindServersOnNetworkResponse_delete()
static UA_INLINE void UA_FindServersOnNetworkResponse_delete (UA_FindServersOnNetworkResponse * p) static
Definition at line 4515 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_FindServersOnNetworkResponse_deleteMembers()
static UA_INLINE void UA_FindServersOnNetworkResponse_deleteMembers (UA_FindServersOnNetworkResponse * p) static
Definition at line 4505 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_FindServersOnNetworkResponse_init()
static UA_INLINE void UA_FindServersOnNetworkResponse_init (UA_FindServersOnNetworkResponse * p) static
Definition at line 4490 of file libs/include/open62541/types_generated_handling.h.
UA_FindServersOnNetworkResponse_new()
static UA_INLINE UA_FindServersOnNetworkResponse* UA_FindServersOnNetworkResponse_new (void) static
Definition at line 4495 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_FindServersRequest_clear()
static UA_INLINE void UA_FindServersRequest_clear (UA_FindServersRequest * p) static
Definition at line 4479 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_FindServersRequest_copy()
static UA_INLINE UA_StatusCode UA_FindServersRequest_copy (const UA_FindServersRequest * src, UA_FindServersRequest * dst) static
Definition at line 4469 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_FindServersRequest_delete()
static UA_INLINE void UA_FindServersRequest_delete (UA_FindServersRequest * p) static
Definition at line 4484 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_FindServersRequest_deleteMembers()
static UA_INLINE void UA_FindServersRequest_deleteMembers (UA_FindServersRequest * p) static
Definition at line 4474 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_FindServersRequest_init()
static UA_INLINE void UA_FindServersRequest_init (UA_FindServersRequest * p) static
Definition at line 4459 of file libs/include/open62541/types_generated_handling.h.
UA_FindServersRequest_new()
static UA_INLINE UA_FindServersRequest* UA_FindServersRequest_new (void) static
Definition at line 4464 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_FindServersResponse_clear()
static UA_INLINE void UA_FindServersResponse_clear (UA_FindServersResponse * p) static
Definition at line 5534 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_FindServersResponse_copy()
static UA_INLINE UA_StatusCode UA_FindServersResponse_copy (const UA_FindServersResponse * src, UA_FindServersResponse * dst) static
Definition at line 5524 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_FindServersResponse_delete()
static UA_INLINE void UA_FindServersResponse_delete (UA_FindServersResponse * p) static
Definition at line 5539 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_FindServersResponse_deleteMembers()
static UA_INLINE void UA_FindServersResponse_deleteMembers (UA_FindServersResponse * p) static
Definition at line 5529 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_FindServersResponse_init()
static UA_INLINE void UA_FindServersResponse_init (UA_FindServersResponse * p) static
Definition at line 5514 of file libs/include/open62541/types_generated_handling.h.
UA_FindServersResponse_new()
static UA_INLINE UA_FindServersResponse* UA_FindServersResponse_new (void) static
Definition at line 5519 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_Float_clear()
static UA_INLINE void UA_Float_clear (UA_Float * p) static
Definition at line 329 of file libs/include/open62541/types_generated_handling.h.
UA_Float_copy()
static UA_INLINE UA_StatusCode UA_Float_copy (const UA_Float * src, UA_Float * dst) static
Definition at line 318 of file libs/include/open62541/types_generated_handling.h.
UA_Float_delete()
static UA_INLINE void UA_Float_delete (UA_Float * p) static
Definition at line 334 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_Float_deleteMembers()
static UA_INLINE void UA_Float_deleteMembers (UA_Float * p) static
Definition at line 324 of file libs/include/open62541/types_generated_handling.h.
UA_Float_init()
static UA_INLINE void UA_Float_init (UA_Float * p) static
Definition at line 308 of file libs/include/open62541/types_generated_handling.h.
UA_Float_new()
static UA_INLINE UA_Float* UA_Float_new (void) static
Definition at line 313 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_GetEndpointsRequest_clear()
static UA_INLINE void UA_GetEndpointsRequest_clear (UA_GetEndpointsRequest * p) static
Definition at line 3419 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_GetEndpointsRequest_copy()
static UA_INLINE UA_StatusCode UA_GetEndpointsRequest_copy (const UA_GetEndpointsRequest * src, UA_GetEndpointsRequest * dst) static
Definition at line 3409 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_GetEndpointsRequest_delete()
static UA_INLINE void UA_GetEndpointsRequest_delete (UA_GetEndpointsRequest * p) static
Definition at line 3424 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_GetEndpointsRequest_deleteMembers()
static UA_INLINE void UA_GetEndpointsRequest_deleteMembers (UA_GetEndpointsRequest * p) static
Definition at line 3414 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_GetEndpointsRequest_init()
static UA_INLINE void UA_GetEndpointsRequest_init (UA_GetEndpointsRequest * p) static
Definition at line 3399 of file libs/include/open62541/types_generated_handling.h.
UA_GetEndpointsRequest_new()
static UA_INLINE UA_GetEndpointsRequest* UA_GetEndpointsRequest_new (void) static
Definition at line 3404 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_GetEndpointsResponse_clear()
static UA_INLINE void UA_GetEndpointsResponse_clear (UA_GetEndpointsResponse * p) static
Definition at line 5782 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_GetEndpointsResponse_copy()
static UA_INLINE UA_StatusCode UA_GetEndpointsResponse_copy (const UA_GetEndpointsResponse * src, UA_GetEndpointsResponse * dst) static
Definition at line 5772 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_GetEndpointsResponse_delete()
static UA_INLINE void UA_GetEndpointsResponse_delete (UA_GetEndpointsResponse * p) static
Definition at line 5787 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_GetEndpointsResponse_deleteMembers()
static UA_INLINE void UA_GetEndpointsResponse_deleteMembers (UA_GetEndpointsResponse * p) static
Definition at line 5777 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_GetEndpointsResponse_init()
static UA_INLINE void UA_GetEndpointsResponse_init (UA_GetEndpointsResponse * p) static
Definition at line 5762 of file libs/include/open62541/types_generated_handling.h.
UA_GetEndpointsResponse_new()
static UA_INLINE UA_GetEndpointsResponse* UA_GetEndpointsResponse_new (void) static
Definition at line 5767 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_Guid_clear()
static UA_INLINE void UA_Guid_clear (UA_Guid * p) static
Definition at line 456 of file libs/include/open62541/types_generated_handling.h.
UA_Guid_copy()
static UA_INLINE UA_StatusCode UA_Guid_copy (const UA_Guid * src, UA_Guid * dst) static
Definition at line 445 of file libs/include/open62541/types_generated_handling.h.
UA_Guid_delete()
static UA_INLINE void UA_Guid_delete (UA_Guid * p) static
Definition at line 461 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_Guid_deleteMembers()
static UA_INLINE void UA_Guid_deleteMembers (UA_Guid * p) static
Definition at line 451 of file libs/include/open62541/types_generated_handling.h.
UA_Guid_init()
static UA_INLINE void UA_Guid_init (UA_Guid * p) static
Definition at line 435 of file libs/include/open62541/types_generated_handling.h.
UA_Guid_new()
static UA_INLINE UA_Guid* UA_Guid_new (void) static
Definition at line 440 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_Int16_clear()
static UA_INLINE void UA_Int16_clear (UA_Int16 * p) static
Definition at line 137 of file libs/include/open62541/types_generated_handling.h.
UA_Int16_copy()
static UA_INLINE UA_StatusCode UA_Int16_copy (const UA_Int16 * src, UA_Int16 * dst) static
Definition at line 126 of file libs/include/open62541/types_generated_handling.h.
UA_Int16_delete()
static UA_INLINE void UA_Int16_delete (UA_Int16 * p) static
Definition at line 142 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_Int16_deleteMembers()
static UA_INLINE void UA_Int16_deleteMembers (UA_Int16 * p) static
Definition at line 132 of file libs/include/open62541/types_generated_handling.h.
UA_Int16_init()
static UA_INLINE void UA_Int16_init (UA_Int16 * p) static
Definition at line 116 of file libs/include/open62541/types_generated_handling.h.
UA_Int16_new()
static UA_INLINE UA_Int16* UA_Int16_new (void) static
Definition at line 121 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_Int32_clear()
static UA_INLINE void UA_Int32_clear (UA_Int32 * p) static
Definition at line 201 of file libs/include/open62541/types_generated_handling.h.
UA_Int32_copy()
static UA_INLINE UA_StatusCode UA_Int32_copy (const UA_Int32 * src, UA_Int32 * dst) static
Definition at line 190 of file libs/include/open62541/types_generated_handling.h.
UA_Int32_delete()
static UA_INLINE void UA_Int32_delete (UA_Int32 * p) static
Definition at line 206 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
Referenced by function_namespace0_generated_73_begin(), function_namespace0_generated_74_begin(), and function_namespace0_generated_76_begin().
UA_Int32_deleteMembers()
static UA_INLINE void UA_Int32_deleteMembers (UA_Int32 * p) static
Definition at line 196 of file libs/include/open62541/types_generated_handling.h.
UA_Int32_init()
static UA_INLINE void UA_Int32_init (UA_Int32 * p) static
Definition at line 180 of file libs/include/open62541/types_generated_handling.h.
Referenced by function_namespace0_generated_73_begin(), function_namespace0_generated_74_begin(), and function_namespace0_generated_76_begin().
UA_Int32_new()
static UA_INLINE UA_Int32* UA_Int32_new (void) static
Definition at line 185 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
Referenced by function_namespace0_generated_73_begin(), function_namespace0_generated_74_begin(), and function_namespace0_generated_76_begin().
UA_Int64_clear()
static UA_INLINE void UA_Int64_clear (UA_Int64 * p) static
Definition at line 265 of file libs/include/open62541/types_generated_handling.h.
UA_Int64_copy()
static UA_INLINE UA_StatusCode UA_Int64_copy (const UA_Int64 * src, UA_Int64 * dst) static
Definition at line 254 of file libs/include/open62541/types_generated_handling.h.
UA_Int64_delete()
static UA_INLINE void UA_Int64_delete (UA_Int64 * p) static
Definition at line 270 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_Int64_deleteMembers()
static UA_INLINE void UA_Int64_deleteMembers (UA_Int64 * p) static
Definition at line 260 of file libs/include/open62541/types_generated_handling.h.
UA_Int64_init()
static UA_INLINE void UA_Int64_init (UA_Int64 * p) static
Definition at line 244 of file libs/include/open62541/types_generated_handling.h.
UA_Int64_new()
static UA_INLINE UA_Int64* UA_Int64_new (void) static
Definition at line 249 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_IssuedIdentityToken_clear()
static UA_INLINE void UA_IssuedIdentityToken_clear (UA_IssuedIdentityToken * p) static
Definition at line 2047 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_IssuedIdentityToken_copy()
static UA_INLINE UA_StatusCode UA_IssuedIdentityToken_copy (const UA_IssuedIdentityToken * src, UA_IssuedIdentityToken * dst) static
Definition at line 2037 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_IssuedIdentityToken_delete()
static UA_INLINE void UA_IssuedIdentityToken_delete (UA_IssuedIdentityToken * p) static
Definition at line 2052 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_IssuedIdentityToken_deleteMembers()
static UA_INLINE void UA_IssuedIdentityToken_deleteMembers (UA_IssuedIdentityToken * p) static
Definition at line 2042 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_IssuedIdentityToken_init()
static UA_INLINE void UA_IssuedIdentityToken_init (UA_IssuedIdentityToken * p) static
Definition at line 2027 of file libs/include/open62541/types_generated_handling.h.
UA_IssuedIdentityToken_new()
static UA_INLINE UA_IssuedIdentityToken* UA_IssuedIdentityToken_new (void) static
Definition at line 2032 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_LiteralOperand_clear()
static UA_INLINE void UA_LiteralOperand_clear (UA_LiteralOperand * p) static
Definition at line 1079 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_LiteralOperand_copy()
static UA_INLINE UA_StatusCode UA_LiteralOperand_copy (const UA_LiteralOperand * src, UA_LiteralOperand * dst) static
Definition at line 1069 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_LiteralOperand_delete()
static UA_INLINE void UA_LiteralOperand_delete (UA_LiteralOperand * p) static
Definition at line 1084 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_LiteralOperand_deleteMembers()
static UA_INLINE void UA_LiteralOperand_deleteMembers (UA_LiteralOperand * p) static
Definition at line 1074 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_LiteralOperand_init()
static UA_INLINE void UA_LiteralOperand_init (UA_LiteralOperand * p) static
Definition at line 1059 of file libs/include/open62541/types_generated_handling.h.
UA_LiteralOperand_new()
static UA_INLINE UA_LiteralOperand* UA_LiteralOperand_new (void) static
Definition at line 1064 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_LocaleId_clear()
static UA_INLINE void UA_LocaleId_clear (UA_LocaleId * p) static
Definition at line 3171 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_LocaleId_copy()
static UA_INLINE UA_StatusCode UA_LocaleId_copy (const UA_LocaleId * src, UA_LocaleId * dst) static
Definition at line 3161 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_LocaleId_delete()
static UA_INLINE void UA_LocaleId_delete (UA_LocaleId * p) static
Definition at line 3176 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_LocaleId_deleteMembers()
static UA_INLINE void UA_LocaleId_deleteMembers (UA_LocaleId * p) static
Definition at line 3166 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_LocaleId_init()
static UA_INLINE void UA_LocaleId_init (UA_LocaleId * p) static
Definition at line 3151 of file libs/include/open62541/types_generated_handling.h.
UA_LocaleId_new()
static UA_INLINE UA_LocaleId* UA_LocaleId_new (void) static
Definition at line 3156 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_LocalizedText_clear()
static UA_INLINE void UA_LocalizedText_clear (UA_LocalizedText * p) static
Definition at line 674 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_LocalizedText_copy()
static UA_INLINE UA_StatusCode UA_LocalizedText_copy (const UA_LocalizedText * src, UA_LocalizedText * dst) static
Definition at line 664 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_LocalizedText_delete()
static UA_INLINE void UA_LocalizedText_delete (UA_LocalizedText * p) static
Definition at line 679 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_LocalizedText_deleteMembers()
static UA_INLINE void UA_LocalizedText_deleteMembers (UA_LocalizedText * p) static
Definition at line 669 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_LocalizedText_init()
static UA_INLINE void UA_LocalizedText_init (UA_LocalizedText * p) static
Definition at line 654 of file libs/include/open62541/types_generated_handling.h.
UA_LocalizedText_new()
static UA_INLINE UA_LocalizedText* UA_LocalizedText_new (void) static
Definition at line 659 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_MdnsDiscoveryConfiguration_clear()
static UA_INLINE void UA_MdnsDiscoveryConfiguration_clear (UA_MdnsDiscoveryConfiguration * p) static
Definition at line 1733 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_MdnsDiscoveryConfiguration_copy()
static UA_INLINE UA_StatusCode UA_MdnsDiscoveryConfiguration_copy (const UA_MdnsDiscoveryConfiguration * src, UA_MdnsDiscoveryConfiguration * dst) static
Definition at line 1723 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_MdnsDiscoveryConfiguration_delete()
static UA_INLINE void UA_MdnsDiscoveryConfiguration_delete (UA_MdnsDiscoveryConfiguration * p) static
Definition at line 1738 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_MdnsDiscoveryConfiguration_deleteMembers()
static UA_INLINE void UA_MdnsDiscoveryConfiguration_deleteMembers (UA_MdnsDiscoveryConfiguration * p) static
Definition at line 1728 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_MdnsDiscoveryConfiguration_init()
static UA_INLINE void UA_MdnsDiscoveryConfiguration_init (UA_MdnsDiscoveryConfiguration * p) static
Definition at line 1713 of file libs/include/open62541/types_generated_handling.h.
UA_MdnsDiscoveryConfiguration_new()
static UA_INLINE UA_MdnsDiscoveryConfiguration* UA_MdnsDiscoveryConfiguration_new (void) static
Definition at line 1718 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_MessageSecurityMode_clear()
static UA_INLINE void UA_MessageSecurityMode_clear (UA_MessageSecurityMode * p) static
Definition at line 1111 of file libs/include/open62541/types_generated_handling.h.
UA_MessageSecurityMode_copy()
static UA_INLINE UA_StatusCode UA_MessageSecurityMode_copy (const UA_MessageSecurityMode * src, UA_MessageSecurityMode * dst) static
Definition at line 1100 of file libs/include/open62541/types_generated_handling.h.
UA_MessageSecurityMode_delete()
static UA_INLINE void UA_MessageSecurityMode_delete (UA_MessageSecurityMode * p) static
Definition at line 1116 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_MessageSecurityMode_deleteMembers()
static UA_INLINE void UA_MessageSecurityMode_deleteMembers (UA_MessageSecurityMode * p) static
Definition at line 1106 of file libs/include/open62541/types_generated_handling.h.
UA_MessageSecurityMode_init()
static UA_INLINE void UA_MessageSecurityMode_init (UA_MessageSecurityMode * p) static
Definition at line 1090 of file libs/include/open62541/types_generated_handling.h.
UA_MessageSecurityMode_new()
static UA_INLINE UA_MessageSecurityMode* UA_MessageSecurityMode_new (void) static
Definition at line 1095 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_MethodAttributes_clear()
static UA_INLINE void UA_MethodAttributes_clear (UA_MethodAttributes * p) static
Definition at line 4044 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_MethodAttributes_copy()
static UA_INLINE UA_StatusCode UA_MethodAttributes_copy (const UA_MethodAttributes * src, UA_MethodAttributes * dst) static
Definition at line 4034 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_MethodAttributes_delete()
static UA_INLINE void UA_MethodAttributes_delete (UA_MethodAttributes * p) static
Definition at line 4049 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_MethodAttributes_deleteMembers()
static UA_INLINE void UA_MethodAttributes_deleteMembers (UA_MethodAttributes * p) static
Definition at line 4039 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_MethodAttributes_init()
static UA_INLINE void UA_MethodAttributes_init (UA_MethodAttributes * p) static
Definition at line 4024 of file libs/include/open62541/types_generated_handling.h.
UA_MethodAttributes_new()
static UA_INLINE UA_MethodAttributes* UA_MethodAttributes_new (void) static
Definition at line 4029 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_ModifyMonitoredItemsRequest_clear()
static UA_INLINE void UA_ModifyMonitoredItemsRequest_clear (UA_ModifyMonitoredItemsRequest * p) static
Definition at line 4696 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_ModifyMonitoredItemsRequest_copy()
static UA_INLINE UA_StatusCode UA_ModifyMonitoredItemsRequest_copy (const UA_ModifyMonitoredItemsRequest * src, UA_ModifyMonitoredItemsRequest * dst) static
Definition at line 4686 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_ModifyMonitoredItemsRequest_delete()
static UA_INLINE void UA_ModifyMonitoredItemsRequest_delete (UA_ModifyMonitoredItemsRequest * p) static
Definition at line 4701 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_ModifyMonitoredItemsRequest_deleteMembers()
static UA_INLINE void UA_ModifyMonitoredItemsRequest_deleteMembers (UA_ModifyMonitoredItemsRequest * p) static
Definition at line 4691 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_ModifyMonitoredItemsRequest_init()
static UA_INLINE void UA_ModifyMonitoredItemsRequest_init (UA_ModifyMonitoredItemsRequest * p) static
Definition at line 4676 of file libs/include/open62541/types_generated_handling.h.
UA_ModifyMonitoredItemsRequest_new()
static UA_INLINE UA_ModifyMonitoredItemsRequest* UA_ModifyMonitoredItemsRequest_new (void) static
Definition at line 4681 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_ModifyMonitoredItemsResponse_clear()
static UA_INLINE void UA_ModifyMonitoredItemsResponse_clear (UA_ModifyMonitoredItemsResponse * p) static
Definition at line 4292 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_ModifyMonitoredItemsResponse_copy()
static UA_INLINE UA_StatusCode UA_ModifyMonitoredItemsResponse_copy (const UA_ModifyMonitoredItemsResponse * src, UA_ModifyMonitoredItemsResponse * dst) static
Definition at line 4282 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_ModifyMonitoredItemsResponse_delete()
static UA_INLINE void UA_ModifyMonitoredItemsResponse_delete (UA_ModifyMonitoredItemsResponse * p) static
Definition at line 4297 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_ModifyMonitoredItemsResponse_deleteMembers()
static UA_INLINE void UA_ModifyMonitoredItemsResponse_deleteMembers (UA_ModifyMonitoredItemsResponse * p) static
Definition at line 4287 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_ModifyMonitoredItemsResponse_init()
static UA_INLINE void UA_ModifyMonitoredItemsResponse_init (UA_ModifyMonitoredItemsResponse * p) static
Definition at line 4272 of file libs/include/open62541/types_generated_handling.h.
UA_ModifyMonitoredItemsResponse_new()
static UA_INLINE UA_ModifyMonitoredItemsResponse* UA_ModifyMonitoredItemsResponse_new (void) static
Definition at line 4277 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_ModifySubscriptionRequest_clear()
static UA_INLINE void UA_ModifySubscriptionRequest_clear (UA_ModifySubscriptionRequest * p) static
Definition at line 2235 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_ModifySubscriptionRequest_copy()
static UA_INLINE UA_StatusCode UA_ModifySubscriptionRequest_copy (const UA_ModifySubscriptionRequest * src, UA_ModifySubscriptionRequest * dst) static
Definition at line 2225 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_ModifySubscriptionRequest_delete()
static UA_INLINE void UA_ModifySubscriptionRequest_delete (UA_ModifySubscriptionRequest * p) static
Definition at line 2240 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_ModifySubscriptionRequest_deleteMembers()
static UA_INLINE void UA_ModifySubscriptionRequest_deleteMembers (UA_ModifySubscriptionRequest * p) static
Definition at line 2230 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_ModifySubscriptionRequest_init()
static UA_INLINE void UA_ModifySubscriptionRequest_init (UA_ModifySubscriptionRequest * p) static
Definition at line 2215 of file libs/include/open62541/types_generated_handling.h.
UA_ModifySubscriptionRequest_new()
static UA_INLINE UA_ModifySubscriptionRequest* UA_ModifySubscriptionRequest_new (void) static
Definition at line 2220 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_ModifySubscriptionResponse_clear()
static UA_INLINE void UA_ModifySubscriptionResponse_clear (UA_ModifySubscriptionResponse * p) static
Definition at line 1328 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_ModifySubscriptionResponse_copy()
static UA_INLINE UA_StatusCode UA_ModifySubscriptionResponse_copy (const UA_ModifySubscriptionResponse * src, UA_ModifySubscriptionResponse * dst) static
Definition at line 1318 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_ModifySubscriptionResponse_delete()
static UA_INLINE void UA_ModifySubscriptionResponse_delete (UA_ModifySubscriptionResponse * p) static
Definition at line 1333 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_ModifySubscriptionResponse_deleteMembers()
static UA_INLINE void UA_ModifySubscriptionResponse_deleteMembers (UA_ModifySubscriptionResponse * p) static
Definition at line 1323 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_ModifySubscriptionResponse_init()
static UA_INLINE void UA_ModifySubscriptionResponse_init (UA_ModifySubscriptionResponse * p) static
Definition at line 1308 of file libs/include/open62541/types_generated_handling.h.
UA_ModifySubscriptionResponse_new()
static UA_INLINE UA_ModifySubscriptionResponse* UA_ModifySubscriptionResponse_new (void) static
Definition at line 1313 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_MonitoredItemCreateRequest_clear()
static UA_INLINE void UA_MonitoredItemCreateRequest_clear (UA_MonitoredItemCreateRequest * p) static
Definition at line 3637 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_MonitoredItemCreateRequest_copy()
static UA_INLINE UA_StatusCode UA_MonitoredItemCreateRequest_copy (const UA_MonitoredItemCreateRequest * src, UA_MonitoredItemCreateRequest * dst) static
Definition at line 3627 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_MonitoredItemCreateRequest_delete()
static UA_INLINE void UA_MonitoredItemCreateRequest_delete (UA_MonitoredItemCreateRequest * p) static
Definition at line 3642 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_MonitoredItemCreateRequest_deleteMembers()
static UA_INLINE void UA_MonitoredItemCreateRequest_deleteMembers (UA_MonitoredItemCreateRequest * p) static
Definition at line 3632 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_MonitoredItemCreateRequest_init()
static UA_INLINE void UA_MonitoredItemCreateRequest_init (UA_MonitoredItemCreateRequest * p) static
Definition at line 3617 of file libs/include/open62541/types_generated_handling.h.
Referenced by UA_MonitoredItemCreateRequest_default().
UA_MonitoredItemCreateRequest_new()
static UA_INLINE UA_MonitoredItemCreateRequest* UA_MonitoredItemCreateRequest_new (void) static
Definition at line 3622 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_MonitoredItemCreateResult_clear()
static UA_INLINE void UA_MonitoredItemCreateResult_clear (UA_MonitoredItemCreateResult * p) static
Definition at line 985 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_MonitoredItemCreateResult_copy()
static UA_INLINE UA_StatusCode UA_MonitoredItemCreateResult_copy (const UA_MonitoredItemCreateResult * src, UA_MonitoredItemCreateResult * dst) static
Definition at line 975 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_MonitoredItemCreateResult_delete()
static UA_INLINE void UA_MonitoredItemCreateResult_delete (UA_MonitoredItemCreateResult * p) static
Definition at line 990 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_MonitoredItemCreateResult_deleteMembers()
static UA_INLINE void UA_MonitoredItemCreateResult_deleteMembers (UA_MonitoredItemCreateResult * p) static
Definition at line 980 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_MonitoredItemCreateResult_init()
static UA_INLINE void UA_MonitoredItemCreateResult_init (UA_MonitoredItemCreateResult * p) static
Definition at line 965 of file libs/include/open62541/types_generated_handling.h.
UA_MonitoredItemCreateResult_new()
static UA_INLINE UA_MonitoredItemCreateResult* UA_MonitoredItemCreateResult_new (void) static
Definition at line 970 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_MonitoredItemModifyRequest_clear()
static UA_INLINE void UA_MonitoredItemModifyRequest_clear (UA_MonitoredItemModifyRequest * p) static
Definition at line 3076 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_MonitoredItemModifyRequest_copy()
static UA_INLINE UA_StatusCode UA_MonitoredItemModifyRequest_copy (const UA_MonitoredItemModifyRequest * src, UA_MonitoredItemModifyRequest * dst) static
Definition at line 3066 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_MonitoredItemModifyRequest_delete()
static UA_INLINE void UA_MonitoredItemModifyRequest_delete (UA_MonitoredItemModifyRequest * p) static
Definition at line 3081 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_MonitoredItemModifyRequest_deleteMembers()
static UA_INLINE void UA_MonitoredItemModifyRequest_deleteMembers (UA_MonitoredItemModifyRequest * p) static
Definition at line 3071 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_MonitoredItemModifyRequest_init()
static UA_INLINE void UA_MonitoredItemModifyRequest_init (UA_MonitoredItemModifyRequest * p) static
Definition at line 3056 of file libs/include/open62541/types_generated_handling.h.
UA_MonitoredItemModifyRequest_new()
static UA_INLINE UA_MonitoredItemModifyRequest* UA_MonitoredItemModifyRequest_new (void) static
Definition at line 3061 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_MonitoredItemModifyResult_clear()
static UA_INLINE void UA_MonitoredItemModifyResult_clear (UA_MonitoredItemModifyResult * p) static
Definition at line 1609 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_MonitoredItemModifyResult_copy()
static UA_INLINE UA_StatusCode UA_MonitoredItemModifyResult_copy (const UA_MonitoredItemModifyResult * src, UA_MonitoredItemModifyResult * dst) static
Definition at line 1599 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_MonitoredItemModifyResult_delete()
static UA_INLINE void UA_MonitoredItemModifyResult_delete (UA_MonitoredItemModifyResult * p) static
Definition at line 1614 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_MonitoredItemModifyResult_deleteMembers()
static UA_INLINE void UA_MonitoredItemModifyResult_deleteMembers (UA_MonitoredItemModifyResult * p) static
Definition at line 1604 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_MonitoredItemModifyResult_init()
static UA_INLINE void UA_MonitoredItemModifyResult_init (UA_MonitoredItemModifyResult * p) static
Definition at line 1589 of file libs/include/open62541/types_generated_handling.h.
UA_MonitoredItemModifyResult_new()
static UA_INLINE UA_MonitoredItemModifyResult* UA_MonitoredItemModifyResult_new (void) static
Definition at line 1594 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_MonitoredItemNotification_clear()
static UA_INLINE void UA_MonitoredItemNotification_clear (UA_MonitoredItemNotification * p) static
Definition at line 1235 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_MonitoredItemNotification_copy()
static UA_INLINE UA_StatusCode UA_MonitoredItemNotification_copy (const UA_MonitoredItemNotification * src, UA_MonitoredItemNotification * dst) static
Definition at line 1225 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_MonitoredItemNotification_delete()
static UA_INLINE void UA_MonitoredItemNotification_delete (UA_MonitoredItemNotification * p) static
Definition at line 1240 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_MonitoredItemNotification_deleteMembers()
static UA_INLINE void UA_MonitoredItemNotification_deleteMembers (UA_MonitoredItemNotification * p) static
Definition at line 1230 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_MonitoredItemNotification_init()
static UA_INLINE void UA_MonitoredItemNotification_init (UA_MonitoredItemNotification * p) static
Definition at line 1215 of file libs/include/open62541/types_generated_handling.h.
UA_MonitoredItemNotification_new()
static UA_INLINE UA_MonitoredItemNotification* UA_MonitoredItemNotification_new (void) static
Definition at line 1220 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_MonitoringMode_clear()
static UA_INLINE void UA_MonitoringMode_clear (UA_MonitoringMode * p) static
Definition at line 1484 of file libs/include/open62541/types_generated_handling.h.
UA_MonitoringMode_copy()
static UA_INLINE UA_StatusCode UA_MonitoringMode_copy (const UA_MonitoringMode * src, UA_MonitoringMode * dst) static
Definition at line 1473 of file libs/include/open62541/types_generated_handling.h.
UA_MonitoringMode_delete()
static UA_INLINE void UA_MonitoringMode_delete (UA_MonitoringMode * p) static
Definition at line 1489 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_MonitoringMode_deleteMembers()
static UA_INLINE void UA_MonitoringMode_deleteMembers (UA_MonitoringMode * p) static
Definition at line 1479 of file libs/include/open62541/types_generated_handling.h.
UA_MonitoringMode_init()
static UA_INLINE void UA_MonitoringMode_init (UA_MonitoringMode * p) static
Definition at line 1463 of file libs/include/open62541/types_generated_handling.h.
UA_MonitoringMode_new()
static UA_INLINE UA_MonitoringMode* UA_MonitoringMode_new (void) static
Definition at line 1468 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_MonitoringParameters_clear()
static UA_INLINE void UA_MonitoringParameters_clear (UA_MonitoringParameters * p) static
Definition at line 2890 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_MonitoringParameters_copy()
static UA_INLINE UA_StatusCode UA_MonitoringParameters_copy (const UA_MonitoringParameters * src, UA_MonitoringParameters * dst) static
Definition at line 2880 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_MonitoringParameters_delete()
static UA_INLINE void UA_MonitoringParameters_delete (UA_MonitoringParameters * p) static
Definition at line 2895 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_MonitoringParameters_deleteMembers()
static UA_INLINE void UA_MonitoringParameters_deleteMembers (UA_MonitoringParameters * p) static
Definition at line 2885 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_MonitoringParameters_init()
static UA_INLINE void UA_MonitoringParameters_init (UA_MonitoringParameters * p) static
Definition at line 2870 of file libs/include/open62541/types_generated_handling.h.
UA_MonitoringParameters_new()
static UA_INLINE UA_MonitoringParameters* UA_MonitoringParameters_new (void) static
Definition at line 2875 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_NodeAttributes_clear()
static UA_INLINE void UA_NodeAttributes_clear (UA_NodeAttributes * p) static
Definition at line 1359 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_NodeAttributes_copy()
static UA_INLINE UA_StatusCode UA_NodeAttributes_copy (const UA_NodeAttributes * src, UA_NodeAttributes * dst) static
Definition at line 1349 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_NodeAttributes_delete()
static UA_INLINE void UA_NodeAttributes_delete (UA_NodeAttributes * p) static
Definition at line 1364 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_NodeAttributes_deleteMembers()
static UA_INLINE void UA_NodeAttributes_deleteMembers (UA_NodeAttributes * p) static
Definition at line 1354 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_NodeAttributes_init()
static UA_INLINE void UA_NodeAttributes_init (UA_NodeAttributes * p) static
Definition at line 1339 of file libs/include/open62541/types_generated_handling.h.
UA_NodeAttributes_new()
static UA_INLINE UA_NodeAttributes* UA_NodeAttributes_new (void) static
Definition at line 1344 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_NodeAttributesMask_clear()
static UA_INLINE void UA_NodeAttributesMask_clear (UA_NodeAttributesMask * p) static
Definition at line 3575 of file libs/include/open62541/types_generated_handling.h.
UA_NodeAttributesMask_copy()
static UA_INLINE UA_StatusCode UA_NodeAttributesMask_copy (const UA_NodeAttributesMask * src, UA_NodeAttributesMask * dst) static
Definition at line 3564 of file libs/include/open62541/types_generated_handling.h.
UA_NodeAttributesMask_delete()
static UA_INLINE void UA_NodeAttributesMask_delete (UA_NodeAttributesMask * p) static
Definition at line 3580 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_NodeAttributesMask_deleteMembers()
static UA_INLINE void UA_NodeAttributesMask_deleteMembers (UA_NodeAttributesMask * p) static
Definition at line 3570 of file libs/include/open62541/types_generated_handling.h.
UA_NodeAttributesMask_init()
static UA_INLINE void UA_NodeAttributesMask_init (UA_NodeAttributesMask * p) static
Definition at line 3554 of file libs/include/open62541/types_generated_handling.h.
UA_NodeAttributesMask_new()
static UA_INLINE UA_NodeAttributesMask* UA_NodeAttributesMask_new (void) static
Definition at line 3559 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_NodeClass_clear()
static UA_INLINE void UA_NodeClass_clear (UA_NodeClass * p) static
Definition at line 1891 of file libs/include/open62541/types_generated_handling.h.
UA_NodeClass_copy()
static UA_INLINE UA_StatusCode UA_NodeClass_copy (const UA_NodeClass * src, UA_NodeClass * dst) static
Definition at line 1880 of file libs/include/open62541/types_generated_handling.h.
UA_NodeClass_delete()
static UA_INLINE void UA_NodeClass_delete (UA_NodeClass * p) static
Definition at line 1896 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_NodeClass_deleteMembers()
static UA_INLINE void UA_NodeClass_deleteMembers (UA_NodeClass * p) static
Definition at line 1886 of file libs/include/open62541/types_generated_handling.h.
UA_NodeClass_init()
static UA_INLINE void UA_NodeClass_init (UA_NodeClass * p) static
Definition at line 1870 of file libs/include/open62541/types_generated_handling.h.
UA_NodeClass_new()
static UA_INLINE UA_NodeClass* UA_NodeClass_new (void) static
Definition at line 1875 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_NodeId_clear()
static UA_INLINE void UA_NodeId_clear (UA_NodeId * p) static
Definition at line 549 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_NodeId_copy()
static UA_INLINE UA_StatusCode UA_NodeId_copy (const UA_NodeId * src, UA_NodeId * dst) static
Definition at line 539 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_NodeId_delete()
static UA_INLINE void UA_NodeId_delete (UA_NodeId * p) static
Definition at line 554 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_NodeId_deleteMembers()
static UA_INLINE void UA_NodeId_deleteMembers (UA_NodeId * p) static
Definition at line 544 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_NodeId_init()
static UA_INLINE void UA_NodeId_init (UA_NodeId * p) static
Definition at line 529 of file libs/include/open62541/types_generated_handling.h.
UA_NodeId_new()
static UA_INLINE UA_NodeId* UA_NodeId_new (void) static
Definition at line 534 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_NotificationMessage_clear()
static UA_INLINE void UA_NotificationMessage_clear (UA_NotificationMessage * p) static
Definition at line 1671 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_NotificationMessage_copy()
static UA_INLINE UA_StatusCode UA_NotificationMessage_copy (const UA_NotificationMessage * src, UA_NotificationMessage * dst) static
Definition at line 1661 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_NotificationMessage_delete()
static UA_INLINE void UA_NotificationMessage_delete (UA_NotificationMessage * p) static
Definition at line 1676 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_NotificationMessage_deleteMembers()
static UA_INLINE void UA_NotificationMessage_deleteMembers (UA_NotificationMessage * p) static
Definition at line 1666 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_NotificationMessage_init()
static UA_INLINE void UA_NotificationMessage_init (UA_NotificationMessage * p) static
Definition at line 1651 of file libs/include/open62541/types_generated_handling.h.
UA_NotificationMessage_new()
static UA_INLINE UA_NotificationMessage* UA_NotificationMessage_new (void) static
Definition at line 1656 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_ObjectAttributes_clear()
static UA_INLINE void UA_ObjectAttributes_clear (UA_ObjectAttributes * p) static
Definition at line 4417 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_ObjectAttributes_copy()
static UA_INLINE UA_StatusCode UA_ObjectAttributes_copy (const UA_ObjectAttributes * src, UA_ObjectAttributes * dst) static
Definition at line 4407 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_ObjectAttributes_delete()
static UA_INLINE void UA_ObjectAttributes_delete (UA_ObjectAttributes * p) static
Definition at line 4422 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_ObjectAttributes_deleteMembers()
static UA_INLINE void UA_ObjectAttributes_deleteMembers (UA_ObjectAttributes * p) static
Definition at line 4412 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_ObjectAttributes_init()
static UA_INLINE void UA_ObjectAttributes_init (UA_ObjectAttributes * p) static
Definition at line 4397 of file libs/include/open62541/types_generated_handling.h.
UA_ObjectAttributes_new()
static UA_INLINE UA_ObjectAttributes* UA_ObjectAttributes_new (void) static
Definition at line 4402 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_ObjectTypeAttributes_clear()
static UA_INLINE void UA_ObjectTypeAttributes_clear (UA_ObjectTypeAttributes * p) static
Definition at line 1922 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_ObjectTypeAttributes_copy()
static UA_INLINE UA_StatusCode UA_ObjectTypeAttributes_copy (const UA_ObjectTypeAttributes * src, UA_ObjectTypeAttributes * dst) static
Definition at line 1912 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_ObjectTypeAttributes_delete()
static UA_INLINE void UA_ObjectTypeAttributes_delete (UA_ObjectTypeAttributes * p) static
Definition at line 1927 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_ObjectTypeAttributes_deleteMembers()
static UA_INLINE void UA_ObjectTypeAttributes_deleteMembers (UA_ObjectTypeAttributes * p) static
Definition at line 1917 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_ObjectTypeAttributes_init()
static UA_INLINE void UA_ObjectTypeAttributes_init (UA_ObjectTypeAttributes * p) static
Definition at line 1902 of file libs/include/open62541/types_generated_handling.h.
UA_ObjectTypeAttributes_new()
static UA_INLINE UA_ObjectTypeAttributes* UA_ObjectTypeAttributes_new (void) static
Definition at line 1907 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_OpenSecureChannelRequest_clear()
static UA_INLINE void UA_OpenSecureChannelRequest_clear (UA_OpenSecureChannelRequest * p) static
Definition at line 4820 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_OpenSecureChannelRequest_copy()
static UA_INLINE UA_StatusCode UA_OpenSecureChannelRequest_copy (const UA_OpenSecureChannelRequest * src, UA_OpenSecureChannelRequest * dst) static
Definition at line 4810 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_OpenSecureChannelRequest_delete()
static UA_INLINE void UA_OpenSecureChannelRequest_delete (UA_OpenSecureChannelRequest * p) static
Definition at line 4825 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_OpenSecureChannelRequest_deleteMembers()
static UA_INLINE void UA_OpenSecureChannelRequest_deleteMembers (UA_OpenSecureChannelRequest * p) static
Definition at line 4815 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_OpenSecureChannelRequest_init()
static UA_INLINE void UA_OpenSecureChannelRequest_init (UA_OpenSecureChannelRequest * p) static
Definition at line 4800 of file libs/include/open62541/types_generated_handling.h.
UA_OpenSecureChannelRequest_new()
static UA_INLINE UA_OpenSecureChannelRequest* UA_OpenSecureChannelRequest_new (void) static
Definition at line 4805 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_OpenSecureChannelResponse_clear()
static UA_INLINE void UA_OpenSecureChannelResponse_clear (UA_OpenSecureChannelResponse * p) static
Definition at line 4137 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_OpenSecureChannelResponse_copy()
static UA_INLINE UA_StatusCode UA_OpenSecureChannelResponse_copy (const UA_OpenSecureChannelResponse * src, UA_OpenSecureChannelResponse * dst) static
Definition at line 4127 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_OpenSecureChannelResponse_delete()
static UA_INLINE void UA_OpenSecureChannelResponse_delete (UA_OpenSecureChannelResponse * p) static
Definition at line 4142 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_OpenSecureChannelResponse_deleteMembers()
static UA_INLINE void UA_OpenSecureChannelResponse_deleteMembers (UA_OpenSecureChannelResponse * p) static
Definition at line 4132 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_OpenSecureChannelResponse_init()
static UA_INLINE void UA_OpenSecureChannelResponse_init (UA_OpenSecureChannelResponse * p) static
Definition at line 4117 of file libs/include/open62541/types_generated_handling.h.
UA_OpenSecureChannelResponse_new()
static UA_INLINE UA_OpenSecureChannelResponse* UA_OpenSecureChannelResponse_new (void) static
Definition at line 4122 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_PublishRequest_clear()
static UA_INLINE void UA_PublishRequest_clear (UA_PublishRequest * p) static
Definition at line 4448 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_PublishRequest_copy()
static UA_INLINE UA_StatusCode UA_PublishRequest_copy (const UA_PublishRequest * src, UA_PublishRequest * dst) static
Definition at line 4438 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_PublishRequest_delete()
static UA_INLINE void UA_PublishRequest_delete (UA_PublishRequest * p) static
Definition at line 4453 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_PublishRequest_deleteMembers()
static UA_INLINE void UA_PublishRequest_deleteMembers (UA_PublishRequest * p) static
Definition at line 4443 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_PublishRequest_init()
static UA_INLINE void UA_PublishRequest_init (UA_PublishRequest * p) static
Definition at line 4428 of file libs/include/open62541/types_generated_handling.h.
UA_PublishRequest_new()
static UA_INLINE UA_PublishRequest* UA_PublishRequest_new (void) static
Definition at line 4433 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_PublishResponse_clear()
static UA_INLINE void UA_PublishResponse_clear (UA_PublishResponse * p) static
Definition at line 4758 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_PublishResponse_copy()
static UA_INLINE UA_StatusCode UA_PublishResponse_copy (const UA_PublishResponse * src, UA_PublishResponse * dst) static
Definition at line 4748 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_PublishResponse_delete()
static UA_INLINE void UA_PublishResponse_delete (UA_PublishResponse * p) static
Definition at line 4763 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_PublishResponse_deleteMembers()
static UA_INLINE void UA_PublishResponse_deleteMembers (UA_PublishResponse * p) static
Definition at line 4753 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_PublishResponse_init()
static UA_INLINE void UA_PublishResponse_init (UA_PublishResponse * p) static
Definition at line 4738 of file libs/include/open62541/types_generated_handling.h.
UA_PublishResponse_new()
static UA_INLINE UA_PublishResponse* UA_PublishResponse_new (void) static
Definition at line 4743 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_QualifiedName_clear()
static UA_INLINE void UA_QualifiedName_clear (UA_QualifiedName * p) static
Definition at line 643 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_QualifiedName_copy()
static UA_INLINE UA_StatusCode UA_QualifiedName_copy (const UA_QualifiedName * src, UA_QualifiedName * dst) static
Definition at line 633 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_QualifiedName_delete()
static UA_INLINE void UA_QualifiedName_delete (UA_QualifiedName * p) static
Definition at line 648 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_QualifiedName_deleteMembers()
static UA_INLINE void UA_QualifiedName_deleteMembers (UA_QualifiedName * p) static
Definition at line 638 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_QualifiedName_init()
static UA_INLINE void UA_QualifiedName_init (UA_QualifiedName * p) static
Definition at line 623 of file libs/include/open62541/types_generated_handling.h.
UA_QualifiedName_new()
static UA_INLINE UA_QualifiedName* UA_QualifiedName_new (void) static
Definition at line 628 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_Range_clear()
static UA_INLINE void UA_Range_clear (UA_Range * p) static
Definition at line 3669 of file libs/include/open62541/types_generated_handling.h.
UA_Range_copy()
static UA_INLINE UA_StatusCode UA_Range_copy (const UA_Range * src, UA_Range * dst) static
Definition at line 3658 of file libs/include/open62541/types_generated_handling.h.
UA_Range_delete()
static UA_INLINE void UA_Range_delete (UA_Range * p) static
Definition at line 3674 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_Range_deleteMembers()
static UA_INLINE void UA_Range_deleteMembers (UA_Range * p) static
Definition at line 3664 of file libs/include/open62541/types_generated_handling.h.
UA_Range_init()
static UA_INLINE void UA_Range_init (UA_Range * p) static
Definition at line 3648 of file libs/include/open62541/types_generated_handling.h.
UA_Range_new()
static UA_INLINE UA_Range* UA_Range_new (void) static
Definition at line 3653 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_ReadRequest_clear()
static UA_INLINE void UA_ReadRequest_clear (UA_ReadRequest * p) static
Definition at line 5130 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_ReadRequest_copy()
static UA_INLINE UA_StatusCode UA_ReadRequest_copy (const UA_ReadRequest * src, UA_ReadRequest * dst) static
Definition at line 5120 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_ReadRequest_delete()
static UA_INLINE void UA_ReadRequest_delete (UA_ReadRequest * p) static
Definition at line 5135 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_ReadRequest_deleteMembers()
static UA_INLINE void UA_ReadRequest_deleteMembers (UA_ReadRequest * p) static
Definition at line 5125 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_ReadRequest_init()
static UA_INLINE void UA_ReadRequest_init (UA_ReadRequest * p) static
Definition at line 5110 of file libs/include/open62541/types_generated_handling.h.
UA_ReadRequest_new()
static UA_INLINE UA_ReadRequest* UA_ReadRequest_new (void) static
Definition at line 5115 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_ReadResponse_clear()
static UA_INLINE void UA_ReadResponse_clear (UA_ReadResponse * p) static
Definition at line 1827 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_ReadResponse_copy()
static UA_INLINE UA_StatusCode UA_ReadResponse_copy (const UA_ReadResponse * src, UA_ReadResponse * dst) static
Definition at line 1817 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_ReadResponse_delete()
static UA_INLINE void UA_ReadResponse_delete (UA_ReadResponse * p) static
Definition at line 1832 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_ReadResponse_deleteMembers()
static UA_INLINE void UA_ReadResponse_deleteMembers (UA_ReadResponse * p) static
Definition at line 1822 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_ReadResponse_init()
static UA_INLINE void UA_ReadResponse_init (UA_ReadResponse * p) static
Definition at line 1807 of file libs/include/open62541/types_generated_handling.h.
UA_ReadResponse_new()
static UA_INLINE UA_ReadResponse* UA_ReadResponse_new (void) static
Definition at line 1812 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_ReadValueId_clear()
static UA_INLINE void UA_ReadValueId_clear (UA_ReadValueId * p) static
Definition at line 2952 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_ReadValueId_copy()
static UA_INLINE UA_StatusCode UA_ReadValueId_copy (const UA_ReadValueId * src, UA_ReadValueId * dst) static
Definition at line 2942 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_ReadValueId_delete()
static UA_INLINE void UA_ReadValueId_delete (UA_ReadValueId * p) static
Definition at line 2957 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_ReadValueId_deleteMembers()
static UA_INLINE void UA_ReadValueId_deleteMembers (UA_ReadValueId * p) static
Definition at line 2947 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_ReadValueId_init()
static UA_INLINE void UA_ReadValueId_init (UA_ReadValueId * p) static
Definition at line 2932 of file libs/include/open62541/types_generated_handling.h.
UA_ReadValueId_new()
static UA_INLINE UA_ReadValueId* UA_ReadValueId_new (void) static
Definition at line 2937 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_RedundancySupport_clear()
static UA_INLINE void UA_RedundancySupport_clear (UA_RedundancySupport * p) static
Definition at line 4355 of file libs/include/open62541/types_generated_handling.h.
UA_RedundancySupport_copy()
static UA_INLINE UA_StatusCode UA_RedundancySupport_copy (const UA_RedundancySupport * src, UA_RedundancySupport * dst) static
Definition at line 4344 of file libs/include/open62541/types_generated_handling.h.
UA_RedundancySupport_delete()
static UA_INLINE void UA_RedundancySupport_delete (UA_RedundancySupport * p) static
Definition at line 4360 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_RedundancySupport_deleteMembers()
static UA_INLINE void UA_RedundancySupport_deleteMembers (UA_RedundancySupport * p) static
Definition at line 4350 of file libs/include/open62541/types_generated_handling.h.
UA_RedundancySupport_init()
static UA_INLINE void UA_RedundancySupport_init (UA_RedundancySupport * p) static
Definition at line 4334 of file libs/include/open62541/types_generated_handling.h.
UA_RedundancySupport_new()
static UA_INLINE UA_RedundancySupport* UA_RedundancySupport_new (void) static
Definition at line 4339 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_ReferenceDescription_clear()
static UA_INLINE void UA_ReferenceDescription_clear (UA_ReferenceDescription * p) static
Definition at line 4541 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_ReferenceDescription_copy()
static UA_INLINE UA_StatusCode UA_ReferenceDescription_copy (const UA_ReferenceDescription * src, UA_ReferenceDescription * dst) static
Definition at line 4531 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_ReferenceDescription_delete()
static UA_INLINE void UA_ReferenceDescription_delete (UA_ReferenceDescription * p) static
Definition at line 4546 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_ReferenceDescription_deleteMembers()
static UA_INLINE void UA_ReferenceDescription_deleteMembers (UA_ReferenceDescription * p) static
Definition at line 4536 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_ReferenceDescription_init()
static UA_INLINE void UA_ReferenceDescription_init (UA_ReferenceDescription * p) static
Definition at line 4521 of file libs/include/open62541/types_generated_handling.h.
UA_ReferenceDescription_new()
static UA_INLINE UA_ReferenceDescription* UA_ReferenceDescription_new (void) static
Definition at line 4526 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_ReferenceTypeAttributes_clear()
static UA_INLINE void UA_ReferenceTypeAttributes_clear (UA_ReferenceTypeAttributes * p) static
Definition at line 3388 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_ReferenceTypeAttributes_copy()
static UA_INLINE UA_StatusCode UA_ReferenceTypeAttributes_copy (const UA_ReferenceTypeAttributes * src, UA_ReferenceTypeAttributes * dst) static
Definition at line 3378 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_ReferenceTypeAttributes_delete()
static UA_INLINE void UA_ReferenceTypeAttributes_delete (UA_ReferenceTypeAttributes * p) static
Definition at line 3393 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_ReferenceTypeAttributes_deleteMembers()
static UA_INLINE void UA_ReferenceTypeAttributes_deleteMembers (UA_ReferenceTypeAttributes * p) static
Definition at line 3383 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_ReferenceTypeAttributes_init()
static UA_INLINE void UA_ReferenceTypeAttributes_init (UA_ReferenceTypeAttributes * p) static
Definition at line 3368 of file libs/include/open62541/types_generated_handling.h.
UA_ReferenceTypeAttributes_new()
static UA_INLINE UA_ReferenceTypeAttributes* UA_ReferenceTypeAttributes_new (void) static
Definition at line 3373 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_RegisteredServer_clear()
static UA_INLINE void UA_RegisteredServer_clear (UA_RegisteredServer * p) static
Definition at line 5068 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_RegisteredServer_copy()
static UA_INLINE UA_StatusCode UA_RegisteredServer_copy (const UA_RegisteredServer * src, UA_RegisteredServer * dst) static
Definition at line 5058 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_RegisteredServer_delete()
static UA_INLINE void UA_RegisteredServer_delete (UA_RegisteredServer * p) static
Definition at line 5073 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_RegisteredServer_deleteMembers()
static UA_INLINE void UA_RegisteredServer_deleteMembers (UA_RegisteredServer * p) static
Definition at line 5063 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_RegisteredServer_init()
static UA_INLINE void UA_RegisteredServer_init (UA_RegisteredServer * p) static
Definition at line 5048 of file libs/include/open62541/types_generated_handling.h.
UA_RegisteredServer_new()
static UA_INLINE UA_RegisteredServer* UA_RegisteredServer_new (void) static
Definition at line 5053 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_RegisterNodesRequest_clear()
static UA_INLINE void UA_RegisterNodesRequest_clear (UA_RegisterNodesRequest * p) static
Definition at line 4013 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_RegisterNodesRequest_copy()
static UA_INLINE UA_StatusCode UA_RegisterNodesRequest_copy (const UA_RegisterNodesRequest * src, UA_RegisterNodesRequest * dst) static
Definition at line 4003 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_RegisterNodesRequest_delete()
static UA_INLINE void UA_RegisterNodesRequest_delete (UA_RegisterNodesRequest * p) static
Definition at line 4018 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_RegisterNodesRequest_deleteMembers()
static UA_INLINE void UA_RegisterNodesRequest_deleteMembers (UA_RegisterNodesRequest * p) static
Definition at line 4008 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_RegisterNodesRequest_init()
static UA_INLINE void UA_RegisterNodesRequest_init (UA_RegisterNodesRequest * p) static
Definition at line 3993 of file libs/include/open62541/types_generated_handling.h.
UA_RegisterNodesRequest_new()
static UA_INLINE UA_RegisterNodesRequest* UA_RegisterNodesRequest_new (void) static
Definition at line 3998 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_RegisterNodesResponse_clear()
static UA_INLINE void UA_RegisterNodesResponse_clear (UA_RegisterNodesResponse * p) static
Definition at line 4261 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_RegisterNodesResponse_copy()
static UA_INLINE UA_StatusCode UA_RegisterNodesResponse_copy (const UA_RegisterNodesResponse * src, UA_RegisterNodesResponse * dst) static
Definition at line 4251 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_RegisterNodesResponse_delete()
static UA_INLINE void UA_RegisterNodesResponse_delete (UA_RegisterNodesResponse * p) static
Definition at line 4266 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_RegisterNodesResponse_deleteMembers()
static UA_INLINE void UA_RegisterNodesResponse_deleteMembers (UA_RegisterNodesResponse * p) static
Definition at line 4256 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_RegisterNodesResponse_init()
static UA_INLINE void UA_RegisterNodesResponse_init (UA_RegisterNodesResponse * p) static
Definition at line 4241 of file libs/include/open62541/types_generated_handling.h.
UA_RegisterNodesResponse_new()
static UA_INLINE UA_RegisterNodesResponse* UA_RegisterNodesResponse_new (void) static
Definition at line 4246 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_RegisterServer2Request_clear()
static UA_INLINE void UA_RegisterServer2Request_clear (UA_RegisterServer2Request * p) static
Definition at line 5347 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_RegisterServer2Request_copy()
static UA_INLINE UA_StatusCode UA_RegisterServer2Request_copy (const UA_RegisterServer2Request * src, UA_RegisterServer2Request * dst) static
Definition at line 5337 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_RegisterServer2Request_delete()
static UA_INLINE void UA_RegisterServer2Request_delete (UA_RegisterServer2Request * p) static
Definition at line 5352 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_RegisterServer2Request_deleteMembers()
static UA_INLINE void UA_RegisterServer2Request_deleteMembers (UA_RegisterServer2Request * p) static
Definition at line 5342 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_RegisterServer2Request_init()
static UA_INLINE void UA_RegisterServer2Request_init (UA_RegisterServer2Request * p) static
Definition at line 5327 of file libs/include/open62541/types_generated_handling.h.
UA_RegisterServer2Request_new()
static UA_INLINE UA_RegisterServer2Request* UA_RegisterServer2Request_new (void) static
Definition at line 5332 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_RegisterServer2Response_clear()
static UA_INLINE void UA_RegisterServer2Response_clear (UA_RegisterServer2Response * p) static
Definition at line 2483 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_RegisterServer2Response_copy()
static UA_INLINE UA_StatusCode UA_RegisterServer2Response_copy (const UA_RegisterServer2Response * src, UA_RegisterServer2Response * dst) static
Definition at line 2473 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_RegisterServer2Response_delete()
static UA_INLINE void UA_RegisterServer2Response_delete (UA_RegisterServer2Response * p) static
Definition at line 2488 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_RegisterServer2Response_deleteMembers()
static UA_INLINE void UA_RegisterServer2Response_deleteMembers (UA_RegisterServer2Response * p) static
Definition at line 2478 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_RegisterServer2Response_init()
static UA_INLINE void UA_RegisterServer2Response_init (UA_RegisterServer2Response * p) static
Definition at line 2463 of file libs/include/open62541/types_generated_handling.h.
UA_RegisterServer2Response_new()
static UA_INLINE UA_RegisterServer2Response* UA_RegisterServer2Response_new (void) static
Definition at line 2468 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_RegisterServerRequest_clear()
static UA_INLINE void UA_RegisterServerRequest_clear (UA_RegisterServerRequest * p) static
Definition at line 5627 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_RegisterServerRequest_copy()
static UA_INLINE UA_StatusCode UA_RegisterServerRequest_copy (const UA_RegisterServerRequest * src, UA_RegisterServerRequest * dst) static
Definition at line 5617 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_RegisterServerRequest_delete()
static UA_INLINE void UA_RegisterServerRequest_delete (UA_RegisterServerRequest * p) static
Definition at line 5632 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_RegisterServerRequest_deleteMembers()
static UA_INLINE void UA_RegisterServerRequest_deleteMembers (UA_RegisterServerRequest * p) static
Definition at line 5622 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_RegisterServerRequest_init()
static UA_INLINE void UA_RegisterServerRequest_init (UA_RegisterServerRequest * p) static
Definition at line 5607 of file libs/include/open62541/types_generated_handling.h.
UA_RegisterServerRequest_new()
static UA_INLINE UA_RegisterServerRequest* UA_RegisterServerRequest_new (void) static
Definition at line 5612 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_RegisterServerResponse_clear()
static UA_INLINE void UA_RegisterServerResponse_clear (UA_RegisterServerResponse * p) static
Definition at line 2421 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_RegisterServerResponse_copy()
static UA_INLINE UA_StatusCode UA_RegisterServerResponse_copy (const UA_RegisterServerResponse * src, UA_RegisterServerResponse * dst) static
Definition at line 2411 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_RegisterServerResponse_delete()
static UA_INLINE void UA_RegisterServerResponse_delete (UA_RegisterServerResponse * p) static
Definition at line 2426 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_RegisterServerResponse_deleteMembers()
static UA_INLINE void UA_RegisterServerResponse_deleteMembers (UA_RegisterServerResponse * p) static
Definition at line 2416 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_RegisterServerResponse_init()
static UA_INLINE void UA_RegisterServerResponse_init (UA_RegisterServerResponse * p) static
Definition at line 2401 of file libs/include/open62541/types_generated_handling.h.
UA_RegisterServerResponse_new()
static UA_INLINE UA_RegisterServerResponse* UA_RegisterServerResponse_new (void) static
Definition at line 2406 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_RelativePath_clear()
static UA_INLINE void UA_RelativePath_clear (UA_RelativePath * p) static
Definition at line 3014 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_RelativePath_copy()
static UA_INLINE UA_StatusCode UA_RelativePath_copy (const UA_RelativePath * src, UA_RelativePath * dst) static
Definition at line 3004 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_RelativePath_delete()
static UA_INLINE void UA_RelativePath_delete (UA_RelativePath * p) static
Definition at line 3019 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_RelativePath_deleteMembers()
static UA_INLINE void UA_RelativePath_deleteMembers (UA_RelativePath * p) static
Definition at line 3009 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_RelativePath_init()
static UA_INLINE void UA_RelativePath_init (UA_RelativePath * p) static
Definition at line 2994 of file libs/include/open62541/types_generated_handling.h.
UA_RelativePath_new()
static UA_INLINE UA_RelativePath* UA_RelativePath_new (void) static
Definition at line 2999 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_RelativePathElement_clear()
static UA_INLINE void UA_RelativePathElement_clear (UA_RelativePathElement * p) static
Definition at line 2545 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_RelativePathElement_copy()
static UA_INLINE UA_StatusCode UA_RelativePathElement_copy (const UA_RelativePathElement * src, UA_RelativePathElement * dst) static
Definition at line 2535 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_RelativePathElement_delete()
static UA_INLINE void UA_RelativePathElement_delete (UA_RelativePathElement * p) static
Definition at line 2550 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_RelativePathElement_deleteMembers()
static UA_INLINE void UA_RelativePathElement_deleteMembers (UA_RelativePathElement * p) static
Definition at line 2540 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_RelativePathElement_init()
static UA_INLINE void UA_RelativePathElement_init (UA_RelativePathElement * p) static
Definition at line 2525 of file libs/include/open62541/types_generated_handling.h.
UA_RelativePathElement_new()
static UA_INLINE UA_RelativePathElement* UA_RelativePathElement_new (void) static
Definition at line 2530 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_RepublishRequest_clear()
static UA_INLINE void UA_RepublishRequest_clear (UA_RepublishRequest * p) static
Definition at line 4230 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_RepublishRequest_copy()
static UA_INLINE UA_StatusCode UA_RepublishRequest_copy (const UA_RepublishRequest * src, UA_RepublishRequest * dst) static
Definition at line 4220 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_RepublishRequest_delete()
static UA_INLINE void UA_RepublishRequest_delete (UA_RepublishRequest * p) static
Definition at line 4235 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_RepublishRequest_deleteMembers()
static UA_INLINE void UA_RepublishRequest_deleteMembers (UA_RepublishRequest * p) static
Definition at line 4225 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_RepublishRequest_init()
static UA_INLINE void UA_RepublishRequest_init (UA_RepublishRequest * p) static
Definition at line 4210 of file libs/include/open62541/types_generated_handling.h.
UA_RepublishRequest_new()
static UA_INLINE UA_RepublishRequest* UA_RepublishRequest_new (void) static
Definition at line 4215 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_RepublishResponse_clear()
static UA_INLINE void UA_RepublishResponse_clear (UA_RepublishResponse * p) static
Definition at line 3951 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_RepublishResponse_copy()
static UA_INLINE UA_StatusCode UA_RepublishResponse_copy (const UA_RepublishResponse * src, UA_RepublishResponse * dst) static
Definition at line 3941 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_RepublishResponse_delete()
static UA_INLINE void UA_RepublishResponse_delete (UA_RepublishResponse * p) static
Definition at line 3956 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_RepublishResponse_deleteMembers()
static UA_INLINE void UA_RepublishResponse_deleteMembers (UA_RepublishResponse * p) static
Definition at line 3946 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_RepublishResponse_init()
static UA_INLINE void UA_RepublishResponse_init (UA_RepublishResponse * p) static
Definition at line 3931 of file libs/include/open62541/types_generated_handling.h.
UA_RepublishResponse_new()
static UA_INLINE UA_RepublishResponse* UA_RepublishResponse_new (void) static
Definition at line 3936 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_RequestHeader_clear()
static UA_INLINE void UA_RequestHeader_clear (UA_RequestHeader * p) static
Definition at line 1578 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_RequestHeader_copy()
static UA_INLINE UA_StatusCode UA_RequestHeader_copy (const UA_RequestHeader * src, UA_RequestHeader * dst) static
Definition at line 1568 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_RequestHeader_delete()
static UA_INLINE void UA_RequestHeader_delete (UA_RequestHeader * p) static
Definition at line 1583 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_RequestHeader_deleteMembers()
static UA_INLINE void UA_RequestHeader_deleteMembers (UA_RequestHeader * p) static
Definition at line 1573 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_RequestHeader_init()
static UA_INLINE void UA_RequestHeader_init (UA_RequestHeader * p) static
Definition at line 1558 of file libs/include/open62541/types_generated_handling.h.
UA_RequestHeader_new()
static UA_INLINE UA_RequestHeader* UA_RequestHeader_new (void) static
Definition at line 1563 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_ResponseHeader_clear()
static UA_INLINE void UA_ResponseHeader_clear (UA_ResponseHeader * p) static
Definition at line 1266 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_ResponseHeader_copy()
static UA_INLINE UA_StatusCode UA_ResponseHeader_copy (const UA_ResponseHeader * src, UA_ResponseHeader * dst) static
Definition at line 1256 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_ResponseHeader_delete()
static UA_INLINE void UA_ResponseHeader_delete (UA_ResponseHeader * p) static
Definition at line 1271 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_ResponseHeader_deleteMembers()
static UA_INLINE void UA_ResponseHeader_deleteMembers (UA_ResponseHeader * p) static
Definition at line 1261 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_ResponseHeader_init()
static UA_INLINE void UA_ResponseHeader_init (UA_ResponseHeader * p) static
Definition at line 1246 of file libs/include/open62541/types_generated_handling.h.
UA_ResponseHeader_new()
static UA_INLINE UA_ResponseHeader* UA_ResponseHeader_new (void) static
Definition at line 1251 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_SByte_clear()
static UA_INLINE void UA_SByte_clear (UA_SByte * p) static
Definition at line 73 of file libs/include/open62541/types_generated_handling.h.
UA_SByte_copy()
static UA_INLINE UA_StatusCode UA_SByte_copy (const UA_SByte * src, UA_SByte * dst) static
Definition at line 62 of file libs/include/open62541/types_generated_handling.h.
UA_SByte_delete()
static UA_INLINE void UA_SByte_delete (UA_SByte * p) static
Definition at line 78 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_SByte_deleteMembers()
static UA_INLINE void UA_SByte_deleteMembers (UA_SByte * p) static
Definition at line 68 of file libs/include/open62541/types_generated_handling.h.
UA_SByte_init()
static UA_INLINE void UA_SByte_init (UA_SByte * p) static
Definition at line 52 of file libs/include/open62541/types_generated_handling.h.
UA_SByte_new()
static UA_INLINE UA_SByte* UA_SByte_new (void) static
Definition at line 57 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_SecurityTokenRequestType_clear()
static UA_INLINE void UA_SecurityTokenRequestType_clear (UA_SecurityTokenRequestType * p) static
Definition at line 1954 of file libs/include/open62541/types_generated_handling.h.
UA_SecurityTokenRequestType_copy()
static UA_INLINE UA_StatusCode UA_SecurityTokenRequestType_copy (const UA_SecurityTokenRequestType * src, UA_SecurityTokenRequestType * dst) static
Definition at line 1943 of file libs/include/open62541/types_generated_handling.h.
UA_SecurityTokenRequestType_delete()
static UA_INLINE void UA_SecurityTokenRequestType_delete (UA_SecurityTokenRequestType * p) static
Definition at line 1959 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_SecurityTokenRequestType_deleteMembers()
static UA_INLINE void UA_SecurityTokenRequestType_deleteMembers (UA_SecurityTokenRequestType * p) static
Definition at line 1949 of file libs/include/open62541/types_generated_handling.h.
UA_SecurityTokenRequestType_init()
static UA_INLINE void UA_SecurityTokenRequestType_init (UA_SecurityTokenRequestType * p) static
Definition at line 1933 of file libs/include/open62541/types_generated_handling.h.
UA_SecurityTokenRequestType_new()
static UA_INLINE UA_SecurityTokenRequestType* UA_SecurityTokenRequestType_new (void) static
Definition at line 1938 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_ServerDiagnosticsSummaryDataType_clear()
static UA_INLINE void UA_ServerDiagnosticsSummaryDataType_clear (UA_ServerDiagnosticsSummaryDataType * p) static
Definition at line 1017 of file libs/include/open62541/types_generated_handling.h.
UA_ServerDiagnosticsSummaryDataType_copy()
static UA_INLINE UA_StatusCode UA_ServerDiagnosticsSummaryDataType_copy (const UA_ServerDiagnosticsSummaryDataType * src, UA_ServerDiagnosticsSummaryDataType * dst) static
Definition at line 1006 of file libs/include/open62541/types_generated_handling.h.
UA_ServerDiagnosticsSummaryDataType_delete()
static UA_INLINE void UA_ServerDiagnosticsSummaryDataType_delete (UA_ServerDiagnosticsSummaryDataType * p) static
Definition at line 1022 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_ServerDiagnosticsSummaryDataType_deleteMembers()
static UA_INLINE void UA_ServerDiagnosticsSummaryDataType_deleteMembers (UA_ServerDiagnosticsSummaryDataType * p) static
Definition at line 1012 of file libs/include/open62541/types_generated_handling.h.
UA_ServerDiagnosticsSummaryDataType_init()
static UA_INLINE void UA_ServerDiagnosticsSummaryDataType_init (UA_ServerDiagnosticsSummaryDataType * p) static
Definition at line 996 of file libs/include/open62541/types_generated_handling.h.
UA_ServerDiagnosticsSummaryDataType_new()
static UA_INLINE UA_ServerDiagnosticsSummaryDataType* UA_ServerDiagnosticsSummaryDataType_new (void) static
Definition at line 1001 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_ServerOnNetwork_clear()
static UA_INLINE void UA_ServerOnNetwork_clear (UA_ServerOnNetwork * p) static
Definition at line 2078 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_ServerOnNetwork_copy()
static UA_INLINE UA_StatusCode UA_ServerOnNetwork_copy (const UA_ServerOnNetwork * src, UA_ServerOnNetwork * dst) static
Definition at line 2068 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_ServerOnNetwork_delete()
static UA_INLINE void UA_ServerOnNetwork_delete (UA_ServerOnNetwork * p) static
Definition at line 2083 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_ServerOnNetwork_deleteMembers()
static UA_INLINE void UA_ServerOnNetwork_deleteMembers (UA_ServerOnNetwork * p) static
Definition at line 2073 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_ServerOnNetwork_init()
static UA_INLINE void UA_ServerOnNetwork_init (UA_ServerOnNetwork * p) static
Definition at line 2058 of file libs/include/open62541/types_generated_handling.h.
UA_ServerOnNetwork_new()
static UA_INLINE UA_ServerOnNetwork* UA_ServerOnNetwork_new (void) static
Definition at line 2063 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_ServerState_clear()
static UA_INLINE void UA_ServerState_clear (UA_ServerState * p) static
Definition at line 3795 of file libs/include/open62541/types_generated_handling.h.
UA_ServerState_copy()
static UA_INLINE UA_StatusCode UA_ServerState_copy (const UA_ServerState * src, UA_ServerState * dst) static
Definition at line 3784 of file libs/include/open62541/types_generated_handling.h.
UA_ServerState_delete()
static UA_INLINE void UA_ServerState_delete (UA_ServerState * p) static
Definition at line 3800 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_ServerState_deleteMembers()
static UA_INLINE void UA_ServerState_deleteMembers (UA_ServerState * p) static
Definition at line 3790 of file libs/include/open62541/types_generated_handling.h.
UA_ServerState_init()
static UA_INLINE void UA_ServerState_init (UA_ServerState * p) static
Definition at line 3774 of file libs/include/open62541/types_generated_handling.h.
UA_ServerState_new()
static UA_INLINE UA_ServerState* UA_ServerState_new (void) static
Definition at line 3779 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_ServerStatusDataType_clear()
static UA_INLINE void UA_ServerStatusDataType_clear (UA_ServerStatusDataType * p) static
Definition at line 5006 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_ServerStatusDataType_copy()
static UA_INLINE UA_StatusCode UA_ServerStatusDataType_copy (const UA_ServerStatusDataType * src, UA_ServerStatusDataType * dst) static
Definition at line 4996 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_ServerStatusDataType_delete()
static UA_INLINE void UA_ServerStatusDataType_delete (UA_ServerStatusDataType * p) static
Definition at line 5011 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_ServerStatusDataType_deleteMembers()
static UA_INLINE void UA_ServerStatusDataType_deleteMembers (UA_ServerStatusDataType * p) static
Definition at line 5001 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_ServerStatusDataType_init()
static UA_INLINE void UA_ServerStatusDataType_init (UA_ServerStatusDataType * p) static
Definition at line 4986 of file libs/include/open62541/types_generated_handling.h.
UA_ServerStatusDataType_new()
static UA_INLINE UA_ServerStatusDataType* UA_ServerStatusDataType_new (void) static
Definition at line 4991 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_ServiceFault_clear()
static UA_INLINE void UA_ServiceFault_clear (UA_ServiceFault * p) static
Definition at line 4727 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_ServiceFault_copy()
static UA_INLINE UA_StatusCode UA_ServiceFault_copy (const UA_ServiceFault * src, UA_ServiceFault * dst) static
Definition at line 4717 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_ServiceFault_delete()
static UA_INLINE void UA_ServiceFault_delete (UA_ServiceFault * p) static
Definition at line 4732 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_ServiceFault_deleteMembers()
static UA_INLINE void UA_ServiceFault_deleteMembers (UA_ServiceFault * p) static
Definition at line 4722 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_ServiceFault_init()
static UA_INLINE void UA_ServiceFault_init (UA_ServiceFault * p) static
Definition at line 4707 of file libs/include/open62541/types_generated_handling.h.
UA_ServiceFault_new()
static UA_INLINE UA_ServiceFault* UA_ServiceFault_new (void) static
Definition at line 4712 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_SetMonitoringModeRequest_clear()
static UA_INLINE void UA_SetMonitoringModeRequest_clear (UA_SetMonitoringModeRequest * p) static
Definition at line 3326 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_SetMonitoringModeRequest_copy()
static UA_INLINE UA_StatusCode UA_SetMonitoringModeRequest_copy (const UA_SetMonitoringModeRequest * src, UA_SetMonitoringModeRequest * dst) static
Definition at line 3316 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_SetMonitoringModeRequest_delete()
static UA_INLINE void UA_SetMonitoringModeRequest_delete (UA_SetMonitoringModeRequest * p) static
Definition at line 3331 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_SetMonitoringModeRequest_deleteMembers()
static UA_INLINE void UA_SetMonitoringModeRequest_deleteMembers (UA_SetMonitoringModeRequest * p) static
Definition at line 3321 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_SetMonitoringModeRequest_init()
static UA_INLINE void UA_SetMonitoringModeRequest_init (UA_SetMonitoringModeRequest * p) static
Definition at line 3306 of file libs/include/open62541/types_generated_handling.h.
UA_SetMonitoringModeRequest_new()
static UA_INLINE UA_SetMonitoringModeRequest* UA_SetMonitoringModeRequest_new (void) static
Definition at line 3311 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_SetMonitoringModeResponse_clear()
static UA_INLINE void UA_SetMonitoringModeResponse_clear (UA_SetMonitoringModeResponse * p) static
Definition at line 1515 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_SetMonitoringModeResponse_copy()
static UA_INLINE UA_StatusCode UA_SetMonitoringModeResponse_copy (const UA_SetMonitoringModeResponse * src, UA_SetMonitoringModeResponse * dst) static
Definition at line 1505 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_SetMonitoringModeResponse_delete()
static UA_INLINE void UA_SetMonitoringModeResponse_delete (UA_SetMonitoringModeResponse * p) static
Definition at line 1520 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_SetMonitoringModeResponse_deleteMembers()
static UA_INLINE void UA_SetMonitoringModeResponse_deleteMembers (UA_SetMonitoringModeResponse * p) static
Definition at line 1510 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_SetMonitoringModeResponse_init()
static UA_INLINE void UA_SetMonitoringModeResponse_init (UA_SetMonitoringModeResponse * p) static
Definition at line 1495 of file libs/include/open62541/types_generated_handling.h.
UA_SetMonitoringModeResponse_new()
static UA_INLINE UA_SetMonitoringModeResponse* UA_SetMonitoringModeResponse_new (void) static
Definition at line 1500 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_SetPublishingModeRequest_clear()
static UA_INLINE void UA_SetPublishingModeRequest_clear (UA_SetPublishingModeRequest * p) static
Definition at line 2016 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_SetPublishingModeRequest_copy()
static UA_INLINE UA_StatusCode UA_SetPublishingModeRequest_copy (const UA_SetPublishingModeRequest * src, UA_SetPublishingModeRequest * dst) static
Definition at line 2006 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_SetPublishingModeRequest_delete()
static UA_INLINE void UA_SetPublishingModeRequest_delete (UA_SetPublishingModeRequest * p) static
Definition at line 2021 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_SetPublishingModeRequest_deleteMembers()
static UA_INLINE void UA_SetPublishingModeRequest_deleteMembers (UA_SetPublishingModeRequest * p) static
Definition at line 2011 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_SetPublishingModeRequest_init()
static UA_INLINE void UA_SetPublishingModeRequest_init (UA_SetPublishingModeRequest * p) static
Definition at line 1996 of file libs/include/open62541/types_generated_handling.h.
UA_SetPublishingModeRequest_new()
static UA_INLINE UA_SetPublishingModeRequest* UA_SetPublishingModeRequest_new (void) static
Definition at line 2001 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_SetPublishingModeResponse_clear()
static UA_INLINE void UA_SetPublishingModeResponse_clear (UA_SetPublishingModeResponse * p) static
Definition at line 3512 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_SetPublishingModeResponse_copy()
static UA_INLINE UA_StatusCode UA_SetPublishingModeResponse_copy (const UA_SetPublishingModeResponse * src, UA_SetPublishingModeResponse * dst) static
Definition at line 3502 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_SetPublishingModeResponse_delete()
static UA_INLINE void UA_SetPublishingModeResponse_delete (UA_SetPublishingModeResponse * p) static
Definition at line 3517 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_SetPublishingModeResponse_deleteMembers()
static UA_INLINE void UA_SetPublishingModeResponse_deleteMembers (UA_SetPublishingModeResponse * p) static
Definition at line 3507 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_SetPublishingModeResponse_init()
static UA_INLINE void UA_SetPublishingModeResponse_init (UA_SetPublishingModeResponse * p) static
Definition at line 3492 of file libs/include/open62541/types_generated_handling.h.
UA_SetPublishingModeResponse_new()
static UA_INLINE UA_SetPublishingModeResponse* UA_SetPublishingModeResponse_new (void) static
Definition at line 3497 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_SetTriggeringRequest_clear()
static UA_INLINE void UA_SetTriggeringRequest_clear (UA_SetTriggeringRequest * p) static
Definition at line 4882 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_SetTriggeringRequest_copy()
static UA_INLINE UA_StatusCode UA_SetTriggeringRequest_copy (const UA_SetTriggeringRequest * src, UA_SetTriggeringRequest * dst) static
Definition at line 4872 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_SetTriggeringRequest_delete()
static UA_INLINE void UA_SetTriggeringRequest_delete (UA_SetTriggeringRequest * p) static
Definition at line 4887 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_SetTriggeringRequest_deleteMembers()
static UA_INLINE void UA_SetTriggeringRequest_deleteMembers (UA_SetTriggeringRequest * p) static
Definition at line 4877 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_SetTriggeringRequest_init()
static UA_INLINE void UA_SetTriggeringRequest_init (UA_SetTriggeringRequest * p) static
Definition at line 4862 of file libs/include/open62541/types_generated_handling.h.
UA_SetTriggeringRequest_new()
static UA_INLINE UA_SetTriggeringRequest* UA_SetTriggeringRequest_new (void) static
Definition at line 4867 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_SetTriggeringResponse_clear()
static UA_INLINE void UA_SetTriggeringResponse_clear (UA_SetTriggeringResponse * p) static
Definition at line 4168 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_SetTriggeringResponse_copy()
static UA_INLINE UA_StatusCode UA_SetTriggeringResponse_copy (const UA_SetTriggeringResponse * src, UA_SetTriggeringResponse * dst) static
Definition at line 4158 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_SetTriggeringResponse_delete()
static UA_INLINE void UA_SetTriggeringResponse_delete (UA_SetTriggeringResponse * p) static
Definition at line 4173 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_SetTriggeringResponse_deleteMembers()
static UA_INLINE void UA_SetTriggeringResponse_deleteMembers (UA_SetTriggeringResponse * p) static
Definition at line 4163 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_SetTriggeringResponse_init()
static UA_INLINE void UA_SetTriggeringResponse_init (UA_SetTriggeringResponse * p) static
Definition at line 4148 of file libs/include/open62541/types_generated_handling.h.
UA_SetTriggeringResponse_new()
static UA_INLINE UA_SetTriggeringResponse* UA_SetTriggeringResponse_new (void) static
Definition at line 4153 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_SignatureData_clear()
static UA_INLINE void UA_SignatureData_clear (UA_SignatureData * p) static
Definition at line 1297 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_SignatureData_copy()
static UA_INLINE UA_StatusCode UA_SignatureData_copy (const UA_SignatureData * src, UA_SignatureData * dst) static
Definition at line 1287 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_SignatureData_delete()
static UA_INLINE void UA_SignatureData_delete (UA_SignatureData * p) static
Definition at line 1302 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_SignatureData_deleteMembers()
static UA_INLINE void UA_SignatureData_deleteMembers (UA_SignatureData * p) static
Definition at line 1292 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_SignatureData_init()
static UA_INLINE void UA_SignatureData_init (UA_SignatureData * p) static
Definition at line 1277 of file libs/include/open62541/types_generated_handling.h.
UA_SignatureData_new()
static UA_INLINE UA_SignatureData* UA_SignatureData_new (void) static
Definition at line 1282 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_SignedSoftwareCertificate_clear()
static UA_INLINE void UA_SignedSoftwareCertificate_clear (UA_SignedSoftwareCertificate * p) static
Definition at line 2297 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_SignedSoftwareCertificate_copy()
static UA_INLINE UA_StatusCode UA_SignedSoftwareCertificate_copy (const UA_SignedSoftwareCertificate * src, UA_SignedSoftwareCertificate * dst) static
Definition at line 2287 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_SignedSoftwareCertificate_delete()
static UA_INLINE void UA_SignedSoftwareCertificate_delete (UA_SignedSoftwareCertificate * p) static
Definition at line 2302 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_SignedSoftwareCertificate_deleteMembers()
static UA_INLINE void UA_SignedSoftwareCertificate_deleteMembers (UA_SignedSoftwareCertificate * p) static
Definition at line 2292 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_SignedSoftwareCertificate_init()
static UA_INLINE void UA_SignedSoftwareCertificate_init (UA_SignedSoftwareCertificate * p) static
Definition at line 2277 of file libs/include/open62541/types_generated_handling.h.
UA_SignedSoftwareCertificate_new()
static UA_INLINE UA_SignedSoftwareCertificate* UA_SignedSoftwareCertificate_new (void) static
Definition at line 2282 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_SimpleAttributeOperand_clear()
static UA_INLINE void UA_SimpleAttributeOperand_clear (UA_SimpleAttributeOperand * p) static
Definition at line 4199 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_SimpleAttributeOperand_copy()
static UA_INLINE UA_StatusCode UA_SimpleAttributeOperand_copy (const UA_SimpleAttributeOperand * src, UA_SimpleAttributeOperand * dst) static
Definition at line 4189 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_SimpleAttributeOperand_delete()
static UA_INLINE void UA_SimpleAttributeOperand_delete (UA_SimpleAttributeOperand * p) static
Definition at line 4204 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_SimpleAttributeOperand_deleteMembers()
static UA_INLINE void UA_SimpleAttributeOperand_deleteMembers (UA_SimpleAttributeOperand * p) static
Definition at line 4194 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_SimpleAttributeOperand_init()
static UA_INLINE void UA_SimpleAttributeOperand_init (UA_SimpleAttributeOperand * p) static
Definition at line 4179 of file libs/include/open62541/types_generated_handling.h.
UA_SimpleAttributeOperand_new()
static UA_INLINE UA_SimpleAttributeOperand* UA_SimpleAttributeOperand_new (void) static
Definition at line 4184 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_StatusChangeNotification_clear()
static UA_INLINE void UA_StatusChangeNotification_clear (UA_StatusChangeNotification * p) static
Definition at line 3543 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_StatusChangeNotification_copy()
static UA_INLINE UA_StatusCode UA_StatusChangeNotification_copy (const UA_StatusChangeNotification * src, UA_StatusChangeNotification * dst) static
Definition at line 3533 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_StatusChangeNotification_delete()
static UA_INLINE void UA_StatusChangeNotification_delete (UA_StatusChangeNotification * p) static
Definition at line 3548 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_StatusChangeNotification_deleteMembers()
static UA_INLINE void UA_StatusChangeNotification_deleteMembers (UA_StatusChangeNotification * p) static
Definition at line 3538 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_StatusChangeNotification_init()
static UA_INLINE void UA_StatusChangeNotification_init (UA_StatusChangeNotification * p) static
Definition at line 3523 of file libs/include/open62541/types_generated_handling.h.
UA_StatusChangeNotification_new()
static UA_INLINE UA_StatusChangeNotification* UA_StatusChangeNotification_new (void) static
Definition at line 3528 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_StatusCode_clear()
static UA_INLINE void UA_StatusCode_clear (UA_StatusCode * p) static
Definition at line 612 of file libs/include/open62541/types_generated_handling.h.
UA_StatusCode_copy()
static UA_INLINE UA_StatusCode UA_StatusCode_copy (const UA_StatusCode * src, UA_StatusCode * dst) static
Definition at line 601 of file libs/include/open62541/types_generated_handling.h.
UA_StatusCode_delete()
static UA_INLINE void UA_StatusCode_delete (UA_StatusCode * p) static
Definition at line 617 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_StatusCode_deleteMembers()
static UA_INLINE void UA_StatusCode_deleteMembers (UA_StatusCode * p) static
Definition at line 607 of file libs/include/open62541/types_generated_handling.h.
UA_StatusCode_init()
static UA_INLINE void UA_StatusCode_init (UA_StatusCode * p) static
Definition at line 591 of file libs/include/open62541/types_generated_handling.h.
UA_StatusCode_new()
static UA_INLINE UA_StatusCode* UA_StatusCode_new (void) static
Definition at line 596 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_String_clear()
static UA_INLINE void UA_String_clear (UA_String * p) static
Definition at line 392 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_String_copy()
static UA_INLINE UA_StatusCode UA_String_copy (const UA_String * src, UA_String * dst) static
Definition at line 382 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_String_delete()
static UA_INLINE void UA_String_delete (UA_String * p) static
Definition at line 397 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
Referenced by function_namespace0_generated_65_begin(), and function_namespace0_generated_66_begin().
UA_String_deleteMembers()
static UA_INLINE void UA_String_deleteMembers (UA_String * p) static
Definition at line 387 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_String_init()
static UA_INLINE void UA_String_init (UA_String * p) static
Definition at line 372 of file libs/include/open62541/types_generated_handling.h.
Referenced by function_namespace0_generated_65_begin(), and function_namespace0_generated_66_begin().
UA_String_new()
static UA_INLINE UA_String* UA_String_new (void) static
Definition at line 377 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
Referenced by function_namespace0_generated_65_begin(), and function_namespace0_generated_66_begin().
UA_SubscriptionAcknowledgement_clear()
static UA_INLINE void UA_SubscriptionAcknowledgement_clear (UA_SubscriptionAcknowledgement * p) static
Definition at line 2577 of file libs/include/open62541/types_generated_handling.h.
UA_SubscriptionAcknowledgement_copy()
static UA_INLINE UA_StatusCode UA_SubscriptionAcknowledgement_copy (const UA_SubscriptionAcknowledgement * src, UA_SubscriptionAcknowledgement * dst) static
Definition at line 2566 of file libs/include/open62541/types_generated_handling.h.
UA_SubscriptionAcknowledgement_delete()
static UA_INLINE void UA_SubscriptionAcknowledgement_delete (UA_SubscriptionAcknowledgement * p) static
Definition at line 2582 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_SubscriptionAcknowledgement_deleteMembers()
static UA_INLINE void UA_SubscriptionAcknowledgement_deleteMembers (UA_SubscriptionAcknowledgement * p) static
Definition at line 2572 of file libs/include/open62541/types_generated_handling.h.
UA_SubscriptionAcknowledgement_init()
static UA_INLINE void UA_SubscriptionAcknowledgement_init (UA_SubscriptionAcknowledgement * p) static
Definition at line 2556 of file libs/include/open62541/types_generated_handling.h.
UA_SubscriptionAcknowledgement_new()
static UA_INLINE UA_SubscriptionAcknowledgement* UA_SubscriptionAcknowledgement_new (void) static
Definition at line 2561 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_TimestampsToReturn_clear()
static UA_INLINE void UA_TimestampsToReturn_clear (UA_TimestampsToReturn * p) static
Definition at line 1859 of file libs/include/open62541/types_generated_handling.h.
UA_TimestampsToReturn_copy()
static UA_INLINE UA_StatusCode UA_TimestampsToReturn_copy (const UA_TimestampsToReturn * src, UA_TimestampsToReturn * dst) static
Definition at line 1848 of file libs/include/open62541/types_generated_handling.h.
UA_TimestampsToReturn_delete()
static UA_INLINE void UA_TimestampsToReturn_delete (UA_TimestampsToReturn * p) static
Definition at line 1864 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_TimestampsToReturn_deleteMembers()
static UA_INLINE void UA_TimestampsToReturn_deleteMembers (UA_TimestampsToReturn * p) static
Definition at line 1854 of file libs/include/open62541/types_generated_handling.h.
UA_TimestampsToReturn_init()
static UA_INLINE void UA_TimestampsToReturn_init (UA_TimestampsToReturn * p) static
Definition at line 1838 of file libs/include/open62541/types_generated_handling.h.
UA_TimestampsToReturn_new()
static UA_INLINE UA_TimestampsToReturn* UA_TimestampsToReturn_new (void) static
Definition at line 1843 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_TranslateBrowsePathsToNodeIdsRequest_clear()
static UA_INLINE void UA_TranslateBrowsePathsToNodeIdsRequest_clear (UA_TranslateBrowsePathsToNodeIdsRequest * p) static
Definition at line 5503 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_TranslateBrowsePathsToNodeIdsRequest_copy()
static UA_INLINE UA_StatusCode UA_TranslateBrowsePathsToNodeIdsRequest_copy (const UA_TranslateBrowsePathsToNodeIdsRequest * src, UA_TranslateBrowsePathsToNodeIdsRequest * dst) static
Definition at line 5493 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_TranslateBrowsePathsToNodeIdsRequest_delete()
static UA_INLINE void UA_TranslateBrowsePathsToNodeIdsRequest_delete (UA_TranslateBrowsePathsToNodeIdsRequest * p) static
Definition at line 5508 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_TranslateBrowsePathsToNodeIdsRequest_deleteMembers()
static UA_INLINE void UA_TranslateBrowsePathsToNodeIdsRequest_deleteMembers (UA_TranslateBrowsePathsToNodeIdsRequest * p) static
Definition at line 5498 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_TranslateBrowsePathsToNodeIdsRequest_init()
static UA_INLINE void UA_TranslateBrowsePathsToNodeIdsRequest_init (UA_TranslateBrowsePathsToNodeIdsRequest * p) static
Definition at line 5483 of file libs/include/open62541/types_generated_handling.h.
UA_TranslateBrowsePathsToNodeIdsRequest_new()
static UA_INLINE UA_TranslateBrowsePathsToNodeIdsRequest* UA_TranslateBrowsePathsToNodeIdsRequest_new (void) static
Definition at line 5488 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_TranslateBrowsePathsToNodeIdsResponse_clear()
static UA_INLINE void UA_TranslateBrowsePathsToNodeIdsResponse_clear (UA_TranslateBrowsePathsToNodeIdsResponse * p) static
Definition at line 5658 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_TranslateBrowsePathsToNodeIdsResponse_copy()
static UA_INLINE UA_StatusCode UA_TranslateBrowsePathsToNodeIdsResponse_copy (const UA_TranslateBrowsePathsToNodeIdsResponse * src, UA_TranslateBrowsePathsToNodeIdsResponse * dst) static
Definition at line 5648 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_TranslateBrowsePathsToNodeIdsResponse_delete()
static UA_INLINE void UA_TranslateBrowsePathsToNodeIdsResponse_delete (UA_TranslateBrowsePathsToNodeIdsResponse * p) static
Definition at line 5663 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_TranslateBrowsePathsToNodeIdsResponse_deleteMembers()
static UA_INLINE void UA_TranslateBrowsePathsToNodeIdsResponse_deleteMembers (UA_TranslateBrowsePathsToNodeIdsResponse * p) static
Definition at line 5653 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_TranslateBrowsePathsToNodeIdsResponse_init()
static UA_INLINE void UA_TranslateBrowsePathsToNodeIdsResponse_init (UA_TranslateBrowsePathsToNodeIdsResponse * p) static
Definition at line 5638 of file libs/include/open62541/types_generated_handling.h.
UA_TranslateBrowsePathsToNodeIdsResponse_new()
static UA_INLINE UA_TranslateBrowsePathsToNodeIdsResponse* UA_TranslateBrowsePathsToNodeIdsResponse_new (void) static
Definition at line 5643 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_UInt16_clear()
static UA_INLINE void UA_UInt16_clear (UA_UInt16 * p) static
Definition at line 169 of file libs/include/open62541/types_generated_handling.h.
UA_UInt16_copy()
static UA_INLINE UA_StatusCode UA_UInt16_copy (const UA_UInt16 * src, UA_UInt16 * dst) static
Definition at line 158 of file libs/include/open62541/types_generated_handling.h.
UA_UInt16_delete()
static UA_INLINE void UA_UInt16_delete (UA_UInt16 * p) static
Definition at line 174 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_UInt16_deleteMembers()
static UA_INLINE void UA_UInt16_deleteMembers (UA_UInt16 * p) static
Definition at line 164 of file libs/include/open62541/types_generated_handling.h.
UA_UInt16_init()
static UA_INLINE void UA_UInt16_init (UA_UInt16 * p) static
Definition at line 148 of file libs/include/open62541/types_generated_handling.h.
UA_UInt16_new()
static UA_INLINE UA_UInt16* UA_UInt16_new (void) static
Definition at line 153 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_UInt32_clear()
static UA_INLINE void UA_UInt32_clear (UA_UInt32 * p) static
Definition at line 233 of file libs/include/open62541/types_generated_handling.h.
UA_UInt32_copy()
static UA_INLINE UA_StatusCode UA_UInt32_copy (const UA_UInt32 * src, UA_UInt32 * dst) static
Definition at line 222 of file libs/include/open62541/types_generated_handling.h.
UA_UInt32_delete()
static UA_INLINE void UA_UInt32_delete (UA_UInt32 * p) static
Definition at line 238 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_UInt32_deleteMembers()
static UA_INLINE void UA_UInt32_deleteMembers (UA_UInt32 * p) static
Definition at line 228 of file libs/include/open62541/types_generated_handling.h.
UA_UInt32_init()
static UA_INLINE void UA_UInt32_init (UA_UInt32 * p) static
Definition at line 212 of file libs/include/open62541/types_generated_handling.h.
UA_UInt32_new()
static UA_INLINE UA_UInt32* UA_UInt32_new (void) static
Definition at line 217 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_UInt64_clear()
static UA_INLINE void UA_UInt64_clear (UA_UInt64 * p) static
Definition at line 297 of file libs/include/open62541/types_generated_handling.h.
UA_UInt64_copy()
static UA_INLINE UA_StatusCode UA_UInt64_copy (const UA_UInt64 * src, UA_UInt64 * dst) static
Definition at line 286 of file libs/include/open62541/types_generated_handling.h.
UA_UInt64_delete()
static UA_INLINE void UA_UInt64_delete (UA_UInt64 * p) static
Definition at line 302 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_UInt64_deleteMembers()
static UA_INLINE void UA_UInt64_deleteMembers (UA_UInt64 * p) static
Definition at line 292 of file libs/include/open62541/types_generated_handling.h.
UA_UInt64_init()
static UA_INLINE void UA_UInt64_init (UA_UInt64 * p) static
Definition at line 276 of file libs/include/open62541/types_generated_handling.h.
UA_UInt64_new()
static UA_INLINE UA_UInt64* UA_UInt64_new (void) static
Definition at line 281 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_UnregisterNodesRequest_clear()
static UA_INLINE void UA_UnregisterNodesRequest_clear (UA_UnregisterNodesRequest * p) static
Definition at line 4106 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_UnregisterNodesRequest_copy()
static UA_INLINE UA_StatusCode UA_UnregisterNodesRequest_copy (const UA_UnregisterNodesRequest * src, UA_UnregisterNodesRequest * dst) static
Definition at line 4096 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_UnregisterNodesRequest_delete()
static UA_INLINE void UA_UnregisterNodesRequest_delete (UA_UnregisterNodesRequest * p) static
Definition at line 4111 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_UnregisterNodesRequest_deleteMembers()
static UA_INLINE void UA_UnregisterNodesRequest_deleteMembers (UA_UnregisterNodesRequest * p) static
Definition at line 4101 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_UnregisterNodesRequest_init()
static UA_INLINE void UA_UnregisterNodesRequest_init (UA_UnregisterNodesRequest * p) static
Definition at line 4086 of file libs/include/open62541/types_generated_handling.h.
UA_UnregisterNodesRequest_new()
static UA_INLINE UA_UnregisterNodesRequest* UA_UnregisterNodesRequest_new (void) static
Definition at line 4091 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_UnregisterNodesResponse_clear()
static UA_INLINE void UA_UnregisterNodesResponse_clear (UA_UnregisterNodesResponse * p) static
Definition at line 3202 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_UnregisterNodesResponse_copy()
static UA_INLINE UA_StatusCode UA_UnregisterNodesResponse_copy (const UA_UnregisterNodesResponse * src, UA_UnregisterNodesResponse * dst) static
Definition at line 3192 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_UnregisterNodesResponse_delete()
static UA_INLINE void UA_UnregisterNodesResponse_delete (UA_UnregisterNodesResponse * p) static
Definition at line 3207 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_UnregisterNodesResponse_deleteMembers()
static UA_INLINE void UA_UnregisterNodesResponse_deleteMembers (UA_UnregisterNodesResponse * p) static
Definition at line 3197 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_UnregisterNodesResponse_init()
static UA_INLINE void UA_UnregisterNodesResponse_init (UA_UnregisterNodesResponse * p) static
Definition at line 3182 of file libs/include/open62541/types_generated_handling.h.
UA_UnregisterNodesResponse_new()
static UA_INLINE UA_UnregisterNodesResponse* UA_UnregisterNodesResponse_new (void) static
Definition at line 3187 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_UserIdentityToken_clear()
static UA_INLINE void UA_UserIdentityToken_clear (UA_UserIdentityToken * p) static
Definition at line 1173 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_UserIdentityToken_copy()
static UA_INLINE UA_StatusCode UA_UserIdentityToken_copy (const UA_UserIdentityToken * src, UA_UserIdentityToken * dst) static
Definition at line 1163 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_UserIdentityToken_delete()
static UA_INLINE void UA_UserIdentityToken_delete (UA_UserIdentityToken * p) static
Definition at line 1178 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_UserIdentityToken_deleteMembers()
static UA_INLINE void UA_UserIdentityToken_deleteMembers (UA_UserIdentityToken * p) static
Definition at line 1168 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_UserIdentityToken_init()
static UA_INLINE void UA_UserIdentityToken_init (UA_UserIdentityToken * p) static
Definition at line 1153 of file libs/include/open62541/types_generated_handling.h.
UA_UserIdentityToken_new()
static UA_INLINE UA_UserIdentityToken* UA_UserIdentityToken_new (void) static
Definition at line 1158 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_UserNameIdentityToken_clear()
static UA_INLINE void UA_UserNameIdentityToken_clear (UA_UserNameIdentityToken * p) static
Definition at line 4075 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_UserNameIdentityToken_copy()
static UA_INLINE UA_StatusCode UA_UserNameIdentityToken_copy (const UA_UserNameIdentityToken * src, UA_UserNameIdentityToken * dst) static
Definition at line 4065 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_UserNameIdentityToken_delete()
static UA_INLINE void UA_UserNameIdentityToken_delete (UA_UserNameIdentityToken * p) static
Definition at line 4080 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_UserNameIdentityToken_deleteMembers()
static UA_INLINE void UA_UserNameIdentityToken_deleteMembers (UA_UserNameIdentityToken * p) static
Definition at line 4070 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_UserNameIdentityToken_init()
static UA_INLINE void UA_UserNameIdentityToken_init (UA_UserNameIdentityToken * p) static
Definition at line 4055 of file libs/include/open62541/types_generated_handling.h.
UA_UserNameIdentityToken_new()
static UA_INLINE UA_UserNameIdentityToken* UA_UserNameIdentityToken_new (void) static
Definition at line 4060 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_UserTokenPolicy_clear()
static UA_INLINE void UA_UserTokenPolicy_clear (UA_UserTokenPolicy * p) static
Definition at line 3264 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_UserTokenPolicy_copy()
static UA_INLINE UA_StatusCode UA_UserTokenPolicy_copy (const UA_UserTokenPolicy * src, UA_UserTokenPolicy * dst) static
Definition at line 3254 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_UserTokenPolicy_delete()
static UA_INLINE void UA_UserTokenPolicy_delete (UA_UserTokenPolicy * p) static
Definition at line 3269 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_UserTokenPolicy_deleteMembers()
static UA_INLINE void UA_UserTokenPolicy_deleteMembers (UA_UserTokenPolicy * p) static
Definition at line 3259 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_UserTokenPolicy_init()
static UA_INLINE void UA_UserTokenPolicy_init (UA_UserTokenPolicy * p) static
Definition at line 3244 of file libs/include/open62541/types_generated_handling.h.
UA_UserTokenPolicy_new()
static UA_INLINE UA_UserTokenPolicy* UA_UserTokenPolicy_new (void) static
Definition at line 3249 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_UserTokenType_clear()
static UA_INLINE void UA_UserTokenType_clear (UA_UserTokenType * p) static
Definition at line 3108 of file libs/include/open62541/types_generated_handling.h.
UA_UserTokenType_copy()
static UA_INLINE UA_StatusCode UA_UserTokenType_copy (const UA_UserTokenType * src, UA_UserTokenType * dst) static
Definition at line 3097 of file libs/include/open62541/types_generated_handling.h.
UA_UserTokenType_delete()
static UA_INLINE void UA_UserTokenType_delete (UA_UserTokenType * p) static
Definition at line 3113 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_UserTokenType_deleteMembers()
static UA_INLINE void UA_UserTokenType_deleteMembers (UA_UserTokenType * p) static
Definition at line 3103 of file libs/include/open62541/types_generated_handling.h.
UA_UserTokenType_init()
static UA_INLINE void UA_UserTokenType_init (UA_UserTokenType * p) static
Definition at line 3087 of file libs/include/open62541/types_generated_handling.h.
UA_UserTokenType_new()
static UA_INLINE UA_UserTokenType* UA_UserTokenType_new (void) static
Definition at line 3092 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_UtcTime_clear()
static UA_INLINE void UA_UtcTime_clear (UA_UtcTime * p) static
Definition at line 1142 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_UtcTime_copy()
static UA_INLINE UA_StatusCode UA_UtcTime_copy (const UA_UtcTime * src, UA_UtcTime * dst) static
Definition at line 1132 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_UtcTime_delete()
static UA_INLINE void UA_UtcTime_delete (UA_UtcTime * p) static
Definition at line 1147 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_UtcTime_deleteMembers()
static UA_INLINE void UA_UtcTime_deleteMembers (UA_UtcTime * p) static
Definition at line 1137 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_UtcTime_init()
static UA_INLINE void UA_UtcTime_init (UA_UtcTime * p) static
Definition at line 1122 of file libs/include/open62541/types_generated_handling.h.
UA_UtcTime_new()
static UA_INLINE UA_UtcTime* UA_UtcTime_new (void) static
Definition at line 1127 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_VariableAttributes_clear()
static UA_INLINE void UA_VariableAttributes_clear (UA_VariableAttributes * p) static
Definition at line 892 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_VariableAttributes_copy()
static UA_INLINE UA_StatusCode UA_VariableAttributes_copy (const UA_VariableAttributes * src, UA_VariableAttributes * dst) static
Definition at line 882 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_VariableAttributes_delete()
static UA_INLINE void UA_VariableAttributes_delete (UA_VariableAttributes * p) static
Definition at line 897 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_VariableAttributes_deleteMembers()
static UA_INLINE void UA_VariableAttributes_deleteMembers (UA_VariableAttributes * p) static
Definition at line 887 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_VariableAttributes_init()
static UA_INLINE void UA_VariableAttributes_init (UA_VariableAttributes * p) static
Definition at line 872 of file libs/include/open62541/types_generated_handling.h.
UA_VariableAttributes_new()
static UA_INLINE UA_VariableAttributes* UA_VariableAttributes_new (void) static
Definition at line 877 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_VariableTypeAttributes_clear()
static UA_INLINE void UA_VariableTypeAttributes_clear (UA_VariableTypeAttributes * p) static
Definition at line 1421 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_VariableTypeAttributes_copy()
static UA_INLINE UA_StatusCode UA_VariableTypeAttributes_copy (const UA_VariableTypeAttributes * src, UA_VariableTypeAttributes * dst) static
Definition at line 1411 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_VariableTypeAttributes_delete()
static UA_INLINE void UA_VariableTypeAttributes_delete (UA_VariableTypeAttributes * p) static
Definition at line 1426 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_VariableTypeAttributes_deleteMembers()
static UA_INLINE void UA_VariableTypeAttributes_deleteMembers (UA_VariableTypeAttributes * p) static
Definition at line 1416 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_VariableTypeAttributes_init()
static UA_INLINE void UA_VariableTypeAttributes_init (UA_VariableTypeAttributes * p) static
Definition at line 1401 of file libs/include/open62541/types_generated_handling.h.
UA_VariableTypeAttributes_new()
static UA_INLINE UA_VariableTypeAttributes* UA_VariableTypeAttributes_new (void) static
Definition at line 1406 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_Variant_clear()
static UA_INLINE void UA_Variant_clear (UA_Variant * p) static
Definition at line 767 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_Variant_copy()
static UA_INLINE UA_StatusCode UA_Variant_copy (const UA_Variant * src, UA_Variant * dst) static
Definition at line 757 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_Variant_delete()
static UA_INLINE void UA_Variant_delete (UA_Variant * p) static
Definition at line 772 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_Variant_deleteMembers()
static UA_INLINE void UA_Variant_deleteMembers (UA_Variant * p) static
Definition at line 762 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_Variant_init()
static UA_INLINE void UA_Variant_init (UA_Variant * p) static
Definition at line 747 of file libs/include/open62541/types_generated_handling.h.
UA_Variant_new()
static UA_INLINE UA_Variant* UA_Variant_new (void) static
Definition at line 752 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_ViewAttributes_clear()
static UA_INLINE void UA_ViewAttributes_clear (UA_ViewAttributes * p) static
Definition at line 829 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_ViewAttributes_copy()
static UA_INLINE UA_StatusCode UA_ViewAttributes_copy (const UA_ViewAttributes * src, UA_ViewAttributes * dst) static
Definition at line 819 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_ViewAttributes_delete()
static UA_INLINE void UA_ViewAttributes_delete (UA_ViewAttributes * p) static
Definition at line 834 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_ViewAttributes_deleteMembers()
static UA_INLINE void UA_ViewAttributes_deleteMembers (UA_ViewAttributes * p) static
Definition at line 824 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_ViewAttributes_init()
static UA_INLINE void UA_ViewAttributes_init (UA_ViewAttributes * p) static
Definition at line 809 of file libs/include/open62541/types_generated_handling.h.
UA_ViewAttributes_new()
static UA_INLINE UA_ViewAttributes* UA_ViewAttributes_new (void) static
Definition at line 814 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_ViewDescription_clear()
static UA_INLINE void UA_ViewDescription_clear (UA_ViewDescription * p) static
Definition at line 3481 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_ViewDescription_copy()
static UA_INLINE UA_StatusCode UA_ViewDescription_copy (const UA_ViewDescription * src, UA_ViewDescription * dst) static
Definition at line 3471 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_ViewDescription_delete()
static UA_INLINE void UA_ViewDescription_delete (UA_ViewDescription * p) static
Definition at line 3486 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_ViewDescription_deleteMembers()
static UA_INLINE void UA_ViewDescription_deleteMembers (UA_ViewDescription * p) static
Definition at line 3476 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_ViewDescription_init()
static UA_INLINE void UA_ViewDescription_init (UA_ViewDescription * p) static
Definition at line 3461 of file libs/include/open62541/types_generated_handling.h.
UA_ViewDescription_new()
static UA_INLINE UA_ViewDescription* UA_ViewDescription_new (void) static
Definition at line 3466 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_WriteRequest_clear()
static UA_INLINE void UA_WriteRequest_clear (UA_WriteRequest * p) static
Definition at line 5285 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_WriteRequest_copy()
static UA_INLINE UA_StatusCode UA_WriteRequest_copy (const UA_WriteRequest * src, UA_WriteRequest * dst) static
Definition at line 5275 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_WriteRequest_delete()
static UA_INLINE void UA_WriteRequest_delete (UA_WriteRequest * p) static
Definition at line 5290 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_WriteRequest_deleteMembers()
static UA_INLINE void UA_WriteRequest_deleteMembers (UA_WriteRequest * p) static
Definition at line 5280 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_WriteRequest_init()
static UA_INLINE void UA_WriteRequest_init (UA_WriteRequest * p) static
Definition at line 5265 of file libs/include/open62541/types_generated_handling.h.
UA_WriteRequest_new()
static UA_INLINE UA_WriteRequest* UA_WriteRequest_new (void) static
Definition at line 5270 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_WriteResponse_clear()
static UA_INLINE void UA_WriteResponse_clear (UA_WriteResponse * p) static
Definition at line 2359 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_WriteResponse_copy()
static UA_INLINE UA_StatusCode UA_WriteResponse_copy (const UA_WriteResponse * src, UA_WriteResponse * dst) static
Definition at line 2349 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_WriteResponse_delete()
static UA_INLINE void UA_WriteResponse_delete (UA_WriteResponse * p) static
Definition at line 2364 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_WriteResponse_deleteMembers()
static UA_INLINE void UA_WriteResponse_deleteMembers (UA_WriteResponse * p) static
Definition at line 2354 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_WriteResponse_init()
static UA_INLINE void UA_WriteResponse_init (UA_WriteResponse * p) static
Definition at line 2339 of file libs/include/open62541/types_generated_handling.h.
UA_WriteResponse_new()
static UA_INLINE UA_WriteResponse* UA_WriteResponse_new (void) static
Definition at line 2344 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_WriteValue_clear()
static UA_INLINE void UA_WriteValue_clear (UA_WriteValue * p) static
Definition at line 2670 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_WriteValue_copy()
static UA_INLINE UA_StatusCode UA_WriteValue_copy (const UA_WriteValue * src, UA_WriteValue * dst) static
Definition at line 2660 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_WriteValue_delete()
static UA_INLINE void UA_WriteValue_delete (UA_WriteValue * p) static
Definition at line 2675 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_WriteValue_deleteMembers()
static UA_INLINE void UA_WriteValue_deleteMembers (UA_WriteValue * p) static
Definition at line 2665 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_WriteValue_init()
static UA_INLINE void UA_WriteValue_init (UA_WriteValue * p) static
Definition at line 2650 of file libs/include/open62541/types_generated_handling.h.
UA_WriteValue_new()
static UA_INLINE UA_WriteValue* UA_WriteValue_new (void) static
Definition at line 2655 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_X509IdentityToken_clear()
static UA_INLINE void UA_X509IdentityToken_clear (UA_X509IdentityToken * p) static
Definition at line 1204 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_X509IdentityToken_copy()
static UA_INLINE UA_StatusCode UA_X509IdentityToken_copy (const UA_X509IdentityToken * src, UA_X509IdentityToken * dst) static
Definition at line 1194 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_X509IdentityToken_delete()
static UA_INLINE void UA_X509IdentityToken_delete (UA_X509IdentityToken * p) static
Definition at line 1209 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_X509IdentityToken_deleteMembers()
static UA_INLINE void UA_X509IdentityToken_deleteMembers (UA_X509IdentityToken * p) static
Definition at line 1199 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_X509IdentityToken_init()
static UA_INLINE void UA_X509IdentityToken_init (UA_X509IdentityToken * p) static
Definition at line 1184 of file libs/include/open62541/types_generated_handling.h.
UA_X509IdentityToken_new()
static UA_INLINE UA_X509IdentityToken* UA_X509IdentityToken_new (void) static
Definition at line 1189 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.
UA_XmlElement_clear()
static UA_INLINE void UA_XmlElement_clear (UA_XmlElement * p) static
Definition at line 518 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_XmlElement_copy()
static UA_INLINE UA_StatusCode UA_XmlElement_copy (const UA_XmlElement * src, UA_XmlElement * dst) static
Definition at line 508 of file libs/include/open62541/types_generated_handling.h.
References UA_copy(), and UA_TYPES.
UA_XmlElement_delete()
static UA_INLINE void UA_XmlElement_delete (UA_XmlElement * p) static
Definition at line 523 of file libs/include/open62541/types_generated_handling.h.
References UA_delete(), and UA_TYPES.
UA_XmlElement_deleteMembers()
static UA_INLINE void UA_XmlElement_deleteMembers (UA_XmlElement * p) static
Definition at line 513 of file libs/include/open62541/types_generated_handling.h.
References UA_clear(), and UA_TYPES.
UA_XmlElement_init()
static UA_INLINE void UA_XmlElement_init (UA_XmlElement * p) static
Definition at line 498 of file libs/include/open62541/types_generated_handling.h.
UA_XmlElement_new()
static UA_INLINE UA_XmlElement* UA_XmlElement_new (void) static
Definition at line 503 of file libs/include/open62541/types_generated_handling.h.
References UA_new(), and UA_TYPES.