Project Template: Opc.Ua.ViewDescription Class Reference
Opc.Ua.ViewDescription Class Reference
Public Member Functions
ViewDescription ()
The default constructor.
virtual void Encode (IEncoder encoder)
virtual void Decode (IDecoder decoder)
virtual bool IsEqual (IEncodeable encodeable)
virtual object Clone ()
new object MemberwiseClone ()
Properties
NodeId ViewId [get, set]
DateTime Timestamp [get, set]
uint ViewVersion [get, set]
virtual ExpandedNodeId TypeId [get]
virtual ExpandedNodeId BinaryEncodingId [get]
virtual ExpandedNodeId XmlEncodingId [get]
Detailed Description
<exclude>
Definition at line 36634 of file Opc.Ua.DataTypes.cs.
Constructor & Destructor Documentation
ViewDescription()
Opc.Ua.ViewDescription.ViewDescription () inline
The default constructor.
Definition at line 36640 of file Opc.Ua.DataTypes.cs.
Member Function Documentation
Clone()
virtual object Opc.Ua.ViewDescription.Clone () inline virtual
Definition at line 36758 of file Opc.Ua.DataTypes.cs.
Referenced by Opc.Ua.BrowseRequest.MemberwiseClone(), and Opc.Ua.QueryFirstRequest.MemberwiseClone().
Decode()
virtual void Opc.Ua.ViewDescription.Decode (IDecoder decoder) inline virtual
Definition at line 36723 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd, and Opc.Ua.Timestamp.
Encode()
virtual void Opc.Ua.ViewDescription.Encode (IEncoder encoder) inline virtual
Definition at line 36711 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd, and Opc.Ua.Timestamp.
IsEqual()
virtual bool Opc.Ua.ViewDescription.IsEqual (IEncodeable encodeable) inline virtual
Definition at line 36735 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Object.
MemberwiseClone()
new object Opc.Ua.ViewDescription.MemberwiseClone () inline
Definition at line 36765 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.ViewDescription.MemberwiseClone(), Opc.Ua.NodeId, and Opc.Ua.Namespaces.OpcUaXsd.
Referenced by Opc.Ua.ViewDescription.MemberwiseClone().
Property Documentation
BinaryEncodingId
virtual ExpandedNodeId Opc.Ua.ViewDescription.BinaryEncodingId get
Definition at line 36700 of file Opc.Ua.DataTypes.cs.
Timestamp
DateTime Opc.Ua.ViewDescription.Timestamp get set
Definition at line 36677 of file Opc.Ua.DataTypes.cs.
TypeId
virtual ExpandedNodeId Opc.Ua.ViewDescription.TypeId get
Definition at line 36694 of file Opc.Ua.DataTypes.cs.
ViewId
NodeId Opc.Ua.ViewDescription.ViewId get set
Definition at line 36669 of file Opc.Ua.DataTypes.cs.
ViewVersion
uint Opc.Ua.ViewDescription.ViewVersion get set
Definition at line 36685 of file Opc.Ua.DataTypes.cs.
XmlEncodingId
virtual ExpandedNodeId Opc.Ua.ViewDescription.XmlEncodingId get
Definition at line 36706 of file Opc.Ua.DataTypes.cs.
The documentation for this class was generated from the following file:
Opc.Ua.DataTypes.cs