Project Template: Opc.Ua.EnumDescription Class Reference
Opc.Ua.EnumDescription Class Reference
Public Member Functions
EnumDescription ()
The default constructor.
override void Encode (IEncoder encoder)
override void Decode (IDecoder decoder)
override bool IsEqual (IEncodeable encodeable)
override object Clone ()
new object MemberwiseClone ()
Public Member Functions inherited from Opc.Ua.DataTypeDescription
DataTypeDescription ()
The default constructor.
new object MemberwiseClone ()
Properties
EnumDefinition EnumDefinition [get, set]
byte BuiltInType [get, set]
override ExpandedNodeId TypeId [get]
override ExpandedNodeId BinaryEncodingId [get]
override ExpandedNodeId XmlEncodingId [get]
Properties inherited from Opc.Ua.DataTypeDescription
NodeId DataTypeId [get, set]
QualifiedName Name [get, set]
virtual ExpandedNodeId TypeId [get]
virtual ExpandedNodeId BinaryEncodingId [get]
virtual ExpandedNodeId XmlEncodingId [get]
Detailed Description
<exclude>
Definition at line 4567 of file Opc.Ua.DataTypes.cs.
Constructor & Destructor Documentation
EnumDescription()
Opc.Ua.EnumDescription.EnumDescription () inline
The default constructor.
Definition at line 4573 of file Opc.Ua.DataTypes.cs.
Member Function Documentation
Clone()
override object Opc.Ua.EnumDescription.Clone () inline virtual
Reimplemented from Opc.Ua.DataTypeDescription.
Definition at line 4698 of file Opc.Ua.DataTypes.cs.
Decode()
override void Opc.Ua.EnumDescription.Decode (IDecoder decoder) inline virtual
Reimplemented from Opc.Ua.DataTypeDescription.
Definition at line 4662 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
Encode()
override void Opc.Ua.EnumDescription.Encode (IEncoder encoder) inline virtual
Reimplemented from Opc.Ua.DataTypeDescription.
Definition at line 4649 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
IsEqual()
override bool Opc.Ua.EnumDescription.IsEqual (IEncodeable encodeable) inline virtual
Reimplemented from Opc.Ua.DataTypeDescription.
Definition at line 4675 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Object.
MemberwiseClone()
new object Opc.Ua.EnumDescription.MemberwiseClone () inline
Definition at line 4705 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.EnumDefinition.Clone(), Opc.Ua.EnumDescription.MemberwiseClone(), and Opc.Ua.Namespaces.OpcUaXsd.
Referenced by Opc.Ua.EnumDescription.MemberwiseClone().
Property Documentation
BinaryEncodingId
override ExpandedNodeId Opc.Ua.EnumDescription.BinaryEncodingId get
Definition at line 4638 of file Opc.Ua.DataTypes.cs.
BuiltInType
byte Opc.Ua.EnumDescription.BuiltInType get set
Definition at line 4623 of file Opc.Ua.DataTypes.cs.
EnumDefinition
EnumDefinition Opc.Ua.EnumDescription.EnumDefinition get set
Definition at line 4603 of file Opc.Ua.DataTypes.cs.
TypeId
override ExpandedNodeId Opc.Ua.EnumDescription.TypeId get
Definition at line 4632 of file Opc.Ua.DataTypes.cs.
XmlEncodingId
override ExpandedNodeId Opc.Ua.EnumDescription.XmlEncodingId get
Definition at line 4644 of file Opc.Ua.DataTypes.cs.
The documentation for this class was generated from the following file:
Opc.Ua.DataTypes.cs