Project Template: nodeset_compiler.backend_graphviz Namespace Reference
nodeset_compiler.backend_graphviz Namespace Reference
Functions
def nodePrintDot (node)
def printDotGraphWalk (nodeset, depth=1, filename="out.dot", rootNode=None, followInverse=False, excludeNodeIds=[])
def getNodeString (node)
def getReferenceString (nodeset, ref)
def getNodeStyle (node)
def add_edges (graph, edges)
def add_nodes (graph, nodes)
def addReferenceToGraph (nodeset, nodeFrom, nodeTo, reference, graph)
def addNodeToGraph (nodeset, node, graph, alreadyAdded=set(), relevantReferences=set(), ignoreNodes=set(), isRoot=False, depth=0)
def generateGraphvizCode (nodeset, filename="dependencies", rootNode=None, excludeNodeIds=[])
Function Documentation
add_edges()
def nodeset_compiler.backend_graphviz.add_edges (graph, edges)
Definition at line 104 of file backend_graphviz.py.
Referenced by nodeset_compiler.backend_graphviz.addReferenceToGraph().
add_nodes()
def nodeset_compiler.backend_graphviz.add_nodes (graph, nodes)
Definition at line 112 of file backend_graphviz.py.
Referenced by nodeset_compiler.backend_graphviz.addNodeToGraph().
addNodeToGraph()
def nodeset_compiler.backend_graphviz.addNodeToGraph (nodeset, node, graph, alreadyAdded = set(), relevantReferences = set(), ignoreNodes = set(), isRoot = False, depth = 0)
Definition at line 124 of file backend_graphviz.py.
References nodeset_compiler.backend_graphviz.add_nodes(), nodeset_compiler.backend_graphviz.addReferenceToGraph(), nodeset_compiler.backend_graphviz.getNodeString(), and nodeset_compiler.backend_graphviz.getNodeStyle().
Referenced by nodeset_compiler.backend_graphviz.generateGraphvizCode().
addReferenceToGraph()
def nodeset_compiler.backend_graphviz.addReferenceToGraph (nodeset, nodeFrom, nodeTo, reference, graph)
Definition at line 120 of file backend_graphviz.py.
References nodeset_compiler.backend_graphviz.add_edges(), nodeset_compiler.backend_graphviz.getNodeString(), and nodeset_compiler.backend_graphviz.getReferenceString().
Referenced by nodeset_compiler.backend_graphviz.addNodeToGraph().
generateGraphvizCode()
def nodeset_compiler.backend_graphviz.generateGraphvizCode (nodeset, filename = "dependencies", rootNode = None, excludeNodeIds = [])
Definition at line 139 of file backend_graphviz.py.
References nodeset_compiler.backend_graphviz.addNodeToGraph().
getNodeString()
def nodeset_compiler.backend_graphviz.getNodeString (node)
Definition at line 79 of file backend_graphviz.py.
Referenced by nodeset_compiler.backend_graphviz.addNodeToGraph(), and nodeset_compiler.backend_graphviz.addReferenceToGraph().
getNodeStyle()
def nodeset_compiler.backend_graphviz.getNodeStyle (node)
Definition at line 86 of file backend_graphviz.py.
Referenced by nodeset_compiler.backend_graphviz.addNodeToGraph().
getReferenceString()
def nodeset_compiler.backend_graphviz.getReferenceString (nodeset, ref)
Definition at line 82 of file backend_graphviz.py.
Referenced by nodeset_compiler.backend_graphviz.addReferenceToGraph().
nodePrintDot()
def nodeset_compiler.backend_graphviz.nodePrintDot (node)
Definition at line 5 of file backend_graphviz.py.
References nodeset_compiler.backend_graphviz.printDotGraphWalk().
Referenced by nodeset_compiler.backend_graphviz.printDotGraphWalk().
printDotGraphWalk()
def nodeset_compiler.backend_graphviz.printDotGraphWalk (nodeset, depth = 1, filename = "out.dot", rootNode = None, followInverse = False, excludeNodeIds = [])
Outputs a graphiz/dot description the nodes centered around rootNode.
    References beginning from rootNode will be followed for depth steps. If
    "followInverse = True" is passed, then inverse (not Forward) references
    will also be followed.
    Nodes can be excluded from the graph by passing a list of NodeIds as
    string representation using excludeNodeIds (ex ["i=53", "ns=2;i=453"]).
    Output is written into filename to be parsed by dot/neato/srfp...
Definition at line 24 of file backend_graphviz.py.
References nodeset_compiler.backend_graphviz.nodePrintDot().
Referenced by nodeset_compiler.backend_graphviz.nodePrintDot().