Project Template: Opc.Ua.ThreeDFrame Class Reference
Opc.Ua.ThreeDFrame Class Reference
Public Member Functions
ThreeDFrame ()
The default constructor.
override void Encode (IEncoder encoder)
override void Decode (IDecoder decoder)
override bool IsEqual (IEncodeable encodeable)
override object Clone ()
new object MemberwiseClone ()
Public Member Functions inherited from Opc.Ua.Frame
Frame ()
The default constructor.
new object MemberwiseClone ()
Properties
ThreeDCartesianCoordinates CartesianCoordinates [get, set]
ThreeDOrientation Orientation [get, set]
override ExpandedNodeId TypeId [get]
override ExpandedNodeId BinaryEncodingId [get]
override ExpandedNodeId XmlEncodingId [get]
Properties inherited from Opc.Ua.Frame
virtual ExpandedNodeId TypeId [get]
virtual ExpandedNodeId BinaryEncodingId [get]
virtual ExpandedNodeId XmlEncodingId [get]
Detailed Description
<exclude>
Definition at line 2542 of file Opc.Ua.DataTypes.cs.
Constructor & Destructor Documentation
ThreeDFrame()
Opc.Ua.ThreeDFrame.ThreeDFrame () inline
The default constructor.
Definition at line 2548 of file Opc.Ua.DataTypes.cs.
Member Function Documentation
Clone()
override object Opc.Ua.ThreeDFrame.Clone () inline virtual
Reimplemented from Opc.Ua.Frame.
Definition at line 2687 of file Opc.Ua.DataTypes.cs.
Decode()
override void Opc.Ua.ThreeDFrame.Decode (IDecoder decoder) inline virtual
Reimplemented from Opc.Ua.Frame.
Definition at line 2651 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
Encode()
override void Opc.Ua.ThreeDFrame.Encode (IEncoder encoder) inline virtual
Reimplemented from Opc.Ua.Frame.
Definition at line 2638 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
IsEqual()
override bool Opc.Ua.ThreeDFrame.IsEqual (IEncodeable encodeable) inline virtual
Reimplemented from Opc.Ua.Frame.
Definition at line 2664 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Object.
MemberwiseClone()
new object Opc.Ua.ThreeDFrame.MemberwiseClone () inline
Definition at line 2694 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.ThreeDCartesianCoordinates.Clone(), Opc.Ua.ThreeDOrientation.Clone(), Opc.Ua.ThreeDFrame.MemberwiseClone(), and Opc.Ua.Namespaces.OpcUaXsd.
Referenced by Opc.Ua.ThreeDFrame.MemberwiseClone().
Property Documentation
BinaryEncodingId
override ExpandedNodeId Opc.Ua.ThreeDFrame.BinaryEncodingId get
Definition at line 2627 of file Opc.Ua.DataTypes.cs.
CartesianCoordinates
ThreeDCartesianCoordinates Opc.Ua.ThreeDFrame.CartesianCoordinates get set
Definition at line 2578 of file Opc.Ua.DataTypes.cs.
Orientation
ThreeDOrientation Opc.Ua.ThreeDFrame.Orientation get set
Definition at line 2600 of file Opc.Ua.DataTypes.cs.
TypeId
override ExpandedNodeId Opc.Ua.ThreeDFrame.TypeId get
Definition at line 2621 of file Opc.Ua.DataTypes.cs.
XmlEncodingId
override ExpandedNodeId Opc.Ua.ThreeDFrame.XmlEncodingId get
Definition at line 2633 of file Opc.Ua.DataTypes.cs.
The documentation for this class was generated from the following file:
Opc.Ua.DataTypes.cs