Project Template: Opc.Ua.HistoryModifiedData Class Reference
Opc.Ua.HistoryModifiedData Class Reference
Public Member Functions
HistoryModifiedData ()
The default constructor.
override void Encode (IEncoder encoder)
override void Decode (IDecoder decoder)
override bool IsEqual (IEncodeable encodeable)
override object Clone ()
new object MemberwiseClone ()
Public Member Functions inherited from Opc.Ua.HistoryData
HistoryData ()
The default constructor.
new object MemberwiseClone ()
Properties
ModificationInfoCollection ModificationInfos [get, set]
override ExpandedNodeId TypeId [get]
override ExpandedNodeId BinaryEncodingId [get]
override ExpandedNodeId XmlEncodingId [get]
Properties inherited from Opc.Ua.HistoryData
DataValueCollection DataValues [get, set]
virtual ExpandedNodeId TypeId [get]
virtual ExpandedNodeId BinaryEncodingId [get]
virtual ExpandedNodeId XmlEncodingId [get]
Detailed Description
<exclude>
Definition at line 47584 of file Opc.Ua.DataTypes.cs.
Constructor & Destructor Documentation
HistoryModifiedData()
Opc.Ua.HistoryModifiedData.HistoryModifiedData () inline
The default constructor.
Definition at line 47590 of file Opc.Ua.DataTypes.cs.
Member Function Documentation
Clone()
override object Opc.Ua.HistoryModifiedData.Clone () inline virtual
Reimplemented from Opc.Ua.HistoryData.
Definition at line 47703 of file Opc.Ua.DataTypes.cs.
Decode()
override void Opc.Ua.HistoryModifiedData.Decode (IDecoder decoder) inline virtual
Reimplemented from Opc.Ua.HistoryData.
Definition at line 47669 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
Encode()
override void Opc.Ua.HistoryModifiedData.Encode (IEncoder encoder) inline virtual
Reimplemented from Opc.Ua.HistoryData.
Definition at line 47657 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
IsEqual()
override bool Opc.Ua.HistoryModifiedData.IsEqual (IEncodeable encodeable) inline virtual
Reimplemented from Opc.Ua.HistoryData.
Definition at line 47681 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Object.
MemberwiseClone()
new object Opc.Ua.HistoryModifiedData.MemberwiseClone () inline
Definition at line 47710 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.ModificationInfoCollection.Clone(), Opc.Ua.HistoryModifiedData.MemberwiseClone(), and Opc.Ua.Namespaces.OpcUaXsd.
Referenced by Opc.Ua.HistoryModifiedData.MemberwiseClone().
Property Documentation
BinaryEncodingId
override ExpandedNodeId Opc.Ua.HistoryModifiedData.BinaryEncodingId get
Definition at line 47646 of file Opc.Ua.DataTypes.cs.
ModificationInfos
ModificationInfoCollection Opc.Ua.HistoryModifiedData.ModificationInfos get set
Definition at line 47619 of file Opc.Ua.DataTypes.cs.
TypeId
override ExpandedNodeId Opc.Ua.HistoryModifiedData.TypeId get
Definition at line 47640 of file Opc.Ua.DataTypes.cs.
XmlEncodingId
override ExpandedNodeId Opc.Ua.HistoryModifiedData.XmlEncodingId get
Definition at line 47652 of file Opc.Ua.DataTypes.cs.
The documentation for this class was generated from the following file:
Opc.Ua.DataTypes.cs