Project Template: Opc.Ua.PubSubConfigurationDataType Class Reference
Opc.Ua.PubSubConfigurationDataType Class Reference
Public Member Functions
PubSubConfigurationDataType ()
The default constructor.
virtual void Encode (IEncoder encoder)
virtual void Decode (IDecoder decoder)
virtual bool IsEqual (IEncodeable encodeable)
virtual object Clone ()
new object MemberwiseClone ()
Properties
PublishedDataSetDataTypeCollection PublishedDataSets [get, set]
PubSubConnectionDataTypeCollection Connections [get, set]
bool Enabled [get, set]
virtual ExpandedNodeId TypeId [get]
virtual ExpandedNodeId BinaryEncodingId [get]
virtual ExpandedNodeId XmlEncodingId [get]
Detailed Description
<exclude>
Definition at line 13376 of file Opc.Ua.DataTypes.cs.
Constructor & Destructor Documentation
PubSubConfigurationDataType()
Opc.Ua.PubSubConfigurationDataType.PubSubConfigurationDataType () inline
The default constructor.
Definition at line 13382 of file Opc.Ua.DataTypes.cs.
Member Function Documentation
Clone()
virtual object Opc.Ua.PubSubConfigurationDataType.Clone () inline virtual
Definition at line 13528 of file Opc.Ua.DataTypes.cs.
Decode()
virtual void Opc.Ua.PubSubConfigurationDataType.Decode (IDecoder decoder) inline virtual
Definition at line 13493 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
Encode()
virtual void Opc.Ua.PubSubConfigurationDataType.Encode (IEncoder encoder) inline virtual
Definition at line 13481 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
IsEqual()
virtual bool Opc.Ua.PubSubConfigurationDataType.IsEqual (IEncodeable encodeable) inline virtual
Definition at line 13505 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Object.
MemberwiseClone()
new object Opc.Ua.PubSubConfigurationDataType.MemberwiseClone () inline
Definition at line 13535 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.PublishedDataSetDataTypeCollection.Clone(), Opc.Ua.PubSubConnectionDataTypeCollection.Clone(), Opc.Ua.PubSubConfigurationDataType.MemberwiseClone(), and Opc.Ua.Namespaces.OpcUaXsd.
Referenced by Opc.Ua.PubSubConfigurationDataType.MemberwiseClone().
Property Documentation
BinaryEncodingId
virtual ExpandedNodeId Opc.Ua.PubSubConfigurationDataType.BinaryEncodingId get
Definition at line 13470 of file Opc.Ua.DataTypes.cs.
Connections
PubSubConnectionDataTypeCollection Opc.Ua.PubSubConfigurationDataType.Connections get set
Definition at line 13435 of file Opc.Ua.DataTypes.cs.
Enabled
bool Opc.Ua.PubSubConfigurationDataType.Enabled get set
Definition at line 13455 of file Opc.Ua.DataTypes.cs.
PublishedDataSets
PublishedDataSetDataTypeCollection Opc.Ua.PubSubConfigurationDataType.PublishedDataSets get set
Definition at line 13413 of file Opc.Ua.DataTypes.cs.
TypeId
virtual ExpandedNodeId Opc.Ua.PubSubConfigurationDataType.TypeId get
Definition at line 13464 of file Opc.Ua.DataTypes.cs.
XmlEncodingId
virtual ExpandedNodeId Opc.Ua.PubSubConfigurationDataType.XmlEncodingId get
Definition at line 13476 of file Opc.Ua.DataTypes.cs.
The documentation for this class was generated from the following file:
Opc.Ua.DataTypes.cs