Project Template: Opc.Ua.CallRequest Class Reference
Opc.Ua.CallRequest Class Reference
Public Member Functions
CallRequest ()
The default constructor.
virtual void Encode (IEncoder encoder)
virtual void Decode (IDecoder decoder)
virtual bool IsEqual (IEncodeable encodeable)
virtual object Clone ()
new object MemberwiseClone ()
Properties
RequestHeader RequestHeader [get, set]
CallMethodRequestCollection MethodsToCall [get, set]
virtual ExpandedNodeId TypeId [get]
virtual ExpandedNodeId BinaryEncodingId [get]
virtual ExpandedNodeId XmlEncodingId [get]
Detailed Description
<exclude>
Definition at line 2822 of file Opc.Ua.Messages.cs.
Constructor & Destructor Documentation
CallRequest()
Opc.Ua.CallRequest.CallRequest () inline
The default constructor.
Definition at line 51329 of file Opc.Ua.DataTypes.cs.
Member Function Documentation
Clone()
virtual object Opc.Ua.CallRequest.Clone () inline virtual
Definition at line 51463 of file Opc.Ua.DataTypes.cs.
Decode()
virtual void Opc.Ua.CallRequest.Decode (IDecoder decoder) inline virtual
Definition at line 51430 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
Encode()
virtual void Opc.Ua.CallRequest.Encode (IEncoder encoder) inline virtual
Definition at line 51419 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Namespaces.OpcUaXsd.
IsEqual()
virtual bool Opc.Ua.CallRequest.IsEqual (IEncodeable encodeable) inline virtual
Definition at line 51441 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.Object.
MemberwiseClone()
new object Opc.Ua.CallRequest.MemberwiseClone () inline
Definition at line 51470 of file Opc.Ua.DataTypes.cs.
References Opc.Ua.RequestHeader.Clone(), Opc.Ua.CallMethodRequestCollection.Clone(), Opc.Ua.CallRequest.MemberwiseClone(), and Opc.Ua.Namespaces.OpcUaXsd.
Referenced by Opc.Ua.CallRequest.MemberwiseClone().
Property Documentation
BinaryEncodingId
virtual ExpandedNodeId Opc.Ua.CallRequest.BinaryEncodingId get
Definition at line 51408 of file Opc.Ua.DataTypes.cs.
MethodsToCall
CallMethodRequestCollection Opc.Ua.CallRequest.MethodsToCall get set
Definition at line 51381 of file Opc.Ua.DataTypes.cs.
Referenced by Opc.Ua.SessionClient.BeginCall(), Opc.Ua.SessionEndpoint.EndHistoryUpdate(), and Opc.Ua.SessionClient.EndHistoryUpdate().
RequestHeader
RequestHeader Opc.Ua.CallRequest.RequestHeader get set
Definition at line 51359 of file Opc.Ua.DataTypes.cs.
Referenced by Opc.Ua.SessionClient.BeginCall(), Opc.Ua.SessionEndpoint.EndHistoryUpdate(), and Opc.Ua.SessionClient.EndHistoryUpdate().
TypeId
virtual ExpandedNodeId Opc.Ua.CallRequest.TypeId get
Definition at line 51402 of file Opc.Ua.DataTypes.cs.
XmlEncodingId
virtual ExpandedNodeId Opc.Ua.CallRequest.XmlEncodingId get
Definition at line 51414 of file Opc.Ua.DataTypes.cs.
The documentation for this class was generated from the following files:
Opc.Ua.Messages.cs
Opc.Ua.DataTypes.cs